# ***Assignment 2:*** Paper Reproduction

## **Members:** *Muhammad Huzaifa Khalid (23i2508), Waqas Ahmed (23i-2540), Abubakar Imran (23i-2589)*

## **Paper:** *"Enhanced credit risk prediction using deep learning and SMOTE-ENN resampling"* by Idowu Aruleba and Yanxia Sun.*

## **Objective:**
This notebook implements a controlled, end-to-end reproduction of the core claims of the selected research paper. Our implementation rigorously tests three models: **MLP, LSTM, and GRU** across both the **German and Australian** credit risk datasets, under two major experimental conditions: **Baseline (no resampling)** and **SMOTE-ENN resampling**.

## **Reproducibility Analysis & Core Scope:**
This notebook serves as both an implementation and a reproducibility audit. Important discrepancies found during our reproduction attempt—such as contradictions in the original paper's datasets descriptions and omitted structural variables—are safely accommodated and carefully documented. Models that were under-specified in the original text (such as CNN/GNN architectures lacking spatial or arbitrary structural definitions) are excluded in favor of rigorously defined temporal and fully connected states.

---

***This Block Is Exclusivly For Testing***

TESTING MODE = Set to True for quick validation, False for full reproduction

In [1]:
TESTING_MODE = False

# Global flags
if TESTING_MODE:
    NUM_EPOCHS = 20  # Test with 20 epochs
    print("TESTING MODE ACTIVE: Using 20 epochs instead of 100")
else:
    NUM_EPOCHS = 100  # Full reproduction
    print("FULL MODE: Using 100 epochs as per paper")

FULL MODE: Using 100 epochs as per paper

## ***Environment, Hardware, and Imports Setup***
***Purpose:*** Ensure all standard scientific computing and deep learning dependencies are fully available, imported safely, and configure optimal runtime hardware parameters.

***Hardware Scaling Strategy:*** 
The notebook script relies heavily on `torch.cuda`. It operates dynamically across local topologies or cloud (e.g., Kaggle free-tier `T4 x2`). Data parallelism is enforced strictly when `torch.cuda.device_count() > 1`. Mixed precision acceleration (`torch.cuda.amp.autocast`) minimizes VRAM consumption and accelerates throughput smoothly.

***Mixed Precision Training:***
We are using PyTorch's Automatic Mixed Precision (AMP) to:
- Reduce VRAM consumption efficiently.
- Accelerate training significantly on capable GPUs.
- Maintain numerical stability for credit risk prediction constraints.

***Reproducibility Note:*** AMP may introduce minor (<0.1%) numerical variations across different GPU architectures due to different hardware FP16 implementations.

***Importing All The Necessary Libraries***

In [2]:
import os
import sys
import random
import logging
import time
import datetime
import warnings
import platform
import gc
import copy
from pathlib import Path
import json
import shutil

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from tqdm.auto import tqdm

import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import DataLoader, TensorDataset, random_split

import sklearn
from sklearn.preprocessing import StandardScaler, OrdinalEncoder
from sklearn.compose import ColumnTransformer
from sklearn.impute import SimpleImputer
from sklearn.pipeline import Pipeline
from sklearn.model_selection import StratifiedKFold
from sklearn.metrics import accuracy_score, confusion_matrix, recall_score

import imblearn
from imblearn.combine import SMOTEENN

import shap

In [3]:
warnings.filterwarnings('ignore')

***Directory Scaffold***

In [4]:
dirs_required = [
    'results/logs',
    'results/metrics',
    'results/histories',
    'results/tables',
    'results/plots',
    'results/shap'
]
for d in dirs_required:
    os.makedirs(d, exist_ok=True)

***Centralized Logging***

In [5]:
logging.basicConfig(
    level=logging.INFO,
    format='%(asctime)s - %(levelname)s - %(message)s',
    handlers=[logging.StreamHandler(), logging.FileHandler('results/logs/master_execution.log')]
)
logger = logging.getLogger('ReproducibilityLog')

***Dynamic Node Extraction***

In [6]:
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
device_count = torch.cuda.device_count()

num_workers = 2 if torch.cuda.is_available() else 0
pin_memory = True if torch.cuda.is_available() else False

logger.info(f"Target Device: {device} | Discovered GPUs: {device_count}")

2026-04-05 05:15:19,945 - INFO - Target Device: cuda | Discovered GPUs: 2

## ***Environment Print & Hardware Registration***
***Purpose:*** Produce an explicit log registering local runtime context variables requested within the formal reproducibility constraints (Python versions, PyTorch variants, OS).

In [7]:
def PrintEnvironmentSummary():
    env_info = {
        "Python": sys.version,
        "System": platform.platform(),
        "PyTorch": torch.__version__,
        "NumPy": np.__version__,
        "Pandas": pd.__version__,
        "Scikit-Learn": sklearn.__version__,
        "Imbalanced-Learn": imblearn.__version__,
        "SHAP": shap.__version__,
        "CUDA Available": torch.cuda.is_available(),
        "GPU Count": device_count,
        "GPU Name(s)": [torch.cuda.get_device_name(i) for i in range(device_count)] if device_count > 0 else ["N/A"]
    }
    
    logger.info("=== Environment Hardware & Package Summary ===")
    with open("results/logs/environment_summary.json", "w") as f:
        import json
        json.dump(env_info, f, indent=4)
        
    for k, v in env_info.items():
        print(f"{k}: {v}")
        
PrintEnvironmentSummary()

2026-04-05 05:15:19,970 - INFO - === Environment Hardware & Package Summary ===

Python: 3.12.12 (main, Oct 10 2025, 08:52:57) [GCC 11.4.0]
System: Linux-6.6.113+-x86_64-with-glibc2.35
PyTorch: 2.10.0+cu128
NumPy: 2.0.2
Pandas: 2.3.3
Scikit-Learn: 1.6.1
Imbalanced-Learn: 0.14.1
SHAP: 0.50.0
CUDA Available: True
GPU Count: 2
GPU Name(s): ['Tesla T4', 'Tesla T4']

## ***Reproducibility Bounds & Seed Control***
***Purpose:*** Hard-lock environments globally.

In [8]:
def SetSeed(seed_value=42):
    random.seed(seed_value)
    np.random.seed(seed_value)
    os.environ['PYTHONHASHSEED'] = str(seed_value)
    torch.manual_seed(seed_value)
    torch.cuda.manual_seed(seed_value)
    torch.cuda.manual_seed_all(seed_value)
    torch.backends.cudnn.deterministic = True
    torch.backends.cudnn.benchmark = False
    logger.info(f"RNG components uniformly saturated against fixed seed: {seed_value}")

SetSeed(42)

2026-04-05 05:15:19,994 - INFO - RNG components uniformly saturated against fixed seed: 42

## ***Dataset Validation and Extract Sequences***
***Purpose:*** This code will actively assert path configurations ensuring nodes fall back gracefully or explicitly declare boundaries when running Kaggle native configurations vs Local extraction protocols.

***Dataset Path Validation***

In [9]:
german_path_kaggle = "/kaggle/input/datasets/huzaifakhalid7/dataset/australian.dat"
australian_path_kaggle = "/kaggle/input/datasets/huzaifakhalid7/dataset/australian.dat"

In [10]:
german_target_path = german_path_kaggle if os.path.exists(german_path_kaggle) else 'dataset/german.data-numeric'
if not os.path.exists(german_target_path):
    german_target_path = '../dataset/german.data-numeric'

australian_target_path = australian_path_kaggle if os.path.exists(australian_path_kaggle) else 'dataset/australian.dat'
if not os.path.exists(australian_target_path):
    australian_target_path = '../dataset/australian.dat'

logger.info("=== Dataset Validation ===")
# Check German dataset
if not os.path.exists(german_target_path):
    error_msg = f"German dataset not found at {german_target_path}"
    logger.error(error_msg)
    logger.error("Please verify Kaggle dataset is properly attached or localized:")
    raise FileNotFoundError(error_msg)
else:
    logger.info(f"✓ German dataset found: {german_target_path}")

# Check Australian dataset
if not os.path.exists(australian_target_path):
    error_msg = f"Australian dataset not found at {australian_target_path}"
    logger.error(error_msg)
    raise FileNotFoundError(error_msg)
else:
    logger.info(f"✓ Australian dataset found: {australian_target_path}")
logger.info("All datasets validated successfully")

def LoadGermanDataset(filepath=german_target_path):
    german_frame = pd.read_csv(filepath, sep=r'\s+', header=None)
    return german_frame

def LoadAustralianDataset(filepath=australian_target_path):
    australian_frame = pd.read_csv(filepath, sep=r'\s+', header=None, na_values=['?'])
    return australian_frame

df_german = LoadGermanDataset()
df_australian = LoadAustralianDataset()

2026-04-05 05:15:20,017 - INFO - === Dataset Validation ===
2026-04-05 05:15:20,018 - INFO - ✓ German dataset found: /kaggle/input/datasets/huzaifakhalid7/dataset/australian.dat
2026-04-05 05:15:20,019 - INFO - ✓ Australian dataset found: /kaggle/input/datasets/huzaifakhalid7/dataset/australian.dat
2026-04-05 05:15:20,019 - INFO - All datasets validated successfully

## ***Subsets Assessment & Initial Dimensional Integrity Validate***
***Purpose:*** Display local layout parameters explicitly referencing target configurations.

***German Dataset Paramters***

In [11]:
print("----- German Dataset Parameters -----")
print(f"Dimension Layout (Rows x Cols): {df_german.shape}")
print(f"Distribution Vector (Col 24): {df_german.iloc[:, -1].value_counts().to_dict()}")
print(f"Aggregated Missing Anomalies: {df_german.isna().sum().sum()}")
display(df_german.head(2))

----- German Dataset Parameters -----
Dimension Layout (Rows x Cols): (690, 15)
Distribution Vector (Col 24): {0: 383, 1: 307}
Aggregated Missing Anomalies: 0

   0      1      2   3   4   5      6   7   8   9   10  11   12    13  14
0   1  22.08  11.46   2   4   4  1.585   0   0   0   1   2  100  1213   0
1   0  22.67   7.00   2   8   4  0.165   0   0   0   0   2  160     1   0

***Australian Dataset Parameters***

In [12]:
print("\n----- Australian Dataset Parameters -----")
print(f"Dimension Layout (Rows x Cols): {df_australian.shape}")
print(f"Distribution Vector (Col 14): {df_australian.iloc[:, -1].value_counts().to_dict()}")
print(f"Aggregated Missing Anomalies: {df_australian.isna().sum().sum()}")
display(df_australian.head(2))

----- Australian Dataset Parameters -----
Dimension Layout (Rows x Cols): (690, 15)
Distribution Vector (Col 14): {0: 383, 1: 307}
Aggregated Missing Anomalies: 0

   0      1      2   3   4   5      6   7   8   9   10  11   12    13  14
0   1  22.08  11.46   2   4   4  1.585   0   0   0   1   2  100  1213   0
1   0  22.67   7.00   2   8   4  0.165   0   0   0   0   2  160     1   0

## ***Preprocessing Formulations & Safe-Fold Transformations***

### ***Australian Dataset Preprocessing Details***

**Categorical Column Resolution:**
The paper's Table 1 lists Australian dataset features but contains semantic inconsistencies with the official UCI repository documentation. We resolve this as follows:

***Official UCI Specification:***
- Categorical columns (indices): [0, 3, 4, 5, 8, 9, 11]
- Continuous columns (indices): [1, 2, 6, 7, 10, 12, 13]

***Implementation Decision:***
We use the ***official UCI specification*** rather than the paper's description because:
1. UCI repository is the authoritative source
2. Paper's Table 1 appears to conflate German and Australian features
3. Using official spec ensures reproducibility for future researchers

***Preprocessing Pipeline:***
1. ***Categorical features (indices 0, 3, 4, 5, 8, 9, 11):***
   - Imputation: Mode (most frequent value)
   - Encoding: OrdinalEncoder (integer mapping)
2. ***Continuous features (indices 1, 2, 6, 7, 10, 12, 13):***
   - Imputation: Mean
   - Scaling: StandardScaler (zero mean, unit variance)
3. ***Missing value handling:***
   - Strategy: Impute cleanly before scaling/encoding inside the active fold.

***Reproducibility Note:*** This discrepancy between paper description and official dataset limits is documented formally as a reproducibility challenge.

***Function To Process German Dataset***

In [13]:
def PreprocessGermanFold(x_train, x_val):
    scaler = StandardScaler()
    x_train_scaled = scaler.fit_transform(x_train)
    x_val_scaled = scaler.transform(x_val)
    return x_train_scaled, x_val_scaled

***Function To Process Australian Dataset***

In [14]:
def PreprocessAustralianFold(x_train, x_val):
    categorical_cols = [0, 3, 4, 5, 8, 9, 11]
    numerical_cols = [1, 2, 6, 7, 10, 12, 13]
    
    categorical_cols = [col for col in categorical_cols if col < x_train.shape[1]]
    numerical_cols = [col for col in numerical_cols if col < x_train.shape[1]]

    num_pipeline = Pipeline([
        ('imputer', SimpleImputer(strategy='mean')),
        ('scaler', StandardScaler())
    ])
    
    cat_pipeline = Pipeline([
        ('imputer', SimpleImputer(strategy='most_frequent')),
        ('encoder', OrdinalEncoder(handle_unknown='use_encoded_value', unknown_value=-1)),
        ('scaler', StandardScaler()) 
    ])

    preprocessor = ColumnTransformer([
        ('num', num_pipeline, numerical_cols),
        ('cat', cat_pipeline, categorical_cols)
    ])
    
    x_train_processed = preprocessor.fit_transform(x_train)
    x_val_processed = preprocessor.transform(x_val)
    
    return x_train_processed, x_val_processed

## ***Metrics Derivations***
***Rationale:*** Standard computational bounds collapse to `0` / `1` targets tracking strict Specificity formulas.

In [15]:
def MapGermanLabels(y_vector):
    return np.where(y_vector == 1, 0, 1)

def MapAustralianLabels(y_vector):
    if isinstance(y_vector, pd.Series):
        return y_vector.values
    return y_vector

def ComputeMetrics(y_true, y_pred):
    accuracy = accuracy_score(y_true, y_pred)
    sensitivity = recall_score(y_true, y_pred, zero_division=0)
    
    conf_matrix = confusion_matrix(y_true, y_pred)
    if conf_matrix.shape == (2, 2):
        tn, fp, fn, tp = conf_matrix.ravel()
        specificity = tn / (tn + fp) if (tn + fp) > 0 else 0.0
    else:
        specificity = 0.0 if len(np.unique(y_true)) > 1 else 1.0
        
    return {
        'accuracy': accuracy, 
        'sensitivity': sensitivity, 
        'specificity': specificity
    }

## ***SMOTE-ENN Resampling Constraints***

In [16]:
def ApplySmoteEnn(x_train, y_train):
    from imblearn.over_sampling import SMOTE
    from imblearn.under_sampling import EditedNearestNeighbours
    # 'auto' safely handles near-balanced datasets like Australian without crashing
    smote = SMOTE(sampling_strategy='auto', random_state=42)
    # Soften ENN to retain hard negatives by using 'mode' instead of unanimous voting
    enn = EditedNearestNeighbours(n_neighbors=5, kind_sel='mode')
    smote_enn_engine = SMOTEENN(smote=smote, enn=enn, random_state=42)
    x_resampled, y_resampled = smote_enn_engine.fit_resample(x_train, y_train)
    return x_resampled, y_resampled

## ***Tensor Converters***

In [17]:
def BuildTensorDatasets(x_array, y_array):
    tensor_x = torch.tensor(x_array, dtype=torch.float32)
    tensor_y = torch.tensor(y_array, dtype=torch.float32).unsqueeze(1) 
    return TensorDataset(tensor_x, tensor_y)

def BuildDataLoaders(train_dataset, val_dataset, load_batch_size):
    loader_train = DataLoader(
        train_dataset, batch_size=load_batch_size, shuffle=True, 
        num_workers=num_workers, pin_memory=pin_memory
    )
    loader_val = DataLoader(
        val_dataset, batch_size=load_batch_size, shuffle=False, 
        num_workers=num_workers, pin_memory=pin_memory
    )
    return loader_train, loader_val

## ***Hyperparameter Configuration Table & Model Tracking Modules***

Our implementation strictly applies the optimal ranges designated directly by the paper's original definitions.

| Hyperparameter | MLP | LSTM | GRU | Source |
|----------------|-----|------|-----|--------|
| **Learning Rate** | 0.001 | 0.001 | 0.001 | Paper Table 3 |
| **Batch Size** | 32 | 64 | 64 | Paper Table 3 |
| **Hidden Units** | 128 | 256 | 256 | Paper Table 3 |
| **Dropout Rate** | 0.3 | 0.3 | 0.3 | Paper Table 3 |
| **Optimizer** | Adam | RMSprop | Adam | Paper Table 3 |
| **Epochs** | 100 | 100 | 100 | Paper Table 3 |
| **Weight Decay** | 0.0 | 0.0 | 0.0 | Default (not formally specified) |
| **Loss Function** | BCEWithLogitsLoss | BCEWithLogitsLoss | BCEWithLogitsLoss | Formal metric |

***Sequence Shaping Framework (LSTM/GRU):***
- Input Shape Requirement: `(batch_size, sequence_length=1, num_features)`
- Rationale: Tabular arrays cross-sections fundamentally omit embedded sequential attributes natively. A temporal vector space mapped cleanly to local depth representations represents the highest standard format.

In [18]:
class BuildMlpModel(nn.Module):
    def __init__(self, in_features_dim):
        super().__init__()
        self.dense_network = nn.Sequential(
            nn.Linear(in_features_dim, 128),
            nn.ReLU(),
            nn.Dropout(0.3),
            nn.Linear(128, 128),
            nn.ReLU(),
            nn.Dropout(0.3),
            nn.Linear(128, 1)
        )
    def forward(self, input_tensor):
        return self.dense_network(input_tensor)

class BuildLstmModel(nn.Module):
    def __init__(self, in_features_dim):
        super().__init__()
        self.lstm_layer = nn.LSTM(input_size=in_features_dim, hidden_size=256, batch_first=True)
        self.dropout_layer = nn.Dropout(0.3)
        self.output_dense = nn.Linear(256, 1)
    def forward(self, input_tensor):
        series_stack = input_tensor.unsqueeze(1) 
        output_states, (hidden, cell) = self.lstm_layer(series_stack)
        dropped_out = self.dropout_layer(output_states[:, -1, :]) 
        return self.output_dense(dropped_out)

class BuildGruModel(nn.Module):
    def __init__(self, in_features_dim):
        super().__init__()
        self.gru_layer = nn.GRU(input_size=in_features_dim, hidden_size=256, batch_first=True)
        self.dropout_layer = nn.Dropout(0.3)
        self.output_dense = nn.Linear(256, 1)
    def forward(self, input_tensor):
        series_stack = input_tensor.unsqueeze(1)
        output_states, hidden_state = self.gru_layer(series_stack)
        dropped_out = self.dropout_layer(output_states[:, -1, :])
        return self.output_dense(dropped_out)

def GetModelAndOptimizer(model_label, in_features_dim):
    if model_label == 'MLP':
        neural_model = BuildMlpModel(in_features_dim)
        adam_optimizer = optim.Adam(neural_model.parameters(), lr=0.001)
        batch_limit = 32
    elif model_label == 'LSTM':
        neural_model = BuildLstmModel(in_features_dim)
        adam_optimizer = optim.RMSprop(neural_model.parameters(), lr=0.001)
        batch_limit = 64
    elif model_label == 'GRU':
        neural_model = BuildGruModel(in_features_dim)
        adam_optimizer = optim.Adam(neural_model.parameters(), lr=0.001)
        batch_limit = 64
    else:
        raise ValueError("Critical: Unrecognized model variant.")
    
    if device_count > 1:
        neural_model = nn.DataParallel(neural_model)
    neural_model = neural_model.to(device)
    return neural_model, adam_optimizer, batch_limit

## ***Core Training Loop Execution Framework***

In [19]:
def TrainOneEpoch(neural_model, data_loader, loss_criterion, iteration_optimizer, gradient_scaler):
    neural_model.train()
    tracked_loss = 0.0
    for local_x, local_y in data_loader:
        local_x, local_y = local_x.to(device), local_y.to(device)
        
        iteration_optimizer.zero_grad()
        with torch.cuda.amp.autocast(enabled=device.type=='cuda'):
            raw_outputs = neural_model(local_x)
            gradient_loss = loss_criterion(raw_outputs, local_y)
            
        gradient_scaler.scale(gradient_loss).backward()
        gradient_scaler.step(iteration_optimizer)
        gradient_scaler.update()
        tracked_loss += gradient_loss.item() * local_x.size(0)
    return tracked_loss / len(data_loader.dataset)

def EvaluateOneEpoch(neural_model, data_loader, loss_criterion):
    neural_model.eval()
    tracked_loss = 0.0
    accumulated_preds = []
    accumulated_actuals = []
    with torch.no_grad():
        for local_x, local_y in data_loader:
            local_x, local_y = local_x.to(device), local_y.to(device)
            with torch.cuda.amp.autocast(enabled=device.type=='cuda'):
                raw_outputs = neural_model(local_x)
                gradient_loss = loss_criterion(raw_outputs, local_y)
            tracked_loss += gradient_loss.item() * local_x.size(0)
            
            sigmoids = torch.sigmoid(raw_outputs)
            thresholds = (sigmoids > 0.5).float()
            accumulated_preds.extend(thresholds.cpu().numpy())
            accumulated_actuals.extend(local_y.cpu().numpy())
            
    epoch_val_loss = tracked_loss / len(data_loader.dataset)
    computed_metrics = ComputeMetrics(np.array(accumulated_actuals), np.array(accumulated_preds))
    computed_metrics['loss'] = epoch_val_loss
    return computed_metrics

## ***Cross Validation Strategy, TQDM Embeddings, and Master Tracking Engine***
***Purpose***: Run dynamic constraints managing memory effectively per iteration bounds isolating memory artifacts across nodes efficiently deploying exact logging protocols universally.

In [20]:
def FitModel(neural_model, loader_train, loader_val, iteration_optimizer, fold_idx, dataset_name, model_name, logger_obj, num_epochs=100):
    loss_criterion = nn.BCEWithLogitsLoss()
    gradient_scaler = torch.cuda.amp.GradScaler(enabled=device.type=='cuda')
    
    history_tracker = {
        'train_losses': [], 'val_losses': [], 
        'val_accuracies': [], 'val_sensitivities': [], 'val_specificities': []
    }
    peak_accuracy = -1
    isolated_state_dict = None
    
    epoch_pbar = tqdm(range(num_epochs), desc=f"Fold {fold_idx+1}", leave=False)
    for iteration_step in epoch_pbar:
        loss_train = TrainOneEpoch(neural_model, loader_train, loss_criterion, iteration_optimizer, gradient_scaler)
        metrics_val = EvaluateOneEpoch(neural_model, loader_val, loss_criterion)
        
        history_tracker['train_losses'].append(loss_train)
        history_tracker['val_losses'].append(metrics_val['loss'])
        history_tracker['val_accuracies'].append(metrics_val['accuracy'])
        history_tracker['val_sensitivities'].append(metrics_val['sensitivity'])
        history_tracker['val_specificities'].append(metrics_val['specificity'])
        
        if metrics_val['accuracy'] > peak_accuracy:
            peak_accuracy = metrics_val['accuracy']
            isolated_state_dict = copy.deepcopy(neural_model.state_dict())
            
        epoch_pbar.set_postfix({'train_loss': f'{loss_train:.4f}', 'val_acc': f"{metrics_val['accuracy']:.4f}"})
        logger_obj.info(f"Epoch {iteration_step+1}/{num_epochs} - Train Loss: {loss_train:.4f} - Val Acc: {metrics_val['accuracy']:.4f}")
            
    return history_tracker, isolated_state_dict

def RunCrossValidationExperiment(dataset_name, model_name, x_data, y_data, use_smote_enn, epochs=100, n_folds=10, batch_size=32):
    condition_label = "smoteenn" if use_smote_enn else "baseline"
    
    fold_driver = StratifiedKFold(n_splits=n_folds, shuffle=True, random_state=42)
    metric_bounds = []
    historical_sequences = []
    
    global_top_accuracy = -1
    global_top_state = None
    global_top_fold = -1
    global_width = 0 
    best_x_val_stack = None
    
    main_pbar = tqdm(fold_driver.split(x_data, y_data), total=n_folds, desc=f"{dataset_name.capitalize()} | {model_name} | {condition_label.upper()}")
    
    for fold_step, (t_idx, v_idx) in enumerate(main_pbar):
        log_file = f"results/logs/{dataset_name}_{model_name}_{condition_label}_fold{fold_step}.log"
        file_handler = logging.FileHandler(log_file, mode='w')
        file_handler.setLevel(logging.INFO)
        logger.addHandler(file_handler)
        
        x_tr, x_val = x_data.iloc[t_idx].values, x_data.iloc[v_idx].values
        y_tr, y_val = y_data[t_idx], y_data[v_idx]
        
        logger.info(f"Original class distribution: {np.bincount(y_tr)}")
        logger.info(f"Training device bound securely to: {device}")
        
        if dataset_name == 'australian':
            x_tr_processed, x_val_processed = PreprocessAustralianFold(x_tr, x_val)
        else:
            x_tr_processed, x_val_processed = PreprocessGermanFold(x_tr, x_val)
            
        global_width = x_tr_processed.shape[1]
        
        if use_smote_enn:
            x_tr_processed, y_tr = ApplySmoteEnn(x_tr_processed, y_tr)
            logger.info(f"After SMOTE-ENN deployment: {np.bincount(y_tr)}")
            
        tensor_tr = BuildTensorDatasets(x_tr_processed, y_tr)
        tensor_val = BuildTensorDatasets(x_val_processed, y_val)
        
        neural_model, adam_optimizer, b_limit = GetModelAndOptimizer(model_label=model_name, in_features_dim=global_width)
        loader_train, loader_val = BuildDataLoaders(tensor_tr, tensor_val, load_batch_size=batch_size)
        
        history_tracker, local_top_state = FitModel(neural_model, loader_train, loader_val, adam_optimizer, fold_step, dataset_name, model_name, logger, num_epochs=epochs)
        
        neural_model.load_state_dict(local_top_state)
        fold_final_metrics = EvaluateOneEpoch(neural_model, loader_val, nn.BCEWithLogitsLoss())
        
        metric_bounds.append(fold_final_metrics)
        historical_sequences.append(history_tracker)
        
        if fold_final_metrics['accuracy'] > global_top_accuracy:
            global_top_accuracy = fold_final_metrics['accuracy']
            global_top_state = copy.deepcopy(local_top_state)
            global_top_fold = fold_step
            best_x_val_stack = x_val_processed
            
        # Clean nodes up per requirement
        del neural_model, adam_optimizer, loader_train, loader_val
        if torch.cuda.is_available():
            torch.cuda.empty_cache()
        gc.collect()
        logger.info(f"Fold {fold_step+1} logically complete. Tensor memory bounds cleared cleanly.")
        
        logger.removeHandler(file_handler)
        file_handler.close()

    acc_mean = np.mean([f['accuracy'] for f in metric_bounds])
    sens_mean = np.mean([f['sensitivity'] for f in metric_bounds])
    spec_mean = np.mean([f['specificity'] for f in metric_bounds])
    
    # Save explicit histories 
    df_histories = []
    for f_idx, history_dict in enumerate(historical_sequences):
        df_h = pd.DataFrame(history_dict)
        df_h['Fold'] = f_idx
        df_histories.append(df_h)
    pd.concat(df_histories).to_csv(f"results/histories/{dataset_name}_{model_name}_{condition_label}_full_history.csv", index=False)
    
    return {
        'model': model_name,
        'smoteenn': use_smote_enn,
        'mean_accuracy': acc_mean, 'std_accuracy': np.std([f['accuracy'] for f in metric_bounds]),
        'mean_sensitivity': sens_mean, 'std_sensitivity': np.std([f['sensitivity'] for f in metric_bounds]),
        'mean_specificity': spec_mean, 'std_specificity': np.std([f['specificity'] for f in metric_bounds]),
        'fold_metrics': metric_bounds,
        'fold_histories': historical_sequences,
        'best_state': global_top_state,
        'best_fold_idx': global_top_fold,
        'input_dim': global_width,
        'x_val': best_x_val_stack
    }

## ***German Dataset Experimental Execution***

***Purpose:*** Execute complete 10-fold cross-validation for all three models (MLP, LSTM, GRU) under both baseline and SMOTE-ENN conditions on the German credit dataset.

***Expected Duration:*** ~6-8 hours on Kaggle T4 x2 (can be reduced to ~2 hours with 20 epochs for testing). Currently scaled against `TESTING_MODE` limitations if defined.

In [21]:
logger.info("="*80)
logger.info("BEGINNING GERMAN DATASET EXPERIMENTAL PHASE")
logger.info("="*80)

x_german = df_german.iloc[:, :-1]
y_german = MapGermanLabels(df_german.iloc[:, -1].values)

DATASET_NAME = 'german'
MODELS_TO_TEST = ['MLP', 'LSTM', 'GRU']
RESAMPLING_CONDITIONS = [False, True] 

german_results = {}
best_german_shap_pkg = {'acc': -1}

for model_name in MODELS_TO_TEST:
    for use_smote in RESAMPLING_CONDITIONS:
        condition_name = 'smoteenn' if use_smote else 'baseline'
        experiment_key = f"{model_name}_{condition_name}"
        
        logger.info(f"\nEXPERIMENT: {experiment_key.upper()} | {DATASET_NAME} | SMOTE-ENN: {use_smote}")
        
        results_dict = RunCrossValidationExperiment(
            dataset_name=DATASET_NAME,
            model_name=model_name,
            x_data=x_german,
            y_data=y_german,
            use_smote_enn=use_smote,
            n_folds=10,
            epochs=NUM_EPOCHS,
            batch_size=32 if model_name == 'MLP' else 64
        )
        
        german_results[experiment_key] = results_dict
        
        logger.info(f"✓ Completed {experiment_key}")
        logger.info(f"  Mean Accuracy: {results_dict['mean_accuracy']:.4f} ± {results_dict['std_accuracy']:.4f}")
        
        if results_dict['mean_accuracy'] > best_german_shap_pkg['acc']:
            best_german_shap_pkg = {
                'acc': results_dict['mean_accuracy'],
                'model_name': model_name,
                'state': results_dict['best_state'],
                'input_dim': results_dict['input_dim'],
                'x_val': results_dict['x_val']
            }

german_summary_df = pd.DataFrame({
    'Experiment': list(german_results.keys()),
    'Mean_Accuracy': [german_results[k]['mean_accuracy'] for k in german_results.keys()],
    'Std_Accuracy': [german_results[k]['std_accuracy'] for k in german_results.keys()],
    'Mean_Sensitivity': [german_results[k]['mean_sensitivity'] for k in german_results.keys()],
    'Std_Sensitivity': [german_results[k]['std_sensitivity'] for k in german_results.keys()],
    'Mean_Specificity': [german_results[k]['mean_specificity'] for k in german_results.keys()],
    'Std_Specificity': [german_results[k]['std_specificity'] for k in german_results.keys()]
})

german_summary_df.to_csv('results/metrics/german_summary_results.csv', index=False)
print("\nGERMAN DATASET - FINAL RESULTS SUMMARY")
display(german_summary_df)

2026-04-05 05:15:20,260 - INFO - ================================================================================
2026-04-05 05:15:20,261 - INFO - BEGINNING GERMAN DATASET EXPERIMENTAL PHASE
2026-04-05 05:15:20,262 - INFO - ================================================================================
2026-04-05 05:15:20,266 - INFO -
EXPERIMENT: MLP_BASELINE | german | SMOTE-ENN: False

German | MLP | BASELINE:   0%|          | 0/10 [00:00<?, ?it/s]

2026-04-05 05:15:20,285 - INFO - Original class distribution: [277 344]
2026-04-05 05:15:20,285 - INFO - Training device bound securely to: cuda

Fold 1:   0%|          | 0/100 [00:00<?, ?it/s]

2026-04-05 05:15:27,160 - INFO - Epoch 1/100 - Train Loss: 0.6252 - Val Acc: 0.8841
2026-04-05 05:15:27,461 - INFO - Epoch 2/100 - Train Loss: 0.4513 - Val Acc: 0.8841
2026-04-05 05:15:27,776 - INFO - Epoch 3/100 - Train Loss: 0.3711 - Val Acc: 0.8841
2026-04-05 05:15:28,090 - INFO - Epoch 4/100 - Train Loss: 0.3447 - Val Acc: 0.8986
2026-04-05 05:15:28,400 - INFO - Epoch 5/100 - Train Loss: 0.3315 - Val Acc: 0.8986
2026-04-05 05:15:28,713 - INFO - Epoch 6/100 - Train Loss: 0.3145 - Val Acc: 0.8986
2026-04-05 05:15:29,017 - INFO - Epoch 7/100 - Train Loss: 0.3062 - Val Acc: 0.8986
2026-04-05 05:15:29,327 - INFO - Epoch 8/100 - Train Loss: 0.3078 - Val Acc: 0.8841
2026-04-05 05:15:29,637 - INFO - Epoch 9/100 - Train Loss: 0.3106 - Val Acc: 0.8841
2026-04-05 05:15:29,945 - INFO - Epoch 10/100 - Train Loss: 0.3025 - Val Acc: 0.8841
2026-04-05 05:15:30,265 - INFO - Epoch 11/100 - Train Loss: 0.2862 - Val Acc: 0.8841
2026-04-05 05:15:30,578 - INFO - Epoch 12/100 - Train Loss: 0.2902 - Val Acc: 0.8841
2026-04-05 05:15:30,888 - INFO - Epoch 13/100 - Train Loss: 0.2842 - Val Acc: 0.8841
2026-04-05 05:15:31,201 - INFO - Epoch 14/100 - Train Loss: 0.2763 - Val Acc: 0.8841
2026-04-05 05:15:31,517 - INFO - Epoch 15/100 - Train Loss: 0.2878 - Val Acc: 0.8841
2026-04-05 05:15:31,832 - INFO - Epoch 16/100 - Train Loss: 0.2684 - Val Acc: 0.8841
2026-04-05 05:15:32,138 - INFO - Epoch 17/100 - Train Loss: 0.2656 - Val Acc: 0.8841
2026-04-05 05:15:32,449 - INFO - Epoch 18/100 - Train Loss: 0.2708 - Val Acc: 0.8841
2026-04-05 05:15:32,774 - INFO - Epoch 19/100 - Train Loss: 0.2674 - Val Acc: 0.8841
2026-04-05 05:15:33,096 - INFO - Epoch 20/100 - Train Loss: 0.2649 - Val Acc: 0.8841
2026-04-05 05:15:33,411 - INFO - Epoch 21/100 - Train Loss: 0.2543 - Val Acc: 0.8841
2026-04-05 05:15:33,725 - INFO - Epoch 22/100 - Train Loss: 0.2433 - Val Acc: 0.8841
2026-04-05 05:15:34,060 - INFO - Epoch 23/100 - Train Loss: 0.2494 - Val Acc: 0.8841
2026-04-05 05:15:34,404 - INFO - Epoch 24/100 - Train Loss: 0.2451 - Val Acc: 0.8841
2026-04-05 05:15:34,759 - INFO - Epoch 25/100 - Train Loss: 0.2466 - Val Acc: 0.8841
2026-04-05 05:15:35,083 - INFO - Epoch 26/100 - Train Loss: 0.2400 - Val Acc: 0.8986
2026-04-05 05:15:35,398 - INFO - Epoch 27/100 - Train Loss: 0.2448 - Val Acc: 0.8841
2026-04-05 05:15:35,720 - INFO - Epoch 28/100 - Train Loss: 0.2298 - Val Acc: 0.8841
2026-04-05 05:15:36,041 - INFO - Epoch 29/100 - Train Loss: 0.2332 - Val Acc: 0.8841
2026-04-05 05:15:36,365 - INFO - Epoch 30/100 - Train Loss: 0.2452 - Val Acc: 0.8841
2026-04-05 05:15:36,691 - INFO - Epoch 31/100 - Train Loss: 0.2220 - Val Acc: 0.8841
2026-04-05 05:15:37,016 - INFO - Epoch 32/100 - Train Loss: 0.2342 - Val Acc: 0.8841
2026-04-05 05:15:37,342 - INFO - Epoch 33/100 - Train Loss: 0.2244 - Val Acc: 0.8841
2026-04-05 05:15:37,667 - INFO - Epoch 34/100 - Train Loss: 0.2321 - Val Acc: 0.8841
2026-04-05 05:15:38,010 - INFO - Epoch 35/100 - Train Loss: 0.2513 - Val Acc: 0.8696
2026-04-05 05:15:38,330 - INFO - Epoch 36/100 - Train Loss: 0.2210 - Val Acc: 0.8841
2026-04-05 05:15:38,646 - INFO - Epoch 37/100 - Train Loss: 0.2265 - Val Acc: 0.8841
2026-04-05 05:15:38,981 - INFO - Epoch 38/100 - Train Loss: 0.2240 - Val Acc: 0.8841
2026-04-05 05:15:39,307 - INFO - Epoch 39/100 - Train Loss: 0.2118 - Val Acc: 0.8841
2026-04-05 05:15:39,641 - INFO - Epoch 40/100 - Train Loss: 0.2008 - Val Acc: 0.8841
2026-04-05 05:15:39,999 - INFO - Epoch 41/100 - Train Loss: 0.1998 - Val Acc: 0.8841
2026-04-05 05:15:40,341 - INFO - Epoch 42/100 - Train Loss: 0.2085 - Val Acc: 0.8986
2026-04-05 05:15:40,663 - INFO - Epoch 43/100 - Train Loss: 0.1953 - Val Acc: 0.8841
2026-04-05 05:15:40,985 - INFO - Epoch 44/100 - Train Loss: 0.2119 - Val Acc: 0.8841
2026-04-05 05:15:41,315 - INFO - Epoch 45/100 - Train Loss: 0.1939 - Val Acc: 0.8841
2026-04-05 05:15:41,634 - INFO - Epoch 46/100 - Train Loss: 0.1979 - Val Acc: 0.8841
2026-04-05 05:15:41,948 - INFO - Epoch 47/100 - Train Loss: 0.1946 - Val Acc: 0.8841
2026-04-05 05:15:42,264 - INFO - Epoch 48/100 - Train Loss: 0.1996 - Val Acc: 0.8841
2026-04-05 05:15:42,576 - INFO - Epoch 49/100 - Train Loss: 0.1796 - Val Acc: 0.8986
2026-04-05 05:15:42,887 - INFO - Epoch 50/100 - Train Loss: 0.1871 - Val Acc: 0.8841
2026-04-05 05:15:43,202 - INFO - Epoch 51/100 - Train Loss: 0.1790 - Val Acc: 0.8841
2026-04-05 05:15:43,512 - INFO - Epoch 52/100 - Train Loss: 0.1802 - Val Acc: 0.8986
2026-04-05 05:15:43,823 - INFO - Epoch 53/100 - Train Loss: 0.1732 - Val Acc: 0.8841
2026-04-05 05:15:44,135 - INFO - Epoch 54/100 - Train Loss: 0.1837 - Val Acc: 0.8841
2026-04-05 05:15:44,487 - INFO - Epoch 55/100 - Train Loss: 0.1748 - Val Acc: 0.8841
2026-04-05 05:15:44,837 - INFO - Epoch 56/100 - Train Loss: 0.1919 - Val Acc: 0.8841
2026-04-05 05:15:45,174 - INFO - Epoch 57/100 - Train Loss: 0.1638 - Val Acc: 0.8841
2026-04-05 05:15:45,490 - INFO - Epoch 58/100 - Train Loss: 0.1615 - Val Acc: 0.8696
2026-04-05 05:15:45,815 - INFO - Epoch 59/100 - Train Loss: 0.1780 - Val Acc: 0.8696
2026-04-05 05:15:46,131 - INFO - Epoch 60/100 - Train Loss: 0.1659 - Val Acc: 0.8841
2026-04-05 05:15:46,450 - INFO - Epoch 61/100 - Train Loss: 0.1568 - Val Acc: 0.8841
2026-04-05 05:15:46,770 - INFO - Epoch 62/100 - Train Loss: 0.1678 - Val Acc: 0.8696
2026-04-05 05:15:47,084 - INFO - Epoch 63/100 - Train Loss: 0.1733 - Val Acc: 0.8986
2026-04-05 05:15:47,395 - INFO - Epoch 64/100 - Train Loss: 0.1609 - Val Acc: 0.8841
2026-04-05 05:15:47,709 - INFO - Epoch 65/100 - Train Loss: 0.1477 - Val Acc: 0.8696
2026-04-05 05:15:48,021 - INFO - Epoch 66/100 - Train Loss: 0.1687 - Val Acc: 0.8841
2026-04-05 05:15:48,341 - INFO - Epoch 67/100 - Train Loss: 0.1821 - Val Acc: 0.8986
2026-04-05 05:15:48,656 - INFO - Epoch 68/100 - Train Loss: 0.1696 - Val Acc: 0.8986
2026-04-05 05:15:48,981 - INFO - Epoch 69/100 - Train Loss: 0.1603 - Val Acc: 0.8841
2026-04-05 05:15:49,301 - INFO - Epoch 70/100 - Train Loss: 0.1544 - Val Acc: 0.8986
2026-04-05 05:15:49,615 - INFO - Epoch 71/100 - Train Loss: 0.1520 - Val Acc: 0.8986
2026-04-05 05:15:49,921 - INFO - Epoch 72/100 - Train Loss: 0.1533 - Val Acc: 0.8841
2026-04-05 05:15:50,240 - INFO - Epoch 73/100 - Train Loss: 0.1505 - Val Acc: 0.8841
2026-04-05 05:15:50,560 - INFO - Epoch 74/100 - Train Loss: 0.1374 - Val Acc: 0.8696
2026-04-05 05:15:50,874 - INFO - Epoch 75/100 - Train Loss: 0.1561 - Val Acc: 0.8841
2026-04-05 05:15:51,187 - INFO - Epoch 76/100 - Train Loss: 0.1358 - Val Acc: 0.8986
2026-04-05 05:15:51,513 - INFO - Epoch 77/100 - Train Loss: 0.1633 - Val Acc: 0.8696
2026-04-05 05:15:51,825 - INFO - Epoch 78/100 - Train Loss: 0.1465 - Val Acc: 0.8841
2026-04-05 05:15:52,137 - INFO - Epoch 79/100 - Train Loss: 0.1487 - Val Acc: 0.8841
2026-04-05 05:15:52,458 - INFO - Epoch 80/100 - Train Loss: 0.1496 - Val Acc: 0.8696
2026-04-05 05:15:52,770 - INFO - Epoch 81/100 - Train Loss: 0.1276 - Val Acc: 0.8841
2026-04-05 05:15:53,092 - INFO - Epoch 82/100 - Train Loss: 0.1513 - Val Acc: 0.8841
2026-04-05 05:15:53,414 - INFO - Epoch 83/100 - Train Loss: 0.1320 - Val Acc: 0.8841
2026-04-05 05:15:53,726 - INFO - Epoch 84/100 - Train Loss: 0.1521 - Val Acc: 0.8841
2026-04-05 05:15:54,048 - INFO - Epoch 85/100 - Train Loss: 0.1462 - Val Acc: 0.8841
2026-04-05 05:15:54,392 - INFO - Epoch 86/100 - Train Loss: 0.1267 - Val Acc: 0.8696
2026-04-05 05:15:54,734 - INFO - Epoch 87/100 - Train Loss: 0.1327 - Val Acc: 0.8551
2026-04-05 05:15:55,055 - INFO - Epoch 88/100 - Train Loss: 0.1390 - Val Acc: 0.8551
2026-04-05 05:15:55,367 - INFO - Epoch 89/100 - Train Loss: 0.1401 - Val Acc: 0.8696
2026-04-05 05:15:55,681 - INFO - Epoch 90/100 - Train Loss: 0.1313 - Val Acc: 0.8696
2026-04-05 05:15:55,988 - INFO - Epoch 91/100 - Train Loss: 0.1438 - Val Acc: 0.8696
2026-04-05 05:15:56,299 - INFO - Epoch 92/100 - Train Loss: 0.1283 - Val Acc: 0.8551
2026-04-05 05:15:56,607 - INFO - Epoch 93/100 - Train Loss: 0.1364 - Val Acc: 0.8551
2026-04-05 05:15:56,915 - INFO - Epoch 94/100 - Train Loss: 0.1240 - Val Acc: 0.8551
2026-04-05 05:15:57,227 - INFO - Epoch 95/100 - Train Loss: 0.1344 - Val Acc: 0.8551
2026-04-05 05:15:57,554 - INFO - Epoch 96/100 - Train Loss: 0.1359 - Val Acc: 0.8841
2026-04-05 05:15:57,879 - INFO - Epoch 97/100 - Train Loss: 0.1205 - Val Acc: 0.8696
2026-04-05 05:15:58,190 - INFO - Epoch 98/100 - Train Loss: 0.1254 - Val Acc: 0.8551
2026-04-05 05:15:58,509 - INFO - Epoch 99/100 - Train Loss: 0.1261 - Val Acc: 0.8551
2026-04-05 05:15:58,834 - INFO - Epoch 100/100 - Train Loss: 0.1232 - Val Acc: 0.8696
2026-04-05 05:15:59,191 - INFO - Fold 1 logically complete. Tensor memory bounds cleared cleanly.
2026-04-05 05:15:59,195 - INFO - Original class distribution: [277 344]
2026-04-05 05:15:59,196 - INFO - Training device bound securely to: cuda

Fold 2:   0%|          | 0/100 [00:00<?, ?it/s]

2026-04-05 05:15:59,528 - INFO - Epoch 1/100 - Train Loss: 0.6169 - Val Acc: 0.8116
2026-04-05 05:15:59,843 - INFO - Epoch 2/100 - Train Loss: 0.4206 - Val Acc: 0.8551
2026-04-05 05:16:00,172 - INFO - Epoch 3/100 - Train Loss: 0.3406 - Val Acc: 0.8696
2026-04-05 05:16:00,484 - INFO - Epoch 4/100 - Train Loss: 0.3278 - Val Acc: 0.8841
2026-04-05 05:16:00,800 - INFO - Epoch 5/100 - Train Loss: 0.3168 - Val Acc: 0.8986
2026-04-05 05:16:01,117 - INFO - Epoch 6/100 - Train Loss: 0.3094 - Val Acc: 0.8986
2026-04-05 05:16:01,436 - INFO - Epoch 7/100 - Train Loss: 0.2932 - Val Acc: 0.9130
2026-04-05 05:16:01,746 - INFO - Epoch 8/100 - Train Loss: 0.2863 - Val Acc: 0.9130
2026-04-05 05:16:02,070 - INFO - Epoch 9/100 - Train Loss: 0.2964 - Val Acc: 0.9130
2026-04-05 05:16:02,380 - INFO - Epoch 10/100 - Train Loss: 0.2832 - Val Acc: 0.8986
2026-04-05 05:16:02,688 - INFO - Epoch 11/100 - Train Loss: 0.2826 - Val Acc: 0.9130
2026-04-05 05:16:03,002 - INFO - Epoch 12/100 - Train Loss: 0.2799 - Val Acc: 0.9130
2026-04-05 05:16:03,316 - INFO - Epoch 13/100 - Train Loss: 0.2823 - Val Acc: 0.9130
2026-04-05 05:16:03,624 - INFO - Epoch 14/100 - Train Loss: 0.2556 - Val Acc: 0.8986
2026-04-05 05:16:03,941 - INFO - Epoch 15/100 - Train Loss: 0.2692 - Val Acc: 0.8986
2026-04-05 05:16:04,263 - INFO - Epoch 16/100 - Train Loss: 0.2514 - Val Acc: 0.9130
2026-04-05 05:16:04,604 - INFO - Epoch 17/100 - Train Loss: 0.2645 - Val Acc: 0.9275
2026-04-05 05:16:04,911 - INFO - Epoch 18/100 - Train Loss: 0.2527 - Val Acc: 0.9130
2026-04-05 05:16:05,217 - INFO - Epoch 19/100 - Train Loss: 0.2463 - Val Acc: 0.9130
2026-04-05 05:16:05,523 - INFO - Epoch 20/100 - Train Loss: 0.2455 - Val Acc: 0.9275
2026-04-05 05:16:05,830 - INFO - Epoch 21/100 - Train Loss: 0.2427 - Val Acc: 0.9275
2026-04-05 05:16:06,144 - INFO - Epoch 22/100 - Train Loss: 0.2356 - Val Acc: 0.9275
2026-04-05 05:16:06,463 - INFO - Epoch 23/100 - Train Loss: 0.2432 - Val Acc: 0.9420
2026-04-05 05:16:06,782 - INFO - Epoch 24/100 - Train Loss: 0.2262 - Val Acc: 0.9275
2026-04-05 05:16:07,095 - INFO - Epoch 25/100 - Train Loss: 0.2436 - Val Acc: 0.9275
2026-04-05 05:16:07,409 - INFO - Epoch 26/100 - Train Loss: 0.2341 - Val Acc: 0.9130
2026-04-05 05:16:07,722 - INFO - Epoch 27/100 - Train Loss: 0.2225 - Val Acc: 0.8986
2026-04-05 05:16:08,039 - INFO - Epoch 28/100 - Train Loss: 0.2177 - Val Acc: 0.8986
2026-04-05 05:16:08,352 - INFO - Epoch 29/100 - Train Loss: 0.2195 - Val Acc: 0.8986
2026-04-05 05:16:08,684 - INFO - Epoch 30/100 - Train Loss: 0.2398 - Val Acc: 0.8696
2026-04-05 05:16:08,996 - INFO - Epoch 31/100 - Train Loss: 0.2142 - Val Acc: 0.8986
2026-04-05 05:16:09,310 - INFO - Epoch 32/100 - Train Loss: 0.2256 - Val Acc: 0.8841
2026-04-05 05:16:09,622 - INFO - Epoch 33/100 - Train Loss: 0.2318 - Val Acc: 0.9130
2026-04-05 05:16:09,937 - INFO - Epoch 34/100 - Train Loss: 0.2200 - Val Acc: 0.8986
2026-04-05 05:16:10,254 - INFO - Epoch 35/100 - Train Loss: 0.2060 - Val Acc: 0.8841
2026-04-05 05:16:10,571 - INFO - Epoch 36/100 - Train Loss: 0.2105 - Val Acc: 0.8986
2026-04-05 05:16:10,877 - INFO - Epoch 37/100 - Train Loss: 0.2094 - Val Acc: 0.8841
2026-04-05 05:16:11,192 - INFO - Epoch 38/100 - Train Loss: 0.2105 - Val Acc: 0.8841
2026-04-05 05:16:11,508 - INFO - Epoch 39/100 - Train Loss: 0.2141 - Val Acc: 0.9130
2026-04-05 05:16:11,827 - INFO - Epoch 40/100 - Train Loss: 0.2022 - Val Acc: 0.8841
2026-04-05 05:16:12,159 - INFO - Epoch 41/100 - Train Loss: 0.2002 - Val Acc: 0.8841
2026-04-05 05:16:12,486 - INFO - Epoch 42/100 - Train Loss: 0.2065 - Val Acc: 0.8841
2026-04-05 05:16:12,818 - INFO - Epoch 43/100 - Train Loss: 0.1915 - Val Acc: 0.9130
2026-04-05 05:16:13,131 - INFO - Epoch 44/100 - Train Loss: 0.1962 - Val Acc: 0.8986
2026-04-05 05:16:13,449 - INFO - Epoch 45/100 - Train Loss: 0.1958 - Val Acc: 0.8986
2026-04-05 05:16:13,769 - INFO - Epoch 46/100 - Train Loss: 0.1956 - Val Acc: 0.8986
2026-04-05 05:16:14,080 - INFO - Epoch 47/100 - Train Loss: 0.1788 - Val Acc: 0.9130
2026-04-05 05:16:14,428 - INFO - Epoch 48/100 - Train Loss: 0.1920 - Val Acc: 0.8986
2026-04-05 05:16:14,761 - INFO - Epoch 49/100 - Train Loss: 0.1904 - Val Acc: 0.9130
2026-04-05 05:16:15,078 - INFO - Epoch 50/100 - Train Loss: 0.1800 - Val Acc: 0.8986
2026-04-05 05:16:15,392 - INFO - Epoch 51/100 - Train Loss: 0.1820 - Val Acc: 0.9130
2026-04-05 05:16:15,710 - INFO - Epoch 52/100 - Train Loss: 0.1700 - Val Acc: 0.8986
2026-04-05 05:16:16,024 - INFO - Epoch 53/100 - Train Loss: 0.1825 - Val Acc: 0.8986
2026-04-05 05:16:16,333 - INFO - Epoch 54/100 - Train Loss: 0.1675 - Val Acc: 0.9130
2026-04-05 05:16:16,654 - INFO - Epoch 55/100 - Train Loss: 0.1780 - Val Acc: 0.8986
2026-04-05 05:16:16,973 - INFO - Epoch 56/100 - Train Loss: 0.1728 - Val Acc: 0.8841
2026-04-05 05:16:17,292 - INFO - Epoch 57/100 - Train Loss: 0.1737 - Val Acc: 0.8986
2026-04-05 05:16:17,614 - INFO - Epoch 58/100 - Train Loss: 0.1617 - Val Acc: 0.8986
2026-04-05 05:16:17,919 - INFO - Epoch 59/100 - Train Loss: 0.1837 - Val Acc: 0.8696
2026-04-05 05:16:18,235 - INFO - Epoch 60/100 - Train Loss: 0.1592 - Val Acc: 0.8986
2026-04-05 05:16:18,549 - INFO - Epoch 61/100 - Train Loss: 0.1556 - Val Acc: 0.8986
2026-04-05 05:16:18,863 - INFO - Epoch 62/100 - Train Loss: 0.1595 - Val Acc: 0.8986
2026-04-05 05:16:19,173 - INFO - Epoch 63/100 - Train Loss: 0.1490 - Val Acc: 0.8986
2026-04-05 05:16:19,486 - INFO - Epoch 64/100 - Train Loss: 0.1666 - Val Acc: 0.9130
2026-04-05 05:16:19,799 - INFO - Epoch 65/100 - Train Loss: 0.1679 - Val Acc: 0.9130
2026-04-05 05:16:20,108 - INFO - Epoch 66/100 - Train Loss: 0.1524 - Val Acc: 0.8986
2026-04-05 05:16:20,425 - INFO - Epoch 67/100 - Train Loss: 0.1801 - Val Acc: 0.8986
2026-04-05 05:16:20,737 - INFO - Epoch 68/100 - Train Loss: 0.1605 - Val Acc: 0.8986
2026-04-05 05:16:21,044 - INFO - Epoch 69/100 - Train Loss: 0.1590 - Val Acc: 0.8986
2026-04-05 05:16:21,349 - INFO - Epoch 70/100 - Train Loss: 0.1548 - Val Acc: 0.8986
2026-04-05 05:16:21,665 - INFO - Epoch 71/100 - Train Loss: 0.1421 - Val Acc: 0.8841
2026-04-05 05:16:21,989 - INFO - Epoch 72/100 - Train Loss: 0.1484 - Val Acc: 0.8841
2026-04-05 05:16:22,298 - INFO - Epoch 73/100 - Train Loss: 0.1433 - Val Acc: 0.8841
2026-04-05 05:16:22,613 - INFO - Epoch 74/100 - Train Loss: 0.1617 - Val Acc: 0.8841
2026-04-05 05:16:22,932 - INFO - Epoch 75/100 - Train Loss: 0.1470 - Val Acc: 0.8841
2026-04-05 05:16:23,252 - INFO - Epoch 76/100 - Train Loss: 0.1464 - Val Acc: 0.8986
2026-04-05 05:16:23,562 - INFO - Epoch 77/100 - Train Loss: 0.1408 - Val Acc: 0.8696
2026-04-05 05:16:23,875 - INFO - Epoch 78/100 - Train Loss: 0.1607 - Val Acc: 0.8986
2026-04-05 05:16:24,193 - INFO - Epoch 79/100 - Train Loss: 0.1392 - Val Acc: 0.8841
2026-04-05 05:16:24,506 - INFO - Epoch 80/100 - Train Loss: 0.1504 - Val Acc: 0.8841
2026-04-05 05:16:24,839 - INFO - Epoch 81/100 - Train Loss: 0.1289 - Val Acc: 0.8841
2026-04-05 05:16:25,158 - INFO - Epoch 82/100 - Train Loss: 0.1400 - Val Acc: 0.8841
2026-04-05 05:16:25,463 - INFO - Epoch 83/100 - Train Loss: 0.1383 - Val Acc: 0.8841
2026-04-05 05:16:25,772 - INFO - Epoch 84/100 - Train Loss: 0.1336 - Val Acc: 0.8841
2026-04-05 05:16:26,083 - INFO - Epoch 85/100 - Train Loss: 0.1456 - Val Acc: 0.8841
2026-04-05 05:16:26,397 - INFO - Epoch 86/100 - Train Loss: 0.1238 - Val Acc: 0.8841
2026-04-05 05:16:26,726 - INFO - Epoch 87/100 - Train Loss: 0.1303 - Val Acc: 0.9275
2026-04-05 05:16:27,030 - INFO - Epoch 88/100 - Train Loss: 0.1300 - Val Acc: 0.9130
2026-04-05 05:16:27,347 - INFO - Epoch 89/100 - Train Loss: 0.1339 - Val Acc: 0.8841
2026-04-05 05:16:27,652 - INFO - Epoch 90/100 - Train Loss: 0.1300 - Val Acc: 0.8986
2026-04-05 05:16:27,981 - INFO - Epoch 91/100 - Train Loss: 0.1327 - Val Acc: 0.8696
2026-04-05 05:16:28,295 - INFO - Epoch 92/100 - Train Loss: 0.1253 - Val Acc: 0.8696
2026-04-05 05:16:28,611 - INFO - Epoch 93/100 - Train Loss: 0.1211 - Val Acc: 0.8986
2026-04-05 05:16:28,921 - INFO - Epoch 94/100 - Train Loss: 0.1303 - Val Acc: 0.8841
2026-04-05 05:16:29,244 - INFO - Epoch 95/100 - Train Loss: 0.1279 - Val Acc: 0.8696
2026-04-05 05:16:29,551 - INFO - Epoch 96/100 - Train Loss: 0.1180 - Val Acc: 0.8696
2026-04-05 05:16:29,867 - INFO - Epoch 97/100 - Train Loss: 0.1154 - Val Acc: 0.8696
2026-04-05 05:16:30,185 - INFO - Epoch 98/100 - Train Loss: 0.1301 - Val Acc: 0.8696
2026-04-05 05:16:30,506 - INFO - Epoch 99/100 - Train Loss: 0.1126 - Val Acc: 0.8696
2026-04-05 05:16:30,831 - INFO - Epoch 100/100 - Train Loss: 0.1206 - Val Acc: 0.8696
2026-04-05 05:16:31,199 - INFO - Fold 2 logically complete. Tensor memory bounds cleared cleanly.
2026-04-05 05:16:31,203 - INFO - Original class distribution: [277 344]
2026-04-05 05:16:31,204 - INFO - Training device bound securely to: cuda

Fold 3:   0%|          | 0/100 [00:00<?, ?it/s]

2026-04-05 05:16:31,552 - INFO - Epoch 1/100 - Train Loss: 0.6127 - Val Acc: 0.9130
2026-04-05 05:16:31,861 - INFO - Epoch 2/100 - Train Loss: 0.4402 - Val Acc: 0.9130
2026-04-05 05:16:32,178 - INFO - Epoch 3/100 - Train Loss: 0.3552 - Val Acc: 0.9130
2026-04-05 05:16:32,506 - INFO - Epoch 4/100 - Train Loss: 0.3439 - Val Acc: 0.9130
2026-04-05 05:16:32,827 - INFO - Epoch 5/100 - Train Loss: 0.3182 - Val Acc: 0.9130
2026-04-05 05:16:33,143 - INFO - Epoch 6/100 - Train Loss: 0.3207 - Val Acc: 0.9130
2026-04-05 05:16:33,468 - INFO - Epoch 7/100 - Train Loss: 0.3045 - Val Acc: 0.9130
2026-04-05 05:16:33,784 - INFO - Epoch 8/100 - Train Loss: 0.3140 - Val Acc: 0.9130
2026-04-05 05:16:34,108 - INFO - Epoch 9/100 - Train Loss: 0.3057 - Val Acc: 0.9130
2026-04-05 05:16:34,473 - INFO - Epoch 10/100 - Train Loss: 0.2922 - Val Acc: 0.9130
2026-04-05 05:16:34,798 - INFO - Epoch 11/100 - Train Loss: 0.2880 - Val Acc: 0.9130
2026-04-05 05:16:35,114 - INFO - Epoch 12/100 - Train Loss: 0.2988 - Val Acc: 0.9130
2026-04-05 05:16:35,451 - INFO - Epoch 13/100 - Train Loss: 0.2785 - Val Acc: 0.9130
2026-04-05 05:16:35,768 - INFO - Epoch 14/100 - Train Loss: 0.2699 - Val Acc: 0.9130
2026-04-05 05:16:36,091 - INFO - Epoch 15/100 - Train Loss: 0.2825 - Val Acc: 0.9130
2026-04-05 05:16:36,410 - INFO - Epoch 16/100 - Train Loss: 0.2853 - Val Acc: 0.9130
2026-04-05 05:16:36,726 - INFO - Epoch 17/100 - Train Loss: 0.2681 - Val Acc: 0.9130
2026-04-05 05:16:37,055 - INFO - Epoch 18/100 - Train Loss: 0.2585 - Val Acc: 0.9130
2026-04-05 05:16:37,374 - INFO - Epoch 19/100 - Train Loss: 0.2528 - Val Acc: 0.9130
2026-04-05 05:16:37,686 - INFO - Epoch 20/100 - Train Loss: 0.2627 - Val Acc: 0.9130
2026-04-05 05:16:38,017 - INFO - Epoch 21/100 - Train Loss: 0.2664 - Val Acc: 0.9130
2026-04-05 05:16:38,334 - INFO - Epoch 22/100 - Train Loss: 0.2574 - Val Acc: 0.9130
2026-04-05 05:16:38,652 - INFO - Epoch 23/100 - Train Loss: 0.2664 - Val Acc: 0.9130
2026-04-05 05:16:38,967 - INFO - Epoch 24/100 - Train Loss: 0.2476 - Val Acc: 0.9130
2026-04-05 05:16:39,275 - INFO - Epoch 25/100 - Train Loss: 0.2559 - Val Acc: 0.9130
2026-04-05 05:16:39,587 - INFO - Epoch 26/100 - Train Loss: 0.2417 - Val Acc: 0.9130
2026-04-05 05:16:39,905 - INFO - Epoch 27/100 - Train Loss: 0.2409 - Val Acc: 0.9275
2026-04-05 05:16:40,221 - INFO - Epoch 28/100 - Train Loss: 0.2385 - Val Acc: 0.9130
2026-04-05 05:16:40,536 - INFO - Epoch 29/100 - Train Loss: 0.2388 - Val Acc: 0.9275
2026-04-05 05:16:40,861 - INFO - Epoch 30/100 - Train Loss: 0.2325 - Val Acc: 0.9130
2026-04-05 05:16:41,179 - INFO - Epoch 31/100 - Train Loss: 0.2273 - Val Acc: 0.9130
2026-04-05 05:16:41,494 - INFO - Epoch 32/100 - Train Loss: 0.2305 - Val Acc: 0.9275
2026-04-05 05:16:41,813 - INFO - Epoch 33/100 - Train Loss: 0.2307 - Val Acc: 0.9130
2026-04-05 05:16:42,128 - INFO - Epoch 34/100 - Train Loss: 0.2239 - Val Acc: 0.9275
2026-04-05 05:16:42,439 - INFO - Epoch 35/100 - Train Loss: 0.2058 - Val Acc: 0.9275
2026-04-05 05:16:42,756 - INFO - Epoch 36/100 - Train Loss: 0.2268 - Val Acc: 0.9275
2026-04-05 05:16:43,082 - INFO - Epoch 37/100 - Train Loss: 0.2076 - Val Acc: 0.9275
2026-04-05 05:16:43,390 - INFO - Epoch 38/100 - Train Loss: 0.2261 - Val Acc: 0.9275
2026-04-05 05:16:43,705 - INFO - Epoch 39/100 - Train Loss: 0.2041 - Val Acc: 0.9275
2026-04-05 05:16:44,014 - INFO - Epoch 40/100 - Train Loss: 0.1986 - Val Acc: 0.9275
2026-04-05 05:16:44,365 - INFO - Epoch 41/100 - Train Loss: 0.1985 - Val Acc: 0.9275
2026-04-05 05:16:44,707 - INFO - Epoch 42/100 - Train Loss: 0.1976 - Val Acc: 0.9275
2026-04-05 05:16:45,030 - INFO - Epoch 43/100 - Train Loss: 0.2141 - Val Acc: 0.9275
2026-04-05 05:16:45,347 - INFO - Epoch 44/100 - Train Loss: 0.1992 - Val Acc: 0.9275
2026-04-05 05:16:45,688 - INFO - Epoch 45/100 - Train Loss: 0.1819 - Val Acc: 0.9275
2026-04-05 05:16:46,022 - INFO - Epoch 46/100 - Train Loss: 0.2051 - Val Acc: 0.9275
2026-04-05 05:16:46,341 - INFO - Epoch 47/100 - Train Loss: 0.1927 - Val Acc: 0.9275
2026-04-05 05:16:46,654 - INFO - Epoch 48/100 - Train Loss: 0.1929 - Val Acc: 0.9275
2026-04-05 05:16:46,988 - INFO - Epoch 49/100 - Train Loss: 0.1973 - Val Acc: 0.9275
2026-04-05 05:16:47,305 - INFO - Epoch 50/100 - Train Loss: 0.1936 - Val Acc: 0.9275
2026-04-05 05:16:47,625 - INFO - Epoch 51/100 - Train Loss: 0.1892 - Val Acc: 0.9275
2026-04-05 05:16:47,944 - INFO - Epoch 52/100 - Train Loss: 0.1900 - Val Acc: 0.9275
2026-04-05 05:16:48,261 - INFO - Epoch 53/100 - Train Loss: 0.1852 - Val Acc: 0.9275
2026-04-05 05:16:48,571 - INFO - Epoch 54/100 - Train Loss: 0.1733 - Val Acc: 0.9275
2026-04-05 05:16:48,892 - INFO - Epoch 55/100 - Train Loss: 0.1742 - Val Acc: 0.9275
2026-04-05 05:16:49,211 - INFO - Epoch 56/100 - Train Loss: 0.1879 - Val Acc: 0.8986
2026-04-05 05:16:49,528 - INFO - Epoch 57/100 - Train Loss: 0.1787 - Val Acc: 0.9275
2026-04-05 05:16:49,849 - INFO - Epoch 58/100 - Train Loss: 0.1868 - Val Acc: 0.9130
2026-04-05 05:16:50,170 - INFO - Epoch 59/100 - Train Loss: 0.1597 - Val Acc: 0.9275
2026-04-05 05:16:50,489 - INFO - Epoch 60/100 - Train Loss: 0.1791 - Val Acc: 0.9275
2026-04-05 05:16:50,809 - INFO - Epoch 61/100 - Train Loss: 0.1769 - Val Acc: 0.9275
2026-04-05 05:16:51,119 - INFO - Epoch 62/100 - Train Loss: 0.1703 - Val Acc: 0.9275
2026-04-05 05:16:51,433 - INFO - Epoch 63/100 - Train Loss: 0.1807 - Val Acc: 0.9275
2026-04-05 05:16:51,752 - INFO - Epoch 64/100 - Train Loss: 0.1849 - Val Acc: 0.9275
2026-04-05 05:16:52,071 - INFO - Epoch 65/100 - Train Loss: 0.1519 - Val Acc: 0.9275
2026-04-05 05:16:52,397 - INFO - Epoch 66/100 - Train Loss: 0.1696 - Val Acc: 0.9275
2026-04-05 05:16:52,707 - INFO - Epoch 67/100 - Train Loss: 0.1659 - Val Acc: 0.9275
2026-04-05 05:16:53,024 - INFO - Epoch 68/100 - Train Loss: 0.1542 - Val Acc: 0.9275
2026-04-05 05:16:53,344 - INFO - Epoch 69/100 - Train Loss: 0.1512 - Val Acc: 0.9130
2026-04-05 05:16:53,658 - INFO - Epoch 70/100 - Train Loss: 0.1531 - Val Acc: 0.9275
2026-04-05 05:16:53,979 - INFO - Epoch 71/100 - Train Loss: 0.1674 - Val Acc: 0.9275
2026-04-05 05:16:54,335 - INFO - Epoch 72/100 - Train Loss: 0.1547 - Val Acc: 0.9275
2026-04-05 05:16:54,676 - INFO - Epoch 73/100 - Train Loss: 0.1663 - Val Acc: 0.9275
2026-04-05 05:16:54,983 - INFO - Epoch 74/100 - Train Loss: 0.1565 - Val Acc: 0.9130
2026-04-05 05:16:55,296 - INFO - Epoch 75/100 - Train Loss: 0.1621 - Val Acc: 0.9130
2026-04-05 05:16:55,609 - INFO - Epoch 76/100 - Train Loss: 0.1685 - Val Acc: 0.9275
2026-04-05 05:16:55,927 - INFO - Epoch 77/100 - Train Loss: 0.1519 - Val Acc: 0.9275
2026-04-05 05:16:56,233 - INFO - Epoch 78/100 - Train Loss: 0.1515 - Val Acc: 0.9130
2026-04-05 05:16:56,546 - INFO - Epoch 79/100 - Train Loss: 0.1379 - Val Acc: 0.9275
2026-04-05 05:16:56,855 - INFO - Epoch 80/100 - Train Loss: 0.1542 - Val Acc: 0.9275
2026-04-05 05:16:57,182 - INFO - Epoch 81/100 - Train Loss: 0.1454 - Val Acc: 0.9275
2026-04-05 05:16:57,500 - INFO - Epoch 82/100 - Train Loss: 0.1430 - Val Acc: 0.9275
2026-04-05 05:16:57,813 - INFO - Epoch 83/100 - Train Loss: 0.1321 - Val Acc: 0.9130
2026-04-05 05:16:58,126 - INFO - Epoch 84/100 - Train Loss: 0.1403 - Val Acc: 0.9130
2026-04-05 05:16:58,442 - INFO - Epoch 85/100 - Train Loss: 0.1369 - Val Acc: 0.9130
2026-04-05 05:16:58,755 - INFO - Epoch 86/100 - Train Loss: 0.1303 - Val Acc: 0.9275
2026-04-05 05:16:59,061 - INFO - Epoch 87/100 - Train Loss: 0.1427 - Val Acc: 0.9275
2026-04-05 05:16:59,379 - INFO - Epoch 88/100 - Train Loss: 0.1541 - Val Acc: 0.8986
2026-04-05 05:16:59,686 - INFO - Epoch 89/100 - Train Loss: 0.1228 - Val Acc: 0.9275
2026-04-05 05:17:00,002 - INFO - Epoch 90/100 - Train Loss: 0.1286 - Val Acc: 0.9275
2026-04-05 05:17:00,313 - INFO - Epoch 91/100 - Train Loss: 0.1266 - Val Acc: 0.9275
2026-04-05 05:17:00,633 - INFO - Epoch 92/100 - Train Loss: 0.1286 - Val Acc: 0.9275
2026-04-05 05:17:00,946 - INFO - Epoch 93/100 - Train Loss: 0.1368 - Val Acc: 0.9130
2026-04-05 05:17:01,255 - INFO - Epoch 94/100 - Train Loss: 0.1523 - Val Acc: 0.8986
2026-04-05 05:17:01,578 - INFO - Epoch 95/100 - Train Loss: 0.1242 - Val Acc: 0.9275
2026-04-05 05:17:01,887 - INFO - Epoch 96/100 - Train Loss: 0.1198 - Val Acc: 0.9130
2026-04-05 05:17:02,193 - INFO - Epoch 97/100 - Train Loss: 0.1338 - Val Acc: 0.9275
2026-04-05 05:17:02,505 - INFO - Epoch 98/100 - Train Loss: 0.1226 - Val Acc: 0.9130
2026-04-05 05:17:02,811 - INFO - Epoch 99/100 - Train Loss: 0.1451 - Val Acc: 0.9275
2026-04-05 05:17:03,117 - INFO - Epoch 100/100 - Train Loss: 0.1307 - Val Acc: 0.9130
2026-04-05 05:17:03,471 - INFO - Fold 3 logically complete. Tensor memory bounds cleared cleanly.
2026-04-05 05:17:03,475 - INFO - Original class distribution: [276 345]
2026-04-05 05:17:03,475 - INFO - Training device bound securely to: cuda

Fold 4:   0%|          | 0/100 [00:00<?, ?it/s]

2026-04-05 05:17:03,802 - INFO - Epoch 1/100 - Train Loss: 0.6000 - Val Acc: 0.8116
2026-04-05 05:17:04,120 - INFO - Epoch 2/100 - Train Loss: 0.4112 - Val Acc: 0.7826
2026-04-05 05:17:04,464 - INFO - Epoch 3/100 - Train Loss: 0.3271 - Val Acc: 0.7971
2026-04-05 05:17:04,807 - INFO - Epoch 4/100 - Train Loss: 0.3045 - Val Acc: 0.8116
2026-04-05 05:17:05,121 - INFO - Epoch 5/100 - Train Loss: 0.3015 - Val Acc: 0.7971
2026-04-05 05:17:05,438 - INFO - Epoch 6/100 - Train Loss: 0.2911 - Val Acc: 0.7971
2026-04-05 05:17:05,754 - INFO - Epoch 7/100 - Train Loss: 0.2792 - Val Acc: 0.7971
2026-04-05 05:17:06,067 - INFO - Epoch 8/100 - Train Loss: 0.2754 - Val Acc: 0.7971
2026-04-05 05:17:06,374 - INFO - Epoch 9/100 - Train Loss: 0.2644 - Val Acc: 0.7971
2026-04-05 05:17:06,685 - INFO - Epoch 10/100 - Train Loss: 0.2717 - Val Acc: 0.7971
2026-04-05 05:17:07,001 - INFO - Epoch 11/100 - Train Loss: 0.2601 - Val Acc: 0.7971
2026-04-05 05:17:07,319 - INFO - Epoch 12/100 - Train Loss: 0.2571 - Val Acc: 0.7971
2026-04-05 05:17:07,653 - INFO - Epoch 13/100 - Train Loss: 0.2660 - Val Acc: 0.7971
2026-04-05 05:17:07,975 - INFO - Epoch 14/100 - Train Loss: 0.2495 - Val Acc: 0.7826
2026-04-05 05:17:08,285 - INFO - Epoch 15/100 - Train Loss: 0.2471 - Val Acc: 0.8116
2026-04-05 05:17:08,597 - INFO - Epoch 16/100 - Train Loss: 0.2389 - Val Acc: 0.7971
2026-04-05 05:17:08,910 - INFO - Epoch 17/100 - Train Loss: 0.2400 - Val Acc: 0.7826
2026-04-05 05:17:09,225 - INFO - Epoch 18/100 - Train Loss: 0.2523 - Val Acc: 0.8116
2026-04-05 05:17:09,549 - INFO - Epoch 19/100 - Train Loss: 0.2230 - Val Acc: 0.7971
2026-04-05 05:17:09,872 - INFO - Epoch 20/100 - Train Loss: 0.2350 - Val Acc: 0.8261
2026-04-05 05:17:10,187 - INFO - Epoch 21/100 - Train Loss: 0.2272 - Val Acc: 0.8116
2026-04-05 05:17:10,503 - INFO - Epoch 22/100 - Train Loss: 0.2141 - Val Acc: 0.8116
2026-04-05 05:17:10,809 - INFO - Epoch 23/100 - Train Loss: 0.2267 - Val Acc: 0.8116
2026-04-05 05:17:11,121 - INFO - Epoch 24/100 - Train Loss: 0.2198 - Val Acc: 0.8116
2026-04-05 05:17:11,443 - INFO - Epoch 25/100 - Train Loss: 0.2201 - Val Acc: 0.7826
2026-04-05 05:17:11,752 - INFO - Epoch 26/100 - Train Loss: 0.2128 - Val Acc: 0.8116
2026-04-05 05:17:12,067 - INFO - Epoch 27/100 - Train Loss: 0.2289 - Val Acc: 0.8261
2026-04-05 05:17:12,385 - INFO - Epoch 28/100 - Train Loss: 0.2073 - Val Acc: 0.7971
2026-04-05 05:17:12,691 - INFO - Epoch 29/100 - Train Loss: 0.1997 - Val Acc: 0.8261
2026-04-05 05:17:13,021 - INFO - Epoch 30/100 - Train Loss: 0.2079 - Val Acc: 0.7971
2026-04-05 05:17:13,349 - INFO - Epoch 31/100 - Train Loss: 0.2059 - Val Acc: 0.8116
2026-04-05 05:17:13,661 - INFO - Epoch 32/100 - Train Loss: 0.1967 - Val Acc: 0.7971
2026-04-05 05:17:13,984 - INFO - Epoch 33/100 - Train Loss: 0.1937 - Val Acc: 0.7826
2026-04-05 05:17:14,330 - INFO - Epoch 34/100 - Train Loss: 0.1918 - Val Acc: 0.8116
2026-04-05 05:17:14,666 - INFO - Epoch 35/100 - Train Loss: 0.1817 - Val Acc: 0.7971
2026-04-05 05:17:14,995 - INFO - Epoch 36/100 - Train Loss: 0.1942 - Val Acc: 0.7971
2026-04-05 05:17:15,320 - INFO - Epoch 37/100 - Train Loss: 0.1741 - Val Acc: 0.7971
2026-04-05 05:17:15,640 - INFO - Epoch 38/100 - Train Loss: 0.1744 - Val Acc: 0.7826
2026-04-05 05:17:15,956 - INFO - Epoch 39/100 - Train Loss: 0.1799 - Val Acc: 0.7971
2026-04-05 05:17:16,265 - INFO - Epoch 40/100 - Train Loss: 0.1844 - Val Acc: 0.8116
2026-04-05 05:17:16,580 - INFO - Epoch 41/100 - Train Loss: 0.1773 - Val Acc: 0.7826
2026-04-05 05:17:16,897 - INFO - Epoch 42/100 - Train Loss: 0.1945 - Val Acc: 0.7971
2026-04-05 05:17:17,214 - INFO - Epoch 43/100 - Train Loss: 0.1807 - Val Acc: 0.7971
2026-04-05 05:17:17,556 - INFO - Epoch 44/100 - Train Loss: 0.1745 - Val Acc: 0.8116
2026-04-05 05:17:17,876 - INFO - Epoch 45/100 - Train Loss: 0.1695 - Val Acc: 0.7971
2026-04-05 05:17:18,201 - INFO - Epoch 46/100 - Train Loss: 0.1828 - Val Acc: 0.7971
2026-04-05 05:17:18,527 - INFO - Epoch 47/100 - Train Loss: 0.1741 - Val Acc: 0.7826
2026-04-05 05:17:18,855 - INFO - Epoch 48/100 - Train Loss: 0.1603 - Val Acc: 0.8116
2026-04-05 05:17:19,182 - INFO - Epoch 49/100 - Train Loss: 0.1561 - Val Acc: 0.8116
2026-04-05 05:17:19,486 - INFO - Epoch 50/100 - Train Loss: 0.1702 - Val Acc: 0.7971
2026-04-05 05:17:19,794 - INFO - Epoch 51/100 - Train Loss: 0.1624 - Val Acc: 0.7971
2026-04-05 05:17:20,110 - INFO - Epoch 52/100 - Train Loss: 0.1437 - Val Acc: 0.7971
2026-04-05 05:17:20,424 - INFO - Epoch 53/100 - Train Loss: 0.1571 - Val Acc: 0.7971
2026-04-05 05:17:20,743 - INFO - Epoch 54/100 - Train Loss: 0.1516 - Val Acc: 0.8116
2026-04-05 05:17:21,049 - INFO - Epoch 55/100 - Train Loss: 0.1522 - Val Acc: 0.7971
2026-04-05 05:17:21,378 - INFO - Epoch 56/100 - Train Loss: 0.1458 - Val Acc: 0.7681
2026-04-05 05:17:21,692 - INFO - Epoch 57/100 - Train Loss: 0.1451 - Val Acc: 0.7681
2026-04-05 05:17:22,008 - INFO - Epoch 58/100 - Train Loss: 0.1465 - Val Acc: 0.8116
2026-04-05 05:17:22,330 - INFO - Epoch 59/100 - Train Loss: 0.1577 - Val Acc: 0.7826
2026-04-05 05:17:22,645 - INFO - Epoch 60/100 - Train Loss: 0.1521 - Val Acc: 0.8116
2026-04-05 05:17:22,966 - INFO - Epoch 61/100 - Train Loss: 0.1470 - Val Acc: 0.7971
2026-04-05 05:17:23,278 - INFO - Epoch 62/100 - Train Loss: 0.1440 - Val Acc: 0.7971
2026-04-05 05:17:23,601 - INFO - Epoch 63/100 - Train Loss: 0.1379 - Val Acc: 0.7971
2026-04-05 05:17:23,936 - INFO - Epoch 64/100 - Train Loss: 0.1422 - Val Acc: 0.7971
2026-04-05 05:17:24,278 - INFO - Epoch 65/100 - Train Loss: 0.1449 - Val Acc: 0.7971
2026-04-05 05:17:24,625 - INFO - Epoch 66/100 - Train Loss: 0.1307 - Val Acc: 0.7826
2026-04-05 05:17:24,940 - INFO - Epoch 67/100 - Train Loss: 0.1393 - Val Acc: 0.7971
2026-04-05 05:17:25,260 - INFO - Epoch 68/100 - Train Loss: 0.1308 - Val Acc: 0.8116
2026-04-05 05:17:25,572 - INFO - Epoch 69/100 - Train Loss: 0.1192 - Val Acc: 0.7971
2026-04-05 05:17:25,879 - INFO - Epoch 70/100 - Train Loss: 0.1377 - Val Acc: 0.7971
2026-04-05 05:17:26,203 - INFO - Epoch 71/100 - Train Loss: 0.1270 - Val Acc: 0.7826
2026-04-05 05:17:26,530 - INFO - Epoch 72/100 - Train Loss: 0.1266 - Val Acc: 0.7971
2026-04-05 05:17:26,853 - INFO - Epoch 73/100 - Train Loss: 0.1347 - Val Acc: 0.7826
2026-04-05 05:17:27,178 - INFO - Epoch 74/100 - Train Loss: 0.1275 - Val Acc: 0.8116
2026-04-05 05:17:27,492 - INFO - Epoch 75/100 - Train Loss: 0.1427 - Val Acc: 0.7971
2026-04-05 05:17:27,826 - INFO - Epoch 76/100 - Train Loss: 0.1239 - Val Acc: 0.8116
2026-04-05 05:17:28,163 - INFO - Epoch 77/100 - Train Loss: 0.1262 - Val Acc: 0.7971
2026-04-05 05:17:28,480 - INFO - Epoch 78/100 - Train Loss: 0.1189 - Val Acc: 0.8261
2026-04-05 05:17:28,796 - INFO - Epoch 79/100 - Train Loss: 0.1222 - Val Acc: 0.7971
2026-04-05 05:17:29,119 - INFO - Epoch 80/100 - Train Loss: 0.1252 - Val Acc: 0.7971
2026-04-05 05:17:29,434 - INFO - Epoch 81/100 - Train Loss: 0.1294 - Val Acc: 0.7826
2026-04-05 05:17:29,753 - INFO - Epoch 82/100 - Train Loss: 0.1143 - Val Acc: 0.7826
2026-04-05 05:17:30,081 - INFO - Epoch 83/100 - Train Loss: 0.1272 - Val Acc: 0.8116
2026-04-05 05:17:30,403 - INFO - Epoch 84/100 - Train Loss: 0.1193 - Val Acc: 0.8116
2026-04-05 05:17:30,739 - INFO - Epoch 85/100 - Train Loss: 0.1147 - Val Acc: 0.8116
2026-04-05 05:17:31,066 - INFO - Epoch 86/100 - Train Loss: 0.1309 - Val Acc: 0.7536
2026-04-05 05:17:31,386 - INFO - Epoch 87/100 - Train Loss: 0.1167 - Val Acc: 0.7826
2026-04-05 05:17:31,713 - INFO - Epoch 88/100 - Train Loss: 0.1101 - Val Acc: 0.8116
2026-04-05 05:17:32,030 - INFO - Epoch 89/100 - Train Loss: 0.1197 - Val Acc: 0.7826
2026-04-05 05:17:32,349 - INFO - Epoch 90/100 - Train Loss: 0.1085 - Val Acc: 0.7826
2026-04-05 05:17:32,655 - INFO - Epoch 91/100 - Train Loss: 0.1223 - Val Acc: 0.8116
2026-04-05 05:17:32,973 - INFO - Epoch 92/100 - Train Loss: 0.1088 - Val Acc: 0.7681
2026-04-05 05:17:33,288 - INFO - Epoch 93/100 - Train Loss: 0.0930 - Val Acc: 0.7681
2026-04-05 05:17:33,608 - INFO - Epoch 94/100 - Train Loss: 0.1159 - Val Acc: 0.7681
2026-04-05 05:17:33,928 - INFO - Epoch 95/100 - Train Loss: 0.1260 - Val Acc: 0.7971
2026-04-05 05:17:34,262 - INFO - Epoch 96/100 - Train Loss: 0.0980 - Val Acc: 0.7826
2026-04-05 05:17:34,597 - INFO - Epoch 97/100 - Train Loss: 0.1098 - Val Acc: 0.7971
2026-04-05 05:17:34,911 - INFO - Epoch 98/100 - Train Loss: 0.1047 - Val Acc: 0.7971
2026-04-05 05:17:35,228 - INFO - Epoch 99/100 - Train Loss: 0.1203 - Val Acc: 0.7826
2026-04-05 05:17:35,554 - INFO - Epoch 100/100 - Train Loss: 0.1015 - Val Acc: 0.8116
2026-04-05 05:17:35,922 - INFO - Fold 4 logically complete. Tensor memory bounds cleared cleanly.
2026-04-05 05:17:35,926 - INFO - Original class distribution: [276 345]
2026-04-05 05:17:35,927 - INFO - Training device bound securely to: cuda

Fold 5:   0%|          | 0/100 [00:00<?, ?it/s]

2026-04-05 05:17:36,266 - INFO - Epoch 1/100 - Train Loss: 0.5935 - Val Acc: 0.8696
2026-04-05 05:17:36,586 - INFO - Epoch 2/100 - Train Loss: 0.4071 - Val Acc: 0.8986
2026-04-05 05:17:36,900 - INFO - Epoch 3/100 - Train Loss: 0.3284 - Val Acc: 0.8986
2026-04-05 05:17:37,219 - INFO - Epoch 4/100 - Train Loss: 0.3224 - Val Acc: 0.8261
2026-04-05 05:17:37,530 - INFO - Epoch 5/100 - Train Loss: 0.3195 - Val Acc: 0.8696
2026-04-05 05:17:37,842 - INFO - Epoch 6/100 - Train Loss: 0.3001 - Val Acc: 0.8696
2026-04-05 05:17:38,155 - INFO - Epoch 7/100 - Train Loss: 0.2873 - Val Acc: 0.8696
2026-04-05 05:17:38,461 - INFO - Epoch 8/100 - Train Loss: 0.2812 - Val Acc: 0.8551
2026-04-05 05:17:38,774 - INFO - Epoch 9/100 - Train Loss: 0.2891 - Val Acc: 0.8551
2026-04-05 05:17:39,090 - INFO - Epoch 10/100 - Train Loss: 0.2809 - Val Acc: 0.8551
2026-04-05 05:17:39,399 - INFO - Epoch 11/100 - Train Loss: 0.2671 - Val Acc: 0.8406
2026-04-05 05:17:39,710 - INFO - Epoch 12/100 - Train Loss: 0.2612 - Val Acc: 0.8406
2026-04-05 05:17:40,025 - INFO - Epoch 13/100 - Train Loss: 0.2640 - Val Acc: 0.8261
2026-04-05 05:17:40,341 - INFO - Epoch 14/100 - Train Loss: 0.2541 - Val Acc: 0.8116
2026-04-05 05:17:40,654 - INFO - Epoch 15/100 - Train Loss: 0.2549 - Val Acc: 0.8116
2026-04-05 05:17:40,971 - INFO - Epoch 16/100 - Train Loss: 0.2520 - Val Acc: 0.8406
2026-04-05 05:17:41,296 - INFO - Epoch 17/100 - Train Loss: 0.2631 - Val Acc: 0.8116
2026-04-05 05:17:41,628 - INFO - Epoch 18/100 - Train Loss: 0.2478 - Val Acc: 0.8116
2026-04-05 05:17:41,962 - INFO - Epoch 19/100 - Train Loss: 0.2382 - Val Acc: 0.8116
2026-04-05 05:17:42,282 - INFO - Epoch 20/100 - Train Loss: 0.2432 - Val Acc: 0.8551
2026-04-05 05:17:42,615 - INFO - Epoch 21/100 - Train Loss: 0.2251 - Val Acc: 0.8261
2026-04-05 05:17:42,933 - INFO - Epoch 22/100 - Train Loss: 0.2427 - Val Acc: 0.8261
2026-04-05 05:17:43,267 - INFO - Epoch 23/100 - Train Loss: 0.2312 - Val Acc: 0.8551
2026-04-05 05:17:43,586 - INFO - Epoch 24/100 - Train Loss: 0.2189 - Val Acc: 0.8551
2026-04-05 05:17:43,897 - INFO - Epoch 25/100 - Train Loss: 0.2230 - Val Acc: 0.8406
2026-04-05 05:17:44,220 - INFO - Epoch 26/100 - Train Loss: 0.2310 - Val Acc: 0.8551
2026-04-05 05:17:44,583 - INFO - Epoch 27/100 - Train Loss: 0.2082 - Val Acc: 0.8551
2026-04-05 05:17:44,908 - INFO - Epoch 28/100 - Train Loss: 0.2168 - Val Acc: 0.8551
2026-04-05 05:17:45,229 - INFO - Epoch 29/100 - Train Loss: 0.2189 - Val Acc: 0.8406
2026-04-05 05:17:45,537 - INFO - Epoch 30/100 - Train Loss: 0.2132 - Val Acc: 0.8261
2026-04-05 05:17:45,853 - INFO - Epoch 31/100 - Train Loss: 0.2198 - Val Acc: 0.8406
2026-04-05 05:17:46,176 - INFO - Epoch 32/100 - Train Loss: 0.2018 - Val Acc: 0.8551
2026-04-05 05:17:46,491 - INFO - Epoch 33/100 - Train Loss: 0.2093 - Val Acc: 0.8406
2026-04-05 05:17:46,808 - INFO - Epoch 34/100 - Train Loss: 0.1887 - Val Acc: 0.8406
2026-04-05 05:17:47,137 - INFO - Epoch 35/100 - Train Loss: 0.2004 - Val Acc: 0.8696
2026-04-05 05:17:47,460 - INFO - Epoch 36/100 - Train Loss: 0.1965 - Val Acc: 0.8116
2026-04-05 05:17:47,788 - INFO - Epoch 37/100 - Train Loss: 0.1996 - Val Acc: 0.8406
2026-04-05 05:17:48,104 - INFO - Epoch 38/100 - Train Loss: 0.1811 - Val Acc: 0.8406
2026-04-05 05:17:48,431 - INFO - Epoch 39/100 - Train Loss: 0.1858 - Val Acc: 0.8406
2026-04-05 05:17:48,747 - INFO - Epoch 40/100 - Train Loss: 0.1944 - Val Acc: 0.8406
2026-04-05 05:17:49,056 - INFO - Epoch 41/100 - Train Loss: 0.1823 - Val Acc: 0.8116
2026-04-05 05:17:49,382 - INFO - Epoch 42/100 - Train Loss: 0.1786 - Val Acc: 0.8116
2026-04-05 05:17:49,698 - INFO - Epoch 43/100 - Train Loss: 0.1920 - Val Acc: 0.8406
2026-04-05 05:17:50,018 - INFO - Epoch 44/100 - Train Loss: 0.1844 - Val Acc: 0.8261
2026-04-05 05:17:50,334 - INFO - Epoch 45/100 - Train Loss: 0.1679 - Val Acc: 0.8551
2026-04-05 05:17:50,648 - INFO - Epoch 46/100 - Train Loss: 0.1765 - Val Acc: 0.8406
2026-04-05 05:17:50,980 - INFO - Epoch 47/100 - Train Loss: 0.1720 - Val Acc: 0.8261
2026-04-05 05:17:51,326 - INFO - Epoch 48/100 - Train Loss: 0.1666 - Val Acc: 0.8261
2026-04-05 05:17:51,655 - INFO - Epoch 49/100 - Train Loss: 0.1777 - Val Acc: 0.8116
2026-04-05 05:17:51,977 - INFO - Epoch 50/100 - Train Loss: 0.1718 - Val Acc: 0.8261
2026-04-05 05:17:52,288 - INFO - Epoch 51/100 - Train Loss: 0.1661 - Val Acc: 0.8261
2026-04-05 05:17:52,601 - INFO - Epoch 52/100 - Train Loss: 0.1733 - Val Acc: 0.8261
2026-04-05 05:17:52,911 - INFO - Epoch 53/100 - Train Loss: 0.1846 - Val Acc: 0.8261
2026-04-05 05:17:53,236 - INFO - Epoch 54/100 - Train Loss: 0.1591 - Val Acc: 0.8261
2026-04-05 05:17:53,553 - INFO - Epoch 55/100 - Train Loss: 0.1607 - Val Acc: 0.8261
2026-04-05 05:17:53,864 - INFO - Epoch 56/100 - Train Loss: 0.1643 - Val Acc: 0.8261
2026-04-05 05:17:54,190 - INFO - Epoch 57/100 - Train Loss: 0.1666 - Val Acc: 0.8261
2026-04-05 05:17:54,514 - INFO - Epoch 58/100 - Train Loss: 0.1636 - Val Acc: 0.8261
2026-04-05 05:17:54,842 - INFO - Epoch 59/100 - Train Loss: 0.1505 - Val Acc: 0.8261
2026-04-05 05:17:55,165 - INFO - Epoch 60/100 - Train Loss: 0.1566 - Val Acc: 0.8261
2026-04-05 05:17:55,474 - INFO - Epoch 61/100 - Train Loss: 0.1520 - Val Acc: 0.8261
2026-04-05 05:17:55,795 - INFO - Epoch 62/100 - Train Loss: 0.1602 - Val Acc: 0.8261
2026-04-05 05:17:56,107 - INFO - Epoch 63/100 - Train Loss: 0.1586 - Val Acc: 0.8116
2026-04-05 05:17:56,441 - INFO - Epoch 64/100 - Train Loss: 0.1394 - Val Acc: 0.8261
2026-04-05 05:17:56,757 - INFO - Epoch 65/100 - Train Loss: 0.1479 - Val Acc: 0.8261
2026-04-05 05:17:57,069 - INFO - Epoch 66/100 - Train Loss: 0.1476 - Val Acc: 0.8261
2026-04-05 05:17:57,380 - INFO - Epoch 67/100 - Train Loss: 0.1478 - Val Acc: 0.8261
2026-04-05 05:17:57,699 - INFO - Epoch 68/100 - Train Loss: 0.1389 - Val Acc: 0.8261
2026-04-05 05:17:58,013 - INFO - Epoch 69/100 - Train Loss: 0.1476 - Val Acc: 0.8261
2026-04-05 05:17:58,318 - INFO - Epoch 70/100 - Train Loss: 0.1482 - Val Acc: 0.7971
2026-04-05 05:17:58,631 - INFO - Epoch 71/100 - Train Loss: 0.1494 - Val Acc: 0.8261
2026-04-05 05:17:58,951 - INFO - Epoch 72/100 - Train Loss: 0.1339 - Val Acc: 0.8261
2026-04-05 05:17:59,261 - INFO - Epoch 73/100 - Train Loss: 0.1402 - Val Acc: 0.8116
2026-04-05 05:17:59,566 - INFO - Epoch 74/100 - Train Loss: 0.1335 - Val Acc: 0.8116
2026-04-05 05:17:59,874 - INFO - Epoch 75/100 - Train Loss: 0.1371 - Val Acc: 0.8116
2026-04-05 05:18:00,190 - INFO - Epoch 76/100 - Train Loss: 0.1393 - Val Acc: 0.7971
2026-04-05 05:18:00,496 - INFO - Epoch 77/100 - Train Loss: 0.1340 - Val Acc: 0.8116
2026-04-05 05:18:00,806 - INFO - Epoch 78/100 - Train Loss: 0.1401 - Val Acc: 0.8116
2026-04-05 05:18:01,114 - INFO - Epoch 79/100 - Train Loss: 0.1357 - Val Acc: 0.8261
2026-04-05 05:18:01,451 - INFO - Epoch 80/100 - Train Loss: 0.1213 - Val Acc: 0.8116
2026-04-05 05:18:01,780 - INFO - Epoch 81/100 - Train Loss: 0.1371 - Val Acc: 0.8261
2026-04-05 05:18:02,096 - INFO - Epoch 82/100 - Train Loss: 0.1168 - Val Acc: 0.8261
2026-04-05 05:18:02,406 - INFO - Epoch 83/100 - Train Loss: 0.1301 - Val Acc: 0.8116
2026-04-05 05:18:02,721 - INFO - Epoch 84/100 - Train Loss: 0.1430 - Val Acc: 0.8116
2026-04-05 05:18:03,036 - INFO - Epoch 85/100 - Train Loss: 0.1499 - Val Acc: 0.8261
2026-04-05 05:18:03,345 - INFO - Epoch 86/100 - Train Loss: 0.1250 - Val Acc: 0.8116
2026-04-05 05:18:03,659 - INFO - Epoch 87/100 - Train Loss: 0.1023 - Val Acc: 0.8116
2026-04-05 05:18:03,963 - INFO - Epoch 88/100 - Train Loss: 0.1079 - Val Acc: 0.8116
2026-04-05 05:18:04,280 - INFO - Epoch 89/100 - Train Loss: 0.1357 - Val Acc: 0.8116
2026-04-05 05:18:04,611 - INFO - Epoch 90/100 - Train Loss: 0.1091 - Val Acc: 0.8406
2026-04-05 05:18:04,932 - INFO - Epoch 91/100 - Train Loss: 0.1322 - Val Acc: 0.8261
2026-04-05 05:18:05,242 - INFO - Epoch 92/100 - Train Loss: 0.1056 - Val Acc: 0.8261
2026-04-05 05:18:05,550 - INFO - Epoch 93/100 - Train Loss: 0.1209 - Val Acc: 0.8116
2026-04-05 05:18:05,870 - INFO - Epoch 94/100 - Train Loss: 0.1280 - Val Acc: 0.8116
2026-04-05 05:18:06,189 - INFO - Epoch 95/100 - Train Loss: 0.1187 - Val Acc: 0.8261
2026-04-05 05:18:06,506 - INFO - Epoch 96/100 - Train Loss: 0.1212 - Val Acc: 0.8261
2026-04-05 05:18:06,822 - INFO - Epoch 97/100 - Train Loss: 0.1141 - Val Acc: 0.8116
2026-04-05 05:18:07,141 - INFO - Epoch 98/100 - Train Loss: 0.1054 - Val Acc: 0.8116
2026-04-05 05:18:07,456 - INFO - Epoch 99/100 - Train Loss: 0.1105 - Val Acc: 0.8116
2026-04-05 05:18:07,769 - INFO - Epoch 100/100 - Train Loss: 0.1030 - Val Acc: 0.8261
2026-04-05 05:18:08,142 - INFO - Fold 5 logically complete. Tensor memory bounds cleared cleanly.
2026-04-05 05:18:08,147 - INFO - Original class distribution: [276 345]
2026-04-05 05:18:08,147 - INFO - Training device bound securely to: cuda

Fold 6:   0%|          | 0/100 [00:00<?, ?it/s]

2026-04-05 05:18:08,483 - INFO - Epoch 1/100 - Train Loss: 0.5974 - Val Acc: 0.8551
2026-04-05 05:18:08,802 - INFO - Epoch 2/100 - Train Loss: 0.4104 - Val Acc: 0.8551
2026-04-05 05:18:09,109 - INFO - Epoch 3/100 - Train Loss: 0.3445 - Val Acc: 0.8841
2026-04-05 05:18:09,430 - INFO - Epoch 4/100 - Train Loss: 0.3321 - Val Acc: 0.8841
2026-04-05 05:18:09,748 - INFO - Epoch 5/100 - Train Loss: 0.3255 - Val Acc: 0.8841
2026-04-05 05:18:10,059 - INFO - Epoch 6/100 - Train Loss: 0.3035 - Val Acc: 0.8696
2026-04-05 05:18:10,371 - INFO - Epoch 7/100 - Train Loss: 0.3067 - Val Acc: 0.8696
2026-04-05 05:18:10,689 - INFO - Epoch 8/100 - Train Loss: 0.2971 - Val Acc: 0.8841
2026-04-05 05:18:10,999 - INFO - Epoch 9/100 - Train Loss: 0.2920 - Val Acc: 0.8696
2026-04-05 05:18:11,325 - INFO - Epoch 10/100 - Train Loss: 0.2878 - Val Acc: 0.8841
2026-04-05 05:18:11,642 - INFO - Epoch 11/100 - Train Loss: 0.2992 - Val Acc: 0.8551
2026-04-05 05:18:11,956 - INFO - Epoch 12/100 - Train Loss: 0.2886 - Val Acc: 0.8696
2026-04-05 05:18:12,270 - INFO - Epoch 13/100 - Train Loss: 0.2671 - Val Acc: 0.8551
2026-04-05 05:18:12,582 - INFO - Epoch 14/100 - Train Loss: 0.2782 - Val Acc: 0.8696
2026-04-05 05:18:12,901 - INFO - Epoch 15/100 - Train Loss: 0.2626 - Val Acc: 0.8696
2026-04-05 05:18:13,227 - INFO - Epoch 16/100 - Train Loss: 0.2573 - Val Acc: 0.8696
2026-04-05 05:18:13,561 - INFO - Epoch 17/100 - Train Loss: 0.2552 - Val Acc: 0.8841
2026-04-05 05:18:13,879 - INFO - Epoch 18/100 - Train Loss: 0.2658 - Val Acc: 0.8696
2026-04-05 05:18:14,235 - INFO - Epoch 19/100 - Train Loss: 0.2559 - Val Acc: 0.8696
2026-04-05 05:18:14,582 - INFO - Epoch 20/100 - Train Loss: 0.2519 - Val Acc: 0.8696
2026-04-05 05:18:14,899 - INFO - Epoch 21/100 - Train Loss: 0.2467 - Val Acc: 0.8696
2026-04-05 05:18:15,211 - INFO - Epoch 22/100 - Train Loss: 0.2511 - Val Acc: 0.8696
2026-04-05 05:18:15,530 - INFO - Epoch 23/100 - Train Loss: 0.2320 - Val Acc: 0.8551
2026-04-05 05:18:15,846 - INFO - Epoch 24/100 - Train Loss: 0.2590 - Val Acc: 0.8551
2026-04-05 05:18:16,164 - INFO - Epoch 25/100 - Train Loss: 0.2332 - Val Acc: 0.8841
2026-04-05 05:18:16,481 - INFO - Epoch 26/100 - Train Loss: 0.2403 - Val Acc: 0.8406
2026-04-05 05:18:16,805 - INFO - Epoch 27/100 - Train Loss: 0.2354 - Val Acc: 0.8406
2026-04-05 05:18:17,118 - INFO - Epoch 28/100 - Train Loss: 0.2318 - Val Acc: 0.8406
2026-04-05 05:18:17,425 - INFO - Epoch 29/100 - Train Loss: 0.2488 - Val Acc: 0.8551
2026-04-05 05:18:17,748 - INFO - Epoch 30/100 - Train Loss: 0.2323 - Val Acc: 0.8406
2026-04-05 05:18:18,084 - INFO - Epoch 31/100 - Train Loss: 0.2357 - Val Acc: 0.8261
2026-04-05 05:18:18,413 - INFO - Epoch 32/100 - Train Loss: 0.2142 - Val Acc: 0.8406
2026-04-05 05:18:18,725 - INFO - Epoch 33/100 - Train Loss: 0.2200 - Val Acc: 0.8551
2026-04-05 05:18:19,036 - INFO - Epoch 34/100 - Train Loss: 0.2129 - Val Acc: 0.8696
2026-04-05 05:18:19,356 - INFO - Epoch 35/100 - Train Loss: 0.2224 - Val Acc: 0.8841
2026-04-05 05:18:19,670 - INFO - Epoch 36/100 - Train Loss: 0.2172 - Val Acc: 0.8551
2026-04-05 05:18:19,988 - INFO - Epoch 37/100 - Train Loss: 0.2096 - Val Acc: 0.8551
2026-04-05 05:18:20,299 - INFO - Epoch 38/100 - Train Loss: 0.2296 - Val Acc: 0.8696
2026-04-05 05:18:20,616 - INFO - Epoch 39/100 - Train Loss: 0.1993 - Val Acc: 0.8406
2026-04-05 05:18:20,928 - INFO - Epoch 40/100 - Train Loss: 0.2127 - Val Acc: 0.8696
2026-04-05 05:18:21,244 - INFO - Epoch 41/100 - Train Loss: 0.2053 - Val Acc: 0.8551
2026-04-05 05:18:21,570 - INFO - Epoch 42/100 - Train Loss: 0.2049 - Val Acc: 0.8696
2026-04-05 05:18:21,893 - INFO - Epoch 43/100 - Train Loss: 0.2082 - Val Acc: 0.8551
2026-04-05 05:18:22,215 - INFO - Epoch 44/100 - Train Loss: 0.2148 - Val Acc: 0.8551
2026-04-05 05:18:22,525 - INFO - Epoch 45/100 - Train Loss: 0.2053 - Val Acc: 0.8406
2026-04-05 05:18:22,846 - INFO - Epoch 46/100 - Train Loss: 0.1976 - Val Acc: 0.8551
2026-04-05 05:18:23,167 - INFO - Epoch 47/100 - Train Loss: 0.1797 - Val Acc: 0.8406
2026-04-05 05:18:23,491 - INFO - Epoch 48/100 - Train Loss: 0.1946 - Val Acc: 0.8551
2026-04-05 05:18:23,811 - INFO - Epoch 49/100 - Train Loss: 0.1929 - Val Acc: 0.8696
2026-04-05 05:18:24,132 - INFO - Epoch 50/100 - Train Loss: 0.1799 - Val Acc: 0.8551
2026-04-05 05:18:24,477 - INFO - Epoch 51/100 - Train Loss: 0.1934 - Val Acc: 0.8551
2026-04-05 05:18:24,828 - INFO - Epoch 52/100 - Train Loss: 0.2016 - Val Acc: 0.8406
2026-04-05 05:18:25,151 - INFO - Epoch 53/100 - Train Loss: 0.1795 - Val Acc: 0.8551
2026-04-05 05:18:25,463 - INFO - Epoch 54/100 - Train Loss: 0.1801 - Val Acc: 0.8551
2026-04-05 05:18:25,777 - INFO - Epoch 55/100 - Train Loss: 0.1866 - Val Acc: 0.8551
2026-04-05 05:18:26,087 - INFO - Epoch 56/100 - Train Loss: 0.1741 - Val Acc: 0.8551
2026-04-05 05:18:26,408 - INFO - Epoch 57/100 - Train Loss: 0.1752 - Val Acc: 0.8551
2026-04-05 05:18:26,714 - INFO - Epoch 58/100 - Train Loss: 0.1694 - Val Acc: 0.8551
2026-04-05 05:18:27,030 - INFO - Epoch 59/100 - Train Loss: 0.1753 - Val Acc: 0.8406
2026-04-05 05:18:27,340 - INFO - Epoch 60/100 - Train Loss: 0.1522 - Val Acc: 0.8406
2026-04-05 05:18:27,659 - INFO - Epoch 61/100 - Train Loss: 0.1773 - Val Acc: 0.8261
2026-04-05 05:18:27,992 - INFO - Epoch 62/100 - Train Loss: 0.1721 - Val Acc: 0.8551
2026-04-05 05:18:28,305 - INFO - Epoch 63/100 - Train Loss: 0.1709 - Val Acc: 0.8406
2026-04-05 05:18:28,629 - INFO - Epoch 64/100 - Train Loss: 0.1758 - Val Acc: 0.8406
2026-04-05 05:18:28,943 - INFO - Epoch 65/100 - Train Loss: 0.1647 - Val Acc: 0.8551
2026-04-05 05:18:29,246 - INFO - Epoch 66/100 - Train Loss: 0.1628 - Val Acc: 0.8551
2026-04-05 05:18:29,562 - INFO - Epoch 67/100 - Train Loss: 0.1632 - Val Acc: 0.8551
2026-04-05 05:18:29,873 - INFO - Epoch 68/100 - Train Loss: 0.1680 - Val Acc: 0.8406
2026-04-05 05:18:30,177 - INFO - Epoch 69/100 - Train Loss: 0.1647 - Val Acc: 0.8261
2026-04-05 05:18:30,495 - INFO - Epoch 70/100 - Train Loss: 0.1489 - Val Acc: 0.8551
2026-04-05 05:18:30,804 - INFO - Epoch 71/100 - Train Loss: 0.1548 - Val Acc: 0.8551
2026-04-05 05:18:31,115 - INFO - Epoch 72/100 - Train Loss: 0.1339 - Val Acc: 0.8551
2026-04-05 05:18:31,426 - INFO - Epoch 73/100 - Train Loss: 0.1671 - Val Acc: 0.8551
2026-04-05 05:18:31,754 - INFO - Epoch 74/100 - Train Loss: 0.1516 - Val Acc: 0.8406
2026-04-05 05:18:32,068 - INFO - Epoch 75/100 - Train Loss: 0.1736 - Val Acc: 0.8406
2026-04-05 05:18:32,374 - INFO - Epoch 76/100 - Train Loss: 0.1520 - Val Acc: 0.8261
2026-04-05 05:18:32,690 - INFO - Epoch 77/100 - Train Loss: 0.1467 - Val Acc: 0.8551
2026-04-05 05:18:33,008 - INFO - Epoch 78/100 - Train Loss: 0.1584 - Val Acc: 0.8551
2026-04-05 05:18:33,317 - INFO - Epoch 79/100 - Train Loss: 0.1321 - Val Acc: 0.8696
2026-04-05 05:18:33,625 - INFO - Epoch 80/100 - Train Loss: 0.1364 - Val Acc: 0.8261
2026-04-05 05:18:33,946 - INFO - Epoch 81/100 - Train Loss: 0.1466 - Val Acc: 0.8696
2026-04-05 05:18:34,268 - INFO - Epoch 82/100 - Train Loss: 0.1355 - Val Acc: 0.8551
2026-04-05 05:18:34,625 - INFO - Epoch 83/100 - Train Loss: 0.1436 - Val Acc: 0.8406
2026-04-05 05:18:34,938 - INFO - Epoch 84/100 - Train Loss: 0.1461 - Val Acc: 0.8551
2026-04-05 05:18:35,251 - INFO - Epoch 85/100 - Train Loss: 0.1302 - Val Acc: 0.8551
2026-04-05 05:18:35,565 - INFO - Epoch 86/100 - Train Loss: 0.1364 - Val Acc: 0.8406
2026-04-05 05:18:35,882 - INFO - Epoch 87/100 - Train Loss: 0.1277 - Val Acc: 0.8551
2026-04-05 05:18:36,201 - INFO - Epoch 88/100 - Train Loss: 0.1254 - Val Acc: 0.8406
2026-04-05 05:18:36,526 - INFO - Epoch 89/100 - Train Loss: 0.1436 - Val Acc: 0.8696
2026-04-05 05:18:36,847 - INFO - Epoch 90/100 - Train Loss: 0.1329 - Val Acc: 0.8406
2026-04-05 05:18:37,154 - INFO - Epoch 91/100 - Train Loss: 0.1406 - Val Acc: 0.8696
2026-04-05 05:18:37,461 - INFO - Epoch 92/100 - Train Loss: 0.1328 - Val Acc: 0.8696
2026-04-05 05:18:37,774 - INFO - Epoch 93/100 - Train Loss: 0.1214 - Val Acc: 0.8551
2026-04-05 05:18:38,091 - INFO - Epoch 94/100 - Train Loss: 0.1338 - Val Acc: 0.8551
2026-04-05 05:18:38,411 - INFO - Epoch 95/100 - Train Loss: 0.1225 - Val Acc: 0.8261
2026-04-05 05:18:38,730 - INFO - Epoch 96/100 - Train Loss: 0.1408 - Val Acc: 0.8696
2026-04-05 05:18:39,044 - INFO - Epoch 97/100 - Train Loss: 0.1336 - Val Acc: 0.8551
2026-04-05 05:18:39,354 - INFO - Epoch 98/100 - Train Loss: 0.1235 - Val Acc: 0.8551
2026-04-05 05:18:39,671 - INFO - Epoch 99/100 - Train Loss: 0.1164 - Val Acc: 0.8696
2026-04-05 05:18:39,981 - INFO - Epoch 100/100 - Train Loss: 0.1075 - Val Acc: 0.8696
2026-04-05 05:18:40,330 - INFO - Fold 6 logically complete. Tensor memory bounds cleared cleanly.
2026-04-05 05:18:40,335 - INFO - Original class distribution: [276 345]
2026-04-05 05:18:40,335 - INFO - Training device bound securely to: cuda

Fold 7:   0%|          | 0/100 [00:00<?, ?it/s]

2026-04-05 05:18:40,660 - INFO - Epoch 1/100 - Train Loss: 0.6088 - Val Acc: 0.7536
2026-04-05 05:18:40,971 - INFO - Epoch 2/100 - Train Loss: 0.4417 - Val Acc: 0.7536
2026-04-05 05:18:41,291 - INFO - Epoch 3/100 - Train Loss: 0.3507 - Val Acc: 0.7536
2026-04-05 05:18:41,597 - INFO - Epoch 4/100 - Train Loss: 0.3120 - Val Acc: 0.7971
2026-04-05 05:18:41,907 - INFO - Epoch 5/100 - Train Loss: 0.2936 - Val Acc: 0.7971
2026-04-05 05:18:42,226 - INFO - Epoch 6/100 - Train Loss: 0.2926 - Val Acc: 0.7971
2026-04-05 05:18:42,539 - INFO - Epoch 7/100 - Train Loss: 0.2746 - Val Acc: 0.7971
2026-04-05 05:18:42,846 - INFO - Epoch 8/100 - Train Loss: 0.2748 - Val Acc: 0.7826
2026-04-05 05:18:43,155 - INFO - Epoch 9/100 - Train Loss: 0.2847 - Val Acc: 0.7826
2026-04-05 05:18:43,465 - INFO - Epoch 10/100 - Train Loss: 0.2639 - Val Acc: 0.7971
2026-04-05 05:18:43,770 - INFO - Epoch 11/100 - Train Loss: 0.2538 - Val Acc: 0.7971
2026-04-05 05:18:44,082 - INFO - Epoch 12/100 - Train Loss: 0.2594 - Val Acc: 0.7681
2026-04-05 05:18:44,418 - INFO - Epoch 13/100 - Train Loss: 0.2455 - Val Acc: 0.7826
2026-04-05 05:18:44,763 - INFO - Epoch 14/100 - Train Loss: 0.2440 - Val Acc: 0.7826
2026-04-05 05:18:45,078 - INFO - Epoch 15/100 - Train Loss: 0.2509 - Val Acc: 0.7971
2026-04-05 05:18:45,384 - INFO - Epoch 16/100 - Train Loss: 0.2367 - Val Acc: 0.7681
2026-04-05 05:18:45,705 - INFO - Epoch 17/100 - Train Loss: 0.2435 - Val Acc: 0.7681
2026-04-05 05:18:46,008 - INFO - Epoch 18/100 - Train Loss: 0.2217 - Val Acc: 0.7826
2026-04-05 05:18:46,319 - INFO - Epoch 19/100 - Train Loss: 0.2240 - Val Acc: 0.7681
2026-04-05 05:18:46,624 - INFO - Epoch 20/100 - Train Loss: 0.2244 - Val Acc: 0.7681
2026-04-05 05:18:46,934 - INFO - Epoch 21/100 - Train Loss: 0.2371 - Val Acc: 0.7536
2026-04-05 05:18:47,244 - INFO - Epoch 22/100 - Train Loss: 0.2193 - Val Acc: 0.7681
2026-04-05 05:18:47,552 - INFO - Epoch 23/100 - Train Loss: 0.2181 - Val Acc: 0.7681
2026-04-05 05:18:47,865 - INFO - Epoch 24/100 - Train Loss: 0.2057 - Val Acc: 0.7681
2026-04-05 05:18:48,181 - INFO - Epoch 25/100 - Train Loss: 0.2110 - Val Acc: 0.7536
2026-04-05 05:18:48,501 - INFO - Epoch 26/100 - Train Loss: 0.2058 - Val Acc: 0.7681
2026-04-05 05:18:48,826 - INFO - Epoch 27/100 - Train Loss: 0.2092 - Val Acc: 0.7681
2026-04-05 05:18:49,136 - INFO - Epoch 28/100 - Train Loss: 0.2041 - Val Acc: 0.7536
2026-04-05 05:18:49,448 - INFO - Epoch 29/100 - Train Loss: 0.2075 - Val Acc: 0.7681
2026-04-05 05:18:49,752 - INFO - Epoch 30/100 - Train Loss: 0.2065 - Val Acc: 0.7681
2026-04-05 05:18:50,067 - INFO - Epoch 31/100 - Train Loss: 0.1960 - Val Acc: 0.7681
2026-04-05 05:18:50,383 - INFO - Epoch 32/100 - Train Loss: 0.1905 - Val Acc: 0.7681
2026-04-05 05:18:50,701 - INFO - Epoch 33/100 - Train Loss: 0.1991 - Val Acc: 0.7681
2026-04-05 05:18:51,035 - INFO - Epoch 34/100 - Train Loss: 0.1948 - Val Acc: 0.7681
2026-04-05 05:18:51,370 - INFO - Epoch 35/100 - Train Loss: 0.1984 - Val Acc: 0.7681
2026-04-05 05:18:51,680 - INFO - Epoch 36/100 - Train Loss: 0.1874 - Val Acc: 0.7681
2026-04-05 05:18:51,994 - INFO - Epoch 37/100 - Train Loss: 0.1822 - Val Acc: 0.7826
2026-04-05 05:18:52,304 - INFO - Epoch 38/100 - Train Loss: 0.1947 - Val Acc: 0.7681
2026-04-05 05:18:52,617 - INFO - Epoch 39/100 - Train Loss: 0.1981 - Val Acc: 0.7681
2026-04-05 05:18:52,935 - INFO - Epoch 40/100 - Train Loss: 0.1879 - Val Acc: 0.7826
2026-04-05 05:18:53,248 - INFO - Epoch 41/100 - Train Loss: 0.1870 - Val Acc: 0.7826
2026-04-05 05:18:53,556 - INFO - Epoch 42/100 - Train Loss: 0.1953 - Val Acc: 0.7826
2026-04-05 05:18:53,861 - INFO - Epoch 43/100 - Train Loss: 0.1885 - Val Acc: 0.7826
2026-04-05 05:18:54,187 - INFO - Epoch 44/100 - Train Loss: 0.1775 - Val Acc: 0.7826
2026-04-05 05:18:54,517 - INFO - Epoch 45/100 - Train Loss: 0.1739 - Val Acc: 0.7826
2026-04-05 05:18:54,851 - INFO - Epoch 46/100 - Train Loss: 0.1880 - Val Acc: 0.7826
2026-04-05 05:18:55,159 - INFO - Epoch 47/100 - Train Loss: 0.1714 - Val Acc: 0.7826
2026-04-05 05:18:55,472 - INFO - Epoch 48/100 - Train Loss: 0.1857 - Val Acc: 0.7826
2026-04-05 05:18:55,796 - INFO - Epoch 49/100 - Train Loss: 0.1696 - Val Acc: 0.7826
2026-04-05 05:18:56,113 - INFO - Epoch 50/100 - Train Loss: 0.1688 - Val Acc: 0.7826
2026-04-05 05:18:56,442 - INFO - Epoch 51/100 - Train Loss: 0.1862 - Val Acc: 0.7826
2026-04-05 05:18:56,760 - INFO - Epoch 52/100 - Train Loss: 0.1742 - Val Acc: 0.7971
2026-04-05 05:18:57,083 - INFO - Epoch 53/100 - Train Loss: 0.1723 - Val Acc: 0.7826
2026-04-05 05:18:57,402 - INFO - Epoch 54/100 - Train Loss: 0.1631 - Val Acc: 0.7826
2026-04-05 05:18:57,738 - INFO - Epoch 55/100 - Train Loss: 0.1727 - Val Acc: 0.7826
2026-04-05 05:18:58,061 - INFO - Epoch 56/100 - Train Loss: 0.1551 - Val Acc: 0.7826
2026-04-05 05:18:58,379 - INFO - Epoch 57/100 - Train Loss: 0.1830 - Val Acc: 0.7681
2026-04-05 05:18:58,688 - INFO - Epoch 58/100 - Train Loss: 0.1587 - Val Acc: 0.7826
2026-04-05 05:18:59,008 - INFO - Epoch 59/100 - Train Loss: 0.1549 - Val Acc: 0.7681
2026-04-05 05:18:59,329 - INFO - Epoch 60/100 - Train Loss: 0.1625 - Val Acc: 0.7681
2026-04-05 05:18:59,647 - INFO - Epoch 61/100 - Train Loss: 0.1547 - Val Acc: 0.7681
2026-04-05 05:18:59,967 - INFO - Epoch 62/100 - Train Loss: 0.1576 - Val Acc: 0.7681
2026-04-05 05:19:00,273 - INFO - Epoch 63/100 - Train Loss: 0.1694 - Val Acc: 0.7971
2026-04-05 05:19:00,587 - INFO - Epoch 64/100 - Train Loss: 0.1519 - Val Acc: 0.7681
2026-04-05 05:19:00,912 - INFO - Epoch 65/100 - Train Loss: 0.1363 - Val Acc: 0.7681
2026-04-05 05:19:01,226 - INFO - Epoch 66/100 - Train Loss: 0.1341 - Val Acc: 0.7681
2026-04-05 05:19:01,547 - INFO - Epoch 67/100 - Train Loss: 0.1607 - Val Acc: 0.7826
2026-04-05 05:19:01,865 - INFO - Epoch 68/100 - Train Loss: 0.1374 - Val Acc: 0.7826
2026-04-05 05:19:02,188 - INFO - Epoch 69/100 - Train Loss: 0.1605 - Val Acc: 0.7826
2026-04-05 05:19:02,508 - INFO - Epoch 70/100 - Train Loss: 0.1537 - Val Acc: 0.7826
2026-04-05 05:19:02,822 - INFO - Epoch 71/100 - Train Loss: 0.1560 - Val Acc: 0.7681
2026-04-05 05:19:03,131 - INFO - Epoch 72/100 - Train Loss: 0.1530 - Val Acc: 0.7681
2026-04-05 05:19:03,441 - INFO - Epoch 73/100 - Train Loss: 0.1390 - Val Acc: 0.7681
2026-04-05 05:19:03,755 - INFO - Epoch 74/100 - Train Loss: 0.1496 - Val Acc: 0.7681
2026-04-05 05:19:04,089 - INFO - Epoch 75/100 - Train Loss: 0.1368 - Val Acc: 0.7681
2026-04-05 05:19:04,437 - INFO - Epoch 76/100 - Train Loss: 0.1320 - Val Acc: 0.7681
2026-04-05 05:19:04,779 - INFO - Epoch 77/100 - Train Loss: 0.1313 - Val Acc: 0.7826
2026-04-05 05:19:05,096 - INFO - Epoch 78/100 - Train Loss: 0.1370 - Val Acc: 0.7971
2026-04-05 05:19:05,437 - INFO - Epoch 79/100 - Train Loss: 0.1221 - Val Acc: 0.7826
2026-04-05 05:19:05,746 - INFO - Epoch 80/100 - Train Loss: 0.1368 - Val Acc: 0.7681
2026-04-05 05:19:06,055 - INFO - Epoch 81/100 - Train Loss: 0.1412 - Val Acc: 0.7826
2026-04-05 05:19:06,368 - INFO - Epoch 82/100 - Train Loss: 0.1311 - Val Acc: 0.7681
2026-04-05 05:19:06,684 - INFO - Epoch 83/100 - Train Loss: 0.1401 - Val Acc: 0.7826
2026-04-05 05:19:07,010 - INFO - Epoch 84/100 - Train Loss: 0.1329 - Val Acc: 0.7826
2026-04-05 05:19:07,318 - INFO - Epoch 85/100 - Train Loss: 0.1227 - Val Acc: 0.7971
2026-04-05 05:19:07,629 - INFO - Epoch 86/100 - Train Loss: 0.1198 - Val Acc: 0.7971
2026-04-05 05:19:07,951 - INFO - Epoch 87/100 - Train Loss: 0.1137 - Val Acc: 0.7826
2026-04-05 05:19:08,257 - INFO - Epoch 88/100 - Train Loss: 0.1273 - Val Acc: 0.7971
2026-04-05 05:19:08,564 - INFO - Epoch 89/100 - Train Loss: 0.1232 - Val Acc: 0.7971
2026-04-05 05:19:08,880 - INFO - Epoch 90/100 - Train Loss: 0.1270 - Val Acc: 0.7826
2026-04-05 05:19:09,197 - INFO - Epoch 91/100 - Train Loss: 0.1206 - Val Acc: 0.7971
2026-04-05 05:19:09,523 - INFO - Epoch 92/100 - Train Loss: 0.1159 - Val Acc: 0.7826
2026-04-05 05:19:09,851 - INFO - Epoch 93/100 - Train Loss: 0.1216 - Val Acc: 0.7681
2026-04-05 05:19:10,170 - INFO - Epoch 94/100 - Train Loss: 0.1234 - Val Acc: 0.7971
2026-04-05 05:19:10,488 - INFO - Epoch 95/100 - Train Loss: 0.1098 - Val Acc: 0.7826
2026-04-05 05:19:10,802 - INFO - Epoch 96/100 - Train Loss: 0.1105 - Val Acc: 0.7826
2026-04-05 05:19:11,120 - INFO - Epoch 97/100 - Train Loss: 0.1073 - Val Acc: 0.7826
2026-04-05 05:19:11,445 - INFO - Epoch 98/100 - Train Loss: 0.1234 - Val Acc: 0.7826
2026-04-05 05:19:11,756 - INFO - Epoch 99/100 - Train Loss: 0.1210 - Val Acc: 0.7826
2026-04-05 05:19:12,064 - INFO - Epoch 100/100 - Train Loss: 0.1106 - Val Acc: 0.7826
2026-04-05 05:19:12,428 - INFO - Fold 7 logically complete. Tensor memory bounds cleared cleanly.
2026-04-05 05:19:12,432 - INFO - Original class distribution: [276 345]
2026-04-05 05:19:12,432 - INFO - Training device bound securely to: cuda

Fold 8:   0%|          | 0/100 [00:00<?, ?it/s]

2026-04-05 05:19:12,770 - INFO - Epoch 1/100 - Train Loss: 0.6247 - Val Acc: 0.8406
2026-04-05 05:19:13,084 - INFO - Epoch 2/100 - Train Loss: 0.4686 - Val Acc: 0.8406
2026-04-05 05:19:13,396 - INFO - Epoch 3/100 - Train Loss: 0.3588 - Val Acc: 0.8406
2026-04-05 05:19:13,711 - INFO - Epoch 4/100 - Train Loss: 0.3400 - Val Acc: 0.8261
2026-04-05 05:19:14,026 - INFO - Epoch 5/100 - Train Loss: 0.3062 - Val Acc: 0.8406
2026-04-05 05:19:14,363 - INFO - Epoch 6/100 - Train Loss: 0.3001 - Val Acc: 0.8261
2026-04-05 05:19:14,699 - INFO - Epoch 7/100 - Train Loss: 0.2983 - Val Acc: 0.8261
2026-04-05 05:19:15,016 - INFO - Epoch 8/100 - Train Loss: 0.2788 - Val Acc: 0.8261
2026-04-05 05:19:15,346 - INFO - Epoch 9/100 - Train Loss: 0.2819 - Val Acc: 0.8261
2026-04-05 05:19:15,665 - INFO - Epoch 10/100 - Train Loss: 0.2864 - Val Acc: 0.8116
2026-04-05 05:19:15,973 - INFO - Epoch 11/100 - Train Loss: 0.2810 - Val Acc: 0.8406
2026-04-05 05:19:16,297 - INFO - Epoch 12/100 - Train Loss: 0.2713 - Val Acc: 0.8261
2026-04-05 05:19:16,610 - INFO - Epoch 13/100 - Train Loss: 0.2740 - Val Acc: 0.8261
2026-04-05 05:19:16,923 - INFO - Epoch 14/100 - Train Loss: 0.2845 - Val Acc: 0.8261
2026-04-05 05:19:17,240 - INFO - Epoch 15/100 - Train Loss: 0.2728 - Val Acc: 0.8261
2026-04-05 05:19:17,558 - INFO - Epoch 16/100 - Train Loss: 0.2676 - Val Acc: 0.8261
2026-04-05 05:19:17,870 - INFO - Epoch 17/100 - Train Loss: 0.2638 - Val Acc: 0.8261
2026-04-05 05:19:18,184 - INFO - Epoch 18/100 - Train Loss: 0.2421 - Val Acc: 0.8406
2026-04-05 05:19:18,498 - INFO - Epoch 19/100 - Train Loss: 0.2525 - Val Acc: 0.8261
2026-04-05 05:19:18,828 - INFO - Epoch 20/100 - Train Loss: 0.2612 - Val Acc: 0.8406
2026-04-05 05:19:19,136 - INFO - Epoch 21/100 - Train Loss: 0.2489 - Val Acc: 0.8406
2026-04-05 05:19:19,462 - INFO - Epoch 22/100 - Train Loss: 0.2379 - Val Acc: 0.8406
2026-04-05 05:19:19,773 - INFO - Epoch 23/100 - Train Loss: 0.2445 - Val Acc: 0.8261
2026-04-05 05:19:20,087 - INFO - Epoch 24/100 - Train Loss: 0.2468 - Val Acc: 0.8261
2026-04-05 05:19:20,398 - INFO - Epoch 25/100 - Train Loss: 0.2215 - Val Acc: 0.8406
2026-04-05 05:19:20,707 - INFO - Epoch 26/100 - Train Loss: 0.2327 - Val Acc: 0.8406
2026-04-05 05:19:21,016 - INFO - Epoch 27/100 - Train Loss: 0.2187 - Val Acc: 0.8406
2026-04-05 05:19:21,330 - INFO - Epoch 28/100 - Train Loss: 0.2365 - Val Acc: 0.8406
2026-04-05 05:19:21,653 - INFO - Epoch 29/100 - Train Loss: 0.2275 - Val Acc: 0.8406
2026-04-05 05:19:21,969 - INFO - Epoch 30/100 - Train Loss: 0.2291 - Val Acc: 0.8406
2026-04-05 05:19:22,280 - INFO - Epoch 31/100 - Train Loss: 0.2276 - Val Acc: 0.8406
2026-04-05 05:19:22,589 - INFO - Epoch 32/100 - Train Loss: 0.2137 - Val Acc: 0.8406
2026-04-05 05:19:22,902 - INFO - Epoch 33/100 - Train Loss: 0.2163 - Val Acc: 0.8406
2026-04-05 05:19:23,212 - INFO - Epoch 34/100 - Train Loss: 0.2147 - Val Acc: 0.8406
2026-04-05 05:19:23,531 - INFO - Epoch 35/100 - Train Loss: 0.2137 - Val Acc: 0.8406
2026-04-05 05:19:23,841 - INFO - Epoch 36/100 - Train Loss: 0.2188 - Val Acc: 0.8406
2026-04-05 05:19:24,155 - INFO - Epoch 37/100 - Train Loss: 0.2209 - Val Acc: 0.8551
2026-04-05 05:19:24,495 - INFO - Epoch 38/100 - Train Loss: 0.1934 - Val Acc: 0.8551
2026-04-05 05:19:24,841 - INFO - Epoch 39/100 - Train Loss: 0.2128 - Val Acc: 0.8261
2026-04-05 05:19:25,152 - INFO - Epoch 40/100 - Train Loss: 0.2135 - Val Acc: 0.8551
2026-04-05 05:19:25,466 - INFO - Epoch 41/100 - Train Loss: 0.2126 - Val Acc: 0.8406
2026-04-05 05:19:25,780 - INFO - Epoch 42/100 - Train Loss: 0.2039 - Val Acc: 0.8406
2026-04-05 05:19:26,089 - INFO - Epoch 43/100 - Train Loss: 0.1873 - Val Acc: 0.8406
2026-04-05 05:19:26,392 - INFO - Epoch 44/100 - Train Loss: 0.2023 - Val Acc: 0.8261
2026-04-05 05:19:26,704 - INFO - Epoch 45/100 - Train Loss: 0.2003 - Val Acc: 0.8551
2026-04-05 05:19:27,014 - INFO - Epoch 46/100 - Train Loss: 0.2039 - Val Acc: 0.8406
2026-04-05 05:19:27,318 - INFO - Epoch 47/100 - Train Loss: 0.1985 - Val Acc: 0.8406
2026-04-05 05:19:27,628 - INFO - Epoch 48/100 - Train Loss: 0.1871 - Val Acc: 0.8551
2026-04-05 05:19:27,944 - INFO - Epoch 49/100 - Train Loss: 0.1960 - Val Acc: 0.8406
2026-04-05 05:19:28,248 - INFO - Epoch 50/100 - Train Loss: 0.1944 - Val Acc: 0.8261
2026-04-05 05:19:28,557 - INFO - Epoch 51/100 - Train Loss: 0.1891 - Val Acc: 0.8406
2026-04-05 05:19:28,880 - INFO - Epoch 52/100 - Train Loss: 0.1672 - Val Acc: 0.8696
2026-04-05 05:19:29,196 - INFO - Epoch 53/100 - Train Loss: 0.1905 - Val Acc: 0.8406
2026-04-05 05:19:29,510 - INFO - Epoch 54/100 - Train Loss: 0.1808 - Val Acc: 0.8551
2026-04-05 05:19:29,837 - INFO - Epoch 55/100 - Train Loss: 0.1798 - Val Acc: 0.8551
2026-04-05 05:19:30,144 - INFO - Epoch 56/100 - Train Loss: 0.1726 - Val Acc: 0.8696
2026-04-05 05:19:30,466 - INFO - Epoch 57/100 - Train Loss: 0.1776 - Val Acc: 0.8551
2026-04-05 05:19:30,783 - INFO - Epoch 58/100 - Train Loss: 0.1895 - Val Acc: 0.8261
2026-04-05 05:19:31,097 - INFO - Epoch 59/100 - Train Loss: 0.1686 - Val Acc: 0.8406
2026-04-05 05:19:31,409 - INFO - Epoch 60/100 - Train Loss: 0.1829 - Val Acc: 0.8406
2026-04-05 05:19:31,721 - INFO - Epoch 61/100 - Train Loss: 0.1921 - Val Acc: 0.8551
2026-04-05 05:19:32,024 - INFO - Epoch 62/100 - Train Loss: 0.1680 - Val Acc: 0.8551
2026-04-05 05:19:32,355 - INFO - Epoch 63/100 - Train Loss: 0.1673 - Val Acc: 0.8551
2026-04-05 05:19:32,675 - INFO - Epoch 64/100 - Train Loss: 0.1633 - Val Acc: 0.8406
2026-04-05 05:19:32,992 - INFO - Epoch 65/100 - Train Loss: 0.1692 - Val Acc: 0.8406
2026-04-05 05:19:33,305 - INFO - Epoch 66/100 - Train Loss: 0.1638 - Val Acc: 0.8551
2026-04-05 05:19:33,625 - INFO - Epoch 67/100 - Train Loss: 0.1698 - Val Acc: 0.8551
2026-04-05 05:19:33,941 - INFO - Epoch 68/100 - Train Loss: 0.1690 - Val Acc: 0.8551
2026-04-05 05:19:34,270 - INFO - Epoch 69/100 - Train Loss: 0.1677 - Val Acc: 0.8551
2026-04-05 05:19:34,610 - INFO - Epoch 70/100 - Train Loss: 0.1555 - Val Acc: 0.8551
2026-04-05 05:19:34,931 - INFO - Epoch 71/100 - Train Loss: 0.1581 - Val Acc: 0.8406
2026-04-05 05:19:35,242 - INFO - Epoch 72/100 - Train Loss: 0.1574 - Val Acc: 0.8406
2026-04-05 05:19:35,550 - INFO - Epoch 73/100 - Train Loss: 0.1666 - Val Acc: 0.8551
2026-04-05 05:19:35,865 - INFO - Epoch 74/100 - Train Loss: 0.1575 - Val Acc: 0.8551
2026-04-05 05:19:36,176 - INFO - Epoch 75/100 - Train Loss: 0.1614 - Val Acc: 0.8551
2026-04-05 05:19:36,483 - INFO - Epoch 76/100 - Train Loss: 0.1484 - Val Acc: 0.8406
2026-04-05 05:19:36,805 - INFO - Epoch 77/100 - Train Loss: 0.1455 - Val Acc: 0.8406
2026-04-05 05:19:37,120 - INFO - Epoch 78/100 - Train Loss: 0.1535 - Val Acc: 0.8406
2026-04-05 05:19:37,434 - INFO - Epoch 79/100 - Train Loss: 0.1428 - Val Acc: 0.8406
2026-04-05 05:19:37,742 - INFO - Epoch 80/100 - Train Loss: 0.1413 - Val Acc: 0.8551
2026-04-05 05:19:38,055 - INFO - Epoch 81/100 - Train Loss: 0.1584 - Val Acc: 0.8551
2026-04-05 05:19:38,368 - INFO - Epoch 82/100 - Train Loss: 0.1410 - Val Acc: 0.8116
2026-04-05 05:19:38,680 - INFO - Epoch 83/100 - Train Loss: 0.1281 - Val Acc: 0.8261
2026-04-05 05:19:39,003 - INFO - Epoch 84/100 - Train Loss: 0.1382 - Val Acc: 0.8551
2026-04-05 05:19:39,312 - INFO - Epoch 85/100 - Train Loss: 0.1449 - Val Acc: 0.8551
2026-04-05 05:19:39,624 - INFO - Epoch 86/100 - Train Loss: 0.1351 - Val Acc: 0.8551
2026-04-05 05:19:39,935 - INFO - Epoch 87/100 - Train Loss: 0.1393 - Val Acc: 0.8406
2026-04-05 05:19:40,266 - INFO - Epoch 88/100 - Train Loss: 0.1401 - Val Acc: 0.8551
2026-04-05 05:19:40,581 - INFO - Epoch 89/100 - Train Loss: 0.1413 - Val Acc: 0.8551
2026-04-05 05:19:40,893 - INFO - Epoch 90/100 - Train Loss: 0.1330 - Val Acc: 0.8551
2026-04-05 05:19:41,213 - INFO - Epoch 91/100 - Train Loss: 0.1391 - Val Acc: 0.8261
2026-04-05 05:19:41,526 - INFO - Epoch 92/100 - Train Loss: 0.1457 - Val Acc: 0.8696
2026-04-05 05:19:41,847 - INFO - Epoch 93/100 - Train Loss: 0.1246 - Val Acc: 0.8551
2026-04-05 05:19:42,170 - INFO - Epoch 94/100 - Train Loss: 0.1066 - Val Acc: 0.8406
2026-04-05 05:19:42,493 - INFO - Epoch 95/100 - Train Loss: 0.1343 - Val Acc: 0.8406
2026-04-05 05:19:42,815 - INFO - Epoch 96/100 - Train Loss: 0.1296 - Val Acc: 0.8261
2026-04-05 05:19:43,134 - INFO - Epoch 97/100 - Train Loss: 0.1283 - Val Acc: 0.8261
2026-04-05 05:19:43,446 - INFO - Epoch 98/100 - Train Loss: 0.1297 - Val Acc: 0.8261
2026-04-05 05:19:43,772 - INFO - Epoch 99/100 - Train Loss: 0.1251 - Val Acc: 0.8551
2026-04-05 05:19:44,110 - INFO - Epoch 100/100 - Train Loss: 0.1215 - Val Acc: 0.8261
2026-04-05 05:19:44,479 - INFO - Fold 8 logically complete. Tensor memory bounds cleared cleanly.
2026-04-05 05:19:44,484 - INFO - Original class distribution: [276 345]
2026-04-05 05:19:44,485 - INFO - Training device bound securely to: cuda

Fold 9:   0%|          | 0/100 [00:00<?, ?it/s]

2026-04-05 05:19:44,840 - INFO - Epoch 1/100 - Train Loss: 0.6146 - Val Acc: 0.8406
2026-04-05 05:19:45,159 - INFO - Epoch 2/100 - Train Loss: 0.4433 - Val Acc: 0.8406
2026-04-05 05:19:45,475 - INFO - Epoch 3/100 - Train Loss: 0.3510 - Val Acc: 0.8406
2026-04-05 05:19:45,793 - INFO - Epoch 4/100 - Train Loss: 0.3189 - Val Acc: 0.8261
2026-04-05 05:19:46,102 - INFO - Epoch 5/100 - Train Loss: 0.3137 - Val Acc: 0.8261
2026-04-05 05:19:46,419 - INFO - Epoch 6/100 - Train Loss: 0.3105 - Val Acc: 0.8261
2026-04-05 05:19:46,740 - INFO - Epoch 7/100 - Train Loss: 0.2882 - Val Acc: 0.8261
2026-04-05 05:19:47,055 - INFO - Epoch 8/100 - Train Loss: 0.2886 - Val Acc: 0.8261
2026-04-05 05:19:47,381 - INFO - Epoch 9/100 - Train Loss: 0.2770 - Val Acc: 0.8116
2026-04-05 05:19:47,691 - INFO - Epoch 10/100 - Train Loss: 0.2747 - Val Acc: 0.8261
2026-04-05 05:19:47,999 - INFO - Epoch 11/100 - Train Loss: 0.2653 - Val Acc: 0.8116
2026-04-05 05:19:48,319 - INFO - Epoch 12/100 - Train Loss: 0.2680 - Val Acc: 0.8116
2026-04-05 05:19:48,637 - INFO - Epoch 13/100 - Train Loss: 0.2715 - Val Acc: 0.8116
2026-04-05 05:19:48,961 - INFO - Epoch 14/100 - Train Loss: 0.2681 - Val Acc: 0.7971
2026-04-05 05:19:49,287 - INFO - Epoch 15/100 - Train Loss: 0.2541 - Val Acc: 0.8406
2026-04-05 05:19:49,621 - INFO - Epoch 16/100 - Train Loss: 0.2550 - Val Acc: 0.8116
2026-04-05 05:19:49,932 - INFO - Epoch 17/100 - Train Loss: 0.2550 - Val Acc: 0.8261
2026-04-05 05:19:50,242 - INFO - Epoch 18/100 - Train Loss: 0.2462 - Val Acc: 0.8116
2026-04-05 05:19:50,553 - INFO - Epoch 19/100 - Train Loss: 0.2425 - Val Acc: 0.8261
2026-04-05 05:19:50,862 - INFO - Epoch 20/100 - Train Loss: 0.2398 - Val Acc: 0.8116
2026-04-05 05:19:51,176 - INFO - Epoch 21/100 - Train Loss: 0.2465 - Val Acc: 0.8116
2026-04-05 05:19:51,499 - INFO - Epoch 22/100 - Train Loss: 0.2477 - Val Acc: 0.8116
2026-04-05 05:19:51,822 - INFO - Epoch 23/100 - Train Loss: 0.2367 - Val Acc: 0.8116
2026-04-05 05:19:52,132 - INFO - Epoch 24/100 - Train Loss: 0.2388 - Val Acc: 0.7971
2026-04-05 05:19:52,449 - INFO - Epoch 25/100 - Train Loss: 0.2271 - Val Acc: 0.8116
2026-04-05 05:19:52,774 - INFO - Epoch 26/100 - Train Loss: 0.2293 - Val Acc: 0.7971
2026-04-05 05:19:53,097 - INFO - Epoch 27/100 - Train Loss: 0.2295 - Val Acc: 0.8116
2026-04-05 05:19:53,411 - INFO - Epoch 28/100 - Train Loss: 0.2257 - Val Acc: 0.7971
2026-04-05 05:19:53,736 - INFO - Epoch 29/100 - Train Loss: 0.2188 - Val Acc: 0.8116
2026-04-05 05:19:54,052 - INFO - Epoch 30/100 - Train Loss: 0.2103 - Val Acc: 0.7826
2026-04-05 05:19:54,416 - INFO - Epoch 31/100 - Train Loss: 0.2147 - Val Acc: 0.7971
2026-04-05 05:19:54,757 - INFO - Epoch 32/100 - Train Loss: 0.2098 - Val Acc: 0.7971
2026-04-05 05:19:55,070 - INFO - Epoch 33/100 - Train Loss: 0.2200 - Val Acc: 0.8261
2026-04-05 05:19:55,388 - INFO - Epoch 34/100 - Train Loss: 0.2013 - Val Acc: 0.7826
2026-04-05 05:19:55,702 - INFO - Epoch 35/100 - Train Loss: 0.2074 - Val Acc: 0.7971
2026-04-05 05:19:56,034 - INFO - Epoch 36/100 - Train Loss: 0.1939 - Val Acc: 0.8261
2026-04-05 05:19:56,351 - INFO - Epoch 37/100 - Train Loss: 0.2117 - Val Acc: 0.7971
2026-04-05 05:19:56,672 - INFO - Epoch 38/100 - Train Loss: 0.2095 - Val Acc: 0.8116
2026-04-05 05:19:56,988 - INFO - Epoch 39/100 - Train Loss: 0.1995 - Val Acc: 0.8116
2026-04-05 05:19:57,304 - INFO - Epoch 40/100 - Train Loss: 0.2018 - Val Acc: 0.7971
2026-04-05 05:19:57,616 - INFO - Epoch 41/100 - Train Loss: 0.1994 - Val Acc: 0.8261
2026-04-05 05:19:57,934 - INFO - Epoch 42/100 - Train Loss: 0.1994 - Val Acc: 0.8116
2026-04-05 05:19:58,274 - INFO - Epoch 43/100 - Train Loss: 0.1944 - Val Acc: 0.8116
2026-04-05 05:19:58,591 - INFO - Epoch 44/100 - Train Loss: 0.1982 - Val Acc: 0.8261
2026-04-05 05:19:58,908 - INFO - Epoch 45/100 - Train Loss: 0.1898 - Val Acc: 0.8261
2026-04-05 05:19:59,222 - INFO - Epoch 46/100 - Train Loss: 0.1796 - Val Acc: 0.8116
2026-04-05 05:19:59,542 - INFO - Epoch 47/100 - Train Loss: 0.1828 - Val Acc: 0.8261
2026-04-05 05:19:59,850 - INFO - Epoch 48/100 - Train Loss: 0.1771 - Val Acc: 0.8116
2026-04-05 05:20:00,166 - INFO - Epoch 49/100 - Train Loss: 0.1648 - Val Acc: 0.8261
2026-04-05 05:20:00,483 - INFO - Epoch 50/100 - Train Loss: 0.1713 - Val Acc: 0.8261
2026-04-05 05:20:00,790 - INFO - Epoch 51/100 - Train Loss: 0.1775 - Val Acc: 0.8261
2026-04-05 05:20:01,115 - INFO - Epoch 52/100 - Train Loss: 0.1844 - Val Acc: 0.8261
2026-04-05 05:20:01,435 - INFO - Epoch 53/100 - Train Loss: 0.1969 - Val Acc: 0.8261
2026-04-05 05:20:01,746 - INFO - Epoch 54/100 - Train Loss: 0.1741 - Val Acc: 0.8261
2026-04-05 05:20:02,069 - INFO - Epoch 55/100 - Train Loss: 0.1629 - Val Acc: 0.8261
2026-04-05 05:20:02,379 - INFO - Epoch 56/100 - Train Loss: 0.1718 - Val Acc: 0.8261
2026-04-05 05:20:02,696 - INFO - Epoch 57/100 - Train Loss: 0.1667 - Val Acc: 0.8261
2026-04-05 05:20:03,005 - INFO - Epoch 58/100 - Train Loss: 0.1906 - Val Acc: 0.8116
2026-04-05 05:20:03,310 - INFO - Epoch 59/100 - Train Loss: 0.1680 - Val Acc: 0.8261
2026-04-05 05:20:03,628 - INFO - Epoch 60/100 - Train Loss: 0.1510 - Val Acc: 0.8261
2026-04-05 05:20:03,934 - INFO - Epoch 61/100 - Train Loss: 0.1657 - Val Acc: 0.8261
2026-04-05 05:20:04,257 - INFO - Epoch 62/100 - Train Loss: 0.1509 - Val Acc: 0.8116
2026-04-05 05:20:04,590 - INFO - Epoch 63/100 - Train Loss: 0.1582 - Val Acc: 0.8261
2026-04-05 05:20:04,896 - INFO - Epoch 64/100 - Train Loss: 0.1458 - Val Acc: 0.8116
2026-04-05 05:20:05,212 - INFO - Epoch 65/100 - Train Loss: 0.1505 - Val Acc: 0.7971
2026-04-05 05:20:05,517 - INFO - Epoch 66/100 - Train Loss: 0.1615 - Val Acc: 0.8116
2026-04-05 05:20:05,837 - INFO - Epoch 67/100 - Train Loss: 0.1461 - Val Acc: 0.7971
2026-04-05 05:20:06,153 - INFO - Epoch 68/100 - Train Loss: 0.1469 - Val Acc: 0.8261
2026-04-05 05:20:06,459 - INFO - Epoch 69/100 - Train Loss: 0.1379 - Val Acc: 0.7971
2026-04-05 05:20:06,761 - INFO - Epoch 70/100 - Train Loss: 0.1514 - Val Acc: 0.8116
2026-04-05 05:20:07,067 - INFO - Epoch 71/100 - Train Loss: 0.1480 - Val Acc: 0.7971
2026-04-05 05:20:07,371 - INFO - Epoch 72/100 - Train Loss: 0.1485 - Val Acc: 0.8116
2026-04-05 05:20:07,697 - INFO - Epoch 73/100 - Train Loss: 0.1488 - Val Acc: 0.7971
2026-04-05 05:20:07,998 - INFO - Epoch 74/100 - Train Loss: 0.1375 - Val Acc: 0.7971
2026-04-05 05:20:08,306 - INFO - Epoch 75/100 - Train Loss: 0.1510 - Val Acc: 0.8406
2026-04-05 05:20:08,604 - INFO - Epoch 76/100 - Train Loss: 0.1567 - Val Acc: 0.7826
2026-04-05 05:20:08,907 - INFO - Epoch 77/100 - Train Loss: 0.1401 - Val Acc: 0.7826
2026-04-05 05:20:09,221 - INFO - Epoch 78/100 - Train Loss: 0.1457 - Val Acc: 0.7826
2026-04-05 05:20:09,540 - INFO - Epoch 79/100 - Train Loss: 0.1446 - Val Acc: 0.7971
2026-04-05 05:20:09,855 - INFO - Epoch 80/100 - Train Loss: 0.1522 - Val Acc: 0.7971
2026-04-05 05:20:10,163 - INFO - Epoch 81/100 - Train Loss: 0.1437 - Val Acc: 0.8116
2026-04-05 05:20:10,493 - INFO - Epoch 82/100 - Train Loss: 0.1263 - Val Acc: 0.8116
2026-04-05 05:20:10,805 - INFO - Epoch 83/100 - Train Loss: 0.1485 - Val Acc: 0.7971
2026-04-05 05:20:11,127 - INFO - Epoch 84/100 - Train Loss: 0.1310 - Val Acc: 0.8116
2026-04-05 05:20:11,439 - INFO - Epoch 85/100 - Train Loss: 0.1350 - Val Acc: 0.8261
2026-04-05 05:20:11,753 - INFO - Epoch 86/100 - Train Loss: 0.1291 - Val Acc: 0.7971
2026-04-05 05:20:12,063 - INFO - Epoch 87/100 - Train Loss: 0.1349 - Val Acc: 0.8261
2026-04-05 05:20:12,385 - INFO - Epoch 88/100 - Train Loss: 0.1235 - Val Acc: 0.8261
2026-04-05 05:20:12,698 - INFO - Epoch 89/100 - Train Loss: 0.1369 - Val Acc: 0.7971
2026-04-05 05:20:13,022 - INFO - Epoch 90/100 - Train Loss: 0.1302 - Val Acc: 0.8116
2026-04-05 05:20:13,340 - INFO - Epoch 91/100 - Train Loss: 0.1268 - Val Acc: 0.7971
2026-04-05 05:20:13,656 - INFO - Epoch 92/100 - Train Loss: 0.1223 - Val Acc: 0.7971
2026-04-05 05:20:13,977 - INFO - Epoch 93/100 - Train Loss: 0.1287 - Val Acc: 0.7971
2026-04-05 05:20:14,318 - INFO - Epoch 94/100 - Train Loss: 0.1182 - Val Acc: 0.8116
2026-04-05 05:20:14,656 - INFO - Epoch 95/100 - Train Loss: 0.1079 - Val Acc: 0.8116
2026-04-05 05:20:14,976 - INFO - Epoch 96/100 - Train Loss: 0.1258 - Val Acc: 0.8116
2026-04-05 05:20:15,307 - INFO - Epoch 97/100 - Train Loss: 0.1228 - Val Acc: 0.8116
2026-04-05 05:20:15,627 - INFO - Epoch 98/100 - Train Loss: 0.1209 - Val Acc: 0.8261
2026-04-05 05:20:15,943 - INFO - Epoch 99/100 - Train Loss: 0.1233 - Val Acc: 0.8116
2026-04-05 05:20:16,272 - INFO - Epoch 100/100 - Train Loss: 0.1295 - Val Acc: 0.8116
2026-04-05 05:20:16,619 - INFO - Fold 9 logically complete. Tensor memory bounds cleared cleanly.
2026-04-05 05:20:16,623 - INFO - Original class distribution: [276 345]
2026-04-05 05:20:16,624 - INFO - Training device bound securely to: cuda

Fold 10:   0%|          | 0/100 [00:00<?, ?it/s]

2026-04-05 05:20:16,955 - INFO - Epoch 1/100 - Train Loss: 0.6049 - Val Acc: 0.9130
2026-04-05 05:20:17,264 - INFO - Epoch 2/100 - Train Loss: 0.4246 - Val Acc: 0.9130
2026-04-05 05:20:17,578 - INFO - Epoch 3/100 - Train Loss: 0.3581 - Val Acc: 0.9275
2026-04-05 05:20:17,899 - INFO - Epoch 4/100 - Train Loss: 0.3433 - Val Acc: 0.9275
2026-04-05 05:20:18,229 - INFO - Epoch 5/100 - Train Loss: 0.3317 - Val Acc: 0.9275
2026-04-05 05:20:18,551 - INFO - Epoch 6/100 - Train Loss: 0.3249 - Val Acc: 0.9275
2026-04-05 05:20:18,864 - INFO - Epoch 7/100 - Train Loss: 0.3366 - Val Acc: 0.9275
2026-04-05 05:20:19,188 - INFO - Epoch 8/100 - Train Loss: 0.3062 - Val Acc: 0.9275
2026-04-05 05:20:19,502 - INFO - Epoch 9/100 - Train Loss: 0.3053 - Val Acc: 0.9275
2026-04-05 05:20:19,835 - INFO - Epoch 10/100 - Train Loss: 0.2959 - Val Acc: 0.9420
2026-04-05 05:20:20,155 - INFO - Epoch 11/100 - Train Loss: 0.2803 - Val Acc: 0.9420
2026-04-05 05:20:20,472 - INFO - Epoch 12/100 - Train Loss: 0.2967 - Val Acc: 0.9565
2026-04-05 05:20:20,785 - INFO - Epoch 13/100 - Train Loss: 0.2992 - Val Acc: 0.9420
2026-04-05 05:20:21,101 - INFO - Epoch 14/100 - Train Loss: 0.2858 - Val Acc: 0.9420
2026-04-05 05:20:21,431 - INFO - Epoch 15/100 - Train Loss: 0.2763 - Val Acc: 0.9420
2026-04-05 05:20:21,770 - INFO - Epoch 16/100 - Train Loss: 0.2757 - Val Acc: 0.9420
2026-04-05 05:20:22,090 - INFO - Epoch 17/100 - Train Loss: 0.2784 - Val Acc: 0.9420
2026-04-05 05:20:22,414 - INFO - Epoch 18/100 - Train Loss: 0.2681 - Val Acc: 0.9420
2026-04-05 05:20:22,734 - INFO - Epoch 19/100 - Train Loss: 0.2634 - Val Acc: 0.9420
2026-04-05 05:20:23,050 - INFO - Epoch 20/100 - Train Loss: 0.2746 - Val Acc: 0.9420
2026-04-05 05:20:23,393 - INFO - Epoch 21/100 - Train Loss: 0.2564 - Val Acc: 0.9420
2026-04-05 05:20:23,716 - INFO - Epoch 22/100 - Train Loss: 0.2505 - Val Acc: 0.9420
2026-04-05 05:20:24,034 - INFO - Epoch 23/100 - Train Loss: 0.2612 - Val Acc: 0.9420
2026-04-05 05:20:24,377 - INFO - Epoch 24/100 - Train Loss: 0.2411 - Val Acc: 0.9420
2026-04-05 05:20:24,715 - INFO - Epoch 25/100 - Train Loss: 0.2346 - Val Acc: 0.9420
2026-04-05 05:20:25,029 - INFO - Epoch 26/100 - Train Loss: 0.2513 - Val Acc: 0.9420
2026-04-05 05:20:25,336 - INFO - Epoch 27/100 - Train Loss: 0.2451 - Val Acc: 0.9420
2026-04-05 05:20:25,654 - INFO - Epoch 28/100 - Train Loss: 0.2410 - Val Acc: 0.9420
2026-04-05 05:20:25,992 - INFO - Epoch 29/100 - Train Loss: 0.2254 - Val Acc: 0.9420
2026-04-05 05:20:26,305 - INFO - Epoch 30/100 - Train Loss: 0.2331 - Val Acc: 0.9420
2026-04-05 05:20:26,614 - INFO - Epoch 31/100 - Train Loss: 0.2439 - Val Acc: 0.9420
2026-04-05 05:20:26,931 - INFO - Epoch 32/100 - Train Loss: 0.2216 - Val Acc: 0.9420
2026-04-05 05:20:27,248 - INFO - Epoch 33/100 - Train Loss: 0.2115 - Val Acc: 0.9420
2026-04-05 05:20:27,564 - INFO - Epoch 34/100 - Train Loss: 0.2122 - Val Acc: 0.9420
2026-04-05 05:20:27,893 - INFO - Epoch 35/100 - Train Loss: 0.2160 - Val Acc: 0.9420
2026-04-05 05:20:28,206 - INFO - Epoch 36/100 - Train Loss: 0.2252 - Val Acc: 0.9420
2026-04-05 05:20:28,535 - INFO - Epoch 37/100 - Train Loss: 0.2190 - Val Acc: 0.9420
2026-04-05 05:20:28,864 - INFO - Epoch 38/100 - Train Loss: 0.2241 - Val Acc: 0.9420
2026-04-05 05:20:29,176 - INFO - Epoch 39/100 - Train Loss: 0.2066 - Val Acc: 0.9275
2026-04-05 05:20:29,497 - INFO - Epoch 40/100 - Train Loss: 0.2211 - Val Acc: 0.9275
2026-04-05 05:20:29,809 - INFO - Epoch 41/100 - Train Loss: 0.2250 - Val Acc: 0.9275
2026-04-05 05:20:30,141 - INFO - Epoch 42/100 - Train Loss: 0.2099 - Val Acc: 0.9420
2026-04-05 05:20:30,459 - INFO - Epoch 43/100 - Train Loss: 0.2115 - Val Acc: 0.9420
2026-04-05 05:20:30,768 - INFO - Epoch 44/100 - Train Loss: 0.2115 - Val Acc: 0.9275
2026-04-05 05:20:31,073 - INFO - Epoch 45/100 - Train Loss: 0.2034 - Val Acc: 0.9420
2026-04-05 05:20:31,395 - INFO - Epoch 46/100 - Train Loss: 0.2120 - Val Acc: 0.9420
2026-04-05 05:20:31,718 - INFO - Epoch 47/100 - Train Loss: 0.1983 - Val Acc: 0.9420
2026-04-05 05:20:32,045 - INFO - Epoch 48/100 - Train Loss: 0.2008 - Val Acc: 0.9420
2026-04-05 05:20:32,364 - INFO - Epoch 49/100 - Train Loss: 0.2030 - Val Acc: 0.9420
2026-04-05 05:20:32,675 - INFO - Epoch 50/100 - Train Loss: 0.2013 - Val Acc: 0.9420
2026-04-05 05:20:33,007 - INFO - Epoch 51/100 - Train Loss: 0.2020 - Val Acc: 0.9420
2026-04-05 05:20:33,319 - INFO - Epoch 52/100 - Train Loss: 0.1876 - Val Acc: 0.9420
2026-04-05 05:20:33,638 - INFO - Epoch 53/100 - Train Loss: 0.1958 - Val Acc: 0.9275
2026-04-05 05:20:33,968 - INFO - Epoch 54/100 - Train Loss: 0.1993 - Val Acc: 0.9420
2026-04-05 05:20:34,298 - INFO - Epoch 55/100 - Train Loss: 0.1804 - Val Acc: 0.9420
2026-04-05 05:20:34,666 - INFO - Epoch 56/100 - Train Loss: 0.1809 - Val Acc: 0.9420
2026-04-05 05:20:34,990 - INFO - Epoch 57/100 - Train Loss: 0.1970 - Val Acc: 0.9275
2026-04-05 05:20:35,312 - INFO - Epoch 58/100 - Train Loss: 0.1814 - Val Acc: 0.9275
2026-04-05 05:20:35,626 - INFO - Epoch 59/100 - Train Loss: 0.1855 - Val Acc: 0.9275
2026-04-05 05:20:35,938 - INFO - Epoch 60/100 - Train Loss: 0.1938 - Val Acc: 0.9275
2026-04-05 05:20:36,262 - INFO - Epoch 61/100 - Train Loss: 0.1784 - Val Acc: 0.9420
2026-04-05 05:20:36,584 - INFO - Epoch 62/100 - Train Loss: 0.1909 - Val Acc: 0.9420
2026-04-05 05:20:36,908 - INFO - Epoch 63/100 - Train Loss: 0.1872 - Val Acc: 0.9275
2026-04-05 05:20:37,232 - INFO - Epoch 64/100 - Train Loss: 0.1682 - Val Acc: 0.9420
2026-04-05 05:20:37,541 - INFO - Epoch 65/100 - Train Loss: 0.1832 - Val Acc: 0.9420
2026-04-05 05:20:37,867 - INFO - Epoch 66/100 - Train Loss: 0.1684 - Val Acc: 0.9420
2026-04-05 05:20:38,191 - INFO - Epoch 67/100 - Train Loss: 0.1689 - Val Acc: 0.9275
2026-04-05 05:20:38,510 - INFO - Epoch 68/100 - Train Loss: 0.1840 - Val Acc: 0.9275
2026-04-05 05:20:38,838 - INFO - Epoch 69/100 - Train Loss: 0.1700 - Val Acc: 0.9420
2026-04-05 05:20:39,157 - INFO - Epoch 70/100 - Train Loss: 0.1776 - Val Acc: 0.9275
2026-04-05 05:20:39,481 - INFO - Epoch 71/100 - Train Loss: 0.1693 - Val Acc: 0.9420
2026-04-05 05:20:39,797 - INFO - Epoch 72/100 - Train Loss: 0.1655 - Val Acc: 0.9275
2026-04-05 05:20:40,130 - INFO - Epoch 73/100 - Train Loss: 0.1716 - Val Acc: 0.9420
2026-04-05 05:20:40,444 - INFO - Epoch 74/100 - Train Loss: 0.1762 - Val Acc: 0.9275
2026-04-05 05:20:40,771 - INFO - Epoch 75/100 - Train Loss: 0.1645 - Val Acc: 0.9420
2026-04-05 05:20:41,082 - INFO - Epoch 76/100 - Train Loss: 0.1694 - Val Acc: 0.9275
2026-04-05 05:20:41,397 - INFO - Epoch 77/100 - Train Loss: 0.1685 - Val Acc: 0.9420
2026-04-05 05:20:41,724 - INFO - Epoch 78/100 - Train Loss: 0.1681 - Val Acc: 0.9420
2026-04-05 05:20:42,057 - INFO - Epoch 79/100 - Train Loss: 0.1592 - Val Acc: 0.9275
2026-04-05 05:20:42,368 - INFO - Epoch 80/100 - Train Loss: 0.1617 - Val Acc: 0.9275
2026-04-05 05:20:42,684 - INFO - Epoch 81/100 - Train Loss: 0.1599 - Val Acc: 0.9275
2026-04-05 05:20:42,997 - INFO - Epoch 82/100 - Train Loss: 0.1509 - Val Acc: 0.9275
2026-04-05 05:20:43,319 - INFO - Epoch 83/100 - Train Loss: 0.1429 - Val Acc: 0.9275
2026-04-05 05:20:43,631 - INFO - Epoch 84/100 - Train Loss: 0.1481 - Val Acc: 0.9275
2026-04-05 05:20:43,945 - INFO - Epoch 85/100 - Train Loss: 0.1515 - Val Acc: 0.9275
2026-04-05 05:20:44,275 - INFO - Epoch 86/100 - Train Loss: 0.1475 - Val Acc: 0.9420
2026-04-05 05:20:44,621 - INFO - Epoch 87/100 - Train Loss: 0.1492 - Val Acc: 0.9420
2026-04-05 05:20:44,936 - INFO - Epoch 88/100 - Train Loss: 0.1459 - Val Acc: 0.9275
2026-04-05 05:20:45,256 - INFO - Epoch 89/100 - Train Loss: 0.1404 - Val Acc: 0.9275
2026-04-05 05:20:45,573 - INFO - Epoch 90/100 - Train Loss: 0.1511 - Val Acc: 0.9420
2026-04-05 05:20:45,912 - INFO - Epoch 91/100 - Train Loss: 0.1506 - Val Acc: 0.9275
2026-04-05 05:20:46,229 - INFO - Epoch 92/100 - Train Loss: 0.1533 - Val Acc: 0.9275
2026-04-05 05:20:46,549 - INFO - Epoch 93/100 - Train Loss: 0.1281 - Val Acc: 0.9275
2026-04-05 05:20:46,864 - INFO - Epoch 94/100 - Train Loss: 0.1299 - Val Acc: 0.9420
2026-04-05 05:20:47,173 - INFO - Epoch 95/100 - Train Loss: 0.1450 - Val Acc: 0.9420
2026-04-05 05:20:47,494 - INFO - Epoch 96/100 - Train Loss: 0.1360 - Val Acc: 0.9275
2026-04-05 05:20:47,821 - INFO - Epoch 97/100 - Train Loss: 0.1214 - Val Acc: 0.9420
2026-04-05 05:20:48,149 - INFO - Epoch 98/100 - Train Loss: 0.1458 - Val Acc: 0.9420
2026-04-05 05:20:48,478 - INFO - Epoch 99/100 - Train Loss: 0.1536 - Val Acc: 0.9275
2026-04-05 05:20:48,788 - INFO - Epoch 100/100 - Train Loss: 0.1457 - Val Acc: 0.9275
2026-04-05 05:20:49,148 - INFO - Fold 10 logically complete. Tensor memory bounds cleared cleanly.
2026-04-05 05:20:49,180 - INFO - ✓ Completed MLP_baseline
2026-04-05 05:20:49,181 - INFO -   Mean Accuracy: 0.8841 ± 0.0489
2026-04-05 05:20:49,182 - INFO -
EXPERIMENT: MLP_SMOTEENN | german | SMOTE-ENN: True

German | MLP | SMOTEENN:   0%|          | 0/10 [00:00<?, ?it/s]

2026-04-05 05:20:49,195 - INFO - Original class distribution: [277 344]
2026-04-05 05:20:49,195 - INFO - Training device bound securely to: cuda
2026-04-05 05:20:49,231 - INFO - After SMOTE-ENN deployment: [344 289]

Fold 1:   0%|          | 0/100 [00:00<?, ?it/s]

2026-04-05 05:20:49,554 - INFO - Epoch 1/100 - Train Loss: 0.5906 - Val Acc: 0.7971
2026-04-05 05:20:49,880 - INFO - Epoch 2/100 - Train Loss: 0.3647 - Val Acc: 0.8551
2026-04-05 05:20:50,192 - INFO - Epoch 3/100 - Train Loss: 0.2419 - Val Acc: 0.8551
2026-04-05 05:20:50,526 - INFO - Epoch 4/100 - Train Loss: 0.2069 - Val Acc: 0.8551
2026-04-05 05:20:50,847 - INFO - Epoch 5/100 - Train Loss: 0.1907 - Val Acc: 0.8696
2026-04-05 05:20:51,162 - INFO - Epoch 6/100 - Train Loss: 0.1916 - Val Acc: 0.8696
2026-04-05 05:20:51,490 - INFO - Epoch 7/100 - Train Loss: 0.1823 - Val Acc: 0.8551
2026-04-05 05:20:51,803 - INFO - Epoch 8/100 - Train Loss: 0.1724 - Val Acc: 0.8696
2026-04-05 05:20:52,134 - INFO - Epoch 9/100 - Train Loss: 0.1596 - Val Acc: 0.8551
2026-04-05 05:20:52,459 - INFO - Epoch 10/100 - Train Loss: 0.1598 - Val Acc: 0.8841
2026-04-05 05:20:52,782 - INFO - Epoch 11/100 - Train Loss: 0.1578 - Val Acc: 0.8696
2026-04-05 05:20:53,112 - INFO - Epoch 12/100 - Train Loss: 0.1551 - Val Acc: 0.8696
2026-04-05 05:20:53,423 - INFO - Epoch 13/100 - Train Loss: 0.1475 - Val Acc: 0.8696
2026-04-05 05:20:53,745 - INFO - Epoch 14/100 - Train Loss: 0.1380 - Val Acc: 0.8696
2026-04-05 05:20:54,060 - INFO - Epoch 15/100 - Train Loss: 0.1326 - Val Acc: 0.8696
2026-04-05 05:20:54,422 - INFO - Epoch 16/100 - Train Loss: 0.1347 - Val Acc: 0.8696
2026-04-05 05:20:54,768 - INFO - Epoch 17/100 - Train Loss: 0.1358 - Val Acc: 0.8696
2026-04-05 05:20:55,082 - INFO - Epoch 18/100 - Train Loss: 0.1334 - Val Acc: 0.8696
2026-04-05 05:20:55,398 - INFO - Epoch 19/100 - Train Loss: 0.1262 - Val Acc: 0.8696
2026-04-05 05:20:55,720 - INFO - Epoch 20/100 - Train Loss: 0.1367 - Val Acc: 0.8696
2026-04-05 05:20:56,031 - INFO - Epoch 21/100 - Train Loss: 0.1143 - Val Acc: 0.8696
2026-04-05 05:20:56,341 - INFO - Epoch 22/100 - Train Loss: 0.1110 - Val Acc: 0.8696
2026-04-05 05:20:56,670 - INFO - Epoch 23/100 - Train Loss: 0.1139 - Val Acc: 0.8551
2026-04-05 05:20:56,986 - INFO - Epoch 24/100 - Train Loss: 0.1187 - Val Acc: 0.8551
2026-04-05 05:20:57,306 - INFO - Epoch 25/100 - Train Loss: 0.1147 - Val Acc: 0.8551
2026-04-05 05:20:57,621 - INFO - Epoch 26/100 - Train Loss: 0.1051 - Val Acc: 0.8551
2026-04-05 05:20:57,932 - INFO - Epoch 27/100 - Train Loss: 0.1101 - Val Acc: 0.8551
2026-04-05 05:20:58,257 - INFO - Epoch 28/100 - Train Loss: 0.1041 - Val Acc: 0.8551
2026-04-05 05:20:58,576 - INFO - Epoch 29/100 - Train Loss: 0.0992 - Val Acc: 0.8551
2026-04-05 05:20:58,892 - INFO - Epoch 30/100 - Train Loss: 0.1040 - Val Acc: 0.8406
2026-04-05 05:20:59,211 - INFO - Epoch 31/100 - Train Loss: 0.0906 - Val Acc: 0.8551
2026-04-05 05:20:59,520 - INFO - Epoch 32/100 - Train Loss: 0.1048 - Val Acc: 0.8551
2026-04-05 05:20:59,838 - INFO - Epoch 33/100 - Train Loss: 0.0910 - Val Acc: 0.8551
2026-04-05 05:21:00,150 - INFO - Epoch 34/100 - Train Loss: 0.0836 - Val Acc: 0.8551
2026-04-05 05:21:00,459 - INFO - Epoch 35/100 - Train Loss: 0.0905 - Val Acc: 0.8696
2026-04-05 05:21:00,792 - INFO - Epoch 36/100 - Train Loss: 0.0781 - Val Acc: 0.8551
2026-04-05 05:21:01,117 - INFO - Epoch 37/100 - Train Loss: 0.0860 - Val Acc: 0.8551
2026-04-05 05:21:01,430 - INFO - Epoch 38/100 - Train Loss: 0.0885 - Val Acc: 0.8551
2026-04-05 05:21:01,751 - INFO - Epoch 39/100 - Train Loss: 0.0834 - Val Acc: 0.8551
2026-04-05 05:21:02,070 - INFO - Epoch 40/100 - Train Loss: 0.0790 - Val Acc: 0.8551
2026-04-05 05:21:02,382 - INFO - Epoch 41/100 - Train Loss: 0.0807 - Val Acc: 0.8551
2026-04-05 05:21:02,703 - INFO - Epoch 42/100 - Train Loss: 0.0811 - Val Acc: 0.8551
2026-04-05 05:21:03,019 - INFO - Epoch 43/100 - Train Loss: 0.0669 - Val Acc: 0.8696
2026-04-05 05:21:03,327 - INFO - Epoch 44/100 - Train Loss: 0.0747 - Val Acc: 0.8696
2026-04-05 05:21:03,664 - INFO - Epoch 45/100 - Train Loss: 0.0806 - Val Acc: 0.8551
2026-04-05 05:21:03,981 - INFO - Epoch 46/100 - Train Loss: 0.0798 - Val Acc: 0.8551
2026-04-05 05:21:04,328 - INFO - Epoch 47/100 - Train Loss: 0.0707 - Val Acc: 0.8696
2026-04-05 05:21:04,668 - INFO - Epoch 48/100 - Train Loss: 0.0708 - Val Acc: 0.8551
2026-04-05 05:21:04,988 - INFO - Epoch 49/100 - Train Loss: 0.0721 - Val Acc: 0.8551
2026-04-05 05:21:05,315 - INFO - Epoch 50/100 - Train Loss: 0.0713 - Val Acc: 0.8696
2026-04-05 05:21:05,631 - INFO - Epoch 51/100 - Train Loss: 0.0609 - Val Acc: 0.8696
2026-04-05 05:21:05,950 - INFO - Epoch 52/100 - Train Loss: 0.0571 - Val Acc: 0.8551
2026-04-05 05:21:06,260 - INFO - Epoch 53/100 - Train Loss: 0.0656 - Val Acc: 0.8551
2026-04-05 05:21:06,575 - INFO - Epoch 54/100 - Train Loss: 0.0651 - Val Acc: 0.8551
2026-04-05 05:21:06,909 - INFO - Epoch 55/100 - Train Loss: 0.0601 - Val Acc: 0.8551
2026-04-05 05:21:07,245 - INFO - Epoch 56/100 - Train Loss: 0.0653 - Val Acc: 0.8696
2026-04-05 05:21:07,575 - INFO - Epoch 57/100 - Train Loss: 0.0660 - Val Acc: 0.8696
2026-04-05 05:21:07,894 - INFO - Epoch 58/100 - Train Loss: 0.0655 - Val Acc: 0.8696
2026-04-05 05:21:08,215 - INFO - Epoch 59/100 - Train Loss: 0.0655 - Val Acc: 0.8696
2026-04-05 05:21:08,532 - INFO - Epoch 60/100 - Train Loss: 0.0562 - Val Acc: 0.8696
2026-04-05 05:21:08,848 - INFO - Epoch 61/100 - Train Loss: 0.0568 - Val Acc: 0.8696
2026-04-05 05:21:09,154 - INFO - Epoch 62/100 - Train Loss: 0.0666 - Val Acc: 0.8696
2026-04-05 05:21:09,467 - INFO - Epoch 63/100 - Train Loss: 0.0558 - Val Acc: 0.8551
2026-04-05 05:21:09,784 - INFO - Epoch 64/100 - Train Loss: 0.0566 - Val Acc: 0.8696
2026-04-05 05:21:10,100 - INFO - Epoch 65/100 - Train Loss: 0.0508 - Val Acc: 0.8696
2026-04-05 05:21:10,420 - INFO - Epoch 66/100 - Train Loss: 0.0550 - Val Acc: 0.8696
2026-04-05 05:21:10,733 - INFO - Epoch 67/100 - Train Loss: 0.0493 - Val Acc: 0.8696
2026-04-05 05:21:11,047 - INFO - Epoch 68/100 - Train Loss: 0.0512 - Val Acc: 0.8696
2026-04-05 05:21:11,368 - INFO - Epoch 69/100 - Train Loss: 0.0577 - Val Acc: 0.8696
2026-04-05 05:21:11,691 - INFO - Epoch 70/100 - Train Loss: 0.0520 - Val Acc: 0.8696
2026-04-05 05:21:12,007 - INFO - Epoch 71/100 - Train Loss: 0.0559 - Val Acc: 0.8696
2026-04-05 05:21:12,315 - INFO - Epoch 72/100 - Train Loss: 0.0444 - Val Acc: 0.8696
2026-04-05 05:21:12,633 - INFO - Epoch 73/100 - Train Loss: 0.0662 - Val Acc: 0.8696
2026-04-05 05:21:12,946 - INFO - Epoch 74/100 - Train Loss: 0.0586 - Val Acc: 0.8551
2026-04-05 05:21:13,273 - INFO - Epoch 75/100 - Train Loss: 0.0486 - Val Acc: 0.8696
2026-04-05 05:21:13,585 - INFO - Epoch 76/100 - Train Loss: 0.0539 - Val Acc: 0.8696
2026-04-05 05:21:13,904 - INFO - Epoch 77/100 - Train Loss: 0.0554 - Val Acc: 0.8696
2026-04-05 05:21:14,234 - INFO - Epoch 78/100 - Train Loss: 0.0405 - Val Acc: 0.8696
2026-04-05 05:21:14,591 - INFO - Epoch 79/100 - Train Loss: 0.0459 - Val Acc: 0.8696
2026-04-05 05:21:14,919 - INFO - Epoch 80/100 - Train Loss: 0.0468 - Val Acc: 0.8696
2026-04-05 05:21:15,232 - INFO - Epoch 81/100 - Train Loss: 0.0483 - Val Acc: 0.8551
2026-04-05 05:21:15,557 - INFO - Epoch 82/100 - Train Loss: 0.0490 - Val Acc: 0.8841
2026-04-05 05:21:15,880 - INFO - Epoch 83/100 - Train Loss: 0.0451 - Val Acc: 0.8696
2026-04-05 05:21:16,196 - INFO - Epoch 84/100 - Train Loss: 0.0468 - Val Acc: 0.8696
2026-04-05 05:21:16,522 - INFO - Epoch 85/100 - Train Loss: 0.0395 - Val Acc: 0.8696
2026-04-05 05:21:16,839 - INFO - Epoch 86/100 - Train Loss: 0.0496 - Val Acc: 0.8551
2026-04-05 05:21:17,153 - INFO - Epoch 87/100 - Train Loss: 0.0474 - Val Acc: 0.8696
2026-04-05 05:21:17,482 - INFO - Epoch 88/100 - Train Loss: 0.0582 - Val Acc: 0.8551
2026-04-05 05:21:17,807 - INFO - Epoch 89/100 - Train Loss: 0.0472 - Val Acc: 0.8696
2026-04-05 05:21:18,128 - INFO - Epoch 90/100 - Train Loss: 0.0385 - Val Acc: 0.8696
2026-04-05 05:21:18,439 - INFO - Epoch 91/100 - Train Loss: 0.0545 - Val Acc: 0.8551
2026-04-05 05:21:18,760 - INFO - Epoch 92/100 - Train Loss: 0.0400 - Val Acc: 0.8696
2026-04-05 05:21:19,073 - INFO - Epoch 93/100 - Train Loss: 0.0452 - Val Acc: 0.8551
2026-04-05 05:21:19,393 - INFO - Epoch 94/100 - Train Loss: 0.0434 - Val Acc: 0.8551
2026-04-05 05:21:19,718 - INFO - Epoch 95/100 - Train Loss: 0.0442 - Val Acc: 0.8551
2026-04-05 05:21:20,063 - INFO - Epoch 96/100 - Train Loss: 0.0432 - Val Acc: 0.8551
2026-04-05 05:21:20,407 - INFO - Epoch 97/100 - Train Loss: 0.0342 - Val Acc: 0.8696
2026-04-05 05:21:20,728 - INFO - Epoch 98/100 - Train Loss: 0.0565 - Val Acc: 0.8551
2026-04-05 05:21:21,052 - INFO - Epoch 99/100 - Train Loss: 0.0403 - Val Acc: 0.8551
2026-04-05 05:21:21,362 - INFO - Epoch 100/100 - Train Loss: 0.0416 - Val Acc: 0.8551
2026-04-05 05:21:21,732 - INFO - Fold 1 logically complete. Tensor memory bounds cleared cleanly.
2026-04-05 05:21:21,736 - INFO - Original class distribution: [277 344]
2026-04-05 05:21:21,737 - INFO - Training device bound securely to: cuda
2026-04-05 05:21:21,753 - INFO - After SMOTE-ENN deployment: [344 288]

Fold 2:   0%|          | 0/100 [00:00<?, ?it/s]

2026-04-05 05:21:22,098 - INFO - Epoch 1/100 - Train Loss: 0.5916 - Val Acc: 0.8696
2026-04-05 05:21:22,426 - INFO - Epoch 2/100 - Train Loss: 0.3754 - Val Acc: 0.8986
2026-04-05 05:21:22,759 - INFO - Epoch 3/100 - Train Loss: 0.2506 - Val Acc: 0.8986
2026-04-05 05:21:23,082 - INFO - Epoch 4/100 - Train Loss: 0.2260 - Val Acc: 0.8841
2026-04-05 05:21:23,407 - INFO - Epoch 5/100 - Train Loss: 0.2060 - Val Acc: 0.8986
2026-04-05 05:21:23,726 - INFO - Epoch 6/100 - Train Loss: 0.2074 - Val Acc: 0.8696
2026-04-05 05:21:24,042 - INFO - Epoch 7/100 - Train Loss: 0.1889 - Val Acc: 0.8841
2026-04-05 05:21:24,383 - INFO - Epoch 8/100 - Train Loss: 0.1804 - Val Acc: 0.8696
2026-04-05 05:21:24,722 - INFO - Epoch 9/100 - Train Loss: 0.1733 - Val Acc: 0.8841
2026-04-05 05:21:25,052 - INFO - Epoch 10/100 - Train Loss: 0.1794 - Val Acc: 0.8841
2026-04-05 05:21:25,379 - INFO - Epoch 11/100 - Train Loss: 0.1553 - Val Acc: 0.8841
2026-04-05 05:21:25,701 - INFO - Epoch 12/100 - Train Loss: 0.1559 - Val Acc: 0.8696
2026-04-05 05:21:26,014 - INFO - Epoch 13/100 - Train Loss: 0.1507 - Val Acc: 0.8841
2026-04-05 05:21:26,326 - INFO - Epoch 14/100 - Train Loss: 0.1542 - Val Acc: 0.8841
2026-04-05 05:21:26,655 - INFO - Epoch 15/100 - Train Loss: 0.1561 - Val Acc: 0.8841
2026-04-05 05:21:26,975 - INFO - Epoch 16/100 - Train Loss: 0.1388 - Val Acc: 0.8841
2026-04-05 05:21:27,300 - INFO - Epoch 17/100 - Train Loss: 0.1335 - Val Acc: 0.8841
2026-04-05 05:21:27,612 - INFO - Epoch 18/100 - Train Loss: 0.1372 - Val Acc: 0.8841
2026-04-05 05:21:27,933 - INFO - Epoch 19/100 - Train Loss: 0.1313 - Val Acc: 0.8841
2026-04-05 05:21:28,254 - INFO - Epoch 20/100 - Train Loss: 0.1290 - Val Acc: 0.8841
2026-04-05 05:21:28,575 - INFO - Epoch 21/100 - Train Loss: 0.1212 - Val Acc: 0.8696
2026-04-05 05:21:28,898 - INFO - Epoch 22/100 - Train Loss: 0.1224 - Val Acc: 0.8696
2026-04-05 05:21:29,213 - INFO - Epoch 23/100 - Train Loss: 0.1239 - Val Acc: 0.8696
2026-04-05 05:21:29,543 - INFO - Epoch 24/100 - Train Loss: 0.1065 - Val Acc: 0.8696
2026-04-05 05:21:29,864 - INFO - Epoch 25/100 - Train Loss: 0.1251 - Val Acc: 0.8551
2026-04-05 05:21:30,182 - INFO - Epoch 26/100 - Train Loss: 0.1199 - Val Acc: 0.8551
2026-04-05 05:21:30,488 - INFO - Epoch 27/100 - Train Loss: 0.1211 - Val Acc: 0.8696
2026-04-05 05:21:30,809 - INFO - Epoch 28/100 - Train Loss: 0.1026 - Val Acc: 0.8551
2026-04-05 05:21:31,128 - INFO - Epoch 29/100 - Train Loss: 0.1069 - Val Acc: 0.8696
2026-04-05 05:21:31,454 - INFO - Epoch 30/100 - Train Loss: 0.1112 - Val Acc: 0.8551
2026-04-05 05:21:31,782 - INFO - Epoch 31/100 - Train Loss: 0.1004 - Val Acc: 0.8551
2026-04-05 05:21:32,104 - INFO - Epoch 32/100 - Train Loss: 0.1090 - Val Acc: 0.8696
2026-04-05 05:21:32,424 - INFO - Epoch 33/100 - Train Loss: 0.0982 - Val Acc: 0.8696
2026-04-05 05:21:32,737 - INFO - Epoch 34/100 - Train Loss: 0.0906 - Val Acc: 0.8696
2026-04-05 05:21:33,053 - INFO - Epoch 35/100 - Train Loss: 0.0880 - Val Acc: 0.8551
2026-04-05 05:21:33,370 - INFO - Epoch 36/100 - Train Loss: 0.0866 - Val Acc: 0.8696
2026-04-05 05:21:33,687 - INFO - Epoch 37/100 - Train Loss: 0.0880 - Val Acc: 0.8696
2026-04-05 05:21:33,997 - INFO - Epoch 38/100 - Train Loss: 0.0824 - Val Acc: 0.8696
2026-04-05 05:21:34,342 - INFO - Epoch 39/100 - Train Loss: 0.0873 - Val Acc: 0.8551
2026-04-05 05:21:34,688 - INFO - Epoch 40/100 - Train Loss: 0.0827 - Val Acc: 0.8696
2026-04-05 05:21:34,998 - INFO - Epoch 41/100 - Train Loss: 0.0888 - Val Acc: 0.8696
2026-04-05 05:21:35,312 - INFO - Epoch 42/100 - Train Loss: 0.0784 - Val Acc: 0.8696
2026-04-05 05:21:35,619 - INFO - Epoch 43/100 - Train Loss: 0.0878 - Val Acc: 0.8551
2026-04-05 05:21:35,925 - INFO - Epoch 44/100 - Train Loss: 0.0776 - Val Acc: 0.8551
2026-04-05 05:21:36,243 - INFO - Epoch 45/100 - Train Loss: 0.0763 - Val Acc: 0.8551
2026-04-05 05:21:36,550 - INFO - Epoch 46/100 - Train Loss: 0.0766 - Val Acc: 0.8696
2026-04-05 05:21:36,860 - INFO - Epoch 47/100 - Train Loss: 0.0856 - Val Acc: 0.8551
2026-04-05 05:21:37,175 - INFO - Epoch 48/100 - Train Loss: 0.0762 - Val Acc: 0.8551
2026-04-05 05:21:37,496 - INFO - Epoch 49/100 - Train Loss: 0.0755 - Val Acc: 0.8551
2026-04-05 05:21:37,807 - INFO - Epoch 50/100 - Train Loss: 0.0745 - Val Acc: 0.8696
2026-04-05 05:21:38,126 - INFO - Epoch 51/100 - Train Loss: 0.0643 - Val Acc: 0.8551
2026-04-05 05:21:38,449 - INFO - Epoch 52/100 - Train Loss: 0.0801 - Val Acc: 0.8841
2026-04-05 05:21:38,766 - INFO - Epoch 53/100 - Train Loss: 0.0640 - Val Acc: 0.8696
2026-04-05 05:21:39,084 - INFO - Epoch 54/100 - Train Loss: 0.0782 - Val Acc: 0.8696
2026-04-05 05:21:39,403 - INFO - Epoch 55/100 - Train Loss: 0.0644 - Val Acc: 0.8696
2026-04-05 05:21:39,730 - INFO - Epoch 56/100 - Train Loss: 0.0573 - Val Acc: 0.8406
2026-04-05 05:21:40,057 - INFO - Epoch 57/100 - Train Loss: 0.0721 - Val Acc: 0.8696
2026-04-05 05:21:40,379 - INFO - Epoch 58/100 - Train Loss: 0.0749 - Val Acc: 0.8551
2026-04-05 05:21:40,687 - INFO - Epoch 59/100 - Train Loss: 0.0771 - Val Acc: 0.8551
2026-04-05 05:21:41,018 - INFO - Epoch 60/100 - Train Loss: 0.0634 - Val Acc: 0.8551
2026-04-05 05:21:41,332 - INFO - Epoch 61/100 - Train Loss: 0.0686 - Val Acc: 0.8406
2026-04-05 05:21:41,657 - INFO - Epoch 62/100 - Train Loss: 0.0579 - Val Acc: 0.8406
2026-04-05 05:21:41,981 - INFO - Epoch 63/100 - Train Loss: 0.0496 - Val Acc: 0.8551
2026-04-05 05:21:42,304 - INFO - Epoch 64/100 - Train Loss: 0.0544 - Val Acc: 0.8551
2026-04-05 05:21:42,628 - INFO - Epoch 65/100 - Train Loss: 0.0514 - Val Acc: 0.8551
2026-04-05 05:21:42,943 - INFO - Epoch 66/100 - Train Loss: 0.0540 - Val Acc: 0.8696
2026-04-05 05:21:43,261 - INFO - Epoch 67/100 - Train Loss: 0.0594 - Val Acc: 0.8696
2026-04-05 05:21:43,572 - INFO - Epoch 68/100 - Train Loss: 0.0585 - Val Acc: 0.8551
2026-04-05 05:21:43,891 - INFO - Epoch 69/100 - Train Loss: 0.0512 - Val Acc: 0.8551
2026-04-05 05:21:44,218 - INFO - Epoch 70/100 - Train Loss: 0.0409 - Val Acc: 0.8551
2026-04-05 05:21:44,567 - INFO - Epoch 71/100 - Train Loss: 0.0456 - Val Acc: 0.8551
2026-04-05 05:21:44,893 - INFO - Epoch 72/100 - Train Loss: 0.0494 - Val Acc: 0.8551
2026-04-05 05:21:45,212 - INFO - Epoch 73/100 - Train Loss: 0.0567 - Val Acc: 0.8551
2026-04-05 05:21:45,535 - INFO - Epoch 74/100 - Train Loss: 0.0517 - Val Acc: 0.8551
2026-04-05 05:21:45,855 - INFO - Epoch 75/100 - Train Loss: 0.0524 - Val Acc: 0.8406
2026-04-05 05:21:46,169 - INFO - Epoch 76/100 - Train Loss: 0.0530 - Val Acc: 0.8406
2026-04-05 05:21:46,486 - INFO - Epoch 77/100 - Train Loss: 0.0446 - Val Acc: 0.8551
2026-04-05 05:21:46,795 - INFO - Epoch 78/100 - Train Loss: 0.0571 - Val Acc: 0.8551
2026-04-05 05:21:47,110 - INFO - Epoch 79/100 - Train Loss: 0.0469 - Val Acc: 0.8551
2026-04-05 05:21:47,428 - INFO - Epoch 80/100 - Train Loss: 0.0497 - Val Acc: 0.8261
2026-04-05 05:21:47,743 - INFO - Epoch 81/100 - Train Loss: 0.0489 - Val Acc: 0.8551
2026-04-05 05:21:48,057 - INFO - Epoch 82/100 - Train Loss: 0.0600 - Val Acc: 0.8551
2026-04-05 05:21:48,385 - INFO - Epoch 83/100 - Train Loss: 0.0512 - Val Acc: 0.8551
2026-04-05 05:21:48,716 - INFO - Epoch 84/100 - Train Loss: 0.0407 - Val Acc: 0.8551
2026-04-05 05:21:49,041 - INFO - Epoch 85/100 - Train Loss: 0.0483 - Val Acc: 0.8551
2026-04-05 05:21:49,357 - INFO - Epoch 86/100 - Train Loss: 0.0457 - Val Acc: 0.8551
2026-04-05 05:21:49,667 - INFO - Epoch 87/100 - Train Loss: 0.0463 - Val Acc: 0.8551
2026-04-05 05:21:50,001 - INFO - Epoch 88/100 - Train Loss: 0.0418 - Val Acc: 0.8406
2026-04-05 05:21:50,324 - INFO - Epoch 89/100 - Train Loss: 0.0481 - Val Acc: 0.8551
2026-04-05 05:21:50,647 - INFO - Epoch 90/100 - Train Loss: 0.0334 - Val Acc: 0.8551
2026-04-05 05:21:50,974 - INFO - Epoch 91/100 - Train Loss: 0.0435 - Val Acc: 0.8406
2026-04-05 05:21:51,292 - INFO - Epoch 92/100 - Train Loss: 0.0476 - Val Acc: 0.8406
2026-04-05 05:21:51,608 - INFO - Epoch 93/100 - Train Loss: 0.0400 - Val Acc: 0.8406
2026-04-05 05:21:51,937 - INFO - Epoch 94/100 - Train Loss: 0.0319 - Val Acc: 0.8551
2026-04-05 05:21:52,255 - INFO - Epoch 95/100 - Train Loss: 0.0511 - Val Acc: 0.8406
2026-04-05 05:21:52,569 - INFO - Epoch 96/100 - Train Loss: 0.0394 - Val Acc: 0.8261
2026-04-05 05:21:52,883 - INFO - Epoch 97/100 - Train Loss: 0.0377 - Val Acc: 0.8261
2026-04-05 05:21:53,205 - INFO - Epoch 98/100 - Train Loss: 0.0397 - Val Acc: 0.8261
2026-04-05 05:21:53,531 - INFO - Epoch 99/100 - Train Loss: 0.0395 - Val Acc: 0.8261
2026-04-05 05:21:53,850 - INFO - Epoch 100/100 - Train Loss: 0.0494 - Val Acc: 0.8551
2026-04-05 05:21:54,203 - INFO - Fold 2 logically complete. Tensor memory bounds cleared cleanly.
2026-04-05 05:21:54,207 - INFO - Original class distribution: [277 344]
2026-04-05 05:21:54,208 - INFO - Training device bound securely to: cuda
2026-04-05 05:21:54,223 - INFO - After SMOTE-ENN deployment: [344 291]

Fold 3:   0%|          | 0/100 [00:00<?, ?it/s]

2026-04-05 05:21:54,582 - INFO - Epoch 1/100 - Train Loss: 0.6131 - Val Acc: 0.8986
2026-04-05 05:21:54,900 - INFO - Epoch 2/100 - Train Loss: 0.3997 - Val Acc: 0.8986
2026-04-05 05:21:55,224 - INFO - Epoch 3/100 - Train Loss: 0.2648 - Val Acc: 0.9130
2026-04-05 05:21:55,540 - INFO - Epoch 4/100 - Train Loss: 0.2176 - Val Acc: 0.9130
2026-04-05 05:21:55,852 - INFO - Epoch 5/100 - Train Loss: 0.2050 - Val Acc: 0.9130
2026-04-05 05:21:56,162 - INFO - Epoch 6/100 - Train Loss: 0.1893 - Val Acc: 0.9130
2026-04-05 05:21:56,475 - INFO - Epoch 7/100 - Train Loss: 0.1800 - Val Acc: 0.9130
2026-04-05 05:21:56,797 - INFO - Epoch 8/100 - Train Loss: 0.1688 - Val Acc: 0.9130
2026-04-05 05:21:57,128 - INFO - Epoch 9/100 - Train Loss: 0.1622 - Val Acc: 0.9130
2026-04-05 05:21:57,438 - INFO - Epoch 10/100 - Train Loss: 0.1620 - Val Acc: 0.9130
2026-04-05 05:21:57,745 - INFO - Epoch 11/100 - Train Loss: 0.1617 - Val Acc: 0.9130
2026-04-05 05:21:58,058 - INFO - Epoch 12/100 - Train Loss: 0.1565 - Val Acc: 0.9130
2026-04-05 05:21:58,381 - INFO - Epoch 13/100 - Train Loss: 0.1567 - Val Acc: 0.9130
2026-04-05 05:21:58,690 - INFO - Epoch 14/100 - Train Loss: 0.1551 - Val Acc: 0.9130
2026-04-05 05:21:59,000 - INFO - Epoch 15/100 - Train Loss: 0.1485 - Val Acc: 0.9130
2026-04-05 05:21:59,320 - INFO - Epoch 16/100 - Train Loss: 0.1428 - Val Acc: 0.9130
2026-04-05 05:21:59,630 - INFO - Epoch 17/100 - Train Loss: 0.1400 - Val Acc: 0.9130
2026-04-05 05:21:59,946 - INFO - Epoch 18/100 - Train Loss: 0.1322 - Val Acc: 0.9130
2026-04-05 05:22:00,258 - INFO - Epoch 19/100 - Train Loss: 0.1407 - Val Acc: 0.9130
2026-04-05 05:22:00,587 - INFO - Epoch 20/100 - Train Loss: 0.1294 - Val Acc: 0.9130
2026-04-05 05:22:00,903 - INFO - Epoch 21/100 - Train Loss: 0.1295 - Val Acc: 0.9130
2026-04-05 05:22:01,222 - INFO - Epoch 22/100 - Train Loss: 0.1213 - Val Acc: 0.9130
2026-04-05 05:22:01,544 - INFO - Epoch 23/100 - Train Loss: 0.1168 - Val Acc: 0.9130
2026-04-05 05:22:01,851 - INFO - Epoch 24/100 - Train Loss: 0.1297 - Val Acc: 0.9130
2026-04-05 05:22:02,158 - INFO - Epoch 25/100 - Train Loss: 0.1181 - Val Acc: 0.9130
2026-04-05 05:22:02,482 - INFO - Epoch 26/100 - Train Loss: 0.1218 - Val Acc: 0.9130
2026-04-05 05:22:02,799 - INFO - Epoch 27/100 - Train Loss: 0.1110 - Val Acc: 0.9130
2026-04-05 05:22:03,108 - INFO - Epoch 28/100 - Train Loss: 0.1063 - Val Acc: 0.9130
2026-04-05 05:22:03,414 - INFO - Epoch 29/100 - Train Loss: 0.1085 - Val Acc: 0.9130
2026-04-05 05:22:03,727 - INFO - Epoch 30/100 - Train Loss: 0.1038 - Val Acc: 0.9130
2026-04-05 05:22:04,052 - INFO - Epoch 31/100 - Train Loss: 0.1053 - Val Acc: 0.8986
2026-04-05 05:22:04,395 - INFO - Epoch 32/100 - Train Loss: 0.1012 - Val Acc: 0.9130
2026-04-05 05:22:04,741 - INFO - Epoch 33/100 - Train Loss: 0.1082 - Val Acc: 0.8986
2026-04-05 05:22:05,063 - INFO - Epoch 34/100 - Train Loss: 0.1006 - Val Acc: 0.8986
2026-04-05 05:22:05,369 - INFO - Epoch 35/100 - Train Loss: 0.0967 - Val Acc: 0.8986
2026-04-05 05:22:05,687 - INFO - Epoch 36/100 - Train Loss: 0.0885 - Val Acc: 0.8986
2026-04-05 05:22:06,007 - INFO - Epoch 37/100 - Train Loss: 0.0995 - Val Acc: 0.8986
2026-04-05 05:22:06,325 - INFO - Epoch 38/100 - Train Loss: 0.0843 - Val Acc: 0.8986
2026-04-05 05:22:06,641 - INFO - Epoch 39/100 - Train Loss: 0.0865 - Val Acc: 0.8986
2026-04-05 05:22:06,952 - INFO - Epoch 40/100 - Train Loss: 0.0880 - Val Acc: 0.9130
2026-04-05 05:22:07,258 - INFO - Epoch 41/100 - Train Loss: 0.0907 - Val Acc: 0.8986
2026-04-05 05:22:07,581 - INFO - Epoch 42/100 - Train Loss: 0.0837 - Val Acc: 0.8986
2026-04-05 05:22:07,897 - INFO - Epoch 43/100 - Train Loss: 0.0847 - Val Acc: 0.8986
2026-04-05 05:22:08,204 - INFO - Epoch 44/100 - Train Loss: 0.0835 - Val Acc: 0.8986
2026-04-05 05:22:08,516 - INFO - Epoch 45/100 - Train Loss: 0.0742 - Val Acc: 0.8986
2026-04-05 05:22:08,843 - INFO - Epoch 46/100 - Train Loss: 0.0872 - Val Acc: 0.8986
2026-04-05 05:22:09,165 - INFO - Epoch 47/100 - Train Loss: 0.0727 - Val Acc: 0.8986
2026-04-05 05:22:09,471 - INFO - Epoch 48/100 - Train Loss: 0.0760 - Val Acc: 0.8986
2026-04-05 05:22:09,797 - INFO - Epoch 49/100 - Train Loss: 0.0692 - Val Acc: 0.8986
2026-04-05 05:22:10,108 - INFO - Epoch 50/100 - Train Loss: 0.0750 - Val Acc: 0.8986
2026-04-05 05:22:10,421 - INFO - Epoch 51/100 - Train Loss: 0.0776 - Val Acc: 0.8986
2026-04-05 05:22:10,740 - INFO - Epoch 52/100 - Train Loss: 0.0777 - Val Acc: 0.8986
2026-04-05 05:22:11,052 - INFO - Epoch 53/100 - Train Loss: 0.0670 - Val Acc: 0.8986
2026-04-05 05:22:11,370 - INFO - Epoch 54/100 - Train Loss: 0.0793 - Val Acc: 0.8986
2026-04-05 05:22:11,700 - INFO - Epoch 55/100 - Train Loss: 0.0697 - Val Acc: 0.8986
2026-04-05 05:22:12,026 - INFO - Epoch 56/100 - Train Loss: 0.0740 - Val Acc: 0.8986
2026-04-05 05:22:12,343 - INFO - Epoch 57/100 - Train Loss: 0.0773 - Val Acc: 0.8986
2026-04-05 05:22:12,660 - INFO - Epoch 58/100 - Train Loss: 0.0750 - Val Acc: 0.8986
2026-04-05 05:22:12,994 - INFO - Epoch 59/100 - Train Loss: 0.0643 - Val Acc: 0.8986
2026-04-05 05:22:13,324 - INFO - Epoch 60/100 - Train Loss: 0.0562 - Val Acc: 0.8986
2026-04-05 05:22:13,652 - INFO - Epoch 61/100 - Train Loss: 0.0637 - Val Acc: 0.8986
2026-04-05 05:22:13,976 - INFO - Epoch 62/100 - Train Loss: 0.0583 - Val Acc: 0.8986
2026-04-05 05:22:14,314 - INFO - Epoch 63/100 - Train Loss: 0.0538 - Val Acc: 0.8986
2026-04-05 05:22:14,655 - INFO - Epoch 64/100 - Train Loss: 0.0612 - Val Acc: 0.8986
2026-04-05 05:22:14,975 - INFO - Epoch 65/100 - Train Loss: 0.0516 - Val Acc: 0.8986
2026-04-05 05:22:15,288 - INFO - Epoch 66/100 - Train Loss: 0.0636 - Val Acc: 0.8841
2026-04-05 05:22:15,605 - INFO - Epoch 67/100 - Train Loss: 0.0627 - Val Acc: 0.8986
2026-04-05 05:22:15,928 - INFO - Epoch 68/100 - Train Loss: 0.0742 - Val Acc: 0.9130
2026-04-05 05:22:16,244 - INFO - Epoch 69/100 - Train Loss: 0.0679 - Val Acc: 0.8841
2026-04-05 05:22:16,557 - INFO - Epoch 70/100 - Train Loss: 0.0616 - Val Acc: 0.9130
2026-04-05 05:22:16,867 - INFO - Epoch 71/100 - Train Loss: 0.0517 - Val Acc: 0.8986
2026-04-05 05:22:17,176 - INFO - Epoch 72/100 - Train Loss: 0.0526 - Val Acc: 0.8986
2026-04-05 05:22:17,499 - INFO - Epoch 73/100 - Train Loss: 0.0529 - Val Acc: 0.8841
2026-04-05 05:22:17,817 - INFO - Epoch 74/100 - Train Loss: 0.0475 - Val Acc: 0.9130
2026-04-05 05:22:18,144 - INFO - Epoch 75/100 - Train Loss: 0.0481 - Val Acc: 0.9130
2026-04-05 05:22:18,477 - INFO - Epoch 76/100 - Train Loss: 0.0649 - Val Acc: 0.8841
2026-04-05 05:22:18,822 - INFO - Epoch 77/100 - Train Loss: 0.0497 - Val Acc: 0.8841
2026-04-05 05:22:19,130 - INFO - Epoch 78/100 - Train Loss: 0.0551 - Val Acc: 0.8841
2026-04-05 05:22:19,453 - INFO - Epoch 79/100 - Train Loss: 0.0474 - Val Acc: 0.8986
2026-04-05 05:22:19,781 - INFO - Epoch 80/100 - Train Loss: 0.0540 - Val Acc: 0.8986
2026-04-05 05:22:20,103 - INFO - Epoch 81/100 - Train Loss: 0.0506 - Val Acc: 0.8841
2026-04-05 05:22:20,420 - INFO - Epoch 82/100 - Train Loss: 0.0453 - Val Acc: 0.8986
2026-04-05 05:22:20,737 - INFO - Epoch 83/100 - Train Loss: 0.0409 - Val Acc: 0.8841
2026-04-05 05:22:21,048 - INFO - Epoch 84/100 - Train Loss: 0.0443 - Val Acc: 0.8841
2026-04-05 05:22:21,363 - INFO - Epoch 85/100 - Train Loss: 0.0430 - Val Acc: 0.8986
2026-04-05 05:22:21,691 - INFO - Epoch 86/100 - Train Loss: 0.0382 - Val Acc: 0.8841
2026-04-05 05:22:22,007 - INFO - Epoch 87/100 - Train Loss: 0.0354 - Val Acc: 0.8696
2026-04-05 05:22:22,329 - INFO - Epoch 88/100 - Train Loss: 0.0611 - Val Acc: 0.8696
2026-04-05 05:22:22,645 - INFO - Epoch 89/100 - Train Loss: 0.0432 - Val Acc: 0.8696
2026-04-05 05:22:22,959 - INFO - Epoch 90/100 - Train Loss: 0.0386 - Val Acc: 0.8696
2026-04-05 05:22:23,282 - INFO - Epoch 91/100 - Train Loss: 0.0450 - Val Acc: 0.8696
2026-04-05 05:22:23,608 - INFO - Epoch 92/100 - Train Loss: 0.0433 - Val Acc: 0.8696
2026-04-05 05:22:23,920 - INFO - Epoch 93/100 - Train Loss: 0.0422 - Val Acc: 0.8696
2026-04-05 05:22:24,247 - INFO - Epoch 94/100 - Train Loss: 0.0495 - Val Acc: 0.8696
2026-04-05 05:22:24,585 - INFO - Epoch 95/100 - Train Loss: 0.0443 - Val Acc: 0.8696
2026-04-05 05:22:24,893 - INFO - Epoch 96/100 - Train Loss: 0.0302 - Val Acc: 0.8696
2026-04-05 05:22:25,208 - INFO - Epoch 97/100 - Train Loss: 0.0385 - Val Acc: 0.8696
2026-04-05 05:22:25,535 - INFO - Epoch 98/100 - Train Loss: 0.0331 - Val Acc: 0.8696
2026-04-05 05:22:25,845 - INFO - Epoch 99/100 - Train Loss: 0.0404 - Val Acc: 0.8841
2026-04-05 05:22:26,175 - INFO - Epoch 100/100 - Train Loss: 0.0315 - Val Acc: 0.8841
2026-04-05 05:22:26,533 - INFO - Fold 3 logically complete. Tensor memory bounds cleared cleanly.
2026-04-05 05:22:26,537 - INFO - Original class distribution: [276 345]
2026-04-05 05:22:26,538 - INFO - Training device bound securely to: cuda
2026-04-05 05:22:26,553 - INFO - After SMOTE-ENN deployment: [345 296]

Fold 4:   0%|          | 0/100 [00:00<?, ?it/s]

2026-04-05 05:22:26,958 - INFO - Epoch 1/100 - Train Loss: 0.5880 - Val Acc: 0.7246
2026-04-05 05:22:27,280 - INFO - Epoch 2/100 - Train Loss: 0.3375 - Val Acc: 0.7681
2026-04-05 05:22:27,614 - INFO - Epoch 3/100 - Train Loss: 0.2101 - Val Acc: 0.7681
2026-04-05 05:22:27,943 - INFO - Epoch 4/100 - Train Loss: 0.1872 - Val Acc: 0.7826
2026-04-05 05:22:28,275 - INFO - Epoch 5/100 - Train Loss: 0.1579 - Val Acc: 0.7681
2026-04-05 05:22:28,615 - INFO - Epoch 6/100 - Train Loss: 0.1624 - Val Acc: 0.7971
2026-04-05 05:22:28,940 - INFO - Epoch 7/100 - Train Loss: 0.1618 - Val Acc: 0.7971
2026-04-05 05:22:29,256 - INFO - Epoch 8/100 - Train Loss: 0.1498 - Val Acc: 0.7826
2026-04-05 05:22:29,571 - INFO - Epoch 9/100 - Train Loss: 0.1380 - Val Acc: 0.7681
2026-04-05 05:22:29,883 - INFO - Epoch 10/100 - Train Loss: 0.1292 - Val Acc: 0.7971
2026-04-05 05:22:30,212 - INFO - Epoch 11/100 - Train Loss: 0.1272 - Val Acc: 0.7971
2026-04-05 05:22:30,545 - INFO - Epoch 12/100 - Train Loss: 0.1288 - Val Acc: 0.7826
2026-04-05 05:22:30,877 - INFO - Epoch 13/100 - Train Loss: 0.1241 - Val Acc: 0.7826
2026-04-05 05:22:31,201 - INFO - Epoch 14/100 - Train Loss: 0.1187 - Val Acc: 0.7826
2026-04-05 05:22:31,529 - INFO - Epoch 15/100 - Train Loss: 0.1162 - Val Acc: 0.7826
2026-04-05 05:22:31,846 - INFO - Epoch 16/100 - Train Loss: 0.1035 - Val Acc: 0.7826
2026-04-05 05:22:32,179 - INFO - Epoch 17/100 - Train Loss: 0.1143 - Val Acc: 0.7826
2026-04-05 05:22:32,502 - INFO - Epoch 18/100 - Train Loss: 0.1109 - Val Acc: 0.7826
2026-04-05 05:22:32,818 - INFO - Epoch 19/100 - Train Loss: 0.0895 - Val Acc: 0.7826
2026-04-05 05:22:33,147 - INFO - Epoch 20/100 - Train Loss: 0.0916 - Val Acc: 0.7826
2026-04-05 05:22:33,467 - INFO - Epoch 21/100 - Train Loss: 0.0896 - Val Acc: 0.7826
2026-04-05 05:22:33,807 - INFO - Epoch 22/100 - Train Loss: 0.0816 - Val Acc: 0.7826
2026-04-05 05:22:34,144 - INFO - Epoch 23/100 - Train Loss: 0.0993 - Val Acc: 0.7826
2026-04-05 05:22:34,477 - INFO - Epoch 24/100 - Train Loss: 0.0925 - Val Acc: 0.8116
2026-04-05 05:22:34,823 - INFO - Epoch 25/100 - Train Loss: 0.1045 - Val Acc: 0.7971
2026-04-05 05:22:35,152 - INFO - Epoch 26/100 - Train Loss: 0.1080 - Val Acc: 0.7971
2026-04-05 05:22:35,477 - INFO - Epoch 27/100 - Train Loss: 0.0872 - Val Acc: 0.7971
2026-04-05 05:22:35,793 - INFO - Epoch 28/100 - Train Loss: 0.0876 - Val Acc: 0.7971
2026-04-05 05:22:36,123 - INFO - Epoch 29/100 - Train Loss: 0.0788 - Val Acc: 0.7971
2026-04-05 05:22:36,447 - INFO - Epoch 30/100 - Train Loss: 0.0779 - Val Acc: 0.7971
2026-04-05 05:22:36,777 - INFO - Epoch 31/100 - Train Loss: 0.0746 - Val Acc: 0.7826
2026-04-05 05:22:37,097 - INFO - Epoch 32/100 - Train Loss: 0.0747 - Val Acc: 0.7826
2026-04-05 05:22:37,425 - INFO - Epoch 33/100 - Train Loss: 0.0783 - Val Acc: 0.7826
2026-04-05 05:22:37,749 - INFO - Epoch 34/100 - Train Loss: 0.0628 - Val Acc: 0.7826
2026-04-05 05:22:38,080 - INFO - Epoch 35/100 - Train Loss: 0.0827 - Val Acc: 0.7826
2026-04-05 05:22:38,415 - INFO - Epoch 36/100 - Train Loss: 0.0719 - Val Acc: 0.7681
2026-04-05 05:22:38,742 - INFO - Epoch 37/100 - Train Loss: 0.0710 - Val Acc: 0.7681
2026-04-05 05:22:39,075 - INFO - Epoch 38/100 - Train Loss: 0.0797 - Val Acc: 0.7681
2026-04-05 05:22:39,408 - INFO - Epoch 39/100 - Train Loss: 0.0689 - Val Acc: 0.7826
2026-04-05 05:22:39,739 - INFO - Epoch 40/100 - Train Loss: 0.0611 - Val Acc: 0.7826
2026-04-05 05:22:40,054 - INFO - Epoch 41/100 - Train Loss: 0.0769 - Val Acc: 0.7681
2026-04-05 05:22:40,375 - INFO - Epoch 42/100 - Train Loss: 0.0609 - Val Acc: 0.7826
2026-04-05 05:22:40,690 - INFO - Epoch 43/100 - Train Loss: 0.0632 - Val Acc: 0.7681
2026-04-05 05:22:41,013 - INFO - Epoch 44/100 - Train Loss: 0.0583 - Val Acc: 0.7826
2026-04-05 05:22:41,339 - INFO - Epoch 45/100 - Train Loss: 0.0628 - Val Acc: 0.7826
2026-04-05 05:22:41,664 - INFO - Epoch 46/100 - Train Loss: 0.0580 - Val Acc: 0.7971
2026-04-05 05:22:41,989 - INFO - Epoch 47/100 - Train Loss: 0.0654 - Val Acc: 0.7826
2026-04-05 05:22:42,308 - INFO - Epoch 48/100 - Train Loss: 0.0552 - Val Acc: 0.7826
2026-04-05 05:22:42,637 - INFO - Epoch 49/100 - Train Loss: 0.0606 - Val Acc: 0.7681
2026-04-05 05:22:42,973 - INFO - Epoch 50/100 - Train Loss: 0.0571 - Val Acc: 0.7536
2026-04-05 05:22:43,293 - INFO - Epoch 51/100 - Train Loss: 0.0521 - Val Acc: 0.7536
2026-04-05 05:22:43,629 - INFO - Epoch 52/100 - Train Loss: 0.0422 - Val Acc: 0.7681
2026-04-05 05:22:43,962 - INFO - Epoch 53/100 - Train Loss: 0.0502 - Val Acc: 0.7681
2026-04-05 05:22:44,314 - INFO - Epoch 54/100 - Train Loss: 0.0559 - Val Acc: 0.7681
2026-04-05 05:22:44,663 - INFO - Epoch 55/100 - Train Loss: 0.0461 - Val Acc: 0.7536
2026-04-05 05:22:44,985 - INFO - Epoch 56/100 - Train Loss: 0.0587 - Val Acc: 0.7826
2026-04-05 05:22:45,305 - INFO - Epoch 57/100 - Train Loss: 0.0460 - Val Acc: 0.7681
2026-04-05 05:22:45,634 - INFO - Epoch 58/100 - Train Loss: 0.0493 - Val Acc: 0.7826
2026-04-05 05:22:45,967 - INFO - Epoch 59/100 - Train Loss: 0.0435 - Val Acc: 0.7826
2026-04-05 05:22:46,288 - INFO - Epoch 60/100 - Train Loss: 0.0399 - Val Acc: 0.7826
2026-04-05 05:22:46,611 - INFO - Epoch 61/100 - Train Loss: 0.0502 - Val Acc: 0.7681
2026-04-05 05:22:46,926 - INFO - Epoch 62/100 - Train Loss: 0.0483 - Val Acc: 0.7681
2026-04-05 05:22:47,245 - INFO - Epoch 63/100 - Train Loss: 0.0478 - Val Acc: 0.7536
2026-04-05 05:22:47,565 - INFO - Epoch 64/100 - Train Loss: 0.0499 - Val Acc: 0.7536
2026-04-05 05:22:47,887 - INFO - Epoch 65/100 - Train Loss: 0.0483 - Val Acc: 0.7681
2026-04-05 05:22:48,204 - INFO - Epoch 66/100 - Train Loss: 0.0469 - Val Acc: 0.7536
2026-04-05 05:22:48,523 - INFO - Epoch 67/100 - Train Loss: 0.0428 - Val Acc: 0.7681
2026-04-05 05:22:48,853 - INFO - Epoch 68/100 - Train Loss: 0.0390 - Val Acc: 0.7681
2026-04-05 05:22:49,176 - INFO - Epoch 69/100 - Train Loss: 0.0389 - Val Acc: 0.7536
2026-04-05 05:22:49,492 - INFO - Epoch 70/100 - Train Loss: 0.0459 - Val Acc: 0.7681
2026-04-05 05:22:49,810 - INFO - Epoch 71/100 - Train Loss: 0.0455 - Val Acc: 0.7681
2026-04-05 05:22:50,146 - INFO - Epoch 72/100 - Train Loss: 0.0358 - Val Acc: 0.7681
2026-04-05 05:22:50,476 - INFO - Epoch 73/100 - Train Loss: 0.0333 - Val Acc: 0.7681
2026-04-05 05:22:50,806 - INFO - Epoch 74/100 - Train Loss: 0.0387 - Val Acc: 0.7681
2026-04-05 05:22:51,132 - INFO - Epoch 75/100 - Train Loss: 0.0385 - Val Acc: 0.7681
2026-04-05 05:22:51,452 - INFO - Epoch 76/100 - Train Loss: 0.0440 - Val Acc: 0.7681
2026-04-05 05:22:51,786 - INFO - Epoch 77/100 - Train Loss: 0.0452 - Val Acc: 0.7681
2026-04-05 05:22:52,123 - INFO - Epoch 78/100 - Train Loss: 0.0417 - Val Acc: 0.7681
2026-04-05 05:22:52,454 - INFO - Epoch 79/100 - Train Loss: 0.0484 - Val Acc: 0.7681
2026-04-05 05:22:52,777 - INFO - Epoch 80/100 - Train Loss: 0.0450 - Val Acc: 0.7681
2026-04-05 05:22:53,115 - INFO - Epoch 81/100 - Train Loss: 0.0300 - Val Acc: 0.7681
2026-04-05 05:22:53,437 - INFO - Epoch 82/100 - Train Loss: 0.0410 - Val Acc: 0.7681
2026-04-05 05:22:53,772 - INFO - Epoch 83/100 - Train Loss: 0.0431 - Val Acc: 0.7681
2026-04-05 05:22:54,095 - INFO - Epoch 84/100 - Train Loss: 0.0388 - Val Acc: 0.7536
2026-04-05 05:22:54,471 - INFO - Epoch 85/100 - Train Loss: 0.0309 - Val Acc: 0.7681
2026-04-05 05:22:54,833 - INFO - Epoch 86/100 - Train Loss: 0.0455 - Val Acc: 0.7681
2026-04-05 05:22:55,173 - INFO - Epoch 87/100 - Train Loss: 0.0390 - Val Acc: 0.7536
2026-04-05 05:22:55,504 - INFO - Epoch 88/100 - Train Loss: 0.0357 - Val Acc: 0.7536
2026-04-05 05:22:55,830 - INFO - Epoch 89/100 - Train Loss: 0.0270 - Val Acc: 0.7391
2026-04-05 05:22:56,164 - INFO - Epoch 90/100 - Train Loss: 0.0455 - Val Acc: 0.7536
2026-04-05 05:22:56,482 - INFO - Epoch 91/100 - Train Loss: 0.0393 - Val Acc: 0.7391
2026-04-05 05:22:56,820 - INFO - Epoch 92/100 - Train Loss: 0.0330 - Val Acc: 0.7681
2026-04-05 05:22:57,153 - INFO - Epoch 93/100 - Train Loss: 0.0281 - Val Acc: 0.7681
2026-04-05 05:22:57,488 - INFO - Epoch 94/100 - Train Loss: 0.0245 - Val Acc: 0.7681
2026-04-05 05:22:57,820 - INFO - Epoch 95/100 - Train Loss: 0.0284 - Val Acc: 0.7681
2026-04-05 05:22:58,154 - INFO - Epoch 96/100 - Train Loss: 0.0335 - Val Acc: 0.7681
2026-04-05 05:22:58,488 - INFO - Epoch 97/100 - Train Loss: 0.0274 - Val Acc: 0.7681
2026-04-05 05:22:58,816 - INFO - Epoch 98/100 - Train Loss: 0.0356 - Val Acc: 0.7536
2026-04-05 05:22:59,143 - INFO - Epoch 99/100 - Train Loss: 0.0326 - Val Acc: 0.7681
2026-04-05 05:22:59,473 - INFO - Epoch 100/100 - Train Loss: 0.0350 - Val Acc: 0.7681
2026-04-05 05:22:59,832 - INFO - Fold 4 logically complete. Tensor memory bounds cleared cleanly.
2026-04-05 05:22:59,836 - INFO - Original class distribution: [276 345]
2026-04-05 05:22:59,837 - INFO - Training device bound securely to: cuda
2026-04-05 05:22:59,853 - INFO - After SMOTE-ENN deployment: [345 287]

Fold 5:   0%|          | 0/100 [00:00<?, ?it/s]

2026-04-05 05:23:00,188 - INFO - Epoch 1/100 - Train Loss: 0.5669 - Val Acc: 0.7536
2026-04-05 05:23:00,509 - INFO - Epoch 2/100 - Train Loss: 0.3490 - Val Acc: 0.8551
2026-04-05 05:23:00,825 - INFO - Epoch 3/100 - Train Loss: 0.2393 - Val Acc: 0.7971
2026-04-05 05:23:01,146 - INFO - Epoch 4/100 - Train Loss: 0.1923 - Val Acc: 0.8116
2026-04-05 05:23:01,475 - INFO - Epoch 5/100 - Train Loss: 0.1728 - Val Acc: 0.8116
2026-04-05 05:23:01,814 - INFO - Epoch 6/100 - Train Loss: 0.1574 - Val Acc: 0.8261
2026-04-05 05:23:02,152 - INFO - Epoch 7/100 - Train Loss: 0.1587 - Val Acc: 0.8261
2026-04-05 05:23:02,478 - INFO - Epoch 8/100 - Train Loss: 0.1374 - Val Acc: 0.8261
2026-04-05 05:23:02,792 - INFO - Epoch 9/100 - Train Loss: 0.1337 - Val Acc: 0.8116
2026-04-05 05:23:03,113 - INFO - Epoch 10/100 - Train Loss: 0.1371 - Val Acc: 0.7971
2026-04-05 05:23:03,430 - INFO - Epoch 11/100 - Train Loss: 0.1398 - Val Acc: 0.8116
2026-04-05 05:23:03,743 - INFO - Epoch 12/100 - Train Loss: 0.1170 - Val Acc: 0.7971
2026-04-05 05:23:04,057 - INFO - Epoch 13/100 - Train Loss: 0.1287 - Val Acc: 0.8116
2026-04-05 05:23:04,405 - INFO - Epoch 14/100 - Train Loss: 0.1138 - Val Acc: 0.7826
2026-04-05 05:23:04,756 - INFO - Epoch 15/100 - Train Loss: 0.1156 - Val Acc: 0.7971
2026-04-05 05:23:05,073 - INFO - Epoch 16/100 - Train Loss: 0.1034 - Val Acc: 0.7826
2026-04-05 05:23:05,391 - INFO - Epoch 17/100 - Train Loss: 0.1098 - Val Acc: 0.7826
2026-04-05 05:23:05,700 - INFO - Epoch 18/100 - Train Loss: 0.1042 - Val Acc: 0.7826
2026-04-05 05:23:06,007 - INFO - Epoch 19/100 - Train Loss: 0.1034 - Val Acc: 0.7971
2026-04-05 05:23:06,330 - INFO - Epoch 20/100 - Train Loss: 0.1107 - Val Acc: 0.7971
2026-04-05 05:23:06,653 - INFO - Epoch 21/100 - Train Loss: 0.0922 - Val Acc: 0.8116
2026-04-05 05:23:06,987 - INFO - Epoch 22/100 - Train Loss: 0.0984 - Val Acc: 0.7971
2026-04-05 05:23:07,295 - INFO - Epoch 23/100 - Train Loss: 0.0979 - Val Acc: 0.8261
2026-04-05 05:23:07,598 - INFO - Epoch 24/100 - Train Loss: 0.0936 - Val Acc: 0.8116
2026-04-05 05:23:07,909 - INFO - Epoch 25/100 - Train Loss: 0.0852 - Val Acc: 0.8116
2026-04-05 05:23:08,207 - INFO - Epoch 26/100 - Train Loss: 0.0837 - Val Acc: 0.7971
2026-04-05 05:23:08,524 - INFO - Epoch 27/100 - Train Loss: 0.0892 - Val Acc: 0.8261
2026-04-05 05:23:08,834 - INFO - Epoch 28/100 - Train Loss: 0.0877 - Val Acc: 0.7971
2026-04-05 05:23:09,151 - INFO - Epoch 29/100 - Train Loss: 0.0846 - Val Acc: 0.8261
2026-04-05 05:23:09,469 - INFO - Epoch 30/100 - Train Loss: 0.0715 - Val Acc: 0.7971
2026-04-05 05:23:09,791 - INFO - Epoch 31/100 - Train Loss: 0.0771 - Val Acc: 0.7971
2026-04-05 05:23:10,119 - INFO - Epoch 32/100 - Train Loss: 0.0759 - Val Acc: 0.8116
2026-04-05 05:23:10,448 - INFO - Epoch 33/100 - Train Loss: 0.0803 - Val Acc: 0.7971
2026-04-05 05:23:10,766 - INFO - Epoch 34/100 - Train Loss: 0.0702 - Val Acc: 0.7971
2026-04-05 05:23:11,074 - INFO - Epoch 35/100 - Train Loss: 0.0711 - Val Acc: 0.7971
2026-04-05 05:23:11,415 - INFO - Epoch 36/100 - Train Loss: 0.0676 - Val Acc: 0.8116
2026-04-05 05:23:11,735 - INFO - Epoch 37/100 - Train Loss: 0.0709 - Val Acc: 0.8261
2026-04-05 05:23:12,062 - INFO - Epoch 38/100 - Train Loss: 0.0623 - Val Acc: 0.7971
2026-04-05 05:23:12,372 - INFO - Epoch 39/100 - Train Loss: 0.0679 - Val Acc: 0.8116
2026-04-05 05:23:12,691 - INFO - Epoch 40/100 - Train Loss: 0.0622 - Val Acc: 0.7971
2026-04-05 05:23:13,007 - INFO - Epoch 41/100 - Train Loss: 0.0648 - Val Acc: 0.8116
2026-04-05 05:23:13,320 - INFO - Epoch 42/100 - Train Loss: 0.0659 - Val Acc: 0.8116
2026-04-05 05:23:13,627 - INFO - Epoch 43/100 - Train Loss: 0.0548 - Val Acc: 0.8116
2026-04-05 05:23:13,942 - INFO - Epoch 44/100 - Train Loss: 0.0561 - Val Acc: 0.8116
2026-04-05 05:23:14,264 - INFO - Epoch 45/100 - Train Loss: 0.0623 - Val Acc: 0.8116
2026-04-05 05:23:14,608 - INFO - Epoch 46/100 - Train Loss: 0.0568 - Val Acc: 0.8116
2026-04-05 05:23:14,927 - INFO - Epoch 47/100 - Train Loss: 0.0578 - Val Acc: 0.8116
2026-04-05 05:23:15,236 - INFO - Epoch 48/100 - Train Loss: 0.0565 - Val Acc: 0.8116
2026-04-05 05:23:15,544 - INFO - Epoch 49/100 - Train Loss: 0.0640 - Val Acc: 0.8261
2026-04-05 05:23:15,863 - INFO - Epoch 50/100 - Train Loss: 0.0530 - Val Acc: 0.8116
2026-04-05 05:23:16,179 - INFO - Epoch 51/100 - Train Loss: 0.0496 - Val Acc: 0.8116
2026-04-05 05:23:16,490 - INFO - Epoch 52/100 - Train Loss: 0.0544 - Val Acc: 0.8116
2026-04-05 05:23:16,812 - INFO - Epoch 53/100 - Train Loss: 0.0604 - Val Acc: 0.8116
2026-04-05 05:23:17,133 - INFO - Epoch 54/100 - Train Loss: 0.0504 - Val Acc: 0.8261
2026-04-05 05:23:17,437 - INFO - Epoch 55/100 - Train Loss: 0.0478 - Val Acc: 0.7971
2026-04-05 05:23:17,754 - INFO - Epoch 56/100 - Train Loss: 0.0491 - Val Acc: 0.8116
2026-04-05 05:23:18,069 - INFO - Epoch 57/100 - Train Loss: 0.0490 - Val Acc: 0.7971
2026-04-05 05:23:18,378 - INFO - Epoch 58/100 - Train Loss: 0.0475 - Val Acc: 0.7971
2026-04-05 05:23:18,688 - INFO - Epoch 59/100 - Train Loss: 0.0460 - Val Acc: 0.8116
2026-04-05 05:23:19,019 - INFO - Epoch 60/100 - Train Loss: 0.0458 - Val Acc: 0.8116
2026-04-05 05:23:19,352 - INFO - Epoch 61/100 - Train Loss: 0.0412 - Val Acc: 0.7971
2026-04-05 05:23:19,682 - INFO - Epoch 62/100 - Train Loss: 0.0398 - Val Acc: 0.8261
2026-04-05 05:23:19,990 - INFO - Epoch 63/100 - Train Loss: 0.0510 - Val Acc: 0.8116
2026-04-05 05:23:20,298 - INFO - Epoch 64/100 - Train Loss: 0.0420 - Val Acc: 0.8116
2026-04-05 05:23:20,620 - INFO - Epoch 65/100 - Train Loss: 0.0425 - Val Acc: 0.8261
2026-04-05 05:23:20,929 - INFO - Epoch 66/100 - Train Loss: 0.0344 - Val Acc: 0.8261
2026-04-05 05:23:21,239 - INFO - Epoch 67/100 - Train Loss: 0.0400 - Val Acc: 0.8116
2026-04-05 05:23:21,563 - INFO - Epoch 68/100 - Train Loss: 0.0423 - Val Acc: 0.8116
2026-04-05 05:23:21,877 - INFO - Epoch 69/100 - Train Loss: 0.0354 - Val Acc: 0.7971
2026-04-05 05:23:22,208 - INFO - Epoch 70/100 - Train Loss: 0.0424 - Val Acc: 0.8116
2026-04-05 05:23:22,525 - INFO - Epoch 71/100 - Train Loss: 0.0463 - Val Acc: 0.7971
2026-04-05 05:23:22,842 - INFO - Epoch 72/100 - Train Loss: 0.0369 - Val Acc: 0.8116
2026-04-05 05:23:23,169 - INFO - Epoch 73/100 - Train Loss: 0.0350 - Val Acc: 0.8116
2026-04-05 05:23:23,484 - INFO - Epoch 74/100 - Train Loss: 0.0367 - Val Acc: 0.8116
2026-04-05 05:23:23,801 - INFO - Epoch 75/100 - Train Loss: 0.0392 - Val Acc: 0.7971
2026-04-05 05:23:24,118 - INFO - Epoch 76/100 - Train Loss: 0.0396 - Val Acc: 0.8116
2026-04-05 05:23:24,469 - INFO - Epoch 77/100 - Train Loss: 0.0316 - Val Acc: 0.8116
2026-04-05 05:23:24,807 - INFO - Epoch 78/100 - Train Loss: 0.0290 - Val Acc: 0.8261
2026-04-05 05:23:25,129 - INFO - Epoch 79/100 - Train Loss: 0.0437 - Val Acc: 0.8116
2026-04-05 05:23:25,448 - INFO - Epoch 80/100 - Train Loss: 0.0397 - Val Acc: 0.8261
2026-04-05 05:23:25,772 - INFO - Epoch 81/100 - Train Loss: 0.0265 - Val Acc: 0.7971
2026-04-05 05:23:26,097 - INFO - Epoch 82/100 - Train Loss: 0.0435 - Val Acc: 0.7826
2026-04-05 05:23:26,408 - INFO - Epoch 83/100 - Train Loss: 0.0354 - Val Acc: 0.8116
2026-04-05 05:23:26,715 - INFO - Epoch 84/100 - Train Loss: 0.0342 - Val Acc: 0.8261
2026-04-05 05:23:27,032 - INFO - Epoch 85/100 - Train Loss: 0.0315 - Val Acc: 0.8116
2026-04-05 05:23:27,356 - INFO - Epoch 86/100 - Train Loss: 0.0320 - Val Acc: 0.8261
2026-04-05 05:23:27,678 - INFO - Epoch 87/100 - Train Loss: 0.0336 - Val Acc: 0.7971
2026-04-05 05:23:28,004 - INFO - Epoch 88/100 - Train Loss: 0.0336 - Val Acc: 0.8116
2026-04-05 05:23:28,327 - INFO - Epoch 89/100 - Train Loss: 0.0344 - Val Acc: 0.8116
2026-04-05 05:23:28,646 - INFO - Epoch 90/100 - Train Loss: 0.0290 - Val Acc: 0.8261
2026-04-05 05:23:28,958 - INFO - Epoch 91/100 - Train Loss: 0.0271 - Val Acc: 0.7971
2026-04-05 05:23:29,281 - INFO - Epoch 92/100 - Train Loss: 0.0331 - Val Acc: 0.7971
2026-04-05 05:23:29,606 - INFO - Epoch 93/100 - Train Loss: 0.0291 - Val Acc: 0.8261
2026-04-05 05:23:29,924 - INFO - Epoch 94/100 - Train Loss: 0.0237 - Val Acc: 0.8116
2026-04-05 05:23:30,238 - INFO - Epoch 95/100 - Train Loss: 0.0295 - Val Acc: 0.8261
2026-04-05 05:23:30,554 - INFO - Epoch 96/100 - Train Loss: 0.0295 - Val Acc: 0.8261
2026-04-05 05:23:30,873 - INFO - Epoch 97/100 - Train Loss: 0.0322 - Val Acc: 0.8261
2026-04-05 05:23:31,179 - INFO - Epoch 98/100 - Train Loss: 0.0182 - Val Acc: 0.8261
2026-04-05 05:23:31,505 - INFO - Epoch 99/100 - Train Loss: 0.0305 - Val Acc: 0.8116
2026-04-05 05:23:31,823 - INFO - Epoch 100/100 - Train Loss: 0.0258 - Val Acc: 0.8116
2026-04-05 05:23:32,174 - INFO - Fold 5 logically complete. Tensor memory bounds cleared cleanly.
2026-04-05 05:23:32,178 - INFO - Original class distribution: [276 345]
2026-04-05 05:23:32,179 - INFO - Training device bound securely to: cuda
2026-04-05 05:23:32,196 - INFO - After SMOTE-ENN deployment: [345 288]

Fold 6:   0%|          | 0/100 [00:00<?, ?it/s]

2026-04-05 05:23:32,518 - INFO - Epoch 1/100 - Train Loss: 0.6036 - Val Acc: 0.8406
2026-04-05 05:23:32,832 - INFO - Epoch 2/100 - Train Loss: 0.3793 - Val Acc: 0.8551
2026-04-05 05:23:33,148 - INFO - Epoch 3/100 - Train Loss: 0.2490 - Val Acc: 0.8841
2026-04-05 05:23:33,459 - INFO - Epoch 4/100 - Train Loss: 0.2120 - Val Acc: 0.8841
2026-04-05 05:23:33,788 - INFO - Epoch 5/100 - Train Loss: 0.1875 - Val Acc: 0.8986
2026-04-05 05:23:34,117 - INFO - Epoch 6/100 - Train Loss: 0.1860 - Val Acc: 0.9130
2026-04-05 05:23:34,462 - INFO - Epoch 7/100 - Train Loss: 0.1716 - Val Acc: 0.9130
2026-04-05 05:23:34,802 - INFO - Epoch 8/100 - Train Loss: 0.1648 - Val Acc: 0.8986
2026-04-05 05:23:35,121 - INFO - Epoch 9/100 - Train Loss: 0.1723 - Val Acc: 0.8986
2026-04-05 05:23:35,439 - INFO - Epoch 10/100 - Train Loss: 0.1578 - Val Acc: 0.9130
2026-04-05 05:23:35,755 - INFO - Epoch 11/100 - Train Loss: 0.1684 - Val Acc: 0.9130
2026-04-05 05:23:36,083 - INFO - Epoch 12/100 - Train Loss: 0.1500 - Val Acc: 0.9130
2026-04-05 05:23:36,400 - INFO - Epoch 13/100 - Train Loss: 0.1498 - Val Acc: 0.9130
2026-04-05 05:23:36,724 - INFO - Epoch 14/100 - Train Loss: 0.1586 - Val Acc: 0.8986
2026-04-05 05:23:37,048 - INFO - Epoch 15/100 - Train Loss: 0.1513 - Val Acc: 0.9130
2026-04-05 05:23:37,368 - INFO - Epoch 16/100 - Train Loss: 0.1397 - Val Acc: 0.8986
2026-04-05 05:23:37,690 - INFO - Epoch 17/100 - Train Loss: 0.1310 - Val Acc: 0.9130
2026-04-05 05:23:38,021 - INFO - Epoch 18/100 - Train Loss: 0.1352 - Val Acc: 0.8841
2026-04-05 05:23:38,340 - INFO - Epoch 19/100 - Train Loss: 0.1298 - Val Acc: 0.8841
2026-04-05 05:23:38,665 - INFO - Epoch 20/100 - Train Loss: 0.1201 - Val Acc: 0.8841
2026-04-05 05:23:38,986 - INFO - Epoch 21/100 - Train Loss: 0.1229 - Val Acc: 0.8841
2026-04-05 05:23:39,310 - INFO - Epoch 22/100 - Train Loss: 0.1112 - Val Acc: 0.8841
2026-04-05 05:23:39,634 - INFO - Epoch 23/100 - Train Loss: 0.1144 - Val Acc: 0.8841
2026-04-05 05:23:39,962 - INFO - Epoch 24/100 - Train Loss: 0.1074 - Val Acc: 0.8841
2026-04-05 05:23:40,275 - INFO - Epoch 25/100 - Train Loss: 0.1104 - Val Acc: 0.8841
2026-04-05 05:23:40,601 - INFO - Epoch 26/100 - Train Loss: 0.1041 - Val Acc: 0.8841
2026-04-05 05:23:40,932 - INFO - Epoch 27/100 - Train Loss: 0.1143 - Val Acc: 0.8841
2026-04-05 05:23:41,268 - INFO - Epoch 28/100 - Train Loss: 0.1155 - Val Acc: 0.8841
2026-04-05 05:23:41,586 - INFO - Epoch 29/100 - Train Loss: 0.1049 - Val Acc: 0.8841
2026-04-05 05:23:41,910 - INFO - Epoch 30/100 - Train Loss: 0.1033 - Val Acc: 0.9130
2026-04-05 05:23:42,222 - INFO - Epoch 31/100 - Train Loss: 0.0957 - Val Acc: 0.8841
2026-04-05 05:23:42,540 - INFO - Epoch 32/100 - Train Loss: 0.0930 - Val Acc: 0.8841
2026-04-05 05:23:42,858 - INFO - Epoch 33/100 - Train Loss: 0.0940 - Val Acc: 0.8986
2026-04-05 05:23:43,172 - INFO - Epoch 34/100 - Train Loss: 0.0953 - Val Acc: 0.8841
2026-04-05 05:23:43,506 - INFO - Epoch 35/100 - Train Loss: 0.0850 - Val Acc: 0.8986
2026-04-05 05:23:43,829 - INFO - Epoch 36/100 - Train Loss: 0.0933 - Val Acc: 0.8841
2026-04-05 05:23:44,143 - INFO - Epoch 37/100 - Train Loss: 0.0911 - Val Acc: 0.8986
2026-04-05 05:23:44,463 - INFO - Epoch 38/100 - Train Loss: 0.0924 - Val Acc: 0.8841
2026-04-05 05:23:44,803 - INFO - Epoch 39/100 - Train Loss: 0.0830 - Val Acc: 0.8841
2026-04-05 05:23:45,114 - INFO - Epoch 40/100 - Train Loss: 0.0768 - Val Acc: 0.8841
2026-04-05 05:23:45,434 - INFO - Epoch 41/100 - Train Loss: 0.0842 - Val Acc: 0.8841
2026-04-05 05:23:45,749 - INFO - Epoch 42/100 - Train Loss: 0.0910 - Val Acc: 0.8696
2026-04-05 05:23:46,073 - INFO - Epoch 43/100 - Train Loss: 0.0856 - Val Acc: 0.8841
2026-04-05 05:23:46,396 - INFO - Epoch 44/100 - Train Loss: 0.0781 - Val Acc: 0.8986
2026-04-05 05:23:46,705 - INFO - Epoch 45/100 - Train Loss: 0.0787 - Val Acc: 0.8986
2026-04-05 05:23:47,016 - INFO - Epoch 46/100 - Train Loss: 0.0780 - Val Acc: 0.8841
2026-04-05 05:23:47,317 - INFO - Epoch 47/100 - Train Loss: 0.0855 - Val Acc: 0.8986
2026-04-05 05:23:47,634 - INFO - Epoch 48/100 - Train Loss: 0.0606 - Val Acc: 0.8986
2026-04-05 05:23:47,961 - INFO - Epoch 49/100 - Train Loss: 0.0782 - Val Acc: 0.8841
2026-04-05 05:23:48,279 - INFO - Epoch 50/100 - Train Loss: 0.0754 - Val Acc: 0.8986
2026-04-05 05:23:48,609 - INFO - Epoch 51/100 - Train Loss: 0.0745 - Val Acc: 0.9130
2026-04-05 05:23:48,935 - INFO - Epoch 52/100 - Train Loss: 0.0614 - Val Acc: 0.8841
2026-04-05 05:23:49,264 - INFO - Epoch 53/100 - Train Loss: 0.0617 - Val Acc: 0.8841
2026-04-05 05:23:49,568 - INFO - Epoch 54/100 - Train Loss: 0.0684 - Val Acc: 0.8841
2026-04-05 05:23:49,882 - INFO - Epoch 55/100 - Train Loss: 0.0751 - Val Acc: 0.8696
2026-04-05 05:23:50,191 - INFO - Epoch 56/100 - Train Loss: 0.0708 - Val Acc: 0.9130
2026-04-05 05:23:50,511 - INFO - Epoch 57/100 - Train Loss: 0.0527 - Val Acc: 0.8986
2026-04-05 05:23:50,826 - INFO - Epoch 58/100 - Train Loss: 0.0674 - Val Acc: 0.9130
2026-04-05 05:23:51,135 - INFO - Epoch 59/100 - Train Loss: 0.0710 - Val Acc: 0.8986
2026-04-05 05:23:51,466 - INFO - Epoch 60/100 - Train Loss: 0.0651 - Val Acc: 0.8986
2026-04-05 05:23:51,794 - INFO - Epoch 61/100 - Train Loss: 0.0726 - Val Acc: 0.8986
2026-04-05 05:23:52,121 - INFO - Epoch 62/100 - Train Loss: 0.0736 - Val Acc: 0.8986
2026-04-05 05:23:52,439 - INFO - Epoch 63/100 - Train Loss: 0.0734 - Val Acc: 0.8986
2026-04-05 05:23:52,760 - INFO - Epoch 64/100 - Train Loss: 0.0790 - Val Acc: 0.8986
2026-04-05 05:23:53,083 - INFO - Epoch 65/100 - Train Loss: 0.0577 - Val Acc: 0.8696
2026-04-05 05:23:53,399 - INFO - Epoch 66/100 - Train Loss: 0.0726 - Val Acc: 0.8986
2026-04-05 05:23:53,718 - INFO - Epoch 67/100 - Train Loss: 0.0594 - Val Acc: 0.8841
2026-04-05 05:23:54,033 - INFO - Epoch 68/100 - Train Loss: 0.0544 - Val Acc: 0.8841
2026-04-05 05:23:54,388 - INFO - Epoch 69/100 - Train Loss: 0.0611 - Val Acc: 0.8841
2026-04-05 05:23:54,730 - INFO - Epoch 70/100 - Train Loss: 0.0676 - Val Acc: 0.8841
2026-04-05 05:23:55,052 - INFO - Epoch 71/100 - Train Loss: 0.0656 - Val Acc: 0.8696
2026-04-05 05:23:55,373 - INFO - Epoch 72/100 - Train Loss: 0.0592 - Val Acc: 0.8841
2026-04-05 05:23:55,690 - INFO - Epoch 73/100 - Train Loss: 0.0566 - Val Acc: 0.8841
2026-04-05 05:23:56,007 - INFO - Epoch 74/100 - Train Loss: 0.0569 - Val Acc: 0.8841
2026-04-05 05:23:56,328 - INFO - Epoch 75/100 - Train Loss: 0.0439 - Val Acc: 0.8841
2026-04-05 05:23:56,644 - INFO - Epoch 76/100 - Train Loss: 0.0451 - Val Acc: 0.8986
2026-04-05 05:23:56,955 - INFO - Epoch 77/100 - Train Loss: 0.0552 - Val Acc: 0.8841
2026-04-05 05:23:57,269 - INFO - Epoch 78/100 - Train Loss: 0.0527 - Val Acc: 0.8986
2026-04-05 05:23:57,589 - INFO - Epoch 79/100 - Train Loss: 0.0450 - Val Acc: 0.8986
2026-04-05 05:23:57,896 - INFO - Epoch 80/100 - Train Loss: 0.0459 - Val Acc: 0.8986
2026-04-05 05:23:58,234 - INFO - Epoch 81/100 - Train Loss: 0.0494 - Val Acc: 0.8841
2026-04-05 05:23:58,563 - INFO - Epoch 82/100 - Train Loss: 0.0400 - Val Acc: 0.8841
2026-04-05 05:23:58,887 - INFO - Epoch 83/100 - Train Loss: 0.0536 - Val Acc: 0.8986
2026-04-05 05:23:59,198 - INFO - Epoch 84/100 - Train Loss: 0.0427 - Val Acc: 0.8986
2026-04-05 05:23:59,505 - INFO - Epoch 85/100 - Train Loss: 0.0534 - Val Acc: 0.8841
2026-04-05 05:23:59,817 - INFO - Epoch 86/100 - Train Loss: 0.0452 - Val Acc: 0.8986
2026-04-05 05:24:00,130 - INFO - Epoch 87/100 - Train Loss: 0.0493 - Val Acc: 0.8986
2026-04-05 05:24:00,433 - INFO - Epoch 88/100 - Train Loss: 0.0494 - Val Acc: 0.8986
2026-04-05 05:24:00,755 - INFO - Epoch 89/100 - Train Loss: 0.0383 - Val Acc: 0.8986
2026-04-05 05:24:01,076 - INFO - Epoch 90/100 - Train Loss: 0.0478 - Val Acc: 0.8841
2026-04-05 05:24:01,395 - INFO - Epoch 91/100 - Train Loss: 0.0431 - Val Acc: 0.8986
2026-04-05 05:24:01,715 - INFO - Epoch 92/100 - Train Loss: 0.0527 - Val Acc: 0.8841
2026-04-05 05:24:02,043 - INFO - Epoch 93/100 - Train Loss: 0.0399 - Val Acc: 0.8841
2026-04-05 05:24:02,372 - INFO - Epoch 94/100 - Train Loss: 0.0403 - Val Acc: 0.8986
2026-04-05 05:24:02,684 - INFO - Epoch 95/100 - Train Loss: 0.0404 - Val Acc: 0.8841
2026-04-05 05:24:02,995 - INFO - Epoch 96/100 - Train Loss: 0.0302 - Val Acc: 0.8841
2026-04-05 05:24:03,309 - INFO - Epoch 97/100 - Train Loss: 0.0357 - Val Acc: 0.8986
2026-04-05 05:24:03,622 - INFO - Epoch 98/100 - Train Loss: 0.0380 - Val Acc: 0.8986
2026-04-05 05:24:03,934 - INFO - Epoch 99/100 - Train Loss: 0.0404 - Val Acc: 0.8986
2026-04-05 05:24:04,266 - INFO - Epoch 100/100 - Train Loss: 0.0397 - Val Acc: 0.9130
2026-04-05 05:24:04,647 - INFO - Fold 6 logically complete. Tensor memory bounds cleared cleanly.
2026-04-05 05:24:04,651 - INFO - Original class distribution: [276 345]
2026-04-05 05:24:04,652 - INFO - Training device bound securely to: cuda
2026-04-05 05:24:04,668 - INFO - After SMOTE-ENN deployment: [345 291]

Fold 7:   0%|          | 0/100 [00:00<?, ?it/s]

2026-04-05 05:24:04,995 - INFO - Epoch 1/100 - Train Loss: 0.5904 - Val Acc: 0.7826
2026-04-05 05:24:05,315 - INFO - Epoch 2/100 - Train Loss: 0.3598 - Val Acc: 0.8116
2026-04-05 05:24:05,627 - INFO - Epoch 3/100 - Train Loss: 0.2449 - Val Acc: 0.7971
2026-04-05 05:24:05,948 - INFO - Epoch 4/100 - Train Loss: 0.2059 - Val Acc: 0.7971
2026-04-05 05:24:06,260 - INFO - Epoch 5/100 - Train Loss: 0.1941 - Val Acc: 0.7681
2026-04-05 05:24:06,589 - INFO - Epoch 6/100 - Train Loss: 0.1777 - Val Acc: 0.7681
2026-04-05 05:24:06,928 - INFO - Epoch 7/100 - Train Loss: 0.1747 - Val Acc: 0.7681
2026-04-05 05:24:07,246 - INFO - Epoch 8/100 - Train Loss: 0.1629 - Val Acc: 0.7826
2026-04-05 05:24:07,569 - INFO - Epoch 9/100 - Train Loss: 0.1635 - Val Acc: 0.7826
2026-04-05 05:24:07,885 - INFO - Epoch 10/100 - Train Loss: 0.1579 - Val Acc: 0.7826
2026-04-05 05:24:08,215 - INFO - Epoch 11/100 - Train Loss: 0.1520 - Val Acc: 0.7971
2026-04-05 05:24:08,529 - INFO - Epoch 12/100 - Train Loss: 0.1330 - Val Acc: 0.7826
2026-04-05 05:24:08,843 - INFO - Epoch 13/100 - Train Loss: 0.1430 - Val Acc: 0.7826
2026-04-05 05:24:09,158 - INFO - Epoch 14/100 - Train Loss: 0.1429 - Val Acc: 0.7826
2026-04-05 05:24:09,468 - INFO - Epoch 15/100 - Train Loss: 0.1310 - Val Acc: 0.7681
2026-04-05 05:24:09,780 - INFO - Epoch 16/100 - Train Loss: 0.1248 - Val Acc: 0.7536
2026-04-05 05:24:10,124 - INFO - Epoch 17/100 - Train Loss: 0.1194 - Val Acc: 0.7681
2026-04-05 05:24:10,439 - INFO - Epoch 18/100 - Train Loss: 0.1230 - Val Acc: 0.7826
2026-04-05 05:24:10,783 - INFO - Epoch 19/100 - Train Loss: 0.1200 - Val Acc: 0.7536
2026-04-05 05:24:11,110 - INFO - Epoch 20/100 - Train Loss: 0.1277 - Val Acc: 0.7681
2026-04-05 05:24:11,416 - INFO - Epoch 21/100 - Train Loss: 0.1157 - Val Acc: 0.7826
2026-04-05 05:24:11,730 - INFO - Epoch 22/100 - Train Loss: 0.1047 - Val Acc: 0.7681
2026-04-05 05:24:12,044 - INFO - Epoch 23/100 - Train Loss: 0.1043 - Val Acc: 0.7681
2026-04-05 05:24:12,354 - INFO - Epoch 24/100 - Train Loss: 0.1104 - Val Acc: 0.7681
2026-04-05 05:24:12,677 - INFO - Epoch 25/100 - Train Loss: 0.1038 - Val Acc: 0.7826
2026-04-05 05:24:12,998 - INFO - Epoch 26/100 - Train Loss: 0.1026 - Val Acc: 0.7826
2026-04-05 05:24:13,318 - INFO - Epoch 27/100 - Train Loss: 0.0962 - Val Acc: 0.7681
2026-04-05 05:24:13,628 - INFO - Epoch 28/100 - Train Loss: 0.1002 - Val Acc: 0.7826
2026-04-05 05:24:13,949 - INFO - Epoch 29/100 - Train Loss: 0.0931 - Val Acc: 0.7826
2026-04-05 05:24:14,269 - INFO - Epoch 30/100 - Train Loss: 0.0819 - Val Acc: 0.7971
2026-04-05 05:24:14,608 - INFO - Epoch 31/100 - Train Loss: 0.0840 - Val Acc: 0.7826
2026-04-05 05:24:14,919 - INFO - Epoch 32/100 - Train Loss: 0.0896 - Val Acc: 0.7971
2026-04-05 05:24:15,251 - INFO - Epoch 33/100 - Train Loss: 0.0862 - Val Acc: 0.7681
2026-04-05 05:24:15,570 - INFO - Epoch 34/100 - Train Loss: 0.0826 - Val Acc: 0.7826
2026-04-05 05:24:15,894 - INFO - Epoch 35/100 - Train Loss: 0.0873 - Val Acc: 0.7826
2026-04-05 05:24:16,214 - INFO - Epoch 36/100 - Train Loss: 0.0866 - Val Acc: 0.7826
2026-04-05 05:24:16,531 - INFO - Epoch 37/100 - Train Loss: 0.0907 - Val Acc: 0.7826
2026-04-05 05:24:16,843 - INFO - Epoch 38/100 - Train Loss: 0.0745 - Val Acc: 0.7826
2026-04-05 05:24:17,166 - INFO - Epoch 39/100 - Train Loss: 0.0804 - Val Acc: 0.7826
2026-04-05 05:24:17,488 - INFO - Epoch 40/100 - Train Loss: 0.0673 - Val Acc: 0.7826
2026-04-05 05:24:17,812 - INFO - Epoch 41/100 - Train Loss: 0.0724 - Val Acc: 0.7826
2026-04-05 05:24:18,128 - INFO - Epoch 42/100 - Train Loss: 0.0733 - Val Acc: 0.7826
2026-04-05 05:24:18,456 - INFO - Epoch 43/100 - Train Loss: 0.0788 - Val Acc: 0.7681
2026-04-05 05:24:18,771 - INFO - Epoch 44/100 - Train Loss: 0.0626 - Val Acc: 0.7681
2026-04-05 05:24:19,084 - INFO - Epoch 45/100 - Train Loss: 0.0597 - Val Acc: 0.7826
2026-04-05 05:24:19,394 - INFO - Epoch 46/100 - Train Loss: 0.0584 - Val Acc: 0.7826
2026-04-05 05:24:19,717 - INFO - Epoch 47/100 - Train Loss: 0.0719 - Val Acc: 0.7826
2026-04-05 05:24:20,032 - INFO - Epoch 48/100 - Train Loss: 0.0569 - Val Acc: 0.7826
2026-04-05 05:24:20,355 - INFO - Epoch 49/100 - Train Loss: 0.0789 - Val Acc: 0.7826
2026-04-05 05:24:20,687 - INFO - Epoch 50/100 - Train Loss: 0.0686 - Val Acc: 0.7971
2026-04-05 05:24:20,998 - INFO - Epoch 51/100 - Train Loss: 0.0693 - Val Acc: 0.7681
2026-04-05 05:24:21,311 - INFO - Epoch 52/100 - Train Loss: 0.0575 - Val Acc: 0.7826
2026-04-05 05:24:21,631 - INFO - Epoch 53/100 - Train Loss: 0.0696 - Val Acc: 0.7971
2026-04-05 05:24:21,957 - INFO - Epoch 54/100 - Train Loss: 0.0591 - Val Acc: 0.7971
2026-04-05 05:24:22,276 - INFO - Epoch 55/100 - Train Loss: 0.0680 - Val Acc: 0.7971
2026-04-05 05:24:22,591 - INFO - Epoch 56/100 - Train Loss: 0.0592 - Val Acc: 0.7971
2026-04-05 05:24:22,906 - INFO - Epoch 57/100 - Train Loss: 0.0688 - Val Acc: 0.7826
2026-04-05 05:24:23,233 - INFO - Epoch 58/100 - Train Loss: 0.0547 - Val Acc: 0.7826
2026-04-05 05:24:23,552 - INFO - Epoch 59/100 - Train Loss: 0.0515 - Val Acc: 0.7971
2026-04-05 05:24:23,872 - INFO - Epoch 60/100 - Train Loss: 0.0534 - Val Acc: 0.7826
2026-04-05 05:24:24,190 - INFO - Epoch 61/100 - Train Loss: 0.0583 - Val Acc: 0.7826
2026-04-05 05:24:24,505 - INFO - Epoch 62/100 - Train Loss: 0.0595 - Val Acc: 0.7826
2026-04-05 05:24:24,850 - INFO - Epoch 63/100 - Train Loss: 0.0538 - Val Acc: 0.7681
2026-04-05 05:24:25,187 - INFO - Epoch 64/100 - Train Loss: 0.0581 - Val Acc: 0.7826
2026-04-05 05:24:25,505 - INFO - Epoch 65/100 - Train Loss: 0.0726 - Val Acc: 0.7826
2026-04-05 05:24:25,841 - INFO - Epoch 66/100 - Train Loss: 0.0656 - Val Acc: 0.7826
2026-04-05 05:24:26,153 - INFO - Epoch 67/100 - Train Loss: 0.0571 - Val Acc: 0.7826
2026-04-05 05:24:26,467 - INFO - Epoch 68/100 - Train Loss: 0.0469 - Val Acc: 0.7826
2026-04-05 05:24:26,780 - INFO - Epoch 69/100 - Train Loss: 0.0551 - Val Acc: 0.7971
2026-04-05 05:24:27,102 - INFO - Epoch 70/100 - Train Loss: 0.0598 - Val Acc: 0.7971
2026-04-05 05:24:27,418 - INFO - Epoch 71/100 - Train Loss: 0.0461 - Val Acc: 0.7826
2026-04-05 05:24:27,731 - INFO - Epoch 72/100 - Train Loss: 0.0488 - Val Acc: 0.7971
2026-04-05 05:24:28,060 - INFO - Epoch 73/100 - Train Loss: 0.0550 - Val Acc: 0.7971
2026-04-05 05:24:28,381 - INFO - Epoch 74/100 - Train Loss: 0.0501 - Val Acc: 0.7826
2026-04-05 05:24:28,684 - INFO - Epoch 75/100 - Train Loss: 0.0454 - Val Acc: 0.7971
2026-04-05 05:24:29,001 - INFO - Epoch 76/100 - Train Loss: 0.0444 - Val Acc: 0.7971
2026-04-05 05:24:29,307 - INFO - Epoch 77/100 - Train Loss: 0.0399 - Val Acc: 0.7971
2026-04-05 05:24:29,640 - INFO - Epoch 78/100 - Train Loss: 0.0461 - Val Acc: 0.7971
2026-04-05 05:24:29,964 - INFO - Epoch 79/100 - Train Loss: 0.0352 - Val Acc: 0.7971
2026-04-05 05:24:30,284 - INFO - Epoch 80/100 - Train Loss: 0.0388 - Val Acc: 0.7826
2026-04-05 05:24:30,597 - INFO - Epoch 81/100 - Train Loss: 0.0435 - Val Acc: 0.7826
2026-04-05 05:24:30,921 - INFO - Epoch 82/100 - Train Loss: 0.0425 - Val Acc: 0.7971
2026-04-05 05:24:31,237 - INFO - Epoch 83/100 - Train Loss: 0.0506 - Val Acc: 0.7826
2026-04-05 05:24:31,554 - INFO - Epoch 84/100 - Train Loss: 0.0418 - Val Acc: 0.7826
2026-04-05 05:24:31,863 - INFO - Epoch 85/100 - Train Loss: 0.0357 - Val Acc: 0.7826
2026-04-05 05:24:32,174 - INFO - Epoch 86/100 - Train Loss: 0.0319 - Val Acc: 0.7826
2026-04-05 05:24:32,493 - INFO - Epoch 87/100 - Train Loss: 0.0407 - Val Acc: 0.7826
2026-04-05 05:24:32,803 - INFO - Epoch 88/100 - Train Loss: 0.0369 - Val Acc: 0.7826
2026-04-05 05:24:33,129 - INFO - Epoch 89/100 - Train Loss: 0.0313 - Val Acc: 0.7826
2026-04-05 05:24:33,432 - INFO - Epoch 90/100 - Train Loss: 0.0381 - Val Acc: 0.7826
2026-04-05 05:24:33,750 - INFO - Epoch 91/100 - Train Loss: 0.0349 - Val Acc: 0.7826
2026-04-05 05:24:34,065 - INFO - Epoch 92/100 - Train Loss: 0.0436 - Val Acc: 0.7826
2026-04-05 05:24:34,412 - INFO - Epoch 93/100 - Train Loss: 0.0368 - Val Acc: 0.7826
2026-04-05 05:24:34,781 - INFO - Epoch 94/100 - Train Loss: 0.0483 - Val Acc: 0.7971
2026-04-05 05:24:35,103 - INFO - Epoch 95/100 - Train Loss: 0.0423 - Val Acc: 0.7971
2026-04-05 05:24:35,417 - INFO - Epoch 96/100 - Train Loss: 0.0355 - Val Acc: 0.7826
2026-04-05 05:24:35,728 - INFO - Epoch 97/100 - Train Loss: 0.0282 - Val Acc: 0.7826
2026-04-05 05:24:36,045 - INFO - Epoch 98/100 - Train Loss: 0.0485 - Val Acc: 0.7826
2026-04-05 05:24:36,364 - INFO - Epoch 99/100 - Train Loss: 0.0430 - Val Acc: 0.7971
2026-04-05 05:24:36,671 - INFO - Epoch 100/100 - Train Loss: 0.0334 - Val Acc: 0.7971
2026-04-05 05:24:37,022 - INFO - Fold 7 logically complete. Tensor memory bounds cleared cleanly.
2026-04-05 05:24:37,026 - INFO - Original class distribution: [276 345]
2026-04-05 05:24:37,027 - INFO - Training device bound securely to: cuda
2026-04-05 05:24:37,043 - INFO - After SMOTE-ENN deployment: [345 289]

Fold 8:   0%|          | 0/100 [00:00<?, ?it/s]

2026-04-05 05:24:37,370 - INFO - Epoch 1/100 - Train Loss: 0.5709 - Val Acc: 0.8406
2026-04-05 05:24:37,674 - INFO - Epoch 2/100 - Train Loss: 0.3552 - Val Acc: 0.8116
2026-04-05 05:24:37,987 - INFO - Epoch 3/100 - Train Loss: 0.2503 - Val Acc: 0.8261
2026-04-05 05:24:38,301 - INFO - Epoch 4/100 - Train Loss: 0.2138 - Val Acc: 0.8261
2026-04-05 05:24:38,616 - INFO - Epoch 5/100 - Train Loss: 0.2053 - Val Acc: 0.8551
2026-04-05 05:24:38,930 - INFO - Epoch 6/100 - Train Loss: 0.1835 - Val Acc: 0.8551
2026-04-05 05:24:39,250 - INFO - Epoch 7/100 - Train Loss: 0.1835 - Val Acc: 0.8551
2026-04-05 05:24:39,567 - INFO - Epoch 8/100 - Train Loss: 0.1822 - Val Acc: 0.8551
2026-04-05 05:24:39,885 - INFO - Epoch 9/100 - Train Loss: 0.1757 - Val Acc: 0.8551
2026-04-05 05:24:40,211 - INFO - Epoch 10/100 - Train Loss: 0.1525 - Val Acc: 0.8551
2026-04-05 05:24:40,520 - INFO - Epoch 11/100 - Train Loss: 0.1580 - Val Acc: 0.8551
2026-04-05 05:24:40,852 - INFO - Epoch 12/100 - Train Loss: 0.1490 - Val Acc: 0.8551
2026-04-05 05:24:41,168 - INFO - Epoch 13/100 - Train Loss: 0.1368 - Val Acc: 0.8551
2026-04-05 05:24:41,476 - INFO - Epoch 14/100 - Train Loss: 0.1433 - Val Acc: 0.8551
2026-04-05 05:24:41,794 - INFO - Epoch 15/100 - Train Loss: 0.1243 - Val Acc: 0.8551
2026-04-05 05:24:42,154 - INFO - Epoch 16/100 - Train Loss: 0.1215 - Val Acc: 0.8551
2026-04-05 05:24:42,480 - INFO - Epoch 17/100 - Train Loss: 0.1190 - Val Acc: 0.8551
2026-04-05 05:24:42,802 - INFO - Epoch 18/100 - Train Loss: 0.1255 - Val Acc: 0.8551
2026-04-05 05:24:43,133 - INFO - Epoch 19/100 - Train Loss: 0.1303 - Val Acc: 0.8551
2026-04-05 05:24:43,443 - INFO - Epoch 20/100 - Train Loss: 0.1185 - Val Acc: 0.8551
2026-04-05 05:24:43,763 - INFO - Epoch 21/100 - Train Loss: 0.1233 - Val Acc: 0.8551
2026-04-05 05:24:44,080 - INFO - Epoch 22/100 - Train Loss: 0.1258 - Val Acc: 0.8551
2026-04-05 05:24:44,424 - INFO - Epoch 23/100 - Train Loss: 0.1123 - Val Acc: 0.8551
2026-04-05 05:24:44,776 - INFO - Epoch 24/100 - Train Loss: 0.1101 - Val Acc: 0.8551
2026-04-05 05:24:45,085 - INFO - Epoch 25/100 - Train Loss: 0.0961 - Val Acc: 0.8551
2026-04-05 05:24:45,419 - INFO - Epoch 26/100 - Train Loss: 0.1186 - Val Acc: 0.8551
2026-04-05 05:24:45,745 - INFO - Epoch 27/100 - Train Loss: 0.1051 - Val Acc: 0.8551
2026-04-05 05:24:46,051 - INFO - Epoch 28/100 - Train Loss: 0.0975 - Val Acc: 0.8551
2026-04-05 05:24:46,368 - INFO - Epoch 29/100 - Train Loss: 0.0905 - Val Acc: 0.8551
2026-04-05 05:24:46,692 - INFO - Epoch 30/100 - Train Loss: 0.1072 - Val Acc: 0.8551
2026-04-05 05:24:46,998 - INFO - Epoch 31/100 - Train Loss: 0.0794 - Val Acc: 0.8551
2026-04-05 05:24:47,318 - INFO - Epoch 32/100 - Train Loss: 0.1054 - Val Acc: 0.8551
2026-04-05 05:24:47,633 - INFO - Epoch 33/100 - Train Loss: 0.0858 - Val Acc: 0.8551
2026-04-05 05:24:47,943 - INFO - Epoch 34/100 - Train Loss: 0.0893 - Val Acc: 0.8551
2026-04-05 05:24:48,251 - INFO - Epoch 35/100 - Train Loss: 0.0769 - Val Acc: 0.8551
2026-04-05 05:24:48,574 - INFO - Epoch 36/100 - Train Loss: 0.0820 - Val Acc: 0.8551
2026-04-05 05:24:48,903 - INFO - Epoch 37/100 - Train Loss: 0.0870 - Val Acc: 0.8551
2026-04-05 05:24:49,227 - INFO - Epoch 38/100 - Train Loss: 0.0769 - Val Acc: 0.8551
2026-04-05 05:24:49,549 - INFO - Epoch 39/100 - Train Loss: 0.0776 - Val Acc: 0.8406
2026-04-05 05:24:49,858 - INFO - Epoch 40/100 - Train Loss: 0.0790 - Val Acc: 0.8551
2026-04-05 05:24:50,182 - INFO - Epoch 41/100 - Train Loss: 0.0804 - Val Acc: 0.8551
2026-04-05 05:24:50,500 - INFO - Epoch 42/100 - Train Loss: 0.0776 - Val Acc: 0.8551
2026-04-05 05:24:50,821 - INFO - Epoch 43/100 - Train Loss: 0.0708 - Val Acc: 0.8551
2026-04-05 05:24:51,140 - INFO - Epoch 44/100 - Train Loss: 0.0841 - Val Acc: 0.8406
2026-04-05 05:24:51,454 - INFO - Epoch 45/100 - Train Loss: 0.0697 - Val Acc: 0.8551
2026-04-05 05:24:51,779 - INFO - Epoch 46/100 - Train Loss: 0.0811 - Val Acc: 0.8551
2026-04-05 05:24:52,113 - INFO - Epoch 47/100 - Train Loss: 0.0726 - Val Acc: 0.8551
2026-04-05 05:24:52,429 - INFO - Epoch 48/100 - Train Loss: 0.0752 - Val Acc: 0.8551
2026-04-05 05:24:52,736 - INFO - Epoch 49/100 - Train Loss: 0.0722 - Val Acc: 0.8551
2026-04-05 05:24:53,056 - INFO - Epoch 50/100 - Train Loss: 0.0700 - Val Acc: 0.8551
2026-04-05 05:24:53,370 - INFO - Epoch 51/100 - Train Loss: 0.0626 - Val Acc: 0.8551
2026-04-05 05:24:53,699 - INFO - Epoch 52/100 - Train Loss: 0.0614 - Val Acc: 0.8551
2026-04-05 05:24:54,014 - INFO - Epoch 53/100 - Train Loss: 0.0598 - Val Acc: 0.8551
2026-04-05 05:24:54,369 - INFO - Epoch 54/100 - Train Loss: 0.0700 - Val Acc: 0.8406
2026-04-05 05:24:54,699 - INFO - Epoch 55/100 - Train Loss: 0.0719 - Val Acc: 0.8551
2026-04-05 05:24:55,027 - INFO - Epoch 56/100 - Train Loss: 0.0627 - Val Acc: 0.8406
2026-04-05 05:24:55,353 - INFO - Epoch 57/100 - Train Loss: 0.0670 - Val Acc: 0.8551
2026-04-05 05:24:55,681 - INFO - Epoch 58/100 - Train Loss: 0.0495 - Val Acc: 0.8551
2026-04-05 05:24:56,002 - INFO - Epoch 59/100 - Train Loss: 0.0461 - Val Acc: 0.8551
2026-04-05 05:24:56,323 - INFO - Epoch 60/100 - Train Loss: 0.0611 - Val Acc: 0.8551
2026-04-05 05:24:56,632 - INFO - Epoch 61/100 - Train Loss: 0.0559 - Val Acc: 0.8551
2026-04-05 05:24:56,947 - INFO - Epoch 62/100 - Train Loss: 0.0494 - Val Acc: 0.8551
2026-04-05 05:24:57,272 - INFO - Epoch 63/100 - Train Loss: 0.0597 - Val Acc: 0.8551
2026-04-05 05:24:57,589 - INFO - Epoch 64/100 - Train Loss: 0.0461 - Val Acc: 0.8551
2026-04-05 05:24:57,916 - INFO - Epoch 65/100 - Train Loss: 0.0506 - Val Acc: 0.8551
2026-04-05 05:24:58,250 - INFO - Epoch 66/100 - Train Loss: 0.0536 - Val Acc: 0.8551
2026-04-05 05:24:58,567 - INFO - Epoch 67/100 - Train Loss: 0.0473 - Val Acc: 0.8551
2026-04-05 05:24:58,887 - INFO - Epoch 68/100 - Train Loss: 0.0445 - Val Acc: 0.8261
2026-04-05 05:24:59,201 - INFO - Epoch 69/100 - Train Loss: 0.0532 - Val Acc: 0.8551
2026-04-05 05:24:59,518 - INFO - Epoch 70/100 - Train Loss: 0.0546 - Val Acc: 0.8551
2026-04-05 05:24:59,836 - INFO - Epoch 71/100 - Train Loss: 0.0431 - Val Acc: 0.8551
2026-04-05 05:25:00,149 - INFO - Epoch 72/100 - Train Loss: 0.0504 - Val Acc: 0.8116
2026-04-05 05:25:00,461 - INFO - Epoch 73/100 - Train Loss: 0.0442 - Val Acc: 0.8551
2026-04-05 05:25:00,785 - INFO - Epoch 74/100 - Train Loss: 0.0369 - Val Acc: 0.8551
2026-04-05 05:25:01,103 - INFO - Epoch 75/100 - Train Loss: 0.0397 - Val Acc: 0.8261
2026-04-05 05:25:01,411 - INFO - Epoch 76/100 - Train Loss: 0.0447 - Val Acc: 0.8551
2026-04-05 05:25:01,718 - INFO - Epoch 77/100 - Train Loss: 0.0612 - Val Acc: 0.8551
2026-04-05 05:25:02,035 - INFO - Epoch 78/100 - Train Loss: 0.0469 - Val Acc: 0.8406
2026-04-05 05:25:02,362 - INFO - Epoch 79/100 - Train Loss: 0.0456 - Val Acc: 0.8551
2026-04-05 05:25:02,691 - INFO - Epoch 80/100 - Train Loss: 0.0480 - Val Acc: 0.8551
2026-04-05 05:25:03,033 - INFO - Epoch 81/100 - Train Loss: 0.0382 - Val Acc: 0.8551
2026-04-05 05:25:03,354 - INFO - Epoch 82/100 - Train Loss: 0.0414 - Val Acc: 0.8551
2026-04-05 05:25:03,668 - INFO - Epoch 83/100 - Train Loss: 0.0425 - Val Acc: 0.8406
2026-04-05 05:25:03,983 - INFO - Epoch 84/100 - Train Loss: 0.0341 - Val Acc: 0.8551
2026-04-05 05:25:04,326 - INFO - Epoch 85/100 - Train Loss: 0.0411 - Val Acc: 0.8406
2026-04-05 05:25:04,669 - INFO - Epoch 86/100 - Train Loss: 0.0381 - Val Acc: 0.8261
2026-04-05 05:25:04,986 - INFO - Epoch 87/100 - Train Loss: 0.0400 - Val Acc: 0.8406
2026-04-05 05:25:05,305 - INFO - Epoch 88/100 - Train Loss: 0.0460 - Val Acc: 0.8406
2026-04-05 05:25:05,628 - INFO - Epoch 89/100 - Train Loss: 0.0428 - Val Acc: 0.8406
2026-04-05 05:25:05,946 - INFO - Epoch 90/100 - Train Loss: 0.0389 - Val Acc: 0.8406
2026-04-05 05:25:06,269 - INFO - Epoch 91/100 - Train Loss: 0.0443 - Val Acc: 0.8406
2026-04-05 05:25:06,578 - INFO - Epoch 92/100 - Train Loss: 0.0363 - Val Acc: 0.8406
2026-04-05 05:25:06,902 - INFO - Epoch 93/100 - Train Loss: 0.0366 - Val Acc: 0.8406
2026-04-05 05:25:07,215 - INFO - Epoch 94/100 - Train Loss: 0.0386 - Val Acc: 0.8406
2026-04-05 05:25:07,545 - INFO - Epoch 95/100 - Train Loss: 0.0320 - Val Acc: 0.8406
2026-04-05 05:25:07,860 - INFO - Epoch 96/100 - Train Loss: 0.0422 - Val Acc: 0.8406
2026-04-05 05:25:08,168 - INFO - Epoch 97/100 - Train Loss: 0.0263 - Val Acc: 0.8406
2026-04-05 05:25:08,483 - INFO - Epoch 98/100 - Train Loss: 0.0313 - Val Acc: 0.8551
2026-04-05 05:25:08,796 - INFO - Epoch 99/100 - Train Loss: 0.0340 - Val Acc: 0.8261
2026-04-05 05:25:09,123 - INFO - Epoch 100/100 - Train Loss: 0.0446 - Val Acc: 0.8406
2026-04-05 05:25:09,480 - INFO - Fold 8 logically complete. Tensor memory bounds cleared cleanly.
2026-04-05 05:25:09,484 - INFO - Original class distribution: [276 345]
2026-04-05 05:25:09,485 - INFO - Training device bound securely to: cuda
2026-04-05 05:25:09,501 - INFO - After SMOTE-ENN deployment: [345 294]

Fold 9:   0%|          | 0/100 [00:00<?, ?it/s]

2026-04-05 05:25:09,836 - INFO - Epoch 1/100 - Train Loss: 0.6009 - Val Acc: 0.8261
2026-04-05 05:25:10,157 - INFO - Epoch 2/100 - Train Loss: 0.3780 - Val Acc: 0.8116
2026-04-05 05:25:10,481 - INFO - Epoch 3/100 - Train Loss: 0.2317 - Val Acc: 0.7971
2026-04-05 05:25:10,807 - INFO - Epoch 4/100 - Train Loss: 0.1863 - Val Acc: 0.8261
2026-04-05 05:25:11,121 - INFO - Epoch 5/100 - Train Loss: 0.1832 - Val Acc: 0.8406
2026-04-05 05:25:11,464 - INFO - Epoch 6/100 - Train Loss: 0.1728 - Val Acc: 0.8261
2026-04-05 05:25:11,774 - INFO - Epoch 7/100 - Train Loss: 0.1697 - Val Acc: 0.8261
2026-04-05 05:25:12,108 - INFO - Epoch 8/100 - Train Loss: 0.1512 - Val Acc: 0.8261
2026-04-05 05:25:12,428 - INFO - Epoch 9/100 - Train Loss: 0.1542 - Val Acc: 0.8406
2026-04-05 05:25:12,742 - INFO - Epoch 10/100 - Train Loss: 0.1433 - Val Acc: 0.8406
2026-04-05 05:25:13,076 - INFO - Epoch 11/100 - Train Loss: 0.1502 - Val Acc: 0.8406
2026-04-05 05:25:13,391 - INFO - Epoch 12/100 - Train Loss: 0.1374 - Val Acc: 0.8406
2026-04-05 05:25:13,702 - INFO - Epoch 13/100 - Train Loss: 0.1287 - Val Acc: 0.8406
2026-04-05 05:25:14,025 - INFO - Epoch 14/100 - Train Loss: 0.1217 - Val Acc: 0.8406
2026-04-05 05:25:14,356 - INFO - Epoch 15/100 - Train Loss: 0.1244 - Val Acc: 0.8261
2026-04-05 05:25:14,707 - INFO - Epoch 16/100 - Train Loss: 0.1228 - Val Acc: 0.8261
2026-04-05 05:25:15,027 - INFO - Epoch 17/100 - Train Loss: 0.1240 - Val Acc: 0.8261
2026-04-05 05:25:15,347 - INFO - Epoch 18/100 - Train Loss: 0.1054 - Val Acc: 0.8406
2026-04-05 05:25:15,671 - INFO - Epoch 19/100 - Train Loss: 0.1088 - Val Acc: 0.8261
2026-04-05 05:25:15,994 - INFO - Epoch 20/100 - Train Loss: 0.1073 - Val Acc: 0.8406
2026-04-05 05:25:16,320 - INFO - Epoch 21/100 - Train Loss: 0.1038 - Val Acc: 0.8406
2026-04-05 05:25:16,629 - INFO - Epoch 22/100 - Train Loss: 0.1019 - Val Acc: 0.8406
2026-04-05 05:25:16,943 - INFO - Epoch 23/100 - Train Loss: 0.1045 - Val Acc: 0.8261
2026-04-05 05:25:17,269 - INFO - Epoch 24/100 - Train Loss: 0.0958 - Val Acc: 0.8261
2026-04-05 05:25:17,586 - INFO - Epoch 25/100 - Train Loss: 0.0965 - Val Acc: 0.8261
2026-04-05 05:25:17,902 - INFO - Epoch 26/100 - Train Loss: 0.0995 - Val Acc: 0.8261
2026-04-05 05:25:18,228 - INFO - Epoch 27/100 - Train Loss: 0.0813 - Val Acc: 0.8261
2026-04-05 05:25:18,549 - INFO - Epoch 28/100 - Train Loss: 0.0866 - Val Acc: 0.8261
2026-04-05 05:25:18,864 - INFO - Epoch 29/100 - Train Loss: 0.0869 - Val Acc: 0.8116
2026-04-05 05:25:19,184 - INFO - Epoch 30/100 - Train Loss: 0.0937 - Val Acc: 0.7971
2026-04-05 05:25:19,496 - INFO - Epoch 31/100 - Train Loss: 0.0871 - Val Acc: 0.8116
2026-04-05 05:25:19,813 - INFO - Epoch 32/100 - Train Loss: 0.0771 - Val Acc: 0.8261
2026-04-05 05:25:20,139 - INFO - Epoch 33/100 - Train Loss: 0.0822 - Val Acc: 0.8116
2026-04-05 05:25:20,453 - INFO - Epoch 34/100 - Train Loss: 0.0795 - Val Acc: 0.8261
2026-04-05 05:25:20,786 - INFO - Epoch 35/100 - Train Loss: 0.0734 - Val Acc: 0.8261
2026-04-05 05:25:21,101 - INFO - Epoch 36/100 - Train Loss: 0.0671 - Val Acc: 0.8261
2026-04-05 05:25:21,427 - INFO - Epoch 37/100 - Train Loss: 0.0693 - Val Acc: 0.8116
2026-04-05 05:25:21,759 - INFO - Epoch 38/100 - Train Loss: 0.0625 - Val Acc: 0.8261
2026-04-05 05:25:22,072 - INFO - Epoch 39/100 - Train Loss: 0.0679 - Val Acc: 0.7971
2026-04-05 05:25:22,387 - INFO - Epoch 40/100 - Train Loss: 0.0770 - Val Acc: 0.7971
2026-04-05 05:25:22,707 - INFO - Epoch 41/100 - Train Loss: 0.0745 - Val Acc: 0.7971
2026-04-05 05:25:23,028 - INFO - Epoch 42/100 - Train Loss: 0.0773 - Val Acc: 0.8116
2026-04-05 05:25:23,344 - INFO - Epoch 43/100 - Train Loss: 0.0735 - Val Acc: 0.7971
2026-04-05 05:25:23,662 - INFO - Epoch 44/100 - Train Loss: 0.0752 - Val Acc: 0.7971
2026-04-05 05:25:23,987 - INFO - Epoch 45/100 - Train Loss: 0.0784 - Val Acc: 0.8261
2026-04-05 05:25:24,338 - INFO - Epoch 46/100 - Train Loss: 0.0632 - Val Acc: 0.8116
2026-04-05 05:25:24,688 - INFO - Epoch 47/100 - Train Loss: 0.0662 - Val Acc: 0.7971
2026-04-05 05:25:25,003 - INFO - Epoch 48/100 - Train Loss: 0.0641 - Val Acc: 0.7971
2026-04-05 05:25:25,332 - INFO - Epoch 49/100 - Train Loss: 0.0551 - Val Acc: 0.8116
2026-04-05 05:25:25,651 - INFO - Epoch 50/100 - Train Loss: 0.0602 - Val Acc: 0.7971
2026-04-05 05:25:25,966 - INFO - Epoch 51/100 - Train Loss: 0.0669 - Val Acc: 0.8116
2026-04-05 05:25:26,283 - INFO - Epoch 52/100 - Train Loss: 0.0577 - Val Acc: 0.7971
2026-04-05 05:25:26,604 - INFO - Epoch 53/100 - Train Loss: 0.0567 - Val Acc: 0.8116
2026-04-05 05:25:26,918 - INFO - Epoch 54/100 - Train Loss: 0.0534 - Val Acc: 0.8261
2026-04-05 05:25:27,245 - INFO - Epoch 55/100 - Train Loss: 0.0522 - Val Acc: 0.7971
2026-04-05 05:25:27,560 - INFO - Epoch 56/100 - Train Loss: 0.0601 - Val Acc: 0.7971
2026-04-05 05:25:27,889 - INFO - Epoch 57/100 - Train Loss: 0.0569 - Val Acc: 0.7971
2026-04-05 05:25:28,206 - INFO - Epoch 58/100 - Train Loss: 0.0554 - Val Acc: 0.7971
2026-04-05 05:25:28,527 - INFO - Epoch 59/100 - Train Loss: 0.0531 - Val Acc: 0.8116
2026-04-05 05:25:28,844 - INFO - Epoch 60/100 - Train Loss: 0.0483 - Val Acc: 0.8116
2026-04-05 05:25:29,159 - INFO - Epoch 61/100 - Train Loss: 0.0536 - Val Acc: 0.7971
2026-04-05 05:25:29,474 - INFO - Epoch 62/100 - Train Loss: 0.0539 - Val Acc: 0.7971
2026-04-05 05:25:29,797 - INFO - Epoch 63/100 - Train Loss: 0.0465 - Val Acc: 0.7971
2026-04-05 05:25:30,126 - INFO - Epoch 64/100 - Train Loss: 0.0500 - Val Acc: 0.8116
2026-04-05 05:25:30,437 - INFO - Epoch 65/100 - Train Loss: 0.0446 - Val Acc: 0.7971
2026-04-05 05:25:30,757 - INFO - Epoch 66/100 - Train Loss: 0.0433 - Val Acc: 0.8116
2026-04-05 05:25:31,094 - INFO - Epoch 67/100 - Train Loss: 0.0490 - Val Acc: 0.8116
2026-04-05 05:25:31,406 - INFO - Epoch 68/100 - Train Loss: 0.0398 - Val Acc: 0.7971
2026-04-05 05:25:31,731 - INFO - Epoch 69/100 - Train Loss: 0.0405 - Val Acc: 0.7971
2026-04-05 05:25:32,047 - INFO - Epoch 70/100 - Train Loss: 0.0463 - Val Acc: 0.8116
2026-04-05 05:25:32,369 - INFO - Epoch 71/100 - Train Loss: 0.0596 - Val Acc: 0.7971
2026-04-05 05:25:32,688 - INFO - Epoch 72/100 - Train Loss: 0.0413 - Val Acc: 0.8116
2026-04-05 05:25:33,007 - INFO - Epoch 73/100 - Train Loss: 0.0433 - Val Acc: 0.8116
2026-04-05 05:25:33,339 - INFO - Epoch 74/100 - Train Loss: 0.0440 - Val Acc: 0.8116
2026-04-05 05:25:33,651 - INFO - Epoch 75/100 - Train Loss: 0.0427 - Val Acc: 0.8116
2026-04-05 05:25:33,958 - INFO - Epoch 76/100 - Train Loss: 0.0386 - Val Acc: 0.8116
2026-04-05 05:25:34,270 - INFO - Epoch 77/100 - Train Loss: 0.0466 - Val Acc: 0.8116
2026-04-05 05:25:34,599 - INFO - Epoch 78/100 - Train Loss: 0.0417 - Val Acc: 0.8261
2026-04-05 05:25:34,906 - INFO - Epoch 79/100 - Train Loss: 0.0449 - Val Acc: 0.8116
2026-04-05 05:25:35,220 - INFO - Epoch 80/100 - Train Loss: 0.0441 - Val Acc: 0.8116
2026-04-05 05:25:35,527 - INFO - Epoch 81/100 - Train Loss: 0.0353 - Val Acc: 0.8116
2026-04-05 05:25:35,843 - INFO - Epoch 82/100 - Train Loss: 0.0461 - Val Acc: 0.7971
2026-04-05 05:25:36,165 - INFO - Epoch 83/100 - Train Loss: 0.0360 - Val Acc: 0.7971
2026-04-05 05:25:36,475 - INFO - Epoch 84/100 - Train Loss: 0.0377 - Val Acc: 0.8116
2026-04-05 05:25:36,803 - INFO - Epoch 85/100 - Train Loss: 0.0397 - Val Acc: 0.7681
2026-04-05 05:25:37,126 - INFO - Epoch 86/100 - Train Loss: 0.0358 - Val Acc: 0.7826
2026-04-05 05:25:37,437 - INFO - Epoch 87/100 - Train Loss: 0.0523 - Val Acc: 0.7681
2026-04-05 05:25:37,754 - INFO - Epoch 88/100 - Train Loss: 0.0510 - Val Acc: 0.7971
2026-04-05 05:25:38,077 - INFO - Epoch 89/100 - Train Loss: 0.0392 - Val Acc: 0.7971
2026-04-05 05:25:38,393 - INFO - Epoch 90/100 - Train Loss: 0.0422 - Val Acc: 0.7971
2026-04-05 05:25:38,730 - INFO - Epoch 91/100 - Train Loss: 0.0336 - Val Acc: 0.8116
2026-04-05 05:25:39,054 - INFO - Epoch 92/100 - Train Loss: 0.0313 - Val Acc: 0.7971
2026-04-05 05:25:39,378 - INFO - Epoch 93/100 - Train Loss: 0.0340 - Val Acc: 0.8116
2026-04-05 05:25:39,697 - INFO - Epoch 94/100 - Train Loss: 0.0468 - Val Acc: 0.7826
2026-04-05 05:25:40,009 - INFO - Epoch 95/100 - Train Loss: 0.0479 - Val Acc: 0.7971
2026-04-05 05:25:40,327 - INFO - Epoch 96/100 - Train Loss: 0.0369 - Val Acc: 0.7971
2026-04-05 05:25:40,641 - INFO - Epoch 97/100 - Train Loss: 0.0398 - Val Acc: 0.7971
2026-04-05 05:25:40,949 - INFO - Epoch 98/100 - Train Loss: 0.0243 - Val Acc: 0.7971
2026-04-05 05:25:41,267 - INFO - Epoch 99/100 - Train Loss: 0.0304 - Val Acc: 0.8116
2026-04-05 05:25:41,588 - INFO - Epoch 100/100 - Train Loss: 0.0369 - Val Acc: 0.7826
2026-04-05 05:25:41,942 - INFO - Fold 9 logically complete. Tensor memory bounds cleared cleanly.
2026-04-05 05:25:41,946 - INFO - Original class distribution: [276 345]
2026-04-05 05:25:41,947 - INFO - Training device bound securely to: cuda
2026-04-05 05:25:41,963 - INFO - After SMOTE-ENN deployment: [345 288]

Fold 10:   0%|          | 0/100 [00:00<?, ?it/s]

2026-04-05 05:25:42,301 - INFO - Epoch 1/100 - Train Loss: 0.5882 - Val Acc: 0.8841
2026-04-05 05:25:42,629 - INFO - Epoch 2/100 - Train Loss: 0.3491 - Val Acc: 0.8841
2026-04-05 05:25:42,952 - INFO - Epoch 3/100 - Train Loss: 0.2331 - Val Acc: 0.9420
2026-04-05 05:25:43,276 - INFO - Epoch 4/100 - Train Loss: 0.2164 - Val Acc: 0.9275
2026-04-05 05:25:43,592 - INFO - Epoch 5/100 - Train Loss: 0.2053 - Val Acc: 0.9275
2026-04-05 05:25:43,900 - INFO - Epoch 6/100 - Train Loss: 0.1926 - Val Acc: 0.9275
2026-04-05 05:25:44,221 - INFO - Epoch 7/100 - Train Loss: 0.1872 - Val Acc: 0.9275
2026-04-05 05:25:44,590 - INFO - Epoch 8/100 - Train Loss: 0.1790 - Val Acc: 0.9420
2026-04-05 05:25:44,914 - INFO - Epoch 9/100 - Train Loss: 0.1709 - Val Acc: 0.9565
2026-04-05 05:25:45,236 - INFO - Epoch 10/100 - Train Loss: 0.1559 - Val Acc: 0.9420
2026-04-05 05:25:45,553 - INFO - Epoch 11/100 - Train Loss: 0.1788 - Val Acc: 0.9420
2026-04-05 05:25:45,879 - INFO - Epoch 12/100 - Train Loss: 0.1531 - Val Acc: 0.9420
2026-04-05 05:25:46,202 - INFO - Epoch 13/100 - Train Loss: 0.1484 - Val Acc: 0.9565
2026-04-05 05:25:46,518 - INFO - Epoch 14/100 - Train Loss: 0.1472 - Val Acc: 0.9565
2026-04-05 05:25:46,824 - INFO - Epoch 15/100 - Train Loss: 0.1377 - Val Acc: 0.9565
2026-04-05 05:25:47,141 - INFO - Epoch 16/100 - Train Loss: 0.1340 - Val Acc: 0.9565
2026-04-05 05:25:47,452 - INFO - Epoch 17/100 - Train Loss: 0.1356 - Val Acc: 0.9420
2026-04-05 05:25:47,760 - INFO - Epoch 18/100 - Train Loss: 0.1314 - Val Acc: 0.9420
2026-04-05 05:25:48,076 - INFO - Epoch 19/100 - Train Loss: 0.1349 - Val Acc: 0.9565
2026-04-05 05:25:48,409 - INFO - Epoch 20/100 - Train Loss: 0.1260 - Val Acc: 0.9565
2026-04-05 05:25:48,734 - INFO - Epoch 21/100 - Train Loss: 0.1270 - Val Acc: 0.9565
2026-04-05 05:25:49,053 - INFO - Epoch 22/100 - Train Loss: 0.1221 - Val Acc: 0.9565
2026-04-05 05:25:49,379 - INFO - Epoch 23/100 - Train Loss: 0.1247 - Val Acc: 0.9565
2026-04-05 05:25:49,699 - INFO - Epoch 24/100 - Train Loss: 0.1187 - Val Acc: 0.9565
2026-04-05 05:25:50,028 - INFO - Epoch 25/100 - Train Loss: 0.1265 - Val Acc: 0.9565
2026-04-05 05:25:50,346 - INFO - Epoch 26/100 - Train Loss: 0.1146 - Val Acc: 0.9565
2026-04-05 05:25:50,667 - INFO - Epoch 27/100 - Train Loss: 0.1172 - Val Acc: 0.9565
2026-04-05 05:25:50,980 - INFO - Epoch 28/100 - Train Loss: 0.1190 - Val Acc: 0.9710
2026-04-05 05:25:51,292 - INFO - Epoch 29/100 - Train Loss: 0.1175 - Val Acc: 0.9710
2026-04-05 05:25:51,613 - INFO - Epoch 30/100 - Train Loss: 0.1121 - Val Acc: 0.9710
2026-04-05 05:25:51,929 - INFO - Epoch 31/100 - Train Loss: 0.1135 - Val Acc: 0.9710
2026-04-05 05:25:52,280 - INFO - Epoch 32/100 - Train Loss: 0.1035 - Val Acc: 0.9710
2026-04-05 05:25:52,623 - INFO - Epoch 33/100 - Train Loss: 0.1027 - Val Acc: 0.9710
2026-04-05 05:25:52,972 - INFO - Epoch 34/100 - Train Loss: 0.1005 - Val Acc: 0.9565
2026-04-05 05:25:53,291 - INFO - Epoch 35/100 - Train Loss: 0.0885 - Val Acc: 0.9710
2026-04-05 05:25:53,614 - INFO - Epoch 36/100 - Train Loss: 0.0871 - Val Acc: 0.9710
2026-04-05 05:25:53,925 - INFO - Epoch 37/100 - Train Loss: 0.0960 - Val Acc: 0.9710
2026-04-05 05:25:54,266 - INFO - Epoch 38/100 - Train Loss: 0.0941 - Val Acc: 0.9710
2026-04-05 05:25:54,603 - INFO - Epoch 39/100 - Train Loss: 0.0922 - Val Acc: 0.9710
2026-04-05 05:25:54,920 - INFO - Epoch 40/100 - Train Loss: 0.0881 - Val Acc: 0.9710
2026-04-05 05:25:55,228 - INFO - Epoch 41/100 - Train Loss: 0.0891 - Val Acc: 0.9710
2026-04-05 05:25:55,539 - INFO - Epoch 42/100 - Train Loss: 0.0883 - Val Acc: 0.9710
2026-04-05 05:25:55,850 - INFO - Epoch 43/100 - Train Loss: 0.0828 - Val Acc: 0.9710
2026-04-05 05:25:56,164 - INFO - Epoch 44/100 - Train Loss: 0.0784 - Val Acc: 0.9710
2026-04-05 05:25:56,492 - INFO - Epoch 45/100 - Train Loss: 0.0911 - Val Acc: 0.9710
2026-04-05 05:25:56,810 - INFO - Epoch 46/100 - Train Loss: 0.0717 - Val Acc: 0.9710
2026-04-05 05:25:57,121 - INFO - Epoch 47/100 - Train Loss: 0.0845 - Val Acc: 0.9710
2026-04-05 05:25:57,431 - INFO - Epoch 48/100 - Train Loss: 0.0869 - Val Acc: 0.9565
2026-04-05 05:25:57,747 - INFO - Epoch 49/100 - Train Loss: 0.0724 - Val Acc: 0.9710
2026-04-05 05:25:58,069 - INFO - Epoch 50/100 - Train Loss: 0.0798 - Val Acc: 0.9710
2026-04-05 05:25:58,387 - INFO - Epoch 51/100 - Train Loss: 0.0765 - Val Acc: 0.9565
2026-04-05 05:25:58,709 - INFO - Epoch 52/100 - Train Loss: 0.0813 - Val Acc: 0.9565
2026-04-05 05:25:59,019 - INFO - Epoch 53/100 - Train Loss: 0.0739 - Val Acc: 0.9565
2026-04-05 05:25:59,337 - INFO - Epoch 54/100 - Train Loss: 0.0764 - Val Acc: 0.9565
2026-04-05 05:25:59,653 - INFO - Epoch 55/100 - Train Loss: 0.0743 - Val Acc: 0.9710
2026-04-05 05:25:59,973 - INFO - Epoch 56/100 - Train Loss: 0.0758 - Val Acc: 0.9710
2026-04-05 05:26:00,296 - INFO - Epoch 57/100 - Train Loss: 0.0724 - Val Acc: 0.9710
2026-04-05 05:26:00,607 - INFO - Epoch 58/100 - Train Loss: 0.0764 - Val Acc: 0.9710
2026-04-05 05:26:00,925 - INFO - Epoch 59/100 - Train Loss: 0.0668 - Val Acc: 0.9710
2026-04-05 05:26:01,240 - INFO - Epoch 60/100 - Train Loss: 0.0643 - Val Acc: 0.9710
2026-04-05 05:26:01,562 - INFO - Epoch 61/100 - Train Loss: 0.0628 - Val Acc: 0.9710
2026-04-05 05:26:01,886 - INFO - Epoch 62/100 - Train Loss: 0.0703 - Val Acc: 0.9710
2026-04-05 05:26:02,216 - INFO - Epoch 63/100 - Train Loss: 0.0701 - Val Acc: 0.9710
2026-04-05 05:26:02,542 - INFO - Epoch 64/100 - Train Loss: 0.0701 - Val Acc: 0.9710
2026-04-05 05:26:02,868 - INFO - Epoch 65/100 - Train Loss: 0.0757 - Val Acc: 0.9710
2026-04-05 05:26:03,183 - INFO - Epoch 66/100 - Train Loss: 0.0694 - Val Acc: 0.9710
2026-04-05 05:26:03,500 - INFO - Epoch 67/100 - Train Loss: 0.0658 - Val Acc: 0.9710
2026-04-05 05:26:03,815 - INFO - Epoch 68/100 - Train Loss: 0.0679 - Val Acc: 0.9710
2026-04-05 05:26:04,132 - INFO - Epoch 69/100 - Train Loss: 0.0519 - Val Acc: 0.9710
2026-04-05 05:26:04,475 - INFO - Epoch 70/100 - Train Loss: 0.0538 - Val Acc: 0.9710
2026-04-05 05:26:04,816 - INFO - Epoch 71/100 - Train Loss: 0.0599 - Val Acc: 0.9710
2026-04-05 05:26:05,133 - INFO - Epoch 72/100 - Train Loss: 0.0686 - Val Acc: 0.9710
2026-04-05 05:26:05,447 - INFO - Epoch 73/100 - Train Loss: 0.0493 - Val Acc: 0.9710
2026-04-05 05:26:05,760 - INFO - Epoch 74/100 - Train Loss: 0.0583 - Val Acc: 0.9710
2026-04-05 05:26:06,074 - INFO - Epoch 75/100 - Train Loss: 0.0514 - Val Acc: 0.9710
2026-04-05 05:26:06,387 - INFO - Epoch 76/100 - Train Loss: 0.0526 - Val Acc: 0.9710
2026-04-05 05:26:06,692 - INFO - Epoch 77/100 - Train Loss: 0.0479 - Val Acc: 0.9710
2026-04-05 05:26:07,013 - INFO - Epoch 78/100 - Train Loss: 0.0469 - Val Acc: 0.9710
2026-04-05 05:26:07,315 - INFO - Epoch 79/100 - Train Loss: 0.0503 - Val Acc: 0.9710
2026-04-05 05:26:07,631 - INFO - Epoch 80/100 - Train Loss: 0.0505 - Val Acc: 0.9710
2026-04-05 05:26:07,950 - INFO - Epoch 81/100 - Train Loss: 0.0656 - Val Acc: 0.9710
2026-04-05 05:26:08,268 - INFO - Epoch 82/100 - Train Loss: 0.0432 - Val Acc: 0.9710
2026-04-05 05:26:08,589 - INFO - Epoch 83/100 - Train Loss: 0.0396 - Val Acc: 0.9710
2026-04-05 05:26:08,901 - INFO - Epoch 84/100 - Train Loss: 0.0406 - Val Acc: 0.9710
2026-04-05 05:26:09,216 - INFO - Epoch 85/100 - Train Loss: 0.0572 - Val Acc: 0.9710
2026-04-05 05:26:09,535 - INFO - Epoch 86/100 - Train Loss: 0.0473 - Val Acc: 0.9710
2026-04-05 05:26:09,855 - INFO - Epoch 87/100 - Train Loss: 0.0479 - Val Acc: 0.9710
2026-04-05 05:26:10,166 - INFO - Epoch 88/100 - Train Loss: 0.0437 - Val Acc: 0.9710
2026-04-05 05:26:10,482 - INFO - Epoch 89/100 - Train Loss: 0.0495 - Val Acc: 0.9710
2026-04-05 05:26:10,797 - INFO - Epoch 90/100 - Train Loss: 0.0503 - Val Acc: 0.9710
2026-04-05 05:26:11,106 - INFO - Epoch 91/100 - Train Loss: 0.0585 - Val Acc: 0.9710
2026-04-05 05:26:11,429 - INFO - Epoch 92/100 - Train Loss: 0.0513 - Val Acc: 0.9710
2026-04-05 05:26:11,737 - INFO - Epoch 93/100 - Train Loss: 0.0434 - Val Acc: 0.9710
2026-04-05 05:26:12,059 - INFO - Epoch 94/100 - Train Loss: 0.0408 - Val Acc: 0.9710
2026-04-05 05:26:12,368 - INFO - Epoch 95/100 - Train Loss: 0.0367 - Val Acc: 0.9710
2026-04-05 05:26:12,685 - INFO - Epoch 96/100 - Train Loss: 0.0459 - Val Acc: 0.9710
2026-04-05 05:26:13,023 - INFO - Epoch 97/100 - Train Loss: 0.0426 - Val Acc: 0.9710
2026-04-05 05:26:13,344 - INFO - Epoch 98/100 - Train Loss: 0.0414 - Val Acc: 0.9710
2026-04-05 05:26:13,656 - INFO - Epoch 99/100 - Train Loss: 0.0402 - Val Acc: 0.9710
2026-04-05 05:26:13,965 - INFO - Epoch 100/100 - Train Loss: 0.0391 - Val Acc: 0.9710
2026-04-05 05:26:14,316 - INFO - Fold 10 logically complete. Tensor memory bounds cleared cleanly.
2026-04-05 05:26:14,334 - INFO - ✓ Completed MLP_smoteenn
2026-04-05 05:26:14,335 - INFO -   Mean Accuracy: 0.8754 ± 0.0477
2026-04-05 05:26:14,336 - INFO -
EXPERIMENT: LSTM_BASELINE | german | SMOTE-ENN: False

German | LSTM | BASELINE:   0%|          | 0/10 [00:00<?, ?it/s]

2026-04-05 05:26:14,348 - INFO - Original class distribution: [277 344]
2026-04-05 05:26:14,349 - INFO - Training device bound securely to: cuda

Fold 1:   0%|          | 0/100 [00:00<?, ?it/s]

2026-04-05 05:26:14,951 - INFO - Epoch 1/100 - Train Loss: 0.5582 - Val Acc: 0.8551
2026-04-05 05:26:15,226 - INFO - Epoch 2/100 - Train Loss: 0.4085 - Val Acc: 0.8696
2026-04-05 05:26:15,505 - INFO - Epoch 3/100 - Train Loss: 0.3667 - Val Acc: 0.8986
2026-04-05 05:26:15,782 - INFO - Epoch 4/100 - Train Loss: 0.3461 - Val Acc: 0.8986
2026-04-05 05:26:16,050 - INFO - Epoch 5/100 - Train Loss: 0.3327 - Val Acc: 0.8986
2026-04-05 05:26:16,321 - INFO - Epoch 6/100 - Train Loss: 0.3248 - Val Acc: 0.8986
2026-04-05 05:26:16,601 - INFO - Epoch 7/100 - Train Loss: 0.3199 - Val Acc: 0.8986
2026-04-05 05:26:16,887 - INFO - Epoch 8/100 - Train Loss: 0.3152 - Val Acc: 0.8986
2026-04-05 05:26:17,163 - INFO - Epoch 9/100 - Train Loss: 0.3094 - Val Acc: 0.8986
2026-04-05 05:26:17,433 - INFO - Epoch 10/100 - Train Loss: 0.3071 - Val Acc: 0.8986
2026-04-05 05:26:17,708 - INFO - Epoch 11/100 - Train Loss: 0.3061 - Val Acc: 0.8986
2026-04-05 05:26:17,977 - INFO - Epoch 12/100 - Train Loss: 0.3050 - Val Acc: 0.9130
2026-04-05 05:26:18,251 - INFO - Epoch 13/100 - Train Loss: 0.3019 - Val Acc: 0.9130
2026-04-05 05:26:18,547 - INFO - Epoch 14/100 - Train Loss: 0.3014 - Val Acc: 0.9130
2026-04-05 05:26:18,817 - INFO - Epoch 15/100 - Train Loss: 0.2982 - Val Acc: 0.9130
2026-04-05 05:26:19,077 - INFO - Epoch 16/100 - Train Loss: 0.2980 - Val Acc: 0.9130
2026-04-05 05:26:19,348 - INFO - Epoch 17/100 - Train Loss: 0.2935 - Val Acc: 0.9130
2026-04-05 05:26:19,613 - INFO - Epoch 18/100 - Train Loss: 0.2933 - Val Acc: 0.9130
2026-04-05 05:26:19,881 - INFO - Epoch 19/100 - Train Loss: 0.2926 - Val Acc: 0.9130
2026-04-05 05:26:20,162 - INFO - Epoch 20/100 - Train Loss: 0.2912 - Val Acc: 0.9130
2026-04-05 05:26:20,461 - INFO - Epoch 21/100 - Train Loss: 0.2916 - Val Acc: 0.9130
2026-04-05 05:26:20,736 - INFO - Epoch 22/100 - Train Loss: 0.2886 - Val Acc: 0.9130
2026-04-05 05:26:21,000 - INFO - Epoch 23/100 - Train Loss: 0.2881 - Val Acc: 0.9130
2026-04-05 05:26:21,272 - INFO - Epoch 24/100 - Train Loss: 0.2868 - Val Acc: 0.9130
2026-04-05 05:26:21,563 - INFO - Epoch 25/100 - Train Loss: 0.2855 - Val Acc: 0.9130
2026-04-05 05:26:21,842 - INFO - Epoch 26/100 - Train Loss: 0.2871 - Val Acc: 0.9130
2026-04-05 05:26:22,117 - INFO - Epoch 27/100 - Train Loss: 0.2852 - Val Acc: 0.9130
2026-04-05 05:26:22,389 - INFO - Epoch 28/100 - Train Loss: 0.2817 - Val Acc: 0.9130
2026-04-05 05:26:22,674 - INFO - Epoch 29/100 - Train Loss: 0.2815 - Val Acc: 0.9130
2026-04-05 05:26:22,967 - INFO - Epoch 30/100 - Train Loss: 0.2853 - Val Acc: 0.9130
2026-04-05 05:26:23,240 - INFO - Epoch 31/100 - Train Loss: 0.2778 - Val Acc: 0.9130
2026-04-05 05:26:23,521 - INFO - Epoch 32/100 - Train Loss: 0.2759 - Val Acc: 0.9130
2026-04-05 05:26:23,805 - INFO - Epoch 33/100 - Train Loss: 0.2789 - Val Acc: 0.9130
2026-04-05 05:26:24,072 - INFO - Epoch 34/100 - Train Loss: 0.2746 - Val Acc: 0.8986
2026-04-05 05:26:24,376 - INFO - Epoch 35/100 - Train Loss: 0.2793 - Val Acc: 0.8986
2026-04-05 05:26:24,677 - INFO - Epoch 36/100 - Train Loss: 0.2718 - Val Acc: 0.8986
2026-04-05 05:26:24,945 - INFO - Epoch 37/100 - Train Loss: 0.2753 - Val Acc: 0.9130
2026-04-05 05:26:25,237 - INFO - Epoch 38/100 - Train Loss: 0.2724 - Val Acc: 0.9130
2026-04-05 05:26:25,508 - INFO - Epoch 39/100 - Train Loss: 0.2721 - Val Acc: 0.8986
2026-04-05 05:26:25,773 - INFO - Epoch 40/100 - Train Loss: 0.2703 - Val Acc: 0.8986
2026-04-05 05:26:26,047 - INFO - Epoch 41/100 - Train Loss: 0.2680 - Val Acc: 0.8986
2026-04-05 05:26:26,316 - INFO - Epoch 42/100 - Train Loss: 0.2688 - Val Acc: 0.8986
2026-04-05 05:26:26,585 - INFO - Epoch 43/100 - Train Loss: 0.2661 - Val Acc: 0.9130
2026-04-05 05:26:26,868 - INFO - Epoch 44/100 - Train Loss: 0.2655 - Val Acc: 0.9130
2026-04-05 05:26:27,132 - INFO - Epoch 45/100 - Train Loss: 0.2671 - Val Acc: 0.8986
2026-04-05 05:26:27,399 - INFO - Epoch 46/100 - Train Loss: 0.2632 - Val Acc: 0.8986
2026-04-05 05:26:27,661 - INFO - Epoch 47/100 - Train Loss: 0.2617 - Val Acc: 0.8986
2026-04-05 05:26:27,932 - INFO - Epoch 48/100 - Train Loss: 0.2609 - Val Acc: 0.8986
2026-04-05 05:26:28,217 - INFO - Epoch 49/100 - Train Loss: 0.2624 - Val Acc: 0.8986
2026-04-05 05:26:28,503 - INFO - Epoch 50/100 - Train Loss: 0.2602 - Val Acc: 0.8986
2026-04-05 05:26:28,772 - INFO - Epoch 51/100 - Train Loss: 0.2591 - Val Acc: 0.8986
2026-04-05 05:26:29,048 - INFO - Epoch 52/100 - Train Loss: 0.2589 - Val Acc: 0.8986
2026-04-05 05:26:29,322 - INFO - Epoch 53/100 - Train Loss: 0.2582 - Val Acc: 0.8986
2026-04-05 05:26:29,606 - INFO - Epoch 54/100 - Train Loss: 0.2598 - Val Acc: 0.8986
2026-04-05 05:26:29,878 - INFO - Epoch 55/100 - Train Loss: 0.2560 - Val Acc: 0.8986
2026-04-05 05:26:30,156 - INFO - Epoch 56/100 - Train Loss: 0.2553 - Val Acc: 0.8986
2026-04-05 05:26:30,428 - INFO - Epoch 57/100 - Train Loss: 0.2553 - Val Acc: 0.8986
2026-04-05 05:26:30,699 - INFO - Epoch 58/100 - Train Loss: 0.2547 - Val Acc: 0.8986
2026-04-05 05:26:30,964 - INFO - Epoch 59/100 - Train Loss: 0.2512 - Val Acc: 0.8986
2026-04-05 05:26:31,234 - INFO - Epoch 60/100 - Train Loss: 0.2485 - Val Acc: 0.8841
2026-04-05 05:26:31,511 - INFO - Epoch 61/100 - Train Loss: 0.2499 - Val Acc: 0.8841
2026-04-05 05:26:31,789 - INFO - Epoch 62/100 - Train Loss: 0.2519 - Val Acc: 0.8841
2026-04-05 05:26:32,063 - INFO - Epoch 63/100 - Train Loss: 0.2530 - Val Acc: 0.8841
2026-04-05 05:26:32,329 - INFO - Epoch 64/100 - Train Loss: 0.2501 - Val Acc: 0.8841
2026-04-05 05:26:32,600 - INFO - Epoch 65/100 - Train Loss: 0.2484 - Val Acc: 0.8841
2026-04-05 05:26:32,877 - INFO - Epoch 66/100 - Train Loss: 0.2499 - Val Acc: 0.8841
2026-04-05 05:26:33,153 - INFO - Epoch 67/100 - Train Loss: 0.2478 - Val Acc: 0.8841
2026-04-05 05:26:33,430 - INFO - Epoch 68/100 - Train Loss: 0.2460 - Val Acc: 0.8841
2026-04-05 05:26:33,709 - INFO - Epoch 69/100 - Train Loss: 0.2445 - Val Acc: 0.8841
2026-04-05 05:26:33,995 - INFO - Epoch 70/100 - Train Loss: 0.2441 - Val Acc: 0.8841
2026-04-05 05:26:34,280 - INFO - Epoch 71/100 - Train Loss: 0.2462 - Val Acc: 0.8841
2026-04-05 05:26:34,593 - INFO - Epoch 72/100 - Train Loss: 0.2421 - Val Acc: 0.8841
2026-04-05 05:26:34,890 - INFO - Epoch 73/100 - Train Loss: 0.2425 - Val Acc: 0.8841
2026-04-05 05:26:35,159 - INFO - Epoch 74/100 - Train Loss: 0.2422 - Val Acc: 0.8841
2026-04-05 05:26:35,441 - INFO - Epoch 75/100 - Train Loss: 0.2367 - Val Acc: 0.8841
2026-04-05 05:26:35,717 - INFO - Epoch 76/100 - Train Loss: 0.2400 - Val Acc: 0.8841
2026-04-05 05:26:35,991 - INFO - Epoch 77/100 - Train Loss: 0.2361 - Val Acc: 0.8841
2026-04-05 05:26:36,272 - INFO - Epoch 78/100 - Train Loss: 0.2397 - Val Acc: 0.8841
2026-04-05 05:26:36,541 - INFO - Epoch 79/100 - Train Loss: 0.2390 - Val Acc: 0.8841
2026-04-05 05:26:36,811 - INFO - Epoch 80/100 - Train Loss: 0.2359 - Val Acc: 0.8841
2026-04-05 05:26:37,075 - INFO - Epoch 81/100 - Train Loss: 0.2403 - Val Acc: 0.8841
2026-04-05 05:26:37,344 - INFO - Epoch 82/100 - Train Loss: 0.2368 - Val Acc: 0.8841
2026-04-05 05:26:37,610 - INFO - Epoch 83/100 - Train Loss: 0.2362 - Val Acc: 0.8841
2026-04-05 05:26:37,873 - INFO - Epoch 84/100 - Train Loss: 0.2337 - Val Acc: 0.8841
2026-04-05 05:26:38,156 - INFO - Epoch 85/100 - Train Loss: 0.2340 - Val Acc: 0.8841
2026-04-05 05:26:38,425 - INFO - Epoch 86/100 - Train Loss: 0.2353 - Val Acc: 0.8841
2026-04-05 05:26:38,683 - INFO - Epoch 87/100 - Train Loss: 0.2319 - Val Acc: 0.8841
2026-04-05 05:26:38,953 - INFO - Epoch 88/100 - Train Loss: 0.2328 - Val Acc: 0.8841
2026-04-05 05:26:39,221 - INFO - Epoch 89/100 - Train Loss: 0.2289 - Val Acc: 0.8841
2026-04-05 05:26:39,498 - INFO - Epoch 90/100 - Train Loss: 0.2315 - Val Acc: 0.8696
2026-04-05 05:26:39,773 - INFO - Epoch 91/100 - Train Loss: 0.2277 - Val Acc: 0.8696
2026-04-05 05:26:40,046 - INFO - Epoch 92/100 - Train Loss: 0.2287 - Val Acc: 0.8696
2026-04-05 05:26:40,328 - INFO - Epoch 93/100 - Train Loss: 0.2317 - Val Acc: 0.8696
2026-04-05 05:26:40,606 - INFO - Epoch 94/100 - Train Loss: 0.2292 - Val Acc: 0.8696
2026-04-05 05:26:40,890 - INFO - Epoch 95/100 - Train Loss: 0.2279 - Val Acc: 0.8696
2026-04-05 05:26:41,165 - INFO - Epoch 96/100 - Train Loss: 0.2246 - Val Acc: 0.8696
2026-04-05 05:26:41,444 - INFO - Epoch 97/100 - Train Loss: 0.2250 - Val Acc: 0.8696
2026-04-05 05:26:41,721 - INFO - Epoch 98/100 - Train Loss: 0.2245 - Val Acc: 0.8696
2026-04-05 05:26:42,001 - INFO - Epoch 99/100 - Train Loss: 0.2304 - Val Acc: 0.8696
2026-04-05 05:26:42,284 - INFO - Epoch 100/100 - Train Loss: 0.2284 - Val Acc: 0.8696
2026-04-05 05:26:42,647 - INFO - Fold 1 logically complete. Tensor memory bounds cleared cleanly.
2026-04-05 05:26:42,651 - INFO - Original class distribution: [277 344]
2026-04-05 05:26:42,652 - INFO - Training device bound securely to: cuda

Fold 2:   0%|          | 0/100 [00:00<?, ?it/s]

2026-04-05 05:26:42,943 - INFO - Epoch 1/100 - Train Loss: 0.5655 - Val Acc: 0.7391
2026-04-05 05:26:43,212 - INFO - Epoch 2/100 - Train Loss: 0.4086 - Val Acc: 0.7681
2026-04-05 05:26:43,497 - INFO - Epoch 3/100 - Train Loss: 0.3601 - Val Acc: 0.8116
2026-04-05 05:26:43,784 - INFO - Epoch 4/100 - Train Loss: 0.3422 - Val Acc: 0.8116
2026-04-05 05:26:44,056 - INFO - Epoch 5/100 - Train Loss: 0.3303 - Val Acc: 0.8551
2026-04-05 05:26:44,356 - INFO - Epoch 6/100 - Train Loss: 0.3218 - Val Acc: 0.8551
2026-04-05 05:26:44,675 - INFO - Epoch 7/100 - Train Loss: 0.3167 - Val Acc: 0.8696
2026-04-05 05:26:44,961 - INFO - Epoch 8/100 - Train Loss: 0.3089 - Val Acc: 0.8841
2026-04-05 05:26:45,239 - INFO - Epoch 9/100 - Train Loss: 0.3055 - Val Acc: 0.8986
2026-04-05 05:26:45,524 - INFO - Epoch 10/100 - Train Loss: 0.3043 - Val Acc: 0.8986
2026-04-05 05:26:45,816 - INFO - Epoch 11/100 - Train Loss: 0.3017 - Val Acc: 0.8986
2026-04-05 05:26:46,088 - INFO - Epoch 12/100 - Train Loss: 0.2973 - Val Acc: 0.8986
2026-04-05 05:26:46,363 - INFO - Epoch 13/100 - Train Loss: 0.2981 - Val Acc: 0.8986
2026-04-05 05:26:46,639 - INFO - Epoch 14/100 - Train Loss: 0.2936 - Val Acc: 0.8986
2026-04-05 05:26:46,906 - INFO - Epoch 15/100 - Train Loss: 0.2937 - Val Acc: 0.8986
2026-04-05 05:26:47,180 - INFO - Epoch 16/100 - Train Loss: 0.2917 - Val Acc: 0.8986
2026-04-05 05:26:47,450 - INFO - Epoch 17/100 - Train Loss: 0.2918 - Val Acc: 0.8986
2026-04-05 05:26:47,735 - INFO - Epoch 18/100 - Train Loss: 0.2864 - Val Acc: 0.8986
2026-04-05 05:26:48,009 - INFO - Epoch 19/100 - Train Loss: 0.2885 - Val Acc: 0.8986
2026-04-05 05:26:48,288 - INFO - Epoch 20/100 - Train Loss: 0.2857 - Val Acc: 0.8986
2026-04-05 05:26:48,559 - INFO - Epoch 21/100 - Train Loss: 0.2879 - Val Acc: 0.8986
2026-04-05 05:26:48,842 - INFO - Epoch 22/100 - Train Loss: 0.2846 - Val Acc: 0.8986
2026-04-05 05:26:49,104 - INFO - Epoch 23/100 - Train Loss: 0.2813 - Val Acc: 0.8986
2026-04-05 05:26:49,380 - INFO - Epoch 24/100 - Train Loss: 0.2796 - Val Acc: 0.8986
2026-04-05 05:26:49,668 - INFO - Epoch 25/100 - Train Loss: 0.2801 - Val Acc: 0.8986
2026-04-05 05:26:49,947 - INFO - Epoch 26/100 - Train Loss: 0.2791 - Val Acc: 0.8986
2026-04-05 05:26:50,213 - INFO - Epoch 27/100 - Train Loss: 0.2771 - Val Acc: 0.8986
2026-04-05 05:26:50,482 - INFO - Epoch 28/100 - Train Loss: 0.2786 - Val Acc: 0.8986
2026-04-05 05:26:50,755 - INFO - Epoch 29/100 - Train Loss: 0.2763 - Val Acc: 0.8986
2026-04-05 05:26:51,040 - INFO - Epoch 30/100 - Train Loss: 0.2720 - Val Acc: 0.8986
2026-04-05 05:26:51,316 - INFO - Epoch 31/100 - Train Loss: 0.2749 - Val Acc: 0.8986
2026-04-05 05:26:51,599 - INFO - Epoch 32/100 - Train Loss: 0.2744 - Val Acc: 0.8986
2026-04-05 05:26:51,876 - INFO - Epoch 33/100 - Train Loss: 0.2721 - Val Acc: 0.8986
2026-04-05 05:26:52,150 - INFO - Epoch 34/100 - Train Loss: 0.2701 - Val Acc: 0.8986
2026-04-05 05:26:52,418 - INFO - Epoch 35/100 - Train Loss: 0.2671 - Val Acc: 0.8986
2026-04-05 05:26:52,707 - INFO - Epoch 36/100 - Train Loss: 0.2690 - Val Acc: 0.8986
2026-04-05 05:26:52,979 - INFO - Epoch 37/100 - Train Loss: 0.2652 - Val Acc: 0.8986
2026-04-05 05:26:53,249 - INFO - Epoch 38/100 - Train Loss: 0.2676 - Val Acc: 0.8986
2026-04-05 05:26:53,515 - INFO - Epoch 39/100 - Train Loss: 0.2657 - Val Acc: 0.8986
2026-04-05 05:26:53,788 - INFO - Epoch 40/100 - Train Loss: 0.2639 - Val Acc: 0.8986
2026-04-05 05:26:54,058 - INFO - Epoch 41/100 - Train Loss: 0.2640 - Val Acc: 0.8986
2026-04-05 05:26:54,378 - INFO - Epoch 42/100 - Train Loss: 0.2605 - Val Acc: 0.8986
2026-04-05 05:26:54,684 - INFO - Epoch 43/100 - Train Loss: 0.2616 - Val Acc: 0.8986
2026-04-05 05:26:54,952 - INFO - Epoch 44/100 - Train Loss: 0.2595 - Val Acc: 0.8986
2026-04-05 05:26:55,238 - INFO - Epoch 45/100 - Train Loss: 0.2599 - Val Acc: 0.8986
2026-04-05 05:26:55,506 - INFO - Epoch 46/100 - Train Loss: 0.2574 - Val Acc: 0.8986
2026-04-05 05:26:55,788 - INFO - Epoch 47/100 - Train Loss: 0.2579 - Val Acc: 0.8986
2026-04-05 05:26:56,083 - INFO - Epoch 48/100 - Train Loss: 0.2535 - Val Acc: 0.8986
2026-04-05 05:26:56,357 - INFO - Epoch 49/100 - Train Loss: 0.2564 - Val Acc: 0.9130
2026-04-05 05:26:56,640 - INFO - Epoch 50/100 - Train Loss: 0.2508 - Val Acc: 0.9130
2026-04-05 05:26:56,916 - INFO - Epoch 51/100 - Train Loss: 0.2534 - Val Acc: 0.9130
2026-04-05 05:26:57,194 - INFO - Epoch 52/100 - Train Loss: 0.2542 - Val Acc: 0.9130
2026-04-05 05:26:57,477 - INFO - Epoch 53/100 - Train Loss: 0.2543 - Val Acc: 0.9130
2026-04-05 05:26:57,741 - INFO - Epoch 54/100 - Train Loss: 0.2545 - Val Acc: 0.9130
2026-04-05 05:26:58,020 - INFO - Epoch 55/100 - Train Loss: 0.2513 - Val Acc: 0.8986
2026-04-05 05:26:58,294 - INFO - Epoch 56/100 - Train Loss: 0.2527 - Val Acc: 0.8986
2026-04-05 05:26:58,567 - INFO - Epoch 57/100 - Train Loss: 0.2511 - Val Acc: 0.8986
2026-04-05 05:26:58,849 - INFO - Epoch 58/100 - Train Loss: 0.2499 - Val Acc: 0.8986
2026-04-05 05:26:59,111 - INFO - Epoch 59/100 - Train Loss: 0.2471 - Val Acc: 0.8841
2026-04-05 05:26:59,382 - INFO - Epoch 60/100 - Train Loss: 0.2464 - Val Acc: 0.8841
2026-04-05 05:26:59,658 - INFO - Epoch 61/100 - Train Loss: 0.2464 - Val Acc: 0.8841
2026-04-05 05:26:59,944 - INFO - Epoch 62/100 - Train Loss: 0.2454 - Val Acc: 0.8841
2026-04-05 05:27:00,216 - INFO - Epoch 63/100 - Train Loss: 0.2483 - Val Acc: 0.8841
2026-04-05 05:27:00,485 - INFO - Epoch 64/100 - Train Loss: 0.2469 - Val Acc: 0.8841
2026-04-05 05:27:00,758 - INFO - Epoch 65/100 - Train Loss: 0.2418 - Val Acc: 0.8841
2026-04-05 05:27:01,029 - INFO - Epoch 66/100 - Train Loss: 0.2452 - Val Acc: 0.8841
2026-04-05 05:27:01,302 - INFO - Epoch 67/100 - Train Loss: 0.2388 - Val Acc: 0.8841
2026-04-05 05:27:01,583 - INFO - Epoch 68/100 - Train Loss: 0.2415 - Val Acc: 0.8841
2026-04-05 05:27:01,857 - INFO - Epoch 69/100 - Train Loss: 0.2349 - Val Acc: 0.8841
2026-04-05 05:27:02,133 - INFO - Epoch 70/100 - Train Loss: 0.2422 - Val Acc: 0.8841
2026-04-05 05:27:02,403 - INFO - Epoch 71/100 - Train Loss: 0.2377 - Val Acc: 0.8841
2026-04-05 05:27:02,675 - INFO - Epoch 72/100 - Train Loss: 0.2364 - Val Acc: 0.8841
2026-04-05 05:27:02,941 - INFO - Epoch 73/100 - Train Loss: 0.2385 - Val Acc: 0.8841
2026-04-05 05:27:03,219 - INFO - Epoch 74/100 - Train Loss: 0.2368 - Val Acc: 0.8841
2026-04-05 05:27:03,490 - INFO - Epoch 75/100 - Train Loss: 0.2379 - Val Acc: 0.8841
2026-04-05 05:27:03,754 - INFO - Epoch 76/100 - Train Loss: 0.2411 - Val Acc: 0.8841
2026-04-05 05:27:04,019 - INFO - Epoch 77/100 - Train Loss: 0.2373 - Val Acc: 0.8841
2026-04-05 05:27:04,316 - INFO - Epoch 78/100 - Train Loss: 0.2344 - Val Acc: 0.8841
2026-04-05 05:27:04,611 - INFO - Epoch 79/100 - Train Loss: 0.2358 - Val Acc: 0.8841
2026-04-05 05:27:04,884 - INFO - Epoch 80/100 - Train Loss: 0.2347 - Val Acc: 0.8841
2026-04-05 05:27:05,153 - INFO - Epoch 81/100 - Train Loss: 0.2353 - Val Acc: 0.8841
2026-04-05 05:27:05,419 - INFO - Epoch 82/100 - Train Loss: 0.2346 - Val Acc: 0.8841
2026-04-05 05:27:05,691 - INFO - Epoch 83/100 - Train Loss: 0.2296 - Val Acc: 0.8841
2026-04-05 05:27:05,963 - INFO - Epoch 84/100 - Train Loss: 0.2349 - Val Acc: 0.8841
2026-04-05 05:27:06,236 - INFO - Epoch 85/100 - Train Loss: 0.2303 - Val Acc: 0.8841
2026-04-05 05:27:06,504 - INFO - Epoch 86/100 - Train Loss: 0.2316 - Val Acc: 0.8841
2026-04-05 05:27:06,772 - INFO - Epoch 87/100 - Train Loss: 0.2321 - Val Acc: 0.8841
2026-04-05 05:27:07,047 - INFO - Epoch 88/100 - Train Loss: 0.2318 - Val Acc: 0.8841
2026-04-05 05:27:07,319 - INFO - Epoch 89/100 - Train Loss: 0.2292 - Val Acc: 0.8841
2026-04-05 05:27:07,604 - INFO - Epoch 90/100 - Train Loss: 0.2286 - Val Acc: 0.8841
2026-04-05 05:27:07,877 - INFO - Epoch 91/100 - Train Loss: 0.2312 - Val Acc: 0.8841
2026-04-05 05:27:08,148 - INFO - Epoch 92/100 - Train Loss: 0.2282 - Val Acc: 0.8841
2026-04-05 05:27:08,410 - INFO - Epoch 93/100 - Train Loss: 0.2267 - Val Acc: 0.8841
2026-04-05 05:27:08,677 - INFO - Epoch 94/100 - Train Loss: 0.2304 - Val Acc: 0.8841
2026-04-05 05:27:08,956 - INFO - Epoch 95/100 - Train Loss: 0.2235 - Val Acc: 0.8841
2026-04-05 05:27:09,231 - INFO - Epoch 96/100 - Train Loss: 0.2253 - Val Acc: 0.8841
2026-04-05 05:27:09,494 - INFO - Epoch 97/100 - Train Loss: 0.2246 - Val Acc: 0.8841
2026-04-05 05:27:09,773 - INFO - Epoch 98/100 - Train Loss: 0.2301 - Val Acc: 0.8841
2026-04-05 05:27:10,036 - INFO - Epoch 99/100 - Train Loss: 0.2269 - Val Acc: 0.8841
2026-04-05 05:27:10,326 - INFO - Epoch 100/100 - Train Loss: 0.2236 - Val Acc: 0.8841
2026-04-05 05:27:10,678 - INFO - Fold 2 logically complete. Tensor memory bounds cleared cleanly.
2026-04-05 05:27:10,682 - INFO - Original class distribution: [277 344]
2026-04-05 05:27:10,683 - INFO - Training device bound securely to: cuda

Fold 3:   0%|          | 0/100 [00:00<?, ?it/s]

2026-04-05 05:27:10,978 - INFO - Epoch 1/100 - Train Loss: 0.5696 - Val Acc: 0.9420
2026-04-05 05:27:11,249 - INFO - Epoch 2/100 - Train Loss: 0.4182 - Val Acc: 0.9420
2026-04-05 05:27:11,522 - INFO - Epoch 3/100 - Train Loss: 0.3760 - Val Acc: 0.9275
2026-04-05 05:27:11,800 - INFO - Epoch 4/100 - Train Loss: 0.3526 - Val Acc: 0.9275
2026-04-05 05:27:12,067 - INFO - Epoch 5/100 - Train Loss: 0.3392 - Val Acc: 0.9130
2026-04-05 05:27:12,326 - INFO - Epoch 6/100 - Train Loss: 0.3283 - Val Acc: 0.9130
2026-04-05 05:27:12,596 - INFO - Epoch 7/100 - Train Loss: 0.3253 - Val Acc: 0.9130
2026-04-05 05:27:12,872 - INFO - Epoch 8/100 - Train Loss: 0.3172 - Val Acc: 0.9130
2026-04-05 05:27:13,135 - INFO - Epoch 9/100 - Train Loss: 0.3136 - Val Acc: 0.9130
2026-04-05 05:27:13,406 - INFO - Epoch 10/100 - Train Loss: 0.3100 - Val Acc: 0.9130
2026-04-05 05:27:13,668 - INFO - Epoch 11/100 - Train Loss: 0.3064 - Val Acc: 0.9130
2026-04-05 05:27:13,935 - INFO - Epoch 12/100 - Train Loss: 0.3048 - Val Acc: 0.9130
2026-04-05 05:27:14,211 - INFO - Epoch 13/100 - Train Loss: 0.3017 - Val Acc: 0.9130
2026-04-05 05:27:14,500 - INFO - Epoch 14/100 - Train Loss: 0.2997 - Val Acc: 0.9130
2026-04-05 05:27:14,788 - INFO - Epoch 15/100 - Train Loss: 0.2993 - Val Acc: 0.9130
2026-04-05 05:27:15,056 - INFO - Epoch 16/100 - Train Loss: 0.2996 - Val Acc: 0.9130
2026-04-05 05:27:15,344 - INFO - Epoch 17/100 - Train Loss: 0.2958 - Val Acc: 0.9130
2026-04-05 05:27:15,626 - INFO - Epoch 18/100 - Train Loss: 0.2960 - Val Acc: 0.9130
2026-04-05 05:27:15,902 - INFO - Epoch 19/100 - Train Loss: 0.2935 - Val Acc: 0.9130
2026-04-05 05:27:16,172 - INFO - Epoch 20/100 - Train Loss: 0.2942 - Val Acc: 0.9130
2026-04-05 05:27:16,447 - INFO - Epoch 21/100 - Train Loss: 0.2901 - Val Acc: 0.9130
2026-04-05 05:27:16,726 - INFO - Epoch 22/100 - Train Loss: 0.2898 - Val Acc: 0.9130
2026-04-05 05:27:16,993 - INFO - Epoch 23/100 - Train Loss: 0.2896 - Val Acc: 0.9130
2026-04-05 05:27:17,256 - INFO - Epoch 24/100 - Train Loss: 0.2861 - Val Acc: 0.9130
2026-04-05 05:27:17,527 - INFO - Epoch 25/100 - Train Loss: 0.2833 - Val Acc: 0.9130
2026-04-05 05:27:17,799 - INFO - Epoch 26/100 - Train Loss: 0.2843 - Val Acc: 0.9130
2026-04-05 05:27:18,069 - INFO - Epoch 27/100 - Train Loss: 0.2798 - Val Acc: 0.9130
2026-04-05 05:27:18,351 - INFO - Epoch 28/100 - Train Loss: 0.2819 - Val Acc: 0.9130
2026-04-05 05:27:18,651 - INFO - Epoch 29/100 - Train Loss: 0.2833 - Val Acc: 0.9130
2026-04-05 05:27:18,925 - INFO - Epoch 30/100 - Train Loss: 0.2800 - Val Acc: 0.9130
2026-04-05 05:27:19,187 - INFO - Epoch 31/100 - Train Loss: 0.2809 - Val Acc: 0.9130
2026-04-05 05:27:19,465 - INFO - Epoch 32/100 - Train Loss: 0.2771 - Val Acc: 0.9130
2026-04-05 05:27:19,734 - INFO - Epoch 33/100 - Train Loss: 0.2763 - Val Acc: 0.9130
2026-04-05 05:27:20,004 - INFO - Epoch 34/100 - Train Loss: 0.2762 - Val Acc: 0.9130
2026-04-05 05:27:20,267 - INFO - Epoch 35/100 - Train Loss: 0.2734 - Val Acc: 0.9130
2026-04-05 05:27:20,538 - INFO - Epoch 36/100 - Train Loss: 0.2717 - Val Acc: 0.9130
2026-04-05 05:27:20,809 - INFO - Epoch 37/100 - Train Loss: 0.2722 - Val Acc: 0.9130
2026-04-05 05:27:21,093 - INFO - Epoch 38/100 - Train Loss: 0.2690 - Val Acc: 0.9130
2026-04-05 05:27:21,376 - INFO - Epoch 39/100 - Train Loss: 0.2711 - Val Acc: 0.9130
2026-04-05 05:27:21,673 - INFO - Epoch 40/100 - Train Loss: 0.2686 - Val Acc: 0.9130
2026-04-05 05:27:21,942 - INFO - Epoch 41/100 - Train Loss: 0.2674 - Val Acc: 0.9130
2026-04-05 05:27:22,223 - INFO - Epoch 42/100 - Train Loss: 0.2648 - Val Acc: 0.9130
2026-04-05 05:27:22,511 - INFO - Epoch 43/100 - Train Loss: 0.2666 - Val Acc: 0.9130
2026-04-05 05:27:22,786 - INFO - Epoch 44/100 - Train Loss: 0.2614 - Val Acc: 0.9130
2026-04-05 05:27:23,079 - INFO - Epoch 45/100 - Train Loss: 0.2646 - Val Acc: 0.9130
2026-04-05 05:27:23,362 - INFO - Epoch 46/100 - Train Loss: 0.2642 - Val Acc: 0.9130
2026-04-05 05:27:23,643 - INFO - Epoch 47/100 - Train Loss: 0.2577 - Val Acc: 0.9130
2026-04-05 05:27:23,927 - INFO - Epoch 48/100 - Train Loss: 0.2575 - Val Acc: 0.9130
2026-04-05 05:27:24,214 - INFO - Epoch 49/100 - Train Loss: 0.2599 - Val Acc: 0.9130
2026-04-05 05:27:24,517 - INFO - Epoch 50/100 - Train Loss: 0.2556 - Val Acc: 0.9130
2026-04-05 05:27:24,806 - INFO - Epoch 51/100 - Train Loss: 0.2568 - Val Acc: 0.9130
2026-04-05 05:27:25,093 - INFO - Epoch 52/100 - Train Loss: 0.2564 - Val Acc: 0.9130
2026-04-05 05:27:25,371 - INFO - Epoch 53/100 - Train Loss: 0.2535 - Val Acc: 0.9130
2026-04-05 05:27:25,639 - INFO - Epoch 54/100 - Train Loss: 0.2514 - Val Acc: 0.9130
2026-04-05 05:27:25,908 - INFO - Epoch 55/100 - Train Loss: 0.2504 - Val Acc: 0.9130
2026-04-05 05:27:26,182 - INFO - Epoch 56/100 - Train Loss: 0.2513 - Val Acc: 0.9130
2026-04-05 05:27:26,453 - INFO - Epoch 57/100 - Train Loss: 0.2495 - Val Acc: 0.9130
2026-04-05 05:27:26,719 - INFO - Epoch 58/100 - Train Loss: 0.2498 - Val Acc: 0.9130
2026-04-05 05:27:26,992 - INFO - Epoch 59/100 - Train Loss: 0.2475 - Val Acc: 0.9130
2026-04-05 05:27:27,257 - INFO - Epoch 60/100 - Train Loss: 0.2481 - Val Acc: 0.9130
2026-04-05 05:27:27,531 - INFO - Epoch 61/100 - Train Loss: 0.2441 - Val Acc: 0.9130
2026-04-05 05:27:27,807 - INFO - Epoch 62/100 - Train Loss: 0.2459 - Val Acc: 0.9130
2026-04-05 05:27:28,082 - INFO - Epoch 63/100 - Train Loss: 0.2444 - Val Acc: 0.9130
2026-04-05 05:27:28,368 - INFO - Epoch 64/100 - Train Loss: 0.2436 - Val Acc: 0.9130
2026-04-05 05:27:28,643 - INFO - Epoch 65/100 - Train Loss: 0.2433 - Val Acc: 0.9130
2026-04-05 05:27:28,928 - INFO - Epoch 66/100 - Train Loss: 0.2411 - Val Acc: 0.9130
2026-04-05 05:27:29,201 - INFO - Epoch 67/100 - Train Loss: 0.2423 - Val Acc: 0.9130
2026-04-05 05:27:29,471 - INFO - Epoch 68/100 - Train Loss: 0.2382 - Val Acc: 0.9130
2026-04-05 05:27:29,763 - INFO - Epoch 69/100 - Train Loss: 0.2405 - Val Acc: 0.9130
2026-04-05 05:27:30,053 - INFO - Epoch 70/100 - Train Loss: 0.2402 - Val Acc: 0.9130
2026-04-05 05:27:30,338 - INFO - Epoch 71/100 - Train Loss: 0.2365 - Val Acc: 0.9275
2026-04-05 05:27:30,627 - INFO - Epoch 72/100 - Train Loss: 0.2333 - Val Acc: 0.9275
2026-04-05 05:27:30,907 - INFO - Epoch 73/100 - Train Loss: 0.2327 - Val Acc: 0.9275
2026-04-05 05:27:31,177 - INFO - Epoch 74/100 - Train Loss: 0.2369 - Val Acc: 0.9275
2026-04-05 05:27:31,446 - INFO - Epoch 75/100 - Train Loss: 0.2354 - Val Acc: 0.9275
2026-04-05 05:27:31,720 - INFO - Epoch 76/100 - Train Loss: 0.2325 - Val Acc: 0.9275
2026-04-05 05:27:31,984 - INFO - Epoch 77/100 - Train Loss: 0.2317 - Val Acc: 0.9275
2026-04-05 05:27:32,250 - INFO - Epoch 78/100 - Train Loss: 0.2296 - Val Acc: 0.9275
2026-04-05 05:27:32,530 - INFO - Epoch 79/100 - Train Loss: 0.2276 - Val Acc: 0.9275
2026-04-05 05:27:32,795 - INFO - Epoch 80/100 - Train Loss: 0.2311 - Val Acc: 0.9275
2026-04-05 05:27:33,069 - INFO - Epoch 81/100 - Train Loss: 0.2296 - Val Acc: 0.9275
2026-04-05 05:27:33,343 - INFO - Epoch 82/100 - Train Loss: 0.2323 - Val Acc: 0.9275
2026-04-05 05:27:33,621 - INFO - Epoch 83/100 - Train Loss: 0.2309 - Val Acc: 0.9275
2026-04-05 05:27:33,883 - INFO - Epoch 84/100 - Train Loss: 0.2264 - Val Acc: 0.9275
2026-04-05 05:27:34,151 - INFO - Epoch 85/100 - Train Loss: 0.2281 - Val Acc: 0.9275
2026-04-05 05:27:34,416 - INFO - Epoch 86/100 - Train Loss: 0.2243 - Val Acc: 0.9275
2026-04-05 05:27:34,727 - INFO - Epoch 87/100 - Train Loss: 0.2272 - Val Acc: 0.9275
2026-04-05 05:27:35,006 - INFO - Epoch 88/100 - Train Loss: 0.2243 - Val Acc: 0.9275
2026-04-05 05:27:35,280 - INFO - Epoch 89/100 - Train Loss: 0.2225 - Val Acc: 0.9275
2026-04-05 05:27:35,554 - INFO - Epoch 90/100 - Train Loss: 0.2217 - Val Acc: 0.9275
2026-04-05 05:27:35,828 - INFO - Epoch 91/100 - Train Loss: 0.2158 - Val Acc: 0.9275
2026-04-05 05:27:36,098 - INFO - Epoch 92/100 - Train Loss: 0.2209 - Val Acc: 0.9275
2026-04-05 05:27:36,370 - INFO - Epoch 93/100 - Train Loss: 0.2245 - Val Acc: 0.9275
2026-04-05 05:27:36,638 - INFO - Epoch 94/100 - Train Loss: 0.2189 - Val Acc: 0.9275
2026-04-05 05:27:36,922 - INFO - Epoch 95/100 - Train Loss: 0.2202 - Val Acc: 0.9275
2026-04-05 05:27:37,190 - INFO - Epoch 96/100 - Train Loss: 0.2210 - Val Acc: 0.9275
2026-04-05 05:27:37,467 - INFO - Epoch 97/100 - Train Loss: 0.2182 - Val Acc: 0.9275
2026-04-05 05:27:37,740 - INFO - Epoch 98/100 - Train Loss: 0.2162 - Val Acc: 0.9275
2026-04-05 05:27:38,008 - INFO - Epoch 99/100 - Train Loss: 0.2201 - Val Acc: 0.9275
2026-04-05 05:27:38,284 - INFO - Epoch 100/100 - Train Loss: 0.2136 - Val Acc: 0.9275
2026-04-05 05:27:38,651 - INFO - Fold 3 logically complete. Tensor memory bounds cleared cleanly.
2026-04-05 05:27:38,656 - INFO - Original class distribution: [276 345]
2026-04-05 05:27:38,657 - INFO - Training device bound securely to: cuda

Fold 4:   0%|          | 0/100 [00:00<?, ?it/s]

2026-04-05 05:27:38,946 - INFO - Epoch 1/100 - Train Loss: 0.5594 - Val Acc: 0.7536
2026-04-05 05:27:39,212 - INFO - Epoch 2/100 - Train Loss: 0.3995 - Val Acc: 0.7536
2026-04-05 05:27:39,492 - INFO - Epoch 3/100 - Train Loss: 0.3498 - Val Acc: 0.7826
2026-04-05 05:27:39,771 - INFO - Epoch 4/100 - Train Loss: 0.3276 - Val Acc: 0.8116
2026-04-05 05:27:40,053 - INFO - Epoch 5/100 - Train Loss: 0.3147 - Val Acc: 0.7971
2026-04-05 05:27:40,319 - INFO - Epoch 6/100 - Train Loss: 0.3040 - Val Acc: 0.7971
2026-04-05 05:27:40,589 - INFO - Epoch 7/100 - Train Loss: 0.2977 - Val Acc: 0.7971
2026-04-05 05:27:40,892 - INFO - Epoch 8/100 - Train Loss: 0.2911 - Val Acc: 0.7971
2026-04-05 05:27:41,163 - INFO - Epoch 9/100 - Train Loss: 0.2855 - Val Acc: 0.7971
2026-04-05 05:27:41,433 - INFO - Epoch 10/100 - Train Loss: 0.2845 - Val Acc: 0.7971
2026-04-05 05:27:41,702 - INFO - Epoch 11/100 - Train Loss: 0.2807 - Val Acc: 0.7971
2026-04-05 05:27:41,969 - INFO - Epoch 12/100 - Train Loss: 0.2791 - Val Acc: 0.7971
2026-04-05 05:27:42,239 - INFO - Epoch 13/100 - Train Loss: 0.2778 - Val Acc: 0.7971
2026-04-05 05:27:42,519 - INFO - Epoch 14/100 - Train Loss: 0.2768 - Val Acc: 0.7971
2026-04-05 05:27:42,793 - INFO - Epoch 15/100 - Train Loss: 0.2730 - Val Acc: 0.7971
2026-04-05 05:27:43,070 - INFO - Epoch 16/100 - Train Loss: 0.2735 - Val Acc: 0.7971
2026-04-05 05:27:43,341 - INFO - Epoch 17/100 - Train Loss: 0.2735 - Val Acc: 0.7971
2026-04-05 05:27:43,605 - INFO - Epoch 18/100 - Train Loss: 0.2700 - Val Acc: 0.7971
2026-04-05 05:27:43,892 - INFO - Epoch 19/100 - Train Loss: 0.2687 - Val Acc: 0.7971
2026-04-05 05:27:44,165 - INFO - Epoch 20/100 - Train Loss: 0.2673 - Val Acc: 0.7971
2026-04-05 05:27:44,439 - INFO - Epoch 21/100 - Train Loss: 0.2678 - Val Acc: 0.7971
2026-04-05 05:27:44,745 - INFO - Epoch 22/100 - Train Loss: 0.2667 - Val Acc: 0.7971
2026-04-05 05:27:45,025 - INFO - Epoch 23/100 - Train Loss: 0.2653 - Val Acc: 0.7971
2026-04-05 05:27:45,299 - INFO - Epoch 24/100 - Train Loss: 0.2635 - Val Acc: 0.7971
2026-04-05 05:27:45,574 - INFO - Epoch 25/100 - Train Loss: 0.2616 - Val Acc: 0.7971
2026-04-05 05:27:45,843 - INFO - Epoch 26/100 - Train Loss: 0.2607 - Val Acc: 0.7971
2026-04-05 05:27:46,121 - INFO - Epoch 27/100 - Train Loss: 0.2588 - Val Acc: 0.7971
2026-04-05 05:27:46,395 - INFO - Epoch 28/100 - Train Loss: 0.2584 - Val Acc: 0.7971
2026-04-05 05:27:46,670 - INFO - Epoch 29/100 - Train Loss: 0.2568 - Val Acc: 0.7971
2026-04-05 05:27:46,943 - INFO - Epoch 30/100 - Train Loss: 0.2571 - Val Acc: 0.7971
2026-04-05 05:27:47,220 - INFO - Epoch 31/100 - Train Loss: 0.2542 - Val Acc: 0.7971
2026-04-05 05:27:47,483 - INFO - Epoch 32/100 - Train Loss: 0.2553 - Val Acc: 0.7971
2026-04-05 05:27:47,760 - INFO - Epoch 33/100 - Train Loss: 0.2515 - Val Acc: 0.7971
2026-04-05 05:27:48,023 - INFO - Epoch 34/100 - Train Loss: 0.2537 - Val Acc: 0.7971
2026-04-05 05:27:48,290 - INFO - Epoch 35/100 - Train Loss: 0.2486 - Val Acc: 0.7971
2026-04-05 05:27:48,562 - INFO - Epoch 36/100 - Train Loss: 0.2495 - Val Acc: 0.7971
2026-04-05 05:27:48,833 - INFO - Epoch 37/100 - Train Loss: 0.2481 - Val Acc: 0.8116
2026-04-05 05:27:49,114 - INFO - Epoch 38/100 - Train Loss: 0.2440 - Val Acc: 0.8116
2026-04-05 05:27:49,403 - INFO - Epoch 39/100 - Train Loss: 0.2441 - Val Acc: 0.8261
2026-04-05 05:27:49,676 - INFO - Epoch 40/100 - Train Loss: 0.2444 - Val Acc: 0.8116
2026-04-05 05:27:49,971 - INFO - Epoch 41/100 - Train Loss: 0.2424 - Val Acc: 0.8116
2026-04-05 05:27:50,246 - INFO - Epoch 42/100 - Train Loss: 0.2425 - Val Acc: 0.8261
2026-04-05 05:27:50,524 - INFO - Epoch 43/100 - Train Loss: 0.2410 - Val Acc: 0.8261
2026-04-05 05:27:50,786 - INFO - Epoch 44/100 - Train Loss: 0.2409 - Val Acc: 0.8261
2026-04-05 05:27:51,061 - INFO - Epoch 45/100 - Train Loss: 0.2380 - Val Acc: 0.8261
2026-04-05 05:27:51,354 - INFO - Epoch 46/100 - Train Loss: 0.2401 - Val Acc: 0.8261
2026-04-05 05:27:51,628 - INFO - Epoch 47/100 - Train Loss: 0.2374 - Val Acc: 0.8261
2026-04-05 05:27:51,904 - INFO - Epoch 48/100 - Train Loss: 0.2376 - Val Acc: 0.8261
2026-04-05 05:27:52,192 - INFO - Epoch 49/100 - Train Loss: 0.2346 - Val Acc: 0.8261
2026-04-05 05:27:52,458 - INFO - Epoch 50/100 - Train Loss: 0.2333 - Val Acc: 0.8261
2026-04-05 05:27:52,734 - INFO - Epoch 51/100 - Train Loss: 0.2329 - Val Acc: 0.8261
2026-04-05 05:27:53,011 - INFO - Epoch 52/100 - Train Loss: 0.2352 - Val Acc: 0.8261
2026-04-05 05:27:53,306 - INFO - Epoch 53/100 - Train Loss: 0.2334 - Val Acc: 0.8261
2026-04-05 05:27:53,588 - INFO - Epoch 54/100 - Train Loss: 0.2316 - Val Acc: 0.8261
2026-04-05 05:27:53,876 - INFO - Epoch 55/100 - Train Loss: 0.2306 - Val Acc: 0.8261
2026-04-05 05:27:54,148 - INFO - Epoch 56/100 - Train Loss: 0.2289 - Val Acc: 0.8551
2026-04-05 05:27:54,441 - INFO - Epoch 57/100 - Train Loss: 0.2294 - Val Acc: 0.8551
2026-04-05 05:27:54,756 - INFO - Epoch 58/100 - Train Loss: 0.2271 - Val Acc: 0.8551
2026-04-05 05:27:55,035 - INFO - Epoch 59/100 - Train Loss: 0.2294 - Val Acc: 0.8551
2026-04-05 05:27:55,316 - INFO - Epoch 60/100 - Train Loss: 0.2237 - Val Acc: 0.8551
2026-04-05 05:27:55,592 - INFO - Epoch 61/100 - Train Loss: 0.2230 - Val Acc: 0.8406
2026-04-05 05:27:55,863 - INFO - Epoch 62/100 - Train Loss: 0.2266 - Val Acc: 0.8551
2026-04-05 05:27:56,132 - INFO - Epoch 63/100 - Train Loss: 0.2230 - Val Acc: 0.8261
2026-04-05 05:27:56,399 - INFO - Epoch 64/100 - Train Loss: 0.2210 - Val Acc: 0.8406
2026-04-05 05:27:56,670 - INFO - Epoch 65/100 - Train Loss: 0.2183 - Val Acc: 0.8406
2026-04-05 05:27:56,948 - INFO - Epoch 66/100 - Train Loss: 0.2187 - Val Acc: 0.8406
2026-04-05 05:27:57,233 - INFO - Epoch 67/100 - Train Loss: 0.2172 - Val Acc: 0.8551
2026-04-05 05:27:57,511 - INFO - Epoch 68/100 - Train Loss: 0.2168 - Val Acc: 0.8406
2026-04-05 05:27:57,792 - INFO - Epoch 69/100 - Train Loss: 0.2191 - Val Acc: 0.8551
2026-04-05 05:27:58,057 - INFO - Epoch 70/100 - Train Loss: 0.2154 - Val Acc: 0.8406
2026-04-05 05:27:58,332 - INFO - Epoch 71/100 - Train Loss: 0.2154 - Val Acc: 0.8406
2026-04-05 05:27:58,601 - INFO - Epoch 72/100 - Train Loss: 0.2128 - Val Acc: 0.8406
2026-04-05 05:27:58,880 - INFO - Epoch 73/100 - Train Loss: 0.2106 - Val Acc: 0.8406
2026-04-05 05:27:59,154 - INFO - Epoch 74/100 - Train Loss: 0.2138 - Val Acc: 0.8406
2026-04-05 05:27:59,426 - INFO - Epoch 75/100 - Train Loss: 0.2154 - Val Acc: 0.8406
2026-04-05 05:27:59,687 - INFO - Epoch 76/100 - Train Loss: 0.2056 - Val Acc: 0.8406
2026-04-05 05:27:59,974 - INFO - Epoch 77/100 - Train Loss: 0.2077 - Val Acc: 0.8406
2026-04-05 05:28:00,253 - INFO - Epoch 78/100 - Train Loss: 0.2098 - Val Acc: 0.8406
2026-04-05 05:28:00,541 - INFO - Epoch 79/100 - Train Loss: 0.2083 - Val Acc: 0.8406
2026-04-05 05:28:00,820 - INFO - Epoch 80/100 - Train Loss: 0.2086 - Val Acc: 0.8261
2026-04-05 05:28:01,092 - INFO - Epoch 81/100 - Train Loss: 0.2066 - Val Acc: 0.8261
2026-04-05 05:28:01,370 - INFO - Epoch 82/100 - Train Loss: 0.2057 - Val Acc: 0.8261
2026-04-05 05:28:01,651 - INFO - Epoch 83/100 - Train Loss: 0.2078 - Val Acc: 0.8261
2026-04-05 05:28:01,929 - INFO - Epoch 84/100 - Train Loss: 0.2065 - Val Acc: 0.8261
2026-04-05 05:28:02,202 - INFO - Epoch 85/100 - Train Loss: 0.2070 - Val Acc: 0.8116
2026-04-05 05:28:02,482 - INFO - Epoch 86/100 - Train Loss: 0.1993 - Val Acc: 0.8116
2026-04-05 05:28:02,765 - INFO - Epoch 87/100 - Train Loss: 0.2066 - Val Acc: 0.8261
2026-04-05 05:28:03,055 - INFO - Epoch 88/100 - Train Loss: 0.2034 - Val Acc: 0.8116
2026-04-05 05:28:03,341 - INFO - Epoch 89/100 - Train Loss: 0.2029 - Val Acc: 0.8116
2026-04-05 05:28:03,629 - INFO - Epoch 90/100 - Train Loss: 0.1998 - Val Acc: 0.8116
2026-04-05 05:28:03,914 - INFO - Epoch 91/100 - Train Loss: 0.1984 - Val Acc: 0.8116
2026-04-05 05:28:04,191 - INFO - Epoch 92/100 - Train Loss: 0.2021 - Val Acc: 0.8116
2026-04-05 05:28:04,479 - INFO - Epoch 93/100 - Train Loss: 0.2003 - Val Acc: 0.8116
2026-04-05 05:28:04,774 - INFO - Epoch 94/100 - Train Loss: 0.1945 - Val Acc: 0.8116
2026-04-05 05:28:05,053 - INFO - Epoch 95/100 - Train Loss: 0.1983 - Val Acc: 0.8261
2026-04-05 05:28:05,315 - INFO - Epoch 96/100 - Train Loss: 0.1982 - Val Acc: 0.8261
2026-04-05 05:28:05,581 - INFO - Epoch 97/100 - Train Loss: 0.1990 - Val Acc: 0.8261
2026-04-05 05:28:05,855 - INFO - Epoch 98/100 - Train Loss: 0.1946 - Val Acc: 0.8116
2026-04-05 05:28:06,130 - INFO - Epoch 99/100 - Train Loss: 0.1957 - Val Acc: 0.8116
2026-04-05 05:28:06,403 - INFO - Epoch 100/100 - Train Loss: 0.1951 - Val Acc: 0.8116
2026-04-05 05:28:06,765 - INFO - Fold 4 logically complete. Tensor memory bounds cleared cleanly.
2026-04-05 05:28:06,769 - INFO - Original class distribution: [276 345]
2026-04-05 05:28:06,769 - INFO - Training device bound securely to: cuda

Fold 5:   0%|          | 0/100 [00:00<?, ?it/s]

2026-04-05 05:28:07,066 - INFO - Epoch 1/100 - Train Loss: 0.5561 - Val Acc: 0.8261
2026-04-05 05:28:07,341 - INFO - Epoch 2/100 - Train Loss: 0.3998 - Val Acc: 0.8551
2026-04-05 05:28:07,618 - INFO - Epoch 3/100 - Train Loss: 0.3554 - Val Acc: 0.8696
2026-04-05 05:28:07,888 - INFO - Epoch 4/100 - Train Loss: 0.3373 - Val Acc: 0.8696
2026-04-05 05:28:08,166 - INFO - Epoch 5/100 - Train Loss: 0.3238 - Val Acc: 0.8696
2026-04-05 05:28:08,447 - INFO - Epoch 6/100 - Train Loss: 0.3158 - Val Acc: 0.8841
2026-04-05 05:28:08,725 - INFO - Epoch 7/100 - Train Loss: 0.3079 - Val Acc: 0.8841
2026-04-05 05:28:09,019 - INFO - Epoch 8/100 - Train Loss: 0.3057 - Val Acc: 0.8841
2026-04-05 05:28:09,292 - INFO - Epoch 9/100 - Train Loss: 0.3006 - Val Acc: 0.8841
2026-04-05 05:28:09,562 - INFO - Epoch 10/100 - Train Loss: 0.2941 - Val Acc: 0.8696
2026-04-05 05:28:09,843 - INFO - Epoch 11/100 - Train Loss: 0.2908 - Val Acc: 0.8696
2026-04-05 05:28:10,114 - INFO - Epoch 12/100 - Train Loss: 0.2881 - Val Acc: 0.8551
2026-04-05 05:28:10,397 - INFO - Epoch 13/100 - Train Loss: 0.2867 - Val Acc: 0.8551
2026-04-05 05:28:10,672 - INFO - Epoch 14/100 - Train Loss: 0.2838 - Val Acc: 0.8551
2026-04-05 05:28:10,949 - INFO - Epoch 15/100 - Train Loss: 0.2862 - Val Acc: 0.8551
2026-04-05 05:28:11,220 - INFO - Epoch 16/100 - Train Loss: 0.2788 - Val Acc: 0.8406
2026-04-05 05:28:11,494 - INFO - Epoch 17/100 - Train Loss: 0.2799 - Val Acc: 0.8406
2026-04-05 05:28:11,758 - INFO - Epoch 18/100 - Train Loss: 0.2789 - Val Acc: 0.8406
2026-04-05 05:28:12,039 - INFO - Epoch 19/100 - Train Loss: 0.2747 - Val Acc: 0.8406
2026-04-05 05:28:12,332 - INFO - Epoch 20/100 - Train Loss: 0.2742 - Val Acc: 0.8406
2026-04-05 05:28:12,623 - INFO - Epoch 21/100 - Train Loss: 0.2716 - Val Acc: 0.8406
2026-04-05 05:28:12,900 - INFO - Epoch 22/100 - Train Loss: 0.2710 - Val Acc: 0.8406
2026-04-05 05:28:13,183 - INFO - Epoch 23/100 - Train Loss: 0.2712 - Val Acc: 0.8551
2026-04-05 05:28:13,443 - INFO - Epoch 24/100 - Train Loss: 0.2669 - Val Acc: 0.8551
2026-04-05 05:28:13,724 - INFO - Epoch 25/100 - Train Loss: 0.2671 - Val Acc: 0.8551
2026-04-05 05:28:14,013 - INFO - Epoch 26/100 - Train Loss: 0.2647 - Val Acc: 0.8551
2026-04-05 05:28:14,286 - INFO - Epoch 27/100 - Train Loss: 0.2636 - Val Acc: 0.8406
2026-04-05 05:28:14,580 - INFO - Epoch 28/100 - Train Loss: 0.2629 - Val Acc: 0.8551
2026-04-05 05:28:14,868 - INFO - Epoch 29/100 - Train Loss: 0.2610 - Val Acc: 0.8406
2026-04-05 05:28:15,160 - INFO - Epoch 30/100 - Train Loss: 0.2575 - Val Acc: 0.8406
2026-04-05 05:28:15,437 - INFO - Epoch 31/100 - Train Loss: 0.2595 - Val Acc: 0.8406
2026-04-05 05:28:15,721 - INFO - Epoch 32/100 - Train Loss: 0.2578 - Val Acc: 0.8406
2026-04-05 05:28:16,000 - INFO - Epoch 33/100 - Train Loss: 0.2557 - Val Acc: 0.8406
2026-04-05 05:28:16,302 - INFO - Epoch 34/100 - Train Loss: 0.2544 - Val Acc: 0.8551
2026-04-05 05:28:16,573 - INFO - Epoch 35/100 - Train Loss: 0.2553 - Val Acc: 0.8551
2026-04-05 05:28:16,856 - INFO - Epoch 36/100 - Train Loss: 0.2517 - Val Acc: 0.8551
2026-04-05 05:28:17,146 - INFO - Epoch 37/100 - Train Loss: 0.2519 - Val Acc: 0.8551
2026-04-05 05:28:17,436 - INFO - Epoch 38/100 - Train Loss: 0.2512 - Val Acc: 0.8551
2026-04-05 05:28:17,727 - INFO - Epoch 39/100 - Train Loss: 0.2472 - Val Acc: 0.8551
2026-04-05 05:28:18,002 - INFO - Epoch 40/100 - Train Loss: 0.2485 - Val Acc: 0.8406
2026-04-05 05:28:18,296 - INFO - Epoch 41/100 - Train Loss: 0.2463 - Val Acc: 0.8551
2026-04-05 05:28:18,576 - INFO - Epoch 42/100 - Train Loss: 0.2441 - Val Acc: 0.8551
2026-04-05 05:28:18,843 - INFO - Epoch 43/100 - Train Loss: 0.2440 - Val Acc: 0.8551
2026-04-05 05:28:19,113 - INFO - Epoch 44/100 - Train Loss: 0.2421 - Val Acc: 0.8551
2026-04-05 05:28:19,387 - INFO - Epoch 45/100 - Train Loss: 0.2407 - Val Acc: 0.8551
2026-04-05 05:28:19,654 - INFO - Epoch 46/100 - Train Loss: 0.2455 - Val Acc: 0.8551
2026-04-05 05:28:19,931 - INFO - Epoch 47/100 - Train Loss: 0.2406 - Val Acc: 0.8551
2026-04-05 05:28:20,189 - INFO - Epoch 48/100 - Train Loss: 0.2393 - Val Acc: 0.8551
2026-04-05 05:28:20,460 - INFO - Epoch 49/100 - Train Loss: 0.2402 - Val Acc: 0.8551
2026-04-05 05:28:20,725 - INFO - Epoch 50/100 - Train Loss: 0.2371 - Val Acc: 0.8551
2026-04-05 05:28:21,013 - INFO - Epoch 51/100 - Train Loss: 0.2313 - Val Acc: 0.8551
2026-04-05 05:28:21,279 - INFO - Epoch 52/100 - Train Loss: 0.2356 - Val Acc: 0.8551
2026-04-05 05:28:21,549 - INFO - Epoch 53/100 - Train Loss: 0.2371 - Val Acc: 0.8551
2026-04-05 05:28:21,833 - INFO - Epoch 54/100 - Train Loss: 0.2330 - Val Acc: 0.8551
2026-04-05 05:28:22,120 - INFO - Epoch 55/100 - Train Loss: 0.2306 - Val Acc: 0.8551
2026-04-05 05:28:22,393 - INFO - Epoch 56/100 - Train Loss: 0.2299 - Val Acc: 0.8406
2026-04-05 05:28:22,672 - INFO - Epoch 57/100 - Train Loss: 0.2314 - Val Acc: 0.8551
2026-04-05 05:28:22,954 - INFO - Epoch 58/100 - Train Loss: 0.2286 - Val Acc: 0.8406
2026-04-05 05:28:23,230 - INFO - Epoch 59/100 - Train Loss: 0.2250 - Val Acc: 0.8406
2026-04-05 05:28:23,520 - INFO - Epoch 60/100 - Train Loss: 0.2289 - Val Acc: 0.8551
2026-04-05 05:28:23,808 - INFO - Epoch 61/100 - Train Loss: 0.2265 - Val Acc: 0.8551
2026-04-05 05:28:24,086 - INFO - Epoch 62/100 - Train Loss: 0.2253 - Val Acc: 0.8551
2026-04-05 05:28:24,401 - INFO - Epoch 63/100 - Train Loss: 0.2214 - Val Acc: 0.8406
2026-04-05 05:28:24,709 - INFO - Epoch 64/100 - Train Loss: 0.2208 - Val Acc: 0.8406
2026-04-05 05:28:24,989 - INFO - Epoch 65/100 - Train Loss: 0.2224 - Val Acc: 0.8551
2026-04-05 05:28:25,283 - INFO - Epoch 66/100 - Train Loss: 0.2226 - Val Acc: 0.8551
2026-04-05 05:28:25,555 - INFO - Epoch 67/100 - Train Loss: 0.2197 - Val Acc: 0.8551
2026-04-05 05:28:25,835 - INFO - Epoch 68/100 - Train Loss: 0.2189 - Val Acc: 0.8551
2026-04-05 05:28:26,111 - INFO - Epoch 69/100 - Train Loss: 0.2238 - Val Acc: 0.8551
2026-04-05 05:28:26,382 - INFO - Epoch 70/100 - Train Loss: 0.2212 - Val Acc: 0.8551
2026-04-05 05:28:26,649 - INFO - Epoch 71/100 - Train Loss: 0.2214 - Val Acc: 0.8696
2026-04-05 05:28:26,917 - INFO - Epoch 72/100 - Train Loss: 0.2187 - Val Acc: 0.8551
2026-04-05 05:28:27,185 - INFO - Epoch 73/100 - Train Loss: 0.2160 - Val Acc: 0.8406
2026-04-05 05:28:27,459 - INFO - Epoch 74/100 - Train Loss: 0.2147 - Val Acc: 0.8406
2026-04-05 05:28:27,736 - INFO - Epoch 75/100 - Train Loss: 0.2129 - Val Acc: 0.8551
2026-04-05 05:28:28,004 - INFO - Epoch 76/100 - Train Loss: 0.2139 - Val Acc: 0.8551
2026-04-05 05:28:28,276 - INFO - Epoch 77/100 - Train Loss: 0.2138 - Val Acc: 0.8696
2026-04-05 05:28:28,548 - INFO - Epoch 78/100 - Train Loss: 0.2122 - Val Acc: 0.8696
2026-04-05 05:28:28,830 - INFO - Epoch 79/100 - Train Loss: 0.2070 - Val Acc: 0.8696
2026-04-05 05:28:29,102 - INFO - Epoch 80/100 - Train Loss: 0.2131 - Val Acc: 0.8551
2026-04-05 05:28:29,374 - INFO - Epoch 81/100 - Train Loss: 0.2122 - Val Acc: 0.8696
2026-04-05 05:28:29,648 - INFO - Epoch 82/100 - Train Loss: 0.2098 - Val Acc: 0.8551
2026-04-05 05:28:29,934 - INFO - Epoch 83/100 - Train Loss: 0.2129 - Val Acc: 0.8696
2026-04-05 05:28:30,213 - INFO - Epoch 84/100 - Train Loss: 0.2113 - Val Acc: 0.8696
2026-04-05 05:28:30,495 - INFO - Epoch 85/100 - Train Loss: 0.2096 - Val Acc: 0.8551
2026-04-05 05:28:30,783 - INFO - Epoch 86/100 - Train Loss: 0.2130 - Val Acc: 0.8551
2026-04-05 05:28:31,063 - INFO - Epoch 87/100 - Train Loss: 0.2088 - Val Acc: 0.8551
2026-04-05 05:28:31,345 - INFO - Epoch 88/100 - Train Loss: 0.2075 - Val Acc: 0.8551
2026-04-05 05:28:31,624 - INFO - Epoch 89/100 - Train Loss: 0.2053 - Val Acc: 0.8551
2026-04-05 05:28:31,900 - INFO - Epoch 90/100 - Train Loss: 0.2109 - Val Acc: 0.8696
2026-04-05 05:28:32,171 - INFO - Epoch 91/100 - Train Loss: 0.2081 - Val Acc: 0.8696
2026-04-05 05:28:32,443 - INFO - Epoch 92/100 - Train Loss: 0.2048 - Val Acc: 0.8696
2026-04-05 05:28:32,719 - INFO - Epoch 93/100 - Train Loss: 0.2048 - Val Acc: 0.8696
2026-04-05 05:28:32,995 - INFO - Epoch 94/100 - Train Loss: 0.2049 - Val Acc: 0.8696
2026-04-05 05:28:33,272 - INFO - Epoch 95/100 - Train Loss: 0.2045 - Val Acc: 0.8551
2026-04-05 05:28:33,544 - INFO - Epoch 96/100 - Train Loss: 0.2041 - Val Acc: 0.8551
2026-04-05 05:28:33,817 - INFO - Epoch 97/100 - Train Loss: 0.2021 - Val Acc: 0.8696
2026-04-05 05:28:34,093 - INFO - Epoch 98/100 - Train Loss: 0.2017 - Val Acc: 0.8696
2026-04-05 05:28:34,365 - INFO - Epoch 99/100 - Train Loss: 0.1989 - Val Acc: 0.8551
2026-04-05 05:28:34,682 - INFO - Epoch 100/100 - Train Loss: 0.1990 - Val Acc: 0.8551
2026-04-05 05:28:35,047 - INFO - Fold 5 logically complete. Tensor memory bounds cleared cleanly.
2026-04-05 05:28:35,052 - INFO - Original class distribution: [276 345]
2026-04-05 05:28:35,052 - INFO - Training device bound securely to: cuda

Fold 6:   0%|          | 0/100 [00:00<?, ?it/s]

2026-04-05 05:28:35,345 - INFO - Epoch 1/100 - Train Loss: 0.5614 - Val Acc: 0.8406
2026-04-05 05:28:35,612 - INFO - Epoch 2/100 - Train Loss: 0.4089 - Val Acc: 0.8551
2026-04-05 05:28:35,889 - INFO - Epoch 3/100 - Train Loss: 0.3663 - Val Acc: 0.8551
2026-04-05 05:28:36,158 - INFO - Epoch 4/100 - Train Loss: 0.3478 - Val Acc: 0.8696
2026-04-05 05:28:36,437 - INFO - Epoch 5/100 - Train Loss: 0.3341 - Val Acc: 0.8696
2026-04-05 05:28:36,701 - INFO - Epoch 6/100 - Train Loss: 0.3231 - Val Acc: 0.8696
2026-04-05 05:28:36,987 - INFO - Epoch 7/100 - Train Loss: 0.3166 - Val Acc: 0.8551
2026-04-05 05:28:37,272 - INFO - Epoch 8/100 - Train Loss: 0.3099 - Val Acc: 0.8551
2026-04-05 05:28:37,547 - INFO - Epoch 9/100 - Train Loss: 0.3079 - Val Acc: 0.8696
2026-04-05 05:28:37,814 - INFO - Epoch 10/100 - Train Loss: 0.3057 - Val Acc: 0.8696
2026-04-05 05:28:38,092 - INFO - Epoch 11/100 - Train Loss: 0.3040 - Val Acc: 0.8841
2026-04-05 05:28:38,364 - INFO - Epoch 12/100 - Train Loss: 0.3017 - Val Acc: 0.8841
2026-04-05 05:28:38,642 - INFO - Epoch 13/100 - Train Loss: 0.2989 - Val Acc: 0.8841
2026-04-05 05:28:38,928 - INFO - Epoch 14/100 - Train Loss: 0.2965 - Val Acc: 0.8841
2026-04-05 05:28:39,225 - INFO - Epoch 15/100 - Train Loss: 0.2929 - Val Acc: 0.8841
2026-04-05 05:28:39,497 - INFO - Epoch 16/100 - Train Loss: 0.2939 - Val Acc: 0.8841
2026-04-05 05:28:39,790 - INFO - Epoch 17/100 - Train Loss: 0.2918 - Val Acc: 0.8841
2026-04-05 05:28:40,072 - INFO - Epoch 18/100 - Train Loss: 0.2906 - Val Acc: 0.8841
2026-04-05 05:28:40,334 - INFO - Epoch 19/100 - Train Loss: 0.2883 - Val Acc: 0.8841
2026-04-05 05:28:40,603 - INFO - Epoch 20/100 - Train Loss: 0.2891 - Val Acc: 0.8841
2026-04-05 05:28:40,879 - INFO - Epoch 21/100 - Train Loss: 0.2890 - Val Acc: 0.8841
2026-04-05 05:28:41,167 - INFO - Epoch 22/100 - Train Loss: 0.2869 - Val Acc: 0.8696
2026-04-05 05:28:41,440 - INFO - Epoch 23/100 - Train Loss: 0.2849 - Val Acc: 0.8841
2026-04-05 05:28:41,709 - INFO - Epoch 24/100 - Train Loss: 0.2830 - Val Acc: 0.8841
2026-04-05 05:28:41,984 - INFO - Epoch 25/100 - Train Loss: 0.2821 - Val Acc: 0.8696
2026-04-05 05:28:42,271 - INFO - Epoch 26/100 - Train Loss: 0.2798 - Val Acc: 0.8696
2026-04-05 05:28:42,548 - INFO - Epoch 27/100 - Train Loss: 0.2808 - Val Acc: 0.8696
2026-04-05 05:28:42,827 - INFO - Epoch 28/100 - Train Loss: 0.2819 - Val Acc: 0.8696
2026-04-05 05:28:43,108 - INFO - Epoch 29/100 - Train Loss: 0.2758 - Val Acc: 0.8696
2026-04-05 05:28:43,378 - INFO - Epoch 30/100 - Train Loss: 0.2776 - Val Acc: 0.8551
2026-04-05 05:28:43,651 - INFO - Epoch 31/100 - Train Loss: 0.2732 - Val Acc: 0.8551
2026-04-05 05:28:43,929 - INFO - Epoch 32/100 - Train Loss: 0.2748 - Val Acc: 0.8696
2026-04-05 05:28:44,201 - INFO - Epoch 33/100 - Train Loss: 0.2714 - Val Acc: 0.8696
2026-04-05 05:28:44,476 - INFO - Epoch 34/100 - Train Loss: 0.2707 - Val Acc: 0.8696
2026-04-05 05:28:44,782 - INFO - Epoch 35/100 - Train Loss: 0.2684 - Val Acc: 0.8696
2026-04-05 05:28:45,063 - INFO - Epoch 36/100 - Train Loss: 0.2670 - Val Acc: 0.8551
2026-04-05 05:28:45,338 - INFO - Epoch 37/100 - Train Loss: 0.2665 - Val Acc: 0.8696
2026-04-05 05:28:45,610 - INFO - Epoch 38/100 - Train Loss: 0.2669 - Val Acc: 0.8696
2026-04-05 05:28:45,883 - INFO - Epoch 39/100 - Train Loss: 0.2673 - Val Acc: 0.8696
2026-04-05 05:28:46,167 - INFO - Epoch 40/100 - Train Loss: 0.2652 - Val Acc: 0.8551
2026-04-05 05:28:46,434 - INFO - Epoch 41/100 - Train Loss: 0.2637 - Val Acc: 0.8696
2026-04-05 05:28:46,716 - INFO - Epoch 42/100 - Train Loss: 0.2648 - Val Acc: 0.8696
2026-04-05 05:28:47,003 - INFO - Epoch 43/100 - Train Loss: 0.2616 - Val Acc: 0.8696
2026-04-05 05:28:47,277 - INFO - Epoch 44/100 - Train Loss: 0.2610 - Val Acc: 0.8696
2026-04-05 05:28:47,553 - INFO - Epoch 45/100 - Train Loss: 0.2602 - Val Acc: 0.8696
2026-04-05 05:28:47,820 - INFO - Epoch 46/100 - Train Loss: 0.2579 - Val Acc: 0.8696
2026-04-05 05:28:48,099 - INFO - Epoch 47/100 - Train Loss: 0.2599 - Val Acc: 0.8696
2026-04-05 05:28:48,389 - INFO - Epoch 48/100 - Train Loss: 0.2575 - Val Acc: 0.8841
2026-04-05 05:28:48,663 - INFO - Epoch 49/100 - Train Loss: 0.2570 - Val Acc: 0.8841
2026-04-05 05:28:48,949 - INFO - Epoch 50/100 - Train Loss: 0.2578 - Val Acc: 0.8696
2026-04-05 05:28:49,226 - INFO - Epoch 51/100 - Train Loss: 0.2565 - Val Acc: 0.8841
2026-04-05 05:28:49,499 - INFO - Epoch 52/100 - Train Loss: 0.2487 - Val Acc: 0.8841
2026-04-05 05:28:49,769 - INFO - Epoch 53/100 - Train Loss: 0.2494 - Val Acc: 0.8696
2026-04-05 05:28:50,048 - INFO - Epoch 54/100 - Train Loss: 0.2513 - Val Acc: 0.8696
2026-04-05 05:28:50,314 - INFO - Epoch 55/100 - Train Loss: 0.2492 - Val Acc: 0.8841
2026-04-05 05:28:50,589 - INFO - Epoch 56/100 - Train Loss: 0.2483 - Val Acc: 0.8841
2026-04-05 05:28:50,854 - INFO - Epoch 57/100 - Train Loss: 0.2452 - Val Acc: 0.8841
2026-04-05 05:28:51,130 - INFO - Epoch 58/100 - Train Loss: 0.2462 - Val Acc: 0.8841
2026-04-05 05:28:51,407 - INFO - Epoch 59/100 - Train Loss: 0.2442 - Val Acc: 0.8841
2026-04-05 05:28:51,672 - INFO - Epoch 60/100 - Train Loss: 0.2450 - Val Acc: 0.8841
2026-04-05 05:28:51,943 - INFO - Epoch 61/100 - Train Loss: 0.2425 - Val Acc: 0.8841
2026-04-05 05:28:52,217 - INFO - Epoch 62/100 - Train Loss: 0.2428 - Val Acc: 0.8696
2026-04-05 05:28:52,491 - INFO - Epoch 63/100 - Train Loss: 0.2453 - Val Acc: 0.8551
2026-04-05 05:28:52,756 - INFO - Epoch 64/100 - Train Loss: 0.2368 - Val Acc: 0.8696
2026-04-05 05:28:53,031 - INFO - Epoch 65/100 - Train Loss: 0.2434 - Val Acc: 0.8696
2026-04-05 05:28:53,300 - INFO - Epoch 66/100 - Train Loss: 0.2413 - Val Acc: 0.8696
2026-04-05 05:28:53,577 - INFO - Epoch 67/100 - Train Loss: 0.2391 - Val Acc: 0.8696
2026-04-05 05:28:53,852 - INFO - Epoch 68/100 - Train Loss: 0.2392 - Val Acc: 0.8696
2026-04-05 05:28:54,146 - INFO - Epoch 69/100 - Train Loss: 0.2403 - Val Acc: 0.8551
2026-04-05 05:28:54,455 - INFO - Epoch 70/100 - Train Loss: 0.2358 - Val Acc: 0.8696
2026-04-05 05:28:54,757 - INFO - Epoch 71/100 - Train Loss: 0.2406 - Val Acc: 0.8696
2026-04-05 05:28:55,053 - INFO - Epoch 72/100 - Train Loss: 0.2372 - Val Acc: 0.8696
2026-04-05 05:28:55,325 - INFO - Epoch 73/100 - Train Loss: 0.2355 - Val Acc: 0.8551
2026-04-05 05:28:55,600 - INFO - Epoch 74/100 - Train Loss: 0.2327 - Val Acc: 0.8696
2026-04-05 05:28:55,862 - INFO - Epoch 75/100 - Train Loss: 0.2333 - Val Acc: 0.8696
2026-04-05 05:28:56,148 - INFO - Epoch 76/100 - Train Loss: 0.2348 - Val Acc: 0.8551
2026-04-05 05:28:56,418 - INFO - Epoch 77/100 - Train Loss: 0.2343 - Val Acc: 0.8551
2026-04-05 05:28:56,691 - INFO - Epoch 78/100 - Train Loss: 0.2335 - Val Acc: 0.8551
2026-04-05 05:28:56,955 - INFO - Epoch 79/100 - Train Loss: 0.2349 - Val Acc: 0.8551
2026-04-05 05:28:57,226 - INFO - Epoch 80/100 - Train Loss: 0.2374 - Val Acc: 0.8551
2026-04-05 05:28:57,503 - INFO - Epoch 81/100 - Train Loss: 0.2326 - Val Acc: 0.8551
2026-04-05 05:28:57,772 - INFO - Epoch 82/100 - Train Loss: 0.2271 - Val Acc: 0.8551
2026-04-05 05:28:58,039 - INFO - Epoch 83/100 - Train Loss: 0.2365 - Val Acc: 0.8551
2026-04-05 05:28:58,298 - INFO - Epoch 84/100 - Train Loss: 0.2292 - Val Acc: 0.8551
2026-04-05 05:28:58,570 - INFO - Epoch 85/100 - Train Loss: 0.2306 - Val Acc: 0.8406
2026-04-05 05:28:58,845 - INFO - Epoch 86/100 - Train Loss: 0.2272 - Val Acc: 0.8551
2026-04-05 05:28:59,113 - INFO - Epoch 87/100 - Train Loss: 0.2267 - Val Acc: 0.8551
2026-04-05 05:28:59,380 - INFO - Epoch 88/100 - Train Loss: 0.2265 - Val Acc: 0.8551
2026-04-05 05:28:59,647 - INFO - Epoch 89/100 - Train Loss: 0.2253 - Val Acc: 0.8551
2026-04-05 05:28:59,919 - INFO - Epoch 90/100 - Train Loss: 0.2238 - Val Acc: 0.8551
2026-04-05 05:29:00,193 - INFO - Epoch 91/100 - Train Loss: 0.2228 - Val Acc: 0.8551
2026-04-05 05:29:00,455 - INFO - Epoch 92/100 - Train Loss: 0.2208 - Val Acc: 0.8551
2026-04-05 05:29:00,733 - INFO - Epoch 93/100 - Train Loss: 0.2234 - Val Acc: 0.8551
2026-04-05 05:29:00,994 - INFO - Epoch 94/100 - Train Loss: 0.2207 - Val Acc: 0.8551
2026-04-05 05:29:01,257 - INFO - Epoch 95/100 - Train Loss: 0.2249 - Val Acc: 0.8551
2026-04-05 05:29:01,531 - INFO - Epoch 96/100 - Train Loss: 0.2228 - Val Acc: 0.8551
2026-04-05 05:29:01,817 - INFO - Epoch 97/100 - Train Loss: 0.2239 - Val Acc: 0.8551
2026-04-05 05:29:02,081 - INFO - Epoch 98/100 - Train Loss: 0.2143 - Val Acc: 0.8551
2026-04-05 05:29:02,359 - INFO - Epoch 99/100 - Train Loss: 0.2181 - Val Acc: 0.8551
2026-04-05 05:29:02,631 - INFO - Epoch 100/100 - Train Loss: 0.2237 - Val Acc: 0.8551
2026-04-05 05:29:02,993 - INFO - Fold 6 logically complete. Tensor memory bounds cleared cleanly.
2026-04-05 05:29:02,997 - INFO - Original class distribution: [276 345]
2026-04-05 05:29:02,998 - INFO - Training device bound securely to: cuda

Fold 7:   0%|          | 0/100 [00:00<?, ?it/s]

2026-04-05 05:29:03,286 - INFO - Epoch 1/100 - Train Loss: 0.5524 - Val Acc: 0.7246
2026-04-05 05:29:03,573 - INFO - Epoch 2/100 - Train Loss: 0.4020 - Val Acc: 0.7391
2026-04-05 05:29:03,849 - INFO - Epoch 3/100 - Train Loss: 0.3515 - Val Acc: 0.7536
2026-04-05 05:29:04,126 - INFO - Epoch 4/100 - Train Loss: 0.3280 - Val Acc: 0.7536
2026-04-05 05:29:04,393 - INFO - Epoch 5/100 - Train Loss: 0.3150 - Val Acc: 0.7536
2026-04-05 05:29:04,702 - INFO - Epoch 6/100 - Train Loss: 0.3039 - Val Acc: 0.7536
2026-04-05 05:29:04,980 - INFO - Epoch 7/100 - Train Loss: 0.2971 - Val Acc: 0.7536
2026-04-05 05:29:05,238 - INFO - Epoch 8/100 - Train Loss: 0.2902 - Val Acc: 0.7826
2026-04-05 05:29:05,508 - INFO - Epoch 9/100 - Train Loss: 0.2854 - Val Acc: 0.7826
2026-04-05 05:29:05,773 - INFO - Epoch 10/100 - Train Loss: 0.2811 - Val Acc: 0.7826
2026-04-05 05:29:06,040 - INFO - Epoch 11/100 - Train Loss: 0.2778 - Val Acc: 0.7826
2026-04-05 05:29:06,307 - INFO - Epoch 12/100 - Train Loss: 0.2742 - Val Acc: 0.7826
2026-04-05 05:29:06,576 - INFO - Epoch 13/100 - Train Loss: 0.2732 - Val Acc: 0.7971
2026-04-05 05:29:06,843 - INFO - Epoch 14/100 - Train Loss: 0.2721 - Val Acc: 0.7971
2026-04-05 05:29:07,112 - INFO - Epoch 15/100 - Train Loss: 0.2702 - Val Acc: 0.7971
2026-04-05 05:29:07,377 - INFO - Epoch 16/100 - Train Loss: 0.2670 - Val Acc: 0.8406
2026-04-05 05:29:07,671 - INFO - Epoch 17/100 - Train Loss: 0.2710 - Val Acc: 0.8116
2026-04-05 05:29:07,946 - INFO - Epoch 18/100 - Train Loss: 0.2660 - Val Acc: 0.8116
2026-04-05 05:29:08,221 - INFO - Epoch 19/100 - Train Loss: 0.2657 - Val Acc: 0.8116
2026-04-05 05:29:08,492 - INFO - Epoch 20/100 - Train Loss: 0.2635 - Val Acc: 0.8116
2026-04-05 05:29:08,765 - INFO - Epoch 21/100 - Train Loss: 0.2623 - Val Acc: 0.7971
2026-04-05 05:29:09,049 - INFO - Epoch 22/100 - Train Loss: 0.2610 - Val Acc: 0.8116
2026-04-05 05:29:09,316 - INFO - Epoch 23/100 - Train Loss: 0.2598 - Val Acc: 0.7971
2026-04-05 05:29:09,580 - INFO - Epoch 24/100 - Train Loss: 0.2582 - Val Acc: 0.7826
2026-04-05 05:29:09,847 - INFO - Epoch 25/100 - Train Loss: 0.2571 - Val Acc: 0.7826
2026-04-05 05:29:10,117 - INFO - Epoch 26/100 - Train Loss: 0.2562 - Val Acc: 0.7826
2026-04-05 05:29:10,388 - INFO - Epoch 27/100 - Train Loss: 0.2565 - Val Acc: 0.7826
2026-04-05 05:29:10,653 - INFO - Epoch 28/100 - Train Loss: 0.2543 - Val Acc: 0.7681
2026-04-05 05:29:10,926 - INFO - Epoch 29/100 - Train Loss: 0.2506 - Val Acc: 0.7681
2026-04-05 05:29:11,205 - INFO - Epoch 30/100 - Train Loss: 0.2518 - Val Acc: 0.7681
2026-04-05 05:29:11,477 - INFO - Epoch 31/100 - Train Loss: 0.2519 - Val Acc: 0.7681
2026-04-05 05:29:11,742 - INFO - Epoch 32/100 - Train Loss: 0.2485 - Val Acc: 0.7681
2026-04-05 05:29:12,014 - INFO - Epoch 33/100 - Train Loss: 0.2470 - Val Acc: 0.7681
2026-04-05 05:29:12,278 - INFO - Epoch 34/100 - Train Loss: 0.2477 - Val Acc: 0.7681
2026-04-05 05:29:12,546 - INFO - Epoch 35/100 - Train Loss: 0.2468 - Val Acc: 0.7681
2026-04-05 05:29:12,821 - INFO - Epoch 36/100 - Train Loss: 0.2455 - Val Acc: 0.7681
2026-04-05 05:29:13,095 - INFO - Epoch 37/100 - Train Loss: 0.2459 - Val Acc: 0.7681
2026-04-05 05:29:13,364 - INFO - Epoch 38/100 - Train Loss: 0.2430 - Val Acc: 0.7681
2026-04-05 05:29:13,647 - INFO - Epoch 39/100 - Train Loss: 0.2418 - Val Acc: 0.7681
2026-04-05 05:29:13,920 - INFO - Epoch 40/100 - Train Loss: 0.2387 - Val Acc: 0.7681
2026-04-05 05:29:14,197 - INFO - Epoch 41/100 - Train Loss: 0.2372 - Val Acc: 0.7681
2026-04-05 05:29:14,462 - INFO - Epoch 42/100 - Train Loss: 0.2397 - Val Acc: 0.7681
2026-04-05 05:29:14,762 - INFO - Epoch 43/100 - Train Loss: 0.2371 - Val Acc: 0.7681
2026-04-05 05:29:15,036 - INFO - Epoch 44/100 - Train Loss: 0.2378 - Val Acc: 0.7681
2026-04-05 05:29:15,305 - INFO - Epoch 45/100 - Train Loss: 0.2359 - Val Acc: 0.7681
2026-04-05 05:29:15,588 - INFO - Epoch 46/100 - Train Loss: 0.2360 - Val Acc: 0.7681
2026-04-05 05:29:15,860 - INFO - Epoch 47/100 - Train Loss: 0.2322 - Val Acc: 0.7681
2026-04-05 05:29:16,132 - INFO - Epoch 48/100 - Train Loss: 0.2309 - Val Acc: 0.7681
2026-04-05 05:29:16,409 - INFO - Epoch 49/100 - Train Loss: 0.2305 - Val Acc: 0.7681
2026-04-05 05:29:16,677 - INFO - Epoch 50/100 - Train Loss: 0.2335 - Val Acc: 0.7681
2026-04-05 05:29:16,953 - INFO - Epoch 51/100 - Train Loss: 0.2301 - Val Acc: 0.7681
2026-04-05 05:29:17,237 - INFO - Epoch 52/100 - Train Loss: 0.2296 - Val Acc: 0.7681
2026-04-05 05:29:17,514 - INFO - Epoch 53/100 - Train Loss: 0.2293 - Val Acc: 0.7681
2026-04-05 05:29:17,781 - INFO - Epoch 54/100 - Train Loss: 0.2280 - Val Acc: 0.7681
2026-04-05 05:29:18,051 - INFO - Epoch 55/100 - Train Loss: 0.2289 - Val Acc: 0.7681
2026-04-05 05:29:18,327 - INFO - Epoch 56/100 - Train Loss: 0.2273 - Val Acc: 0.7681
2026-04-05 05:29:18,598 - INFO - Epoch 57/100 - Train Loss: 0.2227 - Val Acc: 0.7681
2026-04-05 05:29:18,876 - INFO - Epoch 58/100 - Train Loss: 0.2243 - Val Acc: 0.7681
2026-04-05 05:29:19,154 - INFO - Epoch 59/100 - Train Loss: 0.2241 - Val Acc: 0.7681
2026-04-05 05:29:19,417 - INFO - Epoch 60/100 - Train Loss: 0.2257 - Val Acc: 0.7681
2026-04-05 05:29:19,704 - INFO - Epoch 61/100 - Train Loss: 0.2238 - Val Acc: 0.7681
2026-04-05 05:29:19,982 - INFO - Epoch 62/100 - Train Loss: 0.2215 - Val Acc: 0.7681
2026-04-05 05:29:20,261 - INFO - Epoch 63/100 - Train Loss: 0.2215 - Val Acc: 0.7681
2026-04-05 05:29:20,537 - INFO - Epoch 64/100 - Train Loss: 0.2235 - Val Acc: 0.7681
2026-04-05 05:29:20,826 - INFO - Epoch 65/100 - Train Loss: 0.2215 - Val Acc: 0.7681
2026-04-05 05:29:21,098 - INFO - Epoch 66/100 - Train Loss: 0.2220 - Val Acc: 0.7681
2026-04-05 05:29:21,383 - INFO - Epoch 67/100 - Train Loss: 0.2181 - Val Acc: 0.7681
2026-04-05 05:29:21,650 - INFO - Epoch 68/100 - Train Loss: 0.2171 - Val Acc: 0.7681
2026-04-05 05:29:21,929 - INFO - Epoch 69/100 - Train Loss: 0.2216 - Val Acc: 0.7681
2026-04-05 05:29:22,204 - INFO - Epoch 70/100 - Train Loss: 0.2195 - Val Acc: 0.7681
2026-04-05 05:29:22,485 - INFO - Epoch 71/100 - Train Loss: 0.2164 - Val Acc: 0.7681
2026-04-05 05:29:22,780 - INFO - Epoch 72/100 - Train Loss: 0.2171 - Val Acc: 0.7681
2026-04-05 05:29:23,058 - INFO - Epoch 73/100 - Train Loss: 0.2157 - Val Acc: 0.7681
2026-04-05 05:29:23,330 - INFO - Epoch 74/100 - Train Loss: 0.2136 - Val Acc: 0.7681
2026-04-05 05:29:23,598 - INFO - Epoch 75/100 - Train Loss: 0.2150 - Val Acc: 0.7681
2026-04-05 05:29:23,881 - INFO - Epoch 76/100 - Train Loss: 0.2103 - Val Acc: 0.7681
2026-04-05 05:29:24,153 - INFO - Epoch 77/100 - Train Loss: 0.2086 - Val Acc: 0.7681
2026-04-05 05:29:24,439 - INFO - Epoch 78/100 - Train Loss: 0.2121 - Val Acc: 0.7681
2026-04-05 05:29:24,751 - INFO - Epoch 79/100 - Train Loss: 0.2152 - Val Acc: 0.7681
2026-04-05 05:29:25,023 - INFO - Epoch 80/100 - Train Loss: 0.2099 - Val Acc: 0.7681
2026-04-05 05:29:25,292 - INFO - Epoch 81/100 - Train Loss: 0.2059 - Val Acc: 0.7681
2026-04-05 05:29:25,561 - INFO - Epoch 82/100 - Train Loss: 0.2115 - Val Acc: 0.7681
2026-04-05 05:29:25,842 - INFO - Epoch 83/100 - Train Loss: 0.2071 - Val Acc: 0.7681
2026-04-05 05:29:26,117 - INFO - Epoch 84/100 - Train Loss: 0.2079 - Val Acc: 0.7681
2026-04-05 05:29:26,389 - INFO - Epoch 85/100 - Train Loss: 0.2079 - Val Acc: 0.7681
2026-04-05 05:29:26,676 - INFO - Epoch 86/100 - Train Loss: 0.2080 - Val Acc: 0.7681
2026-04-05 05:29:26,961 - INFO - Epoch 87/100 - Train Loss: 0.2060 - Val Acc: 0.7681
2026-04-05 05:29:27,239 - INFO - Epoch 88/100 - Train Loss: 0.2023 - Val Acc: 0.7681
2026-04-05 05:29:27,512 - INFO - Epoch 89/100 - Train Loss: 0.2102 - Val Acc: 0.7681
2026-04-05 05:29:27,795 - INFO - Epoch 90/100 - Train Loss: 0.2019 - Val Acc: 0.7681
2026-04-05 05:29:28,064 - INFO - Epoch 91/100 - Train Loss: 0.2044 - Val Acc: 0.7681
2026-04-05 05:29:28,340 - INFO - Epoch 92/100 - Train Loss: 0.2034 - Val Acc: 0.7681
2026-04-05 05:29:28,630 - INFO - Epoch 93/100 - Train Loss: 0.2038 - Val Acc: 0.7681
2026-04-05 05:29:28,909 - INFO - Epoch 94/100 - Train Loss: 0.2024 - Val Acc: 0.7681
2026-04-05 05:29:29,179 - INFO - Epoch 95/100 - Train Loss: 0.2042 - Val Acc: 0.7681
2026-04-05 05:29:29,446 - INFO - Epoch 96/100 - Train Loss: 0.2041 - Val Acc: 0.7681
2026-04-05 05:29:29,717 - INFO - Epoch 97/100 - Train Loss: 0.1998 - Val Acc: 0.7681
2026-04-05 05:29:29,982 - INFO - Epoch 98/100 - Train Loss: 0.1973 - Val Acc: 0.7681
2026-04-05 05:29:30,244 - INFO - Epoch 99/100 - Train Loss: 0.2028 - Val Acc: 0.7681
2026-04-05 05:29:30,506 - INFO - Epoch 100/100 - Train Loss: 0.1993 - Val Acc: 0.7681
2026-04-05 05:29:30,874 - INFO - Fold 7 logically complete. Tensor memory bounds cleared cleanly.
2026-04-05 05:29:30,878 - INFO - Original class distribution: [276 345]
2026-04-05 05:29:30,879 - INFO - Training device bound securely to: cuda

Fold 8:   0%|          | 0/100 [00:00<?, ?it/s]

2026-04-05 05:29:31,187 - INFO - Epoch 1/100 - Train Loss: 0.5612 - Val Acc: 0.8696
2026-04-05 05:29:31,453 - INFO - Epoch 2/100 - Train Loss: 0.4099 - Val Acc: 0.8406
2026-04-05 05:29:31,730 - INFO - Epoch 3/100 - Train Loss: 0.3646 - Val Acc: 0.8116
2026-04-05 05:29:32,007 - INFO - Epoch 4/100 - Train Loss: 0.3443 - Val Acc: 0.8261
2026-04-05 05:29:32,289 - INFO - Epoch 5/100 - Train Loss: 0.3315 - Val Acc: 0.8261
2026-04-05 05:29:32,575 - INFO - Epoch 6/100 - Train Loss: 0.3194 - Val Acc: 0.8116
2026-04-05 05:29:32,848 - INFO - Epoch 7/100 - Train Loss: 0.3134 - Val Acc: 0.8261
2026-04-05 05:29:33,114 - INFO - Epoch 8/100 - Train Loss: 0.3080 - Val Acc: 0.8261
2026-04-05 05:29:33,378 - INFO - Epoch 9/100 - Train Loss: 0.3079 - Val Acc: 0.8261
2026-04-05 05:29:33,654 - INFO - Epoch 10/100 - Train Loss: 0.3008 - Val Acc: 0.8261
2026-04-05 05:29:33,916 - INFO - Epoch 11/100 - Train Loss: 0.2974 - Val Acc: 0.8406
2026-04-05 05:29:34,188 - INFO - Epoch 12/100 - Train Loss: 0.2971 - Val Acc: 0.8406
2026-04-05 05:29:34,458 - INFO - Epoch 13/100 - Train Loss: 0.2984 - Val Acc: 0.8406
2026-04-05 05:29:34,758 - INFO - Epoch 14/100 - Train Loss: 0.2936 - Val Acc: 0.8406
2026-04-05 05:29:35,040 - INFO - Epoch 15/100 - Train Loss: 0.2922 - Val Acc: 0.8406
2026-04-05 05:29:35,317 - INFO - Epoch 16/100 - Train Loss: 0.2915 - Val Acc: 0.8406
2026-04-05 05:29:35,591 - INFO - Epoch 17/100 - Train Loss: 0.2932 - Val Acc: 0.8406
2026-04-05 05:29:35,863 - INFO - Epoch 18/100 - Train Loss: 0.2869 - Val Acc: 0.8406
2026-04-05 05:29:36,127 - INFO - Epoch 19/100 - Train Loss: 0.2841 - Val Acc: 0.8406
2026-04-05 05:29:36,407 - INFO - Epoch 20/100 - Train Loss: 0.2848 - Val Acc: 0.8406
2026-04-05 05:29:36,684 - INFO - Epoch 21/100 - Train Loss: 0.2836 - Val Acc: 0.8406
2026-04-05 05:29:36,965 - INFO - Epoch 22/100 - Train Loss: 0.2824 - Val Acc: 0.8406
2026-04-05 05:29:37,244 - INFO - Epoch 23/100 - Train Loss: 0.2838 - Val Acc: 0.8406
2026-04-05 05:29:37,523 - INFO - Epoch 24/100 - Train Loss: 0.2808 - Val Acc: 0.8406
2026-04-05 05:29:37,795 - INFO - Epoch 25/100 - Train Loss: 0.2798 - Val Acc: 0.8406
2026-04-05 05:29:38,065 - INFO - Epoch 26/100 - Train Loss: 0.2799 - Val Acc: 0.8406
2026-04-05 05:29:38,344 - INFO - Epoch 27/100 - Train Loss: 0.2764 - Val Acc: 0.8406
2026-04-05 05:29:38,622 - INFO - Epoch 28/100 - Train Loss: 0.2746 - Val Acc: 0.8406
2026-04-05 05:29:38,903 - INFO - Epoch 29/100 - Train Loss: 0.2761 - Val Acc: 0.8406
2026-04-05 05:29:39,170 - INFO - Epoch 30/100 - Train Loss: 0.2751 - Val Acc: 0.8406
2026-04-05 05:29:39,458 - INFO - Epoch 31/100 - Train Loss: 0.2750 - Val Acc: 0.8406
2026-04-05 05:29:39,734 - INFO - Epoch 32/100 - Train Loss: 0.2735 - Val Acc: 0.8406
2026-04-05 05:29:40,007 - INFO - Epoch 33/100 - Train Loss: 0.2721 - Val Acc: 0.8406
2026-04-05 05:29:40,272 - INFO - Epoch 34/100 - Train Loss: 0.2687 - Val Acc: 0.8406
2026-04-05 05:29:40,540 - INFO - Epoch 35/100 - Train Loss: 0.2683 - Val Acc: 0.8406
2026-04-05 05:29:40,806 - INFO - Epoch 36/100 - Train Loss: 0.2655 - Val Acc: 0.8406
2026-04-05 05:29:41,077 - INFO - Epoch 37/100 - Train Loss: 0.2662 - Val Acc: 0.8406
2026-04-05 05:29:41,364 - INFO - Epoch 38/100 - Train Loss: 0.2648 - Val Acc: 0.8406
2026-04-05 05:29:41,629 - INFO - Epoch 39/100 - Train Loss: 0.2634 - Val Acc: 0.8406
2026-04-05 05:29:41,903 - INFO - Epoch 40/100 - Train Loss: 0.2617 - Val Acc: 0.8406
2026-04-05 05:29:42,173 - INFO - Epoch 41/100 - Train Loss: 0.2596 - Val Acc: 0.8406
2026-04-05 05:29:42,448 - INFO - Epoch 42/100 - Train Loss: 0.2576 - Val Acc: 0.8406
2026-04-05 05:29:42,726 - INFO - Epoch 43/100 - Train Loss: 0.2606 - Val Acc: 0.8406
2026-04-05 05:29:42,995 - INFO - Epoch 44/100 - Train Loss: 0.2632 - Val Acc: 0.8406
2026-04-05 05:29:43,259 - INFO - Epoch 45/100 - Train Loss: 0.2590 - Val Acc: 0.8551
2026-04-05 05:29:43,529 - INFO - Epoch 46/100 - Train Loss: 0.2549 - Val Acc: 0.8406
2026-04-05 05:29:43,794 - INFO - Epoch 47/100 - Train Loss: 0.2536 - Val Acc: 0.8406
2026-04-05 05:29:44,065 - INFO - Epoch 48/100 - Train Loss: 0.2521 - Val Acc: 0.8406
2026-04-05 05:29:44,355 - INFO - Epoch 49/100 - Train Loss: 0.2512 - Val Acc: 0.8406
2026-04-05 05:29:44,656 - INFO - Epoch 50/100 - Train Loss: 0.2544 - Val Acc: 0.8406
2026-04-05 05:29:44,927 - INFO - Epoch 51/100 - Train Loss: 0.2529 - Val Acc: 0.8406
2026-04-05 05:29:45,200 - INFO - Epoch 52/100 - Train Loss: 0.2502 - Val Acc: 0.8406
2026-04-05 05:29:45,473 - INFO - Epoch 53/100 - Train Loss: 0.2485 - Val Acc: 0.8406
2026-04-05 05:29:45,738 - INFO - Epoch 54/100 - Train Loss: 0.2484 - Val Acc: 0.8551
2026-04-05 05:29:46,010 - INFO - Epoch 55/100 - Train Loss: 0.2473 - Val Acc: 0.8406
2026-04-05 05:29:46,273 - INFO - Epoch 56/100 - Train Loss: 0.2452 - Val Acc: 0.8406
2026-04-05 05:29:46,546 - INFO - Epoch 57/100 - Train Loss: 0.2442 - Val Acc: 0.8406
2026-04-05 05:29:46,819 - INFO - Epoch 58/100 - Train Loss: 0.2455 - Val Acc: 0.8406
2026-04-05 05:29:47,089 - INFO - Epoch 59/100 - Train Loss: 0.2459 - Val Acc: 0.8406
2026-04-05 05:29:47,359 - INFO - Epoch 60/100 - Train Loss: 0.2425 - Val Acc: 0.8406
2026-04-05 05:29:47,630 - INFO - Epoch 61/100 - Train Loss: 0.2431 - Val Acc: 0.8406
2026-04-05 05:29:47,915 - INFO - Epoch 62/100 - Train Loss: 0.2437 - Val Acc: 0.8406
2026-04-05 05:29:48,188 - INFO - Epoch 63/100 - Train Loss: 0.2441 - Val Acc: 0.8551
2026-04-05 05:29:48,461 - INFO - Epoch 64/100 - Train Loss: 0.2410 - Val Acc: 0.8551
2026-04-05 05:29:48,728 - INFO - Epoch 65/100 - Train Loss: 0.2410 - Val Acc: 0.8551
2026-04-05 05:29:49,000 - INFO - Epoch 66/100 - Train Loss: 0.2389 - Val Acc: 0.8551
2026-04-05 05:29:49,277 - INFO - Epoch 67/100 - Train Loss: 0.2433 - Val Acc: 0.8551
2026-04-05 05:29:49,550 - INFO - Epoch 68/100 - Train Loss: 0.2386 - Val Acc: 0.8551
2026-04-05 05:29:49,821 - INFO - Epoch 69/100 - Train Loss: 0.2411 - Val Acc: 0.8551
2026-04-05 05:29:50,098 - INFO - Epoch 70/100 - Train Loss: 0.2373 - Val Acc: 0.8551
2026-04-05 05:29:50,378 - INFO - Epoch 71/100 - Train Loss: 0.2333 - Val Acc: 0.8551
2026-04-05 05:29:50,649 - INFO - Epoch 72/100 - Train Loss: 0.2364 - Val Acc: 0.8551
2026-04-05 05:29:50,932 - INFO - Epoch 73/100 - Train Loss: 0.2361 - Val Acc: 0.8551
2026-04-05 05:29:51,201 - INFO - Epoch 74/100 - Train Loss: 0.2341 - Val Acc: 0.8551
2026-04-05 05:29:51,468 - INFO - Epoch 75/100 - Train Loss: 0.2334 - Val Acc: 0.8406
2026-04-05 05:29:51,745 - INFO - Epoch 76/100 - Train Loss: 0.2345 - Val Acc: 0.8406
2026-04-05 05:29:52,028 - INFO - Epoch 77/100 - Train Loss: 0.2345 - Val Acc: 0.8551
2026-04-05 05:29:52,297 - INFO - Epoch 78/100 - Train Loss: 0.2333 - Val Acc: 0.8406
2026-04-05 05:29:52,577 - INFO - Epoch 79/100 - Train Loss: 0.2341 - Val Acc: 0.8406
2026-04-05 05:29:52,857 - INFO - Epoch 80/100 - Train Loss: 0.2332 - Val Acc: 0.8406
2026-04-05 05:29:53,136 - INFO - Epoch 81/100 - Train Loss: 0.2291 - Val Acc: 0.8406
2026-04-05 05:29:53,403 - INFO - Epoch 82/100 - Train Loss: 0.2285 - Val Acc: 0.8406
2026-04-05 05:29:53,666 - INFO - Epoch 83/100 - Train Loss: 0.2288 - Val Acc: 0.8406
2026-04-05 05:29:53,939 - INFO - Epoch 84/100 - Train Loss: 0.2287 - Val Acc: 0.8406
2026-04-05 05:29:54,225 - INFO - Epoch 85/100 - Train Loss: 0.2228 - Val Acc: 0.8406
2026-04-05 05:29:54,496 - INFO - Epoch 86/100 - Train Loss: 0.2272 - Val Acc: 0.8261
2026-04-05 05:29:54,785 - INFO - Epoch 87/100 - Train Loss: 0.2254 - Val Acc: 0.8261
2026-04-05 05:29:55,070 - INFO - Epoch 88/100 - Train Loss: 0.2268 - Val Acc: 0.8261
2026-04-05 05:29:55,348 - INFO - Epoch 89/100 - Train Loss: 0.2249 - Val Acc: 0.8261
2026-04-05 05:29:55,626 - INFO - Epoch 90/100 - Train Loss: 0.2252 - Val Acc: 0.8261
2026-04-05 05:29:55,914 - INFO - Epoch 91/100 - Train Loss: 0.2269 - Val Acc: 0.8261
2026-04-05 05:29:56,179 - INFO - Epoch 92/100 - Train Loss: 0.2300 - Val Acc: 0.8261
2026-04-05 05:29:56,449 - INFO - Epoch 93/100 - Train Loss: 0.2242 - Val Acc: 0.8406
2026-04-05 05:29:56,730 - INFO - Epoch 94/100 - Train Loss: 0.2229 - Val Acc: 0.8406
2026-04-05 05:29:57,001 - INFO - Epoch 95/100 - Train Loss: 0.2225 - Val Acc: 0.8406
2026-04-05 05:29:57,265 - INFO - Epoch 96/100 - Train Loss: 0.2221 - Val Acc: 0.8406
2026-04-05 05:29:57,544 - INFO - Epoch 97/100 - Train Loss: 0.2200 - Val Acc: 0.8406
2026-04-05 05:29:57,820 - INFO - Epoch 98/100 - Train Loss: 0.2171 - Val Acc: 0.8261
2026-04-05 05:29:58,089 - INFO - Epoch 99/100 - Train Loss: 0.2189 - Val Acc: 0.8261
2026-04-05 05:29:58,355 - INFO - Epoch 100/100 - Train Loss: 0.2197 - Val Acc: 0.8261
2026-04-05 05:29:58,712 - INFO - Fold 8 logically complete. Tensor memory bounds cleared cleanly.
2026-04-05 05:29:58,715 - INFO - Original class distribution: [276 345]
2026-04-05 05:29:58,716 - INFO - Training device bound securely to: cuda

Fold 9:   0%|          | 0/100 [00:00<?, ?it/s]

2026-04-05 05:29:59,006 - INFO - Epoch 1/100 - Train Loss: 0.5653 - Val Acc: 0.8116
2026-04-05 05:29:59,290 - INFO - Epoch 2/100 - Train Loss: 0.4060 - Val Acc: 0.8406
2026-04-05 05:29:59,557 - INFO - Epoch 3/100 - Train Loss: 0.3591 - Val Acc: 0.8116
2026-04-05 05:29:59,818 - INFO - Epoch 4/100 - Train Loss: 0.3365 - Val Acc: 0.8261
2026-04-05 05:30:00,089 - INFO - Epoch 5/100 - Train Loss: 0.3203 - Val Acc: 0.8261
2026-04-05 05:30:00,368 - INFO - Epoch 6/100 - Train Loss: 0.3153 - Val Acc: 0.8261
2026-04-05 05:30:00,640 - INFO - Epoch 7/100 - Train Loss: 0.3044 - Val Acc: 0.8116
2026-04-05 05:30:00,917 - INFO - Epoch 8/100 - Train Loss: 0.3002 - Val Acc: 0.8116
2026-04-05 05:30:01,183 - INFO - Epoch 9/100 - Train Loss: 0.2956 - Val Acc: 0.8116
2026-04-05 05:30:01,447 - INFO - Epoch 10/100 - Train Loss: 0.2929 - Val Acc: 0.8116
2026-04-05 05:30:01,721 - INFO - Epoch 11/100 - Train Loss: 0.2918 - Val Acc: 0.8116
2026-04-05 05:30:01,994 - INFO - Epoch 12/100 - Train Loss: 0.2886 - Val Acc: 0.8116
2026-04-05 05:30:02,265 - INFO - Epoch 13/100 - Train Loss: 0.2887 - Val Acc: 0.8116
2026-04-05 05:30:02,530 - INFO - Epoch 14/100 - Train Loss: 0.2868 - Val Acc: 0.8261
2026-04-05 05:30:02,800 - INFO - Epoch 15/100 - Train Loss: 0.2822 - Val Acc: 0.8261
2026-04-05 05:30:03,080 - INFO - Epoch 16/100 - Train Loss: 0.2837 - Val Acc: 0.8116
2026-04-05 05:30:03,348 - INFO - Epoch 17/100 - Train Loss: 0.2813 - Val Acc: 0.7971
2026-04-05 05:30:03,610 - INFO - Epoch 18/100 - Train Loss: 0.2818 - Val Acc: 0.7971
2026-04-05 05:30:03,886 - INFO - Epoch 19/100 - Train Loss: 0.2779 - Val Acc: 0.8116
2026-04-05 05:30:04,161 - INFO - Epoch 20/100 - Train Loss: 0.2765 - Val Acc: 0.8116
2026-04-05 05:30:04,426 - INFO - Epoch 21/100 - Train Loss: 0.2770 - Val Acc: 0.8116
2026-04-05 05:30:04,718 - INFO - Epoch 22/100 - Train Loss: 0.2772 - Val Acc: 0.7971
2026-04-05 05:30:04,997 - INFO - Epoch 23/100 - Train Loss: 0.2734 - Val Acc: 0.7971
2026-04-05 05:30:05,281 - INFO - Epoch 24/100 - Train Loss: 0.2766 - Val Acc: 0.8116
2026-04-05 05:30:05,551 - INFO - Epoch 25/100 - Train Loss: 0.2726 - Val Acc: 0.7971
2026-04-05 05:30:05,813 - INFO - Epoch 26/100 - Train Loss: 0.2725 - Val Acc: 0.8116
2026-04-05 05:30:06,090 - INFO - Epoch 27/100 - Train Loss: 0.2724 - Val Acc: 0.8116
2026-04-05 05:30:06,367 - INFO - Epoch 28/100 - Train Loss: 0.2689 - Val Acc: 0.8116
2026-04-05 05:30:06,643 - INFO - Epoch 29/100 - Train Loss: 0.2721 - Val Acc: 0.8116
2026-04-05 05:30:06,911 - INFO - Epoch 30/100 - Train Loss: 0.2660 - Val Acc: 0.8261
2026-04-05 05:30:07,193 - INFO - Epoch 31/100 - Train Loss: 0.2675 - Val Acc: 0.8261
2026-04-05 05:30:07,457 - INFO - Epoch 32/100 - Train Loss: 0.2659 - Val Acc: 0.8261
2026-04-05 05:30:07,733 - INFO - Epoch 33/100 - Train Loss: 0.2668 - Val Acc: 0.8261
2026-04-05 05:30:08,021 - INFO - Epoch 34/100 - Train Loss: 0.2655 - Val Acc: 0.8261
2026-04-05 05:30:08,294 - INFO - Epoch 35/100 - Train Loss: 0.2639 - Val Acc: 0.8261
2026-04-05 05:30:08,552 - INFO - Epoch 36/100 - Train Loss: 0.2632 - Val Acc: 0.8261
2026-04-05 05:30:08,820 - INFO - Epoch 37/100 - Train Loss: 0.2625 - Val Acc: 0.8261
2026-04-05 05:30:09,110 - INFO - Epoch 38/100 - Train Loss: 0.2614 - Val Acc: 0.8261
2026-04-05 05:30:09,383 - INFO - Epoch 39/100 - Train Loss: 0.2615 - Val Acc: 0.8261
2026-04-05 05:30:09,647 - INFO - Epoch 40/100 - Train Loss: 0.2595 - Val Acc: 0.8261
2026-04-05 05:30:09,921 - INFO - Epoch 41/100 - Train Loss: 0.2569 - Val Acc: 0.8261
2026-04-05 05:30:10,194 - INFO - Epoch 42/100 - Train Loss: 0.2556 - Val Acc: 0.8261
2026-04-05 05:30:10,462 - INFO - Epoch 43/100 - Train Loss: 0.2556 - Val Acc: 0.8261
2026-04-05 05:30:10,725 - INFO - Epoch 44/100 - Train Loss: 0.2571 - Val Acc: 0.8261
2026-04-05 05:30:10,992 - INFO - Epoch 45/100 - Train Loss: 0.2557 - Val Acc: 0.8261
2026-04-05 05:30:11,262 - INFO - Epoch 46/100 - Train Loss: 0.2543 - Val Acc: 0.8261
2026-04-05 05:30:11,525 - INFO - Epoch 47/100 - Train Loss: 0.2518 - Val Acc: 0.8261
2026-04-05 05:30:11,802 - INFO - Epoch 48/100 - Train Loss: 0.2508 - Val Acc: 0.8261
2026-04-05 05:30:12,067 - INFO - Epoch 49/100 - Train Loss: 0.2532 - Val Acc: 0.8261
2026-04-05 05:30:12,337 - INFO - Epoch 50/100 - Train Loss: 0.2486 - Val Acc: 0.8261
2026-04-05 05:30:12,613 - INFO - Epoch 51/100 - Train Loss: 0.2490 - Val Acc: 0.8261
2026-04-05 05:30:12,886 - INFO - Epoch 52/100 - Train Loss: 0.2487 - Val Acc: 0.8116
2026-04-05 05:30:13,161 - INFO - Epoch 53/100 - Train Loss: 0.2486 - Val Acc: 0.8261
2026-04-05 05:30:13,433 - INFO - Epoch 54/100 - Train Loss: 0.2494 - Val Acc: 0.8261
2026-04-05 05:30:13,720 - INFO - Epoch 55/100 - Train Loss: 0.2479 - Val Acc: 0.8261
2026-04-05 05:30:14,005 - INFO - Epoch 56/100 - Train Loss: 0.2452 - Val Acc: 0.8261
2026-04-05 05:30:14,282 - INFO - Epoch 57/100 - Train Loss: 0.2445 - Val Acc: 0.8261
2026-04-05 05:30:14,585 - INFO - Epoch 58/100 - Train Loss: 0.2417 - Val Acc: 0.8116
2026-04-05 05:30:14,867 - INFO - Epoch 59/100 - Train Loss: 0.2401 - Val Acc: 0.8116
2026-04-05 05:30:15,144 - INFO - Epoch 60/100 - Train Loss: 0.2394 - Val Acc: 0.8261
2026-04-05 05:30:15,423 - INFO - Epoch 61/100 - Train Loss: 0.2399 - Val Acc: 0.8261
2026-04-05 05:30:15,700 - INFO - Epoch 62/100 - Train Loss: 0.2408 - Val Acc: 0.8261
2026-04-05 05:30:15,978 - INFO - Epoch 63/100 - Train Loss: 0.2364 - Val Acc: 0.8261
2026-04-05 05:30:16,252 - INFO - Epoch 64/100 - Train Loss: 0.2370 - Val Acc: 0.8261
2026-04-05 05:30:16,541 - INFO - Epoch 65/100 - Train Loss: 0.2384 - Val Acc: 0.8261
2026-04-05 05:30:16,821 - INFO - Epoch 66/100 - Train Loss: 0.2371 - Val Acc: 0.8261
2026-04-05 05:30:17,099 - INFO - Epoch 67/100 - Train Loss: 0.2360 - Val Acc: 0.8261
2026-04-05 05:30:17,392 - INFO - Epoch 68/100 - Train Loss: 0.2339 - Val Acc: 0.8261
2026-04-05 05:30:17,677 - INFO - Epoch 69/100 - Train Loss: 0.2328 - Val Acc: 0.8406
2026-04-05 05:30:17,959 - INFO - Epoch 70/100 - Train Loss: 0.2298 - Val Acc: 0.8406
2026-04-05 05:30:18,234 - INFO - Epoch 71/100 - Train Loss: 0.2347 - Val Acc: 0.8406
2026-04-05 05:30:18,512 - INFO - Epoch 72/100 - Train Loss: 0.2330 - Val Acc: 0.8406
2026-04-05 05:30:18,789 - INFO - Epoch 73/100 - Train Loss: 0.2342 - Val Acc: 0.8406
2026-04-05 05:30:19,073 - INFO - Epoch 74/100 - Train Loss: 0.2323 - Val Acc: 0.8406
2026-04-05 05:30:19,351 - INFO - Epoch 75/100 - Train Loss: 0.2268 - Val Acc: 0.8406
2026-04-05 05:30:19,638 - INFO - Epoch 76/100 - Train Loss: 0.2270 - Val Acc: 0.8406
2026-04-05 05:30:19,917 - INFO - Epoch 77/100 - Train Loss: 0.2294 - Val Acc: 0.8406
2026-04-05 05:30:20,192 - INFO - Epoch 78/100 - Train Loss: 0.2266 - Val Acc: 0.8406
2026-04-05 05:30:20,467 - INFO - Epoch 79/100 - Train Loss: 0.2248 - Val Acc: 0.8406
2026-04-05 05:30:20,749 - INFO - Epoch 80/100 - Train Loss: 0.2215 - Val Acc: 0.8406
2026-04-05 05:30:21,023 - INFO - Epoch 81/100 - Train Loss: 0.2258 - Val Acc: 0.8406
2026-04-05 05:30:21,295 - INFO - Epoch 82/100 - Train Loss: 0.2278 - Val Acc: 0.8406
2026-04-05 05:30:21,567 - INFO - Epoch 83/100 - Train Loss: 0.2299 - Val Acc: 0.8406
2026-04-05 05:30:21,843 - INFO - Epoch 84/100 - Train Loss: 0.2237 - Val Acc: 0.8261
2026-04-05 05:30:22,108 - INFO - Epoch 85/100 - Train Loss: 0.2252 - Val Acc: 0.8261
2026-04-05 05:30:22,384 - INFO - Epoch 86/100 - Train Loss: 0.2253 - Val Acc: 0.8406
2026-04-05 05:30:22,663 - INFO - Epoch 87/100 - Train Loss: 0.2251 - Val Acc: 0.8116
2026-04-05 05:30:22,937 - INFO - Epoch 88/100 - Train Loss: 0.2213 - Val Acc: 0.8406
2026-04-05 05:30:23,222 - INFO - Epoch 89/100 - Train Loss: 0.2222 - Val Acc: 0.8406
2026-04-05 05:30:23,491 - INFO - Epoch 90/100 - Train Loss: 0.2191 - Val Acc: 0.8406
2026-04-05 05:30:23,759 - INFO - Epoch 91/100 - Train Loss: 0.2157 - Val Acc: 0.8406
2026-04-05 05:30:24,030 - INFO - Epoch 92/100 - Train Loss: 0.2149 - Val Acc: 0.8406
2026-04-05 05:30:24,320 - INFO - Epoch 93/100 - Train Loss: 0.2178 - Val Acc: 0.8406
2026-04-05 05:30:24,615 - INFO - Epoch 94/100 - Train Loss: 0.2225 - Val Acc: 0.8406
2026-04-05 05:30:24,926 - INFO - Epoch 95/100 - Train Loss: 0.2197 - Val Acc: 0.8406
2026-04-05 05:30:25,227 - INFO - Epoch 96/100 - Train Loss: 0.2207 - Val Acc: 0.8406
2026-04-05 05:30:25,496 - INFO - Epoch 97/100 - Train Loss: 0.2175 - Val Acc: 0.8261
2026-04-05 05:30:25,779 - INFO - Epoch 98/100 - Train Loss: 0.2118 - Val Acc: 0.8406
2026-04-05 05:30:26,065 - INFO - Epoch 99/100 - Train Loss: 0.2162 - Val Acc: 0.8261
2026-04-05 05:30:26,349 - INFO - Epoch 100/100 - Train Loss: 0.2130 - Val Acc: 0.8261
2026-04-05 05:30:26,712 - INFO - Fold 9 logically complete. Tensor memory bounds cleared cleanly.
2026-04-05 05:30:26,716 - INFO - Original class distribution: [276 345]
2026-04-05 05:30:26,717 - INFO - Training device bound securely to: cuda

Fold 10:   0%|          | 0/100 [00:00<?, ?it/s]

2026-04-05 05:30:27,029 - INFO - Epoch 1/100 - Train Loss: 0.5604 - Val Acc: 0.8986
2026-04-05 05:30:27,305 - INFO - Epoch 2/100 - Train Loss: 0.4105 - Val Acc: 0.8986
2026-04-05 05:30:27,576 - INFO - Epoch 3/100 - Train Loss: 0.3688 - Val Acc: 0.8986
2026-04-05 05:30:27,848 - INFO - Epoch 4/100 - Train Loss: 0.3498 - Val Acc: 0.8986
2026-04-05 05:30:28,122 - INFO - Epoch 5/100 - Train Loss: 0.3383 - Val Acc: 0.8986
2026-04-05 05:30:28,397 - INFO - Epoch 6/100 - Train Loss: 0.3337 - Val Acc: 0.8986
2026-04-05 05:30:28,667 - INFO - Epoch 7/100 - Train Loss: 0.3264 - Val Acc: 0.9420
2026-04-05 05:30:28,938 - INFO - Epoch 8/100 - Train Loss: 0.3195 - Val Acc: 0.9420
2026-04-05 05:30:29,219 - INFO - Epoch 9/100 - Train Loss: 0.3176 - Val Acc: 0.9420
2026-04-05 05:30:29,488 - INFO - Epoch 10/100 - Train Loss: 0.3156 - Val Acc: 0.9420
2026-04-05 05:30:29,764 - INFO - Epoch 11/100 - Train Loss: 0.3132 - Val Acc: 0.9420
2026-04-05 05:30:30,035 - INFO - Epoch 12/100 - Train Loss: 0.3088 - Val Acc: 0.9420
2026-04-05 05:30:30,308 - INFO - Epoch 13/100 - Train Loss: 0.3060 - Val Acc: 0.9420
2026-04-05 05:30:30,584 - INFO - Epoch 14/100 - Train Loss: 0.3070 - Val Acc: 0.9565
2026-04-05 05:30:30,849 - INFO - Epoch 15/100 - Train Loss: 0.3049 - Val Acc: 0.9565
2026-04-05 05:30:31,124 - INFO - Epoch 16/100 - Train Loss: 0.3032 - Val Acc: 0.9565
2026-04-05 05:30:31,395 - INFO - Epoch 17/100 - Train Loss: 0.3009 - Val Acc: 0.9565
2026-04-05 05:30:31,662 - INFO - Epoch 18/100 - Train Loss: 0.3008 - Val Acc: 0.9565
2026-04-05 05:30:31,922 - INFO - Epoch 19/100 - Train Loss: 0.2961 - Val Acc: 0.9565
2026-04-05 05:30:32,207 - INFO - Epoch 20/100 - Train Loss: 0.2931 - Val Acc: 0.9565
2026-04-05 05:30:32,478 - INFO - Epoch 21/100 - Train Loss: 0.2963 - Val Acc: 0.9565
2026-04-05 05:30:32,753 - INFO - Epoch 22/100 - Train Loss: 0.2963 - Val Acc: 0.9565
2026-04-05 05:30:33,023 - INFO - Epoch 23/100 - Train Loss: 0.2938 - Val Acc: 0.9565
2026-04-05 05:30:33,302 - INFO - Epoch 24/100 - Train Loss: 0.2947 - Val Acc: 0.9565
2026-04-05 05:30:33,576 - INFO - Epoch 25/100 - Train Loss: 0.2887 - Val Acc: 0.9565
2026-04-05 05:30:33,862 - INFO - Epoch 26/100 - Train Loss: 0.2904 - Val Acc: 0.9565
2026-04-05 05:30:34,153 - INFO - Epoch 27/100 - Train Loss: 0.2899 - Val Acc: 0.9565
2026-04-05 05:30:34,435 - INFO - Epoch 28/100 - Train Loss: 0.2873 - Val Acc: 0.9565
2026-04-05 05:30:34,740 - INFO - Epoch 29/100 - Train Loss: 0.2857 - Val Acc: 0.9565
2026-04-05 05:30:35,026 - INFO - Epoch 30/100 - Train Loss: 0.2837 - Val Acc: 0.9565
2026-04-05 05:30:35,302 - INFO - Epoch 31/100 - Train Loss: 0.2849 - Val Acc: 0.9565
2026-04-05 05:30:35,575 - INFO - Epoch 32/100 - Train Loss: 0.2806 - Val Acc: 0.9565
2026-04-05 05:30:35,848 - INFO - Epoch 33/100 - Train Loss: 0.2806 - Val Acc: 0.9565
2026-04-05 05:30:36,125 - INFO - Epoch 34/100 - Train Loss: 0.2799 - Val Acc: 0.9565
2026-04-05 05:30:36,412 - INFO - Epoch 35/100 - Train Loss: 0.2780 - Val Acc: 0.9565
2026-04-05 05:30:36,690 - INFO - Epoch 36/100 - Train Loss: 0.2786 - Val Acc: 0.9565
2026-04-05 05:30:36,960 - INFO - Epoch 37/100 - Train Loss: 0.2765 - Val Acc: 0.9565
2026-04-05 05:30:37,232 - INFO - Epoch 38/100 - Train Loss: 0.2782 - Val Acc: 0.9565
2026-04-05 05:30:37,511 - INFO - Epoch 39/100 - Train Loss: 0.2758 - Val Acc: 0.9565
2026-04-05 05:30:37,777 - INFO - Epoch 40/100 - Train Loss: 0.2734 - Val Acc: 0.9565
2026-04-05 05:30:38,061 - INFO - Epoch 41/100 - Train Loss: 0.2700 - Val Acc: 0.9565
2026-04-05 05:30:38,330 - INFO - Epoch 42/100 - Train Loss: 0.2739 - Val Acc: 0.9565
2026-04-05 05:30:38,601 - INFO - Epoch 43/100 - Train Loss: 0.2679 - Val Acc: 0.9565
2026-04-05 05:30:38,875 - INFO - Epoch 44/100 - Train Loss: 0.2697 - Val Acc: 0.9565
2026-04-05 05:30:39,155 - INFO - Epoch 45/100 - Train Loss: 0.2665 - Val Acc: 0.9565
2026-04-05 05:30:39,426 - INFO - Epoch 46/100 - Train Loss: 0.2619 - Val Acc: 0.9565
2026-04-05 05:30:39,709 - INFO - Epoch 47/100 - Train Loss: 0.2680 - Val Acc: 0.9565
2026-04-05 05:30:39,997 - INFO - Epoch 48/100 - Train Loss: 0.2673 - Val Acc: 0.9565
2026-04-05 05:30:40,279 - INFO - Epoch 49/100 - Train Loss: 0.2665 - Val Acc: 0.9710
2026-04-05 05:30:40,542 - INFO - Epoch 50/100 - Train Loss: 0.2614 - Val Acc: 0.9710
2026-04-05 05:30:40,823 - INFO - Epoch 51/100 - Train Loss: 0.2613 - Val Acc: 0.9565
2026-04-05 05:30:41,102 - INFO - Epoch 52/100 - Train Loss: 0.2639 - Val Acc: 0.9710
2026-04-05 05:30:41,377 - INFO - Epoch 53/100 - Train Loss: 0.2589 - Val Acc: 0.9565
2026-04-05 05:30:41,656 - INFO - Epoch 54/100 - Train Loss: 0.2540 - Val Acc: 0.9565
2026-04-05 05:30:41,940 - INFO - Epoch 55/100 - Train Loss: 0.2578 - Val Acc: 0.9565
2026-04-05 05:30:42,209 - INFO - Epoch 56/100 - Train Loss: 0.2564 - Val Acc: 0.9565
2026-04-05 05:30:42,477 - INFO - Epoch 57/100 - Train Loss: 0.2522 - Val Acc: 0.9565
2026-04-05 05:30:42,767 - INFO - Epoch 58/100 - Train Loss: 0.2542 - Val Acc: 0.9565
2026-04-05 05:30:43,031 - INFO - Epoch 59/100 - Train Loss: 0.2518 - Val Acc: 0.9565
2026-04-05 05:30:43,302 - INFO - Epoch 60/100 - Train Loss: 0.2550 - Val Acc: 0.9710
2026-04-05 05:30:43,576 - INFO - Epoch 61/100 - Train Loss: 0.2554 - Val Acc: 0.9710
2026-04-05 05:30:43,842 - INFO - Epoch 62/100 - Train Loss: 0.2509 - Val Acc: 0.9565
2026-04-05 05:30:44,119 - INFO - Epoch 63/100 - Train Loss: 0.2546 - Val Acc: 0.9565
2026-04-05 05:30:44,397 - INFO - Epoch 64/100 - Train Loss: 0.2470 - Val Acc: 0.9710
2026-04-05 05:30:44,696 - INFO - Epoch 65/100 - Train Loss: 0.2497 - Val Acc: 0.9710
2026-04-05 05:30:44,978 - INFO - Epoch 66/100 - Train Loss: 0.2490 - Val Acc: 0.9710
2026-04-05 05:30:45,264 - INFO - Epoch 67/100 - Train Loss: 0.2488 - Val Acc: 0.9710
2026-04-05 05:30:45,545 - INFO - Epoch 68/100 - Train Loss: 0.2457 - Val Acc: 0.9710
2026-04-05 05:30:45,847 - INFO - Epoch 69/100 - Train Loss: 0.2476 - Val Acc: 0.9710
2026-04-05 05:30:46,132 - INFO - Epoch 70/100 - Train Loss: 0.2483 - Val Acc: 0.9710
2026-04-05 05:30:46,400 - INFO - Epoch 71/100 - Train Loss: 0.2480 - Val Acc: 0.9710
2026-04-05 05:30:46,686 - INFO - Epoch 72/100 - Train Loss: 0.2396 - Val Acc: 0.9565
2026-04-05 05:30:46,955 - INFO - Epoch 73/100 - Train Loss: 0.2441 - Val Acc: 0.9565
2026-04-05 05:30:47,232 - INFO - Epoch 74/100 - Train Loss: 0.2428 - Val Acc: 0.9565
2026-04-05 05:30:47,516 - INFO - Epoch 75/100 - Train Loss: 0.2386 - Val Acc: 0.9710
2026-04-05 05:30:47,786 - INFO - Epoch 76/100 - Train Loss: 0.2387 - Val Acc: 0.9565
2026-04-05 05:30:48,068 - INFO - Epoch 77/100 - Train Loss: 0.2388 - Val Acc: 0.9710
2026-04-05 05:30:48,357 - INFO - Epoch 78/100 - Train Loss: 0.2421 - Val Acc: 0.9710
2026-04-05 05:30:48,635 - INFO - Epoch 79/100 - Train Loss: 0.2421 - Val Acc: 0.9565
2026-04-05 05:30:48,910 - INFO - Epoch 80/100 - Train Loss: 0.2387 - Val Acc: 0.9565
2026-04-05 05:30:49,184 - INFO - Epoch 81/100 - Train Loss: 0.2311 - Val Acc: 0.9710
2026-04-05 05:30:49,457 - INFO - Epoch 82/100 - Train Loss: 0.2432 - Val Acc: 0.9710
2026-04-05 05:30:49,724 - INFO - Epoch 83/100 - Train Loss: 0.2367 - Val Acc: 0.9565
2026-04-05 05:30:49,998 - INFO - Epoch 84/100 - Train Loss: 0.2368 - Val Acc: 0.9565
2026-04-05 05:30:50,269 - INFO - Epoch 85/100 - Train Loss: 0.2395 - Val Acc: 0.9565
2026-04-05 05:30:50,548 - INFO - Epoch 86/100 - Train Loss: 0.2352 - Val Acc: 0.9565
2026-04-05 05:30:50,837 - INFO - Epoch 87/100 - Train Loss: 0.2352 - Val Acc: 0.9565
2026-04-05 05:30:51,115 - INFO - Epoch 88/100 - Train Loss: 0.2332 - Val Acc: 0.9710
2026-04-05 05:30:51,378 - INFO - Epoch 89/100 - Train Loss: 0.2314 - Val Acc: 0.9565
2026-04-05 05:30:51,658 - INFO - Epoch 90/100 - Train Loss: 0.2351 - Val Acc: 0.9420
2026-04-05 05:30:51,927 - INFO - Epoch 91/100 - Train Loss: 0.2332 - Val Acc: 0.9420
2026-04-05 05:30:52,197 - INFO - Epoch 92/100 - Train Loss: 0.2397 - Val Acc: 0.9565
2026-04-05 05:30:52,475 - INFO - Epoch 93/100 - Train Loss: 0.2366 - Val Acc: 0.9420
2026-04-05 05:30:52,751 - INFO - Epoch 94/100 - Train Loss: 0.2263 - Val Acc: 0.9420
2026-04-05 05:30:53,033 - INFO - Epoch 95/100 - Train Loss: 0.2317 - Val Acc: 0.9565
2026-04-05 05:30:53,318 - INFO - Epoch 96/100 - Train Loss: 0.2345 - Val Acc: 0.9565
2026-04-05 05:30:53,611 - INFO - Epoch 97/100 - Train Loss: 0.2281 - Val Acc: 0.9565
2026-04-05 05:30:53,888 - INFO - Epoch 98/100 - Train Loss: 0.2254 - Val Acc: 0.9420
2026-04-05 05:30:54,178 - INFO - Epoch 99/100 - Train Loss: 0.2277 - Val Acc: 0.9420
2026-04-05 05:30:54,471 - INFO - Epoch 100/100 - Train Loss: 0.2205 - Val Acc: 0.9420
2026-04-05 05:30:54,854 - INFO - Fold 10 logically complete. Tensor memory bounds cleared cleanly.
2026-04-05 05:30:54,872 - INFO - ✓ Completed LSTM_baseline
2026-04-05 05:30:54,873 - INFO -   Mean Accuracy: 0.8913 ± 0.0411
2026-04-05 05:30:54,874 - INFO -
EXPERIMENT: LSTM_SMOTEENN | german | SMOTE-ENN: True

German | LSTM | SMOTEENN:   0%|          | 0/10 [00:00<?, ?it/s]

2026-04-05 05:30:54,886 - INFO - Original class distribution: [277 344]
2026-04-05 05:30:54,887 - INFO - Training device bound securely to: cuda
2026-04-05 05:30:54,903 - INFO - After SMOTE-ENN deployment: [344 289]

Fold 1:   0%|          | 0/100 [00:00<?, ?it/s]

2026-04-05 05:30:55,192 - INFO - Epoch 1/100 - Train Loss: 0.5531 - Val Acc: 0.8406
2026-04-05 05:30:55,456 - INFO - Epoch 2/100 - Train Loss: 0.3673 - Val Acc: 0.8551
2026-04-05 05:30:55,731 - INFO - Epoch 3/100 - Train Loss: 0.2984 - Val Acc: 0.8551
2026-04-05 05:30:56,034 - INFO - Epoch 4/100 - Train Loss: 0.2641 - Val Acc: 0.8551
2026-04-05 05:30:56,304 - INFO - Epoch 5/100 - Train Loss: 0.2421 - Val Acc: 0.8551
2026-04-05 05:30:56,593 - INFO - Epoch 6/100 - Train Loss: 0.2240 - Val Acc: 0.8696
2026-04-05 05:30:56,866 - INFO - Epoch 7/100 - Train Loss: 0.2134 - Val Acc: 0.8696
2026-04-05 05:30:57,137 - INFO - Epoch 8/100 - Train Loss: 0.2040 - Val Acc: 0.8696
2026-04-05 05:30:57,404 - INFO - Epoch 9/100 - Train Loss: 0.1956 - Val Acc: 0.8696
2026-04-05 05:30:57,681 - INFO - Epoch 10/100 - Train Loss: 0.1904 - Val Acc: 0.8696
2026-04-05 05:30:57,956 - INFO - Epoch 11/100 - Train Loss: 0.1879 - Val Acc: 0.8696
2026-04-05 05:30:58,229 - INFO - Epoch 12/100 - Train Loss: 0.1847 - Val Acc: 0.8696
2026-04-05 05:30:58,494 - INFO - Epoch 13/100 - Train Loss: 0.1804 - Val Acc: 0.8841
2026-04-05 05:30:58,768 - INFO - Epoch 14/100 - Train Loss: 0.1775 - Val Acc: 0.8841
2026-04-05 05:30:59,044 - INFO - Epoch 15/100 - Train Loss: 0.1777 - Val Acc: 0.8986
2026-04-05 05:30:59,331 - INFO - Epoch 16/100 - Train Loss: 0.1766 - Val Acc: 0.8986
2026-04-05 05:30:59,591 - INFO - Epoch 17/100 - Train Loss: 0.1746 - Val Acc: 0.8986
2026-04-05 05:30:59,857 - INFO - Epoch 18/100 - Train Loss: 0.1730 - Val Acc: 0.8986
2026-04-05 05:31:00,134 - INFO - Epoch 19/100 - Train Loss: 0.1710 - Val Acc: 0.8986
2026-04-05 05:31:00,401 - INFO - Epoch 20/100 - Train Loss: 0.1686 - Val Acc: 0.8986
2026-04-05 05:31:00,673 - INFO - Epoch 21/100 - Train Loss: 0.1687 - Val Acc: 0.8986
2026-04-05 05:31:00,950 - INFO - Epoch 22/100 - Train Loss: 0.1661 - Val Acc: 0.8986
2026-04-05 05:31:01,229 - INFO - Epoch 23/100 - Train Loss: 0.1658 - Val Acc: 0.8986
2026-04-05 05:31:01,501 - INFO - Epoch 24/100 - Train Loss: 0.1657 - Val Acc: 0.8986
2026-04-05 05:31:01,779 - INFO - Epoch 25/100 - Train Loss: 0.1630 - Val Acc: 0.8986
2026-04-05 05:31:02,045 - INFO - Epoch 26/100 - Train Loss: 0.1615 - Val Acc: 0.8986
2026-04-05 05:31:02,318 - INFO - Epoch 27/100 - Train Loss: 0.1625 - Val Acc: 0.8986
2026-04-05 05:31:02,596 - INFO - Epoch 28/100 - Train Loss: 0.1582 - Val Acc: 0.8986
2026-04-05 05:31:02,859 - INFO - Epoch 29/100 - Train Loss: 0.1572 - Val Acc: 0.8986
2026-04-05 05:31:03,128 - INFO - Epoch 30/100 - Train Loss: 0.1561 - Val Acc: 0.8986
2026-04-05 05:31:03,389 - INFO - Epoch 31/100 - Train Loss: 0.1578 - Val Acc: 0.8986
2026-04-05 05:31:03,660 - INFO - Epoch 32/100 - Train Loss: 0.1555 - Val Acc: 0.8986
2026-04-05 05:31:03,955 - INFO - Epoch 33/100 - Train Loss: 0.1554 - Val Acc: 0.8986
2026-04-05 05:31:04,221 - INFO - Epoch 34/100 - Train Loss: 0.1534 - Val Acc: 0.8986
2026-04-05 05:31:04,506 - INFO - Epoch 35/100 - Train Loss: 0.1530 - Val Acc: 0.8986
2026-04-05 05:31:04,811 - INFO - Epoch 36/100 - Train Loss: 0.1510 - Val Acc: 0.8986
2026-04-05 05:31:05,076 - INFO - Epoch 37/100 - Train Loss: 0.1520 - Val Acc: 0.8986
2026-04-05 05:31:05,349 - INFO - Epoch 38/100 - Train Loss: 0.1473 - Val Acc: 0.8986
2026-04-05 05:31:05,609 - INFO - Epoch 39/100 - Train Loss: 0.1496 - Val Acc: 0.8841
2026-04-05 05:31:05,888 - INFO - Epoch 40/100 - Train Loss: 0.1503 - Val Acc: 0.8841
2026-04-05 05:31:06,163 - INFO - Epoch 41/100 - Train Loss: 0.1480 - Val Acc: 0.8841
2026-04-05 05:31:06,424 - INFO - Epoch 42/100 - Train Loss: 0.1454 - Val Acc: 0.8841
2026-04-05 05:31:06,698 - INFO - Epoch 43/100 - Train Loss: 0.1435 - Val Acc: 0.8841
2026-04-05 05:31:06,964 - INFO - Epoch 44/100 - Train Loss: 0.1448 - Val Acc: 0.8841
2026-04-05 05:31:07,231 - INFO - Epoch 45/100 - Train Loss: 0.1457 - Val Acc: 0.8841
2026-04-05 05:31:07,507 - INFO - Epoch 46/100 - Train Loss: 0.1423 - Val Acc: 0.8841
2026-04-05 05:31:07,783 - INFO - Epoch 47/100 - Train Loss: 0.1400 - Val Acc: 0.8841
2026-04-05 05:31:08,053 - INFO - Epoch 48/100 - Train Loss: 0.1393 - Val Acc: 0.8841
2026-04-05 05:31:08,321 - INFO - Epoch 49/100 - Train Loss: 0.1406 - Val Acc: 0.8841
2026-04-05 05:31:08,589 - INFO - Epoch 50/100 - Train Loss: 0.1391 - Val Acc: 0.8841
2026-04-05 05:31:08,862 - INFO - Epoch 51/100 - Train Loss: 0.1365 - Val Acc: 0.8841
2026-04-05 05:31:09,143 - INFO - Epoch 52/100 - Train Loss: 0.1373 - Val Acc: 0.8841
2026-04-05 05:31:09,431 - INFO - Epoch 53/100 - Train Loss: 0.1373 - Val Acc: 0.8841
2026-04-05 05:31:09,700 - INFO - Epoch 54/100 - Train Loss: 0.1350 - Val Acc: 0.8696
2026-04-05 05:31:09,971 - INFO - Epoch 55/100 - Train Loss: 0.1331 - Val Acc: 0.8696
2026-04-05 05:31:10,242 - INFO - Epoch 56/100 - Train Loss: 0.1341 - Val Acc: 0.8696
2026-04-05 05:31:10,514 - INFO - Epoch 57/100 - Train Loss: 0.1335 - Val Acc: 0.8696
2026-04-05 05:31:10,793 - INFO - Epoch 58/100 - Train Loss: 0.1294 - Val Acc: 0.8696
2026-04-05 05:31:11,064 - INFO - Epoch 59/100 - Train Loss: 0.1311 - Val Acc: 0.8696
2026-04-05 05:31:11,321 - INFO - Epoch 60/100 - Train Loss: 0.1291 - Val Acc: 0.8696
2026-04-05 05:31:11,602 - INFO - Epoch 61/100 - Train Loss: 0.1301 - Val Acc: 0.8696
2026-04-05 05:31:11,879 - INFO - Epoch 62/100 - Train Loss: 0.1273 - Val Acc: 0.8696
2026-04-05 05:31:12,154 - INFO - Epoch 63/100 - Train Loss: 0.1275 - Val Acc: 0.8696
2026-04-05 05:31:12,426 - INFO - Epoch 64/100 - Train Loss: 0.1260 - Val Acc: 0.8696
2026-04-05 05:31:12,695 - INFO - Epoch 65/100 - Train Loss: 0.1240 - Val Acc: 0.8696
2026-04-05 05:31:12,978 - INFO - Epoch 66/100 - Train Loss: 0.1245 - Val Acc: 0.8696
2026-04-05 05:31:13,263 - INFO - Epoch 67/100 - Train Loss: 0.1246 - Val Acc: 0.8696
2026-04-05 05:31:13,536 - INFO - Epoch 68/100 - Train Loss: 0.1221 - Val Acc: 0.8696
2026-04-05 05:31:13,809 - INFO - Epoch 69/100 - Train Loss: 0.1224 - Val Acc: 0.8696
2026-04-05 05:31:14,080 - INFO - Epoch 70/100 - Train Loss: 0.1205 - Val Acc: 0.8696
2026-04-05 05:31:14,354 - INFO - Epoch 71/100 - Train Loss: 0.1215 - Val Acc: 0.8696
2026-04-05 05:31:14,645 - INFO - Epoch 72/100 - Train Loss: 0.1181 - Val Acc: 0.8696
2026-04-05 05:31:14,926 - INFO - Epoch 73/100 - Train Loss: 0.1156 - Val Acc: 0.8696
2026-04-05 05:31:15,198 - INFO - Epoch 74/100 - Train Loss: 0.1158 - Val Acc: 0.8696
2026-04-05 05:31:15,476 - INFO - Epoch 75/100 - Train Loss: 0.1172 - Val Acc: 0.8696
2026-04-05 05:31:15,748 - INFO - Epoch 76/100 - Train Loss: 0.1160 - Val Acc: 0.8696
2026-04-05 05:31:16,028 - INFO - Epoch 77/100 - Train Loss: 0.1154 - Val Acc: 0.8696
2026-04-05 05:31:16,305 - INFO - Epoch 78/100 - Train Loss: 0.1154 - Val Acc: 0.8696
2026-04-05 05:31:16,581 - INFO - Epoch 79/100 - Train Loss: 0.1164 - Val Acc: 0.8696
2026-04-05 05:31:16,859 - INFO - Epoch 80/100 - Train Loss: 0.1157 - Val Acc: 0.8696
2026-04-05 05:31:17,128 - INFO - Epoch 81/100 - Train Loss: 0.1120 - Val Acc: 0.8696
2026-04-05 05:31:17,407 - INFO - Epoch 82/100 - Train Loss: 0.1093 - Val Acc: 0.8696
2026-04-05 05:31:17,673 - INFO - Epoch 83/100 - Train Loss: 0.1132 - Val Acc: 0.8696
2026-04-05 05:31:17,941 - INFO - Epoch 84/100 - Train Loss: 0.1116 - Val Acc: 0.8696
2026-04-05 05:31:18,206 - INFO - Epoch 85/100 - Train Loss: 0.1106 - Val Acc: 0.8696
2026-04-05 05:31:18,483 - INFO - Epoch 86/100 - Train Loss: 0.1121 - Val Acc: 0.8696
2026-04-05 05:31:18,765 - INFO - Epoch 87/100 - Train Loss: 0.1121 - Val Acc: 0.8696
2026-04-05 05:31:19,041 - INFO - Epoch 88/100 - Train Loss: 0.1100 - Val Acc: 0.8696
2026-04-05 05:31:19,309 - INFO - Epoch 89/100 - Train Loss: 0.1081 - Val Acc: 0.8696
2026-04-05 05:31:19,578 - INFO - Epoch 90/100 - Train Loss: 0.1106 - Val Acc: 0.8696
2026-04-05 05:31:19,857 - INFO - Epoch 91/100 - Train Loss: 0.1102 - Val Acc: 0.8696
2026-04-05 05:31:20,128 - INFO - Epoch 92/100 - Train Loss: 0.1065 - Val Acc: 0.8696
2026-04-05 05:31:20,396 - INFO - Epoch 93/100 - Train Loss: 0.1040 - Val Acc: 0.8696
2026-04-05 05:31:20,677 - INFO - Epoch 94/100 - Train Loss: 0.1044 - Val Acc: 0.8696
2026-04-05 05:31:20,952 - INFO - Epoch 95/100 - Train Loss: 0.0991 - Val Acc: 0.8696
2026-04-05 05:31:21,234 - INFO - Epoch 96/100 - Train Loss: 0.1051 - Val Acc: 0.8696
2026-04-05 05:31:21,510 - INFO - Epoch 97/100 - Train Loss: 0.1053 - Val Acc: 0.8696
2026-04-05 05:31:21,783 - INFO - Epoch 98/100 - Train Loss: 0.1037 - Val Acc: 0.8696
2026-04-05 05:31:22,068 - INFO - Epoch 99/100 - Train Loss: 0.1022 - Val Acc: 0.8696
2026-04-05 05:31:22,340 - INFO - Epoch 100/100 - Train Loss: 0.1027 - Val Acc: 0.8696
2026-04-05 05:31:22,705 - INFO - Fold 1 logically complete. Tensor memory bounds cleared cleanly.
2026-04-05 05:31:22,709 - INFO - Original class distribution: [277 344]
2026-04-05 05:31:22,710 - INFO - Training device bound securely to: cuda
2026-04-05 05:31:22,725 - INFO - After SMOTE-ENN deployment: [344 288]

Fold 2:   0%|          | 0/100 [00:00<?, ?it/s]

2026-04-05 05:31:23,010 - INFO - Epoch 1/100 - Train Loss: 0.5332 - Val Acc: 0.8261
2026-04-05 05:31:23,284 - INFO - Epoch 2/100 - Train Loss: 0.3483 - Val Acc: 0.8261
2026-04-05 05:31:23,553 - INFO - Epoch 3/100 - Train Loss: 0.2912 - Val Acc: 0.8696
2026-04-05 05:31:23,838 - INFO - Epoch 4/100 - Train Loss: 0.2628 - Val Acc: 0.9130
2026-04-05 05:31:24,106 - INFO - Epoch 5/100 - Train Loss: 0.2452 - Val Acc: 0.9130
2026-04-05 05:31:24,369 - INFO - Epoch 6/100 - Train Loss: 0.2323 - Val Acc: 0.9130
2026-04-05 05:31:24,668 - INFO - Epoch 7/100 - Train Loss: 0.2230 - Val Acc: 0.9130
2026-04-05 05:31:24,949 - INFO - Epoch 8/100 - Train Loss: 0.2173 - Val Acc: 0.9130
2026-04-05 05:31:25,221 - INFO - Epoch 9/100 - Train Loss: 0.2117 - Val Acc: 0.9130
2026-04-05 05:31:25,485 - INFO - Epoch 10/100 - Train Loss: 0.2079 - Val Acc: 0.9130
2026-04-05 05:31:25,749 - INFO - Epoch 11/100 - Train Loss: 0.1999 - Val Acc: 0.9130
2026-04-05 05:31:26,031 - INFO - Epoch 12/100 - Train Loss: 0.1982 - Val Acc: 0.9130
2026-04-05 05:31:26,296 - INFO - Epoch 13/100 - Train Loss: 0.1962 - Val Acc: 0.9130
2026-04-05 05:31:26,567 - INFO - Epoch 14/100 - Train Loss: 0.1939 - Val Acc: 0.9130
2026-04-05 05:31:26,831 - INFO - Epoch 15/100 - Train Loss: 0.1925 - Val Acc: 0.8986
2026-04-05 05:31:27,108 - INFO - Epoch 16/100 - Train Loss: 0.1905 - Val Acc: 0.8986
2026-04-05 05:31:27,387 - INFO - Epoch 17/100 - Train Loss: 0.1869 - Val Acc: 0.8986
2026-04-05 05:31:27,651 - INFO - Epoch 18/100 - Train Loss: 0.1847 - Val Acc: 0.8986
2026-04-05 05:31:27,931 - INFO - Epoch 19/100 - Train Loss: 0.1835 - Val Acc: 0.8841
2026-04-05 05:31:28,216 - INFO - Epoch 20/100 - Train Loss: 0.1838 - Val Acc: 0.8986
2026-04-05 05:31:28,504 - INFO - Epoch 21/100 - Train Loss: 0.1792 - Val Acc: 0.8986
2026-04-05 05:31:28,787 - INFO - Epoch 22/100 - Train Loss: 0.1782 - Val Acc: 0.8986
2026-04-05 05:31:29,070 - INFO - Epoch 23/100 - Train Loss: 0.1767 - Val Acc: 0.8841
2026-04-05 05:31:29,338 - INFO - Epoch 24/100 - Train Loss: 0.1737 - Val Acc: 0.8841
2026-04-05 05:31:29,610 - INFO - Epoch 25/100 - Train Loss: 0.1741 - Val Acc: 0.8841
2026-04-05 05:31:29,883 - INFO - Epoch 26/100 - Train Loss: 0.1722 - Val Acc: 0.8841
2026-04-05 05:31:30,158 - INFO - Epoch 27/100 - Train Loss: 0.1707 - Val Acc: 0.8841
2026-04-05 05:31:30,426 - INFO - Epoch 28/100 - Train Loss: 0.1714 - Val Acc: 0.8841
2026-04-05 05:31:30,698 - INFO - Epoch 29/100 - Train Loss: 0.1696 - Val Acc: 0.8841
2026-04-05 05:31:30,967 - INFO - Epoch 30/100 - Train Loss: 0.1688 - Val Acc: 0.8841
2026-04-05 05:31:31,236 - INFO - Epoch 31/100 - Train Loss: 0.1668 - Val Acc: 0.8841
2026-04-05 05:31:31,508 - INFO - Epoch 32/100 - Train Loss: 0.1656 - Val Acc: 0.8841
2026-04-05 05:31:31,784 - INFO - Epoch 33/100 - Train Loss: 0.1637 - Val Acc: 0.8841
2026-04-05 05:31:32,066 - INFO - Epoch 34/100 - Train Loss: 0.1632 - Val Acc: 0.8841
2026-04-05 05:31:32,341 - INFO - Epoch 35/100 - Train Loss: 0.1596 - Val Acc: 0.8841
2026-04-05 05:31:32,614 - INFO - Epoch 36/100 - Train Loss: 0.1614 - Val Acc: 0.8841
2026-04-05 05:31:32,880 - INFO - Epoch 37/100 - Train Loss: 0.1597 - Val Acc: 0.8841
2026-04-05 05:31:33,150 - INFO - Epoch 38/100 - Train Loss: 0.1581 - Val Acc: 0.8841
2026-04-05 05:31:33,431 - INFO - Epoch 39/100 - Train Loss: 0.1545 - Val Acc: 0.8841
2026-04-05 05:31:33,709 - INFO - Epoch 40/100 - Train Loss: 0.1574 - Val Acc: 0.8841
2026-04-05 05:31:33,987 - INFO - Epoch 41/100 - Train Loss: 0.1543 - Val Acc: 0.8841
2026-04-05 05:31:34,266 - INFO - Epoch 42/100 - Train Loss: 0.1521 - Val Acc: 0.8841
2026-04-05 05:31:34,559 - INFO - Epoch 43/100 - Train Loss: 0.1512 - Val Acc: 0.8841
2026-04-05 05:31:34,833 - INFO - Epoch 44/100 - Train Loss: 0.1505 - Val Acc: 0.8696
2026-04-05 05:31:35,109 - INFO - Epoch 45/100 - Train Loss: 0.1480 - Val Acc: 0.8696
2026-04-05 05:31:35,388 - INFO - Epoch 46/100 - Train Loss: 0.1461 - Val Acc: 0.8696
2026-04-05 05:31:35,658 - INFO - Epoch 47/100 - Train Loss: 0.1455 - Val Acc: 0.8696
2026-04-05 05:31:35,931 - INFO - Epoch 48/100 - Train Loss: 0.1461 - Val Acc: 0.8696
2026-04-05 05:31:36,204 - INFO - Epoch 49/100 - Train Loss: 0.1440 - Val Acc: 0.8696
2026-04-05 05:31:36,483 - INFO - Epoch 50/100 - Train Loss: 0.1455 - Val Acc: 0.8696
2026-04-05 05:31:36,764 - INFO - Epoch 51/100 - Train Loss: 0.1436 - Val Acc: 0.8696
2026-04-05 05:31:37,040 - INFO - Epoch 52/100 - Train Loss: 0.1412 - Val Acc: 0.8696
2026-04-05 05:31:37,308 - INFO - Epoch 53/100 - Train Loss: 0.1408 - Val Acc: 0.8696
2026-04-05 05:31:37,580 - INFO - Epoch 54/100 - Train Loss: 0.1421 - Val Acc: 0.8696
2026-04-05 05:31:37,847 - INFO - Epoch 55/100 - Train Loss: 0.1396 - Val Acc: 0.8696
2026-04-05 05:31:38,122 - INFO - Epoch 56/100 - Train Loss: 0.1375 - Val Acc: 0.8696
2026-04-05 05:31:38,396 - INFO - Epoch 57/100 - Train Loss: 0.1340 - Val Acc: 0.8696
2026-04-05 05:31:38,657 - INFO - Epoch 58/100 - Train Loss: 0.1364 - Val Acc: 0.8696
2026-04-05 05:31:38,937 - INFO - Epoch 59/100 - Train Loss: 0.1348 - Val Acc: 0.8696
2026-04-05 05:31:39,213 - INFO - Epoch 60/100 - Train Loss: 0.1352 - Val Acc: 0.8696
2026-04-05 05:31:39,484 - INFO - Epoch 61/100 - Train Loss: 0.1367 - Val Acc: 0.8696
2026-04-05 05:31:39,755 - INFO - Epoch 62/100 - Train Loss: 0.1322 - Val Acc: 0.8696
2026-04-05 05:31:40,025 - INFO - Epoch 63/100 - Train Loss: 0.1322 - Val Acc: 0.8841
2026-04-05 05:31:40,289 - INFO - Epoch 64/100 - Train Loss: 0.1320 - Val Acc: 0.8841
2026-04-05 05:31:40,555 - INFO - Epoch 65/100 - Train Loss: 0.1308 - Val Acc: 0.8696
2026-04-05 05:31:40,839 - INFO - Epoch 66/100 - Train Loss: 0.1310 - Val Acc: 0.8696
2026-04-05 05:31:41,107 - INFO - Epoch 67/100 - Train Loss: 0.1322 - Val Acc: 0.8696
2026-04-05 05:31:41,370 - INFO - Epoch 68/100 - Train Loss: 0.1279 - Val Acc: 0.8696
2026-04-05 05:31:41,652 - INFO - Epoch 69/100 - Train Loss: 0.1259 - Val Acc: 0.8696
2026-04-05 05:31:41,923 - INFO - Epoch 70/100 - Train Loss: 0.1255 - Val Acc: 0.8696
2026-04-05 05:31:42,198 - INFO - Epoch 71/100 - Train Loss: 0.1257 - Val Acc: 0.8696
2026-04-05 05:31:42,476 - INFO - Epoch 72/100 - Train Loss: 0.1242 - Val Acc: 0.8696
2026-04-05 05:31:42,756 - INFO - Epoch 73/100 - Train Loss: 0.1255 - Val Acc: 0.8696
2026-04-05 05:31:43,026 - INFO - Epoch 74/100 - Train Loss: 0.1236 - Val Acc: 0.8841
2026-04-05 05:31:43,307 - INFO - Epoch 75/100 - Train Loss: 0.1259 - Val Acc: 0.8696
2026-04-05 05:31:43,589 - INFO - Epoch 76/100 - Train Loss: 0.1236 - Val Acc: 0.8696
2026-04-05 05:31:43,855 - INFO - Epoch 77/100 - Train Loss: 0.1236 - Val Acc: 0.8696
2026-04-05 05:31:44,118 - INFO - Epoch 78/100 - Train Loss: 0.1218 - Val Acc: 0.8696
2026-04-05 05:31:44,405 - INFO - Epoch 79/100 - Train Loss: 0.1183 - Val Acc: 0.8696
2026-04-05 05:31:44,709 - INFO - Epoch 80/100 - Train Loss: 0.1167 - Val Acc: 0.8841
2026-04-05 05:31:44,971 - INFO - Epoch 81/100 - Train Loss: 0.1236 - Val Acc: 0.8696
2026-04-05 05:31:45,248 - INFO - Epoch 82/100 - Train Loss: 0.1215 - Val Acc: 0.8696
2026-04-05 05:31:45,524 - INFO - Epoch 83/100 - Train Loss: 0.1206 - Val Acc: 0.8841
2026-04-05 05:31:45,789 - INFO - Epoch 84/100 - Train Loss: 0.1194 - Val Acc: 0.8696
2026-04-05 05:31:46,072 - INFO - Epoch 85/100 - Train Loss: 0.1163 - Val Acc: 0.8696
2026-04-05 05:31:46,338 - INFO - Epoch 86/100 - Train Loss: 0.1136 - Val Acc: 0.8841
2026-04-05 05:31:46,609 - INFO - Epoch 87/100 - Train Loss: 0.1177 - Val Acc: 0.8841
2026-04-05 05:31:46,877 - INFO - Epoch 88/100 - Train Loss: 0.1121 - Val Acc: 0.8841
2026-04-05 05:31:47,140 - INFO - Epoch 89/100 - Train Loss: 0.1152 - Val Acc: 0.8696
2026-04-05 05:31:47,426 - INFO - Epoch 90/100 - Train Loss: 0.1170 - Val Acc: 0.8841
2026-04-05 05:31:47,693 - INFO - Epoch 91/100 - Train Loss: 0.1154 - Val Acc: 0.8696
2026-04-05 05:31:47,974 - INFO - Epoch 92/100 - Train Loss: 0.1134 - Val Acc: 0.8696
2026-04-05 05:31:48,248 - INFO - Epoch 93/100 - Train Loss: 0.1150 - Val Acc: 0.8696
2026-04-05 05:31:48,518 - INFO - Epoch 94/100 - Train Loss: 0.1133 - Val Acc: 0.8551
2026-04-05 05:31:48,779 - INFO - Epoch 95/100 - Train Loss: 0.1138 - Val Acc: 0.8841
2026-04-05 05:31:49,057 - INFO - Epoch 96/100 - Train Loss: 0.1114 - Val Acc: 0.8841
2026-04-05 05:31:49,334 - INFO - Epoch 97/100 - Train Loss: 0.1109 - Val Acc: 0.8696
2026-04-05 05:31:49,605 - INFO - Epoch 98/100 - Train Loss: 0.1109 - Val Acc: 0.8551
2026-04-05 05:31:49,871 - INFO - Epoch 99/100 - Train Loss: 0.1099 - Val Acc: 0.8551
2026-04-05 05:31:50,135 - INFO - Epoch 100/100 - Train Loss: 0.1075 - Val Acc: 0.8551
2026-04-05 05:31:50,505 - INFO - Fold 2 logically complete. Tensor memory bounds cleared cleanly.
2026-04-05 05:31:50,509 - INFO - Original class distribution: [277 344]
2026-04-05 05:31:50,510 - INFO - Training device bound securely to: cuda
2026-04-05 05:31:50,525 - INFO - After SMOTE-ENN deployment: [344 291]

Fold 3:   0%|          | 0/100 [00:00<?, ?it/s]

2026-04-05 05:31:50,827 - INFO - Epoch 1/100 - Train Loss: 0.5336 - Val Acc: 0.8986
2026-04-05 05:31:51,093 - INFO - Epoch 2/100 - Train Loss: 0.3550 - Val Acc: 0.8986
2026-04-05 05:31:51,371 - INFO - Epoch 3/100 - Train Loss: 0.2908 - Val Acc: 0.9130
2026-04-05 05:31:51,638 - INFO - Epoch 4/100 - Train Loss: 0.2606 - Val Acc: 0.9130
2026-04-05 05:31:51,911 - INFO - Epoch 5/100 - Train Loss: 0.2385 - Val Acc: 0.9130
2026-04-05 05:31:52,187 - INFO - Epoch 6/100 - Train Loss: 0.2222 - Val Acc: 0.9130
2026-04-05 05:31:52,457 - INFO - Epoch 7/100 - Train Loss: 0.2073 - Val Acc: 0.9130
2026-04-05 05:31:52,737 - INFO - Epoch 8/100 - Train Loss: 0.2030 - Val Acc: 0.9130
2026-04-05 05:31:53,001 - INFO - Epoch 9/100 - Train Loss: 0.1967 - Val Acc: 0.9130
2026-04-05 05:31:53,272 - INFO - Epoch 10/100 - Train Loss: 0.1891 - Val Acc: 0.9130
2026-04-05 05:31:53,546 - INFO - Epoch 11/100 - Train Loss: 0.1874 - Val Acc: 0.9130
2026-04-05 05:31:53,815 - INFO - Epoch 12/100 - Train Loss: 0.1832 - Val Acc: 0.9130
2026-04-05 05:31:54,084 - INFO - Epoch 13/100 - Train Loss: 0.1821 - Val Acc: 0.9130
2026-04-05 05:31:54,375 - INFO - Epoch 14/100 - Train Loss: 0.1791 - Val Acc: 0.9130
2026-04-05 05:31:54,679 - INFO - Epoch 15/100 - Train Loss: 0.1782 - Val Acc: 0.9130
2026-04-05 05:31:54,959 - INFO - Epoch 16/100 - Train Loss: 0.1755 - Val Acc: 0.9130
2026-04-05 05:31:55,224 - INFO - Epoch 17/100 - Train Loss: 0.1753 - Val Acc: 0.9130
2026-04-05 05:31:55,484 - INFO - Epoch 18/100 - Train Loss: 0.1704 - Val Acc: 0.9130
2026-04-05 05:31:55,752 - INFO - Epoch 19/100 - Train Loss: 0.1692 - Val Acc: 0.9130
2026-04-05 05:31:56,060 - INFO - Epoch 20/100 - Train Loss: 0.1684 - Val Acc: 0.9130
2026-04-05 05:31:56,338 - INFO - Epoch 21/100 - Train Loss: 0.1700 - Val Acc: 0.9130
2026-04-05 05:31:56,603 - INFO - Epoch 22/100 - Train Loss: 0.1648 - Val Acc: 0.9130
2026-04-05 05:31:56,867 - INFO - Epoch 23/100 - Train Loss: 0.1647 - Val Acc: 0.9130
2026-04-05 05:31:57,131 - INFO - Epoch 24/100 - Train Loss: 0.1638 - Val Acc: 0.9130
2026-04-05 05:31:57,397 - INFO - Epoch 25/100 - Train Loss: 0.1615 - Val Acc: 0.9130
2026-04-05 05:31:57,657 - INFO - Epoch 26/100 - Train Loss: 0.1617 - Val Acc: 0.9130
2026-04-05 05:31:57,917 - INFO - Epoch 27/100 - Train Loss: 0.1607 - Val Acc: 0.9130
2026-04-05 05:31:58,188 - INFO - Epoch 28/100 - Train Loss: 0.1584 - Val Acc: 0.9130
2026-04-05 05:31:58,459 - INFO - Epoch 29/100 - Train Loss: 0.1573 - Val Acc: 0.9130
2026-04-05 05:31:58,740 - INFO - Epoch 30/100 - Train Loss: 0.1557 - Val Acc: 0.9130
2026-04-05 05:31:59,004 - INFO - Epoch 31/100 - Train Loss: 0.1547 - Val Acc: 0.9130
2026-04-05 05:31:59,296 - INFO - Epoch 32/100 - Train Loss: 0.1541 - Val Acc: 0.9130
2026-04-05 05:31:59,554 - INFO - Epoch 33/100 - Train Loss: 0.1549 - Val Acc: 0.9130
2026-04-05 05:31:59,821 - INFO - Epoch 34/100 - Train Loss: 0.1527 - Val Acc: 0.9130
2026-04-05 05:32:00,098 - INFO - Epoch 35/100 - Train Loss: 0.1526 - Val Acc: 0.9130
2026-04-05 05:32:00,366 - INFO - Epoch 36/100 - Train Loss: 0.1510 - Val Acc: 0.9130
2026-04-05 05:32:00,634 - INFO - Epoch 37/100 - Train Loss: 0.1491 - Val Acc: 0.9130
2026-04-05 05:32:00,895 - INFO - Epoch 38/100 - Train Loss: 0.1473 - Val Acc: 0.9130
2026-04-05 05:32:01,160 - INFO - Epoch 39/100 - Train Loss: 0.1441 - Val Acc: 0.9130
2026-04-05 05:32:01,427 - INFO - Epoch 40/100 - Train Loss: 0.1433 - Val Acc: 0.9130
2026-04-05 05:32:01,694 - INFO - Epoch 41/100 - Train Loss: 0.1444 - Val Acc: 0.9130
2026-04-05 05:32:01,964 - INFO - Epoch 42/100 - Train Loss: 0.1418 - Val Acc: 0.9130
2026-04-05 05:32:02,239 - INFO - Epoch 43/100 - Train Loss: 0.1453 - Val Acc: 0.9130
2026-04-05 05:32:02,518 - INFO - Epoch 44/100 - Train Loss: 0.1422 - Val Acc: 0.9130
2026-04-05 05:32:02,787 - INFO - Epoch 45/100 - Train Loss: 0.1416 - Val Acc: 0.9130
2026-04-05 05:32:03,067 - INFO - Epoch 46/100 - Train Loss: 0.1398 - Val Acc: 0.9130
2026-04-05 05:32:03,334 - INFO - Epoch 47/100 - Train Loss: 0.1398 - Val Acc: 0.9130
2026-04-05 05:32:03,609 - INFO - Epoch 48/100 - Train Loss: 0.1354 - Val Acc: 0.9130
2026-04-05 05:32:03,884 - INFO - Epoch 49/100 - Train Loss: 0.1370 - Val Acc: 0.9130
2026-04-05 05:32:04,171 - INFO - Epoch 50/100 - Train Loss: 0.1337 - Val Acc: 0.9130
2026-04-05 05:32:04,450 - INFO - Epoch 51/100 - Train Loss: 0.1351 - Val Acc: 0.9130
2026-04-05 05:32:04,755 - INFO - Epoch 52/100 - Train Loss: 0.1335 - Val Acc: 0.9130
2026-04-05 05:32:05,041 - INFO - Epoch 53/100 - Train Loss: 0.1311 - Val Acc: 0.9130
2026-04-05 05:32:05,322 - INFO - Epoch 54/100 - Train Loss: 0.1327 - Val Acc: 0.9130
2026-04-05 05:32:05,591 - INFO - Epoch 55/100 - Train Loss: 0.1321 - Val Acc: 0.9130
2026-04-05 05:32:05,868 - INFO - Epoch 56/100 - Train Loss: 0.1324 - Val Acc: 0.9130
2026-04-05 05:32:06,141 - INFO - Epoch 57/100 - Train Loss: 0.1299 - Val Acc: 0.9130
2026-04-05 05:32:06,421 - INFO - Epoch 58/100 - Train Loss: 0.1294 - Val Acc: 0.9130
2026-04-05 05:32:06,683 - INFO - Epoch 59/100 - Train Loss: 0.1285 - Val Acc: 0.9130
2026-04-05 05:32:06,952 - INFO - Epoch 60/100 - Train Loss: 0.1285 - Val Acc: 0.9130
2026-04-05 05:32:07,230 - INFO - Epoch 61/100 - Train Loss: 0.1287 - Val Acc: 0.9130
2026-04-05 05:32:07,503 - INFO - Epoch 62/100 - Train Loss: 0.1277 - Val Acc: 0.9130
2026-04-05 05:32:07,776 - INFO - Epoch 63/100 - Train Loss: 0.1271 - Val Acc: 0.9130
2026-04-05 05:32:08,046 - INFO - Epoch 64/100 - Train Loss: 0.1265 - Val Acc: 0.9130
2026-04-05 05:32:08,322 - INFO - Epoch 65/100 - Train Loss: 0.1220 - Val Acc: 0.9130
2026-04-05 05:32:08,589 - INFO - Epoch 66/100 - Train Loss: 0.1246 - Val Acc: 0.9130
2026-04-05 05:32:08,868 - INFO - Epoch 67/100 - Train Loss: 0.1243 - Val Acc: 0.9130
2026-04-05 05:32:09,148 - INFO - Epoch 68/100 - Train Loss: 0.1224 - Val Acc: 0.9130
2026-04-05 05:32:09,428 - INFO - Epoch 69/100 - Train Loss: 0.1185 - Val Acc: 0.9130
2026-04-05 05:32:09,694 - INFO - Epoch 70/100 - Train Loss: 0.1205 - Val Acc: 0.9130
2026-04-05 05:32:09,983 - INFO - Epoch 71/100 - Train Loss: 0.1194 - Val Acc: 0.9130
2026-04-05 05:32:10,268 - INFO - Epoch 72/100 - Train Loss: 0.1195 - Val Acc: 0.9130
2026-04-05 05:32:10,530 - INFO - Epoch 73/100 - Train Loss: 0.1169 - Val Acc: 0.9130
2026-04-05 05:32:10,799 - INFO - Epoch 74/100 - Train Loss: 0.1160 - Val Acc: 0.9130
2026-04-05 05:32:11,066 - INFO - Epoch 75/100 - Train Loss: 0.1151 - Val Acc: 0.9130
2026-04-05 05:32:11,334 - INFO - Epoch 76/100 - Train Loss: 0.1158 - Val Acc: 0.9130
2026-04-05 05:32:11,612 - INFO - Epoch 77/100 - Train Loss: 0.1155 - Val Acc: 0.9130
2026-04-05 05:32:11,897 - INFO - Epoch 78/100 - Train Loss: 0.1133 - Val Acc: 0.9130
2026-04-05 05:32:12,169 - INFO - Epoch 79/100 - Train Loss: 0.1126 - Val Acc: 0.9130
2026-04-05 05:32:12,447 - INFO - Epoch 80/100 - Train Loss: 0.1125 - Val Acc: 0.9130
2026-04-05 05:32:12,725 - INFO - Epoch 81/100 - Train Loss: 0.1147 - Val Acc: 0.9130
2026-04-05 05:32:13,008 - INFO - Epoch 82/100 - Train Loss: 0.1137 - Val Acc: 0.9130
2026-04-05 05:32:13,290 - INFO - Epoch 83/100 - Train Loss: 0.1130 - Val Acc: 0.9130
2026-04-05 05:32:13,570 - INFO - Epoch 84/100 - Train Loss: 0.1131 - Val Acc: 0.9130
2026-04-05 05:32:13,835 - INFO - Epoch 85/100 - Train Loss: 0.1104 - Val Acc: 0.9130
2026-04-05 05:32:14,098 - INFO - Epoch 86/100 - Train Loss: 0.1090 - Val Acc: 0.9130
2026-04-05 05:32:14,381 - INFO - Epoch 87/100 - Train Loss: 0.1125 - Val Acc: 0.9130
2026-04-05 05:32:14,676 - INFO - Epoch 88/100 - Train Loss: 0.1085 - Val Acc: 0.9130
2026-04-05 05:32:14,960 - INFO - Epoch 89/100 - Train Loss: 0.1092 - Val Acc: 0.9130
2026-04-05 05:32:15,227 - INFO - Epoch 90/100 - Train Loss: 0.1092 - Val Acc: 0.9130
2026-04-05 05:32:15,490 - INFO - Epoch 91/100 - Train Loss: 0.1062 - Val Acc: 0.9130
2026-04-05 05:32:15,765 - INFO - Epoch 92/100 - Train Loss: 0.1061 - Val Acc: 0.9130
2026-04-05 05:32:16,044 - INFO - Epoch 93/100 - Train Loss: 0.1048 - Val Acc: 0.9130
2026-04-05 05:32:16,310 - INFO - Epoch 94/100 - Train Loss: 0.1041 - Val Acc: 0.9130
2026-04-05 05:32:16,591 - INFO - Epoch 95/100 - Train Loss: 0.1054 - Val Acc: 0.9130
2026-04-05 05:32:16,858 - INFO - Epoch 96/100 - Train Loss: 0.1063 - Val Acc: 0.9130
2026-04-05 05:32:17,124 - INFO - Epoch 97/100 - Train Loss: 0.1040 - Val Acc: 0.9130
2026-04-05 05:32:17,400 - INFO - Epoch 98/100 - Train Loss: 0.1038 - Val Acc: 0.9130
2026-04-05 05:32:17,667 - INFO - Epoch 99/100 - Train Loss: 0.1043 - Val Acc: 0.9130
2026-04-05 05:32:17,932 - INFO - Epoch 100/100 - Train Loss: 0.1041 - Val Acc: 0.9130
2026-04-05 05:32:18,276 - INFO - Fold 3 logically complete. Tensor memory bounds cleared cleanly.
2026-04-05 05:32:18,281 - INFO - Original class distribution: [276 345]
2026-04-05 05:32:18,281 - INFO - Training device bound securely to: cuda
2026-04-05 05:32:18,299 - INFO - After SMOTE-ENN deployment: [345 296]

Fold 4:   0%|          | 0/100 [00:00<?, ?it/s]

2026-04-05 05:32:18,616 - INFO - Epoch 1/100 - Train Loss: 0.5240 - Val Acc: 0.7391
2026-04-05 05:32:18,913 - INFO - Epoch 2/100 - Train Loss: 0.3264 - Val Acc: 0.7681
2026-04-05 05:32:19,181 - INFO - Epoch 3/100 - Train Loss: 0.2640 - Val Acc: 0.7391
2026-04-05 05:32:19,454 - INFO - Epoch 4/100 - Train Loss: 0.2438 - Val Acc: 0.7391
2026-04-05 05:32:19,735 - INFO - Epoch 5/100 - Train Loss: 0.2240 - Val Acc: 0.7826
2026-04-05 05:32:20,009 - INFO - Epoch 6/100 - Train Loss: 0.2077 - Val Acc: 0.7536
2026-04-05 05:32:20,280 - INFO - Epoch 7/100 - Train Loss: 0.1952 - Val Acc: 0.7536
2026-04-05 05:32:20,558 - INFO - Epoch 8/100 - Train Loss: 0.1876 - Val Acc: 0.7681
2026-04-05 05:32:20,835 - INFO - Epoch 9/100 - Train Loss: 0.1814 - Val Acc: 0.7826
2026-04-05 05:32:21,113 - INFO - Epoch 10/100 - Train Loss: 0.1732 - Val Acc: 0.7826
2026-04-05 05:32:21,390 - INFO - Epoch 11/100 - Train Loss: 0.1676 - Val Acc: 0.7971
2026-04-05 05:32:21,660 - INFO - Epoch 12/100 - Train Loss: 0.1641 - Val Acc: 0.7971
2026-04-05 05:32:21,937 - INFO - Epoch 13/100 - Train Loss: 0.1616 - Val Acc: 0.7971
2026-04-05 05:32:22,209 - INFO - Epoch 14/100 - Train Loss: 0.1596 - Val Acc: 0.7971
2026-04-05 05:32:22,498 - INFO - Epoch 15/100 - Train Loss: 0.1551 - Val Acc: 0.7971
2026-04-05 05:32:22,796 - INFO - Epoch 16/100 - Train Loss: 0.1527 - Val Acc: 0.7971
2026-04-05 05:32:23,087 - INFO - Epoch 17/100 - Train Loss: 0.1536 - Val Acc: 0.7826
2026-04-05 05:32:23,365 - INFO - Epoch 18/100 - Train Loss: 0.1524 - Val Acc: 0.7826
2026-04-05 05:32:23,631 - INFO - Epoch 19/100 - Train Loss: 0.1500 - Val Acc: 0.7826
2026-04-05 05:32:23,912 - INFO - Epoch 20/100 - Train Loss: 0.1485 - Val Acc: 0.8116
2026-04-05 05:32:24,191 - INFO - Epoch 21/100 - Train Loss: 0.1476 - Val Acc: 0.7971
2026-04-05 05:32:24,467 - INFO - Epoch 22/100 - Train Loss: 0.1478 - Val Acc: 0.7971
2026-04-05 05:32:24,762 - INFO - Epoch 23/100 - Train Loss: 0.1447 - Val Acc: 0.7971
2026-04-05 05:32:25,049 - INFO - Epoch 24/100 - Train Loss: 0.1449 - Val Acc: 0.8116
2026-04-05 05:32:25,331 - INFO - Epoch 25/100 - Train Loss: 0.1429 - Val Acc: 0.7971
2026-04-05 05:32:25,610 - INFO - Epoch 26/100 - Train Loss: 0.1461 - Val Acc: 0.8116
2026-04-05 05:32:25,879 - INFO - Epoch 27/100 - Train Loss: 0.1434 - Val Acc: 0.8116
2026-04-05 05:32:26,147 - INFO - Epoch 28/100 - Train Loss: 0.1404 - Val Acc: 0.8116
2026-04-05 05:32:26,416 - INFO - Epoch 29/100 - Train Loss: 0.1383 - Val Acc: 0.7971
2026-04-05 05:32:26,689 - INFO - Epoch 30/100 - Train Loss: 0.1376 - Val Acc: 0.7971
2026-04-05 05:32:26,958 - INFO - Epoch 31/100 - Train Loss: 0.1368 - Val Acc: 0.7971
2026-04-05 05:32:27,228 - INFO - Epoch 32/100 - Train Loss: 0.1385 - Val Acc: 0.7971
2026-04-05 05:32:27,523 - INFO - Epoch 33/100 - Train Loss: 0.1371 - Val Acc: 0.7971
2026-04-05 05:32:27,809 - INFO - Epoch 34/100 - Train Loss: 0.1364 - Val Acc: 0.7971
2026-04-05 05:32:28,082 - INFO - Epoch 35/100 - Train Loss: 0.1366 - Val Acc: 0.7971
2026-04-05 05:32:28,357 - INFO - Epoch 36/100 - Train Loss: 0.1346 - Val Acc: 0.7971
2026-04-05 05:32:28,637 - INFO - Epoch 37/100 - Train Loss: 0.1322 - Val Acc: 0.7971
2026-04-05 05:32:28,921 - INFO - Epoch 38/100 - Train Loss: 0.1337 - Val Acc: 0.7971
2026-04-05 05:32:29,196 - INFO - Epoch 39/100 - Train Loss: 0.1340 - Val Acc: 0.7971
2026-04-05 05:32:29,466 - INFO - Epoch 40/100 - Train Loss: 0.1317 - Val Acc: 0.7971
2026-04-05 05:32:29,730 - INFO - Epoch 41/100 - Train Loss: 0.1325 - Val Acc: 0.7971
2026-04-05 05:32:29,999 - INFO - Epoch 42/100 - Train Loss: 0.1310 - Val Acc: 0.7971
2026-04-05 05:32:30,272 - INFO - Epoch 43/100 - Train Loss: 0.1304 - Val Acc: 0.7971
2026-04-05 05:32:30,549 - INFO - Epoch 44/100 - Train Loss: 0.1302 - Val Acc: 0.7971
2026-04-05 05:32:30,824 - INFO - Epoch 45/100 - Train Loss: 0.1282 - Val Acc: 0.7971
2026-04-05 05:32:31,088 - INFO - Epoch 46/100 - Train Loss: 0.1275 - Val Acc: 0.7971
2026-04-05 05:32:31,354 - INFO - Epoch 47/100 - Train Loss: 0.1254 - Val Acc: 0.7971
2026-04-05 05:32:31,633 - INFO - Epoch 48/100 - Train Loss: 0.1265 - Val Acc: 0.7971
2026-04-05 05:32:31,914 - INFO - Epoch 49/100 - Train Loss: 0.1241 - Val Acc: 0.7971
2026-04-05 05:32:32,189 - INFO - Epoch 50/100 - Train Loss: 0.1255 - Val Acc: 0.7971
2026-04-05 05:32:32,463 - INFO - Epoch 51/100 - Train Loss: 0.1242 - Val Acc: 0.7826
2026-04-05 05:32:32,738 - INFO - Epoch 52/100 - Train Loss: 0.1274 - Val Acc: 0.7826
2026-04-05 05:32:33,010 - INFO - Epoch 53/100 - Train Loss: 0.1239 - Val Acc: 0.7826
2026-04-05 05:32:33,291 - INFO - Epoch 54/100 - Train Loss: 0.1193 - Val Acc: 0.7826
2026-04-05 05:32:33,570 - INFO - Epoch 55/100 - Train Loss: 0.1198 - Val Acc: 0.7826
2026-04-05 05:32:33,848 - INFO - Epoch 56/100 - Train Loss: 0.1230 - Val Acc: 0.7971
2026-04-05 05:32:34,118 - INFO - Epoch 57/100 - Train Loss: 0.1194 - Val Acc: 0.7971
2026-04-05 05:32:34,389 - INFO - Epoch 58/100 - Train Loss: 0.1184 - Val Acc: 0.7971
2026-04-05 05:32:34,695 - INFO - Epoch 59/100 - Train Loss: 0.1185 - Val Acc: 0.7971
2026-04-05 05:32:34,992 - INFO - Epoch 60/100 - Train Loss: 0.1171 - Val Acc: 0.7971
2026-04-05 05:32:35,264 - INFO - Epoch 61/100 - Train Loss: 0.1136 - Val Acc: 0.7971
2026-04-05 05:32:35,532 - INFO - Epoch 62/100 - Train Loss: 0.1160 - Val Acc: 0.7971
2026-04-05 05:32:35,796 - INFO - Epoch 63/100 - Train Loss: 0.1147 - Val Acc: 0.7826
2026-04-05 05:32:36,061 - INFO - Epoch 64/100 - Train Loss: 0.1158 - Val Acc: 0.7826
2026-04-05 05:32:36,345 - INFO - Epoch 65/100 - Train Loss: 0.1152 - Val Acc: 0.7826
2026-04-05 05:32:36,611 - INFO - Epoch 66/100 - Train Loss: 0.1129 - Val Acc: 0.7826
2026-04-05 05:32:36,911 - INFO - Epoch 67/100 - Train Loss: 0.1167 - Val Acc: 0.7826
2026-04-05 05:32:37,184 - INFO - Epoch 68/100 - Train Loss: 0.1108 - Val Acc: 0.7826
2026-04-05 05:32:37,465 - INFO - Epoch 69/100 - Train Loss: 0.1129 - Val Acc: 0.7826
2026-04-05 05:32:37,750 - INFO - Epoch 70/100 - Train Loss: 0.1075 - Val Acc: 0.7826
2026-04-05 05:32:38,041 - INFO - Epoch 71/100 - Train Loss: 0.1103 - Val Acc: 0.7826
2026-04-05 05:32:38,317 - INFO - Epoch 72/100 - Train Loss: 0.1101 - Val Acc: 0.7826
2026-04-05 05:32:38,598 - INFO - Epoch 73/100 - Train Loss: 0.1089 - Val Acc: 0.7826
2026-04-05 05:32:38,878 - INFO - Epoch 74/100 - Train Loss: 0.1071 - Val Acc: 0.7826
2026-04-05 05:32:39,156 - INFO - Epoch 75/100 - Train Loss: 0.1076 - Val Acc: 0.7826
2026-04-05 05:32:39,427 - INFO - Epoch 76/100 - Train Loss: 0.1067 - Val Acc: 0.7971
2026-04-05 05:32:39,721 - INFO - Epoch 77/100 - Train Loss: 0.1069 - Val Acc: 0.7971
2026-04-05 05:32:40,010 - INFO - Epoch 78/100 - Train Loss: 0.1056 - Val Acc: 0.7971
2026-04-05 05:32:40,307 - INFO - Epoch 79/100 - Train Loss: 0.1061 - Val Acc: 0.7971
2026-04-05 05:32:40,583 - INFO - Epoch 80/100 - Train Loss: 0.1028 - Val Acc: 0.7971
2026-04-05 05:32:40,858 - INFO - Epoch 81/100 - Train Loss: 0.1059 - Val Acc: 0.7971
2026-04-05 05:32:41,136 - INFO - Epoch 82/100 - Train Loss: 0.1017 - Val Acc: 0.7826
2026-04-05 05:32:41,416 - INFO - Epoch 83/100 - Train Loss: 0.1045 - Val Acc: 0.8116
2026-04-05 05:32:41,691 - INFO - Epoch 84/100 - Train Loss: 0.1026 - Val Acc: 0.7971
2026-04-05 05:32:41,961 - INFO - Epoch 85/100 - Train Loss: 0.1028 - Val Acc: 0.7971
2026-04-05 05:32:42,249 - INFO - Epoch 86/100 - Train Loss: 0.1010 - Val Acc: 0.7971
2026-04-05 05:32:42,529 - INFO - Epoch 87/100 - Train Loss: 0.0976 - Val Acc: 0.7826
2026-04-05 05:32:42,823 - INFO - Epoch 88/100 - Train Loss: 0.0991 - Val Acc: 0.7826
2026-04-05 05:32:43,101 - INFO - Epoch 89/100 - Train Loss: 0.1002 - Val Acc: 0.7681
2026-04-05 05:32:43,385 - INFO - Epoch 90/100 - Train Loss: 0.0985 - Val Acc: 0.7681
2026-04-05 05:32:43,669 - INFO - Epoch 91/100 - Train Loss: 0.0973 - Val Acc: 0.7681
2026-04-05 05:32:43,958 - INFO - Epoch 92/100 - Train Loss: 0.0967 - Val Acc: 0.7826
2026-04-05 05:32:44,238 - INFO - Epoch 93/100 - Train Loss: 0.0978 - Val Acc: 0.7826
2026-04-05 05:32:44,526 - INFO - Epoch 94/100 - Train Loss: 0.0966 - Val Acc: 0.7826
2026-04-05 05:32:44,830 - INFO - Epoch 95/100 - Train Loss: 0.0992 - Val Acc: 0.7826
2026-04-05 05:32:45,110 - INFO - Epoch 96/100 - Train Loss: 0.0947 - Val Acc: 0.7971
2026-04-05 05:32:45,387 - INFO - Epoch 97/100 - Train Loss: 0.0938 - Val Acc: 0.7826
2026-04-05 05:32:45,660 - INFO - Epoch 98/100 - Train Loss: 0.0964 - Val Acc: 0.7681
2026-04-05 05:32:45,939 - INFO - Epoch 99/100 - Train Loss: 0.0964 - Val Acc: 0.7681
2026-04-05 05:32:46,208 - INFO - Epoch 100/100 - Train Loss: 0.0932 - Val Acc: 0.7681
2026-04-05 05:32:46,562 - INFO - Fold 4 logically complete. Tensor memory bounds cleared cleanly.
2026-04-05 05:32:46,567 - INFO - Original class distribution: [276 345]
2026-04-05 05:32:46,567 - INFO - Training device bound securely to: cuda
2026-04-05 05:32:46,582 - INFO - After SMOTE-ENN deployment: [345 287]

Fold 5:   0%|          | 0/100 [00:00<?, ?it/s]

2026-04-05 05:32:46,880 - INFO - Epoch 1/100 - Train Loss: 0.5227 - Val Acc: 0.8261
2026-04-05 05:32:47,147 - INFO - Epoch 2/100 - Train Loss: 0.3324 - Val Acc: 0.8551
2026-04-05 05:32:47,422 - INFO - Epoch 3/100 - Train Loss: 0.2673 - Val Acc: 0.8406
2026-04-05 05:32:47,690 - INFO - Epoch 4/100 - Train Loss: 0.2336 - Val Acc: 0.8261
2026-04-05 05:32:47,972 - INFO - Epoch 5/100 - Train Loss: 0.2107 - Val Acc: 0.8116
2026-04-05 05:32:48,237 - INFO - Epoch 6/100 - Train Loss: 0.1952 - Val Acc: 0.8261
2026-04-05 05:32:48,511 - INFO - Epoch 7/100 - Train Loss: 0.1822 - Val Acc: 0.8406
2026-04-05 05:32:48,782 - INFO - Epoch 8/100 - Train Loss: 0.1734 - Val Acc: 0.8406
2026-04-05 05:32:49,057 - INFO - Epoch 9/100 - Train Loss: 0.1670 - Val Acc: 0.8406
2026-04-05 05:32:49,329 - INFO - Epoch 10/100 - Train Loss: 0.1614 - Val Acc: 0.8261
2026-04-05 05:32:49,602 - INFO - Epoch 11/100 - Train Loss: 0.1573 - Val Acc: 0.8261
2026-04-05 05:32:49,881 - INFO - Epoch 12/100 - Train Loss: 0.1535 - Val Acc: 0.8261
2026-04-05 05:32:50,143 - INFO - Epoch 13/100 - Train Loss: 0.1491 - Val Acc: 0.7971
2026-04-05 05:32:50,424 - INFO - Epoch 14/100 - Train Loss: 0.1466 - Val Acc: 0.8116
2026-04-05 05:32:50,699 - INFO - Epoch 15/100 - Train Loss: 0.1446 - Val Acc: 0.8116
2026-04-05 05:32:50,967 - INFO - Epoch 16/100 - Train Loss: 0.1445 - Val Acc: 0.7971
2026-04-05 05:32:51,242 - INFO - Epoch 17/100 - Train Loss: 0.1427 - Val Acc: 0.7971
2026-04-05 05:32:51,511 - INFO - Epoch 18/100 - Train Loss: 0.1378 - Val Acc: 0.7971
2026-04-05 05:32:51,787 - INFO - Epoch 19/100 - Train Loss: 0.1389 - Val Acc: 0.7826
2026-04-05 05:32:52,050 - INFO - Epoch 20/100 - Train Loss: 0.1328 - Val Acc: 0.7826
2026-04-05 05:32:52,321 - INFO - Epoch 21/100 - Train Loss: 0.1327 - Val Acc: 0.7826
2026-04-05 05:32:52,588 - INFO - Epoch 22/100 - Train Loss: 0.1306 - Val Acc: 0.7971
2026-04-05 05:32:52,845 - INFO - Epoch 23/100 - Train Loss: 0.1296 - Val Acc: 0.7971
2026-04-05 05:32:53,115 - INFO - Epoch 24/100 - Train Loss: 0.1286 - Val Acc: 0.7971
2026-04-05 05:32:53,382 - INFO - Epoch 25/100 - Train Loss: 0.1271 - Val Acc: 0.7971
2026-04-05 05:32:53,658 - INFO - Epoch 26/100 - Train Loss: 0.1266 - Val Acc: 0.7971
2026-04-05 05:32:53,935 - INFO - Epoch 27/100 - Train Loss: 0.1223 - Val Acc: 0.7971
2026-04-05 05:32:54,210 - INFO - Epoch 28/100 - Train Loss: 0.1260 - Val Acc: 0.7971
2026-04-05 05:32:54,507 - INFO - Epoch 29/100 - Train Loss: 0.1227 - Val Acc: 0.7971
2026-04-05 05:32:54,798 - INFO - Epoch 30/100 - Train Loss: 0.1204 - Val Acc: 0.7971
2026-04-05 05:32:55,071 - INFO - Epoch 31/100 - Train Loss: 0.1192 - Val Acc: 0.7971
2026-04-05 05:32:55,342 - INFO - Epoch 32/100 - Train Loss: 0.1189 - Val Acc: 0.7971
2026-04-05 05:32:55,618 - INFO - Epoch 33/100 - Train Loss: 0.1190 - Val Acc: 0.7971
2026-04-05 05:32:55,897 - INFO - Epoch 34/100 - Train Loss: 0.1185 - Val Acc: 0.7971
2026-04-05 05:32:56,167 - INFO - Epoch 35/100 - Train Loss: 0.1179 - Val Acc: 0.7971
2026-04-05 05:32:56,430 - INFO - Epoch 36/100 - Train Loss: 0.1142 - Val Acc: 0.7971
2026-04-05 05:32:56,701 - INFO - Epoch 37/100 - Train Loss: 0.1128 - Val Acc: 0.7971
2026-04-05 05:32:56,975 - INFO - Epoch 38/100 - Train Loss: 0.1133 - Val Acc: 0.7971
2026-04-05 05:32:57,250 - INFO - Epoch 39/100 - Train Loss: 0.1118 - Val Acc: 0.7971
2026-04-05 05:32:57,521 - INFO - Epoch 40/100 - Train Loss: 0.1116 - Val Acc: 0.7826
2026-04-05 05:32:57,792 - INFO - Epoch 41/100 - Train Loss: 0.1104 - Val Acc: 0.7971
2026-04-05 05:32:58,059 - INFO - Epoch 42/100 - Train Loss: 0.1106 - Val Acc: 0.7681
2026-04-05 05:32:58,321 - INFO - Epoch 43/100 - Train Loss: 0.1079 - Val Acc: 0.7826
2026-04-05 05:32:58,599 - INFO - Epoch 44/100 - Train Loss: 0.1075 - Val Acc: 0.7826
2026-04-05 05:32:58,864 - INFO - Epoch 45/100 - Train Loss: 0.1067 - Val Acc: 0.7971
2026-04-05 05:32:59,137 - INFO - Epoch 46/100 - Train Loss: 0.1089 - Val Acc: 0.8116
2026-04-05 05:32:59,414 - INFO - Epoch 47/100 - Train Loss: 0.1070 - Val Acc: 0.7971
2026-04-05 05:32:59,681 - INFO - Epoch 48/100 - Train Loss: 0.1043 - Val Acc: 0.8116
2026-04-05 05:32:59,958 - INFO - Epoch 49/100 - Train Loss: 0.1034 - Val Acc: 0.7971
2026-04-05 05:33:00,221 - INFO - Epoch 50/100 - Train Loss: 0.1052 - Val Acc: 0.7971
2026-04-05 05:33:00,500 - INFO - Epoch 51/100 - Train Loss: 0.1036 - Val Acc: 0.7971
2026-04-05 05:33:00,780 - INFO - Epoch 52/100 - Train Loss: 0.1019 - Val Acc: 0.7971
2026-04-05 05:33:01,056 - INFO - Epoch 53/100 - Train Loss: 0.1028 - Val Acc: 0.7971
2026-04-05 05:33:01,333 - INFO - Epoch 54/100 - Train Loss: 0.1002 - Val Acc: 0.7971
2026-04-05 05:33:01,621 - INFO - Epoch 55/100 - Train Loss: 0.0981 - Val Acc: 0.7971
2026-04-05 05:33:01,887 - INFO - Epoch 56/100 - Train Loss: 0.0986 - Val Acc: 0.7971
2026-04-05 05:33:02,167 - INFO - Epoch 57/100 - Train Loss: 0.0998 - Val Acc: 0.7971
2026-04-05 05:33:02,432 - INFO - Epoch 58/100 - Train Loss: 0.0973 - Val Acc: 0.7971
2026-04-05 05:33:02,706 - INFO - Epoch 59/100 - Train Loss: 0.0954 - Val Acc: 0.7971
2026-04-05 05:33:02,968 - INFO - Epoch 60/100 - Train Loss: 0.0961 - Val Acc: 0.7971
2026-04-05 05:33:03,230 - INFO - Epoch 61/100 - Train Loss: 0.0926 - Val Acc: 0.7971
2026-04-05 05:33:03,501 - INFO - Epoch 62/100 - Train Loss: 0.0924 - Val Acc: 0.7971
2026-04-05 05:33:03,770 - INFO - Epoch 63/100 - Train Loss: 0.0933 - Val Acc: 0.7971
2026-04-05 05:33:04,039 - INFO - Epoch 64/100 - Train Loss: 0.0948 - Val Acc: 0.7971
2026-04-05 05:33:04,303 - INFO - Epoch 65/100 - Train Loss: 0.0907 - Val Acc: 0.7971
2026-04-05 05:33:04,594 - INFO - Epoch 66/100 - Train Loss: 0.0892 - Val Acc: 0.7971
2026-04-05 05:33:04,862 - INFO - Epoch 67/100 - Train Loss: 0.0897 - Val Acc: 0.7971
2026-04-05 05:33:05,125 - INFO - Epoch 68/100 - Train Loss: 0.0890 - Val Acc: 0.7971
2026-04-05 05:33:05,388 - INFO - Epoch 69/100 - Train Loss: 0.0905 - Val Acc: 0.7971
2026-04-05 05:33:05,666 - INFO - Epoch 70/100 - Train Loss: 0.0890 - Val Acc: 0.7971
2026-04-05 05:33:05,936 - INFO - Epoch 71/100 - Train Loss: 0.0876 - Val Acc: 0.8116
2026-04-05 05:33:06,211 - INFO - Epoch 72/100 - Train Loss: 0.0871 - Val Acc: 0.8116
2026-04-05 05:33:06,480 - INFO - Epoch 73/100 - Train Loss: 0.0877 - Val Acc: 0.8116
2026-04-05 05:33:06,751 - INFO - Epoch 74/100 - Train Loss: 0.0849 - Val Acc: 0.8116
2026-04-05 05:33:07,026 - INFO - Epoch 75/100 - Train Loss: 0.0812 - Val Acc: 0.8116
2026-04-05 05:33:07,295 - INFO - Epoch 76/100 - Train Loss: 0.0860 - Val Acc: 0.7971
2026-04-05 05:33:07,569 - INFO - Epoch 77/100 - Train Loss: 0.0859 - Val Acc: 0.8116
2026-04-05 05:33:07,843 - INFO - Epoch 78/100 - Train Loss: 0.0807 - Val Acc: 0.8116
2026-04-05 05:33:08,108 - INFO - Epoch 79/100 - Train Loss: 0.0809 - Val Acc: 0.7971
2026-04-05 05:33:08,371 - INFO - Epoch 80/100 - Train Loss: 0.0819 - Val Acc: 0.8116
2026-04-05 05:33:08,639 - INFO - Epoch 81/100 - Train Loss: 0.0839 - Val Acc: 0.8116
2026-04-05 05:33:08,901 - INFO - Epoch 82/100 - Train Loss: 0.0829 - Val Acc: 0.8116
2026-04-05 05:33:09,166 - INFO - Epoch 83/100 - Train Loss: 0.0792 - Val Acc: 0.8116
2026-04-05 05:33:09,441 - INFO - Epoch 84/100 - Train Loss: 0.0788 - Val Acc: 0.8261
2026-04-05 05:33:09,714 - INFO - Epoch 85/100 - Train Loss: 0.0742 - Val Acc: 0.8116
2026-04-05 05:33:10,008 - INFO - Epoch 86/100 - Train Loss: 0.0805 - Val Acc: 0.8261
2026-04-05 05:33:10,293 - INFO - Epoch 87/100 - Train Loss: 0.0755 - Val Acc: 0.8261
2026-04-05 05:33:10,561 - INFO - Epoch 88/100 - Train Loss: 0.0770 - Val Acc: 0.8261
2026-04-05 05:33:10,827 - INFO - Epoch 89/100 - Train Loss: 0.0736 - Val Acc: 0.8261
2026-04-05 05:33:11,096 - INFO - Epoch 90/100 - Train Loss: 0.0801 - Val Acc: 0.8116
2026-04-05 05:33:11,362 - INFO - Epoch 91/100 - Train Loss: 0.0751 - Val Acc: 0.8116
2026-04-05 05:33:11,641 - INFO - Epoch 92/100 - Train Loss: 0.0739 - Val Acc: 0.8261
2026-04-05 05:33:11,919 - INFO - Epoch 93/100 - Train Loss: 0.0766 - Val Acc: 0.8116
2026-04-05 05:33:12,189 - INFO - Epoch 94/100 - Train Loss: 0.0760 - Val Acc: 0.8116
2026-04-05 05:33:12,464 - INFO - Epoch 95/100 - Train Loss: 0.0719 - Val Acc: 0.8261
2026-04-05 05:33:12,732 - INFO - Epoch 96/100 - Train Loss: 0.0748 - Val Acc: 0.8261
2026-04-05 05:33:13,032 - INFO - Epoch 97/100 - Train Loss: 0.0703 - Val Acc: 0.8261
2026-04-05 05:33:13,307 - INFO - Epoch 98/100 - Train Loss: 0.0765 - Val Acc: 0.8261
2026-04-05 05:33:13,594 - INFO - Epoch 99/100 - Train Loss: 0.0718 - Val Acc: 0.8261
2026-04-05 05:33:13,861 - INFO - Epoch 100/100 - Train Loss: 0.0688 - Val Acc: 0.8261
2026-04-05 05:33:14,218 - INFO - Fold 5 logically complete. Tensor memory bounds cleared cleanly.
2026-04-05 05:33:14,222 - INFO - Original class distribution: [276 345]
2026-04-05 05:33:14,223 - INFO - Training device bound securely to: cuda
2026-04-05 05:33:14,239 - INFO - After SMOTE-ENN deployment: [345 288]

Fold 6:   0%|          | 0/100 [00:00<?, ?it/s]

2026-04-05 05:33:14,561 - INFO - Epoch 1/100 - Train Loss: 0.5157 - Val Acc: 0.8696
2026-04-05 05:33:14,843 - INFO - Epoch 2/100 - Train Loss: 0.3386 - Val Acc: 0.8696
2026-04-05 05:33:15,142 - INFO - Epoch 3/100 - Train Loss: 0.2796 - Val Acc: 0.8696
2026-04-05 05:33:15,413 - INFO - Epoch 4/100 - Train Loss: 0.2502 - Val Acc: 0.8696
2026-04-05 05:33:15,685 - INFO - Epoch 5/100 - Train Loss: 0.2324 - Val Acc: 0.8551
2026-04-05 05:33:15,951 - INFO - Epoch 6/100 - Train Loss: 0.2185 - Val Acc: 0.8551
2026-04-05 05:33:16,215 - INFO - Epoch 7/100 - Train Loss: 0.2108 - Val Acc: 0.8841
2026-04-05 05:33:16,484 - INFO - Epoch 8/100 - Train Loss: 0.2024 - Val Acc: 0.8841
2026-04-05 05:33:16,751 - INFO - Epoch 9/100 - Train Loss: 0.1941 - Val Acc: 0.8986
2026-04-05 05:33:17,018 - INFO - Epoch 10/100 - Train Loss: 0.1912 - Val Acc: 0.8986
2026-04-05 05:33:17,291 - INFO - Epoch 11/100 - Train Loss: 0.1897 - Val Acc: 0.8986
2026-04-05 05:33:17,557 - INFO - Epoch 12/100 - Train Loss: 0.1838 - Val Acc: 0.9130
2026-04-05 05:33:17,822 - INFO - Epoch 13/100 - Train Loss: 0.1830 - Val Acc: 0.9130
2026-04-05 05:33:18,094 - INFO - Epoch 14/100 - Train Loss: 0.1799 - Val Acc: 0.9130
2026-04-05 05:33:18,366 - INFO - Epoch 15/100 - Train Loss: 0.1791 - Val Acc: 0.9130
2026-04-05 05:33:18,644 - INFO - Epoch 16/100 - Train Loss: 0.1753 - Val Acc: 0.9130
2026-04-05 05:33:18,908 - INFO - Epoch 17/100 - Train Loss: 0.1747 - Val Acc: 0.9130
2026-04-05 05:33:19,186 - INFO - Epoch 18/100 - Train Loss: 0.1736 - Val Acc: 0.9130
2026-04-05 05:33:19,459 - INFO - Epoch 19/100 - Train Loss: 0.1724 - Val Acc: 0.9130
2026-04-05 05:33:19,732 - INFO - Epoch 20/100 - Train Loss: 0.1707 - Val Acc: 0.9130
2026-04-05 05:33:20,006 - INFO - Epoch 21/100 - Train Loss: 0.1669 - Val Acc: 0.9130
2026-04-05 05:33:20,281 - INFO - Epoch 22/100 - Train Loss: 0.1683 - Val Acc: 0.8986
2026-04-05 05:33:20,558 - INFO - Epoch 23/100 - Train Loss: 0.1664 - Val Acc: 0.9130
2026-04-05 05:33:20,842 - INFO - Epoch 24/100 - Train Loss: 0.1645 - Val Acc: 0.8986
2026-04-05 05:33:21,112 - INFO - Epoch 25/100 - Train Loss: 0.1614 - Val Acc: 0.8986
2026-04-05 05:33:21,386 - INFO - Epoch 26/100 - Train Loss: 0.1583 - Val Acc: 0.9130
2026-04-05 05:33:21,658 - INFO - Epoch 27/100 - Train Loss: 0.1603 - Val Acc: 0.9130
2026-04-05 05:33:21,927 - INFO - Epoch 28/100 - Train Loss: 0.1582 - Val Acc: 0.9130
2026-04-05 05:33:22,189 - INFO - Epoch 29/100 - Train Loss: 0.1581 - Val Acc: 0.9130
2026-04-05 05:33:22,479 - INFO - Epoch 30/100 - Train Loss: 0.1564 - Val Acc: 0.9130
2026-04-05 05:33:22,754 - INFO - Epoch 31/100 - Train Loss: 0.1539 - Val Acc: 0.8986
2026-04-05 05:33:23,056 - INFO - Epoch 32/100 - Train Loss: 0.1549 - Val Acc: 0.8986
2026-04-05 05:33:23,359 - INFO - Epoch 33/100 - Train Loss: 0.1526 - Val Acc: 0.8986
2026-04-05 05:33:23,645 - INFO - Epoch 34/100 - Train Loss: 0.1526 - Val Acc: 0.8986
2026-04-05 05:33:23,915 - INFO - Epoch 35/100 - Train Loss: 0.1484 - Val Acc: 0.9130
2026-04-05 05:33:24,193 - INFO - Epoch 36/100 - Train Loss: 0.1514 - Val Acc: 0.8986
2026-04-05 05:33:24,462 - INFO - Epoch 37/100 - Train Loss: 0.1469 - Val Acc: 0.8986
2026-04-05 05:33:24,762 - INFO - Epoch 38/100 - Train Loss: 0.1482 - Val Acc: 0.8986
2026-04-05 05:33:25,033 - INFO - Epoch 39/100 - Train Loss: 0.1464 - Val Acc: 0.8986
2026-04-05 05:33:25,313 - INFO - Epoch 40/100 - Train Loss: 0.1477 - Val Acc: 0.8986
2026-04-05 05:33:25,592 - INFO - Epoch 41/100 - Train Loss: 0.1453 - Val Acc: 0.8986
2026-04-05 05:33:25,851 - INFO - Epoch 42/100 - Train Loss: 0.1427 - Val Acc: 0.8986
2026-04-05 05:33:26,137 - INFO - Epoch 43/100 - Train Loss: 0.1446 - Val Acc: 0.8986
2026-04-05 05:33:26,407 - INFO - Epoch 44/100 - Train Loss: 0.1420 - Val Acc: 0.9130
2026-04-05 05:33:26,689 - INFO - Epoch 45/100 - Train Loss: 0.1430 - Val Acc: 0.9130
2026-04-05 05:33:26,960 - INFO - Epoch 46/100 - Train Loss: 0.1419 - Val Acc: 0.9130
2026-04-05 05:33:27,231 - INFO - Epoch 47/100 - Train Loss: 0.1379 - Val Acc: 0.9130
2026-04-05 05:33:27,517 - INFO - Epoch 48/100 - Train Loss: 0.1376 - Val Acc: 0.8986
2026-04-05 05:33:27,797 - INFO - Epoch 49/100 - Train Loss: 0.1379 - Val Acc: 0.9130
2026-04-05 05:33:28,062 - INFO - Epoch 50/100 - Train Loss: 0.1363 - Val Acc: 0.8986
2026-04-05 05:33:28,336 - INFO - Epoch 51/100 - Train Loss: 0.1341 - Val Acc: 0.8841
2026-04-05 05:33:28,619 - INFO - Epoch 52/100 - Train Loss: 0.1359 - Val Acc: 0.9130
2026-04-05 05:33:28,889 - INFO - Epoch 53/100 - Train Loss: 0.1341 - Val Acc: 0.9130
2026-04-05 05:33:29,169 - INFO - Epoch 54/100 - Train Loss: 0.1343 - Val Acc: 0.9130
2026-04-05 05:33:29,435 - INFO - Epoch 55/100 - Train Loss: 0.1301 - Val Acc: 0.8986
2026-04-05 05:33:29,712 - INFO - Epoch 56/100 - Train Loss: 0.1324 - Val Acc: 0.8986
2026-04-05 05:33:29,998 - INFO - Epoch 57/100 - Train Loss: 0.1309 - Val Acc: 0.8986
2026-04-05 05:33:30,274 - INFO - Epoch 58/100 - Train Loss: 0.1300 - Val Acc: 0.8986
2026-04-05 05:33:30,544 - INFO - Epoch 59/100 - Train Loss: 0.1280 - Val Acc: 0.8986
2026-04-05 05:33:30,818 - INFO - Epoch 60/100 - Train Loss: 0.1314 - Val Acc: 0.8986
2026-04-05 05:33:31,086 - INFO - Epoch 61/100 - Train Loss: 0.1272 - Val Acc: 0.8841
2026-04-05 05:33:31,349 - INFO - Epoch 62/100 - Train Loss: 0.1274 - Val Acc: 0.8986
2026-04-05 05:33:31,624 - INFO - Epoch 63/100 - Train Loss: 0.1270 - Val Acc: 0.8986
2026-04-05 05:33:31,893 - INFO - Epoch 64/100 - Train Loss: 0.1245 - Val Acc: 0.8986
2026-04-05 05:33:32,167 - INFO - Epoch 65/100 - Train Loss: 0.1238 - Val Acc: 0.8841
2026-04-05 05:33:32,438 - INFO - Epoch 66/100 - Train Loss: 0.1226 - Val Acc: 0.8986
2026-04-05 05:33:32,701 - INFO - Epoch 67/100 - Train Loss: 0.1225 - Val Acc: 0.8841
2026-04-05 05:33:32,977 - INFO - Epoch 68/100 - Train Loss: 0.1225 - Val Acc: 0.8841
2026-04-05 05:33:33,242 - INFO - Epoch 69/100 - Train Loss: 0.1225 - Val Acc: 0.8841
2026-04-05 05:33:33,511 - INFO - Epoch 70/100 - Train Loss: 0.1200 - Val Acc: 0.8841
2026-04-05 05:33:33,787 - INFO - Epoch 71/100 - Train Loss: 0.1193 - Val Acc: 0.8841
2026-04-05 05:33:34,053 - INFO - Epoch 72/100 - Train Loss: 0.1214 - Val Acc: 0.8841
2026-04-05 05:33:34,339 - INFO - Epoch 73/100 - Train Loss: 0.1157 - Val Acc: 0.8841
2026-04-05 05:33:34,633 - INFO - Epoch 74/100 - Train Loss: 0.1211 - Val Acc: 0.8841
2026-04-05 05:33:34,898 - INFO - Epoch 75/100 - Train Loss: 0.1188 - Val Acc: 0.8841
2026-04-05 05:33:35,170 - INFO - Epoch 76/100 - Train Loss: 0.1204 - Val Acc: 0.8841
2026-04-05 05:33:35,447 - INFO - Epoch 77/100 - Train Loss: 0.1183 - Val Acc: 0.8841
2026-04-05 05:33:35,714 - INFO - Epoch 78/100 - Train Loss: 0.1161 - Val Acc: 0.8841
2026-04-05 05:33:35,975 - INFO - Epoch 79/100 - Train Loss: 0.1161 - Val Acc: 0.8841
2026-04-05 05:33:36,243 - INFO - Epoch 80/100 - Train Loss: 0.1168 - Val Acc: 0.8841
2026-04-05 05:33:36,513 - INFO - Epoch 81/100 - Train Loss: 0.1168 - Val Acc: 0.8841
2026-04-05 05:33:36,778 - INFO - Epoch 82/100 - Train Loss: 0.1161 - Val Acc: 0.8841
2026-04-05 05:33:37,054 - INFO - Epoch 83/100 - Train Loss: 0.1133 - Val Acc: 0.8841
2026-04-05 05:33:37,327 - INFO - Epoch 84/100 - Train Loss: 0.1122 - Val Acc: 0.8841
2026-04-05 05:33:37,598 - INFO - Epoch 85/100 - Train Loss: 0.1140 - Val Acc: 0.8841
2026-04-05 05:33:37,871 - INFO - Epoch 86/100 - Train Loss: 0.1101 - Val Acc: 0.8841
2026-04-05 05:33:38,142 - INFO - Epoch 87/100 - Train Loss: 0.1120 - Val Acc: 0.8841
2026-04-05 05:33:38,409 - INFO - Epoch 88/100 - Train Loss: 0.1095 - Val Acc: 0.8841
2026-04-05 05:33:38,679 - INFO - Epoch 89/100 - Train Loss: 0.1092 - Val Acc: 0.8841
2026-04-05 05:33:38,950 - INFO - Epoch 90/100 - Train Loss: 0.1081 - Val Acc: 0.8841
2026-04-05 05:33:39,211 - INFO - Epoch 91/100 - Train Loss: 0.1094 - Val Acc: 0.8841
2026-04-05 05:33:39,475 - INFO - Epoch 92/100 - Train Loss: 0.1086 - Val Acc: 0.8841
2026-04-05 05:33:39,737 - INFO - Epoch 93/100 - Train Loss: 0.1063 - Val Acc: 0.8696
2026-04-05 05:33:40,007 - INFO - Epoch 94/100 - Train Loss: 0.1096 - Val Acc: 0.8841
2026-04-05 05:33:40,269 - INFO - Epoch 95/100 - Train Loss: 0.1074 - Val Acc: 0.8841
2026-04-05 05:33:40,536 - INFO - Epoch 96/100 - Train Loss: 0.1032 - Val Acc: 0.8841
2026-04-05 05:33:40,814 - INFO - Epoch 97/100 - Train Loss: 0.1030 - Val Acc: 0.8841
2026-04-05 05:33:41,070 - INFO - Epoch 98/100 - Train Loss: 0.1015 - Val Acc: 0.8841
2026-04-05 05:33:41,348 - INFO - Epoch 99/100 - Train Loss: 0.0990 - Val Acc: 0.8841
2026-04-05 05:33:41,619 - INFO - Epoch 100/100 - Train Loss: 0.1036 - Val Acc: 0.8841
2026-04-05 05:33:41,971 - INFO - Fold 6 logically complete. Tensor memory bounds cleared cleanly.
2026-04-05 05:33:41,975 - INFO - Original class distribution: [276 345]
2026-04-05 05:33:41,976 - INFO - Training device bound securely to: cuda
2026-04-05 05:33:41,991 - INFO - After SMOTE-ENN deployment: [345 291]

Fold 7:   0%|          | 0/100 [00:00<?, ?it/s]

2026-04-05 05:33:42,273 - INFO - Epoch 1/100 - Train Loss: 0.5327 - Val Acc: 0.8116
2026-04-05 05:33:42,558 - INFO - Epoch 2/100 - Train Loss: 0.3384 - Val Acc: 0.7826
2026-04-05 05:33:42,824 - INFO - Epoch 3/100 - Train Loss: 0.2772 - Val Acc: 0.7826
2026-04-05 05:33:43,096 - INFO - Epoch 4/100 - Train Loss: 0.2434 - Val Acc: 0.8116
2026-04-05 05:33:43,363 - INFO - Epoch 5/100 - Train Loss: 0.2249 - Val Acc: 0.8116
2026-04-05 05:33:43,627 - INFO - Epoch 6/100 - Train Loss: 0.2100 - Val Acc: 0.8261
2026-04-05 05:33:43,908 - INFO - Epoch 7/100 - Train Loss: 0.1998 - Val Acc: 0.8261
2026-04-05 05:33:44,188 - INFO - Epoch 8/100 - Train Loss: 0.1905 - Val Acc: 0.8116
2026-04-05 05:33:44,451 - INFO - Epoch 9/100 - Train Loss: 0.1833 - Val Acc: 0.8116
2026-04-05 05:33:44,745 - INFO - Epoch 10/100 - Train Loss: 0.1784 - Val Acc: 0.8116
2026-04-05 05:33:45,015 - INFO - Epoch 11/100 - Train Loss: 0.1752 - Val Acc: 0.8116
2026-04-05 05:33:45,296 - INFO - Epoch 12/100 - Train Loss: 0.1728 - Val Acc: 0.8116
2026-04-05 05:33:45,569 - INFO - Epoch 13/100 - Train Loss: 0.1705 - Val Acc: 0.8116
2026-04-05 05:33:45,833 - INFO - Epoch 14/100 - Train Loss: 0.1691 - Val Acc: 0.7826
2026-04-05 05:33:46,117 - INFO - Epoch 15/100 - Train Loss: 0.1643 - Val Acc: 0.7826
2026-04-05 05:33:46,387 - INFO - Epoch 16/100 - Train Loss: 0.1622 - Val Acc: 0.7826
2026-04-05 05:33:46,657 - INFO - Epoch 17/100 - Train Loss: 0.1598 - Val Acc: 0.7826
2026-04-05 05:33:46,919 - INFO - Epoch 18/100 - Train Loss: 0.1601 - Val Acc: 0.7826
2026-04-05 05:33:47,178 - INFO - Epoch 19/100 - Train Loss: 0.1579 - Val Acc: 0.7826
2026-04-05 05:33:47,449 - INFO - Epoch 20/100 - Train Loss: 0.1563 - Val Acc: 0.7826
2026-04-05 05:33:47,727 - INFO - Epoch 21/100 - Train Loss: 0.1545 - Val Acc: 0.7826
2026-04-05 05:33:47,999 - INFO - Epoch 22/100 - Train Loss: 0.1536 - Val Acc: 0.7826
2026-04-05 05:33:48,268 - INFO - Epoch 23/100 - Train Loss: 0.1519 - Val Acc: 0.7826
2026-04-05 05:33:48,540 - INFO - Epoch 24/100 - Train Loss: 0.1491 - Val Acc: 0.7826
2026-04-05 05:33:48,807 - INFO - Epoch 25/100 - Train Loss: 0.1486 - Val Acc: 0.7826
2026-04-05 05:33:49,071 - INFO - Epoch 26/100 - Train Loss: 0.1458 - Val Acc: 0.7826
2026-04-05 05:33:49,339 - INFO - Epoch 27/100 - Train Loss: 0.1442 - Val Acc: 0.7826
2026-04-05 05:33:49,612 - INFO - Epoch 28/100 - Train Loss: 0.1423 - Val Acc: 0.7826
2026-04-05 05:33:49,890 - INFO - Epoch 29/100 - Train Loss: 0.1434 - Val Acc: 0.7826
2026-04-05 05:33:50,159 - INFO - Epoch 30/100 - Train Loss: 0.1399 - Val Acc: 0.7826
2026-04-05 05:33:50,430 - INFO - Epoch 31/100 - Train Loss: 0.1391 - Val Acc: 0.7681
2026-04-05 05:33:50,695 - INFO - Epoch 32/100 - Train Loss: 0.1393 - Val Acc: 0.7681
2026-04-05 05:33:50,965 - INFO - Epoch 33/100 - Train Loss: 0.1365 - Val Acc: 0.7681
2026-04-05 05:33:51,240 - INFO - Epoch 34/100 - Train Loss: 0.1378 - Val Acc: 0.7681
2026-04-05 05:33:51,508 - INFO - Epoch 35/100 - Train Loss: 0.1352 - Val Acc: 0.7681
2026-04-05 05:33:51,779 - INFO - Epoch 36/100 - Train Loss: 0.1341 - Val Acc: 0.7681
2026-04-05 05:33:52,045 - INFO - Epoch 37/100 - Train Loss: 0.1329 - Val Acc: 0.7681
2026-04-05 05:33:52,324 - INFO - Epoch 38/100 - Train Loss: 0.1304 - Val Acc: 0.7681
2026-04-05 05:33:52,586 - INFO - Epoch 39/100 - Train Loss: 0.1303 - Val Acc: 0.7681
2026-04-05 05:33:52,858 - INFO - Epoch 40/100 - Train Loss: 0.1297 - Val Acc: 0.7681
2026-04-05 05:33:53,135 - INFO - Epoch 41/100 - Train Loss: 0.1284 - Val Acc: 0.7681
2026-04-05 05:33:53,411 - INFO - Epoch 42/100 - Train Loss: 0.1275 - Val Acc: 0.7826
2026-04-05 05:33:53,700 - INFO - Epoch 43/100 - Train Loss: 0.1266 - Val Acc: 0.7826
2026-04-05 05:33:53,970 - INFO - Epoch 44/100 - Train Loss: 0.1278 - Val Acc: 0.7971
2026-04-05 05:33:54,253 - INFO - Epoch 45/100 - Train Loss: 0.1263 - Val Acc: 0.8116
2026-04-05 05:33:54,549 - INFO - Epoch 46/100 - Train Loss: 0.1239 - Val Acc: 0.8116
2026-04-05 05:33:54,836 - INFO - Epoch 47/100 - Train Loss: 0.1205 - Val Acc: 0.8116
2026-04-05 05:33:55,126 - INFO - Epoch 48/100 - Train Loss: 0.1204 - Val Acc: 0.8116
2026-04-05 05:33:55,408 - INFO - Epoch 49/100 - Train Loss: 0.1198 - Val Acc: 0.8116
2026-04-05 05:33:55,679 - INFO - Epoch 50/100 - Train Loss: 0.1190 - Val Acc: 0.8116
2026-04-05 05:33:55,962 - INFO - Epoch 51/100 - Train Loss: 0.1182 - Val Acc: 0.7971
2026-04-05 05:33:56,228 - INFO - Epoch 52/100 - Train Loss: 0.1162 - Val Acc: 0.8116
2026-04-05 05:33:56,496 - INFO - Epoch 53/100 - Train Loss: 0.1161 - Val Acc: 0.8116
2026-04-05 05:33:56,774 - INFO - Epoch 54/100 - Train Loss: 0.1152 - Val Acc: 0.8116
2026-04-05 05:33:57,050 - INFO - Epoch 55/100 - Train Loss: 0.1143 - Val Acc: 0.8116
2026-04-05 05:33:57,321 - INFO - Epoch 56/100 - Train Loss: 0.1159 - Val Acc: 0.8116
2026-04-05 05:33:57,592 - INFO - Epoch 57/100 - Train Loss: 0.1119 - Val Acc: 0.7971
2026-04-05 05:33:57,881 - INFO - Epoch 58/100 - Train Loss: 0.1139 - Val Acc: 0.7971
2026-04-05 05:33:58,146 - INFO - Epoch 59/100 - Train Loss: 0.1129 - Val Acc: 0.7971
2026-04-05 05:33:58,423 - INFO - Epoch 60/100 - Train Loss: 0.1082 - Val Acc: 0.7971
2026-04-05 05:33:58,706 - INFO - Epoch 61/100 - Train Loss: 0.1107 - Val Acc: 0.7826
2026-04-05 05:33:58,982 - INFO - Epoch 62/100 - Train Loss: 0.1087 - Val Acc: 0.7826
2026-04-05 05:33:59,253 - INFO - Epoch 63/100 - Train Loss: 0.1074 - Val Acc: 0.7826
2026-04-05 05:33:59,522 - INFO - Epoch 64/100 - Train Loss: 0.1042 - Val Acc: 0.7826
2026-04-05 05:33:59,789 - INFO - Epoch 65/100 - Train Loss: 0.1057 - Val Acc: 0.7826
2026-04-05 05:34:00,054 - INFO - Epoch 66/100 - Train Loss: 0.1072 - Val Acc: 0.7826
2026-04-05 05:34:00,322 - INFO - Epoch 67/100 - Train Loss: 0.1034 - Val Acc: 0.7826
2026-04-05 05:34:00,595 - INFO - Epoch 68/100 - Train Loss: 0.1034 - Val Acc: 0.7826
2026-04-05 05:34:00,858 - INFO - Epoch 69/100 - Train Loss: 0.1022 - Val Acc: 0.7826
2026-04-05 05:34:01,132 - INFO - Epoch 70/100 - Train Loss: 0.1034 - Val Acc: 0.7826
2026-04-05 05:34:01,400 - INFO - Epoch 71/100 - Train Loss: 0.1032 - Val Acc: 0.7826
2026-04-05 05:34:01,678 - INFO - Epoch 72/100 - Train Loss: 0.1006 - Val Acc: 0.7826
2026-04-05 05:34:01,952 - INFO - Epoch 73/100 - Train Loss: 0.0995 - Val Acc: 0.7681
2026-04-05 05:34:02,224 - INFO - Epoch 74/100 - Train Loss: 0.1028 - Val Acc: 0.7681
2026-04-05 05:34:02,482 - INFO - Epoch 75/100 - Train Loss: 0.0974 - Val Acc: 0.7681
2026-04-05 05:34:02,761 - INFO - Epoch 76/100 - Train Loss: 0.0983 - Val Acc: 0.7681
2026-04-05 05:34:03,020 - INFO - Epoch 77/100 - Train Loss: 0.0978 - Val Acc: 0.7826
2026-04-05 05:34:03,299 - INFO - Epoch 78/100 - Train Loss: 0.0983 - Val Acc: 0.7826
2026-04-05 05:34:03,569 - INFO - Epoch 79/100 - Train Loss: 0.0966 - Val Acc: 0.7826
2026-04-05 05:34:03,835 - INFO - Epoch 80/100 - Train Loss: 0.0972 - Val Acc: 0.7681
2026-04-05 05:34:04,105 - INFO - Epoch 81/100 - Train Loss: 0.0906 - Val Acc: 0.7681
2026-04-05 05:34:04,378 - INFO - Epoch 82/100 - Train Loss: 0.0965 - Val Acc: 0.7681
2026-04-05 05:34:04,674 - INFO - Epoch 83/100 - Train Loss: 0.0964 - Val Acc: 0.7681
2026-04-05 05:34:04,952 - INFO - Epoch 84/100 - Train Loss: 0.0934 - Val Acc: 0.7681
2026-04-05 05:34:05,219 - INFO - Epoch 85/100 - Train Loss: 0.0954 - Val Acc: 0.7681
2026-04-05 05:34:05,483 - INFO - Epoch 86/100 - Train Loss: 0.0962 - Val Acc: 0.7681
2026-04-05 05:34:05,760 - INFO - Epoch 87/100 - Train Loss: 0.0930 - Val Acc: 0.7681
2026-04-05 05:34:06,033 - INFO - Epoch 88/100 - Train Loss: 0.0939 - Val Acc: 0.7681
2026-04-05 05:34:06,309 - INFO - Epoch 89/100 - Train Loss: 0.0922 - Val Acc: 0.7681
2026-04-05 05:34:06,571 - INFO - Epoch 90/100 - Train Loss: 0.0935 - Val Acc: 0.7681
2026-04-05 05:34:06,841 - INFO - Epoch 91/100 - Train Loss: 0.0912 - Val Acc: 0.7681
2026-04-05 05:34:07,110 - INFO - Epoch 92/100 - Train Loss: 0.0900 - Val Acc: 0.7681
2026-04-05 05:34:07,372 - INFO - Epoch 93/100 - Train Loss: 0.0899 - Val Acc: 0.7681
2026-04-05 05:34:07,646 - INFO - Epoch 94/100 - Train Loss: 0.0884 - Val Acc: 0.7681
2026-04-05 05:34:07,911 - INFO - Epoch 95/100 - Train Loss: 0.0931 - Val Acc: 0.7681
2026-04-05 05:34:08,174 - INFO - Epoch 96/100 - Train Loss: 0.0909 - Val Acc: 0.7681
2026-04-05 05:34:08,462 - INFO - Epoch 97/100 - Train Loss: 0.0861 - Val Acc: 0.7681
2026-04-05 05:34:08,736 - INFO - Epoch 98/100 - Train Loss: 0.0891 - Val Acc: 0.7681
2026-04-05 05:34:09,008 - INFO - Epoch 99/100 - Train Loss: 0.0874 - Val Acc: 0.7681
2026-04-05 05:34:09,275 - INFO - Epoch 100/100 - Train Loss: 0.0849 - Val Acc: 0.7681
2026-04-05 05:34:09,636 - INFO - Fold 7 logically complete. Tensor memory bounds cleared cleanly.
2026-04-05 05:34:09,640 - INFO - Original class distribution: [276 345]
2026-04-05 05:34:09,641 - INFO - Training device bound securely to: cuda
2026-04-05 05:34:09,657 - INFO - After SMOTE-ENN deployment: [345 289]

Fold 8:   0%|          | 0/100 [00:00<?, ?it/s]

2026-04-05 05:34:09,959 - INFO - Epoch 1/100 - Train Loss: 0.5436 - Val Acc: 0.8261
2026-04-05 05:34:10,242 - INFO - Epoch 2/100 - Train Loss: 0.3578 - Val Acc: 0.8261
2026-04-05 05:34:10,516 - INFO - Epoch 3/100 - Train Loss: 0.2926 - Val Acc: 0.8116
2026-04-05 05:34:10,796 - INFO - Epoch 4/100 - Train Loss: 0.2613 - Val Acc: 0.7971
2026-04-05 05:34:11,063 - INFO - Epoch 5/100 - Train Loss: 0.2388 - Val Acc: 0.8406
2026-04-05 05:34:11,334 - INFO - Epoch 6/100 - Train Loss: 0.2236 - Val Acc: 0.8406
2026-04-05 05:34:11,598 - INFO - Epoch 7/100 - Train Loss: 0.2103 - Val Acc: 0.8551
2026-04-05 05:34:11,871 - INFO - Epoch 8/100 - Train Loss: 0.2040 - Val Acc: 0.8551
2026-04-05 05:34:12,135 - INFO - Epoch 9/100 - Train Loss: 0.1943 - Val Acc: 0.8551
2026-04-05 05:34:12,408 - INFO - Epoch 10/100 - Train Loss: 0.1923 - Val Acc: 0.8551
2026-04-05 05:34:12,683 - INFO - Epoch 11/100 - Train Loss: 0.1875 - Val Acc: 0.8551
2026-04-05 05:34:12,959 - INFO - Epoch 12/100 - Train Loss: 0.1830 - Val Acc: 0.8551
2026-04-05 05:34:13,217 - INFO - Epoch 13/100 - Train Loss: 0.1808 - Val Acc: 0.8551
2026-04-05 05:34:13,489 - INFO - Epoch 14/100 - Train Loss: 0.1791 - Val Acc: 0.8551
2026-04-05 05:34:13,757 - INFO - Epoch 15/100 - Train Loss: 0.1777 - Val Acc: 0.8551
2026-04-05 05:34:14,031 - INFO - Epoch 16/100 - Train Loss: 0.1747 - Val Acc: 0.8551
2026-04-05 05:34:14,308 - INFO - Epoch 17/100 - Train Loss: 0.1723 - Val Acc: 0.8551
2026-04-05 05:34:14,604 - INFO - Epoch 18/100 - Train Loss: 0.1706 - Val Acc: 0.8551
2026-04-05 05:34:14,873 - INFO - Epoch 19/100 - Train Loss: 0.1704 - Val Acc: 0.8551
2026-04-05 05:34:15,145 - INFO - Epoch 20/100 - Train Loss: 0.1689 - Val Acc: 0.8551
2026-04-05 05:34:15,431 - INFO - Epoch 21/100 - Train Loss: 0.1686 - Val Acc: 0.8551
2026-04-05 05:34:15,701 - INFO - Epoch 22/100 - Train Loss: 0.1655 - Val Acc: 0.8551
2026-04-05 05:34:15,978 - INFO - Epoch 23/100 - Train Loss: 0.1645 - Val Acc: 0.8551
2026-04-05 05:34:16,245 - INFO - Epoch 24/100 - Train Loss: 0.1638 - Val Acc: 0.8551
2026-04-05 05:34:16,517 - INFO - Epoch 25/100 - Train Loss: 0.1596 - Val Acc: 0.8551
2026-04-05 05:34:16,797 - INFO - Epoch 26/100 - Train Loss: 0.1585 - Val Acc: 0.8551
2026-04-05 05:34:17,071 - INFO - Epoch 27/100 - Train Loss: 0.1569 - Val Acc: 0.8551
2026-04-05 05:34:17,349 - INFO - Epoch 28/100 - Train Loss: 0.1551 - Val Acc: 0.8551
2026-04-05 05:34:17,615 - INFO - Epoch 29/100 - Train Loss: 0.1571 - Val Acc: 0.8551
2026-04-05 05:34:17,888 - INFO - Epoch 30/100 - Train Loss: 0.1524 - Val Acc: 0.8551
2026-04-05 05:34:18,160 - INFO - Epoch 31/100 - Train Loss: 0.1524 - Val Acc: 0.8551
2026-04-05 05:34:18,443 - INFO - Epoch 32/100 - Train Loss: 0.1521 - Val Acc: 0.8551
2026-04-05 05:34:18,715 - INFO - Epoch 33/100 - Train Loss: 0.1485 - Val Acc: 0.8551
2026-04-05 05:34:18,991 - INFO - Epoch 34/100 - Train Loss: 0.1504 - Val Acc: 0.8551
2026-04-05 05:34:19,269 - INFO - Epoch 35/100 - Train Loss: 0.1484 - Val Acc: 0.8551
2026-04-05 05:34:19,546 - INFO - Epoch 36/100 - Train Loss: 0.1482 - Val Acc: 0.8551
2026-04-05 05:34:19,812 - INFO - Epoch 37/100 - Train Loss: 0.1461 - Val Acc: 0.8551
2026-04-05 05:34:20,069 - INFO - Epoch 38/100 - Train Loss: 0.1440 - Val Acc: 0.8551
2026-04-05 05:34:20,342 - INFO - Epoch 39/100 - Train Loss: 0.1442 - Val Acc: 0.8551
2026-04-05 05:34:20,615 - INFO - Epoch 40/100 - Train Loss: 0.1411 - Val Acc: 0.8551
2026-04-05 05:34:20,874 - INFO - Epoch 41/100 - Train Loss: 0.1403 - Val Acc: 0.8551
2026-04-05 05:34:21,147 - INFO - Epoch 42/100 - Train Loss: 0.1406 - Val Acc: 0.8551
2026-04-05 05:34:21,408 - INFO - Epoch 43/100 - Train Loss: 0.1404 - Val Acc: 0.8551
2026-04-05 05:34:21,684 - INFO - Epoch 44/100 - Train Loss: 0.1369 - Val Acc: 0.8551
2026-04-05 05:34:21,956 - INFO - Epoch 45/100 - Train Loss: 0.1355 - Val Acc: 0.8551
2026-04-05 05:34:22,233 - INFO - Epoch 46/100 - Train Loss: 0.1363 - Val Acc: 0.8551
2026-04-05 05:34:22,505 - INFO - Epoch 47/100 - Train Loss: 0.1370 - Val Acc: 0.8551
2026-04-05 05:34:22,770 - INFO - Epoch 48/100 - Train Loss: 0.1345 - Val Acc: 0.8551
2026-04-05 05:34:23,045 - INFO - Epoch 49/100 - Train Loss: 0.1316 - Val Acc: 0.8551
2026-04-05 05:34:23,326 - INFO - Epoch 50/100 - Train Loss: 0.1335 - Val Acc: 0.8551
2026-04-05 05:34:23,604 - INFO - Epoch 51/100 - Train Loss: 0.1309 - Val Acc: 0.8551
2026-04-05 05:34:23,875 - INFO - Epoch 52/100 - Train Loss: 0.1288 - Val Acc: 0.8551
2026-04-05 05:34:24,146 - INFO - Epoch 53/100 - Train Loss: 0.1280 - Val Acc: 0.8551
2026-04-05 05:34:24,411 - INFO - Epoch 54/100 - Train Loss: 0.1321 - Val Acc: 0.8551
2026-04-05 05:34:24,713 - INFO - Epoch 55/100 - Train Loss: 0.1296 - Val Acc: 0.8551
2026-04-05 05:34:24,991 - INFO - Epoch 56/100 - Train Loss: 0.1259 - Val Acc: 0.8551
2026-04-05 05:34:25,263 - INFO - Epoch 57/100 - Train Loss: 0.1261 - Val Acc: 0.8551
2026-04-05 05:34:25,532 - INFO - Epoch 58/100 - Train Loss: 0.1244 - Val Acc: 0.8551
2026-04-05 05:34:25,795 - INFO - Epoch 59/100 - Train Loss: 0.1230 - Val Acc: 0.8551
2026-04-05 05:34:26,055 - INFO - Epoch 60/100 - Train Loss: 0.1225 - Val Acc: 0.8551
2026-04-05 05:34:26,336 - INFO - Epoch 61/100 - Train Loss: 0.1190 - Val Acc: 0.8551
2026-04-05 05:34:26,604 - INFO - Epoch 62/100 - Train Loss: 0.1202 - Val Acc: 0.8551
2026-04-05 05:34:26,883 - INFO - Epoch 63/100 - Train Loss: 0.1213 - Val Acc: 0.8551
2026-04-05 05:34:27,155 - INFO - Epoch 64/100 - Train Loss: 0.1209 - Val Acc: 0.8551
2026-04-05 05:34:27,423 - INFO - Epoch 65/100 - Train Loss: 0.1196 - Val Acc: 0.8551
2026-04-05 05:34:27,695 - INFO - Epoch 66/100 - Train Loss: 0.1198 - Val Acc: 0.8551
2026-04-05 05:34:27,961 - INFO - Epoch 67/100 - Train Loss: 0.1170 - Val Acc: 0.8551
2026-04-05 05:34:28,227 - INFO - Epoch 68/100 - Train Loss: 0.1155 - Val Acc: 0.8551
2026-04-05 05:34:28,496 - INFO - Epoch 69/100 - Train Loss: 0.1167 - Val Acc: 0.8551
2026-04-05 05:34:28,777 - INFO - Epoch 70/100 - Train Loss: 0.1151 - Val Acc: 0.8551
2026-04-05 05:34:29,034 - INFO - Epoch 71/100 - Train Loss: 0.1136 - Val Acc: 0.8551
2026-04-05 05:34:29,300 - INFO - Epoch 72/100 - Train Loss: 0.1110 - Val Acc: 0.8551
2026-04-05 05:34:29,568 - INFO - Epoch 73/100 - Train Loss: 0.1118 - Val Acc: 0.8551
2026-04-05 05:34:29,844 - INFO - Epoch 74/100 - Train Loss: 0.1123 - Val Acc: 0.8551
2026-04-05 05:34:30,118 - INFO - Epoch 75/100 - Train Loss: 0.1081 - Val Acc: 0.8551
2026-04-05 05:34:30,393 - INFO - Epoch 76/100 - Train Loss: 0.1124 - Val Acc: 0.8551
2026-04-05 05:34:30,671 - INFO - Epoch 77/100 - Train Loss: 0.1096 - Val Acc: 0.8551
2026-04-05 05:34:30,941 - INFO - Epoch 78/100 - Train Loss: 0.1094 - Val Acc: 0.8551
2026-04-05 05:34:31,212 - INFO - Epoch 79/100 - Train Loss: 0.1088 - Val Acc: 0.8551
2026-04-05 05:34:31,482 - INFO - Epoch 80/100 - Train Loss: 0.1070 - Val Acc: 0.8551
2026-04-05 05:34:31,755 - INFO - Epoch 81/100 - Train Loss: 0.1066 - Val Acc: 0.8551
2026-04-05 05:34:32,030 - INFO - Epoch 82/100 - Train Loss: 0.1051 - Val Acc: 0.8551
2026-04-05 05:34:32,314 - INFO - Epoch 83/100 - Train Loss: 0.1072 - Val Acc: 0.8551
2026-04-05 05:34:32,600 - INFO - Epoch 84/100 - Train Loss: 0.1073 - Val Acc: 0.8551
2026-04-05 05:34:32,872 - INFO - Epoch 85/100 - Train Loss: 0.1021 - Val Acc: 0.8551
2026-04-05 05:34:33,138 - INFO - Epoch 86/100 - Train Loss: 0.1075 - Val Acc: 0.8551
2026-04-05 05:34:33,403 - INFO - Epoch 87/100 - Train Loss: 0.0997 - Val Acc: 0.8551
2026-04-05 05:34:33,681 - INFO - Epoch 88/100 - Train Loss: 0.1016 - Val Acc: 0.8551
2026-04-05 05:34:33,949 - INFO - Epoch 89/100 - Train Loss: 0.0991 - Val Acc: 0.8551
2026-04-05 05:34:34,213 - INFO - Epoch 90/100 - Train Loss: 0.1043 - Val Acc: 0.8551
2026-04-05 05:34:34,499 - INFO - Epoch 91/100 - Train Loss: 0.0985 - Val Acc: 0.8551
2026-04-05 05:34:34,812 - INFO - Epoch 92/100 - Train Loss: 0.0971 - Val Acc: 0.8551
2026-04-05 05:34:35,086 - INFO - Epoch 93/100 - Train Loss: 0.0987 - Val Acc: 0.8551
2026-04-05 05:34:35,356 - INFO - Epoch 94/100 - Train Loss: 0.1011 - Val Acc: 0.8551
2026-04-05 05:34:35,622 - INFO - Epoch 95/100 - Train Loss: 0.0950 - Val Acc: 0.8551
2026-04-05 05:34:35,882 - INFO - Epoch 96/100 - Train Loss: 0.0954 - Val Acc: 0.8551
2026-04-05 05:34:36,157 - INFO - Epoch 97/100 - Train Loss: 0.0944 - Val Acc: 0.8551
2026-04-05 05:34:36,444 - INFO - Epoch 98/100 - Train Loss: 0.0931 - Val Acc: 0.8551
2026-04-05 05:34:36,718 - INFO - Epoch 99/100 - Train Loss: 0.0936 - Val Acc: 0.8551
2026-04-05 05:34:36,990 - INFO - Epoch 100/100 - Train Loss: 0.0927 - Val Acc: 0.8551
2026-04-05 05:34:37,334 - INFO - Fold 8 logically complete. Tensor memory bounds cleared cleanly.
2026-04-05 05:34:37,338 - INFO - Original class distribution: [276 345]
2026-04-05 05:34:37,339 - INFO - Training device bound securely to: cuda
2026-04-05 05:34:37,354 - INFO - After SMOTE-ENN deployment: [345 294]

Fold 9:   0%|          | 0/100 [00:00<?, ?it/s]

2026-04-05 05:34:37,647 - INFO - Epoch 1/100 - Train Loss: 0.5242 - Val Acc: 0.7681
2026-04-05 05:34:37,912 - INFO - Epoch 2/100 - Train Loss: 0.3378 - Val Acc: 0.8116
2026-04-05 05:34:38,171 - INFO - Epoch 3/100 - Train Loss: 0.2729 - Val Acc: 0.7971
2026-04-05 05:34:38,434 - INFO - Epoch 4/100 - Train Loss: 0.2394 - Val Acc: 0.8116
2026-04-05 05:34:38,702 - INFO - Epoch 5/100 - Train Loss: 0.2172 - Val Acc: 0.8116
2026-04-05 05:34:38,964 - INFO - Epoch 6/100 - Train Loss: 0.2035 - Val Acc: 0.8116
2026-04-05 05:34:39,222 - INFO - Epoch 7/100 - Train Loss: 0.1928 - Val Acc: 0.8261
2026-04-05 05:34:39,498 - INFO - Epoch 8/100 - Train Loss: 0.1838 - Val Acc: 0.8406
2026-04-05 05:34:39,775 - INFO - Epoch 9/100 - Train Loss: 0.1783 - Val Acc: 0.8406
2026-04-05 05:34:40,044 - INFO - Epoch 10/100 - Train Loss: 0.1751 - Val Acc: 0.8406
2026-04-05 05:34:40,314 - INFO - Epoch 11/100 - Train Loss: 0.1706 - Val Acc: 0.8406
2026-04-05 05:34:40,576 - INFO - Epoch 12/100 - Train Loss: 0.1690 - Val Acc: 0.8406
2026-04-05 05:34:40,838 - INFO - Epoch 13/100 - Train Loss: 0.1661 - Val Acc: 0.8406
2026-04-05 05:34:41,106 - INFO - Epoch 14/100 - Train Loss: 0.1643 - Val Acc: 0.8406
2026-04-05 05:34:41,378 - INFO - Epoch 15/100 - Train Loss: 0.1641 - Val Acc: 0.8406
2026-04-05 05:34:41,643 - INFO - Epoch 16/100 - Train Loss: 0.1630 - Val Acc: 0.8406
2026-04-05 05:34:41,913 - INFO - Epoch 17/100 - Train Loss: 0.1612 - Val Acc: 0.8406
2026-04-05 05:34:42,190 - INFO - Epoch 18/100 - Train Loss: 0.1578 - Val Acc: 0.8406
2026-04-05 05:34:42,463 - INFO - Epoch 19/100 - Train Loss: 0.1585 - Val Acc: 0.8406
2026-04-05 05:34:42,745 - INFO - Epoch 20/100 - Train Loss: 0.1572 - Val Acc: 0.8406
2026-04-05 05:34:43,018 - INFO - Epoch 21/100 - Train Loss: 0.1568 - Val Acc: 0.8406
2026-04-05 05:34:43,289 - INFO - Epoch 22/100 - Train Loss: 0.1554 - Val Acc: 0.8406
2026-04-05 05:34:43,571 - INFO - Epoch 23/100 - Train Loss: 0.1532 - Val Acc: 0.8406
2026-04-05 05:34:43,852 - INFO - Epoch 24/100 - Train Loss: 0.1522 - Val Acc: 0.8406
2026-04-05 05:34:44,134 - INFO - Epoch 25/100 - Train Loss: 0.1520 - Val Acc: 0.8406
2026-04-05 05:34:44,409 - INFO - Epoch 26/100 - Train Loss: 0.1505 - Val Acc: 0.8406
2026-04-05 05:34:44,711 - INFO - Epoch 27/100 - Train Loss: 0.1509 - Val Acc: 0.8406
2026-04-05 05:34:44,984 - INFO - Epoch 28/100 - Train Loss: 0.1496 - Val Acc: 0.8406
2026-04-05 05:34:45,249 - INFO - Epoch 29/100 - Train Loss: 0.1484 - Val Acc: 0.8406
2026-04-05 05:34:45,515 - INFO - Epoch 30/100 - Train Loss: 0.1454 - Val Acc: 0.8406
2026-04-05 05:34:45,784 - INFO - Epoch 31/100 - Train Loss: 0.1469 - Val Acc: 0.8406
2026-04-05 05:34:46,055 - INFO - Epoch 32/100 - Train Loss: 0.1455 - Val Acc: 0.8406
2026-04-05 05:34:46,329 - INFO - Epoch 33/100 - Train Loss: 0.1465 - Val Acc: 0.8406
2026-04-05 05:34:46,612 - INFO - Epoch 34/100 - Train Loss: 0.1430 - Val Acc: 0.8406
2026-04-05 05:34:46,885 - INFO - Epoch 35/100 - Train Loss: 0.1434 - Val Acc: 0.8406
2026-04-05 05:34:47,158 - INFO - Epoch 36/100 - Train Loss: 0.1416 - Val Acc: 0.8406
2026-04-05 05:34:47,430 - INFO - Epoch 37/100 - Train Loss: 0.1413 - Val Acc: 0.8406
2026-04-05 05:34:47,705 - INFO - Epoch 38/100 - Train Loss: 0.1394 - Val Acc: 0.8406
2026-04-05 05:34:47,977 - INFO - Epoch 39/100 - Train Loss: 0.1385 - Val Acc: 0.8406
2026-04-05 05:34:48,242 - INFO - Epoch 40/100 - Train Loss: 0.1388 - Val Acc: 0.8406
2026-04-05 05:34:48,539 - INFO - Epoch 41/100 - Train Loss: 0.1376 - Val Acc: 0.8406
2026-04-05 05:34:48,808 - INFO - Epoch 42/100 - Train Loss: 0.1353 - Val Acc: 0.8406
2026-04-05 05:34:49,083 - INFO - Epoch 43/100 - Train Loss: 0.1341 - Val Acc: 0.8406
2026-04-05 05:34:49,350 - INFO - Epoch 44/100 - Train Loss: 0.1362 - Val Acc: 0.8406
2026-04-05 05:34:49,625 - INFO - Epoch 45/100 - Train Loss: 0.1358 - Val Acc: 0.8406
2026-04-05 05:34:49,905 - INFO - Epoch 46/100 - Train Loss: 0.1330 - Val Acc: 0.8406
2026-04-05 05:34:50,187 - INFO - Epoch 47/100 - Train Loss: 0.1309 - Val Acc: 0.8406
2026-04-05 05:34:50,456 - INFO - Epoch 48/100 - Train Loss: 0.1326 - Val Acc: 0.8406
2026-04-05 05:34:50,732 - INFO - Epoch 49/100 - Train Loss: 0.1305 - Val Acc: 0.8406
2026-04-05 05:34:51,006 - INFO - Epoch 50/100 - Train Loss: 0.1309 - Val Acc: 0.8406
2026-04-05 05:34:51,284 - INFO - Epoch 51/100 - Train Loss: 0.1290 - Val Acc: 0.8406
2026-04-05 05:34:51,557 - INFO - Epoch 52/100 - Train Loss: 0.1269 - Val Acc: 0.8406
2026-04-05 05:34:51,825 - INFO - Epoch 53/100 - Train Loss: 0.1276 - Val Acc: 0.8406
2026-04-05 05:34:52,089 - INFO - Epoch 54/100 - Train Loss: 0.1251 - Val Acc: 0.8406
2026-04-05 05:34:52,354 - INFO - Epoch 55/100 - Train Loss: 0.1262 - Val Acc: 0.8406
2026-04-05 05:34:52,623 - INFO - Epoch 56/100 - Train Loss: 0.1250 - Val Acc: 0.8406
2026-04-05 05:34:52,903 - INFO - Epoch 57/100 - Train Loss: 0.1238 - Val Acc: 0.8406
2026-04-05 05:34:53,161 - INFO - Epoch 58/100 - Train Loss: 0.1232 - Val Acc: 0.8406
2026-04-05 05:34:53,436 - INFO - Epoch 59/100 - Train Loss: 0.1214 - Val Acc: 0.8406
2026-04-05 05:34:53,701 - INFO - Epoch 60/100 - Train Loss: 0.1213 - Val Acc: 0.8406
2026-04-05 05:34:53,974 - INFO - Epoch 61/100 - Train Loss: 0.1209 - Val Acc: 0.8406
2026-04-05 05:34:54,254 - INFO - Epoch 62/100 - Train Loss: 0.1182 - Val Acc: 0.8406
2026-04-05 05:34:54,553 - INFO - Epoch 63/100 - Train Loss: 0.1193 - Val Acc: 0.8406
2026-04-05 05:34:54,823 - INFO - Epoch 64/100 - Train Loss: 0.1183 - Val Acc: 0.8406
2026-04-05 05:34:55,092 - INFO - Epoch 65/100 - Train Loss: 0.1152 - Val Acc: 0.8406
2026-04-05 05:34:55,382 - INFO - Epoch 66/100 - Train Loss: 0.1173 - Val Acc: 0.8406
2026-04-05 05:34:55,663 - INFO - Epoch 67/100 - Train Loss: 0.1162 - Val Acc: 0.8406
2026-04-05 05:34:55,946 - INFO - Epoch 68/100 - Train Loss: 0.1148 - Val Acc: 0.8406
2026-04-05 05:34:56,230 - INFO - Epoch 69/100 - Train Loss: 0.1144 - Val Acc: 0.8406
2026-04-05 05:34:56,524 - INFO - Epoch 70/100 - Train Loss: 0.1129 - Val Acc: 0.8406
2026-04-05 05:34:56,791 - INFO - Epoch 71/100 - Train Loss: 0.1133 - Val Acc: 0.8406
2026-04-05 05:34:57,061 - INFO - Epoch 72/100 - Train Loss: 0.1124 - Val Acc: 0.8406
2026-04-05 05:34:57,336 - INFO - Epoch 73/100 - Train Loss: 0.1107 - Val Acc: 0.8406
2026-04-05 05:34:57,616 - INFO - Epoch 74/100 - Train Loss: 0.1127 - Val Acc: 0.8406
2026-04-05 05:34:57,906 - INFO - Epoch 75/100 - Train Loss: 0.1067 - Val Acc: 0.8406
2026-04-05 05:34:58,206 - INFO - Epoch 76/100 - Train Loss: 0.1115 - Val Acc: 0.8406
2026-04-05 05:34:58,500 - INFO - Epoch 77/100 - Train Loss: 0.1094 - Val Acc: 0.8116
2026-04-05 05:34:58,778 - INFO - Epoch 78/100 - Train Loss: 0.1077 - Val Acc: 0.8116
2026-04-05 05:34:59,059 - INFO - Epoch 79/100 - Train Loss: 0.1069 - Val Acc: 0.8406
2026-04-05 05:34:59,326 - INFO - Epoch 80/100 - Train Loss: 0.1075 - Val Acc: 0.8261
2026-04-05 05:34:59,601 - INFO - Epoch 81/100 - Train Loss: 0.1063 - Val Acc: 0.8261
2026-04-05 05:34:59,868 - INFO - Epoch 82/100 - Train Loss: 0.1052 - Val Acc: 0.8116
2026-04-05 05:35:00,138 - INFO - Epoch 83/100 - Train Loss: 0.1041 - Val Acc: 0.8116
2026-04-05 05:35:00,399 - INFO - Epoch 84/100 - Train Loss: 0.1032 - Val Acc: 0.8261
2026-04-05 05:35:00,687 - INFO - Epoch 85/100 - Train Loss: 0.1003 - Val Acc: 0.8116
2026-04-05 05:35:00,969 - INFO - Epoch 86/100 - Train Loss: 0.1008 - Val Acc: 0.8116
2026-04-05 05:35:01,234 - INFO - Epoch 87/100 - Train Loss: 0.1016 - Val Acc: 0.8116
2026-04-05 05:35:01,519 - INFO - Epoch 88/100 - Train Loss: 0.1033 - Val Acc: 0.8116
2026-04-05 05:35:01,810 - INFO - Epoch 89/100 - Train Loss: 0.0989 - Val Acc: 0.8116
2026-04-05 05:35:02,079 - INFO - Epoch 90/100 - Train Loss: 0.0981 - Val Acc: 0.8116
2026-04-05 05:35:02,353 - INFO - Epoch 91/100 - Train Loss: 0.0972 - Val Acc: 0.8116
2026-04-05 05:35:02,624 - INFO - Epoch 92/100 - Train Loss: 0.0976 - Val Acc: 0.8116
2026-04-05 05:35:02,889 - INFO - Epoch 93/100 - Train Loss: 0.0985 - Val Acc: 0.8116
2026-04-05 05:35:03,173 - INFO - Epoch 94/100 - Train Loss: 0.0965 - Val Acc: 0.8116
2026-04-05 05:35:03,455 - INFO - Epoch 95/100 - Train Loss: 0.0961 - Val Acc: 0.8116
2026-04-05 05:35:03,726 - INFO - Epoch 96/100 - Train Loss: 0.0952 - Val Acc: 0.8116
2026-04-05 05:35:03,996 - INFO - Epoch 97/100 - Train Loss: 0.0932 - Val Acc: 0.8116
2026-04-05 05:35:04,272 - INFO - Epoch 98/100 - Train Loss: 0.0925 - Val Acc: 0.8116
2026-04-05 05:35:04,559 - INFO - Epoch 99/100 - Train Loss: 0.0910 - Val Acc: 0.8116
2026-04-05 05:35:04,840 - INFO - Epoch 100/100 - Train Loss: 0.0941 - Val Acc: 0.8116
2026-04-05 05:35:05,203 - INFO - Fold 9 logically complete. Tensor memory bounds cleared cleanly.
2026-04-05 05:35:05,208 - INFO - Original class distribution: [276 345]
2026-04-05 05:35:05,209 - INFO - Training device bound securely to: cuda
2026-04-05 05:35:05,226 - INFO - After SMOTE-ENN deployment: [345 288]

Fold 10:   0%|          | 0/100 [00:00<?, ?it/s]

2026-04-05 05:35:05,511 - INFO - Epoch 1/100 - Train Loss: 0.5362 - Val Acc: 0.8841
2026-04-05 05:35:05,784 - INFO - Epoch 2/100 - Train Loss: 0.3431 - Val Acc: 0.8986
2026-04-05 05:35:06,070 - INFO - Epoch 3/100 - Train Loss: 0.2815 - Val Acc: 0.9130
2026-04-05 05:35:06,345 - INFO - Epoch 4/100 - Train Loss: 0.2517 - Val Acc: 0.9275
2026-04-05 05:35:06,616 - INFO - Epoch 5/100 - Train Loss: 0.2322 - Val Acc: 0.9420
2026-04-05 05:35:06,890 - INFO - Epoch 6/100 - Train Loss: 0.2184 - Val Acc: 0.9420
2026-04-05 05:35:07,160 - INFO - Epoch 7/100 - Train Loss: 0.2090 - Val Acc: 0.9275
2026-04-05 05:35:07,429 - INFO - Epoch 8/100 - Train Loss: 0.2008 - Val Acc: 0.9275
2026-04-05 05:35:07,711 - INFO - Epoch 9/100 - Train Loss: 0.1950 - Val Acc: 0.9275
2026-04-05 05:35:07,973 - INFO - Epoch 10/100 - Train Loss: 0.1915 - Val Acc: 0.9275
2026-04-05 05:35:08,239 - INFO - Epoch 11/100 - Train Loss: 0.1887 - Val Acc: 0.9275
2026-04-05 05:35:08,519 - INFO - Epoch 12/100 - Train Loss: 0.1837 - Val Acc: 0.9275
2026-04-05 05:35:08,793 - INFO - Epoch 13/100 - Train Loss: 0.1846 - Val Acc: 0.9275
2026-04-05 05:35:09,067 - INFO - Epoch 14/100 - Train Loss: 0.1833 - Val Acc: 0.9130
2026-04-05 05:35:09,326 - INFO - Epoch 15/100 - Train Loss: 0.1806 - Val Acc: 0.9130
2026-04-05 05:35:09,593 - INFO - Epoch 16/100 - Train Loss: 0.1770 - Val Acc: 0.9130
2026-04-05 05:35:09,857 - INFO - Epoch 17/100 - Train Loss: 0.1770 - Val Acc: 0.9130
2026-04-05 05:35:10,139 - INFO - Epoch 18/100 - Train Loss: 0.1729 - Val Acc: 0.9275
2026-04-05 05:35:10,430 - INFO - Epoch 19/100 - Train Loss: 0.1725 - Val Acc: 0.9275
2026-04-05 05:35:10,705 - INFO - Epoch 20/100 - Train Loss: 0.1723 - Val Acc: 0.9275
2026-04-05 05:35:10,967 - INFO - Epoch 21/100 - Train Loss: 0.1698 - Val Acc: 0.9275
2026-04-05 05:35:11,227 - INFO - Epoch 22/100 - Train Loss: 0.1678 - Val Acc: 0.9275
2026-04-05 05:35:11,499 - INFO - Epoch 23/100 - Train Loss: 0.1648 - Val Acc: 0.9275
2026-04-05 05:35:11,765 - INFO - Epoch 24/100 - Train Loss: 0.1681 - Val Acc: 0.9275
2026-04-05 05:35:12,050 - INFO - Epoch 25/100 - Train Loss: 0.1644 - Val Acc: 0.9275
2026-04-05 05:35:12,326 - INFO - Epoch 26/100 - Train Loss: 0.1626 - Val Acc: 0.9275
2026-04-05 05:35:12,601 - INFO - Epoch 27/100 - Train Loss: 0.1621 - Val Acc: 0.9275
2026-04-05 05:35:12,880 - INFO - Epoch 28/100 - Train Loss: 0.1613 - Val Acc: 0.9275
2026-04-05 05:35:13,152 - INFO - Epoch 29/100 - Train Loss: 0.1621 - Val Acc: 0.9275
2026-04-05 05:35:13,419 - INFO - Epoch 30/100 - Train Loss: 0.1592 - Val Acc: 0.9275
2026-04-05 05:35:13,703 - INFO - Epoch 31/100 - Train Loss: 0.1581 - Val Acc: 0.9275
2026-04-05 05:35:13,965 - INFO - Epoch 32/100 - Train Loss: 0.1568 - Val Acc: 0.9275
2026-04-05 05:35:14,256 - INFO - Epoch 33/100 - Train Loss: 0.1545 - Val Acc: 0.9275
2026-04-05 05:35:14,560 - INFO - Epoch 34/100 - Train Loss: 0.1537 - Val Acc: 0.9275
2026-04-05 05:35:14,854 - INFO - Epoch 35/100 - Train Loss: 0.1532 - Val Acc: 0.9275
2026-04-05 05:35:15,120 - INFO - Epoch 36/100 - Train Loss: 0.1530 - Val Acc: 0.9275
2026-04-05 05:35:15,395 - INFO - Epoch 37/100 - Train Loss: 0.1524 - Val Acc: 0.9275
2026-04-05 05:35:15,664 - INFO - Epoch 38/100 - Train Loss: 0.1514 - Val Acc: 0.9420
2026-04-05 05:35:15,951 - INFO - Epoch 39/100 - Train Loss: 0.1503 - Val Acc: 0.9420
2026-04-05 05:35:16,236 - INFO - Epoch 40/100 - Train Loss: 0.1511 - Val Acc: 0.9420
2026-04-05 05:35:16,507 - INFO - Epoch 41/100 - Train Loss: 0.1500 - Val Acc: 0.9420
2026-04-05 05:35:16,778 - INFO - Epoch 42/100 - Train Loss: 0.1491 - Val Acc: 0.9420
2026-04-05 05:35:17,049 - INFO - Epoch 43/100 - Train Loss: 0.1482 - Val Acc: 0.9420
2026-04-05 05:35:17,307 - INFO - Epoch 44/100 - Train Loss: 0.1454 - Val Acc: 0.9420
2026-04-05 05:35:17,602 - INFO - Epoch 45/100 - Train Loss: 0.1437 - Val Acc: 0.9565
2026-04-05 05:35:17,871 - INFO - Epoch 46/100 - Train Loss: 0.1447 - Val Acc: 0.9565
2026-04-05 05:35:18,154 - INFO - Epoch 47/100 - Train Loss: 0.1424 - Val Acc: 0.9565
2026-04-05 05:35:18,450 - INFO - Epoch 48/100 - Train Loss: 0.1423 - Val Acc: 0.9565
2026-04-05 05:35:18,729 - INFO - Epoch 49/100 - Train Loss: 0.1426 - Val Acc: 0.9565
2026-04-05 05:35:18,998 - INFO - Epoch 50/100 - Train Loss: 0.1414 - Val Acc: 0.9565
2026-04-05 05:35:19,267 - INFO - Epoch 51/100 - Train Loss: 0.1393 - Val Acc: 0.9565
2026-04-05 05:35:19,556 - INFO - Epoch 52/100 - Train Loss: 0.1406 - Val Acc: 0.9565
2026-04-05 05:35:19,839 - INFO - Epoch 53/100 - Train Loss: 0.1382 - Val Acc: 0.9565
2026-04-05 05:35:20,118 - INFO - Epoch 54/100 - Train Loss: 0.1386 - Val Acc: 0.9565
2026-04-05 05:35:20,403 - INFO - Epoch 55/100 - Train Loss: 0.1350 - Val Acc: 0.9565
2026-04-05 05:35:20,676 - INFO - Epoch 56/100 - Train Loss: 0.1339 - Val Acc: 0.9565
2026-04-05 05:35:20,965 - INFO - Epoch 57/100 - Train Loss: 0.1365 - Val Acc: 0.9565
2026-04-05 05:35:21,234 - INFO - Epoch 58/100 - Train Loss: 0.1334 - Val Acc: 0.9565
2026-04-05 05:35:21,516 - INFO - Epoch 59/100 - Train Loss: 0.1319 - Val Acc: 0.9565
2026-04-05 05:35:21,797 - INFO - Epoch 60/100 - Train Loss: 0.1360 - Val Acc: 0.9565
2026-04-05 05:35:22,091 - INFO - Epoch 61/100 - Train Loss: 0.1330 - Val Acc: 0.9710
2026-04-05 05:35:22,373 - INFO - Epoch 62/100 - Train Loss: 0.1333 - Val Acc: 0.9710
2026-04-05 05:35:22,644 - INFO - Epoch 63/100 - Train Loss: 0.1303 - Val Acc: 0.9710
2026-04-05 05:35:22,925 - INFO - Epoch 64/100 - Train Loss: 0.1320 - Val Acc: 0.9710
2026-04-05 05:35:23,208 - INFO - Epoch 65/100 - Train Loss: 0.1283 - Val Acc: 0.9710
2026-04-05 05:35:23,483 - INFO - Epoch 66/100 - Train Loss: 0.1288 - Val Acc: 0.9710
2026-04-05 05:35:23,772 - INFO - Epoch 67/100 - Train Loss: 0.1280 - Val Acc: 0.9710
2026-04-05 05:35:24,050 - INFO - Epoch 68/100 - Train Loss: 0.1301 - Val Acc: 0.9710
2026-04-05 05:35:24,330 - INFO - Epoch 69/100 - Train Loss: 0.1275 - Val Acc: 0.9710
2026-04-05 05:35:24,631 - INFO - Epoch 70/100 - Train Loss: 0.1277 - Val Acc: 0.9710
2026-04-05 05:35:24,919 - INFO - Epoch 71/100 - Train Loss: 0.1278 - Val Acc: 0.9710
2026-04-05 05:35:25,200 - INFO - Epoch 72/100 - Train Loss: 0.1272 - Val Acc: 0.9710
2026-04-05 05:35:25,485 - INFO - Epoch 73/100 - Train Loss: 0.1275 - Val Acc: 0.9710
2026-04-05 05:35:25,767 - INFO - Epoch 74/100 - Train Loss: 0.1229 - Val Acc: 0.9710
2026-04-05 05:35:26,042 - INFO - Epoch 75/100 - Train Loss: 0.1254 - Val Acc: 0.9710
2026-04-05 05:35:26,321 - INFO - Epoch 76/100 - Train Loss: 0.1205 - Val Acc: 0.9710
2026-04-05 05:35:26,603 - INFO - Epoch 77/100 - Train Loss: 0.1240 - Val Acc: 0.9710
2026-04-05 05:35:26,868 - INFO - Epoch 78/100 - Train Loss: 0.1211 - Val Acc: 0.9710
2026-04-05 05:35:27,153 - INFO - Epoch 79/100 - Train Loss: 0.1201 - Val Acc: 0.9710
2026-04-05 05:35:27,430 - INFO - Epoch 80/100 - Train Loss: 0.1199 - Val Acc: 0.9710
2026-04-05 05:35:27,700 - INFO - Epoch 81/100 - Train Loss: 0.1203 - Val Acc: 0.9710
2026-04-05 05:35:27,988 - INFO - Epoch 82/100 - Train Loss: 0.1188 - Val Acc: 0.9710
2026-04-05 05:35:28,288 - INFO - Epoch 83/100 - Train Loss: 0.1161 - Val Acc: 0.9710
2026-04-05 05:35:28,580 - INFO - Epoch 84/100 - Train Loss: 0.1173 - Val Acc: 0.9710
2026-04-05 05:35:28,873 - INFO - Epoch 85/100 - Train Loss: 0.1149 - Val Acc: 0.9710
2026-04-05 05:35:29,142 - INFO - Epoch 86/100 - Train Loss: 0.1169 - Val Acc: 0.9710
2026-04-05 05:35:29,406 - INFO - Epoch 87/100 - Train Loss: 0.1165 - Val Acc: 0.9710
2026-04-05 05:35:29,679 - INFO - Epoch 88/100 - Train Loss: 0.1151 - Val Acc: 0.9710
2026-04-05 05:35:29,951 - INFO - Epoch 89/100 - Train Loss: 0.1143 - Val Acc: 0.9710
2026-04-05 05:35:30,215 - INFO - Epoch 90/100 - Train Loss: 0.1156 - Val Acc: 0.9710
2026-04-05 05:35:30,482 - INFO - Epoch 91/100 - Train Loss: 0.1141 - Val Acc: 0.9710
2026-04-05 05:35:30,751 - INFO - Epoch 92/100 - Train Loss: 0.1134 - Val Acc: 0.9710
2026-04-05 05:35:31,026 - INFO - Epoch 93/100 - Train Loss: 0.1131 - Val Acc: 0.9710
2026-04-05 05:35:31,315 - INFO - Epoch 94/100 - Train Loss: 0.1122 - Val Acc: 0.9710
2026-04-05 05:35:31,588 - INFO - Epoch 95/100 - Train Loss: 0.1105 - Val Acc: 0.9710
2026-04-05 05:35:31,872 - INFO - Epoch 96/100 - Train Loss: 0.1107 - Val Acc: 0.9710
2026-04-05 05:35:32,145 - INFO - Epoch 97/100 - Train Loss: 0.1085 - Val Acc: 0.9710
2026-04-05 05:35:32,423 - INFO - Epoch 98/100 - Train Loss: 0.1116 - Val Acc: 0.9710
2026-04-05 05:35:32,708 - INFO - Epoch 99/100 - Train Loss: 0.1125 - Val Acc: 0.9710
2026-04-05 05:35:32,979 - INFO - Epoch 100/100 - Train Loss: 0.1113 - Val Acc: 0.9710
2026-04-05 05:35:33,350 - INFO - Fold 10 logically complete. Tensor memory bounds cleared cleanly.
2026-04-05 05:35:33,368 - INFO - ✓ Completed LSTM_smoteenn
2026-04-05 05:35:33,369 - INFO -   Mean Accuracy: 0.8797 ± 0.0472
2026-04-05 05:35:33,369 - INFO -
EXPERIMENT: GRU_BASELINE | german | SMOTE-ENN: False

German | GRU | BASELINE:   0%|          | 0/10 [00:00<?, ?it/s]

2026-04-05 05:35:33,382 - INFO - Original class distribution: [277 344]
2026-04-05 05:35:33,383 - INFO - Training device bound securely to: cuda

Fold 1:   0%|          | 0/100 [00:00<?, ?it/s]

2026-04-05 05:35:33,680 - INFO - Epoch 1/100 - Train Loss: 0.6604 - Val Acc: 0.8406
2026-04-05 05:35:33,955 - INFO - Epoch 2/100 - Train Loss: 0.5861 - Val Acc: 0.8261
2026-04-05 05:35:34,241 - INFO - Epoch 3/100 - Train Loss: 0.5183 - Val Acc: 0.8261
2026-04-05 05:35:34,511 - INFO - Epoch 4/100 - Train Loss: 0.4568 - Val Acc: 0.8261
2026-04-05 05:35:34,796 - INFO - Epoch 5/100 - Train Loss: 0.4154 - Val Acc: 0.8406
2026-04-05 05:35:35,073 - INFO - Epoch 6/100 - Train Loss: 0.3865 - Val Acc: 0.8696
2026-04-05 05:35:35,334 - INFO - Epoch 7/100 - Train Loss: 0.3702 - Val Acc: 0.8696
2026-04-05 05:35:35,613 - INFO - Epoch 8/100 - Train Loss: 0.3598 - Val Acc: 0.8696
2026-04-05 05:35:35,885 - INFO - Epoch 9/100 - Train Loss: 0.3505 - Val Acc: 0.8986
2026-04-05 05:35:36,152 - INFO - Epoch 10/100 - Train Loss: 0.3411 - Val Acc: 0.8986
2026-04-05 05:35:36,423 - INFO - Epoch 11/100 - Train Loss: 0.3334 - Val Acc: 0.8986
2026-04-05 05:35:36,697 - INFO - Epoch 12/100 - Train Loss: 0.3263 - Val Acc: 0.8986
2026-04-05 05:35:36,965 - INFO - Epoch 13/100 - Train Loss: 0.3209 - Val Acc: 0.8986
2026-04-05 05:35:37,231 - INFO - Epoch 14/100 - Train Loss: 0.3198 - Val Acc: 0.8986
2026-04-05 05:35:37,509 - INFO - Epoch 15/100 - Train Loss: 0.3136 - Val Acc: 0.8986
2026-04-05 05:35:37,777 - INFO - Epoch 16/100 - Train Loss: 0.3132 - Val Acc: 0.8986
2026-04-05 05:35:38,049 - INFO - Epoch 17/100 - Train Loss: 0.3104 - Val Acc: 0.8986
2026-04-05 05:35:38,312 - INFO - Epoch 18/100 - Train Loss: 0.3096 - Val Acc: 0.9130
2026-04-05 05:35:38,587 - INFO - Epoch 19/100 - Train Loss: 0.3058 - Val Acc: 0.8986
2026-04-05 05:35:38,862 - INFO - Epoch 20/100 - Train Loss: 0.3057 - Val Acc: 0.8986
2026-04-05 05:35:39,146 - INFO - Epoch 21/100 - Train Loss: 0.3068 - Val Acc: 0.8986
2026-04-05 05:35:39,413 - INFO - Epoch 22/100 - Train Loss: 0.3060 - Val Acc: 0.8986
2026-04-05 05:35:39,682 - INFO - Epoch 23/100 - Train Loss: 0.3029 - Val Acc: 0.8986
2026-04-05 05:35:39,950 - INFO - Epoch 24/100 - Train Loss: 0.3012 - Val Acc: 0.8986
2026-04-05 05:35:40,230 - INFO - Epoch 25/100 - Train Loss: 0.3027 - Val Acc: 0.9130
2026-04-05 05:35:40,513 - INFO - Epoch 26/100 - Train Loss: 0.3050 - Val Acc: 0.8986
2026-04-05 05:35:40,780 - INFO - Epoch 27/100 - Train Loss: 0.3009 - Val Acc: 0.8986
2026-04-05 05:35:41,061 - INFO - Epoch 28/100 - Train Loss: 0.2984 - Val Acc: 0.8986
2026-04-05 05:35:41,323 - INFO - Epoch 29/100 - Train Loss: 0.2975 - Val Acc: 0.9130
2026-04-05 05:35:41,599 - INFO - Epoch 30/100 - Train Loss: 0.2965 - Val Acc: 0.8986
2026-04-05 05:35:41,859 - INFO - Epoch 31/100 - Train Loss: 0.2979 - Val Acc: 0.8986
2026-04-05 05:35:42,130 - INFO - Epoch 32/100 - Train Loss: 0.2946 - Val Acc: 0.8986
2026-04-05 05:35:42,399 - INFO - Epoch 33/100 - Train Loss: 0.2945 - Val Acc: 0.9130
2026-04-05 05:35:42,680 - INFO - Epoch 34/100 - Train Loss: 0.2955 - Val Acc: 0.8986
2026-04-05 05:35:42,947 - INFO - Epoch 35/100 - Train Loss: 0.2936 - Val Acc: 0.9130
2026-04-05 05:35:43,222 - INFO - Epoch 36/100 - Train Loss: 0.2911 - Val Acc: 0.9130
2026-04-05 05:35:43,498 - INFO - Epoch 37/100 - Train Loss: 0.2899 - Val Acc: 0.9130
2026-04-05 05:35:43,769 - INFO - Epoch 38/100 - Train Loss: 0.2910 - Val Acc: 0.9130
2026-04-05 05:35:44,045 - INFO - Epoch 39/100 - Train Loss: 0.2882 - Val Acc: 0.9130
2026-04-05 05:35:44,337 - INFO - Epoch 40/100 - Train Loss: 0.2888 - Val Acc: 0.9130
2026-04-05 05:35:44,633 - INFO - Epoch 41/100 - Train Loss: 0.2877 - Val Acc: 0.9130
2026-04-05 05:35:44,903 - INFO - Epoch 42/100 - Train Loss: 0.2870 - Val Acc: 0.9130
2026-04-05 05:35:45,176 - INFO - Epoch 43/100 - Train Loss: 0.2852 - Val Acc: 0.8986
2026-04-05 05:35:45,441 - INFO - Epoch 44/100 - Train Loss: 0.2864 - Val Acc: 0.8986
2026-04-05 05:35:45,714 - INFO - Epoch 45/100 - Train Loss: 0.2811 - Val Acc: 0.9130
2026-04-05 05:35:45,984 - INFO - Epoch 46/100 - Train Loss: 0.2837 - Val Acc: 0.9130
2026-04-05 05:35:46,268 - INFO - Epoch 47/100 - Train Loss: 0.2832 - Val Acc: 0.9130
2026-04-05 05:35:46,543 - INFO - Epoch 48/100 - Train Loss: 0.2811 - Val Acc: 0.9130
2026-04-05 05:35:46,808 - INFO - Epoch 49/100 - Train Loss: 0.2780 - Val Acc: 0.9130
2026-04-05 05:35:47,077 - INFO - Epoch 50/100 - Train Loss: 0.2768 - Val Acc: 0.9130
2026-04-05 05:35:47,341 - INFO - Epoch 51/100 - Train Loss: 0.2763 - Val Acc: 0.9130
2026-04-05 05:35:47,612 - INFO - Epoch 52/100 - Train Loss: 0.2783 - Val Acc: 0.9130
2026-04-05 05:35:47,881 - INFO - Epoch 53/100 - Train Loss: 0.2730 - Val Acc: 0.9130
2026-04-05 05:35:48,150 - INFO - Epoch 54/100 - Train Loss: 0.2773 - Val Acc: 0.9130
2026-04-05 05:35:48,426 - INFO - Epoch 55/100 - Train Loss: 0.2740 - Val Acc: 0.9130
2026-04-05 05:35:48,685 - INFO - Epoch 56/100 - Train Loss: 0.2758 - Val Acc: 0.9130
2026-04-05 05:35:48,953 - INFO - Epoch 57/100 - Train Loss: 0.2737 - Val Acc: 0.9130
2026-04-05 05:35:49,227 - INFO - Epoch 58/100 - Train Loss: 0.2687 - Val Acc: 0.8986
2026-04-05 05:35:49,491 - INFO - Epoch 59/100 - Train Loss: 0.2695 - Val Acc: 0.9130
2026-04-05 05:35:49,774 - INFO - Epoch 60/100 - Train Loss: 0.2680 - Val Acc: 0.9130
2026-04-05 05:35:50,046 - INFO - Epoch 61/100 - Train Loss: 0.2713 - Val Acc: 0.9130
2026-04-05 05:35:50,314 - INFO - Epoch 62/100 - Train Loss: 0.2680 - Val Acc: 0.9130
2026-04-05 05:35:50,584 - INFO - Epoch 63/100 - Train Loss: 0.2692 - Val Acc: 0.9130
2026-04-05 05:35:50,855 - INFO - Epoch 64/100 - Train Loss: 0.2667 - Val Acc: 0.8986
2026-04-05 05:35:51,121 - INFO - Epoch 65/100 - Train Loss: 0.2666 - Val Acc: 0.8986
2026-04-05 05:35:51,391 - INFO - Epoch 66/100 - Train Loss: 0.2676 - Val Acc: 0.9130
2026-04-05 05:35:51,660 - INFO - Epoch 67/100 - Train Loss: 0.2638 - Val Acc: 0.8986
2026-04-05 05:35:51,937 - INFO - Epoch 68/100 - Train Loss: 0.2621 - Val Acc: 0.9130
2026-04-05 05:35:52,208 - INFO - Epoch 69/100 - Train Loss: 0.2632 - Val Acc: 0.8986
2026-04-05 05:35:52,482 - INFO - Epoch 70/100 - Train Loss: 0.2656 - Val Acc: 0.8986
2026-04-05 05:35:52,752 - INFO - Epoch 71/100 - Train Loss: 0.2633 - Val Acc: 0.8986
2026-04-05 05:35:53,030 - INFO - Epoch 72/100 - Train Loss: 0.2568 - Val Acc: 0.8986
2026-04-05 05:35:53,302 - INFO - Epoch 73/100 - Train Loss: 0.2599 - Val Acc: 0.8986
2026-04-05 05:35:53,579 - INFO - Epoch 74/100 - Train Loss: 0.2608 - Val Acc: 0.8986
2026-04-05 05:35:53,849 - INFO - Epoch 75/100 - Train Loss: 0.2544 - Val Acc: 0.8986
2026-04-05 05:35:54,114 - INFO - Epoch 76/100 - Train Loss: 0.2577 - Val Acc: 0.8986
2026-04-05 05:35:54,397 - INFO - Epoch 77/100 - Train Loss: 0.2543 - Val Acc: 0.8986
2026-04-05 05:35:54,696 - INFO - Epoch 78/100 - Train Loss: 0.2527 - Val Acc: 0.8986
2026-04-05 05:35:54,969 - INFO - Epoch 79/100 - Train Loss: 0.2482 - Val Acc: 0.8986
2026-04-05 05:35:55,257 - INFO - Epoch 80/100 - Train Loss: 0.2518 - Val Acc: 0.8986
2026-04-05 05:35:55,519 - INFO - Epoch 81/100 - Train Loss: 0.2510 - Val Acc: 0.8841
2026-04-05 05:35:55,792 - INFO - Epoch 82/100 - Train Loss: 0.2500 - Val Acc: 0.8841
2026-04-05 05:35:56,067 - INFO - Epoch 83/100 - Train Loss: 0.2507 - Val Acc: 0.8841
2026-04-05 05:35:56,349 - INFO - Epoch 84/100 - Train Loss: 0.2516 - Val Acc: 0.8841
2026-04-05 05:35:56,609 - INFO - Epoch 85/100 - Train Loss: 0.2510 - Val Acc: 0.8841
2026-04-05 05:35:56,879 - INFO - Epoch 86/100 - Train Loss: 0.2477 - Val Acc: 0.8841
2026-04-05 05:35:57,141 - INFO - Epoch 87/100 - Train Loss: 0.2486 - Val Acc: 0.8841
2026-04-05 05:35:57,401 - INFO - Epoch 88/100 - Train Loss: 0.2472 - Val Acc: 0.8841
2026-04-05 05:35:57,662 - INFO - Epoch 89/100 - Train Loss: 0.2438 - Val Acc: 0.8986
2026-04-05 05:35:57,936 - INFO - Epoch 90/100 - Train Loss: 0.2445 - Val Acc: 0.8986
2026-04-05 05:35:58,211 - INFO - Epoch 91/100 - Train Loss: 0.2417 - Val Acc: 0.8986
2026-04-05 05:35:58,474 - INFO - Epoch 92/100 - Train Loss: 0.2451 - Val Acc: 0.8841
2026-04-05 05:35:58,749 - INFO - Epoch 93/100 - Train Loss: 0.2472 - Val Acc: 0.8986
2026-04-05 05:35:59,028 - INFO - Epoch 94/100 - Train Loss: 0.2426 - Val Acc: 0.8841
2026-04-05 05:35:59,294 - INFO - Epoch 95/100 - Train Loss: 0.2401 - Val Acc: 0.8841
2026-04-05 05:35:59,571 - INFO - Epoch 96/100 - Train Loss: 0.2479 - Val Acc: 0.8841
2026-04-05 05:35:59,854 - INFO - Epoch 97/100 - Train Loss: 0.2423 - Val Acc: 0.8841
2026-04-05 05:36:00,122 - INFO - Epoch 98/100 - Train Loss: 0.2380 - Val Acc: 0.8841
2026-04-05 05:36:00,379 - INFO - Epoch 99/100 - Train Loss: 0.2380 - Val Acc: 0.8841
2026-04-05 05:36:00,657 - INFO - Epoch 100/100 - Train Loss: 0.2332 - Val Acc: 0.8841
2026-04-05 05:36:01,011 - INFO - Fold 1 logically complete. Tensor memory bounds cleared cleanly.
2026-04-05 05:36:01,015 - INFO - Original class distribution: [277 344]
2026-04-05 05:36:01,016 - INFO - Training device bound securely to: cuda

Fold 2:   0%|          | 0/100 [00:00<?, ?it/s]

2026-04-05 05:36:01,302 - INFO - Epoch 1/100 - Train Loss: 0.6607 - Val Acc: 0.7536
2026-04-05 05:36:01,559 - INFO - Epoch 2/100 - Train Loss: 0.5803 - Val Acc: 0.7536
2026-04-05 05:36:01,820 - INFO - Epoch 3/100 - Train Loss: 0.5104 - Val Acc: 0.7681
2026-04-05 05:36:02,078 - INFO - Epoch 4/100 - Train Loss: 0.4478 - Val Acc: 0.7681
2026-04-05 05:36:02,348 - INFO - Epoch 5/100 - Train Loss: 0.4043 - Val Acc: 0.7681
2026-04-05 05:36:02,625 - INFO - Epoch 6/100 - Train Loss: 0.3757 - Val Acc: 0.7681
2026-04-05 05:36:02,891 - INFO - Epoch 7/100 - Train Loss: 0.3576 - Val Acc: 0.7826
2026-04-05 05:36:03,168 - INFO - Epoch 8/100 - Train Loss: 0.3455 - Val Acc: 0.8116
2026-04-05 05:36:03,438 - INFO - Epoch 9/100 - Train Loss: 0.3368 - Val Acc: 0.8406
2026-04-05 05:36:03,696 - INFO - Epoch 10/100 - Train Loss: 0.3303 - Val Acc: 0.8551
2026-04-05 05:36:03,971 - INFO - Epoch 11/100 - Train Loss: 0.3244 - Val Acc: 0.8551
2026-04-05 05:36:04,236 - INFO - Epoch 12/100 - Train Loss: 0.3192 - Val Acc: 0.8551
2026-04-05 05:36:04,511 - INFO - Epoch 13/100 - Train Loss: 0.3145 - Val Acc: 0.8696
2026-04-05 05:36:04,790 - INFO - Epoch 14/100 - Train Loss: 0.3120 - Val Acc: 0.8986
2026-04-05 05:36:05,067 - INFO - Epoch 15/100 - Train Loss: 0.3087 - Val Acc: 0.8986
2026-04-05 05:36:05,333 - INFO - Epoch 16/100 - Train Loss: 0.3052 - Val Acc: 0.8986
2026-04-05 05:36:05,591 - INFO - Epoch 17/100 - Train Loss: 0.3066 - Val Acc: 0.8986
2026-04-05 05:36:05,870 - INFO - Epoch 18/100 - Train Loss: 0.3040 - Val Acc: 0.8986
2026-04-05 05:36:06,143 - INFO - Epoch 19/100 - Train Loss: 0.3023 - Val Acc: 0.8986
2026-04-05 05:36:06,403 - INFO - Epoch 20/100 - Train Loss: 0.3024 - Val Acc: 0.8986
2026-04-05 05:36:06,669 - INFO - Epoch 21/100 - Train Loss: 0.2992 - Val Acc: 0.8986
2026-04-05 05:36:06,943 - INFO - Epoch 22/100 - Train Loss: 0.2988 - Val Acc: 0.8986
2026-04-05 05:36:07,216 - INFO - Epoch 23/100 - Train Loss: 0.2973 - Val Acc: 0.8986
2026-04-05 05:36:07,505 - INFO - Epoch 24/100 - Train Loss: 0.2965 - Val Acc: 0.8986
2026-04-05 05:36:07,777 - INFO - Epoch 25/100 - Train Loss: 0.2977 - Val Acc: 0.8986
2026-04-05 05:36:08,057 - INFO - Epoch 26/100 - Train Loss: 0.2973 - Val Acc: 0.8986
2026-04-05 05:36:08,330 - INFO - Epoch 27/100 - Train Loss: 0.2959 - Val Acc: 0.9130
2026-04-05 05:36:08,598 - INFO - Epoch 28/100 - Train Loss: 0.2942 - Val Acc: 0.8986
2026-04-05 05:36:08,878 - INFO - Epoch 29/100 - Train Loss: 0.2915 - Val Acc: 0.8986
2026-04-05 05:36:09,142 - INFO - Epoch 30/100 - Train Loss: 0.2930 - Val Acc: 0.8986
2026-04-05 05:36:09,416 - INFO - Epoch 31/100 - Train Loss: 0.2933 - Val Acc: 0.8986
2026-04-05 05:36:09,685 - INFO - Epoch 32/100 - Train Loss: 0.2866 - Val Acc: 0.8986
2026-04-05 05:36:09,959 - INFO - Epoch 33/100 - Train Loss: 0.2903 - Val Acc: 0.8986
2026-04-05 05:36:10,225 - INFO - Epoch 34/100 - Train Loss: 0.2883 - Val Acc: 0.8986
2026-04-05 05:36:10,495 - INFO - Epoch 35/100 - Train Loss: 0.2884 - Val Acc: 0.8986
2026-04-05 05:36:10,760 - INFO - Epoch 36/100 - Train Loss: 0.2890 - Val Acc: 0.8986
2026-04-05 05:36:11,032 - INFO - Epoch 37/100 - Train Loss: 0.2856 - Val Acc: 0.8986
2026-04-05 05:36:11,306 - INFO - Epoch 38/100 - Train Loss: 0.2840 - Val Acc: 0.8986
2026-04-05 05:36:11,580 - INFO - Epoch 39/100 - Train Loss: 0.2861 - Val Acc: 0.8986
2026-04-05 05:36:11,856 - INFO - Epoch 40/100 - Train Loss: 0.2839 - Val Acc: 0.8986
2026-04-05 05:36:12,120 - INFO - Epoch 41/100 - Train Loss: 0.2816 - Val Acc: 0.8986
2026-04-05 05:36:12,393 - INFO - Epoch 42/100 - Train Loss: 0.2809 - Val Acc: 0.8986
2026-04-05 05:36:12,674 - INFO - Epoch 43/100 - Train Loss: 0.2832 - Val Acc: 0.8986
2026-04-05 05:36:12,950 - INFO - Epoch 44/100 - Train Loss: 0.2796 - Val Acc: 0.8986
2026-04-05 05:36:13,221 - INFO - Epoch 45/100 - Train Loss: 0.2767 - Val Acc: 0.8986
2026-04-05 05:36:13,495 - INFO - Epoch 46/100 - Train Loss: 0.2782 - Val Acc: 0.8986
2026-04-05 05:36:13,762 - INFO - Epoch 47/100 - Train Loss: 0.2756 - Val Acc: 0.8986
2026-04-05 05:36:14,027 - INFO - Epoch 48/100 - Train Loss: 0.2757 - Val Acc: 0.8986
2026-04-05 05:36:14,301 - INFO - Epoch 49/100 - Train Loss: 0.2737 - Val Acc: 0.8986
2026-04-05 05:36:14,580 - INFO - Epoch 50/100 - Train Loss: 0.2733 - Val Acc: 0.8986
2026-04-05 05:36:14,857 - INFO - Epoch 51/100 - Train Loss: 0.2702 - Val Acc: 0.8986
2026-04-05 05:36:15,131 - INFO - Epoch 52/100 - Train Loss: 0.2694 - Val Acc: 0.8986
2026-04-05 05:36:15,389 - INFO - Epoch 53/100 - Train Loss: 0.2714 - Val Acc: 0.8986
2026-04-05 05:36:15,662 - INFO - Epoch 54/100 - Train Loss: 0.2682 - Val Acc: 0.8986
2026-04-05 05:36:15,944 - INFO - Epoch 55/100 - Train Loss: 0.2678 - Val Acc: 0.8986
2026-04-05 05:36:16,201 - INFO - Epoch 56/100 - Train Loss: 0.2697 - Val Acc: 0.8986
2026-04-05 05:36:16,469 - INFO - Epoch 57/100 - Train Loss: 0.2654 - Val Acc: 0.8986
2026-04-05 05:36:16,744 - INFO - Epoch 58/100 - Train Loss: 0.2714 - Val Acc: 0.8986
2026-04-05 05:36:17,006 - INFO - Epoch 59/100 - Train Loss: 0.2662 - Val Acc: 0.8841
2026-04-05 05:36:17,264 - INFO - Epoch 60/100 - Train Loss: 0.2678 - Val Acc: 0.8986
2026-04-05 05:36:17,543 - INFO - Epoch 61/100 - Train Loss: 0.2633 - Val Acc: 0.8986
2026-04-05 05:36:17,813 - INFO - Epoch 62/100 - Train Loss: 0.2589 - Val Acc: 0.8986
2026-04-05 05:36:18,086 - INFO - Epoch 63/100 - Train Loss: 0.2603 - Val Acc: 0.8986
2026-04-05 05:36:18,372 - INFO - Epoch 64/100 - Train Loss: 0.2623 - Val Acc: 0.9130
2026-04-05 05:36:18,643 - INFO - Epoch 65/100 - Train Loss: 0.2607 - Val Acc: 0.9130
2026-04-05 05:36:18,921 - INFO - Epoch 66/100 - Train Loss: 0.2558 - Val Acc: 0.9130
2026-04-05 05:36:19,188 - INFO - Epoch 67/100 - Train Loss: 0.2568 - Val Acc: 0.8986
2026-04-05 05:36:19,450 - INFO - Epoch 68/100 - Train Loss: 0.2538 - Val Acc: 0.8986
2026-04-05 05:36:19,722 - INFO - Epoch 69/100 - Train Loss: 0.2537 - Val Acc: 0.8986
2026-04-05 05:36:19,998 - INFO - Epoch 70/100 - Train Loss: 0.2538 - Val Acc: 0.8986
2026-04-05 05:36:20,275 - INFO - Epoch 71/100 - Train Loss: 0.2550 - Val Acc: 0.8986
2026-04-05 05:36:20,543 - INFO - Epoch 72/100 - Train Loss: 0.2555 - Val Acc: 0.8986
2026-04-05 05:36:20,834 - INFO - Epoch 73/100 - Train Loss: 0.2554 - Val Acc: 0.8986
2026-04-05 05:36:21,110 - INFO - Epoch 74/100 - Train Loss: 0.2495 - Val Acc: 0.8986
2026-04-05 05:36:21,381 - INFO - Epoch 75/100 - Train Loss: 0.2527 - Val Acc: 0.8986
2026-04-05 05:36:21,653 - INFO - Epoch 76/100 - Train Loss: 0.2485 - Val Acc: 0.9130
2026-04-05 05:36:21,919 - INFO - Epoch 77/100 - Train Loss: 0.2530 - Val Acc: 0.8986
2026-04-05 05:36:22,191 - INFO - Epoch 78/100 - Train Loss: 0.2468 - Val Acc: 0.8986
2026-04-05 05:36:22,466 - INFO - Epoch 79/100 - Train Loss: 0.2488 - Val Acc: 0.8841
2026-04-05 05:36:22,741 - INFO - Epoch 80/100 - Train Loss: 0.2452 - Val Acc: 0.8841
2026-04-05 05:36:23,009 - INFO - Epoch 81/100 - Train Loss: 0.2501 - Val Acc: 0.8841
2026-04-05 05:36:23,278 - INFO - Epoch 82/100 - Train Loss: 0.2489 - Val Acc: 0.8986
2026-04-05 05:36:23,538 - INFO - Epoch 83/100 - Train Loss: 0.2455 - Val Acc: 0.8986
2026-04-05 05:36:23,806 - INFO - Epoch 84/100 - Train Loss: 0.2428 - Val Acc: 0.8986
2026-04-05 05:36:24,071 - INFO - Epoch 85/100 - Train Loss: 0.2437 - Val Acc: 0.8841
2026-04-05 05:36:24,339 - INFO - Epoch 86/100 - Train Loss: 0.2410 - Val Acc: 0.8841
2026-04-05 05:36:24,631 - INFO - Epoch 87/100 - Train Loss: 0.2462 - Val Acc: 0.8841
2026-04-05 05:36:24,901 - INFO - Epoch 88/100 - Train Loss: 0.2386 - Val Acc: 0.8841
2026-04-05 05:36:25,167 - INFO - Epoch 89/100 - Train Loss: 0.2451 - Val Acc: 0.8841
2026-04-05 05:36:25,425 - INFO - Epoch 90/100 - Train Loss: 0.2356 - Val Acc: 0.8841
2026-04-05 05:36:25,697 - INFO - Epoch 91/100 - Train Loss: 0.2348 - Val Acc: 0.8841
2026-04-05 05:36:25,969 - INFO - Epoch 92/100 - Train Loss: 0.2399 - Val Acc: 0.8841
2026-04-05 05:36:26,232 - INFO - Epoch 93/100 - Train Loss: 0.2362 - Val Acc: 0.8841
2026-04-05 05:36:26,499 - INFO - Epoch 94/100 - Train Loss: 0.2395 - Val Acc: 0.8841
2026-04-05 05:36:26,761 - INFO - Epoch 95/100 - Train Loss: 0.2319 - Val Acc: 0.8841
2026-04-05 05:36:27,031 - INFO - Epoch 96/100 - Train Loss: 0.2348 - Val Acc: 0.8841
2026-04-05 05:36:27,295 - INFO - Epoch 97/100 - Train Loss: 0.2350 - Val Acc: 0.8841
2026-04-05 05:36:27,590 - INFO - Epoch 98/100 - Train Loss: 0.2352 - Val Acc: 0.8841
2026-04-05 05:36:27,856 - INFO - Epoch 99/100 - Train Loss: 0.2370 - Val Acc: 0.8841
2026-04-05 05:36:28,133 - INFO - Epoch 100/100 - Train Loss: 0.2365 - Val Acc: 0.8841
2026-04-05 05:36:28,482 - INFO - Fold 2 logically complete. Tensor memory bounds cleared cleanly.
2026-04-05 05:36:28,486 - INFO - Original class distribution: [277 344]
2026-04-05 05:36:28,486 - INFO - Training device bound securely to: cuda

Fold 3:   0%|          | 0/100 [00:00<?, ?it/s]

2026-04-05 05:36:28,785 - INFO - Epoch 1/100 - Train Loss: 0.6706 - Val Acc: 0.9275
2026-04-05 05:36:29,051 - INFO - Epoch 2/100 - Train Loss: 0.5944 - Val Acc: 0.9130
2026-04-05 05:36:29,316 - INFO - Epoch 3/100 - Train Loss: 0.5238 - Val Acc: 0.9275
2026-04-05 05:36:29,574 - INFO - Epoch 4/100 - Train Loss: 0.4624 - Val Acc: 0.9275
2026-04-05 05:36:29,853 - INFO - Epoch 5/100 - Train Loss: 0.4197 - Val Acc: 0.9420
2026-04-05 05:36:30,129 - INFO - Epoch 6/100 - Train Loss: 0.3940 - Val Acc: 0.9275
2026-04-05 05:36:30,402 - INFO - Epoch 7/100 - Train Loss: 0.3755 - Val Acc: 0.9275
2026-04-05 05:36:30,670 - INFO - Epoch 8/100 - Train Loss: 0.3626 - Val Acc: 0.9275
2026-04-05 05:36:30,940 - INFO - Epoch 9/100 - Train Loss: 0.3535 - Val Acc: 0.9275
2026-04-05 05:36:31,206 - INFO - Epoch 10/100 - Train Loss: 0.3419 - Val Acc: 0.9130
2026-04-05 05:36:31,472 - INFO - Epoch 11/100 - Train Loss: 0.3350 - Val Acc: 0.9130
2026-04-05 05:36:31,744 - INFO - Epoch 12/100 - Train Loss: 0.3272 - Val Acc: 0.9130
2026-04-05 05:36:32,007 - INFO - Epoch 13/100 - Train Loss: 0.3257 - Val Acc: 0.9130
2026-04-05 05:36:32,276 - INFO - Epoch 14/100 - Train Loss: 0.3201 - Val Acc: 0.9130
2026-04-05 05:36:32,553 - INFO - Epoch 15/100 - Train Loss: 0.3157 - Val Acc: 0.9130
2026-04-05 05:36:32,824 - INFO - Epoch 16/100 - Train Loss: 0.3142 - Val Acc: 0.9130
2026-04-05 05:36:33,098 - INFO - Epoch 17/100 - Train Loss: 0.3126 - Val Acc: 0.9130
2026-04-05 05:36:33,376 - INFO - Epoch 18/100 - Train Loss: 0.3107 - Val Acc: 0.9130
2026-04-05 05:36:33,638 - INFO - Epoch 19/100 - Train Loss: 0.3098 - Val Acc: 0.9130
2026-04-05 05:36:33,912 - INFO - Epoch 20/100 - Train Loss: 0.3099 - Val Acc: 0.9130
2026-04-05 05:36:34,176 - INFO - Epoch 21/100 - Train Loss: 0.3080 - Val Acc: 0.9130
2026-04-05 05:36:34,444 - INFO - Epoch 22/100 - Train Loss: 0.3096 - Val Acc: 0.9130
2026-04-05 05:36:34,736 - INFO - Epoch 23/100 - Train Loss: 0.3035 - Val Acc: 0.9130
2026-04-05 05:36:35,011 - INFO - Epoch 24/100 - Train Loss: 0.3041 - Val Acc: 0.9130
2026-04-05 05:36:35,283 - INFO - Epoch 25/100 - Train Loss: 0.3042 - Val Acc: 0.9130
2026-04-05 05:36:35,550 - INFO - Epoch 26/100 - Train Loss: 0.3027 - Val Acc: 0.9130
2026-04-05 05:36:35,821 - INFO - Epoch 27/100 - Train Loss: 0.3039 - Val Acc: 0.9130
2026-04-05 05:36:36,098 - INFO - Epoch 28/100 - Train Loss: 0.2995 - Val Acc: 0.9130
2026-04-05 05:36:36,359 - INFO - Epoch 29/100 - Train Loss: 0.2993 - Val Acc: 0.9130
2026-04-05 05:36:36,632 - INFO - Epoch 30/100 - Train Loss: 0.2980 - Val Acc: 0.9130
2026-04-05 05:36:36,897 - INFO - Epoch 31/100 - Train Loss: 0.2970 - Val Acc: 0.9130
2026-04-05 05:36:37,162 - INFO - Epoch 32/100 - Train Loss: 0.2977 - Val Acc: 0.9130
2026-04-05 05:36:37,433 - INFO - Epoch 33/100 - Train Loss: 0.2937 - Val Acc: 0.9130
2026-04-05 05:36:37,699 - INFO - Epoch 34/100 - Train Loss: 0.2963 - Val Acc: 0.9130
2026-04-05 05:36:37,970 - INFO - Epoch 35/100 - Train Loss: 0.2965 - Val Acc: 0.9130
2026-04-05 05:36:38,251 - INFO - Epoch 36/100 - Train Loss: 0.2910 - Val Acc: 0.9130
2026-04-05 05:36:38,528 - INFO - Epoch 37/100 - Train Loss: 0.2911 - Val Acc: 0.9130
2026-04-05 05:36:38,797 - INFO - Epoch 38/100 - Train Loss: 0.2908 - Val Acc: 0.9130
2026-04-05 05:36:39,073 - INFO - Epoch 39/100 - Train Loss: 0.2911 - Val Acc: 0.9130
2026-04-05 05:36:39,340 - INFO - Epoch 40/100 - Train Loss: 0.2882 - Val Acc: 0.9130
2026-04-05 05:36:39,605 - INFO - Epoch 41/100 - Train Loss: 0.2878 - Val Acc: 0.9130
2026-04-05 05:36:39,867 - INFO - Epoch 42/100 - Train Loss: 0.2859 - Val Acc: 0.9130
2026-04-05 05:36:40,131 - INFO - Epoch 43/100 - Train Loss: 0.2875 - Val Acc: 0.9130
2026-04-05 05:36:40,404 - INFO - Epoch 44/100 - Train Loss: 0.2867 - Val Acc: 0.9130
2026-04-05 05:36:40,673 - INFO - Epoch 45/100 - Train Loss: 0.2796 - Val Acc: 0.9130
2026-04-05 05:36:40,939 - INFO - Epoch 46/100 - Train Loss: 0.2814 - Val Acc: 0.9130
2026-04-05 05:36:41,215 - INFO - Epoch 47/100 - Train Loss: 0.2825 - Val Acc: 0.9130
2026-04-05 05:36:41,492 - INFO - Epoch 48/100 - Train Loss: 0.2836 - Val Acc: 0.9130
2026-04-05 05:36:41,772 - INFO - Epoch 49/100 - Train Loss: 0.2796 - Val Acc: 0.9130
2026-04-05 05:36:42,039 - INFO - Epoch 50/100 - Train Loss: 0.2770 - Val Acc: 0.9130
2026-04-05 05:36:42,298 - INFO - Epoch 51/100 - Train Loss: 0.2792 - Val Acc: 0.9130
2026-04-05 05:36:42,579 - INFO - Epoch 52/100 - Train Loss: 0.2757 - Val Acc: 0.9130
2026-04-05 05:36:42,844 - INFO - Epoch 53/100 - Train Loss: 0.2749 - Val Acc: 0.9130
2026-04-05 05:36:43,106 - INFO - Epoch 54/100 - Train Loss: 0.2748 - Val Acc: 0.9130
2026-04-05 05:36:43,370 - INFO - Epoch 55/100 - Train Loss: 0.2733 - Val Acc: 0.9130
2026-04-05 05:36:43,644 - INFO - Epoch 56/100 - Train Loss: 0.2730 - Val Acc: 0.9130
2026-04-05 05:36:43,911 - INFO - Epoch 57/100 - Train Loss: 0.2722 - Val Acc: 0.9130
2026-04-05 05:36:44,188 - INFO - Epoch 58/100 - Train Loss: 0.2703 - Val Acc: 0.9130
2026-04-05 05:36:44,460 - INFO - Epoch 59/100 - Train Loss: 0.2713 - Val Acc: 0.9130
2026-04-05 05:36:44,755 - INFO - Epoch 60/100 - Train Loss: 0.2655 - Val Acc: 0.9130
2026-04-05 05:36:45,024 - INFO - Epoch 61/100 - Train Loss: 0.2673 - Val Acc: 0.9130
2026-04-05 05:36:45,301 - INFO - Epoch 62/100 - Train Loss: 0.2661 - Val Acc: 0.9130
2026-04-05 05:36:45,565 - INFO - Epoch 63/100 - Train Loss: 0.2662 - Val Acc: 0.9130
2026-04-05 05:36:45,842 - INFO - Epoch 64/100 - Train Loss: 0.2621 - Val Acc: 0.9130
2026-04-05 05:36:46,110 - INFO - Epoch 65/100 - Train Loss: 0.2619 - Val Acc: 0.9130
2026-04-05 05:36:46,376 - INFO - Epoch 66/100 - Train Loss: 0.2598 - Val Acc: 0.9130
2026-04-05 05:36:46,638 - INFO - Epoch 67/100 - Train Loss: 0.2628 - Val Acc: 0.9130
2026-04-05 05:36:46,910 - INFO - Epoch 68/100 - Train Loss: 0.2581 - Val Acc: 0.9130
2026-04-05 05:36:47,172 - INFO - Epoch 69/100 - Train Loss: 0.2560 - Val Acc: 0.9130
2026-04-05 05:36:47,436 - INFO - Epoch 70/100 - Train Loss: 0.2555 - Val Acc: 0.9130
2026-04-05 05:36:47,701 - INFO - Epoch 71/100 - Train Loss: 0.2531 - Val Acc: 0.9130
2026-04-05 05:36:47,972 - INFO - Epoch 72/100 - Train Loss: 0.2569 - Val Acc: 0.9130
2026-04-05 05:36:48,235 - INFO - Epoch 73/100 - Train Loss: 0.2569 - Val Acc: 0.9130
2026-04-05 05:36:48,499 - INFO - Epoch 74/100 - Train Loss: 0.2509 - Val Acc: 0.9130
2026-04-05 05:36:48,756 - INFO - Epoch 75/100 - Train Loss: 0.2495 - Val Acc: 0.9130
2026-04-05 05:36:49,026 - INFO - Epoch 76/100 - Train Loss: 0.2505 - Val Acc: 0.9130
2026-04-05 05:36:49,331 - INFO - Epoch 77/100 - Train Loss: 0.2486 - Val Acc: 0.9130
2026-04-05 05:36:49,611 - INFO - Epoch 78/100 - Train Loss: 0.2428 - Val Acc: 0.9130
2026-04-05 05:36:49,883 - INFO - Epoch 79/100 - Train Loss: 0.2476 - Val Acc: 0.9130
2026-04-05 05:36:50,152 - INFO - Epoch 80/100 - Train Loss: 0.2453 - Val Acc: 0.9130
2026-04-05 05:36:50,423 - INFO - Epoch 81/100 - Train Loss: 0.2489 - Val Acc: 0.9130
2026-04-05 05:36:50,687 - INFO - Epoch 82/100 - Train Loss: 0.2500 - Val Acc: 0.9130
2026-04-05 05:36:50,970 - INFO - Epoch 83/100 - Train Loss: 0.2481 - Val Acc: 0.9130
2026-04-05 05:36:51,242 - INFO - Epoch 84/100 - Train Loss: 0.2426 - Val Acc: 0.9130
2026-04-05 05:36:51,522 - INFO - Epoch 85/100 - Train Loss: 0.2407 - Val Acc: 0.9130
2026-04-05 05:36:51,811 - INFO - Epoch 86/100 - Train Loss: 0.2439 - Val Acc: 0.9130
2026-04-05 05:36:52,073 - INFO - Epoch 87/100 - Train Loss: 0.2427 - Val Acc: 0.9130
2026-04-05 05:36:52,335 - INFO - Epoch 88/100 - Train Loss: 0.2396 - Val Acc: 0.9130
2026-04-05 05:36:52,604 - INFO - Epoch 89/100 - Train Loss: 0.2369 - Val Acc: 0.9130
2026-04-05 05:36:52,873 - INFO - Epoch 90/100 - Train Loss: 0.2417 - Val Acc: 0.9130
2026-04-05 05:36:53,137 - INFO - Epoch 91/100 - Train Loss: 0.2339 - Val Acc: 0.9130
2026-04-05 05:36:53,410 - INFO - Epoch 92/100 - Train Loss: 0.2370 - Val Acc: 0.9130
2026-04-05 05:36:53,678 - INFO - Epoch 93/100 - Train Loss: 0.2338 - Val Acc: 0.9130
2026-04-05 05:36:53,948 - INFO - Epoch 94/100 - Train Loss: 0.2358 - Val Acc: 0.9130
2026-04-05 05:36:54,217 - INFO - Epoch 95/100 - Train Loss: 0.2372 - Val Acc: 0.9130
2026-04-05 05:36:54,500 - INFO - Epoch 96/100 - Train Loss: 0.2343 - Val Acc: 0.9130
2026-04-05 05:36:54,789 - INFO - Epoch 97/100 - Train Loss: 0.2357 - Val Acc: 0.9130
2026-04-05 05:36:55,051 - INFO - Epoch 98/100 - Train Loss: 0.2357 - Val Acc: 0.9275
2026-04-05 05:36:55,313 - INFO - Epoch 99/100 - Train Loss: 0.2330 - Val Acc: 0.9275
2026-04-05 05:36:55,587 - INFO - Epoch 100/100 - Train Loss: 0.2348 - Val Acc: 0.9275
2026-04-05 05:36:55,947 - INFO - Fold 3 logically complete. Tensor memory bounds cleared cleanly.
2026-04-05 05:36:55,951 - INFO - Original class distribution: [276 345]
2026-04-05 05:36:55,952 - INFO - Training device bound securely to: cuda

Fold 4:   0%|          | 0/100 [00:00<?, ?it/s]

2026-04-05 05:36:56,251 - INFO - Epoch 1/100 - Train Loss: 0.6521 - Val Acc: 0.7391
2026-04-05 05:36:56,530 - INFO - Epoch 2/100 - Train Loss: 0.5756 - Val Acc: 0.7536
2026-04-05 05:36:56,802 - INFO - Epoch 3/100 - Train Loss: 0.5005 - Val Acc: 0.7536
2026-04-05 05:36:57,070 - INFO - Epoch 4/100 - Train Loss: 0.4400 - Val Acc: 0.7536
2026-04-05 05:36:57,330 - INFO - Epoch 5/100 - Train Loss: 0.3965 - Val Acc: 0.7536
2026-04-05 05:36:57,594 - INFO - Epoch 6/100 - Train Loss: 0.3686 - Val Acc: 0.7536
2026-04-05 05:36:57,869 - INFO - Epoch 7/100 - Train Loss: 0.3488 - Val Acc: 0.7681
2026-04-05 05:36:58,129 - INFO - Epoch 8/100 - Train Loss: 0.3372 - Val Acc: 0.7971
2026-04-05 05:36:58,398 - INFO - Epoch 9/100 - Train Loss: 0.3238 - Val Acc: 0.8116
2026-04-05 05:36:58,671 - INFO - Epoch 10/100 - Train Loss: 0.3156 - Val Acc: 0.7971
2026-04-05 05:36:58,946 - INFO - Epoch 11/100 - Train Loss: 0.3080 - Val Acc: 0.7826
2026-04-05 05:36:59,212 - INFO - Epoch 12/100 - Train Loss: 0.3015 - Val Acc: 0.7971
2026-04-05 05:36:59,491 - INFO - Epoch 13/100 - Train Loss: 0.2976 - Val Acc: 0.7971
2026-04-05 05:36:59,761 - INFO - Epoch 14/100 - Train Loss: 0.2927 - Val Acc: 0.8116
2026-04-05 05:37:00,028 - INFO - Epoch 15/100 - Train Loss: 0.2925 - Val Acc: 0.7971
2026-04-05 05:37:00,309 - INFO - Epoch 16/100 - Train Loss: 0.2882 - Val Acc: 0.8116
2026-04-05 05:37:00,596 - INFO - Epoch 17/100 - Train Loss: 0.2848 - Val Acc: 0.7971
2026-04-05 05:37:00,858 - INFO - Epoch 18/100 - Train Loss: 0.2818 - Val Acc: 0.8116
2026-04-05 05:37:01,127 - INFO - Epoch 19/100 - Train Loss: 0.2823 - Val Acc: 0.8116
2026-04-05 05:37:01,390 - INFO - Epoch 20/100 - Train Loss: 0.2794 - Val Acc: 0.8116
2026-04-05 05:37:01,664 - INFO - Epoch 21/100 - Train Loss: 0.2798 - Val Acc: 0.8116
2026-04-05 05:37:01,933 - INFO - Epoch 22/100 - Train Loss: 0.2778 - Val Acc: 0.7971
2026-04-05 05:37:02,195 - INFO - Epoch 23/100 - Train Loss: 0.2754 - Val Acc: 0.7971
2026-04-05 05:37:02,459 - INFO - Epoch 24/100 - Train Loss: 0.2761 - Val Acc: 0.7971
2026-04-05 05:37:02,731 - INFO - Epoch 25/100 - Train Loss: 0.2778 - Val Acc: 0.7971
2026-04-05 05:37:03,010 - INFO - Epoch 26/100 - Train Loss: 0.2756 - Val Acc: 0.7971
2026-04-05 05:37:03,270 - INFO - Epoch 27/100 - Train Loss: 0.2730 - Val Acc: 0.7971
2026-04-05 05:37:03,544 - INFO - Epoch 28/100 - Train Loss: 0.2716 - Val Acc: 0.7971
2026-04-05 05:37:03,808 - INFO - Epoch 29/100 - Train Loss: 0.2714 - Val Acc: 0.7971
2026-04-05 05:37:04,081 - INFO - Epoch 30/100 - Train Loss: 0.2708 - Val Acc: 0.7971
2026-04-05 05:37:04,359 - INFO - Epoch 31/100 - Train Loss: 0.2705 - Val Acc: 0.7971
2026-04-05 05:37:04,649 - INFO - Epoch 32/100 - Train Loss: 0.2692 - Val Acc: 0.7971
2026-04-05 05:37:04,919 - INFO - Epoch 33/100 - Train Loss: 0.2691 - Val Acc: 0.7971
2026-04-05 05:37:05,188 - INFO - Epoch 34/100 - Train Loss: 0.2703 - Val Acc: 0.7971
2026-04-05 05:37:05,461 - INFO - Epoch 35/100 - Train Loss: 0.2687 - Val Acc: 0.7971
2026-04-05 05:37:05,747 - INFO - Epoch 36/100 - Train Loss: 0.2680 - Val Acc: 0.7971
2026-04-05 05:37:06,010 - INFO - Epoch 37/100 - Train Loss: 0.2648 - Val Acc: 0.7971
2026-04-05 05:37:06,285 - INFO - Epoch 38/100 - Train Loss: 0.2674 - Val Acc: 0.7971
2026-04-05 05:37:06,558 - INFO - Epoch 39/100 - Train Loss: 0.2642 - Val Acc: 0.7971
2026-04-05 05:37:06,835 - INFO - Epoch 40/100 - Train Loss: 0.2616 - Val Acc: 0.7971
2026-04-05 05:37:07,116 - INFO - Epoch 41/100 - Train Loss: 0.2626 - Val Acc: 0.7971
2026-04-05 05:37:07,391 - INFO - Epoch 42/100 - Train Loss: 0.2602 - Val Acc: 0.7971
2026-04-05 05:37:07,662 - INFO - Epoch 43/100 - Train Loss: 0.2587 - Val Acc: 0.7971
2026-04-05 05:37:07,931 - INFO - Epoch 44/100 - Train Loss: 0.2602 - Val Acc: 0.7971
2026-04-05 05:37:08,201 - INFO - Epoch 45/100 - Train Loss: 0.2590 - Val Acc: 0.7971
2026-04-05 05:37:08,456 - INFO - Epoch 46/100 - Train Loss: 0.2605 - Val Acc: 0.7971
2026-04-05 05:37:08,723 - INFO - Epoch 47/100 - Train Loss: 0.2556 - Val Acc: 0.7971
2026-04-05 05:37:08,992 - INFO - Epoch 48/100 - Train Loss: 0.2546 - Val Acc: 0.7971
2026-04-05 05:37:09,258 - INFO - Epoch 49/100 - Train Loss: 0.2561 - Val Acc: 0.7971
2026-04-05 05:37:09,523 - INFO - Epoch 50/100 - Train Loss: 0.2524 - Val Acc: 0.7971
2026-04-05 05:37:09,805 - INFO - Epoch 51/100 - Train Loss: 0.2487 - Val Acc: 0.8116
2026-04-05 05:37:10,082 - INFO - Epoch 52/100 - Train Loss: 0.2500 - Val Acc: 0.8261
2026-04-05 05:37:10,348 - INFO - Epoch 53/100 - Train Loss: 0.2494 - Val Acc: 0.8261
2026-04-05 05:37:10,629 - INFO - Epoch 54/100 - Train Loss: 0.2499 - Val Acc: 0.8261
2026-04-05 05:37:10,895 - INFO - Epoch 55/100 - Train Loss: 0.2507 - Val Acc: 0.8261
2026-04-05 05:37:11,175 - INFO - Epoch 56/100 - Train Loss: 0.2478 - Val Acc: 0.8261
2026-04-05 05:37:11,446 - INFO - Epoch 57/100 - Train Loss: 0.2449 - Val Acc: 0.8261
2026-04-05 05:37:11,710 - INFO - Epoch 58/100 - Train Loss: 0.2442 - Val Acc: 0.8261
2026-04-05 05:37:11,992 - INFO - Epoch 59/100 - Train Loss: 0.2436 - Val Acc: 0.8261
2026-04-05 05:37:12,272 - INFO - Epoch 60/100 - Train Loss: 0.2472 - Val Acc: 0.8261
2026-04-05 05:37:12,550 - INFO - Epoch 61/100 - Train Loss: 0.2417 - Val Acc: 0.8261
2026-04-05 05:37:12,835 - INFO - Epoch 62/100 - Train Loss: 0.2387 - Val Acc: 0.8261
2026-04-05 05:37:13,110 - INFO - Epoch 63/100 - Train Loss: 0.2381 - Val Acc: 0.8261
2026-04-05 05:37:13,380 - INFO - Epoch 64/100 - Train Loss: 0.2406 - Val Acc: 0.8261
2026-04-05 05:37:13,649 - INFO - Epoch 65/100 - Train Loss: 0.2381 - Val Acc: 0.8261
2026-04-05 05:37:13,937 - INFO - Epoch 66/100 - Train Loss: 0.2377 - Val Acc: 0.8261
2026-04-05 05:37:14,202 - INFO - Epoch 67/100 - Train Loss: 0.2363 - Val Acc: 0.8261
2026-04-05 05:37:14,468 - INFO - Epoch 68/100 - Train Loss: 0.2348 - Val Acc: 0.8406
2026-04-05 05:37:14,764 - INFO - Epoch 69/100 - Train Loss: 0.2340 - Val Acc: 0.8406
2026-04-05 05:37:15,035 - INFO - Epoch 70/100 - Train Loss: 0.2346 - Val Acc: 0.8406
2026-04-05 05:37:15,314 - INFO - Epoch 71/100 - Train Loss: 0.2285 - Val Acc: 0.8406
2026-04-05 05:37:15,591 - INFO - Epoch 72/100 - Train Loss: 0.2325 - Val Acc: 0.8406
2026-04-05 05:37:15,868 - INFO - Epoch 73/100 - Train Loss: 0.2310 - Val Acc: 0.8406
2026-04-05 05:37:16,139 - INFO - Epoch 74/100 - Train Loss: 0.2348 - Val Acc: 0.8551
2026-04-05 05:37:16,403 - INFO - Epoch 75/100 - Train Loss: 0.2342 - Val Acc: 0.8406
2026-04-05 05:37:16,668 - INFO - Epoch 76/100 - Train Loss: 0.2252 - Val Acc: 0.8406
2026-04-05 05:37:16,939 - INFO - Epoch 77/100 - Train Loss: 0.2240 - Val Acc: 0.8551
2026-04-05 05:37:17,208 - INFO - Epoch 78/100 - Train Loss: 0.2293 - Val Acc: 0.8551
2026-04-05 05:37:17,495 - INFO - Epoch 79/100 - Train Loss: 0.2261 - Val Acc: 0.8551
2026-04-05 05:37:17,766 - INFO - Epoch 80/100 - Train Loss: 0.2296 - Val Acc: 0.8261
2026-04-05 05:37:18,058 - INFO - Epoch 81/100 - Train Loss: 0.2292 - Val Acc: 0.8406
2026-04-05 05:37:18,338 - INFO - Epoch 82/100 - Train Loss: 0.2260 - Val Acc: 0.8551
2026-04-05 05:37:18,635 - INFO - Epoch 83/100 - Train Loss: 0.2245 - Val Acc: 0.8551
2026-04-05 05:37:18,938 - INFO - Epoch 84/100 - Train Loss: 0.2195 - Val Acc: 0.8406
2026-04-05 05:37:19,208 - INFO - Epoch 85/100 - Train Loss: 0.2222 - Val Acc: 0.8551
2026-04-05 05:37:19,477 - INFO - Epoch 86/100 - Train Loss: 0.2251 - Val Acc: 0.8551
2026-04-05 05:37:19,735 - INFO - Epoch 87/100 - Train Loss: 0.2178 - Val Acc: 0.8406
2026-04-05 05:37:19,996 - INFO - Epoch 88/100 - Train Loss: 0.2191 - Val Acc: 0.8406
2026-04-05 05:37:20,266 - INFO - Epoch 89/100 - Train Loss: 0.2157 - Val Acc: 0.8406
2026-04-05 05:37:20,539 - INFO - Epoch 90/100 - Train Loss: 0.2222 - Val Acc: 0.8406
2026-04-05 05:37:20,805 - INFO - Epoch 91/100 - Train Loss: 0.2215 - Val Acc: 0.8406
2026-04-05 05:37:21,068 - INFO - Epoch 92/100 - Train Loss: 0.2175 - Val Acc: 0.8551
2026-04-05 05:37:21,334 - INFO - Epoch 93/100 - Train Loss: 0.2144 - Val Acc: 0.8406
2026-04-05 05:37:21,603 - INFO - Epoch 94/100 - Train Loss: 0.2139 - Val Acc: 0.8551
2026-04-05 05:37:21,876 - INFO - Epoch 95/100 - Train Loss: 0.2133 - Val Acc: 0.8551
2026-04-05 05:37:22,150 - INFO - Epoch 96/100 - Train Loss: 0.2149 - Val Acc: 0.8406
2026-04-05 05:37:22,417 - INFO - Epoch 97/100 - Train Loss: 0.2143 - Val Acc: 0.8406
2026-04-05 05:37:22,688 - INFO - Epoch 98/100 - Train Loss: 0.2153 - Val Acc: 0.8406
2026-04-05 05:37:22,953 - INFO - Epoch 99/100 - Train Loss: 0.2116 - Val Acc: 0.8261
2026-04-05 05:37:23,223 - INFO - Epoch 100/100 - Train Loss: 0.2134 - Val Acc: 0.8406
2026-04-05 05:37:23,582 - INFO - Fold 4 logically complete. Tensor memory bounds cleared cleanly.
2026-04-05 05:37:23,586 - INFO - Original class distribution: [276 345]
2026-04-05 05:37:23,587 - INFO - Training device bound securely to: cuda

Fold 5:   0%|          | 0/100 [00:00<?, ?it/s]

2026-04-05 05:37:23,885 - INFO - Epoch 1/100 - Train Loss: 0.6623 - Val Acc: 0.8116
2026-04-05 05:37:24,162 - INFO - Epoch 2/100 - Train Loss: 0.5852 - Val Acc: 0.7971
2026-04-05 05:37:24,425 - INFO - Epoch 3/100 - Train Loss: 0.5158 - Val Acc: 0.8116
2026-04-05 05:37:24,729 - INFO - Epoch 4/100 - Train Loss: 0.4561 - Val Acc: 0.8116
2026-04-05 05:37:25,004 - INFO - Epoch 5/100 - Train Loss: 0.4062 - Val Acc: 0.8261
2026-04-05 05:37:25,264 - INFO - Epoch 6/100 - Train Loss: 0.3784 - Val Acc: 0.8551
2026-04-05 05:37:25,536 - INFO - Epoch 7/100 - Train Loss: 0.3594 - Val Acc: 0.8551
2026-04-05 05:37:25,807 - INFO - Epoch 8/100 - Train Loss: 0.3474 - Val Acc: 0.8551
2026-04-05 05:37:26,078 - INFO - Epoch 9/100 - Train Loss: 0.3368 - Val Acc: 0.8696
2026-04-05 05:37:26,352 - INFO - Epoch 10/100 - Train Loss: 0.3275 - Val Acc: 0.8696
2026-04-05 05:37:26,624 - INFO - Epoch 11/100 - Train Loss: 0.3185 - Val Acc: 0.8696
2026-04-05 05:37:26,889 - INFO - Epoch 12/100 - Train Loss: 0.3153 - Val Acc: 0.8841
2026-04-05 05:37:27,157 - INFO - Epoch 13/100 - Train Loss: 0.3087 - Val Acc: 0.8841
2026-04-05 05:37:27,424 - INFO - Epoch 14/100 - Train Loss: 0.3047 - Val Acc: 0.8841
2026-04-05 05:37:27,697 - INFO - Epoch 15/100 - Train Loss: 0.3036 - Val Acc: 0.8696
2026-04-05 05:37:27,959 - INFO - Epoch 16/100 - Train Loss: 0.2994 - Val Acc: 0.8696
2026-04-05 05:37:28,221 - INFO - Epoch 17/100 - Train Loss: 0.2963 - Val Acc: 0.8696
2026-04-05 05:37:28,489 - INFO - Epoch 18/100 - Train Loss: 0.2956 - Val Acc: 0.8696
2026-04-05 05:37:28,764 - INFO - Epoch 19/100 - Train Loss: 0.2961 - Val Acc: 0.8551
2026-04-05 05:37:29,057 - INFO - Epoch 20/100 - Train Loss: 0.2908 - Val Acc: 0.8551
2026-04-05 05:37:29,323 - INFO - Epoch 21/100 - Train Loss: 0.2925 - Val Acc: 0.8406
2026-04-05 05:37:29,579 - INFO - Epoch 22/100 - Train Loss: 0.2895 - Val Acc: 0.8261
2026-04-05 05:37:29,851 - INFO - Epoch 23/100 - Train Loss: 0.2911 - Val Acc: 0.8406
2026-04-05 05:37:30,114 - INFO - Epoch 24/100 - Train Loss: 0.2858 - Val Acc: 0.8406
2026-04-05 05:37:30,389 - INFO - Epoch 25/100 - Train Loss: 0.2871 - Val Acc: 0.8406
2026-04-05 05:37:30,653 - INFO - Epoch 26/100 - Train Loss: 0.2840 - Val Acc: 0.8551
2026-04-05 05:37:30,920 - INFO - Epoch 27/100 - Train Loss: 0.2850 - Val Acc: 0.8406
2026-04-05 05:37:31,196 - INFO - Epoch 28/100 - Train Loss: 0.2842 - Val Acc: 0.8406
2026-04-05 05:37:31,469 - INFO - Epoch 29/100 - Train Loss: 0.2824 - Val Acc: 0.8406
2026-04-05 05:37:31,729 - INFO - Epoch 30/100 - Train Loss: 0.2852 - Val Acc: 0.8406
2026-04-05 05:37:31,994 - INFO - Epoch 31/100 - Train Loss: 0.2808 - Val Acc: 0.8406
2026-04-05 05:37:32,273 - INFO - Epoch 32/100 - Train Loss: 0.2792 - Val Acc: 0.8406
2026-04-05 05:37:32,536 - INFO - Epoch 33/100 - Train Loss: 0.2773 - Val Acc: 0.8406
2026-04-05 05:37:32,809 - INFO - Epoch 34/100 - Train Loss: 0.2752 - Val Acc: 0.8406
2026-04-05 05:37:33,087 - INFO - Epoch 35/100 - Train Loss: 0.2770 - Val Acc: 0.8406
2026-04-05 05:37:33,355 - INFO - Epoch 36/100 - Train Loss: 0.2720 - Val Acc: 0.8406
2026-04-05 05:37:33,640 - INFO - Epoch 37/100 - Train Loss: 0.2751 - Val Acc: 0.8406
2026-04-05 05:37:33,925 - INFO - Epoch 38/100 - Train Loss: 0.2711 - Val Acc: 0.8406
2026-04-05 05:37:34,209 - INFO - Epoch 39/100 - Train Loss: 0.2707 - Val Acc: 0.8406
2026-04-05 05:37:34,508 - INFO - Epoch 40/100 - Train Loss: 0.2696 - Val Acc: 0.8406
2026-04-05 05:37:34,820 - INFO - Epoch 41/100 - Train Loss: 0.2662 - Val Acc: 0.8406
2026-04-05 05:37:35,086 - INFO - Epoch 42/100 - Train Loss: 0.2667 - Val Acc: 0.8406
2026-04-05 05:37:35,350 - INFO - Epoch 43/100 - Train Loss: 0.2664 - Val Acc: 0.8406
2026-04-05 05:37:35,613 - INFO - Epoch 44/100 - Train Loss: 0.2658 - Val Acc: 0.8551
2026-04-05 05:37:35,886 - INFO - Epoch 45/100 - Train Loss: 0.2653 - Val Acc: 0.8406
2026-04-05 05:37:36,161 - INFO - Epoch 46/100 - Train Loss: 0.2627 - Val Acc: 0.8551
2026-04-05 05:37:36,427 - INFO - Epoch 47/100 - Train Loss: 0.2628 - Val Acc: 0.8551
2026-04-05 05:37:36,704 - INFO - Epoch 48/100 - Train Loss: 0.2616 - Val Acc: 0.8551
2026-04-05 05:37:36,979 - INFO - Epoch 49/100 - Train Loss: 0.2611 - Val Acc: 0.8551
2026-04-05 05:37:37,245 - INFO - Epoch 50/100 - Train Loss: 0.2578 - Val Acc: 0.8406
2026-04-05 05:37:37,508 - INFO - Epoch 51/100 - Train Loss: 0.2551 - Val Acc: 0.8551
2026-04-05 05:37:37,779 - INFO - Epoch 52/100 - Train Loss: 0.2539 - Val Acc: 0.8551
2026-04-05 05:37:38,042 - INFO - Epoch 53/100 - Train Loss: 0.2552 - Val Acc: 0.8551
2026-04-05 05:37:38,316 - INFO - Epoch 54/100 - Train Loss: 0.2528 - Val Acc: 0.8406
2026-04-05 05:37:38,597 - INFO - Epoch 55/100 - Train Loss: 0.2520 - Val Acc: 0.8551
2026-04-05 05:37:38,877 - INFO - Epoch 56/100 - Train Loss: 0.2522 - Val Acc: 0.8551
2026-04-05 05:37:39,154 - INFO - Epoch 57/100 - Train Loss: 0.2504 - Val Acc: 0.8551
2026-04-05 05:37:39,432 - INFO - Epoch 58/100 - Train Loss: 0.2482 - Val Acc: 0.8551
2026-04-05 05:37:39,708 - INFO - Epoch 59/100 - Train Loss: 0.2501 - Val Acc: 0.8551
2026-04-05 05:37:39,970 - INFO - Epoch 60/100 - Train Loss: 0.2497 - Val Acc: 0.8551
2026-04-05 05:37:40,251 - INFO - Epoch 61/100 - Train Loss: 0.2475 - Val Acc: 0.8551
2026-04-05 05:37:40,530 - INFO - Epoch 62/100 - Train Loss: 0.2479 - Val Acc: 0.8551
2026-04-05 05:37:40,792 - INFO - Epoch 63/100 - Train Loss: 0.2434 - Val Acc: 0.8551
2026-04-05 05:37:41,073 - INFO - Epoch 64/100 - Train Loss: 0.2442 - Val Acc: 0.8551
2026-04-05 05:37:41,350 - INFO - Epoch 65/100 - Train Loss: 0.2398 - Val Acc: 0.8551
2026-04-05 05:37:41,619 - INFO - Epoch 66/100 - Train Loss: 0.2398 - Val Acc: 0.8551
2026-04-05 05:37:41,896 - INFO - Epoch 67/100 - Train Loss: 0.2391 - Val Acc: 0.8551
2026-04-05 05:37:42,170 - INFO - Epoch 68/100 - Train Loss: 0.2399 - Val Acc: 0.8551
2026-04-05 05:37:42,436 - INFO - Epoch 69/100 - Train Loss: 0.2379 - Val Acc: 0.8551
2026-04-05 05:37:42,712 - INFO - Epoch 70/100 - Train Loss: 0.2383 - Val Acc: 0.8406
2026-04-05 05:37:42,991 - INFO - Epoch 71/100 - Train Loss: 0.2347 - Val Acc: 0.8406
2026-04-05 05:37:43,259 - INFO - Epoch 72/100 - Train Loss: 0.2385 - Val Acc: 0.8551
2026-04-05 05:37:43,530 - INFO - Epoch 73/100 - Train Loss: 0.2327 - Val Acc: 0.8551
2026-04-05 05:37:43,809 - INFO - Epoch 74/100 - Train Loss: 0.2317 - Val Acc: 0.8551
2026-04-05 05:37:44,100 - INFO - Epoch 75/100 - Train Loss: 0.2354 - Val Acc: 0.8261
2026-04-05 05:37:44,378 - INFO - Epoch 76/100 - Train Loss: 0.2350 - Val Acc: 0.8406
2026-04-05 05:37:44,674 - INFO - Epoch 77/100 - Train Loss: 0.2267 - Val Acc: 0.8406
2026-04-05 05:37:44,953 - INFO - Epoch 78/100 - Train Loss: 0.2330 - Val Acc: 0.8551
2026-04-05 05:37:45,213 - INFO - Epoch 79/100 - Train Loss: 0.2253 - Val Acc: 0.8261
2026-04-05 05:37:45,483 - INFO - Epoch 80/100 - Train Loss: 0.2323 - Val Acc: 0.8261
2026-04-05 05:37:45,744 - INFO - Epoch 81/100 - Train Loss: 0.2224 - Val Acc: 0.8261
2026-04-05 05:37:46,020 - INFO - Epoch 82/100 - Train Loss: 0.2248 - Val Acc: 0.8406
2026-04-05 05:37:46,286 - INFO - Epoch 83/100 - Train Loss: 0.2285 - Val Acc: 0.8261
2026-04-05 05:37:46,556 - INFO - Epoch 84/100 - Train Loss: 0.2264 - Val Acc: 0.8406
2026-04-05 05:37:46,820 - INFO - Epoch 85/100 - Train Loss: 0.2298 - Val Acc: 0.8406
2026-04-05 05:37:47,080 - INFO - Epoch 86/100 - Train Loss: 0.2268 - Val Acc: 0.8406
2026-04-05 05:37:47,358 - INFO - Epoch 87/100 - Train Loss: 0.2197 - Val Acc: 0.8261
2026-04-05 05:37:47,619 - INFO - Epoch 88/100 - Train Loss: 0.2226 - Val Acc: 0.8406
2026-04-05 05:37:47,888 - INFO - Epoch 89/100 - Train Loss: 0.2219 - Val Acc: 0.8261
2026-04-05 05:37:48,167 - INFO - Epoch 90/100 - Train Loss: 0.2189 - Val Acc: 0.8261
2026-04-05 05:37:48,438 - INFO - Epoch 91/100 - Train Loss: 0.2199 - Val Acc: 0.8261
2026-04-05 05:37:48,703 - INFO - Epoch 92/100 - Train Loss: 0.2177 - Val Acc: 0.8551
2026-04-05 05:37:48,973 - INFO - Epoch 93/100 - Train Loss: 0.2195 - Val Acc: 0.8551
2026-04-05 05:37:49,240 - INFO - Epoch 94/100 - Train Loss: 0.2194 - Val Acc: 0.8261
2026-04-05 05:37:49,501 - INFO - Epoch 95/100 - Train Loss: 0.2164 - Val Acc: 0.8261
2026-04-05 05:37:49,771 - INFO - Epoch 96/100 - Train Loss: 0.2206 - Val Acc: 0.8406
2026-04-05 05:37:50,049 - INFO - Epoch 97/100 - Train Loss: 0.2167 - Val Acc: 0.8406
2026-04-05 05:37:50,314 - INFO - Epoch 98/100 - Train Loss: 0.2157 - Val Acc: 0.8406
2026-04-05 05:37:50,599 - INFO - Epoch 99/100 - Train Loss: 0.2191 - Val Acc: 0.8406
2026-04-05 05:37:50,867 - INFO - Epoch 100/100 - Train Loss: 0.2133 - Val Acc: 0.8406
2026-04-05 05:37:51,217 - INFO - Fold 5 logically complete. Tensor memory bounds cleared cleanly.
2026-04-05 05:37:51,221 - INFO - Original class distribution: [276 345]
2026-04-05 05:37:51,222 - INFO - Training device bound securely to: cuda

Fold 6:   0%|          | 0/100 [00:00<?, ?it/s]

2026-04-05 05:37:51,528 - INFO - Epoch 1/100 - Train Loss: 0.6494 - Val Acc: 0.8696
2026-04-05 05:37:51,793 - INFO - Epoch 2/100 - Train Loss: 0.5768 - Val Acc: 0.8551
2026-04-05 05:37:52,055 - INFO - Epoch 3/100 - Train Loss: 0.5064 - Val Acc: 0.8551
2026-04-05 05:37:52,328 - INFO - Epoch 4/100 - Train Loss: 0.4471 - Val Acc: 0.8696
2026-04-05 05:37:52,604 - INFO - Epoch 5/100 - Train Loss: 0.4095 - Val Acc: 0.8696
2026-04-05 05:37:52,872 - INFO - Epoch 6/100 - Train Loss: 0.3806 - Val Acc: 0.8696
2026-04-05 05:37:53,149 - INFO - Epoch 7/100 - Train Loss: 0.3663 - Val Acc: 0.8551
2026-04-05 05:37:53,418 - INFO - Epoch 8/100 - Train Loss: 0.3535 - Val Acc: 0.8551
2026-04-05 05:37:53,697 - INFO - Epoch 9/100 - Train Loss: 0.3444 - Val Acc: 0.8696
2026-04-05 05:37:53,962 - INFO - Epoch 10/100 - Train Loss: 0.3331 - Val Acc: 0.8696
2026-04-05 05:37:54,234 - INFO - Epoch 11/100 - Train Loss: 0.3290 - Val Acc: 0.8551
2026-04-05 05:37:54,511 - INFO - Epoch 12/100 - Train Loss: 0.3232 - Val Acc: 0.8696
2026-04-05 05:37:54,805 - INFO - Epoch 13/100 - Train Loss: 0.3190 - Val Acc: 0.8696
2026-04-05 05:37:55,081 - INFO - Epoch 14/100 - Train Loss: 0.3159 - Val Acc: 0.8696
2026-04-05 05:37:55,349 - INFO - Epoch 15/100 - Train Loss: 0.3124 - Val Acc: 0.8696
2026-04-05 05:37:55,607 - INFO - Epoch 16/100 - Train Loss: 0.3119 - Val Acc: 0.8696
2026-04-05 05:37:55,869 - INFO - Epoch 17/100 - Train Loss: 0.3093 - Val Acc: 0.8841
2026-04-05 05:37:56,135 - INFO - Epoch 18/100 - Train Loss: 0.3078 - Val Acc: 0.8841
2026-04-05 05:37:56,403 - INFO - Epoch 19/100 - Train Loss: 0.3053 - Val Acc: 0.8841
2026-04-05 05:37:56,659 - INFO - Epoch 20/100 - Train Loss: 0.3039 - Val Acc: 0.8841
2026-04-05 05:37:56,919 - INFO - Epoch 21/100 - Train Loss: 0.3040 - Val Acc: 0.8841
2026-04-05 05:37:57,177 - INFO - Epoch 22/100 - Train Loss: 0.3025 - Val Acc: 0.8841
2026-04-05 05:37:57,456 - INFO - Epoch 23/100 - Train Loss: 0.3017 - Val Acc: 0.8841
2026-04-05 05:37:57,717 - INFO - Epoch 24/100 - Train Loss: 0.2995 - Val Acc: 0.8841
2026-04-05 05:37:57,981 - INFO - Epoch 25/100 - Train Loss: 0.3002 - Val Acc: 0.8841
2026-04-05 05:37:58,247 - INFO - Epoch 26/100 - Train Loss: 0.2986 - Val Acc: 0.8841
2026-04-05 05:37:58,517 - INFO - Epoch 27/100 - Train Loss: 0.2978 - Val Acc: 0.8841
2026-04-05 05:37:58,778 - INFO - Epoch 28/100 - Train Loss: 0.2973 - Val Acc: 0.8841
2026-04-05 05:37:59,047 - INFO - Epoch 29/100 - Train Loss: 0.2951 - Val Acc: 0.8841
2026-04-05 05:37:59,313 - INFO - Epoch 30/100 - Train Loss: 0.2935 - Val Acc: 0.8841
2026-04-05 05:37:59,588 - INFO - Epoch 31/100 - Train Loss: 0.2898 - Val Acc: 0.8841
2026-04-05 05:37:59,891 - INFO - Epoch 32/100 - Train Loss: 0.2931 - Val Acc: 0.8841
2026-04-05 05:38:00,191 - INFO - Epoch 33/100 - Train Loss: 0.2932 - Val Acc: 0.8841
2026-04-05 05:38:00,450 - INFO - Epoch 34/100 - Train Loss: 0.2905 - Val Acc: 0.8841
2026-04-05 05:38:00,706 - INFO - Epoch 35/100 - Train Loss: 0.2899 - Val Acc: 0.8841
2026-04-05 05:38:00,966 - INFO - Epoch 36/100 - Train Loss: 0.2864 - Val Acc: 0.8841
2026-04-05 05:38:01,243 - INFO - Epoch 37/100 - Train Loss: 0.2876 - Val Acc: 0.8841
2026-04-05 05:38:01,508 - INFO - Epoch 38/100 - Train Loss: 0.2863 - Val Acc: 0.8986
2026-04-05 05:38:01,764 - INFO - Epoch 39/100 - Train Loss: 0.2837 - Val Acc: 0.8986
2026-04-05 05:38:02,030 - INFO - Epoch 40/100 - Train Loss: 0.2870 - Val Acc: 0.8986
2026-04-05 05:38:02,296 - INFO - Epoch 41/100 - Train Loss: 0.2828 - Val Acc: 0.8986
2026-04-05 05:38:02,558 - INFO - Epoch 42/100 - Train Loss: 0.2833 - Val Acc: 0.8841
2026-04-05 05:38:02,820 - INFO - Epoch 43/100 - Train Loss: 0.2807 - Val Acc: 0.8696
2026-04-05 05:38:03,076 - INFO - Epoch 44/100 - Train Loss: 0.2791 - Val Acc: 0.8696
2026-04-05 05:38:03,339 - INFO - Epoch 45/100 - Train Loss: 0.2803 - Val Acc: 0.8986
2026-04-05 05:38:03,593 - INFO - Epoch 46/100 - Train Loss: 0.2771 - Val Acc: 0.8696
2026-04-05 05:38:03,864 - INFO - Epoch 47/100 - Train Loss: 0.2767 - Val Acc: 0.8551
2026-04-05 05:38:04,131 - INFO - Epoch 48/100 - Train Loss: 0.2793 - Val Acc: 0.8696
2026-04-05 05:38:04,401 - INFO - Epoch 49/100 - Train Loss: 0.2753 - Val Acc: 0.8551
2026-04-05 05:38:04,705 - INFO - Epoch 50/100 - Train Loss: 0.2752 - Val Acc: 0.8551
2026-04-05 05:38:04,983 - INFO - Epoch 51/100 - Train Loss: 0.2708 - Val Acc: 0.8406
2026-04-05 05:38:05,248 - INFO - Epoch 52/100 - Train Loss: 0.2705 - Val Acc: 0.8551
2026-04-05 05:38:05,519 - INFO - Epoch 53/100 - Train Loss: 0.2681 - Val Acc: 0.8696
2026-04-05 05:38:05,782 - INFO - Epoch 54/100 - Train Loss: 0.2709 - Val Acc: 0.8696
2026-04-05 05:38:06,036 - INFO - Epoch 55/100 - Train Loss: 0.2693 - Val Acc: 0.8406
2026-04-05 05:38:06,301 - INFO - Epoch 56/100 - Train Loss: 0.2681 - Val Acc: 0.8551
2026-04-05 05:38:06,597 - INFO - Epoch 57/100 - Train Loss: 0.2662 - Val Acc: 0.8696
2026-04-05 05:38:06,870 - INFO - Epoch 58/100 - Train Loss: 0.2660 - Val Acc: 0.8551
2026-04-05 05:38:07,143 - INFO - Epoch 59/100 - Train Loss: 0.2651 - Val Acc: 0.8551
2026-04-05 05:38:07,415 - INFO - Epoch 60/100 - Train Loss: 0.2609 - Val Acc: 0.8696
2026-04-05 05:38:07,681 - INFO - Epoch 61/100 - Train Loss: 0.2637 - Val Acc: 0.8696
2026-04-05 05:38:07,941 - INFO - Epoch 62/100 - Train Loss: 0.2611 - Val Acc: 0.8696
2026-04-05 05:38:08,207 - INFO - Epoch 63/100 - Train Loss: 0.2643 - Val Acc: 0.8696
2026-04-05 05:38:08,471 - INFO - Epoch 64/100 - Train Loss: 0.2575 - Val Acc: 0.8551
2026-04-05 05:38:08,747 - INFO - Epoch 65/100 - Train Loss: 0.2592 - Val Acc: 0.8696
2026-04-05 05:38:09,020 - INFO - Epoch 66/100 - Train Loss: 0.2553 - Val Acc: 0.8841
2026-04-05 05:38:09,286 - INFO - Epoch 67/100 - Train Loss: 0.2555 - Val Acc: 0.8551
2026-04-05 05:38:09,560 - INFO - Epoch 68/100 - Train Loss: 0.2583 - Val Acc: 0.8841
2026-04-05 05:38:09,831 - INFO - Epoch 69/100 - Train Loss: 0.2574 - Val Acc: 0.8696
2026-04-05 05:38:10,107 - INFO - Epoch 70/100 - Train Loss: 0.2606 - Val Acc: 0.8696
2026-04-05 05:38:10,379 - INFO - Epoch 71/100 - Train Loss: 0.2531 - Val Acc: 0.8696
2026-04-05 05:38:10,653 - INFO - Epoch 72/100 - Train Loss: 0.2560 - Val Acc: 0.8406
2026-04-05 05:38:10,909 - INFO - Epoch 73/100 - Train Loss: 0.2556 - Val Acc: 0.8696
2026-04-05 05:38:11,186 - INFO - Epoch 74/100 - Train Loss: 0.2535 - Val Acc: 0.8696
2026-04-05 05:38:11,458 - INFO - Epoch 75/100 - Train Loss: 0.2468 - Val Acc: 0.8696
2026-04-05 05:38:11,747 - INFO - Epoch 76/100 - Train Loss: 0.2487 - Val Acc: 0.8696
2026-04-05 05:38:12,015 - INFO - Epoch 77/100 - Train Loss: 0.2497 - Val Acc: 0.8696
2026-04-05 05:38:12,285 - INFO - Epoch 78/100 - Train Loss: 0.2471 - Val Acc: 0.8696
2026-04-05 05:38:12,567 - INFO - Epoch 79/100 - Train Loss: 0.2463 - Val Acc: 0.8696
2026-04-05 05:38:12,838 - INFO - Epoch 80/100 - Train Loss: 0.2466 - Val Acc: 0.8696
2026-04-05 05:38:13,100 - INFO - Epoch 81/100 - Train Loss: 0.2426 - Val Acc: 0.8696
2026-04-05 05:38:13,355 - INFO - Epoch 82/100 - Train Loss: 0.2458 - Val Acc: 0.8696
2026-04-05 05:38:13,614 - INFO - Epoch 83/100 - Train Loss: 0.2459 - Val Acc: 0.8696
2026-04-05 05:38:13,876 - INFO - Epoch 84/100 - Train Loss: 0.2418 - Val Acc: 0.8551
2026-04-05 05:38:14,148 - INFO - Epoch 85/100 - Train Loss: 0.2430 - Val Acc: 0.8551
2026-04-05 05:38:14,422 - INFO - Epoch 86/100 - Train Loss: 0.2410 - Val Acc: 0.8696
2026-04-05 05:38:14,713 - INFO - Epoch 87/100 - Train Loss: 0.2417 - Val Acc: 0.8696
2026-04-05 05:38:14,983 - INFO - Epoch 88/100 - Train Loss: 0.2453 - Val Acc: 0.8696
2026-04-05 05:38:15,258 - INFO - Epoch 89/100 - Train Loss: 0.2460 - Val Acc: 0.8696
2026-04-05 05:38:15,531 - INFO - Epoch 90/100 - Train Loss: 0.2455 - Val Acc: 0.8696
2026-04-05 05:38:15,803 - INFO - Epoch 91/100 - Train Loss: 0.2389 - Val Acc: 0.8841
2026-04-05 05:38:16,070 - INFO - Epoch 92/100 - Train Loss: 0.2392 - Val Acc: 0.8696
2026-04-05 05:38:16,347 - INFO - Epoch 93/100 - Train Loss: 0.2392 - Val Acc: 0.8696
2026-04-05 05:38:16,624 - INFO - Epoch 94/100 - Train Loss: 0.2388 - Val Acc: 0.8696
2026-04-05 05:38:16,883 - INFO - Epoch 95/100 - Train Loss: 0.2323 - Val Acc: 0.8696
2026-04-05 05:38:17,152 - INFO - Epoch 96/100 - Train Loss: 0.2361 - Val Acc: 0.8696
2026-04-05 05:38:17,419 - INFO - Epoch 97/100 - Train Loss: 0.2384 - Val Acc: 0.8551
2026-04-05 05:38:17,688 - INFO - Epoch 98/100 - Train Loss: 0.2321 - Val Acc: 0.8551
2026-04-05 05:38:17,951 - INFO - Epoch 99/100 - Train Loss: 0.2337 - Val Acc: 0.8696
2026-04-05 05:38:18,207 - INFO - Epoch 100/100 - Train Loss: 0.2331 - Val Acc: 0.8696
2026-04-05 05:38:18,571 - INFO - Fold 6 logically complete. Tensor memory bounds cleared cleanly.
2026-04-05 05:38:18,575 - INFO - Original class distribution: [276 345]
2026-04-05 05:38:18,575 - INFO - Training device bound securely to: cuda

Fold 7:   0%|          | 0/100 [00:00<?, ?it/s]

2026-04-05 05:38:18,859 - INFO - Epoch 1/100 - Train Loss: 0.6530 - Val Acc: 0.7246
2026-04-05 05:38:19,120 - INFO - Epoch 2/100 - Train Loss: 0.5743 - Val Acc: 0.7101
2026-04-05 05:38:19,382 - INFO - Epoch 3/100 - Train Loss: 0.5029 - Val Acc: 0.7246
2026-04-05 05:38:19,640 - INFO - Epoch 4/100 - Train Loss: 0.4427 - Val Acc: 0.7246
2026-04-05 05:38:19,905 - INFO - Epoch 5/100 - Train Loss: 0.4007 - Val Acc: 0.7391
2026-04-05 05:38:20,182 - INFO - Epoch 6/100 - Train Loss: 0.3737 - Val Acc: 0.7391
2026-04-05 05:38:20,458 - INFO - Epoch 7/100 - Train Loss: 0.3563 - Val Acc: 0.7391
2026-04-05 05:38:20,719 - INFO - Epoch 8/100 - Train Loss: 0.3388 - Val Acc: 0.7391
2026-04-05 05:38:20,994 - INFO - Epoch 9/100 - Train Loss: 0.3275 - Val Acc: 0.7536
2026-04-05 05:38:21,253 - INFO - Epoch 10/100 - Train Loss: 0.3189 - Val Acc: 0.7536
2026-04-05 05:38:21,529 - INFO - Epoch 11/100 - Train Loss: 0.3094 - Val Acc: 0.7536
2026-04-05 05:38:21,796 - INFO - Epoch 12/100 - Train Loss: 0.3020 - Val Acc: 0.7536
2026-04-05 05:38:22,056 - INFO - Epoch 13/100 - Train Loss: 0.2987 - Val Acc: 0.7681
2026-04-05 05:38:22,316 - INFO - Epoch 14/100 - Train Loss: 0.2931 - Val Acc: 0.7826
2026-04-05 05:38:22,577 - INFO - Epoch 15/100 - Train Loss: 0.2884 - Val Acc: 0.7826
2026-04-05 05:38:22,845 - INFO - Epoch 16/100 - Train Loss: 0.2874 - Val Acc: 0.7971
2026-04-05 05:38:23,111 - INFO - Epoch 17/100 - Train Loss: 0.2847 - Val Acc: 0.7971
2026-04-05 05:38:23,374 - INFO - Epoch 18/100 - Train Loss: 0.2818 - Val Acc: 0.8116
2026-04-05 05:38:23,644 - INFO - Epoch 19/100 - Train Loss: 0.2824 - Val Acc: 0.8116
2026-04-05 05:38:23,914 - INFO - Epoch 20/100 - Train Loss: 0.2773 - Val Acc: 0.8116
2026-04-05 05:38:24,193 - INFO - Epoch 21/100 - Train Loss: 0.2804 - Val Acc: 0.7971
2026-04-05 05:38:24,457 - INFO - Epoch 22/100 - Train Loss: 0.2772 - Val Acc: 0.8261
2026-04-05 05:38:24,755 - INFO - Epoch 23/100 - Train Loss: 0.2747 - Val Acc: 0.8261
2026-04-05 05:38:25,022 - INFO - Epoch 24/100 - Train Loss: 0.2757 - Val Acc: 0.8261
2026-04-05 05:38:25,284 - INFO - Epoch 25/100 - Train Loss: 0.2745 - Val Acc: 0.8261
2026-04-05 05:38:25,543 - INFO - Epoch 26/100 - Train Loss: 0.2706 - Val Acc: 0.8116
2026-04-05 05:38:25,822 - INFO - Epoch 27/100 - Train Loss: 0.2716 - Val Acc: 0.8116
2026-04-05 05:38:26,084 - INFO - Epoch 28/100 - Train Loss: 0.2686 - Val Acc: 0.8261
2026-04-05 05:38:26,368 - INFO - Epoch 29/100 - Train Loss: 0.2682 - Val Acc: 0.8116
2026-04-05 05:38:26,645 - INFO - Epoch 30/100 - Train Loss: 0.2666 - Val Acc: 0.8261
2026-04-05 05:38:26,913 - INFO - Epoch 31/100 - Train Loss: 0.2682 - Val Acc: 0.7971
2026-04-05 05:38:27,187 - INFO - Epoch 32/100 - Train Loss: 0.2655 - Val Acc: 0.8261
2026-04-05 05:38:27,458 - INFO - Epoch 33/100 - Train Loss: 0.2632 - Val Acc: 0.8261
2026-04-05 05:38:27,730 - INFO - Epoch 34/100 - Train Loss: 0.2628 - Val Acc: 0.8116
2026-04-05 05:38:28,010 - INFO - Epoch 35/100 - Train Loss: 0.2643 - Val Acc: 0.8406
2026-04-05 05:38:28,273 - INFO - Epoch 36/100 - Train Loss: 0.2619 - Val Acc: 0.8406
2026-04-05 05:38:28,563 - INFO - Epoch 37/100 - Train Loss: 0.2610 - Val Acc: 0.8116
2026-04-05 05:38:28,839 - INFO - Epoch 38/100 - Train Loss: 0.2609 - Val Acc: 0.7971
2026-04-05 05:38:29,114 - INFO - Epoch 39/100 - Train Loss: 0.2593 - Val Acc: 0.8116
2026-04-05 05:38:29,394 - INFO - Epoch 40/100 - Train Loss: 0.2572 - Val Acc: 0.7826
2026-04-05 05:38:29,658 - INFO - Epoch 41/100 - Train Loss: 0.2557 - Val Acc: 0.7971
2026-04-05 05:38:29,930 - INFO - Epoch 42/100 - Train Loss: 0.2549 - Val Acc: 0.7826
2026-04-05 05:38:30,244 - INFO - Epoch 43/100 - Train Loss: 0.2565 - Val Acc: 0.7681
2026-04-05 05:38:30,526 - INFO - Epoch 44/100 - Train Loss: 0.2538 - Val Acc: 0.7681
2026-04-05 05:38:30,801 - INFO - Epoch 45/100 - Train Loss: 0.2548 - Val Acc: 0.7681
2026-04-05 05:38:31,067 - INFO - Epoch 46/100 - Train Loss: 0.2517 - Val Acc: 0.7681
2026-04-05 05:38:31,343 - INFO - Epoch 47/100 - Train Loss: 0.2550 - Val Acc: 0.7681
2026-04-05 05:38:31,620 - INFO - Epoch 48/100 - Train Loss: 0.2494 - Val Acc: 0.7681
2026-04-05 05:38:31,883 - INFO - Epoch 49/100 - Train Loss: 0.2510 - Val Acc: 0.7681
2026-04-05 05:38:32,155 - INFO - Epoch 50/100 - Train Loss: 0.2515 - Val Acc: 0.7681
2026-04-05 05:38:32,421 - INFO - Epoch 51/100 - Train Loss: 0.2464 - Val Acc: 0.7681
2026-04-05 05:38:32,691 - INFO - Epoch 52/100 - Train Loss: 0.2479 - Val Acc: 0.7681
2026-04-05 05:38:32,957 - INFO - Epoch 53/100 - Train Loss: 0.2493 - Val Acc: 0.7681
2026-04-05 05:38:33,220 - INFO - Epoch 54/100 - Train Loss: 0.2447 - Val Acc: 0.7681
2026-04-05 05:38:33,493 - INFO - Epoch 55/100 - Train Loss: 0.2414 - Val Acc: 0.7681
2026-04-05 05:38:33,780 - INFO - Epoch 56/100 - Train Loss: 0.2401 - Val Acc: 0.7681
2026-04-05 05:38:34,056 - INFO - Epoch 57/100 - Train Loss: 0.2437 - Val Acc: 0.7681
2026-04-05 05:38:34,322 - INFO - Epoch 58/100 - Train Loss: 0.2408 - Val Acc: 0.7681
2026-04-05 05:38:34,620 - INFO - Epoch 59/100 - Train Loss: 0.2404 - Val Acc: 0.7681
2026-04-05 05:38:34,918 - INFO - Epoch 60/100 - Train Loss: 0.2378 - Val Acc: 0.7681
2026-04-05 05:38:35,187 - INFO - Epoch 61/100 - Train Loss: 0.2391 - Val Acc: 0.7681
2026-04-05 05:38:35,468 - INFO - Epoch 62/100 - Train Loss: 0.2390 - Val Acc: 0.7681
2026-04-05 05:38:35,751 - INFO - Epoch 63/100 - Train Loss: 0.2396 - Val Acc: 0.7681
2026-04-05 05:38:36,034 - INFO - Epoch 64/100 - Train Loss: 0.2381 - Val Acc: 0.7681
2026-04-05 05:38:36,317 - INFO - Epoch 65/100 - Train Loss: 0.2375 - Val Acc: 0.7681
2026-04-05 05:38:36,597 - INFO - Epoch 66/100 - Train Loss: 0.2365 - Val Acc: 0.7681
2026-04-05 05:38:36,862 - INFO - Epoch 67/100 - Train Loss: 0.2357 - Val Acc: 0.7681
2026-04-05 05:38:37,128 - INFO - Epoch 68/100 - Train Loss: 0.2343 - Val Acc: 0.7681
2026-04-05 05:38:37,406 - INFO - Epoch 69/100 - Train Loss: 0.2335 - Val Acc: 0.7681
2026-04-05 05:38:37,672 - INFO - Epoch 70/100 - Train Loss: 0.2320 - Val Acc: 0.7681
2026-04-05 05:38:37,936 - INFO - Epoch 71/100 - Train Loss: 0.2320 - Val Acc: 0.7681
2026-04-05 05:38:38,193 - INFO - Epoch 72/100 - Train Loss: 0.2313 - Val Acc: 0.7681
2026-04-05 05:38:38,460 - INFO - Epoch 73/100 - Train Loss: 0.2299 - Val Acc: 0.7681
2026-04-05 05:38:38,724 - INFO - Epoch 74/100 - Train Loss: 0.2244 - Val Acc: 0.7681
2026-04-05 05:38:39,016 - INFO - Epoch 75/100 - Train Loss: 0.2275 - Val Acc: 0.7681
2026-04-05 05:38:39,288 - INFO - Epoch 76/100 - Train Loss: 0.2249 - Val Acc: 0.7681
2026-04-05 05:38:39,572 - INFO - Epoch 77/100 - Train Loss: 0.2218 - Val Acc: 0.7681
2026-04-05 05:38:39,854 - INFO - Epoch 78/100 - Train Loss: 0.2269 - Val Acc: 0.7681
2026-04-05 05:38:40,136 - INFO - Epoch 79/100 - Train Loss: 0.2252 - Val Acc: 0.7681
2026-04-05 05:38:40,410 - INFO - Epoch 80/100 - Train Loss: 0.2269 - Val Acc: 0.7681
2026-04-05 05:38:40,685 - INFO - Epoch 81/100 - Train Loss: 0.2230 - Val Acc: 0.7681
2026-04-05 05:38:40,967 - INFO - Epoch 82/100 - Train Loss: 0.2242 - Val Acc: 0.7681
2026-04-05 05:38:41,241 - INFO - Epoch 83/100 - Train Loss: 0.2220 - Val Acc: 0.7681
2026-04-05 05:38:41,504 - INFO - Epoch 84/100 - Train Loss: 0.2217 - Val Acc: 0.7681
2026-04-05 05:38:41,778 - INFO - Epoch 85/100 - Train Loss: 0.2206 - Val Acc: 0.7681
2026-04-05 05:38:42,047 - INFO - Epoch 86/100 - Train Loss: 0.2251 - Val Acc: 0.7681
2026-04-05 05:38:42,326 - INFO - Epoch 87/100 - Train Loss: 0.2191 - Val Acc: 0.7681
2026-04-05 05:38:42,597 - INFO - Epoch 88/100 - Train Loss: 0.2192 - Val Acc: 0.7681
2026-04-05 05:38:42,857 - INFO - Epoch 89/100 - Train Loss: 0.2198 - Val Acc: 0.7681
2026-04-05 05:38:43,130 - INFO - Epoch 90/100 - Train Loss: 0.2151 - Val Acc: 0.7681
2026-04-05 05:38:43,396 - INFO - Epoch 91/100 - Train Loss: 0.2179 - Val Acc: 0.7681
2026-04-05 05:38:43,662 - INFO - Epoch 92/100 - Train Loss: 0.2130 - Val Acc: 0.7681
2026-04-05 05:38:43,942 - INFO - Epoch 93/100 - Train Loss: 0.2189 - Val Acc: 0.7681
2026-04-05 05:38:44,211 - INFO - Epoch 94/100 - Train Loss: 0.2137 - Val Acc: 0.7681
2026-04-05 05:38:44,493 - INFO - Epoch 95/100 - Train Loss: 0.2117 - Val Acc: 0.7681
2026-04-05 05:38:44,801 - INFO - Epoch 96/100 - Train Loss: 0.2158 - Val Acc: 0.7681
2026-04-05 05:38:45,081 - INFO - Epoch 97/100 - Train Loss: 0.2130 - Val Acc: 0.7681
2026-04-05 05:38:45,349 - INFO - Epoch 98/100 - Train Loss: 0.2147 - Val Acc: 0.7681
2026-04-05 05:38:45,610 - INFO - Epoch 99/100 - Train Loss: 0.2112 - Val Acc: 0.7681
2026-04-05 05:38:45,882 - INFO - Epoch 100/100 - Train Loss: 0.2147 - Val Acc: 0.7681
2026-04-05 05:38:46,238 - INFO - Fold 7 logically complete. Tensor memory bounds cleared cleanly.
2026-04-05 05:38:46,242 - INFO - Original class distribution: [276 345]
2026-04-05 05:38:46,243 - INFO - Training device bound securely to: cuda

Fold 8:   0%|          | 0/100 [00:00<?, ?it/s]

2026-04-05 05:38:46,524 - INFO - Epoch 1/100 - Train Loss: 0.6687 - Val Acc: 0.8696
2026-04-05 05:38:46,798 - INFO - Epoch 2/100 - Train Loss: 0.5950 - Val Acc: 0.8551
2026-04-05 05:38:47,060 - INFO - Epoch 3/100 - Train Loss: 0.5215 - Val Acc: 0.8696
2026-04-05 05:38:47,319 - INFO - Epoch 4/100 - Train Loss: 0.4661 - Val Acc: 0.8551
2026-04-05 05:38:47,584 - INFO - Epoch 5/100 - Train Loss: 0.4209 - Val Acc: 0.8841
2026-04-05 05:38:47,845 - INFO - Epoch 6/100 - Train Loss: 0.3904 - Val Acc: 0.8841
2026-04-05 05:38:48,111 - INFO - Epoch 7/100 - Train Loss: 0.3716 - Val Acc: 0.8696
2026-04-05 05:38:48,372 - INFO - Epoch 8/100 - Train Loss: 0.3541 - Val Acc: 0.8261
2026-04-05 05:38:48,634 - INFO - Epoch 9/100 - Train Loss: 0.3447 - Val Acc: 0.8261
2026-04-05 05:38:48,903 - INFO - Epoch 10/100 - Train Loss: 0.3363 - Val Acc: 0.8261
2026-04-05 05:38:49,172 - INFO - Epoch 11/100 - Train Loss: 0.3275 - Val Acc: 0.8261
2026-04-05 05:38:49,440 - INFO - Epoch 12/100 - Train Loss: 0.3197 - Val Acc: 0.8261
2026-04-05 05:38:49,700 - INFO - Epoch 13/100 - Train Loss: 0.3154 - Val Acc: 0.8261
2026-04-05 05:38:49,965 - INFO - Epoch 14/100 - Train Loss: 0.3105 - Val Acc: 0.8261
2026-04-05 05:38:50,232 - INFO - Epoch 15/100 - Train Loss: 0.3089 - Val Acc: 0.8261
2026-04-05 05:38:50,498 - INFO - Epoch 16/100 - Train Loss: 0.3045 - Val Acc: 0.8406
2026-04-05 05:38:50,758 - INFO - Epoch 17/100 - Train Loss: 0.3057 - Val Acc: 0.8406
2026-04-05 05:38:51,020 - INFO - Epoch 18/100 - Train Loss: 0.3018 - Val Acc: 0.8406
2026-04-05 05:38:51,280 - INFO - Epoch 19/100 - Train Loss: 0.3024 - Val Acc: 0.8406
2026-04-05 05:38:51,553 - INFO - Epoch 20/100 - Train Loss: 0.2999 - Val Acc: 0.8406
2026-04-05 05:38:51,813 - INFO - Epoch 21/100 - Train Loss: 0.2990 - Val Acc: 0.8406
2026-04-05 05:38:52,076 - INFO - Epoch 22/100 - Train Loss: 0.2991 - Val Acc: 0.8406
2026-04-05 05:38:52,340 - INFO - Epoch 23/100 - Train Loss: 0.2984 - Val Acc: 0.8406
2026-04-05 05:38:52,601 - INFO - Epoch 24/100 - Train Loss: 0.2972 - Val Acc: 0.8406
2026-04-05 05:38:52,869 - INFO - Epoch 25/100 - Train Loss: 0.2933 - Val Acc: 0.8406
2026-04-05 05:38:53,133 - INFO - Epoch 26/100 - Train Loss: 0.2951 - Val Acc: 0.8406
2026-04-05 05:38:53,399 - INFO - Epoch 27/100 - Train Loss: 0.2949 - Val Acc: 0.8406
2026-04-05 05:38:53,669 - INFO - Epoch 28/100 - Train Loss: 0.2918 - Val Acc: 0.8406
2026-04-05 05:38:53,938 - INFO - Epoch 29/100 - Train Loss: 0.2935 - Val Acc: 0.8406
2026-04-05 05:38:54,222 - INFO - Epoch 30/100 - Train Loss: 0.2914 - Val Acc: 0.8406
2026-04-05 05:38:54,496 - INFO - Epoch 31/100 - Train Loss: 0.2917 - Val Acc: 0.8406
2026-04-05 05:38:54,776 - INFO - Epoch 32/100 - Train Loss: 0.2900 - Val Acc: 0.8406
2026-04-05 05:38:55,046 - INFO - Epoch 33/100 - Train Loss: 0.2883 - Val Acc: 0.8406
2026-04-05 05:38:55,312 - INFO - Epoch 34/100 - Train Loss: 0.2879 - Val Acc: 0.8406
2026-04-05 05:38:55,577 - INFO - Epoch 35/100 - Train Loss: 0.2861 - Val Acc: 0.8406
2026-04-05 05:38:55,835 - INFO - Epoch 36/100 - Train Loss: 0.2864 - Val Acc: 0.8406
2026-04-05 05:38:56,097 - INFO - Epoch 37/100 - Train Loss: 0.2867 - Val Acc: 0.8406
2026-04-05 05:38:56,359 - INFO - Epoch 38/100 - Train Loss: 0.2838 - Val Acc: 0.8406
2026-04-05 05:38:56,622 - INFO - Epoch 39/100 - Train Loss: 0.2817 - Val Acc: 0.8406
2026-04-05 05:38:56,895 - INFO - Epoch 40/100 - Train Loss: 0.2860 - Val Acc: 0.8406
2026-04-05 05:38:57,162 - INFO - Epoch 41/100 - Train Loss: 0.2815 - Val Acc: 0.8406
2026-04-05 05:38:57,417 - INFO - Epoch 42/100 - Train Loss: 0.2800 - Val Acc: 0.8406
2026-04-05 05:38:57,689 - INFO - Epoch 43/100 - Train Loss: 0.2783 - Val Acc: 0.8406
2026-04-05 05:38:57,963 - INFO - Epoch 44/100 - Train Loss: 0.2802 - Val Acc: 0.8406
2026-04-05 05:38:58,230 - INFO - Epoch 45/100 - Train Loss: 0.2779 - Val Acc: 0.8406
2026-04-05 05:38:58,485 - INFO - Epoch 46/100 - Train Loss: 0.2762 - Val Acc: 0.8406
2026-04-05 05:38:58,744 - INFO - Epoch 47/100 - Train Loss: 0.2765 - Val Acc: 0.8406
2026-04-05 05:38:59,013 - INFO - Epoch 48/100 - Train Loss: 0.2729 - Val Acc: 0.8406
2026-04-05 05:38:59,279 - INFO - Epoch 49/100 - Train Loss: 0.2771 - Val Acc: 0.8406
2026-04-05 05:38:59,538 - INFO - Epoch 50/100 - Train Loss: 0.2750 - Val Acc: 0.8406
2026-04-05 05:38:59,808 - INFO - Epoch 51/100 - Train Loss: 0.2741 - Val Acc: 0.8406
2026-04-05 05:39:00,080 - INFO - Epoch 52/100 - Train Loss: 0.2723 - Val Acc: 0.8406
2026-04-05 05:39:00,345 - INFO - Epoch 53/100 - Train Loss: 0.2698 - Val Acc: 0.8406
2026-04-05 05:39:00,600 - INFO - Epoch 54/100 - Train Loss: 0.2694 - Val Acc: 0.8406
2026-04-05 05:39:00,866 - INFO - Epoch 55/100 - Train Loss: 0.2692 - Val Acc: 0.8406
2026-04-05 05:39:01,140 - INFO - Epoch 56/100 - Train Loss: 0.2654 - Val Acc: 0.8406
2026-04-05 05:39:01,406 - INFO - Epoch 57/100 - Train Loss: 0.2619 - Val Acc: 0.8406
2026-04-05 05:39:01,667 - INFO - Epoch 58/100 - Train Loss: 0.2638 - Val Acc: 0.8406
2026-04-05 05:39:01,933 - INFO - Epoch 59/100 - Train Loss: 0.2649 - Val Acc: 0.8406
2026-04-05 05:39:02,208 - INFO - Epoch 60/100 - Train Loss: 0.2611 - Val Acc: 0.8261
2026-04-05 05:39:02,494 - INFO - Epoch 61/100 - Train Loss: 0.2597 - Val Acc: 0.8261
2026-04-05 05:39:02,755 - INFO - Epoch 62/100 - Train Loss: 0.2601 - Val Acc: 0.8261
2026-04-05 05:39:03,024 - INFO - Epoch 63/100 - Train Loss: 0.2595 - Val Acc: 0.8406
2026-04-05 05:39:03,301 - INFO - Epoch 64/100 - Train Loss: 0.2590 - Val Acc: 0.8406
2026-04-05 05:39:03,565 - INFO - Epoch 65/100 - Train Loss: 0.2590 - Val Acc: 0.8261
2026-04-05 05:39:03,833 - INFO - Epoch 66/100 - Train Loss: 0.2548 - Val Acc: 0.8406
2026-04-05 05:39:04,104 - INFO - Epoch 67/100 - Train Loss: 0.2569 - Val Acc: 0.8551
2026-04-05 05:39:04,374 - INFO - Epoch 68/100 - Train Loss: 0.2555 - Val Acc: 0.8406
2026-04-05 05:39:04,668 - INFO - Epoch 69/100 - Train Loss: 0.2495 - Val Acc: 0.8406
2026-04-05 05:39:04,937 - INFO - Epoch 70/100 - Train Loss: 0.2551 - Val Acc: 0.8551
2026-04-05 05:39:05,215 - INFO - Epoch 71/100 - Train Loss: 0.2503 - Val Acc: 0.8551
2026-04-05 05:39:05,481 - INFO - Epoch 72/100 - Train Loss: 0.2494 - Val Acc: 0.8551
2026-04-05 05:39:05,738 - INFO - Epoch 73/100 - Train Loss: 0.2539 - Val Acc: 0.8551
2026-04-05 05:39:06,013 - INFO - Epoch 74/100 - Train Loss: 0.2497 - Val Acc: 0.8551
2026-04-05 05:39:06,284 - INFO - Epoch 75/100 - Train Loss: 0.2501 - Val Acc: 0.8551
2026-04-05 05:39:06,556 - INFO - Epoch 76/100 - Train Loss: 0.2500 - Val Acc: 0.8406
2026-04-05 05:39:06,822 - INFO - Epoch 77/100 - Train Loss: 0.2481 - Val Acc: 0.8551
2026-04-05 05:39:07,088 - INFO - Epoch 78/100 - Train Loss: 0.2467 - Val Acc: 0.8551
2026-04-05 05:39:07,354 - INFO - Epoch 79/100 - Train Loss: 0.2469 - Val Acc: 0.8551
2026-04-05 05:39:07,618 - INFO - Epoch 80/100 - Train Loss: 0.2393 - Val Acc: 0.8406
2026-04-05 05:39:07,879 - INFO - Epoch 81/100 - Train Loss: 0.2472 - Val Acc: 0.8406
2026-04-05 05:39:08,152 - INFO - Epoch 82/100 - Train Loss: 0.2407 - Val Acc: 0.8551
2026-04-05 05:39:08,413 - INFO - Epoch 83/100 - Train Loss: 0.2429 - Val Acc: 0.8551
2026-04-05 05:39:08,680 - INFO - Epoch 84/100 - Train Loss: 0.2472 - Val Acc: 0.8551
2026-04-05 05:39:08,950 - INFO - Epoch 85/100 - Train Loss: 0.2425 - Val Acc: 0.8406
2026-04-05 05:39:09,216 - INFO - Epoch 86/100 - Train Loss: 0.2397 - Val Acc: 0.8406
2026-04-05 05:39:09,479 - INFO - Epoch 87/100 - Train Loss: 0.2387 - Val Acc: 0.8551
2026-04-05 05:39:09,751 - INFO - Epoch 88/100 - Train Loss: 0.2416 - Val Acc: 0.8406
2026-04-05 05:39:10,019 - INFO - Epoch 89/100 - Train Loss: 0.2394 - Val Acc: 0.8406
2026-04-05 05:39:10,299 - INFO - Epoch 90/100 - Train Loss: 0.2381 - Val Acc: 0.8406
2026-04-05 05:39:10,572 - INFO - Epoch 91/100 - Train Loss: 0.2335 - Val Acc: 0.8551
2026-04-05 05:39:10,839 - INFO - Epoch 92/100 - Train Loss: 0.2355 - Val Acc: 0.8551
2026-04-05 05:39:11,091 - INFO - Epoch 93/100 - Train Loss: 0.2333 - Val Acc: 0.8406
2026-04-05 05:39:11,361 - INFO - Epoch 94/100 - Train Loss: 0.2327 - Val Acc: 0.8406
2026-04-05 05:39:11,630 - INFO - Epoch 95/100 - Train Loss: 0.2378 - Val Acc: 0.8406
2026-04-05 05:39:11,892 - INFO - Epoch 96/100 - Train Loss: 0.2337 - Val Acc: 0.8551
2026-04-05 05:39:12,165 - INFO - Epoch 97/100 - Train Loss: 0.2350 - Val Acc: 0.8406
2026-04-05 05:39:12,448 - INFO - Epoch 98/100 - Train Loss: 0.2391 - Val Acc: 0.8406
2026-04-05 05:39:12,730 - INFO - Epoch 99/100 - Train Loss: 0.2349 - Val Acc: 0.8551
2026-04-05 05:39:13,010 - INFO - Epoch 100/100 - Train Loss: 0.2298 - Val Acc: 0.8406
2026-04-05 05:39:13,377 - INFO - Fold 8 logically complete. Tensor memory bounds cleared cleanly.
2026-04-05 05:39:13,381 - INFO - Original class distribution: [276 345]
2026-04-05 05:39:13,382 - INFO - Training device bound securely to: cuda

Fold 9:   0%|          | 0/100 [00:00<?, ?it/s]

2026-04-05 05:39:13,671 - INFO - Epoch 1/100 - Train Loss: 0.6640 - Val Acc: 0.7391
2026-04-05 05:39:13,942 - INFO - Epoch 2/100 - Train Loss: 0.5865 - Val Acc: 0.7826
2026-04-05 05:39:14,217 - INFO - Epoch 3/100 - Train Loss: 0.5156 - Val Acc: 0.7971
2026-04-05 05:39:14,493 - INFO - Epoch 4/100 - Train Loss: 0.4542 - Val Acc: 0.7971
2026-04-05 05:39:14,787 - INFO - Epoch 5/100 - Train Loss: 0.4102 - Val Acc: 0.7971
2026-04-05 05:39:15,049 - INFO - Epoch 6/100 - Train Loss: 0.3809 - Val Acc: 0.8406
2026-04-05 05:39:15,323 - INFO - Epoch 7/100 - Train Loss: 0.3612 - Val Acc: 0.8406
2026-04-05 05:39:15,595 - INFO - Epoch 8/100 - Train Loss: 0.3470 - Val Acc: 0.8261
2026-04-05 05:39:15,859 - INFO - Epoch 9/100 - Train Loss: 0.3347 - Val Acc: 0.8116
2026-04-05 05:39:16,118 - INFO - Epoch 10/100 - Train Loss: 0.3253 - Val Acc: 0.8261
2026-04-05 05:39:16,382 - INFO - Epoch 11/100 - Train Loss: 0.3184 - Val Acc: 0.8261
2026-04-05 05:39:16,650 - INFO - Epoch 12/100 - Train Loss: 0.3146 - Val Acc: 0.8261
2026-04-05 05:39:16,914 - INFO - Epoch 13/100 - Train Loss: 0.3091 - Val Acc: 0.8261
2026-04-05 05:39:17,196 - INFO - Epoch 14/100 - Train Loss: 0.3032 - Val Acc: 0.8261
2026-04-05 05:39:17,464 - INFO - Epoch 15/100 - Train Loss: 0.3003 - Val Acc: 0.8261
2026-04-05 05:39:17,736 - INFO - Epoch 16/100 - Train Loss: 0.3013 - Val Acc: 0.8116
2026-04-05 05:39:17,999 - INFO - Epoch 17/100 - Train Loss: 0.2967 - Val Acc: 0.8116
2026-04-05 05:39:18,270 - INFO - Epoch 18/100 - Train Loss: 0.2922 - Val Acc: 0.8116
2026-04-05 05:39:18,545 - INFO - Epoch 19/100 - Train Loss: 0.2946 - Val Acc: 0.8116
2026-04-05 05:39:18,813 - INFO - Epoch 20/100 - Train Loss: 0.2921 - Val Acc: 0.8116
2026-04-05 05:39:19,076 - INFO - Epoch 21/100 - Train Loss: 0.2924 - Val Acc: 0.8116
2026-04-05 05:39:19,350 - INFO - Epoch 22/100 - Train Loss: 0.2905 - Val Acc: 0.8261
2026-04-05 05:39:19,625 - INFO - Epoch 23/100 - Train Loss: 0.2886 - Val Acc: 0.8261
2026-04-05 05:39:19,894 - INFO - Epoch 24/100 - Train Loss: 0.2898 - Val Acc: 0.8261
2026-04-05 05:39:20,151 - INFO - Epoch 25/100 - Train Loss: 0.2904 - Val Acc: 0.8261
2026-04-05 05:39:20,421 - INFO - Epoch 26/100 - Train Loss: 0.2880 - Val Acc: 0.8261
2026-04-05 05:39:20,687 - INFO - Epoch 27/100 - Train Loss: 0.2836 - Val Acc: 0.8116
2026-04-05 05:39:20,958 - INFO - Epoch 28/100 - Train Loss: 0.2831 - Val Acc: 0.8261
2026-04-05 05:39:21,237 - INFO - Epoch 29/100 - Train Loss: 0.2824 - Val Acc: 0.8261
2026-04-05 05:39:21,511 - INFO - Epoch 30/100 - Train Loss: 0.2825 - Val Acc: 0.8261
2026-04-05 05:39:21,777 - INFO - Epoch 31/100 - Train Loss: 0.2825 - Val Acc: 0.8261
2026-04-05 05:39:22,048 - INFO - Epoch 32/100 - Train Loss: 0.2810 - Val Acc: 0.8261
2026-04-05 05:39:22,323 - INFO - Epoch 33/100 - Train Loss: 0.2820 - Val Acc: 0.8261
2026-04-05 05:39:22,596 - INFO - Epoch 34/100 - Train Loss: 0.2796 - Val Acc: 0.8261
2026-04-05 05:39:22,873 - INFO - Epoch 35/100 - Train Loss: 0.2802 - Val Acc: 0.8261
2026-04-05 05:39:23,145 - INFO - Epoch 36/100 - Train Loss: 0.2778 - Val Acc: 0.8261
2026-04-05 05:39:23,414 - INFO - Epoch 37/100 - Train Loss: 0.2789 - Val Acc: 0.8116
2026-04-05 05:39:23,700 - INFO - Epoch 38/100 - Train Loss: 0.2762 - Val Acc: 0.8261
2026-04-05 05:39:23,966 - INFO - Epoch 39/100 - Train Loss: 0.2742 - Val Acc: 0.8261
2026-04-05 05:39:24,260 - INFO - Epoch 40/100 - Train Loss: 0.2730 - Val Acc: 0.8261
2026-04-05 05:39:24,537 - INFO - Epoch 41/100 - Train Loss: 0.2736 - Val Acc: 0.8116
2026-04-05 05:39:24,809 - INFO - Epoch 42/100 - Train Loss: 0.2704 - Val Acc: 0.8116
2026-04-05 05:39:25,076 - INFO - Epoch 43/100 - Train Loss: 0.2742 - Val Acc: 0.8116
2026-04-05 05:39:25,340 - INFO - Epoch 44/100 - Train Loss: 0.2721 - Val Acc: 0.8116
2026-04-05 05:39:25,602 - INFO - Epoch 45/100 - Train Loss: 0.2714 - Val Acc: 0.8116
2026-04-05 05:39:25,873 - INFO - Epoch 46/100 - Train Loss: 0.2725 - Val Acc: 0.8261
2026-04-05 05:39:26,144 - INFO - Epoch 47/100 - Train Loss: 0.2677 - Val Acc: 0.8261
2026-04-05 05:39:26,410 - INFO - Epoch 48/100 - Train Loss: 0.2702 - Val Acc: 0.8261
2026-04-05 05:39:26,679 - INFO - Epoch 49/100 - Train Loss: 0.2675 - Val Acc: 0.8261
2026-04-05 05:39:26,937 - INFO - Epoch 50/100 - Train Loss: 0.2670 - Val Acc: 0.8261
2026-04-05 05:39:27,220 - INFO - Epoch 51/100 - Train Loss: 0.2660 - Val Acc: 0.8261
2026-04-05 05:39:27,481 - INFO - Epoch 52/100 - Train Loss: 0.2639 - Val Acc: 0.8261
2026-04-05 05:39:27,754 - INFO - Epoch 53/100 - Train Loss: 0.2647 - Val Acc: 0.8261
2026-04-05 05:39:28,019 - INFO - Epoch 54/100 - Train Loss: 0.2629 - Val Acc: 0.8261
2026-04-05 05:39:28,281 - INFO - Epoch 55/100 - Train Loss: 0.2624 - Val Acc: 0.8261
2026-04-05 05:39:28,545 - INFO - Epoch 56/100 - Train Loss: 0.2613 - Val Acc: 0.8261
2026-04-05 05:39:28,818 - INFO - Epoch 57/100 - Train Loss: 0.2575 - Val Acc: 0.8261
2026-04-05 05:39:29,080 - INFO - Epoch 58/100 - Train Loss: 0.2589 - Val Acc: 0.8261
2026-04-05 05:39:29,342 - INFO - Epoch 59/100 - Train Loss: 0.2576 - Val Acc: 0.8261
2026-04-05 05:39:29,608 - INFO - Epoch 60/100 - Train Loss: 0.2556 - Val Acc: 0.8261
2026-04-05 05:39:29,872 - INFO - Epoch 61/100 - Train Loss: 0.2577 - Val Acc: 0.8261
2026-04-05 05:39:30,146 - INFO - Epoch 62/100 - Train Loss: 0.2567 - Val Acc: 0.8261
2026-04-05 05:39:30,439 - INFO - Epoch 63/100 - Train Loss: 0.2517 - Val Acc: 0.8261
2026-04-05 05:39:30,732 - INFO - Epoch 64/100 - Train Loss: 0.2523 - Val Acc: 0.8116
2026-04-05 05:39:30,999 - INFO - Epoch 65/100 - Train Loss: 0.2520 - Val Acc: 0.8261
2026-04-05 05:39:31,260 - INFO - Epoch 66/100 - Train Loss: 0.2536 - Val Acc: 0.8261
2026-04-05 05:39:31,522 - INFO - Epoch 67/100 - Train Loss: 0.2517 - Val Acc: 0.8116
2026-04-05 05:39:31,792 - INFO - Epoch 68/100 - Train Loss: 0.2492 - Val Acc: 0.8116
2026-04-05 05:39:32,050 - INFO - Epoch 69/100 - Train Loss: 0.2513 - Val Acc: 0.8261
2026-04-05 05:39:32,323 - INFO - Epoch 70/100 - Train Loss: 0.2506 - Val Acc: 0.8261
2026-04-05 05:39:32,589 - INFO - Epoch 71/100 - Train Loss: 0.2434 - Val Acc: 0.8116
2026-04-05 05:39:32,856 - INFO - Epoch 72/100 - Train Loss: 0.2480 - Val Acc: 0.8116
2026-04-05 05:39:33,127 - INFO - Epoch 73/100 - Train Loss: 0.2486 - Val Acc: 0.8116
2026-04-05 05:39:33,394 - INFO - Epoch 74/100 - Train Loss: 0.2456 - Val Acc: 0.8116
2026-04-05 05:39:33,670 - INFO - Epoch 75/100 - Train Loss: 0.2460 - Val Acc: 0.8116
2026-04-05 05:39:33,930 - INFO - Epoch 76/100 - Train Loss: 0.2451 - Val Acc: 0.8116
2026-04-05 05:39:34,203 - INFO - Epoch 77/100 - Train Loss: 0.2441 - Val Acc: 0.8116
2026-04-05 05:39:34,473 - INFO - Epoch 78/100 - Train Loss: 0.2431 - Val Acc: 0.8116
2026-04-05 05:39:34,765 - INFO - Epoch 79/100 - Train Loss: 0.2413 - Val Acc: 0.8116
2026-04-05 05:39:35,029 - INFO - Epoch 80/100 - Train Loss: 0.2402 - Val Acc: 0.8116
2026-04-05 05:39:35,294 - INFO - Epoch 81/100 - Train Loss: 0.2398 - Val Acc: 0.8116
2026-04-05 05:39:35,563 - INFO - Epoch 82/100 - Train Loss: 0.2365 - Val Acc: 0.8116
2026-04-05 05:39:35,831 - INFO - Epoch 83/100 - Train Loss: 0.2411 - Val Acc: 0.8261
2026-04-05 05:39:36,095 - INFO - Epoch 84/100 - Train Loss: 0.2391 - Val Acc: 0.8261
2026-04-05 05:39:36,366 - INFO - Epoch 85/100 - Train Loss: 0.2356 - Val Acc: 0.8261
2026-04-05 05:39:36,639 - INFO - Epoch 86/100 - Train Loss: 0.2395 - Val Acc: 0.8261
2026-04-05 05:39:36,913 - INFO - Epoch 87/100 - Train Loss: 0.2300 - Val Acc: 0.8261
2026-04-05 05:39:37,191 - INFO - Epoch 88/100 - Train Loss: 0.2370 - Val Acc: 0.7971
2026-04-05 05:39:37,477 - INFO - Epoch 89/100 - Train Loss: 0.2327 - Val Acc: 0.8116
2026-04-05 05:39:37,743 - INFO - Epoch 90/100 - Train Loss: 0.2347 - Val Acc: 0.8116
2026-04-05 05:39:38,011 - INFO - Epoch 91/100 - Train Loss: 0.2375 - Val Acc: 0.8116
2026-04-05 05:39:38,282 - INFO - Epoch 92/100 - Train Loss: 0.2319 - Val Acc: 0.8261
2026-04-05 05:39:38,556 - INFO - Epoch 93/100 - Train Loss: 0.2288 - Val Acc: 0.8116
2026-04-05 05:39:38,824 - INFO - Epoch 94/100 - Train Loss: 0.2332 - Val Acc: 0.8406
2026-04-05 05:39:39,088 - INFO - Epoch 95/100 - Train Loss: 0.2273 - Val Acc: 0.8116
2026-04-05 05:39:39,348 - INFO - Epoch 96/100 - Train Loss: 0.2261 - Val Acc: 0.8261
2026-04-05 05:39:39,610 - INFO - Epoch 97/100 - Train Loss: 0.2314 - Val Acc: 0.8116
2026-04-05 05:39:39,885 - INFO - Epoch 98/100 - Train Loss: 0.2303 - Val Acc: 0.8261
2026-04-05 05:39:40,161 - INFO - Epoch 99/100 - Train Loss: 0.2221 - Val Acc: 0.8261
2026-04-05 05:39:40,433 - INFO - Epoch 100/100 - Train Loss: 0.2228 - Val Acc: 0.8116
2026-04-05 05:39:40,793 - INFO - Fold 9 logically complete. Tensor memory bounds cleared cleanly.
2026-04-05 05:39:40,797 - INFO - Original class distribution: [276 345]
2026-04-05 05:39:40,798 - INFO - Training device bound securely to: cuda

Fold 10:   0%|          | 0/100 [00:00<?, ?it/s]

2026-04-05 05:39:41,082 - INFO - Epoch 1/100 - Train Loss: 0.6682 - Val Acc: 0.8551
2026-04-05 05:39:41,342 - INFO - Epoch 2/100 - Train Loss: 0.5950 - Val Acc: 0.8841
2026-04-05 05:39:41,604 - INFO - Epoch 3/100 - Train Loss: 0.5265 - Val Acc: 0.8841
2026-04-05 05:39:41,887 - INFO - Epoch 4/100 - Train Loss: 0.4659 - Val Acc: 0.8841
2026-04-05 05:39:42,149 - INFO - Epoch 5/100 - Train Loss: 0.4195 - Val Acc: 0.8986
2026-04-05 05:39:42,419 - INFO - Epoch 6/100 - Train Loss: 0.3891 - Val Acc: 0.8986
2026-04-05 05:39:42,710 - INFO - Epoch 7/100 - Train Loss: 0.3720 - Val Acc: 0.8986
2026-04-05 05:39:42,988 - INFO - Epoch 8/100 - Train Loss: 0.3603 - Val Acc: 0.8986
2026-04-05 05:39:43,259 - INFO - Epoch 9/100 - Train Loss: 0.3522 - Val Acc: 0.8986
2026-04-05 05:39:43,522 - INFO - Epoch 10/100 - Train Loss: 0.3437 - Val Acc: 0.8986
2026-04-05 05:39:43,791 - INFO - Epoch 11/100 - Train Loss: 0.3362 - Val Acc: 0.8986
2026-04-05 05:39:44,071 - INFO - Epoch 12/100 - Train Loss: 0.3308 - Val Acc: 0.8986
2026-04-05 05:39:44,330 - INFO - Epoch 13/100 - Train Loss: 0.3274 - Val Acc: 0.9275
2026-04-05 05:39:44,625 - INFO - Epoch 14/100 - Train Loss: 0.3247 - Val Acc: 0.9275
2026-04-05 05:39:44,895 - INFO - Epoch 15/100 - Train Loss: 0.3221 - Val Acc: 0.9420
2026-04-05 05:39:45,163 - INFO - Epoch 16/100 - Train Loss: 0.3184 - Val Acc: 0.9420
2026-04-05 05:39:45,438 - INFO - Epoch 17/100 - Train Loss: 0.3157 - Val Acc: 0.9420
2026-04-05 05:39:45,697 - INFO - Epoch 18/100 - Train Loss: 0.3146 - Val Acc: 0.9420
2026-04-05 05:39:45,956 - INFO - Epoch 19/100 - Train Loss: 0.3144 - Val Acc: 0.9420
2026-04-05 05:39:46,218 - INFO - Epoch 20/100 - Train Loss: 0.3120 - Val Acc: 0.9565
2026-04-05 05:39:46,482 - INFO - Epoch 21/100 - Train Loss: 0.3126 - Val Acc: 0.9565
2026-04-05 05:39:46,762 - INFO - Epoch 22/100 - Train Loss: 0.3086 - Val Acc: 0.9565
2026-04-05 05:39:47,033 - INFO - Epoch 23/100 - Train Loss: 0.3103 - Val Acc: 0.9565
2026-04-05 05:39:47,305 - INFO - Epoch 24/100 - Train Loss: 0.3104 - Val Acc: 0.9565
2026-04-05 05:39:47,558 - INFO - Epoch 25/100 - Train Loss: 0.3097 - Val Acc: 0.9565
2026-04-05 05:39:47,818 - INFO - Epoch 26/100 - Train Loss: 0.3081 - Val Acc: 0.9565
2026-04-05 05:39:48,081 - INFO - Epoch 27/100 - Train Loss: 0.3071 - Val Acc: 0.9565
2026-04-05 05:39:48,357 - INFO - Epoch 28/100 - Train Loss: 0.3062 - Val Acc: 0.9565
2026-04-05 05:39:48,621 - INFO - Epoch 29/100 - Train Loss: 0.3034 - Val Acc: 0.9565
2026-04-05 05:39:48,895 - INFO - Epoch 30/100 - Train Loss: 0.3027 - Val Acc: 0.9565
2026-04-05 05:39:49,165 - INFO - Epoch 31/100 - Train Loss: 0.3012 - Val Acc: 0.9565
2026-04-05 05:39:49,441 - INFO - Epoch 32/100 - Train Loss: 0.3017 - Val Acc: 0.9565
2026-04-05 05:39:49,710 - INFO - Epoch 33/100 - Train Loss: 0.2991 - Val Acc: 0.9565
2026-04-05 05:39:49,977 - INFO - Epoch 34/100 - Train Loss: 0.2975 - Val Acc: 0.9565
2026-04-05 05:39:50,248 - INFO - Epoch 35/100 - Train Loss: 0.2980 - Val Acc: 0.9565
2026-04-05 05:39:50,523 - INFO - Epoch 36/100 - Train Loss: 0.2973 - Val Acc: 0.9565
2026-04-05 05:39:50,793 - INFO - Epoch 37/100 - Train Loss: 0.2973 - Val Acc: 0.9565
2026-04-05 05:39:51,067 - INFO - Epoch 38/100 - Train Loss: 0.2958 - Val Acc: 0.9565
2026-04-05 05:39:51,332 - INFO - Epoch 39/100 - Train Loss: 0.2946 - Val Acc: 0.9565
2026-04-05 05:39:51,596 - INFO - Epoch 40/100 - Train Loss: 0.2935 - Val Acc: 0.9565
2026-04-05 05:39:51,869 - INFO - Epoch 41/100 - Train Loss: 0.2922 - Val Acc: 0.9565
2026-04-05 05:39:52,146 - INFO - Epoch 42/100 - Train Loss: 0.2922 - Val Acc: 0.9565
2026-04-05 05:39:52,408 - INFO - Epoch 43/100 - Train Loss: 0.2907 - Val Acc: 0.9565
2026-04-05 05:39:52,665 - INFO - Epoch 44/100 - Train Loss: 0.2904 - Val Acc: 0.9565
2026-04-05 05:39:52,935 - INFO - Epoch 45/100 - Train Loss: 0.2918 - Val Acc: 0.9565
2026-04-05 05:39:53,209 - INFO - Epoch 46/100 - Train Loss: 0.2903 - Val Acc: 0.9565
2026-04-05 05:39:53,472 - INFO - Epoch 47/100 - Train Loss: 0.2869 - Val Acc: 0.9565
2026-04-05 05:39:53,732 - INFO - Epoch 48/100 - Train Loss: 0.2856 - Val Acc: 0.9565
2026-04-05 05:39:54,007 - INFO - Epoch 49/100 - Train Loss: 0.2839 - Val Acc: 0.9565
2026-04-05 05:39:54,284 - INFO - Epoch 50/100 - Train Loss: 0.2849 - Val Acc: 0.9565
2026-04-05 05:39:54,585 - INFO - Epoch 51/100 - Train Loss: 0.2860 - Val Acc: 0.9565
2026-04-05 05:39:54,854 - INFO - Epoch 52/100 - Train Loss: 0.2793 - Val Acc: 0.9565
2026-04-05 05:39:55,134 - INFO - Epoch 53/100 - Train Loss: 0.2769 - Val Acc: 0.9565
2026-04-05 05:39:55,401 - INFO - Epoch 54/100 - Train Loss: 0.2779 - Val Acc: 0.9565
2026-04-05 05:39:55,680 - INFO - Epoch 55/100 - Train Loss: 0.2761 - Val Acc: 0.9565
2026-04-05 05:39:55,950 - INFO - Epoch 56/100 - Train Loss: 0.2725 - Val Acc: 0.9565
2026-04-05 05:39:56,212 - INFO - Epoch 57/100 - Train Loss: 0.2775 - Val Acc: 0.9565
2026-04-05 05:39:56,480 - INFO - Epoch 58/100 - Train Loss: 0.2771 - Val Acc: 0.9565
2026-04-05 05:39:56,748 - INFO - Epoch 59/100 - Train Loss: 0.2743 - Val Acc: 0.9565
2026-04-05 05:39:57,034 - INFO - Epoch 60/100 - Train Loss: 0.2728 - Val Acc: 0.9565
2026-04-05 05:39:57,312 - INFO - Epoch 61/100 - Train Loss: 0.2733 - Val Acc: 0.9565
2026-04-05 05:39:57,585 - INFO - Epoch 62/100 - Train Loss: 0.2696 - Val Acc: 0.9565
2026-04-05 05:39:57,861 - INFO - Epoch 63/100 - Train Loss: 0.2685 - Val Acc: 0.9565
2026-04-05 05:39:58,124 - INFO - Epoch 64/100 - Train Loss: 0.2644 - Val Acc: 0.9565
2026-04-05 05:39:58,390 - INFO - Epoch 65/100 - Train Loss: 0.2655 - Val Acc: 0.9565
2026-04-05 05:39:58,659 - INFO - Epoch 66/100 - Train Loss: 0.2686 - Val Acc: 0.9710
2026-04-05 05:39:58,941 - INFO - Epoch 67/100 - Train Loss: 0.2655 - Val Acc: 0.9710
2026-04-05 05:39:59,205 - INFO - Epoch 68/100 - Train Loss: 0.2673 - Val Acc: 0.9565
2026-04-05 05:39:59,479 - INFO - Epoch 69/100 - Train Loss: 0.2643 - Val Acc: 0.9565
2026-04-05 05:39:59,758 - INFO - Epoch 70/100 - Train Loss: 0.2611 - Val Acc: 0.9565
2026-04-05 05:40:00,032 - INFO - Epoch 71/100 - Train Loss: 0.2639 - Val Acc: 0.9565
2026-04-05 05:40:00,298 - INFO - Epoch 72/100 - Train Loss: 0.2604 - Val Acc: 0.9710
2026-04-05 05:40:00,575 - INFO - Epoch 73/100 - Train Loss: 0.2617 - Val Acc: 0.9710
2026-04-05 05:40:00,858 - INFO - Epoch 74/100 - Train Loss: 0.2595 - Val Acc: 0.9710
2026-04-05 05:40:01,126 - INFO - Epoch 75/100 - Train Loss: 0.2584 - Val Acc: 0.9565
2026-04-05 05:40:01,398 - INFO - Epoch 76/100 - Train Loss: 0.2571 - Val Acc: 0.9565
2026-04-05 05:40:01,668 - INFO - Epoch 77/100 - Train Loss: 0.2573 - Val Acc: 0.9565
2026-04-05 05:40:01,942 - INFO - Epoch 78/100 - Train Loss: 0.2567 - Val Acc: 0.9565
2026-04-05 05:40:02,214 - INFO - Epoch 79/100 - Train Loss: 0.2583 - Val Acc: 0.9710
2026-04-05 05:40:02,481 - INFO - Epoch 80/100 - Train Loss: 0.2515 - Val Acc: 0.9565
2026-04-05 05:40:02,759 - INFO - Epoch 81/100 - Train Loss: 0.2568 - Val Acc: 0.9710
2026-04-05 05:40:03,036 - INFO - Epoch 82/100 - Train Loss: 0.2566 - Val Acc: 0.9565
2026-04-05 05:40:03,305 - INFO - Epoch 83/100 - Train Loss: 0.2534 - Val Acc: 0.9565
2026-04-05 05:40:03,569 - INFO - Epoch 84/100 - Train Loss: 0.2545 - Val Acc: 0.9710
2026-04-05 05:40:03,852 - INFO - Epoch 85/100 - Train Loss: 0.2502 - Val Acc: 0.9710
2026-04-05 05:40:04,135 - INFO - Epoch 86/100 - Train Loss: 0.2491 - Val Acc: 0.9710
2026-04-05 05:40:04,416 - INFO - Epoch 87/100 - Train Loss: 0.2505 - Val Acc: 0.9565
2026-04-05 05:40:04,715 - INFO - Epoch 88/100 - Train Loss: 0.2487 - Val Acc: 0.9565
2026-04-05 05:40:04,994 - INFO - Epoch 89/100 - Train Loss: 0.2479 - Val Acc: 0.9710
2026-04-05 05:40:05,260 - INFO - Epoch 90/100 - Train Loss: 0.2503 - Val Acc: 0.9710
2026-04-05 05:40:05,529 - INFO - Epoch 91/100 - Train Loss: 0.2444 - Val Acc: 0.9710
2026-04-05 05:40:05,805 - INFO - Epoch 92/100 - Train Loss: 0.2452 - Val Acc: 0.9565
2026-04-05 05:40:06,080 - INFO - Epoch 93/100 - Train Loss: 0.2445 - Val Acc: 0.9710
2026-04-05 05:40:06,356 - INFO - Epoch 94/100 - Train Loss: 0.2473 - Val Acc: 0.9710
2026-04-05 05:40:06,617 - INFO - Epoch 95/100 - Train Loss: 0.2465 - Val Acc: 0.9710
2026-04-05 05:40:06,885 - INFO - Epoch 96/100 - Train Loss: 0.2451 - Val Acc: 0.9710
2026-04-05 05:40:07,154 - INFO - Epoch 97/100 - Train Loss: 0.2499 - Val Acc: 0.9565
2026-04-05 05:40:07,423 - INFO - Epoch 98/100 - Train Loss: 0.2421 - Val Acc: 0.9710
2026-04-05 05:40:07,701 - INFO - Epoch 99/100 - Train Loss: 0.2406 - Val Acc: 0.9710
2026-04-05 05:40:07,972 - INFO - Epoch 100/100 - Train Loss: 0.2406 - Val Acc: 0.9565
2026-04-05 05:40:08,322 - INFO - Fold 10 logically complete. Tensor memory bounds cleared cleanly.
2026-04-05 05:40:08,339 - INFO - ✓ Completed GRU_baseline
2026-04-05 05:40:08,339 - INFO -   Mean Accuracy: 0.8942 ± 0.0405
2026-04-05 05:40:08,340 - INFO -
EXPERIMENT: GRU_SMOTEENN | german | SMOTE-ENN: True

German | GRU | SMOTEENN:   0%|          | 0/10 [00:00<?, ?it/s]

2026-04-05 05:40:08,353 - INFO - Original class distribution: [277 344]
2026-04-05 05:40:08,354 - INFO - Training device bound securely to: cuda
2026-04-05 05:40:08,370 - INFO - After SMOTE-ENN deployment: [344 289]

Fold 1:   0%|          | 0/100 [00:00<?, ?it/s]

2026-04-05 05:40:08,651 - INFO - Epoch 1/100 - Train Loss: 0.6500 - Val Acc: 0.8261
2026-04-05 05:40:08,912 - INFO - Epoch 2/100 - Train Loss: 0.5659 - Val Acc: 0.8406
2026-04-05 05:40:09,171 - INFO - Epoch 3/100 - Train Loss: 0.4857 - Val Acc: 0.8406
2026-04-05 05:40:09,445 - INFO - Epoch 4/100 - Train Loss: 0.4125 - Val Acc: 0.8406
2026-04-05 05:40:09,709 - INFO - Epoch 5/100 - Train Loss: 0.3568 - Val Acc: 0.8406
2026-04-05 05:40:09,978 - INFO - Epoch 6/100 - Train Loss: 0.3163 - Val Acc: 0.8551
2026-04-05 05:40:10,254 - INFO - Epoch 7/100 - Train Loss: 0.2888 - Val Acc: 0.8551
2026-04-05 05:40:10,517 - INFO - Epoch 8/100 - Train Loss: 0.2684 - Val Acc: 0.8551
2026-04-05 05:40:10,786 - INFO - Epoch 9/100 - Train Loss: 0.2512 - Val Acc: 0.8551
2026-04-05 05:40:11,055 - INFO - Epoch 10/100 - Train Loss: 0.2383 - Val Acc: 0.8551
2026-04-05 05:40:11,320 - INFO - Epoch 11/100 - Train Loss: 0.2283 - Val Acc: 0.8551
2026-04-05 05:40:11,594 - INFO - Epoch 12/100 - Train Loss: 0.2180 - Val Acc: 0.8696
2026-04-05 05:40:11,857 - INFO - Epoch 13/100 - Train Loss: 0.2106 - Val Acc: 0.8696
2026-04-05 05:40:12,126 - INFO - Epoch 14/100 - Train Loss: 0.2056 - Val Acc: 0.8696
2026-04-05 05:40:12,415 - INFO - Epoch 15/100 - Train Loss: 0.2014 - Val Acc: 0.8841
2026-04-05 05:40:12,701 - INFO - Epoch 16/100 - Train Loss: 0.1969 - Val Acc: 0.8841
2026-04-05 05:40:12,965 - INFO - Epoch 17/100 - Train Loss: 0.1939 - Val Acc: 0.8841
2026-04-05 05:40:13,229 - INFO - Epoch 18/100 - Train Loss: 0.1903 - Val Acc: 0.8696
2026-04-05 05:40:13,503 - INFO - Epoch 19/100 - Train Loss: 0.1889 - Val Acc: 0.8696
2026-04-05 05:40:13,773 - INFO - Epoch 20/100 - Train Loss: 0.1898 - Val Acc: 0.8841
2026-04-05 05:40:14,050 - INFO - Epoch 21/100 - Train Loss: 0.1863 - Val Acc: 0.8841
2026-04-05 05:40:14,318 - INFO - Epoch 22/100 - Train Loss: 0.1848 - Val Acc: 0.8841
2026-04-05 05:40:14,607 - INFO - Epoch 23/100 - Train Loss: 0.1848 - Val Acc: 0.8841
2026-04-05 05:40:14,873 - INFO - Epoch 24/100 - Train Loss: 0.1814 - Val Acc: 0.8841
2026-04-05 05:40:15,133 - INFO - Epoch 25/100 - Train Loss: 0.1834 - Val Acc: 0.8841
2026-04-05 05:40:15,400 - INFO - Epoch 26/100 - Train Loss: 0.1829 - Val Acc: 0.8841
2026-04-05 05:40:15,672 - INFO - Epoch 27/100 - Train Loss: 0.1787 - Val Acc: 0.8841
2026-04-05 05:40:15,954 - INFO - Epoch 28/100 - Train Loss: 0.1756 - Val Acc: 0.8841
2026-04-05 05:40:16,236 - INFO - Epoch 29/100 - Train Loss: 0.1763 - Val Acc: 0.8841
2026-04-05 05:40:16,503 - INFO - Epoch 30/100 - Train Loss: 0.1754 - Val Acc: 0.8841
2026-04-05 05:40:16,782 - INFO - Epoch 31/100 - Train Loss: 0.1764 - Val Acc: 0.8986
2026-04-05 05:40:17,057 - INFO - Epoch 32/100 - Train Loss: 0.1755 - Val Acc: 0.8841
2026-04-05 05:40:17,315 - INFO - Epoch 33/100 - Train Loss: 0.1750 - Val Acc: 0.8841
2026-04-05 05:40:17,581 - INFO - Epoch 34/100 - Train Loss: 0.1726 - Val Acc: 0.8986
2026-04-05 05:40:17,842 - INFO - Epoch 35/100 - Train Loss: 0.1700 - Val Acc: 0.8986
2026-04-05 05:40:18,112 - INFO - Epoch 36/100 - Train Loss: 0.1691 - Val Acc: 0.8986
2026-04-05 05:40:18,384 - INFO - Epoch 37/100 - Train Loss: 0.1694 - Val Acc: 0.8986
2026-04-05 05:40:18,653 - INFO - Epoch 38/100 - Train Loss: 0.1659 - Val Acc: 0.8986
2026-04-05 05:40:18,921 - INFO - Epoch 39/100 - Train Loss: 0.1668 - Val Acc: 0.8986
2026-04-05 05:40:19,185 - INFO - Epoch 40/100 - Train Loss: 0.1666 - Val Acc: 0.8986
2026-04-05 05:40:19,454 - INFO - Epoch 41/100 - Train Loss: 0.1655 - Val Acc: 0.8986
2026-04-05 05:40:19,719 - INFO - Epoch 42/100 - Train Loss: 0.1655 - Val Acc: 0.8986
2026-04-05 05:40:19,977 - INFO - Epoch 43/100 - Train Loss: 0.1649 - Val Acc: 0.8986
2026-04-05 05:40:20,239 - INFO - Epoch 44/100 - Train Loss: 0.1658 - Val Acc: 0.8986
2026-04-05 05:40:20,509 - INFO - Epoch 45/100 - Train Loss: 0.1615 - Val Acc: 0.8986
2026-04-05 05:40:20,788 - INFO - Epoch 46/100 - Train Loss: 0.1604 - Val Acc: 0.8986
2026-04-05 05:40:21,063 - INFO - Epoch 47/100 - Train Loss: 0.1616 - Val Acc: 0.8986
2026-04-05 05:40:21,342 - INFO - Epoch 48/100 - Train Loss: 0.1597 - Val Acc: 0.8986
2026-04-05 05:40:21,616 - INFO - Epoch 49/100 - Train Loss: 0.1589 - Val Acc: 0.8986
2026-04-05 05:40:21,883 - INFO - Epoch 50/100 - Train Loss: 0.1593 - Val Acc: 0.8986
2026-04-05 05:40:22,156 - INFO - Epoch 51/100 - Train Loss: 0.1556 - Val Acc: 0.8986
2026-04-05 05:40:22,416 - INFO - Epoch 52/100 - Train Loss: 0.1566 - Val Acc: 0.8986
2026-04-05 05:40:22,686 - INFO - Epoch 53/100 - Train Loss: 0.1549 - Val Acc: 0.8986
2026-04-05 05:40:22,974 - INFO - Epoch 54/100 - Train Loss: 0.1543 - Val Acc: 0.8986
2026-04-05 05:40:23,246 - INFO - Epoch 55/100 - Train Loss: 0.1533 - Val Acc: 0.8841
2026-04-05 05:40:23,534 - INFO - Epoch 56/100 - Train Loss: 0.1497 - Val Acc: 0.8841
2026-04-05 05:40:23,802 - INFO - Epoch 57/100 - Train Loss: 0.1535 - Val Acc: 0.8841
2026-04-05 05:40:24,073 - INFO - Epoch 58/100 - Train Loss: 0.1517 - Val Acc: 0.8986
2026-04-05 05:40:24,355 - INFO - Epoch 59/100 - Train Loss: 0.1501 - Val Acc: 0.8841
2026-04-05 05:40:24,657 - INFO - Epoch 60/100 - Train Loss: 0.1501 - Val Acc: 0.8986
2026-04-05 05:40:24,929 - INFO - Epoch 61/100 - Train Loss: 0.1500 - Val Acc: 0.8841
2026-04-05 05:40:25,198 - INFO - Epoch 62/100 - Train Loss: 0.1451 - Val Acc: 0.8841
2026-04-05 05:40:25,465 - INFO - Epoch 63/100 - Train Loss: 0.1447 - Val Acc: 0.8841
2026-04-05 05:40:25,748 - INFO - Epoch 64/100 - Train Loss: 0.1450 - Val Acc: 0.8841
2026-04-05 05:40:26,020 - INFO - Epoch 65/100 - Train Loss: 0.1455 - Val Acc: 0.8841
2026-04-05 05:40:26,280 - INFO - Epoch 66/100 - Train Loss: 0.1430 - Val Acc: 0.8841
2026-04-05 05:40:26,550 - INFO - Epoch 67/100 - Train Loss: 0.1455 - Val Acc: 0.8696
2026-04-05 05:40:26,815 - INFO - Epoch 68/100 - Train Loss: 0.1439 - Val Acc: 0.8696
2026-04-05 05:40:27,081 - INFO - Epoch 69/100 - Train Loss: 0.1415 - Val Acc: 0.8696
2026-04-05 05:40:27,346 - INFO - Epoch 70/100 - Train Loss: 0.1424 - Val Acc: 0.8696
2026-04-05 05:40:27,627 - INFO - Epoch 71/100 - Train Loss: 0.1361 - Val Acc: 0.8696
2026-04-05 05:40:27,891 - INFO - Epoch 72/100 - Train Loss: 0.1382 - Val Acc: 0.8696
2026-04-05 05:40:28,164 - INFO - Epoch 73/100 - Train Loss: 0.1367 - Val Acc: 0.8696
2026-04-05 05:40:28,431 - INFO - Epoch 74/100 - Train Loss: 0.1413 - Val Acc: 0.8696
2026-04-05 05:40:28,700 - INFO - Epoch 75/100 - Train Loss: 0.1348 - Val Acc: 0.8696
2026-04-05 05:40:28,974 - INFO - Epoch 76/100 - Train Loss: 0.1369 - Val Acc: 0.8696
2026-04-05 05:40:29,258 - INFO - Epoch 77/100 - Train Loss: 0.1366 - Val Acc: 0.8696
2026-04-05 05:40:29,531 - INFO - Epoch 78/100 - Train Loss: 0.1314 - Val Acc: 0.8696
2026-04-05 05:40:29,809 - INFO - Epoch 79/100 - Train Loss: 0.1337 - Val Acc: 0.8696
2026-04-05 05:40:30,078 - INFO - Epoch 80/100 - Train Loss: 0.1338 - Val Acc: 0.8696
2026-04-05 05:40:30,353 - INFO - Epoch 81/100 - Train Loss: 0.1303 - Val Acc: 0.8696
2026-04-05 05:40:30,633 - INFO - Epoch 82/100 - Train Loss: 0.1310 - Val Acc: 0.8696
2026-04-05 05:40:30,909 - INFO - Epoch 83/100 - Train Loss: 0.1316 - Val Acc: 0.8696
2026-04-05 05:40:31,169 - INFO - Epoch 84/100 - Train Loss: 0.1307 - Val Acc: 0.8696
2026-04-05 05:40:31,434 - INFO - Epoch 85/100 - Train Loss: 0.1268 - Val Acc: 0.8696
2026-04-05 05:40:31,706 - INFO - Epoch 86/100 - Train Loss: 0.1243 - Val Acc: 0.8696
2026-04-05 05:40:31,972 - INFO - Epoch 87/100 - Train Loss: 0.1252 - Val Acc: 0.8696
2026-04-05 05:40:32,233 - INFO - Epoch 88/100 - Train Loss: 0.1264 - Val Acc: 0.8696
2026-04-05 05:40:32,505 - INFO - Epoch 89/100 - Train Loss: 0.1239 - Val Acc: 0.8696
2026-04-05 05:40:32,769 - INFO - Epoch 90/100 - Train Loss: 0.1245 - Val Acc: 0.8696
2026-04-05 05:40:33,032 - INFO - Epoch 91/100 - Train Loss: 0.1209 - Val Acc: 0.8696
2026-04-05 05:40:33,292 - INFO - Epoch 92/100 - Train Loss: 0.1237 - Val Acc: 0.8696
2026-04-05 05:40:33,557 - INFO - Epoch 93/100 - Train Loss: 0.1222 - Val Acc: 0.8696
2026-04-05 05:40:33,836 - INFO - Epoch 94/100 - Train Loss: 0.1241 - Val Acc: 0.8696
2026-04-05 05:40:34,096 - INFO - Epoch 95/100 - Train Loss: 0.1273 - Val Acc: 0.8696
2026-04-05 05:40:34,362 - INFO - Epoch 96/100 - Train Loss: 0.1190 - Val Acc: 0.8696
2026-04-05 05:40:34,665 - INFO - Epoch 97/100 - Train Loss: 0.1198 - Val Acc: 0.8696
2026-04-05 05:40:34,965 - INFO - Epoch 98/100 - Train Loss: 0.1184 - Val Acc: 0.8696
2026-04-05 05:40:35,241 - INFO - Epoch 99/100 - Train Loss: 0.1161 - Val Acc: 0.8696
2026-04-05 05:40:35,529 - INFO - Epoch 100/100 - Train Loss: 0.1178 - Val Acc: 0.8696
2026-04-05 05:40:35,895 - INFO - Fold 1 logically complete. Tensor memory bounds cleared cleanly.
2026-04-05 05:40:35,899 - INFO - Original class distribution: [277 344]
2026-04-05 05:40:35,899 - INFO - Training device bound securely to: cuda
2026-04-05 05:40:35,916 - INFO - After SMOTE-ENN deployment: [344 288]

Fold 2:   0%|          | 0/100 [00:00<?, ?it/s]

2026-04-05 05:40:36,218 - INFO - Epoch 1/100 - Train Loss: 0.6594 - Val Acc: 0.8551
2026-04-05 05:40:36,501 - INFO - Epoch 2/100 - Train Loss: 0.5758 - Val Acc: 0.8551
2026-04-05 05:40:36,778 - INFO - Epoch 3/100 - Train Loss: 0.4947 - Val Acc: 0.8696
2026-04-05 05:40:37,057 - INFO - Epoch 4/100 - Train Loss: 0.4203 - Val Acc: 0.8406
2026-04-05 05:40:37,335 - INFO - Epoch 5/100 - Train Loss: 0.3633 - Val Acc: 0.8406
2026-04-05 05:40:37,610 - INFO - Epoch 6/100 - Train Loss: 0.3230 - Val Acc: 0.8406
2026-04-05 05:40:37,883 - INFO - Epoch 7/100 - Train Loss: 0.2975 - Val Acc: 0.8551
2026-04-05 05:40:38,152 - INFO - Epoch 8/100 - Train Loss: 0.2774 - Val Acc: 0.8551
2026-04-05 05:40:38,434 - INFO - Epoch 9/100 - Train Loss: 0.2648 - Val Acc: 0.8841
2026-04-05 05:40:38,699 - INFO - Epoch 10/100 - Train Loss: 0.2543 - Val Acc: 0.9130
2026-04-05 05:40:38,975 - INFO - Epoch 11/100 - Train Loss: 0.2423 - Val Acc: 0.9130
2026-04-05 05:40:39,247 - INFO - Epoch 12/100 - Train Loss: 0.2380 - Val Acc: 0.9130
2026-04-05 05:40:39,533 - INFO - Epoch 13/100 - Train Loss: 0.2292 - Val Acc: 0.9130
2026-04-05 05:40:39,805 - INFO - Epoch 14/100 - Train Loss: 0.2223 - Val Acc: 0.9130
2026-04-05 05:40:40,081 - INFO - Epoch 15/100 - Train Loss: 0.2207 - Val Acc: 0.9130
2026-04-05 05:40:40,358 - INFO - Epoch 16/100 - Train Loss: 0.2167 - Val Acc: 0.9130
2026-04-05 05:40:40,633 - INFO - Epoch 17/100 - Train Loss: 0.2136 - Val Acc: 0.9130
2026-04-05 05:40:40,905 - INFO - Epoch 18/100 - Train Loss: 0.2124 - Val Acc: 0.9130
2026-04-05 05:40:41,169 - INFO - Epoch 19/100 - Train Loss: 0.2080 - Val Acc: 0.9130
2026-04-05 05:40:41,427 - INFO - Epoch 20/100 - Train Loss: 0.2057 - Val Acc: 0.8986
2026-04-05 05:40:41,685 - INFO - Epoch 21/100 - Train Loss: 0.2054 - Val Acc: 0.8986
2026-04-05 05:40:41,956 - INFO - Epoch 22/100 - Train Loss: 0.2038 - Val Acc: 0.8986
2026-04-05 05:40:42,227 - INFO - Epoch 23/100 - Train Loss: 0.2013 - Val Acc: 0.8986
2026-04-05 05:40:42,487 - INFO - Epoch 24/100 - Train Loss: 0.2001 - Val Acc: 0.8986
2026-04-05 05:40:42,749 - INFO - Epoch 25/100 - Train Loss: 0.1997 - Val Acc: 0.8986
2026-04-05 05:40:43,014 - INFO - Epoch 26/100 - Train Loss: 0.1985 - Val Acc: 0.9130
2026-04-05 05:40:43,275 - INFO - Epoch 27/100 - Train Loss: 0.1934 - Val Acc: 0.8841
2026-04-05 05:40:43,537 - INFO - Epoch 28/100 - Train Loss: 0.1952 - Val Acc: 0.8841
2026-04-05 05:40:43,810 - INFO - Epoch 29/100 - Train Loss: 0.1946 - Val Acc: 0.8986
2026-04-05 05:40:44,073 - INFO - Epoch 30/100 - Train Loss: 0.1912 - Val Acc: 0.8986
2026-04-05 05:40:44,338 - INFO - Epoch 31/100 - Train Loss: 0.1930 - Val Acc: 0.8841
2026-04-05 05:40:44,626 - INFO - Epoch 32/100 - Train Loss: 0.1882 - Val Acc: 0.8841
2026-04-05 05:40:44,889 - INFO - Epoch 33/100 - Train Loss: 0.1886 - Val Acc: 0.8841
2026-04-05 05:40:45,167 - INFO - Epoch 34/100 - Train Loss: 0.1868 - Val Acc: 0.8986
2026-04-05 05:40:45,426 - INFO - Epoch 35/100 - Train Loss: 0.1869 - Val Acc: 0.8986
2026-04-05 05:40:45,695 - INFO - Epoch 36/100 - Train Loss: 0.1849 - Val Acc: 0.9130
2026-04-05 05:40:45,964 - INFO - Epoch 37/100 - Train Loss: 0.1835 - Val Acc: 0.8986
2026-04-05 05:40:46,226 - INFO - Epoch 38/100 - Train Loss: 0.1836 - Val Acc: 0.8841
2026-04-05 05:40:46,492 - INFO - Epoch 39/100 - Train Loss: 0.1819 - Val Acc: 0.8841
2026-04-05 05:40:46,761 - INFO - Epoch 40/100 - Train Loss: 0.1799 - Val Acc: 0.8986
2026-04-05 05:40:47,029 - INFO - Epoch 41/100 - Train Loss: 0.1793 - Val Acc: 0.8986
2026-04-05 05:40:47,287 - INFO - Epoch 42/100 - Train Loss: 0.1759 - Val Acc: 0.8841
2026-04-05 05:40:47,570 - INFO - Epoch 43/100 - Train Loss: 0.1759 - Val Acc: 0.8986
2026-04-05 05:40:47,836 - INFO - Epoch 44/100 - Train Loss: 0.1763 - Val Acc: 0.8841
2026-04-05 05:40:48,104 - INFO - Epoch 45/100 - Train Loss: 0.1745 - Val Acc: 0.8841
2026-04-05 05:40:48,368 - INFO - Epoch 46/100 - Train Loss: 0.1732 - Val Acc: 0.8841
2026-04-05 05:40:48,635 - INFO - Epoch 47/100 - Train Loss: 0.1719 - Val Acc: 0.8841
2026-04-05 05:40:48,919 - INFO - Epoch 48/100 - Train Loss: 0.1713 - Val Acc: 0.8841
2026-04-05 05:40:49,186 - INFO - Epoch 49/100 - Train Loss: 0.1662 - Val Acc: 0.8841
2026-04-05 05:40:49,444 - INFO - Epoch 50/100 - Train Loss: 0.1700 - Val Acc: 0.8841
2026-04-05 05:40:49,708 - INFO - Epoch 51/100 - Train Loss: 0.1668 - Val Acc: 0.8841
2026-04-05 05:40:49,967 - INFO - Epoch 52/100 - Train Loss: 0.1666 - Val Acc: 0.8841
2026-04-05 05:40:50,230 - INFO - Epoch 53/100 - Train Loss: 0.1664 - Val Acc: 0.8841
2026-04-05 05:40:50,499 - INFO - Epoch 54/100 - Train Loss: 0.1621 - Val Acc: 0.8841
2026-04-05 05:40:50,778 - INFO - Epoch 55/100 - Train Loss: 0.1618 - Val Acc: 0.8986
2026-04-05 05:40:51,046 - INFO - Epoch 56/100 - Train Loss: 0.1632 - Val Acc: 0.8841
2026-04-05 05:40:51,310 - INFO - Epoch 57/100 - Train Loss: 0.1598 - Val Acc: 0.8841
2026-04-05 05:40:51,576 - INFO - Epoch 58/100 - Train Loss: 0.1599 - Val Acc: 0.8841
2026-04-05 05:40:51,851 - INFO - Epoch 59/100 - Train Loss: 0.1607 - Val Acc: 0.8841
2026-04-05 05:40:52,125 - INFO - Epoch 60/100 - Train Loss: 0.1572 - Val Acc: 0.8841
2026-04-05 05:40:52,395 - INFO - Epoch 61/100 - Train Loss: 0.1574 - Val Acc: 0.8986
2026-04-05 05:40:52,665 - INFO - Epoch 62/100 - Train Loss: 0.1552 - Val Acc: 0.8841
2026-04-05 05:40:52,921 - INFO - Epoch 63/100 - Train Loss: 0.1533 - Val Acc: 0.8841
2026-04-05 05:40:53,196 - INFO - Epoch 64/100 - Train Loss: 0.1525 - Val Acc: 0.8696
2026-04-05 05:40:53,466 - INFO - Epoch 65/100 - Train Loss: 0.1517 - Val Acc: 0.8696
2026-04-05 05:40:53,737 - INFO - Epoch 66/100 - Train Loss: 0.1544 - Val Acc: 0.8841
2026-04-05 05:40:53,998 - INFO - Epoch 67/100 - Train Loss: 0.1471 - Val Acc: 0.8841
2026-04-05 05:40:54,278 - INFO - Epoch 68/100 - Train Loss: 0.1487 - Val Acc: 0.8841
2026-04-05 05:40:54,564 - INFO - Epoch 69/100 - Train Loss: 0.1500 - Val Acc: 0.8841
2026-04-05 05:40:54,840 - INFO - Epoch 70/100 - Train Loss: 0.1478 - Val Acc: 0.8841
2026-04-05 05:40:55,109 - INFO - Epoch 71/100 - Train Loss: 0.1457 - Val Acc: 0.8696
2026-04-05 05:40:55,371 - INFO - Epoch 72/100 - Train Loss: 0.1439 - Val Acc: 0.8841
2026-04-05 05:40:55,640 - INFO - Epoch 73/100 - Train Loss: 0.1430 - Val Acc: 0.8841
2026-04-05 05:40:55,908 - INFO - Epoch 74/100 - Train Loss: 0.1454 - Val Acc: 0.8841
2026-04-05 05:40:56,176 - INFO - Epoch 75/100 - Train Loss: 0.1434 - Val Acc: 0.8841
2026-04-05 05:40:56,433 - INFO - Epoch 76/100 - Train Loss: 0.1379 - Val Acc: 0.8841
2026-04-05 05:40:56,702 - INFO - Epoch 77/100 - Train Loss: 0.1424 - Val Acc: 0.8841
2026-04-05 05:40:56,977 - INFO - Epoch 78/100 - Train Loss: 0.1400 - Val Acc: 0.8841
2026-04-05 05:40:57,246 - INFO - Epoch 79/100 - Train Loss: 0.1381 - Val Acc: 0.8841
2026-04-05 05:40:57,512 - INFO - Epoch 80/100 - Train Loss: 0.1411 - Val Acc: 0.8841
2026-04-05 05:40:57,770 - INFO - Epoch 81/100 - Train Loss: 0.1396 - Val Acc: 0.8841
2026-04-05 05:40:58,036 - INFO - Epoch 82/100 - Train Loss: 0.1353 - Val Acc: 0.8841
2026-04-05 05:40:58,305 - INFO - Epoch 83/100 - Train Loss: 0.1367 - Val Acc: 0.8841
2026-04-05 05:40:58,582 - INFO - Epoch 84/100 - Train Loss: 0.1345 - Val Acc: 0.8841
2026-04-05 05:40:58,857 - INFO - Epoch 85/100 - Train Loss: 0.1339 - Val Acc: 0.8841
2026-04-05 05:40:59,125 - INFO - Epoch 86/100 - Train Loss: 0.1329 - Val Acc: 0.8841
2026-04-05 05:40:59,388 - INFO - Epoch 87/100 - Train Loss: 0.1317 - Val Acc: 0.8841
2026-04-05 05:40:59,657 - INFO - Epoch 88/100 - Train Loss: 0.1322 - Val Acc: 0.8841
2026-04-05 05:40:59,925 - INFO - Epoch 89/100 - Train Loss: 0.1334 - Val Acc: 0.8841
2026-04-05 05:41:00,210 - INFO - Epoch 90/100 - Train Loss: 0.1294 - Val Acc: 0.8841
2026-04-05 05:41:00,483 - INFO - Epoch 91/100 - Train Loss: 0.1301 - Val Acc: 0.8841
2026-04-05 05:41:00,747 - INFO - Epoch 92/100 - Train Loss: 0.1282 - Val Acc: 0.8986
2026-04-05 05:41:01,028 - INFO - Epoch 93/100 - Train Loss: 0.1254 - Val Acc: 0.8986
2026-04-05 05:41:01,333 - INFO - Epoch 94/100 - Train Loss: 0.1306 - Val Acc: 0.8986
2026-04-05 05:41:01,610 - INFO - Epoch 95/100 - Train Loss: 0.1272 - Val Acc: 0.8841
2026-04-05 05:41:01,891 - INFO - Epoch 96/100 - Train Loss: 0.1272 - Val Acc: 0.8986
2026-04-05 05:41:02,149 - INFO - Epoch 97/100 - Train Loss: 0.1262 - Val Acc: 0.8841
2026-04-05 05:41:02,420 - INFO - Epoch 98/100 - Train Loss: 0.1229 - Val Acc: 0.8841
2026-04-05 05:41:02,690 - INFO - Epoch 99/100 - Train Loss: 0.1275 - Val Acc: 0.8986
2026-04-05 05:41:02,958 - INFO - Epoch 100/100 - Train Loss: 0.1269 - Val Acc: 0.8841
2026-04-05 05:41:03,307 - INFO - Fold 2 logically complete. Tensor memory bounds cleared cleanly.
2026-04-05 05:41:03,311 - INFO - Original class distribution: [277 344]
2026-04-05 05:41:03,311 - INFO - Training device bound securely to: cuda
2026-04-05 05:41:03,326 - INFO - After SMOTE-ENN deployment: [344 291]

Fold 3:   0%|          | 0/100 [00:00<?, ?it/s]

2026-04-05 05:41:03,616 - INFO - Epoch 1/100 - Train Loss: 0.6432 - Val Acc: 0.8696
2026-04-05 05:41:03,891 - INFO - Epoch 2/100 - Train Loss: 0.5601 - Val Acc: 0.8841
2026-04-05 05:41:04,158 - INFO - Epoch 3/100 - Train Loss: 0.4811 - Val Acc: 0.8986
2026-04-05 05:41:04,435 - INFO - Epoch 4/100 - Train Loss: 0.4101 - Val Acc: 0.9130
2026-04-05 05:41:04,739 - INFO - Epoch 5/100 - Train Loss: 0.3567 - Val Acc: 0.9130
2026-04-05 05:41:05,005 - INFO - Epoch 6/100 - Train Loss: 0.3185 - Val Acc: 0.9130
2026-04-05 05:41:05,270 - INFO - Epoch 7/100 - Train Loss: 0.2925 - Val Acc: 0.8986
2026-04-05 05:41:05,535 - INFO - Epoch 8/100 - Train Loss: 0.2717 - Val Acc: 0.8986
2026-04-05 05:41:05,792 - INFO - Epoch 9/100 - Train Loss: 0.2547 - Val Acc: 0.9130
2026-04-05 05:41:06,058 - INFO - Epoch 10/100 - Train Loss: 0.2423 - Val Acc: 0.9130
2026-04-05 05:41:06,320 - INFO - Epoch 11/100 - Train Loss: 0.2280 - Val Acc: 0.9130
2026-04-05 05:41:06,584 - INFO - Epoch 12/100 - Train Loss: 0.2207 - Val Acc: 0.9130
2026-04-05 05:41:06,866 - INFO - Epoch 13/100 - Train Loss: 0.2126 - Val Acc: 0.9130
2026-04-05 05:41:07,137 - INFO - Epoch 14/100 - Train Loss: 0.2052 - Val Acc: 0.9130
2026-04-05 05:41:07,403 - INFO - Epoch 15/100 - Train Loss: 0.2003 - Val Acc: 0.9130
2026-04-05 05:41:07,662 - INFO - Epoch 16/100 - Train Loss: 0.1981 - Val Acc: 0.9130
2026-04-05 05:41:07,930 - INFO - Epoch 17/100 - Train Loss: 0.1951 - Val Acc: 0.9130
2026-04-05 05:41:08,205 - INFO - Epoch 18/100 - Train Loss: 0.1933 - Val Acc: 0.9130
2026-04-05 05:41:08,480 - INFO - Epoch 19/100 - Train Loss: 0.1915 - Val Acc: 0.9130
2026-04-05 05:41:08,764 - INFO - Epoch 20/100 - Train Loss: 0.1896 - Val Acc: 0.9130
2026-04-05 05:41:09,035 - INFO - Epoch 21/100 - Train Loss: 0.1879 - Val Acc: 0.9130
2026-04-05 05:41:09,302 - INFO - Epoch 22/100 - Train Loss: 0.1862 - Val Acc: 0.9130
2026-04-05 05:41:09,585 - INFO - Epoch 23/100 - Train Loss: 0.1840 - Val Acc: 0.9130
2026-04-05 05:41:09,849 - INFO - Epoch 24/100 - Train Loss: 0.1838 - Val Acc: 0.9130
2026-04-05 05:41:10,123 - INFO - Epoch 25/100 - Train Loss: 0.1825 - Val Acc: 0.9130
2026-04-05 05:41:10,399 - INFO - Epoch 26/100 - Train Loss: 0.1830 - Val Acc: 0.9130
2026-04-05 05:41:10,677 - INFO - Epoch 27/100 - Train Loss: 0.1812 - Val Acc: 0.9130
2026-04-05 05:41:10,946 - INFO - Epoch 28/100 - Train Loss: 0.1787 - Val Acc: 0.9130
2026-04-05 05:41:11,209 - INFO - Epoch 29/100 - Train Loss: 0.1790 - Val Acc: 0.9130
2026-04-05 05:41:11,474 - INFO - Epoch 30/100 - Train Loss: 0.1765 - Val Acc: 0.9130
2026-04-05 05:41:11,740 - INFO - Epoch 31/100 - Train Loss: 0.1753 - Val Acc: 0.9130
2026-04-05 05:41:12,013 - INFO - Epoch 32/100 - Train Loss: 0.1736 - Val Acc: 0.9130
2026-04-05 05:41:12,277 - INFO - Epoch 33/100 - Train Loss: 0.1744 - Val Acc: 0.9130
2026-04-05 05:41:12,538 - INFO - Epoch 34/100 - Train Loss: 0.1736 - Val Acc: 0.9130
2026-04-05 05:41:12,804 - INFO - Epoch 35/100 - Train Loss: 0.1725 - Val Acc: 0.9130
2026-04-05 05:41:13,070 - INFO - Epoch 36/100 - Train Loss: 0.1683 - Val Acc: 0.9130
2026-04-05 05:41:13,332 - INFO - Epoch 37/100 - Train Loss: 0.1665 - Val Acc: 0.9130
2026-04-05 05:41:13,600 - INFO - Epoch 38/100 - Train Loss: 0.1690 - Val Acc: 0.9130
2026-04-05 05:41:13,868 - INFO - Epoch 39/100 - Train Loss: 0.1669 - Val Acc: 0.9130
2026-04-05 05:41:14,134 - INFO - Epoch 40/100 - Train Loss: 0.1646 - Val Acc: 0.9130
2026-04-05 05:41:14,408 - INFO - Epoch 41/100 - Train Loss: 0.1646 - Val Acc: 0.9130
2026-04-05 05:41:14,707 - INFO - Epoch 42/100 - Train Loss: 0.1646 - Val Acc: 0.9130
2026-04-05 05:41:14,976 - INFO - Epoch 43/100 - Train Loss: 0.1623 - Val Acc: 0.9130
2026-04-05 05:41:15,239 - INFO - Epoch 44/100 - Train Loss: 0.1607 - Val Acc: 0.9130
2026-04-05 05:41:15,500 - INFO - Epoch 45/100 - Train Loss: 0.1584 - Val Acc: 0.9130
2026-04-05 05:41:15,774 - INFO - Epoch 46/100 - Train Loss: 0.1594 - Val Acc: 0.9130
2026-04-05 05:41:16,037 - INFO - Epoch 47/100 - Train Loss: 0.1607 - Val Acc: 0.9130
2026-04-05 05:41:16,310 - INFO - Epoch 48/100 - Train Loss: 0.1574 - Val Acc: 0.9130
2026-04-05 05:41:16,565 - INFO - Epoch 49/100 - Train Loss: 0.1547 - Val Acc: 0.9130
2026-04-05 05:41:16,829 - INFO - Epoch 50/100 - Train Loss: 0.1558 - Val Acc: 0.9130
2026-04-05 05:41:17,099 - INFO - Epoch 51/100 - Train Loss: 0.1547 - Val Acc: 0.9130
2026-04-05 05:41:17,377 - INFO - Epoch 52/100 - Train Loss: 0.1547 - Val Acc: 0.9130
2026-04-05 05:41:17,657 - INFO - Epoch 53/100 - Train Loss: 0.1527 - Val Acc: 0.9130
2026-04-05 05:41:17,935 - INFO - Epoch 54/100 - Train Loss: 0.1500 - Val Acc: 0.9130
2026-04-05 05:41:18,213 - INFO - Epoch 55/100 - Train Loss: 0.1488 - Val Acc: 0.9130
2026-04-05 05:41:18,505 - INFO - Epoch 56/100 - Train Loss: 0.1514 - Val Acc: 0.9130
2026-04-05 05:41:18,786 - INFO - Epoch 57/100 - Train Loss: 0.1507 - Val Acc: 0.9130
2026-04-05 05:41:19,050 - INFO - Epoch 58/100 - Train Loss: 0.1495 - Val Acc: 0.9130
2026-04-05 05:41:19,336 - INFO - Epoch 59/100 - Train Loss: 0.1500 - Val Acc: 0.9130
2026-04-05 05:41:19,609 - INFO - Epoch 60/100 - Train Loss: 0.1477 - Val Acc: 0.9130
2026-04-05 05:41:19,882 - INFO - Epoch 61/100 - Train Loss: 0.1487 - Val Acc: 0.9130
2026-04-05 05:41:20,155 - INFO - Epoch 62/100 - Train Loss: 0.1452 - Val Acc: 0.9130
2026-04-05 05:41:20,420 - INFO - Epoch 63/100 - Train Loss: 0.1424 - Val Acc: 0.9130
2026-04-05 05:41:20,701 - INFO - Epoch 64/100 - Train Loss: 0.1450 - Val Acc: 0.9130
2026-04-05 05:41:20,966 - INFO - Epoch 65/100 - Train Loss: 0.1449 - Val Acc: 0.9130
2026-04-05 05:41:21,233 - INFO - Epoch 66/100 - Train Loss: 0.1425 - Val Acc: 0.9130
2026-04-05 05:41:21,490 - INFO - Epoch 67/100 - Train Loss: 0.1425 - Val Acc: 0.9130
2026-04-05 05:41:21,770 - INFO - Epoch 68/100 - Train Loss: 0.1403 - Val Acc: 0.9130
2026-04-05 05:41:22,046 - INFO - Epoch 69/100 - Train Loss: 0.1386 - Val Acc: 0.9130
2026-04-05 05:41:22,317 - INFO - Epoch 70/100 - Train Loss: 0.1398 - Val Acc: 0.9130
2026-04-05 05:41:22,586 - INFO - Epoch 71/100 - Train Loss: 0.1406 - Val Acc: 0.9130
2026-04-05 05:41:22,862 - INFO - Epoch 72/100 - Train Loss: 0.1373 - Val Acc: 0.9130
2026-04-05 05:41:23,130 - INFO - Epoch 73/100 - Train Loss: 0.1356 - Val Acc: 0.9130
2026-04-05 05:41:23,400 - INFO - Epoch 74/100 - Train Loss: 0.1377 - Val Acc: 0.9130
2026-04-05 05:41:23,665 - INFO - Epoch 75/100 - Train Loss: 0.1372 - Val Acc: 0.9130
2026-04-05 05:41:23,957 - INFO - Epoch 76/100 - Train Loss: 0.1366 - Val Acc: 0.9130
2026-04-05 05:41:24,236 - INFO - Epoch 77/100 - Train Loss: 0.1355 - Val Acc: 0.9130
2026-04-05 05:41:24,522 - INFO - Epoch 78/100 - Train Loss: 0.1318 - Val Acc: 0.9130
2026-04-05 05:41:24,811 - INFO - Epoch 79/100 - Train Loss: 0.1325 - Val Acc: 0.9130
2026-04-05 05:41:25,072 - INFO - Epoch 80/100 - Train Loss: 0.1333 - Val Acc: 0.9130
2026-04-05 05:41:25,335 - INFO - Epoch 81/100 - Train Loss: 0.1321 - Val Acc: 0.9130
2026-04-05 05:41:25,606 - INFO - Epoch 82/100 - Train Loss: 0.1299 - Val Acc: 0.9130
2026-04-05 05:41:25,878 - INFO - Epoch 83/100 - Train Loss: 0.1276 - Val Acc: 0.9130
2026-04-05 05:41:26,150 - INFO - Epoch 84/100 - Train Loss: 0.1291 - Val Acc: 0.9130
2026-04-05 05:41:26,414 - INFO - Epoch 85/100 - Train Loss: 0.1305 - Val Acc: 0.9130
2026-04-05 05:41:26,678 - INFO - Epoch 86/100 - Train Loss: 0.1272 - Val Acc: 0.9130
2026-04-05 05:41:26,958 - INFO - Epoch 87/100 - Train Loss: 0.1282 - Val Acc: 0.9130
2026-04-05 05:41:27,228 - INFO - Epoch 88/100 - Train Loss: 0.1284 - Val Acc: 0.9130
2026-04-05 05:41:27,492 - INFO - Epoch 89/100 - Train Loss: 0.1258 - Val Acc: 0.9130
2026-04-05 05:41:27,766 - INFO - Epoch 90/100 - Train Loss: 0.1261 - Val Acc: 0.9130
2026-04-05 05:41:28,032 - INFO - Epoch 91/100 - Train Loss: 0.1270 - Val Acc: 0.9130
2026-04-05 05:41:28,303 - INFO - Epoch 92/100 - Train Loss: 0.1235 - Val Acc: 0.9130
2026-04-05 05:41:28,582 - INFO - Epoch 93/100 - Train Loss: 0.1256 - Val Acc: 0.9130
2026-04-05 05:41:28,844 - INFO - Epoch 94/100 - Train Loss: 0.1253 - Val Acc: 0.9130
2026-04-05 05:41:29,134 - INFO - Epoch 95/100 - Train Loss: 0.1237 - Val Acc: 0.9130
2026-04-05 05:41:29,393 - INFO - Epoch 96/100 - Train Loss: 0.1208 - Val Acc: 0.9130
2026-04-05 05:41:29,657 - INFO - Epoch 97/100 - Train Loss: 0.1207 - Val Acc: 0.9130
2026-04-05 05:41:29,929 - INFO - Epoch 98/100 - Train Loss: 0.1208 - Val Acc: 0.9130
2026-04-05 05:41:30,208 - INFO - Epoch 99/100 - Train Loss: 0.1200 - Val Acc: 0.9130
2026-04-05 05:41:30,481 - INFO - Epoch 100/100 - Train Loss: 0.1191 - Val Acc: 0.9130
2026-04-05 05:41:30,850 - INFO - Fold 3 logically complete. Tensor memory bounds cleared cleanly.
2026-04-05 05:41:30,854 - INFO - Original class distribution: [276 345]
2026-04-05 05:41:30,855 - INFO - Training device bound securely to: cuda
2026-04-05 05:41:30,871 - INFO - After SMOTE-ENN deployment: [345 296]

Fold 4:   0%|          | 0/100 [00:00<?, ?it/s]

2026-04-05 05:41:31,167 - INFO - Epoch 1/100 - Train Loss: 0.6510 - Val Acc: 0.7536
2026-04-05 05:41:31,440 - INFO - Epoch 2/100 - Train Loss: 0.5571 - Val Acc: 0.7681
2026-04-05 05:41:31,744 - INFO - Epoch 3/100 - Train Loss: 0.4751 - Val Acc: 0.7391
2026-04-05 05:41:32,019 - INFO - Epoch 4/100 - Train Loss: 0.4112 - Val Acc: 0.7681
2026-04-05 05:41:32,294 - INFO - Epoch 5/100 - Train Loss: 0.3549 - Val Acc: 0.7681
2026-04-05 05:41:32,565 - INFO - Epoch 6/100 - Train Loss: 0.3101 - Val Acc: 0.7681
2026-04-05 05:41:32,838 - INFO - Epoch 7/100 - Train Loss: 0.2760 - Val Acc: 0.7681
2026-04-05 05:41:33,105 - INFO - Epoch 8/100 - Train Loss: 0.2537 - Val Acc: 0.7536
2026-04-05 05:41:33,374 - INFO - Epoch 9/100 - Train Loss: 0.2371 - Val Acc: 0.7681
2026-04-05 05:41:33,655 - INFO - Epoch 10/100 - Train Loss: 0.2254 - Val Acc: 0.7826
2026-04-05 05:41:33,935 - INFO - Epoch 11/100 - Train Loss: 0.2149 - Val Acc: 0.7826
2026-04-05 05:41:34,203 - INFO - Epoch 12/100 - Train Loss: 0.2036 - Val Acc: 0.7826
2026-04-05 05:41:34,493 - INFO - Epoch 13/100 - Train Loss: 0.1978 - Val Acc: 0.7681
2026-04-05 05:41:34,789 - INFO - Epoch 14/100 - Train Loss: 0.1880 - Val Acc: 0.7681
2026-04-05 05:41:35,060 - INFO - Epoch 15/100 - Train Loss: 0.1833 - Val Acc: 0.7826
2026-04-05 05:41:35,332 - INFO - Epoch 16/100 - Train Loss: 0.1800 - Val Acc: 0.7826
2026-04-05 05:41:35,595 - INFO - Epoch 17/100 - Train Loss: 0.1745 - Val Acc: 0.7826
2026-04-05 05:41:35,877 - INFO - Epoch 18/100 - Train Loss: 0.1712 - Val Acc: 0.7826
2026-04-05 05:41:36,151 - INFO - Epoch 19/100 - Train Loss: 0.1694 - Val Acc: 0.7826
2026-04-05 05:41:36,422 - INFO - Epoch 20/100 - Train Loss: 0.1656 - Val Acc: 0.7826
2026-04-05 05:41:36,708 - INFO - Epoch 21/100 - Train Loss: 0.1641 - Val Acc: 0.7971
2026-04-05 05:41:36,987 - INFO - Epoch 22/100 - Train Loss: 0.1637 - Val Acc: 0.7826
2026-04-05 05:41:37,259 - INFO - Epoch 23/100 - Train Loss: 0.1629 - Val Acc: 0.7826
2026-04-05 05:41:37,536 - INFO - Epoch 24/100 - Train Loss: 0.1620 - Val Acc: 0.7826
2026-04-05 05:41:37,815 - INFO - Epoch 25/100 - Train Loss: 0.1605 - Val Acc: 0.7826
2026-04-05 05:41:38,090 - INFO - Epoch 26/100 - Train Loss: 0.1571 - Val Acc: 0.7826
2026-04-05 05:41:38,367 - INFO - Epoch 27/100 - Train Loss: 0.1598 - Val Acc: 0.7826
2026-04-05 05:41:38,651 - INFO - Epoch 28/100 - Train Loss: 0.1603 - Val Acc: 0.7971
2026-04-05 05:41:38,936 - INFO - Epoch 29/100 - Train Loss: 0.1589 - Val Acc: 0.7971
2026-04-05 05:41:39,216 - INFO - Epoch 30/100 - Train Loss: 0.1542 - Val Acc: 0.7971
2026-04-05 05:41:39,490 - INFO - Epoch 31/100 - Train Loss: 0.1548 - Val Acc: 0.7971
2026-04-05 05:41:39,765 - INFO - Epoch 32/100 - Train Loss: 0.1525 - Val Acc: 0.7971
2026-04-05 05:41:40,049 - INFO - Epoch 33/100 - Train Loss: 0.1512 - Val Acc: 0.7971
2026-04-05 05:41:40,323 - INFO - Epoch 34/100 - Train Loss: 0.1524 - Val Acc: 0.7971
2026-04-05 05:41:40,593 - INFO - Epoch 35/100 - Train Loss: 0.1538 - Val Acc: 0.7971
2026-04-05 05:41:40,878 - INFO - Epoch 36/100 - Train Loss: 0.1492 - Val Acc: 0.7971
2026-04-05 05:41:41,162 - INFO - Epoch 37/100 - Train Loss: 0.1491 - Val Acc: 0.7826
2026-04-05 05:41:41,433 - INFO - Epoch 38/100 - Train Loss: 0.1473 - Val Acc: 0.7971
2026-04-05 05:41:41,709 - INFO - Epoch 39/100 - Train Loss: 0.1457 - Val Acc: 0.7971
2026-04-05 05:41:41,981 - INFO - Epoch 40/100 - Train Loss: 0.1471 - Val Acc: 0.7971
2026-04-05 05:41:42,272 - INFO - Epoch 41/100 - Train Loss: 0.1469 - Val Acc: 0.7971
2026-04-05 05:41:42,550 - INFO - Epoch 42/100 - Train Loss: 0.1446 - Val Acc: 0.7971
2026-04-05 05:41:42,823 - INFO - Epoch 43/100 - Train Loss: 0.1454 - Val Acc: 0.7971
2026-04-05 05:41:43,107 - INFO - Epoch 44/100 - Train Loss: 0.1430 - Val Acc: 0.7971
2026-04-05 05:41:43,392 - INFO - Epoch 45/100 - Train Loss: 0.1412 - Val Acc: 0.7971
2026-04-05 05:41:43,664 - INFO - Epoch 46/100 - Train Loss: 0.1415 - Val Acc: 0.7971
2026-04-05 05:41:43,937 - INFO - Epoch 47/100 - Train Loss: 0.1415 - Val Acc: 0.7826
2026-04-05 05:41:44,223 - INFO - Epoch 48/100 - Train Loss: 0.1390 - Val Acc: 0.7826
2026-04-05 05:41:44,503 - INFO - Epoch 49/100 - Train Loss: 0.1389 - Val Acc: 0.7826
2026-04-05 05:41:44,810 - INFO - Epoch 50/100 - Train Loss: 0.1378 - Val Acc: 0.7971
2026-04-05 05:41:45,098 - INFO - Epoch 51/100 - Train Loss: 0.1357 - Val Acc: 0.7826
2026-04-05 05:41:45,392 - INFO - Epoch 52/100 - Train Loss: 0.1422 - Val Acc: 0.7826
2026-04-05 05:41:45,661 - INFO - Epoch 53/100 - Train Loss: 0.1381 - Val Acc: 0.7826
2026-04-05 05:41:45,944 - INFO - Epoch 54/100 - Train Loss: 0.1397 - Val Acc: 0.7971
2026-04-05 05:41:46,218 - INFO - Epoch 55/100 - Train Loss: 0.1362 - Val Acc: 0.7971
2026-04-05 05:41:46,488 - INFO - Epoch 56/100 - Train Loss: 0.1338 - Val Acc: 0.7971
2026-04-05 05:41:46,777 - INFO - Epoch 57/100 - Train Loss: 0.1349 - Val Acc: 0.7971
2026-04-05 05:41:47,046 - INFO - Epoch 58/100 - Train Loss: 0.1337 - Val Acc: 0.7826
2026-04-05 05:41:47,316 - INFO - Epoch 59/100 - Train Loss: 0.1299 - Val Acc: 0.7971
2026-04-05 05:41:47,587 - INFO - Epoch 60/100 - Train Loss: 0.1349 - Val Acc: 0.7826
2026-04-05 05:41:47,871 - INFO - Epoch 61/100 - Train Loss: 0.1352 - Val Acc: 0.7971
2026-04-05 05:41:48,154 - INFO - Epoch 62/100 - Train Loss: 0.1322 - Val Acc: 0.7971
2026-04-05 05:41:48,428 - INFO - Epoch 63/100 - Train Loss: 0.1265 - Val Acc: 0.7971
2026-04-05 05:41:48,709 - INFO - Epoch 64/100 - Train Loss: 0.1292 - Val Acc: 0.7971
2026-04-05 05:41:48,982 - INFO - Epoch 65/100 - Train Loss: 0.1295 - Val Acc: 0.7971
2026-04-05 05:41:49,271 - INFO - Epoch 66/100 - Train Loss: 0.1259 - Val Acc: 0.7971
2026-04-05 05:41:49,557 - INFO - Epoch 67/100 - Train Loss: 0.1270 - Val Acc: 0.7971
2026-04-05 05:41:49,828 - INFO - Epoch 68/100 - Train Loss: 0.1240 - Val Acc: 0.7971
2026-04-05 05:41:50,107 - INFO - Epoch 69/100 - Train Loss: 0.1236 - Val Acc: 0.7971
2026-04-05 05:41:50,378 - INFO - Epoch 70/100 - Train Loss: 0.1233 - Val Acc: 0.7971
2026-04-05 05:41:50,649 - INFO - Epoch 71/100 - Train Loss: 0.1239 - Val Acc: 0.7971
2026-04-05 05:41:50,929 - INFO - Epoch 72/100 - Train Loss: 0.1249 - Val Acc: 0.7971
2026-04-05 05:41:51,206 - INFO - Epoch 73/100 - Train Loss: 0.1256 - Val Acc: 0.7971
2026-04-05 05:41:51,497 - INFO - Epoch 74/100 - Train Loss: 0.1239 - Val Acc: 0.7826
2026-04-05 05:41:51,766 - INFO - Epoch 75/100 - Train Loss: 0.1212 - Val Acc: 0.7826
2026-04-05 05:41:52,048 - INFO - Epoch 76/100 - Train Loss: 0.1204 - Val Acc: 0.7826
2026-04-05 05:41:52,334 - INFO - Epoch 77/100 - Train Loss: 0.1205 - Val Acc: 0.7826
2026-04-05 05:41:52,624 - INFO - Epoch 78/100 - Train Loss: 0.1195 - Val Acc: 0.7971
2026-04-05 05:41:52,905 - INFO - Epoch 79/100 - Train Loss: 0.1251 - Val Acc: 0.7826
2026-04-05 05:41:53,186 - INFO - Epoch 80/100 - Train Loss: 0.1294 - Val Acc: 0.7681
2026-04-05 05:41:53,465 - INFO - Epoch 81/100 - Train Loss: 0.1259 - Val Acc: 0.7681
2026-04-05 05:41:53,758 - INFO - Epoch 82/100 - Train Loss: 0.1250 - Val Acc: 0.7826
2026-04-05 05:41:54,044 - INFO - Epoch 83/100 - Train Loss: 0.1237 - Val Acc: 0.7826
2026-04-05 05:41:54,324 - INFO - Epoch 84/100 - Train Loss: 0.1239 - Val Acc: 0.7971
2026-04-05 05:41:54,623 - INFO - Epoch 85/100 - Train Loss: 0.1172 - Val Acc: 0.7971
2026-04-05 05:41:54,899 - INFO - Epoch 86/100 - Train Loss: 0.1197 - Val Acc: 0.7971
2026-04-05 05:41:55,174 - INFO - Epoch 87/100 - Train Loss: 0.1161 - Val Acc: 0.7971
2026-04-05 05:41:55,452 - INFO - Epoch 88/100 - Train Loss: 0.1146 - Val Acc: 0.7971
2026-04-05 05:41:55,723 - INFO - Epoch 89/100 - Train Loss: 0.1156 - Val Acc: 0.7971
2026-04-05 05:41:55,999 - INFO - Epoch 90/100 - Train Loss: 0.1124 - Val Acc: 0.7971
2026-04-05 05:41:56,285 - INFO - Epoch 91/100 - Train Loss: 0.1145 - Val Acc: 0.7971
2026-04-05 05:41:56,548 - INFO - Epoch 92/100 - Train Loss: 0.1142 - Val Acc: 0.7971
2026-04-05 05:41:56,828 - INFO - Epoch 93/100 - Train Loss: 0.1118 - Val Acc: 0.7971
2026-04-05 05:41:57,102 - INFO - Epoch 94/100 - Train Loss: 0.1142 - Val Acc: 0.8116
2026-04-05 05:41:57,386 - INFO - Epoch 95/100 - Train Loss: 0.1164 - Val Acc: 0.8116
2026-04-05 05:41:57,672 - INFO - Epoch 96/100 - Train Loss: 0.1137 - Val Acc: 0.7971
2026-04-05 05:41:57,947 - INFO - Epoch 97/100 - Train Loss: 0.1123 - Val Acc: 0.7971
2026-04-05 05:41:58,217 - INFO - Epoch 98/100 - Train Loss: 0.1152 - Val Acc: 0.7826
2026-04-05 05:41:58,493 - INFO - Epoch 99/100 - Train Loss: 0.1111 - Val Acc: 0.7826
2026-04-05 05:41:58,763 - INFO - Epoch 100/100 - Train Loss: 0.1091 - Val Acc: 0.7971
2026-04-05 05:41:59,122 - INFO - Fold 4 logically complete. Tensor memory bounds cleared cleanly.
2026-04-05 05:41:59,126 - INFO - Original class distribution: [276 345]
2026-04-05 05:41:59,127 - INFO - Training device bound securely to: cuda
2026-04-05 05:41:59,143 - INFO - After SMOTE-ENN deployment: [345 287]

Fold 5:   0%|          | 0/100 [00:00<?, ?it/s]

2026-04-05 05:41:59,437 - INFO - Epoch 1/100 - Train Loss: 0.6643 - Val Acc: 0.7971
2026-04-05 05:41:59,708 - INFO - Epoch 2/100 - Train Loss: 0.5780 - Val Acc: 0.7971
2026-04-05 05:41:59,971 - INFO - Epoch 3/100 - Train Loss: 0.4911 - Val Acc: 0.7971
2026-04-05 05:42:00,229 - INFO - Epoch 4/100 - Train Loss: 0.4139 - Val Acc: 0.7826
2026-04-05 05:42:00,492 - INFO - Epoch 5/100 - Train Loss: 0.3513 - Val Acc: 0.8261
2026-04-05 05:42:00,763 - INFO - Epoch 6/100 - Train Loss: 0.3081 - Val Acc: 0.8116
2026-04-05 05:42:01,040 - INFO - Epoch 7/100 - Train Loss: 0.2763 - Val Acc: 0.8406
2026-04-05 05:42:01,299 - INFO - Epoch 8/100 - Train Loss: 0.2538 - Val Acc: 0.8406
2026-04-05 05:42:01,584 - INFO - Epoch 9/100 - Train Loss: 0.2352 - Val Acc: 0.8261
2026-04-05 05:42:01,851 - INFO - Epoch 10/100 - Train Loss: 0.2194 - Val Acc: 0.8261
2026-04-05 05:42:02,115 - INFO - Epoch 11/100 - Train Loss: 0.2080 - Val Acc: 0.7971
2026-04-05 05:42:02,383 - INFO - Epoch 12/100 - Train Loss: 0.1968 - Val Acc: 0.7971
2026-04-05 05:42:02,656 - INFO - Epoch 13/100 - Train Loss: 0.1882 - Val Acc: 0.8261
2026-04-05 05:42:02,921 - INFO - Epoch 14/100 - Train Loss: 0.1827 - Val Acc: 0.8261
2026-04-05 05:42:03,183 - INFO - Epoch 15/100 - Train Loss: 0.1763 - Val Acc: 0.8261
2026-04-05 05:42:03,447 - INFO - Epoch 16/100 - Train Loss: 0.1711 - Val Acc: 0.8406
2026-04-05 05:42:03,714 - INFO - Epoch 17/100 - Train Loss: 0.1662 - Val Acc: 0.8261
2026-04-05 05:42:03,987 - INFO - Epoch 18/100 - Train Loss: 0.1617 - Val Acc: 0.8261
2026-04-05 05:42:04,261 - INFO - Epoch 19/100 - Train Loss: 0.1603 - Val Acc: 0.8261
2026-04-05 05:42:04,554 - INFO - Epoch 20/100 - Train Loss: 0.1553 - Val Acc: 0.8116
2026-04-05 05:42:04,825 - INFO - Epoch 21/100 - Train Loss: 0.1524 - Val Acc: 0.8116
2026-04-05 05:42:05,094 - INFO - Epoch 22/100 - Train Loss: 0.1557 - Val Acc: 0.8116
2026-04-05 05:42:05,358 - INFO - Epoch 23/100 - Train Loss: 0.1528 - Val Acc: 0.8116
2026-04-05 05:42:05,628 - INFO - Epoch 24/100 - Train Loss: 0.1513 - Val Acc: 0.8261
2026-04-05 05:42:05,901 - INFO - Epoch 25/100 - Train Loss: 0.1518 - Val Acc: 0.8261
2026-04-05 05:42:06,174 - INFO - Epoch 26/100 - Train Loss: 0.1474 - Val Acc: 0.8261
2026-04-05 05:42:06,454 - INFO - Epoch 27/100 - Train Loss: 0.1460 - Val Acc: 0.8261
2026-04-05 05:42:06,718 - INFO - Epoch 28/100 - Train Loss: 0.1457 - Val Acc: 0.8116
2026-04-05 05:42:06,993 - INFO - Epoch 29/100 - Train Loss: 0.1431 - Val Acc: 0.8261
2026-04-05 05:42:07,272 - INFO - Epoch 30/100 - Train Loss: 0.1427 - Val Acc: 0.8261
2026-04-05 05:42:07,540 - INFO - Epoch 31/100 - Train Loss: 0.1403 - Val Acc: 0.8116
2026-04-05 05:42:07,809 - INFO - Epoch 32/100 - Train Loss: 0.1424 - Val Acc: 0.8116
2026-04-05 05:42:08,082 - INFO - Epoch 33/100 - Train Loss: 0.1371 - Val Acc: 0.8116
2026-04-05 05:42:08,347 - INFO - Epoch 34/100 - Train Loss: 0.1380 - Val Acc: 0.8116
2026-04-05 05:42:08,613 - INFO - Epoch 35/100 - Train Loss: 0.1352 - Val Acc: 0.8116
2026-04-05 05:42:08,882 - INFO - Epoch 36/100 - Train Loss: 0.1347 - Val Acc: 0.7971
2026-04-05 05:42:09,141 - INFO - Epoch 37/100 - Train Loss: 0.1343 - Val Acc: 0.7971
2026-04-05 05:42:09,413 - INFO - Epoch 38/100 - Train Loss: 0.1337 - Val Acc: 0.7971
2026-04-05 05:42:09,678 - INFO - Epoch 39/100 - Train Loss: 0.1318 - Val Acc: 0.7971
2026-04-05 05:42:09,940 - INFO - Epoch 40/100 - Train Loss: 0.1296 - Val Acc: 0.7971
2026-04-05 05:42:10,210 - INFO - Epoch 41/100 - Train Loss: 0.1292 - Val Acc: 0.7971
2026-04-05 05:42:10,480 - INFO - Epoch 42/100 - Train Loss: 0.1253 - Val Acc: 0.7971
2026-04-05 05:42:10,744 - INFO - Epoch 43/100 - Train Loss: 0.1260 - Val Acc: 0.7971
2026-04-05 05:42:11,022 - INFO - Epoch 44/100 - Train Loss: 0.1268 - Val Acc: 0.7971
2026-04-05 05:42:11,292 - INFO - Epoch 45/100 - Train Loss: 0.1269 - Val Acc: 0.7971
2026-04-05 05:42:11,552 - INFO - Epoch 46/100 - Train Loss: 0.1245 - Val Acc: 0.7971
2026-04-05 05:42:11,823 - INFO - Epoch 47/100 - Train Loss: 0.1216 - Val Acc: 0.7971
2026-04-05 05:42:12,110 - INFO - Epoch 48/100 - Train Loss: 0.1243 - Val Acc: 0.7971
2026-04-05 05:42:12,394 - INFO - Epoch 49/100 - Train Loss: 0.1219 - Val Acc: 0.7971
2026-04-05 05:42:12,671 - INFO - Epoch 50/100 - Train Loss: 0.1242 - Val Acc: 0.8116
2026-04-05 05:42:12,955 - INFO - Epoch 51/100 - Train Loss: 0.1202 - Val Acc: 0.8116
2026-04-05 05:42:13,233 - INFO - Epoch 52/100 - Train Loss: 0.1192 - Val Acc: 0.8116
2026-04-05 05:42:13,498 - INFO - Epoch 53/100 - Train Loss: 0.1169 - Val Acc: 0.8116
2026-04-05 05:42:13,773 - INFO - Epoch 54/100 - Train Loss: 0.1183 - Val Acc: 0.8116
2026-04-05 05:42:14,046 - INFO - Epoch 55/100 - Train Loss: 0.1151 - Val Acc: 0.8116
2026-04-05 05:42:14,316 - INFO - Epoch 56/100 - Train Loss: 0.1179 - Val Acc: 0.8116
2026-04-05 05:42:14,619 - INFO - Epoch 57/100 - Train Loss: 0.1146 - Val Acc: 0.8116
2026-04-05 05:42:14,897 - INFO - Epoch 58/100 - Train Loss: 0.1140 - Val Acc: 0.8116
2026-04-05 05:42:15,163 - INFO - Epoch 59/100 - Train Loss: 0.1157 - Val Acc: 0.8261
2026-04-05 05:42:15,430 - INFO - Epoch 60/100 - Train Loss: 0.1111 - Val Acc: 0.8261
2026-04-05 05:42:15,689 - INFO - Epoch 61/100 - Train Loss: 0.1134 - Val Acc: 0.8116
2026-04-05 05:42:15,964 - INFO - Epoch 62/100 - Train Loss: 0.1130 - Val Acc: 0.8116
2026-04-05 05:42:16,240 - INFO - Epoch 63/100 - Train Loss: 0.1137 - Val Acc: 0.8116
2026-04-05 05:42:16,524 - INFO - Epoch 64/100 - Train Loss: 0.1096 - Val Acc: 0.8116
2026-04-05 05:42:16,785 - INFO - Epoch 65/100 - Train Loss: 0.1126 - Val Acc: 0.7971
2026-04-05 05:42:17,045 - INFO - Epoch 66/100 - Train Loss: 0.1103 - Val Acc: 0.8116
2026-04-05 05:42:17,310 - INFO - Epoch 67/100 - Train Loss: 0.1080 - Val Acc: 0.8116
2026-04-05 05:42:17,581 - INFO - Epoch 68/100 - Train Loss: 0.1059 - Val Acc: 0.8116
2026-04-05 05:42:17,859 - INFO - Epoch 69/100 - Train Loss: 0.1095 - Val Acc: 0.8116
2026-04-05 05:42:18,129 - INFO - Epoch 70/100 - Train Loss: 0.1063 - Val Acc: 0.8116
2026-04-05 05:42:18,396 - INFO - Epoch 71/100 - Train Loss: 0.1054 - Val Acc: 0.8116
2026-04-05 05:42:18,709 - INFO - Epoch 72/100 - Train Loss: 0.1066 - Val Acc: 0.8116
2026-04-05 05:42:18,991 - INFO - Epoch 73/100 - Train Loss: 0.1052 - Val Acc: 0.8116
2026-04-05 05:42:19,271 - INFO - Epoch 74/100 - Train Loss: 0.0998 - Val Acc: 0.7971
2026-04-05 05:42:19,540 - INFO - Epoch 75/100 - Train Loss: 0.1047 - Val Acc: 0.7971
2026-04-05 05:42:19,807 - INFO - Epoch 76/100 - Train Loss: 0.0994 - Val Acc: 0.7971
2026-04-05 05:42:20,074 - INFO - Epoch 77/100 - Train Loss: 0.0998 - Val Acc: 0.8116
2026-04-05 05:42:20,336 - INFO - Epoch 78/100 - Train Loss: 0.1029 - Val Acc: 0.7971
2026-04-05 05:42:20,621 - INFO - Epoch 79/100 - Train Loss: 0.0990 - Val Acc: 0.8116
2026-04-05 05:42:20,894 - INFO - Epoch 80/100 - Train Loss: 0.1009 - Val Acc: 0.7971
2026-04-05 05:42:21,167 - INFO - Epoch 81/100 - Train Loss: 0.1009 - Val Acc: 0.7971
2026-04-05 05:42:21,434 - INFO - Epoch 82/100 - Train Loss: 0.0965 - Val Acc: 0.7971
2026-04-05 05:42:21,699 - INFO - Epoch 83/100 - Train Loss: 0.0993 - Val Acc: 0.7971
2026-04-05 05:42:21,979 - INFO - Epoch 84/100 - Train Loss: 0.0961 - Val Acc: 0.7826
2026-04-05 05:42:22,247 - INFO - Epoch 85/100 - Train Loss: 0.0960 - Val Acc: 0.7971
2026-04-05 05:42:22,529 - INFO - Epoch 86/100 - Train Loss: 0.0970 - Val Acc: 0.8116
2026-04-05 05:42:22,805 - INFO - Epoch 87/100 - Train Loss: 0.0961 - Val Acc: 0.8116
2026-04-05 05:42:23,069 - INFO - Epoch 88/100 - Train Loss: 0.0914 - Val Acc: 0.8116
2026-04-05 05:42:23,346 - INFO - Epoch 89/100 - Train Loss: 0.0937 - Val Acc: 0.8116
2026-04-05 05:42:23,622 - INFO - Epoch 90/100 - Train Loss: 0.0956 - Val Acc: 0.8116
2026-04-05 05:42:23,892 - INFO - Epoch 91/100 - Train Loss: 0.0936 - Val Acc: 0.7971
2026-04-05 05:42:24,172 - INFO - Epoch 92/100 - Train Loss: 0.0893 - Val Acc: 0.8116
2026-04-05 05:42:24,442 - INFO - Epoch 93/100 - Train Loss: 0.0883 - Val Acc: 0.8116
2026-04-05 05:42:24,746 - INFO - Epoch 94/100 - Train Loss: 0.0870 - Val Acc: 0.8116
2026-04-05 05:42:25,014 - INFO - Epoch 95/100 - Train Loss: 0.0895 - Val Acc: 0.7971
2026-04-05 05:42:25,291 - INFO - Epoch 96/100 - Train Loss: 0.0881 - Val Acc: 0.8116
2026-04-05 05:42:25,563 - INFO - Epoch 97/100 - Train Loss: 0.0884 - Val Acc: 0.7971
2026-04-05 05:42:25,841 - INFO - Epoch 98/100 - Train Loss: 0.0902 - Val Acc: 0.8116
2026-04-05 05:42:26,113 - INFO - Epoch 99/100 - Train Loss: 0.0881 - Val Acc: 0.8116
2026-04-05 05:42:26,388 - INFO - Epoch 100/100 - Train Loss: 0.0850 - Val Acc: 0.8116
2026-04-05 05:42:26,762 - INFO - Fold 5 logically complete. Tensor memory bounds cleared cleanly.
2026-04-05 05:42:26,766 - INFO - Original class distribution: [276 345]
2026-04-05 05:42:26,767 - INFO - Training device bound securely to: cuda
2026-04-05 05:42:26,783 - INFO - After SMOTE-ENN deployment: [345 288]

Fold 6:   0%|          | 0/100 [00:00<?, ?it/s]

2026-04-05 05:42:27,080 - INFO - Epoch 1/100 - Train Loss: 0.6493 - Val Acc: 0.8116
2026-04-05 05:42:27,347 - INFO - Epoch 2/100 - Train Loss: 0.5660 - Val Acc: 0.8261
2026-04-05 05:42:27,611 - INFO - Epoch 3/100 - Train Loss: 0.4843 - Val Acc: 0.8551
2026-04-05 05:42:27,873 - INFO - Epoch 4/100 - Train Loss: 0.4108 - Val Acc: 0.8551
2026-04-05 05:42:28,143 - INFO - Epoch 5/100 - Train Loss: 0.3527 - Val Acc: 0.8841
2026-04-05 05:42:28,405 - INFO - Epoch 6/100 - Train Loss: 0.3152 - Val Acc: 0.8696
2026-04-05 05:42:28,674 - INFO - Epoch 7/100 - Train Loss: 0.2880 - Val Acc: 0.8696
2026-04-05 05:42:28,941 - INFO - Epoch 8/100 - Train Loss: 0.2692 - Val Acc: 0.8696
2026-04-05 05:42:29,216 - INFO - Epoch 9/100 - Train Loss: 0.2537 - Val Acc: 0.8696
2026-04-05 05:42:29,472 - INFO - Epoch 10/100 - Train Loss: 0.2428 - Val Acc: 0.8696
2026-04-05 05:42:29,744 - INFO - Epoch 11/100 - Train Loss: 0.2312 - Val Acc: 0.8551
2026-04-05 05:42:30,018 - INFO - Epoch 12/100 - Train Loss: 0.2249 - Val Acc: 0.8551
2026-04-05 05:42:30,279 - INFO - Epoch 13/100 - Train Loss: 0.2152 - Val Acc: 0.8696
2026-04-05 05:42:30,546 - INFO - Epoch 14/100 - Train Loss: 0.2100 - Val Acc: 0.8986
2026-04-05 05:42:30,811 - INFO - Epoch 15/100 - Train Loss: 0.2072 - Val Acc: 0.8986
2026-04-05 05:42:31,082 - INFO - Epoch 16/100 - Train Loss: 0.2014 - Val Acc: 0.8986
2026-04-05 05:42:31,356 - INFO - Epoch 17/100 - Train Loss: 0.1983 - Val Acc: 0.8841
2026-04-05 05:42:31,626 - INFO - Epoch 18/100 - Train Loss: 0.1976 - Val Acc: 0.8986
2026-04-05 05:42:31,903 - INFO - Epoch 19/100 - Train Loss: 0.1931 - Val Acc: 0.8841
2026-04-05 05:42:32,173 - INFO - Epoch 20/100 - Train Loss: 0.1942 - Val Acc: 0.8986
2026-04-05 05:42:32,465 - INFO - Epoch 21/100 - Train Loss: 0.1911 - Val Acc: 0.8986
2026-04-05 05:42:32,743 - INFO - Epoch 22/100 - Train Loss: 0.1887 - Val Acc: 0.8986
2026-04-05 05:42:33,025 - INFO - Epoch 23/100 - Train Loss: 0.1863 - Val Acc: 0.8986
2026-04-05 05:42:33,325 - INFO - Epoch 24/100 - Train Loss: 0.1857 - Val Acc: 0.8986
2026-04-05 05:42:33,608 - INFO - Epoch 25/100 - Train Loss: 0.1858 - Val Acc: 0.8986
2026-04-05 05:42:33,878 - INFO - Epoch 26/100 - Train Loss: 0.1825 - Val Acc: 0.8986
2026-04-05 05:42:34,159 - INFO - Epoch 27/100 - Train Loss: 0.1822 - Val Acc: 0.8986
2026-04-05 05:42:34,428 - INFO - Epoch 28/100 - Train Loss: 0.1797 - Val Acc: 0.8986
2026-04-05 05:42:34,735 - INFO - Epoch 29/100 - Train Loss: 0.1808 - Val Acc: 0.8986
2026-04-05 05:42:35,005 - INFO - Epoch 30/100 - Train Loss: 0.1783 - Val Acc: 0.8986
2026-04-05 05:42:35,275 - INFO - Epoch 31/100 - Train Loss: 0.1774 - Val Acc: 0.8986
2026-04-05 05:42:35,538 - INFO - Epoch 32/100 - Train Loss: 0.1776 - Val Acc: 0.8986
2026-04-05 05:42:35,808 - INFO - Epoch 33/100 - Train Loss: 0.1767 - Val Acc: 0.8986
2026-04-05 05:42:36,078 - INFO - Epoch 34/100 - Train Loss: 0.1748 - Val Acc: 0.8986
2026-04-05 05:42:36,355 - INFO - Epoch 35/100 - Train Loss: 0.1726 - Val Acc: 0.8986
2026-04-05 05:42:36,632 - INFO - Epoch 36/100 - Train Loss: 0.1691 - Val Acc: 0.8986
2026-04-05 05:42:36,912 - INFO - Epoch 37/100 - Train Loss: 0.1692 - Val Acc: 0.8986
2026-04-05 05:42:37,180 - INFO - Epoch 38/100 - Train Loss: 0.1715 - Val Acc: 0.8986
2026-04-05 05:42:37,458 - INFO - Epoch 39/100 - Train Loss: 0.1679 - Val Acc: 0.8986
2026-04-05 05:42:37,720 - INFO - Epoch 40/100 - Train Loss: 0.1669 - Val Acc: 0.8986
2026-04-05 05:42:37,995 - INFO - Epoch 41/100 - Train Loss: 0.1661 - Val Acc: 0.8986
2026-04-05 05:42:38,263 - INFO - Epoch 42/100 - Train Loss: 0.1661 - Val Acc: 0.8986
2026-04-05 05:42:38,524 - INFO - Epoch 43/100 - Train Loss: 0.1641 - Val Acc: 0.8986
2026-04-05 05:42:38,803 - INFO - Epoch 44/100 - Train Loss: 0.1636 - Val Acc: 0.8986
2026-04-05 05:42:39,073 - INFO - Epoch 45/100 - Train Loss: 0.1612 - Val Acc: 0.8986
2026-04-05 05:42:39,350 - INFO - Epoch 46/100 - Train Loss: 0.1614 - Val Acc: 0.8986
2026-04-05 05:42:39,631 - INFO - Epoch 47/100 - Train Loss: 0.1604 - Val Acc: 0.8986
2026-04-05 05:42:39,901 - INFO - Epoch 48/100 - Train Loss: 0.1592 - Val Acc: 0.8986
2026-04-05 05:42:40,185 - INFO - Epoch 49/100 - Train Loss: 0.1588 - Val Acc: 0.8986
2026-04-05 05:42:40,449 - INFO - Epoch 50/100 - Train Loss: 0.1583 - Val Acc: 0.8986
2026-04-05 05:42:40,715 - INFO - Epoch 51/100 - Train Loss: 0.1551 - Val Acc: 0.8986
2026-04-05 05:42:40,987 - INFO - Epoch 52/100 - Train Loss: 0.1577 - Val Acc: 0.8986
2026-04-05 05:42:41,265 - INFO - Epoch 53/100 - Train Loss: 0.1528 - Val Acc: 0.8986
2026-04-05 05:42:41,538 - INFO - Epoch 54/100 - Train Loss: 0.1517 - Val Acc: 0.8986
2026-04-05 05:42:41,812 - INFO - Epoch 55/100 - Train Loss: 0.1541 - Val Acc: 0.8986
2026-04-05 05:42:42,072 - INFO - Epoch 56/100 - Train Loss: 0.1516 - Val Acc: 0.8986
2026-04-05 05:42:42,349 - INFO - Epoch 57/100 - Train Loss: 0.1512 - Val Acc: 0.8986
2026-04-05 05:42:42,636 - INFO - Epoch 58/100 - Train Loss: 0.1509 - Val Acc: 0.8986
2026-04-05 05:42:42,908 - INFO - Epoch 59/100 - Train Loss: 0.1487 - Val Acc: 0.8986
2026-04-05 05:42:43,178 - INFO - Epoch 60/100 - Train Loss: 0.1478 - Val Acc: 0.8986
2026-04-05 05:42:43,453 - INFO - Epoch 61/100 - Train Loss: 0.1476 - Val Acc: 0.8986
2026-04-05 05:42:43,726 - INFO - Epoch 62/100 - Train Loss: 0.1464 - Val Acc: 0.8986
2026-04-05 05:42:43,999 - INFO - Epoch 63/100 - Train Loss: 0.1476 - Val Acc: 0.8986
2026-04-05 05:42:44,267 - INFO - Epoch 64/100 - Train Loss: 0.1470 - Val Acc: 0.8986
2026-04-05 05:42:44,551 - INFO - Epoch 65/100 - Train Loss: 0.1435 - Val Acc: 0.8986
2026-04-05 05:42:44,829 - INFO - Epoch 66/100 - Train Loss: 0.1429 - Val Acc: 0.8986
2026-04-05 05:42:45,102 - INFO - Epoch 67/100 - Train Loss: 0.1427 - Val Acc: 0.8841
2026-04-05 05:42:45,370 - INFO - Epoch 68/100 - Train Loss: 0.1390 - Val Acc: 0.8841
2026-04-05 05:42:45,628 - INFO - Epoch 69/100 - Train Loss: 0.1414 - Val Acc: 0.8841
2026-04-05 05:42:45,885 - INFO - Epoch 70/100 - Train Loss: 0.1405 - Val Acc: 0.8986
2026-04-05 05:42:46,154 - INFO - Epoch 71/100 - Train Loss: 0.1368 - Val Acc: 0.8841
2026-04-05 05:42:46,422 - INFO - Epoch 72/100 - Train Loss: 0.1376 - Val Acc: 0.8841
2026-04-05 05:42:46,698 - INFO - Epoch 73/100 - Train Loss: 0.1391 - Val Acc: 0.8841
2026-04-05 05:42:46,981 - INFO - Epoch 74/100 - Train Loss: 0.1356 - Val Acc: 0.8841
2026-04-05 05:42:47,259 - INFO - Epoch 75/100 - Train Loss: 0.1354 - Val Acc: 0.8841
2026-04-05 05:42:47,523 - INFO - Epoch 76/100 - Train Loss: 0.1369 - Val Acc: 0.8841
2026-04-05 05:42:47,790 - INFO - Epoch 77/100 - Train Loss: 0.1360 - Val Acc: 0.8986
2026-04-05 05:42:48,055 - INFO - Epoch 78/100 - Train Loss: 0.1338 - Val Acc: 0.8841
2026-04-05 05:42:48,323 - INFO - Epoch 79/100 - Train Loss: 0.1335 - Val Acc: 0.8986
2026-04-05 05:42:48,592 - INFO - Epoch 80/100 - Train Loss: 0.1292 - Val Acc: 0.8986
2026-04-05 05:42:48,860 - INFO - Epoch 81/100 - Train Loss: 0.1280 - Val Acc: 0.8986
2026-04-05 05:42:49,149 - INFO - Epoch 82/100 - Train Loss: 0.1303 - Val Acc: 0.8986
2026-04-05 05:42:49,406 - INFO - Epoch 83/100 - Train Loss: 0.1276 - Val Acc: 0.8986
2026-04-05 05:42:49,675 - INFO - Epoch 84/100 - Train Loss: 0.1290 - Val Acc: 0.8986
2026-04-05 05:42:49,939 - INFO - Epoch 85/100 - Train Loss: 0.1268 - Val Acc: 0.8986
2026-04-05 05:42:50,210 - INFO - Epoch 86/100 - Train Loss: 0.1273 - Val Acc: 0.8986
2026-04-05 05:42:50,496 - INFO - Epoch 87/100 - Train Loss: 0.1266 - Val Acc: 0.8841
2026-04-05 05:42:50,776 - INFO - Epoch 88/100 - Train Loss: 0.1253 - Val Acc: 0.8841
2026-04-05 05:42:51,061 - INFO - Epoch 89/100 - Train Loss: 0.1242 - Val Acc: 0.8841
2026-04-05 05:42:51,330 - INFO - Epoch 90/100 - Train Loss: 0.1243 - Val Acc: 0.8841
2026-04-05 05:42:51,603 - INFO - Epoch 91/100 - Train Loss: 0.1223 - Val Acc: 0.8841
2026-04-05 05:42:51,888 - INFO - Epoch 92/100 - Train Loss: 0.1229 - Val Acc: 0.8841
2026-04-05 05:42:52,166 - INFO - Epoch 93/100 - Train Loss: 0.1226 - Val Acc: 0.8841
2026-04-05 05:42:52,432 - INFO - Epoch 94/100 - Train Loss: 0.1235 - Val Acc: 0.8841
2026-04-05 05:42:52,718 - INFO - Epoch 95/100 - Train Loss: 0.1215 - Val Acc: 0.8841
2026-04-05 05:42:52,985 - INFO - Epoch 96/100 - Train Loss: 0.1239 - Val Acc: 0.8841
2026-04-05 05:42:53,264 - INFO - Epoch 97/100 - Train Loss: 0.1211 - Val Acc: 0.8841
2026-04-05 05:42:53,538 - INFO - Epoch 98/100 - Train Loss: 0.1177 - Val Acc: 0.8841
2026-04-05 05:42:53,797 - INFO - Epoch 99/100 - Train Loss: 0.1211 - Val Acc: 0.8841
2026-04-05 05:42:54,069 - INFO - Epoch 100/100 - Train Loss: 0.1182 - Val Acc: 0.8841
2026-04-05 05:42:54,437 - INFO - Fold 6 logically complete. Tensor memory bounds cleared cleanly.
2026-04-05 05:42:54,441 - INFO - Original class distribution: [276 345]
2026-04-05 05:42:54,442 - INFO - Training device bound securely to: cuda
2026-04-05 05:42:54,458 - INFO - After SMOTE-ENN deployment: [345 291]

Fold 7:   0%|          | 0/100 [00:00<?, ?it/s]

2026-04-05 05:42:54,760 - INFO - Epoch 1/100 - Train Loss: 0.6434 - Val Acc: 0.8116
2026-04-05 05:42:55,032 - INFO - Epoch 2/100 - Train Loss: 0.5535 - Val Acc: 0.8116
2026-04-05 05:42:55,303 - INFO - Epoch 3/100 - Train Loss: 0.4688 - Val Acc: 0.8116
2026-04-05 05:42:55,586 - INFO - Epoch 4/100 - Train Loss: 0.3962 - Val Acc: 0.8116
2026-04-05 05:42:55,849 - INFO - Epoch 5/100 - Train Loss: 0.3402 - Val Acc: 0.8116
2026-04-05 05:42:56,110 - INFO - Epoch 6/100 - Train Loss: 0.3042 - Val Acc: 0.7971
2026-04-05 05:42:56,370 - INFO - Epoch 7/100 - Train Loss: 0.2766 - Val Acc: 0.7826
2026-04-05 05:42:56,631 - INFO - Epoch 8/100 - Train Loss: 0.2582 - Val Acc: 0.7826
2026-04-05 05:42:56,896 - INFO - Epoch 9/100 - Train Loss: 0.2435 - Val Acc: 0.8116
2026-04-05 05:42:57,168 - INFO - Epoch 10/100 - Train Loss: 0.2311 - Val Acc: 0.8116
2026-04-05 05:42:57,431 - INFO - Epoch 11/100 - Train Loss: 0.2205 - Val Acc: 0.7971
2026-04-05 05:42:57,710 - INFO - Epoch 12/100 - Train Loss: 0.2121 - Val Acc: 0.7971
2026-04-05 05:42:57,970 - INFO - Epoch 13/100 - Train Loss: 0.2035 - Val Acc: 0.8261
2026-04-05 05:42:58,254 - INFO - Epoch 14/100 - Train Loss: 0.2001 - Val Acc: 0.8261
2026-04-05 05:42:58,553 - INFO - Epoch 15/100 - Train Loss: 0.1945 - Val Acc: 0.8261
2026-04-05 05:42:58,824 - INFO - Epoch 16/100 - Train Loss: 0.1901 - Val Acc: 0.8261
2026-04-05 05:42:59,099 - INFO - Epoch 17/100 - Train Loss: 0.1877 - Val Acc: 0.8261
2026-04-05 05:42:59,381 - INFO - Epoch 18/100 - Train Loss: 0.1808 - Val Acc: 0.7971
2026-04-05 05:42:59,642 - INFO - Epoch 19/100 - Train Loss: 0.1827 - Val Acc: 0.7971
2026-04-05 05:42:59,905 - INFO - Epoch 20/100 - Train Loss: 0.1769 - Val Acc: 0.7971
2026-04-05 05:43:00,180 - INFO - Epoch 21/100 - Train Loss: 0.1796 - Val Acc: 0.7826
2026-04-05 05:43:00,446 - INFO - Epoch 22/100 - Train Loss: 0.1747 - Val Acc: 0.7826
2026-04-05 05:43:00,724 - INFO - Epoch 23/100 - Train Loss: 0.1754 - Val Acc: 0.7826
2026-04-05 05:43:00,998 - INFO - Epoch 24/100 - Train Loss: 0.1711 - Val Acc: 0.7826
2026-04-05 05:43:01,266 - INFO - Epoch 25/100 - Train Loss: 0.1718 - Val Acc: 0.7826
2026-04-05 05:43:01,529 - INFO - Epoch 26/100 - Train Loss: 0.1706 - Val Acc: 0.7826
2026-04-05 05:43:01,790 - INFO - Epoch 27/100 - Train Loss: 0.1684 - Val Acc: 0.7826
2026-04-05 05:43:02,056 - INFO - Epoch 28/100 - Train Loss: 0.1676 - Val Acc: 0.7826
2026-04-05 05:43:02,319 - INFO - Epoch 29/100 - Train Loss: 0.1646 - Val Acc: 0.7681
2026-04-05 05:43:02,588 - INFO - Epoch 30/100 - Train Loss: 0.1663 - Val Acc: 0.7826
2026-04-05 05:43:02,862 - INFO - Epoch 31/100 - Train Loss: 0.1634 - Val Acc: 0.7826
2026-04-05 05:43:03,121 - INFO - Epoch 32/100 - Train Loss: 0.1612 - Val Acc: 0.7826
2026-04-05 05:43:03,377 - INFO - Epoch 33/100 - Train Loss: 0.1602 - Val Acc: 0.7826
2026-04-05 05:43:03,646 - INFO - Epoch 34/100 - Train Loss: 0.1600 - Val Acc: 0.7826
2026-04-05 05:43:03,929 - INFO - Epoch 35/100 - Train Loss: 0.1581 - Val Acc: 0.7826
2026-04-05 05:43:04,197 - INFO - Epoch 36/100 - Train Loss: 0.1568 - Val Acc: 0.7826
2026-04-05 05:43:04,482 - INFO - Epoch 37/100 - Train Loss: 0.1556 - Val Acc: 0.7826
2026-04-05 05:43:04,773 - INFO - Epoch 38/100 - Train Loss: 0.1538 - Val Acc: 0.7826
2026-04-05 05:43:05,047 - INFO - Epoch 39/100 - Train Loss: 0.1524 - Val Acc: 0.7826
2026-04-05 05:43:05,315 - INFO - Epoch 40/100 - Train Loss: 0.1499 - Val Acc: 0.7826
2026-04-05 05:43:05,577 - INFO - Epoch 41/100 - Train Loss: 0.1494 - Val Acc: 0.7826
2026-04-05 05:43:05,850 - INFO - Epoch 42/100 - Train Loss: 0.1461 - Val Acc: 0.7826
2026-04-05 05:43:06,135 - INFO - Epoch 43/100 - Train Loss: 0.1500 - Val Acc: 0.7826
2026-04-05 05:43:06,399 - INFO - Epoch 44/100 - Train Loss: 0.1464 - Val Acc: 0.7826
2026-04-05 05:43:06,662 - INFO - Epoch 45/100 - Train Loss: 0.1443 - Val Acc: 0.7826
2026-04-05 05:43:06,932 - INFO - Epoch 46/100 - Train Loss: 0.1460 - Val Acc: 0.7826
2026-04-05 05:43:07,203 - INFO - Epoch 47/100 - Train Loss: 0.1434 - Val Acc: 0.7826
2026-04-05 05:43:07,474 - INFO - Epoch 48/100 - Train Loss: 0.1440 - Val Acc: 0.7826
2026-04-05 05:43:07,742 - INFO - Epoch 49/100 - Train Loss: 0.1429 - Val Acc: 0.7826
2026-04-05 05:43:08,017 - INFO - Epoch 50/100 - Train Loss: 0.1394 - Val Acc: 0.7826
2026-04-05 05:43:08,291 - INFO - Epoch 51/100 - Train Loss: 0.1417 - Val Acc: 0.7826
2026-04-05 05:43:08,568 - INFO - Epoch 52/100 - Train Loss: 0.1359 - Val Acc: 0.7826
2026-04-05 05:43:08,839 - INFO - Epoch 53/100 - Train Loss: 0.1364 - Val Acc: 0.7681
2026-04-05 05:43:09,105 - INFO - Epoch 54/100 - Train Loss: 0.1358 - Val Acc: 0.7826
2026-04-05 05:43:09,377 - INFO - Epoch 55/100 - Train Loss: 0.1347 - Val Acc: 0.7681
2026-04-05 05:43:09,649 - INFO - Epoch 56/100 - Train Loss: 0.1350 - Val Acc: 0.7681
2026-04-05 05:43:09,917 - INFO - Epoch 57/100 - Train Loss: 0.1368 - Val Acc: 0.7826
2026-04-05 05:43:10,193 - INFO - Epoch 58/100 - Train Loss: 0.1328 - Val Acc: 0.7826
2026-04-05 05:43:10,462 - INFO - Epoch 59/100 - Train Loss: 0.1310 - Val Acc: 0.7681
2026-04-05 05:43:10,737 - INFO - Epoch 60/100 - Train Loss: 0.1275 - Val Acc: 0.7681
2026-04-05 05:43:11,023 - INFO - Epoch 61/100 - Train Loss: 0.1290 - Val Acc: 0.7681
2026-04-05 05:43:11,308 - INFO - Epoch 62/100 - Train Loss: 0.1276 - Val Acc: 0.7681
2026-04-05 05:43:11,587 - INFO - Epoch 63/100 - Train Loss: 0.1283 - Val Acc: 0.7681
2026-04-05 05:43:11,852 - INFO - Epoch 64/100 - Train Loss: 0.1264 - Val Acc: 0.7681
2026-04-05 05:43:12,121 - INFO - Epoch 65/100 - Train Loss: 0.1244 - Val Acc: 0.7681
2026-04-05 05:43:12,387 - INFO - Epoch 66/100 - Train Loss: 0.1245 - Val Acc: 0.7681
2026-04-05 05:43:12,662 - INFO - Epoch 67/100 - Train Loss: 0.1240 - Val Acc: 0.7971
2026-04-05 05:43:12,946 - INFO - Epoch 68/100 - Train Loss: 0.1217 - Val Acc: 0.7681
2026-04-05 05:43:13,220 - INFO - Epoch 69/100 - Train Loss: 0.1232 - Val Acc: 0.7971
2026-04-05 05:43:13,494 - INFO - Epoch 70/100 - Train Loss: 0.1228 - Val Acc: 0.7971
2026-04-05 05:43:13,752 - INFO - Epoch 71/100 - Train Loss: 0.1195 - Val Acc: 0.7971
2026-04-05 05:43:14,036 - INFO - Epoch 72/100 - Train Loss: 0.1210 - Val Acc: 0.7826
2026-04-05 05:43:14,309 - INFO - Epoch 73/100 - Train Loss: 0.1156 - Val Acc: 0.7971
2026-04-05 05:43:14,605 - INFO - Epoch 74/100 - Train Loss: 0.1186 - Val Acc: 0.7971
2026-04-05 05:43:14,885 - INFO - Epoch 75/100 - Train Loss: 0.1192 - Val Acc: 0.7826
2026-04-05 05:43:15,161 - INFO - Epoch 76/100 - Train Loss: 0.1179 - Val Acc: 0.7971
2026-04-05 05:43:15,437 - INFO - Epoch 77/100 - Train Loss: 0.1179 - Val Acc: 0.8116
2026-04-05 05:43:15,716 - INFO - Epoch 78/100 - Train Loss: 0.1170 - Val Acc: 0.7971
2026-04-05 05:43:15,986 - INFO - Epoch 79/100 - Train Loss: 0.1140 - Val Acc: 0.7971
2026-04-05 05:43:16,261 - INFO - Epoch 80/100 - Train Loss: 0.1150 - Val Acc: 0.7971
2026-04-05 05:43:16,534 - INFO - Epoch 81/100 - Train Loss: 0.1122 - Val Acc: 0.7971
2026-04-05 05:43:16,803 - INFO - Epoch 82/100 - Train Loss: 0.1119 - Val Acc: 0.7971
2026-04-05 05:43:17,077 - INFO - Epoch 83/100 - Train Loss: 0.1097 - Val Acc: 0.7971
2026-04-05 05:43:17,350 - INFO - Epoch 84/100 - Train Loss: 0.1109 - Val Acc: 0.7971
2026-04-05 05:43:17,631 - INFO - Epoch 85/100 - Train Loss: 0.1095 - Val Acc: 0.7971
2026-04-05 05:43:17,913 - INFO - Epoch 86/100 - Train Loss: 0.1083 - Val Acc: 0.7971
2026-04-05 05:43:18,186 - INFO - Epoch 87/100 - Train Loss: 0.1066 - Val Acc: 0.7826
2026-04-05 05:43:18,468 - INFO - Epoch 88/100 - Train Loss: 0.1080 - Val Acc: 0.7971
2026-04-05 05:43:18,744 - INFO - Epoch 89/100 - Train Loss: 0.1088 - Val Acc: 0.7826
2026-04-05 05:43:19,009 - INFO - Epoch 90/100 - Train Loss: 0.1052 - Val Acc: 0.7971
2026-04-05 05:43:19,279 - INFO - Epoch 91/100 - Train Loss: 0.1059 - Val Acc: 0.8116
2026-04-05 05:43:19,541 - INFO - Epoch 92/100 - Train Loss: 0.1039 - Val Acc: 0.7826
2026-04-05 05:43:19,810 - INFO - Epoch 93/100 - Train Loss: 0.1044 - Val Acc: 0.7971
2026-04-05 05:43:20,081 - INFO - Epoch 94/100 - Train Loss: 0.1076 - Val Acc: 0.7971
2026-04-05 05:43:20,362 - INFO - Epoch 95/100 - Train Loss: 0.1068 - Val Acc: 0.7971
2026-04-05 05:43:20,625 - INFO - Epoch 96/100 - Train Loss: 0.1047 - Val Acc: 0.7971
2026-04-05 05:43:20,908 - INFO - Epoch 97/100 - Train Loss: 0.1037 - Val Acc: 0.7971
2026-04-05 05:43:21,190 - INFO - Epoch 98/100 - Train Loss: 0.1020 - Val Acc: 0.7826
2026-04-05 05:43:21,472 - INFO - Epoch 99/100 - Train Loss: 0.1039 - Val Acc: 0.7826
2026-04-05 05:43:21,750 - INFO - Epoch 100/100 - Train Loss: 0.1021 - Val Acc: 0.7971
2026-04-05 05:43:22,127 - INFO - Fold 7 logically complete. Tensor memory bounds cleared cleanly.
2026-04-05 05:43:22,131 - INFO - Original class distribution: [276 345]
2026-04-05 05:43:22,132 - INFO - Training device bound securely to: cuda
2026-04-05 05:43:22,148 - INFO - After SMOTE-ENN deployment: [345 289]

Fold 8:   0%|          | 0/100 [00:00<?, ?it/s]

2026-04-05 05:43:22,443 - INFO - Epoch 1/100 - Train Loss: 0.6560 - Val Acc: 0.8406
2026-04-05 05:43:22,708 - INFO - Epoch 2/100 - Train Loss: 0.5687 - Val Acc: 0.8261
2026-04-05 05:43:22,975 - INFO - Epoch 3/100 - Train Loss: 0.4889 - Val Acc: 0.8406
2026-04-05 05:43:23,237 - INFO - Epoch 4/100 - Train Loss: 0.4162 - Val Acc: 0.8406
2026-04-05 05:43:23,510 - INFO - Epoch 5/100 - Train Loss: 0.3630 - Val Acc: 0.8261
2026-04-05 05:43:23,794 - INFO - Epoch 6/100 - Train Loss: 0.3230 - Val Acc: 0.8116
2026-04-05 05:43:24,075 - INFO - Epoch 7/100 - Train Loss: 0.2964 - Val Acc: 0.8116
2026-04-05 05:43:24,353 - INFO - Epoch 8/100 - Train Loss: 0.2763 - Val Acc: 0.8116
2026-04-05 05:43:24,644 - INFO - Epoch 9/100 - Train Loss: 0.2579 - Val Acc: 0.7971
2026-04-05 05:43:24,921 - INFO - Epoch 10/100 - Train Loss: 0.2470 - Val Acc: 0.7971
2026-04-05 05:43:25,201 - INFO - Epoch 11/100 - Train Loss: 0.2342 - Val Acc: 0.8116
2026-04-05 05:43:25,471 - INFO - Epoch 12/100 - Train Loss: 0.2240 - Val Acc: 0.8261
2026-04-05 05:43:25,739 - INFO - Epoch 13/100 - Train Loss: 0.2154 - Val Acc: 0.8261
2026-04-05 05:43:26,014 - INFO - Epoch 14/100 - Train Loss: 0.2086 - Val Acc: 0.8406
2026-04-05 05:43:26,293 - INFO - Epoch 15/100 - Train Loss: 0.2052 - Val Acc: 0.8406
2026-04-05 05:43:26,556 - INFO - Epoch 16/100 - Train Loss: 0.2018 - Val Acc: 0.8406
2026-04-05 05:43:26,813 - INFO - Epoch 17/100 - Train Loss: 0.1981 - Val Acc: 0.8406
2026-04-05 05:43:27,073 - INFO - Epoch 18/100 - Train Loss: 0.1964 - Val Acc: 0.8406
2026-04-05 05:43:27,341 - INFO - Epoch 19/100 - Train Loss: 0.1927 - Val Acc: 0.8406
2026-04-05 05:43:27,614 - INFO - Epoch 20/100 - Train Loss: 0.1921 - Val Acc: 0.8406
2026-04-05 05:43:27,890 - INFO - Epoch 21/100 - Train Loss: 0.1890 - Val Acc: 0.8406
2026-04-05 05:43:28,167 - INFO - Epoch 22/100 - Train Loss: 0.1880 - Val Acc: 0.8406
2026-04-05 05:43:28,434 - INFO - Epoch 23/100 - Train Loss: 0.1854 - Val Acc: 0.8406
2026-04-05 05:43:28,699 - INFO - Epoch 24/100 - Train Loss: 0.1848 - Val Acc: 0.8406
2026-04-05 05:43:28,969 - INFO - Epoch 25/100 - Train Loss: 0.1845 - Val Acc: 0.8406
2026-04-05 05:43:29,251 - INFO - Epoch 26/100 - Train Loss: 0.1824 - Val Acc: 0.8406
2026-04-05 05:43:29,530 - INFO - Epoch 27/100 - Train Loss: 0.1806 - Val Acc: 0.8551
2026-04-05 05:43:29,815 - INFO - Epoch 28/100 - Train Loss: 0.1796 - Val Acc: 0.8406
2026-04-05 05:43:30,085 - INFO - Epoch 29/100 - Train Loss: 0.1788 - Val Acc: 0.8551
2026-04-05 05:43:30,357 - INFO - Epoch 30/100 - Train Loss: 0.1762 - Val Acc: 0.8551
2026-04-05 05:43:30,632 - INFO - Epoch 31/100 - Train Loss: 0.1756 - Val Acc: 0.8551
2026-04-05 05:43:30,901 - INFO - Epoch 32/100 - Train Loss: 0.1746 - Val Acc: 0.8551
2026-04-05 05:43:31,180 - INFO - Epoch 33/100 - Train Loss: 0.1726 - Val Acc: 0.8551
2026-04-05 05:43:31,460 - INFO - Epoch 34/100 - Train Loss: 0.1738 - Val Acc: 0.8551
2026-04-05 05:43:31,739 - INFO - Epoch 35/100 - Train Loss: 0.1719 - Val Acc: 0.8551
2026-04-05 05:43:32,019 - INFO - Epoch 36/100 - Train Loss: 0.1718 - Val Acc: 0.8551
2026-04-05 05:43:32,306 - INFO - Epoch 37/100 - Train Loss: 0.1671 - Val Acc: 0.8551
2026-04-05 05:43:32,580 - INFO - Epoch 38/100 - Train Loss: 0.1677 - Val Acc: 0.8551
2026-04-05 05:43:32,845 - INFO - Epoch 39/100 - Train Loss: 0.1663 - Val Acc: 0.8551
2026-04-05 05:43:33,115 - INFO - Epoch 40/100 - Train Loss: 0.1636 - Val Acc: 0.8551
2026-04-05 05:43:33,382 - INFO - Epoch 41/100 - Train Loss: 0.1634 - Val Acc: 0.8551
2026-04-05 05:43:33,657 - INFO - Epoch 42/100 - Train Loss: 0.1608 - Val Acc: 0.8551
2026-04-05 05:43:33,924 - INFO - Epoch 43/100 - Train Loss: 0.1610 - Val Acc: 0.8551
2026-04-05 05:43:34,217 - INFO - Epoch 44/100 - Train Loss: 0.1619 - Val Acc: 0.8551
2026-04-05 05:43:34,520 - INFO - Epoch 45/100 - Train Loss: 0.1605 - Val Acc: 0.8551
2026-04-05 05:43:34,809 - INFO - Epoch 46/100 - Train Loss: 0.1584 - Val Acc: 0.8551
2026-04-05 05:43:35,090 - INFO - Epoch 47/100 - Train Loss: 0.1556 - Val Acc: 0.8551
2026-04-05 05:43:35,368 - INFO - Epoch 48/100 - Train Loss: 0.1579 - Val Acc: 0.8551
2026-04-05 05:43:35,649 - INFO - Epoch 49/100 - Train Loss: 0.1575 - Val Acc: 0.8551
2026-04-05 05:43:35,930 - INFO - Epoch 50/100 - Train Loss: 0.1531 - Val Acc: 0.8551
2026-04-05 05:43:36,214 - INFO - Epoch 51/100 - Train Loss: 0.1545 - Val Acc: 0.8551
2026-04-05 05:43:36,498 - INFO - Epoch 52/100 - Train Loss: 0.1520 - Val Acc: 0.8551
2026-04-05 05:43:36,776 - INFO - Epoch 53/100 - Train Loss: 0.1504 - Val Acc: 0.8551
2026-04-05 05:43:37,042 - INFO - Epoch 54/100 - Train Loss: 0.1505 - Val Acc: 0.8551
2026-04-05 05:43:37,314 - INFO - Epoch 55/100 - Train Loss: 0.1509 - Val Acc: 0.8551
2026-04-05 05:43:37,588 - INFO - Epoch 56/100 - Train Loss: 0.1504 - Val Acc: 0.8551
2026-04-05 05:43:37,855 - INFO - Epoch 57/100 - Train Loss: 0.1498 - Val Acc: 0.8551
2026-04-05 05:43:38,133 - INFO - Epoch 58/100 - Train Loss: 0.1490 - Val Acc: 0.8551
2026-04-05 05:43:38,409 - INFO - Epoch 59/100 - Train Loss: 0.1457 - Val Acc: 0.8551
2026-04-05 05:43:38,681 - INFO - Epoch 60/100 - Train Loss: 0.1437 - Val Acc: 0.8551
2026-04-05 05:43:38,945 - INFO - Epoch 61/100 - Train Loss: 0.1444 - Val Acc: 0.8551
2026-04-05 05:43:39,220 - INFO - Epoch 62/100 - Train Loss: 0.1441 - Val Acc: 0.8551
2026-04-05 05:43:39,494 - INFO - Epoch 63/100 - Train Loss: 0.1387 - Val Acc: 0.8551
2026-04-05 05:43:39,757 - INFO - Epoch 64/100 - Train Loss: 0.1446 - Val Acc: 0.8551
2026-04-05 05:43:40,036 - INFO - Epoch 65/100 - Train Loss: 0.1415 - Val Acc: 0.8551
2026-04-05 05:43:40,302 - INFO - Epoch 66/100 - Train Loss: 0.1396 - Val Acc: 0.8551
2026-04-05 05:43:40,582 - INFO - Epoch 67/100 - Train Loss: 0.1399 - Val Acc: 0.8551
2026-04-05 05:43:40,863 - INFO - Epoch 68/100 - Train Loss: 0.1369 - Val Acc: 0.8551
2026-04-05 05:43:41,126 - INFO - Epoch 69/100 - Train Loss: 0.1366 - Val Acc: 0.8551
2026-04-05 05:43:41,396 - INFO - Epoch 70/100 - Train Loss: 0.1350 - Val Acc: 0.8551
2026-04-05 05:43:41,667 - INFO - Epoch 71/100 - Train Loss: 0.1343 - Val Acc: 0.8551
2026-04-05 05:43:41,937 - INFO - Epoch 72/100 - Train Loss: 0.1337 - Val Acc: 0.8551
2026-04-05 05:43:42,209 - INFO - Epoch 73/100 - Train Loss: 0.1301 - Val Acc: 0.8551
2026-04-05 05:43:42,481 - INFO - Epoch 74/100 - Train Loss: 0.1323 - Val Acc: 0.8551
2026-04-05 05:43:42,751 - INFO - Epoch 75/100 - Train Loss: 0.1362 - Val Acc: 0.8551
2026-04-05 05:43:43,039 - INFO - Epoch 76/100 - Train Loss: 0.1306 - Val Acc: 0.8551
2026-04-05 05:43:43,317 - INFO - Epoch 77/100 - Train Loss: 0.1305 - Val Acc: 0.8551
2026-04-05 05:43:43,590 - INFO - Epoch 78/100 - Train Loss: 0.1312 - Val Acc: 0.8551
2026-04-05 05:43:43,864 - INFO - Epoch 79/100 - Train Loss: 0.1286 - Val Acc: 0.8551
2026-04-05 05:43:44,139 - INFO - Epoch 80/100 - Train Loss: 0.1328 - Val Acc: 0.8551
2026-04-05 05:43:44,442 - INFO - Epoch 81/100 - Train Loss: 0.1274 - Val Acc: 0.8551
2026-04-05 05:43:44,731 - INFO - Epoch 82/100 - Train Loss: 0.1217 - Val Acc: 0.8551
2026-04-05 05:43:45,004 - INFO - Epoch 83/100 - Train Loss: 0.1266 - Val Acc: 0.8551
2026-04-05 05:43:45,290 - INFO - Epoch 84/100 - Train Loss: 0.1246 - Val Acc: 0.8551
2026-04-05 05:43:45,557 - INFO - Epoch 85/100 - Train Loss: 0.1254 - Val Acc: 0.8551
2026-04-05 05:43:45,831 - INFO - Epoch 86/100 - Train Loss: 0.1250 - Val Acc: 0.8551
2026-04-05 05:43:46,095 - INFO - Epoch 87/100 - Train Loss: 0.1198 - Val Acc: 0.8551
2026-04-05 05:43:46,362 - INFO - Epoch 88/100 - Train Loss: 0.1219 - Val Acc: 0.8551
2026-04-05 05:43:46,658 - INFO - Epoch 89/100 - Train Loss: 0.1177 - Val Acc: 0.8551
2026-04-05 05:43:46,928 - INFO - Epoch 90/100 - Train Loss: 0.1169 - Val Acc: 0.8551
2026-04-05 05:43:47,203 - INFO - Epoch 91/100 - Train Loss: 0.1182 - Val Acc: 0.8551
2026-04-05 05:43:47,471 - INFO - Epoch 92/100 - Train Loss: 0.1165 - Val Acc: 0.8551
2026-04-05 05:43:47,742 - INFO - Epoch 93/100 - Train Loss: 0.1171 - Val Acc: 0.8551
2026-04-05 05:43:48,014 - INFO - Epoch 94/100 - Train Loss: 0.1154 - Val Acc: 0.8551
2026-04-05 05:43:48,293 - INFO - Epoch 95/100 - Train Loss: 0.1211 - Val Acc: 0.8551
2026-04-05 05:43:48,566 - INFO - Epoch 96/100 - Train Loss: 0.1147 - Val Acc: 0.8551
2026-04-05 05:43:48,847 - INFO - Epoch 97/100 - Train Loss: 0.1141 - Val Acc: 0.8551
2026-04-05 05:43:49,128 - INFO - Epoch 98/100 - Train Loss: 0.1162 - Val Acc: 0.8551
2026-04-05 05:43:49,401 - INFO - Epoch 99/100 - Train Loss: 0.1123 - Val Acc: 0.8551
2026-04-05 05:43:49,694 - INFO - Epoch 100/100 - Train Loss: 0.1157 - Val Acc: 0.8551
2026-04-05 05:43:50,061 - INFO - Fold 8 logically complete. Tensor memory bounds cleared cleanly.
2026-04-05 05:43:50,066 - INFO - Original class distribution: [276 345]
2026-04-05 05:43:50,066 - INFO - Training device bound securely to: cuda
2026-04-05 05:43:50,082 - INFO - After SMOTE-ENN deployment: [345 294]

Fold 9:   0%|          | 0/100 [00:00<?, ?it/s]

2026-04-05 05:43:50,369 - INFO - Epoch 1/100 - Train Loss: 0.6520 - Val Acc: 0.7681
2026-04-05 05:43:50,648 - INFO - Epoch 2/100 - Train Loss: 0.5660 - Val Acc: 0.7536
2026-04-05 05:43:50,919 - INFO - Epoch 3/100 - Train Loss: 0.4836 - Val Acc: 0.7536
2026-04-05 05:43:51,186 - INFO - Epoch 4/100 - Train Loss: 0.4113 - Val Acc: 0.7681
2026-04-05 05:43:51,447 - INFO - Epoch 5/100 - Train Loss: 0.3506 - Val Acc: 0.7826
2026-04-05 05:43:51,722 - INFO - Epoch 6/100 - Train Loss: 0.3076 - Val Acc: 0.7971
2026-04-05 05:43:51,996 - INFO - Epoch 7/100 - Train Loss: 0.2799 - Val Acc: 0.8116
2026-04-05 05:43:52,261 - INFO - Epoch 8/100 - Train Loss: 0.2577 - Val Acc: 0.7971
2026-04-05 05:43:52,545 - INFO - Epoch 9/100 - Train Loss: 0.2392 - Val Acc: 0.7971
2026-04-05 05:43:52,818 - INFO - Epoch 10/100 - Train Loss: 0.2237 - Val Acc: 0.8116
2026-04-05 05:43:53,084 - INFO - Epoch 11/100 - Train Loss: 0.2141 - Val Acc: 0.8116
2026-04-05 05:43:53,360 - INFO - Epoch 12/100 - Train Loss: 0.2033 - Val Acc: 0.8116
2026-04-05 05:43:53,625 - INFO - Epoch 13/100 - Train Loss: 0.1949 - Val Acc: 0.8261
2026-04-05 05:43:53,892 - INFO - Epoch 14/100 - Train Loss: 0.1881 - Val Acc: 0.8261
2026-04-05 05:43:54,175 - INFO - Epoch 15/100 - Train Loss: 0.1848 - Val Acc: 0.8406
2026-04-05 05:43:54,466 - INFO - Epoch 16/100 - Train Loss: 0.1794 - Val Acc: 0.8406
2026-04-05 05:43:54,749 - INFO - Epoch 17/100 - Train Loss: 0.1773 - Val Acc: 0.8406
2026-04-05 05:43:55,020 - INFO - Epoch 18/100 - Train Loss: 0.1746 - Val Acc: 0.8406
2026-04-05 05:43:55,292 - INFO - Epoch 19/100 - Train Loss: 0.1718 - Val Acc: 0.8406
2026-04-05 05:43:55,549 - INFO - Epoch 20/100 - Train Loss: 0.1704 - Val Acc: 0.8406
2026-04-05 05:43:55,828 - INFO - Epoch 21/100 - Train Loss: 0.1698 - Val Acc: 0.8406
2026-04-05 05:43:56,101 - INFO - Epoch 22/100 - Train Loss: 0.1664 - Val Acc: 0.8406
2026-04-05 05:43:56,363 - INFO - Epoch 23/100 - Train Loss: 0.1660 - Val Acc: 0.8406
2026-04-05 05:43:56,640 - INFO - Epoch 24/100 - Train Loss: 0.1651 - Val Acc: 0.8406
2026-04-05 05:43:56,912 - INFO - Epoch 25/100 - Train Loss: 0.1654 - Val Acc: 0.8406
2026-04-05 05:43:57,173 - INFO - Epoch 26/100 - Train Loss: 0.1657 - Val Acc: 0.8406
2026-04-05 05:43:57,432 - INFO - Epoch 27/100 - Train Loss: 0.1652 - Val Acc: 0.8406
2026-04-05 05:43:57,701 - INFO - Epoch 28/100 - Train Loss: 0.1640 - Val Acc: 0.8406
2026-04-05 05:43:57,971 - INFO - Epoch 29/100 - Train Loss: 0.1620 - Val Acc: 0.8406
2026-04-05 05:43:58,242 - INFO - Epoch 30/100 - Train Loss: 0.1617 - Val Acc: 0.8406
2026-04-05 05:43:58,520 - INFO - Epoch 31/100 - Train Loss: 0.1617 - Val Acc: 0.8406
2026-04-05 05:43:58,791 - INFO - Epoch 32/100 - Train Loss: 0.1589 - Val Acc: 0.8406
2026-04-05 05:43:59,058 - INFO - Epoch 33/100 - Train Loss: 0.1587 - Val Acc: 0.8406
2026-04-05 05:43:59,329 - INFO - Epoch 34/100 - Train Loss: 0.1553 - Val Acc: 0.8406
2026-04-05 05:43:59,606 - INFO - Epoch 35/100 - Train Loss: 0.1567 - Val Acc: 0.8406
2026-04-05 05:43:59,879 - INFO - Epoch 36/100 - Train Loss: 0.1589 - Val Acc: 0.8406
2026-04-05 05:44:00,138 - INFO - Epoch 37/100 - Train Loss: 0.1575 - Val Acc: 0.8406
2026-04-05 05:44:00,401 - INFO - Epoch 38/100 - Train Loss: 0.1556 - Val Acc: 0.8406
2026-04-05 05:44:00,672 - INFO - Epoch 39/100 - Train Loss: 0.1565 - Val Acc: 0.8406
2026-04-05 05:44:00,933 - INFO - Epoch 40/100 - Train Loss: 0.1546 - Val Acc: 0.8406
2026-04-05 05:44:01,197 - INFO - Epoch 41/100 - Train Loss: 0.1549 - Val Acc: 0.8406
2026-04-05 05:44:01,472 - INFO - Epoch 42/100 - Train Loss: 0.1528 - Val Acc: 0.8406
2026-04-05 05:44:01,739 - INFO - Epoch 43/100 - Train Loss: 0.1508 - Val Acc: 0.8406
2026-04-05 05:44:02,014 - INFO - Epoch 44/100 - Train Loss: 0.1527 - Val Acc: 0.8406
2026-04-05 05:44:02,289 - INFO - Epoch 45/100 - Train Loss: 0.1496 - Val Acc: 0.8406
2026-04-05 05:44:02,561 - INFO - Epoch 46/100 - Train Loss: 0.1498 - Val Acc: 0.8406
2026-04-05 05:44:02,856 - INFO - Epoch 47/100 - Train Loss: 0.1500 - Val Acc: 0.8406
2026-04-05 05:44:03,159 - INFO - Epoch 48/100 - Train Loss: 0.1467 - Val Acc: 0.8406
2026-04-05 05:44:03,454 - INFO - Epoch 49/100 - Train Loss: 0.1499 - Val Acc: 0.8406
2026-04-05 05:44:03,723 - INFO - Epoch 50/100 - Train Loss: 0.1458 - Val Acc: 0.8406
2026-04-05 05:44:03,986 - INFO - Epoch 51/100 - Train Loss: 0.1474 - Val Acc: 0.8406
2026-04-05 05:44:04,284 - INFO - Epoch 52/100 - Train Loss: 0.1464 - Val Acc: 0.8406
2026-04-05 05:44:04,593 - INFO - Epoch 53/100 - Train Loss: 0.1450 - Val Acc: 0.8406
2026-04-05 05:44:04,864 - INFO - Epoch 54/100 - Train Loss: 0.1447 - Val Acc: 0.8406
2026-04-05 05:44:05,140 - INFO - Epoch 55/100 - Train Loss: 0.1441 - Val Acc: 0.8406
2026-04-05 05:44:05,410 - INFO - Epoch 56/100 - Train Loss: 0.1417 - Val Acc: 0.8406
2026-04-05 05:44:05,673 - INFO - Epoch 57/100 - Train Loss: 0.1427 - Val Acc: 0.8406
2026-04-05 05:44:05,952 - INFO - Epoch 58/100 - Train Loss: 0.1407 - Val Acc: 0.8406
2026-04-05 05:44:06,224 - INFO - Epoch 59/100 - Train Loss: 0.1393 - Val Acc: 0.8406
2026-04-05 05:44:06,495 - INFO - Epoch 60/100 - Train Loss: 0.1420 - Val Acc: 0.8406
2026-04-05 05:44:06,756 - INFO - Epoch 61/100 - Train Loss: 0.1369 - Val Acc: 0.8406
2026-04-05 05:44:07,026 - INFO - Epoch 62/100 - Train Loss: 0.1401 - Val Acc: 0.8406
2026-04-05 05:44:07,299 - INFO - Epoch 63/100 - Train Loss: 0.1363 - Val Acc: 0.8406
2026-04-05 05:44:07,577 - INFO - Epoch 64/100 - Train Loss: 0.1370 - Val Acc: 0.8406
2026-04-05 05:44:07,842 - INFO - Epoch 65/100 - Train Loss: 0.1367 - Val Acc: 0.8406
2026-04-05 05:44:08,109 - INFO - Epoch 66/100 - Train Loss: 0.1353 - Val Acc: 0.8406
2026-04-05 05:44:08,373 - INFO - Epoch 67/100 - Train Loss: 0.1372 - Val Acc: 0.8406
2026-04-05 05:44:08,632 - INFO - Epoch 68/100 - Train Loss: 0.1347 - Val Acc: 0.8406
2026-04-05 05:44:08,910 - INFO - Epoch 69/100 - Train Loss: 0.1355 - Val Acc: 0.8406
2026-04-05 05:44:09,180 - INFO - Epoch 70/100 - Train Loss: 0.1309 - Val Acc: 0.8406
2026-04-05 05:44:09,440 - INFO - Epoch 71/100 - Train Loss: 0.1317 - Val Acc: 0.8406
2026-04-05 05:44:09,726 - INFO - Epoch 72/100 - Train Loss: 0.1321 - Val Acc: 0.8406
2026-04-05 05:44:10,006 - INFO - Epoch 73/100 - Train Loss: 0.1282 - Val Acc: 0.8406
2026-04-05 05:44:10,273 - INFO - Epoch 74/100 - Train Loss: 0.1287 - Val Acc: 0.8406
2026-04-05 05:44:10,542 - INFO - Epoch 75/100 - Train Loss: 0.1310 - Val Acc: 0.8406
2026-04-05 05:44:10,824 - INFO - Epoch 76/100 - Train Loss: 0.1292 - Val Acc: 0.8406
2026-04-05 05:44:11,094 - INFO - Epoch 77/100 - Train Loss: 0.1267 - Val Acc: 0.8406
2026-04-05 05:44:11,368 - INFO - Epoch 78/100 - Train Loss: 0.1257 - Val Acc: 0.8406
2026-04-05 05:44:11,644 - INFO - Epoch 79/100 - Train Loss: 0.1256 - Val Acc: 0.8406
2026-04-05 05:44:11,915 - INFO - Epoch 80/100 - Train Loss: 0.1231 - Val Acc: 0.8406
2026-04-05 05:44:12,187 - INFO - Epoch 81/100 - Train Loss: 0.1231 - Val Acc: 0.8406
2026-04-05 05:44:12,456 - INFO - Epoch 82/100 - Train Loss: 0.1207 - Val Acc: 0.8406
2026-04-05 05:44:12,722 - INFO - Epoch 83/100 - Train Loss: 0.1216 - Val Acc: 0.8406
2026-04-05 05:44:13,016 - INFO - Epoch 84/100 - Train Loss: 0.1195 - Val Acc: 0.8261
2026-04-05 05:44:13,291 - INFO - Epoch 85/100 - Train Loss: 0.1219 - Val Acc: 0.8261
2026-04-05 05:44:13,569 - INFO - Epoch 86/100 - Train Loss: 0.1205 - Val Acc: 0.8406
2026-04-05 05:44:13,833 - INFO - Epoch 87/100 - Train Loss: 0.1160 - Val Acc: 0.8406
2026-04-05 05:44:14,105 - INFO - Epoch 88/100 - Train Loss: 0.1188 - Val Acc: 0.8406
2026-04-05 05:44:14,379 - INFO - Epoch 89/100 - Train Loss: 0.1191 - Val Acc: 0.8406
2026-04-05 05:44:14,679 - INFO - Epoch 90/100 - Train Loss: 0.1169 - Val Acc: 0.8261
2026-04-05 05:44:14,950 - INFO - Epoch 91/100 - Train Loss: 0.1167 - Val Acc: 0.8261
2026-04-05 05:44:15,213 - INFO - Epoch 92/100 - Train Loss: 0.1138 - Val Acc: 0.8261
2026-04-05 05:44:15,483 - INFO - Epoch 93/100 - Train Loss: 0.1145 - Val Acc: 0.8261
2026-04-05 05:44:15,753 - INFO - Epoch 94/100 - Train Loss: 0.1115 - Val Acc: 0.8261
2026-04-05 05:44:16,013 - INFO - Epoch 95/100 - Train Loss: 0.1102 - Val Acc: 0.8261
2026-04-05 05:44:16,279 - INFO - Epoch 96/100 - Train Loss: 0.1123 - Val Acc: 0.8261
2026-04-05 05:44:16,555 - INFO - Epoch 97/100 - Train Loss: 0.1129 - Val Acc: 0.8261
2026-04-05 05:44:16,833 - INFO - Epoch 98/100 - Train Loss: 0.1140 - Val Acc: 0.8116
2026-04-05 05:44:17,096 - INFO - Epoch 99/100 - Train Loss: 0.1129 - Val Acc: 0.8261
2026-04-05 05:44:17,361 - INFO - Epoch 100/100 - Train Loss: 0.1104 - Val Acc: 0.8261
2026-04-05 05:44:17,729 - INFO - Fold 9 logically complete. Tensor memory bounds cleared cleanly.
2026-04-05 05:44:17,732 - INFO - Original class distribution: [276 345]
2026-04-05 05:44:17,733 - INFO - Training device bound securely to: cuda
2026-04-05 05:44:17,749 - INFO - After SMOTE-ENN deployment: [345 288]

Fold 10:   0%|          | 0/100 [00:00<?, ?it/s]

2026-04-05 05:44:18,031 - INFO - Epoch 1/100 - Train Loss: 0.6522 - Val Acc: 0.8116
2026-04-05 05:44:18,296 - INFO - Epoch 2/100 - Train Loss: 0.5709 - Val Acc: 0.8261
2026-04-05 05:44:18,564 - INFO - Epoch 3/100 - Train Loss: 0.4877 - Val Acc: 0.8261
2026-04-05 05:44:18,841 - INFO - Epoch 4/100 - Train Loss: 0.4120 - Val Acc: 0.8406
2026-04-05 05:44:19,099 - INFO - Epoch 5/100 - Train Loss: 0.3558 - Val Acc: 0.8406
2026-04-05 05:44:19,360 - INFO - Epoch 6/100 - Train Loss: 0.3133 - Val Acc: 0.8841
2026-04-05 05:44:19,619 - INFO - Epoch 7/100 - Train Loss: 0.2870 - Val Acc: 0.8841
2026-04-05 05:44:19,879 - INFO - Epoch 8/100 - Train Loss: 0.2660 - Val Acc: 0.8986
2026-04-05 05:44:20,142 - INFO - Epoch 9/100 - Train Loss: 0.2507 - Val Acc: 0.9275
2026-04-05 05:44:20,413 - INFO - Epoch 10/100 - Train Loss: 0.2386 - Val Acc: 0.9275
2026-04-05 05:44:20,693 - INFO - Epoch 11/100 - Train Loss: 0.2310 - Val Acc: 0.9420
2026-04-05 05:44:20,957 - INFO - Epoch 12/100 - Train Loss: 0.2206 - Val Acc: 0.9420
2026-04-05 05:44:21,230 - INFO - Epoch 13/100 - Train Loss: 0.2142 - Val Acc: 0.9275
2026-04-05 05:44:21,492 - INFO - Epoch 14/100 - Train Loss: 0.2081 - Val Acc: 0.9275
2026-04-05 05:44:21,764 - INFO - Epoch 15/100 - Train Loss: 0.2027 - Val Acc: 0.9275
2026-04-05 05:44:22,032 - INFO - Epoch 16/100 - Train Loss: 0.2005 - Val Acc: 0.9275
2026-04-05 05:44:22,304 - INFO - Epoch 17/100 - Train Loss: 0.1958 - Val Acc: 0.9275
2026-04-05 05:44:22,579 - INFO - Epoch 18/100 - Train Loss: 0.1948 - Val Acc: 0.9275
2026-04-05 05:44:22,848 - INFO - Epoch 19/100 - Train Loss: 0.1920 - Val Acc: 0.9130
2026-04-05 05:44:23,103 - INFO - Epoch 20/100 - Train Loss: 0.1922 - Val Acc: 0.9130
2026-04-05 05:44:23,372 - INFO - Epoch 21/100 - Train Loss: 0.1871 - Val Acc: 0.9130
2026-04-05 05:44:23,638 - INFO - Epoch 22/100 - Train Loss: 0.1867 - Val Acc: 0.9130
2026-04-05 05:44:23,907 - INFO - Epoch 23/100 - Train Loss: 0.1867 - Val Acc: 0.9130
2026-04-05 05:44:24,177 - INFO - Epoch 24/100 - Train Loss: 0.1864 - Val Acc: 0.9130
2026-04-05 05:44:24,450 - INFO - Epoch 25/100 - Train Loss: 0.1841 - Val Acc: 0.9275
2026-04-05 05:44:24,747 - INFO - Epoch 26/100 - Train Loss: 0.1827 - Val Acc: 0.9275
2026-04-05 05:44:25,021 - INFO - Epoch 27/100 - Train Loss: 0.1823 - Val Acc: 0.9275
2026-04-05 05:44:25,291 - INFO - Epoch 28/100 - Train Loss: 0.1799 - Val Acc: 0.9275
2026-04-05 05:44:25,552 - INFO - Epoch 29/100 - Train Loss: 0.1786 - Val Acc: 0.9275
2026-04-05 05:44:25,808 - INFO - Epoch 30/100 - Train Loss: 0.1804 - Val Acc: 0.9275
2026-04-05 05:44:26,081 - INFO - Epoch 31/100 - Train Loss: 0.1777 - Val Acc: 0.9275
2026-04-05 05:44:26,365 - INFO - Epoch 32/100 - Train Loss: 0.1765 - Val Acc: 0.9275
2026-04-05 05:44:26,632 - INFO - Epoch 33/100 - Train Loss: 0.1787 - Val Acc: 0.9275
2026-04-05 05:44:26,910 - INFO - Epoch 34/100 - Train Loss: 0.1748 - Val Acc: 0.9275
2026-04-05 05:44:27,188 - INFO - Epoch 35/100 - Train Loss: 0.1749 - Val Acc: 0.9275
2026-04-05 05:44:27,455 - INFO - Epoch 36/100 - Train Loss: 0.1728 - Val Acc: 0.9275
2026-04-05 05:44:27,734 - INFO - Epoch 37/100 - Train Loss: 0.1734 - Val Acc: 0.9275
2026-04-05 05:44:28,002 - INFO - Epoch 38/100 - Train Loss: 0.1711 - Val Acc: 0.9275
2026-04-05 05:44:28,271 - INFO - Epoch 39/100 - Train Loss: 0.1692 - Val Acc: 0.9275
2026-04-05 05:44:28,550 - INFO - Epoch 40/100 - Train Loss: 0.1687 - Val Acc: 0.9275
2026-04-05 05:44:28,818 - INFO - Epoch 41/100 - Train Loss: 0.1700 - Val Acc: 0.9275
2026-04-05 05:44:29,094 - INFO - Epoch 42/100 - Train Loss: 0.1663 - Val Acc: 0.9275
2026-04-05 05:44:29,365 - INFO - Epoch 43/100 - Train Loss: 0.1649 - Val Acc: 0.9275
2026-04-05 05:44:29,630 - INFO - Epoch 44/100 - Train Loss: 0.1688 - Val Acc: 0.9275
2026-04-05 05:44:29,902 - INFO - Epoch 45/100 - Train Loss: 0.1639 - Val Acc: 0.9275
2026-04-05 05:44:30,168 - INFO - Epoch 46/100 - Train Loss: 0.1633 - Val Acc: 0.9275
2026-04-05 05:44:30,437 - INFO - Epoch 47/100 - Train Loss: 0.1610 - Val Acc: 0.9275
2026-04-05 05:44:30,714 - INFO - Epoch 48/100 - Train Loss: 0.1629 - Val Acc: 0.9275
2026-04-05 05:44:31,000 - INFO - Epoch 49/100 - Train Loss: 0.1627 - Val Acc: 0.9275
2026-04-05 05:44:31,264 - INFO - Epoch 50/100 - Train Loss: 0.1590 - Val Acc: 0.9275
2026-04-05 05:44:31,536 - INFO - Epoch 51/100 - Train Loss: 0.1592 - Val Acc: 0.9275
2026-04-05 05:44:31,803 - INFO - Epoch 52/100 - Train Loss: 0.1595 - Val Acc: 0.9275
2026-04-05 05:44:32,061 - INFO - Epoch 53/100 - Train Loss: 0.1579 - Val Acc: 0.9275
2026-04-05 05:44:32,338 - INFO - Epoch 54/100 - Train Loss: 0.1570 - Val Acc: 0.9275
2026-04-05 05:44:32,611 - INFO - Epoch 55/100 - Train Loss: 0.1566 - Val Acc: 0.9275
2026-04-05 05:44:32,888 - INFO - Epoch 56/100 - Train Loss: 0.1560 - Val Acc: 0.9420
2026-04-05 05:44:33,167 - INFO - Epoch 57/100 - Train Loss: 0.1537 - Val Acc: 0.9275
2026-04-05 05:44:33,453 - INFO - Epoch 58/100 - Train Loss: 0.1507 - Val Acc: 0.9420
2026-04-05 05:44:33,724 - INFO - Epoch 59/100 - Train Loss: 0.1547 - Val Acc: 0.9420
2026-04-05 05:44:33,988 - INFO - Epoch 60/100 - Train Loss: 0.1533 - Val Acc: 0.9275
2026-04-05 05:44:34,258 - INFO - Epoch 61/100 - Train Loss: 0.1509 - Val Acc: 0.9420
2026-04-05 05:44:34,542 - INFO - Epoch 62/100 - Train Loss: 0.1473 - Val Acc: 0.9420
2026-04-05 05:44:34,831 - INFO - Epoch 63/100 - Train Loss: 0.1504 - Val Acc: 0.9420
2026-04-05 05:44:35,130 - INFO - Epoch 64/100 - Train Loss: 0.1436 - Val Acc: 0.9420
2026-04-05 05:44:35,409 - INFO - Epoch 65/100 - Train Loss: 0.1451 - Val Acc: 0.9420
2026-04-05 05:44:35,680 - INFO - Epoch 66/100 - Train Loss: 0.1474 - Val Acc: 0.9420
2026-04-05 05:44:35,951 - INFO - Epoch 67/100 - Train Loss: 0.1476 - Val Acc: 0.9420
2026-04-05 05:44:36,225 - INFO - Epoch 68/100 - Train Loss: 0.1448 - Val Acc: 0.9420
2026-04-05 05:44:36,487 - INFO - Epoch 69/100 - Train Loss: 0.1430 - Val Acc: 0.9420
2026-04-05 05:44:36,764 - INFO - Epoch 70/100 - Train Loss: 0.1439 - Val Acc: 0.9565
2026-04-05 05:44:37,039 - INFO - Epoch 71/100 - Train Loss: 0.1443 - Val Acc: 0.9565
2026-04-05 05:44:37,313 - INFO - Epoch 72/100 - Train Loss: 0.1452 - Val Acc: 0.9565
2026-04-05 05:44:37,586 - INFO - Epoch 73/100 - Train Loss: 0.1422 - Val Acc: 0.9565
2026-04-05 05:44:37,847 - INFO - Epoch 74/100 - Train Loss: 0.1408 - Val Acc: 0.9565
2026-04-05 05:44:38,123 - INFO - Epoch 75/100 - Train Loss: 0.1390 - Val Acc: 0.9565
2026-04-05 05:44:38,395 - INFO - Epoch 76/100 - Train Loss: 0.1375 - Val Acc: 0.9565
2026-04-05 05:44:38,659 - INFO - Epoch 77/100 - Train Loss: 0.1418 - Val Acc: 0.9565
2026-04-05 05:44:38,926 - INFO - Epoch 78/100 - Train Loss: 0.1364 - Val Acc: 0.9565
2026-04-05 05:44:39,203 - INFO - Epoch 79/100 - Train Loss: 0.1355 - Val Acc: 0.9565
2026-04-05 05:44:39,469 - INFO - Epoch 80/100 - Train Loss: 0.1381 - Val Acc: 0.9565
2026-04-05 05:44:39,730 - INFO - Epoch 81/100 - Train Loss: 0.1348 - Val Acc: 0.9565
2026-04-05 05:44:40,000 - INFO - Epoch 82/100 - Train Loss: 0.1319 - Val Acc: 0.9565
2026-04-05 05:44:40,263 - INFO - Epoch 83/100 - Train Loss: 0.1354 - Val Acc: 0.9565
2026-04-05 05:44:40,517 - INFO - Epoch 84/100 - Train Loss: 0.1310 - Val Acc: 0.9565
2026-04-05 05:44:40,778 - INFO - Epoch 85/100 - Train Loss: 0.1325 - Val Acc: 0.9565
2026-04-05 05:44:41,047 - INFO - Epoch 86/100 - Train Loss: 0.1324 - Val Acc: 0.9565
2026-04-05 05:44:41,313 - INFO - Epoch 87/100 - Train Loss: 0.1261 - Val Acc: 0.9565
2026-04-05 05:44:41,575 - INFO - Epoch 88/100 - Train Loss: 0.1293 - Val Acc: 0.9565
2026-04-05 05:44:41,844 - INFO - Epoch 89/100 - Train Loss: 0.1326 - Val Acc: 0.9565
2026-04-05 05:44:42,100 - INFO - Epoch 90/100 - Train Loss: 0.1309 - Val Acc: 0.9565
2026-04-05 05:44:42,365 - INFO - Epoch 91/100 - Train Loss: 0.1317 - Val Acc: 0.9565
2026-04-05 05:44:42,633 - INFO - Epoch 92/100 - Train Loss: 0.1318 - Val Acc: 0.9565
2026-04-05 05:44:42,893 - INFO - Epoch 93/100 - Train Loss: 0.1263 - Val Acc: 0.9710
2026-04-05 05:44:43,154 - INFO - Epoch 94/100 - Train Loss: 0.1275 - Val Acc: 0.9710
2026-04-05 05:44:43,426 - INFO - Epoch 95/100 - Train Loss: 0.1259 - Val Acc: 0.9710
2026-04-05 05:44:43,682 - INFO - Epoch 96/100 - Train Loss: 0.1241 - Val Acc: 0.9710
2026-04-05 05:44:43,948 - INFO - Epoch 97/100 - Train Loss: 0.1234 - Val Acc: 0.9710
2026-04-05 05:44:44,227 - INFO - Epoch 98/100 - Train Loss: 0.1248 - Val Acc: 0.9710
2026-04-05 05:44:44,514 - INFO - Epoch 99/100 - Train Loss: 0.1252 - Val Acc: 0.9710
2026-04-05 05:44:44,804 - INFO - Epoch 100/100 - Train Loss: 0.1234 - Val Acc: 0.9710
2026-04-05 05:44:45,168 - INFO - Fold 10 logically complete. Tensor memory bounds cleared cleanly.
2026-04-05 05:44:45,185 - INFO - ✓ Completed GRU_smoteenn
2026-04-05 05:44:45,185 - INFO -   Mean Accuracy: 0.8768 ± 0.0473

GERMAN DATASET - FINAL RESULTS SUMMARY

,Experiment,Mean_Accuracy,Std_Accuracy,Mean_Sensitivity,Std_Sensitivity,Mean_Specificity,Std_Specificity
0,MLP_baseline,0.884058,0.048933,0.903576,0.046483,0.861075,0.108754
1,MLP_smoteenn,0.875362,0.047716,0.840823,0.057802,0.919247,0.080581
2,LSTM_baseline,0.891304,0.041120,0.919366,0.034981,0.857849,0.105066
3,LSTM_smoteenn,0.879710,0.047207,0.845951,0.058107,0.922473,0.070900
4,GRU_baseline,0.894203,0.040502,0.919366,0.034981,0.864301,0.103684
5,GRU_smoteenn,0.876812,0.047296,0.845951,0.054415,0.916022,0.080512

## ***Australian Dataset Experimental Execution***

***Purpose:*** Execute complete 10-fold cross-validation natively deploying dataset-specific preprocessing mechanisms (mode/mean + numerical boundaries strictly resolved) as implemented previously inside Section 6.

In [22]:
logger.info("="*80)
logger.info("BEGINNING AUSTRALIAN DATASET EXPERIMENTAL PHASE")
logger.info("="*80)

x_australian = df_australian.iloc[:, :-1]
y_australian = MapAustralianLabels(df_australian.iloc[:, -1].values)

DATASET_NAME = 'australian'

australian_results = {}
best_australian_shap_pkg = {'acc': -1}

for model_name in MODELS_TO_TEST:
    for use_smote in RESAMPLING_CONDITIONS:
        condition_name = 'smoteenn' if use_smote else 'baseline'
        experiment_key = f"{model_name}_{condition_name}"
        
        logger.info(f"\nEXPERIMENT: {experiment_key.upper()} | {DATASET_NAME} | SMOTE-ENN: {use_smote}")
        
        results_dict = RunCrossValidationExperiment(
            dataset_name=DATASET_NAME,
            model_name=model_name,
            x_data=x_australian,
            y_data=y_australian,
            use_smote_enn=use_smote,
            n_folds=10,
            epochs=NUM_EPOCHS,
            batch_size=32 if model_name == 'MLP' else 64
        )
        
        australian_results[experiment_key] = results_dict
        logger.info(f"✓ Completed {experiment_key} -> Acc: {results_dict['mean_accuracy']:.4f}")
        
        if results_dict['mean_accuracy'] > best_australian_shap_pkg['acc']:
            best_australian_shap_pkg = {
                'acc': results_dict['mean_accuracy'],
                'model_name': model_name,
                'state': results_dict['best_state'],
                'input_dim': results_dict['input_dim'],
                'x_val': results_dict['x_val']
            }

australian_summary_df = pd.DataFrame({
    'Experiment': list(australian_results.keys()),
    'Mean_Accuracy': [australian_results[k]['mean_accuracy'] for k in australian_results.keys()],
    'Std_Accuracy': [australian_results[k]['std_accuracy'] for k in australian_results.keys()],
    'Mean_Sensitivity': [australian_results[k]['mean_sensitivity'] for k in australian_results.keys()],
    'Std_Sensitivity': [australian_results[k]['std_sensitivity'] for k in australian_results.keys()],
    'Mean_Specificity': [australian_results[k]['mean_specificity'] for k in australian_results.keys()],
    'Std_Specificity': [australian_results[k]['std_specificity'] for k in australian_results.keys()]
})

australian_summary_df.to_csv('results/metrics/australian_summary_results.csv', index=False)
print("\nAUSTRALIAN DATASET - FINAL RESULTS SUMMARY")
display(australian_summary_df)

2026-04-05 05:44:45,205 - INFO - ================================================================================
2026-04-05 05:44:45,206 - INFO - BEGINNING AUSTRALIAN DATASET EXPERIMENTAL PHASE
2026-04-05 05:44:45,207 - INFO - ================================================================================
2026-04-05 05:44:45,209 - INFO -
EXPERIMENT: MLP_BASELINE | australian | SMOTE-ENN: False

Australian | MLP | BASELINE:   0%|          | 0/10 [00:00<?, ?it/s]

2026-04-05 05:44:45,224 - INFO - Original class distribution: [344 277]
2026-04-05 05:44:45,224 - INFO - Training device bound securely to: cuda

Fold 1:   0%|          | 0/100 [00:00<?, ?it/s]

2026-04-05 05:44:45,579 - INFO - Epoch 1/100 - Train Loss: 0.6119 - Val Acc: 0.8696
2026-04-05 05:44:45,897 - INFO - Epoch 2/100 - Train Loss: 0.4408 - Val Acc: 0.8986
2026-04-05 05:44:46,216 - INFO - Epoch 3/100 - Train Loss: 0.3683 - Val Acc: 0.8986
2026-04-05 05:44:46,538 - INFO - Epoch 4/100 - Train Loss: 0.3184 - Val Acc: 0.9130
2026-04-05 05:44:46,852 - INFO - Epoch 5/100 - Train Loss: 0.3213 - Val Acc: 0.9130
2026-04-05 05:44:47,170 - INFO - Epoch 6/100 - Train Loss: 0.3073 - Val Acc: 0.8986
2026-04-05 05:44:47,482 - INFO - Epoch 7/100 - Train Loss: 0.3172 - Val Acc: 0.8986
2026-04-05 05:44:47,810 - INFO - Epoch 8/100 - Train Loss: 0.3078 - Val Acc: 0.8841
2026-04-05 05:44:48,138 - INFO - Epoch 9/100 - Train Loss: 0.3053 - Val Acc: 0.8841
2026-04-05 05:44:48,456 - INFO - Epoch 10/100 - Train Loss: 0.2910 - Val Acc: 0.8986
2026-04-05 05:44:48,775 - INFO - Epoch 11/100 - Train Loss: 0.2916 - Val Acc: 0.8986
2026-04-05 05:44:49,084 - INFO - Epoch 12/100 - Train Loss: 0.2769 - Val Acc: 0.9130
2026-04-05 05:44:49,403 - INFO - Epoch 13/100 - Train Loss: 0.2871 - Val Acc: 0.8986
2026-04-05 05:44:49,721 - INFO - Epoch 14/100 - Train Loss: 0.2738 - Val Acc: 0.8986
2026-04-05 05:44:50,043 - INFO - Epoch 15/100 - Train Loss: 0.2667 - Val Acc: 0.8841
2026-04-05 05:44:50,383 - INFO - Epoch 16/100 - Train Loss: 0.2720 - Val Acc: 0.8841
2026-04-05 05:44:50,707 - INFO - Epoch 17/100 - Train Loss: 0.2604 - Val Acc: 0.8841
2026-04-05 05:44:51,030 - INFO - Epoch 18/100 - Train Loss: 0.2584 - Val Acc: 0.8986
2026-04-05 05:44:51,343 - INFO - Epoch 19/100 - Train Loss: 0.2531 - Val Acc: 0.9130
2026-04-05 05:44:51,656 - INFO - Epoch 20/100 - Train Loss: 0.2659 - Val Acc: 0.8986
2026-04-05 05:44:51,989 - INFO - Epoch 21/100 - Train Loss: 0.2493 - Val Acc: 0.8841
2026-04-05 05:44:52,320 - INFO - Epoch 22/100 - Train Loss: 0.2379 - Val Acc: 0.8986
2026-04-05 05:44:52,647 - INFO - Epoch 23/100 - Train Loss: 0.2591 - Val Acc: 0.8841
2026-04-05 05:44:52,975 - INFO - Epoch 24/100 - Train Loss: 0.2372 - Val Acc: 0.8986
2026-04-05 05:44:53,289 - INFO - Epoch 25/100 - Train Loss: 0.2394 - Val Acc: 0.8986
2026-04-05 05:44:53,599 - INFO - Epoch 26/100 - Train Loss: 0.2347 - Val Acc: 0.8841
2026-04-05 05:44:53,926 - INFO - Epoch 27/100 - Train Loss: 0.2364 - Val Acc: 0.8841
2026-04-05 05:44:54,260 - INFO - Epoch 28/100 - Train Loss: 0.2349 - Val Acc: 0.8986
2026-04-05 05:44:54,602 - INFO - Epoch 29/100 - Train Loss: 0.2424 - Val Acc: 0.8841
2026-04-05 05:44:54,917 - INFO - Epoch 30/100 - Train Loss: 0.2330 - Val Acc: 0.8986
2026-04-05 05:44:55,238 - INFO - Epoch 31/100 - Train Loss: 0.2279 - Val Acc: 0.8986
2026-04-05 05:44:55,551 - INFO - Epoch 32/100 - Train Loss: 0.2238 - Val Acc: 0.8986
2026-04-05 05:44:55,863 - INFO - Epoch 33/100 - Train Loss: 0.2236 - Val Acc: 0.8841
2026-04-05 05:44:56,181 - INFO - Epoch 34/100 - Train Loss: 0.2185 - Val Acc: 0.8986
2026-04-05 05:44:56,511 - INFO - Epoch 35/100 - Train Loss: 0.2120 - Val Acc: 0.8986
2026-04-05 05:44:56,828 - INFO - Epoch 36/100 - Train Loss: 0.2081 - Val Acc: 0.8986
2026-04-05 05:44:57,144 - INFO - Epoch 37/100 - Train Loss: 0.2105 - Val Acc: 0.8986
2026-04-05 05:44:57,464 - INFO - Epoch 38/100 - Train Loss: 0.2137 - Val Acc: 0.8986
2026-04-05 05:44:57,784 - INFO - Epoch 39/100 - Train Loss: 0.2065 - Val Acc: 0.8841
2026-04-05 05:44:58,103 - INFO - Epoch 40/100 - Train Loss: 0.2032 - Val Acc: 0.8986
2026-04-05 05:44:58,433 - INFO - Epoch 41/100 - Train Loss: 0.2063 - Val Acc: 0.8986
2026-04-05 05:44:58,751 - INFO - Epoch 42/100 - Train Loss: 0.2100 - Val Acc: 0.8986
2026-04-05 05:44:59,081 - INFO - Epoch 43/100 - Train Loss: 0.2011 - Val Acc: 0.8841
2026-04-05 05:44:59,407 - INFO - Epoch 44/100 - Train Loss: 0.1817 - Val Acc: 0.8841
2026-04-05 05:44:59,713 - INFO - Epoch 45/100 - Train Loss: 0.1911 - Val Acc: 0.8696
2026-04-05 05:45:00,033 - INFO - Epoch 46/100 - Train Loss: 0.2027 - Val Acc: 0.8696
2026-04-05 05:45:00,350 - INFO - Epoch 47/100 - Train Loss: 0.1970 - Val Acc: 0.8841
2026-04-05 05:45:00,670 - INFO - Epoch 48/100 - Train Loss: 0.1813 - Val Acc: 0.8696
2026-04-05 05:45:00,985 - INFO - Epoch 49/100 - Train Loss: 0.1931 - Val Acc: 0.8696
2026-04-05 05:45:01,315 - INFO - Epoch 50/100 - Train Loss: 0.1887 - Val Acc: 0.8696
2026-04-05 05:45:01,643 - INFO - Epoch 51/100 - Train Loss: 0.1915 - Val Acc: 0.8696
2026-04-05 05:45:01,961 - INFO - Epoch 52/100 - Train Loss: 0.1897 - Val Acc: 0.8551
2026-04-05 05:45:02,278 - INFO - Epoch 53/100 - Train Loss: 0.1847 - Val Acc: 0.8696
2026-04-05 05:45:02,609 - INFO - Epoch 54/100 - Train Loss: 0.1892 - Val Acc: 0.8551
2026-04-05 05:45:02,922 - INFO - Epoch 55/100 - Train Loss: 0.1733 - Val Acc: 0.8551
2026-04-05 05:45:03,245 - INFO - Epoch 56/100 - Train Loss: 0.1665 - Val Acc: 0.8551
2026-04-05 05:45:03,571 - INFO - Epoch 57/100 - Train Loss: 0.1776 - Val Acc: 0.8551
2026-04-05 05:45:03,887 - INFO - Epoch 58/100 - Train Loss: 0.1727 - Val Acc: 0.8696
2026-04-05 05:45:04,214 - INFO - Epoch 59/100 - Train Loss: 0.1766 - Val Acc: 0.8551
2026-04-05 05:45:04,553 - INFO - Epoch 60/100 - Train Loss: 0.1811 - Val Acc: 0.8696
2026-04-05 05:45:04,890 - INFO - Epoch 61/100 - Train Loss: 0.1686 - Val Acc: 0.8696
2026-04-05 05:45:05,209 - INFO - Epoch 62/100 - Train Loss: 0.1720 - Val Acc: 0.8696
2026-04-05 05:45:05,526 - INFO - Epoch 63/100 - Train Loss: 0.1724 - Val Acc: 0.8696
2026-04-05 05:45:05,850 - INFO - Epoch 64/100 - Train Loss: 0.1628 - Val Acc: 0.8696
2026-04-05 05:45:06,172 - INFO - Epoch 65/100 - Train Loss: 0.1586 - Val Acc: 0.8696
2026-04-05 05:45:06,506 - INFO - Epoch 66/100 - Train Loss: 0.1654 - Val Acc: 0.8696
2026-04-05 05:45:06,835 - INFO - Epoch 67/100 - Train Loss: 0.1623 - Val Acc: 0.8841
2026-04-05 05:45:07,171 - INFO - Epoch 68/100 - Train Loss: 0.1501 - Val Acc: 0.8551
2026-04-05 05:45:07,492 - INFO - Epoch 69/100 - Train Loss: 0.1560 - Val Acc: 0.8551
2026-04-05 05:45:07,809 - INFO - Epoch 70/100 - Train Loss: 0.1517 - Val Acc: 0.8841
2026-04-05 05:45:08,130 - INFO - Epoch 71/100 - Train Loss: 0.1598 - Val Acc: 0.8696
2026-04-05 05:45:08,445 - INFO - Epoch 72/100 - Train Loss: 0.1415 - Val Acc: 0.8696
2026-04-05 05:45:08,757 - INFO - Epoch 73/100 - Train Loss: 0.1586 - Val Acc: 0.8551
2026-04-05 05:45:09,083 - INFO - Epoch 74/100 - Train Loss: 0.1483 - Val Acc: 0.8551
2026-04-05 05:45:09,424 - INFO - Epoch 75/100 - Train Loss: 0.1585 - Val Acc: 0.8696
2026-04-05 05:45:09,758 - INFO - Epoch 76/100 - Train Loss: 0.1565 - Val Acc: 0.8696
2026-04-05 05:45:10,081 - INFO - Epoch 77/100 - Train Loss: 0.1502 - Val Acc: 0.8696
2026-04-05 05:45:10,396 - INFO - Epoch 78/100 - Train Loss: 0.1415 - Val Acc: 0.8841
2026-04-05 05:45:10,728 - INFO - Epoch 79/100 - Train Loss: 0.1496 - Val Acc: 0.8551
2026-04-05 05:45:11,049 - INFO - Epoch 80/100 - Train Loss: 0.1432 - Val Acc: 0.8551
2026-04-05 05:45:11,361 - INFO - Epoch 81/100 - Train Loss: 0.1362 - Val Acc: 0.8696
2026-04-05 05:45:11,674 - INFO - Epoch 82/100 - Train Loss: 0.1456 - Val Acc: 0.8551
2026-04-05 05:45:11,992 - INFO - Epoch 83/100 - Train Loss: 0.1458 - Val Acc: 0.8841
2026-04-05 05:45:12,315 - INFO - Epoch 84/100 - Train Loss: 0.1495 - Val Acc: 0.8551
2026-04-05 05:45:12,641 - INFO - Epoch 85/100 - Train Loss: 0.1402 - Val Acc: 0.8551
2026-04-05 05:45:12,963 - INFO - Epoch 86/100 - Train Loss: 0.1367 - Val Acc: 0.8406
2026-04-05 05:45:13,279 - INFO - Epoch 87/100 - Train Loss: 0.1445 - Val Acc: 0.8551
2026-04-05 05:45:13,610 - INFO - Epoch 88/100 - Train Loss: 0.1334 - Val Acc: 0.8551
2026-04-05 05:45:13,933 - INFO - Epoch 89/100 - Train Loss: 0.1282 - Val Acc: 0.8841
2026-04-05 05:45:14,260 - INFO - Epoch 90/100 - Train Loss: 0.1223 - Val Acc: 0.8696
2026-04-05 05:45:14,600 - INFO - Epoch 91/100 - Train Loss: 0.1368 - Val Acc: 0.8406
2026-04-05 05:45:14,921 - INFO - Epoch 92/100 - Train Loss: 0.1387 - Val Acc: 0.8261
2026-04-05 05:45:15,240 - INFO - Epoch 93/100 - Train Loss: 0.1280 - Val Acc: 0.8551
2026-04-05 05:45:15,568 - INFO - Epoch 94/100 - Train Loss: 0.1318 - Val Acc: 0.8551
2026-04-05 05:45:15,888 - INFO - Epoch 95/100 - Train Loss: 0.1301 - Val Acc: 0.8551
2026-04-05 05:45:16,214 - INFO - Epoch 96/100 - Train Loss: 0.1469 - Val Acc: 0.8551
2026-04-05 05:45:16,533 - INFO - Epoch 97/100 - Train Loss: 0.1246 - Val Acc: 0.8406
2026-04-05 05:45:16,855 - INFO - Epoch 98/100 - Train Loss: 0.1192 - Val Acc: 0.8406
2026-04-05 05:45:17,168 - INFO - Epoch 99/100 - Train Loss: 0.1253 - Val Acc: 0.8551
2026-04-05 05:45:17,500 - INFO - Epoch 100/100 - Train Loss: 0.1028 - Val Acc: 0.8406
2026-04-05 05:45:17,865 - INFO - Fold 1 logically complete. Tensor memory bounds cleared cleanly.
2026-04-05 05:45:17,869 - INFO - Original class distribution: [344 277]
2026-04-05 05:45:17,870 - INFO - Training device bound securely to: cuda

Fold 2:   0%|          | 0/100 [00:00<?, ?it/s]

2026-04-05 05:45:18,216 - INFO - Epoch 1/100 - Train Loss: 0.6211 - Val Acc: 0.8406
2026-04-05 05:45:18,541 - INFO - Epoch 2/100 - Train Loss: 0.4404 - Val Acc: 0.8406
2026-04-05 05:45:18,875 - INFO - Epoch 3/100 - Train Loss: 0.3481 - Val Acc: 0.8696
2026-04-05 05:45:19,193 - INFO - Epoch 4/100 - Train Loss: 0.3152 - Val Acc: 0.8986
2026-04-05 05:45:19,509 - INFO - Epoch 5/100 - Train Loss: 0.3118 - Val Acc: 0.8986
2026-04-05 05:45:19,829 - INFO - Epoch 6/100 - Train Loss: 0.3044 - Val Acc: 0.9130
2026-04-05 05:45:20,144 - INFO - Epoch 7/100 - Train Loss: 0.3056 - Val Acc: 0.8841
2026-04-05 05:45:20,474 - INFO - Epoch 8/100 - Train Loss: 0.3005 - Val Acc: 0.8841
2026-04-05 05:45:20,808 - INFO - Epoch 9/100 - Train Loss: 0.2810 - Val Acc: 0.9130
2026-04-05 05:45:21,131 - INFO - Epoch 10/100 - Train Loss: 0.2761 - Val Acc: 0.9130
2026-04-05 05:45:21,450 - INFO - Epoch 11/100 - Train Loss: 0.2736 - Val Acc: 0.8841
2026-04-05 05:45:21,770 - INFO - Epoch 12/100 - Train Loss: 0.2628 - Val Acc: 0.8986
2026-04-05 05:45:22,097 - INFO - Epoch 13/100 - Train Loss: 0.2668 - Val Acc: 0.8986
2026-04-05 05:45:22,417 - INFO - Epoch 14/100 - Train Loss: 0.2666 - Val Acc: 0.8986
2026-04-05 05:45:22,740 - INFO - Epoch 15/100 - Train Loss: 0.2684 - Val Acc: 0.8841
2026-04-05 05:45:23,049 - INFO - Epoch 16/100 - Train Loss: 0.2578 - Val Acc: 0.9130
2026-04-05 05:45:23,376 - INFO - Epoch 17/100 - Train Loss: 0.2471 - Val Acc: 0.8986
2026-04-05 05:45:23,700 - INFO - Epoch 18/100 - Train Loss: 0.2619 - Val Acc: 0.8841
2026-04-05 05:45:24,012 - INFO - Epoch 19/100 - Train Loss: 0.2543 - Val Acc: 0.9130
2026-04-05 05:45:24,329 - INFO - Epoch 20/100 - Train Loss: 0.2511 - Val Acc: 0.8986
2026-04-05 05:45:24,667 - INFO - Epoch 21/100 - Train Loss: 0.2360 - Val Acc: 0.8986
2026-04-05 05:45:24,995 - INFO - Epoch 22/100 - Train Loss: 0.2472 - Val Acc: 0.8986
2026-04-05 05:45:25,318 - INFO - Epoch 23/100 - Train Loss: 0.2400 - Val Acc: 0.8841
2026-04-05 05:45:25,633 - INFO - Epoch 24/100 - Train Loss: 0.2292 - Val Acc: 0.8986
2026-04-05 05:45:25,949 - INFO - Epoch 25/100 - Train Loss: 0.2322 - Val Acc: 0.9130
2026-04-05 05:45:26,266 - INFO - Epoch 26/100 - Train Loss: 0.2435 - Val Acc: 0.8841
2026-04-05 05:45:26,605 - INFO - Epoch 27/100 - Train Loss: 0.2265 - Val Acc: 0.8841
2026-04-05 05:45:26,929 - INFO - Epoch 28/100 - Train Loss: 0.2283 - Val Acc: 0.8841
2026-04-05 05:45:27,260 - INFO - Epoch 29/100 - Train Loss: 0.2243 - Val Acc: 0.8986
2026-04-05 05:45:27,568 - INFO - Epoch 30/100 - Train Loss: 0.2186 - Val Acc: 0.8841
2026-04-05 05:45:27,889 - INFO - Epoch 31/100 - Train Loss: 0.2285 - Val Acc: 0.9130
2026-04-05 05:45:28,204 - INFO - Epoch 32/100 - Train Loss: 0.2252 - Val Acc: 0.8841
2026-04-05 05:45:28,527 - INFO - Epoch 33/100 - Train Loss: 0.2176 - Val Acc: 0.8986
2026-04-05 05:45:28,848 - INFO - Epoch 34/100 - Train Loss: 0.2069 - Val Acc: 0.8841
2026-04-05 05:45:29,168 - INFO - Epoch 35/100 - Train Loss: 0.2051 - Val Acc: 0.8841
2026-04-05 05:45:29,488 - INFO - Epoch 36/100 - Train Loss: 0.2102 - Val Acc: 0.8841
2026-04-05 05:45:29,810 - INFO - Epoch 37/100 - Train Loss: 0.2109 - Val Acc: 0.8841
2026-04-05 05:45:30,124 - INFO - Epoch 38/100 - Train Loss: 0.2117 - Val Acc: 0.8841
2026-04-05 05:45:30,439 - INFO - Epoch 39/100 - Train Loss: 0.2150 - Val Acc: 0.8841
2026-04-05 05:45:30,769 - INFO - Epoch 40/100 - Train Loss: 0.2074 - Val Acc: 0.8696
2026-04-05 05:45:31,094 - INFO - Epoch 41/100 - Train Loss: 0.2021 - Val Acc: 0.8696
2026-04-05 05:45:31,418 - INFO - Epoch 42/100 - Train Loss: 0.2053 - Val Acc: 0.8696
2026-04-05 05:45:31,735 - INFO - Epoch 43/100 - Train Loss: 0.2040 - Val Acc: 0.8986
2026-04-05 05:45:32,062 - INFO - Epoch 44/100 - Train Loss: 0.2048 - Val Acc: 0.8841
2026-04-05 05:45:32,381 - INFO - Epoch 45/100 - Train Loss: 0.1929 - Val Acc: 0.8986
2026-04-05 05:45:32,703 - INFO - Epoch 46/100 - Train Loss: 0.1981 - Val Acc: 0.8841
2026-04-05 05:45:33,026 - INFO - Epoch 47/100 - Train Loss: 0.1899 - Val Acc: 0.9130
2026-04-05 05:45:33,358 - INFO - Epoch 48/100 - Train Loss: 0.1940 - Val Acc: 0.9130
2026-04-05 05:45:33,688 - INFO - Epoch 49/100 - Train Loss: 0.2024 - Val Acc: 0.8986
2026-04-05 05:45:34,012 - INFO - Epoch 50/100 - Train Loss: 0.1951 - Val Acc: 0.8841
2026-04-05 05:45:34,331 - INFO - Epoch 51/100 - Train Loss: 0.1885 - Val Acc: 0.9130
2026-04-05 05:45:34,691 - INFO - Epoch 52/100 - Train Loss: 0.1714 - Val Acc: 0.8841
2026-04-05 05:45:35,017 - INFO - Epoch 53/100 - Train Loss: 0.1737 - Val Acc: 0.8841
2026-04-05 05:45:35,339 - INFO - Epoch 54/100 - Train Loss: 0.1729 - Val Acc: 0.8841
2026-04-05 05:45:35,662 - INFO - Epoch 55/100 - Train Loss: 0.1712 - Val Acc: 0.8986
2026-04-05 05:45:35,979 - INFO - Epoch 56/100 - Train Loss: 0.1756 - Val Acc: 0.8841
2026-04-05 05:45:36,301 - INFO - Epoch 57/100 - Train Loss: 0.1717 - Val Acc: 0.8986
2026-04-05 05:45:36,627 - INFO - Epoch 58/100 - Train Loss: 0.1617 - Val Acc: 0.8841
2026-04-05 05:45:36,951 - INFO - Epoch 59/100 - Train Loss: 0.1650 - Val Acc: 0.8841
2026-04-05 05:45:37,267 - INFO - Epoch 60/100 - Train Loss: 0.1733 - Val Acc: 0.8841
2026-04-05 05:45:37,596 - INFO - Epoch 61/100 - Train Loss: 0.1622 - Val Acc: 0.8841
2026-04-05 05:45:37,925 - INFO - Epoch 62/100 - Train Loss: 0.1498 - Val Acc: 0.8986
2026-04-05 05:45:38,250 - INFO - Epoch 63/100 - Train Loss: 0.1539 - Val Acc: 0.8841
2026-04-05 05:45:38,581 - INFO - Epoch 64/100 - Train Loss: 0.1649 - Val Acc: 0.8841
2026-04-05 05:45:38,901 - INFO - Epoch 65/100 - Train Loss: 0.1722 - Val Acc: 0.8986
2026-04-05 05:45:39,227 - INFO - Epoch 66/100 - Train Loss: 0.1624 - Val Acc: 0.8986
2026-04-05 05:45:39,554 - INFO - Epoch 67/100 - Train Loss: 0.1632 - Val Acc: 0.8841
2026-04-05 05:45:39,875 - INFO - Epoch 68/100 - Train Loss: 0.1562 - Val Acc: 0.8841
2026-04-05 05:45:40,197 - INFO - Epoch 69/100 - Train Loss: 0.1459 - Val Acc: 0.8986
2026-04-05 05:45:40,519 - INFO - Epoch 70/100 - Train Loss: 0.1545 - Val Acc: 0.8841
2026-04-05 05:45:40,842 - INFO - Epoch 71/100 - Train Loss: 0.1486 - Val Acc: 0.8841
2026-04-05 05:45:41,165 - INFO - Epoch 72/100 - Train Loss: 0.1438 - Val Acc: 0.8841
2026-04-05 05:45:41,476 - INFO - Epoch 73/100 - Train Loss: 0.1634 - Val Acc: 0.8986
2026-04-05 05:45:41,810 - INFO - Epoch 74/100 - Train Loss: 0.1395 - Val Acc: 0.8841
2026-04-05 05:45:42,125 - INFO - Epoch 75/100 - Train Loss: 0.1561 - Val Acc: 0.8841
2026-04-05 05:45:42,466 - INFO - Epoch 76/100 - Train Loss: 0.1519 - Val Acc: 0.8841
2026-04-05 05:45:42,791 - INFO - Epoch 77/100 - Train Loss: 0.1570 - Val Acc: 0.8841
2026-04-05 05:45:43,109 - INFO - Epoch 78/100 - Train Loss: 0.1394 - Val Acc: 0.8841
2026-04-05 05:45:43,430 - INFO - Epoch 79/100 - Train Loss: 0.1565 - Val Acc: 0.8841
2026-04-05 05:45:43,757 - INFO - Epoch 80/100 - Train Loss: 0.1540 - Val Acc: 0.8986
2026-04-05 05:45:44,070 - INFO - Epoch 81/100 - Train Loss: 0.1419 - Val Acc: 0.8841
2026-04-05 05:45:44,393 - INFO - Epoch 82/100 - Train Loss: 0.1440 - Val Acc: 0.8841
2026-04-05 05:45:44,744 - INFO - Epoch 83/100 - Train Loss: 0.1252 - Val Acc: 0.8841
2026-04-05 05:45:45,063 - INFO - Epoch 84/100 - Train Loss: 0.1327 - Val Acc: 0.8841
2026-04-05 05:45:45,385 - INFO - Epoch 85/100 - Train Loss: 0.1288 - Val Acc: 0.8696
2026-04-05 05:45:45,714 - INFO - Epoch 86/100 - Train Loss: 0.1253 - Val Acc: 0.8841
2026-04-05 05:45:46,041 - INFO - Epoch 87/100 - Train Loss: 0.1383 - Val Acc: 0.8696
2026-04-05 05:45:46,358 - INFO - Epoch 88/100 - Train Loss: 0.1245 - Val Acc: 0.8841
2026-04-05 05:45:46,668 - INFO - Epoch 89/100 - Train Loss: 0.1201 - Val Acc: 0.8986
2026-04-05 05:45:46,991 - INFO - Epoch 90/100 - Train Loss: 0.1116 - Val Acc: 0.8841
2026-04-05 05:45:47,306 - INFO - Epoch 91/100 - Train Loss: 0.1210 - Val Acc: 0.8696
2026-04-05 05:45:47,639 - INFO - Epoch 92/100 - Train Loss: 0.1419 - Val Acc: 0.8696
2026-04-05 05:45:47,954 - INFO - Epoch 93/100 - Train Loss: 0.1403 - Val Acc: 0.8986
2026-04-05 05:45:48,283 - INFO - Epoch 94/100 - Train Loss: 0.1094 - Val Acc: 0.8696
2026-04-05 05:45:48,604 - INFO - Epoch 95/100 - Train Loss: 0.1251 - Val Acc: 0.8696
2026-04-05 05:45:48,927 - INFO - Epoch 96/100 - Train Loss: 0.1285 - Val Acc: 0.8696
2026-04-05 05:45:49,250 - INFO - Epoch 97/100 - Train Loss: 0.1411 - Val Acc: 0.8841
2026-04-05 05:45:49,565 - INFO - Epoch 98/100 - Train Loss: 0.1118 - Val Acc: 0.8841
2026-04-05 05:45:49,886 - INFO - Epoch 99/100 - Train Loss: 0.1153 - Val Acc: 0.8986
2026-04-05 05:45:50,197 - INFO - Epoch 100/100 - Train Loss: 0.1379 - Val Acc: 0.8841
2026-04-05 05:45:50,561 - INFO - Fold 2 logically complete. Tensor memory bounds cleared cleanly.
2026-04-05 05:45:50,565 - INFO - Original class distribution: [344 277]
2026-04-05 05:45:50,566 - INFO - Training device bound securely to: cuda

Fold 3:   0%|          | 0/100 [00:00<?, ?it/s]

2026-04-05 05:45:50,919 - INFO - Epoch 1/100 - Train Loss: 0.6075 - Val Acc: 0.9275
2026-04-05 05:45:51,246 - INFO - Epoch 2/100 - Train Loss: 0.4420 - Val Acc: 0.9275
2026-04-05 05:45:51,561 - INFO - Epoch 3/100 - Train Loss: 0.3560 - Val Acc: 0.9130
2026-04-05 05:45:51,896 - INFO - Epoch 4/100 - Train Loss: 0.3371 - Val Acc: 0.9130
2026-04-05 05:45:52,219 - INFO - Epoch 5/100 - Train Loss: 0.3277 - Val Acc: 0.9130
2026-04-05 05:45:52,536 - INFO - Epoch 6/100 - Train Loss: 0.3130 - Val Acc: 0.9130
2026-04-05 05:45:52,852 - INFO - Epoch 7/100 - Train Loss: 0.3119 - Val Acc: 0.9130
2026-04-05 05:45:53,170 - INFO - Epoch 8/100 - Train Loss: 0.3114 - Val Acc: 0.9130
2026-04-05 05:45:53,492 - INFO - Epoch 9/100 - Train Loss: 0.2937 - Val Acc: 0.9130
2026-04-05 05:45:53,804 - INFO - Epoch 10/100 - Train Loss: 0.2953 - Val Acc: 0.9130
2026-04-05 05:45:54,125 - INFO - Epoch 11/100 - Train Loss: 0.2912 - Val Acc: 0.9130
2026-04-05 05:45:54,470 - INFO - Epoch 12/100 - Train Loss: 0.2827 - Val Acc: 0.9130
2026-04-05 05:45:54,814 - INFO - Epoch 13/100 - Train Loss: 0.2829 - Val Acc: 0.9130
2026-04-05 05:45:55,132 - INFO - Epoch 14/100 - Train Loss: 0.2730 - Val Acc: 0.9130
2026-04-05 05:45:55,457 - INFO - Epoch 15/100 - Train Loss: 0.2717 - Val Acc: 0.9130
2026-04-05 05:45:55,774 - INFO - Epoch 16/100 - Train Loss: 0.2751 - Val Acc: 0.9130
2026-04-05 05:45:56,090 - INFO - Epoch 17/100 - Train Loss: 0.2698 - Val Acc: 0.9130
2026-04-05 05:45:56,405 - INFO - Epoch 18/100 - Train Loss: 0.2632 - Val Acc: 0.9130
2026-04-05 05:45:56,717 - INFO - Epoch 19/100 - Train Loss: 0.2617 - Val Acc: 0.9130
2026-04-05 05:45:57,046 - INFO - Epoch 20/100 - Train Loss: 0.2570 - Val Acc: 0.9130
2026-04-05 05:45:57,366 - INFO - Epoch 21/100 - Train Loss: 0.2508 - Val Acc: 0.9130
2026-04-05 05:45:57,692 - INFO - Epoch 22/100 - Train Loss: 0.2475 - Val Acc: 0.9130
2026-04-05 05:45:58,009 - INFO - Epoch 23/100 - Train Loss: 0.2472 - Val Acc: 0.9275
2026-04-05 05:45:58,334 - INFO - Epoch 24/100 - Train Loss: 0.2505 - Val Acc: 0.9275
2026-04-05 05:45:58,658 - INFO - Epoch 25/100 - Train Loss: 0.2449 - Val Acc: 0.9275
2026-04-05 05:45:58,981 - INFO - Epoch 26/100 - Train Loss: 0.2519 - Val Acc: 0.9275
2026-04-05 05:45:59,306 - INFO - Epoch 27/100 - Train Loss: 0.2408 - Val Acc: 0.9275
2026-04-05 05:45:59,638 - INFO - Epoch 28/100 - Train Loss: 0.2454 - Val Acc: 0.9275
2026-04-05 05:45:59,965 - INFO - Epoch 29/100 - Train Loss: 0.2194 - Val Acc: 0.9275
2026-04-05 05:46:00,281 - INFO - Epoch 30/100 - Train Loss: 0.2222 - Val Acc: 0.9275
2026-04-05 05:46:00,602 - INFO - Epoch 31/100 - Train Loss: 0.2319 - Val Acc: 0.9275
2026-04-05 05:46:00,938 - INFO - Epoch 32/100 - Train Loss: 0.2118 - Val Acc: 0.9130
2026-04-05 05:46:01,257 - INFO - Epoch 33/100 - Train Loss: 0.2120 - Val Acc: 0.9275
2026-04-05 05:46:01,580 - INFO - Epoch 34/100 - Train Loss: 0.2175 - Val Acc: 0.9275
2026-04-05 05:46:01,899 - INFO - Epoch 35/100 - Train Loss: 0.2131 - Val Acc: 0.9275
2026-04-05 05:46:02,213 - INFO - Epoch 36/100 - Train Loss: 0.2226 - Val Acc: 0.9275
2026-04-05 05:46:02,539 - INFO - Epoch 37/100 - Train Loss: 0.2297 - Val Acc: 0.9275
2026-04-05 05:46:02,870 - INFO - Epoch 38/100 - Train Loss: 0.2122 - Val Acc: 0.9275
2026-04-05 05:46:03,184 - INFO - Epoch 39/100 - Train Loss: 0.1956 - Val Acc: 0.9275
2026-04-05 05:46:03,509 - INFO - Epoch 40/100 - Train Loss: 0.2098 - Val Acc: 0.9275
2026-04-05 05:46:03,835 - INFO - Epoch 41/100 - Train Loss: 0.2143 - Val Acc: 0.9275
2026-04-05 05:46:04,161 - INFO - Epoch 42/100 - Train Loss: 0.2143 - Val Acc: 0.9275
2026-04-05 05:46:04,487 - INFO - Epoch 43/100 - Train Loss: 0.1929 - Val Acc: 0.9275
2026-04-05 05:46:04,850 - INFO - Epoch 44/100 - Train Loss: 0.2015 - Val Acc: 0.9275
2026-04-05 05:46:05,171 - INFO - Epoch 45/100 - Train Loss: 0.1978 - Val Acc: 0.9275
2026-04-05 05:46:05,487 - INFO - Epoch 46/100 - Train Loss: 0.2048 - Val Acc: 0.9275
2026-04-05 05:46:05,829 - INFO - Epoch 47/100 - Train Loss: 0.1942 - Val Acc: 0.9275
2026-04-05 05:46:06,156 - INFO - Epoch 48/100 - Train Loss: 0.1914 - Val Acc: 0.9275
2026-04-05 05:46:06,473 - INFO - Epoch 49/100 - Train Loss: 0.1927 - Val Acc: 0.9275
2026-04-05 05:46:06,791 - INFO - Epoch 50/100 - Train Loss: 0.1839 - Val Acc: 0.9275
2026-04-05 05:46:07,124 - INFO - Epoch 51/100 - Train Loss: 0.1970 - Val Acc: 0.9275
2026-04-05 05:46:07,442 - INFO - Epoch 52/100 - Train Loss: 0.1972 - Val Acc: 0.9275
2026-04-05 05:46:07,766 - INFO - Epoch 53/100 - Train Loss: 0.1761 - Val Acc: 0.9275
2026-04-05 05:46:08,093 - INFO - Epoch 54/100 - Train Loss: 0.1805 - Val Acc: 0.9275
2026-04-05 05:46:08,407 - INFO - Epoch 55/100 - Train Loss: 0.1911 - Val Acc: 0.9275
2026-04-05 05:46:08,728 - INFO - Epoch 56/100 - Train Loss: 0.1794 - Val Acc: 0.9275
2026-04-05 05:46:09,053 - INFO - Epoch 57/100 - Train Loss: 0.1801 - Val Acc: 0.9275
2026-04-05 05:46:09,371 - INFO - Epoch 58/100 - Train Loss: 0.1737 - Val Acc: 0.9275
2026-04-05 05:46:09,692 - INFO - Epoch 59/100 - Train Loss: 0.1685 - Val Acc: 0.9275
2026-04-05 05:46:10,022 - INFO - Epoch 60/100 - Train Loss: 0.1631 - Val Acc: 0.9275
2026-04-05 05:46:10,340 - INFO - Epoch 61/100 - Train Loss: 0.1593 - Val Acc: 0.9275
2026-04-05 05:46:10,656 - INFO - Epoch 62/100 - Train Loss: 0.1622 - Val Acc: 0.9275
2026-04-05 05:46:10,973 - INFO - Epoch 63/100 - Train Loss: 0.1715 - Val Acc: 0.9275
2026-04-05 05:46:11,290 - INFO - Epoch 64/100 - Train Loss: 0.1742 - Val Acc: 0.9275
2026-04-05 05:46:11,606 - INFO - Epoch 65/100 - Train Loss: 0.1740 - Val Acc: 0.9275
2026-04-05 05:46:11,924 - INFO - Epoch 66/100 - Train Loss: 0.1697 - Val Acc: 0.9275
2026-04-05 05:46:12,238 - INFO - Epoch 67/100 - Train Loss: 0.1660 - Val Acc: 0.9275
2026-04-05 05:46:12,565 - INFO - Epoch 68/100 - Train Loss: 0.1608 - Val Acc: 0.9275
2026-04-05 05:46:12,882 - INFO - Epoch 69/100 - Train Loss: 0.1566 - Val Acc: 0.9275
2026-04-05 05:46:13,212 - INFO - Epoch 70/100 - Train Loss: 0.1442 - Val Acc: 0.9275
2026-04-05 05:46:13,522 - INFO - Epoch 71/100 - Train Loss: 0.1564 - Val Acc: 0.9275
2026-04-05 05:46:13,855 - INFO - Epoch 72/100 - Train Loss: 0.1532 - Val Acc: 0.9275
2026-04-05 05:46:14,187 - INFO - Epoch 73/100 - Train Loss: 0.1476 - Val Acc: 0.9275
2026-04-05 05:46:14,513 - INFO - Epoch 74/100 - Train Loss: 0.1463 - Val Acc: 0.9275
2026-04-05 05:46:14,846 - INFO - Epoch 75/100 - Train Loss: 0.1520 - Val Acc: 0.9275
2026-04-05 05:46:15,167 - INFO - Epoch 76/100 - Train Loss: 0.1423 - Val Acc: 0.9275
2026-04-05 05:46:15,516 - INFO - Epoch 77/100 - Train Loss: 0.1666 - Val Acc: 0.9275
2026-04-05 05:46:15,851 - INFO - Epoch 78/100 - Train Loss: 0.1594 - Val Acc: 0.9275
2026-04-05 05:46:16,171 - INFO - Epoch 79/100 - Train Loss: 0.1525 - Val Acc: 0.9275
2026-04-05 05:46:16,489 - INFO - Epoch 80/100 - Train Loss: 0.1670 - Val Acc: 0.9275
2026-04-05 05:46:16,805 - INFO - Epoch 81/100 - Train Loss: 0.1497 - Val Acc: 0.9275
2026-04-05 05:46:17,132 - INFO - Epoch 82/100 - Train Loss: 0.1376 - Val Acc: 0.9275
2026-04-05 05:46:17,447 - INFO - Epoch 83/100 - Train Loss: 0.1503 - Val Acc: 0.9275
2026-04-05 05:46:17,792 - INFO - Epoch 84/100 - Train Loss: 0.1372 - Val Acc: 0.9275
2026-04-05 05:46:18,113 - INFO - Epoch 85/100 - Train Loss: 0.1409 - Val Acc: 0.9275
2026-04-05 05:46:18,422 - INFO - Epoch 86/100 - Train Loss: 0.1384 - Val Acc: 0.9275
2026-04-05 05:46:18,741 - INFO - Epoch 87/100 - Train Loss: 0.1394 - Val Acc: 0.9275
2026-04-05 05:46:19,065 - INFO - Epoch 88/100 - Train Loss: 0.1274 - Val Acc: 0.9275
2026-04-05 05:46:19,378 - INFO - Epoch 89/100 - Train Loss: 0.1315 - Val Acc: 0.9275
2026-04-05 05:46:19,693 - INFO - Epoch 90/100 - Train Loss: 0.1379 - Val Acc: 0.9275
2026-04-05 05:46:20,013 - INFO - Epoch 91/100 - Train Loss: 0.1286 - Val Acc: 0.9275
2026-04-05 05:46:20,324 - INFO - Epoch 92/100 - Train Loss: 0.1287 - Val Acc: 0.9275
2026-04-05 05:46:20,643 - INFO - Epoch 93/100 - Train Loss: 0.1462 - Val Acc: 0.9275
2026-04-05 05:46:20,966 - INFO - Epoch 94/100 - Train Loss: 0.1569 - Val Acc: 0.9275
2026-04-05 05:46:21,281 - INFO - Epoch 95/100 - Train Loss: 0.1306 - Val Acc: 0.9275
2026-04-05 05:46:21,601 - INFO - Epoch 96/100 - Train Loss: 0.1495 - Val Acc: 0.9275
2026-04-05 05:46:21,928 - INFO - Epoch 97/100 - Train Loss: 0.1187 - Val Acc: 0.9130
2026-04-05 05:46:22,243 - INFO - Epoch 98/100 - Train Loss: 0.1139 - Val Acc: 0.9275
2026-04-05 05:46:22,553 - INFO - Epoch 99/100 - Train Loss: 0.1087 - Val Acc: 0.9275
2026-04-05 05:46:22,870 - INFO - Epoch 100/100 - Train Loss: 0.1332 - Val Acc: 0.9275
2026-04-05 05:46:23,222 - INFO - Fold 3 logically complete. Tensor memory bounds cleared cleanly.
2026-04-05 05:46:23,227 - INFO - Original class distribution: [345 276]
2026-04-05 05:46:23,227 - INFO - Training device bound securely to: cuda

Fold 4:   0%|          | 0/100 [00:00<?, ?it/s]

2026-04-05 05:46:23,584 - INFO - Epoch 1/100 - Train Loss: 0.5841 - Val Acc: 0.7681
2026-04-05 05:46:23,916 - INFO - Epoch 2/100 - Train Loss: 0.3992 - Val Acc: 0.7826
2026-04-05 05:46:24,245 - INFO - Epoch 3/100 - Train Loss: 0.3349 - Val Acc: 0.7971
2026-04-05 05:46:24,587 - INFO - Epoch 4/100 - Train Loss: 0.3114 - Val Acc: 0.7971
2026-04-05 05:46:24,904 - INFO - Epoch 5/100 - Train Loss: 0.3044 - Val Acc: 0.7826
2026-04-05 05:46:25,218 - INFO - Epoch 6/100 - Train Loss: 0.2903 - Val Acc: 0.7971
2026-04-05 05:46:25,530 - INFO - Epoch 7/100 - Train Loss: 0.2758 - Val Acc: 0.7971
2026-04-05 05:46:25,847 - INFO - Epoch 8/100 - Train Loss: 0.2816 - Val Acc: 0.7971
2026-04-05 05:46:26,173 - INFO - Epoch 9/100 - Train Loss: 0.2761 - Val Acc: 0.8116
2026-04-05 05:46:26,483 - INFO - Epoch 10/100 - Train Loss: 0.2656 - Val Acc: 0.7971
2026-04-05 05:46:26,808 - INFO - Epoch 11/100 - Train Loss: 0.2766 - Val Acc: 0.8116
2026-04-05 05:46:27,127 - INFO - Epoch 12/100 - Train Loss: 0.2668 - Val Acc: 0.7971
2026-04-05 05:46:27,454 - INFO - Epoch 13/100 - Train Loss: 0.2637 - Val Acc: 0.7971
2026-04-05 05:46:27,783 - INFO - Epoch 14/100 - Train Loss: 0.2563 - Val Acc: 0.8261
2026-04-05 05:46:28,106 - INFO - Epoch 15/100 - Train Loss: 0.2539 - Val Acc: 0.8116
2026-04-05 05:46:28,425 - INFO - Epoch 16/100 - Train Loss: 0.2402 - Val Acc: 0.8406
2026-04-05 05:46:28,751 - INFO - Epoch 17/100 - Train Loss: 0.2484 - Val Acc: 0.8406
2026-04-05 05:46:29,086 - INFO - Epoch 18/100 - Train Loss: 0.2430 - Val Acc: 0.8261
2026-04-05 05:46:29,400 - INFO - Epoch 19/100 - Train Loss: 0.2334 - Val Acc: 0.8261
2026-04-05 05:46:29,722 - INFO - Epoch 20/100 - Train Loss: 0.2412 - Val Acc: 0.8696
2026-04-05 05:46:30,043 - INFO - Epoch 21/100 - Train Loss: 0.2276 - Val Acc: 0.8261
2026-04-05 05:46:30,367 - INFO - Epoch 22/100 - Train Loss: 0.2253 - Val Acc: 0.8406
2026-04-05 05:46:30,700 - INFO - Epoch 23/100 - Train Loss: 0.2251 - Val Acc: 0.8406
2026-04-05 05:46:31,030 - INFO - Epoch 24/100 - Train Loss: 0.2250 - Val Acc: 0.8261
2026-04-05 05:46:31,372 - INFO - Epoch 25/100 - Train Loss: 0.2144 - Val Acc: 0.8406
2026-04-05 05:46:31,691 - INFO - Epoch 26/100 - Train Loss: 0.2195 - Val Acc: 0.8406
2026-04-05 05:46:32,015 - INFO - Epoch 27/100 - Train Loss: 0.2095 - Val Acc: 0.8261
2026-04-05 05:46:32,330 - INFO - Epoch 28/100 - Train Loss: 0.2065 - Val Acc: 0.8406
2026-04-05 05:46:32,649 - INFO - Epoch 29/100 - Train Loss: 0.2046 - Val Acc: 0.8551
2026-04-05 05:46:32,978 - INFO - Epoch 30/100 - Train Loss: 0.1967 - Val Acc: 0.8406
2026-04-05 05:46:33,297 - INFO - Epoch 31/100 - Train Loss: 0.2010 - Val Acc: 0.8116
2026-04-05 05:46:33,626 - INFO - Epoch 32/100 - Train Loss: 0.1913 - Val Acc: 0.8406
2026-04-05 05:46:33,957 - INFO - Epoch 33/100 - Train Loss: 0.2087 - Val Acc: 0.8116
2026-04-05 05:46:34,286 - INFO - Epoch 34/100 - Train Loss: 0.1979 - Val Acc: 0.8406
2026-04-05 05:46:34,638 - INFO - Epoch 35/100 - Train Loss: 0.1893 - Val Acc: 0.8261
2026-04-05 05:46:34,989 - INFO - Epoch 36/100 - Train Loss: 0.2000 - Val Acc: 0.8116
2026-04-05 05:46:35,322 - INFO - Epoch 37/100 - Train Loss: 0.1835 - Val Acc: 0.8261
2026-04-05 05:46:35,640 - INFO - Epoch 38/100 - Train Loss: 0.2024 - Val Acc: 0.8261
2026-04-05 05:46:35,966 - INFO - Epoch 39/100 - Train Loss: 0.1784 - Val Acc: 0.8261
2026-04-05 05:46:36,276 - INFO - Epoch 40/100 - Train Loss: 0.1860 - Val Acc: 0.8116
2026-04-05 05:46:36,595 - INFO - Epoch 41/100 - Train Loss: 0.1796 - Val Acc: 0.8261
2026-04-05 05:46:36,910 - INFO - Epoch 42/100 - Train Loss: 0.1866 - Val Acc: 0.7971
2026-04-05 05:46:37,228 - INFO - Epoch 43/100 - Train Loss: 0.1621 - Val Acc: 0.8116
2026-04-05 05:46:37,539 - INFO - Epoch 44/100 - Train Loss: 0.1845 - Val Acc: 0.8261
2026-04-05 05:46:37,858 - INFO - Epoch 45/100 - Train Loss: 0.1632 - Val Acc: 0.8261
2026-04-05 05:46:38,172 - INFO - Epoch 46/100 - Train Loss: 0.1776 - Val Acc: 0.8261
2026-04-05 05:46:38,484 - INFO - Epoch 47/100 - Train Loss: 0.1826 - Val Acc: 0.8116
2026-04-05 05:46:38,802 - INFO - Epoch 48/100 - Train Loss: 0.1679 - Val Acc: 0.8116
2026-04-05 05:46:39,124 - INFO - Epoch 49/100 - Train Loss: 0.1642 - Val Acc: 0.7971
2026-04-05 05:46:39,454 - INFO - Epoch 50/100 - Train Loss: 0.1652 - Val Acc: 0.7971
2026-04-05 05:46:39,780 - INFO - Epoch 51/100 - Train Loss: 0.1566 - Val Acc: 0.7971
2026-04-05 05:46:40,095 - INFO - Epoch 52/100 - Train Loss: 0.1778 - Val Acc: 0.7971
2026-04-05 05:46:40,418 - INFO - Epoch 53/100 - Train Loss: 0.1748 - Val Acc: 0.7971
2026-04-05 05:46:40,735 - INFO - Epoch 54/100 - Train Loss: 0.1623 - Val Acc: 0.7971
2026-04-05 05:46:41,065 - INFO - Epoch 55/100 - Train Loss: 0.1510 - Val Acc: 0.7971
2026-04-05 05:46:41,379 - INFO - Epoch 56/100 - Train Loss: 0.1659 - Val Acc: 0.7971
2026-04-05 05:46:41,702 - INFO - Epoch 57/100 - Train Loss: 0.1527 - Val Acc: 0.7971
2026-04-05 05:46:42,032 - INFO - Epoch 58/100 - Train Loss: 0.1415 - Val Acc: 0.8116
2026-04-05 05:46:42,354 - INFO - Epoch 59/100 - Train Loss: 0.1388 - Val Acc: 0.7971
2026-04-05 05:46:42,679 - INFO - Epoch 60/100 - Train Loss: 0.1467 - Val Acc: 0.8116
2026-04-05 05:46:43,010 - INFO - Epoch 61/100 - Train Loss: 0.1570 - Val Acc: 0.7971
2026-04-05 05:46:43,332 - INFO - Epoch 62/100 - Train Loss: 0.1454 - Val Acc: 0.8116
2026-04-05 05:46:43,656 - INFO - Epoch 63/100 - Train Loss: 0.1580 - Val Acc: 0.7971
2026-04-05 05:46:43,986 - INFO - Epoch 64/100 - Train Loss: 0.1659 - Val Acc: 0.8116
2026-04-05 05:46:44,313 - INFO - Epoch 65/100 - Train Loss: 0.1510 - Val Acc: 0.8116
2026-04-05 05:46:44,674 - INFO - Epoch 66/100 - Train Loss: 0.1458 - Val Acc: 0.7971
2026-04-05 05:46:45,013 - INFO - Epoch 67/100 - Train Loss: 0.1640 - Val Acc: 0.7971
2026-04-05 05:46:45,338 - INFO - Epoch 68/100 - Train Loss: 0.1559 - Val Acc: 0.7971
2026-04-05 05:46:45,663 - INFO - Epoch 69/100 - Train Loss: 0.1606 - Val Acc: 0.8116
2026-04-05 05:46:45,985 - INFO - Epoch 70/100 - Train Loss: 0.1256 - Val Acc: 0.8116
2026-04-05 05:46:46,303 - INFO - Epoch 71/100 - Train Loss: 0.1500 - Val Acc: 0.8261
2026-04-05 05:46:46,620 - INFO - Epoch 72/100 - Train Loss: 0.1356 - Val Acc: 0.7826
2026-04-05 05:46:46,951 - INFO - Epoch 73/100 - Train Loss: 0.1331 - Val Acc: 0.7971
2026-04-05 05:46:47,276 - INFO - Epoch 74/100 - Train Loss: 0.1332 - Val Acc: 0.7971
2026-04-05 05:46:47,604 - INFO - Epoch 75/100 - Train Loss: 0.1290 - Val Acc: 0.7971
2026-04-05 05:46:47,931 - INFO - Epoch 76/100 - Train Loss: 0.1353 - Val Acc: 0.7971
2026-04-05 05:46:48,251 - INFO - Epoch 77/100 - Train Loss: 0.1421 - Val Acc: 0.8116
2026-04-05 05:46:48,602 - INFO - Epoch 78/100 - Train Loss: 0.1272 - Val Acc: 0.8116
2026-04-05 05:46:48,930 - INFO - Epoch 79/100 - Train Loss: 0.1284 - Val Acc: 0.7971
2026-04-05 05:46:49,256 - INFO - Epoch 80/100 - Train Loss: 0.1283 - Val Acc: 0.8116
2026-04-05 05:46:49,574 - INFO - Epoch 81/100 - Train Loss: 0.1628 - Val Acc: 0.7971
2026-04-05 05:46:49,890 - INFO - Epoch 82/100 - Train Loss: 0.1293 - Val Acc: 0.7971
2026-04-05 05:46:50,221 - INFO - Epoch 83/100 - Train Loss: 0.1186 - Val Acc: 0.8116
2026-04-05 05:46:50,558 - INFO - Epoch 84/100 - Train Loss: 0.1249 - Val Acc: 0.8116
2026-04-05 05:46:50,891 - INFO - Epoch 85/100 - Train Loss: 0.1215 - Val Acc: 0.7971
2026-04-05 05:46:51,220 - INFO - Epoch 86/100 - Train Loss: 0.1222 - Val Acc: 0.8116
2026-04-05 05:46:51,539 - INFO - Epoch 87/100 - Train Loss: 0.1119 - Val Acc: 0.7971
2026-04-05 05:46:51,857 - INFO - Epoch 88/100 - Train Loss: 0.1230 - Val Acc: 0.7971
2026-04-05 05:46:52,185 - INFO - Epoch 89/100 - Train Loss: 0.1273 - Val Acc: 0.7826
2026-04-05 05:46:52,504 - INFO - Epoch 90/100 - Train Loss: 0.1175 - Val Acc: 0.7971
2026-04-05 05:46:52,823 - INFO - Epoch 91/100 - Train Loss: 0.1199 - Val Acc: 0.8116
2026-04-05 05:46:53,137 - INFO - Epoch 92/100 - Train Loss: 0.1210 - Val Acc: 0.8116
2026-04-05 05:46:53,463 - INFO - Epoch 93/100 - Train Loss: 0.1204 - Val Acc: 0.7971
2026-04-05 05:46:53,787 - INFO - Epoch 94/100 - Train Loss: 0.1176 - Val Acc: 0.7971
2026-04-05 05:46:54,104 - INFO - Epoch 95/100 - Train Loss: 0.1071 - Val Acc: 0.7971
2026-04-05 05:46:54,438 - INFO - Epoch 96/100 - Train Loss: 0.1162 - Val Acc: 0.8116
2026-04-05 05:46:54,789 - INFO - Epoch 97/100 - Train Loss: 0.1075 - Val Acc: 0.8116
2026-04-05 05:46:55,109 - INFO - Epoch 98/100 - Train Loss: 0.1128 - Val Acc: 0.8116
2026-04-05 05:46:55,430 - INFO - Epoch 99/100 - Train Loss: 0.1109 - Val Acc: 0.7971
2026-04-05 05:46:55,743 - INFO - Epoch 100/100 - Train Loss: 0.1071 - Val Acc: 0.8116
2026-04-05 05:46:56,116 - INFO - Fold 4 logically complete. Tensor memory bounds cleared cleanly.
2026-04-05 05:46:56,120 - INFO - Original class distribution: [345 276]
2026-04-05 05:46:56,121 - INFO - Training device bound securely to: cuda

Fold 5:   0%|          | 0/100 [00:00<?, ?it/s]

2026-04-05 05:46:56,476 - INFO - Epoch 1/100 - Train Loss: 0.6016 - Val Acc: 0.8696
2026-04-05 05:46:56,788 - INFO - Epoch 2/100 - Train Loss: 0.4224 - Val Acc: 0.8841
2026-04-05 05:46:57,105 - INFO - Epoch 3/100 - Train Loss: 0.3497 - Val Acc: 0.8986
2026-04-05 05:46:57,424 - INFO - Epoch 4/100 - Train Loss: 0.3278 - Val Acc: 0.8841
2026-04-05 05:46:57,759 - INFO - Epoch 5/100 - Train Loss: 0.3196 - Val Acc: 0.8551
2026-04-05 05:46:58,081 - INFO - Epoch 6/100 - Train Loss: 0.3096 - Val Acc: 0.8551
2026-04-05 05:46:58,393 - INFO - Epoch 7/100 - Train Loss: 0.2930 - Val Acc: 0.8551
2026-04-05 05:46:58,703 - INFO - Epoch 8/100 - Train Loss: 0.2961 - Val Acc: 0.8551
2026-04-05 05:46:59,018 - INFO - Epoch 9/100 - Train Loss: 0.2818 - Val Acc: 0.8406
2026-04-05 05:46:59,339 - INFO - Epoch 10/100 - Train Loss: 0.2979 - Val Acc: 0.8406
2026-04-05 05:46:59,650 - INFO - Epoch 11/100 - Train Loss: 0.2637 - Val Acc: 0.8551
2026-04-05 05:46:59,968 - INFO - Epoch 12/100 - Train Loss: 0.2690 - Val Acc: 0.8551
2026-04-05 05:47:00,286 - INFO - Epoch 13/100 - Train Loss: 0.2509 - Val Acc: 0.8261
2026-04-05 05:47:00,602 - INFO - Epoch 14/100 - Train Loss: 0.2574 - Val Acc: 0.8551
2026-04-05 05:47:00,918 - INFO - Epoch 15/100 - Train Loss: 0.2537 - Val Acc: 0.8406
2026-04-05 05:47:01,249 - INFO - Epoch 16/100 - Train Loss: 0.2460 - Val Acc: 0.8406
2026-04-05 05:47:01,575 - INFO - Epoch 17/100 - Train Loss: 0.2533 - Val Acc: 0.8406
2026-04-05 05:47:01,903 - INFO - Epoch 18/100 - Train Loss: 0.2552 - Val Acc: 0.8406
2026-04-05 05:47:02,220 - INFO - Epoch 19/100 - Train Loss: 0.2358 - Val Acc: 0.8551
2026-04-05 05:47:02,537 - INFO - Epoch 20/100 - Train Loss: 0.2395 - Val Acc: 0.8551
2026-04-05 05:47:02,857 - INFO - Epoch 21/100 - Train Loss: 0.2286 - Val Acc: 0.8406
2026-04-05 05:47:03,184 - INFO - Epoch 22/100 - Train Loss: 0.2363 - Val Acc: 0.8406
2026-04-05 05:47:03,510 - INFO - Epoch 23/100 - Train Loss: 0.2280 - Val Acc: 0.8406
2026-04-05 05:47:03,838 - INFO - Epoch 24/100 - Train Loss: 0.2353 - Val Acc: 0.8551
2026-04-05 05:47:04,155 - INFO - Epoch 25/100 - Train Loss: 0.2297 - Val Acc: 0.8406
2026-04-05 05:47:04,492 - INFO - Epoch 26/100 - Train Loss: 0.2211 - Val Acc: 0.8406
2026-04-05 05:47:04,847 - INFO - Epoch 27/100 - Train Loss: 0.2236 - Val Acc: 0.8551
2026-04-05 05:47:05,202 - INFO - Epoch 28/100 - Train Loss: 0.2185 - Val Acc: 0.8551
2026-04-05 05:47:05,551 - INFO - Epoch 29/100 - Train Loss: 0.2058 - Val Acc: 0.8696
2026-04-05 05:47:05,874 - INFO - Epoch 30/100 - Train Loss: 0.2112 - Val Acc: 0.8551
2026-04-05 05:47:06,205 - INFO - Epoch 31/100 - Train Loss: 0.1937 - Val Acc: 0.8406
2026-04-05 05:47:06,526 - INFO - Epoch 32/100 - Train Loss: 0.2127 - Val Acc: 0.8551
2026-04-05 05:47:06,858 - INFO - Epoch 33/100 - Train Loss: 0.1991 - Val Acc: 0.8406
2026-04-05 05:47:07,201 - INFO - Epoch 34/100 - Train Loss: 0.2087 - Val Acc: 0.8406
2026-04-05 05:47:07,526 - INFO - Epoch 35/100 - Train Loss: 0.1970 - Val Acc: 0.8406
2026-04-05 05:47:07,850 - INFO - Epoch 36/100 - Train Loss: 0.2030 - Val Acc: 0.8406
2026-04-05 05:47:08,181 - INFO - Epoch 37/100 - Train Loss: 0.1982 - Val Acc: 0.8406
2026-04-05 05:47:08,496 - INFO - Epoch 38/100 - Train Loss: 0.2050 - Val Acc: 0.8406
2026-04-05 05:47:08,822 - INFO - Epoch 39/100 - Train Loss: 0.1924 - Val Acc: 0.8406
2026-04-05 05:47:09,141 - INFO - Epoch 40/100 - Train Loss: 0.1789 - Val Acc: 0.8406
2026-04-05 05:47:09,462 - INFO - Epoch 41/100 - Train Loss: 0.1801 - Val Acc: 0.8551
2026-04-05 05:47:09,784 - INFO - Epoch 42/100 - Train Loss: 0.1952 - Val Acc: 0.8551
2026-04-05 05:47:10,106 - INFO - Epoch 43/100 - Train Loss: 0.1859 - Val Acc: 0.8406
2026-04-05 05:47:10,435 - INFO - Epoch 44/100 - Train Loss: 0.2031 - Val Acc: 0.8551
2026-04-05 05:47:10,764 - INFO - Epoch 45/100 - Train Loss: 0.1824 - Val Acc: 0.8551
2026-04-05 05:47:11,087 - INFO - Epoch 46/100 - Train Loss: 0.1980 - Val Acc: 0.8551
2026-04-05 05:47:11,419 - INFO - Epoch 47/100 - Train Loss: 0.1636 - Val Acc: 0.8551
2026-04-05 05:47:11,751 - INFO - Epoch 48/100 - Train Loss: 0.1728 - Val Acc: 0.8551
2026-04-05 05:47:12,064 - INFO - Epoch 49/100 - Train Loss: 0.1686 - Val Acc: 0.8696
2026-04-05 05:47:12,398 - INFO - Epoch 50/100 - Train Loss: 0.1700 - Val Acc: 0.8551
2026-04-05 05:47:12,727 - INFO - Epoch 51/100 - Train Loss: 0.1705 - Val Acc: 0.8406
2026-04-05 05:47:13,058 - INFO - Epoch 52/100 - Train Loss: 0.1595 - Val Acc: 0.8551
2026-04-05 05:47:13,380 - INFO - Epoch 53/100 - Train Loss: 0.1683 - Val Acc: 0.8406
2026-04-05 05:47:13,697 - INFO - Epoch 54/100 - Train Loss: 0.1634 - Val Acc: 0.8406
2026-04-05 05:47:14,020 - INFO - Epoch 55/100 - Train Loss: 0.1846 - Val Acc: 0.8551
2026-04-05 05:47:14,347 - INFO - Epoch 56/100 - Train Loss: 0.1777 - Val Acc: 0.8551
2026-04-05 05:47:14,698 - INFO - Epoch 57/100 - Train Loss: 0.1647 - Val Acc: 0.8406
2026-04-05 05:47:15,037 - INFO - Epoch 58/100 - Train Loss: 0.1645 - Val Acc: 0.8551
2026-04-05 05:47:15,352 - INFO - Epoch 59/100 - Train Loss: 0.1573 - Val Acc: 0.8406
2026-04-05 05:47:15,696 - INFO - Epoch 60/100 - Train Loss: 0.1523 - Val Acc: 0.8406
2026-04-05 05:47:16,026 - INFO - Epoch 61/100 - Train Loss: 0.1611 - Val Acc: 0.8406
2026-04-05 05:47:16,345 - INFO - Epoch 62/100 - Train Loss: 0.1668 - Val Acc: 0.8406
2026-04-05 05:47:16,660 - INFO - Epoch 63/100 - Train Loss: 0.1561 - Val Acc: 0.8696
2026-04-05 05:47:16,974 - INFO - Epoch 64/100 - Train Loss: 0.1489 - Val Acc: 0.8406
2026-04-05 05:47:17,288 - INFO - Epoch 65/100 - Train Loss: 0.1426 - Val Acc: 0.8696
2026-04-05 05:47:17,612 - INFO - Epoch 66/100 - Train Loss: 0.1555 - Val Acc: 0.8406
2026-04-05 05:47:17,936 - INFO - Epoch 67/100 - Train Loss: 0.1626 - Val Acc: 0.8551
2026-04-05 05:47:18,251 - INFO - Epoch 68/100 - Train Loss: 0.1358 - Val Acc: 0.8406
2026-04-05 05:47:18,598 - INFO - Epoch 69/100 - Train Loss: 0.1519 - Val Acc: 0.8551
2026-04-05 05:47:18,958 - INFO - Epoch 70/100 - Train Loss: 0.1698 - Val Acc: 0.8406
2026-04-05 05:47:19,275 - INFO - Epoch 71/100 - Train Loss: 0.1456 - Val Acc: 0.8406
2026-04-05 05:47:19,596 - INFO - Epoch 72/100 - Train Loss: 0.1573 - Val Acc: 0.8406
2026-04-05 05:47:19,907 - INFO - Epoch 73/100 - Train Loss: 0.1300 - Val Acc: 0.8261
2026-04-05 05:47:20,216 - INFO - Epoch 74/100 - Train Loss: 0.1387 - Val Acc: 0.8261
2026-04-05 05:47:20,528 - INFO - Epoch 75/100 - Train Loss: 0.1365 - Val Acc: 0.8406
2026-04-05 05:47:20,831 - INFO - Epoch 76/100 - Train Loss: 0.1301 - Val Acc: 0.8551
2026-04-05 05:47:21,154 - INFO - Epoch 77/100 - Train Loss: 0.1331 - Val Acc: 0.8261
2026-04-05 05:47:21,497 - INFO - Epoch 78/100 - Train Loss: 0.1422 - Val Acc: 0.8406
2026-04-05 05:47:21,843 - INFO - Epoch 79/100 - Train Loss: 0.1421 - Val Acc: 0.8696
2026-04-05 05:47:22,167 - INFO - Epoch 80/100 - Train Loss: 0.1567 - Val Acc: 0.8406
2026-04-05 05:47:22,479 - INFO - Epoch 81/100 - Train Loss: 0.1299 - Val Acc: 0.8406
2026-04-05 05:47:22,807 - INFO - Epoch 82/100 - Train Loss: 0.1387 - Val Acc: 0.8406
2026-04-05 05:47:23,124 - INFO - Epoch 83/100 - Train Loss: 0.1370 - Val Acc: 0.8551
2026-04-05 05:47:23,444 - INFO - Epoch 84/100 - Train Loss: 0.1424 - Val Acc: 0.8406
2026-04-05 05:47:23,765 - INFO - Epoch 85/100 - Train Loss: 0.1410 - Val Acc: 0.8406
2026-04-05 05:47:24,080 - INFO - Epoch 86/100 - Train Loss: 0.1430 - Val Acc: 0.8406
2026-04-05 05:47:24,403 - INFO - Epoch 87/100 - Train Loss: 0.1334 - Val Acc: 0.8406
2026-04-05 05:47:24,752 - INFO - Epoch 88/100 - Train Loss: 0.1212 - Val Acc: 0.8406
2026-04-05 05:47:25,067 - INFO - Epoch 89/100 - Train Loss: 0.1180 - Val Acc: 0.8551
2026-04-05 05:47:25,388 - INFO - Epoch 90/100 - Train Loss: 0.1151 - Val Acc: 0.8551
2026-04-05 05:47:25,714 - INFO - Epoch 91/100 - Train Loss: 0.1084 - Val Acc: 0.8406
2026-04-05 05:47:26,035 - INFO - Epoch 92/100 - Train Loss: 0.1211 - Val Acc: 0.8261
2026-04-05 05:47:26,352 - INFO - Epoch 93/100 - Train Loss: 0.1316 - Val Acc: 0.8261
2026-04-05 05:47:26,673 - INFO - Epoch 94/100 - Train Loss: 0.1313 - Val Acc: 0.8261
2026-04-05 05:47:26,990 - INFO - Epoch 95/100 - Train Loss: 0.1077 - Val Acc: 0.8551
2026-04-05 05:47:27,319 - INFO - Epoch 96/100 - Train Loss: 0.1243 - Val Acc: 0.8406
2026-04-05 05:47:27,628 - INFO - Epoch 97/100 - Train Loss: 0.1184 - Val Acc: 0.8261
2026-04-05 05:47:27,950 - INFO - Epoch 98/100 - Train Loss: 0.1183 - Val Acc: 0.8406
2026-04-05 05:47:28,288 - INFO - Epoch 99/100 - Train Loss: 0.1165 - Val Acc: 0.8261
2026-04-05 05:47:28,608 - INFO - Epoch 100/100 - Train Loss: 0.1166 - Val Acc: 0.8406
2026-04-05 05:47:28,972 - INFO - Fold 5 logically complete. Tensor memory bounds cleared cleanly.
2026-04-05 05:47:28,977 - INFO - Original class distribution: [345 276]
2026-04-05 05:47:28,977 - INFO - Training device bound securely to: cuda

Fold 6:   0%|          | 0/100 [00:00<?, ?it/s]

2026-04-05 05:47:29,332 - INFO - Epoch 1/100 - Train Loss: 0.5962 - Val Acc: 0.8841
2026-04-05 05:47:29,651 - INFO - Epoch 2/100 - Train Loss: 0.4359 - Val Acc: 0.8986
2026-04-05 05:47:29,975 - INFO - Epoch 3/100 - Train Loss: 0.3627 - Val Acc: 0.8841
2026-04-05 05:47:30,309 - INFO - Epoch 4/100 - Train Loss: 0.3390 - Val Acc: 0.8841
2026-04-05 05:47:30,646 - INFO - Epoch 5/100 - Train Loss: 0.3155 - Val Acc: 0.8841
2026-04-05 05:47:30,961 - INFO - Epoch 6/100 - Train Loss: 0.3297 - Val Acc: 0.8696
2026-04-05 05:47:31,295 - INFO - Epoch 7/100 - Train Loss: 0.3151 - Val Acc: 0.8841
2026-04-05 05:47:31,635 - INFO - Epoch 8/100 - Train Loss: 0.3049 - Val Acc: 0.8696
2026-04-05 05:47:31,958 - INFO - Epoch 9/100 - Train Loss: 0.2905 - Val Acc: 0.8696
2026-04-05 05:47:32,281 - INFO - Epoch 10/100 - Train Loss: 0.2787 - Val Acc: 0.8696
2026-04-05 05:47:32,604 - INFO - Epoch 11/100 - Train Loss: 0.2858 - Val Acc: 0.8551
2026-04-05 05:47:32,926 - INFO - Epoch 12/100 - Train Loss: 0.2772 - Val Acc: 0.8551
2026-04-05 05:47:33,255 - INFO - Epoch 13/100 - Train Loss: 0.2784 - Val Acc: 0.8551
2026-04-05 05:47:33,580 - INFO - Epoch 14/100 - Train Loss: 0.2774 - Val Acc: 0.8696
2026-04-05 05:47:33,907 - INFO - Epoch 15/100 - Train Loss: 0.2644 - Val Acc: 0.8406
2026-04-05 05:47:34,243 - INFO - Epoch 16/100 - Train Loss: 0.2810 - Val Acc: 0.8406
2026-04-05 05:47:34,594 - INFO - Epoch 17/100 - Train Loss: 0.2614 - Val Acc: 0.8696
2026-04-05 05:47:34,925 - INFO - Epoch 18/100 - Train Loss: 0.2579 - Val Acc: 0.8551
2026-04-05 05:47:35,242 - INFO - Epoch 19/100 - Train Loss: 0.2499 - Val Acc: 0.8551
2026-04-05 05:47:35,564 - INFO - Epoch 20/100 - Train Loss: 0.2480 - Val Acc: 0.8406
2026-04-05 05:47:35,894 - INFO - Epoch 21/100 - Train Loss: 0.2437 - Val Acc: 0.8551
2026-04-05 05:47:36,220 - INFO - Epoch 22/100 - Train Loss: 0.2439 - Val Acc: 0.8261
2026-04-05 05:47:36,536 - INFO - Epoch 23/100 - Train Loss: 0.2388 - Val Acc: 0.8406
2026-04-05 05:47:36,849 - INFO - Epoch 24/100 - Train Loss: 0.2443 - Val Acc: 0.8406
2026-04-05 05:47:37,166 - INFO - Epoch 25/100 - Train Loss: 0.2316 - Val Acc: 0.8406
2026-04-05 05:47:37,484 - INFO - Epoch 26/100 - Train Loss: 0.2366 - Val Acc: 0.8406
2026-04-05 05:47:37,802 - INFO - Epoch 27/100 - Train Loss: 0.2362 - Val Acc: 0.8551
2026-04-05 05:47:38,128 - INFO - Epoch 28/100 - Train Loss: 0.2271 - Val Acc: 0.8406
2026-04-05 05:47:38,452 - INFO - Epoch 29/100 - Train Loss: 0.2418 - Val Acc: 0.8406
2026-04-05 05:47:38,773 - INFO - Epoch 30/100 - Train Loss: 0.2272 - Val Acc: 0.8406
2026-04-05 05:47:39,095 - INFO - Epoch 31/100 - Train Loss: 0.2294 - Val Acc: 0.8261
2026-04-05 05:47:39,419 - INFO - Epoch 32/100 - Train Loss: 0.2132 - Val Acc: 0.8261
2026-04-05 05:47:39,760 - INFO - Epoch 33/100 - Train Loss: 0.2297 - Val Acc: 0.8551
2026-04-05 05:47:40,079 - INFO - Epoch 34/100 - Train Loss: 0.2198 - Val Acc: 0.8261
2026-04-05 05:47:40,396 - INFO - Epoch 35/100 - Train Loss: 0.2149 - Val Acc: 0.8406
2026-04-05 05:47:40,729 - INFO - Epoch 36/100 - Train Loss: 0.1973 - Val Acc: 0.8406
2026-04-05 05:47:41,057 - INFO - Epoch 37/100 - Train Loss: 0.2142 - Val Acc: 0.8406
2026-04-05 05:47:41,382 - INFO - Epoch 38/100 - Train Loss: 0.2087 - Val Acc: 0.8406
2026-04-05 05:47:41,720 - INFO - Epoch 39/100 - Train Loss: 0.2043 - Val Acc: 0.8696
2026-04-05 05:47:42,048 - INFO - Epoch 40/100 - Train Loss: 0.2139 - Val Acc: 0.8551
2026-04-05 05:47:42,366 - INFO - Epoch 41/100 - Train Loss: 0.2114 - Val Acc: 0.8696
2026-04-05 05:47:42,688 - INFO - Epoch 42/100 - Train Loss: 0.2071 - Val Acc: 0.8406
2026-04-05 05:47:43,018 - INFO - Epoch 43/100 - Train Loss: 0.1883 - Val Acc: 0.8406
2026-04-05 05:47:43,341 - INFO - Epoch 44/100 - Train Loss: 0.2112 - Val Acc: 0.8696
2026-04-05 05:47:43,658 - INFO - Epoch 45/100 - Train Loss: 0.1942 - Val Acc: 0.8406
2026-04-05 05:47:43,981 - INFO - Epoch 46/100 - Train Loss: 0.2041 - Val Acc: 0.8406
2026-04-05 05:47:44,309 - INFO - Epoch 47/100 - Train Loss: 0.1949 - Val Acc: 0.8551
2026-04-05 05:47:44,662 - INFO - Epoch 48/100 - Train Loss: 0.1766 - Val Acc: 0.8406
2026-04-05 05:47:44,987 - INFO - Epoch 49/100 - Train Loss: 0.2085 - Val Acc: 0.8551
2026-04-05 05:47:45,306 - INFO - Epoch 50/100 - Train Loss: 0.1874 - Val Acc: 0.8841
2026-04-05 05:47:45,620 - INFO - Epoch 51/100 - Train Loss: 0.1923 - Val Acc: 0.8551
2026-04-05 05:47:45,947 - INFO - Epoch 52/100 - Train Loss: 0.1829 - Val Acc: 0.8551
2026-04-05 05:47:46,280 - INFO - Epoch 53/100 - Train Loss: 0.1862 - Val Acc: 0.8551
2026-04-05 05:47:46,596 - INFO - Epoch 54/100 - Train Loss: 0.1721 - Val Acc: 0.8696
2026-04-05 05:47:46,919 - INFO - Epoch 55/100 - Train Loss: 0.1978 - Val Acc: 0.8551
2026-04-05 05:47:47,234 - INFO - Epoch 56/100 - Train Loss: 0.1875 - Val Acc: 0.8696
2026-04-05 05:47:47,555 - INFO - Epoch 57/100 - Train Loss: 0.1834 - Val Acc: 0.8551
2026-04-05 05:47:47,884 - INFO - Epoch 58/100 - Train Loss: 0.1732 - Val Acc: 0.8551
2026-04-05 05:47:48,205 - INFO - Epoch 59/100 - Train Loss: 0.1636 - Val Acc: 0.8551
2026-04-05 05:47:48,533 - INFO - Epoch 60/100 - Train Loss: 0.1656 - Val Acc: 0.8696
2026-04-05 05:47:48,857 - INFO - Epoch 61/100 - Train Loss: 0.1736 - Val Acc: 0.8551
2026-04-05 05:47:49,176 - INFO - Epoch 62/100 - Train Loss: 0.1555 - Val Acc: 0.8551
2026-04-05 05:47:49,494 - INFO - Epoch 63/100 - Train Loss: 0.1660 - Val Acc: 0.8551
2026-04-05 05:47:49,820 - INFO - Epoch 64/100 - Train Loss: 0.1586 - Val Acc: 0.8696
2026-04-05 05:47:50,147 - INFO - Epoch 65/100 - Train Loss: 0.1726 - Val Acc: 0.8261
2026-04-05 05:47:50,468 - INFO - Epoch 66/100 - Train Loss: 0.1557 - Val Acc: 0.8696
2026-04-05 05:47:50,798 - INFO - Epoch 67/100 - Train Loss: 0.1501 - Val Acc: 0.8551
2026-04-05 05:47:51,125 - INFO - Epoch 68/100 - Train Loss: 0.1808 - Val Acc: 0.8406
2026-04-05 05:47:51,444 - INFO - Epoch 69/100 - Train Loss: 0.1515 - Val Acc: 0.8551
2026-04-05 05:47:51,772 - INFO - Epoch 70/100 - Train Loss: 0.1605 - Val Acc: 0.8696
2026-04-05 05:47:52,084 - INFO - Epoch 71/100 - Train Loss: 0.1435 - Val Acc: 0.8551
2026-04-05 05:47:52,411 - INFO - Epoch 72/100 - Train Loss: 0.1580 - Val Acc: 0.8696
2026-04-05 05:47:52,732 - INFO - Epoch 73/100 - Train Loss: 0.1534 - Val Acc: 0.8551
2026-04-05 05:47:53,052 - INFO - Epoch 74/100 - Train Loss: 0.1512 - Val Acc: 0.8406
2026-04-05 05:47:53,377 - INFO - Epoch 75/100 - Train Loss: 0.1536 - Val Acc: 0.8696
2026-04-05 05:47:53,706 - INFO - Epoch 76/100 - Train Loss: 0.1501 - Val Acc: 0.8406
2026-04-05 05:47:54,022 - INFO - Epoch 77/100 - Train Loss: 0.1469 - Val Acc: 0.8406
2026-04-05 05:47:54,375 - INFO - Epoch 78/100 - Train Loss: 0.1415 - Val Acc: 0.8406
2026-04-05 05:47:54,736 - INFO - Epoch 79/100 - Train Loss: 0.1334 - Val Acc: 0.8406
2026-04-05 05:47:55,078 - INFO - Epoch 80/100 - Train Loss: 0.1346 - Val Acc: 0.8551
2026-04-05 05:47:55,402 - INFO - Epoch 81/100 - Train Loss: 0.1576 - Val Acc: 0.8406
2026-04-05 05:47:55,720 - INFO - Epoch 82/100 - Train Loss: 0.1501 - Val Acc: 0.8551
2026-04-05 05:47:56,045 - INFO - Epoch 83/100 - Train Loss: 0.1387 - Val Acc: 0.8551
2026-04-05 05:47:56,364 - INFO - Epoch 84/100 - Train Loss: 0.1283 - Val Acc: 0.8551
2026-04-05 05:47:56,677 - INFO - Epoch 85/100 - Train Loss: 0.1372 - Val Acc: 0.8406
2026-04-05 05:47:56,997 - INFO - Epoch 86/100 - Train Loss: 0.1458 - Val Acc: 0.8406
2026-04-05 05:47:57,322 - INFO - Epoch 87/100 - Train Loss: 0.1526 - Val Acc: 0.8406
2026-04-05 05:47:57,649 - INFO - Epoch 88/100 - Train Loss: 0.1361 - Val Acc: 0.8406
2026-04-05 05:47:57,977 - INFO - Epoch 89/100 - Train Loss: 0.1217 - Val Acc: 0.8406
2026-04-05 05:47:58,291 - INFO - Epoch 90/100 - Train Loss: 0.1434 - Val Acc: 0.8406
2026-04-05 05:47:58,613 - INFO - Epoch 91/100 - Train Loss: 0.1368 - Val Acc: 0.8551
2026-04-05 05:47:58,942 - INFO - Epoch 92/100 - Train Loss: 0.1167 - Val Acc: 0.8406
2026-04-05 05:47:59,267 - INFO - Epoch 93/100 - Train Loss: 0.1314 - Val Acc: 0.8696
2026-04-05 05:47:59,592 - INFO - Epoch 94/100 - Train Loss: 0.1339 - Val Acc: 0.8551
2026-04-05 05:47:59,920 - INFO - Epoch 95/100 - Train Loss: 0.1297 - Val Acc: 0.8406
2026-04-05 05:48:00,250 - INFO - Epoch 96/100 - Train Loss: 0.1276 - Val Acc: 0.8406
2026-04-05 05:48:00,567 - INFO - Epoch 97/100 - Train Loss: 0.1215 - Val Acc: 0.8406
2026-04-05 05:48:00,878 - INFO - Epoch 98/100 - Train Loss: 0.1237 - Val Acc: 0.8406
2026-04-05 05:48:01,201 - INFO - Epoch 99/100 - Train Loss: 0.1272 - Val Acc: 0.8406
2026-04-05 05:48:01,509 - INFO - Epoch 100/100 - Train Loss: 0.1180 - Val Acc: 0.8551
2026-04-05 05:48:01,866 - INFO - Fold 6 logically complete. Tensor memory bounds cleared cleanly.
2026-04-05 05:48:01,871 - INFO - Original class distribution: [345 276]
2026-04-05 05:48:01,872 - INFO - Training device bound securely to: cuda

Fold 7:   0%|          | 0/100 [00:00<?, ?it/s]

2026-04-05 05:48:02,254 - INFO - Epoch 1/100 - Train Loss: 0.5924 - Val Acc: 0.7536
2026-04-05 05:48:02,574 - INFO - Epoch 2/100 - Train Loss: 0.4092 - Val Acc: 0.7681
2026-04-05 05:48:02,900 - INFO - Epoch 3/100 - Train Loss: 0.3360 - Val Acc: 0.7971
2026-04-05 05:48:03,226 - INFO - Epoch 4/100 - Train Loss: 0.3119 - Val Acc: 0.8116
2026-04-05 05:48:03,539 - INFO - Epoch 5/100 - Train Loss: 0.2823 - Val Acc: 0.7971
2026-04-05 05:48:03,871 - INFO - Epoch 6/100 - Train Loss: 0.2692 - Val Acc: 0.7971
2026-04-05 05:48:04,197 - INFO - Epoch 7/100 - Train Loss: 0.2799 - Val Acc: 0.7971
2026-04-05 05:48:04,547 - INFO - Epoch 8/100 - Train Loss: 0.2666 - Val Acc: 0.7971
2026-04-05 05:48:04,875 - INFO - Epoch 9/100 - Train Loss: 0.2642 - Val Acc: 0.7681
2026-04-05 05:48:05,205 - INFO - Epoch 10/100 - Train Loss: 0.2571 - Val Acc: 0.7681
2026-04-05 05:48:05,527 - INFO - Epoch 11/100 - Train Loss: 0.2501 - Val Acc: 0.7681
2026-04-05 05:48:05,857 - INFO - Epoch 12/100 - Train Loss: 0.2361 - Val Acc: 0.7826
2026-04-05 05:48:06,175 - INFO - Epoch 13/100 - Train Loss: 0.2526 - Val Acc: 0.7826
2026-04-05 05:48:06,494 - INFO - Epoch 14/100 - Train Loss: 0.2458 - Val Acc: 0.7681
2026-04-05 05:48:06,814 - INFO - Epoch 15/100 - Train Loss: 0.2460 - Val Acc: 0.7826
2026-04-05 05:48:07,132 - INFO - Epoch 16/100 - Train Loss: 0.2336 - Val Acc: 0.7826
2026-04-05 05:48:07,450 - INFO - Epoch 17/100 - Train Loss: 0.2386 - Val Acc: 0.7681
2026-04-05 05:48:07,771 - INFO - Epoch 18/100 - Train Loss: 0.2297 - Val Acc: 0.7826
2026-04-05 05:48:08,091 - INFO - Epoch 19/100 - Train Loss: 0.2189 - Val Acc: 0.7681
2026-04-05 05:48:08,408 - INFO - Epoch 20/100 - Train Loss: 0.2084 - Val Acc: 0.7826
2026-04-05 05:48:08,735 - INFO - Epoch 21/100 - Train Loss: 0.2177 - Val Acc: 0.7681
2026-04-05 05:48:09,065 - INFO - Epoch 22/100 - Train Loss: 0.2143 - Val Acc: 0.7681
2026-04-05 05:48:09,380 - INFO - Epoch 23/100 - Train Loss: 0.2281 - Val Acc: 0.7681
2026-04-05 05:48:09,700 - INFO - Epoch 24/100 - Train Loss: 0.2082 - Val Acc: 0.7681
2026-04-05 05:48:10,021 - INFO - Epoch 25/100 - Train Loss: 0.2135 - Val Acc: 0.7681
2026-04-05 05:48:10,347 - INFO - Epoch 26/100 - Train Loss: 0.2064 - Val Acc: 0.7681
2026-04-05 05:48:10,678 - INFO - Epoch 27/100 - Train Loss: 0.2082 - Val Acc: 0.7681
2026-04-05 05:48:11,003 - INFO - Epoch 28/100 - Train Loss: 0.2148 - Val Acc: 0.7536
2026-04-05 05:48:11,313 - INFO - Epoch 29/100 - Train Loss: 0.2004 - Val Acc: 0.7681
2026-04-05 05:48:11,641 - INFO - Epoch 30/100 - Train Loss: 0.2026 - Val Acc: 0.7681
2026-04-05 05:48:11,959 - INFO - Epoch 31/100 - Train Loss: 0.1996 - Val Acc: 0.7681
2026-04-05 05:48:12,279 - INFO - Epoch 32/100 - Train Loss: 0.1975 - Val Acc: 0.7681
2026-04-05 05:48:12,593 - INFO - Epoch 33/100 - Train Loss: 0.1992 - Val Acc: 0.7681
2026-04-05 05:48:12,914 - INFO - Epoch 34/100 - Train Loss: 0.1926 - Val Acc: 0.7681
2026-04-05 05:48:13,251 - INFO - Epoch 35/100 - Train Loss: 0.1977 - Val Acc: 0.7681
2026-04-05 05:48:13,572 - INFO - Epoch 36/100 - Train Loss: 0.1835 - Val Acc: 0.7681
2026-04-05 05:48:13,903 - INFO - Epoch 37/100 - Train Loss: 0.1802 - Val Acc: 0.7681
2026-04-05 05:48:14,229 - INFO - Epoch 38/100 - Train Loss: 0.1709 - Val Acc: 0.7681
2026-04-05 05:48:14,565 - INFO - Epoch 39/100 - Train Loss: 0.1821 - Val Acc: 0.7681
2026-04-05 05:48:14,881 - INFO - Epoch 40/100 - Train Loss: 0.1870 - Val Acc: 0.7826
2026-04-05 05:48:15,204 - INFO - Epoch 41/100 - Train Loss: 0.1756 - Val Acc: 0.7826
2026-04-05 05:48:15,527 - INFO - Epoch 42/100 - Train Loss: 0.1756 - Val Acc: 0.7681
2026-04-05 05:48:15,850 - INFO - Epoch 43/100 - Train Loss: 0.1648 - Val Acc: 0.7681
2026-04-05 05:48:16,181 - INFO - Epoch 44/100 - Train Loss: 0.1704 - Val Acc: 0.7681
2026-04-05 05:48:16,504 - INFO - Epoch 45/100 - Train Loss: 0.1637 - Val Acc: 0.7971
2026-04-05 05:48:16,822 - INFO - Epoch 46/100 - Train Loss: 0.1700 - Val Acc: 0.7681
2026-04-05 05:48:17,143 - INFO - Epoch 47/100 - Train Loss: 0.1608 - Val Acc: 0.7681
2026-04-05 05:48:17,467 - INFO - Epoch 48/100 - Train Loss: 0.1770 - Val Acc: 0.7971
2026-04-05 05:48:17,790 - INFO - Epoch 49/100 - Train Loss: 0.1633 - Val Acc: 0.7826
2026-04-05 05:48:18,113 - INFO - Epoch 50/100 - Train Loss: 0.1707 - Val Acc: 0.7681
2026-04-05 05:48:18,449 - INFO - Epoch 51/100 - Train Loss: 0.1625 - Val Acc: 0.7971
2026-04-05 05:48:18,777 - INFO - Epoch 52/100 - Train Loss: 0.1546 - Val Acc: 0.7826
2026-04-05 05:48:19,095 - INFO - Epoch 53/100 - Train Loss: 0.1566 - Val Acc: 0.7826
2026-04-05 05:48:19,423 - INFO - Epoch 54/100 - Train Loss: 0.1733 - Val Acc: 0.7681
2026-04-05 05:48:19,732 - INFO - Epoch 55/100 - Train Loss: 0.1602 - Val Acc: 0.7826
2026-04-05 05:48:20,061 - INFO - Epoch 56/100 - Train Loss: 0.1488 - Val Acc: 0.7681
2026-04-05 05:48:20,383 - INFO - Epoch 57/100 - Train Loss: 0.1531 - Val Acc: 0.7826
2026-04-05 05:48:20,704 - INFO - Epoch 58/100 - Train Loss: 0.1619 - Val Acc: 0.7826
2026-04-05 05:48:21,032 - INFO - Epoch 59/100 - Train Loss: 0.1520 - Val Acc: 0.7826
2026-04-05 05:48:21,351 - INFO - Epoch 60/100 - Train Loss: 0.1539 - Val Acc: 0.7971
2026-04-05 05:48:21,676 - INFO - Epoch 61/100 - Train Loss: 0.1648 - Val Acc: 0.8116
2026-04-05 05:48:22,012 - INFO - Epoch 62/100 - Train Loss: 0.1549 - Val Acc: 0.7971
2026-04-05 05:48:22,347 - INFO - Epoch 63/100 - Train Loss: 0.1287 - Val Acc: 0.7971
2026-04-05 05:48:22,672 - INFO - Epoch 64/100 - Train Loss: 0.1444 - Val Acc: 0.7971
2026-04-05 05:48:22,983 - INFO - Epoch 65/100 - Train Loss: 0.1306 - Val Acc: 0.7826
2026-04-05 05:48:23,299 - INFO - Epoch 66/100 - Train Loss: 0.1467 - Val Acc: 0.7971
2026-04-05 05:48:23,629 - INFO - Epoch 67/100 - Train Loss: 0.1384 - Val Acc: 0.7971
2026-04-05 05:48:23,970 - INFO - Epoch 68/100 - Train Loss: 0.1408 - Val Acc: 0.7971
2026-04-05 05:48:24,299 - INFO - Epoch 69/100 - Train Loss: 0.1456 - Val Acc: 0.7971
2026-04-05 05:48:24,643 - INFO - Epoch 70/100 - Train Loss: 0.1401 - Val Acc: 0.7971
2026-04-05 05:48:24,971 - INFO - Epoch 71/100 - Train Loss: 0.1303 - Val Acc: 0.7826
2026-04-05 05:48:25,298 - INFO - Epoch 72/100 - Train Loss: 0.1319 - Val Acc: 0.7971
2026-04-05 05:48:25,622 - INFO - Epoch 73/100 - Train Loss: 0.1368 - Val Acc: 0.7971
2026-04-05 05:48:25,939 - INFO - Epoch 74/100 - Train Loss: 0.1360 - Val Acc: 0.7971
2026-04-05 05:48:26,279 - INFO - Epoch 75/100 - Train Loss: 0.1440 - Val Acc: 0.7971
2026-04-05 05:48:26,587 - INFO - Epoch 76/100 - Train Loss: 0.1312 - Val Acc: 0.7971
2026-04-05 05:48:26,895 - INFO - Epoch 77/100 - Train Loss: 0.1164 - Val Acc: 0.7826
2026-04-05 05:48:27,210 - INFO - Epoch 78/100 - Train Loss: 0.1249 - Val Acc: 0.7826
2026-04-05 05:48:27,550 - INFO - Epoch 79/100 - Train Loss: 0.1513 - Val Acc: 0.7826
2026-04-05 05:48:27,882 - INFO - Epoch 80/100 - Train Loss: 0.1174 - Val Acc: 0.7971
2026-04-05 05:48:28,217 - INFO - Epoch 81/100 - Train Loss: 0.1411 - Val Acc: 0.7826
2026-04-05 05:48:28,533 - INFO - Epoch 82/100 - Train Loss: 0.1349 - Val Acc: 0.7971
2026-04-05 05:48:28,857 - INFO - Epoch 83/100 - Train Loss: 0.1173 - Val Acc: 0.7826
2026-04-05 05:48:29,179 - INFO - Epoch 84/100 - Train Loss: 0.1230 - Val Acc: 0.7826
2026-04-05 05:48:29,502 - INFO - Epoch 85/100 - Train Loss: 0.1393 - Val Acc: 0.7971
2026-04-05 05:48:29,816 - INFO - Epoch 86/100 - Train Loss: 0.1198 - Val Acc: 0.7826
2026-04-05 05:48:30,139 - INFO - Epoch 87/100 - Train Loss: 0.1113 - Val Acc: 0.7536
2026-04-05 05:48:30,455 - INFO - Epoch 88/100 - Train Loss: 0.1479 - Val Acc: 0.7826
2026-04-05 05:48:30,780 - INFO - Epoch 89/100 - Train Loss: 0.1186 - Val Acc: 0.7826
2026-04-05 05:48:31,109 - INFO - Epoch 90/100 - Train Loss: 0.1260 - Val Acc: 0.7826
2026-04-05 05:48:31,428 - INFO - Epoch 91/100 - Train Loss: 0.1312 - Val Acc: 0.7826
2026-04-05 05:48:31,748 - INFO - Epoch 92/100 - Train Loss: 0.1160 - Val Acc: 0.7971
2026-04-05 05:48:32,062 - INFO - Epoch 93/100 - Train Loss: 0.1175 - Val Acc: 0.7826
2026-04-05 05:48:32,381 - INFO - Epoch 94/100 - Train Loss: 0.1041 - Val Acc: 0.7826
2026-04-05 05:48:32,706 - INFO - Epoch 95/100 - Train Loss: 0.1221 - Val Acc: 0.7971
2026-04-05 05:48:33,034 - INFO - Epoch 96/100 - Train Loss: 0.1198 - Val Acc: 0.7971
2026-04-05 05:48:33,344 - INFO - Epoch 97/100 - Train Loss: 0.1106 - Val Acc: 0.7971
2026-04-05 05:48:33,659 - INFO - Epoch 98/100 - Train Loss: 0.1035 - Val Acc: 0.7971
2026-04-05 05:48:33,972 - INFO - Epoch 99/100 - Train Loss: 0.1096 - Val Acc: 0.7536
2026-04-05 05:48:34,292 - INFO - Epoch 100/100 - Train Loss: 0.1113 - Val Acc: 0.7536
2026-04-05 05:48:34,681 - INFO - Fold 7 logically complete. Tensor memory bounds cleared cleanly.
2026-04-05 05:48:34,685 - INFO - Original class distribution: [345 276]
2026-04-05 05:48:34,686 - INFO - Training device bound securely to: cuda

Fold 8:   0%|          | 0/100 [00:00<?, ?it/s]

2026-04-05 05:48:35,048 - INFO - Epoch 1/100 - Train Loss: 0.5988 - Val Acc: 0.8406
2026-04-05 05:48:35,369 - INFO - Epoch 2/100 - Train Loss: 0.4181 - Val Acc: 0.8406
2026-04-05 05:48:35,687 - INFO - Epoch 3/100 - Train Loss: 0.3492 - Val Acc: 0.8406
2026-04-05 05:48:36,043 - INFO - Epoch 4/100 - Train Loss: 0.3302 - Val Acc: 0.8261
2026-04-05 05:48:36,386 - INFO - Epoch 5/100 - Train Loss: 0.3245 - Val Acc: 0.8406
2026-04-05 05:48:36,708 - INFO - Epoch 6/100 - Train Loss: 0.3076 - Val Acc: 0.8406
2026-04-05 05:48:37,058 - INFO - Epoch 7/100 - Train Loss: 0.3164 - Val Acc: 0.8406
2026-04-05 05:48:37,382 - INFO - Epoch 8/100 - Train Loss: 0.3043 - Val Acc: 0.8406
2026-04-05 05:48:37,709 - INFO - Epoch 9/100 - Train Loss: 0.2898 - Val Acc: 0.8551
2026-04-05 05:48:38,033 - INFO - Epoch 10/100 - Train Loss: 0.2915 - Val Acc: 0.8551
2026-04-05 05:48:38,363 - INFO - Epoch 11/100 - Train Loss: 0.2887 - Val Acc: 0.8406
2026-04-05 05:48:38,680 - INFO - Epoch 12/100 - Train Loss: 0.2761 - Val Acc: 0.8261
2026-04-05 05:48:39,001 - INFO - Epoch 13/100 - Train Loss: 0.2737 - Val Acc: 0.8406
2026-04-05 05:48:39,323 - INFO - Epoch 14/100 - Train Loss: 0.2771 - Val Acc: 0.8406
2026-04-05 05:48:39,640 - INFO - Epoch 15/100 - Train Loss: 0.2706 - Val Acc: 0.8261
2026-04-05 05:48:39,977 - INFO - Epoch 16/100 - Train Loss: 0.2618 - Val Acc: 0.8406
2026-04-05 05:48:40,300 - INFO - Epoch 17/100 - Train Loss: 0.2585 - Val Acc: 0.8406
2026-04-05 05:48:40,618 - INFO - Epoch 18/100 - Train Loss: 0.2592 - Val Acc: 0.8406
2026-04-05 05:48:40,938 - INFO - Epoch 19/100 - Train Loss: 0.2515 - Val Acc: 0.8261
2026-04-05 05:48:41,257 - INFO - Epoch 20/100 - Train Loss: 0.2595 - Val Acc: 0.8261
2026-04-05 05:48:41,577 - INFO - Epoch 21/100 - Train Loss: 0.2353 - Val Acc: 0.8406
2026-04-05 05:48:41,902 - INFO - Epoch 22/100 - Train Loss: 0.2381 - Val Acc: 0.8261
2026-04-05 05:48:42,219 - INFO - Epoch 23/100 - Train Loss: 0.2276 - Val Acc: 0.8551
2026-04-05 05:48:42,541 - INFO - Epoch 24/100 - Train Loss: 0.2319 - Val Acc: 0.8261
2026-04-05 05:48:42,863 - INFO - Epoch 25/100 - Train Loss: 0.2231 - Val Acc: 0.8261
2026-04-05 05:48:43,190 - INFO - Epoch 26/100 - Train Loss: 0.2129 - Val Acc: 0.8261
2026-04-05 05:48:43,509 - INFO - Epoch 27/100 - Train Loss: 0.2148 - Val Acc: 0.8406
2026-04-05 05:48:43,823 - INFO - Epoch 28/100 - Train Loss: 0.2229 - Val Acc: 0.8261
2026-04-05 05:48:44,138 - INFO - Epoch 29/100 - Train Loss: 0.2035 - Val Acc: 0.8116
2026-04-05 05:48:44,469 - INFO - Epoch 30/100 - Train Loss: 0.2264 - Val Acc: 0.8261
2026-04-05 05:48:44,821 - INFO - Epoch 31/100 - Train Loss: 0.2213 - Val Acc: 0.8551
2026-04-05 05:48:45,149 - INFO - Epoch 32/100 - Train Loss: 0.2226 - Val Acc: 0.8261
2026-04-05 05:48:45,481 - INFO - Epoch 33/100 - Train Loss: 0.2095 - Val Acc: 0.8261
2026-04-05 05:48:45,801 - INFO - Epoch 34/100 - Train Loss: 0.2001 - Val Acc: 0.8116
2026-04-05 05:48:46,137 - INFO - Epoch 35/100 - Train Loss: 0.2104 - Val Acc: 0.8406
2026-04-05 05:48:46,465 - INFO - Epoch 36/100 - Train Loss: 0.2169 - Val Acc: 0.8261
2026-04-05 05:48:46,796 - INFO - Epoch 37/100 - Train Loss: 0.2077 - Val Acc: 0.8261
2026-04-05 05:48:47,140 - INFO - Epoch 38/100 - Train Loss: 0.1840 - Val Acc: 0.8406
2026-04-05 05:48:47,461 - INFO - Epoch 39/100 - Train Loss: 0.1968 - Val Acc: 0.8261
2026-04-05 05:48:47,793 - INFO - Epoch 40/100 - Train Loss: 0.2007 - Val Acc: 0.8406
2026-04-05 05:48:48,137 - INFO - Epoch 41/100 - Train Loss: 0.1905 - Val Acc: 0.8261
2026-04-05 05:48:48,457 - INFO - Epoch 42/100 - Train Loss: 0.1977 - Val Acc: 0.8261
2026-04-05 05:48:48,780 - INFO - Epoch 43/100 - Train Loss: 0.2046 - Val Acc: 0.8406
2026-04-05 05:48:49,104 - INFO - Epoch 44/100 - Train Loss: 0.1955 - Val Acc: 0.8406
2026-04-05 05:48:49,421 - INFO - Epoch 45/100 - Train Loss: 0.1917 - Val Acc: 0.8261
2026-04-05 05:48:49,750 - INFO - Epoch 46/100 - Train Loss: 0.1880 - Val Acc: 0.8261
2026-04-05 05:48:50,070 - INFO - Epoch 47/100 - Train Loss: 0.1713 - Val Acc: 0.8406
2026-04-05 05:48:50,394 - INFO - Epoch 48/100 - Train Loss: 0.1902 - Val Acc: 0.8261
2026-04-05 05:48:50,727 - INFO - Epoch 49/100 - Train Loss: 0.1618 - Val Acc: 0.8406
2026-04-05 05:48:51,052 - INFO - Epoch 50/100 - Train Loss: 0.1723 - Val Acc: 0.8116
2026-04-05 05:48:51,387 - INFO - Epoch 51/100 - Train Loss: 0.1788 - Val Acc: 0.8261
2026-04-05 05:48:51,711 - INFO - Epoch 52/100 - Train Loss: 0.1901 - Val Acc: 0.8406
2026-04-05 05:48:52,042 - INFO - Epoch 53/100 - Train Loss: 0.1756 - Val Acc: 0.8261
2026-04-05 05:48:52,373 - INFO - Epoch 54/100 - Train Loss: 0.1724 - Val Acc: 0.8261
2026-04-05 05:48:52,706 - INFO - Epoch 55/100 - Train Loss: 0.1750 - Val Acc: 0.8261
2026-04-05 05:48:53,035 - INFO - Epoch 56/100 - Train Loss: 0.1758 - Val Acc: 0.8551
2026-04-05 05:48:53,366 - INFO - Epoch 57/100 - Train Loss: 0.1827 - Val Acc: 0.8261
2026-04-05 05:48:53,694 - INFO - Epoch 58/100 - Train Loss: 0.1615 - Val Acc: 0.8261
2026-04-05 05:48:54,046 - INFO - Epoch 59/100 - Train Loss: 0.1793 - Val Acc: 0.8116
2026-04-05 05:48:54,377 - INFO - Epoch 60/100 - Train Loss: 0.1574 - Val Acc: 0.8261
2026-04-05 05:48:54,721 - INFO - Epoch 61/100 - Train Loss: 0.1639 - Val Acc: 0.8261
2026-04-05 05:48:55,081 - INFO - Epoch 62/100 - Train Loss: 0.1561 - Val Acc: 0.8261
2026-04-05 05:48:55,416 - INFO - Epoch 63/100 - Train Loss: 0.1715 - Val Acc: 0.8261
2026-04-05 05:48:55,738 - INFO - Epoch 64/100 - Train Loss: 0.1600 - Val Acc: 0.8261
2026-04-05 05:48:56,055 - INFO - Epoch 65/100 - Train Loss: 0.1714 - Val Acc: 0.8261
2026-04-05 05:48:56,386 - INFO - Epoch 66/100 - Train Loss: 0.1602 - Val Acc: 0.8261
2026-04-05 05:48:56,715 - INFO - Epoch 67/100 - Train Loss: 0.1502 - Val Acc: 0.8406
2026-04-05 05:48:57,038 - INFO - Epoch 68/100 - Train Loss: 0.1493 - Val Acc: 0.8406
2026-04-05 05:48:57,357 - INFO - Epoch 69/100 - Train Loss: 0.1545 - Val Acc: 0.8406
2026-04-05 05:48:57,677 - INFO - Epoch 70/100 - Train Loss: 0.1349 - Val Acc: 0.8261
2026-04-05 05:48:57,999 - INFO - Epoch 71/100 - Train Loss: 0.1402 - Val Acc: 0.8551
2026-04-05 05:48:58,312 - INFO - Epoch 72/100 - Train Loss: 0.1478 - Val Acc: 0.8406
2026-04-05 05:48:58,624 - INFO - Epoch 73/100 - Train Loss: 0.1479 - Val Acc: 0.8261
2026-04-05 05:48:58,953 - INFO - Epoch 74/100 - Train Loss: 0.1459 - Val Acc: 0.8406
2026-04-05 05:48:59,280 - INFO - Epoch 75/100 - Train Loss: 0.1271 - Val Acc: 0.8261
2026-04-05 05:48:59,615 - INFO - Epoch 76/100 - Train Loss: 0.1307 - Val Acc: 0.8261
2026-04-05 05:48:59,932 - INFO - Epoch 77/100 - Train Loss: 0.1382 - Val Acc: 0.8261
2026-04-05 05:49:00,285 - INFO - Epoch 78/100 - Train Loss: 0.1458 - Val Acc: 0.8406
2026-04-05 05:49:00,621 - INFO - Epoch 79/100 - Train Loss: 0.1373 - Val Acc: 0.8261
2026-04-05 05:49:00,941 - INFO - Epoch 80/100 - Train Loss: 0.1307 - Val Acc: 0.8551
2026-04-05 05:49:01,262 - INFO - Epoch 81/100 - Train Loss: 0.1475 - Val Acc: 0.8406
2026-04-05 05:49:01,577 - INFO - Epoch 82/100 - Train Loss: 0.1401 - Val Acc: 0.8261
2026-04-05 05:49:01,890 - INFO - Epoch 83/100 - Train Loss: 0.1505 - Val Acc: 0.8406
2026-04-05 05:49:02,208 - INFO - Epoch 84/100 - Train Loss: 0.1327 - Val Acc: 0.8406
2026-04-05 05:49:02,533 - INFO - Epoch 85/100 - Train Loss: 0.1322 - Val Acc: 0.8551
2026-04-05 05:49:02,852 - INFO - Epoch 86/100 - Train Loss: 0.1181 - Val Acc: 0.8406
2026-04-05 05:49:03,180 - INFO - Epoch 87/100 - Train Loss: 0.1300 - Val Acc: 0.8406
2026-04-05 05:49:03,510 - INFO - Epoch 88/100 - Train Loss: 0.1310 - Val Acc: 0.8261
2026-04-05 05:49:03,841 - INFO - Epoch 89/100 - Train Loss: 0.1353 - Val Acc: 0.8261
2026-04-05 05:49:04,164 - INFO - Epoch 90/100 - Train Loss: 0.1398 - Val Acc: 0.8406
2026-04-05 05:49:04,494 - INFO - Epoch 91/100 - Train Loss: 0.1447 - Val Acc: 0.8551
2026-04-05 05:49:04,831 - INFO - Epoch 92/100 - Train Loss: 0.1377 - Val Acc: 0.8406
2026-04-05 05:49:05,161 - INFO - Epoch 93/100 - Train Loss: 0.1219 - Val Acc: 0.8551
2026-04-05 05:49:05,471 - INFO - Epoch 94/100 - Train Loss: 0.1290 - Val Acc: 0.8406
2026-04-05 05:49:05,791 - INFO - Epoch 95/100 - Train Loss: 0.1288 - Val Acc: 0.8551
2026-04-05 05:49:06,108 - INFO - Epoch 96/100 - Train Loss: 0.1184 - Val Acc: 0.8551
2026-04-05 05:49:06,431 - INFO - Epoch 97/100 - Train Loss: 0.1153 - Val Acc: 0.8551
2026-04-05 05:49:06,766 - INFO - Epoch 98/100 - Train Loss: 0.1103 - Val Acc: 0.8406
2026-04-05 05:49:07,094 - INFO - Epoch 99/100 - Train Loss: 0.1292 - Val Acc: 0.8261
2026-04-05 05:49:07,412 - INFO - Epoch 100/100 - Train Loss: 0.1232 - Val Acc: 0.8406
2026-04-05 05:49:07,774 - INFO - Fold 8 logically complete. Tensor memory bounds cleared cleanly.
2026-04-05 05:49:07,778 - INFO - Original class distribution: [345 276]
2026-04-05 05:49:07,779 - INFO - Training device bound securely to: cuda

Fold 9:   0%|          | 0/100 [00:00<?, ?it/s]

2026-04-05 05:49:08,119 - INFO - Epoch 1/100 - Train Loss: 0.6114 - Val Acc: 0.8261
2026-04-05 05:49:08,434 - INFO - Epoch 2/100 - Train Loss: 0.4361 - Val Acc: 0.8261
2026-04-05 05:49:08,748 - INFO - Epoch 3/100 - Train Loss: 0.3554 - Val Acc: 0.8261
2026-04-05 05:49:09,059 - INFO - Epoch 4/100 - Train Loss: 0.3251 - Val Acc: 0.8261
2026-04-05 05:49:09,389 - INFO - Epoch 5/100 - Train Loss: 0.2937 - Val Acc: 0.8406
2026-04-05 05:49:09,706 - INFO - Epoch 6/100 - Train Loss: 0.3000 - Val Acc: 0.8116
2026-04-05 05:49:10,025 - INFO - Epoch 7/100 - Train Loss: 0.3002 - Val Acc: 0.8261
2026-04-05 05:49:10,355 - INFO - Epoch 8/100 - Train Loss: 0.2947 - Val Acc: 0.7971
2026-04-05 05:49:10,668 - INFO - Epoch 9/100 - Train Loss: 0.2731 - Val Acc: 0.8261
2026-04-05 05:49:10,987 - INFO - Epoch 10/100 - Train Loss: 0.2780 - Val Acc: 0.8406
2026-04-05 05:49:11,299 - INFO - Epoch 11/100 - Train Loss: 0.2686 - Val Acc: 0.8406
2026-04-05 05:49:11,624 - INFO - Epoch 12/100 - Train Loss: 0.2656 - Val Acc: 0.8261
2026-04-05 05:49:11,951 - INFO - Epoch 13/100 - Train Loss: 0.2671 - Val Acc: 0.8551
2026-04-05 05:49:12,270 - INFO - Epoch 14/100 - Train Loss: 0.2496 - Val Acc: 0.8551
2026-04-05 05:49:12,588 - INFO - Epoch 15/100 - Train Loss: 0.2536 - Val Acc: 0.8406
2026-04-05 05:49:12,921 - INFO - Epoch 16/100 - Train Loss: 0.2557 - Val Acc: 0.8406
2026-04-05 05:49:13,252 - INFO - Epoch 17/100 - Train Loss: 0.2626 - Val Acc: 0.8551
2026-04-05 05:49:13,575 - INFO - Epoch 18/100 - Train Loss: 0.2485 - Val Acc: 0.8696
2026-04-05 05:49:13,892 - INFO - Epoch 19/100 - Train Loss: 0.2467 - Val Acc: 0.8551
2026-04-05 05:49:14,215 - INFO - Epoch 20/100 - Train Loss: 0.2493 - Val Acc: 0.8551
2026-04-05 05:49:14,551 - INFO - Epoch 21/100 - Train Loss: 0.2369 - Val Acc: 0.8551
2026-04-05 05:49:14,884 - INFO - Epoch 22/100 - Train Loss: 0.2341 - Val Acc: 0.8261
2026-04-05 05:49:15,195 - INFO - Epoch 23/100 - Train Loss: 0.2228 - Val Acc: 0.8551
2026-04-05 05:49:15,515 - INFO - Epoch 24/100 - Train Loss: 0.2195 - Val Acc: 0.8696
2026-04-05 05:49:15,838 - INFO - Epoch 25/100 - Train Loss: 0.2325 - Val Acc: 0.8551
2026-04-05 05:49:16,159 - INFO - Epoch 26/100 - Train Loss: 0.2273 - Val Acc: 0.8696
2026-04-05 05:49:16,482 - INFO - Epoch 27/100 - Train Loss: 0.2317 - Val Acc: 0.8696
2026-04-05 05:49:16,804 - INFO - Epoch 28/100 - Train Loss: 0.2146 - Val Acc: 0.8696
2026-04-05 05:49:17,111 - INFO - Epoch 29/100 - Train Loss: 0.2048 - Val Acc: 0.8696
2026-04-05 05:49:17,442 - INFO - Epoch 30/100 - Train Loss: 0.2209 - Val Acc: 0.8696
2026-04-05 05:49:17,762 - INFO - Epoch 31/100 - Train Loss: 0.2226 - Val Acc: 0.8696
2026-04-05 05:49:18,090 - INFO - Epoch 32/100 - Train Loss: 0.2222 - Val Acc: 0.8696
2026-04-05 05:49:18,435 - INFO - Epoch 33/100 - Train Loss: 0.2152 - Val Acc: 0.8696
2026-04-05 05:49:18,763 - INFO - Epoch 34/100 - Train Loss: 0.2046 - Val Acc: 0.8551
2026-04-05 05:49:19,091 - INFO - Epoch 35/100 - Train Loss: 0.2006 - Val Acc: 0.8696
2026-04-05 05:49:19,406 - INFO - Epoch 36/100 - Train Loss: 0.2017 - Val Acc: 0.8696
2026-04-05 05:49:19,735 - INFO - Epoch 37/100 - Train Loss: 0.1919 - Val Acc: 0.8551
2026-04-05 05:49:20,049 - INFO - Epoch 38/100 - Train Loss: 0.1972 - Val Acc: 0.8696
2026-04-05 05:49:20,360 - INFO - Epoch 39/100 - Train Loss: 0.1990 - Val Acc: 0.8696
2026-04-05 05:49:20,677 - INFO - Epoch 40/100 - Train Loss: 0.2126 - Val Acc: 0.8551
2026-04-05 05:49:20,997 - INFO - Epoch 41/100 - Train Loss: 0.1888 - Val Acc: 0.8406
2026-04-05 05:49:21,319 - INFO - Epoch 42/100 - Train Loss: 0.2004 - Val Acc: 0.8696
2026-04-05 05:49:21,642 - INFO - Epoch 43/100 - Train Loss: 0.1988 - Val Acc: 0.8696
2026-04-05 05:49:21,961 - INFO - Epoch 44/100 - Train Loss: 0.1834 - Val Acc: 0.8551
2026-04-05 05:49:22,276 - INFO - Epoch 45/100 - Train Loss: 0.1914 - Val Acc: 0.8696
2026-04-05 05:49:22,602 - INFO - Epoch 46/100 - Train Loss: 0.1836 - Val Acc: 0.8551
2026-04-05 05:49:22,919 - INFO - Epoch 47/100 - Train Loss: 0.1903 - Val Acc: 0.8406
2026-04-05 05:49:23,246 - INFO - Epoch 48/100 - Train Loss: 0.1781 - Val Acc: 0.8406
2026-04-05 05:49:23,569 - INFO - Epoch 49/100 - Train Loss: 0.1949 - Val Acc: 0.8551
2026-04-05 05:49:23,879 - INFO - Epoch 50/100 - Train Loss: 0.1861 - Val Acc: 0.8551
2026-04-05 05:49:24,213 - INFO - Epoch 51/100 - Train Loss: 0.1713 - Val Acc: 0.8551
2026-04-05 05:49:24,547 - INFO - Epoch 52/100 - Train Loss: 0.1665 - Val Acc: 0.8261
2026-04-05 05:49:24,872 - INFO - Epoch 53/100 - Train Loss: 0.1714 - Val Acc: 0.8406
2026-04-05 05:49:25,189 - INFO - Epoch 54/100 - Train Loss: 0.1743 - Val Acc: 0.8406
2026-04-05 05:49:25,510 - INFO - Epoch 55/100 - Train Loss: 0.1603 - Val Acc: 0.8551
2026-04-05 05:49:25,819 - INFO - Epoch 56/100 - Train Loss: 0.1735 - Val Acc: 0.8551
2026-04-05 05:49:26,137 - INFO - Epoch 57/100 - Train Loss: 0.1549 - Val Acc: 0.8551
2026-04-05 05:49:26,452 - INFO - Epoch 58/100 - Train Loss: 0.1540 - Val Acc: 0.8551
2026-04-05 05:49:26,782 - INFO - Epoch 59/100 - Train Loss: 0.1617 - Val Acc: 0.8551
2026-04-05 05:49:27,099 - INFO - Epoch 60/100 - Train Loss: 0.1698 - Val Acc: 0.8551
2026-04-05 05:49:27,421 - INFO - Epoch 61/100 - Train Loss: 0.1641 - Val Acc: 0.8551
2026-04-05 05:49:27,744 - INFO - Epoch 62/100 - Train Loss: 0.1423 - Val Acc: 0.8551
2026-04-05 05:49:28,053 - INFO - Epoch 63/100 - Train Loss: 0.1414 - Val Acc: 0.8406
2026-04-05 05:49:28,362 - INFO - Epoch 64/100 - Train Loss: 0.1644 - Val Acc: 0.8406
2026-04-05 05:49:28,666 - INFO - Epoch 65/100 - Train Loss: 0.1548 - Val Acc: 0.8406
2026-04-05 05:49:28,976 - INFO - Epoch 66/100 - Train Loss: 0.1704 - Val Acc: 0.8261
2026-04-05 05:49:29,293 - INFO - Epoch 67/100 - Train Loss: 0.1618 - Val Acc: 0.8551
2026-04-05 05:49:29,614 - INFO - Epoch 68/100 - Train Loss: 0.1398 - Val Acc: 0.8551
2026-04-05 05:49:29,929 - INFO - Epoch 69/100 - Train Loss: 0.1467 - Val Acc: 0.8406
2026-04-05 05:49:30,248 - INFO - Epoch 70/100 - Train Loss: 0.1469 - Val Acc: 0.8406
2026-04-05 05:49:30,566 - INFO - Epoch 71/100 - Train Loss: 0.1527 - Val Acc: 0.8406
2026-04-05 05:49:30,879 - INFO - Epoch 72/100 - Train Loss: 0.1563 - Val Acc: 0.8406
2026-04-05 05:49:31,209 - INFO - Epoch 73/100 - Train Loss: 0.1462 - Val Acc: 0.8406
2026-04-05 05:49:31,525 - INFO - Epoch 74/100 - Train Loss: 0.1497 - Val Acc: 0.8551
2026-04-05 05:49:31,839 - INFO - Epoch 75/100 - Train Loss: 0.1319 - Val Acc: 0.8406
2026-04-05 05:49:32,156 - INFO - Epoch 76/100 - Train Loss: 0.1257 - Val Acc: 0.8406
2026-04-05 05:49:32,483 - INFO - Epoch 77/100 - Train Loss: 0.1362 - Val Acc: 0.8406
2026-04-05 05:49:32,799 - INFO - Epoch 78/100 - Train Loss: 0.1525 - Val Acc: 0.8406
2026-04-05 05:49:33,121 - INFO - Epoch 79/100 - Train Loss: 0.1298 - Val Acc: 0.8551
2026-04-05 05:49:33,442 - INFO - Epoch 80/100 - Train Loss: 0.1338 - Val Acc: 0.8406
2026-04-05 05:49:33,764 - INFO - Epoch 81/100 - Train Loss: 0.1219 - Val Acc: 0.8551
2026-04-05 05:49:34,091 - INFO - Epoch 82/100 - Train Loss: 0.1375 - Val Acc: 0.8261
2026-04-05 05:49:34,432 - INFO - Epoch 83/100 - Train Loss: 0.1351 - Val Acc: 0.8406
2026-04-05 05:49:34,782 - INFO - Epoch 84/100 - Train Loss: 0.1269 - Val Acc: 0.8551
2026-04-05 05:49:35,100 - INFO - Epoch 85/100 - Train Loss: 0.1290 - Val Acc: 0.8551
2026-04-05 05:49:35,439 - INFO - Epoch 86/100 - Train Loss: 0.1317 - Val Acc: 0.8551
2026-04-05 05:49:35,760 - INFO - Epoch 87/100 - Train Loss: 0.1257 - Val Acc: 0.8551
2026-04-05 05:49:36,101 - INFO - Epoch 88/100 - Train Loss: 0.1241 - Val Acc: 0.8406
2026-04-05 05:49:36,431 - INFO - Epoch 89/100 - Train Loss: 0.1194 - Val Acc: 0.8696
2026-04-05 05:49:36,765 - INFO - Epoch 90/100 - Train Loss: 0.1330 - Val Acc: 0.8551
2026-04-05 05:49:37,086 - INFO - Epoch 91/100 - Train Loss: 0.1109 - Val Acc: 0.8551
2026-04-05 05:49:37,403 - INFO - Epoch 92/100 - Train Loss: 0.1233 - Val Acc: 0.8406
2026-04-05 05:49:37,722 - INFO - Epoch 93/100 - Train Loss: 0.1221 - Val Acc: 0.8551
2026-04-05 05:49:38,044 - INFO - Epoch 94/100 - Train Loss: 0.1122 - Val Acc: 0.8406
2026-04-05 05:49:38,357 - INFO - Epoch 95/100 - Train Loss: 0.1111 - Val Acc: 0.8551
2026-04-05 05:49:38,694 - INFO - Epoch 96/100 - Train Loss: 0.1286 - Val Acc: 0.8406
2026-04-05 05:49:39,017 - INFO - Epoch 97/100 - Train Loss: 0.1099 - Val Acc: 0.8261
2026-04-05 05:49:39,343 - INFO - Epoch 98/100 - Train Loss: 0.1174 - Val Acc: 0.8406
2026-04-05 05:49:39,658 - INFO - Epoch 99/100 - Train Loss: 0.1262 - Val Acc: 0.8406
2026-04-05 05:49:39,972 - INFO - Epoch 100/100 - Train Loss: 0.1100 - Val Acc: 0.8406
2026-04-05 05:49:40,345 - INFO - Fold 9 logically complete. Tensor memory bounds cleared cleanly.
2026-04-05 05:49:40,350 - INFO - Original class distribution: [345 276]
2026-04-05 05:49:40,350 - INFO - Training device bound securely to: cuda

Fold 10:   0%|          | 0/100 [00:00<?, ?it/s]

2026-04-05 05:49:40,690 - INFO - Epoch 1/100 - Train Loss: 0.6123 - Val Acc: 0.8841
2026-04-05 05:49:41,011 - INFO - Epoch 2/100 - Train Loss: 0.4429 - Val Acc: 0.8986
2026-04-05 05:49:41,336 - INFO - Epoch 3/100 - Train Loss: 0.3743 - Val Acc: 0.9130
2026-04-05 05:49:41,655 - INFO - Epoch 4/100 - Train Loss: 0.3613 - Val Acc: 0.9420
2026-04-05 05:49:41,983 - INFO - Epoch 5/100 - Train Loss: 0.3452 - Val Acc: 0.9565
2026-04-05 05:49:42,303 - INFO - Epoch 6/100 - Train Loss: 0.3291 - Val Acc: 0.9565
2026-04-05 05:49:42,624 - INFO - Epoch 7/100 - Train Loss: 0.3228 - Val Acc: 0.9565
2026-04-05 05:49:42,942 - INFO - Epoch 8/100 - Train Loss: 0.3261 - Val Acc: 0.9565
2026-04-05 05:49:43,265 - INFO - Epoch 9/100 - Train Loss: 0.3168 - Val Acc: 0.9710
2026-04-05 05:49:43,579 - INFO - Epoch 10/100 - Train Loss: 0.2964 - Val Acc: 0.9710
2026-04-05 05:49:43,896 - INFO - Epoch 11/100 - Train Loss: 0.3061 - Val Acc: 0.9710
2026-04-05 05:49:44,224 - INFO - Epoch 12/100 - Train Loss: 0.2881 - Val Acc: 0.9710
2026-04-05 05:49:44,564 - INFO - Epoch 13/100 - Train Loss: 0.2948 - Val Acc: 0.9710
2026-04-05 05:49:44,882 - INFO - Epoch 14/100 - Train Loss: 0.2821 - Val Acc: 0.9710
2026-04-05 05:49:45,202 - INFO - Epoch 15/100 - Train Loss: 0.2861 - Val Acc: 0.9710
2026-04-05 05:49:45,527 - INFO - Epoch 16/100 - Train Loss: 0.2664 - Val Acc: 0.9710
2026-04-05 05:49:45,862 - INFO - Epoch 17/100 - Train Loss: 0.2752 - Val Acc: 0.9565
2026-04-05 05:49:46,186 - INFO - Epoch 18/100 - Train Loss: 0.2654 - Val Acc: 0.9710
2026-04-05 05:49:46,500 - INFO - Epoch 19/100 - Train Loss: 0.2662 - Val Acc: 0.9565
2026-04-05 05:49:46,814 - INFO - Epoch 20/100 - Train Loss: 0.2445 - Val Acc: 0.9565
2026-04-05 05:49:47,138 - INFO - Epoch 21/100 - Train Loss: 0.2498 - Val Acc: 0.9565
2026-04-05 05:49:47,446 - INFO - Epoch 22/100 - Train Loss: 0.2415 - Val Acc: 0.9420
2026-04-05 05:49:47,773 - INFO - Epoch 23/100 - Train Loss: 0.2606 - Val Acc: 0.9420
2026-04-05 05:49:48,095 - INFO - Epoch 24/100 - Train Loss: 0.2465 - Val Acc: 0.9565
2026-04-05 05:49:48,406 - INFO - Epoch 25/100 - Train Loss: 0.2506 - Val Acc: 0.9420
2026-04-05 05:49:48,718 - INFO - Epoch 26/100 - Train Loss: 0.2457 - Val Acc: 0.9420
2026-04-05 05:49:49,033 - INFO - Epoch 27/100 - Train Loss: 0.2417 - Val Acc: 0.9420
2026-04-05 05:49:49,358 - INFO - Epoch 28/100 - Train Loss: 0.2425 - Val Acc: 0.9420
2026-04-05 05:49:49,684 - INFO - Epoch 29/100 - Train Loss: 0.2432 - Val Acc: 0.9420
2026-04-05 05:49:50,010 - INFO - Epoch 30/100 - Train Loss: 0.2249 - Val Acc: 0.9420
2026-04-05 05:49:50,339 - INFO - Epoch 31/100 - Train Loss: 0.2297 - Val Acc: 0.9420
2026-04-05 05:49:50,668 - INFO - Epoch 32/100 - Train Loss: 0.2383 - Val Acc: 0.9420
2026-04-05 05:49:51,000 - INFO - Epoch 33/100 - Train Loss: 0.2250 - Val Acc: 0.9420
2026-04-05 05:49:51,334 - INFO - Epoch 34/100 - Train Loss: 0.2313 - Val Acc: 0.9420
2026-04-05 05:49:51,652 - INFO - Epoch 35/100 - Train Loss: 0.2283 - Val Acc: 0.9420
2026-04-05 05:49:51,967 - INFO - Epoch 36/100 - Train Loss: 0.2327 - Val Acc: 0.9420
2026-04-05 05:49:52,275 - INFO - Epoch 37/100 - Train Loss: 0.2207 - Val Acc: 0.9420
2026-04-05 05:49:52,594 - INFO - Epoch 38/100 - Train Loss: 0.2160 - Val Acc: 0.9420
2026-04-05 05:49:52,909 - INFO - Epoch 39/100 - Train Loss: 0.2029 - Val Acc: 0.9420
2026-04-05 05:49:53,229 - INFO - Epoch 40/100 - Train Loss: 0.1975 - Val Acc: 0.9420
2026-04-05 05:49:53,561 - INFO - Epoch 41/100 - Train Loss: 0.2003 - Val Acc: 0.9420
2026-04-05 05:49:53,891 - INFO - Epoch 42/100 - Train Loss: 0.1934 - Val Acc: 0.9420
2026-04-05 05:49:54,214 - INFO - Epoch 43/100 - Train Loss: 0.1981 - Val Acc: 0.9420
2026-04-05 05:49:54,568 - INFO - Epoch 44/100 - Train Loss: 0.1943 - Val Acc: 0.9420
2026-04-05 05:49:54,885 - INFO - Epoch 45/100 - Train Loss: 0.2039 - Val Acc: 0.9420
2026-04-05 05:49:55,199 - INFO - Epoch 46/100 - Train Loss: 0.1965 - Val Acc: 0.9420
2026-04-05 05:49:55,528 - INFO - Epoch 47/100 - Train Loss: 0.2138 - Val Acc: 0.9420
2026-04-05 05:49:55,854 - INFO - Epoch 48/100 - Train Loss: 0.1894 - Val Acc: 0.9420
2026-04-05 05:49:56,172 - INFO - Epoch 49/100 - Train Loss: 0.1860 - Val Acc: 0.9420
2026-04-05 05:49:56,499 - INFO - Epoch 50/100 - Train Loss: 0.1711 - Val Acc: 0.9420
2026-04-05 05:49:56,816 - INFO - Epoch 51/100 - Train Loss: 0.1813 - Val Acc: 0.9420
2026-04-05 05:49:57,146 - INFO - Epoch 52/100 - Train Loss: 0.1873 - Val Acc: 0.9420
2026-04-05 05:49:57,464 - INFO - Epoch 53/100 - Train Loss: 0.1879 - Val Acc: 0.9420
2026-04-05 05:49:57,795 - INFO - Epoch 54/100 - Train Loss: 0.1762 - Val Acc: 0.9420
2026-04-05 05:49:58,111 - INFO - Epoch 55/100 - Train Loss: 0.2003 - Val Acc: 0.9420
2026-04-05 05:49:58,435 - INFO - Epoch 56/100 - Train Loss: 0.1803 - Val Acc: 0.9420
2026-04-05 05:49:58,765 - INFO - Epoch 57/100 - Train Loss: 0.1837 - Val Acc: 0.9420
2026-04-05 05:49:59,092 - INFO - Epoch 58/100 - Train Loss: 0.1615 - Val Acc: 0.9420
2026-04-05 05:49:59,404 - INFO - Epoch 59/100 - Train Loss: 0.1772 - Val Acc: 0.9420
2026-04-05 05:49:59,717 - INFO - Epoch 60/100 - Train Loss: 0.1736 - Val Acc: 0.9420
2026-04-05 05:50:00,035 - INFO - Epoch 61/100 - Train Loss: 0.1709 - Val Acc: 0.9420
2026-04-05 05:50:00,356 - INFO - Epoch 62/100 - Train Loss: 0.1750 - Val Acc: 0.9420
2026-04-05 05:50:00,672 - INFO - Epoch 63/100 - Train Loss: 0.1645 - Val Acc: 0.9420
2026-04-05 05:50:00,989 - INFO - Epoch 64/100 - Train Loss: 0.1622 - Val Acc: 0.9420
2026-04-05 05:50:01,310 - INFO - Epoch 65/100 - Train Loss: 0.1685 - Val Acc: 0.9420
2026-04-05 05:50:01,635 - INFO - Epoch 66/100 - Train Loss: 0.1690 - Val Acc: 0.9420
2026-04-05 05:50:01,952 - INFO - Epoch 67/100 - Train Loss: 0.1557 - Val Acc: 0.9420
2026-04-05 05:50:02,289 - INFO - Epoch 68/100 - Train Loss: 0.1622 - Val Acc: 0.9420
2026-04-05 05:50:02,604 - INFO - Epoch 69/100 - Train Loss: 0.1694 - Val Acc: 0.9420
2026-04-05 05:50:02,921 - INFO - Epoch 70/100 - Train Loss: 0.1522 - Val Acc: 0.9420
2026-04-05 05:50:03,236 - INFO - Epoch 71/100 - Train Loss: 0.1524 - Val Acc: 0.9420
2026-04-05 05:50:03,566 - INFO - Epoch 72/100 - Train Loss: 0.1514 - Val Acc: 0.9420
2026-04-05 05:50:03,892 - INFO - Epoch 73/100 - Train Loss: 0.1548 - Val Acc: 0.9420
2026-04-05 05:50:04,222 - INFO - Epoch 74/100 - Train Loss: 0.1366 - Val Acc: 0.9420
2026-04-05 05:50:04,560 - INFO - Epoch 75/100 - Train Loss: 0.1401 - Val Acc: 0.9420
2026-04-05 05:50:04,893 - INFO - Epoch 76/100 - Train Loss: 0.1663 - Val Acc: 0.9420
2026-04-05 05:50:05,210 - INFO - Epoch 77/100 - Train Loss: 0.1502 - Val Acc: 0.9420
2026-04-05 05:50:05,534 - INFO - Epoch 78/100 - Train Loss: 0.1554 - Val Acc: 0.9420
2026-04-05 05:50:05,859 - INFO - Epoch 79/100 - Train Loss: 0.1386 - Val Acc: 0.9420
2026-04-05 05:50:06,172 - INFO - Epoch 80/100 - Train Loss: 0.1492 - Val Acc: 0.9420
2026-04-05 05:50:06,514 - INFO - Epoch 81/100 - Train Loss: 0.1412 - Val Acc: 0.9420
2026-04-05 05:50:06,843 - INFO - Epoch 82/100 - Train Loss: 0.1309 - Val Acc: 0.9420
2026-04-05 05:50:07,161 - INFO - Epoch 83/100 - Train Loss: 0.1480 - Val Acc: 0.9420
2026-04-05 05:50:07,488 - INFO - Epoch 84/100 - Train Loss: 0.1564 - Val Acc: 0.9420
2026-04-05 05:50:07,813 - INFO - Epoch 85/100 - Train Loss: 0.1458 - Val Acc: 0.9420
2026-04-05 05:50:08,138 - INFO - Epoch 86/100 - Train Loss: 0.1312 - Val Acc: 0.9420
2026-04-05 05:50:08,456 - INFO - Epoch 87/100 - Train Loss: 0.1511 - Val Acc: 0.9275
2026-04-05 05:50:08,771 - INFO - Epoch 88/100 - Train Loss: 0.1349 - Val Acc: 0.9420
2026-04-05 05:50:09,104 - INFO - Epoch 89/100 - Train Loss: 0.1203 - Val Acc: 0.9420
2026-04-05 05:50:09,419 - INFO - Epoch 90/100 - Train Loss: 0.1406 - Val Acc: 0.9420
2026-04-05 05:50:09,750 - INFO - Epoch 91/100 - Train Loss: 0.1310 - Val Acc: 0.9420
2026-04-05 05:50:10,080 - INFO - Epoch 92/100 - Train Loss: 0.1393 - Val Acc: 0.9420
2026-04-05 05:50:10,402 - INFO - Epoch 93/100 - Train Loss: 0.1333 - Val Acc: 0.9420
2026-04-05 05:50:10,715 - INFO - Epoch 94/100 - Train Loss: 0.1298 - Val Acc: 0.9420
2026-04-05 05:50:11,045 - INFO - Epoch 95/100 - Train Loss: 0.1355 - Val Acc: 0.9420
2026-04-05 05:50:11,381 - INFO - Epoch 96/100 - Train Loss: 0.1452 - Val Acc: 0.9420
2026-04-05 05:50:11,695 - INFO - Epoch 97/100 - Train Loss: 0.1240 - Val Acc: 0.9420
2026-04-05 05:50:12,018 - INFO - Epoch 98/100 - Train Loss: 0.1295 - Val Acc: 0.9420
2026-04-05 05:50:12,343 - INFO - Epoch 99/100 - Train Loss: 0.1300 - Val Acc: 0.9420
2026-04-05 05:50:12,660 - INFO - Epoch 100/100 - Train Loss: 0.1230 - Val Acc: 0.9420
2026-04-05 05:50:13,028 - INFO - Fold 10 logically complete. Tensor memory bounds cleared cleanly.
2026-04-05 05:50:13,047 - INFO - ✓ Completed MLP_baseline -> Acc: 0.8928
2026-04-05 05:50:13,047 - INFO -
EXPERIMENT: MLP_SMOTEENN | australian | SMOTE-ENN: True

Australian | MLP | SMOTEENN:   0%|          | 0/10 [00:00<?, ?it/s]

2026-04-05 05:50:13,060 - INFO - Original class distribution: [344 277]
2026-04-05 05:50:13,060 - INFO - Training device bound securely to: cuda
2026-04-05 05:50:13,087 - INFO - After SMOTE-ENN deployment: [344 287]

Fold 1:   0%|          | 0/100 [00:00<?, ?it/s]

2026-04-05 05:50:13,420 - INFO - Epoch 1/100 - Train Loss: 0.5844 - Val Acc: 0.8841
2026-04-05 05:50:13,731 - INFO - Epoch 2/100 - Train Loss: 0.3620 - Val Acc: 0.8841
2026-04-05 05:50:14,041 - INFO - Epoch 3/100 - Train Loss: 0.2449 - Val Acc: 0.8986
2026-04-05 05:50:14,353 - INFO - Epoch 4/100 - Train Loss: 0.2130 - Val Acc: 0.8986
2026-04-05 05:50:14,698 - INFO - Epoch 5/100 - Train Loss: 0.2070 - Val Acc: 0.8986
2026-04-05 05:50:15,030 - INFO - Epoch 6/100 - Train Loss: 0.1905 - Val Acc: 0.8841
2026-04-05 05:50:15,359 - INFO - Epoch 7/100 - Train Loss: 0.1814 - Val Acc: 0.8986
2026-04-05 05:50:15,689 - INFO - Epoch 8/100 - Train Loss: 0.1681 - Val Acc: 0.8986
2026-04-05 05:50:16,003 - INFO - Epoch 9/100 - Train Loss: 0.1618 - Val Acc: 0.8986
2026-04-05 05:50:16,318 - INFO - Epoch 10/100 - Train Loss: 0.1522 - Val Acc: 0.8986
2026-04-05 05:50:16,643 - INFO - Epoch 11/100 - Train Loss: 0.1636 - Val Acc: 0.8986
2026-04-05 05:50:16,954 - INFO - Epoch 12/100 - Train Loss: 0.1555 - Val Acc: 0.8986
2026-04-05 05:50:17,275 - INFO - Epoch 13/100 - Train Loss: 0.1471 - Val Acc: 0.8986
2026-04-05 05:50:17,601 - INFO - Epoch 14/100 - Train Loss: 0.1484 - Val Acc: 0.8986
2026-04-05 05:50:17,914 - INFO - Epoch 15/100 - Train Loss: 0.1435 - Val Acc: 0.8986
2026-04-05 05:50:18,232 - INFO - Epoch 16/100 - Train Loss: 0.1320 - Val Acc: 0.8986
2026-04-05 05:50:18,572 - INFO - Epoch 17/100 - Train Loss: 0.1292 - Val Acc: 0.8986
2026-04-05 05:50:18,897 - INFO - Epoch 18/100 - Train Loss: 0.1309 - Val Acc: 0.8986
2026-04-05 05:50:19,216 - INFO - Epoch 19/100 - Train Loss: 0.1299 - Val Acc: 0.8986
2026-04-05 05:50:19,526 - INFO - Epoch 20/100 - Train Loss: 0.1225 - Val Acc: 0.9130
2026-04-05 05:50:19,837 - INFO - Epoch 21/100 - Train Loss: 0.1184 - Val Acc: 0.8986
2026-04-05 05:50:20,145 - INFO - Epoch 22/100 - Train Loss: 0.1243 - Val Acc: 0.8986
2026-04-05 05:50:20,463 - INFO - Epoch 23/100 - Train Loss: 0.1181 - Val Acc: 0.8986
2026-04-05 05:50:20,777 - INFO - Epoch 24/100 - Train Loss: 0.1281 - Val Acc: 0.8986
2026-04-05 05:50:21,110 - INFO - Epoch 25/100 - Train Loss: 0.1109 - Val Acc: 0.8986
2026-04-05 05:50:21,422 - INFO - Epoch 26/100 - Train Loss: 0.1016 - Val Acc: 0.9130
2026-04-05 05:50:21,734 - INFO - Epoch 27/100 - Train Loss: 0.1095 - Val Acc: 0.9130
2026-04-05 05:50:22,056 - INFO - Epoch 28/100 - Train Loss: 0.1021 - Val Acc: 0.9130
2026-04-05 05:50:22,368 - INFO - Epoch 29/100 - Train Loss: 0.0962 - Val Acc: 0.9275
2026-04-05 05:50:22,690 - INFO - Epoch 30/100 - Train Loss: 0.0925 - Val Acc: 0.9275
2026-04-05 05:50:23,010 - INFO - Epoch 31/100 - Train Loss: 0.0959 - Val Acc: 0.9275
2026-04-05 05:50:23,330 - INFO - Epoch 32/100 - Train Loss: 0.1014 - Val Acc: 0.9130
2026-04-05 05:50:23,644 - INFO - Epoch 33/100 - Train Loss: 0.0949 - Val Acc: 0.9275
2026-04-05 05:50:23,969 - INFO - Epoch 34/100 - Train Loss: 0.0958 - Val Acc: 0.9275
2026-04-05 05:50:24,292 - INFO - Epoch 35/100 - Train Loss: 0.0937 - Val Acc: 0.8986
2026-04-05 05:50:24,629 - INFO - Epoch 36/100 - Train Loss: 0.0982 - Val Acc: 0.8986
2026-04-05 05:50:24,944 - INFO - Epoch 37/100 - Train Loss: 0.0787 - Val Acc: 0.9275
2026-04-05 05:50:25,257 - INFO - Epoch 38/100 - Train Loss: 0.0882 - Val Acc: 0.9275
2026-04-05 05:50:25,565 - INFO - Epoch 39/100 - Train Loss: 0.0811 - Val Acc: 0.9275
2026-04-05 05:50:25,881 - INFO - Epoch 40/100 - Train Loss: 0.0736 - Val Acc: 0.9275
2026-04-05 05:50:26,200 - INFO - Epoch 41/100 - Train Loss: 0.0827 - Val Acc: 0.9275
2026-04-05 05:50:26,513 - INFO - Epoch 42/100 - Train Loss: 0.0897 - Val Acc: 0.9275
2026-04-05 05:50:26,828 - INFO - Epoch 43/100 - Train Loss: 0.0753 - Val Acc: 0.9275
2026-04-05 05:50:27,143 - INFO - Epoch 44/100 - Train Loss: 0.0735 - Val Acc: 0.9275
2026-04-05 05:50:27,457 - INFO - Epoch 45/100 - Train Loss: 0.0689 - Val Acc: 0.9275
2026-04-05 05:50:27,796 - INFO - Epoch 46/100 - Train Loss: 0.0809 - Val Acc: 0.9275
2026-04-05 05:50:28,121 - INFO - Epoch 47/100 - Train Loss: 0.0707 - Val Acc: 0.9275
2026-04-05 05:50:28,448 - INFO - Epoch 48/100 - Train Loss: 0.0773 - Val Acc: 0.9275
2026-04-05 05:50:28,761 - INFO - Epoch 49/100 - Train Loss: 0.0690 - Val Acc: 0.9275
2026-04-05 05:50:29,073 - INFO - Epoch 50/100 - Train Loss: 0.0779 - Val Acc: 0.9275
2026-04-05 05:50:29,386 - INFO - Epoch 51/100 - Train Loss: 0.0705 - Val Acc: 0.9275
2026-04-05 05:50:29,729 - INFO - Epoch 52/100 - Train Loss: 0.0545 - Val Acc: 0.9275
2026-04-05 05:50:30,059 - INFO - Epoch 53/100 - Train Loss: 0.0705 - Val Acc: 0.9275
2026-04-05 05:50:30,376 - INFO - Epoch 54/100 - Train Loss: 0.0749 - Val Acc: 0.9275
2026-04-05 05:50:30,697 - INFO - Epoch 55/100 - Train Loss: 0.0595 - Val Acc: 0.9275
2026-04-05 05:50:31,017 - INFO - Epoch 56/100 - Train Loss: 0.0764 - Val Acc: 0.9275
2026-04-05 05:50:31,327 - INFO - Epoch 57/100 - Train Loss: 0.0612 - Val Acc: 0.9275
2026-04-05 05:50:31,644 - INFO - Epoch 58/100 - Train Loss: 0.0696 - Val Acc: 0.9275
2026-04-05 05:50:31,966 - INFO - Epoch 59/100 - Train Loss: 0.0590 - Val Acc: 0.9275
2026-04-05 05:50:32,286 - INFO - Epoch 60/100 - Train Loss: 0.0727 - Val Acc: 0.9275
2026-04-05 05:50:32,625 - INFO - Epoch 61/100 - Train Loss: 0.0596 - Val Acc: 0.9275
2026-04-05 05:50:32,938 - INFO - Epoch 62/100 - Train Loss: 0.0519 - Val Acc: 0.9275
2026-04-05 05:50:33,252 - INFO - Epoch 63/100 - Train Loss: 0.0605 - Val Acc: 0.9420
2026-04-05 05:50:33,571 - INFO - Epoch 64/100 - Train Loss: 0.0666 - Val Acc: 0.9275
2026-04-05 05:50:33,909 - INFO - Epoch 65/100 - Train Loss: 0.0492 - Val Acc: 0.9275
2026-04-05 05:50:34,240 - INFO - Epoch 66/100 - Train Loss: 0.0578 - Val Acc: 0.9275
2026-04-05 05:50:34,592 - INFO - Epoch 67/100 - Train Loss: 0.0417 - Val Acc: 0.9275
2026-04-05 05:50:34,931 - INFO - Epoch 68/100 - Train Loss: 0.0543 - Val Acc: 0.9275
2026-04-05 05:50:35,260 - INFO - Epoch 69/100 - Train Loss: 0.0454 - Val Acc: 0.9275
2026-04-05 05:50:35,586 - INFO - Epoch 70/100 - Train Loss: 0.0467 - Val Acc: 0.9275
2026-04-05 05:50:35,903 - INFO - Epoch 71/100 - Train Loss: 0.0433 - Val Acc: 0.9275
2026-04-05 05:50:36,232 - INFO - Epoch 72/100 - Train Loss: 0.0414 - Val Acc: 0.9275
2026-04-05 05:50:36,540 - INFO - Epoch 73/100 - Train Loss: 0.0487 - Val Acc: 0.9275
2026-04-05 05:50:36,863 - INFO - Epoch 74/100 - Train Loss: 0.0539 - Val Acc: 0.9275
2026-04-05 05:50:37,187 - INFO - Epoch 75/100 - Train Loss: 0.0519 - Val Acc: 0.9275
2026-04-05 05:50:37,505 - INFO - Epoch 76/100 - Train Loss: 0.0519 - Val Acc: 0.9275
2026-04-05 05:50:37,841 - INFO - Epoch 77/100 - Train Loss: 0.0484 - Val Acc: 0.9275
2026-04-05 05:50:38,165 - INFO - Epoch 78/100 - Train Loss: 0.0413 - Val Acc: 0.9275
2026-04-05 05:50:38,490 - INFO - Epoch 79/100 - Train Loss: 0.0409 - Val Acc: 0.9275
2026-04-05 05:50:38,811 - INFO - Epoch 80/100 - Train Loss: 0.0645 - Val Acc: 0.9275
2026-04-05 05:50:39,142 - INFO - Epoch 81/100 - Train Loss: 0.0522 - Val Acc: 0.9275
2026-04-05 05:50:39,476 - INFO - Epoch 82/100 - Train Loss: 0.0436 - Val Acc: 0.9275
2026-04-05 05:50:39,791 - INFO - Epoch 83/100 - Train Loss: 0.0570 - Val Acc: 0.9420
2026-04-05 05:50:40,112 - INFO - Epoch 84/100 - Train Loss: 0.0445 - Val Acc: 0.9275
2026-04-05 05:50:40,434 - INFO - Epoch 85/100 - Train Loss: 0.0411 - Val Acc: 0.9275
2026-04-05 05:50:40,764 - INFO - Epoch 86/100 - Train Loss: 0.0378 - Val Acc: 0.9420
2026-04-05 05:50:41,080 - INFO - Epoch 87/100 - Train Loss: 0.0446 - Val Acc: 0.9420
2026-04-05 05:50:41,401 - INFO - Epoch 88/100 - Train Loss: 0.0424 - Val Acc: 0.9420
2026-04-05 05:50:41,734 - INFO - Epoch 89/100 - Train Loss: 0.0382 - Val Acc: 0.9420
2026-04-05 05:50:42,057 - INFO - Epoch 90/100 - Train Loss: 0.0401 - Val Acc: 0.9420
2026-04-05 05:50:42,383 - INFO - Epoch 91/100 - Train Loss: 0.0505 - Val Acc: 0.9420
2026-04-05 05:50:42,712 - INFO - Epoch 92/100 - Train Loss: 0.0566 - Val Acc: 0.9275
2026-04-05 05:50:43,031 - INFO - Epoch 93/100 - Train Loss: 0.0590 - Val Acc: 0.9275
2026-04-05 05:50:43,351 - INFO - Epoch 94/100 - Train Loss: 0.0403 - Val Acc: 0.9275
2026-04-05 05:50:43,673 - INFO - Epoch 95/100 - Train Loss: 0.0337 - Val Acc: 0.9275
2026-04-05 05:50:43,999 - INFO - Epoch 96/100 - Train Loss: 0.0431 - Val Acc: 0.9275
2026-04-05 05:50:44,314 - INFO - Epoch 97/100 - Train Loss: 0.0370 - Val Acc: 0.9275
2026-04-05 05:50:44,671 - INFO - Epoch 98/100 - Train Loss: 0.0389 - Val Acc: 0.9420
2026-04-05 05:50:44,990 - INFO - Epoch 99/100 - Train Loss: 0.0395 - Val Acc: 0.9420
2026-04-05 05:50:45,316 - INFO - Epoch 100/100 - Train Loss: 0.0341 - Val Acc: 0.9275
2026-04-05 05:50:45,679 - INFO - Fold 1 logically complete. Tensor memory bounds cleared cleanly.
2026-04-05 05:50:45,684 - INFO - Original class distribution: [344 277]
2026-04-05 05:50:45,684 - INFO - Training device bound securely to: cuda
2026-04-05 05:50:45,714 - INFO - After SMOTE-ENN deployment: [344 292]

Fold 2:   0%|          | 0/100 [00:00<?, ?it/s]

2026-04-05 05:50:46,049 - INFO - Epoch 1/100 - Train Loss: 0.5806 - Val Acc: 0.7971
2026-04-05 05:50:46,376 - INFO - Epoch 2/100 - Train Loss: 0.3404 - Val Acc: 0.7971
2026-04-05 05:50:46,702 - INFO - Epoch 3/100 - Train Loss: 0.2385 - Val Acc: 0.7971
2026-04-05 05:50:47,019 - INFO - Epoch 4/100 - Train Loss: 0.2128 - Val Acc: 0.8406
2026-04-05 05:50:47,345 - INFO - Epoch 5/100 - Train Loss: 0.2049 - Val Acc: 0.8551
2026-04-05 05:50:47,676 - INFO - Epoch 6/100 - Train Loss: 0.1976 - Val Acc: 0.8551
2026-04-05 05:50:48,003 - INFO - Epoch 7/100 - Train Loss: 0.1948 - Val Acc: 0.8841
2026-04-05 05:50:48,317 - INFO - Epoch 8/100 - Train Loss: 0.1781 - Val Acc: 0.8551
2026-04-05 05:50:48,639 - INFO - Epoch 9/100 - Train Loss: 0.1799 - Val Acc: 0.8986
2026-04-05 05:50:48,962 - INFO - Epoch 10/100 - Train Loss: 0.1674 - Val Acc: 0.8841
2026-04-05 05:50:49,279 - INFO - Epoch 11/100 - Train Loss: 0.1547 - Val Acc: 0.8841
2026-04-05 05:50:49,594 - INFO - Epoch 12/100 - Train Loss: 0.1608 - Val Acc: 0.9130
2026-04-05 05:50:49,908 - INFO - Epoch 13/100 - Train Loss: 0.1492 - Val Acc: 0.8696
2026-04-05 05:50:50,236 - INFO - Epoch 14/100 - Train Loss: 0.1544 - Val Acc: 0.8841
2026-04-05 05:50:50,557 - INFO - Epoch 15/100 - Train Loss: 0.1436 - Val Acc: 0.8841
2026-04-05 05:50:50,890 - INFO - Epoch 16/100 - Train Loss: 0.1354 - Val Acc: 0.8696
2026-04-05 05:50:51,211 - INFO - Epoch 17/100 - Train Loss: 0.1229 - Val Acc: 0.8841
2026-04-05 05:50:51,540 - INFO - Epoch 18/100 - Train Loss: 0.1301 - Val Acc: 0.8696
2026-04-05 05:50:51,871 - INFO - Epoch 19/100 - Train Loss: 0.1310 - Val Acc: 0.8841
2026-04-05 05:50:52,186 - INFO - Epoch 20/100 - Train Loss: 0.1274 - Val Acc: 0.8696
2026-04-05 05:50:52,507 - INFO - Epoch 21/100 - Train Loss: 0.1208 - Val Acc: 0.8551
2026-04-05 05:50:52,823 - INFO - Epoch 22/100 - Train Loss: 0.1106 - Val Acc: 0.8696
2026-04-05 05:50:53,139 - INFO - Epoch 23/100 - Train Loss: 0.1220 - Val Acc: 0.8696
2026-04-05 05:50:53,455 - INFO - Epoch 24/100 - Train Loss: 0.1221 - Val Acc: 0.8696
2026-04-05 05:50:53,788 - INFO - Epoch 25/100 - Train Loss: 0.1251 - Val Acc: 0.8696
2026-04-05 05:50:54,097 - INFO - Epoch 26/100 - Train Loss: 0.1114 - Val Acc: 0.8696
2026-04-05 05:50:54,424 - INFO - Epoch 27/100 - Train Loss: 0.1118 - Val Acc: 0.8696
2026-04-05 05:50:54,771 - INFO - Epoch 28/100 - Train Loss: 0.1090 - Val Acc: 0.8696
2026-04-05 05:50:55,089 - INFO - Epoch 29/100 - Train Loss: 0.0989 - Val Acc: 0.8696
2026-04-05 05:50:55,404 - INFO - Epoch 30/100 - Train Loss: 0.1047 - Val Acc: 0.8696
2026-04-05 05:50:55,726 - INFO - Epoch 31/100 - Train Loss: 0.0942 - Val Acc: 0.8551
2026-04-05 05:50:56,036 - INFO - Epoch 32/100 - Train Loss: 0.0959 - Val Acc: 0.8696
2026-04-05 05:50:56,357 - INFO - Epoch 33/100 - Train Loss: 0.1113 - Val Acc: 0.8551
2026-04-05 05:50:56,679 - INFO - Epoch 34/100 - Train Loss: 0.0988 - Val Acc: 0.8696
2026-04-05 05:50:56,996 - INFO - Epoch 35/100 - Train Loss: 0.0909 - Val Acc: 0.8696
2026-04-05 05:50:57,313 - INFO - Epoch 36/100 - Train Loss: 0.0848 - Val Acc: 0.8696
2026-04-05 05:50:57,626 - INFO - Epoch 37/100 - Train Loss: 0.0922 - Val Acc: 0.8551
2026-04-05 05:50:57,948 - INFO - Epoch 38/100 - Train Loss: 0.0946 - Val Acc: 0.8406
2026-04-05 05:50:58,267 - INFO - Epoch 39/100 - Train Loss: 0.0821 - Val Acc: 0.8406
2026-04-05 05:50:58,576 - INFO - Epoch 40/100 - Train Loss: 0.1066 - Val Acc: 0.8551
2026-04-05 05:50:58,881 - INFO - Epoch 41/100 - Train Loss: 0.0770 - Val Acc: 0.8406
2026-04-05 05:50:59,189 - INFO - Epoch 42/100 - Train Loss: 0.0894 - Val Acc: 0.8696
2026-04-05 05:50:59,512 - INFO - Epoch 43/100 - Train Loss: 0.0740 - Val Acc: 0.8406
2026-04-05 05:50:59,844 - INFO - Epoch 44/100 - Train Loss: 0.0845 - Val Acc: 0.8551
2026-04-05 05:51:00,164 - INFO - Epoch 45/100 - Train Loss: 0.0650 - Val Acc: 0.8551
2026-04-05 05:51:00,476 - INFO - Epoch 46/100 - Train Loss: 0.0825 - Val Acc: 0.8551
2026-04-05 05:51:00,789 - INFO - Epoch 47/100 - Train Loss: 0.0871 - Val Acc: 0.8696
2026-04-05 05:51:01,108 - INFO - Epoch 48/100 - Train Loss: 0.0805 - Val Acc: 0.8406
2026-04-05 05:51:01,414 - INFO - Epoch 49/100 - Train Loss: 0.0679 - Val Acc: 0.8406
2026-04-05 05:51:01,728 - INFO - Epoch 50/100 - Train Loss: 0.0662 - Val Acc: 0.8406
2026-04-05 05:51:02,041 - INFO - Epoch 51/100 - Train Loss: 0.0685 - Val Acc: 0.8551
2026-04-05 05:51:02,360 - INFO - Epoch 52/100 - Train Loss: 0.0733 - Val Acc: 0.8551
2026-04-05 05:51:02,682 - INFO - Epoch 53/100 - Train Loss: 0.0726 - Val Acc: 0.8406
2026-04-05 05:51:03,015 - INFO - Epoch 54/100 - Train Loss: 0.0589 - Val Acc: 0.8551
2026-04-05 05:51:03,330 - INFO - Epoch 55/100 - Train Loss: 0.0628 - Val Acc: 0.8696
2026-04-05 05:51:03,645 - INFO - Epoch 56/100 - Train Loss: 0.0551 - Val Acc: 0.8696
2026-04-05 05:51:03,968 - INFO - Epoch 57/100 - Train Loss: 0.0628 - Val Acc: 0.8551
2026-04-05 05:51:04,303 - INFO - Epoch 58/100 - Train Loss: 0.0752 - Val Acc: 0.8406
2026-04-05 05:51:04,647 - INFO - Epoch 59/100 - Train Loss: 0.0603 - Val Acc: 0.8551
2026-04-05 05:51:04,964 - INFO - Epoch 60/100 - Train Loss: 0.0700 - Val Acc: 0.8551
2026-04-05 05:51:05,281 - INFO - Epoch 61/100 - Train Loss: 0.0680 - Val Acc: 0.8406
2026-04-05 05:51:05,606 - INFO - Epoch 62/100 - Train Loss: 0.0528 - Val Acc: 0.8406
2026-04-05 05:51:05,946 - INFO - Epoch 63/100 - Train Loss: 0.0553 - Val Acc: 0.8406
2026-04-05 05:51:06,268 - INFO - Epoch 64/100 - Train Loss: 0.0539 - Val Acc: 0.8406
2026-04-05 05:51:06,596 - INFO - Epoch 65/100 - Train Loss: 0.0612 - Val Acc: 0.8406
2026-04-05 05:51:06,917 - INFO - Epoch 66/100 - Train Loss: 0.0555 - Val Acc: 0.8551
2026-04-05 05:51:07,233 - INFO - Epoch 67/100 - Train Loss: 0.0653 - Val Acc: 0.8696
2026-04-05 05:51:07,553 - INFO - Epoch 68/100 - Train Loss: 0.0565 - Val Acc: 0.8551
2026-04-05 05:51:07,883 - INFO - Epoch 69/100 - Train Loss: 0.0709 - Val Acc: 0.8696
2026-04-05 05:51:08,199 - INFO - Epoch 70/100 - Train Loss: 0.0545 - Val Acc: 0.8551
2026-04-05 05:51:08,522 - INFO - Epoch 71/100 - Train Loss: 0.0579 - Val Acc: 0.8551
2026-04-05 05:51:08,833 - INFO - Epoch 72/100 - Train Loss: 0.0504 - Val Acc: 0.8551
2026-04-05 05:51:09,148 - INFO - Epoch 73/100 - Train Loss: 0.0511 - Val Acc: 0.8551
2026-04-05 05:51:09,468 - INFO - Epoch 74/100 - Train Loss: 0.0597 - Val Acc: 0.8261
2026-04-05 05:51:09,796 - INFO - Epoch 75/100 - Train Loss: 0.0631 - Val Acc: 0.8406
2026-04-05 05:51:10,125 - INFO - Epoch 76/100 - Train Loss: 0.0476 - Val Acc: 0.8406
2026-04-05 05:51:10,448 - INFO - Epoch 77/100 - Train Loss: 0.0653 - Val Acc: 0.8406
2026-04-05 05:51:10,761 - INFO - Epoch 78/100 - Train Loss: 0.0530 - Val Acc: 0.8406
2026-04-05 05:51:11,072 - INFO - Epoch 79/100 - Train Loss: 0.0635 - Val Acc: 0.8406
2026-04-05 05:51:11,392 - INFO - Epoch 80/100 - Train Loss: 0.0477 - Val Acc: 0.8261
2026-04-05 05:51:11,703 - INFO - Epoch 81/100 - Train Loss: 0.0431 - Val Acc: 0.8551
2026-04-05 05:51:12,026 - INFO - Epoch 82/100 - Train Loss: 0.0382 - Val Acc: 0.8551
2026-04-05 05:51:12,341 - INFO - Epoch 83/100 - Train Loss: 0.0362 - Val Acc: 0.8406
2026-04-05 05:51:12,670 - INFO - Epoch 84/100 - Train Loss: 0.0452 - Val Acc: 0.8406
2026-04-05 05:51:12,995 - INFO - Epoch 85/100 - Train Loss: 0.0388 - Val Acc: 0.8261
2026-04-05 05:51:13,316 - INFO - Epoch 86/100 - Train Loss: 0.0377 - Val Acc: 0.8261
2026-04-05 05:51:13,630 - INFO - Epoch 87/100 - Train Loss: 0.0404 - Val Acc: 0.8406
2026-04-05 05:51:13,956 - INFO - Epoch 88/100 - Train Loss: 0.0433 - Val Acc: 0.8406
2026-04-05 05:51:14,278 - INFO - Epoch 89/100 - Train Loss: 0.0604 - Val Acc: 0.8551
2026-04-05 05:51:14,621 - INFO - Epoch 90/100 - Train Loss: 0.0450 - Val Acc: 0.8406
2026-04-05 05:51:14,947 - INFO - Epoch 91/100 - Train Loss: 0.0628 - Val Acc: 0.8406
2026-04-05 05:51:15,272 - INFO - Epoch 92/100 - Train Loss: 0.0403 - Val Acc: 0.8551
2026-04-05 05:51:15,589 - INFO - Epoch 93/100 - Train Loss: 0.0321 - Val Acc: 0.8551
2026-04-05 05:51:15,900 - INFO - Epoch 94/100 - Train Loss: 0.0342 - Val Acc: 0.8406
2026-04-05 05:51:16,211 - INFO - Epoch 95/100 - Train Loss: 0.0479 - Val Acc: 0.8261
2026-04-05 05:51:16,526 - INFO - Epoch 96/100 - Train Loss: 0.0367 - Val Acc: 0.8261
2026-04-05 05:51:16,854 - INFO - Epoch 97/100 - Train Loss: 0.0347 - Val Acc: 0.8261
2026-04-05 05:51:17,182 - INFO - Epoch 98/100 - Train Loss: 0.0391 - Val Acc: 0.8406
2026-04-05 05:51:17,512 - INFO - Epoch 99/100 - Train Loss: 0.0433 - Val Acc: 0.8261
2026-04-05 05:51:17,840 - INFO - Epoch 100/100 - Train Loss: 0.0390 - Val Acc: 0.8261
2026-04-05 05:51:18,208 - INFO - Fold 2 logically complete. Tensor memory bounds cleared cleanly.
2026-04-05 05:51:18,212 - INFO - Original class distribution: [344 277]
2026-04-05 05:51:18,213 - INFO - Training device bound securely to: cuda
2026-04-05 05:51:18,241 - INFO - After SMOTE-ENN deployment: [344 290]

Fold 3:   0%|          | 0/100 [00:00<?, ?it/s]

2026-04-05 05:51:18,599 - INFO - Epoch 1/100 - Train Loss: 0.5840 - Val Acc: 0.9130
2026-04-05 05:51:18,927 - INFO - Epoch 2/100 - Train Loss: 0.3406 - Val Acc: 0.9275
2026-04-05 05:51:19,244 - INFO - Epoch 3/100 - Train Loss: 0.2310 - Val Acc: 0.9275
2026-04-05 05:51:19,568 - INFO - Epoch 4/100 - Train Loss: 0.2074 - Val Acc: 0.9275
2026-04-05 05:51:19,894 - INFO - Epoch 5/100 - Train Loss: 0.1884 - Val Acc: 0.9130
2026-04-05 05:51:20,211 - INFO - Epoch 6/100 - Train Loss: 0.1799 - Val Acc: 0.9130
2026-04-05 05:51:20,534 - INFO - Epoch 7/100 - Train Loss: 0.1587 - Val Acc: 0.9130
2026-04-05 05:51:20,846 - INFO - Epoch 8/100 - Train Loss: 0.1610 - Val Acc: 0.9130
2026-04-05 05:51:21,155 - INFO - Epoch 9/100 - Train Loss: 0.1687 - Val Acc: 0.9130
2026-04-05 05:51:21,473 - INFO - Epoch 10/100 - Train Loss: 0.1495 - Val Acc: 0.9130
2026-04-05 05:51:21,798 - INFO - Epoch 11/100 - Train Loss: 0.1531 - Val Acc: 0.9130
2026-04-05 05:51:22,124 - INFO - Epoch 12/100 - Train Loss: 0.1392 - Val Acc: 0.9130
2026-04-05 05:51:22,460 - INFO - Epoch 13/100 - Train Loss: 0.1391 - Val Acc: 0.9130
2026-04-05 05:51:22,784 - INFO - Epoch 14/100 - Train Loss: 0.1353 - Val Acc: 0.9130
2026-04-05 05:51:23,101 - INFO - Epoch 15/100 - Train Loss: 0.1339 - Val Acc: 0.9130
2026-04-05 05:51:23,427 - INFO - Epoch 16/100 - Train Loss: 0.1331 - Val Acc: 0.9130
2026-04-05 05:51:23,757 - INFO - Epoch 17/100 - Train Loss: 0.1176 - Val Acc: 0.9130
2026-04-05 05:51:24,074 - INFO - Epoch 18/100 - Train Loss: 0.1213 - Val Acc: 0.9130
2026-04-05 05:51:24,411 - INFO - Epoch 19/100 - Train Loss: 0.1252 - Val Acc: 0.9275
2026-04-05 05:51:24,759 - INFO - Epoch 20/100 - Train Loss: 0.1176 - Val Acc: 0.9130
2026-04-05 05:51:25,076 - INFO - Epoch 21/100 - Train Loss: 0.1156 - Val Acc: 0.9130
2026-04-05 05:51:25,406 - INFO - Epoch 22/100 - Train Loss: 0.1173 - Val Acc: 0.9130
2026-04-05 05:51:25,717 - INFO - Epoch 23/100 - Train Loss: 0.1031 - Val Acc: 0.9275
2026-04-05 05:51:26,029 - INFO - Epoch 24/100 - Train Loss: 0.0949 - Val Acc: 0.9130
2026-04-05 05:51:26,341 - INFO - Epoch 25/100 - Train Loss: 0.1041 - Val Acc: 0.9275
2026-04-05 05:51:26,677 - INFO - Epoch 26/100 - Train Loss: 0.1067 - Val Acc: 0.9275
2026-04-05 05:51:26,993 - INFO - Epoch 27/100 - Train Loss: 0.1016 - Val Acc: 0.9275
2026-04-05 05:51:27,307 - INFO - Epoch 28/100 - Train Loss: 0.0912 - Val Acc: 0.9130
2026-04-05 05:51:27,624 - INFO - Epoch 29/100 - Train Loss: 0.0904 - Val Acc: 0.9130
2026-04-05 05:51:27,948 - INFO - Epoch 30/100 - Train Loss: 0.0913 - Val Acc: 0.9275
2026-04-05 05:51:28,266 - INFO - Epoch 31/100 - Train Loss: 0.0880 - Val Acc: 0.9275
2026-04-05 05:51:28,580 - INFO - Epoch 32/100 - Train Loss: 0.0840 - Val Acc: 0.9275
2026-04-05 05:51:28,900 - INFO - Epoch 33/100 - Train Loss: 0.0893 - Val Acc: 0.9275
2026-04-05 05:51:29,217 - INFO - Epoch 34/100 - Train Loss: 0.0838 - Val Acc: 0.9275
2026-04-05 05:51:29,533 - INFO - Epoch 35/100 - Train Loss: 0.0762 - Val Acc: 0.9275
2026-04-05 05:51:29,861 - INFO - Epoch 36/100 - Train Loss: 0.0751 - Val Acc: 0.9275
2026-04-05 05:51:30,172 - INFO - Epoch 37/100 - Train Loss: 0.0817 - Val Acc: 0.9275
2026-04-05 05:51:30,478 - INFO - Epoch 38/100 - Train Loss: 0.0745 - Val Acc: 0.9275
2026-04-05 05:51:30,801 - INFO - Epoch 39/100 - Train Loss: 0.0799 - Val Acc: 0.9275
2026-04-05 05:51:31,119 - INFO - Epoch 40/100 - Train Loss: 0.0830 - Val Acc: 0.9275
2026-04-05 05:51:31,431 - INFO - Epoch 41/100 - Train Loss: 0.0754 - Val Acc: 0.9275
2026-04-05 05:51:31,746 - INFO - Epoch 42/100 - Train Loss: 0.0676 - Val Acc: 0.9275
2026-04-05 05:51:32,056 - INFO - Epoch 43/100 - Train Loss: 0.0714 - Val Acc: 0.9275
2026-04-05 05:51:32,375 - INFO - Epoch 44/100 - Train Loss: 0.0818 - Val Acc: 0.9420
2026-04-05 05:51:32,713 - INFO - Epoch 45/100 - Train Loss: 0.0703 - Val Acc: 0.9275
2026-04-05 05:51:33,031 - INFO - Epoch 46/100 - Train Loss: 0.0704 - Val Acc: 0.9275
2026-04-05 05:51:33,357 - INFO - Epoch 47/100 - Train Loss: 0.0652 - Val Acc: 0.9130
2026-04-05 05:51:33,684 - INFO - Epoch 48/100 - Train Loss: 0.0644 - Val Acc: 0.9275
2026-04-05 05:51:34,007 - INFO - Epoch 49/100 - Train Loss: 0.0586 - Val Acc: 0.9275
2026-04-05 05:51:34,327 - INFO - Epoch 50/100 - Train Loss: 0.0632 - Val Acc: 0.9275
2026-04-05 05:51:34,670 - INFO - Epoch 51/100 - Train Loss: 0.0580 - Val Acc: 0.9275
2026-04-05 05:51:34,994 - INFO - Epoch 52/100 - Train Loss: 0.0589 - Val Acc: 0.9275
2026-04-05 05:51:35,332 - INFO - Epoch 53/100 - Train Loss: 0.0647 - Val Acc: 0.9275
2026-04-05 05:51:35,648 - INFO - Epoch 54/100 - Train Loss: 0.0634 - Val Acc: 0.9130
2026-04-05 05:51:35,980 - INFO - Epoch 55/100 - Train Loss: 0.0583 - Val Acc: 0.9275
2026-04-05 05:51:36,312 - INFO - Epoch 56/100 - Train Loss: 0.0548 - Val Acc: 0.9275
2026-04-05 05:51:36,630 - INFO - Epoch 57/100 - Train Loss: 0.0600 - Val Acc: 0.9275
2026-04-05 05:51:36,946 - INFO - Epoch 58/100 - Train Loss: 0.0639 - Val Acc: 0.9275
2026-04-05 05:51:37,261 - INFO - Epoch 59/100 - Train Loss: 0.0666 - Val Acc: 0.9275
2026-04-05 05:51:37,587 - INFO - Epoch 60/100 - Train Loss: 0.0559 - Val Acc: 0.9275
2026-04-05 05:51:37,937 - INFO - Epoch 61/100 - Train Loss: 0.0536 - Val Acc: 0.9420
2026-04-05 05:51:38,304 - INFO - Epoch 62/100 - Train Loss: 0.0516 - Val Acc: 0.9275
2026-04-05 05:51:38,637 - INFO - Epoch 63/100 - Train Loss: 0.0556 - Val Acc: 0.9275
2026-04-05 05:51:38,960 - INFO - Epoch 64/100 - Train Loss: 0.0663 - Val Acc: 0.9420
2026-04-05 05:51:39,281 - INFO - Epoch 65/100 - Train Loss: 0.0479 - Val Acc: 0.9420
2026-04-05 05:51:39,596 - INFO - Epoch 66/100 - Train Loss: 0.0471 - Val Acc: 0.9275
2026-04-05 05:51:39,927 - INFO - Epoch 67/100 - Train Loss: 0.0425 - Val Acc: 0.9275
2026-04-05 05:51:40,250 - INFO - Epoch 68/100 - Train Loss: 0.0543 - Val Acc: 0.9275
2026-04-05 05:51:40,562 - INFO - Epoch 69/100 - Train Loss: 0.0425 - Val Acc: 0.9275
2026-04-05 05:51:40,880 - INFO - Epoch 70/100 - Train Loss: 0.0423 - Val Acc: 0.9130
2026-04-05 05:51:41,200 - INFO - Epoch 71/100 - Train Loss: 0.0427 - Val Acc: 0.9275
2026-04-05 05:51:41,523 - INFO - Epoch 72/100 - Train Loss: 0.0566 - Val Acc: 0.9275
2026-04-05 05:51:41,868 - INFO - Epoch 73/100 - Train Loss: 0.0461 - Val Acc: 0.9275
2026-04-05 05:51:42,189 - INFO - Epoch 74/100 - Train Loss: 0.0458 - Val Acc: 0.9275
2026-04-05 05:51:42,514 - INFO - Epoch 75/100 - Train Loss: 0.0463 - Val Acc: 0.9275
2026-04-05 05:51:42,853 - INFO - Epoch 76/100 - Train Loss: 0.0370 - Val Acc: 0.9275
2026-04-05 05:51:43,173 - INFO - Epoch 77/100 - Train Loss: 0.0443 - Val Acc: 0.9275
2026-04-05 05:51:43,489 - INFO - Epoch 78/100 - Train Loss: 0.0451 - Val Acc: 0.9275
2026-04-05 05:51:43,816 - INFO - Epoch 79/100 - Train Loss: 0.0456 - Val Acc: 0.9275
2026-04-05 05:51:44,147 - INFO - Epoch 80/100 - Train Loss: 0.0489 - Val Acc: 0.9275
2026-04-05 05:51:44,482 - INFO - Epoch 81/100 - Train Loss: 0.0382 - Val Acc: 0.9275
2026-04-05 05:51:44,837 - INFO - Epoch 82/100 - Train Loss: 0.0422 - Val Acc: 0.9275
2026-04-05 05:51:45,164 - INFO - Epoch 83/100 - Train Loss: 0.0364 - Val Acc: 0.9275
2026-04-05 05:51:45,476 - INFO - Epoch 84/100 - Train Loss: 0.0396 - Val Acc: 0.9275
2026-04-05 05:51:45,804 - INFO - Epoch 85/100 - Train Loss: 0.0374 - Val Acc: 0.9275
2026-04-05 05:51:46,131 - INFO - Epoch 86/100 - Train Loss: 0.0287 - Val Acc: 0.9130
2026-04-05 05:51:46,452 - INFO - Epoch 87/100 - Train Loss: 0.0353 - Val Acc: 0.9275
2026-04-05 05:51:46,775 - INFO - Epoch 88/100 - Train Loss: 0.0465 - Val Acc: 0.9275
2026-04-05 05:51:47,094 - INFO - Epoch 89/100 - Train Loss: 0.0380 - Val Acc: 0.9275
2026-04-05 05:51:47,417 - INFO - Epoch 90/100 - Train Loss: 0.0394 - Val Acc: 0.9275
2026-04-05 05:51:47,742 - INFO - Epoch 91/100 - Train Loss: 0.0418 - Val Acc: 0.9275
2026-04-05 05:51:48,064 - INFO - Epoch 92/100 - Train Loss: 0.0379 - Val Acc: 0.9275
2026-04-05 05:51:48,382 - INFO - Epoch 93/100 - Train Loss: 0.0411 - Val Acc: 0.9275
2026-04-05 05:51:48,708 - INFO - Epoch 94/100 - Train Loss: 0.0305 - Val Acc: 0.9275
2026-04-05 05:51:49,028 - INFO - Epoch 95/100 - Train Loss: 0.0464 - Val Acc: 0.9275
2026-04-05 05:51:49,357 - INFO - Epoch 96/100 - Train Loss: 0.0320 - Val Acc: 0.9275
2026-04-05 05:51:49,671 - INFO - Epoch 97/100 - Train Loss: 0.0289 - Val Acc: 0.9275
2026-04-05 05:51:49,984 - INFO - Epoch 98/100 - Train Loss: 0.0250 - Val Acc: 0.9275
2026-04-05 05:51:50,305 - INFO - Epoch 99/100 - Train Loss: 0.0248 - Val Acc: 0.9275
2026-04-05 05:51:50,633 - INFO - Epoch 100/100 - Train Loss: 0.0321 - Val Acc: 0.9275
2026-04-05 05:51:50,996 - INFO - Fold 3 logically complete. Tensor memory bounds cleared cleanly.
2026-04-05 05:51:51,000 - INFO - Original class distribution: [345 276]
2026-04-05 05:51:51,001 - INFO - Training device bound securely to: cuda
2026-04-05 05:51:51,030 - INFO - After SMOTE-ENN deployment: [345 299]

Fold 4:   0%|          | 0/100 [00:00<?, ?it/s]

2026-04-05 05:51:51,376 - INFO - Epoch 1/100 - Train Loss: 0.5898 - Val Acc: 0.7826
2026-04-05 05:51:51,707 - INFO - Epoch 2/100 - Train Loss: 0.3588 - Val Acc: 0.7971
2026-04-05 05:51:52,034 - INFO - Epoch 3/100 - Train Loss: 0.2395 - Val Acc: 0.7971
2026-04-05 05:51:52,360 - INFO - Epoch 4/100 - Train Loss: 0.2019 - Val Acc: 0.7971
2026-04-05 05:51:52,695 - INFO - Epoch 5/100 - Train Loss: 0.2005 - Val Acc: 0.7826
2026-04-05 05:51:53,030 - INFO - Epoch 6/100 - Train Loss: 0.1925 - Val Acc: 0.7826
2026-04-05 05:51:53,346 - INFO - Epoch 7/100 - Train Loss: 0.1756 - Val Acc: 0.7826
2026-04-05 05:51:53,664 - INFO - Epoch 8/100 - Train Loss: 0.1751 - Val Acc: 0.7826
2026-04-05 05:51:53,983 - INFO - Epoch 9/100 - Train Loss: 0.1721 - Val Acc: 0.7971
2026-04-05 05:51:54,319 - INFO - Epoch 10/100 - Train Loss: 0.1653 - Val Acc: 0.7826
2026-04-05 05:51:54,670 - INFO - Epoch 11/100 - Train Loss: 0.1513 - Val Acc: 0.7826
2026-04-05 05:51:54,996 - INFO - Epoch 12/100 - Train Loss: 0.1517 - Val Acc: 0.7826
2026-04-05 05:51:55,320 - INFO - Epoch 13/100 - Train Loss: 0.1440 - Val Acc: 0.7826
2026-04-05 05:51:55,642 - INFO - Epoch 14/100 - Train Loss: 0.1477 - Val Acc: 0.7826
2026-04-05 05:51:55,961 - INFO - Epoch 15/100 - Train Loss: 0.1439 - Val Acc: 0.8116
2026-04-05 05:51:56,275 - INFO - Epoch 16/100 - Train Loss: 0.1503 - Val Acc: 0.7971
2026-04-05 05:51:56,595 - INFO - Epoch 17/100 - Train Loss: 0.1326 - Val Acc: 0.7971
2026-04-05 05:51:56,914 - INFO - Epoch 18/100 - Train Loss: 0.1333 - Val Acc: 0.7826
2026-04-05 05:51:57,241 - INFO - Epoch 19/100 - Train Loss: 0.1362 - Val Acc: 0.8116
2026-04-05 05:51:57,563 - INFO - Epoch 20/100 - Train Loss: 0.1208 - Val Acc: 0.7971
2026-04-05 05:51:57,890 - INFO - Epoch 21/100 - Train Loss: 0.1302 - Val Acc: 0.7826
2026-04-05 05:51:58,211 - INFO - Epoch 22/100 - Train Loss: 0.1104 - Val Acc: 0.8116
2026-04-05 05:51:58,531 - INFO - Epoch 23/100 - Train Loss: 0.1123 - Val Acc: 0.7971
2026-04-05 05:51:58,874 - INFO - Epoch 24/100 - Train Loss: 0.1270 - Val Acc: 0.8116
2026-04-05 05:51:59,203 - INFO - Epoch 25/100 - Train Loss: 0.1061 - Val Acc: 0.7826
2026-04-05 05:51:59,530 - INFO - Epoch 26/100 - Train Loss: 0.1213 - Val Acc: 0.7681
2026-04-05 05:51:59,869 - INFO - Epoch 27/100 - Train Loss: 0.1034 - Val Acc: 0.8116
2026-04-05 05:52:00,202 - INFO - Epoch 28/100 - Train Loss: 0.1130 - Val Acc: 0.7971
2026-04-05 05:52:00,527 - INFO - Epoch 29/100 - Train Loss: 0.1025 - Val Acc: 0.7971
2026-04-05 05:52:00,849 - INFO - Epoch 30/100 - Train Loss: 0.0983 - Val Acc: 0.7826
2026-04-05 05:52:01,180 - INFO - Epoch 31/100 - Train Loss: 0.1001 - Val Acc: 0.7826
2026-04-05 05:52:01,493 - INFO - Epoch 32/100 - Train Loss: 0.0891 - Val Acc: 0.7971
2026-04-05 05:52:01,817 - INFO - Epoch 33/100 - Train Loss: 0.0944 - Val Acc: 0.7971
2026-04-05 05:52:02,145 - INFO - Epoch 34/100 - Train Loss: 0.0864 - Val Acc: 0.7971
2026-04-05 05:52:02,473 - INFO - Epoch 35/100 - Train Loss: 0.0946 - Val Acc: 0.7826
2026-04-05 05:52:02,809 - INFO - Epoch 36/100 - Train Loss: 0.0945 - Val Acc: 0.7971
2026-04-05 05:52:03,140 - INFO - Epoch 37/100 - Train Loss: 0.0853 - Val Acc: 0.7971
2026-04-05 05:52:03,460 - INFO - Epoch 38/100 - Train Loss: 0.0776 - Val Acc: 0.7971
2026-04-05 05:52:03,791 - INFO - Epoch 39/100 - Train Loss: 0.0976 - Val Acc: 0.7826
2026-04-05 05:52:04,127 - INFO - Epoch 40/100 - Train Loss: 0.0887 - Val Acc: 0.7826
2026-04-05 05:52:04,454 - INFO - Epoch 41/100 - Train Loss: 0.0747 - Val Acc: 0.7971
2026-04-05 05:52:04,824 - INFO - Epoch 42/100 - Train Loss: 0.0832 - Val Acc: 0.7826
2026-04-05 05:52:05,156 - INFO - Epoch 43/100 - Train Loss: 0.0897 - Val Acc: 0.7971
2026-04-05 05:52:05,487 - INFO - Epoch 44/100 - Train Loss: 0.0833 - Val Acc: 0.7826
2026-04-05 05:52:05,820 - INFO - Epoch 45/100 - Train Loss: 0.0703 - Val Acc: 0.7826
2026-04-05 05:52:06,142 - INFO - Epoch 46/100 - Train Loss: 0.0784 - Val Acc: 0.7826
2026-04-05 05:52:06,461 - INFO - Epoch 47/100 - Train Loss: 0.0738 - Val Acc: 0.7826
2026-04-05 05:52:06,787 - INFO - Epoch 48/100 - Train Loss: 0.0733 - Val Acc: 0.7826
2026-04-05 05:52:07,128 - INFO - Epoch 49/100 - Train Loss: 0.0718 - Val Acc: 0.7826
2026-04-05 05:52:07,456 - INFO - Epoch 50/100 - Train Loss: 0.0778 - Val Acc: 0.7826
2026-04-05 05:52:07,784 - INFO - Epoch 51/100 - Train Loss: 0.0761 - Val Acc: 0.7826
2026-04-05 05:52:08,113 - INFO - Epoch 52/100 - Train Loss: 0.0769 - Val Acc: 0.7681
2026-04-05 05:52:08,434 - INFO - Epoch 53/100 - Train Loss: 0.0656 - Val Acc: 0.7826
2026-04-05 05:52:08,763 - INFO - Epoch 54/100 - Train Loss: 0.0594 - Val Acc: 0.7826
2026-04-05 05:52:09,084 - INFO - Epoch 55/100 - Train Loss: 0.0634 - Val Acc: 0.7971
2026-04-05 05:52:09,400 - INFO - Epoch 56/100 - Train Loss: 0.0632 - Val Acc: 0.7826
2026-04-05 05:52:09,726 - INFO - Epoch 57/100 - Train Loss: 0.0593 - Val Acc: 0.7826
2026-04-05 05:52:10,053 - INFO - Epoch 58/100 - Train Loss: 0.0669 - Val Acc: 0.7826
2026-04-05 05:52:10,390 - INFO - Epoch 59/100 - Train Loss: 0.0527 - Val Acc: 0.7826
2026-04-05 05:52:10,718 - INFO - Epoch 60/100 - Train Loss: 0.0718 - Val Acc: 0.7971
2026-04-05 05:52:11,038 - INFO - Epoch 61/100 - Train Loss: 0.0540 - Val Acc: 0.7826
2026-04-05 05:52:11,355 - INFO - Epoch 62/100 - Train Loss: 0.0599 - Val Acc: 0.7826
2026-04-05 05:52:11,680 - INFO - Epoch 63/100 - Train Loss: 0.0605 - Val Acc: 0.7826
2026-04-05 05:52:12,002 - INFO - Epoch 64/100 - Train Loss: 0.0517 - Val Acc: 0.7826
2026-04-05 05:52:12,314 - INFO - Epoch 65/100 - Train Loss: 0.0579 - Val Acc: 0.7826
2026-04-05 05:52:12,646 - INFO - Epoch 66/100 - Train Loss: 0.0677 - Val Acc: 0.7826
2026-04-05 05:52:12,977 - INFO - Epoch 67/100 - Train Loss: 0.0674 - Val Acc: 0.7681
2026-04-05 05:52:13,304 - INFO - Epoch 68/100 - Train Loss: 0.0596 - Val Acc: 0.7971
2026-04-05 05:52:13,630 - INFO - Epoch 69/100 - Train Loss: 0.0527 - Val Acc: 0.7826
2026-04-05 05:52:13,971 - INFO - Epoch 70/100 - Train Loss: 0.0640 - Val Acc: 0.7826
2026-04-05 05:52:14,292 - INFO - Epoch 71/100 - Train Loss: 0.0496 - Val Acc: 0.7826
2026-04-05 05:52:14,635 - INFO - Epoch 72/100 - Train Loss: 0.0431 - Val Acc: 0.7826
2026-04-05 05:52:14,969 - INFO - Epoch 73/100 - Train Loss: 0.0531 - Val Acc: 0.7826
2026-04-05 05:52:15,292 - INFO - Epoch 74/100 - Train Loss: 0.0515 - Val Acc: 0.7826
2026-04-05 05:52:15,613 - INFO - Epoch 75/100 - Train Loss: 0.0469 - Val Acc: 0.7826
2026-04-05 05:52:15,946 - INFO - Epoch 76/100 - Train Loss: 0.0463 - Val Acc: 0.7826
2026-04-05 05:52:16,273 - INFO - Epoch 77/100 - Train Loss: 0.0573 - Val Acc: 0.7826
2026-04-05 05:52:16,603 - INFO - Epoch 78/100 - Train Loss: 0.0463 - Val Acc: 0.7826
2026-04-05 05:52:16,938 - INFO - Epoch 79/100 - Train Loss: 0.0518 - Val Acc: 0.7681
2026-04-05 05:52:17,267 - INFO - Epoch 80/100 - Train Loss: 0.0385 - Val Acc: 0.7826
2026-04-05 05:52:17,589 - INFO - Epoch 81/100 - Train Loss: 0.0472 - Val Acc: 0.7826
2026-04-05 05:52:17,917 - INFO - Epoch 82/100 - Train Loss: 0.0495 - Val Acc: 0.7826
2026-04-05 05:52:18,246 - INFO - Epoch 83/100 - Train Loss: 0.0595 - Val Acc: 0.7826
2026-04-05 05:52:18,603 - INFO - Epoch 84/100 - Train Loss: 0.0424 - Val Acc: 0.7826
2026-04-05 05:52:18,930 - INFO - Epoch 85/100 - Train Loss: 0.0399 - Val Acc: 0.7826
2026-04-05 05:52:19,255 - INFO - Epoch 86/100 - Train Loss: 0.0468 - Val Acc: 0.7826
2026-04-05 05:52:19,580 - INFO - Epoch 87/100 - Train Loss: 0.0412 - Val Acc: 0.7826
2026-04-05 05:52:19,907 - INFO - Epoch 88/100 - Train Loss: 0.0412 - Val Acc: 0.7826
2026-04-05 05:52:20,233 - INFO - Epoch 89/100 - Train Loss: 0.0425 - Val Acc: 0.7826
2026-04-05 05:52:20,569 - INFO - Epoch 90/100 - Train Loss: 0.0471 - Val Acc: 0.7826
2026-04-05 05:52:20,892 - INFO - Epoch 91/100 - Train Loss: 0.0479 - Val Acc: 0.7826
2026-04-05 05:52:21,212 - INFO - Epoch 92/100 - Train Loss: 0.0386 - Val Acc: 0.7826
2026-04-05 05:52:21,532 - INFO - Epoch 93/100 - Train Loss: 0.0472 - Val Acc: 0.7826
2026-04-05 05:52:21,861 - INFO - Epoch 94/100 - Train Loss: 0.0411 - Val Acc: 0.7826
2026-04-05 05:52:22,200 - INFO - Epoch 95/100 - Train Loss: 0.0390 - Val Acc: 0.7826
2026-04-05 05:52:22,532 - INFO - Epoch 96/100 - Train Loss: 0.0349 - Val Acc: 0.7826
2026-04-05 05:52:22,866 - INFO - Epoch 97/100 - Train Loss: 0.0305 - Val Acc: 0.7826
2026-04-05 05:52:23,202 - INFO - Epoch 98/100 - Train Loss: 0.0337 - Val Acc: 0.7826
2026-04-05 05:52:23,522 - INFO - Epoch 99/100 - Train Loss: 0.0308 - Val Acc: 0.7826
2026-04-05 05:52:23,844 - INFO - Epoch 100/100 - Train Loss: 0.0363 - Val Acc: 0.7826
2026-04-05 05:52:24,217 - INFO - Fold 4 logically complete. Tensor memory bounds cleared cleanly.
2026-04-05 05:52:24,222 - INFO - Original class distribution: [345 276]
2026-04-05 05:52:24,222 - INFO - Training device bound securely to: cuda
2026-04-05 05:52:24,250 - INFO - After SMOTE-ENN deployment: [345 305]

Fold 5:   0%|          | 0/100 [00:00<?, ?it/s]

2026-04-05 05:52:24,613 - INFO - Epoch 1/100 - Train Loss: 0.5823 - Val Acc: 0.8696
2026-04-05 05:52:24,954 - INFO - Epoch 2/100 - Train Loss: 0.3451 - Val Acc: 0.8841
2026-04-05 05:52:25,278 - INFO - Epoch 3/100 - Train Loss: 0.2479 - Val Acc: 0.8696
2026-04-05 05:52:25,601 - INFO - Epoch 4/100 - Train Loss: 0.2127 - Val Acc: 0.8696
2026-04-05 05:52:25,942 - INFO - Epoch 5/100 - Train Loss: 0.1994 - Val Acc: 0.8551
2026-04-05 05:52:26,265 - INFO - Epoch 6/100 - Train Loss: 0.1866 - Val Acc: 0.8696
2026-04-05 05:52:26,584 - INFO - Epoch 7/100 - Train Loss: 0.1695 - Val Acc: 0.8696
2026-04-05 05:52:26,905 - INFO - Epoch 8/100 - Train Loss: 0.1747 - Val Acc: 0.8551
2026-04-05 05:52:27,241 - INFO - Epoch 9/100 - Train Loss: 0.1595 - Val Acc: 0.8406
2026-04-05 05:52:27,568 - INFO - Epoch 10/100 - Train Loss: 0.1524 - Val Acc: 0.8261
2026-04-05 05:52:27,895 - INFO - Epoch 11/100 - Train Loss: 0.1506 - Val Acc: 0.8261
2026-04-05 05:52:28,221 - INFO - Epoch 12/100 - Train Loss: 0.1428 - Val Acc: 0.8261
2026-04-05 05:52:28,538 - INFO - Epoch 13/100 - Train Loss: 0.1381 - Val Acc: 0.8261
2026-04-05 05:52:28,871 - INFO - Epoch 14/100 - Train Loss: 0.1518 - Val Acc: 0.8261
2026-04-05 05:52:29,201 - INFO - Epoch 15/100 - Train Loss: 0.1416 - Val Acc: 0.8261
2026-04-05 05:52:29,526 - INFO - Epoch 16/100 - Train Loss: 0.1410 - Val Acc: 0.8261
2026-04-05 05:52:29,864 - INFO - Epoch 17/100 - Train Loss: 0.1340 - Val Acc: 0.8261
2026-04-05 05:52:30,188 - INFO - Epoch 18/100 - Train Loss: 0.1369 - Val Acc: 0.8261
2026-04-05 05:52:30,532 - INFO - Epoch 19/100 - Train Loss: 0.1293 - Val Acc: 0.8261
2026-04-05 05:52:30,865 - INFO - Epoch 20/100 - Train Loss: 0.1425 - Val Acc: 0.8116
2026-04-05 05:52:31,191 - INFO - Epoch 21/100 - Train Loss: 0.1252 - Val Acc: 0.8261
2026-04-05 05:52:31,520 - INFO - Epoch 22/100 - Train Loss: 0.1130 - Val Acc: 0.8261
2026-04-05 05:52:31,858 - INFO - Epoch 23/100 - Train Loss: 0.1206 - Val Acc: 0.8261
2026-04-05 05:52:32,184 - INFO - Epoch 24/100 - Train Loss: 0.1219 - Val Acc: 0.8116
2026-04-05 05:52:32,510 - INFO - Epoch 25/100 - Train Loss: 0.1249 - Val Acc: 0.8116
2026-04-05 05:52:32,834 - INFO - Epoch 26/100 - Train Loss: 0.1106 - Val Acc: 0.8116
2026-04-05 05:52:33,165 - INFO - Epoch 27/100 - Train Loss: 0.1117 - Val Acc: 0.8116
2026-04-05 05:52:33,493 - INFO - Epoch 28/100 - Train Loss: 0.1000 - Val Acc: 0.8261
2026-04-05 05:52:33,814 - INFO - Epoch 29/100 - Train Loss: 0.0993 - Val Acc: 0.8116
2026-04-05 05:52:34,145 - INFO - Epoch 30/100 - Train Loss: 0.0953 - Val Acc: 0.8261
2026-04-05 05:52:34,475 - INFO - Epoch 31/100 - Train Loss: 0.1038 - Val Acc: 0.7971
2026-04-05 05:52:34,821 - INFO - Epoch 32/100 - Train Loss: 0.0988 - Val Acc: 0.8261
2026-04-05 05:52:35,179 - INFO - Epoch 33/100 - Train Loss: 0.1031 - Val Acc: 0.7971
2026-04-05 05:52:35,511 - INFO - Epoch 34/100 - Train Loss: 0.1009 - Val Acc: 0.8116
2026-04-05 05:52:35,833 - INFO - Epoch 35/100 - Train Loss: 0.0889 - Val Acc: 0.8116
2026-04-05 05:52:36,167 - INFO - Epoch 36/100 - Train Loss: 0.0927 - Val Acc: 0.8261
2026-04-05 05:52:36,496 - INFO - Epoch 37/100 - Train Loss: 0.0847 - Val Acc: 0.8116
2026-04-05 05:52:36,834 - INFO - Epoch 38/100 - Train Loss: 0.0856 - Val Acc: 0.8116
2026-04-05 05:52:37,164 - INFO - Epoch 39/100 - Train Loss: 0.0896 - Val Acc: 0.7971
2026-04-05 05:52:37,482 - INFO - Epoch 40/100 - Train Loss: 0.0852 - Val Acc: 0.8116
2026-04-05 05:52:37,812 - INFO - Epoch 41/100 - Train Loss: 0.0891 - Val Acc: 0.7971
2026-04-05 05:52:38,135 - INFO - Epoch 42/100 - Train Loss: 0.0761 - Val Acc: 0.7971
2026-04-05 05:52:38,451 - INFO - Epoch 43/100 - Train Loss: 0.0929 - Val Acc: 0.7971
2026-04-05 05:52:38,767 - INFO - Epoch 44/100 - Train Loss: 0.0971 - Val Acc: 0.7971
2026-04-05 05:52:39,094 - INFO - Epoch 45/100 - Train Loss: 0.0841 - Val Acc: 0.7971
2026-04-05 05:52:39,434 - INFO - Epoch 46/100 - Train Loss: 0.0851 - Val Acc: 0.7971
2026-04-05 05:52:39,766 - INFO - Epoch 47/100 - Train Loss: 0.0847 - Val Acc: 0.7971
2026-04-05 05:52:40,095 - INFO - Epoch 48/100 - Train Loss: 0.0817 - Val Acc: 0.7971
2026-04-05 05:52:40,420 - INFO - Epoch 49/100 - Train Loss: 0.0660 - Val Acc: 0.7971
2026-04-05 05:52:40,744 - INFO - Epoch 50/100 - Train Loss: 0.0690 - Val Acc: 0.7971
2026-04-05 05:52:41,079 - INFO - Epoch 51/100 - Train Loss: 0.0752 - Val Acc: 0.7971
2026-04-05 05:52:41,407 - INFO - Epoch 52/100 - Train Loss: 0.0604 - Val Acc: 0.7971
2026-04-05 05:52:41,741 - INFO - Epoch 53/100 - Train Loss: 0.0697 - Val Acc: 0.7971
2026-04-05 05:52:42,078 - INFO - Epoch 54/100 - Train Loss: 0.0803 - Val Acc: 0.7971
2026-04-05 05:52:42,403 - INFO - Epoch 55/100 - Train Loss: 0.0652 - Val Acc: 0.7971
2026-04-05 05:52:42,745 - INFO - Epoch 56/100 - Train Loss: 0.0663 - Val Acc: 0.7971
2026-04-05 05:52:43,081 - INFO - Epoch 57/100 - Train Loss: 0.0635 - Val Acc: 0.7971
2026-04-05 05:52:43,402 - INFO - Epoch 58/100 - Train Loss: 0.0738 - Val Acc: 0.7971
2026-04-05 05:52:43,725 - INFO - Epoch 59/100 - Train Loss: 0.0620 - Val Acc: 0.7971
2026-04-05 05:52:44,066 - INFO - Epoch 60/100 - Train Loss: 0.0650 - Val Acc: 0.7971
2026-04-05 05:52:44,397 - INFO - Epoch 61/100 - Train Loss: 0.0708 - Val Acc: 0.7971
2026-04-05 05:52:44,742 - INFO - Epoch 62/100 - Train Loss: 0.0714 - Val Acc: 0.7971
2026-04-05 05:52:45,086 - INFO - Epoch 63/100 - Train Loss: 0.0622 - Val Acc: 0.7971
2026-04-05 05:52:45,413 - INFO - Epoch 64/100 - Train Loss: 0.0627 - Val Acc: 0.7971
2026-04-05 05:52:45,743 - INFO - Epoch 65/100 - Train Loss: 0.0763 - Val Acc: 0.7971
2026-04-05 05:52:46,080 - INFO - Epoch 66/100 - Train Loss: 0.0653 - Val Acc: 0.7971
2026-04-05 05:52:46,426 - INFO - Epoch 67/100 - Train Loss: 0.0683 - Val Acc: 0.7971
2026-04-05 05:52:46,756 - INFO - Epoch 68/100 - Train Loss: 0.0546 - Val Acc: 0.7971
2026-04-05 05:52:47,086 - INFO - Epoch 69/100 - Train Loss: 0.0624 - Val Acc: 0.7971
2026-04-05 05:52:47,399 - INFO - Epoch 70/100 - Train Loss: 0.0631 - Val Acc: 0.7971
2026-04-05 05:52:47,723 - INFO - Epoch 71/100 - Train Loss: 0.0508 - Val Acc: 0.7971
2026-04-05 05:52:48,067 - INFO - Epoch 72/100 - Train Loss: 0.0636 - Val Acc: 0.7971
2026-04-05 05:52:48,394 - INFO - Epoch 73/100 - Train Loss: 0.0530 - Val Acc: 0.7971
2026-04-05 05:52:48,732 - INFO - Epoch 74/100 - Train Loss: 0.0492 - Val Acc: 0.7971
2026-04-05 05:52:49,061 - INFO - Epoch 75/100 - Train Loss: 0.0527 - Val Acc: 0.7971
2026-04-05 05:52:49,396 - INFO - Epoch 76/100 - Train Loss: 0.0502 - Val Acc: 0.7971
2026-04-05 05:52:49,737 - INFO - Epoch 77/100 - Train Loss: 0.0536 - Val Acc: 0.7971
2026-04-05 05:52:50,071 - INFO - Epoch 78/100 - Train Loss: 0.0589 - Val Acc: 0.7971
2026-04-05 05:52:50,399 - INFO - Epoch 79/100 - Train Loss: 0.0574 - Val Acc: 0.7971
2026-04-05 05:52:50,724 - INFO - Epoch 80/100 - Train Loss: 0.0473 - Val Acc: 0.7971
2026-04-05 05:52:51,062 - INFO - Epoch 81/100 - Train Loss: 0.0428 - Val Acc: 0.7971
2026-04-05 05:52:51,385 - INFO - Epoch 82/100 - Train Loss: 0.0416 - Val Acc: 0.7971
2026-04-05 05:52:51,739 - INFO - Epoch 83/100 - Train Loss: 0.0491 - Val Acc: 0.7971
2026-04-05 05:52:52,077 - INFO - Epoch 84/100 - Train Loss: 0.0402 - Val Acc: 0.7971
2026-04-05 05:52:52,413 - INFO - Epoch 85/100 - Train Loss: 0.0442 - Val Acc: 0.7971
2026-04-05 05:52:52,745 - INFO - Epoch 86/100 - Train Loss: 0.0411 - Val Acc: 0.7971
2026-04-05 05:52:53,073 - INFO - Epoch 87/100 - Train Loss: 0.0536 - Val Acc: 0.7971
2026-04-05 05:52:53,409 - INFO - Epoch 88/100 - Train Loss: 0.0639 - Val Acc: 0.7971
2026-04-05 05:52:53,743 - INFO - Epoch 89/100 - Train Loss: 0.0399 - Val Acc: 0.7971
2026-04-05 05:52:54,064 - INFO - Epoch 90/100 - Train Loss: 0.0460 - Val Acc: 0.7971
2026-04-05 05:52:54,402 - INFO - Epoch 91/100 - Train Loss: 0.0498 - Val Acc: 0.7971
2026-04-05 05:52:54,743 - INFO - Epoch 92/100 - Train Loss: 0.0522 - Val Acc: 0.7971
2026-04-05 05:52:55,076 - INFO - Epoch 93/100 - Train Loss: 0.0395 - Val Acc: 0.7971
2026-04-05 05:52:55,417 - INFO - Epoch 94/100 - Train Loss: 0.0425 - Val Acc: 0.7971
2026-04-05 05:52:55,743 - INFO - Epoch 95/100 - Train Loss: 0.0396 - Val Acc: 0.7971
2026-04-05 05:52:56,070 - INFO - Epoch 96/100 - Train Loss: 0.0568 - Val Acc: 0.7971
2026-04-05 05:52:56,390 - INFO - Epoch 97/100 - Train Loss: 0.0478 - Val Acc: 0.7971
2026-04-05 05:52:56,723 - INFO - Epoch 98/100 - Train Loss: 0.0411 - Val Acc: 0.7971
2026-04-05 05:52:57,051 - INFO - Epoch 99/100 - Train Loss: 0.0436 - Val Acc: 0.7971
2026-04-05 05:52:57,387 - INFO - Epoch 100/100 - Train Loss: 0.0366 - Val Acc: 0.7971
2026-04-05 05:52:57,754 - INFO - Fold 5 logically complete. Tensor memory bounds cleared cleanly.
2026-04-05 05:52:57,758 - INFO - Original class distribution: [345 276]
2026-04-05 05:52:57,759 - INFO - Training device bound securely to: cuda
2026-04-05 05:52:57,786 - INFO - After SMOTE-ENN deployment: [345 293]

Fold 6:   0%|          | 0/100 [00:00<?, ?it/s]

2026-04-05 05:52:58,120 - INFO - Epoch 1/100 - Train Loss: 0.5982 - Val Acc: 0.8696
2026-04-05 05:52:58,434 - INFO - Epoch 2/100 - Train Loss: 0.3704 - Val Acc: 0.8696
2026-04-05 05:52:58,768 - INFO - Epoch 3/100 - Train Loss: 0.2463 - Val Acc: 0.8696
2026-04-05 05:52:59,088 - INFO - Epoch 4/100 - Train Loss: 0.2299 - Val Acc: 0.8551
2026-04-05 05:52:59,418 - INFO - Epoch 5/100 - Train Loss: 0.2105 - Val Acc: 0.8696
2026-04-05 05:52:59,734 - INFO - Epoch 6/100 - Train Loss: 0.1872 - Val Acc: 0.8406
2026-04-05 05:53:00,046 - INFO - Epoch 7/100 - Train Loss: 0.1857 - Val Acc: 0.8551
2026-04-05 05:53:00,354 - INFO - Epoch 8/100 - Train Loss: 0.1793 - Val Acc: 0.8551
2026-04-05 05:53:00,675 - INFO - Epoch 9/100 - Train Loss: 0.1692 - Val Acc: 0.8406
2026-04-05 05:53:00,993 - INFO - Epoch 10/100 - Train Loss: 0.1775 - Val Acc: 0.8406
2026-04-05 05:53:01,321 - INFO - Epoch 11/100 - Train Loss: 0.1590 - Val Acc: 0.8261
2026-04-05 05:53:01,639 - INFO - Epoch 12/100 - Train Loss: 0.1623 - Val Acc: 0.8261
2026-04-05 05:53:01,969 - INFO - Epoch 13/100 - Train Loss: 0.1602 - Val Acc: 0.8261
2026-04-05 05:53:02,284 - INFO - Epoch 14/100 - Train Loss: 0.1518 - Val Acc: 0.8261
2026-04-05 05:53:02,604 - INFO - Epoch 15/100 - Train Loss: 0.1508 - Val Acc: 0.8261
2026-04-05 05:53:02,931 - INFO - Epoch 16/100 - Train Loss: 0.1437 - Val Acc: 0.8261
2026-04-05 05:53:03,245 - INFO - Epoch 17/100 - Train Loss: 0.1424 - Val Acc: 0.8406
2026-04-05 05:53:03,568 - INFO - Epoch 18/100 - Train Loss: 0.1371 - Val Acc: 0.8406
2026-04-05 05:53:03,896 - INFO - Epoch 19/100 - Train Loss: 0.1271 - Val Acc: 0.8551
2026-04-05 05:53:04,234 - INFO - Epoch 20/100 - Train Loss: 0.1211 - Val Acc: 0.8406
2026-04-05 05:53:04,578 - INFO - Epoch 21/100 - Train Loss: 0.1324 - Val Acc: 0.8406
2026-04-05 05:53:04,901 - INFO - Epoch 22/100 - Train Loss: 0.1268 - Val Acc: 0.8261
2026-04-05 05:53:05,224 - INFO - Epoch 23/100 - Train Loss: 0.1235 - Val Acc: 0.8406
2026-04-05 05:53:05,531 - INFO - Epoch 24/100 - Train Loss: 0.1146 - Val Acc: 0.8261
2026-04-05 05:53:05,849 - INFO - Epoch 25/100 - Train Loss: 0.1247 - Val Acc: 0.8261
2026-04-05 05:53:06,173 - INFO - Epoch 26/100 - Train Loss: 0.1115 - Val Acc: 0.8261
2026-04-05 05:53:06,503 - INFO - Epoch 27/100 - Train Loss: 0.1106 - Val Acc: 0.8261
2026-04-05 05:53:06,828 - INFO - Epoch 28/100 - Train Loss: 0.1011 - Val Acc: 0.8261
2026-04-05 05:53:07,148 - INFO - Epoch 29/100 - Train Loss: 0.1067 - Val Acc: 0.8261
2026-04-05 05:53:07,475 - INFO - Epoch 30/100 - Train Loss: 0.1043 - Val Acc: 0.8261
2026-04-05 05:53:07,787 - INFO - Epoch 31/100 - Train Loss: 0.1082 - Val Acc: 0.8116
2026-04-05 05:53:08,112 - INFO - Epoch 32/100 - Train Loss: 0.0961 - Val Acc: 0.8406
2026-04-05 05:53:08,435 - INFO - Epoch 33/100 - Train Loss: 0.0947 - Val Acc: 0.8261
2026-04-05 05:53:08,762 - INFO - Epoch 34/100 - Train Loss: 0.0911 - Val Acc: 0.8116
2026-04-05 05:53:09,088 - INFO - Epoch 35/100 - Train Loss: 0.0955 - Val Acc: 0.8406
2026-04-05 05:53:09,403 - INFO - Epoch 36/100 - Train Loss: 0.1015 - Val Acc: 0.8116
2026-04-05 05:53:09,711 - INFO - Epoch 37/100 - Train Loss: 0.0876 - Val Acc: 0.8261
2026-04-05 05:53:10,030 - INFO - Epoch 38/100 - Train Loss: 0.0984 - Val Acc: 0.8116
2026-04-05 05:53:10,347 - INFO - Epoch 39/100 - Train Loss: 0.0858 - Val Acc: 0.8116
2026-04-05 05:53:10,654 - INFO - Epoch 40/100 - Train Loss: 0.0882 - Val Acc: 0.8116
2026-04-05 05:53:10,973 - INFO - Epoch 41/100 - Train Loss: 0.0836 - Val Acc: 0.8116
2026-04-05 05:53:11,290 - INFO - Epoch 42/100 - Train Loss: 0.0808 - Val Acc: 0.8116
2026-04-05 05:53:11,606 - INFO - Epoch 43/100 - Train Loss: 0.0915 - Val Acc: 0.7971
2026-04-05 05:53:11,933 - INFO - Epoch 44/100 - Train Loss: 0.0843 - Val Acc: 0.8116
2026-04-05 05:53:12,266 - INFO - Epoch 45/100 - Train Loss: 0.0782 - Val Acc: 0.8116
2026-04-05 05:53:12,598 - INFO - Epoch 46/100 - Train Loss: 0.0716 - Val Acc: 0.8116
2026-04-05 05:53:12,926 - INFO - Epoch 47/100 - Train Loss: 0.0843 - Val Acc: 0.8116
2026-04-05 05:53:13,243 - INFO - Epoch 48/100 - Train Loss: 0.0746 - Val Acc: 0.8116
2026-04-05 05:53:13,556 - INFO - Epoch 49/100 - Train Loss: 0.0670 - Val Acc: 0.8116
2026-04-05 05:53:13,885 - INFO - Epoch 50/100 - Train Loss: 0.0730 - Val Acc: 0.8116
2026-04-05 05:53:14,211 - INFO - Epoch 51/100 - Train Loss: 0.0709 - Val Acc: 0.7971
2026-04-05 05:53:14,546 - INFO - Epoch 52/100 - Train Loss: 0.0786 - Val Acc: 0.8116
2026-04-05 05:53:14,869 - INFO - Epoch 53/100 - Train Loss: 0.0644 - Val Acc: 0.8116
2026-04-05 05:53:15,200 - INFO - Epoch 54/100 - Train Loss: 0.0629 - Val Acc: 0.8116
2026-04-05 05:53:15,518 - INFO - Epoch 55/100 - Train Loss: 0.0708 - Val Acc: 0.7971
2026-04-05 05:53:15,838 - INFO - Epoch 56/100 - Train Loss: 0.0570 - Val Acc: 0.8116
2026-04-05 05:53:16,152 - INFO - Epoch 57/100 - Train Loss: 0.0640 - Val Acc: 0.8116
2026-04-05 05:53:16,468 - INFO - Epoch 58/100 - Train Loss: 0.0634 - Val Acc: 0.8116
2026-04-05 05:53:16,777 - INFO - Epoch 59/100 - Train Loss: 0.0549 - Val Acc: 0.8116
2026-04-05 05:53:17,089 - INFO - Epoch 60/100 - Train Loss: 0.0582 - Val Acc: 0.8116
2026-04-05 05:53:17,401 - INFO - Epoch 61/100 - Train Loss: 0.0539 - Val Acc: 0.7971
2026-04-05 05:53:17,731 - INFO - Epoch 62/100 - Train Loss: 0.0550 - Val Acc: 0.8261
2026-04-05 05:53:18,049 - INFO - Epoch 63/100 - Train Loss: 0.0460 - Val Acc: 0.8261
2026-04-05 05:53:18,376 - INFO - Epoch 64/100 - Train Loss: 0.0567 - Val Acc: 0.8116
2026-04-05 05:53:18,705 - INFO - Epoch 65/100 - Train Loss: 0.0626 - Val Acc: 0.8116
2026-04-05 05:53:19,027 - INFO - Epoch 66/100 - Train Loss: 0.0409 - Val Acc: 0.8116
2026-04-05 05:53:19,354 - INFO - Epoch 67/100 - Train Loss: 0.0612 - Val Acc: 0.8116
2026-04-05 05:53:19,670 - INFO - Epoch 68/100 - Train Loss: 0.0473 - Val Acc: 0.8116
2026-04-05 05:53:20,000 - INFO - Epoch 69/100 - Train Loss: 0.0544 - Val Acc: 0.8116
2026-04-05 05:53:20,317 - INFO - Epoch 70/100 - Train Loss: 0.0510 - Val Acc: 0.8116
2026-04-05 05:53:20,627 - INFO - Epoch 71/100 - Train Loss: 0.0474 - Val Acc: 0.8116
2026-04-05 05:53:20,948 - INFO - Epoch 72/100 - Train Loss: 0.0478 - Val Acc: 0.8116
2026-04-05 05:53:21,265 - INFO - Epoch 73/100 - Train Loss: 0.0582 - Val Acc: 0.8116
2026-04-05 05:53:21,583 - INFO - Epoch 74/100 - Train Loss: 0.0466 - Val Acc: 0.7971
2026-04-05 05:53:21,905 - INFO - Epoch 75/100 - Train Loss: 0.0458 - Val Acc: 0.8116
2026-04-05 05:53:22,226 - INFO - Epoch 76/100 - Train Loss: 0.0529 - Val Acc: 0.8261
2026-04-05 05:53:22,547 - INFO - Epoch 77/100 - Train Loss: 0.0524 - Val Acc: 0.7971
2026-04-05 05:53:22,853 - INFO - Epoch 78/100 - Train Loss: 0.0464 - Val Acc: 0.8116
2026-04-05 05:53:23,156 - INFO - Epoch 79/100 - Train Loss: 0.0464 - Val Acc: 0.7971
2026-04-05 05:53:23,476 - INFO - Epoch 80/100 - Train Loss: 0.0481 - Val Acc: 0.8116
2026-04-05 05:53:23,782 - INFO - Epoch 81/100 - Train Loss: 0.0572 - Val Acc: 0.8116
2026-04-05 05:53:24,093 - INFO - Epoch 82/100 - Train Loss: 0.0395 - Val Acc: 0.8116
2026-04-05 05:53:24,412 - INFO - Epoch 83/100 - Train Loss: 0.0361 - Val Acc: 0.8116
2026-04-05 05:53:24,746 - INFO - Epoch 84/100 - Train Loss: 0.0466 - Val Acc: 0.8261
2026-04-05 05:53:25,072 - INFO - Epoch 85/100 - Train Loss: 0.0418 - Val Acc: 0.8261
2026-04-05 05:53:25,389 - INFO - Epoch 86/100 - Train Loss: 0.0414 - Val Acc: 0.8116
2026-04-05 05:53:25,690 - INFO - Epoch 87/100 - Train Loss: 0.0448 - Val Acc: 0.8116
2026-04-05 05:53:25,999 - INFO - Epoch 88/100 - Train Loss: 0.0403 - Val Acc: 0.8406
2026-04-05 05:53:26,310 - INFO - Epoch 89/100 - Train Loss: 0.0332 - Val Acc: 0.8261
2026-04-05 05:53:26,617 - INFO - Epoch 90/100 - Train Loss: 0.0496 - Val Acc: 0.8261
2026-04-05 05:53:26,929 - INFO - Epoch 91/100 - Train Loss: 0.0393 - Val Acc: 0.8261
2026-04-05 05:53:27,232 - INFO - Epoch 92/100 - Train Loss: 0.0441 - Val Acc: 0.8261
2026-04-05 05:53:27,537 - INFO - Epoch 93/100 - Train Loss: 0.0414 - Val Acc: 0.8261
2026-04-05 05:53:27,850 - INFO - Epoch 94/100 - Train Loss: 0.0378 - Val Acc: 0.8261
2026-04-05 05:53:28,166 - INFO - Epoch 95/100 - Train Loss: 0.0357 - Val Acc: 0.8116
2026-04-05 05:53:28,475 - INFO - Epoch 96/100 - Train Loss: 0.0314 - Val Acc: 0.8261
2026-04-05 05:53:28,797 - INFO - Epoch 97/100 - Train Loss: 0.0343 - Val Acc: 0.8261
2026-04-05 05:53:29,107 - INFO - Epoch 98/100 - Train Loss: 0.0352 - Val Acc: 0.8116
2026-04-05 05:53:29,433 - INFO - Epoch 99/100 - Train Loss: 0.0359 - Val Acc: 0.8261
2026-04-05 05:53:29,775 - INFO - Epoch 100/100 - Train Loss: 0.0495 - Val Acc: 0.8406
2026-04-05 05:53:30,145 - INFO - Fold 6 logically complete. Tensor memory bounds cleared cleanly.
2026-04-05 05:53:30,149 - INFO - Original class distribution: [345 276]
2026-04-05 05:53:30,150 - INFO - Training device bound securely to: cuda
2026-04-05 05:53:30,176 - INFO - After SMOTE-ENN deployment: [345 302]

Fold 7:   0%|          | 0/100 [00:00<?, ?it/s]

2026-04-05 05:53:30,536 - INFO - Epoch 1/100 - Train Loss: 0.5909 - Val Acc: 0.7536
2026-04-05 05:53:30,854 - INFO - Epoch 2/100 - Train Loss: 0.3463 - Val Acc: 0.7536
2026-04-05 05:53:31,179 - INFO - Epoch 3/100 - Train Loss: 0.2441 - Val Acc: 0.7391
2026-04-05 05:53:31,506 - INFO - Epoch 4/100 - Train Loss: 0.1996 - Val Acc: 0.7681
2026-04-05 05:53:31,838 - INFO - Epoch 5/100 - Train Loss: 0.1860 - Val Acc: 0.7536
2026-04-05 05:53:32,173 - INFO - Epoch 6/100 - Train Loss: 0.1829 - Val Acc: 0.7536
2026-04-05 05:53:32,495 - INFO - Epoch 7/100 - Train Loss: 0.1746 - Val Acc: 0.7391
2026-04-05 05:53:32,823 - INFO - Epoch 8/100 - Train Loss: 0.1667 - Val Acc: 0.7391
2026-04-05 05:53:33,154 - INFO - Epoch 9/100 - Train Loss: 0.1603 - Val Acc: 0.7391
2026-04-05 05:53:33,489 - INFO - Epoch 10/100 - Train Loss: 0.1512 - Val Acc: 0.7391
2026-04-05 05:53:33,819 - INFO - Epoch 11/100 - Train Loss: 0.1509 - Val Acc: 0.7391
2026-04-05 05:53:34,154 - INFO - Epoch 12/100 - Train Loss: 0.1426 - Val Acc: 0.7536
2026-04-05 05:53:34,499 - INFO - Epoch 13/100 - Train Loss: 0.1357 - Val Acc: 0.7391
2026-04-05 05:53:34,831 - INFO - Epoch 14/100 - Train Loss: 0.1449 - Val Acc: 0.7536
2026-04-05 05:53:35,159 - INFO - Epoch 15/100 - Train Loss: 0.1384 - Val Acc: 0.7536
2026-04-05 05:53:35,480 - INFO - Epoch 16/100 - Train Loss: 0.1269 - Val Acc: 0.7536
2026-04-05 05:53:35,810 - INFO - Epoch 17/100 - Train Loss: 0.1228 - Val Acc: 0.7536
2026-04-05 05:53:36,142 - INFO - Epoch 18/100 - Train Loss: 0.1260 - Val Acc: 0.7536
2026-04-05 05:53:36,486 - INFO - Epoch 19/100 - Train Loss: 0.1231 - Val Acc: 0.7536
2026-04-05 05:53:36,828 - INFO - Epoch 20/100 - Train Loss: 0.1251 - Val Acc: 0.7536
2026-04-05 05:53:37,158 - INFO - Epoch 21/100 - Train Loss: 0.1125 - Val Acc: 0.7536
2026-04-05 05:53:37,482 - INFO - Epoch 22/100 - Train Loss: 0.1130 - Val Acc: 0.7681
2026-04-05 05:53:37,803 - INFO - Epoch 23/100 - Train Loss: 0.1172 - Val Acc: 0.7681
2026-04-05 05:53:38,122 - INFO - Epoch 24/100 - Train Loss: 0.1218 - Val Acc: 0.7681
2026-04-05 05:53:38,437 - INFO - Epoch 25/100 - Train Loss: 0.1107 - Val Acc: 0.7681
2026-04-05 05:53:38,766 - INFO - Epoch 26/100 - Train Loss: 0.1198 - Val Acc: 0.7536
2026-04-05 05:53:39,108 - INFO - Epoch 27/100 - Train Loss: 0.1071 - Val Acc: 0.7681
2026-04-05 05:53:39,430 - INFO - Epoch 28/100 - Train Loss: 0.1054 - Val Acc: 0.7681
2026-04-05 05:53:39,780 - INFO - Epoch 29/100 - Train Loss: 0.1056 - Val Acc: 0.7536
2026-04-05 05:53:40,113 - INFO - Epoch 30/100 - Train Loss: 0.1047 - Val Acc: 0.7536
2026-04-05 05:53:40,442 - INFO - Epoch 31/100 - Train Loss: 0.0925 - Val Acc: 0.7536
2026-04-05 05:53:40,764 - INFO - Epoch 32/100 - Train Loss: 0.1012 - Val Acc: 0.7536
2026-04-05 05:53:41,103 - INFO - Epoch 33/100 - Train Loss: 0.0895 - Val Acc: 0.7536
2026-04-05 05:53:41,427 - INFO - Epoch 34/100 - Train Loss: 0.0919 - Val Acc: 0.7536
2026-04-05 05:53:41,761 - INFO - Epoch 35/100 - Train Loss: 0.0944 - Val Acc: 0.7391
2026-04-05 05:53:42,085 - INFO - Epoch 36/100 - Train Loss: 0.0928 - Val Acc: 0.7536
2026-04-05 05:53:42,427 - INFO - Epoch 37/100 - Train Loss: 0.0960 - Val Acc: 0.7391
2026-04-05 05:53:42,746 - INFO - Epoch 38/100 - Train Loss: 0.0970 - Val Acc: 0.7826
2026-04-05 05:53:43,068 - INFO - Epoch 39/100 - Train Loss: 0.0835 - Val Acc: 0.7536
2026-04-05 05:53:43,396 - INFO - Epoch 40/100 - Train Loss: 0.0793 - Val Acc: 0.7391
2026-04-05 05:53:43,731 - INFO - Epoch 41/100 - Train Loss: 0.0794 - Val Acc: 0.7391
2026-04-05 05:53:44,055 - INFO - Epoch 42/100 - Train Loss: 0.0830 - Val Acc: 0.7826
2026-04-05 05:53:44,394 - INFO - Epoch 43/100 - Train Loss: 0.0912 - Val Acc: 0.7826
2026-04-05 05:53:44,760 - INFO - Epoch 44/100 - Train Loss: 0.0960 - Val Acc: 0.7536
2026-04-05 05:53:45,086 - INFO - Epoch 45/100 - Train Loss: 0.0801 - Val Acc: 0.7681
2026-04-05 05:53:45,421 - INFO - Epoch 46/100 - Train Loss: 0.0817 - Val Acc: 0.7826
2026-04-05 05:53:45,748 - INFO - Epoch 47/100 - Train Loss: 0.0912 - Val Acc: 0.7536
2026-04-05 05:53:46,077 - INFO - Epoch 48/100 - Train Loss: 0.0860 - Val Acc: 0.7536
2026-04-05 05:53:46,407 - INFO - Epoch 49/100 - Train Loss: 0.0890 - Val Acc: 0.7826
2026-04-05 05:53:46,736 - INFO - Epoch 50/100 - Train Loss: 0.0810 - Val Acc: 0.7536
2026-04-05 05:53:47,056 - INFO - Epoch 51/100 - Train Loss: 0.0765 - Val Acc: 0.7536
2026-04-05 05:53:47,380 - INFO - Epoch 52/100 - Train Loss: 0.0756 - Val Acc: 0.7681
2026-04-05 05:53:47,705 - INFO - Epoch 53/100 - Train Loss: 0.0816 - Val Acc: 0.7971
2026-04-05 05:53:48,028 - INFO - Epoch 54/100 - Train Loss: 0.0780 - Val Acc: 0.7826
2026-04-05 05:53:48,360 - INFO - Epoch 55/100 - Train Loss: 0.0845 - Val Acc: 0.7536
2026-04-05 05:53:48,688 - INFO - Epoch 56/100 - Train Loss: 0.0795 - Val Acc: 0.7536
2026-04-05 05:53:49,012 - INFO - Epoch 57/100 - Train Loss: 0.0786 - Val Acc: 0.7681
2026-04-05 05:53:49,341 - INFO - Epoch 58/100 - Train Loss: 0.0701 - Val Acc: 0.7391
2026-04-05 05:53:49,665 - INFO - Epoch 59/100 - Train Loss: 0.0652 - Val Acc: 0.7681
2026-04-05 05:53:50,002 - INFO - Epoch 60/100 - Train Loss: 0.0646 - Val Acc: 0.7681
2026-04-05 05:53:50,326 - INFO - Epoch 61/100 - Train Loss: 0.0640 - Val Acc: 0.7826
2026-04-05 05:53:50,646 - INFO - Epoch 62/100 - Train Loss: 0.0684 - Val Acc: 0.7826
2026-04-05 05:53:50,971 - INFO - Epoch 63/100 - Train Loss: 0.0653 - Val Acc: 0.7826
2026-04-05 05:53:51,321 - INFO - Epoch 64/100 - Train Loss: 0.0645 - Val Acc: 0.7826
2026-04-05 05:53:51,658 - INFO - Epoch 65/100 - Train Loss: 0.0709 - Val Acc: 0.7826
2026-04-05 05:53:51,991 - INFO - Epoch 66/100 - Train Loss: 0.0623 - Val Acc: 0.7681
2026-04-05 05:53:52,328 - INFO - Epoch 67/100 - Train Loss: 0.0479 - Val Acc: 0.7681
2026-04-05 05:53:52,652 - INFO - Epoch 68/100 - Train Loss: 0.0618 - Val Acc: 0.7826
2026-04-05 05:53:52,976 - INFO - Epoch 69/100 - Train Loss: 0.0718 - Val Acc: 0.7681
2026-04-05 05:53:53,309 - INFO - Epoch 70/100 - Train Loss: 0.0621 - Val Acc: 0.7681
2026-04-05 05:53:53,647 - INFO - Epoch 71/100 - Train Loss: 0.0666 - Val Acc: 0.7681
2026-04-05 05:53:53,975 - INFO - Epoch 72/100 - Train Loss: 0.0610 - Val Acc: 0.7536
2026-04-05 05:53:54,326 - INFO - Epoch 73/100 - Train Loss: 0.0646 - Val Acc: 0.7536
2026-04-05 05:53:54,680 - INFO - Epoch 74/100 - Train Loss: 0.0712 - Val Acc: 0.7826
2026-04-05 05:53:55,012 - INFO - Epoch 75/100 - Train Loss: 0.0599 - Val Acc: 0.7681
2026-04-05 05:53:55,350 - INFO - Epoch 76/100 - Train Loss: 0.0692 - Val Acc: 0.7536
2026-04-05 05:53:55,692 - INFO - Epoch 77/100 - Train Loss: 0.0630 - Val Acc: 0.7536
2026-04-05 05:53:56,038 - INFO - Epoch 78/100 - Train Loss: 0.0555 - Val Acc: 0.7681
2026-04-05 05:53:56,371 - INFO - Epoch 79/100 - Train Loss: 0.0540 - Val Acc: 0.7536
2026-04-05 05:53:56,704 - INFO - Epoch 80/100 - Train Loss: 0.0552 - Val Acc: 0.7536
2026-04-05 05:53:57,039 - INFO - Epoch 81/100 - Train Loss: 0.0526 - Val Acc: 0.7826
2026-04-05 05:53:57,369 - INFO - Epoch 82/100 - Train Loss: 0.0548 - Val Acc: 0.7826
2026-04-05 05:53:57,689 - INFO - Epoch 83/100 - Train Loss: 0.0611 - Val Acc: 0.7826
2026-04-05 05:53:58,016 - INFO - Epoch 84/100 - Train Loss: 0.0510 - Val Acc: 0.7826
2026-04-05 05:53:58,349 - INFO - Epoch 85/100 - Train Loss: 0.0584 - Val Acc: 0.7536
2026-04-05 05:53:58,683 - INFO - Epoch 86/100 - Train Loss: 0.0430 - Val Acc: 0.7826
2026-04-05 05:53:59,022 - INFO - Epoch 87/100 - Train Loss: 0.0473 - Val Acc: 0.7826
2026-04-05 05:53:59,344 - INFO - Epoch 88/100 - Train Loss: 0.0404 - Val Acc: 0.7826
2026-04-05 05:53:59,668 - INFO - Epoch 89/100 - Train Loss: 0.0333 - Val Acc: 0.7826
2026-04-05 05:53:59,991 - INFO - Epoch 90/100 - Train Loss: 0.0474 - Val Acc: 0.7826
2026-04-05 05:54:00,322 - INFO - Epoch 91/100 - Train Loss: 0.0362 - Val Acc: 0.7826
2026-04-05 05:54:00,647 - INFO - Epoch 92/100 - Train Loss: 0.0505 - Val Acc: 0.7826
2026-04-05 05:54:00,983 - INFO - Epoch 93/100 - Train Loss: 0.0526 - Val Acc: 0.7826
2026-04-05 05:54:01,317 - INFO - Epoch 94/100 - Train Loss: 0.0377 - Val Acc: 0.7826
2026-04-05 05:54:01,648 - INFO - Epoch 95/100 - Train Loss: 0.0439 - Val Acc: 0.7826
2026-04-05 05:54:01,979 - INFO - Epoch 96/100 - Train Loss: 0.0447 - Val Acc: 0.7681
2026-04-05 05:54:02,311 - INFO - Epoch 97/100 - Train Loss: 0.0433 - Val Acc: 0.7536
2026-04-05 05:54:02,642 - INFO - Epoch 98/100 - Train Loss: 0.0405 - Val Acc: 0.7681
2026-04-05 05:54:02,969 - INFO - Epoch 99/100 - Train Loss: 0.0510 - Val Acc: 0.7826
2026-04-05 05:54:03,313 - INFO - Epoch 100/100 - Train Loss: 0.0442 - Val Acc: 0.7681
2026-04-05 05:54:03,678 - INFO - Fold 7 logically complete. Tensor memory bounds cleared cleanly.
2026-04-05 05:54:03,682 - INFO - Original class distribution: [345 276]
2026-04-05 05:54:03,683 - INFO - Training device bound securely to: cuda
2026-04-05 05:54:03,712 - INFO - After SMOTE-ENN deployment: [345 296]

Fold 8:   0%|          | 0/100 [00:00<?, ?it/s]

2026-04-05 05:54:04,055 - INFO - Epoch 1/100 - Train Loss: 0.5704 - Val Acc: 0.8696
2026-04-05 05:54:04,392 - INFO - Epoch 2/100 - Train Loss: 0.3396 - Val Acc: 0.8551
2026-04-05 05:54:04,758 - INFO - Epoch 3/100 - Train Loss: 0.2520 - Val Acc: 0.8406
2026-04-05 05:54:05,093 - INFO - Epoch 4/100 - Train Loss: 0.2379 - Val Acc: 0.8551
2026-04-05 05:54:05,452 - INFO - Epoch 5/100 - Train Loss: 0.2073 - Val Acc: 0.8696
2026-04-05 05:54:05,796 - INFO - Epoch 6/100 - Train Loss: 0.1969 - Val Acc: 0.8551
2026-04-05 05:54:06,121 - INFO - Epoch 7/100 - Train Loss: 0.2129 - Val Acc: 0.8696
2026-04-05 05:54:06,448 - INFO - Epoch 8/100 - Train Loss: 0.1971 - Val Acc: 0.8551
2026-04-05 05:54:06,784 - INFO - Epoch 9/100 - Train Loss: 0.1838 - Val Acc: 0.8696
2026-04-05 05:54:07,131 - INFO - Epoch 10/100 - Train Loss: 0.1758 - Val Acc: 0.8551
2026-04-05 05:54:07,473 - INFO - Epoch 11/100 - Train Loss: 0.1758 - Val Acc: 0.8696
2026-04-05 05:54:07,793 - INFO - Epoch 12/100 - Train Loss: 0.1722 - Val Acc: 0.8551
2026-04-05 05:54:08,121 - INFO - Epoch 13/100 - Train Loss: 0.1680 - Val Acc: 0.8551
2026-04-05 05:54:08,447 - INFO - Epoch 14/100 - Train Loss: 0.1584 - Val Acc: 0.8406
2026-04-05 05:54:08,783 - INFO - Epoch 15/100 - Train Loss: 0.1536 - Val Acc: 0.8551
2026-04-05 05:54:09,123 - INFO - Epoch 16/100 - Train Loss: 0.1565 - Val Acc: 0.8261
2026-04-05 05:54:09,440 - INFO - Epoch 17/100 - Train Loss: 0.1595 - Val Acc: 0.8261
2026-04-05 05:54:09,774 - INFO - Epoch 18/100 - Train Loss: 0.1498 - Val Acc: 0.8406
2026-04-05 05:54:10,090 - INFO - Epoch 19/100 - Train Loss: 0.1529 - Val Acc: 0.8406
2026-04-05 05:54:10,412 - INFO - Epoch 20/100 - Train Loss: 0.1466 - Val Acc: 0.8406
2026-04-05 05:54:10,742 - INFO - Epoch 21/100 - Train Loss: 0.1375 - Val Acc: 0.8406
2026-04-05 05:54:11,085 - INFO - Epoch 22/100 - Train Loss: 0.1343 - Val Acc: 0.8261
2026-04-05 05:54:11,421 - INFO - Epoch 23/100 - Train Loss: 0.1291 - Val Acc: 0.8261
2026-04-05 05:54:11,746 - INFO - Epoch 24/100 - Train Loss: 0.1234 - Val Acc: 0.8406
2026-04-05 05:54:12,064 - INFO - Epoch 25/100 - Train Loss: 0.1322 - Val Acc: 0.8406
2026-04-05 05:54:12,391 - INFO - Epoch 26/100 - Train Loss: 0.1187 - Val Acc: 0.8406
2026-04-05 05:54:12,716 - INFO - Epoch 27/100 - Train Loss: 0.1246 - Val Acc: 0.8406
2026-04-05 05:54:13,050 - INFO - Epoch 28/100 - Train Loss: 0.1269 - Val Acc: 0.8406
2026-04-05 05:54:13,377 - INFO - Epoch 29/100 - Train Loss: 0.1134 - Val Acc: 0.8406
2026-04-05 05:54:13,694 - INFO - Epoch 30/100 - Train Loss: 0.1149 - Val Acc: 0.8406
2026-04-05 05:54:14,021 - INFO - Epoch 31/100 - Train Loss: 0.1263 - Val Acc: 0.8406
2026-04-05 05:54:14,355 - INFO - Epoch 32/100 - Train Loss: 0.1195 - Val Acc: 0.8406
2026-04-05 05:54:14,695 - INFO - Epoch 33/100 - Train Loss: 0.1158 - Val Acc: 0.8406
2026-04-05 05:54:15,039 - INFO - Epoch 34/100 - Train Loss: 0.1168 - Val Acc: 0.8406
2026-04-05 05:54:15,364 - INFO - Epoch 35/100 - Train Loss: 0.1032 - Val Acc: 0.8406
2026-04-05 05:54:15,684 - INFO - Epoch 36/100 - Train Loss: 0.1264 - Val Acc: 0.8406
2026-04-05 05:54:16,023 - INFO - Epoch 37/100 - Train Loss: 0.1120 - Val Acc: 0.8551
2026-04-05 05:54:16,349 - INFO - Epoch 38/100 - Train Loss: 0.1051 - Val Acc: 0.8406
2026-04-05 05:54:16,676 - INFO - Epoch 39/100 - Train Loss: 0.0912 - Val Acc: 0.8406
2026-04-05 05:54:16,991 - INFO - Epoch 40/100 - Train Loss: 0.1001 - Val Acc: 0.8406
2026-04-05 05:54:17,322 - INFO - Epoch 41/100 - Train Loss: 0.1110 - Val Acc: 0.8406
2026-04-05 05:54:17,650 - INFO - Epoch 42/100 - Train Loss: 0.0946 - Val Acc: 0.8406
2026-04-05 05:54:17,971 - INFO - Epoch 43/100 - Train Loss: 0.0882 - Val Acc: 0.8406
2026-04-05 05:54:18,295 - INFO - Epoch 44/100 - Train Loss: 0.0896 - Val Acc: 0.8406
2026-04-05 05:54:18,631 - INFO - Epoch 45/100 - Train Loss: 0.0944 - Val Acc: 0.8261
2026-04-05 05:54:18,970 - INFO - Epoch 46/100 - Train Loss: 0.0934 - Val Acc: 0.8406
2026-04-05 05:54:19,294 - INFO - Epoch 47/100 - Train Loss: 0.1013 - Val Acc: 0.8406
2026-04-05 05:54:19,616 - INFO - Epoch 48/100 - Train Loss: 0.0955 - Val Acc: 0.8261
2026-04-05 05:54:19,948 - INFO - Epoch 49/100 - Train Loss: 0.0992 - Val Acc: 0.8406
2026-04-05 05:54:20,275 - INFO - Epoch 50/100 - Train Loss: 0.0947 - Val Acc: 0.8406
2026-04-05 05:54:20,614 - INFO - Epoch 51/100 - Train Loss: 0.1050 - Val Acc: 0.8406
2026-04-05 05:54:20,945 - INFO - Epoch 52/100 - Train Loss: 0.0758 - Val Acc: 0.8406
2026-04-05 05:54:21,288 - INFO - Epoch 53/100 - Train Loss: 0.0989 - Val Acc: 0.8406
2026-04-05 05:54:21,610 - INFO - Epoch 54/100 - Train Loss: 0.0870 - Val Acc: 0.8406
2026-04-05 05:54:21,936 - INFO - Epoch 55/100 - Train Loss: 0.0825 - Val Acc: 0.8406
2026-04-05 05:54:22,261 - INFO - Epoch 56/100 - Train Loss: 0.0757 - Val Acc: 0.8406
2026-04-05 05:54:22,579 - INFO - Epoch 57/100 - Train Loss: 0.0908 - Val Acc: 0.8406
2026-04-05 05:54:22,898 - INFO - Epoch 58/100 - Train Loss: 0.0888 - Val Acc: 0.8406
2026-04-05 05:54:23,226 - INFO - Epoch 59/100 - Train Loss: 0.0872 - Val Acc: 0.8406
2026-04-05 05:54:23,553 - INFO - Epoch 60/100 - Train Loss: 0.0746 - Val Acc: 0.8406
2026-04-05 05:54:23,875 - INFO - Epoch 61/100 - Train Loss: 0.0695 - Val Acc: 0.8406
2026-04-05 05:54:24,211 - INFO - Epoch 62/100 - Train Loss: 0.0888 - Val Acc: 0.8406
2026-04-05 05:54:24,560 - INFO - Epoch 63/100 - Train Loss: 0.0923 - Val Acc: 0.8406
2026-04-05 05:54:24,884 - INFO - Epoch 64/100 - Train Loss: 0.0726 - Val Acc: 0.8406
2026-04-05 05:54:25,213 - INFO - Epoch 65/100 - Train Loss: 0.0641 - Val Acc: 0.8406
2026-04-05 05:54:25,544 - INFO - Epoch 66/100 - Train Loss: 0.0748 - Val Acc: 0.8406
2026-04-05 05:54:25,871 - INFO - Epoch 67/100 - Train Loss: 0.0807 - Val Acc: 0.8261
2026-04-05 05:54:26,183 - INFO - Epoch 68/100 - Train Loss: 0.0780 - Val Acc: 0.8406
2026-04-05 05:54:26,514 - INFO - Epoch 69/100 - Train Loss: 0.0711 - Val Acc: 0.8406
2026-04-05 05:54:26,839 - INFO - Epoch 70/100 - Train Loss: 0.0724 - Val Acc: 0.8406
2026-04-05 05:54:27,175 - INFO - Epoch 71/100 - Train Loss: 0.0775 - Val Acc: 0.8406
2026-04-05 05:54:27,502 - INFO - Epoch 72/100 - Train Loss: 0.0581 - Val Acc: 0.8406
2026-04-05 05:54:27,834 - INFO - Epoch 73/100 - Train Loss: 0.0629 - Val Acc: 0.8406
2026-04-05 05:54:28,176 - INFO - Epoch 74/100 - Train Loss: 0.0563 - Val Acc: 0.8406
2026-04-05 05:54:28,501 - INFO - Epoch 75/100 - Train Loss: 0.0662 - Val Acc: 0.8406
2026-04-05 05:54:28,824 - INFO - Epoch 76/100 - Train Loss: 0.0543 - Val Acc: 0.8261
2026-04-05 05:54:29,143 - INFO - Epoch 77/100 - Train Loss: 0.0589 - Val Acc: 0.8406
2026-04-05 05:54:29,470 - INFO - Epoch 78/100 - Train Loss: 0.0602 - Val Acc: 0.8406
2026-04-05 05:54:29,794 - INFO - Epoch 79/100 - Train Loss: 0.0633 - Val Acc: 0.8406
2026-04-05 05:54:30,135 - INFO - Epoch 80/100 - Train Loss: 0.0591 - Val Acc: 0.8406
2026-04-05 05:54:30,467 - INFO - Epoch 81/100 - Train Loss: 0.0587 - Val Acc: 0.8406
2026-04-05 05:54:30,790 - INFO - Epoch 82/100 - Train Loss: 0.0655 - Val Acc: 0.8116
2026-04-05 05:54:31,115 - INFO - Epoch 83/100 - Train Loss: 0.0772 - Val Acc: 0.8116
2026-04-05 05:54:31,434 - INFO - Epoch 84/100 - Train Loss: 0.0768 - Val Acc: 0.8261
2026-04-05 05:54:31,761 - INFO - Epoch 85/100 - Train Loss: 0.0675 - Val Acc: 0.8406
2026-04-05 05:54:32,085 - INFO - Epoch 86/100 - Train Loss: 0.0524 - Val Acc: 0.8406
2026-04-05 05:54:32,411 - INFO - Epoch 87/100 - Train Loss: 0.0607 - Val Acc: 0.8406
2026-04-05 05:54:32,729 - INFO - Epoch 88/100 - Train Loss: 0.0683 - Val Acc: 0.8406
2026-04-05 05:54:33,044 - INFO - Epoch 89/100 - Train Loss: 0.0612 - Val Acc: 0.8406
2026-04-05 05:54:33,366 - INFO - Epoch 90/100 - Train Loss: 0.0750 - Val Acc: 0.8406
2026-04-05 05:54:33,687 - INFO - Epoch 91/100 - Train Loss: 0.0475 - Val Acc: 0.8406
2026-04-05 05:54:34,004 - INFO - Epoch 92/100 - Train Loss: 0.0592 - Val Acc: 0.8406
2026-04-05 05:54:34,334 - INFO - Epoch 93/100 - Train Loss: 0.0437 - Val Acc: 0.8406
2026-04-05 05:54:34,689 - INFO - Epoch 94/100 - Train Loss: 0.0511 - Val Acc: 0.8406
2026-04-05 05:54:35,037 - INFO - Epoch 95/100 - Train Loss: 0.0573 - Val Acc: 0.8406
2026-04-05 05:54:35,369 - INFO - Epoch 96/100 - Train Loss: 0.0448 - Val Acc: 0.8406
2026-04-05 05:54:35,688 - INFO - Epoch 97/100 - Train Loss: 0.0635 - Val Acc: 0.8261
2026-04-05 05:54:36,009 - INFO - Epoch 98/100 - Train Loss: 0.0513 - Val Acc: 0.8261
2026-04-05 05:54:36,345 - INFO - Epoch 99/100 - Train Loss: 0.0479 - Val Acc: 0.8261
2026-04-05 05:54:36,664 - INFO - Epoch 100/100 - Train Loss: 0.0463 - Val Acc: 0.8261
2026-04-05 05:54:37,024 - INFO - Fold 8 logically complete. Tensor memory bounds cleared cleanly.
2026-04-05 05:54:37,028 - INFO - Original class distribution: [345 276]
2026-04-05 05:54:37,029 - INFO - Training device bound securely to: cuda
2026-04-05 05:54:37,057 - INFO - After SMOTE-ENN deployment: [345 301]

Fold 9:   0%|          | 0/100 [00:00<?, ?it/s]

2026-04-05 05:54:37,395 - INFO - Epoch 1/100 - Train Loss: 0.5751 - Val Acc: 0.8261
2026-04-05 05:54:37,721 - INFO - Epoch 2/100 - Train Loss: 0.3284 - Val Acc: 0.8116
2026-04-05 05:54:38,055 - INFO - Epoch 3/100 - Train Loss: 0.2228 - Val Acc: 0.8116
2026-04-05 05:54:38,379 - INFO - Epoch 4/100 - Train Loss: 0.1971 - Val Acc: 0.8116
2026-04-05 05:54:38,701 - INFO - Epoch 5/100 - Train Loss: 0.1892 - Val Acc: 0.8406
2026-04-05 05:54:39,029 - INFO - Epoch 6/100 - Train Loss: 0.1764 - Val Acc: 0.8261
2026-04-05 05:54:39,359 - INFO - Epoch 7/100 - Train Loss: 0.1804 - Val Acc: 0.8261
2026-04-05 05:54:39,674 - INFO - Epoch 8/100 - Train Loss: 0.1571 - Val Acc: 0.8261
2026-04-05 05:54:40,002 - INFO - Epoch 9/100 - Train Loss: 0.1510 - Val Acc: 0.8261
2026-04-05 05:54:40,341 - INFO - Epoch 10/100 - Train Loss: 0.1510 - Val Acc: 0.8406
2026-04-05 05:54:40,679 - INFO - Epoch 11/100 - Train Loss: 0.1456 - Val Acc: 0.8406
2026-04-05 05:54:41,008 - INFO - Epoch 12/100 - Train Loss: 0.1441 - Val Acc: 0.8406
2026-04-05 05:54:41,320 - INFO - Epoch 13/100 - Train Loss: 0.1469 - Val Acc: 0.8406
2026-04-05 05:54:41,637 - INFO - Epoch 14/100 - Train Loss: 0.1392 - Val Acc: 0.8406
2026-04-05 05:54:41,967 - INFO - Epoch 15/100 - Train Loss: 0.1404 - Val Acc: 0.8406
2026-04-05 05:54:42,304 - INFO - Epoch 16/100 - Train Loss: 0.1327 - Val Acc: 0.8261
2026-04-05 05:54:42,622 - INFO - Epoch 17/100 - Train Loss: 0.1421 - Val Acc: 0.8261
2026-04-05 05:54:42,947 - INFO - Epoch 18/100 - Train Loss: 0.1322 - Val Acc: 0.8261
2026-04-05 05:54:43,269 - INFO - Epoch 19/100 - Train Loss: 0.1279 - Val Acc: 0.8116
2026-04-05 05:54:43,598 - INFO - Epoch 20/100 - Train Loss: 0.1218 - Val Acc: 0.8116
2026-04-05 05:54:43,930 - INFO - Epoch 21/100 - Train Loss: 0.1312 - Val Acc: 0.8261
2026-04-05 05:54:44,260 - INFO - Epoch 22/100 - Train Loss: 0.1140 - Val Acc: 0.8261
2026-04-05 05:54:44,599 - INFO - Epoch 23/100 - Train Loss: 0.1204 - Val Acc: 0.8406
2026-04-05 05:54:44,923 - INFO - Epoch 24/100 - Train Loss: 0.1143 - Val Acc: 0.8116
2026-04-05 05:54:45,247 - INFO - Epoch 25/100 - Train Loss: 0.1126 - Val Acc: 0.8116
2026-04-05 05:54:45,570 - INFO - Epoch 26/100 - Train Loss: 0.1113 - Val Acc: 0.8116
2026-04-05 05:54:45,889 - INFO - Epoch 27/100 - Train Loss: 0.1063 - Val Acc: 0.8116
2026-04-05 05:54:46,211 - INFO - Epoch 28/100 - Train Loss: 0.0991 - Val Acc: 0.8116
2026-04-05 05:54:46,536 - INFO - Epoch 29/100 - Train Loss: 0.0969 - Val Acc: 0.8116
2026-04-05 05:54:46,869 - INFO - Epoch 30/100 - Train Loss: 0.1108 - Val Acc: 0.8116
2026-04-05 05:54:47,194 - INFO - Epoch 31/100 - Train Loss: 0.1102 - Val Acc: 0.8261
2026-04-05 05:54:47,526 - INFO - Epoch 32/100 - Train Loss: 0.1095 - Val Acc: 0.8261
2026-04-05 05:54:47,851 - INFO - Epoch 33/100 - Train Loss: 0.0953 - Val Acc: 0.8406
2026-04-05 05:54:48,169 - INFO - Epoch 34/100 - Train Loss: 0.0989 - Val Acc: 0.8116
2026-04-05 05:54:48,503 - INFO - Epoch 35/100 - Train Loss: 0.0922 - Val Acc: 0.8261
2026-04-05 05:54:48,830 - INFO - Epoch 36/100 - Train Loss: 0.0915 - Val Acc: 0.8261
2026-04-05 05:54:49,162 - INFO - Epoch 37/100 - Train Loss: 0.0950 - Val Acc: 0.8261
2026-04-05 05:54:49,502 - INFO - Epoch 38/100 - Train Loss: 0.0890 - Val Acc: 0.8261
2026-04-05 05:54:49,826 - INFO - Epoch 39/100 - Train Loss: 0.0873 - Val Acc: 0.8406
2026-04-05 05:54:50,166 - INFO - Epoch 40/100 - Train Loss: 0.0898 - Val Acc: 0.8261
2026-04-05 05:54:50,507 - INFO - Epoch 41/100 - Train Loss: 0.1038 - Val Acc: 0.8261
2026-04-05 05:54:50,829 - INFO - Epoch 42/100 - Train Loss: 0.0865 - Val Acc: 0.8261
2026-04-05 05:54:51,164 - INFO - Epoch 43/100 - Train Loss: 0.0837 - Val Acc: 0.8261
2026-04-05 05:54:51,511 - INFO - Epoch 44/100 - Train Loss: 0.0817 - Val Acc: 0.8116
2026-04-05 05:54:51,840 - INFO - Epoch 45/100 - Train Loss: 0.0899 - Val Acc: 0.8261
2026-04-05 05:54:52,159 - INFO - Epoch 46/100 - Train Loss: 0.0849 - Val Acc: 0.8261
2026-04-05 05:54:52,488 - INFO - Epoch 47/100 - Train Loss: 0.0878 - Val Acc: 0.8261
2026-04-05 05:54:52,824 - INFO - Epoch 48/100 - Train Loss: 0.0751 - Val Acc: 0.8261
2026-04-05 05:54:53,141 - INFO - Epoch 49/100 - Train Loss: 0.0833 - Val Acc: 0.8261
2026-04-05 05:54:53,462 - INFO - Epoch 50/100 - Train Loss: 0.0734 - Val Acc: 0.8406
2026-04-05 05:54:53,783 - INFO - Epoch 51/100 - Train Loss: 0.0668 - Val Acc: 0.8261
2026-04-05 05:54:54,118 - INFO - Epoch 52/100 - Train Loss: 0.0899 - Val Acc: 0.8261
2026-04-05 05:54:54,451 - INFO - Epoch 53/100 - Train Loss: 0.0774 - Val Acc: 0.8261
2026-04-05 05:54:54,808 - INFO - Epoch 54/100 - Train Loss: 0.0720 - Val Acc: 0.8116
2026-04-05 05:54:55,129 - INFO - Epoch 55/100 - Train Loss: 0.0753 - Val Acc: 0.8116
2026-04-05 05:54:55,450 - INFO - Epoch 56/100 - Train Loss: 0.0818 - Val Acc: 0.8261
2026-04-05 05:54:55,773 - INFO - Epoch 57/100 - Train Loss: 0.0808 - Val Acc: 0.8261
2026-04-05 05:54:56,104 - INFO - Epoch 58/100 - Train Loss: 0.0631 - Val Acc: 0.8261
2026-04-05 05:54:56,433 - INFO - Epoch 59/100 - Train Loss: 0.0659 - Val Acc: 0.8116
2026-04-05 05:54:56,762 - INFO - Epoch 60/100 - Train Loss: 0.0683 - Val Acc: 0.8261
2026-04-05 05:54:57,071 - INFO - Epoch 61/100 - Train Loss: 0.0640 - Val Acc: 0.8116
2026-04-05 05:54:57,393 - INFO - Epoch 62/100 - Train Loss: 0.0697 - Val Acc: 0.8261
2026-04-05 05:54:57,715 - INFO - Epoch 63/100 - Train Loss: 0.0699 - Val Acc: 0.8406
2026-04-05 05:54:58,031 - INFO - Epoch 64/100 - Train Loss: 0.0675 - Val Acc: 0.8406
2026-04-05 05:54:58,358 - INFO - Epoch 65/100 - Train Loss: 0.0638 - Val Acc: 0.8261
2026-04-05 05:54:58,692 - INFO - Epoch 66/100 - Train Loss: 0.0636 - Val Acc: 0.8261
2026-04-05 05:54:59,011 - INFO - Epoch 67/100 - Train Loss: 0.0764 - Val Acc: 0.8261
2026-04-05 05:54:59,337 - INFO - Epoch 68/100 - Train Loss: 0.0654 - Val Acc: 0.8261
2026-04-05 05:54:59,673 - INFO - Epoch 69/100 - Train Loss: 0.0572 - Val Acc: 0.8116
2026-04-05 05:54:59,991 - INFO - Epoch 70/100 - Train Loss: 0.0614 - Val Acc: 0.8261
2026-04-05 05:55:00,315 - INFO - Epoch 71/100 - Train Loss: 0.0599 - Val Acc: 0.8261
2026-04-05 05:55:00,656 - INFO - Epoch 72/100 - Train Loss: 0.0428 - Val Acc: 0.8261
2026-04-05 05:55:00,987 - INFO - Epoch 73/100 - Train Loss: 0.0611 - Val Acc: 0.8261
2026-04-05 05:55:01,324 - INFO - Epoch 74/100 - Train Loss: 0.0690 - Val Acc: 0.8261
2026-04-05 05:55:01,658 - INFO - Epoch 75/100 - Train Loss: 0.0513 - Val Acc: 0.8406
2026-04-05 05:55:01,976 - INFO - Epoch 76/100 - Train Loss: 0.0555 - Val Acc: 0.8261
2026-04-05 05:55:02,304 - INFO - Epoch 77/100 - Train Loss: 0.0572 - Val Acc: 0.8406
2026-04-05 05:55:02,627 - INFO - Epoch 78/100 - Train Loss: 0.0460 - Val Acc: 0.8261
2026-04-05 05:55:02,949 - INFO - Epoch 79/100 - Train Loss: 0.0612 - Val Acc: 0.8406
2026-04-05 05:55:03,279 - INFO - Epoch 80/100 - Train Loss: 0.0504 - Val Acc: 0.8261
2026-04-05 05:55:03,617 - INFO - Epoch 81/100 - Train Loss: 0.0573 - Val Acc: 0.8261
2026-04-05 05:55:03,955 - INFO - Epoch 82/100 - Train Loss: 0.0585 - Val Acc: 0.8406
2026-04-05 05:55:04,284 - INFO - Epoch 83/100 - Train Loss: 0.0592 - Val Acc: 0.8406
2026-04-05 05:55:04,632 - INFO - Epoch 84/100 - Train Loss: 0.0567 - Val Acc: 0.8261
2026-04-05 05:55:04,952 - INFO - Epoch 85/100 - Train Loss: 0.0439 - Val Acc: 0.8261
2026-04-05 05:55:05,283 - INFO - Epoch 86/100 - Train Loss: 0.0469 - Val Acc: 0.8116
2026-04-05 05:55:05,608 - INFO - Epoch 87/100 - Train Loss: 0.0364 - Val Acc: 0.8261
2026-04-05 05:55:05,936 - INFO - Epoch 88/100 - Train Loss: 0.0530 - Val Acc: 0.8261
2026-04-05 05:55:06,259 - INFO - Epoch 89/100 - Train Loss: 0.0482 - Val Acc: 0.8261
2026-04-05 05:55:06,581 - INFO - Epoch 90/100 - Train Loss: 0.0591 - Val Acc: 0.8261
2026-04-05 05:55:06,901 - INFO - Epoch 91/100 - Train Loss: 0.0389 - Val Acc: 0.8116
2026-04-05 05:55:07,234 - INFO - Epoch 92/100 - Train Loss: 0.0513 - Val Acc: 0.8261
2026-04-05 05:55:07,570 - INFO - Epoch 93/100 - Train Loss: 0.0415 - Val Acc: 0.8261
2026-04-05 05:55:07,881 - INFO - Epoch 94/100 - Train Loss: 0.0409 - Val Acc: 0.8261
2026-04-05 05:55:08,211 - INFO - Epoch 95/100 - Train Loss: 0.0521 - Val Acc: 0.8261
2026-04-05 05:55:08,545 - INFO - Epoch 96/100 - Train Loss: 0.0453 - Val Acc: 0.8261
2026-04-05 05:55:08,865 - INFO - Epoch 97/100 - Train Loss: 0.0503 - Val Acc: 0.8261
2026-04-05 05:55:09,181 - INFO - Epoch 98/100 - Train Loss: 0.0518 - Val Acc: 0.8406
2026-04-05 05:55:09,502 - INFO - Epoch 99/100 - Train Loss: 0.0430 - Val Acc: 0.8261
2026-04-05 05:55:09,824 - INFO - Epoch 100/100 - Train Loss: 0.0527 - Val Acc: 0.8406
2026-04-05 05:55:10,186 - INFO - Fold 9 logically complete. Tensor memory bounds cleared cleanly.
2026-04-05 05:55:10,190 - INFO - Original class distribution: [345 276]
2026-04-05 05:55:10,191 - INFO - Training device bound securely to: cuda
2026-04-05 05:55:10,220 - INFO - After SMOTE-ENN deployment: [345 296]

Fold 10:   0%|          | 0/100 [00:00<?, ?it/s]

2026-04-05 05:55:10,566 - INFO - Epoch 1/100 - Train Loss: 0.5873 - Val Acc: 0.8986
2026-04-05 05:55:10,886 - INFO - Epoch 2/100 - Train Loss: 0.3697 - Val Acc: 0.8986
2026-04-05 05:55:11,227 - INFO - Epoch 3/100 - Train Loss: 0.2632 - Val Acc: 0.9130
2026-04-05 05:55:11,555 - INFO - Epoch 4/100 - Train Loss: 0.2392 - Val Acc: 0.9130
2026-04-05 05:55:11,880 - INFO - Epoch 5/100 - Train Loss: 0.1968 - Val Acc: 0.9130
2026-04-05 05:55:12,200 - INFO - Epoch 6/100 - Train Loss: 0.1949 - Val Acc: 0.9420
2026-04-05 05:55:12,522 - INFO - Epoch 7/100 - Train Loss: 0.1792 - Val Acc: 0.9275
2026-04-05 05:55:12,852 - INFO - Epoch 8/100 - Train Loss: 0.1870 - Val Acc: 0.9420
2026-04-05 05:55:13,166 - INFO - Epoch 9/100 - Train Loss: 0.1613 - Val Acc: 0.9420
2026-04-05 05:55:13,482 - INFO - Epoch 10/100 - Train Loss: 0.1655 - Val Acc: 0.9420
2026-04-05 05:55:13,817 - INFO - Epoch 11/100 - Train Loss: 0.1684 - Val Acc: 0.9420
2026-04-05 05:55:14,158 - INFO - Epoch 12/100 - Train Loss: 0.1632 - Val Acc: 0.9420
2026-04-05 05:55:14,497 - INFO - Epoch 13/100 - Train Loss: 0.1580 - Val Acc: 0.9420
2026-04-05 05:55:14,836 - INFO - Epoch 14/100 - Train Loss: 0.1552 - Val Acc: 0.9420
2026-04-05 05:55:15,152 - INFO - Epoch 15/100 - Train Loss: 0.1493 - Val Acc: 0.9275
2026-04-05 05:55:15,484 - INFO - Epoch 16/100 - Train Loss: 0.1550 - Val Acc: 0.9130
2026-04-05 05:55:15,812 - INFO - Epoch 17/100 - Train Loss: 0.1420 - Val Acc: 0.9420
2026-04-05 05:55:16,128 - INFO - Epoch 18/100 - Train Loss: 0.1325 - Val Acc: 0.9420
2026-04-05 05:55:16,451 - INFO - Epoch 19/100 - Train Loss: 0.1352 - Val Acc: 0.9420
2026-04-05 05:55:16,783 - INFO - Epoch 20/100 - Train Loss: 0.1331 - Val Acc: 0.9420
2026-04-05 05:55:17,106 - INFO - Epoch 21/100 - Train Loss: 0.1206 - Val Acc: 0.9420
2026-04-05 05:55:17,424 - INFO - Epoch 22/100 - Train Loss: 0.1196 - Val Acc: 0.9420
2026-04-05 05:55:17,757 - INFO - Epoch 23/100 - Train Loss: 0.1487 - Val Acc: 0.9420
2026-04-05 05:55:18,083 - INFO - Epoch 24/100 - Train Loss: 0.1346 - Val Acc: 0.9420
2026-04-05 05:55:18,405 - INFO - Epoch 25/100 - Train Loss: 0.1444 - Val Acc: 0.9420
2026-04-05 05:55:18,737 - INFO - Epoch 26/100 - Train Loss: 0.1221 - Val Acc: 0.9420
2026-04-05 05:55:19,060 - INFO - Epoch 27/100 - Train Loss: 0.1198 - Val Acc: 0.9420
2026-04-05 05:55:19,387 - INFO - Epoch 28/100 - Train Loss: 0.1277 - Val Acc: 0.9420
2026-04-05 05:55:19,716 - INFO - Epoch 29/100 - Train Loss: 0.1222 - Val Acc: 0.9420
2026-04-05 05:55:20,044 - INFO - Epoch 30/100 - Train Loss: 0.1227 - Val Acc: 0.9420
2026-04-05 05:55:20,363 - INFO - Epoch 31/100 - Train Loss: 0.1045 - Val Acc: 0.9420
2026-04-05 05:55:20,679 - INFO - Epoch 32/100 - Train Loss: 0.1102 - Val Acc: 0.9420
2026-04-05 05:55:21,006 - INFO - Epoch 33/100 - Train Loss: 0.1140 - Val Acc: 0.9420
2026-04-05 05:55:21,342 - INFO - Epoch 34/100 - Train Loss: 0.1064 - Val Acc: 0.9420
2026-04-05 05:55:21,662 - INFO - Epoch 35/100 - Train Loss: 0.1139 - Val Acc: 0.9420
2026-04-05 05:55:21,985 - INFO - Epoch 36/100 - Train Loss: 0.1216 - Val Acc: 0.9275
2026-04-05 05:55:22,306 - INFO - Epoch 37/100 - Train Loss: 0.1128 - Val Acc: 0.9275
2026-04-05 05:55:22,633 - INFO - Epoch 38/100 - Train Loss: 0.1012 - Val Acc: 0.9420
2026-04-05 05:55:22,969 - INFO - Epoch 39/100 - Train Loss: 0.1195 - Val Acc: 0.9420
2026-04-05 05:55:23,294 - INFO - Epoch 40/100 - Train Loss: 0.1155 - Val Acc: 0.9420
2026-04-05 05:55:23,622 - INFO - Epoch 41/100 - Train Loss: 0.0949 - Val Acc: 0.9420
2026-04-05 05:55:23,958 - INFO - Epoch 42/100 - Train Loss: 0.1078 - Val Acc: 0.9275
2026-04-05 05:55:24,302 - INFO - Epoch 43/100 - Train Loss: 0.0977 - Val Acc: 0.9275
2026-04-05 05:55:24,658 - INFO - Epoch 44/100 - Train Loss: 0.1006 - Val Acc: 0.9275
2026-04-05 05:55:24,991 - INFO - Epoch 45/100 - Train Loss: 0.1043 - Val Acc: 0.9275
2026-04-05 05:55:25,321 - INFO - Epoch 46/100 - Train Loss: 0.0969 - Val Acc: 0.9275
2026-04-05 05:55:25,644 - INFO - Epoch 47/100 - Train Loss: 0.0997 - Val Acc: 0.9275
2026-04-05 05:55:25,967 - INFO - Epoch 48/100 - Train Loss: 0.0995 - Val Acc: 0.8986
2026-04-05 05:55:26,284 - INFO - Epoch 49/100 - Train Loss: 0.0888 - Val Acc: 0.9275
2026-04-05 05:55:26,618 - INFO - Epoch 50/100 - Train Loss: 0.1000 - Val Acc: 0.9130
2026-04-05 05:55:26,938 - INFO - Epoch 51/100 - Train Loss: 0.0844 - Val Acc: 0.9420
2026-04-05 05:55:27,259 - INFO - Epoch 52/100 - Train Loss: 0.0918 - Val Acc: 0.9130
2026-04-05 05:55:27,583 - INFO - Epoch 53/100 - Train Loss: 0.0902 - Val Acc: 0.9130
2026-04-05 05:55:27,906 - INFO - Epoch 54/100 - Train Loss: 0.0909 - Val Acc: 0.9130
2026-04-05 05:55:28,242 - INFO - Epoch 55/100 - Train Loss: 0.0941 - Val Acc: 0.9130
2026-04-05 05:55:28,581 - INFO - Epoch 56/100 - Train Loss: 0.0988 - Val Acc: 0.9275
2026-04-05 05:55:28,904 - INFO - Epoch 57/100 - Train Loss: 0.0814 - Val Acc: 0.9130
2026-04-05 05:55:29,243 - INFO - Epoch 58/100 - Train Loss: 0.0876 - Val Acc: 0.9130
2026-04-05 05:55:29,566 - INFO - Epoch 59/100 - Train Loss: 0.0837 - Val Acc: 0.9130
2026-04-05 05:55:29,884 - INFO - Epoch 60/100 - Train Loss: 0.0875 - Val Acc: 0.9130
2026-04-05 05:55:30,224 - INFO - Epoch 61/100 - Train Loss: 0.0781 - Val Acc: 0.9130
2026-04-05 05:55:30,545 - INFO - Epoch 62/100 - Train Loss: 0.0654 - Val Acc: 0.9130
2026-04-05 05:55:30,872 - INFO - Epoch 63/100 - Train Loss: 0.0844 - Val Acc: 0.9130
2026-04-05 05:55:31,193 - INFO - Epoch 64/100 - Train Loss: 0.0698 - Val Acc: 0.9130
2026-04-05 05:55:31,520 - INFO - Epoch 65/100 - Train Loss: 0.0708 - Val Acc: 0.9130
2026-04-05 05:55:31,838 - INFO - Epoch 66/100 - Train Loss: 0.0950 - Val Acc: 0.9130
2026-04-05 05:55:32,160 - INFO - Epoch 67/100 - Train Loss: 0.0742 - Val Acc: 0.9130
2026-04-05 05:55:32,497 - INFO - Epoch 68/100 - Train Loss: 0.0778 - Val Acc: 0.9130
2026-04-05 05:55:32,824 - INFO - Epoch 69/100 - Train Loss: 0.0729 - Val Acc: 0.9130
2026-04-05 05:55:33,145 - INFO - Epoch 70/100 - Train Loss: 0.0720 - Val Acc: 0.9130
2026-04-05 05:55:33,469 - INFO - Epoch 71/100 - Train Loss: 0.0651 - Val Acc: 0.9130
2026-04-05 05:55:33,803 - INFO - Epoch 72/100 - Train Loss: 0.0647 - Val Acc: 0.9130
2026-04-05 05:55:34,131 - INFO - Epoch 73/100 - Train Loss: 0.0575 - Val Acc: 0.9130
2026-04-05 05:55:34,483 - INFO - Epoch 74/100 - Train Loss: 0.0642 - Val Acc: 0.9130
2026-04-05 05:55:34,825 - INFO - Epoch 75/100 - Train Loss: 0.0640 - Val Acc: 0.9130
2026-04-05 05:55:35,142 - INFO - Epoch 76/100 - Train Loss: 0.0610 - Val Acc: 0.9130
2026-04-05 05:55:35,465 - INFO - Epoch 77/100 - Train Loss: 0.0630 - Val Acc: 0.9275
2026-04-05 05:55:35,779 - INFO - Epoch 78/100 - Train Loss: 0.0657 - Val Acc: 0.9130
2026-04-05 05:55:36,100 - INFO - Epoch 79/100 - Train Loss: 0.0648 - Val Acc: 0.9130
2026-04-05 05:55:36,437 - INFO - Epoch 80/100 - Train Loss: 0.0587 - Val Acc: 0.9130
2026-04-05 05:55:36,783 - INFO - Epoch 81/100 - Train Loss: 0.0548 - Val Acc: 0.9130
2026-04-05 05:55:37,114 - INFO - Epoch 82/100 - Train Loss: 0.0555 - Val Acc: 0.9130
2026-04-05 05:55:37,449 - INFO - Epoch 83/100 - Train Loss: 0.0722 - Val Acc: 0.9130
2026-04-05 05:55:37,769 - INFO - Epoch 84/100 - Train Loss: 0.0855 - Val Acc: 0.9130
2026-04-05 05:55:38,092 - INFO - Epoch 85/100 - Train Loss: 0.0655 - Val Acc: 0.9130
2026-04-05 05:55:38,416 - INFO - Epoch 86/100 - Train Loss: 0.0706 - Val Acc: 0.9130
2026-04-05 05:55:38,755 - INFO - Epoch 87/100 - Train Loss: 0.0604 - Val Acc: 0.9130
2026-04-05 05:55:39,087 - INFO - Epoch 88/100 - Train Loss: 0.0524 - Val Acc: 0.9130
2026-04-05 05:55:39,409 - INFO - Epoch 89/100 - Train Loss: 0.0514 - Val Acc: 0.9130
2026-04-05 05:55:39,730 - INFO - Epoch 90/100 - Train Loss: 0.0603 - Val Acc: 0.9130
2026-04-05 05:55:40,062 - INFO - Epoch 91/100 - Train Loss: 0.0519 - Val Acc: 0.9130
2026-04-05 05:55:40,381 - INFO - Epoch 92/100 - Train Loss: 0.0540 - Val Acc: 0.9130
2026-04-05 05:55:40,705 - INFO - Epoch 93/100 - Train Loss: 0.0475 - Val Acc: 0.9130
2026-04-05 05:55:41,037 - INFO - Epoch 94/100 - Train Loss: 0.0588 - Val Acc: 0.9130
2026-04-05 05:55:41,355 - INFO - Epoch 95/100 - Train Loss: 0.0450 - Val Acc: 0.9130
2026-04-05 05:55:41,676 - INFO - Epoch 96/100 - Train Loss: 0.0480 - Val Acc: 0.9130
2026-04-05 05:55:41,991 - INFO - Epoch 97/100 - Train Loss: 0.0663 - Val Acc: 0.9130
2026-04-05 05:55:42,314 - INFO - Epoch 98/100 - Train Loss: 0.0788 - Val Acc: 0.9275
2026-04-05 05:55:42,645 - INFO - Epoch 99/100 - Train Loss: 0.0518 - Val Acc: 0.9130
2026-04-05 05:55:42,970 - INFO - Epoch 100/100 - Train Loss: 0.0644 - Val Acc: 0.9275
2026-04-05 05:55:43,331 - INFO - Fold 10 logically complete. Tensor memory bounds cleared cleanly.
2026-04-05 05:55:43,348 - INFO - ✓ Completed MLP_smoteenn -> Acc: 0.8812
2026-04-05 05:55:43,349 - INFO -
EXPERIMENT: LSTM_BASELINE | australian | SMOTE-ENN: False

Australian | LSTM | BASELINE:   0%|          | 0/10 [00:00<?, ?it/s]

2026-04-05 05:55:43,361 - INFO - Original class distribution: [344 277]
2026-04-05 05:55:43,362 - INFO - Training device bound securely to: cuda

Fold 1:   0%|          | 0/100 [00:00<?, ?it/s]

2026-04-05 05:55:43,666 - INFO - Epoch 1/100 - Train Loss: 0.5631 - Val Acc: 0.8261
2026-04-05 05:55:43,931 - INFO - Epoch 2/100 - Train Loss: 0.4131 - Val Acc: 0.8696
2026-04-05 05:55:44,211 - INFO - Epoch 3/100 - Train Loss: 0.3717 - Val Acc: 0.8841
2026-04-05 05:55:44,495 - INFO - Epoch 4/100 - Train Loss: 0.3502 - Val Acc: 0.8986
2026-04-05 05:55:44,779 - INFO - Epoch 5/100 - Train Loss: 0.3402 - Val Acc: 0.8986
2026-04-05 05:55:45,051 - INFO - Epoch 6/100 - Train Loss: 0.3274 - Val Acc: 0.8986
2026-04-05 05:55:45,316 - INFO - Epoch 7/100 - Train Loss: 0.3194 - Val Acc: 0.8986
2026-04-05 05:55:45,595 - INFO - Epoch 8/100 - Train Loss: 0.3177 - Val Acc: 0.8986
2026-04-05 05:55:45,879 - INFO - Epoch 9/100 - Train Loss: 0.3132 - Val Acc: 0.8986
2026-04-05 05:55:46,145 - INFO - Epoch 10/100 - Train Loss: 0.3083 - Val Acc: 0.8986
2026-04-05 05:55:46,416 - INFO - Epoch 11/100 - Train Loss: 0.3064 - Val Acc: 0.8986
2026-04-05 05:55:46,697 - INFO - Epoch 12/100 - Train Loss: 0.3065 - Val Acc: 0.8986
2026-04-05 05:55:46,982 - INFO - Epoch 13/100 - Train Loss: 0.3015 - Val Acc: 0.9130
2026-04-05 05:55:47,258 - INFO - Epoch 14/100 - Train Loss: 0.3012 - Val Acc: 0.9130
2026-04-05 05:55:47,526 - INFO - Epoch 15/100 - Train Loss: 0.2995 - Val Acc: 0.9130
2026-04-05 05:55:47,806 - INFO - Epoch 16/100 - Train Loss: 0.2965 - Val Acc: 0.9130
2026-04-05 05:55:48,084 - INFO - Epoch 17/100 - Train Loss: 0.2975 - Val Acc: 0.8986
2026-04-05 05:55:48,351 - INFO - Epoch 18/100 - Train Loss: 0.2950 - Val Acc: 0.9130
2026-04-05 05:55:48,616 - INFO - Epoch 19/100 - Train Loss: 0.2912 - Val Acc: 0.9130
2026-04-05 05:55:48,885 - INFO - Epoch 20/100 - Train Loss: 0.2916 - Val Acc: 0.9130
2026-04-05 05:55:49,150 - INFO - Epoch 21/100 - Train Loss: 0.2940 - Val Acc: 0.9130
2026-04-05 05:55:49,431 - INFO - Epoch 22/100 - Train Loss: 0.2883 - Val Acc: 0.9130
2026-04-05 05:55:49,707 - INFO - Epoch 23/100 - Train Loss: 0.2841 - Val Acc: 0.9130
2026-04-05 05:55:49,981 - INFO - Epoch 24/100 - Train Loss: 0.2845 - Val Acc: 0.9130
2026-04-05 05:55:50,267 - INFO - Epoch 25/100 - Train Loss: 0.2847 - Val Acc: 0.9130
2026-04-05 05:55:50,544 - INFO - Epoch 26/100 - Train Loss: 0.2839 - Val Acc: 0.9130
2026-04-05 05:55:50,826 - INFO - Epoch 27/100 - Train Loss: 0.2816 - Val Acc: 0.9130
2026-04-05 05:55:51,096 - INFO - Epoch 28/100 - Train Loss: 0.2800 - Val Acc: 0.9130
2026-04-05 05:55:51,365 - INFO - Epoch 29/100 - Train Loss: 0.2806 - Val Acc: 0.9130
2026-04-05 05:55:51,641 - INFO - Epoch 30/100 - Train Loss: 0.2811 - Val Acc: 0.9130
2026-04-05 05:55:51,908 - INFO - Epoch 31/100 - Train Loss: 0.2779 - Val Acc: 0.9130
2026-04-05 05:55:52,169 - INFO - Epoch 32/100 - Train Loss: 0.2789 - Val Acc: 0.9130
2026-04-05 05:55:52,431 - INFO - Epoch 33/100 - Train Loss: 0.2749 - Val Acc: 0.9130
2026-04-05 05:55:52,692 - INFO - Epoch 34/100 - Train Loss: 0.2758 - Val Acc: 0.9130
2026-04-05 05:55:52,955 - INFO - Epoch 35/100 - Train Loss: 0.2747 - Val Acc: 0.9130
2026-04-05 05:55:53,219 - INFO - Epoch 36/100 - Train Loss: 0.2709 - Val Acc: 0.9130
2026-04-05 05:55:53,505 - INFO - Epoch 37/100 - Train Loss: 0.2728 - Val Acc: 0.9130
2026-04-05 05:55:53,794 - INFO - Epoch 38/100 - Train Loss: 0.2709 - Val Acc: 0.9130
2026-04-05 05:55:54,072 - INFO - Epoch 39/100 - Train Loss: 0.2709 - Val Acc: 0.9130
2026-04-05 05:55:54,358 - INFO - Epoch 40/100 - Train Loss: 0.2690 - Val Acc: 0.9130
2026-04-05 05:55:54,663 - INFO - Epoch 41/100 - Train Loss: 0.2675 - Val Acc: 0.9130
2026-04-05 05:55:54,946 - INFO - Epoch 42/100 - Train Loss: 0.2671 - Val Acc: 0.8986
2026-04-05 05:55:55,223 - INFO - Epoch 43/100 - Train Loss: 0.2629 - Val Acc: 0.8986
2026-04-05 05:55:55,500 - INFO - Epoch 44/100 - Train Loss: 0.2655 - Val Acc: 0.8986
2026-04-05 05:55:55,777 - INFO - Epoch 45/100 - Train Loss: 0.2621 - Val Acc: 0.9130
2026-04-05 05:55:56,046 - INFO - Epoch 46/100 - Train Loss: 0.2614 - Val Acc: 0.9130
2026-04-05 05:55:56,325 - INFO - Epoch 47/100 - Train Loss: 0.2633 - Val Acc: 0.8841
2026-04-05 05:55:56,592 - INFO - Epoch 48/100 - Train Loss: 0.2609 - Val Acc: 0.8841
2026-04-05 05:55:56,864 - INFO - Epoch 49/100 - Train Loss: 0.2564 - Val Acc: 0.8841
2026-04-05 05:55:57,135 - INFO - Epoch 50/100 - Train Loss: 0.2599 - Val Acc: 0.8841
2026-04-05 05:55:57,406 - INFO - Epoch 51/100 - Train Loss: 0.2576 - Val Acc: 0.8841
2026-04-05 05:55:57,698 - INFO - Epoch 52/100 - Train Loss: 0.2573 - Val Acc: 0.8841
2026-04-05 05:55:57,966 - INFO - Epoch 53/100 - Train Loss: 0.2543 - Val Acc: 0.8841
2026-04-05 05:55:58,236 - INFO - Epoch 54/100 - Train Loss: 0.2560 - Val Acc: 0.8841
2026-04-05 05:55:58,520 - INFO - Epoch 55/100 - Train Loss: 0.2558 - Val Acc: 0.8841
2026-04-05 05:55:58,794 - INFO - Epoch 56/100 - Train Loss: 0.2525 - Val Acc: 0.8841
2026-04-05 05:55:59,058 - INFO - Epoch 57/100 - Train Loss: 0.2546 - Val Acc: 0.8841
2026-04-05 05:55:59,340 - INFO - Epoch 58/100 - Train Loss: 0.2523 - Val Acc: 0.8841
2026-04-05 05:55:59,614 - INFO - Epoch 59/100 - Train Loss: 0.2526 - Val Acc: 0.8841
2026-04-05 05:55:59,902 - INFO - Epoch 60/100 - Train Loss: 0.2533 - Val Acc: 0.8841
2026-04-05 05:56:00,182 - INFO - Epoch 61/100 - Train Loss: 0.2507 - Val Acc: 0.8841
2026-04-05 05:56:00,462 - INFO - Epoch 62/100 - Train Loss: 0.2499 - Val Acc: 0.8841
2026-04-05 05:56:00,730 - INFO - Epoch 63/100 - Train Loss: 0.2466 - Val Acc: 0.8841
2026-04-05 05:56:01,007 - INFO - Epoch 64/100 - Train Loss: 0.2467 - Val Acc: 0.8841
2026-04-05 05:56:01,279 - INFO - Epoch 65/100 - Train Loss: 0.2455 - Val Acc: 0.8841
2026-04-05 05:56:01,548 - INFO - Epoch 66/100 - Train Loss: 0.2477 - Val Acc: 0.8841
2026-04-05 05:56:01,820 - INFO - Epoch 67/100 - Train Loss: 0.2489 - Val Acc: 0.8841
2026-04-05 05:56:02,087 - INFO - Epoch 68/100 - Train Loss: 0.2436 - Val Acc: 0.8841
2026-04-05 05:56:02,360 - INFO - Epoch 69/100 - Train Loss: 0.2391 - Val Acc: 0.8841
2026-04-05 05:56:02,627 - INFO - Epoch 70/100 - Train Loss: 0.2430 - Val Acc: 0.8841
2026-04-05 05:56:02,892 - INFO - Epoch 71/100 - Train Loss: 0.2451 - Val Acc: 0.8841
2026-04-05 05:56:03,171 - INFO - Epoch 72/100 - Train Loss: 0.2352 - Val Acc: 0.8841
2026-04-05 05:56:03,434 - INFO - Epoch 73/100 - Train Loss: 0.2430 - Val Acc: 0.8841
2026-04-05 05:56:03,698 - INFO - Epoch 74/100 - Train Loss: 0.2396 - Val Acc: 0.8841
2026-04-05 05:56:03,977 - INFO - Epoch 75/100 - Train Loss: 0.2389 - Val Acc: 0.8841
2026-04-05 05:56:04,255 - INFO - Epoch 76/100 - Train Loss: 0.2417 - Val Acc: 0.8841
2026-04-05 05:56:04,556 - INFO - Epoch 77/100 - Train Loss: 0.2368 - Val Acc: 0.8841
2026-04-05 05:56:04,837 - INFO - Epoch 78/100 - Train Loss: 0.2391 - Val Acc: 0.8841
2026-04-05 05:56:05,100 - INFO - Epoch 79/100 - Train Loss: 0.2408 - Val Acc: 0.8841
2026-04-05 05:56:05,371 - INFO - Epoch 80/100 - Train Loss: 0.2377 - Val Acc: 0.8841
2026-04-05 05:56:05,642 - INFO - Epoch 81/100 - Train Loss: 0.2347 - Val Acc: 0.8841
2026-04-05 05:56:05,907 - INFO - Epoch 82/100 - Train Loss: 0.2359 - Val Acc: 0.8841
2026-04-05 05:56:06,190 - INFO - Epoch 83/100 - Train Loss: 0.2323 - Val Acc: 0.8841
2026-04-05 05:56:06,465 - INFO - Epoch 84/100 - Train Loss: 0.2312 - Val Acc: 0.8841
2026-04-05 05:56:06,744 - INFO - Epoch 85/100 - Train Loss: 0.2306 - Val Acc: 0.8841
2026-04-05 05:56:07,013 - INFO - Epoch 86/100 - Train Loss: 0.2336 - Val Acc: 0.8841
2026-04-05 05:56:07,292 - INFO - Epoch 87/100 - Train Loss: 0.2279 - Val Acc: 0.8841
2026-04-05 05:56:07,583 - INFO - Epoch 88/100 - Train Loss: 0.2286 - Val Acc: 0.8841
2026-04-05 05:56:07,842 - INFO - Epoch 89/100 - Train Loss: 0.2292 - Val Acc: 0.8841
2026-04-05 05:56:08,113 - INFO - Epoch 90/100 - Train Loss: 0.2304 - Val Acc: 0.8841
2026-04-05 05:56:08,393 - INFO - Epoch 91/100 - Train Loss: 0.2306 - Val Acc: 0.8841
2026-04-05 05:56:08,678 - INFO - Epoch 92/100 - Train Loss: 0.2265 - Val Acc: 0.8841
2026-04-05 05:56:08,961 - INFO - Epoch 93/100 - Train Loss: 0.2294 - Val Acc: 0.8841
2026-04-05 05:56:09,225 - INFO - Epoch 94/100 - Train Loss: 0.2254 - Val Acc: 0.8841
2026-04-05 05:56:09,495 - INFO - Epoch 95/100 - Train Loss: 0.2283 - Val Acc: 0.8841
2026-04-05 05:56:09,760 - INFO - Epoch 96/100 - Train Loss: 0.2260 - Val Acc: 0.8841
2026-04-05 05:56:10,036 - INFO - Epoch 97/100 - Train Loss: 0.2284 - Val Acc: 0.8841
2026-04-05 05:56:10,316 - INFO - Epoch 98/100 - Train Loss: 0.2210 - Val Acc: 0.8841
2026-04-05 05:56:10,596 - INFO - Epoch 99/100 - Train Loss: 0.2236 - Val Acc: 0.8841
2026-04-05 05:56:10,901 - INFO - Epoch 100/100 - Train Loss: 0.2217 - Val Acc: 0.8841
2026-04-05 05:56:11,281 - INFO - Fold 1 logically complete. Tensor memory bounds cleared cleanly.
2026-04-05 05:56:11,286 - INFO - Original class distribution: [344 277]
2026-04-05 05:56:11,286 - INFO - Training device bound securely to: cuda

Fold 2:   0%|          | 0/100 [00:00<?, ?it/s]

2026-04-05 05:56:11,597 - INFO - Epoch 1/100 - Train Loss: 0.5594 - Val Acc: 0.7681
2026-04-05 05:56:11,867 - INFO - Epoch 2/100 - Train Loss: 0.4007 - Val Acc: 0.7971
2026-04-05 05:56:12,142 - INFO - Epoch 3/100 - Train Loss: 0.3563 - Val Acc: 0.8116
2026-04-05 05:56:12,420 - INFO - Epoch 4/100 - Train Loss: 0.3404 - Val Acc: 0.8261
2026-04-05 05:56:12,691 - INFO - Epoch 5/100 - Train Loss: 0.3257 - Val Acc: 0.8406
2026-04-05 05:56:12,968 - INFO - Epoch 6/100 - Train Loss: 0.3195 - Val Acc: 0.8696
2026-04-05 05:56:13,247 - INFO - Epoch 7/100 - Train Loss: 0.3147 - Val Acc: 0.8696
2026-04-05 05:56:13,520 - INFO - Epoch 8/100 - Train Loss: 0.3085 - Val Acc: 0.8986
2026-04-05 05:56:13,798 - INFO - Epoch 9/100 - Train Loss: 0.3073 - Val Acc: 0.8986
2026-04-05 05:56:14,068 - INFO - Epoch 10/100 - Train Loss: 0.3040 - Val Acc: 0.8986
2026-04-05 05:56:14,333 - INFO - Epoch 11/100 - Train Loss: 0.3001 - Val Acc: 0.8986
2026-04-05 05:56:14,629 - INFO - Epoch 12/100 - Train Loss: 0.2972 - Val Acc: 0.8986
2026-04-05 05:56:14,902 - INFO - Epoch 13/100 - Train Loss: 0.2965 - Val Acc: 0.8986
2026-04-05 05:56:15,177 - INFO - Epoch 14/100 - Train Loss: 0.2961 - Val Acc: 0.8986
2026-04-05 05:56:15,435 - INFO - Epoch 15/100 - Train Loss: 0.2963 - Val Acc: 0.8986
2026-04-05 05:56:15,713 - INFO - Epoch 16/100 - Train Loss: 0.2907 - Val Acc: 0.8986
2026-04-05 05:56:15,993 - INFO - Epoch 17/100 - Train Loss: 0.2916 - Val Acc: 0.8986
2026-04-05 05:56:16,264 - INFO - Epoch 18/100 - Train Loss: 0.2890 - Val Acc: 0.8986
2026-04-05 05:56:16,544 - INFO - Epoch 19/100 - Train Loss: 0.2873 - Val Acc: 0.8986
2026-04-05 05:56:16,836 - INFO - Epoch 20/100 - Train Loss: 0.2882 - Val Acc: 0.8986
2026-04-05 05:56:17,107 - INFO - Epoch 21/100 - Train Loss: 0.2857 - Val Acc: 0.8986
2026-04-05 05:56:17,374 - INFO - Epoch 22/100 - Train Loss: 0.2857 - Val Acc: 0.8986
2026-04-05 05:56:17,642 - INFO - Epoch 23/100 - Train Loss: 0.2828 - Val Acc: 0.8986
2026-04-05 05:56:17,923 - INFO - Epoch 24/100 - Train Loss: 0.2802 - Val Acc: 0.8986
2026-04-05 05:56:18,193 - INFO - Epoch 25/100 - Train Loss: 0.2810 - Val Acc: 0.8986
2026-04-05 05:56:18,470 - INFO - Epoch 26/100 - Train Loss: 0.2781 - Val Acc: 0.8986
2026-04-05 05:56:18,755 - INFO - Epoch 27/100 - Train Loss: 0.2746 - Val Acc: 0.8986
2026-04-05 05:56:19,026 - INFO - Epoch 28/100 - Train Loss: 0.2753 - Val Acc: 0.8986
2026-04-05 05:56:19,292 - INFO - Epoch 29/100 - Train Loss: 0.2786 - Val Acc: 0.8986
2026-04-05 05:56:19,561 - INFO - Epoch 30/100 - Train Loss: 0.2724 - Val Acc: 0.8986
2026-04-05 05:56:19,836 - INFO - Epoch 31/100 - Train Loss: 0.2743 - Val Acc: 0.8986
2026-04-05 05:56:20,110 - INFO - Epoch 32/100 - Train Loss: 0.2687 - Val Acc: 0.8986
2026-04-05 05:56:20,380 - INFO - Epoch 33/100 - Train Loss: 0.2722 - Val Acc: 0.8986
2026-04-05 05:56:20,661 - INFO - Epoch 34/100 - Train Loss: 0.2685 - Val Acc: 0.8841
2026-04-05 05:56:20,931 - INFO - Epoch 35/100 - Train Loss: 0.2695 - Val Acc: 0.8841
2026-04-05 05:56:21,211 - INFO - Epoch 36/100 - Train Loss: 0.2687 - Val Acc: 0.8841
2026-04-05 05:56:21,482 - INFO - Epoch 37/100 - Train Loss: 0.2671 - Val Acc: 0.8841
2026-04-05 05:56:21,748 - INFO - Epoch 38/100 - Train Loss: 0.2673 - Val Acc: 0.8841
2026-04-05 05:56:22,026 - INFO - Epoch 39/100 - Train Loss: 0.2641 - Val Acc: 0.8986
2026-04-05 05:56:22,302 - INFO - Epoch 40/100 - Train Loss: 0.2623 - Val Acc: 0.8841
2026-04-05 05:56:22,584 - INFO - Epoch 41/100 - Train Loss: 0.2618 - Val Acc: 0.8841
2026-04-05 05:56:22,851 - INFO - Epoch 42/100 - Train Loss: 0.2621 - Val Acc: 0.8841
2026-04-05 05:56:23,124 - INFO - Epoch 43/100 - Train Loss: 0.2611 - Val Acc: 0.8841
2026-04-05 05:56:23,387 - INFO - Epoch 44/100 - Train Loss: 0.2620 - Val Acc: 0.8841
2026-04-05 05:56:23,662 - INFO - Epoch 45/100 - Train Loss: 0.2556 - Val Acc: 0.8841
2026-04-05 05:56:23,932 - INFO - Epoch 46/100 - Train Loss: 0.2554 - Val Acc: 0.8841
2026-04-05 05:56:24,222 - INFO - Epoch 47/100 - Train Loss: 0.2612 - Val Acc: 0.8841
2026-04-05 05:56:24,502 - INFO - Epoch 48/100 - Train Loss: 0.2564 - Val Acc: 0.8841
2026-04-05 05:56:24,786 - INFO - Epoch 49/100 - Train Loss: 0.2557 - Val Acc: 0.8841
2026-04-05 05:56:25,056 - INFO - Epoch 50/100 - Train Loss: 0.2548 - Val Acc: 0.8841
2026-04-05 05:56:25,327 - INFO - Epoch 51/100 - Train Loss: 0.2537 - Val Acc: 0.8986
2026-04-05 05:56:25,610 - INFO - Epoch 52/100 - Train Loss: 0.2526 - Val Acc: 0.8986
2026-04-05 05:56:25,882 - INFO - Epoch 53/100 - Train Loss: 0.2513 - Val Acc: 0.8841
2026-04-05 05:56:26,156 - INFO - Epoch 54/100 - Train Loss: 0.2494 - Val Acc: 0.8986
2026-04-05 05:56:26,423 - INFO - Epoch 55/100 - Train Loss: 0.2465 - Val Acc: 0.8841
2026-04-05 05:56:26,684 - INFO - Epoch 56/100 - Train Loss: 0.2497 - Val Acc: 0.8841
2026-04-05 05:56:26,957 - INFO - Epoch 57/100 - Train Loss: 0.2478 - Val Acc: 0.8841
2026-04-05 05:56:27,237 - INFO - Epoch 58/100 - Train Loss: 0.2484 - Val Acc: 0.8841
2026-04-05 05:56:27,502 - INFO - Epoch 59/100 - Train Loss: 0.2467 - Val Acc: 0.8841
2026-04-05 05:56:27,778 - INFO - Epoch 60/100 - Train Loss: 0.2489 - Val Acc: 0.8841
2026-04-05 05:56:28,046 - INFO - Epoch 61/100 - Train Loss: 0.2469 - Val Acc: 0.8841
2026-04-05 05:56:28,323 - INFO - Epoch 62/100 - Train Loss: 0.2445 - Val Acc: 0.8841
2026-04-05 05:56:28,596 - INFO - Epoch 63/100 - Train Loss: 0.2475 - Val Acc: 0.8841
2026-04-05 05:56:28,866 - INFO - Epoch 64/100 - Train Loss: 0.2468 - Val Acc: 0.8841
2026-04-05 05:56:29,125 - INFO - Epoch 65/100 - Train Loss: 0.2412 - Val Acc: 0.8841
2026-04-05 05:56:29,397 - INFO - Epoch 66/100 - Train Loss: 0.2404 - Val Acc: 0.8841
2026-04-05 05:56:29,660 - INFO - Epoch 67/100 - Train Loss: 0.2395 - Val Acc: 0.8841
2026-04-05 05:56:29,942 - INFO - Epoch 68/100 - Train Loss: 0.2386 - Val Acc: 0.8841
2026-04-05 05:56:30,220 - INFO - Epoch 69/100 - Train Loss: 0.2373 - Val Acc: 0.8841
2026-04-05 05:56:30,492 - INFO - Epoch 70/100 - Train Loss: 0.2436 - Val Acc: 0.8841
2026-04-05 05:56:30,769 - INFO - Epoch 71/100 - Train Loss: 0.2388 - Val Acc: 0.8841
2026-04-05 05:56:31,039 - INFO - Epoch 72/100 - Train Loss: 0.2379 - Val Acc: 0.8841
2026-04-05 05:56:31,300 - INFO - Epoch 73/100 - Train Loss: 0.2404 - Val Acc: 0.8841
2026-04-05 05:56:31,572 - INFO - Epoch 74/100 - Train Loss: 0.2295 - Val Acc: 0.8841
2026-04-05 05:56:31,853 - INFO - Epoch 75/100 - Train Loss: 0.2368 - Val Acc: 0.8841
2026-04-05 05:56:32,133 - INFO - Epoch 76/100 - Train Loss: 0.2345 - Val Acc: 0.8841
2026-04-05 05:56:32,400 - INFO - Epoch 77/100 - Train Loss: 0.2368 - Val Acc: 0.8841
2026-04-05 05:56:32,673 - INFO - Epoch 78/100 - Train Loss: 0.2333 - Val Acc: 0.8841
2026-04-05 05:56:32,948 - INFO - Epoch 79/100 - Train Loss: 0.2295 - Val Acc: 0.8841
2026-04-05 05:56:33,228 - INFO - Epoch 80/100 - Train Loss: 0.2361 - Val Acc: 0.8841
2026-04-05 05:56:33,509 - INFO - Epoch 81/100 - Train Loss: 0.2314 - Val Acc: 0.8841
2026-04-05 05:56:33,779 - INFO - Epoch 82/100 - Train Loss: 0.2339 - Val Acc: 0.8841
2026-04-05 05:56:34,044 - INFO - Epoch 83/100 - Train Loss: 0.2300 - Val Acc: 0.8841
2026-04-05 05:56:34,311 - INFO - Epoch 84/100 - Train Loss: 0.2324 - Val Acc: 0.8841
2026-04-05 05:56:34,603 - INFO - Epoch 85/100 - Train Loss: 0.2320 - Val Acc: 0.8841
2026-04-05 05:56:34,876 - INFO - Epoch 86/100 - Train Loss: 0.2337 - Val Acc: 0.8841
2026-04-05 05:56:35,156 - INFO - Epoch 87/100 - Train Loss: 0.2287 - Val Acc: 0.8841
2026-04-05 05:56:35,434 - INFO - Epoch 88/100 - Train Loss: 0.2286 - Val Acc: 0.8841
2026-04-05 05:56:35,711 - INFO - Epoch 89/100 - Train Loss: 0.2274 - Val Acc: 0.8841
2026-04-05 05:56:36,001 - INFO - Epoch 90/100 - Train Loss: 0.2289 - Val Acc: 0.8841
2026-04-05 05:56:36,273 - INFO - Epoch 91/100 - Train Loss: 0.2254 - Val Acc: 0.8841
2026-04-05 05:56:36,540 - INFO - Epoch 92/100 - Train Loss: 0.2243 - Val Acc: 0.8841
2026-04-05 05:56:36,818 - INFO - Epoch 93/100 - Train Loss: 0.2254 - Val Acc: 0.8841
2026-04-05 05:56:37,087 - INFO - Epoch 94/100 - Train Loss: 0.2190 - Val Acc: 0.8841
2026-04-05 05:56:37,350 - INFO - Epoch 95/100 - Train Loss: 0.2231 - Val Acc: 0.8841
2026-04-05 05:56:37,616 - INFO - Epoch 96/100 - Train Loss: 0.2235 - Val Acc: 0.8841
2026-04-05 05:56:37,897 - INFO - Epoch 97/100 - Train Loss: 0.2257 - Val Acc: 0.8841
2026-04-05 05:56:38,170 - INFO - Epoch 98/100 - Train Loss: 0.2225 - Val Acc: 0.8841
2026-04-05 05:56:38,435 - INFO - Epoch 99/100 - Train Loss: 0.2230 - Val Acc: 0.8841
2026-04-05 05:56:38,705 - INFO - Epoch 100/100 - Train Loss: 0.2204 - Val Acc: 0.8841
2026-04-05 05:56:39,080 - INFO - Fold 2 logically complete. Tensor memory bounds cleared cleanly.
2026-04-05 05:56:39,084 - INFO - Original class distribution: [344 277]
2026-04-05 05:56:39,085 - INFO - Training device bound securely to: cuda

Fold 3:   0%|          | 0/100 [00:00<?, ?it/s]

2026-04-05 05:56:39,386 - INFO - Epoch 1/100 - Train Loss: 0.5685 - Val Acc: 0.9275
2026-04-05 05:56:39,653 - INFO - Epoch 2/100 - Train Loss: 0.4207 - Val Acc: 0.9420
2026-04-05 05:56:39,941 - INFO - Epoch 3/100 - Train Loss: 0.3762 - Val Acc: 0.9275
2026-04-05 05:56:40,206 - INFO - Epoch 4/100 - Train Loss: 0.3550 - Val Acc: 0.9275
2026-04-05 05:56:40,486 - INFO - Epoch 5/100 - Train Loss: 0.3382 - Val Acc: 0.9130
2026-04-05 05:56:40,758 - INFO - Epoch 6/100 - Train Loss: 0.3288 - Val Acc: 0.9130
2026-04-05 05:56:41,019 - INFO - Epoch 7/100 - Train Loss: 0.3216 - Val Acc: 0.9130
2026-04-05 05:56:41,285 - INFO - Epoch 8/100 - Train Loss: 0.3146 - Val Acc: 0.9130
2026-04-05 05:56:41,552 - INFO - Epoch 9/100 - Train Loss: 0.3118 - Val Acc: 0.9130
2026-04-05 05:56:41,831 - INFO - Epoch 10/100 - Train Loss: 0.3069 - Val Acc: 0.9130
2026-04-05 05:56:42,107 - INFO - Epoch 11/100 - Train Loss: 0.3049 - Val Acc: 0.9130
2026-04-05 05:56:42,371 - INFO - Epoch 12/100 - Train Loss: 0.3032 - Val Acc: 0.9130
2026-04-05 05:56:42,637 - INFO - Epoch 13/100 - Train Loss: 0.3028 - Val Acc: 0.9130
2026-04-05 05:56:42,906 - INFO - Epoch 14/100 - Train Loss: 0.3010 - Val Acc: 0.9130
2026-04-05 05:56:43,178 - INFO - Epoch 15/100 - Train Loss: 0.2989 - Val Acc: 0.9130
2026-04-05 05:56:43,444 - INFO - Epoch 16/100 - Train Loss: 0.2944 - Val Acc: 0.9130
2026-04-05 05:56:43,702 - INFO - Epoch 17/100 - Train Loss: 0.2950 - Val Acc: 0.9130
2026-04-05 05:56:43,974 - INFO - Epoch 18/100 - Train Loss: 0.2938 - Val Acc: 0.9130
2026-04-05 05:56:44,263 - INFO - Epoch 19/100 - Train Loss: 0.2920 - Val Acc: 0.9130
2026-04-05 05:56:44,542 - INFO - Epoch 20/100 - Train Loss: 0.2917 - Val Acc: 0.9130
2026-04-05 05:56:44,838 - INFO - Epoch 21/100 - Train Loss: 0.2873 - Val Acc: 0.9130
2026-04-05 05:56:45,099 - INFO - Epoch 22/100 - Train Loss: 0.2858 - Val Acc: 0.9130
2026-04-05 05:56:45,373 - INFO - Epoch 23/100 - Train Loss: 0.2888 - Val Acc: 0.9130
2026-04-05 05:56:45,651 - INFO - Epoch 24/100 - Train Loss: 0.2856 - Val Acc: 0.9130
2026-04-05 05:56:45,933 - INFO - Epoch 25/100 - Train Loss: 0.2845 - Val Acc: 0.9130
2026-04-05 05:56:46,204 - INFO - Epoch 26/100 - Train Loss: 0.2821 - Val Acc: 0.9130
2026-04-05 05:56:46,479 - INFO - Epoch 27/100 - Train Loss: 0.2777 - Val Acc: 0.9130
2026-04-05 05:56:46,747 - INFO - Epoch 28/100 - Train Loss: 0.2810 - Val Acc: 0.9130
2026-04-05 05:56:47,013 - INFO - Epoch 29/100 - Train Loss: 0.2800 - Val Acc: 0.9130
2026-04-05 05:56:47,296 - INFO - Epoch 30/100 - Train Loss: 0.2760 - Val Acc: 0.9130
2026-04-05 05:56:47,578 - INFO - Epoch 31/100 - Train Loss: 0.2773 - Val Acc: 0.9130
2026-04-05 05:56:47,843 - INFO - Epoch 32/100 - Train Loss: 0.2725 - Val Acc: 0.9130
2026-04-05 05:56:48,117 - INFO - Epoch 33/100 - Train Loss: 0.2763 - Val Acc: 0.9130
2026-04-05 05:56:48,381 - INFO - Epoch 34/100 - Train Loss: 0.2719 - Val Acc: 0.9130
2026-04-05 05:56:48,653 - INFO - Epoch 35/100 - Train Loss: 0.2725 - Val Acc: 0.9130
2026-04-05 05:56:48,919 - INFO - Epoch 36/100 - Train Loss: 0.2694 - Val Acc: 0.9130
2026-04-05 05:56:49,191 - INFO - Epoch 37/100 - Train Loss: 0.2684 - Val Acc: 0.9130
2026-04-05 05:56:49,460 - INFO - Epoch 38/100 - Train Loss: 0.2674 - Val Acc: 0.9130
2026-04-05 05:56:49,738 - INFO - Epoch 39/100 - Train Loss: 0.2672 - Val Acc: 0.9130
2026-04-05 05:56:49,998 - INFO - Epoch 40/100 - Train Loss: 0.2663 - Val Acc: 0.9130
2026-04-05 05:56:50,279 - INFO - Epoch 41/100 - Train Loss: 0.2650 - Val Acc: 0.9130
2026-04-05 05:56:50,557 - INFO - Epoch 42/100 - Train Loss: 0.2624 - Val Acc: 0.9130
2026-04-05 05:56:50,824 - INFO - Epoch 43/100 - Train Loss: 0.2635 - Val Acc: 0.9130
2026-04-05 05:56:51,086 - INFO - Epoch 44/100 - Train Loss: 0.2605 - Val Acc: 0.9130
2026-04-05 05:56:51,355 - INFO - Epoch 45/100 - Train Loss: 0.2599 - Val Acc: 0.9130
2026-04-05 05:56:51,621 - INFO - Epoch 46/100 - Train Loss: 0.2622 - Val Acc: 0.9130
2026-04-05 05:56:51,883 - INFO - Epoch 47/100 - Train Loss: 0.2606 - Val Acc: 0.9130
2026-04-05 05:56:52,151 - INFO - Epoch 48/100 - Train Loss: 0.2576 - Val Acc: 0.9130
2026-04-05 05:56:52,415 - INFO - Epoch 49/100 - Train Loss: 0.2558 - Val Acc: 0.9130
2026-04-05 05:56:52,681 - INFO - Epoch 50/100 - Train Loss: 0.2544 - Val Acc: 0.9130
2026-04-05 05:56:52,942 - INFO - Epoch 51/100 - Train Loss: 0.2549 - Val Acc: 0.9130
2026-04-05 05:56:53,207 - INFO - Epoch 52/100 - Train Loss: 0.2525 - Val Acc: 0.9130
2026-04-05 05:56:53,469 - INFO - Epoch 53/100 - Train Loss: 0.2568 - Val Acc: 0.9130
2026-04-05 05:56:53,739 - INFO - Epoch 54/100 - Train Loss: 0.2549 - Val Acc: 0.9130
2026-04-05 05:56:54,005 - INFO - Epoch 55/100 - Train Loss: 0.2505 - Val Acc: 0.9130
2026-04-05 05:56:54,285 - INFO - Epoch 56/100 - Train Loss: 0.2510 - Val Acc: 0.9130
2026-04-05 05:56:54,591 - INFO - Epoch 57/100 - Train Loss: 0.2490 - Val Acc: 0.9130
2026-04-05 05:56:54,856 - INFO - Epoch 58/100 - Train Loss: 0.2503 - Val Acc: 0.9130
2026-04-05 05:56:55,126 - INFO - Epoch 59/100 - Train Loss: 0.2462 - Val Acc: 0.9130
2026-04-05 05:56:55,400 - INFO - Epoch 60/100 - Train Loss: 0.2470 - Val Acc: 0.9130
2026-04-05 05:56:55,675 - INFO - Epoch 61/100 - Train Loss: 0.2427 - Val Acc: 0.9130
2026-04-05 05:56:55,953 - INFO - Epoch 62/100 - Train Loss: 0.2452 - Val Acc: 0.9130
2026-04-05 05:56:56,231 - INFO - Epoch 63/100 - Train Loss: 0.2451 - Val Acc: 0.9130
2026-04-05 05:56:56,501 - INFO - Epoch 64/100 - Train Loss: 0.2390 - Val Acc: 0.9130
2026-04-05 05:56:56,774 - INFO - Epoch 65/100 - Train Loss: 0.2432 - Val Acc: 0.9130
2026-04-05 05:56:57,044 - INFO - Epoch 66/100 - Train Loss: 0.2409 - Val Acc: 0.9130
2026-04-05 05:56:57,317 - INFO - Epoch 67/100 - Train Loss: 0.2413 - Val Acc: 0.9130
2026-04-05 05:56:57,580 - INFO - Epoch 68/100 - Train Loss: 0.2352 - Val Acc: 0.9130
2026-04-05 05:56:57,845 - INFO - Epoch 69/100 - Train Loss: 0.2390 - Val Acc: 0.9130
2026-04-05 05:56:58,111 - INFO - Epoch 70/100 - Train Loss: 0.2388 - Val Acc: 0.9130
2026-04-05 05:56:58,377 - INFO - Epoch 71/100 - Train Loss: 0.2393 - Val Acc: 0.9130
2026-04-05 05:56:58,645 - INFO - Epoch 72/100 - Train Loss: 0.2337 - Val Acc: 0.9130
2026-04-05 05:56:58,916 - INFO - Epoch 73/100 - Train Loss: 0.2359 - Val Acc: 0.9130
2026-04-05 05:56:59,177 - INFO - Epoch 74/100 - Train Loss: 0.2312 - Val Acc: 0.9130
2026-04-05 05:56:59,451 - INFO - Epoch 75/100 - Train Loss: 0.2324 - Val Acc: 0.9130
2026-04-05 05:56:59,725 - INFO - Epoch 76/100 - Train Loss: 0.2294 - Val Acc: 0.9275
2026-04-05 05:57:00,011 - INFO - Epoch 77/100 - Train Loss: 0.2344 - Val Acc: 0.9275
2026-04-05 05:57:00,271 - INFO - Epoch 78/100 - Train Loss: 0.2312 - Val Acc: 0.9275
2026-04-05 05:57:00,543 - INFO - Epoch 79/100 - Train Loss: 0.2282 - Val Acc: 0.9275
2026-04-05 05:57:00,811 - INFO - Epoch 80/100 - Train Loss: 0.2297 - Val Acc: 0.9275
2026-04-05 05:57:01,084 - INFO - Epoch 81/100 - Train Loss: 0.2301 - Val Acc: 0.9275
2026-04-05 05:57:01,345 - INFO - Epoch 82/100 - Train Loss: 0.2276 - Val Acc: 0.9275
2026-04-05 05:57:01,597 - INFO - Epoch 83/100 - Train Loss: 0.2295 - Val Acc: 0.9275
2026-04-05 05:57:01,868 - INFO - Epoch 84/100 - Train Loss: 0.2269 - Val Acc: 0.9275
2026-04-05 05:57:02,146 - INFO - Epoch 85/100 - Train Loss: 0.2223 - Val Acc: 0.9275
2026-04-05 05:57:02,422 - INFO - Epoch 86/100 - Train Loss: 0.2254 - Val Acc: 0.9275
2026-04-05 05:57:02,697 - INFO - Epoch 87/100 - Train Loss: 0.2281 - Val Acc: 0.9275
2026-04-05 05:57:02,971 - INFO - Epoch 88/100 - Train Loss: 0.2226 - Val Acc: 0.9275
2026-04-05 05:57:03,248 - INFO - Epoch 89/100 - Train Loss: 0.2237 - Val Acc: 0.9275
2026-04-05 05:57:03,524 - INFO - Epoch 90/100 - Train Loss: 0.2199 - Val Acc: 0.9275
2026-04-05 05:57:03,806 - INFO - Epoch 91/100 - Train Loss: 0.2246 - Val Acc: 0.9275
2026-04-05 05:57:04,086 - INFO - Epoch 92/100 - Train Loss: 0.2186 - Val Acc: 0.9275
2026-04-05 05:57:04,342 - INFO - Epoch 93/100 - Train Loss: 0.2248 - Val Acc: 0.9275
2026-04-05 05:57:04,627 - INFO - Epoch 94/100 - Train Loss: 0.2177 - Val Acc: 0.9275
2026-04-05 05:57:04,898 - INFO - Epoch 95/100 - Train Loss: 0.2144 - Val Acc: 0.9275
2026-04-05 05:57:05,164 - INFO - Epoch 96/100 - Train Loss: 0.2201 - Val Acc: 0.9275
2026-04-05 05:57:05,426 - INFO - Epoch 97/100 - Train Loss: 0.2193 - Val Acc: 0.9275
2026-04-05 05:57:05,701 - INFO - Epoch 98/100 - Train Loss: 0.2158 - Val Acc: 0.9275
2026-04-05 05:57:05,980 - INFO - Epoch 99/100 - Train Loss: 0.2180 - Val Acc: 0.9275
2026-04-05 05:57:06,250 - INFO - Epoch 100/100 - Train Loss: 0.2131 - Val Acc: 0.9275
2026-04-05 05:57:06,607 - INFO - Fold 3 logically complete. Tensor memory bounds cleared cleanly.
2026-04-05 05:57:06,610 - INFO - Original class distribution: [345 276]
2026-04-05 05:57:06,611 - INFO - Training device bound securely to: cuda

Fold 4:   0%|          | 0/100 [00:00<?, ?it/s]

2026-04-05 05:57:06,911 - INFO - Epoch 1/100 - Train Loss: 0.5579 - Val Acc: 0.7681
2026-04-05 05:57:07,172 - INFO - Epoch 2/100 - Train Loss: 0.3951 - Val Acc: 0.7826
2026-04-05 05:57:07,430 - INFO - Epoch 3/100 - Train Loss: 0.3449 - Val Acc: 0.7826
2026-04-05 05:57:07,699 - INFO - Epoch 4/100 - Train Loss: 0.3271 - Val Acc: 0.8116
2026-04-05 05:57:07,968 - INFO - Epoch 5/100 - Train Loss: 0.3123 - Val Acc: 0.7971
2026-04-05 05:57:08,227 - INFO - Epoch 6/100 - Train Loss: 0.3032 - Val Acc: 0.8116
2026-04-05 05:57:08,484 - INFO - Epoch 7/100 - Train Loss: 0.2962 - Val Acc: 0.7971
2026-04-05 05:57:08,744 - INFO - Epoch 8/100 - Train Loss: 0.2907 - Val Acc: 0.7971
2026-04-05 05:57:08,998 - INFO - Epoch 9/100 - Train Loss: 0.2877 - Val Acc: 0.7971
2026-04-05 05:57:09,260 - INFO - Epoch 10/100 - Train Loss: 0.2856 - Val Acc: 0.7971
2026-04-05 05:57:09,519 - INFO - Epoch 11/100 - Train Loss: 0.2815 - Val Acc: 0.7971
2026-04-05 05:57:09,792 - INFO - Epoch 12/100 - Train Loss: 0.2799 - Val Acc: 0.7971
2026-04-05 05:57:10,059 - INFO - Epoch 13/100 - Train Loss: 0.2776 - Val Acc: 0.7971
2026-04-05 05:57:10,331 - INFO - Epoch 14/100 - Train Loss: 0.2783 - Val Acc: 0.7971
2026-04-05 05:57:10,597 - INFO - Epoch 15/100 - Train Loss: 0.2740 - Val Acc: 0.7971
2026-04-05 05:57:10,865 - INFO - Epoch 16/100 - Train Loss: 0.2747 - Val Acc: 0.7971
2026-04-05 05:57:11,136 - INFO - Epoch 17/100 - Train Loss: 0.2749 - Val Acc: 0.7971
2026-04-05 05:57:11,413 - INFO - Epoch 18/100 - Train Loss: 0.2732 - Val Acc: 0.7971
2026-04-05 05:57:11,677 - INFO - Epoch 19/100 - Train Loss: 0.2685 - Val Acc: 0.7971
2026-04-05 05:57:11,956 - INFO - Epoch 20/100 - Train Loss: 0.2692 - Val Acc: 0.7971
2026-04-05 05:57:12,217 - INFO - Epoch 21/100 - Train Loss: 0.2694 - Val Acc: 0.7971
2026-04-05 05:57:12,480 - INFO - Epoch 22/100 - Train Loss: 0.2682 - Val Acc: 0.7971
2026-04-05 05:57:12,750 - INFO - Epoch 23/100 - Train Loss: 0.2634 - Val Acc: 0.7971
2026-04-05 05:57:13,028 - INFO - Epoch 24/100 - Train Loss: 0.2647 - Val Acc: 0.7971
2026-04-05 05:57:13,305 - INFO - Epoch 25/100 - Train Loss: 0.2635 - Val Acc: 0.7971
2026-04-05 05:57:13,571 - INFO - Epoch 26/100 - Train Loss: 0.2613 - Val Acc: 0.7971
2026-04-05 05:57:13,842 - INFO - Epoch 27/100 - Train Loss: 0.2621 - Val Acc: 0.7971
2026-04-05 05:57:14,117 - INFO - Epoch 28/100 - Train Loss: 0.2590 - Val Acc: 0.7971
2026-04-05 05:57:14,390 - INFO - Epoch 29/100 - Train Loss: 0.2589 - Val Acc: 0.7971
2026-04-05 05:57:14,697 - INFO - Epoch 30/100 - Train Loss: 0.2551 - Val Acc: 0.7971
2026-04-05 05:57:14,976 - INFO - Epoch 31/100 - Train Loss: 0.2578 - Val Acc: 0.7971
2026-04-05 05:57:15,258 - INFO - Epoch 32/100 - Train Loss: 0.2543 - Val Acc: 0.7971
2026-04-05 05:57:15,534 - INFO - Epoch 33/100 - Train Loss: 0.2531 - Val Acc: 0.7971
2026-04-05 05:57:15,816 - INFO - Epoch 34/100 - Train Loss: 0.2519 - Val Acc: 0.7971
2026-04-05 05:57:16,081 - INFO - Epoch 35/100 - Train Loss: 0.2516 - Val Acc: 0.7971
2026-04-05 05:57:16,346 - INFO - Epoch 36/100 - Train Loss: 0.2497 - Val Acc: 0.7971
2026-04-05 05:57:16,604 - INFO - Epoch 37/100 - Train Loss: 0.2501 - Val Acc: 0.7971
2026-04-05 05:57:16,882 - INFO - Epoch 38/100 - Train Loss: 0.2496 - Val Acc: 0.8116
2026-04-05 05:57:17,145 - INFO - Epoch 39/100 - Train Loss: 0.2485 - Val Acc: 0.7971
2026-04-05 05:57:17,413 - INFO - Epoch 40/100 - Train Loss: 0.2419 - Val Acc: 0.8261
2026-04-05 05:57:17,684 - INFO - Epoch 41/100 - Train Loss: 0.2461 - Val Acc: 0.8261
2026-04-05 05:57:17,948 - INFO - Epoch 42/100 - Train Loss: 0.2452 - Val Acc: 0.8261
2026-04-05 05:57:18,211 - INFO - Epoch 43/100 - Train Loss: 0.2425 - Val Acc: 0.8261
2026-04-05 05:57:18,479 - INFO - Epoch 44/100 - Train Loss: 0.2385 - Val Acc: 0.8261
2026-04-05 05:57:18,778 - INFO - Epoch 45/100 - Train Loss: 0.2427 - Val Acc: 0.8261
2026-04-05 05:57:19,042 - INFO - Epoch 46/100 - Train Loss: 0.2377 - Val Acc: 0.8261
2026-04-05 05:57:19,300 - INFO - Epoch 47/100 - Train Loss: 0.2394 - Val Acc: 0.8261
2026-04-05 05:57:19,565 - INFO - Epoch 48/100 - Train Loss: 0.2365 - Val Acc: 0.8261
2026-04-05 05:57:19,843 - INFO - Epoch 49/100 - Train Loss: 0.2355 - Val Acc: 0.8261
2026-04-05 05:57:20,105 - INFO - Epoch 50/100 - Train Loss: 0.2355 - Val Acc: 0.8261
2026-04-05 05:57:20,383 - INFO - Epoch 51/100 - Train Loss: 0.2332 - Val Acc: 0.8261
2026-04-05 05:57:20,655 - INFO - Epoch 52/100 - Train Loss: 0.2320 - Val Acc: 0.8261
2026-04-05 05:57:20,943 - INFO - Epoch 53/100 - Train Loss: 0.2326 - Val Acc: 0.8261
2026-04-05 05:57:21,209 - INFO - Epoch 54/100 - Train Loss: 0.2308 - Val Acc: 0.8261
2026-04-05 05:57:21,477 - INFO - Epoch 55/100 - Train Loss: 0.2300 - Val Acc: 0.8261
2026-04-05 05:57:21,748 - INFO - Epoch 56/100 - Train Loss: 0.2299 - Val Acc: 0.8261
2026-04-05 05:57:22,012 - INFO - Epoch 57/100 - Train Loss: 0.2274 - Val Acc: 0.8261
2026-04-05 05:57:22,274 - INFO - Epoch 58/100 - Train Loss: 0.2312 - Val Acc: 0.8406
2026-04-05 05:57:22,537 - INFO - Epoch 59/100 - Train Loss: 0.2204 - Val Acc: 0.8406
2026-04-05 05:57:22,807 - INFO - Epoch 60/100 - Train Loss: 0.2251 - Val Acc: 0.8406
2026-04-05 05:57:23,067 - INFO - Epoch 61/100 - Train Loss: 0.2221 - Val Acc: 0.8406
2026-04-05 05:57:23,331 - INFO - Epoch 62/100 - Train Loss: 0.2224 - Val Acc: 0.8261
2026-04-05 05:57:23,601 - INFO - Epoch 63/100 - Train Loss: 0.2206 - Val Acc: 0.8261
2026-04-05 05:57:23,876 - INFO - Epoch 64/100 - Train Loss: 0.2228 - Val Acc: 0.8551
2026-04-05 05:57:24,148 - INFO - Epoch 65/100 - Train Loss: 0.2213 - Val Acc: 0.8406
2026-04-05 05:57:24,414 - INFO - Epoch 66/100 - Train Loss: 0.2220 - Val Acc: 0.8261
2026-04-05 05:57:24,696 - INFO - Epoch 67/100 - Train Loss: 0.2189 - Val Acc: 0.8261
2026-04-05 05:57:24,965 - INFO - Epoch 68/100 - Train Loss: 0.2202 - Val Acc: 0.8406
2026-04-05 05:57:25,241 - INFO - Epoch 69/100 - Train Loss: 0.2154 - Val Acc: 0.8406
2026-04-05 05:57:25,503 - INFO - Epoch 70/100 - Train Loss: 0.2181 - Val Acc: 0.8406
2026-04-05 05:57:25,767 - INFO - Epoch 71/100 - Train Loss: 0.2169 - Val Acc: 0.8406
2026-04-05 05:57:26,036 - INFO - Epoch 72/100 - Train Loss: 0.2151 - Val Acc: 0.8406
2026-04-05 05:57:26,310 - INFO - Epoch 73/100 - Train Loss: 0.2162 - Val Acc: 0.8406
2026-04-05 05:57:26,581 - INFO - Epoch 74/100 - Train Loss: 0.2136 - Val Acc: 0.8406
2026-04-05 05:57:26,848 - INFO - Epoch 75/100 - Train Loss: 0.2144 - Val Acc: 0.8406
2026-04-05 05:57:27,103 - INFO - Epoch 76/100 - Train Loss: 0.2117 - Val Acc: 0.8406
2026-04-05 05:57:27,361 - INFO - Epoch 77/100 - Train Loss: 0.2134 - Val Acc: 0.8406
2026-04-05 05:57:27,627 - INFO - Epoch 78/100 - Train Loss: 0.2087 - Val Acc: 0.8261
2026-04-05 05:57:27,896 - INFO - Epoch 79/100 - Train Loss: 0.2088 - Val Acc: 0.8261
2026-04-05 05:57:28,174 - INFO - Epoch 80/100 - Train Loss: 0.2114 - Val Acc: 0.8116
2026-04-05 05:57:28,450 - INFO - Epoch 81/100 - Train Loss: 0.2078 - Val Acc: 0.8406
2026-04-05 05:57:28,716 - INFO - Epoch 82/100 - Train Loss: 0.2108 - Val Acc: 0.8261
2026-04-05 05:57:28,973 - INFO - Epoch 83/100 - Train Loss: 0.2011 - Val Acc: 0.8261
2026-04-05 05:57:29,243 - INFO - Epoch 84/100 - Train Loss: 0.2094 - Val Acc: 0.8406
2026-04-05 05:57:29,507 - INFO - Epoch 85/100 - Train Loss: 0.2070 - Val Acc: 0.8551
2026-04-05 05:57:29,774 - INFO - Epoch 86/100 - Train Loss: 0.2054 - Val Acc: 0.8406
2026-04-05 05:57:30,047 - INFO - Epoch 87/100 - Train Loss: 0.2033 - Val Acc: 0.8551
2026-04-05 05:57:30,319 - INFO - Epoch 88/100 - Train Loss: 0.2019 - Val Acc: 0.8551
2026-04-05 05:57:30,601 - INFO - Epoch 89/100 - Train Loss: 0.2027 - Val Acc: 0.8406
2026-04-05 05:57:30,875 - INFO - Epoch 90/100 - Train Loss: 0.2013 - Val Acc: 0.8261
2026-04-05 05:57:31,145 - INFO - Epoch 91/100 - Train Loss: 0.1997 - Val Acc: 0.8261
2026-04-05 05:57:31,411 - INFO - Epoch 92/100 - Train Loss: 0.1987 - Val Acc: 0.8261
2026-04-05 05:57:31,671 - INFO - Epoch 93/100 - Train Loss: 0.2052 - Val Acc: 0.8261
2026-04-05 05:57:31,946 - INFO - Epoch 94/100 - Train Loss: 0.1970 - Val Acc: 0.8261
2026-04-05 05:57:32,205 - INFO - Epoch 95/100 - Train Loss: 0.1970 - Val Acc: 0.8261
2026-04-05 05:57:32,473 - INFO - Epoch 96/100 - Train Loss: 0.1928 - Val Acc: 0.8261
2026-04-05 05:57:32,736 - INFO - Epoch 97/100 - Train Loss: 0.1959 - Val Acc: 0.8261
2026-04-05 05:57:33,009 - INFO - Epoch 98/100 - Train Loss: 0.1965 - Val Acc: 0.8261
2026-04-05 05:57:33,283 - INFO - Epoch 99/100 - Train Loss: 0.1916 - Val Acc: 0.8116
2026-04-05 05:57:33,548 - INFO - Epoch 100/100 - Train Loss: 0.1943 - Val Acc: 0.8261
2026-04-05 05:57:33,901 - INFO - Fold 4 logically complete. Tensor memory bounds cleared cleanly.
2026-04-05 05:57:33,905 - INFO - Original class distribution: [345 276]
2026-04-05 05:57:33,905 - INFO - Training device bound securely to: cuda

Fold 5:   0%|          | 0/100 [00:00<?, ?it/s]

2026-04-05 05:57:34,225 - INFO - Epoch 1/100 - Train Loss: 0.5552 - Val Acc: 0.8261
2026-04-05 05:57:34,494 - INFO - Epoch 2/100 - Train Loss: 0.4001 - Val Acc: 0.8551
2026-04-05 05:57:34,787 - INFO - Epoch 3/100 - Train Loss: 0.3561 - Val Acc: 0.8696
2026-04-05 05:57:35,050 - INFO - Epoch 4/100 - Train Loss: 0.3374 - Val Acc: 0.8696
2026-04-05 05:57:35,315 - INFO - Epoch 5/100 - Train Loss: 0.3220 - Val Acc: 0.8696
2026-04-05 05:57:35,592 - INFO - Epoch 6/100 - Train Loss: 0.3128 - Val Acc: 0.8696
2026-04-05 05:57:35,864 - INFO - Epoch 7/100 - Train Loss: 0.3064 - Val Acc: 0.8841
2026-04-05 05:57:36,129 - INFO - Epoch 8/100 - Train Loss: 0.3008 - Val Acc: 0.8841
2026-04-05 05:57:36,396 - INFO - Epoch 9/100 - Train Loss: 0.2981 - Val Acc: 0.8986
2026-04-05 05:57:36,668 - INFO - Epoch 10/100 - Train Loss: 0.2951 - Val Acc: 0.8696
2026-04-05 05:57:36,949 - INFO - Epoch 11/100 - Train Loss: 0.2896 - Val Acc: 0.8696
2026-04-05 05:57:37,225 - INFO - Epoch 12/100 - Train Loss: 0.2883 - Val Acc: 0.8696
2026-04-05 05:57:37,497 - INFO - Epoch 13/100 - Train Loss: 0.2857 - Val Acc: 0.8551
2026-04-05 05:57:37,764 - INFO - Epoch 14/100 - Train Loss: 0.2859 - Val Acc: 0.8551
2026-04-05 05:57:38,038 - INFO - Epoch 15/100 - Train Loss: 0.2838 - Val Acc: 0.8406
2026-04-05 05:57:38,304 - INFO - Epoch 16/100 - Train Loss: 0.2822 - Val Acc: 0.8406
2026-04-05 05:57:38,569 - INFO - Epoch 17/100 - Train Loss: 0.2789 - Val Acc: 0.8406
2026-04-05 05:57:38,837 - INFO - Epoch 18/100 - Train Loss: 0.2746 - Val Acc: 0.8406
2026-04-05 05:57:39,112 - INFO - Epoch 19/100 - Train Loss: 0.2749 - Val Acc: 0.8406
2026-04-05 05:57:39,375 - INFO - Epoch 20/100 - Train Loss: 0.2738 - Val Acc: 0.8406
2026-04-05 05:57:39,636 - INFO - Epoch 21/100 - Train Loss: 0.2710 - Val Acc: 0.8406
2026-04-05 05:57:39,900 - INFO - Epoch 22/100 - Train Loss: 0.2734 - Val Acc: 0.8406
2026-04-05 05:57:40,160 - INFO - Epoch 23/100 - Train Loss: 0.2670 - Val Acc: 0.8406
2026-04-05 05:57:40,443 - INFO - Epoch 24/100 - Train Loss: 0.2683 - Val Acc: 0.8406
2026-04-05 05:57:40,711 - INFO - Epoch 25/100 - Train Loss: 0.2679 - Val Acc: 0.8406
2026-04-05 05:57:40,984 - INFO - Epoch 26/100 - Train Loss: 0.2651 - Val Acc: 0.8406
2026-04-05 05:57:41,251 - INFO - Epoch 27/100 - Train Loss: 0.2656 - Val Acc: 0.8406
2026-04-05 05:57:41,518 - INFO - Epoch 28/100 - Train Loss: 0.2609 - Val Acc: 0.8261
2026-04-05 05:57:41,797 - INFO - Epoch 29/100 - Train Loss: 0.2600 - Val Acc: 0.8261
2026-04-05 05:57:42,091 - INFO - Epoch 30/100 - Train Loss: 0.2611 - Val Acc: 0.8261
2026-04-05 05:57:42,384 - INFO - Epoch 31/100 - Train Loss: 0.2597 - Val Acc: 0.8261
2026-04-05 05:57:42,662 - INFO - Epoch 32/100 - Train Loss: 0.2557 - Val Acc: 0.8261
2026-04-05 05:57:42,933 - INFO - Epoch 33/100 - Train Loss: 0.2538 - Val Acc: 0.8406
2026-04-05 05:57:43,207 - INFO - Epoch 34/100 - Train Loss: 0.2559 - Val Acc: 0.8406
2026-04-05 05:57:43,481 - INFO - Epoch 35/100 - Train Loss: 0.2523 - Val Acc: 0.8551
2026-04-05 05:57:43,753 - INFO - Epoch 36/100 - Train Loss: 0.2546 - Val Acc: 0.8551
2026-04-05 05:57:44,021 - INFO - Epoch 37/100 - Train Loss: 0.2480 - Val Acc: 0.8406
2026-04-05 05:57:44,291 - INFO - Epoch 38/100 - Train Loss: 0.2521 - Val Acc: 0.8406
2026-04-05 05:57:44,582 - INFO - Epoch 39/100 - Train Loss: 0.2493 - Val Acc: 0.8551
2026-04-05 05:57:44,865 - INFO - Epoch 40/100 - Train Loss: 0.2493 - Val Acc: 0.8406
2026-04-05 05:57:45,157 - INFO - Epoch 41/100 - Train Loss: 0.2461 - Val Acc: 0.8551
2026-04-05 05:57:45,429 - INFO - Epoch 42/100 - Train Loss: 0.2467 - Val Acc: 0.8551
2026-04-05 05:57:45,703 - INFO - Epoch 43/100 - Train Loss: 0.2452 - Val Acc: 0.8551
2026-04-05 05:57:46,010 - INFO - Epoch 44/100 - Train Loss: 0.2407 - Val Acc: 0.8551
2026-04-05 05:57:46,293 - INFO - Epoch 45/100 - Train Loss: 0.2425 - Val Acc: 0.8551
2026-04-05 05:57:46,562 - INFO - Epoch 46/100 - Train Loss: 0.2405 - Val Acc: 0.8551
2026-04-05 05:57:46,841 - INFO - Epoch 47/100 - Train Loss: 0.2387 - Val Acc: 0.8551
2026-04-05 05:57:47,107 - INFO - Epoch 48/100 - Train Loss: 0.2385 - Val Acc: 0.8551
2026-04-05 05:57:47,369 - INFO - Epoch 49/100 - Train Loss: 0.2355 - Val Acc: 0.8551
2026-04-05 05:57:47,631 - INFO - Epoch 50/100 - Train Loss: 0.2364 - Val Acc: 0.8551
2026-04-05 05:57:47,895 - INFO - Epoch 51/100 - Train Loss: 0.2368 - Val Acc: 0.8551
2026-04-05 05:57:48,173 - INFO - Epoch 52/100 - Train Loss: 0.2358 - Val Acc: 0.8551
2026-04-05 05:57:48,436 - INFO - Epoch 53/100 - Train Loss: 0.2361 - Val Acc: 0.8551
2026-04-05 05:57:48,709 - INFO - Epoch 54/100 - Train Loss: 0.2329 - Val Acc: 0.8551
2026-04-05 05:57:48,989 - INFO - Epoch 55/100 - Train Loss: 0.2311 - Val Acc: 0.8406
2026-04-05 05:57:49,268 - INFO - Epoch 56/100 - Train Loss: 0.2330 - Val Acc: 0.8551
2026-04-05 05:57:49,538 - INFO - Epoch 57/100 - Train Loss: 0.2284 - Val Acc: 0.8406
2026-04-05 05:57:49,813 - INFO - Epoch 58/100 - Train Loss: 0.2271 - Val Acc: 0.8406
2026-04-05 05:57:50,098 - INFO - Epoch 59/100 - Train Loss: 0.2260 - Val Acc: 0.8406
2026-04-05 05:57:50,370 - INFO - Epoch 60/100 - Train Loss: 0.2292 - Val Acc: 0.8406
2026-04-05 05:57:50,641 - INFO - Epoch 61/100 - Train Loss: 0.2269 - Val Acc: 0.8406
2026-04-05 05:57:50,909 - INFO - Epoch 62/100 - Train Loss: 0.2265 - Val Acc: 0.8406
2026-04-05 05:57:51,184 - INFO - Epoch 63/100 - Train Loss: 0.2239 - Val Acc: 0.8406
2026-04-05 05:57:51,454 - INFO - Epoch 64/100 - Train Loss: 0.2248 - Val Acc: 0.8406
2026-04-05 05:57:51,714 - INFO - Epoch 65/100 - Train Loss: 0.2213 - Val Acc: 0.8551
2026-04-05 05:57:51,991 - INFO - Epoch 66/100 - Train Loss: 0.2216 - Val Acc: 0.8551
2026-04-05 05:57:52,274 - INFO - Epoch 67/100 - Train Loss: 0.2195 - Val Acc: 0.8406
2026-04-05 05:57:52,543 - INFO - Epoch 68/100 - Train Loss: 0.2206 - Val Acc: 0.8406
2026-04-05 05:57:52,811 - INFO - Epoch 69/100 - Train Loss: 0.2177 - Val Acc: 0.8406
2026-04-05 05:57:53,082 - INFO - Epoch 70/100 - Train Loss: 0.2213 - Val Acc: 0.8406
2026-04-05 05:57:53,348 - INFO - Epoch 71/100 - Train Loss: 0.2172 - Val Acc: 0.8406
2026-04-05 05:57:53,613 - INFO - Epoch 72/100 - Train Loss: 0.2202 - Val Acc: 0.8406
2026-04-05 05:57:53,883 - INFO - Epoch 73/100 - Train Loss: 0.2172 - Val Acc: 0.8406
2026-04-05 05:57:54,155 - INFO - Epoch 74/100 - Train Loss: 0.2146 - Val Acc: 0.8406
2026-04-05 05:57:54,442 - INFO - Epoch 75/100 - Train Loss: 0.2179 - Val Acc: 0.8406
2026-04-05 05:57:54,733 - INFO - Epoch 76/100 - Train Loss: 0.2148 - Val Acc: 0.8406
2026-04-05 05:57:54,997 - INFO - Epoch 77/100 - Train Loss: 0.2144 - Val Acc: 0.8406
2026-04-05 05:57:55,256 - INFO - Epoch 78/100 - Train Loss: 0.2132 - Val Acc: 0.8551
2026-04-05 05:57:55,515 - INFO - Epoch 79/100 - Train Loss: 0.2122 - Val Acc: 0.8551
2026-04-05 05:57:55,770 - INFO - Epoch 80/100 - Train Loss: 0.2106 - Val Acc: 0.8406
2026-04-05 05:57:56,052 - INFO - Epoch 81/100 - Train Loss: 0.2122 - Val Acc: 0.8696
2026-04-05 05:57:56,321 - INFO - Epoch 82/100 - Train Loss: 0.2115 - Val Acc: 0.8696
2026-04-05 05:57:56,580 - INFO - Epoch 83/100 - Train Loss: 0.2112 - Val Acc: 0.8696
2026-04-05 05:57:56,845 - INFO - Epoch 84/100 - Train Loss: 0.2120 - Val Acc: 0.8696
2026-04-05 05:57:57,117 - INFO - Epoch 85/100 - Train Loss: 0.2108 - Val Acc: 0.8551
2026-04-05 05:57:57,386 - INFO - Epoch 86/100 - Train Loss: 0.2091 - Val Acc: 0.8551
2026-04-05 05:57:57,653 - INFO - Epoch 87/100 - Train Loss: 0.2089 - Val Acc: 0.8551
2026-04-05 05:57:57,919 - INFO - Epoch 88/100 - Train Loss: 0.2106 - Val Acc: 0.8551
2026-04-05 05:57:58,179 - INFO - Epoch 89/100 - Train Loss: 0.2057 - Val Acc: 0.8551
2026-04-05 05:57:58,450 - INFO - Epoch 90/100 - Train Loss: 0.2087 - Val Acc: 0.8551
2026-04-05 05:57:58,710 - INFO - Epoch 91/100 - Train Loss: 0.2065 - Val Acc: 0.8696
2026-04-05 05:57:58,984 - INFO - Epoch 92/100 - Train Loss: 0.2057 - Val Acc: 0.8551
2026-04-05 05:57:59,250 - INFO - Epoch 93/100 - Train Loss: 0.2046 - Val Acc: 0.8551
2026-04-05 05:57:59,516 - INFO - Epoch 94/100 - Train Loss: 0.2036 - Val Acc: 0.8551
2026-04-05 05:57:59,774 - INFO - Epoch 95/100 - Train Loss: 0.2024 - Val Acc: 0.8551
2026-04-05 05:58:00,058 - INFO - Epoch 96/100 - Train Loss: 0.2058 - Val Acc: 0.8551
2026-04-05 05:58:00,331 - INFO - Epoch 97/100 - Train Loss: 0.2075 - Val Acc: 0.8551
2026-04-05 05:58:00,600 - INFO - Epoch 98/100 - Train Loss: 0.2069 - Val Acc: 0.8551
2026-04-05 05:58:00,869 - INFO - Epoch 99/100 - Train Loss: 0.2021 - Val Acc: 0.8551
2026-04-05 05:58:01,130 - INFO - Epoch 100/100 - Train Loss: 0.2016 - Val Acc: 0.8551
2026-04-05 05:58:01,483 - INFO - Fold 5 logically complete. Tensor memory bounds cleared cleanly.
2026-04-05 05:58:01,486 - INFO - Original class distribution: [345 276]
2026-04-05 05:58:01,487 - INFO - Training device bound securely to: cuda

Fold 6:   0%|          | 0/100 [00:00<?, ?it/s]

2026-04-05 05:58:01,781 - INFO - Epoch 1/100 - Train Loss: 0.5600 - Val Acc: 0.8406
2026-04-05 05:58:02,054 - INFO - Epoch 2/100 - Train Loss: 0.4079 - Val Acc: 0.8551
2026-04-05 05:58:02,320 - INFO - Epoch 3/100 - Train Loss: 0.3652 - Val Acc: 0.8696
2026-04-05 05:58:02,597 - INFO - Epoch 4/100 - Train Loss: 0.3472 - Val Acc: 0.8696
2026-04-05 05:58:02,881 - INFO - Epoch 5/100 - Train Loss: 0.3333 - Val Acc: 0.8551
2026-04-05 05:58:03,155 - INFO - Epoch 6/100 - Train Loss: 0.3250 - Val Acc: 0.8551
2026-04-05 05:58:03,425 - INFO - Epoch 7/100 - Train Loss: 0.3194 - Val Acc: 0.8551
2026-04-05 05:58:03,706 - INFO - Epoch 8/100 - Train Loss: 0.3155 - Val Acc: 0.8696
2026-04-05 05:58:03,974 - INFO - Epoch 9/100 - Train Loss: 0.3089 - Val Acc: 0.8696
2026-04-05 05:58:04,254 - INFO - Epoch 10/100 - Train Loss: 0.3074 - Val Acc: 0.8841
2026-04-05 05:58:04,526 - INFO - Epoch 11/100 - Train Loss: 0.3025 - Val Acc: 0.8841
2026-04-05 05:58:04,815 - INFO - Epoch 12/100 - Train Loss: 0.3045 - Val Acc: 0.8841
2026-04-05 05:58:05,093 - INFO - Epoch 13/100 - Train Loss: 0.3001 - Val Acc: 0.8841
2026-04-05 05:58:05,346 - INFO - Epoch 14/100 - Train Loss: 0.2980 - Val Acc: 0.8841
2026-04-05 05:58:05,609 - INFO - Epoch 15/100 - Train Loss: 0.2934 - Val Acc: 0.8841
2026-04-05 05:58:05,879 - INFO - Epoch 16/100 - Train Loss: 0.2944 - Val Acc: 0.8841
2026-04-05 05:58:06,143 - INFO - Epoch 17/100 - Train Loss: 0.2933 - Val Acc: 0.8841
2026-04-05 05:58:06,407 - INFO - Epoch 18/100 - Train Loss: 0.2911 - Val Acc: 0.8841
2026-04-05 05:58:06,677 - INFO - Epoch 19/100 - Train Loss: 0.2891 - Val Acc: 0.8841
2026-04-05 05:58:06,933 - INFO - Epoch 20/100 - Train Loss: 0.2890 - Val Acc: 0.8696
2026-04-05 05:58:07,196 - INFO - Epoch 21/100 - Train Loss: 0.2852 - Val Acc: 0.8696
2026-04-05 05:58:07,477 - INFO - Epoch 22/100 - Train Loss: 0.2853 - Val Acc: 0.8841
2026-04-05 05:58:07,752 - INFO - Epoch 23/100 - Train Loss: 0.2826 - Val Acc: 0.8696
2026-04-05 05:58:08,026 - INFO - Epoch 24/100 - Train Loss: 0.2847 - Val Acc: 0.8696
2026-04-05 05:58:08,288 - INFO - Epoch 25/100 - Train Loss: 0.2857 - Val Acc: 0.8696
2026-04-05 05:58:08,550 - INFO - Epoch 26/100 - Train Loss: 0.2815 - Val Acc: 0.8696
2026-04-05 05:58:08,814 - INFO - Epoch 27/100 - Train Loss: 0.2798 - Val Acc: 0.8696
2026-04-05 05:58:09,084 - INFO - Epoch 28/100 - Train Loss: 0.2785 - Val Acc: 0.8696
2026-04-05 05:58:09,355 - INFO - Epoch 29/100 - Train Loss: 0.2781 - Val Acc: 0.8696
2026-04-05 05:58:09,614 - INFO - Epoch 30/100 - Train Loss: 0.2767 - Val Acc: 0.8551
2026-04-05 05:58:09,884 - INFO - Epoch 31/100 - Train Loss: 0.2765 - Val Acc: 0.8551
2026-04-05 05:58:10,153 - INFO - Epoch 32/100 - Train Loss: 0.2749 - Val Acc: 0.8551
2026-04-05 05:58:10,434 - INFO - Epoch 33/100 - Train Loss: 0.2728 - Val Acc: 0.8551
2026-04-05 05:58:10,702 - INFO - Epoch 34/100 - Train Loss: 0.2761 - Val Acc: 0.8551
2026-04-05 05:58:10,968 - INFO - Epoch 35/100 - Train Loss: 0.2710 - Val Acc: 0.8551
2026-04-05 05:58:11,225 - INFO - Epoch 36/100 - Train Loss: 0.2687 - Val Acc: 0.8551
2026-04-05 05:58:11,505 - INFO - Epoch 37/100 - Train Loss: 0.2669 - Val Acc: 0.8551
2026-04-05 05:58:11,767 - INFO - Epoch 38/100 - Train Loss: 0.2643 - Val Acc: 0.8551
2026-04-05 05:58:12,037 - INFO - Epoch 39/100 - Train Loss: 0.2673 - Val Acc: 0.8551
2026-04-05 05:58:12,300 - INFO - Epoch 40/100 - Train Loss: 0.2675 - Val Acc: 0.8551
2026-04-05 05:58:12,570 - INFO - Epoch 41/100 - Train Loss: 0.2647 - Val Acc: 0.8551
2026-04-05 05:58:12,863 - INFO - Epoch 42/100 - Train Loss: 0.2662 - Val Acc: 0.8551
2026-04-05 05:58:13,147 - INFO - Epoch 43/100 - Train Loss: 0.2615 - Val Acc: 0.8551
2026-04-05 05:58:13,413 - INFO - Epoch 44/100 - Train Loss: 0.2592 - Val Acc: 0.8696
2026-04-05 05:58:13,687 - INFO - Epoch 45/100 - Train Loss: 0.2586 - Val Acc: 0.8696
2026-04-05 05:58:13,976 - INFO - Epoch 46/100 - Train Loss: 0.2597 - Val Acc: 0.8696
2026-04-05 05:58:14,266 - INFO - Epoch 47/100 - Train Loss: 0.2588 - Val Acc: 0.8696
2026-04-05 05:58:14,553 - INFO - Epoch 48/100 - Train Loss: 0.2583 - Val Acc: 0.8696
2026-04-05 05:58:14,826 - INFO - Epoch 49/100 - Train Loss: 0.2575 - Val Acc: 0.8696
2026-04-05 05:58:15,092 - INFO - Epoch 50/100 - Train Loss: 0.2560 - Val Acc: 0.8841
2026-04-05 05:58:15,365 - INFO - Epoch 51/100 - Train Loss: 0.2527 - Val Acc: 0.8696
2026-04-05 05:58:15,641 - INFO - Epoch 52/100 - Train Loss: 0.2529 - Val Acc: 0.8696
2026-04-05 05:58:15,909 - INFO - Epoch 53/100 - Train Loss: 0.2545 - Val Acc: 0.8841
2026-04-05 05:58:16,176 - INFO - Epoch 54/100 - Train Loss: 0.2536 - Val Acc: 0.8696
2026-04-05 05:58:16,445 - INFO - Epoch 55/100 - Train Loss: 0.2515 - Val Acc: 0.8696
2026-04-05 05:58:16,713 - INFO - Epoch 56/100 - Train Loss: 0.2518 - Val Acc: 0.8696
2026-04-05 05:58:16,983 - INFO - Epoch 57/100 - Train Loss: 0.2484 - Val Acc: 0.8696
2026-04-05 05:58:17,253 - INFO - Epoch 58/100 - Train Loss: 0.2511 - Val Acc: 0.8696
2026-04-05 05:58:17,533 - INFO - Epoch 59/100 - Train Loss: 0.2497 - Val Acc: 0.8551
2026-04-05 05:58:17,805 - INFO - Epoch 60/100 - Train Loss: 0.2437 - Val Acc: 0.8696
2026-04-05 05:58:18,078 - INFO - Epoch 61/100 - Train Loss: 0.2493 - Val Acc: 0.8551
2026-04-05 05:58:18,363 - INFO - Epoch 62/100 - Train Loss: 0.2426 - Val Acc: 0.8551
2026-04-05 05:58:18,656 - INFO - Epoch 63/100 - Train Loss: 0.2443 - Val Acc: 0.8696
2026-04-05 05:58:18,927 - INFO - Epoch 64/100 - Train Loss: 0.2422 - Val Acc: 0.8696
2026-04-05 05:58:19,205 - INFO - Epoch 65/100 - Train Loss: 0.2423 - Val Acc: 0.8551
2026-04-05 05:58:19,491 - INFO - Epoch 66/100 - Train Loss: 0.2438 - Val Acc: 0.8551
2026-04-05 05:58:19,777 - INFO - Epoch 67/100 - Train Loss: 0.2431 - Val Acc: 0.8551
2026-04-05 05:58:20,051 - INFO - Epoch 68/100 - Train Loss: 0.2434 - Val Acc: 0.8551
2026-04-05 05:58:20,332 - INFO - Epoch 69/100 - Train Loss: 0.2408 - Val Acc: 0.8551
2026-04-05 05:58:20,626 - INFO - Epoch 70/100 - Train Loss: 0.2400 - Val Acc: 0.8696
2026-04-05 05:58:20,894 - INFO - Epoch 71/100 - Train Loss: 0.2390 - Val Acc: 0.8551
2026-04-05 05:58:21,163 - INFO - Epoch 72/100 - Train Loss: 0.2392 - Val Acc: 0.8551
2026-04-05 05:58:21,433 - INFO - Epoch 73/100 - Train Loss: 0.2362 - Val Acc: 0.8696
2026-04-05 05:58:21,703 - INFO - Epoch 74/100 - Train Loss: 0.2366 - Val Acc: 0.8551
2026-04-05 05:58:21,976 - INFO - Epoch 75/100 - Train Loss: 0.2361 - Val Acc: 0.8551
2026-04-05 05:58:22,241 - INFO - Epoch 76/100 - Train Loss: 0.2346 - Val Acc: 0.8551
2026-04-05 05:58:22,517 - INFO - Epoch 77/100 - Train Loss: 0.2350 - Val Acc: 0.8696
2026-04-05 05:58:22,791 - INFO - Epoch 78/100 - Train Loss: 0.2343 - Val Acc: 0.8696
2026-04-05 05:58:23,056 - INFO - Epoch 79/100 - Train Loss: 0.2326 - Val Acc: 0.8696
2026-04-05 05:58:23,324 - INFO - Epoch 80/100 - Train Loss: 0.2328 - Val Acc: 0.8696
2026-04-05 05:58:23,584 - INFO - Epoch 81/100 - Train Loss: 0.2318 - Val Acc: 0.8696
2026-04-05 05:58:23,848 - INFO - Epoch 82/100 - Train Loss: 0.2315 - Val Acc: 0.8696
2026-04-05 05:58:24,109 - INFO - Epoch 83/100 - Train Loss: 0.2269 - Val Acc: 0.8696
2026-04-05 05:58:24,376 - INFO - Epoch 84/100 - Train Loss: 0.2313 - Val Acc: 0.8696
2026-04-05 05:58:24,675 - INFO - Epoch 85/100 - Train Loss: 0.2282 - Val Acc: 0.8551
2026-04-05 05:58:24,950 - INFO - Epoch 86/100 - Train Loss: 0.2306 - Val Acc: 0.8551
2026-04-05 05:58:25,213 - INFO - Epoch 87/100 - Train Loss: 0.2276 - Val Acc: 0.8696
2026-04-05 05:58:25,490 - INFO - Epoch 88/100 - Train Loss: 0.2303 - Val Acc: 0.8406
2026-04-05 05:58:25,757 - INFO - Epoch 89/100 - Train Loss: 0.2271 - Val Acc: 0.8551
2026-04-05 05:58:26,025 - INFO - Epoch 90/100 - Train Loss: 0.2269 - Val Acc: 0.8551
2026-04-05 05:58:26,284 - INFO - Epoch 91/100 - Train Loss: 0.2237 - Val Acc: 0.8551
2026-04-05 05:58:26,542 - INFO - Epoch 92/100 - Train Loss: 0.2274 - Val Acc: 0.8551
2026-04-05 05:58:26,818 - INFO - Epoch 93/100 - Train Loss: 0.2253 - Val Acc: 0.8551
2026-04-05 05:58:27,095 - INFO - Epoch 94/100 - Train Loss: 0.2266 - Val Acc: 0.8406
2026-04-05 05:58:27,354 - INFO - Epoch 95/100 - Train Loss: 0.2197 - Val Acc: 0.8696
2026-04-05 05:58:27,622 - INFO - Epoch 96/100 - Train Loss: 0.2265 - Val Acc: 0.8551
2026-04-05 05:58:27,889 - INFO - Epoch 97/100 - Train Loss: 0.2192 - Val Acc: 0.8696
2026-04-05 05:58:28,177 - INFO - Epoch 98/100 - Train Loss: 0.2213 - Val Acc: 0.8696
2026-04-05 05:58:28,452 - INFO - Epoch 99/100 - Train Loss: 0.2189 - Val Acc: 0.8696
2026-04-05 05:58:28,720 - INFO - Epoch 100/100 - Train Loss: 0.2201 - Val Acc: 0.8696
2026-04-05 05:58:29,075 - INFO - Fold 6 logically complete. Tensor memory bounds cleared cleanly.
2026-04-05 05:58:29,079 - INFO - Original class distribution: [345 276]
2026-04-05 05:58:29,080 - INFO - Training device bound securely to: cuda

Fold 7:   0%|          | 0/100 [00:00<?, ?it/s]

2026-04-05 05:58:29,380 - INFO - Epoch 1/100 - Train Loss: 0.5436 - Val Acc: 0.7391
2026-04-05 05:58:29,649 - INFO - Epoch 2/100 - Train Loss: 0.3937 - Val Acc: 0.7391
2026-04-05 05:58:29,925 - INFO - Epoch 3/100 - Train Loss: 0.3494 - Val Acc: 0.7536
2026-04-05 05:58:30,193 - INFO - Epoch 4/100 - Train Loss: 0.3268 - Val Acc: 0.7536
2026-04-05 05:58:30,451 - INFO - Epoch 5/100 - Train Loss: 0.3151 - Val Acc: 0.7536
2026-04-05 05:58:30,714 - INFO - Epoch 6/100 - Train Loss: 0.3036 - Val Acc: 0.7536
2026-04-05 05:58:30,988 - INFO - Epoch 7/100 - Train Loss: 0.2975 - Val Acc: 0.7681
2026-04-05 05:58:31,251 - INFO - Epoch 8/100 - Train Loss: 0.2926 - Val Acc: 0.7826
2026-04-05 05:58:31,530 - INFO - Epoch 9/100 - Train Loss: 0.2870 - Val Acc: 0.7826
2026-04-05 05:58:31,806 - INFO - Epoch 10/100 - Train Loss: 0.2812 - Val Acc: 0.7826
2026-04-05 05:58:32,074 - INFO - Epoch 11/100 - Train Loss: 0.2786 - Val Acc: 0.7971
2026-04-05 05:58:32,337 - INFO - Epoch 12/100 - Train Loss: 0.2761 - Val Acc: 0.7971
2026-04-05 05:58:32,612 - INFO - Epoch 13/100 - Train Loss: 0.2744 - Val Acc: 0.7971
2026-04-05 05:58:32,891 - INFO - Epoch 14/100 - Train Loss: 0.2735 - Val Acc: 0.8116
2026-04-05 05:58:33,163 - INFO - Epoch 15/100 - Train Loss: 0.2712 - Val Acc: 0.8116
2026-04-05 05:58:33,442 - INFO - Epoch 16/100 - Train Loss: 0.2700 - Val Acc: 0.8116
2026-04-05 05:58:33,707 - INFO - Epoch 17/100 - Train Loss: 0.2702 - Val Acc: 0.8116
2026-04-05 05:58:33,976 - INFO - Epoch 18/100 - Train Loss: 0.2675 - Val Acc: 0.8116
2026-04-05 05:58:34,257 - INFO - Epoch 19/100 - Train Loss: 0.2663 - Val Acc: 0.8116
2026-04-05 05:58:34,554 - INFO - Epoch 20/100 - Train Loss: 0.2627 - Val Acc: 0.8406
2026-04-05 05:58:34,861 - INFO - Epoch 21/100 - Train Loss: 0.2614 - Val Acc: 0.8261
2026-04-05 05:58:35,146 - INFO - Epoch 22/100 - Train Loss: 0.2609 - Val Acc: 0.8116
2026-04-05 05:58:35,429 - INFO - Epoch 23/100 - Train Loss: 0.2599 - Val Acc: 0.8261
2026-04-05 05:58:35,690 - INFO - Epoch 24/100 - Train Loss: 0.2572 - Val Acc: 0.7826
2026-04-05 05:58:35,954 - INFO - Epoch 25/100 - Train Loss: 0.2566 - Val Acc: 0.7826
2026-04-05 05:58:36,230 - INFO - Epoch 26/100 - Train Loss: 0.2554 - Val Acc: 0.7681
2026-04-05 05:58:36,508 - INFO - Epoch 27/100 - Train Loss: 0.2574 - Val Acc: 0.7681
2026-04-05 05:58:36,788 - INFO - Epoch 28/100 - Train Loss: 0.2530 - Val Acc: 0.7681
2026-04-05 05:58:37,077 - INFO - Epoch 29/100 - Train Loss: 0.2521 - Val Acc: 0.7681
2026-04-05 05:58:37,345 - INFO - Epoch 30/100 - Train Loss: 0.2504 - Val Acc: 0.7681
2026-04-05 05:58:37,618 - INFO - Epoch 31/100 - Train Loss: 0.2490 - Val Acc: 0.7681
2026-04-05 05:58:37,883 - INFO - Epoch 32/100 - Train Loss: 0.2498 - Val Acc: 0.7681
2026-04-05 05:58:38,149 - INFO - Epoch 33/100 - Train Loss: 0.2498 - Val Acc: 0.7681
2026-04-05 05:58:38,412 - INFO - Epoch 34/100 - Train Loss: 0.2471 - Val Acc: 0.7681
2026-04-05 05:58:38,680 - INFO - Epoch 35/100 - Train Loss: 0.2461 - Val Acc: 0.7681
2026-04-05 05:58:38,956 - INFO - Epoch 36/100 - Train Loss: 0.2424 - Val Acc: 0.7681
2026-04-05 05:58:39,225 - INFO - Epoch 37/100 - Train Loss: 0.2444 - Val Acc: 0.7681
2026-04-05 05:58:39,490 - INFO - Epoch 38/100 - Train Loss: 0.2462 - Val Acc: 0.7681
2026-04-05 05:58:39,756 - INFO - Epoch 39/100 - Train Loss: 0.2430 - Val Acc: 0.7681
2026-04-05 05:58:40,025 - INFO - Epoch 40/100 - Train Loss: 0.2411 - Val Acc: 0.7681
2026-04-05 05:58:40,291 - INFO - Epoch 41/100 - Train Loss: 0.2445 - Val Acc: 0.7681
2026-04-05 05:58:40,562 - INFO - Epoch 42/100 - Train Loss: 0.2385 - Val Acc: 0.7681
2026-04-05 05:58:40,832 - INFO - Epoch 43/100 - Train Loss: 0.2397 - Val Acc: 0.7681
2026-04-05 05:58:41,103 - INFO - Epoch 44/100 - Train Loss: 0.2379 - Val Acc: 0.7681
2026-04-05 05:58:41,375 - INFO - Epoch 45/100 - Train Loss: 0.2385 - Val Acc: 0.7681
2026-04-05 05:58:41,647 - INFO - Epoch 46/100 - Train Loss: 0.2363 - Val Acc: 0.7681
2026-04-05 05:58:41,925 - INFO - Epoch 47/100 - Train Loss: 0.2366 - Val Acc: 0.7681
2026-04-05 05:58:42,189 - INFO - Epoch 48/100 - Train Loss: 0.2349 - Val Acc: 0.7681
2026-04-05 05:58:42,448 - INFO - Epoch 49/100 - Train Loss: 0.2323 - Val Acc: 0.7681
2026-04-05 05:58:42,713 - INFO - Epoch 50/100 - Train Loss: 0.2335 - Val Acc: 0.7681
2026-04-05 05:58:42,976 - INFO - Epoch 51/100 - Train Loss: 0.2318 - Val Acc: 0.7681
2026-04-05 05:58:43,241 - INFO - Epoch 52/100 - Train Loss: 0.2300 - Val Acc: 0.7681
2026-04-05 05:58:43,510 - INFO - Epoch 53/100 - Train Loss: 0.2318 - Val Acc: 0.7681
2026-04-05 05:58:43,772 - INFO - Epoch 54/100 - Train Loss: 0.2291 - Val Acc: 0.7681
2026-04-05 05:58:44,039 - INFO - Epoch 55/100 - Train Loss: 0.2304 - Val Acc: 0.7681
2026-04-05 05:58:44,314 - INFO - Epoch 56/100 - Train Loss: 0.2253 - Val Acc: 0.7681
2026-04-05 05:58:44,616 - INFO - Epoch 57/100 - Train Loss: 0.2265 - Val Acc: 0.7681
2026-04-05 05:58:44,892 - INFO - Epoch 58/100 - Train Loss: 0.2266 - Val Acc: 0.7681
2026-04-05 05:58:45,160 - INFO - Epoch 59/100 - Train Loss: 0.2217 - Val Acc: 0.7681
2026-04-05 05:58:45,439 - INFO - Epoch 60/100 - Train Loss: 0.2265 - Val Acc: 0.7681
2026-04-05 05:58:45,704 - INFO - Epoch 61/100 - Train Loss: 0.2233 - Val Acc: 0.7681
2026-04-05 05:58:45,963 - INFO - Epoch 62/100 - Train Loss: 0.2262 - Val Acc: 0.7681
2026-04-05 05:58:46,247 - INFO - Epoch 63/100 - Train Loss: 0.2200 - Val Acc: 0.7681
2026-04-05 05:58:46,522 - INFO - Epoch 64/100 - Train Loss: 0.2176 - Val Acc: 0.7681
2026-04-05 05:58:46,798 - INFO - Epoch 65/100 - Train Loss: 0.2207 - Val Acc: 0.7681
2026-04-05 05:58:47,060 - INFO - Epoch 66/100 - Train Loss: 0.2185 - Val Acc: 0.7681
2026-04-05 05:58:47,326 - INFO - Epoch 67/100 - Train Loss: 0.2225 - Val Acc: 0.7681
2026-04-05 05:58:47,608 - INFO - Epoch 68/100 - Train Loss: 0.2180 - Val Acc: 0.7681
2026-04-05 05:58:47,869 - INFO - Epoch 69/100 - Train Loss: 0.2188 - Val Acc: 0.7681
2026-04-05 05:58:48,142 - INFO - Epoch 70/100 - Train Loss: 0.2202 - Val Acc: 0.7681
2026-04-05 05:58:48,427 - INFO - Epoch 71/100 - Train Loss: 0.2156 - Val Acc: 0.7681
2026-04-05 05:58:48,712 - INFO - Epoch 72/100 - Train Loss: 0.2137 - Val Acc: 0.7681
2026-04-05 05:58:48,984 - INFO - Epoch 73/100 - Train Loss: 0.2153 - Val Acc: 0.7681
2026-04-05 05:58:49,268 - INFO - Epoch 74/100 - Train Loss: 0.2176 - Val Acc: 0.7681
2026-04-05 05:58:49,534 - INFO - Epoch 75/100 - Train Loss: 0.2129 - Val Acc: 0.7681
2026-04-05 05:58:49,807 - INFO - Epoch 76/100 - Train Loss: 0.2137 - Val Acc: 0.7681
2026-04-05 05:58:50,079 - INFO - Epoch 77/100 - Train Loss: 0.2129 - Val Acc: 0.7681
2026-04-05 05:58:50,346 - INFO - Epoch 78/100 - Train Loss: 0.2142 - Val Acc: 0.7681
2026-04-05 05:58:50,624 - INFO - Epoch 79/100 - Train Loss: 0.2161 - Val Acc: 0.7681
2026-04-05 05:58:50,895 - INFO - Epoch 80/100 - Train Loss: 0.2117 - Val Acc: 0.7681
2026-04-05 05:58:51,167 - INFO - Epoch 81/100 - Train Loss: 0.2123 - Val Acc: 0.7681
2026-04-05 05:58:51,436 - INFO - Epoch 82/100 - Train Loss: 0.2088 - Val Acc: 0.7681
2026-04-05 05:58:51,707 - INFO - Epoch 83/100 - Train Loss: 0.2107 - Val Acc: 0.7681
2026-04-05 05:58:51,999 - INFO - Epoch 84/100 - Train Loss: 0.2115 - Val Acc: 0.7681
2026-04-05 05:58:52,272 - INFO - Epoch 85/100 - Train Loss: 0.2118 - Val Acc: 0.7681
2026-04-05 05:58:52,553 - INFO - Epoch 86/100 - Train Loss: 0.2050 - Val Acc: 0.7681
2026-04-05 05:58:52,825 - INFO - Epoch 87/100 - Train Loss: 0.2066 - Val Acc: 0.7681
2026-04-05 05:58:53,091 - INFO - Epoch 88/100 - Train Loss: 0.2108 - Val Acc: 0.7681
2026-04-05 05:58:53,362 - INFO - Epoch 89/100 - Train Loss: 0.2083 - Val Acc: 0.7826
2026-04-05 05:58:53,646 - INFO - Epoch 90/100 - Train Loss: 0.2059 - Val Acc: 0.7681
2026-04-05 05:58:53,905 - INFO - Epoch 91/100 - Train Loss: 0.2049 - Val Acc: 0.7681
2026-04-05 05:58:54,183 - INFO - Epoch 92/100 - Train Loss: 0.2031 - Val Acc: 0.7681
2026-04-05 05:58:54,456 - INFO - Epoch 93/100 - Train Loss: 0.2048 - Val Acc: 0.7681
2026-04-05 05:58:54,756 - INFO - Epoch 94/100 - Train Loss: 0.2048 - Val Acc: 0.7681
2026-04-05 05:58:55,020 - INFO - Epoch 95/100 - Train Loss: 0.2097 - Val Acc: 0.7681
2026-04-05 05:58:55,299 - INFO - Epoch 96/100 - Train Loss: 0.2046 - Val Acc: 0.7681
2026-04-05 05:58:55,570 - INFO - Epoch 97/100 - Train Loss: 0.2022 - Val Acc: 0.7826
2026-04-05 05:58:55,847 - INFO - Epoch 98/100 - Train Loss: 0.2049 - Val Acc: 0.7681
2026-04-05 05:58:56,124 - INFO - Epoch 99/100 - Train Loss: 0.1997 - Val Acc: 0.7681
2026-04-05 05:58:56,408 - INFO - Epoch 100/100 - Train Loss: 0.2001 - Val Acc: 0.7681
2026-04-05 05:58:56,773 - INFO - Fold 7 logically complete. Tensor memory bounds cleared cleanly.
2026-04-05 05:58:56,776 - INFO - Original class distribution: [345 276]
2026-04-05 05:58:56,777 - INFO - Training device bound securely to: cuda

Fold 8:   0%|          | 0/100 [00:00<?, ?it/s]

2026-04-05 05:58:57,073 - INFO - Epoch 1/100 - Train Loss: 0.5617 - Val Acc: 0.8841
2026-04-05 05:58:57,336 - INFO - Epoch 2/100 - Train Loss: 0.4093 - Val Acc: 0.8841
2026-04-05 05:58:57,590 - INFO - Epoch 3/100 - Train Loss: 0.3635 - Val Acc: 0.8696
2026-04-05 05:58:57,865 - INFO - Epoch 4/100 - Train Loss: 0.3442 - Val Acc: 0.8406
2026-04-05 05:58:58,139 - INFO - Epoch 5/100 - Train Loss: 0.3306 - Val Acc: 0.8261
2026-04-05 05:58:58,410 - INFO - Epoch 6/100 - Train Loss: 0.3240 - Val Acc: 0.8261
2026-04-05 05:58:58,690 - INFO - Epoch 7/100 - Train Loss: 0.3146 - Val Acc: 0.8116
2026-04-05 05:58:58,951 - INFO - Epoch 8/100 - Train Loss: 0.3077 - Val Acc: 0.8261
2026-04-05 05:58:59,210 - INFO - Epoch 9/100 - Train Loss: 0.3046 - Val Acc: 0.8261
2026-04-05 05:58:59,472 - INFO - Epoch 10/100 - Train Loss: 0.3001 - Val Acc: 0.8261
2026-04-05 05:58:59,732 - INFO - Epoch 11/100 - Train Loss: 0.2983 - Val Acc: 0.8406
2026-04-05 05:58:59,998 - INFO - Epoch 12/100 - Train Loss: 0.2947 - Val Acc: 0.8406
2026-04-05 05:59:00,261 - INFO - Epoch 13/100 - Train Loss: 0.2956 - Val Acc: 0.8406
2026-04-05 05:59:00,533 - INFO - Epoch 14/100 - Train Loss: 0.2947 - Val Acc: 0.8406
2026-04-05 05:59:00,805 - INFO - Epoch 15/100 - Train Loss: 0.2912 - Val Acc: 0.8406
2026-04-05 05:59:01,068 - INFO - Epoch 16/100 - Train Loss: 0.2901 - Val Acc: 0.8406
2026-04-05 05:59:01,341 - INFO - Epoch 17/100 - Train Loss: 0.2892 - Val Acc: 0.8406
2026-04-05 05:59:01,600 - INFO - Epoch 18/100 - Train Loss: 0.2848 - Val Acc: 0.8406
2026-04-05 05:59:01,865 - INFO - Epoch 19/100 - Train Loss: 0.2886 - Val Acc: 0.8406
2026-04-05 05:59:02,146 - INFO - Epoch 20/100 - Train Loss: 0.2865 - Val Acc: 0.8406
2026-04-05 05:59:02,406 - INFO - Epoch 21/100 - Train Loss: 0.2842 - Val Acc: 0.8406
2026-04-05 05:59:02,670 - INFO - Epoch 22/100 - Train Loss: 0.2838 - Val Acc: 0.8406
2026-04-05 05:59:02,926 - INFO - Epoch 23/100 - Train Loss: 0.2824 - Val Acc: 0.8406
2026-04-05 05:59:03,190 - INFO - Epoch 24/100 - Train Loss: 0.2815 - Val Acc: 0.8406
2026-04-05 05:59:03,445 - INFO - Epoch 25/100 - Train Loss: 0.2801 - Val Acc: 0.8406
2026-04-05 05:59:03,711 - INFO - Epoch 26/100 - Train Loss: 0.2771 - Val Acc: 0.8406
2026-04-05 05:59:03,974 - INFO - Epoch 27/100 - Train Loss: 0.2757 - Val Acc: 0.8406
2026-04-05 05:59:04,251 - INFO - Epoch 28/100 - Train Loss: 0.2761 - Val Acc: 0.8406
2026-04-05 05:59:04,529 - INFO - Epoch 29/100 - Train Loss: 0.2750 - Val Acc: 0.8406
2026-04-05 05:59:04,815 - INFO - Epoch 30/100 - Train Loss: 0.2736 - Val Acc: 0.8406
2026-04-05 05:59:05,088 - INFO - Epoch 31/100 - Train Loss: 0.2748 - Val Acc: 0.8406
2026-04-05 05:59:05,349 - INFO - Epoch 32/100 - Train Loss: 0.2707 - Val Acc: 0.8406
2026-04-05 05:59:05,621 - INFO - Epoch 33/100 - Train Loss: 0.2686 - Val Acc: 0.8406
2026-04-05 05:59:05,884 - INFO - Epoch 34/100 - Train Loss: 0.2673 - Val Acc: 0.8406
2026-04-05 05:59:06,166 - INFO - Epoch 35/100 - Train Loss: 0.2646 - Val Acc: 0.8406
2026-04-05 05:59:06,443 - INFO - Epoch 36/100 - Train Loss: 0.2665 - Val Acc: 0.8551
2026-04-05 05:59:06,732 - INFO - Epoch 37/100 - Train Loss: 0.2680 - Val Acc: 0.8551
2026-04-05 05:59:07,020 - INFO - Epoch 38/100 - Train Loss: 0.2643 - Val Acc: 0.8551
2026-04-05 05:59:07,284 - INFO - Epoch 39/100 - Train Loss: 0.2634 - Val Acc: 0.8551
2026-04-05 05:59:07,550 - INFO - Epoch 40/100 - Train Loss: 0.2642 - Val Acc: 0.8551
2026-04-05 05:59:07,830 - INFO - Epoch 41/100 - Train Loss: 0.2617 - Val Acc: 0.8551
2026-04-05 05:59:08,107 - INFO - Epoch 42/100 - Train Loss: 0.2592 - Val Acc: 0.8551
2026-04-05 05:59:08,389 - INFO - Epoch 43/100 - Train Loss: 0.2619 - Val Acc: 0.8551
2026-04-05 05:59:08,659 - INFO - Epoch 44/100 - Train Loss: 0.2611 - Val Acc: 0.8551
2026-04-05 05:59:08,922 - INFO - Epoch 45/100 - Train Loss: 0.2580 - Val Acc: 0.8551
2026-04-05 05:59:09,188 - INFO - Epoch 46/100 - Train Loss: 0.2543 - Val Acc: 0.8696
2026-04-05 05:59:09,460 - INFO - Epoch 47/100 - Train Loss: 0.2555 - Val Acc: 0.8696
2026-04-05 05:59:09,728 - INFO - Epoch 48/100 - Train Loss: 0.2580 - Val Acc: 0.8551
2026-04-05 05:59:10,001 - INFO - Epoch 49/100 - Train Loss: 0.2513 - Val Acc: 0.8406
2026-04-05 05:59:10,267 - INFO - Epoch 50/100 - Train Loss: 0.2526 - Val Acc: 0.8406
2026-04-05 05:59:10,541 - INFO - Epoch 51/100 - Train Loss: 0.2524 - Val Acc: 0.8406
2026-04-05 05:59:10,823 - INFO - Epoch 52/100 - Train Loss: 0.2480 - Val Acc: 0.8551
2026-04-05 05:59:11,095 - INFO - Epoch 53/100 - Train Loss: 0.2460 - Val Acc: 0.8551
2026-04-05 05:59:11,370 - INFO - Epoch 54/100 - Train Loss: 0.2497 - Val Acc: 0.8551
2026-04-05 05:59:11,647 - INFO - Epoch 55/100 - Train Loss: 0.2465 - Val Acc: 0.8551
2026-04-05 05:59:11,919 - INFO - Epoch 56/100 - Train Loss: 0.2468 - Val Acc: 0.8551
2026-04-05 05:59:12,183 - INFO - Epoch 57/100 - Train Loss: 0.2469 - Val Acc: 0.8551
2026-04-05 05:59:12,482 - INFO - Epoch 58/100 - Train Loss: 0.2431 - Val Acc: 0.8551
2026-04-05 05:59:12,759 - INFO - Epoch 59/100 - Train Loss: 0.2452 - Val Acc: 0.8551
2026-04-05 05:59:13,067 - INFO - Epoch 60/100 - Train Loss: 0.2443 - Val Acc: 0.8551
2026-04-05 05:59:13,371 - INFO - Epoch 61/100 - Train Loss: 0.2444 - Val Acc: 0.8551
2026-04-05 05:59:13,681 - INFO - Epoch 62/100 - Train Loss: 0.2426 - Val Acc: 0.8551
2026-04-05 05:59:13,970 - INFO - Epoch 63/100 - Train Loss: 0.2418 - Val Acc: 0.8551
2026-04-05 05:59:14,246 - INFO - Epoch 64/100 - Train Loss: 0.2422 - Val Acc: 0.8551
2026-04-05 05:59:14,535 - INFO - Epoch 65/100 - Train Loss: 0.2403 - Val Acc: 0.8551
2026-04-05 05:59:14,816 - INFO - Epoch 66/100 - Train Loss: 0.2369 - Val Acc: 0.8551
2026-04-05 05:59:15,100 - INFO - Epoch 67/100 - Train Loss: 0.2385 - Val Acc: 0.8551
2026-04-05 05:59:15,382 - INFO - Epoch 68/100 - Train Loss: 0.2387 - Val Acc: 0.8551
2026-04-05 05:59:15,655 - INFO - Epoch 69/100 - Train Loss: 0.2373 - Val Acc: 0.8551
2026-04-05 05:59:15,933 - INFO - Epoch 70/100 - Train Loss: 0.2356 - Val Acc: 0.8551
2026-04-05 05:59:16,229 - INFO - Epoch 71/100 - Train Loss: 0.2419 - Val Acc: 0.8551
2026-04-05 05:59:16,508 - INFO - Epoch 72/100 - Train Loss: 0.2329 - Val Acc: 0.8551
2026-04-05 05:59:16,780 - INFO - Epoch 73/100 - Train Loss: 0.2332 - Val Acc: 0.8551
2026-04-05 05:59:17,049 - INFO - Epoch 74/100 - Train Loss: 0.2369 - Val Acc: 0.8551
2026-04-05 05:59:17,313 - INFO - Epoch 75/100 - Train Loss: 0.2297 - Val Acc: 0.8551
2026-04-05 05:59:17,577 - INFO - Epoch 76/100 - Train Loss: 0.2297 - Val Acc: 0.8551
2026-04-05 05:59:17,849 - INFO - Epoch 77/100 - Train Loss: 0.2328 - Val Acc: 0.8551
2026-04-05 05:59:18,124 - INFO - Epoch 78/100 - Train Loss: 0.2299 - Val Acc: 0.8551
2026-04-05 05:59:18,395 - INFO - Epoch 79/100 - Train Loss: 0.2269 - Val Acc: 0.8551
2026-04-05 05:59:18,676 - INFO - Epoch 80/100 - Train Loss: 0.2283 - Val Acc: 0.8406
2026-04-05 05:59:18,945 - INFO - Epoch 81/100 - Train Loss: 0.2289 - Val Acc: 0.8551
2026-04-05 05:59:19,220 - INFO - Epoch 82/100 - Train Loss: 0.2260 - Val Acc: 0.8551
2026-04-05 05:59:19,491 - INFO - Epoch 83/100 - Train Loss: 0.2276 - Val Acc: 0.8406
2026-04-05 05:59:19,776 - INFO - Epoch 84/100 - Train Loss: 0.2279 - Val Acc: 0.8551
2026-04-05 05:59:20,044 - INFO - Epoch 85/100 - Train Loss: 0.2256 - Val Acc: 0.8551
2026-04-05 05:59:20,322 - INFO - Epoch 86/100 - Train Loss: 0.2275 - Val Acc: 0.8406
2026-04-05 05:59:20,588 - INFO - Epoch 87/100 - Train Loss: 0.2250 - Val Acc: 0.8551
2026-04-05 05:59:20,854 - INFO - Epoch 88/100 - Train Loss: 0.2308 - Val Acc: 0.8406
2026-04-05 05:59:21,124 - INFO - Epoch 89/100 - Train Loss: 0.2221 - Val Acc: 0.8406
2026-04-05 05:59:21,400 - INFO - Epoch 90/100 - Train Loss: 0.2217 - Val Acc: 0.8261
2026-04-05 05:59:21,666 - INFO - Epoch 91/100 - Train Loss: 0.2209 - Val Acc: 0.8406
2026-04-05 05:59:21,930 - INFO - Epoch 92/100 - Train Loss: 0.2191 - Val Acc: 0.8406
2026-04-05 05:59:22,202 - INFO - Epoch 93/100 - Train Loss: 0.2242 - Val Acc: 0.8406
2026-04-05 05:59:22,470 - INFO - Epoch 94/100 - Train Loss: 0.2229 - Val Acc: 0.8406
2026-04-05 05:59:22,739 - INFO - Epoch 95/100 - Train Loss: 0.2181 - Val Acc: 0.8406
2026-04-05 05:59:23,030 - INFO - Epoch 96/100 - Train Loss: 0.2214 - Val Acc: 0.8406
2026-04-05 05:59:23,295 - INFO - Epoch 97/100 - Train Loss: 0.2180 - Val Acc: 0.8406
2026-04-05 05:59:23,571 - INFO - Epoch 98/100 - Train Loss: 0.2215 - Val Acc: 0.8406
2026-04-05 05:59:23,837 - INFO - Epoch 99/100 - Train Loss: 0.2206 - Val Acc: 0.8406
2026-04-05 05:59:24,123 - INFO - Epoch 100/100 - Train Loss: 0.2148 - Val Acc: 0.8406
2026-04-05 05:59:24,481 - INFO - Fold 8 logically complete. Tensor memory bounds cleared cleanly.
2026-04-05 05:59:24,485 - INFO - Original class distribution: [345 276]
2026-04-05 05:59:24,486 - INFO - Training device bound securely to: cuda

Fold 9:   0%|          | 0/100 [00:00<?, ?it/s]

2026-04-05 05:59:24,788 - INFO - Epoch 1/100 - Train Loss: 0.5580 - Val Acc: 0.8116
2026-04-05 05:59:25,061 - INFO - Epoch 2/100 - Train Loss: 0.4012 - Val Acc: 0.8406
2026-04-05 05:59:25,338 - INFO - Epoch 3/100 - Train Loss: 0.3573 - Val Acc: 0.8406
2026-04-05 05:59:25,617 - INFO - Epoch 4/100 - Train Loss: 0.3385 - Val Acc: 0.8116
2026-04-05 05:59:25,877 - INFO - Epoch 5/100 - Train Loss: 0.3227 - Val Acc: 0.8261
2026-04-05 05:59:26,142 - INFO - Epoch 6/100 - Train Loss: 0.3113 - Val Acc: 0.8261
2026-04-05 05:59:26,407 - INFO - Epoch 7/100 - Train Loss: 0.3057 - Val Acc: 0.8261
2026-04-05 05:59:26,670 - INFO - Epoch 8/100 - Train Loss: 0.3017 - Val Acc: 0.8116
2026-04-05 05:59:26,944 - INFO - Epoch 9/100 - Train Loss: 0.2985 - Val Acc: 0.8116
2026-04-05 05:59:27,213 - INFO - Epoch 10/100 - Train Loss: 0.2932 - Val Acc: 0.8116
2026-04-05 05:59:27,476 - INFO - Epoch 11/100 - Train Loss: 0.2921 - Val Acc: 0.8116
2026-04-05 05:59:27,749 - INFO - Epoch 12/100 - Train Loss: 0.2915 - Val Acc: 0.8116
2026-04-05 05:59:28,026 - INFO - Epoch 13/100 - Train Loss: 0.2886 - Val Acc: 0.8116
2026-04-05 05:59:28,288 - INFO - Epoch 14/100 - Train Loss: 0.2846 - Val Acc: 0.8116
2026-04-05 05:59:28,557 - INFO - Epoch 15/100 - Train Loss: 0.2856 - Val Acc: 0.7971
2026-04-05 05:59:28,836 - INFO - Epoch 16/100 - Train Loss: 0.2828 - Val Acc: 0.7971
2026-04-05 05:59:29,102 - INFO - Epoch 17/100 - Train Loss: 0.2823 - Val Acc: 0.8116
2026-04-05 05:59:29,365 - INFO - Epoch 18/100 - Train Loss: 0.2780 - Val Acc: 0.8116
2026-04-05 05:59:29,632 - INFO - Epoch 19/100 - Train Loss: 0.2785 - Val Acc: 0.8116
2026-04-05 05:59:29,904 - INFO - Epoch 20/100 - Train Loss: 0.2807 - Val Acc: 0.8116
2026-04-05 05:59:30,183 - INFO - Epoch 21/100 - Train Loss: 0.2789 - Val Acc: 0.8116
2026-04-05 05:59:30,463 - INFO - Epoch 22/100 - Train Loss: 0.2748 - Val Acc: 0.7971
2026-04-05 05:59:30,744 - INFO - Epoch 23/100 - Train Loss: 0.2739 - Val Acc: 0.7971
2026-04-05 05:59:31,016 - INFO - Epoch 24/100 - Train Loss: 0.2736 - Val Acc: 0.7971
2026-04-05 05:59:31,288 - INFO - Epoch 25/100 - Train Loss: 0.2712 - Val Acc: 0.7971
2026-04-05 05:59:31,559 - INFO - Epoch 26/100 - Train Loss: 0.2710 - Val Acc: 0.7971
2026-04-05 05:59:31,831 - INFO - Epoch 27/100 - Train Loss: 0.2676 - Val Acc: 0.8116
2026-04-05 05:59:32,091 - INFO - Epoch 28/100 - Train Loss: 0.2709 - Val Acc: 0.7971
2026-04-05 05:59:32,364 - INFO - Epoch 29/100 - Train Loss: 0.2698 - Val Acc: 0.8116
2026-04-05 05:59:32,637 - INFO - Epoch 30/100 - Train Loss: 0.2659 - Val Acc: 0.8116
2026-04-05 05:59:32,911 - INFO - Epoch 31/100 - Train Loss: 0.2698 - Val Acc: 0.8261
2026-04-05 05:59:33,173 - INFO - Epoch 32/100 - Train Loss: 0.2653 - Val Acc: 0.8261
2026-04-05 05:59:33,446 - INFO - Epoch 33/100 - Train Loss: 0.2657 - Val Acc: 0.8261
2026-04-05 05:59:33,718 - INFO - Epoch 34/100 - Train Loss: 0.2653 - Val Acc: 0.8261
2026-04-05 05:59:34,004 - INFO - Epoch 35/100 - Train Loss: 0.2652 - Val Acc: 0.8261
2026-04-05 05:59:34,280 - INFO - Epoch 36/100 - Train Loss: 0.2625 - Val Acc: 0.8116
2026-04-05 05:59:34,576 - INFO - Epoch 37/100 - Train Loss: 0.2634 - Val Acc: 0.8116
2026-04-05 05:59:34,846 - INFO - Epoch 38/100 - Train Loss: 0.2590 - Val Acc: 0.8261
2026-04-05 05:59:35,116 - INFO - Epoch 39/100 - Train Loss: 0.2592 - Val Acc: 0.8261
2026-04-05 05:59:35,378 - INFO - Epoch 40/100 - Train Loss: 0.2583 - Val Acc: 0.8116
2026-04-05 05:59:35,648 - INFO - Epoch 41/100 - Train Loss: 0.2583 - Val Acc: 0.8116
2026-04-05 05:59:35,926 - INFO - Epoch 42/100 - Train Loss: 0.2573 - Val Acc: 0.8261
2026-04-05 05:59:36,200 - INFO - Epoch 43/100 - Train Loss: 0.2577 - Val Acc: 0.8261
2026-04-05 05:59:36,479 - INFO - Epoch 44/100 - Train Loss: 0.2534 - Val Acc: 0.8261
2026-04-05 05:59:36,749 - INFO - Epoch 45/100 - Train Loss: 0.2544 - Val Acc: 0.8261
2026-04-05 05:59:37,018 - INFO - Epoch 46/100 - Train Loss: 0.2508 - Val Acc: 0.8116
2026-04-05 05:59:37,300 - INFO - Epoch 47/100 - Train Loss: 0.2539 - Val Acc: 0.8116
2026-04-05 05:59:37,576 - INFO - Epoch 48/100 - Train Loss: 0.2533 - Val Acc: 0.8261
2026-04-05 05:59:37,847 - INFO - Epoch 49/100 - Train Loss: 0.2507 - Val Acc: 0.8261
2026-04-05 05:59:38,128 - INFO - Epoch 50/100 - Train Loss: 0.2481 - Val Acc: 0.8261
2026-04-05 05:59:38,410 - INFO - Epoch 51/100 - Train Loss: 0.2499 - Val Acc: 0.8116
2026-04-05 05:59:38,680 - INFO - Epoch 52/100 - Train Loss: 0.2481 - Val Acc: 0.8261
2026-04-05 05:59:38,950 - INFO - Epoch 53/100 - Train Loss: 0.2460 - Val Acc: 0.8116
2026-04-05 05:59:39,225 - INFO - Epoch 54/100 - Train Loss: 0.2464 - Val Acc: 0.8261
2026-04-05 05:59:39,495 - INFO - Epoch 55/100 - Train Loss: 0.2463 - Val Acc: 0.8261
2026-04-05 05:59:39,781 - INFO - Epoch 56/100 - Train Loss: 0.2454 - Val Acc: 0.8116
2026-04-05 05:59:40,056 - INFO - Epoch 57/100 - Train Loss: 0.2465 - Val Acc: 0.8116
2026-04-05 05:59:40,322 - INFO - Epoch 58/100 - Train Loss: 0.2443 - Val Acc: 0.8261
2026-04-05 05:59:40,598 - INFO - Epoch 59/100 - Train Loss: 0.2401 - Val Acc: 0.8261
2026-04-05 05:59:40,870 - INFO - Epoch 60/100 - Train Loss: 0.2400 - Val Acc: 0.8261
2026-04-05 05:59:41,143 - INFO - Epoch 61/100 - Train Loss: 0.2396 - Val Acc: 0.8116
2026-04-05 05:59:41,412 - INFO - Epoch 62/100 - Train Loss: 0.2376 - Val Acc: 0.8261
2026-04-05 05:59:41,681 - INFO - Epoch 63/100 - Train Loss: 0.2388 - Val Acc: 0.8261
2026-04-05 05:59:41,974 - INFO - Epoch 64/100 - Train Loss: 0.2362 - Val Acc: 0.8261
2026-04-05 05:59:42,242 - INFO - Epoch 65/100 - Train Loss: 0.2349 - Val Acc: 0.8261
2026-04-05 05:59:42,519 - INFO - Epoch 66/100 - Train Loss: 0.2404 - Val Acc: 0.8261
2026-04-05 05:59:42,795 - INFO - Epoch 67/100 - Train Loss: 0.2347 - Val Acc: 0.8261
2026-04-05 05:59:43,065 - INFO - Epoch 68/100 - Train Loss: 0.2342 - Val Acc: 0.8261
2026-04-05 05:59:43,340 - INFO - Epoch 69/100 - Train Loss: 0.2302 - Val Acc: 0.8406
2026-04-05 05:59:43,605 - INFO - Epoch 70/100 - Train Loss: 0.2319 - Val Acc: 0.8261
2026-04-05 05:59:43,898 - INFO - Epoch 71/100 - Train Loss: 0.2301 - Val Acc: 0.8261
2026-04-05 05:59:44,169 - INFO - Epoch 72/100 - Train Loss: 0.2305 - Val Acc: 0.8406
2026-04-05 05:59:44,435 - INFO - Epoch 73/100 - Train Loss: 0.2294 - Val Acc: 0.8406
2026-04-05 05:59:44,731 - INFO - Epoch 74/100 - Train Loss: 0.2291 - Val Acc: 0.8406
2026-04-05 05:59:44,995 - INFO - Epoch 75/100 - Train Loss: 0.2314 - Val Acc: 0.8406
2026-04-05 05:59:45,276 - INFO - Epoch 76/100 - Train Loss: 0.2269 - Val Acc: 0.8406
2026-04-05 05:59:45,540 - INFO - Epoch 77/100 - Train Loss: 0.2249 - Val Acc: 0.8551
2026-04-05 05:59:45,812 - INFO - Epoch 78/100 - Train Loss: 0.2284 - Val Acc: 0.8406
2026-04-05 05:59:46,074 - INFO - Epoch 79/100 - Train Loss: 0.2279 - Val Acc: 0.8406
2026-04-05 05:59:46,348 - INFO - Epoch 80/100 - Train Loss: 0.2229 - Val Acc: 0.8551
2026-04-05 05:59:46,623 - INFO - Epoch 81/100 - Train Loss: 0.2226 - Val Acc: 0.8551
2026-04-05 05:59:46,897 - INFO - Epoch 82/100 - Train Loss: 0.2249 - Val Acc: 0.8406
2026-04-05 05:59:47,164 - INFO - Epoch 83/100 - Train Loss: 0.2293 - Val Acc: 0.8551
2026-04-05 05:59:47,441 - INFO - Epoch 84/100 - Train Loss: 0.2243 - Val Acc: 0.8551
2026-04-05 05:59:47,704 - INFO - Epoch 85/100 - Train Loss: 0.2238 - Val Acc: 0.8551
2026-04-05 05:59:47,975 - INFO - Epoch 86/100 - Train Loss: 0.2212 - Val Acc: 0.8551
2026-04-05 05:59:48,249 - INFO - Epoch 87/100 - Train Loss: 0.2204 - Val Acc: 0.8551
2026-04-05 05:59:48,518 - INFO - Epoch 88/100 - Train Loss: 0.2235 - Val Acc: 0.8551
2026-04-05 05:59:48,798 - INFO - Epoch 89/100 - Train Loss: 0.2186 - Val Acc: 0.8551
2026-04-05 05:59:49,067 - INFO - Epoch 90/100 - Train Loss: 0.2180 - Val Acc: 0.8551
2026-04-05 05:59:49,327 - INFO - Epoch 91/100 - Train Loss: 0.2217 - Val Acc: 0.8406
2026-04-05 05:59:49,597 - INFO - Epoch 92/100 - Train Loss: 0.2218 - Val Acc: 0.8406
2026-04-05 05:59:49,869 - INFO - Epoch 93/100 - Train Loss: 0.2187 - Val Acc: 0.8406
2026-04-05 05:59:50,140 - INFO - Epoch 94/100 - Train Loss: 0.2151 - Val Acc: 0.8406
2026-04-05 05:59:50,417 - INFO - Epoch 95/100 - Train Loss: 0.2179 - Val Acc: 0.8406
2026-04-05 05:59:50,691 - INFO - Epoch 96/100 - Train Loss: 0.2188 - Val Acc: 0.8406
2026-04-05 05:59:50,953 - INFO - Epoch 97/100 - Train Loss: 0.2165 - Val Acc: 0.8406
2026-04-05 05:59:51,221 - INFO - Epoch 98/100 - Train Loss: 0.2108 - Val Acc: 0.8261
2026-04-05 05:59:51,487 - INFO - Epoch 99/100 - Train Loss: 0.2144 - Val Acc: 0.8406
2026-04-05 05:59:51,769 - INFO - Epoch 100/100 - Train Loss: 0.2124 - Val Acc: 0.8261
2026-04-05 05:59:52,124 - INFO - Fold 9 logically complete. Tensor memory bounds cleared cleanly.
2026-04-05 05:59:52,128 - INFO - Original class distribution: [345 276]
2026-04-05 05:59:52,129 - INFO - Training device bound securely to: cuda

Fold 10:   0%|          | 0/100 [00:00<?, ?it/s]

2026-04-05 05:59:52,427 - INFO - Epoch 1/100 - Train Loss: 0.5673 - Val Acc: 0.8841
2026-04-05 05:59:52,690 - INFO - Epoch 2/100 - Train Loss: 0.4143 - Val Acc: 0.8986
2026-04-05 05:59:52,959 - INFO - Epoch 3/100 - Train Loss: 0.3721 - Val Acc: 0.8986
2026-04-05 05:59:53,224 - INFO - Epoch 4/100 - Train Loss: 0.3552 - Val Acc: 0.8986
2026-04-05 05:59:53,495 - INFO - Epoch 5/100 - Train Loss: 0.3433 - Val Acc: 0.8986
2026-04-05 05:59:53,767 - INFO - Epoch 6/100 - Train Loss: 0.3313 - Val Acc: 0.8986
2026-04-05 05:59:54,032 - INFO - Epoch 7/100 - Train Loss: 0.3283 - Val Acc: 0.9130
2026-04-05 05:59:54,320 - INFO - Epoch 8/100 - Train Loss: 0.3212 - Val Acc: 0.9420
2026-04-05 05:59:54,616 - INFO - Epoch 9/100 - Train Loss: 0.3219 - Val Acc: 0.9420
2026-04-05 05:59:54,880 - INFO - Epoch 10/100 - Train Loss: 0.3148 - Val Acc: 0.9420
2026-04-05 05:59:55,148 - INFO - Epoch 11/100 - Train Loss: 0.3135 - Val Acc: 0.9420
2026-04-05 05:59:55,411 - INFO - Epoch 12/100 - Train Loss: 0.3104 - Val Acc: 0.9420
2026-04-05 05:59:55,674 - INFO - Epoch 13/100 - Train Loss: 0.3087 - Val Acc: 0.9420
2026-04-05 05:59:55,942 - INFO - Epoch 14/100 - Train Loss: 0.3082 - Val Acc: 0.9420
2026-04-05 05:59:56,215 - INFO - Epoch 15/100 - Train Loss: 0.3057 - Val Acc: 0.9565
2026-04-05 05:59:56,498 - INFO - Epoch 16/100 - Train Loss: 0.3049 - Val Acc: 0.9565
2026-04-05 05:59:56,769 - INFO - Epoch 17/100 - Train Loss: 0.3015 - Val Acc: 0.9565
2026-04-05 05:59:57,037 - INFO - Epoch 18/100 - Train Loss: 0.3012 - Val Acc: 0.9565
2026-04-05 05:59:57,306 - INFO - Epoch 19/100 - Train Loss: 0.3005 - Val Acc: 0.9565
2026-04-05 05:59:57,585 - INFO - Epoch 20/100 - Train Loss: 0.2986 - Val Acc: 0.9565
2026-04-05 05:59:57,863 - INFO - Epoch 21/100 - Train Loss: 0.2962 - Val Acc: 0.9565
2026-04-05 05:59:58,147 - INFO - Epoch 22/100 - Train Loss: 0.2962 - Val Acc: 0.9565
2026-04-05 05:59:58,416 - INFO - Epoch 23/100 - Train Loss: 0.2948 - Val Acc: 0.9565
2026-04-05 05:59:58,680 - INFO - Epoch 24/100 - Train Loss: 0.2952 - Val Acc: 0.9565
2026-04-05 05:59:58,961 - INFO - Epoch 25/100 - Train Loss: 0.2926 - Val Acc: 0.9565
2026-04-05 05:59:59,222 - INFO - Epoch 26/100 - Train Loss: 0.2913 - Val Acc: 0.9565
2026-04-05 05:59:59,487 - INFO - Epoch 27/100 - Train Loss: 0.2906 - Val Acc: 0.9565
2026-04-05 05:59:59,750 - INFO - Epoch 28/100 - Train Loss: 0.2920 - Val Acc: 0.9565
2026-04-05 06:00:00,015 - INFO - Epoch 29/100 - Train Loss: 0.2873 - Val Acc: 0.9565
2026-04-05 06:00:00,291 - INFO - Epoch 30/100 - Train Loss: 0.2878 - Val Acc: 0.9565
2026-04-05 06:00:00,564 - INFO - Epoch 31/100 - Train Loss: 0.2860 - Val Acc: 0.9565
2026-04-05 06:00:00,835 - INFO - Epoch 32/100 - Train Loss: 0.2861 - Val Acc: 0.9565
2026-04-05 06:00:01,095 - INFO - Epoch 33/100 - Train Loss: 0.2838 - Val Acc: 0.9565
2026-04-05 06:00:01,360 - INFO - Epoch 34/100 - Train Loss: 0.2815 - Val Acc: 0.9565
2026-04-05 06:00:01,632 - INFO - Epoch 35/100 - Train Loss: 0.2827 - Val Acc: 0.9565
2026-04-05 06:00:01,907 - INFO - Epoch 36/100 - Train Loss: 0.2758 - Val Acc: 0.9565
2026-04-05 06:00:02,170 - INFO - Epoch 37/100 - Train Loss: 0.2796 - Val Acc: 0.9565
2026-04-05 06:00:02,458 - INFO - Epoch 38/100 - Train Loss: 0.2810 - Val Acc: 0.9565
2026-04-05 06:00:02,723 - INFO - Epoch 39/100 - Train Loss: 0.2776 - Val Acc: 0.9565
2026-04-05 06:00:03,004 - INFO - Epoch 40/100 - Train Loss: 0.2751 - Val Acc: 0.9565
2026-04-05 06:00:03,277 - INFO - Epoch 41/100 - Train Loss: 0.2790 - Val Acc: 0.9565
2026-04-05 06:00:03,544 - INFO - Epoch 42/100 - Train Loss: 0.2717 - Val Acc: 0.9565
2026-04-05 06:00:03,807 - INFO - Epoch 43/100 - Train Loss: 0.2714 - Val Acc: 0.9565
2026-04-05 06:00:04,072 - INFO - Epoch 44/100 - Train Loss: 0.2719 - Val Acc: 0.9565
2026-04-05 06:00:04,343 - INFO - Epoch 45/100 - Train Loss: 0.2710 - Val Acc: 0.9565
2026-04-05 06:00:04,637 - INFO - Epoch 46/100 - Train Loss: 0.2683 - Val Acc: 0.9565
2026-04-05 06:00:04,906 - INFO - Epoch 47/100 - Train Loss: 0.2692 - Val Acc: 0.9565
2026-04-05 06:00:05,179 - INFO - Epoch 48/100 - Train Loss: 0.2646 - Val Acc: 0.9565
2026-04-05 06:00:05,453 - INFO - Epoch 49/100 - Train Loss: 0.2652 - Val Acc: 0.9565
2026-04-05 06:00:05,714 - INFO - Epoch 50/100 - Train Loss: 0.2619 - Val Acc: 0.9565
2026-04-05 06:00:05,977 - INFO - Epoch 51/100 - Train Loss: 0.2618 - Val Acc: 0.9565
2026-04-05 06:00:06,235 - INFO - Epoch 52/100 - Train Loss: 0.2626 - Val Acc: 0.9565
2026-04-05 06:00:06,510 - INFO - Epoch 53/100 - Train Loss: 0.2623 - Val Acc: 0.9565
2026-04-05 06:00:06,773 - INFO - Epoch 54/100 - Train Loss: 0.2594 - Val Acc: 0.9565
2026-04-05 06:00:07,034 - INFO - Epoch 55/100 - Train Loss: 0.2585 - Val Acc: 0.9565
2026-04-05 06:00:07,305 - INFO - Epoch 56/100 - Train Loss: 0.2607 - Val Acc: 0.9565
2026-04-05 06:00:07,559 - INFO - Epoch 57/100 - Train Loss: 0.2563 - Val Acc: 0.9565
2026-04-05 06:00:07,821 - INFO - Epoch 58/100 - Train Loss: 0.2564 - Val Acc: 0.9565
2026-04-05 06:00:08,094 - INFO - Epoch 59/100 - Train Loss: 0.2534 - Val Acc: 0.9565
2026-04-05 06:00:08,380 - INFO - Epoch 60/100 - Train Loss: 0.2546 - Val Acc: 0.9565
2026-04-05 06:00:08,651 - INFO - Epoch 61/100 - Train Loss: 0.2576 - Val Acc: 0.9565
2026-04-05 06:00:08,917 - INFO - Epoch 62/100 - Train Loss: 0.2546 - Val Acc: 0.9565
2026-04-05 06:00:09,200 - INFO - Epoch 63/100 - Train Loss: 0.2521 - Val Acc: 0.9565
2026-04-05 06:00:09,478 - INFO - Epoch 64/100 - Train Loss: 0.2521 - Val Acc: 0.9565
2026-04-05 06:00:09,761 - INFO - Epoch 65/100 - Train Loss: 0.2510 - Val Acc: 0.9565
2026-04-05 06:00:10,032 - INFO - Epoch 66/100 - Train Loss: 0.2510 - Val Acc: 0.9565
2026-04-05 06:00:10,304 - INFO - Epoch 67/100 - Train Loss: 0.2534 - Val Acc: 0.9565
2026-04-05 06:00:10,579 - INFO - Epoch 68/100 - Train Loss: 0.2452 - Val Acc: 0.9565
2026-04-05 06:00:10,849 - INFO - Epoch 69/100 - Train Loss: 0.2490 - Val Acc: 0.9565
2026-04-05 06:00:11,119 - INFO - Epoch 70/100 - Train Loss: 0.2469 - Val Acc: 0.9565
2026-04-05 06:00:11,390 - INFO - Epoch 71/100 - Train Loss: 0.2475 - Val Acc: 0.9565
2026-04-05 06:00:11,669 - INFO - Epoch 72/100 - Train Loss: 0.2440 - Val Acc: 0.9710
2026-04-05 06:00:11,947 - INFO - Epoch 73/100 - Train Loss: 0.2453 - Val Acc: 0.9710
2026-04-05 06:00:12,218 - INFO - Epoch 74/100 - Train Loss: 0.2461 - Val Acc: 0.9565
2026-04-05 06:00:12,512 - INFO - Epoch 75/100 - Train Loss: 0.2433 - Val Acc: 0.9565
2026-04-05 06:00:12,788 - INFO - Epoch 76/100 - Train Loss: 0.2435 - Val Acc: 0.9565
2026-04-05 06:00:13,064 - INFO - Epoch 77/100 - Train Loss: 0.2438 - Val Acc: 0.9565
2026-04-05 06:00:13,337 - INFO - Epoch 78/100 - Train Loss: 0.2435 - Val Acc: 0.9565
2026-04-05 06:00:13,612 - INFO - Epoch 79/100 - Train Loss: 0.2441 - Val Acc: 0.9710
2026-04-05 06:00:13,881 - INFO - Epoch 80/100 - Train Loss: 0.2365 - Val Acc: 0.9710
2026-04-05 06:00:14,149 - INFO - Epoch 81/100 - Train Loss: 0.2383 - Val Acc: 0.9710
2026-04-05 06:00:14,420 - INFO - Epoch 82/100 - Train Loss: 0.2405 - Val Acc: 0.9565
2026-04-05 06:00:14,713 - INFO - Epoch 83/100 - Train Loss: 0.2353 - Val Acc: 0.9565
2026-04-05 06:00:14,984 - INFO - Epoch 84/100 - Train Loss: 0.2366 - Val Acc: 0.9565
2026-04-05 06:00:15,257 - INFO - Epoch 85/100 - Train Loss: 0.2368 - Val Acc: 0.9565
2026-04-05 06:00:15,532 - INFO - Epoch 86/100 - Train Loss: 0.2341 - Val Acc: 0.9565
2026-04-05 06:00:15,799 - INFO - Epoch 87/100 - Train Loss: 0.2343 - Val Acc: 0.9565
2026-04-05 06:00:16,057 - INFO - Epoch 88/100 - Train Loss: 0.2337 - Val Acc: 0.9565
2026-04-05 06:00:16,338 - INFO - Epoch 89/100 - Train Loss: 0.2322 - Val Acc: 0.9565
2026-04-05 06:00:16,604 - INFO - Epoch 90/100 - Train Loss: 0.2347 - Val Acc: 0.9565
2026-04-05 06:00:16,865 - INFO - Epoch 91/100 - Train Loss: 0.2313 - Val Acc: 0.9565
2026-04-05 06:00:17,129 - INFO - Epoch 92/100 - Train Loss: 0.2295 - Val Acc: 0.9565
2026-04-05 06:00:17,394 - INFO - Epoch 93/100 - Train Loss: 0.2297 - Val Acc: 0.9565
2026-04-05 06:00:17,658 - INFO - Epoch 94/100 - Train Loss: 0.2354 - Val Acc: 0.9565
2026-04-05 06:00:17,941 - INFO - Epoch 95/100 - Train Loss: 0.2297 - Val Acc: 0.9565
2026-04-05 06:00:18,211 - INFO - Epoch 96/100 - Train Loss: 0.2249 - Val Acc: 0.9565
2026-04-05 06:00:18,501 - INFO - Epoch 97/100 - Train Loss: 0.2251 - Val Acc: 0.9565
2026-04-05 06:00:18,777 - INFO - Epoch 98/100 - Train Loss: 0.2303 - Val Acc: 0.9565
2026-04-05 06:00:19,051 - INFO - Epoch 99/100 - Train Loss: 0.2205 - Val Acc: 0.9565
2026-04-05 06:00:19,324 - INFO - Epoch 100/100 - Train Loss: 0.2265 - Val Acc: 0.9565
2026-04-05 06:00:19,679 - INFO - Fold 10 logically complete. Tensor memory bounds cleared cleanly.
2026-04-05 06:00:19,697 - INFO - ✓ Completed LSTM_baseline -> Acc: 0.8942
2026-04-05 06:00:19,697 - INFO -
EXPERIMENT: LSTM_SMOTEENN | australian | SMOTE-ENN: True

Australian | LSTM | SMOTEENN:   0%|          | 0/10 [00:00<?, ?it/s]

2026-04-05 06:00:19,710 - INFO - Original class distribution: [344 277]
2026-04-05 06:00:19,711 - INFO - Training device bound securely to: cuda
2026-04-05 06:00:19,740 - INFO - After SMOTE-ENN deployment: [344 287]

Fold 1:   0%|          | 0/100 [00:00<?, ?it/s]

2026-04-05 06:00:20,033 - INFO - Epoch 1/100 - Train Loss: 0.5275 - Val Acc: 0.8406
2026-04-05 06:00:20,290 - INFO - Epoch 2/100 - Train Loss: 0.3298 - Val Acc: 0.8841
2026-04-05 06:00:20,556 - INFO - Epoch 3/100 - Train Loss: 0.2655 - Val Acc: 0.8841
2026-04-05 06:00:20,824 - INFO - Epoch 4/100 - Train Loss: 0.2421 - Val Acc: 0.8986
2026-04-05 06:00:21,100 - INFO - Epoch 5/100 - Train Loss: 0.2254 - Val Acc: 0.9130
2026-04-05 06:00:21,370 - INFO - Epoch 6/100 - Train Loss: 0.2132 - Val Acc: 0.8986
2026-04-05 06:00:21,632 - INFO - Epoch 7/100 - Train Loss: 0.2026 - Val Acc: 0.8986
2026-04-05 06:00:21,906 - INFO - Epoch 8/100 - Train Loss: 0.1960 - Val Acc: 0.8986
2026-04-05 06:00:22,179 - INFO - Epoch 9/100 - Train Loss: 0.1891 - Val Acc: 0.8986
2026-04-05 06:00:22,462 - INFO - Epoch 10/100 - Train Loss: 0.1839 - Val Acc: 0.8841
2026-04-05 06:00:22,735 - INFO - Epoch 11/100 - Train Loss: 0.1810 - Val Acc: 0.8986
2026-04-05 06:00:23,010 - INFO - Epoch 12/100 - Train Loss: 0.1793 - Val Acc: 0.8841
2026-04-05 06:00:23,285 - INFO - Epoch 13/100 - Train Loss: 0.1754 - Val Acc: 0.8841
2026-04-05 06:00:23,552 - INFO - Epoch 14/100 - Train Loss: 0.1711 - Val Acc: 0.8986
2026-04-05 06:00:23,828 - INFO - Epoch 15/100 - Train Loss: 0.1702 - Val Acc: 0.8986
2026-04-05 06:00:24,103 - INFO - Epoch 16/100 - Train Loss: 0.1678 - Val Acc: 0.8841
2026-04-05 06:00:24,377 - INFO - Epoch 17/100 - Train Loss: 0.1671 - Val Acc: 0.8841
2026-04-05 06:00:24,677 - INFO - Epoch 18/100 - Train Loss: 0.1663 - Val Acc: 0.8841
2026-04-05 06:00:24,936 - INFO - Epoch 19/100 - Train Loss: 0.1643 - Val Acc: 0.8986
2026-04-05 06:00:25,205 - INFO - Epoch 20/100 - Train Loss: 0.1610 - Val Acc: 0.8841
2026-04-05 06:00:25,466 - INFO - Epoch 21/100 - Train Loss: 0.1614 - Val Acc: 0.8841
2026-04-05 06:00:25,733 - INFO - Epoch 22/100 - Train Loss: 0.1590 - Val Acc: 0.8986
2026-04-05 06:00:26,002 - INFO - Epoch 23/100 - Train Loss: 0.1589 - Val Acc: 0.8841
2026-04-05 06:00:26,262 - INFO - Epoch 24/100 - Train Loss: 0.1569 - Val Acc: 0.8986
2026-04-05 06:00:26,536 - INFO - Epoch 25/100 - Train Loss: 0.1542 - Val Acc: 0.8986
2026-04-05 06:00:26,800 - INFO - Epoch 26/100 - Train Loss: 0.1550 - Val Acc: 0.8986
2026-04-05 06:00:27,076 - INFO - Epoch 27/100 - Train Loss: 0.1547 - Val Acc: 0.8986
2026-04-05 06:00:27,353 - INFO - Epoch 28/100 - Train Loss: 0.1533 - Val Acc: 0.8986
2026-04-05 06:00:27,627 - INFO - Epoch 29/100 - Train Loss: 0.1537 - Val Acc: 0.8841
2026-04-05 06:00:27,903 - INFO - Epoch 30/100 - Train Loss: 0.1523 - Val Acc: 0.8986
2026-04-05 06:00:28,169 - INFO - Epoch 31/100 - Train Loss: 0.1513 - Val Acc: 0.8986
2026-04-05 06:00:28,433 - INFO - Epoch 32/100 - Train Loss: 0.1471 - Val Acc: 0.8986
2026-04-05 06:00:28,695 - INFO - Epoch 33/100 - Train Loss: 0.1490 - Val Acc: 0.8986
2026-04-05 06:00:28,970 - INFO - Epoch 34/100 - Train Loss: 0.1469 - Val Acc: 0.8986
2026-04-05 06:00:29,235 - INFO - Epoch 35/100 - Train Loss: 0.1471 - Val Acc: 0.8986
2026-04-05 06:00:29,498 - INFO - Epoch 36/100 - Train Loss: 0.1452 - Val Acc: 0.8986
2026-04-05 06:00:29,770 - INFO - Epoch 37/100 - Train Loss: 0.1451 - Val Acc: 0.8986
2026-04-05 06:00:30,043 - INFO - Epoch 38/100 - Train Loss: 0.1446 - Val Acc: 0.8986
2026-04-05 06:00:30,339 - INFO - Epoch 39/100 - Train Loss: 0.1420 - Val Acc: 0.8986
2026-04-05 06:00:30,614 - INFO - Epoch 40/100 - Train Loss: 0.1409 - Val Acc: 0.9130
2026-04-05 06:00:30,882 - INFO - Epoch 41/100 - Train Loss: 0.1380 - Val Acc: 0.9130
2026-04-05 06:00:31,161 - INFO - Epoch 42/100 - Train Loss: 0.1436 - Val Acc: 0.9130
2026-04-05 06:00:31,436 - INFO - Epoch 43/100 - Train Loss: 0.1403 - Val Acc: 0.9130
2026-04-05 06:00:31,714 - INFO - Epoch 44/100 - Train Loss: 0.1410 - Val Acc: 0.9130
2026-04-05 06:00:31,990 - INFO - Epoch 45/100 - Train Loss: 0.1367 - Val Acc: 0.9130
2026-04-05 06:00:32,263 - INFO - Epoch 46/100 - Train Loss: 0.1362 - Val Acc: 0.9130
2026-04-05 06:00:32,529 - INFO - Epoch 47/100 - Train Loss: 0.1356 - Val Acc: 0.9130
2026-04-05 06:00:32,793 - INFO - Epoch 48/100 - Train Loss: 0.1333 - Val Acc: 0.9130
2026-04-05 06:00:33,057 - INFO - Epoch 49/100 - Train Loss: 0.1344 - Val Acc: 0.9130
2026-04-05 06:00:33,330 - INFO - Epoch 50/100 - Train Loss: 0.1357 - Val Acc: 0.9130
2026-04-05 06:00:33,592 - INFO - Epoch 51/100 - Train Loss: 0.1312 - Val Acc: 0.9130
2026-04-05 06:00:33,858 - INFO - Epoch 52/100 - Train Loss: 0.1322 - Val Acc: 0.9130
2026-04-05 06:00:34,129 - INFO - Epoch 53/100 - Train Loss: 0.1329 - Val Acc: 0.9130
2026-04-05 06:00:34,403 - INFO - Epoch 54/100 - Train Loss: 0.1299 - Val Acc: 0.9130
2026-04-05 06:00:34,701 - INFO - Epoch 55/100 - Train Loss: 0.1327 - Val Acc: 0.9130
2026-04-05 06:00:34,977 - INFO - Epoch 56/100 - Train Loss: 0.1311 - Val Acc: 0.9130
2026-04-05 06:00:35,260 - INFO - Epoch 57/100 - Train Loss: 0.1301 - Val Acc: 0.9130
2026-04-05 06:00:35,527 - INFO - Epoch 58/100 - Train Loss: 0.1304 - Val Acc: 0.9130
2026-04-05 06:00:35,793 - INFO - Epoch 59/100 - Train Loss: 0.1291 - Val Acc: 0.9130
2026-04-05 06:00:36,060 - INFO - Epoch 60/100 - Train Loss: 0.1293 - Val Acc: 0.9130
2026-04-05 06:00:36,333 - INFO - Epoch 61/100 - Train Loss: 0.1267 - Val Acc: 0.9130
2026-04-05 06:00:36,614 - INFO - Epoch 62/100 - Train Loss: 0.1250 - Val Acc: 0.9130
2026-04-05 06:00:36,888 - INFO - Epoch 63/100 - Train Loss: 0.1252 - Val Acc: 0.9130
2026-04-05 06:00:37,156 - INFO - Epoch 64/100 - Train Loss: 0.1270 - Val Acc: 0.9130
2026-04-05 06:00:37,420 - INFO - Epoch 65/100 - Train Loss: 0.1263 - Val Acc: 0.9130
2026-04-05 06:00:37,687 - INFO - Epoch 66/100 - Train Loss: 0.1226 - Val Acc: 0.9130
2026-04-05 06:00:37,954 - INFO - Epoch 67/100 - Train Loss: 0.1248 - Val Acc: 0.9130
2026-04-05 06:00:38,224 - INFO - Epoch 68/100 - Train Loss: 0.1232 - Val Acc: 0.9130
2026-04-05 06:00:38,490 - INFO - Epoch 69/100 - Train Loss: 0.1238 - Val Acc: 0.9130
2026-04-05 06:00:38,756 - INFO - Epoch 70/100 - Train Loss: 0.1231 - Val Acc: 0.9130
2026-04-05 06:00:39,029 - INFO - Epoch 71/100 - Train Loss: 0.1236 - Val Acc: 0.9130
2026-04-05 06:00:39,296 - INFO - Epoch 72/100 - Train Loss: 0.1230 - Val Acc: 0.9130
2026-04-05 06:00:39,571 - INFO - Epoch 73/100 - Train Loss: 0.1234 - Val Acc: 0.9130
2026-04-05 06:00:39,846 - INFO - Epoch 74/100 - Train Loss: 0.1216 - Val Acc: 0.9130
2026-04-05 06:00:40,110 - INFO - Epoch 75/100 - Train Loss: 0.1209 - Val Acc: 0.9130
2026-04-05 06:00:40,388 - INFO - Epoch 76/100 - Train Loss: 0.1186 - Val Acc: 0.9130
2026-04-05 06:00:40,671 - INFO - Epoch 77/100 - Train Loss: 0.1186 - Val Acc: 0.9130
2026-04-05 06:00:40,950 - INFO - Epoch 78/100 - Train Loss: 0.1198 - Val Acc: 0.9130
2026-04-05 06:00:41,221 - INFO - Epoch 79/100 - Train Loss: 0.1176 - Val Acc: 0.9130
2026-04-05 06:00:41,494 - INFO - Epoch 80/100 - Train Loss: 0.1188 - Val Acc: 0.9130
2026-04-05 06:00:41,772 - INFO - Epoch 81/100 - Train Loss: 0.1194 - Val Acc: 0.9130
2026-04-05 06:00:42,039 - INFO - Epoch 82/100 - Train Loss: 0.1180 - Val Acc: 0.9130
2026-04-05 06:00:42,309 - INFO - Epoch 83/100 - Train Loss: 0.1184 - Val Acc: 0.9130
2026-04-05 06:00:42,591 - INFO - Epoch 84/100 - Train Loss: 0.1178 - Val Acc: 0.9130
2026-04-05 06:00:42,853 - INFO - Epoch 85/100 - Train Loss: 0.1171 - Val Acc: 0.9130
2026-04-05 06:00:43,123 - INFO - Epoch 86/100 - Train Loss: 0.1122 - Val Acc: 0.9130
2026-04-05 06:00:43,391 - INFO - Epoch 87/100 - Train Loss: 0.1196 - Val Acc: 0.9130
2026-04-05 06:00:43,656 - INFO - Epoch 88/100 - Train Loss: 0.1140 - Val Acc: 0.9130
2026-04-05 06:00:43,928 - INFO - Epoch 89/100 - Train Loss: 0.1176 - Val Acc: 0.9130
2026-04-05 06:00:44,208 - INFO - Epoch 90/100 - Train Loss: 0.1109 - Val Acc: 0.9130
2026-04-05 06:00:44,490 - INFO - Epoch 91/100 - Train Loss: 0.1160 - Val Acc: 0.9130
2026-04-05 06:00:44,773 - INFO - Epoch 92/100 - Train Loss: 0.1145 - Val Acc: 0.9130
2026-04-05 06:00:45,064 - INFO - Epoch 93/100 - Train Loss: 0.1115 - Val Acc: 0.9130
2026-04-05 06:00:45,328 - INFO - Epoch 94/100 - Train Loss: 0.1116 - Val Acc: 0.9130
2026-04-05 06:00:45,601 - INFO - Epoch 95/100 - Train Loss: 0.1094 - Val Acc: 0.9130
2026-04-05 06:00:45,866 - INFO - Epoch 96/100 - Train Loss: 0.1107 - Val Acc: 0.9130
2026-04-05 06:00:46,145 - INFO - Epoch 97/100 - Train Loss: 0.1134 - Val Acc: 0.9130
2026-04-05 06:00:46,423 - INFO - Epoch 98/100 - Train Loss: 0.1098 - Val Acc: 0.9130
2026-04-05 06:00:46,688 - INFO - Epoch 99/100 - Train Loss: 0.1140 - Val Acc: 0.9130
2026-04-05 06:00:46,966 - INFO - Epoch 100/100 - Train Loss: 0.1106 - Val Acc: 0.9130
2026-04-05 06:00:47,334 - INFO - Fold 1 logically complete. Tensor memory bounds cleared cleanly.
2026-04-05 06:00:47,338 - INFO - Original class distribution: [344 277]
2026-04-05 06:00:47,339 - INFO - Training device bound securely to: cuda
2026-04-05 06:00:47,366 - INFO - After SMOTE-ENN deployment: [344 292]

Fold 2:   0%|          | 0/100 [00:00<?, ?it/s]

2026-04-05 06:00:47,649 - INFO - Epoch 1/100 - Train Loss: 0.5330 - Val Acc: 0.7536
2026-04-05 06:00:47,920 - INFO - Epoch 2/100 - Train Loss: 0.3327 - Val Acc: 0.7681
2026-04-05 06:00:48,182 - INFO - Epoch 3/100 - Train Loss: 0.2710 - Val Acc: 0.7826
2026-04-05 06:00:48,460 - INFO - Epoch 4/100 - Train Loss: 0.2465 - Val Acc: 0.7826
2026-04-05 06:00:48,742 - INFO - Epoch 5/100 - Train Loss: 0.2301 - Val Acc: 0.7971
2026-04-05 06:00:49,022 - INFO - Epoch 6/100 - Train Loss: 0.2221 - Val Acc: 0.7971
2026-04-05 06:00:49,275 - INFO - Epoch 7/100 - Train Loss: 0.2146 - Val Acc: 0.7971
2026-04-05 06:00:49,540 - INFO - Epoch 8/100 - Train Loss: 0.2088 - Val Acc: 0.7971
2026-04-05 06:00:49,799 - INFO - Epoch 9/100 - Train Loss: 0.2051 - Val Acc: 0.7971
2026-04-05 06:00:50,077 - INFO - Epoch 10/100 - Train Loss: 0.1999 - Val Acc: 0.8116
2026-04-05 06:00:50,351 - INFO - Epoch 11/100 - Train Loss: 0.1967 - Val Acc: 0.8116
2026-04-05 06:00:50,636 - INFO - Epoch 12/100 - Train Loss: 0.1935 - Val Acc: 0.8406
2026-04-05 06:00:50,900 - INFO - Epoch 13/100 - Train Loss: 0.1918 - Val Acc: 0.8696
2026-04-05 06:00:51,190 - INFO - Epoch 14/100 - Train Loss: 0.1906 - Val Acc: 0.8696
2026-04-05 06:00:51,459 - INFO - Epoch 15/100 - Train Loss: 0.1900 - Val Acc: 0.8551
2026-04-05 06:00:51,728 - INFO - Epoch 16/100 - Train Loss: 0.1878 - Val Acc: 0.8551
2026-04-05 06:00:52,004 - INFO - Epoch 17/100 - Train Loss: 0.1827 - Val Acc: 0.8696
2026-04-05 06:00:52,280 - INFO - Epoch 18/100 - Train Loss: 0.1822 - Val Acc: 0.8841
2026-04-05 06:00:52,554 - INFO - Epoch 19/100 - Train Loss: 0.1831 - Val Acc: 0.8841
2026-04-05 06:00:52,836 - INFO - Epoch 20/100 - Train Loss: 0.1819 - Val Acc: 0.8841
2026-04-05 06:00:53,116 - INFO - Epoch 21/100 - Train Loss: 0.1779 - Val Acc: 0.8986
2026-04-05 06:00:53,383 - INFO - Epoch 22/100 - Train Loss: 0.1773 - Val Acc: 0.8986
2026-04-05 06:00:53,651 - INFO - Epoch 23/100 - Train Loss: 0.1762 - Val Acc: 0.8986
2026-04-05 06:00:53,915 - INFO - Epoch 24/100 - Train Loss: 0.1733 - Val Acc: 0.9130
2026-04-05 06:00:54,194 - INFO - Epoch 25/100 - Train Loss: 0.1717 - Val Acc: 0.9130
2026-04-05 06:00:54,472 - INFO - Epoch 26/100 - Train Loss: 0.1700 - Val Acc: 0.8986
2026-04-05 06:00:54,748 - INFO - Epoch 27/100 - Train Loss: 0.1694 - Val Acc: 0.8841
2026-04-05 06:00:55,011 - INFO - Epoch 28/100 - Train Loss: 0.1699 - Val Acc: 0.8841
2026-04-05 06:00:55,287 - INFO - Epoch 29/100 - Train Loss: 0.1624 - Val Acc: 0.8841
2026-04-05 06:00:55,549 - INFO - Epoch 30/100 - Train Loss: 0.1643 - Val Acc: 0.8986
2026-04-05 06:00:55,820 - INFO - Epoch 31/100 - Train Loss: 0.1664 - Val Acc: 0.8841
2026-04-05 06:00:56,085 - INFO - Epoch 32/100 - Train Loss: 0.1640 - Val Acc: 0.8986
2026-04-05 06:00:56,337 - INFO - Epoch 33/100 - Train Loss: 0.1623 - Val Acc: 0.8986
2026-04-05 06:00:56,602 - INFO - Epoch 34/100 - Train Loss: 0.1612 - Val Acc: 0.8986
2026-04-05 06:00:56,874 - INFO - Epoch 35/100 - Train Loss: 0.1590 - Val Acc: 0.8986
2026-04-05 06:00:57,156 - INFO - Epoch 36/100 - Train Loss: 0.1557 - Val Acc: 0.8986
2026-04-05 06:00:57,434 - INFO - Epoch 37/100 - Train Loss: 0.1567 - Val Acc: 0.8986
2026-04-05 06:00:57,699 - INFO - Epoch 38/100 - Train Loss: 0.1551 - Val Acc: 0.8841
2026-04-05 06:00:57,969 - INFO - Epoch 39/100 - Train Loss: 0.1542 - Val Acc: 0.8841
2026-04-05 06:00:58,238 - INFO - Epoch 40/100 - Train Loss: 0.1521 - Val Acc: 0.8841
2026-04-05 06:00:58,505 - INFO - Epoch 41/100 - Train Loss: 0.1534 - Val Acc: 0.8986
2026-04-05 06:00:58,769 - INFO - Epoch 42/100 - Train Loss: 0.1485 - Val Acc: 0.8986
2026-04-05 06:00:59,025 - INFO - Epoch 43/100 - Train Loss: 0.1494 - Val Acc: 0.8841
2026-04-05 06:00:59,282 - INFO - Epoch 44/100 - Train Loss: 0.1484 - Val Acc: 0.8841
2026-04-05 06:00:59,543 - INFO - Epoch 45/100 - Train Loss: 0.1465 - Val Acc: 0.8841
2026-04-05 06:00:59,810 - INFO - Epoch 46/100 - Train Loss: 0.1464 - Val Acc: 0.8841
2026-04-05 06:01:00,072 - INFO - Epoch 47/100 - Train Loss: 0.1430 - Val Acc: 0.8841
2026-04-05 06:01:00,327 - INFO - Epoch 48/100 - Train Loss: 0.1447 - Val Acc: 0.8841
2026-04-05 06:01:00,591 - INFO - Epoch 49/100 - Train Loss: 0.1453 - Val Acc: 0.8841
2026-04-05 06:01:00,851 - INFO - Epoch 50/100 - Train Loss: 0.1421 - Val Acc: 0.8986
2026-04-05 06:01:01,128 - INFO - Epoch 51/100 - Train Loss: 0.1445 - Val Acc: 0.8841
2026-04-05 06:01:01,395 - INFO - Epoch 52/100 - Train Loss: 0.1426 - Val Acc: 0.8986
2026-04-05 06:01:01,660 - INFO - Epoch 53/100 - Train Loss: 0.1411 - Val Acc: 0.8841
2026-04-05 06:01:01,933 - INFO - Epoch 54/100 - Train Loss: 0.1398 - Val Acc: 0.8841
2026-04-05 06:01:02,207 - INFO - Epoch 55/100 - Train Loss: 0.1373 - Val Acc: 0.8841
2026-04-05 06:01:02,488 - INFO - Epoch 56/100 - Train Loss: 0.1360 - Val Acc: 0.8841
2026-04-05 06:01:02,763 - INFO - Epoch 57/100 - Train Loss: 0.1384 - Val Acc: 0.8841
2026-04-05 06:01:03,040 - INFO - Epoch 58/100 - Train Loss: 0.1353 - Val Acc: 0.8841
2026-04-05 06:01:03,312 - INFO - Epoch 59/100 - Train Loss: 0.1363 - Val Acc: 0.8841
2026-04-05 06:01:03,591 - INFO - Epoch 60/100 - Train Loss: 0.1339 - Val Acc: 0.8841
2026-04-05 06:01:03,871 - INFO - Epoch 61/100 - Train Loss: 0.1297 - Val Acc: 0.8841
2026-04-05 06:01:04,150 - INFO - Epoch 62/100 - Train Loss: 0.1332 - Val Acc: 0.8841
2026-04-05 06:01:04,429 - INFO - Epoch 63/100 - Train Loss: 0.1313 - Val Acc: 0.8841
2026-04-05 06:01:04,742 - INFO - Epoch 64/100 - Train Loss: 0.1351 - Val Acc: 0.8841
2026-04-05 06:01:05,010 - INFO - Epoch 65/100 - Train Loss: 0.1299 - Val Acc: 0.8841
2026-04-05 06:01:05,293 - INFO - Epoch 66/100 - Train Loss: 0.1307 - Val Acc: 0.8841
2026-04-05 06:01:05,574 - INFO - Epoch 67/100 - Train Loss: 0.1318 - Val Acc: 0.8841
2026-04-05 06:01:05,843 - INFO - Epoch 68/100 - Train Loss: 0.1283 - Val Acc: 0.8841
2026-04-05 06:01:06,108 - INFO - Epoch 69/100 - Train Loss: 0.1304 - Val Acc: 0.8841
2026-04-05 06:01:06,384 - INFO - Epoch 70/100 - Train Loss: 0.1300 - Val Acc: 0.8841
2026-04-05 06:01:06,664 - INFO - Epoch 71/100 - Train Loss: 0.1288 - Val Acc: 0.8841
2026-04-05 06:01:06,926 - INFO - Epoch 72/100 - Train Loss: 0.1262 - Val Acc: 0.8841
2026-04-05 06:01:07,207 - INFO - Epoch 73/100 - Train Loss: 0.1260 - Val Acc: 0.8841
2026-04-05 06:01:07,483 - INFO - Epoch 74/100 - Train Loss: 0.1202 - Val Acc: 0.8841
2026-04-05 06:01:07,758 - INFO - Epoch 75/100 - Train Loss: 0.1274 - Val Acc: 0.8841
2026-04-05 06:01:08,035 - INFO - Epoch 76/100 - Train Loss: 0.1274 - Val Acc: 0.8841
2026-04-05 06:01:08,310 - INFO - Epoch 77/100 - Train Loss: 0.1222 - Val Acc: 0.8841
2026-04-05 06:01:08,581 - INFO - Epoch 78/100 - Train Loss: 0.1249 - Val Acc: 0.8841
2026-04-05 06:01:08,853 - INFO - Epoch 79/100 - Train Loss: 0.1211 - Val Acc: 0.8841
2026-04-05 06:01:09,126 - INFO - Epoch 80/100 - Train Loss: 0.1256 - Val Acc: 0.8841
2026-04-05 06:01:09,396 - INFO - Epoch 81/100 - Train Loss: 0.1231 - Val Acc: 0.8986
2026-04-05 06:01:09,673 - INFO - Epoch 82/100 - Train Loss: 0.1192 - Val Acc: 0.8986
2026-04-05 06:01:09,946 - INFO - Epoch 83/100 - Train Loss: 0.1206 - Val Acc: 0.8841
2026-04-05 06:01:10,217 - INFO - Epoch 84/100 - Train Loss: 0.1207 - Val Acc: 0.8986
2026-04-05 06:01:10,486 - INFO - Epoch 85/100 - Train Loss: 0.1197 - Val Acc: 0.8986
2026-04-05 06:01:10,766 - INFO - Epoch 86/100 - Train Loss: 0.1210 - Val Acc: 0.8841
2026-04-05 06:01:11,020 - INFO - Epoch 87/100 - Train Loss: 0.1186 - Val Acc: 0.8841
2026-04-05 06:01:11,284 - INFO - Epoch 88/100 - Train Loss: 0.1169 - Val Acc: 0.8841
2026-04-05 06:01:11,552 - INFO - Epoch 89/100 - Train Loss: 0.1152 - Val Acc: 0.8841
2026-04-05 06:01:11,827 - INFO - Epoch 90/100 - Train Loss: 0.1181 - Val Acc: 0.8841
2026-04-05 06:01:12,089 - INFO - Epoch 91/100 - Train Loss: 0.1217 - Val Acc: 0.8986
2026-04-05 06:01:12,357 - INFO - Epoch 92/100 - Train Loss: 0.1169 - Val Acc: 0.8841
2026-04-05 06:01:12,633 - INFO - Epoch 93/100 - Train Loss: 0.1154 - Val Acc: 0.8841
2026-04-05 06:01:12,911 - INFO - Epoch 94/100 - Train Loss: 0.1160 - Val Acc: 0.8841
2026-04-05 06:01:13,186 - INFO - Epoch 95/100 - Train Loss: 0.1138 - Val Acc: 0.8551
2026-04-05 06:01:13,466 - INFO - Epoch 96/100 - Train Loss: 0.1117 - Val Acc: 0.8696
2026-04-05 06:01:13,734 - INFO - Epoch 97/100 - Train Loss: 0.1117 - Val Acc: 0.8841
2026-04-05 06:01:14,004 - INFO - Epoch 98/100 - Train Loss: 0.1126 - Val Acc: 0.8841
2026-04-05 06:01:14,273 - INFO - Epoch 99/100 - Train Loss: 0.1139 - Val Acc: 0.8696
2026-04-05 06:01:14,567 - INFO - Epoch 100/100 - Train Loss: 0.1141 - Val Acc: 0.8696
2026-04-05 06:01:14,950 - INFO - Fold 2 logically complete. Tensor memory bounds cleared cleanly.
2026-04-05 06:01:14,954 - INFO - Original class distribution: [344 277]
2026-04-05 06:01:14,955 - INFO - Training device bound securely to: cuda
2026-04-05 06:01:14,983 - INFO - After SMOTE-ENN deployment: [344 290]

Fold 3:   0%|          | 0/100 [00:00<?, ?it/s]

2026-04-05 06:01:15,267 - INFO - Epoch 1/100 - Train Loss: 0.5186 - Val Acc: 0.9275
2026-04-05 06:01:15,545 - INFO - Epoch 2/100 - Train Loss: 0.3294 - Val Acc: 0.9275
2026-04-05 06:01:15,810 - INFO - Epoch 3/100 - Train Loss: 0.2726 - Val Acc: 0.9275
2026-04-05 06:01:16,077 - INFO - Epoch 4/100 - Train Loss: 0.2424 - Val Acc: 0.9275
2026-04-05 06:01:16,336 - INFO - Epoch 5/100 - Train Loss: 0.2269 - Val Acc: 0.9420
2026-04-05 06:01:16,616 - INFO - Epoch 6/100 - Train Loss: 0.2149 - Val Acc: 0.9275
2026-04-05 06:01:16,889 - INFO - Epoch 7/100 - Train Loss: 0.2030 - Val Acc: 0.9275
2026-04-05 06:01:17,159 - INFO - Epoch 8/100 - Train Loss: 0.1954 - Val Acc: 0.9275
2026-04-05 06:01:17,437 - INFO - Epoch 9/100 - Train Loss: 0.1884 - Val Acc: 0.9275
2026-04-05 06:01:17,710 - INFO - Epoch 10/100 - Train Loss: 0.1859 - Val Acc: 0.9275
2026-04-05 06:01:17,977 - INFO - Epoch 11/100 - Train Loss: 0.1787 - Val Acc: 0.9275
2026-04-05 06:01:18,246 - INFO - Epoch 12/100 - Train Loss: 0.1767 - Val Acc: 0.9275
2026-04-05 06:01:18,533 - INFO - Epoch 13/100 - Train Loss: 0.1753 - Val Acc: 0.9275
2026-04-05 06:01:18,807 - INFO - Epoch 14/100 - Train Loss: 0.1711 - Val Acc: 0.9275
2026-04-05 06:01:19,077 - INFO - Epoch 15/100 - Train Loss: 0.1658 - Val Acc: 0.9130
2026-04-05 06:01:19,341 - INFO - Epoch 16/100 - Train Loss: 0.1671 - Val Acc: 0.9130
2026-04-05 06:01:19,603 - INFO - Epoch 17/100 - Train Loss: 0.1666 - Val Acc: 0.9130
2026-04-05 06:01:19,873 - INFO - Epoch 18/100 - Train Loss: 0.1642 - Val Acc: 0.9130
2026-04-05 06:01:20,145 - INFO - Epoch 19/100 - Train Loss: 0.1627 - Val Acc: 0.9130
2026-04-05 06:01:20,414 - INFO - Epoch 20/100 - Train Loss: 0.1615 - Val Acc: 0.9130
2026-04-05 06:01:20,694 - INFO - Epoch 21/100 - Train Loss: 0.1572 - Val Acc: 0.9130
2026-04-05 06:01:20,981 - INFO - Epoch 22/100 - Train Loss: 0.1566 - Val Acc: 0.9130
2026-04-05 06:01:21,263 - INFO - Epoch 23/100 - Train Loss: 0.1577 - Val Acc: 0.9130
2026-04-05 06:01:21,551 - INFO - Epoch 24/100 - Train Loss: 0.1547 - Val Acc: 0.9130
2026-04-05 06:01:21,817 - INFO - Epoch 25/100 - Train Loss: 0.1543 - Val Acc: 0.9130
2026-04-05 06:01:22,079 - INFO - Epoch 26/100 - Train Loss: 0.1499 - Val Acc: 0.9130
2026-04-05 06:01:22,347 - INFO - Epoch 27/100 - Train Loss: 0.1516 - Val Acc: 0.9130
2026-04-05 06:01:22,625 - INFO - Epoch 28/100 - Train Loss: 0.1515 - Val Acc: 0.9130
2026-04-05 06:01:22,899 - INFO - Epoch 29/100 - Train Loss: 0.1471 - Val Acc: 0.9130
2026-04-05 06:01:23,173 - INFO - Epoch 30/100 - Train Loss: 0.1465 - Val Acc: 0.9130
2026-04-05 06:01:23,446 - INFO - Epoch 31/100 - Train Loss: 0.1439 - Val Acc: 0.9130
2026-04-05 06:01:23,723 - INFO - Epoch 32/100 - Train Loss: 0.1448 - Val Acc: 0.9130
2026-04-05 06:01:23,988 - INFO - Epoch 33/100 - Train Loss: 0.1419 - Val Acc: 0.9130
2026-04-05 06:01:24,269 - INFO - Epoch 34/100 - Train Loss: 0.1459 - Val Acc: 0.9130
2026-04-05 06:01:24,575 - INFO - Epoch 35/100 - Train Loss: 0.1418 - Val Acc: 0.9130
2026-04-05 06:01:24,866 - INFO - Epoch 36/100 - Train Loss: 0.1389 - Val Acc: 0.9130
2026-04-05 06:01:25,142 - INFO - Epoch 37/100 - Train Loss: 0.1385 - Val Acc: 0.9130
2026-04-05 06:01:25,408 - INFO - Epoch 38/100 - Train Loss: 0.1385 - Val Acc: 0.9130
2026-04-05 06:01:25,683 - INFO - Epoch 39/100 - Train Loss: 0.1366 - Val Acc: 0.9130
2026-04-05 06:01:25,954 - INFO - Epoch 40/100 - Train Loss: 0.1344 - Val Acc: 0.9130
2026-04-05 06:01:26,232 - INFO - Epoch 41/100 - Train Loss: 0.1340 - Val Acc: 0.9130
2026-04-05 06:01:26,505 - INFO - Epoch 42/100 - Train Loss: 0.1335 - Val Acc: 0.9130
2026-04-05 06:01:26,782 - INFO - Epoch 43/100 - Train Loss: 0.1317 - Val Acc: 0.9130
2026-04-05 06:01:27,060 - INFO - Epoch 44/100 - Train Loss: 0.1317 - Val Acc: 0.9130
2026-04-05 06:01:27,329 - INFO - Epoch 45/100 - Train Loss: 0.1275 - Val Acc: 0.9130
2026-04-05 06:01:27,606 - INFO - Epoch 46/100 - Train Loss: 0.1263 - Val Acc: 0.9130
2026-04-05 06:01:27,879 - INFO - Epoch 47/100 - Train Loss: 0.1268 - Val Acc: 0.9130
2026-04-05 06:01:28,144 - INFO - Epoch 48/100 - Train Loss: 0.1263 - Val Acc: 0.9130
2026-04-05 06:01:28,414 - INFO - Epoch 49/100 - Train Loss: 0.1281 - Val Acc: 0.9130
2026-04-05 06:01:28,704 - INFO - Epoch 50/100 - Train Loss: 0.1234 - Val Acc: 0.9130
2026-04-05 06:01:28,979 - INFO - Epoch 51/100 - Train Loss: 0.1227 - Val Acc: 0.9130
2026-04-05 06:01:29,242 - INFO - Epoch 52/100 - Train Loss: 0.1221 - Val Acc: 0.9130
2026-04-05 06:01:29,515 - INFO - Epoch 53/100 - Train Loss: 0.1221 - Val Acc: 0.9130
2026-04-05 06:01:29,793 - INFO - Epoch 54/100 - Train Loss: 0.1190 - Val Acc: 0.9130
2026-04-05 06:01:30,064 - INFO - Epoch 55/100 - Train Loss: 0.1172 - Val Acc: 0.9130
2026-04-05 06:01:30,329 - INFO - Epoch 56/100 - Train Loss: 0.1184 - Val Acc: 0.9275
2026-04-05 06:01:30,594 - INFO - Epoch 57/100 - Train Loss: 0.1166 - Val Acc: 0.9130
2026-04-05 06:01:30,870 - INFO - Epoch 58/100 - Train Loss: 0.1163 - Val Acc: 0.9275
2026-04-05 06:01:31,152 - INFO - Epoch 59/100 - Train Loss: 0.1164 - Val Acc: 0.9275
2026-04-05 06:01:31,422 - INFO - Epoch 60/100 - Train Loss: 0.1170 - Val Acc: 0.9275
2026-04-05 06:01:31,703 - INFO - Epoch 61/100 - Train Loss: 0.1138 - Val Acc: 0.9275
2026-04-05 06:01:31,973 - INFO - Epoch 62/100 - Train Loss: 0.1116 - Val Acc: 0.9275
2026-04-05 06:01:32,234 - INFO - Epoch 63/100 - Train Loss: 0.1140 - Val Acc: 0.9275
2026-04-05 06:01:32,506 - INFO - Epoch 64/100 - Train Loss: 0.1166 - Val Acc: 0.9275
2026-04-05 06:01:32,769 - INFO - Epoch 65/100 - Train Loss: 0.1124 - Val Acc: 0.9275
2026-04-05 06:01:33,036 - INFO - Epoch 66/100 - Train Loss: 0.1102 - Val Acc: 0.9275
2026-04-05 06:01:33,294 - INFO - Epoch 67/100 - Train Loss: 0.1110 - Val Acc: 0.9275
2026-04-05 06:01:33,569 - INFO - Epoch 68/100 - Train Loss: 0.1098 - Val Acc: 0.9275
2026-04-05 06:01:33,836 - INFO - Epoch 69/100 - Train Loss: 0.1113 - Val Acc: 0.9275
2026-04-05 06:01:34,119 - INFO - Epoch 70/100 - Train Loss: 0.1081 - Val Acc: 0.9275
2026-04-05 06:01:34,398 - INFO - Epoch 71/100 - Train Loss: 0.1124 - Val Acc: 0.9275
2026-04-05 06:01:34,700 - INFO - Epoch 72/100 - Train Loss: 0.1065 - Val Acc: 0.9275
2026-04-05 06:01:34,992 - INFO - Epoch 73/100 - Train Loss: 0.1077 - Val Acc: 0.9275
2026-04-05 06:01:35,264 - INFO - Epoch 74/100 - Train Loss: 0.1069 - Val Acc: 0.9275
2026-04-05 06:01:35,541 - INFO - Epoch 75/100 - Train Loss: 0.1024 - Val Acc: 0.9275
2026-04-05 06:01:35,831 - INFO - Epoch 76/100 - Train Loss: 0.1058 - Val Acc: 0.9275
2026-04-05 06:01:36,108 - INFO - Epoch 77/100 - Train Loss: 0.1021 - Val Acc: 0.9275
2026-04-05 06:01:36,393 - INFO - Epoch 78/100 - Train Loss: 0.1033 - Val Acc: 0.9275
2026-04-05 06:01:36,689 - INFO - Epoch 79/100 - Train Loss: 0.1033 - Val Acc: 0.9275
2026-04-05 06:01:36,967 - INFO - Epoch 80/100 - Train Loss: 0.1000 - Val Acc: 0.9275
2026-04-05 06:01:37,240 - INFO - Epoch 81/100 - Train Loss: 0.1044 - Val Acc: 0.9275
2026-04-05 06:01:37,501 - INFO - Epoch 82/100 - Train Loss: 0.1020 - Val Acc: 0.9275
2026-04-05 06:01:37,770 - INFO - Epoch 83/100 - Train Loss: 0.1006 - Val Acc: 0.9275
2026-04-05 06:01:38,038 - INFO - Epoch 84/100 - Train Loss: 0.1001 - Val Acc: 0.9420
2026-04-05 06:01:38,311 - INFO - Epoch 85/100 - Train Loss: 0.0996 - Val Acc: 0.9420
2026-04-05 06:01:38,577 - INFO - Epoch 86/100 - Train Loss: 0.0991 - Val Acc: 0.9275
2026-04-05 06:01:38,849 - INFO - Epoch 87/100 - Train Loss: 0.0993 - Val Acc: 0.9275
2026-04-05 06:01:39,110 - INFO - Epoch 88/100 - Train Loss: 0.0965 - Val Acc: 0.9275
2026-04-05 06:01:39,385 - INFO - Epoch 89/100 - Train Loss: 0.0929 - Val Acc: 0.9275
2026-04-05 06:01:39,659 - INFO - Epoch 90/100 - Train Loss: 0.0975 - Val Acc: 0.9275
2026-04-05 06:01:39,926 - INFO - Epoch 91/100 - Train Loss: 0.0958 - Val Acc: 0.9275
2026-04-05 06:01:40,207 - INFO - Epoch 92/100 - Train Loss: 0.0960 - Val Acc: 0.9275
2026-04-05 06:01:40,476 - INFO - Epoch 93/100 - Train Loss: 0.0979 - Val Acc: 0.9420
2026-04-05 06:01:40,762 - INFO - Epoch 94/100 - Train Loss: 0.0961 - Val Acc: 0.9275
2026-04-05 06:01:41,026 - INFO - Epoch 95/100 - Train Loss: 0.0958 - Val Acc: 0.9420
2026-04-05 06:01:41,291 - INFO - Epoch 96/100 - Train Loss: 0.0956 - Val Acc: 0.9420
2026-04-05 06:01:41,563 - INFO - Epoch 97/100 - Train Loss: 0.0947 - Val Acc: 0.9420
2026-04-05 06:01:41,832 - INFO - Epoch 98/100 - Train Loss: 0.0943 - Val Acc: 0.9420
2026-04-05 06:01:42,103 - INFO - Epoch 99/100 - Train Loss: 0.0923 - Val Acc: 0.9275
2026-04-05 06:01:42,375 - INFO - Epoch 100/100 - Train Loss: 0.0904 - Val Acc: 0.9275
2026-04-05 06:01:42,732 - INFO - Fold 3 logically complete. Tensor memory bounds cleared cleanly.
2026-04-05 06:01:42,737 - INFO - Original class distribution: [345 276]
2026-04-05 06:01:42,737 - INFO - Training device bound securely to: cuda
2026-04-05 06:01:42,764 - INFO - After SMOTE-ENN deployment: [345 299]

Fold 4:   0%|          | 0/100 [00:00<?, ?it/s]

2026-04-05 06:01:43,064 - INFO - Epoch 1/100 - Train Loss: 0.5238 - Val Acc: 0.7681
2026-04-05 06:01:43,345 - INFO - Epoch 2/100 - Train Loss: 0.3236 - Val Acc: 0.7681
2026-04-05 06:01:43,634 - INFO - Epoch 3/100 - Train Loss: 0.2701 - Val Acc: 0.7826
2026-04-05 06:01:43,920 - INFO - Epoch 4/100 - Train Loss: 0.2431 - Val Acc: 0.7971
2026-04-05 06:01:44,212 - INFO - Epoch 5/100 - Train Loss: 0.2262 - Val Acc: 0.7971
2026-04-05 06:01:44,513 - INFO - Epoch 6/100 - Train Loss: 0.2157 - Val Acc: 0.7971
2026-04-05 06:01:44,818 - INFO - Epoch 7/100 - Train Loss: 0.2069 - Val Acc: 0.7971
2026-04-05 06:01:45,100 - INFO - Epoch 8/100 - Train Loss: 0.1991 - Val Acc: 0.7971
2026-04-05 06:01:45,380 - INFO - Epoch 9/100 - Train Loss: 0.1945 - Val Acc: 0.7971
2026-04-05 06:01:45,658 - INFO - Epoch 10/100 - Train Loss: 0.1914 - Val Acc: 0.7971
2026-04-05 06:01:45,955 - INFO - Epoch 11/100 - Train Loss: 0.1900 - Val Acc: 0.7971
2026-04-05 06:01:46,232 - INFO - Epoch 12/100 - Train Loss: 0.1850 - Val Acc: 0.7826
2026-04-05 06:01:46,513 - INFO - Epoch 13/100 - Train Loss: 0.1851 - Val Acc: 0.7826
2026-04-05 06:01:46,794 - INFO - Epoch 14/100 - Train Loss: 0.1819 - Val Acc: 0.7826
2026-04-05 06:01:47,066 - INFO - Epoch 15/100 - Train Loss: 0.1818 - Val Acc: 0.7826
2026-04-05 06:01:47,338 - INFO - Epoch 16/100 - Train Loss: 0.1767 - Val Acc: 0.7826
2026-04-05 06:01:47,628 - INFO - Epoch 17/100 - Train Loss: 0.1786 - Val Acc: 0.7826
2026-04-05 06:01:47,909 - INFO - Epoch 18/100 - Train Loss: 0.1782 - Val Acc: 0.7826
2026-04-05 06:01:48,186 - INFO - Epoch 19/100 - Train Loss: 0.1740 - Val Acc: 0.7826
2026-04-05 06:01:48,473 - INFO - Epoch 20/100 - Train Loss: 0.1746 - Val Acc: 0.7971
2026-04-05 06:01:48,771 - INFO - Epoch 21/100 - Train Loss: 0.1748 - Val Acc: 0.7826
2026-04-05 06:01:49,047 - INFO - Epoch 22/100 - Train Loss: 0.1708 - Val Acc: 0.7971
2026-04-05 06:01:49,322 - INFO - Epoch 23/100 - Train Loss: 0.1711 - Val Acc: 0.7971
2026-04-05 06:01:49,601 - INFO - Epoch 24/100 - Train Loss: 0.1698 - Val Acc: 0.7826
2026-04-05 06:01:49,873 - INFO - Epoch 25/100 - Train Loss: 0.1700 - Val Acc: 0.7971
2026-04-05 06:01:50,153 - INFO - Epoch 26/100 - Train Loss: 0.1691 - Val Acc: 0.7826
2026-04-05 06:01:50,435 - INFO - Epoch 27/100 - Train Loss: 0.1670 - Val Acc: 0.7826
2026-04-05 06:01:50,714 - INFO - Epoch 28/100 - Train Loss: 0.1649 - Val Acc: 0.7826
2026-04-05 06:01:50,995 - INFO - Epoch 29/100 - Train Loss: 0.1638 - Val Acc: 0.7826
2026-04-05 06:01:51,276 - INFO - Epoch 30/100 - Train Loss: 0.1624 - Val Acc: 0.7826
2026-04-05 06:01:51,555 - INFO - Epoch 31/100 - Train Loss: 0.1644 - Val Acc: 0.7826
2026-04-05 06:01:51,843 - INFO - Epoch 32/100 - Train Loss: 0.1629 - Val Acc: 0.7826
2026-04-05 06:01:52,119 - INFO - Epoch 33/100 - Train Loss: 0.1622 - Val Acc: 0.7826
2026-04-05 06:01:52,407 - INFO - Epoch 34/100 - Train Loss: 0.1611 - Val Acc: 0.7826
2026-04-05 06:01:52,694 - INFO - Epoch 35/100 - Train Loss: 0.1605 - Val Acc: 0.7826
2026-04-05 06:01:52,964 - INFO - Epoch 36/100 - Train Loss: 0.1597 - Val Acc: 0.7826
2026-04-05 06:01:53,254 - INFO - Epoch 37/100 - Train Loss: 0.1605 - Val Acc: 0.7826
2026-04-05 06:01:53,531 - INFO - Epoch 38/100 - Train Loss: 0.1571 - Val Acc: 0.7826
2026-04-05 06:01:53,812 - INFO - Epoch 39/100 - Train Loss: 0.1563 - Val Acc: 0.7826
2026-04-05 06:01:54,092 - INFO - Epoch 40/100 - Train Loss: 0.1562 - Val Acc: 0.7826
2026-04-05 06:01:54,393 - INFO - Epoch 41/100 - Train Loss: 0.1574 - Val Acc: 0.7826
2026-04-05 06:01:54,703 - INFO - Epoch 42/100 - Train Loss: 0.1543 - Val Acc: 0.7826
2026-04-05 06:01:54,985 - INFO - Epoch 43/100 - Train Loss: 0.1557 - Val Acc: 0.7826
2026-04-05 06:01:55,265 - INFO - Epoch 44/100 - Train Loss: 0.1522 - Val Acc: 0.7826
2026-04-05 06:01:55,546 - INFO - Epoch 45/100 - Train Loss: 0.1546 - Val Acc: 0.7971
2026-04-05 06:01:55,818 - INFO - Epoch 46/100 - Train Loss: 0.1520 - Val Acc: 0.7971
2026-04-05 06:01:56,102 - INFO - Epoch 47/100 - Train Loss: 0.1488 - Val Acc: 0.7971
2026-04-05 06:01:56,381 - INFO - Epoch 48/100 - Train Loss: 0.1505 - Val Acc: 0.7826
2026-04-05 06:01:56,667 - INFO - Epoch 49/100 - Train Loss: 0.1490 - Val Acc: 0.7826
2026-04-05 06:01:56,946 - INFO - Epoch 50/100 - Train Loss: 0.1495 - Val Acc: 0.7826
2026-04-05 06:01:57,230 - INFO - Epoch 51/100 - Train Loss: 0.1461 - Val Acc: 0.7826
2026-04-05 06:01:57,511 - INFO - Epoch 52/100 - Train Loss: 0.1492 - Val Acc: 0.7826
2026-04-05 06:01:57,790 - INFO - Epoch 53/100 - Train Loss: 0.1455 - Val Acc: 0.7826
2026-04-05 06:01:58,070 - INFO - Epoch 54/100 - Train Loss: 0.1464 - Val Acc: 0.7971
2026-04-05 06:01:58,356 - INFO - Epoch 55/100 - Train Loss: 0.1452 - Val Acc: 0.7971
2026-04-05 06:01:58,632 - INFO - Epoch 56/100 - Train Loss: 0.1451 - Val Acc: 0.8116
2026-04-05 06:01:58,907 - INFO - Epoch 57/100 - Train Loss: 0.1460 - Val Acc: 0.8116
2026-04-05 06:01:59,186 - INFO - Epoch 58/100 - Train Loss: 0.1443 - Val Acc: 0.8116
2026-04-05 06:01:59,462 - INFO - Epoch 59/100 - Train Loss: 0.1423 - Val Acc: 0.8116
2026-04-05 06:01:59,747 - INFO - Epoch 60/100 - Train Loss: 0.1436 - Val Acc: 0.8116
2026-04-05 06:02:00,031 - INFO - Epoch 61/100 - Train Loss: 0.1435 - Val Acc: 0.8116
2026-04-05 06:02:00,312 - INFO - Epoch 62/100 - Train Loss: 0.1410 - Val Acc: 0.8116
2026-04-05 06:02:00,619 - INFO - Epoch 63/100 - Train Loss: 0.1417 - Val Acc: 0.8116
2026-04-05 06:02:00,903 - INFO - Epoch 64/100 - Train Loss: 0.1379 - Val Acc: 0.8116
2026-04-05 06:02:01,185 - INFO - Epoch 65/100 - Train Loss: 0.1416 - Val Acc: 0.8116
2026-04-05 06:02:01,472 - INFO - Epoch 66/100 - Train Loss: 0.1381 - Val Acc: 0.8116
2026-04-05 06:02:01,746 - INFO - Epoch 67/100 - Train Loss: 0.1404 - Val Acc: 0.8116
2026-04-05 06:02:02,016 - INFO - Epoch 68/100 - Train Loss: 0.1372 - Val Acc: 0.8116
2026-04-05 06:02:02,314 - INFO - Epoch 69/100 - Train Loss: 0.1380 - Val Acc: 0.8116
2026-04-05 06:02:02,605 - INFO - Epoch 70/100 - Train Loss: 0.1337 - Val Acc: 0.8116
2026-04-05 06:02:02,873 - INFO - Epoch 71/100 - Train Loss: 0.1354 - Val Acc: 0.8116
2026-04-05 06:02:03,155 - INFO - Epoch 72/100 - Train Loss: 0.1365 - Val Acc: 0.8116
2026-04-05 06:02:03,431 - INFO - Epoch 73/100 - Train Loss: 0.1343 - Val Acc: 0.8116
2026-04-05 06:02:03,728 - INFO - Epoch 74/100 - Train Loss: 0.1336 - Val Acc: 0.8116
2026-04-05 06:02:04,009 - INFO - Epoch 75/100 - Train Loss: 0.1316 - Val Acc: 0.8116
2026-04-05 06:02:04,288 - INFO - Epoch 76/100 - Train Loss: 0.1345 - Val Acc: 0.8116
2026-04-05 06:02:04,591 - INFO - Epoch 77/100 - Train Loss: 0.1330 - Val Acc: 0.8116
2026-04-05 06:02:04,868 - INFO - Epoch 78/100 - Train Loss: 0.1312 - Val Acc: 0.8116
2026-04-05 06:02:05,143 - INFO - Epoch 79/100 - Train Loss: 0.1313 - Val Acc: 0.8116
2026-04-05 06:02:05,428 - INFO - Epoch 80/100 - Train Loss: 0.1301 - Val Acc: 0.8116
2026-04-05 06:02:05,719 - INFO - Epoch 81/100 - Train Loss: 0.1294 - Val Acc: 0.8116
2026-04-05 06:02:05,999 - INFO - Epoch 82/100 - Train Loss: 0.1295 - Val Acc: 0.8116
2026-04-05 06:02:06,285 - INFO - Epoch 83/100 - Train Loss: 0.1299 - Val Acc: 0.8116
2026-04-05 06:02:06,563 - INFO - Epoch 84/100 - Train Loss: 0.1272 - Val Acc: 0.8116
2026-04-05 06:02:06,837 - INFO - Epoch 85/100 - Train Loss: 0.1291 - Val Acc: 0.8116
2026-04-05 06:02:07,136 - INFO - Epoch 86/100 - Train Loss: 0.1293 - Val Acc: 0.8116
2026-04-05 06:02:07,417 - INFO - Epoch 87/100 - Train Loss: 0.1272 - Val Acc: 0.8116
2026-04-05 06:02:07,704 - INFO - Epoch 88/100 - Train Loss: 0.1248 - Val Acc: 0.8116
2026-04-05 06:02:07,978 - INFO - Epoch 89/100 - Train Loss: 0.1243 - Val Acc: 0.8116
2026-04-05 06:02:08,259 - INFO - Epoch 90/100 - Train Loss: 0.1237 - Val Acc: 0.8116
2026-04-05 06:02:08,541 - INFO - Epoch 91/100 - Train Loss: 0.1228 - Val Acc: 0.8116
2026-04-05 06:02:08,822 - INFO - Epoch 92/100 - Train Loss: 0.1248 - Val Acc: 0.8116
2026-04-05 06:02:09,091 - INFO - Epoch 93/100 - Train Loss: 0.1227 - Val Acc: 0.8116
2026-04-05 06:02:09,386 - INFO - Epoch 94/100 - Train Loss: 0.1210 - Val Acc: 0.8116
2026-04-05 06:02:09,690 - INFO - Epoch 95/100 - Train Loss: 0.1212 - Val Acc: 0.8116
2026-04-05 06:02:09,970 - INFO - Epoch 96/100 - Train Loss: 0.1221 - Val Acc: 0.8116
2026-04-05 06:02:10,250 - INFO - Epoch 97/100 - Train Loss: 0.1252 - Val Acc: 0.8116
2026-04-05 06:02:10,534 - INFO - Epoch 98/100 - Train Loss: 0.1197 - Val Acc: 0.7971
2026-04-05 06:02:10,816 - INFO - Epoch 99/100 - Train Loss: 0.1202 - Val Acc: 0.8116
2026-04-05 06:02:11,108 - INFO - Epoch 100/100 - Train Loss: 0.1205 - Val Acc: 0.8116
2026-04-05 06:02:11,467 - INFO - Fold 4 logically complete. Tensor memory bounds cleared cleanly.
2026-04-05 06:02:11,471 - INFO - Original class distribution: [345 276]
2026-04-05 06:02:11,472 - INFO - Training device bound securely to: cuda
2026-04-05 06:02:11,499 - INFO - After SMOTE-ENN deployment: [345 305]

Fold 5:   0%|          | 0/100 [00:00<?, ?it/s]

2026-04-05 06:02:11,811 - INFO - Epoch 1/100 - Train Loss: 0.5304 - Val Acc: 0.8406
2026-04-05 06:02:12,087 - INFO - Epoch 2/100 - Train Loss: 0.3328 - Val Acc: 0.8406
2026-04-05 06:02:12,377 - INFO - Epoch 3/100 - Train Loss: 0.2754 - Val Acc: 0.8551
2026-04-05 06:02:12,658 - INFO - Epoch 4/100 - Train Loss: 0.2489 - Val Acc: 0.8551
2026-04-05 06:02:12,940 - INFO - Epoch 5/100 - Train Loss: 0.2318 - Val Acc: 0.8696
2026-04-05 06:02:13,219 - INFO - Epoch 6/100 - Train Loss: 0.2188 - Val Acc: 0.8696
2026-04-05 06:02:13,503 - INFO - Epoch 7/100 - Train Loss: 0.2076 - Val Acc: 0.8696
2026-04-05 06:02:13,793 - INFO - Epoch 8/100 - Train Loss: 0.2011 - Val Acc: 0.8696
2026-04-05 06:02:14,095 - INFO - Epoch 9/100 - Train Loss: 0.1946 - Val Acc: 0.8696
2026-04-05 06:02:14,374 - INFO - Epoch 10/100 - Train Loss: 0.1922 - Val Acc: 0.8696
2026-04-05 06:02:14,674 - INFO - Epoch 11/100 - Train Loss: 0.1876 - Val Acc: 0.8696
2026-04-05 06:02:14,972 - INFO - Epoch 12/100 - Train Loss: 0.1840 - Val Acc: 0.8551
2026-04-05 06:02:15,266 - INFO - Epoch 13/100 - Train Loss: 0.1795 - Val Acc: 0.8551
2026-04-05 06:02:15,547 - INFO - Epoch 14/100 - Train Loss: 0.1770 - Val Acc: 0.8551
2026-04-05 06:02:15,829 - INFO - Epoch 15/100 - Train Loss: 0.1757 - Val Acc: 0.8551
2026-04-05 06:02:16,106 - INFO - Epoch 16/100 - Train Loss: 0.1732 - Val Acc: 0.8696
2026-04-05 06:02:16,395 - INFO - Epoch 17/100 - Train Loss: 0.1729 - Val Acc: 0.8551
2026-04-05 06:02:16,674 - INFO - Epoch 18/100 - Train Loss: 0.1700 - Val Acc: 0.8551
2026-04-05 06:02:16,954 - INFO - Epoch 19/100 - Train Loss: 0.1697 - Val Acc: 0.8551
2026-04-05 06:02:17,229 - INFO - Epoch 20/100 - Train Loss: 0.1672 - Val Acc: 0.8551
2026-04-05 06:02:17,540 - INFO - Epoch 21/100 - Train Loss: 0.1661 - Val Acc: 0.8551
2026-04-05 06:02:17,826 - INFO - Epoch 22/100 - Train Loss: 0.1660 - Val Acc: 0.8696
2026-04-05 06:02:18,104 - INFO - Epoch 23/100 - Train Loss: 0.1626 - Val Acc: 0.8551
2026-04-05 06:02:18,393 - INFO - Epoch 24/100 - Train Loss: 0.1622 - Val Acc: 0.8551
2026-04-05 06:02:18,707 - INFO - Epoch 25/100 - Train Loss: 0.1619 - Val Acc: 0.8551
2026-04-05 06:02:18,996 - INFO - Epoch 26/100 - Train Loss: 0.1595 - Val Acc: 0.8551
2026-04-05 06:02:19,267 - INFO - Epoch 27/100 - Train Loss: 0.1580 - Val Acc: 0.8551
2026-04-05 06:02:19,547 - INFO - Epoch 28/100 - Train Loss: 0.1574 - Val Acc: 0.8551
2026-04-05 06:02:19,823 - INFO - Epoch 29/100 - Train Loss: 0.1564 - Val Acc: 0.8551
2026-04-05 06:02:20,116 - INFO - Epoch 30/100 - Train Loss: 0.1546 - Val Acc: 0.8551
2026-04-05 06:02:20,389 - INFO - Epoch 31/100 - Train Loss: 0.1543 - Val Acc: 0.8551
2026-04-05 06:02:20,668 - INFO - Epoch 32/100 - Train Loss: 0.1515 - Val Acc: 0.8406
2026-04-05 06:02:20,938 - INFO - Epoch 33/100 - Train Loss: 0.1529 - Val Acc: 0.8551
2026-04-05 06:02:21,208 - INFO - Epoch 34/100 - Train Loss: 0.1479 - Val Acc: 0.8406
2026-04-05 06:02:21,485 - INFO - Epoch 35/100 - Train Loss: 0.1488 - Val Acc: 0.8406
2026-04-05 06:02:21,759 - INFO - Epoch 36/100 - Train Loss: 0.1467 - Val Acc: 0.8551
2026-04-05 06:02:22,032 - INFO - Epoch 37/100 - Train Loss: 0.1477 - Val Acc: 0.8551
2026-04-05 06:02:22,305 - INFO - Epoch 38/100 - Train Loss: 0.1458 - Val Acc: 0.8551
2026-04-05 06:02:22,586 - INFO - Epoch 39/100 - Train Loss: 0.1464 - Val Acc: 0.8551
2026-04-05 06:02:22,863 - INFO - Epoch 40/100 - Train Loss: 0.1434 - Val Acc: 0.8551
2026-04-05 06:02:23,153 - INFO - Epoch 41/100 - Train Loss: 0.1437 - Val Acc: 0.8406
2026-04-05 06:02:23,419 - INFO - Epoch 42/100 - Train Loss: 0.1382 - Val Acc: 0.8406
2026-04-05 06:02:23,691 - INFO - Epoch 43/100 - Train Loss: 0.1410 - Val Acc: 0.8406
2026-04-05 06:02:23,976 - INFO - Epoch 44/100 - Train Loss: 0.1415 - Val Acc: 0.8551
2026-04-05 06:02:24,259 - INFO - Epoch 45/100 - Train Loss: 0.1381 - Val Acc: 0.8406
2026-04-05 06:02:24,565 - INFO - Epoch 46/100 - Train Loss: 0.1384 - Val Acc: 0.8406
2026-04-05 06:02:24,847 - INFO - Epoch 47/100 - Train Loss: 0.1355 - Val Acc: 0.8406
2026-04-05 06:02:25,122 - INFO - Epoch 48/100 - Train Loss: 0.1344 - Val Acc: 0.8551
2026-04-05 06:02:25,405 - INFO - Epoch 49/100 - Train Loss: 0.1374 - Val Acc: 0.8551
2026-04-05 06:02:25,686 - INFO - Epoch 50/100 - Train Loss: 0.1308 - Val Acc: 0.8406
2026-04-05 06:02:25,963 - INFO - Epoch 51/100 - Train Loss: 0.1326 - Val Acc: 0.8406
2026-04-05 06:02:26,240 - INFO - Epoch 52/100 - Train Loss: 0.1329 - Val Acc: 0.8551
2026-04-05 06:02:26,510 - INFO - Epoch 53/100 - Train Loss: 0.1330 - Val Acc: 0.8551
2026-04-05 06:02:26,796 - INFO - Epoch 54/100 - Train Loss: 0.1308 - Val Acc: 0.8551
2026-04-05 06:02:27,076 - INFO - Epoch 55/100 - Train Loss: 0.1287 - Val Acc: 0.8551
2026-04-05 06:02:27,360 - INFO - Epoch 56/100 - Train Loss: 0.1320 - Val Acc: 0.8261
2026-04-05 06:02:27,647 - INFO - Epoch 57/100 - Train Loss: 0.1308 - Val Acc: 0.8406
2026-04-05 06:02:27,920 - INFO - Epoch 58/100 - Train Loss: 0.1277 - Val Acc: 0.8551
2026-04-05 06:02:28,200 - INFO - Epoch 59/100 - Train Loss: 0.1272 - Val Acc: 0.8406
2026-04-05 06:02:28,473 - INFO - Epoch 60/100 - Train Loss: 0.1260 - Val Acc: 0.8406
2026-04-05 06:02:28,746 - INFO - Epoch 61/100 - Train Loss: 0.1269 - Val Acc: 0.8551
2026-04-05 06:02:29,028 - INFO - Epoch 62/100 - Train Loss: 0.1269 - Val Acc: 0.8406
2026-04-05 06:02:29,294 - INFO - Epoch 63/100 - Train Loss: 0.1276 - Val Acc: 0.8406
2026-04-05 06:02:29,574 - INFO - Epoch 64/100 - Train Loss: 0.1246 - Val Acc: 0.8406
2026-04-05 06:02:29,858 - INFO - Epoch 65/100 - Train Loss: 0.1246 - Val Acc: 0.8406
2026-04-05 06:02:30,138 - INFO - Epoch 66/100 - Train Loss: 0.1246 - Val Acc: 0.8406
2026-04-05 06:02:30,422 - INFO - Epoch 67/100 - Train Loss: 0.1210 - Val Acc: 0.8261
2026-04-05 06:02:30,704 - INFO - Epoch 68/100 - Train Loss: 0.1215 - Val Acc: 0.8406
2026-04-05 06:02:30,982 - INFO - Epoch 69/100 - Train Loss: 0.1175 - Val Acc: 0.8261
2026-04-05 06:02:31,254 - INFO - Epoch 70/100 - Train Loss: 0.1187 - Val Acc: 0.8406
2026-04-05 06:02:31,527 - INFO - Epoch 71/100 - Train Loss: 0.1182 - Val Acc: 0.8406
2026-04-05 06:02:31,806 - INFO - Epoch 72/100 - Train Loss: 0.1224 - Val Acc: 0.8406
2026-04-05 06:02:32,080 - INFO - Epoch 73/100 - Train Loss: 0.1193 - Val Acc: 0.8406
2026-04-05 06:02:32,355 - INFO - Epoch 74/100 - Train Loss: 0.1218 - Val Acc: 0.8261
2026-04-05 06:02:32,648 - INFO - Epoch 75/100 - Train Loss: 0.1213 - Val Acc: 0.8261
2026-04-05 06:02:32,946 - INFO - Epoch 76/100 - Train Loss: 0.1193 - Val Acc: 0.8261
2026-04-05 06:02:33,224 - INFO - Epoch 77/100 - Train Loss: 0.1174 - Val Acc: 0.8261
2026-04-05 06:02:33,519 - INFO - Epoch 78/100 - Train Loss: 0.1201 - Val Acc: 0.7971
2026-04-05 06:02:33,811 - INFO - Epoch 79/100 - Train Loss: 0.1172 - Val Acc: 0.8116
2026-04-05 06:02:34,094 - INFO - Epoch 80/100 - Train Loss: 0.1175 - Val Acc: 0.8261
2026-04-05 06:02:34,389 - INFO - Epoch 81/100 - Train Loss: 0.1120 - Val Acc: 0.8261
2026-04-05 06:02:34,689 - INFO - Epoch 82/100 - Train Loss: 0.1113 - Val Acc: 0.8116
2026-04-05 06:02:34,967 - INFO - Epoch 83/100 - Train Loss: 0.1173 - Val Acc: 0.8116
2026-04-05 06:02:35,241 - INFO - Epoch 84/100 - Train Loss: 0.1116 - Val Acc: 0.8116
2026-04-05 06:02:35,545 - INFO - Epoch 85/100 - Train Loss: 0.1127 - Val Acc: 0.8116
2026-04-05 06:02:35,828 - INFO - Epoch 86/100 - Train Loss: 0.1115 - Val Acc: 0.8116
2026-04-05 06:02:36,106 - INFO - Epoch 87/100 - Train Loss: 0.1098 - Val Acc: 0.8261
2026-04-05 06:02:36,406 - INFO - Epoch 88/100 - Train Loss: 0.1133 - Val Acc: 0.8261
2026-04-05 06:02:36,689 - INFO - Epoch 89/100 - Train Loss: 0.1115 - Val Acc: 0.8116
2026-04-05 06:02:36,985 - INFO - Epoch 90/100 - Train Loss: 0.1102 - Val Acc: 0.7971
2026-04-05 06:02:37,258 - INFO - Epoch 91/100 - Train Loss: 0.1089 - Val Acc: 0.8116
2026-04-05 06:02:37,541 - INFO - Epoch 92/100 - Train Loss: 0.1121 - Val Acc: 0.8261
2026-04-05 06:02:37,826 - INFO - Epoch 93/100 - Train Loss: 0.1094 - Val Acc: 0.8261
2026-04-05 06:02:38,116 - INFO - Epoch 94/100 - Train Loss: 0.1052 - Val Acc: 0.8116
2026-04-05 06:02:38,398 - INFO - Epoch 95/100 - Train Loss: 0.1098 - Val Acc: 0.8116
2026-04-05 06:02:38,679 - INFO - Epoch 96/100 - Train Loss: 0.1088 - Val Acc: 0.8116
2026-04-05 06:02:38,958 - INFO - Epoch 97/100 - Train Loss: 0.1088 - Val Acc: 0.8116
2026-04-05 06:02:39,237 - INFO - Epoch 98/100 - Train Loss: 0.1071 - Val Acc: 0.8116
2026-04-05 06:02:39,523 - INFO - Epoch 99/100 - Train Loss: 0.1107 - Val Acc: 0.8261
2026-04-05 06:02:39,800 - INFO - Epoch 100/100 - Train Loss: 0.1104 - Val Acc: 0.8261
2026-04-05 06:02:40,156 - INFO - Fold 5 logically complete. Tensor memory bounds cleared cleanly.
2026-04-05 06:02:40,160 - INFO - Original class distribution: [345 276]
2026-04-05 06:02:40,161 - INFO - Training device bound securely to: cuda
2026-04-05 06:02:40,189 - INFO - After SMOTE-ENN deployment: [345 293]

Fold 6:   0%|          | 0/100 [00:00<?, ?it/s]

2026-04-05 06:02:40,473 - INFO - Epoch 1/100 - Train Loss: 0.5267 - Val Acc: 0.8551
2026-04-05 06:02:40,762 - INFO - Epoch 2/100 - Train Loss: 0.3292 - Val Acc: 0.8406
2026-04-05 06:02:41,040 - INFO - Epoch 3/100 - Train Loss: 0.2755 - Val Acc: 0.8551
2026-04-05 06:02:41,301 - INFO - Epoch 4/100 - Train Loss: 0.2498 - Val Acc: 0.8696
2026-04-05 06:02:41,565 - INFO - Epoch 5/100 - Train Loss: 0.2360 - Val Acc: 0.8696
2026-04-05 06:02:41,837 - INFO - Epoch 6/100 - Train Loss: 0.2244 - Val Acc: 0.8696
2026-04-05 06:02:42,100 - INFO - Epoch 7/100 - Train Loss: 0.2171 - Val Acc: 0.8551
2026-04-05 06:02:42,369 - INFO - Epoch 8/100 - Train Loss: 0.2104 - Val Acc: 0.8551
2026-04-05 06:02:42,641 - INFO - Epoch 9/100 - Train Loss: 0.2034 - Val Acc: 0.8551
2026-04-05 06:02:42,920 - INFO - Epoch 10/100 - Train Loss: 0.1995 - Val Acc: 0.8551
2026-04-05 06:02:43,188 - INFO - Epoch 11/100 - Train Loss: 0.1954 - Val Acc: 0.8551
2026-04-05 06:02:43,449 - INFO - Epoch 12/100 - Train Loss: 0.1930 - Val Acc: 0.8551
2026-04-05 06:02:43,715 - INFO - Epoch 13/100 - Train Loss: 0.1902 - Val Acc: 0.8551
2026-04-05 06:02:43,983 - INFO - Epoch 14/100 - Train Loss: 0.1882 - Val Acc: 0.8551
2026-04-05 06:02:44,261 - INFO - Epoch 15/100 - Train Loss: 0.1848 - Val Acc: 0.8551
2026-04-05 06:02:44,553 - INFO - Epoch 16/100 - Train Loss: 0.1841 - Val Acc: 0.8551
2026-04-05 06:02:44,843 - INFO - Epoch 17/100 - Train Loss: 0.1819 - Val Acc: 0.8551
2026-04-05 06:02:45,118 - INFO - Epoch 18/100 - Train Loss: 0.1793 - Val Acc: 0.8551
2026-04-05 06:02:45,386 - INFO - Epoch 19/100 - Train Loss: 0.1799 - Val Acc: 0.8551
2026-04-05 06:02:45,672 - INFO - Epoch 20/100 - Train Loss: 0.1747 - Val Acc: 0.8551
2026-04-05 06:02:45,947 - INFO - Epoch 21/100 - Train Loss: 0.1773 - Val Acc: 0.8551
2026-04-05 06:02:46,220 - INFO - Epoch 22/100 - Train Loss: 0.1726 - Val Acc: 0.8406
2026-04-05 06:02:46,492 - INFO - Epoch 23/100 - Train Loss: 0.1735 - Val Acc: 0.8551
2026-04-05 06:02:46,771 - INFO - Epoch 24/100 - Train Loss: 0.1702 - Val Acc: 0.8551
2026-04-05 06:02:47,035 - INFO - Epoch 25/100 - Train Loss: 0.1703 - Val Acc: 0.8551
2026-04-05 06:02:47,300 - INFO - Epoch 26/100 - Train Loss: 0.1695 - Val Acc: 0.8551
2026-04-05 06:02:47,577 - INFO - Epoch 27/100 - Train Loss: 0.1663 - Val Acc: 0.8406
2026-04-05 06:02:47,855 - INFO - Epoch 28/100 - Train Loss: 0.1646 - Val Acc: 0.8551
2026-04-05 06:02:48,136 - INFO - Epoch 29/100 - Train Loss: 0.1656 - Val Acc: 0.8406
2026-04-05 06:02:48,411 - INFO - Epoch 30/100 - Train Loss: 0.1617 - Val Acc: 0.8406
2026-04-05 06:02:48,682 - INFO - Epoch 31/100 - Train Loss: 0.1627 - Val Acc: 0.8406
2026-04-05 06:02:48,945 - INFO - Epoch 32/100 - Train Loss: 0.1603 - Val Acc: 0.8406
2026-04-05 06:02:49,222 - INFO - Epoch 33/100 - Train Loss: 0.1604 - Val Acc: 0.8406
2026-04-05 06:02:49,499 - INFO - Epoch 34/100 - Train Loss: 0.1570 - Val Acc: 0.8406
2026-04-05 06:02:49,763 - INFO - Epoch 35/100 - Train Loss: 0.1581 - Val Acc: 0.8406
2026-04-05 06:02:50,030 - INFO - Epoch 36/100 - Train Loss: 0.1553 - Val Acc: 0.8406
2026-04-05 06:02:50,301 - INFO - Epoch 37/100 - Train Loss: 0.1567 - Val Acc: 0.8261
2026-04-05 06:02:50,581 - INFO - Epoch 38/100 - Train Loss: 0.1548 - Val Acc: 0.8261
2026-04-05 06:02:50,856 - INFO - Epoch 39/100 - Train Loss: 0.1512 - Val Acc: 0.8261
2026-04-05 06:02:51,134 - INFO - Epoch 40/100 - Train Loss: 0.1523 - Val Acc: 0.8261
2026-04-05 06:02:51,414 - INFO - Epoch 41/100 - Train Loss: 0.1490 - Val Acc: 0.8261
2026-04-05 06:02:51,683 - INFO - Epoch 42/100 - Train Loss: 0.1485 - Val Acc: 0.8261
2026-04-05 06:02:51,973 - INFO - Epoch 43/100 - Train Loss: 0.1461 - Val Acc: 0.8261
2026-04-05 06:02:52,260 - INFO - Epoch 44/100 - Train Loss: 0.1496 - Val Acc: 0.8261
2026-04-05 06:02:52,536 - INFO - Epoch 45/100 - Train Loss: 0.1455 - Val Acc: 0.8261
2026-04-05 06:02:52,809 - INFO - Epoch 46/100 - Train Loss: 0.1485 - Val Acc: 0.8261
2026-04-05 06:02:53,078 - INFO - Epoch 47/100 - Train Loss: 0.1436 - Val Acc: 0.8261
2026-04-05 06:02:53,347 - INFO - Epoch 48/100 - Train Loss: 0.1451 - Val Acc: 0.8261
2026-04-05 06:02:53,615 - INFO - Epoch 49/100 - Train Loss: 0.1428 - Val Acc: 0.8261
2026-04-05 06:02:53,893 - INFO - Epoch 50/100 - Train Loss: 0.1414 - Val Acc: 0.8261
2026-04-05 06:02:54,179 - INFO - Epoch 51/100 - Train Loss: 0.1415 - Val Acc: 0.8261
2026-04-05 06:02:54,453 - INFO - Epoch 52/100 - Train Loss: 0.1412 - Val Acc: 0.8261
2026-04-05 06:02:54,767 - INFO - Epoch 53/100 - Train Loss: 0.1389 - Val Acc: 0.8261
2026-04-05 06:02:55,043 - INFO - Epoch 54/100 - Train Loss: 0.1377 - Val Acc: 0.8261
2026-04-05 06:02:55,310 - INFO - Epoch 55/100 - Train Loss: 0.1373 - Val Acc: 0.8261
2026-04-05 06:02:55,590 - INFO - Epoch 56/100 - Train Loss: 0.1385 - Val Acc: 0.8261
2026-04-05 06:02:55,867 - INFO - Epoch 57/100 - Train Loss: 0.1367 - Val Acc: 0.8261
2026-04-05 06:02:56,136 - INFO - Epoch 58/100 - Train Loss: 0.1376 - Val Acc: 0.8261
2026-04-05 06:02:56,419 - INFO - Epoch 59/100 - Train Loss: 0.1343 - Val Acc: 0.8261
2026-04-05 06:02:56,686 - INFO - Epoch 60/100 - Train Loss: 0.1333 - Val Acc: 0.8261
2026-04-05 06:02:56,958 - INFO - Epoch 61/100 - Train Loss: 0.1331 - Val Acc: 0.8261
2026-04-05 06:02:57,233 - INFO - Epoch 62/100 - Train Loss: 0.1333 - Val Acc: 0.8261
2026-04-05 06:02:57,508 - INFO - Epoch 63/100 - Train Loss: 0.1321 - Val Acc: 0.8261
2026-04-05 06:02:57,785 - INFO - Epoch 64/100 - Train Loss: 0.1306 - Val Acc: 0.8261
2026-04-05 06:02:58,077 - INFO - Epoch 65/100 - Train Loss: 0.1334 - Val Acc: 0.8261
2026-04-05 06:02:58,342 - INFO - Epoch 66/100 - Train Loss: 0.1292 - Val Acc: 0.8261
2026-04-05 06:02:58,613 - INFO - Epoch 67/100 - Train Loss: 0.1295 - Val Acc: 0.8261
2026-04-05 06:02:58,887 - INFO - Epoch 68/100 - Train Loss: 0.1283 - Val Acc: 0.8261
2026-04-05 06:02:59,147 - INFO - Epoch 69/100 - Train Loss: 0.1313 - Val Acc: 0.8261
2026-04-05 06:02:59,408 - INFO - Epoch 70/100 - Train Loss: 0.1278 - Val Acc: 0.8261
2026-04-05 06:02:59,675 - INFO - Epoch 71/100 - Train Loss: 0.1267 - Val Acc: 0.8261
2026-04-05 06:02:59,951 - INFO - Epoch 72/100 - Train Loss: 0.1286 - Val Acc: 0.8261
2026-04-05 06:03:00,217 - INFO - Epoch 73/100 - Train Loss: 0.1264 - Val Acc: 0.8261
2026-04-05 06:03:00,479 - INFO - Epoch 74/100 - Train Loss: 0.1280 - Val Acc: 0.8261
2026-04-05 06:03:00,767 - INFO - Epoch 75/100 - Train Loss: 0.1241 - Val Acc: 0.8261
2026-04-05 06:03:01,053 - INFO - Epoch 76/100 - Train Loss: 0.1209 - Val Acc: 0.8261
2026-04-05 06:03:01,332 - INFO - Epoch 77/100 - Train Loss: 0.1260 - Val Acc: 0.8261
2026-04-05 06:03:01,603 - INFO - Epoch 78/100 - Train Loss: 0.1212 - Val Acc: 0.8261
2026-04-05 06:03:01,899 - INFO - Epoch 79/100 - Train Loss: 0.1207 - Val Acc: 0.8261
2026-04-05 06:03:02,172 - INFO - Epoch 80/100 - Train Loss: 0.1224 - Val Acc: 0.8261
2026-04-05 06:03:02,443 - INFO - Epoch 81/100 - Train Loss: 0.1242 - Val Acc: 0.8261
2026-04-05 06:03:02,713 - INFO - Epoch 82/100 - Train Loss: 0.1211 - Val Acc: 0.8261
2026-04-05 06:03:02,985 - INFO - Epoch 83/100 - Train Loss: 0.1208 - Val Acc: 0.8261
2026-04-05 06:03:03,264 - INFO - Epoch 84/100 - Train Loss: 0.1204 - Val Acc: 0.8406
2026-04-05 06:03:03,540 - INFO - Epoch 85/100 - Train Loss: 0.1190 - Val Acc: 0.8406
2026-04-05 06:03:03,814 - INFO - Epoch 86/100 - Train Loss: 0.1179 - Val Acc: 0.8261
2026-04-05 06:03:04,085 - INFO - Epoch 87/100 - Train Loss: 0.1173 - Val Acc: 0.8406
2026-04-05 06:03:04,364 - INFO - Epoch 88/100 - Train Loss: 0.1178 - Val Acc: 0.8406
2026-04-05 06:03:04,662 - INFO - Epoch 89/100 - Train Loss: 0.1155 - Val Acc: 0.8406
2026-04-05 06:03:04,950 - INFO - Epoch 90/100 - Train Loss: 0.1179 - Val Acc: 0.8261
2026-04-05 06:03:05,218 - INFO - Epoch 91/100 - Train Loss: 0.1166 - Val Acc: 0.8261
2026-04-05 06:03:05,491 - INFO - Epoch 92/100 - Train Loss: 0.1173 - Val Acc: 0.8261
2026-04-05 06:03:05,762 - INFO - Epoch 93/100 - Train Loss: 0.1149 - Val Acc: 0.8261
2026-04-05 06:03:06,038 - INFO - Epoch 94/100 - Train Loss: 0.1103 - Val Acc: 0.8261
2026-04-05 06:03:06,319 - INFO - Epoch 95/100 - Train Loss: 0.1126 - Val Acc: 0.8261
2026-04-05 06:03:06,590 - INFO - Epoch 96/100 - Train Loss: 0.1119 - Val Acc: 0.8261
2026-04-05 06:03:06,870 - INFO - Epoch 97/100 - Train Loss: 0.1118 - Val Acc: 0.8261
2026-04-05 06:03:07,137 - INFO - Epoch 98/100 - Train Loss: 0.1132 - Val Acc: 0.8261
2026-04-05 06:03:07,411 - INFO - Epoch 99/100 - Train Loss: 0.1107 - Val Acc: 0.8261
2026-04-05 06:03:07,680 - INFO - Epoch 100/100 - Train Loss: 0.1124 - Val Acc: 0.8261
2026-04-05 06:03:08,054 - INFO - Fold 6 logically complete. Tensor memory bounds cleared cleanly.
2026-04-05 06:03:08,058 - INFO - Original class distribution: [345 276]
2026-04-05 06:03:08,059 - INFO - Training device bound securely to: cuda
2026-04-05 06:03:08,088 - INFO - After SMOTE-ENN deployment: [345 302]

Fold 7:   0%|          | 0/100 [00:00<?, ?it/s]

2026-04-05 06:03:08,391 - INFO - Epoch 1/100 - Train Loss: 0.5323 - Val Acc: 0.7246
2026-04-05 06:03:08,672 - INFO - Epoch 2/100 - Train Loss: 0.3230 - Val Acc: 0.7246
2026-04-05 06:03:08,957 - INFO - Epoch 3/100 - Train Loss: 0.2623 - Val Acc: 0.7246
2026-04-05 06:03:09,229 - INFO - Epoch 4/100 - Train Loss: 0.2347 - Val Acc: 0.7246
2026-04-05 06:03:09,508 - INFO - Epoch 5/100 - Train Loss: 0.2177 - Val Acc: 0.7391
2026-04-05 06:03:09,800 - INFO - Epoch 6/100 - Train Loss: 0.2069 - Val Acc: 0.7246
2026-04-05 06:03:10,073 - INFO - Epoch 7/100 - Train Loss: 0.2004 - Val Acc: 0.7246
2026-04-05 06:03:10,357 - INFO - Epoch 8/100 - Train Loss: 0.1915 - Val Acc: 0.7246
2026-04-05 06:03:10,641 - INFO - Epoch 9/100 - Train Loss: 0.1854 - Val Acc: 0.7246
2026-04-05 06:03:10,918 - INFO - Epoch 10/100 - Train Loss: 0.1814 - Val Acc: 0.7246
2026-04-05 06:03:11,196 - INFO - Epoch 11/100 - Train Loss: 0.1752 - Val Acc: 0.7246
2026-04-05 06:03:11,473 - INFO - Epoch 12/100 - Train Loss: 0.1736 - Val Acc: 0.7391
2026-04-05 06:03:11,753 - INFO - Epoch 13/100 - Train Loss: 0.1719 - Val Acc: 0.7391
2026-04-05 06:03:12,041 - INFO - Epoch 14/100 - Train Loss: 0.1665 - Val Acc: 0.7391
2026-04-05 06:03:12,312 - INFO - Epoch 15/100 - Train Loss: 0.1684 - Val Acc: 0.7391
2026-04-05 06:03:12,594 - INFO - Epoch 16/100 - Train Loss: 0.1620 - Val Acc: 0.7391
2026-04-05 06:03:12,895 - INFO - Epoch 17/100 - Train Loss: 0.1636 - Val Acc: 0.7391
2026-04-05 06:03:13,187 - INFO - Epoch 18/100 - Train Loss: 0.1600 - Val Acc: 0.7391
2026-04-05 06:03:13,460 - INFO - Epoch 19/100 - Train Loss: 0.1606 - Val Acc: 0.7391
2026-04-05 06:03:13,741 - INFO - Epoch 20/100 - Train Loss: 0.1556 - Val Acc: 0.7391
2026-04-05 06:03:14,030 - INFO - Epoch 21/100 - Train Loss: 0.1536 - Val Acc: 0.7391
2026-04-05 06:03:14,319 - INFO - Epoch 22/100 - Train Loss: 0.1511 - Val Acc: 0.7391
2026-04-05 06:03:14,615 - INFO - Epoch 23/100 - Train Loss: 0.1541 - Val Acc: 0.7391
2026-04-05 06:03:14,908 - INFO - Epoch 24/100 - Train Loss: 0.1529 - Val Acc: 0.7391
2026-04-05 06:03:15,193 - INFO - Epoch 25/100 - Train Loss: 0.1513 - Val Acc: 0.7391
2026-04-05 06:03:15,497 - INFO - Epoch 26/100 - Train Loss: 0.1511 - Val Acc: 0.7391
2026-04-05 06:03:15,777 - INFO - Epoch 27/100 - Train Loss: 0.1506 - Val Acc: 0.7536
2026-04-05 06:03:16,065 - INFO - Epoch 28/100 - Train Loss: 0.1471 - Val Acc: 0.7536
2026-04-05 06:03:16,333 - INFO - Epoch 29/100 - Train Loss: 0.1464 - Val Acc: 0.7536
2026-04-05 06:03:16,609 - INFO - Epoch 30/100 - Train Loss: 0.1438 - Val Acc: 0.7536
2026-04-05 06:03:16,885 - INFO - Epoch 31/100 - Train Loss: 0.1436 - Val Acc: 0.7536
2026-04-05 06:03:17,165 - INFO - Epoch 32/100 - Train Loss: 0.1424 - Val Acc: 0.7536
2026-04-05 06:03:17,445 - INFO - Epoch 33/100 - Train Loss: 0.1409 - Val Acc: 0.7536
2026-04-05 06:03:17,726 - INFO - Epoch 34/100 - Train Loss: 0.1415 - Val Acc: 0.7536
2026-04-05 06:03:18,004 - INFO - Epoch 35/100 - Train Loss: 0.1414 - Val Acc: 0.7536
2026-04-05 06:03:18,289 - INFO - Epoch 36/100 - Train Loss: 0.1396 - Val Acc: 0.7536
2026-04-05 06:03:18,564 - INFO - Epoch 37/100 - Train Loss: 0.1408 - Val Acc: 0.7536
2026-04-05 06:03:18,838 - INFO - Epoch 38/100 - Train Loss: 0.1366 - Val Acc: 0.7536
2026-04-05 06:03:19,113 - INFO - Epoch 39/100 - Train Loss: 0.1367 - Val Acc: 0.7536
2026-04-05 06:03:19,391 - INFO - Epoch 40/100 - Train Loss: 0.1364 - Val Acc: 0.7536
2026-04-05 06:03:19,675 - INFO - Epoch 41/100 - Train Loss: 0.1340 - Val Acc: 0.7536
2026-04-05 06:03:19,955 - INFO - Epoch 42/100 - Train Loss: 0.1344 - Val Acc: 0.7536
2026-04-05 06:03:20,231 - INFO - Epoch 43/100 - Train Loss: 0.1311 - Val Acc: 0.7536
2026-04-05 06:03:20,495 - INFO - Epoch 44/100 - Train Loss: 0.1331 - Val Acc: 0.7536
2026-04-05 06:03:20,766 - INFO - Epoch 45/100 - Train Loss: 0.1330 - Val Acc: 0.7391
2026-04-05 06:03:21,045 - INFO - Epoch 46/100 - Train Loss: 0.1290 - Val Acc: 0.7391
2026-04-05 06:03:21,320 - INFO - Epoch 47/100 - Train Loss: 0.1288 - Val Acc: 0.7536
2026-04-05 06:03:21,601 - INFO - Epoch 48/100 - Train Loss: 0.1279 - Val Acc: 0.7536
2026-04-05 06:03:21,884 - INFO - Epoch 49/100 - Train Loss: 0.1265 - Val Acc: 0.7536
2026-04-05 06:03:22,178 - INFO - Epoch 50/100 - Train Loss: 0.1243 - Val Acc: 0.7391
2026-04-05 06:03:22,452 - INFO - Epoch 51/100 - Train Loss: 0.1262 - Val Acc: 0.7391
2026-04-05 06:03:22,735 - INFO - Epoch 52/100 - Train Loss: 0.1236 - Val Acc: 0.7391
2026-04-05 06:03:23,012 - INFO - Epoch 53/100 - Train Loss: 0.1283 - Val Acc: 0.7391
2026-04-05 06:03:23,303 - INFO - Epoch 54/100 - Train Loss: 0.1260 - Val Acc: 0.7391
2026-04-05 06:03:23,591 - INFO - Epoch 55/100 - Train Loss: 0.1208 - Val Acc: 0.7391
2026-04-05 06:03:23,869 - INFO - Epoch 56/100 - Train Loss: 0.1254 - Val Acc: 0.7391
2026-04-05 06:03:24,147 - INFO - Epoch 57/100 - Train Loss: 0.1216 - Val Acc: 0.7536
2026-04-05 06:03:24,432 - INFO - Epoch 58/100 - Train Loss: 0.1200 - Val Acc: 0.7391
2026-04-05 06:03:24,734 - INFO - Epoch 59/100 - Train Loss: 0.1219 - Val Acc: 0.7391
2026-04-05 06:03:25,008 - INFO - Epoch 60/100 - Train Loss: 0.1222 - Val Acc: 0.7536
2026-04-05 06:03:25,290 - INFO - Epoch 61/100 - Train Loss: 0.1207 - Val Acc: 0.7536
2026-04-05 06:03:25,574 - INFO - Epoch 62/100 - Train Loss: 0.1199 - Val Acc: 0.7536
2026-04-05 06:03:25,847 - INFO - Epoch 63/100 - Train Loss: 0.1173 - Val Acc: 0.7536
2026-04-05 06:03:26,113 - INFO - Epoch 64/100 - Train Loss: 0.1153 - Val Acc: 0.7536
2026-04-05 06:03:26,393 - INFO - Epoch 65/100 - Train Loss: 0.1156 - Val Acc: 0.7536
2026-04-05 06:03:26,666 - INFO - Epoch 66/100 - Train Loss: 0.1161 - Val Acc: 0.7536
2026-04-05 06:03:26,947 - INFO - Epoch 67/100 - Train Loss: 0.1165 - Val Acc: 0.7536
2026-04-05 06:03:27,228 - INFO - Epoch 68/100 - Train Loss: 0.1142 - Val Acc: 0.7536
2026-04-05 06:03:27,511 - INFO - Epoch 69/100 - Train Loss: 0.1151 - Val Acc: 0.7536
2026-04-05 06:03:27,802 - INFO - Epoch 70/100 - Train Loss: 0.1133 - Val Acc: 0.7536
2026-04-05 06:03:28,104 - INFO - Epoch 71/100 - Train Loss: 0.1102 - Val Acc: 0.7536
2026-04-05 06:03:28,392 - INFO - Epoch 72/100 - Train Loss: 0.1128 - Val Acc: 0.7536
2026-04-05 06:03:28,685 - INFO - Epoch 73/100 - Train Loss: 0.1122 - Val Acc: 0.7536
2026-04-05 06:03:28,963 - INFO - Epoch 74/100 - Train Loss: 0.1110 - Val Acc: 0.7536
2026-04-05 06:03:29,239 - INFO - Epoch 75/100 - Train Loss: 0.1091 - Val Acc: 0.7391
2026-04-05 06:03:29,516 - INFO - Epoch 76/100 - Train Loss: 0.1080 - Val Acc: 0.7536
2026-04-05 06:03:29,803 - INFO - Epoch 77/100 - Train Loss: 0.1105 - Val Acc: 0.7536
2026-04-05 06:03:30,083 - INFO - Epoch 78/100 - Train Loss: 0.1097 - Val Acc: 0.7536
2026-04-05 06:03:30,355 - INFO - Epoch 79/100 - Train Loss: 0.1093 - Val Acc: 0.7536
2026-04-05 06:03:30,629 - INFO - Epoch 80/100 - Train Loss: 0.1082 - Val Acc: 0.7536
2026-04-05 06:03:30,908 - INFO - Epoch 81/100 - Train Loss: 0.1089 - Val Acc: 0.7536
2026-04-05 06:03:31,182 - INFO - Epoch 82/100 - Train Loss: 0.1084 - Val Acc: 0.7536
2026-04-05 06:03:31,454 - INFO - Epoch 83/100 - Train Loss: 0.1078 - Val Acc: 0.7536
2026-04-05 06:03:31,732 - INFO - Epoch 84/100 - Train Loss: 0.1075 - Val Acc: 0.7536
2026-04-05 06:03:32,023 - INFO - Epoch 85/100 - Train Loss: 0.1065 - Val Acc: 0.7536
2026-04-05 06:03:32,306 - INFO - Epoch 86/100 - Train Loss: 0.1109 - Val Acc: 0.7536
2026-04-05 06:03:32,596 - INFO - Epoch 87/100 - Train Loss: 0.1082 - Val Acc: 0.7536
2026-04-05 06:03:32,895 - INFO - Epoch 88/100 - Train Loss: 0.1095 - Val Acc: 0.7536
2026-04-05 06:03:33,190 - INFO - Epoch 89/100 - Train Loss: 0.1078 - Val Acc: 0.7536
2026-04-05 06:03:33,478 - INFO - Epoch 90/100 - Train Loss: 0.1076 - Val Acc: 0.7536
2026-04-05 06:03:33,754 - INFO - Epoch 91/100 - Train Loss: 0.1065 - Val Acc: 0.7536
2026-04-05 06:03:34,039 - INFO - Epoch 92/100 - Train Loss: 0.1063 - Val Acc: 0.7536
2026-04-05 06:03:34,318 - INFO - Epoch 93/100 - Train Loss: 0.1051 - Val Acc: 0.7681
2026-04-05 06:03:34,621 - INFO - Epoch 94/100 - Train Loss: 0.1078 - Val Acc: 0.7681
2026-04-05 06:03:34,913 - INFO - Epoch 95/100 - Train Loss: 0.1042 - Val Acc: 0.7536
2026-04-05 06:03:35,201 - INFO - Epoch 96/100 - Train Loss: 0.1010 - Val Acc: 0.7681
2026-04-05 06:03:35,481 - INFO - Epoch 97/100 - Train Loss: 0.1047 - Val Acc: 0.7826
2026-04-05 06:03:35,755 - INFO - Epoch 98/100 - Train Loss: 0.1029 - Val Acc: 0.7536
2026-04-05 06:03:36,033 - INFO - Epoch 99/100 - Train Loss: 0.1052 - Val Acc: 0.7681
2026-04-05 06:03:36,332 - INFO - Epoch 100/100 - Train Loss: 0.1012 - Val Acc: 0.7536
2026-04-05 06:03:36,700 - INFO - Fold 7 logically complete. Tensor memory bounds cleared cleanly.
2026-04-05 06:03:36,704 - INFO - Original class distribution: [345 276]
2026-04-05 06:03:36,704 - INFO - Training device bound securely to: cuda
2026-04-05 06:03:36,733 - INFO - After SMOTE-ENN deployment: [345 296]

Fold 8:   0%|          | 0/100 [00:00<?, ?it/s]

2026-04-05 06:03:37,033 - INFO - Epoch 1/100 - Train Loss: 0.5312 - Val Acc: 0.8551
2026-04-05 06:03:37,318 - INFO - Epoch 2/100 - Train Loss: 0.3564 - Val Acc: 0.8696
2026-04-05 06:03:37,595 - INFO - Epoch 3/100 - Train Loss: 0.2966 - Val Acc: 0.8551
2026-04-05 06:03:37,862 - INFO - Epoch 4/100 - Train Loss: 0.2672 - Val Acc: 0.8696
2026-04-05 06:03:38,144 - INFO - Epoch 5/100 - Train Loss: 0.2496 - Val Acc: 0.8696
2026-04-05 06:03:38,415 - INFO - Epoch 6/100 - Train Loss: 0.2406 - Val Acc: 0.8551
2026-04-05 06:03:38,692 - INFO - Epoch 7/100 - Train Loss: 0.2301 - Val Acc: 0.8696
2026-04-05 06:03:38,975 - INFO - Epoch 8/100 - Train Loss: 0.2217 - Val Acc: 0.8986
2026-04-05 06:03:39,262 - INFO - Epoch 9/100 - Train Loss: 0.2177 - Val Acc: 0.8841
2026-04-05 06:03:39,537 - INFO - Epoch 10/100 - Train Loss: 0.2120 - Val Acc: 0.8551
2026-04-05 06:03:39,811 - INFO - Epoch 11/100 - Train Loss: 0.2084 - Val Acc: 0.8261
2026-04-05 06:03:40,116 - INFO - Epoch 12/100 - Train Loss: 0.2050 - Val Acc: 0.8261
2026-04-05 06:03:40,397 - INFO - Epoch 13/100 - Train Loss: 0.1996 - Val Acc: 0.8116
2026-04-05 06:03:40,678 - INFO - Epoch 14/100 - Train Loss: 0.1969 - Val Acc: 0.8406
2026-04-05 06:03:40,964 - INFO - Epoch 15/100 - Train Loss: 0.1943 - Val Acc: 0.8406
2026-04-05 06:03:41,255 - INFO - Epoch 16/100 - Train Loss: 0.1919 - Val Acc: 0.8696
2026-04-05 06:03:41,538 - INFO - Epoch 17/100 - Train Loss: 0.1913 - Val Acc: 0.8551
2026-04-05 06:03:41,808 - INFO - Epoch 18/100 - Train Loss: 0.1889 - Val Acc: 0.8551
2026-04-05 06:03:42,105 - INFO - Epoch 19/100 - Train Loss: 0.1884 - Val Acc: 0.8551
2026-04-05 06:03:42,387 - INFO - Epoch 20/100 - Train Loss: 0.1865 - Val Acc: 0.8551
2026-04-05 06:03:42,656 - INFO - Epoch 21/100 - Train Loss: 0.1873 - Val Acc: 0.8551
2026-04-05 06:03:42,930 - INFO - Epoch 22/100 - Train Loss: 0.1857 - Val Acc: 0.8551
2026-04-05 06:03:43,194 - INFO - Epoch 23/100 - Train Loss: 0.1846 - Val Acc: 0.8551
2026-04-05 06:03:43,473 - INFO - Epoch 24/100 - Train Loss: 0.1833 - Val Acc: 0.8551
2026-04-05 06:03:43,752 - INFO - Epoch 25/100 - Train Loss: 0.1823 - Val Acc: 0.8696
2026-04-05 06:03:44,028 - INFO - Epoch 26/100 - Train Loss: 0.1799 - Val Acc: 0.8696
2026-04-05 06:03:44,306 - INFO - Epoch 27/100 - Train Loss: 0.1776 - Val Acc: 0.8551
2026-04-05 06:03:44,603 - INFO - Epoch 28/100 - Train Loss: 0.1767 - Val Acc: 0.8551
2026-04-05 06:03:44,896 - INFO - Epoch 29/100 - Train Loss: 0.1767 - Val Acc: 0.8551
2026-04-05 06:03:45,190 - INFO - Epoch 30/100 - Train Loss: 0.1747 - Val Acc: 0.8551
2026-04-05 06:03:45,464 - INFO - Epoch 31/100 - Train Loss: 0.1745 - Val Acc: 0.8551
2026-04-05 06:03:45,771 - INFO - Epoch 32/100 - Train Loss: 0.1740 - Val Acc: 0.8551
2026-04-05 06:03:46,083 - INFO - Epoch 33/100 - Train Loss: 0.1725 - Val Acc: 0.8551
2026-04-05 06:03:46,387 - INFO - Epoch 34/100 - Train Loss: 0.1706 - Val Acc: 0.8551
2026-04-05 06:03:46,672 - INFO - Epoch 35/100 - Train Loss: 0.1709 - Val Acc: 0.8551
2026-04-05 06:03:46,946 - INFO - Epoch 36/100 - Train Loss: 0.1696 - Val Acc: 0.8406
2026-04-05 06:03:47,222 - INFO - Epoch 37/100 - Train Loss: 0.1737 - Val Acc: 0.8406
2026-04-05 06:03:47,495 - INFO - Epoch 38/100 - Train Loss: 0.1696 - Val Acc: 0.8261
2026-04-05 06:03:47,765 - INFO - Epoch 39/100 - Train Loss: 0.1664 - Val Acc: 0.8551
2026-04-05 06:03:48,056 - INFO - Epoch 40/100 - Train Loss: 0.1680 - Val Acc: 0.8551
2026-04-05 06:03:48,353 - INFO - Epoch 41/100 - Train Loss: 0.1644 - Val Acc: 0.8696
2026-04-05 06:03:48,646 - INFO - Epoch 42/100 - Train Loss: 0.1644 - Val Acc: 0.8696
2026-04-05 06:03:48,918 - INFO - Epoch 43/100 - Train Loss: 0.1617 - Val Acc: 0.8551
2026-04-05 06:03:49,202 - INFO - Epoch 44/100 - Train Loss: 0.1625 - Val Acc: 0.8551
2026-04-05 06:03:49,486 - INFO - Epoch 45/100 - Train Loss: 0.1627 - Val Acc: 0.8551
2026-04-05 06:03:49,772 - INFO - Epoch 46/100 - Train Loss: 0.1603 - Val Acc: 0.8551
2026-04-05 06:03:50,051 - INFO - Epoch 47/100 - Train Loss: 0.1598 - Val Acc: 0.8841
2026-04-05 06:03:50,336 - INFO - Epoch 48/100 - Train Loss: 0.1602 - Val Acc: 0.8696
2026-04-05 06:03:50,614 - INFO - Epoch 49/100 - Train Loss: 0.1580 - Val Acc: 0.8551
2026-04-05 06:03:50,896 - INFO - Epoch 50/100 - Train Loss: 0.1596 - Val Acc: 0.8551
2026-04-05 06:03:51,175 - INFO - Epoch 51/100 - Train Loss: 0.1556 - Val Acc: 0.8696
2026-04-05 06:03:51,443 - INFO - Epoch 52/100 - Train Loss: 0.1561 - Val Acc: 0.8551
2026-04-05 06:03:51,716 - INFO - Epoch 53/100 - Train Loss: 0.1530 - Val Acc: 0.8406
2026-04-05 06:03:51,993 - INFO - Epoch 54/100 - Train Loss: 0.1520 - Val Acc: 0.8406
2026-04-05 06:03:52,290 - INFO - Epoch 55/100 - Train Loss: 0.1534 - Val Acc: 0.8551
2026-04-05 06:03:52,559 - INFO - Epoch 56/100 - Train Loss: 0.1491 - Val Acc: 0.8551
2026-04-05 06:03:52,833 - INFO - Epoch 57/100 - Train Loss: 0.1494 - Val Acc: 0.8406
2026-04-05 06:03:53,109 - INFO - Epoch 58/100 - Train Loss: 0.1536 - Val Acc: 0.8551
2026-04-05 06:03:53,383 - INFO - Epoch 59/100 - Train Loss: 0.1513 - Val Acc: 0.8551
2026-04-05 06:03:53,657 - INFO - Epoch 60/100 - Train Loss: 0.1497 - Val Acc: 0.8406
2026-04-05 06:03:53,927 - INFO - Epoch 61/100 - Train Loss: 0.1490 - Val Acc: 0.8551
2026-04-05 06:03:54,215 - INFO - Epoch 62/100 - Train Loss: 0.1425 - Val Acc: 0.8406
2026-04-05 06:03:54,497 - INFO - Epoch 63/100 - Train Loss: 0.1443 - Val Acc: 0.8406
2026-04-05 06:03:54,786 - INFO - Epoch 64/100 - Train Loss: 0.1470 - Val Acc: 0.8551
2026-04-05 06:03:55,064 - INFO - Epoch 65/100 - Train Loss: 0.1458 - Val Acc: 0.8551
2026-04-05 06:03:55,333 - INFO - Epoch 66/100 - Train Loss: 0.1485 - Val Acc: 0.8261
2026-04-05 06:03:55,605 - INFO - Epoch 67/100 - Train Loss: 0.1420 - Val Acc: 0.8406
2026-04-05 06:03:55,874 - INFO - Epoch 68/100 - Train Loss: 0.1429 - Val Acc: 0.8406
2026-04-05 06:03:56,153 - INFO - Epoch 69/100 - Train Loss: 0.1393 - Val Acc: 0.8406
2026-04-05 06:03:56,432 - INFO - Epoch 70/100 - Train Loss: 0.1394 - Val Acc: 0.8406
2026-04-05 06:03:56,707 - INFO - Epoch 71/100 - Train Loss: 0.1385 - Val Acc: 0.8406
2026-04-05 06:03:56,988 - INFO - Epoch 72/100 - Train Loss: 0.1400 - Val Acc: 0.8406
2026-04-05 06:03:57,263 - INFO - Epoch 73/100 - Train Loss: 0.1378 - Val Acc: 0.8406
2026-04-05 06:03:57,542 - INFO - Epoch 74/100 - Train Loss: 0.1403 - Val Acc: 0.8406
2026-04-05 06:03:57,814 - INFO - Epoch 75/100 - Train Loss: 0.1384 - Val Acc: 0.8406
2026-04-05 06:03:58,096 - INFO - Epoch 76/100 - Train Loss: 0.1391 - Val Acc: 0.8551
2026-04-05 06:03:58,379 - INFO - Epoch 77/100 - Train Loss: 0.1405 - Val Acc: 0.8551
2026-04-05 06:03:58,651 - INFO - Epoch 78/100 - Train Loss: 0.1351 - Val Acc: 0.8551
2026-04-05 06:03:58,932 - INFO - Epoch 79/100 - Train Loss: 0.1363 - Val Acc: 0.8551
2026-04-05 06:03:59,207 - INFO - Epoch 80/100 - Train Loss: 0.1339 - Val Acc: 0.8551
2026-04-05 06:03:59,475 - INFO - Epoch 81/100 - Train Loss: 0.1326 - Val Acc: 0.8551
2026-04-05 06:03:59,748 - INFO - Epoch 82/100 - Train Loss: 0.1326 - Val Acc: 0.8406
2026-04-05 06:04:00,020 - INFO - Epoch 83/100 - Train Loss: 0.1348 - Val Acc: 0.8406
2026-04-05 06:04:00,294 - INFO - Epoch 84/100 - Train Loss: 0.1345 - Val Acc: 0.8406
2026-04-05 06:04:00,567 - INFO - Epoch 85/100 - Train Loss: 0.1342 - Val Acc: 0.8406
2026-04-05 06:04:00,842 - INFO - Epoch 86/100 - Train Loss: 0.1312 - Val Acc: 0.8406
2026-04-05 06:04:01,122 - INFO - Epoch 87/100 - Train Loss: 0.1320 - Val Acc: 0.8551
2026-04-05 06:04:01,398 - INFO - Epoch 88/100 - Train Loss: 0.1329 - Val Acc: 0.8551
2026-04-05 06:04:01,665 - INFO - Epoch 89/100 - Train Loss: 0.1316 - Val Acc: 0.8551
2026-04-05 06:04:01,944 - INFO - Epoch 90/100 - Train Loss: 0.1281 - Val Acc: 0.8406
2026-04-05 06:04:02,219 - INFO - Epoch 91/100 - Train Loss: 0.1363 - Val Acc: 0.8261
2026-04-05 06:04:02,490 - INFO - Epoch 92/100 - Train Loss: 0.1346 - Val Acc: 0.8406
2026-04-05 06:04:02,768 - INFO - Epoch 93/100 - Train Loss: 0.1288 - Val Acc: 0.8406
2026-04-05 06:04:03,053 - INFO - Epoch 94/100 - Train Loss: 0.1281 - Val Acc: 0.8406
2026-04-05 06:04:03,323 - INFO - Epoch 95/100 - Train Loss: 0.1248 - Val Acc: 0.8406
2026-04-05 06:04:03,592 - INFO - Epoch 96/100 - Train Loss: 0.1280 - Val Acc: 0.8551
2026-04-05 06:04:03,874 - INFO - Epoch 97/100 - Train Loss: 0.1301 - Val Acc: 0.8696
2026-04-05 06:04:04,152 - INFO - Epoch 98/100 - Train Loss: 0.1290 - Val Acc: 0.8696
2026-04-05 06:04:04,448 - INFO - Epoch 99/100 - Train Loss: 0.1254 - Val Acc: 0.8406
2026-04-05 06:04:04,753 - INFO - Epoch 100/100 - Train Loss: 0.1240 - Val Acc: 0.8406
2026-04-05 06:04:05,126 - INFO - Fold 8 logically complete. Tensor memory bounds cleared cleanly.
2026-04-05 06:04:05,130 - INFO - Original class distribution: [345 276]
2026-04-05 06:04:05,131 - INFO - Training device bound securely to: cuda
2026-04-05 06:04:05,158 - INFO - After SMOTE-ENN deployment: [345 301]

Fold 9:   0%|          | 0/100 [00:00<?, ?it/s]

2026-04-05 06:04:05,451 - INFO - Epoch 1/100 - Train Loss: 0.5242 - Val Acc: 0.8406
2026-04-05 06:04:05,732 - INFO - Epoch 2/100 - Train Loss: 0.3251 - Val Acc: 0.8261
2026-04-05 06:04:06,004 - INFO - Epoch 3/100 - Train Loss: 0.2674 - Val Acc: 0.8406
2026-04-05 06:04:06,277 - INFO - Epoch 4/100 - Train Loss: 0.2450 - Val Acc: 0.8551
2026-04-05 06:04:06,565 - INFO - Epoch 5/100 - Train Loss: 0.2291 - Val Acc: 0.8406
2026-04-05 06:04:06,839 - INFO - Epoch 6/100 - Train Loss: 0.2157 - Val Acc: 0.8406
2026-04-05 06:04:07,125 - INFO - Epoch 7/100 - Train Loss: 0.2034 - Val Acc: 0.8116
2026-04-05 06:04:07,406 - INFO - Epoch 8/100 - Train Loss: 0.1958 - Val Acc: 0.8261
2026-04-05 06:04:07,682 - INFO - Epoch 9/100 - Train Loss: 0.1924 - Val Acc: 0.8116
2026-04-05 06:04:07,965 - INFO - Epoch 10/100 - Train Loss: 0.1866 - Val Acc: 0.8406
2026-04-05 06:04:08,243 - INFO - Epoch 11/100 - Train Loss: 0.1824 - Val Acc: 0.8261
2026-04-05 06:04:08,524 - INFO - Epoch 12/100 - Train Loss: 0.1777 - Val Acc: 0.8116
2026-04-05 06:04:08,803 - INFO - Epoch 13/100 - Train Loss: 0.1763 - Val Acc: 0.8116
2026-04-05 06:04:09,097 - INFO - Epoch 14/100 - Train Loss: 0.1727 - Val Acc: 0.8261
2026-04-05 06:04:09,383 - INFO - Epoch 15/100 - Train Loss: 0.1717 - Val Acc: 0.8116
2026-04-05 06:04:09,661 - INFO - Epoch 16/100 - Train Loss: 0.1706 - Val Acc: 0.8116
2026-04-05 06:04:09,935 - INFO - Epoch 17/100 - Train Loss: 0.1683 - Val Acc: 0.8261
2026-04-05 06:04:10,223 - INFO - Epoch 18/100 - Train Loss: 0.1691 - Val Acc: 0.8116
2026-04-05 06:04:10,504 - INFO - Epoch 19/100 - Train Loss: 0.1659 - Val Acc: 0.8261
2026-04-05 06:04:10,776 - INFO - Epoch 20/100 - Train Loss: 0.1656 - Val Acc: 0.8261
2026-04-05 06:04:11,051 - INFO - Epoch 21/100 - Train Loss: 0.1629 - Val Acc: 0.8261
2026-04-05 06:04:11,338 - INFO - Epoch 22/100 - Train Loss: 0.1610 - Val Acc: 0.8116
2026-04-05 06:04:11,614 - INFO - Epoch 23/100 - Train Loss: 0.1597 - Val Acc: 0.8261
2026-04-05 06:04:11,904 - INFO - Epoch 24/100 - Train Loss: 0.1601 - Val Acc: 0.8261
2026-04-05 06:04:12,186 - INFO - Epoch 25/100 - Train Loss: 0.1571 - Val Acc: 0.8116
2026-04-05 06:04:12,458 - INFO - Epoch 26/100 - Train Loss: 0.1585 - Val Acc: 0.8116
2026-04-05 06:04:12,740 - INFO - Epoch 27/100 - Train Loss: 0.1554 - Val Acc: 0.8261
2026-04-05 06:04:13,025 - INFO - Epoch 28/100 - Train Loss: 0.1544 - Val Acc: 0.8116
2026-04-05 06:04:13,321 - INFO - Epoch 29/100 - Train Loss: 0.1558 - Val Acc: 0.8116
2026-04-05 06:04:13,599 - INFO - Epoch 30/100 - Train Loss: 0.1524 - Val Acc: 0.8116
2026-04-05 06:04:13,878 - INFO - Epoch 31/100 - Train Loss: 0.1556 - Val Acc: 0.8116
2026-04-05 06:04:14,159 - INFO - Epoch 32/100 - Train Loss: 0.1511 - Val Acc: 0.8116
2026-04-05 06:04:14,438 - INFO - Epoch 33/100 - Train Loss: 0.1500 - Val Acc: 0.8116
2026-04-05 06:04:14,752 - INFO - Epoch 34/100 - Train Loss: 0.1497 - Val Acc: 0.8116
2026-04-05 06:04:15,044 - INFO - Epoch 35/100 - Train Loss: 0.1493 - Val Acc: 0.8116
2026-04-05 06:04:15,320 - INFO - Epoch 36/100 - Train Loss: 0.1481 - Val Acc: 0.8116
2026-04-05 06:04:15,595 - INFO - Epoch 37/100 - Train Loss: 0.1472 - Val Acc: 0.8116
2026-04-05 06:04:15,867 - INFO - Epoch 38/100 - Train Loss: 0.1453 - Val Acc: 0.8116
2026-04-05 06:04:16,145 - INFO - Epoch 39/100 - Train Loss: 0.1448 - Val Acc: 0.8116
2026-04-05 06:04:16,426 - INFO - Epoch 40/100 - Train Loss: 0.1480 - Val Acc: 0.8261
2026-04-05 06:04:16,726 - INFO - Epoch 41/100 - Train Loss: 0.1427 - Val Acc: 0.8261
2026-04-05 06:04:17,011 - INFO - Epoch 42/100 - Train Loss: 0.1425 - Val Acc: 0.8261
2026-04-05 06:04:17,296 - INFO - Epoch 43/100 - Train Loss: 0.1415 - Val Acc: 0.8261
2026-04-05 06:04:17,574 - INFO - Epoch 44/100 - Train Loss: 0.1408 - Val Acc: 0.8261
2026-04-05 06:04:17,860 - INFO - Epoch 45/100 - Train Loss: 0.1404 - Val Acc: 0.8261
2026-04-05 06:04:18,133 - INFO - Epoch 46/100 - Train Loss: 0.1408 - Val Acc: 0.8261
2026-04-05 06:04:18,441 - INFO - Epoch 47/100 - Train Loss: 0.1360 - Val Acc: 0.8261
2026-04-05 06:04:18,719 - INFO - Epoch 48/100 - Train Loss: 0.1364 - Val Acc: 0.8261
2026-04-05 06:04:19,004 - INFO - Epoch 49/100 - Train Loss: 0.1361 - Val Acc: 0.8261
2026-04-05 06:04:19,281 - INFO - Epoch 50/100 - Train Loss: 0.1369 - Val Acc: 0.8261
2026-04-05 06:04:19,563 - INFO - Epoch 51/100 - Train Loss: 0.1329 - Val Acc: 0.8261
2026-04-05 06:04:19,839 - INFO - Epoch 52/100 - Train Loss: 0.1336 - Val Acc: 0.8261
2026-04-05 06:04:20,136 - INFO - Epoch 53/100 - Train Loss: 0.1326 - Val Acc: 0.8116
2026-04-05 06:04:20,437 - INFO - Epoch 54/100 - Train Loss: 0.1343 - Val Acc: 0.8261
2026-04-05 06:04:20,717 - INFO - Epoch 55/100 - Train Loss: 0.1319 - Val Acc: 0.8261
2026-04-05 06:04:21,002 - INFO - Epoch 56/100 - Train Loss: 0.1304 - Val Acc: 0.8261
2026-04-05 06:04:21,289 - INFO - Epoch 57/100 - Train Loss: 0.1314 - Val Acc: 0.8261
2026-04-05 06:04:21,579 - INFO - Epoch 58/100 - Train Loss: 0.1324 - Val Acc: 0.8261
2026-04-05 06:04:21,852 - INFO - Epoch 59/100 - Train Loss: 0.1287 - Val Acc: 0.8261
2026-04-05 06:04:22,140 - INFO - Epoch 60/100 - Train Loss: 0.1319 - Val Acc: 0.8261
2026-04-05 06:04:22,420 - INFO - Epoch 61/100 - Train Loss: 0.1286 - Val Acc: 0.8261
2026-04-05 06:04:22,694 - INFO - Epoch 62/100 - Train Loss: 0.1291 - Val Acc: 0.8261
2026-04-05 06:04:22,962 - INFO - Epoch 63/100 - Train Loss: 0.1305 - Val Acc: 0.8261
2026-04-05 06:04:23,247 - INFO - Epoch 64/100 - Train Loss: 0.1259 - Val Acc: 0.8261
2026-04-05 06:04:23,531 - INFO - Epoch 65/100 - Train Loss: 0.1283 - Val Acc: 0.8261
2026-04-05 06:04:23,812 - INFO - Epoch 66/100 - Train Loss: 0.1251 - Val Acc: 0.8261
2026-04-05 06:04:24,103 - INFO - Epoch 67/100 - Train Loss: 0.1253 - Val Acc: 0.8261
2026-04-05 06:04:24,389 - INFO - Epoch 68/100 - Train Loss: 0.1255 - Val Acc: 0.8116
2026-04-05 06:04:24,698 - INFO - Epoch 69/100 - Train Loss: 0.1247 - Val Acc: 0.7971
2026-04-05 06:04:24,981 - INFO - Epoch 70/100 - Train Loss: 0.1216 - Val Acc: 0.7971
2026-04-05 06:04:25,260 - INFO - Epoch 71/100 - Train Loss: 0.1218 - Val Acc: 0.8116
2026-04-05 06:04:25,539 - INFO - Epoch 72/100 - Train Loss: 0.1215 - Val Acc: 0.7971
2026-04-05 06:04:25,834 - INFO - Epoch 73/100 - Train Loss: 0.1242 - Val Acc: 0.8116
2026-04-05 06:04:26,113 - INFO - Epoch 74/100 - Train Loss: 0.1190 - Val Acc: 0.7971
2026-04-05 06:04:26,399 - INFO - Epoch 75/100 - Train Loss: 0.1223 - Val Acc: 0.8116
2026-04-05 06:04:26,691 - INFO - Epoch 76/100 - Train Loss: 0.1173 - Val Acc: 0.7971
2026-04-05 06:04:26,994 - INFO - Epoch 77/100 - Train Loss: 0.1151 - Val Acc: 0.8116
2026-04-05 06:04:27,281 - INFO - Epoch 78/100 - Train Loss: 0.1189 - Val Acc: 0.8116
2026-04-05 06:04:27,561 - INFO - Epoch 79/100 - Train Loss: 0.1163 - Val Acc: 0.8116
2026-04-05 06:04:27,852 - INFO - Epoch 80/100 - Train Loss: 0.1175 - Val Acc: 0.7971
2026-04-05 06:04:28,139 - INFO - Epoch 81/100 - Train Loss: 0.1142 - Val Acc: 0.8116
2026-04-05 06:04:28,420 - INFO - Epoch 82/100 - Train Loss: 0.1149 - Val Acc: 0.7971
2026-04-05 06:04:28,693 - INFO - Epoch 83/100 - Train Loss: 0.1161 - Val Acc: 0.7971
2026-04-05 06:04:28,967 - INFO - Epoch 84/100 - Train Loss: 0.1150 - Val Acc: 0.7971
2026-04-05 06:04:29,249 - INFO - Epoch 85/100 - Train Loss: 0.1158 - Val Acc: 0.7971
2026-04-05 06:04:29,527 - INFO - Epoch 86/100 - Train Loss: 0.1140 - Val Acc: 0.7971
2026-04-05 06:04:29,805 - INFO - Epoch 87/100 - Train Loss: 0.1172 - Val Acc: 0.7826
2026-04-05 06:04:30,081 - INFO - Epoch 88/100 - Train Loss: 0.1125 - Val Acc: 0.7826
2026-04-05 06:04:30,364 - INFO - Epoch 89/100 - Train Loss: 0.1168 - Val Acc: 0.7826
2026-04-05 06:04:30,644 - INFO - Epoch 90/100 - Train Loss: 0.1106 - Val Acc: 0.7971
2026-04-05 06:04:30,925 - INFO - Epoch 91/100 - Train Loss: 0.1118 - Val Acc: 0.8116
2026-04-05 06:04:31,207 - INFO - Epoch 92/100 - Train Loss: 0.1135 - Val Acc: 0.8116
2026-04-05 06:04:31,487 - INFO - Epoch 93/100 - Train Loss: 0.1117 - Val Acc: 0.7971
2026-04-05 06:04:31,766 - INFO - Epoch 94/100 - Train Loss: 0.1107 - Val Acc: 0.7971
2026-04-05 06:04:32,063 - INFO - Epoch 95/100 - Train Loss: 0.1142 - Val Acc: 0.8116
2026-04-05 06:04:32,356 - INFO - Epoch 96/100 - Train Loss: 0.1126 - Val Acc: 0.8116
2026-04-05 06:04:32,638 - INFO - Epoch 97/100 - Train Loss: 0.1105 - Val Acc: 0.8116
2026-04-05 06:04:32,916 - INFO - Epoch 98/100 - Train Loss: 0.1084 - Val Acc: 0.7971
2026-04-05 06:04:33,194 - INFO - Epoch 99/100 - Train Loss: 0.1046 - Val Acc: 0.8116
2026-04-05 06:04:33,481 - INFO - Epoch 100/100 - Train Loss: 0.1091 - Val Acc: 0.7971
2026-04-05 06:04:33,854 - INFO - Fold 9 logically complete. Tensor memory bounds cleared cleanly.
2026-04-05 06:04:33,858 - INFO - Original class distribution: [345 276]
2026-04-05 06:04:33,858 - INFO - Training device bound securely to: cuda
2026-04-05 06:04:33,889 - INFO - After SMOTE-ENN deployment: [345 296]

Fold 10:   0%|          | 0/100 [00:00<?, ?it/s]

2026-04-05 06:04:34,216 - INFO - Epoch 1/100 - Train Loss: 0.5267 - Val Acc: 0.8841
2026-04-05 06:04:34,521 - INFO - Epoch 2/100 - Train Loss: 0.3250 - Val Acc: 0.8986
2026-04-05 06:04:34,812 - INFO - Epoch 3/100 - Train Loss: 0.2738 - Val Acc: 0.8986
2026-04-05 06:04:35,111 - INFO - Epoch 4/100 - Train Loss: 0.2482 - Val Acc: 0.8986
2026-04-05 06:04:35,381 - INFO - Epoch 5/100 - Train Loss: 0.2325 - Val Acc: 0.8986
2026-04-05 06:04:35,652 - INFO - Epoch 6/100 - Train Loss: 0.2218 - Val Acc: 0.8986
2026-04-05 06:04:35,925 - INFO - Epoch 7/100 - Train Loss: 0.2144 - Val Acc: 0.9130
2026-04-05 06:04:36,214 - INFO - Epoch 8/100 - Train Loss: 0.2066 - Val Acc: 0.9130
2026-04-05 06:04:36,499 - INFO - Epoch 9/100 - Train Loss: 0.2000 - Val Acc: 0.9130
2026-04-05 06:04:36,778 - INFO - Epoch 10/100 - Train Loss: 0.1947 - Val Acc: 0.9130
2026-04-05 06:04:37,063 - INFO - Epoch 11/100 - Train Loss: 0.1926 - Val Acc: 0.9130
2026-04-05 06:04:37,338 - INFO - Epoch 12/100 - Train Loss: 0.1876 - Val Acc: 0.9130
2026-04-05 06:04:37,629 - INFO - Epoch 13/100 - Train Loss: 0.1859 - Val Acc: 0.9130
2026-04-05 06:04:37,913 - INFO - Epoch 14/100 - Train Loss: 0.1835 - Val Acc: 0.9130
2026-04-05 06:04:38,187 - INFO - Epoch 15/100 - Train Loss: 0.1811 - Val Acc: 0.9420
2026-04-05 06:04:38,459 - INFO - Epoch 16/100 - Train Loss: 0.1799 - Val Acc: 0.9275
2026-04-05 06:04:38,736 - INFO - Epoch 17/100 - Train Loss: 0.1761 - Val Acc: 0.9420
2026-04-05 06:04:39,013 - INFO - Epoch 18/100 - Train Loss: 0.1759 - Val Acc: 0.9420
2026-04-05 06:04:39,299 - INFO - Epoch 19/100 - Train Loss: 0.1757 - Val Acc: 0.9420
2026-04-05 06:04:39,585 - INFO - Epoch 20/100 - Train Loss: 0.1731 - Val Acc: 0.9420
2026-04-05 06:04:39,865 - INFO - Epoch 21/100 - Train Loss: 0.1723 - Val Acc: 0.9420
2026-04-05 06:04:40,157 - INFO - Epoch 22/100 - Train Loss: 0.1730 - Val Acc: 0.9420
2026-04-05 06:04:40,422 - INFO - Epoch 23/100 - Train Loss: 0.1690 - Val Acc: 0.9420
2026-04-05 06:04:40,698 - INFO - Epoch 24/100 - Train Loss: 0.1674 - Val Acc: 0.9420
2026-04-05 06:04:40,976 - INFO - Epoch 25/100 - Train Loss: 0.1659 - Val Acc: 0.9420
2026-04-05 06:04:41,263 - INFO - Epoch 26/100 - Train Loss: 0.1692 - Val Acc: 0.9420
2026-04-05 06:04:41,538 - INFO - Epoch 27/100 - Train Loss: 0.1647 - Val Acc: 0.9420
2026-04-05 06:04:41,819 - INFO - Epoch 28/100 - Train Loss: 0.1646 - Val Acc: 0.9420
2026-04-05 06:04:42,095 - INFO - Epoch 29/100 - Train Loss: 0.1632 - Val Acc: 0.9565
2026-04-05 06:04:42,369 - INFO - Epoch 30/100 - Train Loss: 0.1620 - Val Acc: 0.9565
2026-04-05 06:04:42,656 - INFO - Epoch 31/100 - Train Loss: 0.1618 - Val Acc: 0.9420
2026-04-05 06:04:42,931 - INFO - Epoch 32/100 - Train Loss: 0.1618 - Val Acc: 0.9420
2026-04-05 06:04:43,220 - INFO - Epoch 33/100 - Train Loss: 0.1559 - Val Acc: 0.9275
2026-04-05 06:04:43,492 - INFO - Epoch 34/100 - Train Loss: 0.1558 - Val Acc: 0.9275
2026-04-05 06:04:43,772 - INFO - Epoch 35/100 - Train Loss: 0.1565 - Val Acc: 0.9275
2026-04-05 06:04:44,052 - INFO - Epoch 36/100 - Train Loss: 0.1546 - Val Acc: 0.9420
2026-04-05 06:04:44,328 - INFO - Epoch 37/100 - Train Loss: 0.1566 - Val Acc: 0.9420
2026-04-05 06:04:44,637 - INFO - Epoch 38/100 - Train Loss: 0.1543 - Val Acc: 0.9275
2026-04-05 06:04:44,922 - INFO - Epoch 39/100 - Train Loss: 0.1523 - Val Acc: 0.9275
2026-04-05 06:04:45,207 - INFO - Epoch 40/100 - Train Loss: 0.1489 - Val Acc: 0.9275
2026-04-05 06:04:45,490 - INFO - Epoch 41/100 - Train Loss: 0.1494 - Val Acc: 0.9420
2026-04-05 06:04:45,772 - INFO - Epoch 42/100 - Train Loss: 0.1538 - Val Acc: 0.9420
2026-04-05 06:04:46,040 - INFO - Epoch 43/100 - Train Loss: 0.1511 - Val Acc: 0.9420
2026-04-05 06:04:46,327 - INFO - Epoch 44/100 - Train Loss: 0.1465 - Val Acc: 0.9420
2026-04-05 06:04:46,599 - INFO - Epoch 45/100 - Train Loss: 0.1454 - Val Acc: 0.9420
2026-04-05 06:04:46,883 - INFO - Epoch 46/100 - Train Loss: 0.1458 - Val Acc: 0.9275
2026-04-05 06:04:47,156 - INFO - Epoch 47/100 - Train Loss: 0.1487 - Val Acc: 0.9275
2026-04-05 06:04:47,445 - INFO - Epoch 48/100 - Train Loss: 0.1461 - Val Acc: 0.9275
2026-04-05 06:04:47,727 - INFO - Epoch 49/100 - Train Loss: 0.1433 - Val Acc: 0.9420
2026-04-05 06:04:48,000 - INFO - Epoch 50/100 - Train Loss: 0.1429 - Val Acc: 0.9420
2026-04-05 06:04:48,290 - INFO - Epoch 51/100 - Train Loss: 0.1436 - Val Acc: 0.9420
2026-04-05 06:04:48,570 - INFO - Epoch 52/100 - Train Loss: 0.1440 - Val Acc: 0.9420
2026-04-05 06:04:48,846 - INFO - Epoch 53/100 - Train Loss: 0.1446 - Val Acc: 0.9275
2026-04-05 06:04:49,132 - INFO - Epoch 54/100 - Train Loss: 0.1407 - Val Acc: 0.9275
2026-04-05 06:04:49,406 - INFO - Epoch 55/100 - Train Loss: 0.1404 - Val Acc: 0.9275
2026-04-05 06:04:49,684 - INFO - Epoch 56/100 - Train Loss: 0.1397 - Val Acc: 0.9275
2026-04-05 06:04:49,956 - INFO - Epoch 57/100 - Train Loss: 0.1372 - Val Acc: 0.9420
2026-04-05 06:04:50,232 - INFO - Epoch 58/100 - Train Loss: 0.1411 - Val Acc: 0.9420
2026-04-05 06:04:50,504 - INFO - Epoch 59/100 - Train Loss: 0.1386 - Val Acc: 0.9420
2026-04-05 06:04:50,794 - INFO - Epoch 60/100 - Train Loss: 0.1373 - Val Acc: 0.9420
2026-04-05 06:04:51,064 - INFO - Epoch 61/100 - Train Loss: 0.1365 - Val Acc: 0.9420
2026-04-05 06:04:51,347 - INFO - Epoch 62/100 - Train Loss: 0.1358 - Val Acc: 0.9275
2026-04-05 06:04:51,620 - INFO - Epoch 63/100 - Train Loss: 0.1368 - Val Acc: 0.9275
2026-04-05 06:04:51,897 - INFO - Epoch 64/100 - Train Loss: 0.1333 - Val Acc: 0.9275
2026-04-05 06:04:52,175 - INFO - Epoch 65/100 - Train Loss: 0.1341 - Val Acc: 0.9275
2026-04-05 06:04:52,472 - INFO - Epoch 66/100 - Train Loss: 0.1330 - Val Acc: 0.9275
2026-04-05 06:04:52,754 - INFO - Epoch 67/100 - Train Loss: 0.1314 - Val Acc: 0.9275
2026-04-05 06:04:53,032 - INFO - Epoch 68/100 - Train Loss: 0.1332 - Val Acc: 0.9275
2026-04-05 06:04:53,322 - INFO - Epoch 69/100 - Train Loss: 0.1327 - Val Acc: 0.9275
2026-04-05 06:04:53,604 - INFO - Epoch 70/100 - Train Loss: 0.1335 - Val Acc: 0.9275
2026-04-05 06:04:53,880 - INFO - Epoch 71/100 - Train Loss: 0.1310 - Val Acc: 0.9275
2026-04-05 06:04:54,159 - INFO - Epoch 72/100 - Train Loss: 0.1302 - Val Acc: 0.9275
2026-04-05 06:04:54,458 - INFO - Epoch 73/100 - Train Loss: 0.1310 - Val Acc: 0.9275
2026-04-05 06:04:54,798 - INFO - Epoch 74/100 - Train Loss: 0.1315 - Val Acc: 0.9275
2026-04-05 06:04:55,082 - INFO - Epoch 75/100 - Train Loss: 0.1266 - Val Acc: 0.9275
2026-04-05 06:04:55,367 - INFO - Epoch 76/100 - Train Loss: 0.1265 - Val Acc: 0.9130
2026-04-05 06:04:55,655 - INFO - Epoch 77/100 - Train Loss: 0.1244 - Val Acc: 0.9420
2026-04-05 06:04:55,949 - INFO - Epoch 78/100 - Train Loss: 0.1315 - Val Acc: 0.9420
2026-04-05 06:04:56,235 - INFO - Epoch 79/100 - Train Loss: 0.1277 - Val Acc: 0.9420
2026-04-05 06:04:56,515 - INFO - Epoch 80/100 - Train Loss: 0.1278 - Val Acc: 0.9420
2026-04-05 06:04:56,796 - INFO - Epoch 81/100 - Train Loss: 0.1250 - Val Acc: 0.9130
2026-04-05 06:04:57,099 - INFO - Epoch 82/100 - Train Loss: 0.1248 - Val Acc: 0.9130
2026-04-05 06:04:57,373 - INFO - Epoch 83/100 - Train Loss: 0.1253 - Val Acc: 0.9130
2026-04-05 06:04:57,645 - INFO - Epoch 84/100 - Train Loss: 0.1232 - Val Acc: 0.9130
2026-04-05 06:04:57,911 - INFO - Epoch 85/100 - Train Loss: 0.1222 - Val Acc: 0.9130
2026-04-05 06:04:58,191 - INFO - Epoch 86/100 - Train Loss: 0.1229 - Val Acc: 0.9130
2026-04-05 06:04:58,477 - INFO - Epoch 87/100 - Train Loss: 0.1253 - Val Acc: 0.9130
2026-04-05 06:04:58,756 - INFO - Epoch 88/100 - Train Loss: 0.1216 - Val Acc: 0.9130
2026-04-05 06:04:59,027 - INFO - Epoch 89/100 - Train Loss: 0.1220 - Val Acc: 0.9420
2026-04-05 06:04:59,305 - INFO - Epoch 90/100 - Train Loss: 0.1248 - Val Acc: 0.9420
2026-04-05 06:04:59,585 - INFO - Epoch 91/100 - Train Loss: 0.1227 - Val Acc: 0.9420
2026-04-05 06:04:59,861 - INFO - Epoch 92/100 - Train Loss: 0.1193 - Val Acc: 0.9420
2026-04-05 06:05:00,144 - INFO - Epoch 93/100 - Train Loss: 0.1196 - Val Acc: 0.9275
2026-04-05 06:05:00,420 - INFO - Epoch 94/100 - Train Loss: 0.1205 - Val Acc: 0.9275
2026-04-05 06:05:00,693 - INFO - Epoch 95/100 - Train Loss: 0.1207 - Val Acc: 0.9275
2026-04-05 06:05:00,964 - INFO - Epoch 96/100 - Train Loss: 0.1184 - Val Acc: 0.9275
2026-04-05 06:05:01,236 - INFO - Epoch 97/100 - Train Loss: 0.1166 - Val Acc: 0.9275
2026-04-05 06:05:01,529 - INFO - Epoch 98/100 - Train Loss: 0.1210 - Val Acc: 0.9420
2026-04-05 06:05:01,804 - INFO - Epoch 99/100 - Train Loss: 0.1206 - Val Acc: 0.9275
2026-04-05 06:05:02,076 - INFO - Epoch 100/100 - Train Loss: 0.1144 - Val Acc: 0.8841
2026-04-05 06:05:02,440 - INFO - Fold 10 logically complete. Tensor memory bounds cleared cleanly.
2026-04-05 06:05:02,457 - INFO - ✓ Completed LSTM_smoteenn -> Acc: 0.8812
2026-04-05 06:05:02,458 - INFO -
EXPERIMENT: GRU_BASELINE | australian | SMOTE-ENN: False

Australian | GRU | BASELINE:   0%|          | 0/10 [00:00<?, ?it/s]

2026-04-05 06:05:02,473 - INFO - Original class distribution: [344 277]
2026-04-05 06:05:02,473 - INFO - Training device bound securely to: cuda

Fold 1:   0%|          | 0/100 [00:00<?, ?it/s]

2026-04-05 06:05:02,793 - INFO - Epoch 1/100 - Train Loss: 0.6620 - Val Acc: 0.8261
2026-04-05 06:05:03,077 - INFO - Epoch 2/100 - Train Loss: 0.5871 - Val Acc: 0.8406
2026-04-05 06:05:03,340 - INFO - Epoch 3/100 - Train Loss: 0.5150 - Val Acc: 0.8406
2026-04-05 06:05:03,610 - INFO - Epoch 4/100 - Train Loss: 0.4554 - Val Acc: 0.8406
2026-04-05 06:05:03,878 - INFO - Epoch 5/100 - Train Loss: 0.4096 - Val Acc: 0.8696
2026-04-05 06:05:04,153 - INFO - Epoch 6/100 - Train Loss: 0.3858 - Val Acc: 0.8841
2026-04-05 06:05:04,436 - INFO - Epoch 7/100 - Train Loss: 0.3682 - Val Acc: 0.8841
2026-04-05 06:05:04,725 - INFO - Epoch 8/100 - Train Loss: 0.3556 - Val Acc: 0.8841
2026-04-05 06:05:05,005 - INFO - Epoch 9/100 - Train Loss: 0.3466 - Val Acc: 0.8986
2026-04-05 06:05:05,278 - INFO - Epoch 10/100 - Train Loss: 0.3382 - Val Acc: 0.8986
2026-04-05 06:05:05,542 - INFO - Epoch 11/100 - Train Loss: 0.3325 - Val Acc: 0.8986
2026-04-05 06:05:05,824 - INFO - Epoch 12/100 - Train Loss: 0.3284 - Val Acc: 0.8986
2026-04-05 06:05:06,097 - INFO - Epoch 13/100 - Train Loss: 0.3233 - Val Acc: 0.8986
2026-04-05 06:05:06,370 - INFO - Epoch 14/100 - Train Loss: 0.3185 - Val Acc: 0.8986
2026-04-05 06:05:06,637 - INFO - Epoch 15/100 - Train Loss: 0.3148 - Val Acc: 0.8986
2026-04-05 06:05:06,910 - INFO - Epoch 16/100 - Train Loss: 0.3136 - Val Acc: 0.8986
2026-04-05 06:05:07,189 - INFO - Epoch 17/100 - Train Loss: 0.3114 - Val Acc: 0.8986
2026-04-05 06:05:07,455 - INFO - Epoch 18/100 - Train Loss: 0.3109 - Val Acc: 0.8986
2026-04-05 06:05:07,716 - INFO - Epoch 19/100 - Train Loss: 0.3095 - Val Acc: 0.8986
2026-04-05 06:05:07,981 - INFO - Epoch 20/100 - Train Loss: 0.3076 - Val Acc: 0.8986
2026-04-05 06:05:08,258 - INFO - Epoch 21/100 - Train Loss: 0.3051 - Val Acc: 0.8986
2026-04-05 06:05:08,540 - INFO - Epoch 22/100 - Train Loss: 0.3042 - Val Acc: 0.8986
2026-04-05 06:05:08,818 - INFO - Epoch 23/100 - Train Loss: 0.3038 - Val Acc: 0.8986
2026-04-05 06:05:09,100 - INFO - Epoch 24/100 - Train Loss: 0.3033 - Val Acc: 0.8986
2026-04-05 06:05:09,369 - INFO - Epoch 25/100 - Train Loss: 0.3031 - Val Acc: 0.8986
2026-04-05 06:05:09,625 - INFO - Epoch 26/100 - Train Loss: 0.3035 - Val Acc: 0.8986
2026-04-05 06:05:09,887 - INFO - Epoch 27/100 - Train Loss: 0.3040 - Val Acc: 0.8986
2026-04-05 06:05:10,159 - INFO - Epoch 28/100 - Train Loss: 0.3013 - Val Acc: 0.8986
2026-04-05 06:05:10,434 - INFO - Epoch 29/100 - Train Loss: 0.2998 - Val Acc: 0.9130
2026-04-05 06:05:10,713 - INFO - Epoch 30/100 - Train Loss: 0.2965 - Val Acc: 0.9130
2026-04-05 06:05:10,980 - INFO - Epoch 31/100 - Train Loss: 0.2988 - Val Acc: 0.9130
2026-04-05 06:05:11,250 - INFO - Epoch 32/100 - Train Loss: 0.2957 - Val Acc: 0.9130
2026-04-05 06:05:11,522 - INFO - Epoch 33/100 - Train Loss: 0.2962 - Val Acc: 0.9130
2026-04-05 06:05:11,789 - INFO - Epoch 34/100 - Train Loss: 0.2948 - Val Acc: 0.8986
2026-04-05 06:05:12,051 - INFO - Epoch 35/100 - Train Loss: 0.2948 - Val Acc: 0.9130
2026-04-05 06:05:12,326 - INFO - Epoch 36/100 - Train Loss: 0.2915 - Val Acc: 0.9130
2026-04-05 06:05:12,598 - INFO - Epoch 37/100 - Train Loss: 0.2914 - Val Acc: 0.9130
2026-04-05 06:05:12,876 - INFO - Epoch 38/100 - Train Loss: 0.2883 - Val Acc: 0.9130
2026-04-05 06:05:13,148 - INFO - Epoch 39/100 - Train Loss: 0.2890 - Val Acc: 0.9130
2026-04-05 06:05:13,420 - INFO - Epoch 40/100 - Train Loss: 0.2884 - Val Acc: 0.9130
2026-04-05 06:05:13,689 - INFO - Epoch 41/100 - Train Loss: 0.2868 - Val Acc: 0.9130
2026-04-05 06:05:13,972 - INFO - Epoch 42/100 - Train Loss: 0.2845 - Val Acc: 0.9130
2026-04-05 06:05:14,248 - INFO - Epoch 43/100 - Train Loss: 0.2840 - Val Acc: 0.9130
2026-04-05 06:05:14,543 - INFO - Epoch 44/100 - Train Loss: 0.2845 - Val Acc: 0.9130
2026-04-05 06:05:14,824 - INFO - Epoch 45/100 - Train Loss: 0.2832 - Val Acc: 0.9130
2026-04-05 06:05:15,123 - INFO - Epoch 46/100 - Train Loss: 0.2832 - Val Acc: 0.9130
2026-04-05 06:05:15,401 - INFO - Epoch 47/100 - Train Loss: 0.2834 - Val Acc: 0.9130
2026-04-05 06:05:15,667 - INFO - Epoch 48/100 - Train Loss: 0.2791 - Val Acc: 0.9130
2026-04-05 06:05:15,932 - INFO - Epoch 49/100 - Train Loss: 0.2811 - Val Acc: 0.9130
2026-04-05 06:05:16,202 - INFO - Epoch 50/100 - Train Loss: 0.2770 - Val Acc: 0.9130
2026-04-05 06:05:16,473 - INFO - Epoch 51/100 - Train Loss: 0.2749 - Val Acc: 0.9130
2026-04-05 06:05:16,753 - INFO - Epoch 52/100 - Train Loss: 0.2772 - Val Acc: 0.9130
2026-04-05 06:05:17,037 - INFO - Epoch 53/100 - Train Loss: 0.2739 - Val Acc: 0.9130
2026-04-05 06:05:17,318 - INFO - Epoch 54/100 - Train Loss: 0.2741 - Val Acc: 0.9130
2026-04-05 06:05:17,598 - INFO - Epoch 55/100 - Train Loss: 0.2709 - Val Acc: 0.9130
2026-04-05 06:05:17,855 - INFO - Epoch 56/100 - Train Loss: 0.2694 - Val Acc: 0.9130
2026-04-05 06:05:18,121 - INFO - Epoch 57/100 - Train Loss: 0.2698 - Val Acc: 0.9130
2026-04-05 06:05:18,399 - INFO - Epoch 58/100 - Train Loss: 0.2726 - Val Acc: 0.9130
2026-04-05 06:05:18,672 - INFO - Epoch 59/100 - Train Loss: 0.2661 - Val Acc: 0.9130
2026-04-05 06:05:18,945 - INFO - Epoch 60/100 - Train Loss: 0.2692 - Val Acc: 0.9130
2026-04-05 06:05:19,215 - INFO - Epoch 61/100 - Train Loss: 0.2667 - Val Acc: 0.9130
2026-04-05 06:05:19,490 - INFO - Epoch 62/100 - Train Loss: 0.2667 - Val Acc: 0.9130
2026-04-05 06:05:19,766 - INFO - Epoch 63/100 - Train Loss: 0.2645 - Val Acc: 0.8986
2026-04-05 06:05:20,045 - INFO - Epoch 64/100 - Train Loss: 0.2658 - Val Acc: 0.8986
2026-04-05 06:05:20,321 - INFO - Epoch 65/100 - Train Loss: 0.2638 - Val Acc: 0.8841
2026-04-05 06:05:20,594 - INFO - Epoch 66/100 - Train Loss: 0.2591 - Val Acc: 0.8986
2026-04-05 06:05:20,857 - INFO - Epoch 67/100 - Train Loss: 0.2649 - Val Acc: 0.8986
2026-04-05 06:05:21,120 - INFO - Epoch 68/100 - Train Loss: 0.2586 - Val Acc: 0.8986
2026-04-05 06:05:21,392 - INFO - Epoch 69/100 - Train Loss: 0.2587 - Val Acc: 0.8986
2026-04-05 06:05:21,672 - INFO - Epoch 70/100 - Train Loss: 0.2551 - Val Acc: 0.8986
2026-04-05 06:05:21,955 - INFO - Epoch 71/100 - Train Loss: 0.2598 - Val Acc: 0.8986
2026-04-05 06:05:22,239 - INFO - Epoch 72/100 - Train Loss: 0.2557 - Val Acc: 0.8986
2026-04-05 06:05:22,515 - INFO - Epoch 73/100 - Train Loss: 0.2518 - Val Acc: 0.8841
2026-04-05 06:05:22,792 - INFO - Epoch 74/100 - Train Loss: 0.2537 - Val Acc: 0.8841
2026-04-05 06:05:23,057 - INFO - Epoch 75/100 - Train Loss: 0.2564 - Val Acc: 0.8841
2026-04-05 06:05:23,334 - INFO - Epoch 76/100 - Train Loss: 0.2570 - Val Acc: 0.8986
2026-04-05 06:05:23,601 - INFO - Epoch 77/100 - Train Loss: 0.2494 - Val Acc: 0.8986
2026-04-05 06:05:23,865 - INFO - Epoch 78/100 - Train Loss: 0.2548 - Val Acc: 0.8841
2026-04-05 06:05:24,133 - INFO - Epoch 79/100 - Train Loss: 0.2527 - Val Acc: 0.8986
2026-04-05 06:05:24,412 - INFO - Epoch 80/100 - Train Loss: 0.2501 - Val Acc: 0.8986
2026-04-05 06:05:24,719 - INFO - Epoch 81/100 - Train Loss: 0.2496 - Val Acc: 0.8841
2026-04-05 06:05:24,985 - INFO - Epoch 82/100 - Train Loss: 0.2484 - Val Acc: 0.8841
2026-04-05 06:05:25,261 - INFO - Epoch 83/100 - Train Loss: 0.2455 - Val Acc: 0.8841
2026-04-05 06:05:25,530 - INFO - Epoch 84/100 - Train Loss: 0.2440 - Val Acc: 0.8841
2026-04-05 06:05:25,812 - INFO - Epoch 85/100 - Train Loss: 0.2484 - Val Acc: 0.8841
2026-04-05 06:05:26,089 - INFO - Epoch 86/100 - Train Loss: 0.2505 - Val Acc: 0.8841
2026-04-05 06:05:26,365 - INFO - Epoch 87/100 - Train Loss: 0.2491 - Val Acc: 0.8841
2026-04-05 06:05:26,626 - INFO - Epoch 88/100 - Train Loss: 0.2435 - Val Acc: 0.8841
2026-04-05 06:05:26,884 - INFO - Epoch 89/100 - Train Loss: 0.2418 - Val Acc: 0.8841
2026-04-05 06:05:27,164 - INFO - Epoch 90/100 - Train Loss: 0.2455 - Val Acc: 0.8841
2026-04-05 06:05:27,440 - INFO - Epoch 91/100 - Train Loss: 0.2415 - Val Acc: 0.8986
2026-04-05 06:05:27,731 - INFO - Epoch 92/100 - Train Loss: 0.2401 - Val Acc: 0.8841
2026-04-05 06:05:27,988 - INFO - Epoch 93/100 - Train Loss: 0.2398 - Val Acc: 0.8841
2026-04-05 06:05:28,256 - INFO - Epoch 94/100 - Train Loss: 0.2394 - Val Acc: 0.8841
2026-04-05 06:05:28,521 - INFO - Epoch 95/100 - Train Loss: 0.2370 - Val Acc: 0.8841
2026-04-05 06:05:28,812 - INFO - Epoch 96/100 - Train Loss: 0.2382 - Val Acc: 0.8841
2026-04-05 06:05:29,087 - INFO - Epoch 97/100 - Train Loss: 0.2418 - Val Acc: 0.8841
2026-04-05 06:05:29,378 - INFO - Epoch 98/100 - Train Loss: 0.2431 - Val Acc: 0.8841
2026-04-05 06:05:29,645 - INFO - Epoch 99/100 - Train Loss: 0.2397 - Val Acc: 0.8841
2026-04-05 06:05:29,913 - INFO - Epoch 100/100 - Train Loss: 0.2389 - Val Acc: 0.8841
2026-04-05 06:05:30,284 - INFO - Fold 1 logically complete. Tensor memory bounds cleared cleanly.
2026-04-05 06:05:30,289 - INFO - Original class distribution: [344 277]
2026-04-05 06:05:30,290 - INFO - Training device bound securely to: cuda

Fold 2:   0%|          | 0/100 [00:00<?, ?it/s]

2026-04-05 06:05:30,606 - INFO - Epoch 1/100 - Train Loss: 0.6508 - Val Acc: 0.7971
2026-04-05 06:05:30,883 - INFO - Epoch 2/100 - Train Loss: 0.5711 - Val Acc: 0.7681
2026-04-05 06:05:31,145 - INFO - Epoch 3/100 - Train Loss: 0.4966 - Val Acc: 0.7681
2026-04-05 06:05:31,417 - INFO - Epoch 4/100 - Train Loss: 0.4375 - Val Acc: 0.7681
2026-04-05 06:05:31,688 - INFO - Epoch 5/100 - Train Loss: 0.3979 - Val Acc: 0.7681
2026-04-05 06:05:31,952 - INFO - Epoch 6/100 - Train Loss: 0.3732 - Val Acc: 0.7826
2026-04-05 06:05:32,228 - INFO - Epoch 7/100 - Train Loss: 0.3576 - Val Acc: 0.7971
2026-04-05 06:05:32,507 - INFO - Epoch 8/100 - Train Loss: 0.3478 - Val Acc: 0.8116
2026-04-05 06:05:32,770 - INFO - Epoch 9/100 - Train Loss: 0.3391 - Val Acc: 0.8261
2026-04-05 06:05:33,033 - INFO - Epoch 10/100 - Train Loss: 0.3320 - Val Acc: 0.8406
2026-04-05 06:05:33,293 - INFO - Epoch 11/100 - Train Loss: 0.3237 - Val Acc: 0.8551
2026-04-05 06:05:33,552 - INFO - Epoch 12/100 - Train Loss: 0.3177 - Val Acc: 0.8551
2026-04-05 06:05:33,824 - INFO - Epoch 13/100 - Train Loss: 0.3146 - Val Acc: 0.8696
2026-04-05 06:05:34,088 - INFO - Epoch 14/100 - Train Loss: 0.3127 - Val Acc: 0.8841
2026-04-05 06:05:34,364 - INFO - Epoch 15/100 - Train Loss: 0.3084 - Val Acc: 0.8841
2026-04-05 06:05:34,666 - INFO - Epoch 16/100 - Train Loss: 0.3061 - Val Acc: 0.8986
2026-04-05 06:05:34,938 - INFO - Epoch 17/100 - Train Loss: 0.3066 - Val Acc: 0.8986
2026-04-05 06:05:35,212 - INFO - Epoch 18/100 - Train Loss: 0.3032 - Val Acc: 0.8986
2026-04-05 06:05:35,476 - INFO - Epoch 19/100 - Train Loss: 0.3026 - Val Acc: 0.8986
2026-04-05 06:05:35,749 - INFO - Epoch 20/100 - Train Loss: 0.2999 - Val Acc: 0.8986
2026-04-05 06:05:36,012 - INFO - Epoch 21/100 - Train Loss: 0.3002 - Val Acc: 0.8986
2026-04-05 06:05:36,281 - INFO - Epoch 22/100 - Train Loss: 0.2961 - Val Acc: 0.8986
2026-04-05 06:05:36,558 - INFO - Epoch 23/100 - Train Loss: 0.2987 - Val Acc: 0.9130
2026-04-05 06:05:36,829 - INFO - Epoch 24/100 - Train Loss: 0.2992 - Val Acc: 0.8986
2026-04-05 06:05:37,095 - INFO - Epoch 25/100 - Train Loss: 0.2946 - Val Acc: 0.8986
2026-04-05 06:05:37,363 - INFO - Epoch 26/100 - Train Loss: 0.2947 - Val Acc: 0.8986
2026-04-05 06:05:37,656 - INFO - Epoch 27/100 - Train Loss: 0.2940 - Val Acc: 0.8986
2026-04-05 06:05:37,922 - INFO - Epoch 28/100 - Train Loss: 0.2917 - Val Acc: 0.8986
2026-04-05 06:05:38,188 - INFO - Epoch 29/100 - Train Loss: 0.2917 - Val Acc: 0.8986
2026-04-05 06:05:38,463 - INFO - Epoch 30/100 - Train Loss: 0.2915 - Val Acc: 0.8986
2026-04-05 06:05:38,736 - INFO - Epoch 31/100 - Train Loss: 0.2899 - Val Acc: 0.8986
2026-04-05 06:05:39,006 - INFO - Epoch 32/100 - Train Loss: 0.2907 - Val Acc: 0.8986
2026-04-05 06:05:39,284 - INFO - Epoch 33/100 - Train Loss: 0.2882 - Val Acc: 0.8986
2026-04-05 06:05:39,558 - INFO - Epoch 34/100 - Train Loss: 0.2883 - Val Acc: 0.8986
2026-04-05 06:05:39,840 - INFO - Epoch 35/100 - Train Loss: 0.2839 - Val Acc: 0.8986
2026-04-05 06:05:40,107 - INFO - Epoch 36/100 - Train Loss: 0.2853 - Val Acc: 0.8986
2026-04-05 06:05:40,379 - INFO - Epoch 37/100 - Train Loss: 0.2840 - Val Acc: 0.8986
2026-04-05 06:05:40,650 - INFO - Epoch 38/100 - Train Loss: 0.2822 - Val Acc: 0.8986
2026-04-05 06:05:40,923 - INFO - Epoch 39/100 - Train Loss: 0.2822 - Val Acc: 0.8986
2026-04-05 06:05:41,195 - INFO - Epoch 40/100 - Train Loss: 0.2824 - Val Acc: 0.8986
2026-04-05 06:05:41,460 - INFO - Epoch 41/100 - Train Loss: 0.2769 - Val Acc: 0.8986
2026-04-05 06:05:41,731 - INFO - Epoch 42/100 - Train Loss: 0.2805 - Val Acc: 0.8986
2026-04-05 06:05:42,012 - INFO - Epoch 43/100 - Train Loss: 0.2761 - Val Acc: 0.8986
2026-04-05 06:05:42,288 - INFO - Epoch 44/100 - Train Loss: 0.2795 - Val Acc: 0.8986
2026-04-05 06:05:42,570 - INFO - Epoch 45/100 - Train Loss: 0.2770 - Val Acc: 0.8986
2026-04-05 06:05:42,835 - INFO - Epoch 46/100 - Train Loss: 0.2742 - Val Acc: 0.8986
2026-04-05 06:05:43,118 - INFO - Epoch 47/100 - Train Loss: 0.2755 - Val Acc: 0.8986
2026-04-05 06:05:43,401 - INFO - Epoch 48/100 - Train Loss: 0.2716 - Val Acc: 0.8986
2026-04-05 06:05:43,681 - INFO - Epoch 49/100 - Train Loss: 0.2764 - Val Acc: 0.8986
2026-04-05 06:05:43,958 - INFO - Epoch 50/100 - Train Loss: 0.2739 - Val Acc: 0.8986
2026-04-05 06:05:44,236 - INFO - Epoch 51/100 - Train Loss: 0.2676 - Val Acc: 0.8841
2026-04-05 06:05:44,519 - INFO - Epoch 52/100 - Train Loss: 0.2693 - Val Acc: 0.8986
2026-04-05 06:05:44,819 - INFO - Epoch 53/100 - Train Loss: 0.2684 - Val Acc: 0.8841
2026-04-05 06:05:45,101 - INFO - Epoch 54/100 - Train Loss: 0.2692 - Val Acc: 0.8841
2026-04-05 06:05:45,377 - INFO - Epoch 55/100 - Train Loss: 0.2685 - Val Acc: 0.8841
2026-04-05 06:05:45,646 - INFO - Epoch 56/100 - Train Loss: 0.2657 - Val Acc: 0.8841
2026-04-05 06:05:45,922 - INFO - Epoch 57/100 - Train Loss: 0.2677 - Val Acc: 0.8841
2026-04-05 06:05:46,191 - INFO - Epoch 58/100 - Train Loss: 0.2600 - Val Acc: 0.8841
2026-04-05 06:05:46,459 - INFO - Epoch 59/100 - Train Loss: 0.2631 - Val Acc: 0.8986
2026-04-05 06:05:46,720 - INFO - Epoch 60/100 - Train Loss: 0.2626 - Val Acc: 0.8841
2026-04-05 06:05:46,986 - INFO - Epoch 61/100 - Train Loss: 0.2588 - Val Acc: 0.8841
2026-04-05 06:05:47,260 - INFO - Epoch 62/100 - Train Loss: 0.2572 - Val Acc: 0.8841
2026-04-05 06:05:47,530 - INFO - Epoch 63/100 - Train Loss: 0.2630 - Val Acc: 0.8841
2026-04-05 06:05:47,816 - INFO - Epoch 64/100 - Train Loss: 0.2589 - Val Acc: 0.8841
2026-04-05 06:05:48,087 - INFO - Epoch 65/100 - Train Loss: 0.2587 - Val Acc: 0.8986
2026-04-05 06:05:48,358 - INFO - Epoch 66/100 - Train Loss: 0.2542 - Val Acc: 0.8841
2026-04-05 06:05:48,632 - INFO - Epoch 67/100 - Train Loss: 0.2522 - Val Acc: 0.8841
2026-04-05 06:05:48,905 - INFO - Epoch 68/100 - Train Loss: 0.2578 - Val Acc: 0.8841
2026-04-05 06:05:49,185 - INFO - Epoch 69/100 - Train Loss: 0.2523 - Val Acc: 0.8841
2026-04-05 06:05:49,453 - INFO - Epoch 70/100 - Train Loss: 0.2525 - Val Acc: 0.8841
2026-04-05 06:05:49,728 - INFO - Epoch 71/100 - Train Loss: 0.2538 - Val Acc: 0.8841
2026-04-05 06:05:49,997 - INFO - Epoch 72/100 - Train Loss: 0.2503 - Val Acc: 0.8841
2026-04-05 06:05:50,262 - INFO - Epoch 73/100 - Train Loss: 0.2501 - Val Acc: 0.8841
2026-04-05 06:05:50,538 - INFO - Epoch 74/100 - Train Loss: 0.2498 - Val Acc: 0.8841
2026-04-05 06:05:50,805 - INFO - Epoch 75/100 - Train Loss: 0.2497 - Val Acc: 0.8841
2026-04-05 06:05:51,075 - INFO - Epoch 76/100 - Train Loss: 0.2458 - Val Acc: 0.8841
2026-04-05 06:05:51,345 - INFO - Epoch 77/100 - Train Loss: 0.2482 - Val Acc: 0.8841
2026-04-05 06:05:51,612 - INFO - Epoch 78/100 - Train Loss: 0.2482 - Val Acc: 0.8841
2026-04-05 06:05:51,883 - INFO - Epoch 79/100 - Train Loss: 0.2414 - Val Acc: 0.8841
2026-04-05 06:05:52,167 - INFO - Epoch 80/100 - Train Loss: 0.2459 - Val Acc: 0.8841
2026-04-05 06:05:52,443 - INFO - Epoch 81/100 - Train Loss: 0.2451 - Val Acc: 0.8841
2026-04-05 06:05:52,704 - INFO - Epoch 82/100 - Train Loss: 0.2430 - Val Acc: 0.8841
2026-04-05 06:05:52,977 - INFO - Epoch 83/100 - Train Loss: 0.2445 - Val Acc: 0.8841
2026-04-05 06:05:53,241 - INFO - Epoch 84/100 - Train Loss: 0.2475 - Val Acc: 0.8841
2026-04-05 06:05:53,516 - INFO - Epoch 85/100 - Train Loss: 0.2451 - Val Acc: 0.8841
2026-04-05 06:05:53,774 - INFO - Epoch 86/100 - Train Loss: 0.2394 - Val Acc: 0.8841
2026-04-05 06:05:54,047 - INFO - Epoch 87/100 - Train Loss: 0.2406 - Val Acc: 0.8841
2026-04-05 06:05:54,357 - INFO - Epoch 88/100 - Train Loss: 0.2399 - Val Acc: 0.8841
2026-04-05 06:05:54,674 - INFO - Epoch 89/100 - Train Loss: 0.2385 - Val Acc: 0.8841
2026-04-05 06:05:54,952 - INFO - Epoch 90/100 - Train Loss: 0.2375 - Val Acc: 0.8841
2026-04-05 06:05:55,214 - INFO - Epoch 91/100 - Train Loss: 0.2370 - Val Acc: 0.8841
2026-04-05 06:05:55,484 - INFO - Epoch 92/100 - Train Loss: 0.2384 - Val Acc: 0.8841
2026-04-05 06:05:55,751 - INFO - Epoch 93/100 - Train Loss: 0.2358 - Val Acc: 0.8841
2026-04-05 06:05:56,015 - INFO - Epoch 94/100 - Train Loss: 0.2331 - Val Acc: 0.8841
2026-04-05 06:05:56,286 - INFO - Epoch 95/100 - Train Loss: 0.2318 - Val Acc: 0.8841
2026-04-05 06:05:56,557 - INFO - Epoch 96/100 - Train Loss: 0.2371 - Val Acc: 0.8841
2026-04-05 06:05:56,823 - INFO - Epoch 97/100 - Train Loss: 0.2362 - Val Acc: 0.8841
2026-04-05 06:05:57,100 - INFO - Epoch 98/100 - Train Loss: 0.2332 - Val Acc: 0.8841
2026-04-05 06:05:57,373 - INFO - Epoch 99/100 - Train Loss: 0.2322 - Val Acc: 0.8841
2026-04-05 06:05:57,640 - INFO - Epoch 100/100 - Train Loss: 0.2373 - Val Acc: 0.8841
2026-04-05 06:05:58,002 - INFO - Fold 2 logically complete. Tensor memory bounds cleared cleanly.
2026-04-05 06:05:58,006 - INFO - Original class distribution: [344 277]
2026-04-05 06:05:58,007 - INFO - Training device bound securely to: cuda

Fold 3:   0%|          | 0/100 [00:00<?, ?it/s]

2026-04-05 06:05:58,302 - INFO - Epoch 1/100 - Train Loss: 0.6614 - Val Acc: 0.9275
2026-04-05 06:05:58,568 - INFO - Epoch 2/100 - Train Loss: 0.5868 - Val Acc: 0.9275
2026-04-05 06:05:58,840 - INFO - Epoch 3/100 - Train Loss: 0.5162 - Val Acc: 0.9420
2026-04-05 06:05:59,100 - INFO - Epoch 4/100 - Train Loss: 0.4566 - Val Acc: 0.9420
2026-04-05 06:05:59,362 - INFO - Epoch 5/100 - Train Loss: 0.4179 - Val Acc: 0.9420
2026-04-05 06:05:59,628 - INFO - Epoch 6/100 - Train Loss: 0.3895 - Val Acc: 0.9420
2026-04-05 06:05:59,902 - INFO - Epoch 7/100 - Train Loss: 0.3733 - Val Acc: 0.9275
2026-04-05 06:06:00,171 - INFO - Epoch 8/100 - Train Loss: 0.3624 - Val Acc: 0.9275
2026-04-05 06:06:00,436 - INFO - Epoch 9/100 - Train Loss: 0.3487 - Val Acc: 0.9275
2026-04-05 06:06:00,728 - INFO - Epoch 10/100 - Train Loss: 0.3403 - Val Acc: 0.9130
2026-04-05 06:06:00,999 - INFO - Epoch 11/100 - Train Loss: 0.3341 - Val Acc: 0.9130
2026-04-05 06:06:01,269 - INFO - Epoch 12/100 - Train Loss: 0.3288 - Val Acc: 0.9130
2026-04-05 06:06:01,546 - INFO - Epoch 13/100 - Train Loss: 0.3226 - Val Acc: 0.9130
2026-04-05 06:06:01,827 - INFO - Epoch 14/100 - Train Loss: 0.3193 - Val Acc: 0.9130
2026-04-05 06:06:02,116 - INFO - Epoch 15/100 - Train Loss: 0.3162 - Val Acc: 0.9130
2026-04-05 06:06:02,384 - INFO - Epoch 16/100 - Train Loss: 0.3161 - Val Acc: 0.9130
2026-04-05 06:06:02,647 - INFO - Epoch 17/100 - Train Loss: 0.3132 - Val Acc: 0.9130
2026-04-05 06:06:02,910 - INFO - Epoch 18/100 - Train Loss: 0.3091 - Val Acc: 0.9130
2026-04-05 06:06:03,183 - INFO - Epoch 19/100 - Train Loss: 0.3093 - Val Acc: 0.9130
2026-04-05 06:06:03,467 - INFO - Epoch 20/100 - Train Loss: 0.3084 - Val Acc: 0.9130
2026-04-05 06:06:03,745 - INFO - Epoch 21/100 - Train Loss: 0.3077 - Val Acc: 0.9130
2026-04-05 06:06:04,024 - INFO - Epoch 22/100 - Train Loss: 0.3056 - Val Acc: 0.9130
2026-04-05 06:06:04,303 - INFO - Epoch 23/100 - Train Loss: 0.3057 - Val Acc: 0.9130
2026-04-05 06:06:04,602 - INFO - Epoch 24/100 - Train Loss: 0.3055 - Val Acc: 0.9130
2026-04-05 06:06:04,864 - INFO - Epoch 25/100 - Train Loss: 0.3034 - Val Acc: 0.9130
2026-04-05 06:06:05,155 - INFO - Epoch 26/100 - Train Loss: 0.3013 - Val Acc: 0.9130
2026-04-05 06:06:05,431 - INFO - Epoch 27/100 - Train Loss: 0.3027 - Val Acc: 0.9130
2026-04-05 06:06:05,720 - INFO - Epoch 28/100 - Train Loss: 0.3025 - Val Acc: 0.9130
2026-04-05 06:06:05,981 - INFO - Epoch 29/100 - Train Loss: 0.2985 - Val Acc: 0.9130
2026-04-05 06:06:06,252 - INFO - Epoch 30/100 - Train Loss: 0.2985 - Val Acc: 0.9130
2026-04-05 06:06:06,518 - INFO - Epoch 31/100 - Train Loss: 0.2973 - Val Acc: 0.9130
2026-04-05 06:06:06,777 - INFO - Epoch 32/100 - Train Loss: 0.2973 - Val Acc: 0.9130
2026-04-05 06:06:07,051 - INFO - Epoch 33/100 - Train Loss: 0.2961 - Val Acc: 0.9130
2026-04-05 06:06:07,329 - INFO - Epoch 34/100 - Train Loss: 0.2965 - Val Acc: 0.9130
2026-04-05 06:06:07,591 - INFO - Epoch 35/100 - Train Loss: 0.2949 - Val Acc: 0.9130
2026-04-05 06:06:07,853 - INFO - Epoch 36/100 - Train Loss: 0.2901 - Val Acc: 0.9130
2026-04-05 06:06:08,114 - INFO - Epoch 37/100 - Train Loss: 0.2933 - Val Acc: 0.9130
2026-04-05 06:06:08,384 - INFO - Epoch 38/100 - Train Loss: 0.2898 - Val Acc: 0.9130
2026-04-05 06:06:08,656 - INFO - Epoch 39/100 - Train Loss: 0.2900 - Val Acc: 0.9130
2026-04-05 06:06:08,929 - INFO - Epoch 40/100 - Train Loss: 0.2876 - Val Acc: 0.9130
2026-04-05 06:06:09,204 - INFO - Epoch 41/100 - Train Loss: 0.2855 - Val Acc: 0.9130
2026-04-05 06:06:09,469 - INFO - Epoch 42/100 - Train Loss: 0.2852 - Val Acc: 0.9130
2026-04-05 06:06:09,752 - INFO - Epoch 43/100 - Train Loss: 0.2849 - Val Acc: 0.9130
2026-04-05 06:06:10,026 - INFO - Epoch 44/100 - Train Loss: 0.2840 - Val Acc: 0.9130
2026-04-05 06:06:10,293 - INFO - Epoch 45/100 - Train Loss: 0.2818 - Val Acc: 0.9130
2026-04-05 06:06:10,568 - INFO - Epoch 46/100 - Train Loss: 0.2836 - Val Acc: 0.9130
2026-04-05 06:06:10,848 - INFO - Epoch 47/100 - Train Loss: 0.2817 - Val Acc: 0.9130
2026-04-05 06:06:11,111 - INFO - Epoch 48/100 - Train Loss: 0.2803 - Val Acc: 0.9130
2026-04-05 06:06:11,376 - INFO - Epoch 49/100 - Train Loss: 0.2792 - Val Acc: 0.9130
2026-04-05 06:06:11,649 - INFO - Epoch 50/100 - Train Loss: 0.2790 - Val Acc: 0.9130
2026-04-05 06:06:11,932 - INFO - Epoch 51/100 - Train Loss: 0.2784 - Val Acc: 0.9130
2026-04-05 06:06:12,210 - INFO - Epoch 52/100 - Train Loss: 0.2768 - Val Acc: 0.9130
2026-04-05 06:06:12,487 - INFO - Epoch 53/100 - Train Loss: 0.2763 - Val Acc: 0.9130
2026-04-05 06:06:12,758 - INFO - Epoch 54/100 - Train Loss: 0.2741 - Val Acc: 0.9130
2026-04-05 06:06:13,028 - INFO - Epoch 55/100 - Train Loss: 0.2726 - Val Acc: 0.9130
2026-04-05 06:06:13,295 - INFO - Epoch 56/100 - Train Loss: 0.2705 - Val Acc: 0.9130
2026-04-05 06:06:13,566 - INFO - Epoch 57/100 - Train Loss: 0.2655 - Val Acc: 0.9130
2026-04-05 06:06:13,837 - INFO - Epoch 58/100 - Train Loss: 0.2700 - Val Acc: 0.9130
2026-04-05 06:06:14,106 - INFO - Epoch 59/100 - Train Loss: 0.2690 - Val Acc: 0.9130
2026-04-05 06:06:14,391 - INFO - Epoch 60/100 - Train Loss: 0.2705 - Val Acc: 0.9130
2026-04-05 06:06:14,688 - INFO - Epoch 61/100 - Train Loss: 0.2663 - Val Acc: 0.9130
2026-04-05 06:06:14,955 - INFO - Epoch 62/100 - Train Loss: 0.2634 - Val Acc: 0.9130
2026-04-05 06:06:15,221 - INFO - Epoch 63/100 - Train Loss: 0.2638 - Val Acc: 0.9130
2026-04-05 06:06:15,505 - INFO - Epoch 64/100 - Train Loss: 0.2629 - Val Acc: 0.9130
2026-04-05 06:06:15,774 - INFO - Epoch 65/100 - Train Loss: 0.2642 - Val Acc: 0.9130
2026-04-05 06:06:16,049 - INFO - Epoch 66/100 - Train Loss: 0.2614 - Val Acc: 0.9130
2026-04-05 06:06:16,321 - INFO - Epoch 67/100 - Train Loss: 0.2622 - Val Acc: 0.9130
2026-04-05 06:06:16,590 - INFO - Epoch 68/100 - Train Loss: 0.2564 - Val Acc: 0.9130
2026-04-05 06:06:16,856 - INFO - Epoch 69/100 - Train Loss: 0.2589 - Val Acc: 0.9130
2026-04-05 06:06:17,126 - INFO - Epoch 70/100 - Train Loss: 0.2565 - Val Acc: 0.9130
2026-04-05 06:06:17,400 - INFO - Epoch 71/100 - Train Loss: 0.2560 - Val Acc: 0.9130
2026-04-05 06:06:17,668 - INFO - Epoch 72/100 - Train Loss: 0.2541 - Val Acc: 0.9130
2026-04-05 06:06:17,931 - INFO - Epoch 73/100 - Train Loss: 0.2568 - Val Acc: 0.9130
2026-04-05 06:06:18,188 - INFO - Epoch 74/100 - Train Loss: 0.2521 - Val Acc: 0.9130
2026-04-05 06:06:18,475 - INFO - Epoch 75/100 - Train Loss: 0.2538 - Val Acc: 0.9130
2026-04-05 06:06:18,759 - INFO - Epoch 76/100 - Train Loss: 0.2508 - Val Acc: 0.9130
2026-04-05 06:06:19,029 - INFO - Epoch 77/100 - Train Loss: 0.2537 - Val Acc: 0.9130
2026-04-05 06:06:19,307 - INFO - Epoch 78/100 - Train Loss: 0.2517 - Val Acc: 0.9130
2026-04-05 06:06:19,569 - INFO - Epoch 79/100 - Train Loss: 0.2445 - Val Acc: 0.9130
2026-04-05 06:06:19,841 - INFO - Epoch 80/100 - Train Loss: 0.2491 - Val Acc: 0.9130
2026-04-05 06:06:20,110 - INFO - Epoch 81/100 - Train Loss: 0.2427 - Val Acc: 0.9130
2026-04-05 06:06:20,376 - INFO - Epoch 82/100 - Train Loss: 0.2468 - Val Acc: 0.9130
2026-04-05 06:06:20,653 - INFO - Epoch 83/100 - Train Loss: 0.2475 - Val Acc: 0.9130
2026-04-05 06:06:20,921 - INFO - Epoch 84/100 - Train Loss: 0.2435 - Val Acc: 0.9130
2026-04-05 06:06:21,187 - INFO - Epoch 85/100 - Train Loss: 0.2411 - Val Acc: 0.9130
2026-04-05 06:06:21,460 - INFO - Epoch 86/100 - Train Loss: 0.2470 - Val Acc: 0.9130
2026-04-05 06:06:21,730 - INFO - Epoch 87/100 - Train Loss: 0.2410 - Val Acc: 0.9130
2026-04-05 06:06:22,007 - INFO - Epoch 88/100 - Train Loss: 0.2411 - Val Acc: 0.9130
2026-04-05 06:06:22,284 - INFO - Epoch 89/100 - Train Loss: 0.2385 - Val Acc: 0.9130
2026-04-05 06:06:22,558 - INFO - Epoch 90/100 - Train Loss: 0.2404 - Val Acc: 0.9130
2026-04-05 06:06:22,820 - INFO - Epoch 91/100 - Train Loss: 0.2422 - Val Acc: 0.9130
2026-04-05 06:06:23,088 - INFO - Epoch 92/100 - Train Loss: 0.2372 - Val Acc: 0.9275
2026-04-05 06:06:23,361 - INFO - Epoch 93/100 - Train Loss: 0.2368 - Val Acc: 0.9275
2026-04-05 06:06:23,636 - INFO - Epoch 94/100 - Train Loss: 0.2387 - Val Acc: 0.9130
2026-04-05 06:06:23,919 - INFO - Epoch 95/100 - Train Loss: 0.2375 - Val Acc: 0.9130
2026-04-05 06:06:24,189 - INFO - Epoch 96/100 - Train Loss: 0.2311 - Val Acc: 0.9130
2026-04-05 06:06:24,458 - INFO - Epoch 97/100 - Train Loss: 0.2373 - Val Acc: 0.9130
2026-04-05 06:06:24,750 - INFO - Epoch 98/100 - Train Loss: 0.2338 - Val Acc: 0.9130
2026-04-05 06:06:25,017 - INFO - Epoch 99/100 - Train Loss: 0.2364 - Val Acc: 0.9275
2026-04-05 06:06:25,283 - INFO - Epoch 100/100 - Train Loss: 0.2322 - Val Acc: 0.9275
2026-04-05 06:06:25,645 - INFO - Fold 3 logically complete. Tensor memory bounds cleared cleanly.
2026-04-05 06:06:25,649 - INFO - Original class distribution: [345 276]
2026-04-05 06:06:25,650 - INFO - Training device bound securely to: cuda

Fold 4:   0%|          | 0/100 [00:00<?, ?it/s]

2026-04-05 06:06:25,952 - INFO - Epoch 1/100 - Train Loss: 0.6614 - Val Acc: 0.7681
2026-04-05 06:06:26,228 - INFO - Epoch 2/100 - Train Loss: 0.5849 - Val Acc: 0.7681
2026-04-05 06:06:26,491 - INFO - Epoch 3/100 - Train Loss: 0.5102 - Val Acc: 0.7681
2026-04-05 06:06:26,765 - INFO - Epoch 4/100 - Train Loss: 0.4492 - Val Acc: 0.7681
2026-04-05 06:06:27,030 - INFO - Epoch 5/100 - Train Loss: 0.4033 - Val Acc: 0.7681
2026-04-05 06:06:27,301 - INFO - Epoch 6/100 - Train Loss: 0.3709 - Val Acc: 0.7681
2026-04-05 06:06:27,569 - INFO - Epoch 7/100 - Train Loss: 0.3539 - Val Acc: 0.7681
2026-04-05 06:06:27,840 - INFO - Epoch 8/100 - Train Loss: 0.3365 - Val Acc: 0.7826
2026-04-05 06:06:28,103 - INFO - Epoch 9/100 - Train Loss: 0.3266 - Val Acc: 0.8116
2026-04-05 06:06:28,361 - INFO - Epoch 10/100 - Train Loss: 0.3140 - Val Acc: 0.7971
2026-04-05 06:06:28,633 - INFO - Epoch 11/100 - Train Loss: 0.3106 - Val Acc: 0.7681
2026-04-05 06:06:28,903 - INFO - Epoch 12/100 - Train Loss: 0.3018 - Val Acc: 0.8116
2026-04-05 06:06:29,180 - INFO - Epoch 13/100 - Train Loss: 0.2968 - Val Acc: 0.7971
2026-04-05 06:06:29,456 - INFO - Epoch 14/100 - Train Loss: 0.2962 - Val Acc: 0.7971
2026-04-05 06:06:29,727 - INFO - Epoch 15/100 - Train Loss: 0.2896 - Val Acc: 0.8116
2026-04-05 06:06:29,997 - INFO - Epoch 16/100 - Train Loss: 0.2867 - Val Acc: 0.8116
2026-04-05 06:06:30,268 - INFO - Epoch 17/100 - Train Loss: 0.2877 - Val Acc: 0.8116
2026-04-05 06:06:30,533 - INFO - Epoch 18/100 - Train Loss: 0.2871 - Val Acc: 0.8116
2026-04-05 06:06:30,817 - INFO - Epoch 19/100 - Train Loss: 0.2839 - Val Acc: 0.8116
2026-04-05 06:06:31,086 - INFO - Epoch 20/100 - Train Loss: 0.2821 - Val Acc: 0.8116
2026-04-05 06:06:31,368 - INFO - Epoch 21/100 - Train Loss: 0.2813 - Val Acc: 0.7971
2026-04-05 06:06:31,639 - INFO - Epoch 22/100 - Train Loss: 0.2800 - Val Acc: 0.7971
2026-04-05 06:06:31,903 - INFO - Epoch 23/100 - Train Loss: 0.2796 - Val Acc: 0.7971
2026-04-05 06:06:32,174 - INFO - Epoch 24/100 - Train Loss: 0.2780 - Val Acc: 0.7971
2026-04-05 06:06:32,448 - INFO - Epoch 25/100 - Train Loss: 0.2765 - Val Acc: 0.7971
2026-04-05 06:06:32,719 - INFO - Epoch 26/100 - Train Loss: 0.2774 - Val Acc: 0.7971
2026-04-05 06:06:32,987 - INFO - Epoch 27/100 - Train Loss: 0.2788 - Val Acc: 0.7971
2026-04-05 06:06:33,248 - INFO - Epoch 28/100 - Train Loss: 0.2772 - Val Acc: 0.7971
2026-04-05 06:06:33,537 - INFO - Epoch 29/100 - Train Loss: 0.2760 - Val Acc: 0.7971
2026-04-05 06:06:33,828 - INFO - Epoch 30/100 - Train Loss: 0.2729 - Val Acc: 0.7971
2026-04-05 06:06:34,109 - INFO - Epoch 31/100 - Train Loss: 0.2711 - Val Acc: 0.7971
2026-04-05 06:06:34,424 - INFO - Epoch 32/100 - Train Loss: 0.2717 - Val Acc: 0.7971
2026-04-05 06:06:34,719 - INFO - Epoch 33/100 - Train Loss: 0.2709 - Val Acc: 0.7971
2026-04-05 06:06:34,983 - INFO - Epoch 34/100 - Train Loss: 0.2709 - Val Acc: 0.7971
2026-04-05 06:06:35,256 - INFO - Epoch 35/100 - Train Loss: 0.2701 - Val Acc: 0.7971
2026-04-05 06:06:35,529 - INFO - Epoch 36/100 - Train Loss: 0.2687 - Val Acc: 0.7971
2026-04-05 06:06:35,800 - INFO - Epoch 37/100 - Train Loss: 0.2677 - Val Acc: 0.7971
2026-04-05 06:06:36,073 - INFO - Epoch 38/100 - Train Loss: 0.2686 - Val Acc: 0.7971
2026-04-05 06:06:36,350 - INFO - Epoch 39/100 - Train Loss: 0.2659 - Val Acc: 0.7971
2026-04-05 06:06:36,622 - INFO - Epoch 40/100 - Train Loss: 0.2629 - Val Acc: 0.7971
2026-04-05 06:06:36,887 - INFO - Epoch 41/100 - Train Loss: 0.2634 - Val Acc: 0.7971
2026-04-05 06:06:37,170 - INFO - Epoch 42/100 - Train Loss: 0.2624 - Val Acc: 0.7971
2026-04-05 06:06:37,448 - INFO - Epoch 43/100 - Train Loss: 0.2605 - Val Acc: 0.7971
2026-04-05 06:06:37,720 - INFO - Epoch 44/100 - Train Loss: 0.2578 - Val Acc: 0.7971
2026-04-05 06:06:37,979 - INFO - Epoch 45/100 - Train Loss: 0.2613 - Val Acc: 0.7971
2026-04-05 06:06:38,240 - INFO - Epoch 46/100 - Train Loss: 0.2588 - Val Acc: 0.7971
2026-04-05 06:06:38,505 - INFO - Epoch 47/100 - Train Loss: 0.2591 - Val Acc: 0.8116
2026-04-05 06:06:38,782 - INFO - Epoch 48/100 - Train Loss: 0.2563 - Val Acc: 0.8116
2026-04-05 06:06:39,048 - INFO - Epoch 49/100 - Train Loss: 0.2564 - Val Acc: 0.7971
2026-04-05 06:06:39,326 - INFO - Epoch 50/100 - Train Loss: 0.2548 - Val Acc: 0.8116
2026-04-05 06:06:39,595 - INFO - Epoch 51/100 - Train Loss: 0.2537 - Val Acc: 0.8261
2026-04-05 06:06:39,874 - INFO - Epoch 52/100 - Train Loss: 0.2551 - Val Acc: 0.8116
2026-04-05 06:06:40,145 - INFO - Epoch 53/100 - Train Loss: 0.2539 - Val Acc: 0.8116
2026-04-05 06:06:40,416 - INFO - Epoch 54/100 - Train Loss: 0.2477 - Val Acc: 0.8116
2026-04-05 06:06:40,680 - INFO - Epoch 55/100 - Train Loss: 0.2517 - Val Acc: 0.8261
2026-04-05 06:06:40,949 - INFO - Epoch 56/100 - Train Loss: 0.2517 - Val Acc: 0.8261
2026-04-05 06:06:41,210 - INFO - Epoch 57/100 - Train Loss: 0.2496 - Val Acc: 0.8261
2026-04-05 06:06:41,480 - INFO - Epoch 58/100 - Train Loss: 0.2472 - Val Acc: 0.8116
2026-04-05 06:06:41,753 - INFO - Epoch 59/100 - Train Loss: 0.2461 - Val Acc: 0.8261
2026-04-05 06:06:42,035 - INFO - Epoch 60/100 - Train Loss: 0.2438 - Val Acc: 0.8261
2026-04-05 06:06:42,310 - INFO - Epoch 61/100 - Train Loss: 0.2470 - Val Acc: 0.8261
2026-04-05 06:06:42,593 - INFO - Epoch 62/100 - Train Loss: 0.2438 - Val Acc: 0.8261
2026-04-05 06:06:42,864 - INFO - Epoch 63/100 - Train Loss: 0.2432 - Val Acc: 0.8261
2026-04-05 06:06:43,131 - INFO - Epoch 64/100 - Train Loss: 0.2442 - Val Acc: 0.8261
2026-04-05 06:06:43,396 - INFO - Epoch 65/100 - Train Loss: 0.2373 - Val Acc: 0.8261
2026-04-05 06:06:43,672 - INFO - Epoch 66/100 - Train Loss: 0.2405 - Val Acc: 0.8261
2026-04-05 06:06:43,941 - INFO - Epoch 67/100 - Train Loss: 0.2442 - Val Acc: 0.8261
2026-04-05 06:06:44,223 - INFO - Epoch 68/100 - Train Loss: 0.2398 - Val Acc: 0.8261
2026-04-05 06:06:44,499 - INFO - Epoch 69/100 - Train Loss: 0.2339 - Val Acc: 0.8261
2026-04-05 06:06:44,807 - INFO - Epoch 70/100 - Train Loss: 0.2362 - Val Acc: 0.8406
2026-04-05 06:06:45,101 - INFO - Epoch 71/100 - Train Loss: 0.2366 - Val Acc: 0.8406
2026-04-05 06:06:45,379 - INFO - Epoch 72/100 - Train Loss: 0.2264 - Val Acc: 0.8406
2026-04-05 06:06:45,645 - INFO - Epoch 73/100 - Train Loss: 0.2343 - Val Acc: 0.8406
2026-04-05 06:06:45,922 - INFO - Epoch 74/100 - Train Loss: 0.2326 - Val Acc: 0.8406
2026-04-05 06:06:46,198 - INFO - Epoch 75/100 - Train Loss: 0.2304 - Val Acc: 0.8406
2026-04-05 06:06:46,479 - INFO - Epoch 76/100 - Train Loss: 0.2301 - Val Acc: 0.8406
2026-04-05 06:06:46,743 - INFO - Epoch 77/100 - Train Loss: 0.2246 - Val Acc: 0.8406
2026-04-05 06:06:47,007 - INFO - Epoch 78/100 - Train Loss: 0.2290 - Val Acc: 0.8406
2026-04-05 06:06:47,280 - INFO - Epoch 79/100 - Train Loss: 0.2254 - Val Acc: 0.8406
2026-04-05 06:06:47,544 - INFO - Epoch 80/100 - Train Loss: 0.2246 - Val Acc: 0.8406
2026-04-05 06:06:47,812 - INFO - Epoch 81/100 - Train Loss: 0.2243 - Val Acc: 0.8406
2026-04-05 06:06:48,086 - INFO - Epoch 82/100 - Train Loss: 0.2270 - Val Acc: 0.8406
2026-04-05 06:06:48,348 - INFO - Epoch 83/100 - Train Loss: 0.2258 - Val Acc: 0.8406
2026-04-05 06:06:48,621 - INFO - Epoch 84/100 - Train Loss: 0.2256 - Val Acc: 0.8406
2026-04-05 06:06:48,901 - INFO - Epoch 85/100 - Train Loss: 0.2226 - Val Acc: 0.8551
2026-04-05 06:06:49,183 - INFO - Epoch 86/100 - Train Loss: 0.2219 - Val Acc: 0.8551
2026-04-05 06:06:49,444 - INFO - Epoch 87/100 - Train Loss: 0.2202 - Val Acc: 0.8406
2026-04-05 06:06:49,705 - INFO - Epoch 88/100 - Train Loss: 0.2205 - Val Acc: 0.8406
2026-04-05 06:06:49,973 - INFO - Epoch 89/100 - Train Loss: 0.2187 - Val Acc: 0.8406
2026-04-05 06:06:50,253 - INFO - Epoch 90/100 - Train Loss: 0.2179 - Val Acc: 0.8406
2026-04-05 06:06:50,522 - INFO - Epoch 91/100 - Train Loss: 0.2162 - Val Acc: 0.8551
2026-04-05 06:06:50,796 - INFO - Epoch 92/100 - Train Loss: 0.2198 - Val Acc: 0.8406
2026-04-05 06:06:51,058 - INFO - Epoch 93/100 - Train Loss: 0.2190 - Val Acc: 0.8406
2026-04-05 06:06:51,324 - INFO - Epoch 94/100 - Train Loss: 0.2134 - Val Acc: 0.8406
2026-04-05 06:06:51,598 - INFO - Epoch 95/100 - Train Loss: 0.2131 - Val Acc: 0.8406
2026-04-05 06:06:51,869 - INFO - Epoch 96/100 - Train Loss: 0.2168 - Val Acc: 0.8261
2026-04-05 06:06:52,139 - INFO - Epoch 97/100 - Train Loss: 0.2136 - Val Acc: 0.8406
2026-04-05 06:06:52,424 - INFO - Epoch 98/100 - Train Loss: 0.2156 - Val Acc: 0.8406
2026-04-05 06:06:52,689 - INFO - Epoch 99/100 - Train Loss: 0.2150 - Val Acc: 0.8261
2026-04-05 06:06:52,948 - INFO - Epoch 100/100 - Train Loss: 0.2071 - Val Acc: 0.8406
2026-04-05 06:06:53,308 - INFO - Fold 4 logically complete. Tensor memory bounds cleared cleanly.
2026-04-05 06:06:53,313 - INFO - Original class distribution: [345 276]
2026-04-05 06:06:53,313 - INFO - Training device bound securely to: cuda

Fold 5:   0%|          | 0/100 [00:00<?, ?it/s]

2026-04-05 06:06:53,616 - INFO - Epoch 1/100 - Train Loss: 0.6588 - Val Acc: 0.8261
2026-04-05 06:06:53,879 - INFO - Epoch 2/100 - Train Loss: 0.5793 - Val Acc: 0.7971
2026-04-05 06:06:54,151 - INFO - Epoch 3/100 - Train Loss: 0.5058 - Val Acc: 0.7826
2026-04-05 06:06:54,440 - INFO - Epoch 4/100 - Train Loss: 0.4431 - Val Acc: 0.7971
2026-04-05 06:06:54,740 - INFO - Epoch 5/100 - Train Loss: 0.4031 - Val Acc: 0.8261
2026-04-05 06:06:55,016 - INFO - Epoch 6/100 - Train Loss: 0.3762 - Val Acc: 0.8261
2026-04-05 06:06:55,282 - INFO - Epoch 7/100 - Train Loss: 0.3611 - Val Acc: 0.8551
2026-04-05 06:06:55,553 - INFO - Epoch 8/100 - Train Loss: 0.3490 - Val Acc: 0.8551
2026-04-05 06:06:55,827 - INFO - Epoch 9/100 - Train Loss: 0.3363 - Val Acc: 0.8551
2026-04-05 06:06:56,100 - INFO - Epoch 10/100 - Train Loss: 0.3277 - Val Acc: 0.8696
2026-04-05 06:06:56,369 - INFO - Epoch 11/100 - Train Loss: 0.3240 - Val Acc: 0.8696
2026-04-05 06:06:56,632 - INFO - Epoch 12/100 - Train Loss: 0.3177 - Val Acc: 0.8696
2026-04-05 06:06:56,895 - INFO - Epoch 13/100 - Train Loss: 0.3111 - Val Acc: 0.8696
2026-04-05 06:06:57,153 - INFO - Epoch 14/100 - Train Loss: 0.3056 - Val Acc: 0.8696
2026-04-05 06:06:57,420 - INFO - Epoch 15/100 - Train Loss: 0.3032 - Val Acc: 0.8696
2026-04-05 06:06:57,683 - INFO - Epoch 16/100 - Train Loss: 0.2998 - Val Acc: 0.8551
2026-04-05 06:06:57,961 - INFO - Epoch 17/100 - Train Loss: 0.2975 - Val Acc: 0.8696
2026-04-05 06:06:58,230 - INFO - Epoch 18/100 - Train Loss: 0.2968 - Val Acc: 0.8551
2026-04-05 06:06:58,500 - INFO - Epoch 19/100 - Train Loss: 0.2974 - Val Acc: 0.8406
2026-04-05 06:06:58,769 - INFO - Epoch 20/100 - Train Loss: 0.2926 - Val Acc: 0.8551
2026-04-05 06:06:59,036 - INFO - Epoch 21/100 - Train Loss: 0.2891 - Val Acc: 0.8551
2026-04-05 06:06:59,298 - INFO - Epoch 22/100 - Train Loss: 0.2909 - Val Acc: 0.8551
2026-04-05 06:06:59,570 - INFO - Epoch 23/100 - Train Loss: 0.2917 - Val Acc: 0.8551
2026-04-05 06:06:59,827 - INFO - Epoch 24/100 - Train Loss: 0.2876 - Val Acc: 0.8406
2026-04-05 06:07:00,094 - INFO - Epoch 25/100 - Train Loss: 0.2871 - Val Acc: 0.8406
2026-04-05 06:07:00,364 - INFO - Epoch 26/100 - Train Loss: 0.2850 - Val Acc: 0.8406
2026-04-05 06:07:00,632 - INFO - Epoch 27/100 - Train Loss: 0.2833 - Val Acc: 0.8406
2026-04-05 06:07:00,892 - INFO - Epoch 28/100 - Train Loss: 0.2836 - Val Acc: 0.8406
2026-04-05 06:07:01,153 - INFO - Epoch 29/100 - Train Loss: 0.2816 - Val Acc: 0.8406
2026-04-05 06:07:01,422 - INFO - Epoch 30/100 - Train Loss: 0.2802 - Val Acc: 0.8406
2026-04-05 06:07:01,694 - INFO - Epoch 31/100 - Train Loss: 0.2807 - Val Acc: 0.8406
2026-04-05 06:07:01,963 - INFO - Epoch 32/100 - Train Loss: 0.2796 - Val Acc: 0.8406
2026-04-05 06:07:02,232 - INFO - Epoch 33/100 - Train Loss: 0.2787 - Val Acc: 0.8406
2026-04-05 06:07:02,507 - INFO - Epoch 34/100 - Train Loss: 0.2787 - Val Acc: 0.8406
2026-04-05 06:07:02,769 - INFO - Epoch 35/100 - Train Loss: 0.2745 - Val Acc: 0.8406
2026-04-05 06:07:03,036 - INFO - Epoch 36/100 - Train Loss: 0.2731 - Val Acc: 0.8406
2026-04-05 06:07:03,291 - INFO - Epoch 37/100 - Train Loss: 0.2735 - Val Acc: 0.8406
2026-04-05 06:07:03,564 - INFO - Epoch 38/100 - Train Loss: 0.2703 - Val Acc: 0.8406
2026-04-05 06:07:03,842 - INFO - Epoch 39/100 - Train Loss: 0.2720 - Val Acc: 0.8406
2026-04-05 06:07:04,113 - INFO - Epoch 40/100 - Train Loss: 0.2684 - Val Acc: 0.8406
2026-04-05 06:07:04,396 - INFO - Epoch 41/100 - Train Loss: 0.2702 - Val Acc: 0.8406
2026-04-05 06:07:04,685 - INFO - Epoch 42/100 - Train Loss: 0.2679 - Val Acc: 0.8551
2026-04-05 06:07:04,951 - INFO - Epoch 43/100 - Train Loss: 0.2636 - Val Acc: 0.8406
2026-04-05 06:07:05,224 - INFO - Epoch 44/100 - Train Loss: 0.2619 - Val Acc: 0.8551
2026-04-05 06:07:05,492 - INFO - Epoch 45/100 - Train Loss: 0.2603 - Val Acc: 0.8551
2026-04-05 06:07:05,764 - INFO - Epoch 46/100 - Train Loss: 0.2643 - Val Acc: 0.8551
2026-04-05 06:07:06,024 - INFO - Epoch 47/100 - Train Loss: 0.2585 - Val Acc: 0.8406
2026-04-05 06:07:06,292 - INFO - Epoch 48/100 - Train Loss: 0.2604 - Val Acc: 0.8406
2026-04-05 06:07:06,579 - INFO - Epoch 49/100 - Train Loss: 0.2595 - Val Acc: 0.8406
2026-04-05 06:07:06,863 - INFO - Epoch 50/100 - Train Loss: 0.2542 - Val Acc: 0.8406
2026-04-05 06:07:07,141 - INFO - Epoch 51/100 - Train Loss: 0.2569 - Val Acc: 0.8406
2026-04-05 06:07:07,409 - INFO - Epoch 52/100 - Train Loss: 0.2542 - Val Acc: 0.8406
2026-04-05 06:07:07,682 - INFO - Epoch 53/100 - Train Loss: 0.2526 - Val Acc: 0.8406
2026-04-05 06:07:07,958 - INFO - Epoch 54/100 - Train Loss: 0.2527 - Val Acc: 0.8406
2026-04-05 06:07:08,229 - INFO - Epoch 55/100 - Train Loss: 0.2494 - Val Acc: 0.8551
2026-04-05 06:07:08,501 - INFO - Epoch 56/100 - Train Loss: 0.2535 - Val Acc: 0.8551
2026-04-05 06:07:08,767 - INFO - Epoch 57/100 - Train Loss: 0.2507 - Val Acc: 0.8406
2026-04-05 06:07:09,036 - INFO - Epoch 58/100 - Train Loss: 0.2502 - Val Acc: 0.8406
2026-04-05 06:07:09,312 - INFO - Epoch 59/100 - Train Loss: 0.2469 - Val Acc: 0.8551
2026-04-05 06:07:09,575 - INFO - Epoch 60/100 - Train Loss: 0.2495 - Val Acc: 0.8406
2026-04-05 06:07:09,837 - INFO - Epoch 61/100 - Train Loss: 0.2460 - Val Acc: 0.8551
2026-04-05 06:07:10,106 - INFO - Epoch 62/100 - Train Loss: 0.2477 - Val Acc: 0.8551
2026-04-05 06:07:10,372 - INFO - Epoch 63/100 - Train Loss: 0.2470 - Val Acc: 0.8551
2026-04-05 06:07:10,640 - INFO - Epoch 64/100 - Train Loss: 0.2455 - Val Acc: 0.8551
2026-04-05 06:07:10,905 - INFO - Epoch 65/100 - Train Loss: 0.2434 - Val Acc: 0.8551
2026-04-05 06:07:11,184 - INFO - Epoch 66/100 - Train Loss: 0.2453 - Val Acc: 0.8551
2026-04-05 06:07:11,458 - INFO - Epoch 67/100 - Train Loss: 0.2418 - Val Acc: 0.8696
2026-04-05 06:07:11,720 - INFO - Epoch 68/100 - Train Loss: 0.2362 - Val Acc: 0.8551
2026-04-05 06:07:11,984 - INFO - Epoch 69/100 - Train Loss: 0.2364 - Val Acc: 0.8696
2026-04-05 06:07:12,254 - INFO - Epoch 70/100 - Train Loss: 0.2407 - Val Acc: 0.8696
2026-04-05 06:07:12,518 - INFO - Epoch 71/100 - Train Loss: 0.2358 - Val Acc: 0.8696
2026-04-05 06:07:12,784 - INFO - Epoch 72/100 - Train Loss: 0.2340 - Val Acc: 0.8406
2026-04-05 06:07:13,056 - INFO - Epoch 73/100 - Train Loss: 0.2363 - Val Acc: 0.8406
2026-04-05 06:07:13,344 - INFO - Epoch 74/100 - Train Loss: 0.2355 - Val Acc: 0.8551
2026-04-05 06:07:13,621 - INFO - Epoch 75/100 - Train Loss: 0.2335 - Val Acc: 0.8406
2026-04-05 06:07:13,894 - INFO - Epoch 76/100 - Train Loss: 0.2308 - Val Acc: 0.8551
2026-04-05 06:07:14,168 - INFO - Epoch 77/100 - Train Loss: 0.2296 - Val Acc: 0.8551
2026-04-05 06:07:14,447 - INFO - Epoch 78/100 - Train Loss: 0.2314 - Val Acc: 0.8551
2026-04-05 06:07:14,753 - INFO - Epoch 79/100 - Train Loss: 0.2311 - Val Acc: 0.8551
2026-04-05 06:07:15,022 - INFO - Epoch 80/100 - Train Loss: 0.2286 - Val Acc: 0.8551
2026-04-05 06:07:15,297 - INFO - Epoch 81/100 - Train Loss: 0.2258 - Val Acc: 0.8551
2026-04-05 06:07:15,569 - INFO - Epoch 82/100 - Train Loss: 0.2298 - Val Acc: 0.8406
2026-04-05 06:07:15,839 - INFO - Epoch 83/100 - Train Loss: 0.2252 - Val Acc: 0.8406
2026-04-05 06:07:16,113 - INFO - Epoch 84/100 - Train Loss: 0.2327 - Val Acc: 0.8551
2026-04-05 06:07:16,377 - INFO - Epoch 85/100 - Train Loss: 0.2286 - Val Acc: 0.8406
2026-04-05 06:07:16,638 - INFO - Epoch 86/100 - Train Loss: 0.2237 - Val Acc: 0.8261
2026-04-05 06:07:16,908 - INFO - Epoch 87/100 - Train Loss: 0.2276 - Val Acc: 0.8261
2026-04-05 06:07:17,187 - INFO - Epoch 88/100 - Train Loss: 0.2253 - Val Acc: 0.8551
2026-04-05 06:07:17,457 - INFO - Epoch 89/100 - Train Loss: 0.2222 - Val Acc: 0.8406
2026-04-05 06:07:17,738 - INFO - Epoch 90/100 - Train Loss: 0.2230 - Val Acc: 0.8551
2026-04-05 06:07:18,022 - INFO - Epoch 91/100 - Train Loss: 0.2231 - Val Acc: 0.8551
2026-04-05 06:07:18,304 - INFO - Epoch 92/100 - Train Loss: 0.2218 - Val Acc: 0.8551
2026-04-05 06:07:18,597 - INFO - Epoch 93/100 - Train Loss: 0.2229 - Val Acc: 0.8696
2026-04-05 06:07:18,891 - INFO - Epoch 94/100 - Train Loss: 0.2239 - Val Acc: 0.8551
2026-04-05 06:07:19,165 - INFO - Epoch 95/100 - Train Loss: 0.2240 - Val Acc: 0.8261
2026-04-05 06:07:19,437 - INFO - Epoch 96/100 - Train Loss: 0.2201 - Val Acc: 0.8551
2026-04-05 06:07:19,710 - INFO - Epoch 97/100 - Train Loss: 0.2210 - Val Acc: 0.8696
2026-04-05 06:07:19,978 - INFO - Epoch 98/100 - Train Loss: 0.2159 - Val Acc: 0.8696
2026-04-05 06:07:20,246 - INFO - Epoch 99/100 - Train Loss: 0.2164 - Val Acc: 0.8696
2026-04-05 06:07:20,511 - INFO - Epoch 100/100 - Train Loss: 0.2173 - Val Acc: 0.8696
2026-04-05 06:07:20,884 - INFO - Fold 5 logically complete. Tensor memory bounds cleared cleanly.
2026-04-05 06:07:20,888 - INFO - Original class distribution: [345 276]
2026-04-05 06:07:20,889 - INFO - Training device bound securely to: cuda

Fold 6:   0%|          | 0/100 [00:00<?, ?it/s]

2026-04-05 06:07:21,183 - INFO - Epoch 1/100 - Train Loss: 0.6563 - Val Acc: 0.8116
2026-04-05 06:07:21,465 - INFO - Epoch 2/100 - Train Loss: 0.5794 - Val Acc: 0.8406
2026-04-05 06:07:21,747 - INFO - Epoch 3/100 - Train Loss: 0.5083 - Val Acc: 0.8406
2026-04-05 06:07:22,011 - INFO - Epoch 4/100 - Train Loss: 0.4473 - Val Acc: 0.8406
2026-04-05 06:07:22,280 - INFO - Epoch 5/100 - Train Loss: 0.4075 - Val Acc: 0.8551
2026-04-05 06:07:22,554 - INFO - Epoch 6/100 - Train Loss: 0.3802 - Val Acc: 0.8551
2026-04-05 06:07:22,822 - INFO - Epoch 7/100 - Train Loss: 0.3652 - Val Acc: 0.8551
2026-04-05 06:07:23,088 - INFO - Epoch 8/100 - Train Loss: 0.3547 - Val Acc: 0.8551
2026-04-05 06:07:23,358 - INFO - Epoch 9/100 - Train Loss: 0.3443 - Val Acc: 0.8696
2026-04-05 06:07:23,620 - INFO - Epoch 10/100 - Train Loss: 0.3351 - Val Acc: 0.8551
2026-04-05 06:07:23,894 - INFO - Epoch 11/100 - Train Loss: 0.3321 - Val Acc: 0.8551
2026-04-05 06:07:24,163 - INFO - Epoch 12/100 - Train Loss: 0.3217 - Val Acc: 0.8841
2026-04-05 06:07:24,440 - INFO - Epoch 13/100 - Train Loss: 0.3212 - Val Acc: 0.8696
2026-04-05 06:07:24,754 - INFO - Epoch 14/100 - Train Loss: 0.3165 - Val Acc: 0.8696
2026-04-05 06:07:25,033 - INFO - Epoch 15/100 - Train Loss: 0.3123 - Val Acc: 0.8841
2026-04-05 06:07:25,302 - INFO - Epoch 16/100 - Train Loss: 0.3127 - Val Acc: 0.8986
2026-04-05 06:07:25,573 - INFO - Epoch 17/100 - Train Loss: 0.3090 - Val Acc: 0.8841
2026-04-05 06:07:25,852 - INFO - Epoch 18/100 - Train Loss: 0.3072 - Val Acc: 0.8841
2026-04-05 06:07:26,117 - INFO - Epoch 19/100 - Train Loss: 0.3063 - Val Acc: 0.8841
2026-04-05 06:07:26,385 - INFO - Epoch 20/100 - Train Loss: 0.3055 - Val Acc: 0.8841
2026-04-05 06:07:26,652 - INFO - Epoch 21/100 - Train Loss: 0.3040 - Val Acc: 0.8841
2026-04-05 06:07:26,921 - INFO - Epoch 22/100 - Train Loss: 0.3029 - Val Acc: 0.8841
2026-04-05 06:07:27,191 - INFO - Epoch 23/100 - Train Loss: 0.3002 - Val Acc: 0.8841
2026-04-05 06:07:27,447 - INFO - Epoch 24/100 - Train Loss: 0.3030 - Val Acc: 0.8841
2026-04-05 06:07:27,722 - INFO - Epoch 25/100 - Train Loss: 0.2991 - Val Acc: 0.8841
2026-04-05 06:07:27,987 - INFO - Epoch 26/100 - Train Loss: 0.2991 - Val Acc: 0.8841
2026-04-05 06:07:28,244 - INFO - Epoch 27/100 - Train Loss: 0.2962 - Val Acc: 0.8841
2026-04-05 06:07:28,516 - INFO - Epoch 28/100 - Train Loss: 0.2958 - Val Acc: 0.8841
2026-04-05 06:07:28,784 - INFO - Epoch 29/100 - Train Loss: 0.2951 - Val Acc: 0.8841
2026-04-05 06:07:29,049 - INFO - Epoch 30/100 - Train Loss: 0.2940 - Val Acc: 0.8841
2026-04-05 06:07:29,324 - INFO - Epoch 31/100 - Train Loss: 0.2913 - Val Acc: 0.8841
2026-04-05 06:07:29,594 - INFO - Epoch 32/100 - Train Loss: 0.2924 - Val Acc: 0.8841
2026-04-05 06:07:29,865 - INFO - Epoch 33/100 - Train Loss: 0.2908 - Val Acc: 0.8841
2026-04-05 06:07:30,140 - INFO - Epoch 34/100 - Train Loss: 0.2927 - Val Acc: 0.8986
2026-04-05 06:07:30,404 - INFO - Epoch 35/100 - Train Loss: 0.2907 - Val Acc: 0.8841
2026-04-05 06:07:30,674 - INFO - Epoch 36/100 - Train Loss: 0.2895 - Val Acc: 0.8841
2026-04-05 06:07:30,937 - INFO - Epoch 37/100 - Train Loss: 0.2896 - Val Acc: 0.8986
2026-04-05 06:07:31,209 - INFO - Epoch 38/100 - Train Loss: 0.2860 - Val Acc: 0.8986
2026-04-05 06:07:31,473 - INFO - Epoch 39/100 - Train Loss: 0.2840 - Val Acc: 0.8841
2026-04-05 06:07:31,740 - INFO - Epoch 40/100 - Train Loss: 0.2856 - Val Acc: 0.8551
2026-04-05 06:07:32,012 - INFO - Epoch 41/100 - Train Loss: 0.2832 - Val Acc: 0.8551
2026-04-05 06:07:32,285 - INFO - Epoch 42/100 - Train Loss: 0.2789 - Val Acc: 0.8551
2026-04-05 06:07:32,572 - INFO - Epoch 43/100 - Train Loss: 0.2846 - Val Acc: 0.8551
2026-04-05 06:07:32,840 - INFO - Epoch 44/100 - Train Loss: 0.2840 - Val Acc: 0.8696
2026-04-05 06:07:33,103 - INFO - Epoch 45/100 - Train Loss: 0.2803 - Val Acc: 0.8696
2026-04-05 06:07:33,372 - INFO - Epoch 46/100 - Train Loss: 0.2783 - Val Acc: 0.8406
2026-04-05 06:07:33,639 - INFO - Epoch 47/100 - Train Loss: 0.2764 - Val Acc: 0.8406
2026-04-05 06:07:33,907 - INFO - Epoch 48/100 - Train Loss: 0.2750 - Val Acc: 0.8551
2026-04-05 06:07:34,188 - INFO - Epoch 49/100 - Train Loss: 0.2753 - Val Acc: 0.8406
2026-04-05 06:07:34,459 - INFO - Epoch 50/100 - Train Loss: 0.2758 - Val Acc: 0.8551
2026-04-05 06:07:34,760 - INFO - Epoch 51/100 - Train Loss: 0.2753 - Val Acc: 0.8551
2026-04-05 06:07:35,047 - INFO - Epoch 52/100 - Train Loss: 0.2737 - Val Acc: 0.8696
2026-04-05 06:07:35,323 - INFO - Epoch 53/100 - Train Loss: 0.2719 - Val Acc: 0.8551
2026-04-05 06:07:35,608 - INFO - Epoch 54/100 - Train Loss: 0.2730 - Val Acc: 0.8551
2026-04-05 06:07:35,888 - INFO - Epoch 55/100 - Train Loss: 0.2688 - Val Acc: 0.8406
2026-04-05 06:07:36,161 - INFO - Epoch 56/100 - Train Loss: 0.2696 - Val Acc: 0.8261
2026-04-05 06:07:36,432 - INFO - Epoch 57/100 - Train Loss: 0.2686 - Val Acc: 0.8406
2026-04-05 06:07:36,719 - INFO - Epoch 58/100 - Train Loss: 0.2656 - Val Acc: 0.8406
2026-04-05 06:07:37,001 - INFO - Epoch 59/100 - Train Loss: 0.2663 - Val Acc: 0.8551
2026-04-05 06:07:37,267 - INFO - Epoch 60/100 - Train Loss: 0.2644 - Val Acc: 0.8406
2026-04-05 06:07:37,548 - INFO - Epoch 61/100 - Train Loss: 0.2665 - Val Acc: 0.8551
2026-04-05 06:07:37,819 - INFO - Epoch 62/100 - Train Loss: 0.2639 - Val Acc: 0.8551
2026-04-05 06:07:38,087 - INFO - Epoch 63/100 - Train Loss: 0.2642 - Val Acc: 0.8551
2026-04-05 06:07:38,348 - INFO - Epoch 64/100 - Train Loss: 0.2593 - Val Acc: 0.8406
2026-04-05 06:07:38,623 - INFO - Epoch 65/100 - Train Loss: 0.2615 - Val Acc: 0.8696
2026-04-05 06:07:38,898 - INFO - Epoch 66/100 - Train Loss: 0.2604 - Val Acc: 0.8696
2026-04-05 06:07:39,169 - INFO - Epoch 67/100 - Train Loss: 0.2596 - Val Acc: 0.8696
2026-04-05 06:07:39,450 - INFO - Epoch 68/100 - Train Loss: 0.2559 - Val Acc: 0.8696
2026-04-05 06:07:39,732 - INFO - Epoch 69/100 - Train Loss: 0.2556 - Val Acc: 0.8551
2026-04-05 06:07:40,005 - INFO - Epoch 70/100 - Train Loss: 0.2600 - Val Acc: 0.8406
2026-04-05 06:07:40,274 - INFO - Epoch 71/100 - Train Loss: 0.2529 - Val Acc: 0.8551
2026-04-05 06:07:40,542 - INFO - Epoch 72/100 - Train Loss: 0.2567 - Val Acc: 0.8406
2026-04-05 06:07:40,810 - INFO - Epoch 73/100 - Train Loss: 0.2515 - Val Acc: 0.8406
2026-04-05 06:07:41,085 - INFO - Epoch 74/100 - Train Loss: 0.2558 - Val Acc: 0.8406
2026-04-05 06:07:41,364 - INFO - Epoch 75/100 - Train Loss: 0.2535 - Val Acc: 0.8406
2026-04-05 06:07:41,638 - INFO - Epoch 76/100 - Train Loss: 0.2469 - Val Acc: 0.8551
2026-04-05 06:07:41,904 - INFO - Epoch 77/100 - Train Loss: 0.2497 - Val Acc: 0.8406
2026-04-05 06:07:42,177 - INFO - Epoch 78/100 - Train Loss: 0.2509 - Val Acc: 0.8406
2026-04-05 06:07:42,453 - INFO - Epoch 79/100 - Train Loss: 0.2451 - Val Acc: 0.8406
2026-04-05 06:07:42,723 - INFO - Epoch 80/100 - Train Loss: 0.2488 - Val Acc: 0.8406
2026-04-05 06:07:42,999 - INFO - Epoch 81/100 - Train Loss: 0.2491 - Val Acc: 0.8261
2026-04-05 06:07:43,262 - INFO - Epoch 82/100 - Train Loss: 0.2482 - Val Acc: 0.8261
2026-04-05 06:07:43,543 - INFO - Epoch 83/100 - Train Loss: 0.2480 - Val Acc: 0.8261
2026-04-05 06:07:43,812 - INFO - Epoch 84/100 - Train Loss: 0.2437 - Val Acc: 0.8406
2026-04-05 06:07:44,079 - INFO - Epoch 85/100 - Train Loss: 0.2475 - Val Acc: 0.8406
2026-04-05 06:07:44,368 - INFO - Epoch 86/100 - Train Loss: 0.2445 - Val Acc: 0.8261
2026-04-05 06:07:44,673 - INFO - Epoch 87/100 - Train Loss: 0.2400 - Val Acc: 0.8406
2026-04-05 06:07:44,938 - INFO - Epoch 88/100 - Train Loss: 0.2446 - Val Acc: 0.8261
2026-04-05 06:07:45,225 - INFO - Epoch 89/100 - Train Loss: 0.2410 - Val Acc: 0.8406
2026-04-05 06:07:45,511 - INFO - Epoch 90/100 - Train Loss: 0.2402 - Val Acc: 0.8261
2026-04-05 06:07:45,785 - INFO - Epoch 91/100 - Train Loss: 0.2400 - Val Acc: 0.8261
2026-04-05 06:07:46,065 - INFO - Epoch 92/100 - Train Loss: 0.2359 - Val Acc: 0.8696
2026-04-05 06:07:46,369 - INFO - Epoch 93/100 - Train Loss: 0.2413 - Val Acc: 0.8551
2026-04-05 06:07:46,646 - INFO - Epoch 94/100 - Train Loss: 0.2386 - Val Acc: 0.8406
2026-04-05 06:07:46,923 - INFO - Epoch 95/100 - Train Loss: 0.2321 - Val Acc: 0.8406
2026-04-05 06:07:47,196 - INFO - Epoch 96/100 - Train Loss: 0.2359 - Val Acc: 0.8551
2026-04-05 06:07:47,463 - INFO - Epoch 97/100 - Train Loss: 0.2323 - Val Acc: 0.8406
2026-04-05 06:07:47,732 - INFO - Epoch 98/100 - Train Loss: 0.2345 - Val Acc: 0.8406
2026-04-05 06:07:47,995 - INFO - Epoch 99/100 - Train Loss: 0.2363 - Val Acc: 0.8551
2026-04-05 06:07:48,269 - INFO - Epoch 100/100 - Train Loss: 0.2320 - Val Acc: 0.8406
2026-04-05 06:07:48,626 - INFO - Fold 6 logically complete. Tensor memory bounds cleared cleanly.
2026-04-05 06:07:48,629 - INFO - Original class distribution: [345 276]
2026-04-05 06:07:48,631 - INFO - Training device bound securely to: cuda

Fold 7:   0%|          | 0/100 [00:00<?, ?it/s]

2026-04-05 06:07:48,940 - INFO - Epoch 1/100 - Train Loss: 0.6593 - Val Acc: 0.7391
2026-04-05 06:07:49,203 - INFO - Epoch 2/100 - Train Loss: 0.5852 - Val Acc: 0.7246
2026-04-05 06:07:49,470 - INFO - Epoch 3/100 - Train Loss: 0.5114 - Val Acc: 0.7246
2026-04-05 06:07:49,748 - INFO - Epoch 4/100 - Train Loss: 0.4451 - Val Acc: 0.7246
2026-04-05 06:07:50,014 - INFO - Epoch 5/100 - Train Loss: 0.4020 - Val Acc: 0.7391
2026-04-05 06:07:50,279 - INFO - Epoch 6/100 - Train Loss: 0.3721 - Val Acc: 0.7391
2026-04-05 06:07:50,562 - INFO - Epoch 7/100 - Train Loss: 0.3542 - Val Acc: 0.7391
2026-04-05 06:07:50,837 - INFO - Epoch 8/100 - Train Loss: 0.3400 - Val Acc: 0.7391
2026-04-05 06:07:51,106 - INFO - Epoch 9/100 - Train Loss: 0.3297 - Val Acc: 0.7391
2026-04-05 06:07:51,372 - INFO - Epoch 10/100 - Train Loss: 0.3180 - Val Acc: 0.7536
2026-04-05 06:07:51,661 - INFO - Epoch 11/100 - Train Loss: 0.3108 - Val Acc: 0.7536
2026-04-05 06:07:51,944 - INFO - Epoch 12/100 - Train Loss: 0.3031 - Val Acc: 0.7681
2026-04-05 06:07:52,215 - INFO - Epoch 13/100 - Train Loss: 0.2981 - Val Acc: 0.7826
2026-04-05 06:07:52,501 - INFO - Epoch 14/100 - Train Loss: 0.2940 - Val Acc: 0.7971
2026-04-05 06:07:52,780 - INFO - Epoch 15/100 - Train Loss: 0.2902 - Val Acc: 0.7971
2026-04-05 06:07:53,060 - INFO - Epoch 16/100 - Train Loss: 0.2843 - Val Acc: 0.7971
2026-04-05 06:07:53,326 - INFO - Epoch 17/100 - Train Loss: 0.2849 - Val Acc: 0.7971
2026-04-05 06:07:53,598 - INFO - Epoch 18/100 - Train Loss: 0.2833 - Val Acc: 0.7971
2026-04-05 06:07:53,880 - INFO - Epoch 19/100 - Train Loss: 0.2820 - Val Acc: 0.8116
2026-04-05 06:07:54,140 - INFO - Epoch 20/100 - Train Loss: 0.2786 - Val Acc: 0.8116
2026-04-05 06:07:54,418 - INFO - Epoch 21/100 - Train Loss: 0.2768 - Val Acc: 0.7971
2026-04-05 06:07:54,716 - INFO - Epoch 22/100 - Train Loss: 0.2780 - Val Acc: 0.7971
2026-04-05 06:07:54,987 - INFO - Epoch 23/100 - Train Loss: 0.2785 - Val Acc: 0.8406
2026-04-05 06:07:55,258 - INFO - Epoch 24/100 - Train Loss: 0.2725 - Val Acc: 0.8261
2026-04-05 06:07:55,529 - INFO - Epoch 25/100 - Train Loss: 0.2756 - Val Acc: 0.8261
2026-04-05 06:07:55,806 - INFO - Epoch 26/100 - Train Loss: 0.2740 - Val Acc: 0.8261
2026-04-05 06:07:56,077 - INFO - Epoch 27/100 - Train Loss: 0.2714 - Val Acc: 0.8261
2026-04-05 06:07:56,344 - INFO - Epoch 28/100 - Train Loss: 0.2695 - Val Acc: 0.8261
2026-04-05 06:07:56,607 - INFO - Epoch 29/100 - Train Loss: 0.2696 - Val Acc: 0.8261
2026-04-05 06:07:56,888 - INFO - Epoch 30/100 - Train Loss: 0.2691 - Val Acc: 0.8261
2026-04-05 06:07:57,159 - INFO - Epoch 31/100 - Train Loss: 0.2675 - Val Acc: 0.8261
2026-04-05 06:07:57,440 - INFO - Epoch 32/100 - Train Loss: 0.2672 - Val Acc: 0.8406
2026-04-05 06:07:57,712 - INFO - Epoch 33/100 - Train Loss: 0.2646 - Val Acc: 0.8406
2026-04-05 06:07:57,990 - INFO - Epoch 34/100 - Train Loss: 0.2646 - Val Acc: 0.8406
2026-04-05 06:07:58,269 - INFO - Epoch 35/100 - Train Loss: 0.2642 - Val Acc: 0.8406
2026-04-05 06:07:58,548 - INFO - Epoch 36/100 - Train Loss: 0.2621 - Val Acc: 0.8261
2026-04-05 06:07:58,827 - INFO - Epoch 37/100 - Train Loss: 0.2604 - Val Acc: 0.8406
2026-04-05 06:07:59,104 - INFO - Epoch 38/100 - Train Loss: 0.2601 - Val Acc: 0.8261
2026-04-05 06:07:59,384 - INFO - Epoch 39/100 - Train Loss: 0.2599 - Val Acc: 0.8261
2026-04-05 06:07:59,670 - INFO - Epoch 40/100 - Train Loss: 0.2568 - Val Acc: 0.8261
2026-04-05 06:07:59,935 - INFO - Epoch 41/100 - Train Loss: 0.2584 - Val Acc: 0.7971
2026-04-05 06:08:00,208 - INFO - Epoch 42/100 - Train Loss: 0.2558 - Val Acc: 0.7826
2026-04-05 06:08:00,477 - INFO - Epoch 43/100 - Train Loss: 0.2547 - Val Acc: 0.7826
2026-04-05 06:08:00,757 - INFO - Epoch 44/100 - Train Loss: 0.2548 - Val Acc: 0.7826
2026-04-05 06:08:01,033 - INFO - Epoch 45/100 - Train Loss: 0.2542 - Val Acc: 0.7971
2026-04-05 06:08:01,302 - INFO - Epoch 46/100 - Train Loss: 0.2517 - Val Acc: 0.7971
2026-04-05 06:08:01,574 - INFO - Epoch 47/100 - Train Loss: 0.2483 - Val Acc: 0.7681
2026-04-05 06:08:01,847 - INFO - Epoch 48/100 - Train Loss: 0.2500 - Val Acc: 0.7681
2026-04-05 06:08:02,115 - INFO - Epoch 49/100 - Train Loss: 0.2472 - Val Acc: 0.7681
2026-04-05 06:08:02,383 - INFO - Epoch 50/100 - Train Loss: 0.2450 - Val Acc: 0.7681
2026-04-05 06:08:02,654 - INFO - Epoch 51/100 - Train Loss: 0.2460 - Val Acc: 0.7681
2026-04-05 06:08:02,928 - INFO - Epoch 52/100 - Train Loss: 0.2456 - Val Acc: 0.7681
2026-04-05 06:08:03,186 - INFO - Epoch 53/100 - Train Loss: 0.2415 - Val Acc: 0.7681
2026-04-05 06:08:03,450 - INFO - Epoch 54/100 - Train Loss: 0.2427 - Val Acc: 0.7681
2026-04-05 06:08:03,711 - INFO - Epoch 55/100 - Train Loss: 0.2433 - Val Acc: 0.7681
2026-04-05 06:08:03,988 - INFO - Epoch 56/100 - Train Loss: 0.2434 - Val Acc: 0.7681
2026-04-05 06:08:04,274 - INFO - Epoch 57/100 - Train Loss: 0.2399 - Val Acc: 0.7681
2026-04-05 06:08:04,579 - INFO - Epoch 58/100 - Train Loss: 0.2389 - Val Acc: 0.7681
2026-04-05 06:08:04,854 - INFO - Epoch 59/100 - Train Loss: 0.2393 - Val Acc: 0.7681
2026-04-05 06:08:05,126 - INFO - Epoch 60/100 - Train Loss: 0.2419 - Val Acc: 0.7681
2026-04-05 06:08:05,400 - INFO - Epoch 61/100 - Train Loss: 0.2362 - Val Acc: 0.7681
2026-04-05 06:08:05,673 - INFO - Epoch 62/100 - Train Loss: 0.2373 - Val Acc: 0.7681
2026-04-05 06:08:05,937 - INFO - Epoch 63/100 - Train Loss: 0.2368 - Val Acc: 0.7681
2026-04-05 06:08:06,223 - INFO - Epoch 64/100 - Train Loss: 0.2333 - Val Acc: 0.7681
2026-04-05 06:08:06,494 - INFO - Epoch 65/100 - Train Loss: 0.2357 - Val Acc: 0.7681
2026-04-05 06:08:06,780 - INFO - Epoch 66/100 - Train Loss: 0.2342 - Val Acc: 0.7681
2026-04-05 06:08:07,053 - INFO - Epoch 67/100 - Train Loss: 0.2329 - Val Acc: 0.7681
2026-04-05 06:08:07,331 - INFO - Epoch 68/100 - Train Loss: 0.2339 - Val Acc: 0.7681
2026-04-05 06:08:07,613 - INFO - Epoch 69/100 - Train Loss: 0.2322 - Val Acc: 0.7681
2026-04-05 06:08:07,895 - INFO - Epoch 70/100 - Train Loss: 0.2305 - Val Acc: 0.7681
2026-04-05 06:08:08,169 - INFO - Epoch 71/100 - Train Loss: 0.2342 - Val Acc: 0.7681
2026-04-05 06:08:08,440 - INFO - Epoch 72/100 - Train Loss: 0.2237 - Val Acc: 0.7681
2026-04-05 06:08:08,717 - INFO - Epoch 73/100 - Train Loss: 0.2275 - Val Acc: 0.7681
2026-04-05 06:08:08,989 - INFO - Epoch 74/100 - Train Loss: 0.2268 - Val Acc: 0.7681
2026-04-05 06:08:09,261 - INFO - Epoch 75/100 - Train Loss: 0.2268 - Val Acc: 0.7681
2026-04-05 06:08:09,526 - INFO - Epoch 76/100 - Train Loss: 0.2263 - Val Acc: 0.7681
2026-04-05 06:08:09,809 - INFO - Epoch 77/100 - Train Loss: 0.2242 - Val Acc: 0.7681
2026-04-05 06:08:10,083 - INFO - Epoch 78/100 - Train Loss: 0.2232 - Val Acc: 0.7681
2026-04-05 06:08:10,358 - INFO - Epoch 79/100 - Train Loss: 0.2217 - Val Acc: 0.7681
2026-04-05 06:08:10,635 - INFO - Epoch 80/100 - Train Loss: 0.2202 - Val Acc: 0.7681
2026-04-05 06:08:10,909 - INFO - Epoch 81/100 - Train Loss: 0.2200 - Val Acc: 0.7681
2026-04-05 06:08:11,188 - INFO - Epoch 82/100 - Train Loss: 0.2206 - Val Acc: 0.7681
2026-04-05 06:08:11,459 - INFO - Epoch 83/100 - Train Loss: 0.2211 - Val Acc: 0.7681
2026-04-05 06:08:11,738 - INFO - Epoch 84/100 - Train Loss: 0.2191 - Val Acc: 0.7681
2026-04-05 06:08:12,024 - INFO - Epoch 85/100 - Train Loss: 0.2234 - Val Acc: 0.7681
2026-04-05 06:08:12,293 - INFO - Epoch 86/100 - Train Loss: 0.2199 - Val Acc: 0.7681
2026-04-05 06:08:12,583 - INFO - Epoch 87/100 - Train Loss: 0.2187 - Val Acc: 0.7681
2026-04-05 06:08:12,864 - INFO - Epoch 88/100 - Train Loss: 0.2186 - Val Acc: 0.7681
2026-04-05 06:08:13,157 - INFO - Epoch 89/100 - Train Loss: 0.2176 - Val Acc: 0.7681
2026-04-05 06:08:13,431 - INFO - Epoch 90/100 - Train Loss: 0.2194 - Val Acc: 0.7681
2026-04-05 06:08:13,707 - INFO - Epoch 91/100 - Train Loss: 0.2207 - Val Acc: 0.7681
2026-04-05 06:08:14,003 - INFO - Epoch 92/100 - Train Loss: 0.2165 - Val Acc: 0.7681
2026-04-05 06:08:14,281 - INFO - Epoch 93/100 - Train Loss: 0.2177 - Val Acc: 0.7681
2026-04-05 06:08:14,586 - INFO - Epoch 94/100 - Train Loss: 0.2123 - Val Acc: 0.7681
2026-04-05 06:08:14,858 - INFO - Epoch 95/100 - Train Loss: 0.2138 - Val Acc: 0.7681
2026-04-05 06:08:15,132 - INFO - Epoch 96/100 - Train Loss: 0.2145 - Val Acc: 0.7681
2026-04-05 06:08:15,402 - INFO - Epoch 97/100 - Train Loss: 0.2153 - Val Acc: 0.7681
2026-04-05 06:08:15,679 - INFO - Epoch 98/100 - Train Loss: 0.2130 - Val Acc: 0.7681
2026-04-05 06:08:15,944 - INFO - Epoch 99/100 - Train Loss: 0.2064 - Val Acc: 0.7681
2026-04-05 06:08:16,218 - INFO - Epoch 100/100 - Train Loss: 0.2130 - Val Acc: 0.7681
2026-04-05 06:08:16,588 - INFO - Fold 7 logically complete. Tensor memory bounds cleared cleanly.
2026-04-05 06:08:16,592 - INFO - Original class distribution: [345 276]
2026-04-05 06:08:16,592 - INFO - Training device bound securely to: cuda

Fold 8:   0%|          | 0/100 [00:00<?, ?it/s]

2026-04-05 06:08:16,903 - INFO - Epoch 1/100 - Train Loss: 0.6516 - Val Acc: 0.8406
2026-04-05 06:08:17,180 - INFO - Epoch 2/100 - Train Loss: 0.5786 - Val Acc: 0.8551
2026-04-05 06:08:17,472 - INFO - Epoch 3/100 - Train Loss: 0.5082 - Val Acc: 0.8551
2026-04-05 06:08:17,747 - INFO - Epoch 4/100 - Train Loss: 0.4508 - Val Acc: 0.8696
2026-04-05 06:08:18,029 - INFO - Epoch 5/100 - Train Loss: 0.4098 - Val Acc: 0.8841
2026-04-05 06:08:18,315 - INFO - Epoch 6/100 - Train Loss: 0.3817 - Val Acc: 0.8841
2026-04-05 06:08:18,603 - INFO - Epoch 7/100 - Train Loss: 0.3645 - Val Acc: 0.8696
2026-04-05 06:08:18,887 - INFO - Epoch 8/100 - Train Loss: 0.3527 - Val Acc: 0.8551
2026-04-05 06:08:19,179 - INFO - Epoch 9/100 - Train Loss: 0.3443 - Val Acc: 0.8261
2026-04-05 06:08:19,459 - INFO - Epoch 10/100 - Train Loss: 0.3348 - Val Acc: 0.8116
2026-04-05 06:08:19,729 - INFO - Epoch 11/100 - Train Loss: 0.3241 - Val Acc: 0.8261
2026-04-05 06:08:20,000 - INFO - Epoch 12/100 - Train Loss: 0.3199 - Val Acc: 0.8116
2026-04-05 06:08:20,267 - INFO - Epoch 13/100 - Train Loss: 0.3156 - Val Acc: 0.8116
2026-04-05 06:08:20,550 - INFO - Epoch 14/100 - Train Loss: 0.3108 - Val Acc: 0.8261
2026-04-05 06:08:20,829 - INFO - Epoch 15/100 - Train Loss: 0.3085 - Val Acc: 0.8261
2026-04-05 06:08:21,107 - INFO - Epoch 16/100 - Train Loss: 0.3067 - Val Acc: 0.8406
2026-04-05 06:08:21,385 - INFO - Epoch 17/100 - Train Loss: 0.3055 - Val Acc: 0.8406
2026-04-05 06:08:21,650 - INFO - Epoch 18/100 - Train Loss: 0.3027 - Val Acc: 0.8406
2026-04-05 06:08:21,929 - INFO - Epoch 19/100 - Train Loss: 0.3029 - Val Acc: 0.8406
2026-04-05 06:08:22,200 - INFO - Epoch 20/100 - Train Loss: 0.3011 - Val Acc: 0.8406
2026-04-05 06:08:22,467 - INFO - Epoch 21/100 - Train Loss: 0.2970 - Val Acc: 0.8406
2026-04-05 06:08:22,744 - INFO - Epoch 22/100 - Train Loss: 0.2972 - Val Acc: 0.8406
2026-04-05 06:08:23,021 - INFO - Epoch 23/100 - Train Loss: 0.2951 - Val Acc: 0.8406
2026-04-05 06:08:23,282 - INFO - Epoch 24/100 - Train Loss: 0.2941 - Val Acc: 0.8406
2026-04-05 06:08:23,554 - INFO - Epoch 25/100 - Train Loss: 0.2959 - Val Acc: 0.8406
2026-04-05 06:08:23,825 - INFO - Epoch 26/100 - Train Loss: 0.2961 - Val Acc: 0.8406
2026-04-05 06:08:24,105 - INFO - Epoch 27/100 - Train Loss: 0.2941 - Val Acc: 0.8406
2026-04-05 06:08:24,377 - INFO - Epoch 28/100 - Train Loss: 0.2912 - Val Acc: 0.8406
2026-04-05 06:08:24,673 - INFO - Epoch 29/100 - Train Loss: 0.2915 - Val Acc: 0.8406
2026-04-05 06:08:24,938 - INFO - Epoch 30/100 - Train Loss: 0.2912 - Val Acc: 0.8406
2026-04-05 06:08:25,208 - INFO - Epoch 31/100 - Train Loss: 0.2901 - Val Acc: 0.8406
2026-04-05 06:08:25,478 - INFO - Epoch 32/100 - Train Loss: 0.2898 - Val Acc: 0.8406
2026-04-05 06:08:25,756 - INFO - Epoch 33/100 - Train Loss: 0.2898 - Val Acc: 0.8406
2026-04-05 06:08:26,036 - INFO - Epoch 34/100 - Train Loss: 0.2875 - Val Acc: 0.8406
2026-04-05 06:08:26,294 - INFO - Epoch 35/100 - Train Loss: 0.2869 - Val Acc: 0.8406
2026-04-05 06:08:26,572 - INFO - Epoch 36/100 - Train Loss: 0.2849 - Val Acc: 0.8406
2026-04-05 06:08:26,861 - INFO - Epoch 37/100 - Train Loss: 0.2856 - Val Acc: 0.8406
2026-04-05 06:08:27,124 - INFO - Epoch 38/100 - Train Loss: 0.2833 - Val Acc: 0.8406
2026-04-05 06:08:27,395 - INFO - Epoch 39/100 - Train Loss: 0.2816 - Val Acc: 0.8406
2026-04-05 06:08:27,680 - INFO - Epoch 40/100 - Train Loss: 0.2836 - Val Acc: 0.8406
2026-04-05 06:08:27,961 - INFO - Epoch 41/100 - Train Loss: 0.2798 - Val Acc: 0.8406
2026-04-05 06:08:28,241 - INFO - Epoch 42/100 - Train Loss: 0.2806 - Val Acc: 0.8406
2026-04-05 06:08:28,517 - INFO - Epoch 43/100 - Train Loss: 0.2786 - Val Acc: 0.8406
2026-04-05 06:08:28,803 - INFO - Epoch 44/100 - Train Loss: 0.2805 - Val Acc: 0.8406
2026-04-05 06:08:29,063 - INFO - Epoch 45/100 - Train Loss: 0.2767 - Val Acc: 0.8406
2026-04-05 06:08:29,339 - INFO - Epoch 46/100 - Train Loss: 0.2776 - Val Acc: 0.8406
2026-04-05 06:08:29,617 - INFO - Epoch 47/100 - Train Loss: 0.2734 - Val Acc: 0.8406
2026-04-05 06:08:29,878 - INFO - Epoch 48/100 - Train Loss: 0.2747 - Val Acc: 0.8406
2026-04-05 06:08:30,146 - INFO - Epoch 49/100 - Train Loss: 0.2734 - Val Acc: 0.8406
2026-04-05 06:08:30,415 - INFO - Epoch 50/100 - Train Loss: 0.2732 - Val Acc: 0.8406
2026-04-05 06:08:30,694 - INFO - Epoch 51/100 - Train Loss: 0.2705 - Val Acc: 0.8406
2026-04-05 06:08:30,979 - INFO - Epoch 52/100 - Train Loss: 0.2720 - Val Acc: 0.8406
2026-04-05 06:08:31,263 - INFO - Epoch 53/100 - Train Loss: 0.2683 - Val Acc: 0.8406
2026-04-05 06:08:31,534 - INFO - Epoch 54/100 - Train Loss: 0.2667 - Val Acc: 0.8406
2026-04-05 06:08:31,807 - INFO - Epoch 55/100 - Train Loss: 0.2694 - Val Acc: 0.8406
2026-04-05 06:08:32,080 - INFO - Epoch 56/100 - Train Loss: 0.2626 - Val Acc: 0.8406
2026-04-05 06:08:32,350 - INFO - Epoch 57/100 - Train Loss: 0.2660 - Val Acc: 0.8406
2026-04-05 06:08:32,620 - INFO - Epoch 58/100 - Train Loss: 0.2628 - Val Acc: 0.8406
2026-04-05 06:08:32,895 - INFO - Epoch 59/100 - Train Loss: 0.2611 - Val Acc: 0.8406
2026-04-05 06:08:33,155 - INFO - Epoch 60/100 - Train Loss: 0.2620 - Val Acc: 0.8406
2026-04-05 06:08:33,435 - INFO - Epoch 61/100 - Train Loss: 0.2567 - Val Acc: 0.8551
2026-04-05 06:08:33,719 - INFO - Epoch 62/100 - Train Loss: 0.2646 - Val Acc: 0.8261
2026-04-05 06:08:33,995 - INFO - Epoch 63/100 - Train Loss: 0.2571 - Val Acc: 0.8406
2026-04-05 06:08:34,278 - INFO - Epoch 64/100 - Train Loss: 0.2588 - Val Acc: 0.8406
2026-04-05 06:08:34,582 - INFO - Epoch 65/100 - Train Loss: 0.2563 - Val Acc: 0.8406
2026-04-05 06:08:34,860 - INFO - Epoch 66/100 - Train Loss: 0.2538 - Val Acc: 0.8406
2026-04-05 06:08:35,141 - INFO - Epoch 67/100 - Train Loss: 0.2565 - Val Acc: 0.8406
2026-04-05 06:08:35,431 - INFO - Epoch 68/100 - Train Loss: 0.2538 - Val Acc: 0.8406
2026-04-05 06:08:35,712 - INFO - Epoch 69/100 - Train Loss: 0.2538 - Val Acc: 0.8406
2026-04-05 06:08:35,981 - INFO - Epoch 70/100 - Train Loss: 0.2517 - Val Acc: 0.8406
2026-04-05 06:08:36,272 - INFO - Epoch 71/100 - Train Loss: 0.2509 - Val Acc: 0.8406
2026-04-05 06:08:36,547 - INFO - Epoch 72/100 - Train Loss: 0.2525 - Val Acc: 0.8551
2026-04-05 06:08:36,825 - INFO - Epoch 73/100 - Train Loss: 0.2528 - Val Acc: 0.8551
2026-04-05 06:08:37,099 - INFO - Epoch 74/100 - Train Loss: 0.2550 - Val Acc: 0.8551
2026-04-05 06:08:37,375 - INFO - Epoch 75/100 - Train Loss: 0.2436 - Val Acc: 0.8551
2026-04-05 06:08:37,662 - INFO - Epoch 76/100 - Train Loss: 0.2467 - Val Acc: 0.8551
2026-04-05 06:08:37,947 - INFO - Epoch 77/100 - Train Loss: 0.2460 - Val Acc: 0.8551
2026-04-05 06:08:38,219 - INFO - Epoch 78/100 - Train Loss: 0.2388 - Val Acc: 0.8551
2026-04-05 06:08:38,494 - INFO - Epoch 79/100 - Train Loss: 0.2453 - Val Acc: 0.8551
2026-04-05 06:08:38,769 - INFO - Epoch 80/100 - Train Loss: 0.2491 - Val Acc: 0.8551
2026-04-05 06:08:39,038 - INFO - Epoch 81/100 - Train Loss: 0.2425 - Val Acc: 0.8551
2026-04-05 06:08:39,320 - INFO - Epoch 82/100 - Train Loss: 0.2435 - Val Acc: 0.8551
2026-04-05 06:08:39,591 - INFO - Epoch 83/100 - Train Loss: 0.2398 - Val Acc: 0.8551
2026-04-05 06:08:39,873 - INFO - Epoch 84/100 - Train Loss: 0.2360 - Val Acc: 0.8551
2026-04-05 06:08:40,148 - INFO - Epoch 85/100 - Train Loss: 0.2374 - Val Acc: 0.8551
2026-04-05 06:08:40,427 - INFO - Epoch 86/100 - Train Loss: 0.2373 - Val Acc: 0.8551
2026-04-05 06:08:40,720 - INFO - Epoch 87/100 - Train Loss: 0.2398 - Val Acc: 0.8551
2026-04-05 06:08:41,003 - INFO - Epoch 88/100 - Train Loss: 0.2394 - Val Acc: 0.8551
2026-04-05 06:08:41,271 - INFO - Epoch 89/100 - Train Loss: 0.2372 - Val Acc: 0.8551
2026-04-05 06:08:41,550 - INFO - Epoch 90/100 - Train Loss: 0.2352 - Val Acc: 0.8551
2026-04-05 06:08:41,827 - INFO - Epoch 91/100 - Train Loss: 0.2417 - Val Acc: 0.8406
2026-04-05 06:08:42,127 - INFO - Epoch 92/100 - Train Loss: 0.2339 - Val Acc: 0.8406
2026-04-05 06:08:42,394 - INFO - Epoch 93/100 - Train Loss: 0.2330 - Val Acc: 0.8406
2026-04-05 06:08:42,676 - INFO - Epoch 94/100 - Train Loss: 0.2335 - Val Acc: 0.8551
2026-04-05 06:08:42,947 - INFO - Epoch 95/100 - Train Loss: 0.2376 - Val Acc: 0.8551
2026-04-05 06:08:43,232 - INFO - Epoch 96/100 - Train Loss: 0.2344 - Val Acc: 0.8551
2026-04-05 06:08:43,498 - INFO - Epoch 97/100 - Train Loss: 0.2309 - Val Acc: 0.8551
2026-04-05 06:08:43,766 - INFO - Epoch 98/100 - Train Loss: 0.2331 - Val Acc: 0.8406
2026-04-05 06:08:44,040 - INFO - Epoch 99/100 - Train Loss: 0.2293 - Val Acc: 0.8551
2026-04-05 06:08:44,325 - INFO - Epoch 100/100 - Train Loss: 0.2369 - Val Acc: 0.8406
2026-04-05 06:08:44,707 - INFO - Fold 8 logically complete. Tensor memory bounds cleared cleanly.
2026-04-05 06:08:44,712 - INFO - Original class distribution: [345 276]
2026-04-05 06:08:44,712 - INFO - Training device bound securely to: cuda

Fold 9:   0%|          | 0/100 [00:00<?, ?it/s]

2026-04-05 06:08:45,024 - INFO - Epoch 1/100 - Train Loss: 0.6647 - Val Acc: 0.8116
2026-04-05 06:08:45,304 - INFO - Epoch 2/100 - Train Loss: 0.5863 - Val Acc: 0.8116
2026-04-05 06:08:45,573 - INFO - Epoch 3/100 - Train Loss: 0.5113 - Val Acc: 0.8116
2026-04-05 06:08:45,846 - INFO - Epoch 4/100 - Train Loss: 0.4512 - Val Acc: 0.8116
2026-04-05 06:08:46,125 - INFO - Epoch 5/100 - Train Loss: 0.4078 - Val Acc: 0.8261
2026-04-05 06:08:46,402 - INFO - Epoch 6/100 - Train Loss: 0.3761 - Val Acc: 0.8406
2026-04-05 06:08:46,675 - INFO - Epoch 7/100 - Train Loss: 0.3603 - Val Acc: 0.8406
2026-04-05 06:08:46,949 - INFO - Epoch 8/100 - Train Loss: 0.3465 - Val Acc: 0.8261
2026-04-05 06:08:47,222 - INFO - Epoch 9/100 - Train Loss: 0.3351 - Val Acc: 0.8116
2026-04-05 06:08:47,492 - INFO - Epoch 10/100 - Train Loss: 0.3273 - Val Acc: 0.8261
2026-04-05 06:08:47,795 - INFO - Epoch 11/100 - Train Loss: 0.3197 - Val Acc: 0.8261
2026-04-05 06:08:48,076 - INFO - Epoch 12/100 - Train Loss: 0.3141 - Val Acc: 0.8261
2026-04-05 06:08:48,356 - INFO - Epoch 13/100 - Train Loss: 0.3097 - Val Acc: 0.8261
2026-04-05 06:08:48,636 - INFO - Epoch 14/100 - Train Loss: 0.3044 - Val Acc: 0.8261
2026-04-05 06:08:48,915 - INFO - Epoch 15/100 - Train Loss: 0.3006 - Val Acc: 0.8261
2026-04-05 06:08:49,194 - INFO - Epoch 16/100 - Train Loss: 0.2976 - Val Acc: 0.8116
2026-04-05 06:08:49,463 - INFO - Epoch 17/100 - Train Loss: 0.2991 - Val Acc: 0.8116
2026-04-05 06:08:49,752 - INFO - Epoch 18/100 - Train Loss: 0.2962 - Val Acc: 0.8116
2026-04-05 06:08:50,028 - INFO - Epoch 19/100 - Train Loss: 0.2924 - Val Acc: 0.8116
2026-04-05 06:08:50,298 - INFO - Epoch 20/100 - Train Loss: 0.2936 - Val Acc: 0.8116
2026-04-05 06:08:50,569 - INFO - Epoch 21/100 - Train Loss: 0.2914 - Val Acc: 0.8261
2026-04-05 06:08:50,841 - INFO - Epoch 22/100 - Train Loss: 0.2891 - Val Acc: 0.8261
2026-04-05 06:08:51,123 - INFO - Epoch 23/100 - Train Loss: 0.2885 - Val Acc: 0.8261
2026-04-05 06:08:51,399 - INFO - Epoch 24/100 - Train Loss: 0.2867 - Val Acc: 0.8261
2026-04-05 06:08:51,682 - INFO - Epoch 25/100 - Train Loss: 0.2859 - Val Acc: 0.8261
2026-04-05 06:08:51,964 - INFO - Epoch 26/100 - Train Loss: 0.2861 - Val Acc: 0.8261
2026-04-05 06:08:52,243 - INFO - Epoch 27/100 - Train Loss: 0.2868 - Val Acc: 0.8261
2026-04-05 06:08:52,530 - INFO - Epoch 28/100 - Train Loss: 0.2868 - Val Acc: 0.8261
2026-04-05 06:08:52,806 - INFO - Epoch 29/100 - Train Loss: 0.2832 - Val Acc: 0.8261
2026-04-05 06:08:53,079 - INFO - Epoch 30/100 - Train Loss: 0.2825 - Val Acc: 0.8261
2026-04-05 06:08:53,355 - INFO - Epoch 31/100 - Train Loss: 0.2840 - Val Acc: 0.8261
2026-04-05 06:08:53,628 - INFO - Epoch 32/100 - Train Loss: 0.2821 - Val Acc: 0.8261
2026-04-05 06:08:53,910 - INFO - Epoch 33/100 - Train Loss: 0.2808 - Val Acc: 0.8261
2026-04-05 06:08:54,187 - INFO - Epoch 34/100 - Train Loss: 0.2814 - Val Acc: 0.8261
2026-04-05 06:08:54,480 - INFO - Epoch 35/100 - Train Loss: 0.2810 - Val Acc: 0.8116
2026-04-05 06:08:54,769 - INFO - Epoch 36/100 - Train Loss: 0.2764 - Val Acc: 0.7971
2026-04-05 06:08:55,063 - INFO - Epoch 37/100 - Train Loss: 0.2791 - Val Acc: 0.8116
2026-04-05 06:08:55,338 - INFO - Epoch 38/100 - Train Loss: 0.2786 - Val Acc: 0.8261
2026-04-05 06:08:55,603 - INFO - Epoch 39/100 - Train Loss: 0.2791 - Val Acc: 0.8261
2026-04-05 06:08:55,865 - INFO - Epoch 40/100 - Train Loss: 0.2779 - Val Acc: 0.8116
2026-04-05 06:08:56,144 - INFO - Epoch 41/100 - Train Loss: 0.2757 - Val Acc: 0.8406
2026-04-05 06:08:56,426 - INFO - Epoch 42/100 - Train Loss: 0.2748 - Val Acc: 0.8116
2026-04-05 06:08:56,708 - INFO - Epoch 43/100 - Train Loss: 0.2728 - Val Acc: 0.8261
2026-04-05 06:08:56,989 - INFO - Epoch 44/100 - Train Loss: 0.2707 - Val Acc: 0.8116
2026-04-05 06:08:57,262 - INFO - Epoch 45/100 - Train Loss: 0.2724 - Val Acc: 0.8116
2026-04-05 06:08:57,532 - INFO - Epoch 46/100 - Train Loss: 0.2711 - Val Acc: 0.8261
2026-04-05 06:08:57,805 - INFO - Epoch 47/100 - Train Loss: 0.2714 - Val Acc: 0.8261
2026-04-05 06:08:58,075 - INFO - Epoch 48/100 - Train Loss: 0.2704 - Val Acc: 0.8261
2026-04-05 06:08:58,352 - INFO - Epoch 49/100 - Train Loss: 0.2702 - Val Acc: 0.8116
2026-04-05 06:08:58,624 - INFO - Epoch 50/100 - Train Loss: 0.2699 - Val Acc: 0.8261
2026-04-05 06:08:58,891 - INFO - Epoch 51/100 - Train Loss: 0.2684 - Val Acc: 0.8261
2026-04-05 06:08:59,160 - INFO - Epoch 52/100 - Train Loss: 0.2683 - Val Acc: 0.8261
2026-04-05 06:08:59,437 - INFO - Epoch 53/100 - Train Loss: 0.2665 - Val Acc: 0.8261
2026-04-05 06:08:59,718 - INFO - Epoch 54/100 - Train Loss: 0.2640 - Val Acc: 0.8261
2026-04-05 06:08:59,998 - INFO - Epoch 55/100 - Train Loss: 0.2639 - Val Acc: 0.8261
2026-04-05 06:09:00,269 - INFO - Epoch 56/100 - Train Loss: 0.2624 - Val Acc: 0.8261
2026-04-05 06:09:00,540 - INFO - Epoch 57/100 - Train Loss: 0.2613 - Val Acc: 0.8261
2026-04-05 06:09:00,816 - INFO - Epoch 58/100 - Train Loss: 0.2621 - Val Acc: 0.8261
2026-04-05 06:09:01,095 - INFO - Epoch 59/100 - Train Loss: 0.2610 - Val Acc: 0.8261
2026-04-05 06:09:01,373 - INFO - Epoch 60/100 - Train Loss: 0.2607 - Val Acc: 0.8261
2026-04-05 06:09:01,653 - INFO - Epoch 61/100 - Train Loss: 0.2566 - Val Acc: 0.8261
2026-04-05 06:09:01,929 - INFO - Epoch 62/100 - Train Loss: 0.2587 - Val Acc: 0.8261
2026-04-05 06:09:02,195 - INFO - Epoch 63/100 - Train Loss: 0.2565 - Val Acc: 0.8261
2026-04-05 06:09:02,476 - INFO - Epoch 64/100 - Train Loss: 0.2552 - Val Acc: 0.8261
2026-04-05 06:09:02,760 - INFO - Epoch 65/100 - Train Loss: 0.2544 - Val Acc: 0.8261
2026-04-05 06:09:03,036 - INFO - Epoch 66/100 - Train Loss: 0.2560 - Val Acc: 0.8261
2026-04-05 06:09:03,314 - INFO - Epoch 67/100 - Train Loss: 0.2507 - Val Acc: 0.8261
2026-04-05 06:09:03,592 - INFO - Epoch 68/100 - Train Loss: 0.2523 - Val Acc: 0.8261
2026-04-05 06:09:03,879 - INFO - Epoch 69/100 - Train Loss: 0.2511 - Val Acc: 0.8261
2026-04-05 06:09:04,158 - INFO - Epoch 70/100 - Train Loss: 0.2520 - Val Acc: 0.8116
2026-04-05 06:09:04,445 - INFO - Epoch 71/100 - Train Loss: 0.2521 - Val Acc: 0.8116
2026-04-05 06:09:04,746 - INFO - Epoch 72/100 - Train Loss: 0.2504 - Val Acc: 0.8261
2026-04-05 06:09:05,021 - INFO - Epoch 73/100 - Train Loss: 0.2480 - Val Acc: 0.8261
2026-04-05 06:09:05,297 - INFO - Epoch 74/100 - Train Loss: 0.2452 - Val Acc: 0.8261
2026-04-05 06:09:05,563 - INFO - Epoch 75/100 - Train Loss: 0.2471 - Val Acc: 0.8261
2026-04-05 06:09:05,845 - INFO - Epoch 76/100 - Train Loss: 0.2438 - Val Acc: 0.8261
2026-04-05 06:09:06,117 - INFO - Epoch 77/100 - Train Loss: 0.2447 - Val Acc: 0.8116
2026-04-05 06:09:06,405 - INFO - Epoch 78/100 - Train Loss: 0.2451 - Val Acc: 0.8116
2026-04-05 06:09:06,690 - INFO - Epoch 79/100 - Train Loss: 0.2454 - Val Acc: 0.8261
2026-04-05 06:09:06,964 - INFO - Epoch 80/100 - Train Loss: 0.2397 - Val Acc: 0.8261
2026-04-05 06:09:07,246 - INFO - Epoch 81/100 - Train Loss: 0.2504 - Val Acc: 0.8261
2026-04-05 06:09:07,515 - INFO - Epoch 82/100 - Train Loss: 0.2440 - Val Acc: 0.8116
2026-04-05 06:09:07,795 - INFO - Epoch 83/100 - Train Loss: 0.2416 - Val Acc: 0.8261
2026-04-05 06:09:08,073 - INFO - Epoch 84/100 - Train Loss: 0.2388 - Val Acc: 0.8261
2026-04-05 06:09:08,356 - INFO - Epoch 85/100 - Train Loss: 0.2395 - Val Acc: 0.8261
2026-04-05 06:09:08,627 - INFO - Epoch 86/100 - Train Loss: 0.2385 - Val Acc: 0.8261
2026-04-05 06:09:08,899 - INFO - Epoch 87/100 - Train Loss: 0.2403 - Val Acc: 0.8116
2026-04-05 06:09:09,163 - INFO - Epoch 88/100 - Train Loss: 0.2375 - Val Acc: 0.8261
2026-04-05 06:09:09,447 - INFO - Epoch 89/100 - Train Loss: 0.2355 - Val Acc: 0.8261
2026-04-05 06:09:09,714 - INFO - Epoch 90/100 - Train Loss: 0.2386 - Val Acc: 0.8261
2026-04-05 06:09:09,986 - INFO - Epoch 91/100 - Train Loss: 0.2341 - Val Acc: 0.8406
2026-04-05 06:09:10,255 - INFO - Epoch 92/100 - Train Loss: 0.2343 - Val Acc: 0.8406
2026-04-05 06:09:10,525 - INFO - Epoch 93/100 - Train Loss: 0.2348 - Val Acc: 0.8406
2026-04-05 06:09:10,800 - INFO - Epoch 94/100 - Train Loss: 0.2348 - Val Acc: 0.8116
2026-04-05 06:09:11,075 - INFO - Epoch 95/100 - Train Loss: 0.2296 - Val Acc: 0.8406
2026-04-05 06:09:11,356 - INFO - Epoch 96/100 - Train Loss: 0.2274 - Val Acc: 0.8406
2026-04-05 06:09:11,627 - INFO - Epoch 97/100 - Train Loss: 0.2293 - Val Acc: 0.8406
2026-04-05 06:09:11,900 - INFO - Epoch 98/100 - Train Loss: 0.2297 - Val Acc: 0.8406
2026-04-05 06:09:12,172 - INFO - Epoch 99/100 - Train Loss: 0.2363 - Val Acc: 0.8406
2026-04-05 06:09:12,454 - INFO - Epoch 100/100 - Train Loss: 0.2307 - Val Acc: 0.8406
2026-04-05 06:09:12,836 - INFO - Fold 9 logically complete. Tensor memory bounds cleared cleanly.
2026-04-05 06:09:12,840 - INFO - Original class distribution: [345 276]
2026-04-05 06:09:12,841 - INFO - Training device bound securely to: cuda

Fold 10:   0%|          | 0/100 [00:00<?, ?it/s]

2026-04-05 06:09:13,144 - INFO - Epoch 1/100 - Train Loss: 0.6595 - Val Acc: 0.8551
2026-04-05 06:09:13,419 - INFO - Epoch 2/100 - Train Loss: 0.5833 - Val Acc: 0.8696
2026-04-05 06:09:13,698 - INFO - Epoch 3/100 - Train Loss: 0.5126 - Val Acc: 0.8841
2026-04-05 06:09:13,969 - INFO - Epoch 4/100 - Train Loss: 0.4555 - Val Acc: 0.8841
2026-04-05 06:09:14,235 - INFO - Epoch 5/100 - Train Loss: 0.4128 - Val Acc: 0.8986
2026-04-05 06:09:14,525 - INFO - Epoch 6/100 - Train Loss: 0.3879 - Val Acc: 0.8986
2026-04-05 06:09:14,809 - INFO - Epoch 7/100 - Train Loss: 0.3729 - Val Acc: 0.8986
2026-04-05 06:09:15,086 - INFO - Epoch 8/100 - Train Loss: 0.3607 - Val Acc: 0.8986
2026-04-05 06:09:15,359 - INFO - Epoch 9/100 - Train Loss: 0.3512 - Val Acc: 0.8986
2026-04-05 06:09:15,634 - INFO - Epoch 10/100 - Train Loss: 0.3467 - Val Acc: 0.8986
2026-04-05 06:09:15,911 - INFO - Epoch 11/100 - Train Loss: 0.3357 - Val Acc: 0.8986
2026-04-05 06:09:16,186 - INFO - Epoch 12/100 - Train Loss: 0.3308 - Val Acc: 0.9130
2026-04-05 06:09:16,475 - INFO - Epoch 13/100 - Train Loss: 0.3268 - Val Acc: 0.9275
2026-04-05 06:09:16,749 - INFO - Epoch 14/100 - Train Loss: 0.3235 - Val Acc: 0.9420
2026-04-05 06:09:17,030 - INFO - Epoch 15/100 - Train Loss: 0.3224 - Val Acc: 0.9420
2026-04-05 06:09:17,316 - INFO - Epoch 16/100 - Train Loss: 0.3188 - Val Acc: 0.9420
2026-04-05 06:09:17,588 - INFO - Epoch 17/100 - Train Loss: 0.3161 - Val Acc: 0.9420
2026-04-05 06:09:17,855 - INFO - Epoch 18/100 - Train Loss: 0.3175 - Val Acc: 0.9420
2026-04-05 06:09:18,133 - INFO - Epoch 19/100 - Train Loss: 0.3140 - Val Acc: 0.9420
2026-04-05 06:09:18,423 - INFO - Epoch 20/100 - Train Loss: 0.3121 - Val Acc: 0.9420
2026-04-05 06:09:18,691 - INFO - Epoch 21/100 - Train Loss: 0.3139 - Val Acc: 0.9565
2026-04-05 06:09:18,969 - INFO - Epoch 22/100 - Train Loss: 0.3109 - Val Acc: 0.9565
2026-04-05 06:09:19,240 - INFO - Epoch 23/100 - Train Loss: 0.3112 - Val Acc: 0.9565
2026-04-05 06:09:19,519 - INFO - Epoch 24/100 - Train Loss: 0.3110 - Val Acc: 0.9565
2026-04-05 06:09:19,788 - INFO - Epoch 25/100 - Train Loss: 0.3100 - Val Acc: 0.9565
2026-04-05 06:09:20,068 - INFO - Epoch 26/100 - Train Loss: 0.3073 - Val Acc: 0.9565
2026-04-05 06:09:20,331 - INFO - Epoch 27/100 - Train Loss: 0.3057 - Val Acc: 0.9565
2026-04-05 06:09:20,603 - INFO - Epoch 28/100 - Train Loss: 0.3066 - Val Acc: 0.9565
2026-04-05 06:09:20,870 - INFO - Epoch 29/100 - Train Loss: 0.3049 - Val Acc: 0.9565
2026-04-05 06:09:21,140 - INFO - Epoch 30/100 - Train Loss: 0.3037 - Val Acc: 0.9565
2026-04-05 06:09:21,420 - INFO - Epoch 31/100 - Train Loss: 0.3045 - Val Acc: 0.9565
2026-04-05 06:09:21,692 - INFO - Epoch 32/100 - Train Loss: 0.2999 - Val Acc: 0.9565
2026-04-05 06:09:21,957 - INFO - Epoch 33/100 - Train Loss: 0.2995 - Val Acc: 0.9565
2026-04-05 06:09:22,231 - INFO - Epoch 34/100 - Train Loss: 0.3007 - Val Acc: 0.9565
2026-04-05 06:09:22,508 - INFO - Epoch 35/100 - Train Loss: 0.2982 - Val Acc: 0.9565
2026-04-05 06:09:22,786 - INFO - Epoch 36/100 - Train Loss: 0.2989 - Val Acc: 0.9565
2026-04-05 06:09:23,069 - INFO - Epoch 37/100 - Train Loss: 0.2947 - Val Acc: 0.9565
2026-04-05 06:09:23,341 - INFO - Epoch 38/100 - Train Loss: 0.2961 - Val Acc: 0.9565
2026-04-05 06:09:23,617 - INFO - Epoch 39/100 - Train Loss: 0.2960 - Val Acc: 0.9565
2026-04-05 06:09:23,889 - INFO - Epoch 40/100 - Train Loss: 0.2940 - Val Acc: 0.9565
2026-04-05 06:09:24,155 - INFO - Epoch 41/100 - Train Loss: 0.2930 - Val Acc: 0.9565
2026-04-05 06:09:24,443 - INFO - Epoch 42/100 - Train Loss: 0.2907 - Val Acc: 0.9565
2026-04-05 06:09:24,751 - INFO - Epoch 43/100 - Train Loss: 0.2912 - Val Acc: 0.9565
2026-04-05 06:09:25,034 - INFO - Epoch 44/100 - Train Loss: 0.2858 - Val Acc: 0.9565
2026-04-05 06:09:25,316 - INFO - Epoch 45/100 - Train Loss: 0.2896 - Val Acc: 0.9565
2026-04-05 06:09:25,592 - INFO - Epoch 46/100 - Train Loss: 0.2857 - Val Acc: 0.9565
2026-04-05 06:09:25,857 - INFO - Epoch 47/100 - Train Loss: 0.2827 - Val Acc: 0.9565
2026-04-05 06:09:26,130 - INFO - Epoch 48/100 - Train Loss: 0.2847 - Val Acc: 0.9565
2026-04-05 06:09:26,403 - INFO - Epoch 49/100 - Train Loss: 0.2813 - Val Acc: 0.9565
2026-04-05 06:09:26,667 - INFO - Epoch 50/100 - Train Loss: 0.2810 - Val Acc: 0.9565
2026-04-05 06:09:26,948 - INFO - Epoch 51/100 - Train Loss: 0.2824 - Val Acc: 0.9565
2026-04-05 06:09:27,222 - INFO - Epoch 52/100 - Train Loss: 0.2804 - Val Acc: 0.9565
2026-04-05 06:09:27,510 - INFO - Epoch 53/100 - Train Loss: 0.2782 - Val Acc: 0.9565
2026-04-05 06:09:27,796 - INFO - Epoch 54/100 - Train Loss: 0.2774 - Val Acc: 0.9565
2026-04-05 06:09:28,079 - INFO - Epoch 55/100 - Train Loss: 0.2750 - Val Acc: 0.9565
2026-04-05 06:09:28,347 - INFO - Epoch 56/100 - Train Loss: 0.2739 - Val Acc: 0.9565
2026-04-05 06:09:28,624 - INFO - Epoch 57/100 - Train Loss: 0.2725 - Val Acc: 0.9565
2026-04-05 06:09:28,906 - INFO - Epoch 58/100 - Train Loss: 0.2740 - Val Acc: 0.9565
2026-04-05 06:09:29,185 - INFO - Epoch 59/100 - Train Loss: 0.2721 - Val Acc: 0.9565
2026-04-05 06:09:29,465 - INFO - Epoch 60/100 - Train Loss: 0.2721 - Val Acc: 0.9565
2026-04-05 06:09:29,747 - INFO - Epoch 61/100 - Train Loss: 0.2713 - Val Acc: 0.9565
2026-04-05 06:09:30,022 - INFO - Epoch 62/100 - Train Loss: 0.2710 - Val Acc: 0.9565
2026-04-05 06:09:30,321 - INFO - Epoch 63/100 - Train Loss: 0.2711 - Val Acc: 0.9565
2026-04-05 06:09:30,600 - INFO - Epoch 64/100 - Train Loss: 0.2671 - Val Acc: 0.9565
2026-04-05 06:09:30,880 - INFO - Epoch 65/100 - Train Loss: 0.2627 - Val Acc: 0.9565
2026-04-05 06:09:31,166 - INFO - Epoch 66/100 - Train Loss: 0.2664 - Val Acc: 0.9565
2026-04-05 06:09:31,440 - INFO - Epoch 67/100 - Train Loss: 0.2677 - Val Acc: 0.9565
2026-04-05 06:09:31,730 - INFO - Epoch 68/100 - Train Loss: 0.2670 - Val Acc: 0.9565
2026-04-05 06:09:31,997 - INFO - Epoch 69/100 - Train Loss: 0.2641 - Val Acc: 0.9565
2026-04-05 06:09:32,281 - INFO - Epoch 70/100 - Train Loss: 0.2643 - Val Acc: 0.9565
2026-04-05 06:09:32,559 - INFO - Epoch 71/100 - Train Loss: 0.2595 - Val Acc: 0.9565
2026-04-05 06:09:32,835 - INFO - Epoch 72/100 - Train Loss: 0.2586 - Val Acc: 0.9565
2026-04-05 06:09:33,111 - INFO - Epoch 73/100 - Train Loss: 0.2564 - Val Acc: 0.9565
2026-04-05 06:09:33,382 - INFO - Epoch 74/100 - Train Loss: 0.2600 - Val Acc: 0.9565
2026-04-05 06:09:33,663 - INFO - Epoch 75/100 - Train Loss: 0.2593 - Val Acc: 0.9565
2026-04-05 06:09:33,941 - INFO - Epoch 76/100 - Train Loss: 0.2548 - Val Acc: 0.9565
2026-04-05 06:09:34,226 - INFO - Epoch 77/100 - Train Loss: 0.2568 - Val Acc: 0.9565
2026-04-05 06:09:34,521 - INFO - Epoch 78/100 - Train Loss: 0.2560 - Val Acc: 0.9565
2026-04-05 06:09:34,817 - INFO - Epoch 79/100 - Train Loss: 0.2541 - Val Acc: 0.9565
2026-04-05 06:09:35,118 - INFO - Epoch 80/100 - Train Loss: 0.2564 - Val Acc: 0.9565
2026-04-05 06:09:35,400 - INFO - Epoch 81/100 - Train Loss: 0.2539 - Val Acc: 0.9565
2026-04-05 06:09:35,679 - INFO - Epoch 82/100 - Train Loss: 0.2541 - Val Acc: 0.9565
2026-04-05 06:09:35,969 - INFO - Epoch 83/100 - Train Loss: 0.2516 - Val Acc: 0.9565
2026-04-05 06:09:36,252 - INFO - Epoch 84/100 - Train Loss: 0.2532 - Val Acc: 0.9565
2026-04-05 06:09:36,529 - INFO - Epoch 85/100 - Train Loss: 0.2484 - Val Acc: 0.9565
2026-04-05 06:09:36,811 - INFO - Epoch 86/100 - Train Loss: 0.2537 - Val Acc: 0.9565
2026-04-05 06:09:37,092 - INFO - Epoch 87/100 - Train Loss: 0.2509 - Val Acc: 0.9565
2026-04-05 06:09:37,394 - INFO - Epoch 88/100 - Train Loss: 0.2489 - Val Acc: 0.9565
2026-04-05 06:09:37,678 - INFO - Epoch 89/100 - Train Loss: 0.2466 - Val Acc: 0.9565
2026-04-05 06:09:37,953 - INFO - Epoch 90/100 - Train Loss: 0.2468 - Val Acc: 0.9565
2026-04-05 06:09:38,228 - INFO - Epoch 91/100 - Train Loss: 0.2455 - Val Acc: 0.9565
2026-04-05 06:09:38,514 - INFO - Epoch 92/100 - Train Loss: 0.2498 - Val Acc: 0.9565
2026-04-05 06:09:38,801 - INFO - Epoch 93/100 - Train Loss: 0.2434 - Val Acc: 0.9565
2026-04-05 06:09:39,093 - INFO - Epoch 94/100 - Train Loss: 0.2444 - Val Acc: 0.9565
2026-04-05 06:09:39,372 - INFO - Epoch 95/100 - Train Loss: 0.2427 - Val Acc: 0.9565
2026-04-05 06:09:39,651 - INFO - Epoch 96/100 - Train Loss: 0.2485 - Val Acc: 0.9565
2026-04-05 06:09:39,932 - INFO - Epoch 97/100 - Train Loss: 0.2434 - Val Acc: 0.9565
2026-04-05 06:09:40,221 - INFO - Epoch 98/100 - Train Loss: 0.2406 - Val Acc: 0.9565
2026-04-05 06:09:40,505 - INFO - Epoch 99/100 - Train Loss: 0.2372 - Val Acc: 0.9565
2026-04-05 06:09:40,775 - INFO - Epoch 100/100 - Train Loss: 0.2420 - Val Acc: 0.9565
2026-04-05 06:09:41,146 - INFO - Fold 10 logically complete. Tensor memory bounds cleared cleanly.
2026-04-05 06:09:41,164 - INFO - ✓ Completed GRU_baseline -> Acc: 0.8913
2026-04-05 06:09:41,165 - INFO -
EXPERIMENT: GRU_SMOTEENN | australian | SMOTE-ENN: True

Australian | GRU | SMOTEENN:   0%|          | 0/10 [00:00<?, ?it/s]

2026-04-05 06:09:41,177 - INFO - Original class distribution: [344 277]
2026-04-05 06:09:41,178 - INFO - Training device bound securely to: cuda
2026-04-05 06:09:41,207 - INFO - After SMOTE-ENN deployment: [344 287]

Fold 1:   0%|          | 0/100 [00:00<?, ?it/s]

2026-04-05 06:09:41,502 - INFO - Epoch 1/100 - Train Loss: 0.6455 - Val Acc: 0.7971
2026-04-05 06:09:41,785 - INFO - Epoch 2/100 - Train Loss: 0.5508 - Val Acc: 0.8116
2026-04-05 06:09:42,060 - INFO - Epoch 3/100 - Train Loss: 0.4602 - Val Acc: 0.8406
2026-04-05 06:09:42,334 - INFO - Epoch 4/100 - Train Loss: 0.3843 - Val Acc: 0.8551
2026-04-05 06:09:42,618 - INFO - Epoch 5/100 - Train Loss: 0.3295 - Val Acc: 0.8551
2026-04-05 06:09:42,899 - INFO - Epoch 6/100 - Train Loss: 0.2920 - Val Acc: 0.8696
2026-04-05 06:09:43,173 - INFO - Epoch 7/100 - Train Loss: 0.2685 - Val Acc: 0.8841
2026-04-05 06:09:43,454 - INFO - Epoch 8/100 - Train Loss: 0.2497 - Val Acc: 0.8986
2026-04-05 06:09:43,733 - INFO - Epoch 9/100 - Train Loss: 0.2362 - Val Acc: 0.8841
2026-04-05 06:09:44,004 - INFO - Epoch 10/100 - Train Loss: 0.2282 - Val Acc: 0.8841
2026-04-05 06:09:44,276 - INFO - Epoch 11/100 - Train Loss: 0.2174 - Val Acc: 0.8841
2026-04-05 06:09:44,563 - INFO - Epoch 12/100 - Train Loss: 0.2122 - Val Acc: 0.8986
2026-04-05 06:09:44,842 - INFO - Epoch 13/100 - Train Loss: 0.2027 - Val Acc: 0.8841
2026-04-05 06:09:45,122 - INFO - Epoch 14/100 - Train Loss: 0.1988 - Val Acc: 0.8986
2026-04-05 06:09:45,395 - INFO - Epoch 15/100 - Train Loss: 0.1923 - Val Acc: 0.8841
2026-04-05 06:09:45,657 - INFO - Epoch 16/100 - Train Loss: 0.1868 - Val Acc: 0.8986
2026-04-05 06:09:45,938 - INFO - Epoch 17/100 - Train Loss: 0.1857 - Val Acc: 0.8841
2026-04-05 06:09:46,217 - INFO - Epoch 18/100 - Train Loss: 0.1824 - Val Acc: 0.8841
2026-04-05 06:09:46,493 - INFO - Epoch 19/100 - Train Loss: 0.1803 - Val Acc: 0.8986
2026-04-05 06:09:46,762 - INFO - Epoch 20/100 - Train Loss: 0.1774 - Val Acc: 0.8841
2026-04-05 06:09:47,030 - INFO - Epoch 21/100 - Train Loss: 0.1738 - Val Acc: 0.8986
2026-04-05 06:09:47,294 - INFO - Epoch 22/100 - Train Loss: 0.1735 - Val Acc: 0.8841
2026-04-05 06:09:47,569 - INFO - Epoch 23/100 - Train Loss: 0.1702 - Val Acc: 0.8986
2026-04-05 06:09:47,840 - INFO - Epoch 24/100 - Train Loss: 0.1708 - Val Acc: 0.8986
2026-04-05 06:09:48,117 - INFO - Epoch 25/100 - Train Loss: 0.1700 - Val Acc: 0.8986
2026-04-05 06:09:48,396 - INFO - Epoch 26/100 - Train Loss: 0.1675 - Val Acc: 0.8986
2026-04-05 06:09:48,669 - INFO - Epoch 27/100 - Train Loss: 0.1684 - Val Acc: 0.8841
2026-04-05 06:09:48,939 - INFO - Epoch 28/100 - Train Loss: 0.1655 - Val Acc: 0.8986
2026-04-05 06:09:49,222 - INFO - Epoch 29/100 - Train Loss: 0.1660 - Val Acc: 0.8986
2026-04-05 06:09:49,496 - INFO - Epoch 30/100 - Train Loss: 0.1666 - Val Acc: 0.8986
2026-04-05 06:09:49,765 - INFO - Epoch 31/100 - Train Loss: 0.1640 - Val Acc: 0.8986
2026-04-05 06:09:50,041 - INFO - Epoch 32/100 - Train Loss: 0.1631 - Val Acc: 0.8986
2026-04-05 06:09:50,316 - INFO - Epoch 33/100 - Train Loss: 0.1632 - Val Acc: 0.8986
2026-04-05 06:09:50,592 - INFO - Epoch 34/100 - Train Loss: 0.1614 - Val Acc: 0.8986
2026-04-05 06:09:50,859 - INFO - Epoch 35/100 - Train Loss: 0.1606 - Val Acc: 0.8986
2026-04-05 06:09:51,128 - INFO - Epoch 36/100 - Train Loss: 0.1614 - Val Acc: 0.8986
2026-04-05 06:09:51,408 - INFO - Epoch 37/100 - Train Loss: 0.1592 - Val Acc: 0.8986
2026-04-05 06:09:51,694 - INFO - Epoch 38/100 - Train Loss: 0.1591 - Val Acc: 0.8986
2026-04-05 06:09:51,970 - INFO - Epoch 39/100 - Train Loss: 0.1575 - Val Acc: 0.8986
2026-04-05 06:09:52,242 - INFO - Epoch 40/100 - Train Loss: 0.1561 - Val Acc: 0.8986
2026-04-05 06:09:52,516 - INFO - Epoch 41/100 - Train Loss: 0.1549 - Val Acc: 0.8986
2026-04-05 06:09:52,791 - INFO - Epoch 42/100 - Train Loss: 0.1549 - Val Acc: 0.8986
2026-04-05 06:09:53,065 - INFO - Epoch 43/100 - Train Loss: 0.1563 - Val Acc: 0.8986
2026-04-05 06:09:53,345 - INFO - Epoch 44/100 - Train Loss: 0.1555 - Val Acc: 0.8986
2026-04-05 06:09:53,628 - INFO - Epoch 45/100 - Train Loss: 0.1547 - Val Acc: 0.8986
2026-04-05 06:09:53,897 - INFO - Epoch 46/100 - Train Loss: 0.1536 - Val Acc: 0.8986
2026-04-05 06:09:54,185 - INFO - Epoch 47/100 - Train Loss: 0.1511 - Val Acc: 0.8986
2026-04-05 06:09:54,469 - INFO - Epoch 48/100 - Train Loss: 0.1507 - Val Acc: 0.8986
2026-04-05 06:09:54,780 - INFO - Epoch 49/100 - Train Loss: 0.1492 - Val Acc: 0.8986
2026-04-05 06:09:55,048 - INFO - Epoch 50/100 - Train Loss: 0.1492 - Val Acc: 0.8986
2026-04-05 06:09:55,314 - INFO - Epoch 51/100 - Train Loss: 0.1478 - Val Acc: 0.8986
2026-04-05 06:09:55,586 - INFO - Epoch 52/100 - Train Loss: 0.1472 - Val Acc: 0.8986
2026-04-05 06:09:55,860 - INFO - Epoch 53/100 - Train Loss: 0.1470 - Val Acc: 0.8986
2026-04-05 06:09:56,138 - INFO - Epoch 54/100 - Train Loss: 0.1453 - Val Acc: 0.8986
2026-04-05 06:09:56,411 - INFO - Epoch 55/100 - Train Loss: 0.1461 - Val Acc: 0.8986
2026-04-05 06:09:56,698 - INFO - Epoch 56/100 - Train Loss: 0.1412 - Val Acc: 0.8986
2026-04-05 06:09:56,973 - INFO - Epoch 57/100 - Train Loss: 0.1435 - Val Acc: 0.8986
2026-04-05 06:09:57,248 - INFO - Epoch 58/100 - Train Loss: 0.1443 - Val Acc: 0.8986
2026-04-05 06:09:57,526 - INFO - Epoch 59/100 - Train Loss: 0.1410 - Val Acc: 0.8986
2026-04-05 06:09:57,809 - INFO - Epoch 60/100 - Train Loss: 0.1417 - Val Acc: 0.8986
2026-04-05 06:09:58,079 - INFO - Epoch 61/100 - Train Loss: 0.1418 - Val Acc: 0.8986
2026-04-05 06:09:58,353 - INFO - Epoch 62/100 - Train Loss: 0.1361 - Val Acc: 0.8986
2026-04-05 06:09:58,632 - INFO - Epoch 63/100 - Train Loss: 0.1428 - Val Acc: 0.8986
2026-04-05 06:09:58,920 - INFO - Epoch 64/100 - Train Loss: 0.1405 - Val Acc: 0.8986
2026-04-05 06:09:59,213 - INFO - Epoch 65/100 - Train Loss: 0.1369 - Val Acc: 0.9130
2026-04-05 06:09:59,491 - INFO - Epoch 66/100 - Train Loss: 0.1358 - Val Acc: 0.9130
2026-04-05 06:09:59,777 - INFO - Epoch 67/100 - Train Loss: 0.1386 - Val Acc: 0.9130
2026-04-05 06:10:00,066 - INFO - Epoch 68/100 - Train Loss: 0.1370 - Val Acc: 0.9130
2026-04-05 06:10:00,342 - INFO - Epoch 69/100 - Train Loss: 0.1358 - Val Acc: 0.9130
2026-04-05 06:10:00,611 - INFO - Epoch 70/100 - Train Loss: 0.1338 - Val Acc: 0.9130
2026-04-05 06:10:00,881 - INFO - Epoch 71/100 - Train Loss: 0.1317 - Val Acc: 0.9130
2026-04-05 06:10:01,156 - INFO - Epoch 72/100 - Train Loss: 0.1325 - Val Acc: 0.9130
2026-04-05 06:10:01,425 - INFO - Epoch 73/100 - Train Loss: 0.1325 - Val Acc: 0.9130
2026-04-05 06:10:01,699 - INFO - Epoch 74/100 - Train Loss: 0.1337 - Val Acc: 0.9130
2026-04-05 06:10:01,975 - INFO - Epoch 75/100 - Train Loss: 0.1329 - Val Acc: 0.9130
2026-04-05 06:10:02,254 - INFO - Epoch 76/100 - Train Loss: 0.1297 - Val Acc: 0.9130
2026-04-05 06:10:02,539 - INFO - Epoch 77/100 - Train Loss: 0.1317 - Val Acc: 0.9130
2026-04-05 06:10:02,820 - INFO - Epoch 78/100 - Train Loss: 0.1308 - Val Acc: 0.9130
2026-04-05 06:10:03,094 - INFO - Epoch 79/100 - Train Loss: 0.1301 - Val Acc: 0.9130
2026-04-05 06:10:03,368 - INFO - Epoch 80/100 - Train Loss: 0.1306 - Val Acc: 0.9130
2026-04-05 06:10:03,638 - INFO - Epoch 81/100 - Train Loss: 0.1304 - Val Acc: 0.9130
2026-04-05 06:10:03,911 - INFO - Epoch 82/100 - Train Loss: 0.1286 - Val Acc: 0.9130
2026-04-05 06:10:04,195 - INFO - Epoch 83/100 - Train Loss: 0.1250 - Val Acc: 0.9130
2026-04-05 06:10:04,482 - INFO - Epoch 84/100 - Train Loss: 0.1278 - Val Acc: 0.9130
2026-04-05 06:10:04,785 - INFO - Epoch 85/100 - Train Loss: 0.1264 - Val Acc: 0.9130
2026-04-05 06:10:05,071 - INFO - Epoch 86/100 - Train Loss: 0.1293 - Val Acc: 0.9130
2026-04-05 06:10:05,342 - INFO - Epoch 87/100 - Train Loss: 0.1224 - Val Acc: 0.9130
2026-04-05 06:10:05,614 - INFO - Epoch 88/100 - Train Loss: 0.1268 - Val Acc: 0.9130
2026-04-05 06:10:05,888 - INFO - Epoch 89/100 - Train Loss: 0.1274 - Val Acc: 0.9130
2026-04-05 06:10:06,161 - INFO - Epoch 90/100 - Train Loss: 0.1225 - Val Acc: 0.9130
2026-04-05 06:10:06,427 - INFO - Epoch 91/100 - Train Loss: 0.1270 - Val Acc: 0.9130
2026-04-05 06:10:06,698 - INFO - Epoch 92/100 - Train Loss: 0.1272 - Val Acc: 0.9130
2026-04-05 06:10:06,968 - INFO - Epoch 93/100 - Train Loss: 0.1237 - Val Acc: 0.9130
2026-04-05 06:10:07,246 - INFO - Epoch 94/100 - Train Loss: 0.1227 - Val Acc: 0.9130
2026-04-05 06:10:07,514 - INFO - Epoch 95/100 - Train Loss: 0.1214 - Val Acc: 0.9130
2026-04-05 06:10:07,797 - INFO - Epoch 96/100 - Train Loss: 0.1189 - Val Acc: 0.9130
2026-04-05 06:10:08,073 - INFO - Epoch 97/100 - Train Loss: 0.1215 - Val Acc: 0.9130
2026-04-05 06:10:08,371 - INFO - Epoch 98/100 - Train Loss: 0.1217 - Val Acc: 0.9130
2026-04-05 06:10:08,652 - INFO - Epoch 99/100 - Train Loss: 0.1221 - Val Acc: 0.9130
2026-04-05 06:10:08,925 - INFO - Epoch 100/100 - Train Loss: 0.1182 - Val Acc: 0.9130
2026-04-05 06:10:09,302 - INFO - Fold 1 logically complete. Tensor memory bounds cleared cleanly.
2026-04-05 06:10:09,306 - INFO - Original class distribution: [344 277]
2026-04-05 06:10:09,307 - INFO - Training device bound securely to: cuda
2026-04-05 06:10:09,336 - INFO - After SMOTE-ENN deployment: [344 292]

Fold 2:   0%|          | 0/100 [00:00<?, ?it/s]

2026-04-05 06:10:09,623 - INFO - Epoch 1/100 - Train Loss: 0.6495 - Val Acc: 0.7536
2026-04-05 06:10:09,911 - INFO - Epoch 2/100 - Train Loss: 0.5571 - Val Acc: 0.7536
2026-04-05 06:10:10,186 - INFO - Epoch 3/100 - Train Loss: 0.4680 - Val Acc: 0.7536
2026-04-05 06:10:10,452 - INFO - Epoch 4/100 - Train Loss: 0.3879 - Val Acc: 0.7681
2026-04-05 06:10:10,732 - INFO - Epoch 5/100 - Train Loss: 0.3303 - Val Acc: 0.7681
2026-04-05 06:10:11,009 - INFO - Epoch 6/100 - Train Loss: 0.2916 - Val Acc: 0.7681
2026-04-05 06:10:11,299 - INFO - Epoch 7/100 - Train Loss: 0.2657 - Val Acc: 0.7826
2026-04-05 06:10:11,575 - INFO - Epoch 8/100 - Train Loss: 0.2513 - Val Acc: 0.7826
2026-04-05 06:10:11,871 - INFO - Epoch 9/100 - Train Loss: 0.2395 - Val Acc: 0.7826
2026-04-05 06:10:12,153 - INFO - Epoch 10/100 - Train Loss: 0.2275 - Val Acc: 0.7826
2026-04-05 06:10:12,435 - INFO - Epoch 11/100 - Train Loss: 0.2232 - Val Acc: 0.7971
2026-04-05 06:10:12,719 - INFO - Epoch 12/100 - Train Loss: 0.2173 - Val Acc: 0.7971
2026-04-05 06:10:12,993 - INFO - Epoch 13/100 - Train Loss: 0.2126 - Val Acc: 0.7971
2026-04-05 06:10:13,273 - INFO - Epoch 14/100 - Train Loss: 0.2109 - Val Acc: 0.7971
2026-04-05 06:10:13,550 - INFO - Epoch 15/100 - Train Loss: 0.2058 - Val Acc: 0.7971
2026-04-05 06:10:13,827 - INFO - Epoch 16/100 - Train Loss: 0.2033 - Val Acc: 0.8116
2026-04-05 06:10:14,100 - INFO - Epoch 17/100 - Train Loss: 0.2005 - Val Acc: 0.8406
2026-04-05 06:10:14,379 - INFO - Epoch 18/100 - Train Loss: 0.2000 - Val Acc: 0.8551
2026-04-05 06:10:14,699 - INFO - Epoch 19/100 - Train Loss: 0.1974 - Val Acc: 0.8551
2026-04-05 06:10:14,969 - INFO - Epoch 20/100 - Train Loss: 0.1943 - Val Acc: 0.8551
2026-04-05 06:10:15,246 - INFO - Epoch 21/100 - Train Loss: 0.1934 - Val Acc: 0.8551
2026-04-05 06:10:15,532 - INFO - Epoch 22/100 - Train Loss: 0.1922 - Val Acc: 0.8696
2026-04-05 06:10:15,805 - INFO - Epoch 23/100 - Train Loss: 0.1923 - Val Acc: 0.8696
2026-04-05 06:10:16,096 - INFO - Epoch 24/100 - Train Loss: 0.1908 - Val Acc: 0.8696
2026-04-05 06:10:16,370 - INFO - Epoch 25/100 - Train Loss: 0.1913 - Val Acc: 0.8841
2026-04-05 06:10:16,648 - INFO - Epoch 26/100 - Train Loss: 0.1871 - Val Acc: 0.8986
2026-04-05 06:10:16,926 - INFO - Epoch 27/100 - Train Loss: 0.1872 - Val Acc: 0.9130
2026-04-05 06:10:17,207 - INFO - Epoch 28/100 - Train Loss: 0.1867 - Val Acc: 0.9130
2026-04-05 06:10:17,486 - INFO - Epoch 29/100 - Train Loss: 0.1854 - Val Acc: 0.8986
2026-04-05 06:10:17,773 - INFO - Epoch 30/100 - Train Loss: 0.1847 - Val Acc: 0.8986
2026-04-05 06:10:18,071 - INFO - Epoch 31/100 - Train Loss: 0.1841 - Val Acc: 0.8986
2026-04-05 06:10:18,364 - INFO - Epoch 32/100 - Train Loss: 0.1826 - Val Acc: 0.9130
2026-04-05 06:10:18,651 - INFO - Epoch 33/100 - Train Loss: 0.1812 - Val Acc: 0.9130
2026-04-05 06:10:18,939 - INFO - Epoch 34/100 - Train Loss: 0.1823 - Val Acc: 0.8986
2026-04-05 06:10:19,226 - INFO - Epoch 35/100 - Train Loss: 0.1798 - Val Acc: 0.8986
2026-04-05 06:10:19,504 - INFO - Epoch 36/100 - Train Loss: 0.1785 - Val Acc: 0.9130
2026-04-05 06:10:19,776 - INFO - Epoch 37/100 - Train Loss: 0.1785 - Val Acc: 0.9130
2026-04-05 06:10:20,049 - INFO - Epoch 38/100 - Train Loss: 0.1792 - Val Acc: 0.9130
2026-04-05 06:10:20,332 - INFO - Epoch 39/100 - Train Loss: 0.1754 - Val Acc: 0.8986
2026-04-05 06:10:20,607 - INFO - Epoch 40/100 - Train Loss: 0.1752 - Val Acc: 0.8986
2026-04-05 06:10:20,875 - INFO - Epoch 41/100 - Train Loss: 0.1737 - Val Acc: 0.8986
2026-04-05 06:10:21,145 - INFO - Epoch 42/100 - Train Loss: 0.1726 - Val Acc: 0.9130
2026-04-05 06:10:21,424 - INFO - Epoch 43/100 - Train Loss: 0.1726 - Val Acc: 0.9130
2026-04-05 06:10:21,694 - INFO - Epoch 44/100 - Train Loss: 0.1687 - Val Acc: 0.9130
2026-04-05 06:10:21,973 - INFO - Epoch 45/100 - Train Loss: 0.1695 - Val Acc: 0.8986
2026-04-05 06:10:22,280 - INFO - Epoch 46/100 - Train Loss: 0.1654 - Val Acc: 0.8986
2026-04-05 06:10:22,584 - INFO - Epoch 47/100 - Train Loss: 0.1641 - Val Acc: 0.8986
2026-04-05 06:10:22,863 - INFO - Epoch 48/100 - Train Loss: 0.1643 - Val Acc: 0.8986
2026-04-05 06:10:23,140 - INFO - Epoch 49/100 - Train Loss: 0.1640 - Val Acc: 0.8986
2026-04-05 06:10:23,429 - INFO - Epoch 50/100 - Train Loss: 0.1622 - Val Acc: 0.8986
2026-04-05 06:10:23,705 - INFO - Epoch 51/100 - Train Loss: 0.1623 - Val Acc: 0.8986
2026-04-05 06:10:23,983 - INFO - Epoch 52/100 - Train Loss: 0.1580 - Val Acc: 0.8986
2026-04-05 06:10:24,261 - INFO - Epoch 53/100 - Train Loss: 0.1599 - Val Acc: 0.8696
2026-04-05 06:10:24,566 - INFO - Epoch 54/100 - Train Loss: 0.1599 - Val Acc: 0.8696
2026-04-05 06:10:24,851 - INFO - Epoch 55/100 - Train Loss: 0.1592 - Val Acc: 0.8841
2026-04-05 06:10:25,135 - INFO - Epoch 56/100 - Train Loss: 0.1577 - Val Acc: 0.8841
2026-04-05 06:10:25,417 - INFO - Epoch 57/100 - Train Loss: 0.1542 - Val Acc: 0.8841
2026-04-05 06:10:25,706 - INFO - Epoch 58/100 - Train Loss: 0.1567 - Val Acc: 0.8841
2026-04-05 06:10:25,981 - INFO - Epoch 59/100 - Train Loss: 0.1555 - Val Acc: 0.8551
2026-04-05 06:10:26,265 - INFO - Epoch 60/100 - Train Loss: 0.1529 - Val Acc: 0.8841
2026-04-05 06:10:26,535 - INFO - Epoch 61/100 - Train Loss: 0.1510 - Val Acc: 0.8696
2026-04-05 06:10:26,832 - INFO - Epoch 62/100 - Train Loss: 0.1493 - Val Acc: 0.8986
2026-04-05 06:10:27,108 - INFO - Epoch 63/100 - Train Loss: 0.1518 - Val Acc: 0.8696
2026-04-05 06:10:27,381 - INFO - Epoch 64/100 - Train Loss: 0.1507 - Val Acc: 0.8696
2026-04-05 06:10:27,657 - INFO - Epoch 65/100 - Train Loss: 0.1449 - Val Acc: 0.8841
2026-04-05 06:10:27,932 - INFO - Epoch 66/100 - Train Loss: 0.1430 - Val Acc: 0.8696
2026-04-05 06:10:28,204 - INFO - Epoch 67/100 - Train Loss: 0.1497 - Val Acc: 0.8696
2026-04-05 06:10:28,474 - INFO - Epoch 68/100 - Train Loss: 0.1437 - Val Acc: 0.8551
2026-04-05 06:10:28,741 - INFO - Epoch 69/100 - Train Loss: 0.1443 - Val Acc: 0.8551
2026-04-05 06:10:29,008 - INFO - Epoch 70/100 - Train Loss: 0.1448 - Val Acc: 0.8841
2026-04-05 06:10:29,293 - INFO - Epoch 71/100 - Train Loss: 0.1433 - Val Acc: 0.8841
2026-04-05 06:10:29,577 - INFO - Epoch 72/100 - Train Loss: 0.1451 - Val Acc: 0.8551
2026-04-05 06:10:29,855 - INFO - Epoch 73/100 - Train Loss: 0.1425 - Val Acc: 0.8696
2026-04-05 06:10:30,148 - INFO - Epoch 74/100 - Train Loss: 0.1407 - Val Acc: 0.8696
2026-04-05 06:10:30,436 - INFO - Epoch 75/100 - Train Loss: 0.1452 - Val Acc: 0.8841
2026-04-05 06:10:30,713 - INFO - Epoch 76/100 - Train Loss: 0.1400 - Val Acc: 0.8696
2026-04-05 06:10:30,994 - INFO - Epoch 77/100 - Train Loss: 0.1391 - Val Acc: 0.8696
2026-04-05 06:10:31,261 - INFO - Epoch 78/100 - Train Loss: 0.1385 - Val Acc: 0.8841
2026-04-05 06:10:31,530 - INFO - Epoch 79/100 - Train Loss: 0.1417 - Val Acc: 0.8696
2026-04-05 06:10:31,812 - INFO - Epoch 80/100 - Train Loss: 0.1390 - Val Acc: 0.8696
2026-04-05 06:10:32,083 - INFO - Epoch 81/100 - Train Loss: 0.1342 - Val Acc: 0.8841
2026-04-05 06:10:32,353 - INFO - Epoch 82/100 - Train Loss: 0.1387 - Val Acc: 0.8841
2026-04-05 06:10:32,636 - INFO - Epoch 83/100 - Train Loss: 0.1355 - Val Acc: 0.8841
2026-04-05 06:10:32,914 - INFO - Epoch 84/100 - Train Loss: 0.1360 - Val Acc: 0.8841
2026-04-05 06:10:33,205 - INFO - Epoch 85/100 - Train Loss: 0.1348 - Val Acc: 0.8696
2026-04-05 06:10:33,472 - INFO - Epoch 86/100 - Train Loss: 0.1339 - Val Acc: 0.8696
2026-04-05 06:10:33,756 - INFO - Epoch 87/100 - Train Loss: 0.1337 - Val Acc: 0.8696
2026-04-05 06:10:34,028 - INFO - Epoch 88/100 - Train Loss: 0.1340 - Val Acc: 0.8551
2026-04-05 06:10:34,344 - INFO - Epoch 89/100 - Train Loss: 0.1298 - Val Acc: 0.8696
2026-04-05 06:10:34,656 - INFO - Epoch 90/100 - Train Loss: 0.1270 - Val Acc: 0.8696
2026-04-05 06:10:34,938 - INFO - Epoch 91/100 - Train Loss: 0.1328 - Val Acc: 0.8696
2026-04-05 06:10:35,224 - INFO - Epoch 92/100 - Train Loss: 0.1288 - Val Acc: 0.8841
2026-04-05 06:10:35,515 - INFO - Epoch 93/100 - Train Loss: 0.1290 - Val Acc: 0.8841
2026-04-05 06:10:35,805 - INFO - Epoch 94/100 - Train Loss: 0.1266 - Val Acc: 0.8696
2026-04-05 06:10:36,086 - INFO - Epoch 95/100 - Train Loss: 0.1292 - Val Acc: 0.8841
2026-04-05 06:10:36,367 - INFO - Epoch 96/100 - Train Loss: 0.1303 - Val Acc: 0.8696
2026-04-05 06:10:36,642 - INFO - Epoch 97/100 - Train Loss: 0.1248 - Val Acc: 0.8696
2026-04-05 06:10:36,918 - INFO - Epoch 98/100 - Train Loss: 0.1256 - Val Acc: 0.8841
2026-04-05 06:10:37,211 - INFO - Epoch 99/100 - Train Loss: 0.1286 - Val Acc: 0.8841
2026-04-05 06:10:37,493 - INFO - Epoch 100/100 - Train Loss: 0.1288 - Val Acc: 0.8841
2026-04-05 06:10:37,860 - INFO - Fold 2 logically complete. Tensor memory bounds cleared cleanly.
2026-04-05 06:10:37,865 - INFO - Original class distribution: [344 277]
2026-04-05 06:10:37,866 - INFO - Training device bound securely to: cuda
2026-04-05 06:10:37,893 - INFO - After SMOTE-ENN deployment: [344 290]

Fold 3:   0%|          | 0/100 [00:00<?, ?it/s]

2026-04-05 06:10:38,189 - INFO - Epoch 1/100 - Train Loss: 0.6524 - Val Acc: 0.9565
2026-04-05 06:10:38,458 - INFO - Epoch 2/100 - Train Loss: 0.5587 - Val Acc: 0.9420
2026-04-05 06:10:38,727 - INFO - Epoch 3/100 - Train Loss: 0.4716 - Val Acc: 0.9275
2026-04-05 06:10:38,998 - INFO - Epoch 4/100 - Train Loss: 0.3939 - Val Acc: 0.9275
2026-04-05 06:10:39,291 - INFO - Epoch 5/100 - Train Loss: 0.3375 - Val Acc: 0.9275
2026-04-05 06:10:39,574 - INFO - Epoch 6/100 - Train Loss: 0.2980 - Val Acc: 0.9275
2026-04-05 06:10:39,866 - INFO - Epoch 7/100 - Train Loss: 0.2737 - Val Acc: 0.9275
2026-04-05 06:10:40,148 - INFO - Epoch 8/100 - Train Loss: 0.2563 - Val Acc: 0.9275
2026-04-05 06:10:40,425 - INFO - Epoch 9/100 - Train Loss: 0.2415 - Val Acc: 0.9275
2026-04-05 06:10:40,697 - INFO - Epoch 10/100 - Train Loss: 0.2295 - Val Acc: 0.9420
2026-04-05 06:10:40,967 - INFO - Epoch 11/100 - Train Loss: 0.2221 - Val Acc: 0.9420
2026-04-05 06:10:41,238 - INFO - Epoch 12/100 - Train Loss: 0.2124 - Val Acc: 0.9275
2026-04-05 06:10:41,503 - INFO - Epoch 13/100 - Train Loss: 0.2077 - Val Acc: 0.9275
2026-04-05 06:10:41,771 - INFO - Epoch 14/100 - Train Loss: 0.1987 - Val Acc: 0.9275
2026-04-05 06:10:42,054 - INFO - Epoch 15/100 - Train Loss: 0.1940 - Val Acc: 0.9275
2026-04-05 06:10:42,332 - INFO - Epoch 16/100 - Train Loss: 0.1870 - Val Acc: 0.9275
2026-04-05 06:10:42,608 - INFO - Epoch 17/100 - Train Loss: 0.1845 - Val Acc: 0.9275
2026-04-05 06:10:42,888 - INFO - Epoch 18/100 - Train Loss: 0.1829 - Val Acc: 0.9275
2026-04-05 06:10:43,161 - INFO - Epoch 19/100 - Train Loss: 0.1818 - Val Acc: 0.9275
2026-04-05 06:10:43,441 - INFO - Epoch 20/100 - Train Loss: 0.1767 - Val Acc: 0.9275
2026-04-05 06:10:43,729 - INFO - Epoch 21/100 - Train Loss: 0.1750 - Val Acc: 0.9275
2026-04-05 06:10:44,016 - INFO - Epoch 22/100 - Train Loss: 0.1740 - Val Acc: 0.9275
2026-04-05 06:10:44,287 - INFO - Epoch 23/100 - Train Loss: 0.1730 - Val Acc: 0.9130
2026-04-05 06:10:44,584 - INFO - Epoch 24/100 - Train Loss: 0.1713 - Val Acc: 0.9130
2026-04-05 06:10:44,881 - INFO - Epoch 25/100 - Train Loss: 0.1687 - Val Acc: 0.9275
2026-04-05 06:10:45,166 - INFO - Epoch 26/100 - Train Loss: 0.1693 - Val Acc: 0.9130
2026-04-05 06:10:45,455 - INFO - Epoch 27/100 - Train Loss: 0.1654 - Val Acc: 0.9130
2026-04-05 06:10:45,728 - INFO - Epoch 28/100 - Train Loss: 0.1649 - Val Acc: 0.9130
2026-04-05 06:10:46,009 - INFO - Epoch 29/100 - Train Loss: 0.1640 - Val Acc: 0.9130
2026-04-05 06:10:46,282 - INFO - Epoch 30/100 - Train Loss: 0.1624 - Val Acc: 0.9130
2026-04-05 06:10:46,561 - INFO - Epoch 31/100 - Train Loss: 0.1633 - Val Acc: 0.9130
2026-04-05 06:10:46,846 - INFO - Epoch 32/100 - Train Loss: 0.1636 - Val Acc: 0.9130
2026-04-05 06:10:47,107 - INFO - Epoch 33/100 - Train Loss: 0.1608 - Val Acc: 0.9130
2026-04-05 06:10:47,401 - INFO - Epoch 34/100 - Train Loss: 0.1605 - Val Acc: 0.9130
2026-04-05 06:10:47,681 - INFO - Epoch 35/100 - Train Loss: 0.1593 - Val Acc: 0.9130
2026-04-05 06:10:47,967 - INFO - Epoch 36/100 - Train Loss: 0.1571 - Val Acc: 0.9130
2026-04-05 06:10:48,250 - INFO - Epoch 37/100 - Train Loss: 0.1575 - Val Acc: 0.9130
2026-04-05 06:10:48,524 - INFO - Epoch 38/100 - Train Loss: 0.1556 - Val Acc: 0.9130
2026-04-05 06:10:48,810 - INFO - Epoch 39/100 - Train Loss: 0.1547 - Val Acc: 0.9130
2026-04-05 06:10:49,087 - INFO - Epoch 40/100 - Train Loss: 0.1562 - Val Acc: 0.9130
2026-04-05 06:10:49,368 - INFO - Epoch 41/100 - Train Loss: 0.1547 - Val Acc: 0.9130
2026-04-05 06:10:49,651 - INFO - Epoch 42/100 - Train Loss: 0.1540 - Val Acc: 0.9130
2026-04-05 06:10:49,923 - INFO - Epoch 43/100 - Train Loss: 0.1531 - Val Acc: 0.9130
2026-04-05 06:10:50,194 - INFO - Epoch 44/100 - Train Loss: 0.1509 - Val Acc: 0.9130
2026-04-05 06:10:50,469 - INFO - Epoch 45/100 - Train Loss: 0.1490 - Val Acc: 0.9130
2026-04-05 06:10:50,739 - INFO - Epoch 46/100 - Train Loss: 0.1477 - Val Acc: 0.9130
2026-04-05 06:10:51,006 - INFO - Epoch 47/100 - Train Loss: 0.1481 - Val Acc: 0.9130
2026-04-05 06:10:51,282 - INFO - Epoch 48/100 - Train Loss: 0.1480 - Val Acc: 0.9130
2026-04-05 06:10:51,554 - INFO - Epoch 49/100 - Train Loss: 0.1446 - Val Acc: 0.9130
2026-04-05 06:10:51,829 - INFO - Epoch 50/100 - Train Loss: 0.1486 - Val Acc: 0.9130
2026-04-05 06:10:52,101 - INFO - Epoch 51/100 - Train Loss: 0.1455 - Val Acc: 0.9130
2026-04-05 06:10:52,377 - INFO - Epoch 52/100 - Train Loss: 0.1424 - Val Acc: 0.9130
2026-04-05 06:10:52,648 - INFO - Epoch 53/100 - Train Loss: 0.1447 - Val Acc: 0.9130
2026-04-05 06:10:52,932 - INFO - Epoch 54/100 - Train Loss: 0.1398 - Val Acc: 0.9130
2026-04-05 06:10:53,217 - INFO - Epoch 55/100 - Train Loss: 0.1390 - Val Acc: 0.9130
2026-04-05 06:10:53,491 - INFO - Epoch 56/100 - Train Loss: 0.1387 - Val Acc: 0.9130
2026-04-05 06:10:53,765 - INFO - Epoch 57/100 - Train Loss: 0.1398 - Val Acc: 0.9130
2026-04-05 06:10:54,036 - INFO - Epoch 58/100 - Train Loss: 0.1394 - Val Acc: 0.9130
2026-04-05 06:10:54,321 - INFO - Epoch 59/100 - Train Loss: 0.1382 - Val Acc: 0.9130
2026-04-05 06:10:54,619 - INFO - Epoch 60/100 - Train Loss: 0.1368 - Val Acc: 0.9130
2026-04-05 06:10:54,884 - INFO - Epoch 61/100 - Train Loss: 0.1350 - Val Acc: 0.9130
2026-04-05 06:10:55,175 - INFO - Epoch 62/100 - Train Loss: 0.1333 - Val Acc: 0.9130
2026-04-05 06:10:55,470 - INFO - Epoch 63/100 - Train Loss: 0.1347 - Val Acc: 0.9130
2026-04-05 06:10:55,742 - INFO - Epoch 64/100 - Train Loss: 0.1327 - Val Acc: 0.9130
2026-04-05 06:10:56,017 - INFO - Epoch 65/100 - Train Loss: 0.1323 - Val Acc: 0.9130
2026-04-05 06:10:56,289 - INFO - Epoch 66/100 - Train Loss: 0.1287 - Val Acc: 0.9130
2026-04-05 06:10:56,564 - INFO - Epoch 67/100 - Train Loss: 0.1318 - Val Acc: 0.9130
2026-04-05 06:10:56,842 - INFO - Epoch 68/100 - Train Loss: 0.1308 - Val Acc: 0.9130
2026-04-05 06:10:57,116 - INFO - Epoch 69/100 - Train Loss: 0.1311 - Val Acc: 0.9130
2026-04-05 06:10:57,392 - INFO - Epoch 70/100 - Train Loss: 0.1274 - Val Acc: 0.9130
2026-04-05 06:10:57,665 - INFO - Epoch 71/100 - Train Loss: 0.1294 - Val Acc: 0.9130
2026-04-05 06:10:57,947 - INFO - Epoch 72/100 - Train Loss: 0.1293 - Val Acc: 0.9130
2026-04-05 06:10:58,230 - INFO - Epoch 73/100 - Train Loss: 0.1261 - Val Acc: 0.9130
2026-04-05 06:10:58,511 - INFO - Epoch 74/100 - Train Loss: 0.1216 - Val Acc: 0.9130
2026-04-05 06:10:58,800 - INFO - Epoch 75/100 - Train Loss: 0.1230 - Val Acc: 0.9130
2026-04-05 06:10:59,072 - INFO - Epoch 76/100 - Train Loss: 0.1281 - Val Acc: 0.9130
2026-04-05 06:10:59,340 - INFO - Epoch 77/100 - Train Loss: 0.1205 - Val Acc: 0.9130
2026-04-05 06:10:59,599 - INFO - Epoch 78/100 - Train Loss: 0.1221 - Val Acc: 0.9275
2026-04-05 06:10:59,878 - INFO - Epoch 79/100 - Train Loss: 0.1214 - Val Acc: 0.9275
2026-04-05 06:11:00,149 - INFO - Epoch 80/100 - Train Loss: 0.1213 - Val Acc: 0.9275
2026-04-05 06:11:00,445 - INFO - Epoch 81/100 - Train Loss: 0.1206 - Val Acc: 0.9130
2026-04-05 06:11:00,711 - INFO - Epoch 82/100 - Train Loss: 0.1185 - Val Acc: 0.9275
2026-04-05 06:11:00,990 - INFO - Epoch 83/100 - Train Loss: 0.1172 - Val Acc: 0.9275
2026-04-05 06:11:01,266 - INFO - Epoch 84/100 - Train Loss: 0.1201 - Val Acc: 0.9275
2026-04-05 06:11:01,532 - INFO - Epoch 85/100 - Train Loss: 0.1193 - Val Acc: 0.9275
2026-04-05 06:11:01,807 - INFO - Epoch 86/100 - Train Loss: 0.1181 - Val Acc: 0.9275
2026-04-05 06:11:02,097 - INFO - Epoch 87/100 - Train Loss: 0.1135 - Val Acc: 0.9275
2026-04-05 06:11:02,373 - INFO - Epoch 88/100 - Train Loss: 0.1145 - Val Acc: 0.9275
2026-04-05 06:11:02,643 - INFO - Epoch 89/100 - Train Loss: 0.1137 - Val Acc: 0.9275
2026-04-05 06:11:02,916 - INFO - Epoch 90/100 - Train Loss: 0.1126 - Val Acc: 0.9275
2026-04-05 06:11:03,181 - INFO - Epoch 91/100 - Train Loss: 0.1125 - Val Acc: 0.9275
2026-04-05 06:11:03,456 - INFO - Epoch 92/100 - Train Loss: 0.1103 - Val Acc: 0.9275
2026-04-05 06:11:03,728 - INFO - Epoch 93/100 - Train Loss: 0.1083 - Val Acc: 0.9275
2026-04-05 06:11:04,020 - INFO - Epoch 94/100 - Train Loss: 0.1117 - Val Acc: 0.9275
2026-04-05 06:11:04,303 - INFO - Epoch 95/100 - Train Loss: 0.1091 - Val Acc: 0.9275
2026-04-05 06:11:04,606 - INFO - Epoch 96/100 - Train Loss: 0.1106 - Val Acc: 0.9275
2026-04-05 06:11:04,879 - INFO - Epoch 97/100 - Train Loss: 0.1106 - Val Acc: 0.9275
2026-04-05 06:11:05,167 - INFO - Epoch 98/100 - Train Loss: 0.1067 - Val Acc: 0.9275
2026-04-05 06:11:05,462 - INFO - Epoch 99/100 - Train Loss: 0.1079 - Val Acc: 0.9275
2026-04-05 06:11:05,731 - INFO - Epoch 100/100 - Train Loss: 0.1063 - Val Acc: 0.9275
2026-04-05 06:11:06,114 - INFO - Fold 3 logically complete. Tensor memory bounds cleared cleanly.
2026-04-05 06:11:06,119 - INFO - Original class distribution: [345 276]
2026-04-05 06:11:06,119 - INFO - Training device bound securely to: cuda
2026-04-05 06:11:06,148 - INFO - After SMOTE-ENN deployment: [345 299]

Fold 4:   0%|          | 0/100 [00:00<?, ?it/s]

2026-04-05 06:11:06,456 - INFO - Epoch 1/100 - Train Loss: 0.6572 - Val Acc: 0.7681
2026-04-05 06:11:06,744 - INFO - Epoch 2/100 - Train Loss: 0.5603 - Val Acc: 0.7681
2026-04-05 06:11:07,028 - INFO - Epoch 3/100 - Train Loss: 0.4728 - Val Acc: 0.7681
2026-04-05 06:11:07,303 - INFO - Epoch 4/100 - Train Loss: 0.3935 - Val Acc: 0.7681
2026-04-05 06:11:07,590 - INFO - Epoch 5/100 - Train Loss: 0.3362 - Val Acc: 0.7681
2026-04-05 06:11:07,861 - INFO - Epoch 6/100 - Train Loss: 0.2950 - Val Acc: 0.7681
2026-04-05 06:11:08,132 - INFO - Epoch 7/100 - Train Loss: 0.2699 - Val Acc: 0.7681
2026-04-05 06:11:08,415 - INFO - Epoch 8/100 - Train Loss: 0.2533 - Val Acc: 0.7826
2026-04-05 06:11:08,696 - INFO - Epoch 9/100 - Train Loss: 0.2427 - Val Acc: 0.8116
2026-04-05 06:11:08,972 - INFO - Epoch 10/100 - Train Loss: 0.2284 - Val Acc: 0.7971
2026-04-05 06:11:09,258 - INFO - Epoch 11/100 - Train Loss: 0.2201 - Val Acc: 0.7971
2026-04-05 06:11:09,544 - INFO - Epoch 12/100 - Train Loss: 0.2146 - Val Acc: 0.7971
2026-04-05 06:11:09,841 - INFO - Epoch 13/100 - Train Loss: 0.2095 - Val Acc: 0.7971
2026-04-05 06:11:10,123 - INFO - Epoch 14/100 - Train Loss: 0.2042 - Val Acc: 0.7971
2026-04-05 06:11:10,400 - INFO - Epoch 15/100 - Train Loss: 0.2002 - Val Acc: 0.7971
2026-04-05 06:11:10,673 - INFO - Epoch 16/100 - Train Loss: 0.1950 - Val Acc: 0.7971
2026-04-05 06:11:10,953 - INFO - Epoch 17/100 - Train Loss: 0.1935 - Val Acc: 0.7971
2026-04-05 06:11:11,240 - INFO - Epoch 18/100 - Train Loss: 0.1913 - Val Acc: 0.7971
2026-04-05 06:11:11,515 - INFO - Epoch 19/100 - Train Loss: 0.1895 - Val Acc: 0.7971
2026-04-05 06:11:11,798 - INFO - Epoch 20/100 - Train Loss: 0.1890 - Val Acc: 0.7971
2026-04-05 06:11:12,082 - INFO - Epoch 21/100 - Train Loss: 0.1857 - Val Acc: 0.7971
2026-04-05 06:11:12,366 - INFO - Epoch 22/100 - Train Loss: 0.1830 - Val Acc: 0.7971
2026-04-05 06:11:12,656 - INFO - Epoch 23/100 - Train Loss: 0.1848 - Val Acc: 0.7971
2026-04-05 06:11:12,941 - INFO - Epoch 24/100 - Train Loss: 0.1820 - Val Acc: 0.7971
2026-04-05 06:11:13,222 - INFO - Epoch 25/100 - Train Loss: 0.1801 - Val Acc: 0.7826
2026-04-05 06:11:13,507 - INFO - Epoch 26/100 - Train Loss: 0.1805 - Val Acc: 0.7826
2026-04-05 06:11:13,793 - INFO - Epoch 27/100 - Train Loss: 0.1792 - Val Acc: 0.7681
2026-04-05 06:11:14,074 - INFO - Epoch 28/100 - Train Loss: 0.1784 - Val Acc: 0.7971
2026-04-05 06:11:14,352 - INFO - Epoch 29/100 - Train Loss: 0.1790 - Val Acc: 0.7971
2026-04-05 06:11:14,660 - INFO - Epoch 30/100 - Train Loss: 0.1788 - Val Acc: 0.7971
2026-04-05 06:11:14,937 - INFO - Epoch 31/100 - Train Loss: 0.1772 - Val Acc: 0.7681
2026-04-05 06:11:15,223 - INFO - Epoch 32/100 - Train Loss: 0.1781 - Val Acc: 0.7826
2026-04-05 06:11:15,517 - INFO - Epoch 33/100 - Train Loss: 0.1763 - Val Acc: 0.7826
2026-04-05 06:11:15,791 - INFO - Epoch 34/100 - Train Loss: 0.1759 - Val Acc: 0.7681
2026-04-05 06:11:16,066 - INFO - Epoch 35/100 - Train Loss: 0.1737 - Val Acc: 0.7681
2026-04-05 06:11:16,346 - INFO - Epoch 36/100 - Train Loss: 0.1729 - Val Acc: 0.7681
2026-04-05 06:11:16,630 - INFO - Epoch 37/100 - Train Loss: 0.1738 - Val Acc: 0.7826
2026-04-05 06:11:16,917 - INFO - Epoch 38/100 - Train Loss: 0.1720 - Val Acc: 0.7826
2026-04-05 06:11:17,194 - INFO - Epoch 39/100 - Train Loss: 0.1740 - Val Acc: 0.7826
2026-04-05 06:11:17,463 - INFO - Epoch 40/100 - Train Loss: 0.1714 - Val Acc: 0.7826
2026-04-05 06:11:17,756 - INFO - Epoch 41/100 - Train Loss: 0.1722 - Val Acc: 0.7826
2026-04-05 06:11:18,028 - INFO - Epoch 42/100 - Train Loss: 0.1707 - Val Acc: 0.7826
2026-04-05 06:11:18,309 - INFO - Epoch 43/100 - Train Loss: 0.1681 - Val Acc: 0.7826
2026-04-05 06:11:18,588 - INFO - Epoch 44/100 - Train Loss: 0.1685 - Val Acc: 0.7681
2026-04-05 06:11:18,861 - INFO - Epoch 45/100 - Train Loss: 0.1672 - Val Acc: 0.7826
2026-04-05 06:11:19,160 - INFO - Epoch 46/100 - Train Loss: 0.1651 - Val Acc: 0.7826
2026-04-05 06:11:19,447 - INFO - Epoch 47/100 - Train Loss: 0.1676 - Val Acc: 0.7971
2026-04-05 06:11:19,721 - INFO - Epoch 48/100 - Train Loss: 0.1643 - Val Acc: 0.7971
2026-04-05 06:11:19,997 - INFO - Epoch 49/100 - Train Loss: 0.1638 - Val Acc: 0.7826
2026-04-05 06:11:20,287 - INFO - Epoch 50/100 - Train Loss: 0.1659 - Val Acc: 0.7971
2026-04-05 06:11:20,581 - INFO - Epoch 51/100 - Train Loss: 0.1649 - Val Acc: 0.7826
2026-04-05 06:11:20,868 - INFO - Epoch 52/100 - Train Loss: 0.1646 - Val Acc: 0.7826
2026-04-05 06:11:21,141 - INFO - Epoch 53/100 - Train Loss: 0.1662 - Val Acc: 0.7826
2026-04-05 06:11:21,436 - INFO - Epoch 54/100 - Train Loss: 0.1651 - Val Acc: 0.7826
2026-04-05 06:11:21,711 - INFO - Epoch 55/100 - Train Loss: 0.1659 - Val Acc: 0.7826
2026-04-05 06:11:21,992 - INFO - Epoch 56/100 - Train Loss: 0.1613 - Val Acc: 0.7826
2026-04-05 06:11:22,272 - INFO - Epoch 57/100 - Train Loss: 0.1640 - Val Acc: 0.7826
2026-04-05 06:11:22,553 - INFO - Epoch 58/100 - Train Loss: 0.1600 - Val Acc: 0.7826
2026-04-05 06:11:22,847 - INFO - Epoch 59/100 - Train Loss: 0.1599 - Val Acc: 0.7826
2026-04-05 06:11:23,137 - INFO - Epoch 60/100 - Train Loss: 0.1588 - Val Acc: 0.8116
2026-04-05 06:11:23,409 - INFO - Epoch 61/100 - Train Loss: 0.1567 - Val Acc: 0.8116
2026-04-05 06:11:23,684 - INFO - Epoch 62/100 - Train Loss: 0.1579 - Val Acc: 0.8261
2026-04-05 06:11:23,963 - INFO - Epoch 63/100 - Train Loss: 0.1605 - Val Acc: 0.8261
2026-04-05 06:11:24,246 - INFO - Epoch 64/100 - Train Loss: 0.1573 - Val Acc: 0.8261
2026-04-05 06:11:24,538 - INFO - Epoch 65/100 - Train Loss: 0.1570 - Val Acc: 0.8116
2026-04-05 06:11:24,835 - INFO - Epoch 66/100 - Train Loss: 0.1538 - Val Acc: 0.8116
2026-04-05 06:11:25,121 - INFO - Epoch 67/100 - Train Loss: 0.1555 - Val Acc: 0.8116
2026-04-05 06:11:25,412 - INFO - Epoch 68/100 - Train Loss: 0.1578 - Val Acc: 0.8116
2026-04-05 06:11:25,690 - INFO - Epoch 69/100 - Train Loss: 0.1542 - Val Acc: 0.8116
2026-04-05 06:11:25,967 - INFO - Epoch 70/100 - Train Loss: 0.1546 - Val Acc: 0.8116
2026-04-05 06:11:26,240 - INFO - Epoch 71/100 - Train Loss: 0.1502 - Val Acc: 0.8116
2026-04-05 06:11:26,526 - INFO - Epoch 72/100 - Train Loss: 0.1519 - Val Acc: 0.8116
2026-04-05 06:11:26,814 - INFO - Epoch 73/100 - Train Loss: 0.1527 - Val Acc: 0.7971
2026-04-05 06:11:27,084 - INFO - Epoch 74/100 - Train Loss: 0.1503 - Val Acc: 0.8116
2026-04-05 06:11:27,361 - INFO - Epoch 75/100 - Train Loss: 0.1488 - Val Acc: 0.7971
2026-04-05 06:11:27,644 - INFO - Epoch 76/100 - Train Loss: 0.1473 - Val Acc: 0.8116
2026-04-05 06:11:27,927 - INFO - Epoch 77/100 - Train Loss: 0.1490 - Val Acc: 0.8261
2026-04-05 06:11:28,210 - INFO - Epoch 78/100 - Train Loss: 0.1505 - Val Acc: 0.8261
2026-04-05 06:11:28,516 - INFO - Epoch 79/100 - Train Loss: 0.1469 - Val Acc: 0.8261
2026-04-05 06:11:28,799 - INFO - Epoch 80/100 - Train Loss: 0.1458 - Val Acc: 0.8261
2026-04-05 06:11:29,078 - INFO - Epoch 81/100 - Train Loss: 0.1455 - Val Acc: 0.8116
2026-04-05 06:11:29,355 - INFO - Epoch 82/100 - Train Loss: 0.1432 - Val Acc: 0.8116
2026-04-05 06:11:29,634 - INFO - Epoch 83/100 - Train Loss: 0.1427 - Val Acc: 0.8116
2026-04-05 06:11:29,908 - INFO - Epoch 84/100 - Train Loss: 0.1427 - Val Acc: 0.8116
2026-04-05 06:11:30,191 - INFO - Epoch 85/100 - Train Loss: 0.1450 - Val Acc: 0.8116
2026-04-05 06:11:30,474 - INFO - Epoch 86/100 - Train Loss: 0.1446 - Val Acc: 0.8116
2026-04-05 06:11:30,772 - INFO - Epoch 87/100 - Train Loss: 0.1430 - Val Acc: 0.8116
2026-04-05 06:11:31,056 - INFO - Epoch 88/100 - Train Loss: 0.1445 - Val Acc: 0.8116
2026-04-05 06:11:31,344 - INFO - Epoch 89/100 - Train Loss: 0.1408 - Val Acc: 0.8116
2026-04-05 06:11:31,632 - INFO - Epoch 90/100 - Train Loss: 0.1385 - Val Acc: 0.8116
2026-04-05 06:11:31,917 - INFO - Epoch 91/100 - Train Loss: 0.1400 - Val Acc: 0.8116
2026-04-05 06:11:32,191 - INFO - Epoch 92/100 - Train Loss: 0.1407 - Val Acc: 0.8116
2026-04-05 06:11:32,460 - INFO - Epoch 93/100 - Train Loss: 0.1419 - Val Acc: 0.8116
2026-04-05 06:11:32,738 - INFO - Epoch 94/100 - Train Loss: 0.1445 - Val Acc: 0.8116
2026-04-05 06:11:33,018 - INFO - Epoch 95/100 - Train Loss: 0.1396 - Val Acc: 0.8116
2026-04-05 06:11:33,305 - INFO - Epoch 96/100 - Train Loss: 0.1352 - Val Acc: 0.8116
2026-04-05 06:11:33,586 - INFO - Epoch 97/100 - Train Loss: 0.1366 - Val Acc: 0.8116
2026-04-05 06:11:33,869 - INFO - Epoch 98/100 - Train Loss: 0.1347 - Val Acc: 0.8116
2026-04-05 06:11:34,150 - INFO - Epoch 99/100 - Train Loss: 0.1353 - Val Acc: 0.8116
2026-04-05 06:11:34,450 - INFO - Epoch 100/100 - Train Loss: 0.1375 - Val Acc: 0.8116
2026-04-05 06:11:34,848 - INFO - Fold 4 logically complete. Tensor memory bounds cleared cleanly.
2026-04-05 06:11:34,852 - INFO - Original class distribution: [345 276]
2026-04-05 06:11:34,853 - INFO - Training device bound securely to: cuda
2026-04-05 06:11:34,881 - INFO - After SMOTE-ENN deployment: [345 305]

Fold 5:   0%|          | 0/100 [00:00<?, ?it/s]

2026-04-05 06:11:35,169 - INFO - Epoch 1/100 - Train Loss: 0.6532 - Val Acc: 0.7826
2026-04-05 06:11:35,438 - INFO - Epoch 2/100 - Train Loss: 0.5564 - Val Acc: 0.8116
2026-04-05 06:11:35,734 - INFO - Epoch 3/100 - Train Loss: 0.4662 - Val Acc: 0.8406
2026-04-05 06:11:36,032 - INFO - Epoch 4/100 - Train Loss: 0.3864 - Val Acc: 0.8406
2026-04-05 06:11:36,313 - INFO - Epoch 5/100 - Train Loss: 0.3306 - Val Acc: 0.8551
2026-04-05 06:11:36,595 - INFO - Epoch 6/100 - Train Loss: 0.2941 - Val Acc: 0.8406
2026-04-05 06:11:36,880 - INFO - Epoch 7/100 - Train Loss: 0.2699 - Val Acc: 0.8551
2026-04-05 06:11:37,155 - INFO - Epoch 8/100 - Train Loss: 0.2532 - Val Acc: 0.8551
2026-04-05 06:11:37,444 - INFO - Epoch 9/100 - Train Loss: 0.2378 - Val Acc: 0.8696
2026-04-05 06:11:37,716 - INFO - Epoch 10/100 - Train Loss: 0.2287 - Val Acc: 0.8696
2026-04-05 06:11:37,995 - INFO - Epoch 11/100 - Train Loss: 0.2209 - Val Acc: 0.8696
2026-04-05 06:11:38,266 - INFO - Epoch 12/100 - Train Loss: 0.2150 - Val Acc: 0.8696
2026-04-05 06:11:38,538 - INFO - Epoch 13/100 - Train Loss: 0.2082 - Val Acc: 0.8696
2026-04-05 06:11:38,826 - INFO - Epoch 14/100 - Train Loss: 0.2025 - Val Acc: 0.8696
2026-04-05 06:11:39,119 - INFO - Epoch 15/100 - Train Loss: 0.1977 - Val Acc: 0.8696
2026-04-05 06:11:39,393 - INFO - Epoch 16/100 - Train Loss: 0.1945 - Val Acc: 0.8696
2026-04-05 06:11:39,669 - INFO - Epoch 17/100 - Train Loss: 0.1890 - Val Acc: 0.8696
2026-04-05 06:11:39,952 - INFO - Epoch 18/100 - Train Loss: 0.1881 - Val Acc: 0.8551
2026-04-05 06:11:40,230 - INFO - Epoch 19/100 - Train Loss: 0.1870 - Val Acc: 0.8551
2026-04-05 06:11:40,513 - INFO - Epoch 20/100 - Train Loss: 0.1828 - Val Acc: 0.8406
2026-04-05 06:11:40,797 - INFO - Epoch 21/100 - Train Loss: 0.1829 - Val Acc: 0.8406
2026-04-05 06:11:41,079 - INFO - Epoch 22/100 - Train Loss: 0.1783 - Val Acc: 0.8696
2026-04-05 06:11:41,356 - INFO - Epoch 23/100 - Train Loss: 0.1797 - Val Acc: 0.8406
2026-04-05 06:11:41,653 - INFO - Epoch 24/100 - Train Loss: 0.1748 - Val Acc: 0.8551
2026-04-05 06:11:41,955 - INFO - Epoch 25/100 - Train Loss: 0.1768 - Val Acc: 0.8406
2026-04-05 06:11:42,235 - INFO - Epoch 26/100 - Train Loss: 0.1733 - Val Acc: 0.8406
2026-04-05 06:11:42,528 - INFO - Epoch 27/100 - Train Loss: 0.1742 - Val Acc: 0.8406
2026-04-05 06:11:42,822 - INFO - Epoch 28/100 - Train Loss: 0.1718 - Val Acc: 0.8551
2026-04-05 06:11:43,119 - INFO - Epoch 29/100 - Train Loss: 0.1692 - Val Acc: 0.8551
2026-04-05 06:11:43,399 - INFO - Epoch 30/100 - Train Loss: 0.1696 - Val Acc: 0.8551
2026-04-05 06:11:43,687 - INFO - Epoch 31/100 - Train Loss: 0.1667 - Val Acc: 0.8551
2026-04-05 06:11:43,982 - INFO - Epoch 32/100 - Train Loss: 0.1691 - Val Acc: 0.8551
2026-04-05 06:11:44,277 - INFO - Epoch 33/100 - Train Loss: 0.1665 - Val Acc: 0.8551
2026-04-05 06:11:44,597 - INFO - Epoch 34/100 - Train Loss: 0.1662 - Val Acc: 0.8551
2026-04-05 06:11:44,898 - INFO - Epoch 35/100 - Train Loss: 0.1657 - Val Acc: 0.8551
2026-04-05 06:11:45,177 - INFO - Epoch 36/100 - Train Loss: 0.1641 - Val Acc: 0.8551
2026-04-05 06:11:45,463 - INFO - Epoch 37/100 - Train Loss: 0.1624 - Val Acc: 0.8551
2026-04-05 06:11:45,757 - INFO - Epoch 38/100 - Train Loss: 0.1610 - Val Acc: 0.8551
2026-04-05 06:11:46,040 - INFO - Epoch 39/100 - Train Loss: 0.1618 - Val Acc: 0.8551
2026-04-05 06:11:46,320 - INFO - Epoch 40/100 - Train Loss: 0.1600 - Val Acc: 0.8551
2026-04-05 06:11:46,615 - INFO - Epoch 41/100 - Train Loss: 0.1596 - Val Acc: 0.8551
2026-04-05 06:11:46,903 - INFO - Epoch 42/100 - Train Loss: 0.1578 - Val Acc: 0.8551
2026-04-05 06:11:47,177 - INFO - Epoch 43/100 - Train Loss: 0.1584 - Val Acc: 0.8551
2026-04-05 06:11:47,467 - INFO - Epoch 44/100 - Train Loss: 0.1580 - Val Acc: 0.8406
2026-04-05 06:11:47,744 - INFO - Epoch 45/100 - Train Loss: 0.1554 - Val Acc: 0.8551
2026-04-05 06:11:48,022 - INFO - Epoch 46/100 - Train Loss: 0.1579 - Val Acc: 0.8551
2026-04-05 06:11:48,297 - INFO - Epoch 47/100 - Train Loss: 0.1544 - Val Acc: 0.8551
2026-04-05 06:11:48,580 - INFO - Epoch 48/100 - Train Loss: 0.1537 - Val Acc: 0.8551
2026-04-05 06:11:48,858 - INFO - Epoch 49/100 - Train Loss: 0.1506 - Val Acc: 0.8551
2026-04-05 06:11:49,135 - INFO - Epoch 50/100 - Train Loss: 0.1531 - Val Acc: 0.8551
2026-04-05 06:11:49,429 - INFO - Epoch 51/100 - Train Loss: 0.1511 - Val Acc: 0.8551
2026-04-05 06:11:49,709 - INFO - Epoch 52/100 - Train Loss: 0.1500 - Val Acc: 0.8551
2026-04-05 06:11:49,987 - INFO - Epoch 53/100 - Train Loss: 0.1493 - Val Acc: 0.8551
2026-04-05 06:11:50,268 - INFO - Epoch 54/100 - Train Loss: 0.1473 - Val Acc: 0.8551
2026-04-05 06:11:50,552 - INFO - Epoch 55/100 - Train Loss: 0.1485 - Val Acc: 0.8551
2026-04-05 06:11:50,835 - INFO - Epoch 56/100 - Train Loss: 0.1476 - Val Acc: 0.8551
2026-04-05 06:11:51,110 - INFO - Epoch 57/100 - Train Loss: 0.1462 - Val Acc: 0.8261
2026-04-05 06:11:51,398 - INFO - Epoch 58/100 - Train Loss: 0.1481 - Val Acc: 0.8406
2026-04-05 06:11:51,675 - INFO - Epoch 59/100 - Train Loss: 0.1467 - Val Acc: 0.8406
2026-04-05 06:11:51,952 - INFO - Epoch 60/100 - Train Loss: 0.1439 - Val Acc: 0.8551
2026-04-05 06:11:52,234 - INFO - Epoch 61/100 - Train Loss: 0.1432 - Val Acc: 0.8551
2026-04-05 06:11:52,523 - INFO - Epoch 62/100 - Train Loss: 0.1412 - Val Acc: 0.8551
2026-04-05 06:11:52,808 - INFO - Epoch 63/100 - Train Loss: 0.1389 - Val Acc: 0.8406
2026-04-05 06:11:53,090 - INFO - Epoch 64/100 - Train Loss: 0.1405 - Val Acc: 0.8406
2026-04-05 06:11:53,377 - INFO - Epoch 65/100 - Train Loss: 0.1368 - Val Acc: 0.8261
2026-04-05 06:11:53,650 - INFO - Epoch 66/100 - Train Loss: 0.1393 - Val Acc: 0.8406
2026-04-05 06:11:53,931 - INFO - Epoch 67/100 - Train Loss: 0.1379 - Val Acc: 0.8406
2026-04-05 06:11:54,221 - INFO - Epoch 68/100 - Train Loss: 0.1365 - Val Acc: 0.8406
2026-04-05 06:11:54,538 - INFO - Epoch 69/100 - Train Loss: 0.1344 - Val Acc: 0.8551
2026-04-05 06:11:54,832 - INFO - Epoch 70/100 - Train Loss: 0.1330 - Val Acc: 0.8551
2026-04-05 06:11:55,113 - INFO - Epoch 71/100 - Train Loss: 0.1383 - Val Acc: 0.8551
2026-04-05 06:11:55,396 - INFO - Epoch 72/100 - Train Loss: 0.1348 - Val Acc: 0.8406
2026-04-05 06:11:55,665 - INFO - Epoch 73/100 - Train Loss: 0.1349 - Val Acc: 0.8406
2026-04-05 06:11:55,953 - INFO - Epoch 74/100 - Train Loss: 0.1319 - Val Acc: 0.8551
2026-04-05 06:11:56,245 - INFO - Epoch 75/100 - Train Loss: 0.1332 - Val Acc: 0.8551
2026-04-05 06:11:56,531 - INFO - Epoch 76/100 - Train Loss: 0.1329 - Val Acc: 0.8406
2026-04-05 06:11:56,812 - INFO - Epoch 77/100 - Train Loss: 0.1324 - Val Acc: 0.8406
2026-04-05 06:11:57,102 - INFO - Epoch 78/100 - Train Loss: 0.1318 - Val Acc: 0.8406
2026-04-05 06:11:57,382 - INFO - Epoch 79/100 - Train Loss: 0.1280 - Val Acc: 0.8406
2026-04-05 06:11:57,668 - INFO - Epoch 80/100 - Train Loss: 0.1303 - Val Acc: 0.8406
2026-04-05 06:11:57,952 - INFO - Epoch 81/100 - Train Loss: 0.1279 - Val Acc: 0.8406
2026-04-05 06:11:58,228 - INFO - Epoch 82/100 - Train Loss: 0.1249 - Val Acc: 0.8406
2026-04-05 06:11:58,516 - INFO - Epoch 83/100 - Train Loss: 0.1266 - Val Acc: 0.8406
2026-04-05 06:11:58,809 - INFO - Epoch 84/100 - Train Loss: 0.1276 - Val Acc: 0.8406
2026-04-05 06:11:59,087 - INFO - Epoch 85/100 - Train Loss: 0.1225 - Val Acc: 0.8406
2026-04-05 06:11:59,361 - INFO - Epoch 86/100 - Train Loss: 0.1246 - Val Acc: 0.8406
2026-04-05 06:11:59,646 - INFO - Epoch 87/100 - Train Loss: 0.1305 - Val Acc: 0.8406
2026-04-05 06:11:59,922 - INFO - Epoch 88/100 - Train Loss: 0.1257 - Val Acc: 0.8406
2026-04-05 06:12:00,196 - INFO - Epoch 89/100 - Train Loss: 0.1265 - Val Acc: 0.8406
2026-04-05 06:12:00,476 - INFO - Epoch 90/100 - Train Loss: 0.1239 - Val Acc: 0.8696
2026-04-05 06:12:00,764 - INFO - Epoch 91/100 - Train Loss: 0.1230 - Val Acc: 0.8551
2026-04-05 06:12:01,062 - INFO - Epoch 92/100 - Train Loss: 0.1242 - Val Acc: 0.8261
2026-04-05 06:12:01,343 - INFO - Epoch 93/100 - Train Loss: 0.1268 - Val Acc: 0.8406
2026-04-05 06:12:01,618 - INFO - Epoch 94/100 - Train Loss: 0.1253 - Val Acc: 0.8406
2026-04-05 06:12:01,910 - INFO - Epoch 95/100 - Train Loss: 0.1219 - Val Acc: 0.8261
2026-04-05 06:12:02,179 - INFO - Epoch 96/100 - Train Loss: 0.1218 - Val Acc: 0.8406
2026-04-05 06:12:02,462 - INFO - Epoch 97/100 - Train Loss: 0.1226 - Val Acc: 0.8261
2026-04-05 06:12:02,746 - INFO - Epoch 98/100 - Train Loss: 0.1189 - Val Acc: 0.8261
2026-04-05 06:12:03,035 - INFO - Epoch 99/100 - Train Loss: 0.1204 - Val Acc: 0.8261
2026-04-05 06:12:03,317 - INFO - Epoch 100/100 - Train Loss: 0.1202 - Val Acc: 0.8261
2026-04-05 06:12:03,688 - INFO - Fold 5 logically complete. Tensor memory bounds cleared cleanly.
2026-04-05 06:12:03,693 - INFO - Original class distribution: [345 276]
2026-04-05 06:12:03,693 - INFO - Training device bound securely to: cuda
2026-04-05 06:12:03,721 - INFO - After SMOTE-ENN deployment: [345 293]

Fold 6:   0%|          | 0/100 [00:00<?, ?it/s]

2026-04-05 06:12:04,021 - INFO - Epoch 1/100 - Train Loss: 0.6512 - Val Acc: 0.8551
2026-04-05 06:12:04,294 - INFO - Epoch 2/100 - Train Loss: 0.5594 - Val Acc: 0.8551
2026-04-05 06:12:04,585 - INFO - Epoch 3/100 - Train Loss: 0.4708 - Val Acc: 0.8551
2026-04-05 06:12:04,861 - INFO - Epoch 4/100 - Train Loss: 0.3917 - Val Acc: 0.8406
2026-04-05 06:12:05,131 - INFO - Epoch 5/100 - Train Loss: 0.3353 - Val Acc: 0.8406
2026-04-05 06:12:05,403 - INFO - Epoch 6/100 - Train Loss: 0.2980 - Val Acc: 0.8406
2026-04-05 06:12:05,670 - INFO - Epoch 7/100 - Train Loss: 0.2748 - Val Acc: 0.8406
2026-04-05 06:12:05,943 - INFO - Epoch 8/100 - Train Loss: 0.2608 - Val Acc: 0.8406
2026-04-05 06:12:06,222 - INFO - Epoch 9/100 - Train Loss: 0.2477 - Val Acc: 0.8551
2026-04-05 06:12:06,503 - INFO - Epoch 10/100 - Train Loss: 0.2394 - Val Acc: 0.8696
2026-04-05 06:12:06,783 - INFO - Epoch 11/100 - Train Loss: 0.2313 - Val Acc: 0.8696
2026-04-05 06:12:07,075 - INFO - Epoch 12/100 - Train Loss: 0.2254 - Val Acc: 0.8696
2026-04-05 06:12:07,340 - INFO - Epoch 13/100 - Train Loss: 0.2188 - Val Acc: 0.8551
2026-04-05 06:12:07,607 - INFO - Epoch 14/100 - Train Loss: 0.2147 - Val Acc: 0.8551
2026-04-05 06:12:07,892 - INFO - Epoch 15/100 - Train Loss: 0.2093 - Val Acc: 0.8551
2026-04-05 06:12:08,165 - INFO - Epoch 16/100 - Train Loss: 0.2082 - Val Acc: 0.8551
2026-04-05 06:12:08,435 - INFO - Epoch 17/100 - Train Loss: 0.2011 - Val Acc: 0.8551
2026-04-05 06:12:08,703 - INFO - Epoch 18/100 - Train Loss: 0.2002 - Val Acc: 0.8551
2026-04-05 06:12:08,980 - INFO - Epoch 19/100 - Train Loss: 0.1975 - Val Acc: 0.8551
2026-04-05 06:12:09,255 - INFO - Epoch 20/100 - Train Loss: 0.1923 - Val Acc: 0.8696
2026-04-05 06:12:09,538 - INFO - Epoch 21/100 - Train Loss: 0.1940 - Val Acc: 0.8551
2026-04-05 06:12:09,801 - INFO - Epoch 22/100 - Train Loss: 0.1942 - Val Acc: 0.8406
2026-04-05 06:12:10,066 - INFO - Epoch 23/100 - Train Loss: 0.1893 - Val Acc: 0.8551
2026-04-05 06:12:10,354 - INFO - Epoch 24/100 - Train Loss: 0.1912 - Val Acc: 0.8551
2026-04-05 06:12:10,625 - INFO - Epoch 25/100 - Train Loss: 0.1893 - Val Acc: 0.8696
2026-04-05 06:12:10,901 - INFO - Epoch 26/100 - Train Loss: 0.1881 - Val Acc: 0.8551
2026-04-05 06:12:11,173 - INFO - Epoch 27/100 - Train Loss: 0.1847 - Val Acc: 0.8551
2026-04-05 06:12:11,444 - INFO - Epoch 28/100 - Train Loss: 0.1845 - Val Acc: 0.8551
2026-04-05 06:12:11,715 - INFO - Epoch 29/100 - Train Loss: 0.1853 - Val Acc: 0.8551
2026-04-05 06:12:11,993 - INFO - Epoch 30/100 - Train Loss: 0.1832 - Val Acc: 0.8551
2026-04-05 06:12:12,264 - INFO - Epoch 31/100 - Train Loss: 0.1819 - Val Acc: 0.8406
2026-04-05 06:12:12,536 - INFO - Epoch 32/100 - Train Loss: 0.1769 - Val Acc: 0.8406
2026-04-05 06:12:12,818 - INFO - Epoch 33/100 - Train Loss: 0.1810 - Val Acc: 0.8261
2026-04-05 06:12:13,098 - INFO - Epoch 34/100 - Train Loss: 0.1767 - Val Acc: 0.8406
2026-04-05 06:12:13,377 - INFO - Epoch 35/100 - Train Loss: 0.1776 - Val Acc: 0.8406
2026-04-05 06:12:13,651 - INFO - Epoch 36/100 - Train Loss: 0.1792 - Val Acc: 0.8261
2026-04-05 06:12:13,924 - INFO - Epoch 37/100 - Train Loss: 0.1757 - Val Acc: 0.8261
2026-04-05 06:12:14,190 - INFO - Epoch 38/100 - Train Loss: 0.1737 - Val Acc: 0.8261
2026-04-05 06:12:14,465 - INFO - Epoch 39/100 - Train Loss: 0.1754 - Val Acc: 0.8406
2026-04-05 06:12:14,770 - INFO - Epoch 40/100 - Train Loss: 0.1760 - Val Acc: 0.8406
2026-04-05 06:12:15,040 - INFO - Epoch 41/100 - Train Loss: 0.1733 - Val Acc: 0.8261
2026-04-05 06:12:15,305 - INFO - Epoch 42/100 - Train Loss: 0.1711 - Val Acc: 0.8261
2026-04-05 06:12:15,582 - INFO - Epoch 43/100 - Train Loss: 0.1701 - Val Acc: 0.8261
2026-04-05 06:12:15,855 - INFO - Epoch 44/100 - Train Loss: 0.1687 - Val Acc: 0.8261
2026-04-05 06:12:16,134 - INFO - Epoch 45/100 - Train Loss: 0.1675 - Val Acc: 0.8261
2026-04-05 06:12:16,402 - INFO - Epoch 46/100 - Train Loss: 0.1654 - Val Acc: 0.8261
2026-04-05 06:12:16,676 - INFO - Epoch 47/100 - Train Loss: 0.1656 - Val Acc: 0.8261
2026-04-05 06:12:16,939 - INFO - Epoch 48/100 - Train Loss: 0.1644 - Val Acc: 0.8261
2026-04-05 06:12:17,217 - INFO - Epoch 49/100 - Train Loss: 0.1645 - Val Acc: 0.8261
2026-04-05 06:12:17,491 - INFO - Epoch 50/100 - Train Loss: 0.1632 - Val Acc: 0.8261
2026-04-05 06:12:17,785 - INFO - Epoch 51/100 - Train Loss: 0.1623 - Val Acc: 0.8261
2026-04-05 06:12:18,060 - INFO - Epoch 52/100 - Train Loss: 0.1604 - Val Acc: 0.8261
2026-04-05 06:12:18,337 - INFO - Epoch 53/100 - Train Loss: 0.1587 - Val Acc: 0.8261
2026-04-05 06:12:18,630 - INFO - Epoch 54/100 - Train Loss: 0.1605 - Val Acc: 0.8261
2026-04-05 06:12:18,918 - INFO - Epoch 55/100 - Train Loss: 0.1586 - Val Acc: 0.8261
2026-04-05 06:12:19,194 - INFO - Epoch 56/100 - Train Loss: 0.1556 - Val Acc: 0.8261
2026-04-05 06:12:19,466 - INFO - Epoch 57/100 - Train Loss: 0.1571 - Val Acc: 0.8261
2026-04-05 06:12:19,736 - INFO - Epoch 58/100 - Train Loss: 0.1544 - Val Acc: 0.8116
2026-04-05 06:12:20,004 - INFO - Epoch 59/100 - Train Loss: 0.1530 - Val Acc: 0.8116
2026-04-05 06:12:20,286 - INFO - Epoch 60/100 - Train Loss: 0.1581 - Val Acc: 0.8116
2026-04-05 06:12:20,559 - INFO - Epoch 61/100 - Train Loss: 0.1538 - Val Acc: 0.8116
2026-04-05 06:12:20,833 - INFO - Epoch 62/100 - Train Loss: 0.1500 - Val Acc: 0.8261
2026-04-05 06:12:21,100 - INFO - Epoch 63/100 - Train Loss: 0.1522 - Val Acc: 0.8116
2026-04-05 06:12:21,381 - INFO - Epoch 64/100 - Train Loss: 0.1489 - Val Acc: 0.8116
2026-04-05 06:12:21,652 - INFO - Epoch 65/100 - Train Loss: 0.1483 - Val Acc: 0.8261
2026-04-05 06:12:21,946 - INFO - Epoch 66/100 - Train Loss: 0.1482 - Val Acc: 0.8261
2026-04-05 06:12:22,222 - INFO - Epoch 67/100 - Train Loss: 0.1464 - Val Acc: 0.8261
2026-04-05 06:12:22,509 - INFO - Epoch 68/100 - Train Loss: 0.1481 - Val Acc: 0.8261
2026-04-05 06:12:22,793 - INFO - Epoch 69/100 - Train Loss: 0.1431 - Val Acc: 0.8261
2026-04-05 06:12:23,062 - INFO - Epoch 70/100 - Train Loss: 0.1480 - Val Acc: 0.8261
2026-04-05 06:12:23,326 - INFO - Epoch 71/100 - Train Loss: 0.1466 - Val Acc: 0.8261
2026-04-05 06:12:23,598 - INFO - Epoch 72/100 - Train Loss: 0.1424 - Val Acc: 0.8261
2026-04-05 06:12:23,881 - INFO - Epoch 73/100 - Train Loss: 0.1399 - Val Acc: 0.8261
2026-04-05 06:12:24,158 - INFO - Epoch 74/100 - Train Loss: 0.1404 - Val Acc: 0.8261
2026-04-05 06:12:24,433 - INFO - Epoch 75/100 - Train Loss: 0.1418 - Val Acc: 0.8261
2026-04-05 06:12:24,736 - INFO - Epoch 76/100 - Train Loss: 0.1429 - Val Acc: 0.8261
2026-04-05 06:12:25,008 - INFO - Epoch 77/100 - Train Loss: 0.1406 - Val Acc: 0.8261
2026-04-05 06:12:25,280 - INFO - Epoch 78/100 - Train Loss: 0.1405 - Val Acc: 0.8261
2026-04-05 06:12:25,568 - INFO - Epoch 79/100 - Train Loss: 0.1402 - Val Acc: 0.8261
2026-04-05 06:12:25,839 - INFO - Epoch 80/100 - Train Loss: 0.1370 - Val Acc: 0.8261
2026-04-05 06:12:26,111 - INFO - Epoch 81/100 - Train Loss: 0.1346 - Val Acc: 0.8261
2026-04-05 06:12:26,385 - INFO - Epoch 82/100 - Train Loss: 0.1326 - Val Acc: 0.8261
2026-04-05 06:12:26,657 - INFO - Epoch 83/100 - Train Loss: 0.1354 - Val Acc: 0.8261
2026-04-05 06:12:26,929 - INFO - Epoch 84/100 - Train Loss: 0.1363 - Val Acc: 0.8261
2026-04-05 06:12:27,203 - INFO - Epoch 85/100 - Train Loss: 0.1386 - Val Acc: 0.8261
2026-04-05 06:12:27,472 - INFO - Epoch 86/100 - Train Loss: 0.1344 - Val Acc: 0.8261
2026-04-05 06:12:27,747 - INFO - Epoch 87/100 - Train Loss: 0.1404 - Val Acc: 0.8261
2026-04-05 06:12:28,025 - INFO - Epoch 88/100 - Train Loss: 0.1347 - Val Acc: 0.8261
2026-04-05 06:12:28,298 - INFO - Epoch 89/100 - Train Loss: 0.1365 - Val Acc: 0.8261
2026-04-05 06:12:28,573 - INFO - Epoch 90/100 - Train Loss: 0.1331 - Val Acc: 0.8261
2026-04-05 06:12:28,846 - INFO - Epoch 91/100 - Train Loss: 0.1304 - Val Acc: 0.8261
2026-04-05 06:12:29,115 - INFO - Epoch 92/100 - Train Loss: 0.1306 - Val Acc: 0.8261
2026-04-05 06:12:29,383 - INFO - Epoch 93/100 - Train Loss: 0.1352 - Val Acc: 0.8261
2026-04-05 06:12:29,661 - INFO - Epoch 94/100 - Train Loss: 0.1281 - Val Acc: 0.8261
2026-04-05 06:12:29,937 - INFO - Epoch 95/100 - Train Loss: 0.1309 - Val Acc: 0.8261
2026-04-05 06:12:30,203 - INFO - Epoch 96/100 - Train Loss: 0.1338 - Val Acc: 0.8261
2026-04-05 06:12:30,476 - INFO - Epoch 97/100 - Train Loss: 0.1264 - Val Acc: 0.8261
2026-04-05 06:12:30,748 - INFO - Epoch 98/100 - Train Loss: 0.1300 - Val Acc: 0.8261
2026-04-05 06:12:31,020 - INFO - Epoch 99/100 - Train Loss: 0.1290 - Val Acc: 0.8261
2026-04-05 06:12:31,302 - INFO - Epoch 100/100 - Train Loss: 0.1249 - Val Acc: 0.8261
2026-04-05 06:12:31,662 - INFO - Fold 6 logically complete. Tensor memory bounds cleared cleanly.
2026-04-05 06:12:31,666 - INFO - Original class distribution: [345 276]
2026-04-05 06:12:31,667 - INFO - Training device bound securely to: cuda
2026-04-05 06:12:31,695 - INFO - After SMOTE-ENN deployment: [345 302]

Fold 7:   0%|          | 0/100 [00:00<?, ?it/s]

2026-04-05 06:12:31,998 - INFO - Epoch 1/100 - Train Loss: 0.6630 - Val Acc: 0.7246
2026-04-05 06:12:32,283 - INFO - Epoch 2/100 - Train Loss: 0.5691 - Val Acc: 0.7246
2026-04-05 06:12:32,563 - INFO - Epoch 3/100 - Train Loss: 0.4758 - Val Acc: 0.7246
2026-04-05 06:12:32,843 - INFO - Epoch 4/100 - Train Loss: 0.3951 - Val Acc: 0.7391
2026-04-05 06:12:33,124 - INFO - Epoch 5/100 - Train Loss: 0.3328 - Val Acc: 0.7391
2026-04-05 06:12:33,405 - INFO - Epoch 6/100 - Train Loss: 0.2913 - Val Acc: 0.7391
2026-04-05 06:12:33,705 - INFO - Epoch 7/100 - Train Loss: 0.2608 - Val Acc: 0.7391
2026-04-05 06:12:33,998 - INFO - Epoch 8/100 - Train Loss: 0.2449 - Val Acc: 0.7391
2026-04-05 06:12:34,283 - INFO - Epoch 9/100 - Train Loss: 0.2301 - Val Acc: 0.7246
2026-04-05 06:12:34,598 - INFO - Epoch 10/100 - Train Loss: 0.2176 - Val Acc: 0.7246
2026-04-05 06:12:34,871 - INFO - Epoch 11/100 - Train Loss: 0.2084 - Val Acc: 0.7391
2026-04-05 06:12:35,143 - INFO - Epoch 12/100 - Train Loss: 0.2011 - Val Acc: 0.7536
2026-04-05 06:12:35,425 - INFO - Epoch 13/100 - Train Loss: 0.1946 - Val Acc: 0.7536
2026-04-05 06:12:35,699 - INFO - Epoch 14/100 - Train Loss: 0.1892 - Val Acc: 0.7391
2026-04-05 06:12:35,979 - INFO - Epoch 15/100 - Train Loss: 0.1843 - Val Acc: 0.7391
2026-04-05 06:12:36,254 - INFO - Epoch 16/100 - Train Loss: 0.1788 - Val Acc: 0.7391
2026-04-05 06:12:36,535 - INFO - Epoch 17/100 - Train Loss: 0.1781 - Val Acc: 0.7391
2026-04-05 06:12:36,812 - INFO - Epoch 18/100 - Train Loss: 0.1746 - Val Acc: 0.7536
2026-04-05 06:12:37,094 - INFO - Epoch 19/100 - Train Loss: 0.1729 - Val Acc: 0.7391
2026-04-05 06:12:37,378 - INFO - Epoch 20/100 - Train Loss: 0.1736 - Val Acc: 0.7391
2026-04-05 06:12:37,651 - INFO - Epoch 21/100 - Train Loss: 0.1694 - Val Acc: 0.7536
2026-04-05 06:12:37,922 - INFO - Epoch 22/100 - Train Loss: 0.1680 - Val Acc: 0.7536
2026-04-05 06:12:38,190 - INFO - Epoch 23/100 - Train Loss: 0.1668 - Val Acc: 0.7391
2026-04-05 06:12:38,466 - INFO - Epoch 24/100 - Train Loss: 0.1652 - Val Acc: 0.7536
2026-04-05 06:12:38,734 - INFO - Epoch 25/100 - Train Loss: 0.1631 - Val Acc: 0.7536
2026-04-05 06:12:39,014 - INFO - Epoch 26/100 - Train Loss: 0.1621 - Val Acc: 0.7536
2026-04-05 06:12:39,290 - INFO - Epoch 27/100 - Train Loss: 0.1585 - Val Acc: 0.7536
2026-04-05 06:12:39,570 - INFO - Epoch 28/100 - Train Loss: 0.1595 - Val Acc: 0.7536
2026-04-05 06:12:39,854 - INFO - Epoch 29/100 - Train Loss: 0.1581 - Val Acc: 0.7536
2026-04-05 06:12:40,133 - INFO - Epoch 30/100 - Train Loss: 0.1574 - Val Acc: 0.7536
2026-04-05 06:12:40,419 - INFO - Epoch 31/100 - Train Loss: 0.1563 - Val Acc: 0.7536
2026-04-05 06:12:40,690 - INFO - Epoch 32/100 - Train Loss: 0.1577 - Val Acc: 0.7536
2026-04-05 06:12:40,974 - INFO - Epoch 33/100 - Train Loss: 0.1548 - Val Acc: 0.7536
2026-04-05 06:12:41,254 - INFO - Epoch 34/100 - Train Loss: 0.1549 - Val Acc: 0.7536
2026-04-05 06:12:41,549 - INFO - Epoch 35/100 - Train Loss: 0.1554 - Val Acc: 0.7536
2026-04-05 06:12:41,825 - INFO - Epoch 36/100 - Train Loss: 0.1541 - Val Acc: 0.7536
2026-04-05 06:12:42,117 - INFO - Epoch 37/100 - Train Loss: 0.1511 - Val Acc: 0.7536
2026-04-05 06:12:42,398 - INFO - Epoch 38/100 - Train Loss: 0.1503 - Val Acc: 0.7536
2026-04-05 06:12:42,690 - INFO - Epoch 39/100 - Train Loss: 0.1498 - Val Acc: 0.7536
2026-04-05 06:12:42,968 - INFO - Epoch 40/100 - Train Loss: 0.1484 - Val Acc: 0.7536
2026-04-05 06:12:43,249 - INFO - Epoch 41/100 - Train Loss: 0.1495 - Val Acc: 0.7536
2026-04-05 06:12:43,532 - INFO - Epoch 42/100 - Train Loss: 0.1469 - Val Acc: 0.7536
2026-04-05 06:12:43,813 - INFO - Epoch 43/100 - Train Loss: 0.1482 - Val Acc: 0.7681
2026-04-05 06:12:44,095 - INFO - Epoch 44/100 - Train Loss: 0.1441 - Val Acc: 0.7681
2026-04-05 06:12:44,377 - INFO - Epoch 45/100 - Train Loss: 0.1455 - Val Acc: 0.7536
2026-04-05 06:12:44,684 - INFO - Epoch 46/100 - Train Loss: 0.1445 - Val Acc: 0.7536
2026-04-05 06:12:44,968 - INFO - Epoch 47/100 - Train Loss: 0.1439 - Val Acc: 0.7536
2026-04-05 06:12:45,246 - INFO - Epoch 48/100 - Train Loss: 0.1434 - Val Acc: 0.7536
2026-04-05 06:12:45,523 - INFO - Epoch 49/100 - Train Loss: 0.1408 - Val Acc: 0.7536
2026-04-05 06:12:45,805 - INFO - Epoch 50/100 - Train Loss: 0.1413 - Val Acc: 0.7536
2026-04-05 06:12:46,099 - INFO - Epoch 51/100 - Train Loss: 0.1405 - Val Acc: 0.7536
2026-04-05 06:12:46,370 - INFO - Epoch 52/100 - Train Loss: 0.1393 - Val Acc: 0.7536
2026-04-05 06:12:46,646 - INFO - Epoch 53/100 - Train Loss: 0.1403 - Val Acc: 0.7536
2026-04-05 06:12:46,931 - INFO - Epoch 54/100 - Train Loss: 0.1364 - Val Acc: 0.7536
2026-04-05 06:12:47,207 - INFO - Epoch 55/100 - Train Loss: 0.1370 - Val Acc: 0.7536
2026-04-05 06:12:47,485 - INFO - Epoch 56/100 - Train Loss: 0.1354 - Val Acc: 0.7536
2026-04-05 06:12:47,774 - INFO - Epoch 57/100 - Train Loss: 0.1342 - Val Acc: 0.7391
2026-04-05 06:12:48,054 - INFO - Epoch 58/100 - Train Loss: 0.1334 - Val Acc: 0.7391
2026-04-05 06:12:48,316 - INFO - Epoch 59/100 - Train Loss: 0.1315 - Val Acc: 0.7391
2026-04-05 06:12:48,591 - INFO - Epoch 60/100 - Train Loss: 0.1313 - Val Acc: 0.7391
2026-04-05 06:12:48,880 - INFO - Epoch 61/100 - Train Loss: 0.1347 - Val Acc: 0.7391
2026-04-05 06:12:49,160 - INFO - Epoch 62/100 - Train Loss: 0.1283 - Val Acc: 0.7391
2026-04-05 06:12:49,435 - INFO - Epoch 63/100 - Train Loss: 0.1294 - Val Acc: 0.7391
2026-04-05 06:12:49,714 - INFO - Epoch 64/100 - Train Loss: 0.1306 - Val Acc: 0.7391
2026-04-05 06:12:50,007 - INFO - Epoch 65/100 - Train Loss: 0.1291 - Val Acc: 0.7536
2026-04-05 06:12:50,288 - INFO - Epoch 66/100 - Train Loss: 0.1294 - Val Acc: 0.7536
2026-04-05 06:12:50,583 - INFO - Epoch 67/100 - Train Loss: 0.1311 - Val Acc: 0.7536
2026-04-05 06:12:50,867 - INFO - Epoch 68/100 - Train Loss: 0.1283 - Val Acc: 0.7536
2026-04-05 06:12:51,142 - INFO - Epoch 69/100 - Train Loss: 0.1249 - Val Acc: 0.7536
2026-04-05 06:12:51,424 - INFO - Epoch 70/100 - Train Loss: 0.1253 - Val Acc: 0.7536
2026-04-05 06:12:51,707 - INFO - Epoch 71/100 - Train Loss: 0.1259 - Val Acc: 0.7391
2026-04-05 06:12:52,017 - INFO - Epoch 72/100 - Train Loss: 0.1230 - Val Acc: 0.7536
2026-04-05 06:12:52,318 - INFO - Epoch 73/100 - Train Loss: 0.1239 - Val Acc: 0.7391
2026-04-05 06:12:52,604 - INFO - Epoch 74/100 - Train Loss: 0.1249 - Val Acc: 0.7536
2026-04-05 06:12:52,880 - INFO - Epoch 75/100 - Train Loss: 0.1229 - Val Acc: 0.7536
2026-04-05 06:12:53,162 - INFO - Epoch 76/100 - Train Loss: 0.1219 - Val Acc: 0.7536
2026-04-05 06:12:53,457 - INFO - Epoch 77/100 - Train Loss: 0.1212 - Val Acc: 0.7391
2026-04-05 06:12:53,731 - INFO - Epoch 78/100 - Train Loss: 0.1202 - Val Acc: 0.7391
2026-04-05 06:12:54,008 - INFO - Epoch 79/100 - Train Loss: 0.1198 - Val Acc: 0.7536
2026-04-05 06:12:54,303 - INFO - Epoch 80/100 - Train Loss: 0.1207 - Val Acc: 0.7536
2026-04-05 06:12:54,599 - INFO - Epoch 81/100 - Train Loss: 0.1205 - Val Acc: 0.7536
2026-04-05 06:12:54,877 - INFO - Epoch 82/100 - Train Loss: 0.1196 - Val Acc: 0.7391
2026-04-05 06:12:55,163 - INFO - Epoch 83/100 - Train Loss: 0.1210 - Val Acc: 0.7391
2026-04-05 06:12:55,468 - INFO - Epoch 84/100 - Train Loss: 0.1179 - Val Acc: 0.7391
2026-04-05 06:12:55,754 - INFO - Epoch 85/100 - Train Loss: 0.1172 - Val Acc: 0.7391
2026-04-05 06:12:56,036 - INFO - Epoch 86/100 - Train Loss: 0.1191 - Val Acc: 0.7536
2026-04-05 06:12:56,310 - INFO - Epoch 87/100 - Train Loss: 0.1137 - Val Acc: 0.7536
2026-04-05 06:12:56,590 - INFO - Epoch 88/100 - Train Loss: 0.1177 - Val Acc: 0.7536
2026-04-05 06:12:56,872 - INFO - Epoch 89/100 - Train Loss: 0.1160 - Val Acc: 0.7536
2026-04-05 06:12:57,163 - INFO - Epoch 90/100 - Train Loss: 0.1190 - Val Acc: 0.7536
2026-04-05 06:12:57,442 - INFO - Epoch 91/100 - Train Loss: 0.1169 - Val Acc: 0.7536
2026-04-05 06:12:57,732 - INFO - Epoch 92/100 - Train Loss: 0.1179 - Val Acc: 0.7391
2026-04-05 06:12:58,009 - INFO - Epoch 93/100 - Train Loss: 0.1157 - Val Acc: 0.7536
2026-04-05 06:12:58,283 - INFO - Epoch 94/100 - Train Loss: 0.1161 - Val Acc: 0.7536
2026-04-05 06:12:58,550 - INFO - Epoch 95/100 - Train Loss: 0.1093 - Val Acc: 0.7536
2026-04-05 06:12:58,827 - INFO - Epoch 96/100 - Train Loss: 0.1128 - Val Acc: 0.7536
2026-04-05 06:12:59,110 - INFO - Epoch 97/100 - Train Loss: 0.1146 - Val Acc: 0.7536
2026-04-05 06:12:59,381 - INFO - Epoch 98/100 - Train Loss: 0.1133 - Val Acc: 0.7536
2026-04-05 06:12:59,659 - INFO - Epoch 99/100 - Train Loss: 0.1096 - Val Acc: 0.7536
2026-04-05 06:12:59,938 - INFO - Epoch 100/100 - Train Loss: 0.1088 - Val Acc: 0.7391
2026-04-05 06:13:00,298 - INFO - Fold 7 logically complete. Tensor memory bounds cleared cleanly.
2026-04-05 06:13:00,302 - INFO - Original class distribution: [345 276]
2026-04-05 06:13:00,303 - INFO - Training device bound securely to: cuda
2026-04-05 06:13:00,331 - INFO - After SMOTE-ENN deployment: [345 296]

Fold 8:   0%|          | 0/100 [00:00<?, ?it/s]

2026-04-05 06:13:00,627 - INFO - Epoch 1/100 - Train Loss: 0.6604 - Val Acc: 0.8116
2026-04-05 06:13:00,901 - INFO - Epoch 2/100 - Train Loss: 0.5693 - Val Acc: 0.8261
2026-04-05 06:13:01,169 - INFO - Epoch 3/100 - Train Loss: 0.4907 - Val Acc: 0.7971
2026-04-05 06:13:01,464 - INFO - Epoch 4/100 - Train Loss: 0.4238 - Val Acc: 0.8406
2026-04-05 06:13:01,749 - INFO - Epoch 5/100 - Train Loss: 0.3678 - Val Acc: 0.8696
2026-04-05 06:13:02,033 - INFO - Epoch 6/100 - Train Loss: 0.3306 - Val Acc: 0.8841
2026-04-05 06:13:02,325 - INFO - Epoch 7/100 - Train Loss: 0.3018 - Val Acc: 0.8841
2026-04-05 06:13:02,606 - INFO - Epoch 8/100 - Train Loss: 0.2840 - Val Acc: 0.8841
2026-04-05 06:13:02,887 - INFO - Epoch 9/100 - Train Loss: 0.2686 - Val Acc: 0.8696
2026-04-05 06:13:03,164 - INFO - Epoch 10/100 - Train Loss: 0.2594 - Val Acc: 0.8841
2026-04-05 06:13:03,443 - INFO - Epoch 11/100 - Train Loss: 0.2488 - Val Acc: 0.8841
2026-04-05 06:13:03,703 - INFO - Epoch 12/100 - Train Loss: 0.2452 - Val Acc: 0.8841
2026-04-05 06:13:03,982 - INFO - Epoch 13/100 - Train Loss: 0.2409 - Val Acc: 0.8696
2026-04-05 06:13:04,263 - INFO - Epoch 14/100 - Train Loss: 0.2363 - Val Acc: 0.8841
2026-04-05 06:13:04,546 - INFO - Epoch 15/100 - Train Loss: 0.2312 - Val Acc: 0.8841
2026-04-05 06:13:04,832 - INFO - Epoch 16/100 - Train Loss: 0.2261 - Val Acc: 0.8551
2026-04-05 06:13:05,109 - INFO - Epoch 17/100 - Train Loss: 0.2217 - Val Acc: 0.8406
2026-04-05 06:13:05,376 - INFO - Epoch 18/100 - Train Loss: 0.2160 - Val Acc: 0.8406
2026-04-05 06:13:05,653 - INFO - Epoch 19/100 - Train Loss: 0.2142 - Val Acc: 0.8406
2026-04-05 06:13:05,950 - INFO - Epoch 20/100 - Train Loss: 0.2116 - Val Acc: 0.8261
2026-04-05 06:13:06,225 - INFO - Epoch 21/100 - Train Loss: 0.2095 - Val Acc: 0.8261
2026-04-05 06:13:06,504 - INFO - Epoch 22/100 - Train Loss: 0.2049 - Val Acc: 0.8261
2026-04-05 06:13:06,803 - INFO - Epoch 23/100 - Train Loss: 0.2018 - Val Acc: 0.8696
2026-04-05 06:13:07,075 - INFO - Epoch 24/100 - Train Loss: 0.1979 - Val Acc: 0.8696
2026-04-05 06:13:07,350 - INFO - Epoch 25/100 - Train Loss: 0.1981 - Val Acc: 0.8551
2026-04-05 06:13:07,622 - INFO - Epoch 26/100 - Train Loss: 0.1965 - Val Acc: 0.8551
2026-04-05 06:13:07,901 - INFO - Epoch 27/100 - Train Loss: 0.1965 - Val Acc: 0.8551
2026-04-05 06:13:08,175 - INFO - Epoch 28/100 - Train Loss: 0.1950 - Val Acc: 0.8551
2026-04-05 06:13:08,452 - INFO - Epoch 29/100 - Train Loss: 0.1946 - Val Acc: 0.8696
2026-04-05 06:13:08,730 - INFO - Epoch 30/100 - Train Loss: 0.1960 - Val Acc: 0.8696
2026-04-05 06:13:09,024 - INFO - Epoch 31/100 - Train Loss: 0.1940 - Val Acc: 0.8551
2026-04-05 06:13:09,294 - INFO - Epoch 32/100 - Train Loss: 0.1914 - Val Acc: 0.8551
2026-04-05 06:13:09,570 - INFO - Epoch 33/100 - Train Loss: 0.1897 - Val Acc: 0.8551
2026-04-05 06:13:09,846 - INFO - Epoch 34/100 - Train Loss: 0.1930 - Val Acc: 0.8551
2026-04-05 06:13:10,130 - INFO - Epoch 35/100 - Train Loss: 0.1906 - Val Acc: 0.8551
2026-04-05 06:13:10,406 - INFO - Epoch 36/100 - Train Loss: 0.1883 - Val Acc: 0.8551
2026-04-05 06:13:10,684 - INFO - Epoch 37/100 - Train Loss: 0.1878 - Val Acc: 0.8551
2026-04-05 06:13:10,972 - INFO - Epoch 38/100 - Train Loss: 0.1861 - Val Acc: 0.8551
2026-04-05 06:13:11,245 - INFO - Epoch 39/100 - Train Loss: 0.1889 - Val Acc: 0.8406
2026-04-05 06:13:11,527 - INFO - Epoch 40/100 - Train Loss: 0.1935 - Val Acc: 0.8406
2026-04-05 06:13:11,801 - INFO - Epoch 41/100 - Train Loss: 0.1895 - Val Acc: 0.8406
2026-04-05 06:13:12,064 - INFO - Epoch 42/100 - Train Loss: 0.1877 - Val Acc: 0.8406
2026-04-05 06:13:12,331 - INFO - Epoch 43/100 - Train Loss: 0.1884 - Val Acc: 0.8551
2026-04-05 06:13:12,622 - INFO - Epoch 44/100 - Train Loss: 0.1839 - Val Acc: 0.8551
2026-04-05 06:13:12,900 - INFO - Epoch 45/100 - Train Loss: 0.1841 - Val Acc: 0.8551
2026-04-05 06:13:13,193 - INFO - Epoch 46/100 - Train Loss: 0.1822 - Val Acc: 0.8551
2026-04-05 06:13:13,468 - INFO - Epoch 47/100 - Train Loss: 0.1857 - Val Acc: 0.8551
2026-04-05 06:13:13,733 - INFO - Epoch 48/100 - Train Loss: 0.1820 - Val Acc: 0.8551
2026-04-05 06:13:14,016 - INFO - Epoch 49/100 - Train Loss: 0.1837 - Val Acc: 0.8406
2026-04-05 06:13:14,295 - INFO - Epoch 50/100 - Train Loss: 0.1923 - Val Acc: 0.8696
2026-04-05 06:13:14,594 - INFO - Epoch 51/100 - Train Loss: 0.1909 - Val Acc: 0.8696
2026-04-05 06:13:14,880 - INFO - Epoch 52/100 - Train Loss: 0.1901 - Val Acc: 0.8551
2026-04-05 06:13:15,157 - INFO - Epoch 53/100 - Train Loss: 0.1883 - Val Acc: 0.8261
2026-04-05 06:13:15,440 - INFO - Epoch 54/100 - Train Loss: 0.1841 - Val Acc: 0.8261
2026-04-05 06:13:15,725 - INFO - Epoch 55/100 - Train Loss: 0.1767 - Val Acc: 0.8406
2026-04-05 06:13:16,023 - INFO - Epoch 56/100 - Train Loss: 0.1775 - Val Acc: 0.8551
2026-04-05 06:13:16,306 - INFO - Epoch 57/100 - Train Loss: 0.1752 - Val Acc: 0.8551
2026-04-05 06:13:16,588 - INFO - Epoch 58/100 - Train Loss: 0.1770 - Val Acc: 0.8551
2026-04-05 06:13:16,879 - INFO - Epoch 59/100 - Train Loss: 0.1790 - Val Acc: 0.8551
2026-04-05 06:13:17,165 - INFO - Epoch 60/100 - Train Loss: 0.1750 - Val Acc: 0.8551
2026-04-05 06:13:17,447 - INFO - Epoch 61/100 - Train Loss: 0.1721 - Val Acc: 0.8551
2026-04-05 06:13:17,717 - INFO - Epoch 62/100 - Train Loss: 0.1712 - Val Acc: 0.8696
2026-04-05 06:13:18,012 - INFO - Epoch 63/100 - Train Loss: 0.1734 - Val Acc: 0.8551
2026-04-05 06:13:18,305 - INFO - Epoch 64/100 - Train Loss: 0.1732 - Val Acc: 0.8261
2026-04-05 06:13:18,587 - INFO - Epoch 65/100 - Train Loss: 0.1722 - Val Acc: 0.8406
2026-04-05 06:13:18,866 - INFO - Epoch 66/100 - Train Loss: 0.1716 - Val Acc: 0.8261
2026-04-05 06:13:19,147 - INFO - Epoch 67/100 - Train Loss: 0.1712 - Val Acc: 0.8406
2026-04-05 06:13:19,422 - INFO - Epoch 68/100 - Train Loss: 0.1683 - Val Acc: 0.8406
2026-04-05 06:13:19,699 - INFO - Epoch 69/100 - Train Loss: 0.1672 - Val Acc: 0.8406
2026-04-05 06:13:19,977 - INFO - Epoch 70/100 - Train Loss: 0.1652 - Val Acc: 0.8551
2026-04-05 06:13:20,257 - INFO - Epoch 71/100 - Train Loss: 0.1627 - Val Acc: 0.8551
2026-04-05 06:13:20,529 - INFO - Epoch 72/100 - Train Loss: 0.1640 - Val Acc: 0.8551
2026-04-05 06:13:20,824 - INFO - Epoch 73/100 - Train Loss: 0.1657 - Val Acc: 0.8551
2026-04-05 06:13:21,118 - INFO - Epoch 74/100 - Train Loss: 0.1636 - Val Acc: 0.8551
2026-04-05 06:13:21,392 - INFO - Epoch 75/100 - Train Loss: 0.1660 - Val Acc: 0.8551
2026-04-05 06:13:21,674 - INFO - Epoch 76/100 - Train Loss: 0.1610 - Val Acc: 0.8551
2026-04-05 06:13:21,967 - INFO - Epoch 77/100 - Train Loss: 0.1634 - Val Acc: 0.8551
2026-04-05 06:13:22,244 - INFO - Epoch 78/100 - Train Loss: 0.1651 - Val Acc: 0.8551
2026-04-05 06:13:22,538 - INFO - Epoch 79/100 - Train Loss: 0.1695 - Val Acc: 0.8551
2026-04-05 06:13:22,825 - INFO - Epoch 80/100 - Train Loss: 0.1671 - Val Acc: 0.8551
2026-04-05 06:13:23,107 - INFO - Epoch 81/100 - Train Loss: 0.1705 - Val Acc: 0.8551
2026-04-05 06:13:23,399 - INFO - Epoch 82/100 - Train Loss: 0.1645 - Val Acc: 0.8551
2026-04-05 06:13:23,674 - INFO - Epoch 83/100 - Train Loss: 0.1635 - Val Acc: 0.8551
2026-04-05 06:13:23,954 - INFO - Epoch 84/100 - Train Loss: 0.1614 - Val Acc: 0.8406
2026-04-05 06:13:24,249 - INFO - Epoch 85/100 - Train Loss: 0.1614 - Val Acc: 0.8406
2026-04-05 06:13:24,557 - INFO - Epoch 86/100 - Train Loss: 0.1613 - Val Acc: 0.8261
2026-04-05 06:13:24,837 - INFO - Epoch 87/100 - Train Loss: 0.1536 - Val Acc: 0.8261
2026-04-05 06:13:25,115 - INFO - Epoch 88/100 - Train Loss: 0.1547 - Val Acc: 0.8261
2026-04-05 06:13:25,396 - INFO - Epoch 89/100 - Train Loss: 0.1560 - Val Acc: 0.8261
2026-04-05 06:13:25,676 - INFO - Epoch 90/100 - Train Loss: 0.1579 - Val Acc: 0.8406
2026-04-05 06:13:25,956 - INFO - Epoch 91/100 - Train Loss: 0.1502 - Val Acc: 0.8551
2026-04-05 06:13:26,233 - INFO - Epoch 92/100 - Train Loss: 0.1522 - Val Acc: 0.8551
2026-04-05 06:13:26,522 - INFO - Epoch 93/100 - Train Loss: 0.1535 - Val Acc: 0.8551
2026-04-05 06:13:26,796 - INFO - Epoch 94/100 - Train Loss: 0.1494 - Val Acc: 0.8551
2026-04-05 06:13:27,074 - INFO - Epoch 95/100 - Train Loss: 0.1527 - Val Acc: 0.8696
2026-04-05 06:13:27,361 - INFO - Epoch 96/100 - Train Loss: 0.1490 - Val Acc: 0.8696
2026-04-05 06:13:27,648 - INFO - Epoch 97/100 - Train Loss: 0.1516 - Val Acc: 0.8551
2026-04-05 06:13:27,927 - INFO - Epoch 98/100 - Train Loss: 0.1460 - Val Acc: 0.8551
2026-04-05 06:13:28,211 - INFO - Epoch 99/100 - Train Loss: 0.1437 - Val Acc: 0.8406
2026-04-05 06:13:28,495 - INFO - Epoch 100/100 - Train Loss: 0.1450 - Val Acc: 0.8406
2026-04-05 06:13:28,866 - INFO - Fold 8 logically complete. Tensor memory bounds cleared cleanly.
2026-04-05 06:13:28,870 - INFO - Original class distribution: [345 276]
2026-04-05 06:13:28,870 - INFO - Training device bound securely to: cuda
2026-04-05 06:13:28,899 - INFO - After SMOTE-ENN deployment: [345 301]

Fold 9:   0%|          | 0/100 [00:00<?, ?it/s]

2026-04-05 06:13:29,190 - INFO - Epoch 1/100 - Train Loss: 0.6467 - Val Acc: 0.7826
2026-04-05 06:13:29,473 - INFO - Epoch 2/100 - Train Loss: 0.5482 - Val Acc: 0.8116
2026-04-05 06:13:29,757 - INFO - Epoch 3/100 - Train Loss: 0.4563 - Val Acc: 0.7971
2026-04-05 06:13:30,039 - INFO - Epoch 4/100 - Train Loss: 0.3821 - Val Acc: 0.8116
2026-04-05 06:13:30,312 - INFO - Epoch 5/100 - Train Loss: 0.3274 - Val Acc: 0.8116
2026-04-05 06:13:30,591 - INFO - Epoch 6/100 - Train Loss: 0.2918 - Val Acc: 0.8261
2026-04-05 06:13:30,878 - INFO - Epoch 7/100 - Train Loss: 0.2687 - Val Acc: 0.8406
2026-04-05 06:13:31,185 - INFO - Epoch 8/100 - Train Loss: 0.2524 - Val Acc: 0.8406
2026-04-05 06:13:31,464 - INFO - Epoch 9/100 - Train Loss: 0.2401 - Val Acc: 0.8406
2026-04-05 06:13:31,745 - INFO - Epoch 10/100 - Train Loss: 0.2289 - Val Acc: 0.8406
2026-04-05 06:13:32,033 - INFO - Epoch 11/100 - Train Loss: 0.2180 - Val Acc: 0.8261
2026-04-05 06:13:32,309 - INFO - Epoch 12/100 - Train Loss: 0.2125 - Val Acc: 0.8261
2026-04-05 06:13:32,592 - INFO - Epoch 13/100 - Train Loss: 0.2072 - Val Acc: 0.8261
2026-04-05 06:13:32,872 - INFO - Epoch 14/100 - Train Loss: 0.2019 - Val Acc: 0.8261
2026-04-05 06:13:33,149 - INFO - Epoch 15/100 - Train Loss: 0.1960 - Val Acc: 0.8406
2026-04-05 06:13:33,425 - INFO - Epoch 16/100 - Train Loss: 0.1906 - Val Acc: 0.8261
2026-04-05 06:13:33,707 - INFO - Epoch 17/100 - Train Loss: 0.1889 - Val Acc: 0.8261
2026-04-05 06:13:33,979 - INFO - Epoch 18/100 - Train Loss: 0.1854 - Val Acc: 0.8261
2026-04-05 06:13:34,270 - INFO - Epoch 19/100 - Train Loss: 0.1815 - Val Acc: 0.8116
2026-04-05 06:13:34,572 - INFO - Epoch 20/100 - Train Loss: 0.1820 - Val Acc: 0.8261
2026-04-05 06:13:34,868 - INFO - Epoch 21/100 - Train Loss: 0.1765 - Val Acc: 0.8406
2026-04-05 06:13:35,154 - INFO - Epoch 22/100 - Train Loss: 0.1754 - Val Acc: 0.8261
2026-04-05 06:13:35,431 - INFO - Epoch 23/100 - Train Loss: 0.1728 - Val Acc: 0.8261
2026-04-05 06:13:35,717 - INFO - Epoch 24/100 - Train Loss: 0.1736 - Val Acc: 0.8261
2026-04-05 06:13:36,012 - INFO - Epoch 25/100 - Train Loss: 0.1723 - Val Acc: 0.8261
2026-04-05 06:13:36,304 - INFO - Epoch 26/100 - Train Loss: 0.1712 - Val Acc: 0.8116
2026-04-05 06:13:36,596 - INFO - Epoch 27/100 - Train Loss: 0.1690 - Val Acc: 0.7971
2026-04-05 06:13:36,882 - INFO - Epoch 28/100 - Train Loss: 0.1673 - Val Acc: 0.7971
2026-04-05 06:13:37,171 - INFO - Epoch 29/100 - Train Loss: 0.1699 - Val Acc: 0.8116
2026-04-05 06:13:37,448 - INFO - Epoch 30/100 - Train Loss: 0.1674 - Val Acc: 0.7971
2026-04-05 06:13:37,720 - INFO - Epoch 31/100 - Train Loss: 0.1636 - Val Acc: 0.7971
2026-04-05 06:13:38,006 - INFO - Epoch 32/100 - Train Loss: 0.1644 - Val Acc: 0.7971
2026-04-05 06:13:38,284 - INFO - Epoch 33/100 - Train Loss: 0.1636 - Val Acc: 0.8116
2026-04-05 06:13:38,560 - INFO - Epoch 34/100 - Train Loss: 0.1649 - Val Acc: 0.8116
2026-04-05 06:13:38,839 - INFO - Epoch 35/100 - Train Loss: 0.1628 - Val Acc: 0.8116
2026-04-05 06:13:39,118 - INFO - Epoch 36/100 - Train Loss: 0.1610 - Val Acc: 0.8261
2026-04-05 06:13:39,393 - INFO - Epoch 37/100 - Train Loss: 0.1607 - Val Acc: 0.8261
2026-04-05 06:13:39,700 - INFO - Epoch 38/100 - Train Loss: 0.1617 - Val Acc: 0.8261
2026-04-05 06:13:39,979 - INFO - Epoch 39/100 - Train Loss: 0.1601 - Val Acc: 0.8261
2026-04-05 06:13:40,260 - INFO - Epoch 40/100 - Train Loss: 0.1562 - Val Acc: 0.8261
2026-04-05 06:13:40,537 - INFO - Epoch 41/100 - Train Loss: 0.1579 - Val Acc: 0.8116
2026-04-05 06:13:40,819 - INFO - Epoch 42/100 - Train Loss: 0.1571 - Val Acc: 0.8116
2026-04-05 06:13:41,096 - INFO - Epoch 43/100 - Train Loss: 0.1553 - Val Acc: 0.8116
2026-04-05 06:13:41,383 - INFO - Epoch 44/100 - Train Loss: 0.1578 - Val Acc: 0.8116
2026-04-05 06:13:41,659 - INFO - Epoch 45/100 - Train Loss: 0.1555 - Val Acc: 0.8116
2026-04-05 06:13:41,942 - INFO - Epoch 46/100 - Train Loss: 0.1544 - Val Acc: 0.8116
2026-04-05 06:13:42,219 - INFO - Epoch 47/100 - Train Loss: 0.1538 - Val Acc: 0.8116
2026-04-05 06:13:42,504 - INFO - Epoch 48/100 - Train Loss: 0.1544 - Val Acc: 0.8116
2026-04-05 06:13:42,779 - INFO - Epoch 49/100 - Train Loss: 0.1540 - Val Acc: 0.8261
2026-04-05 06:13:43,059 - INFO - Epoch 50/100 - Train Loss: 0.1533 - Val Acc: 0.8261
2026-04-05 06:13:43,337 - INFO - Epoch 51/100 - Train Loss: 0.1524 - Val Acc: 0.8261
2026-04-05 06:13:43,615 - INFO - Epoch 52/100 - Train Loss: 0.1489 - Val Acc: 0.8261
2026-04-05 06:13:43,907 - INFO - Epoch 53/100 - Train Loss: 0.1505 - Val Acc: 0.8116
2026-04-05 06:13:44,194 - INFO - Epoch 54/100 - Train Loss: 0.1480 - Val Acc: 0.8116
2026-04-05 06:13:44,499 - INFO - Epoch 55/100 - Train Loss: 0.1491 - Val Acc: 0.8116
2026-04-05 06:13:44,804 - INFO - Epoch 56/100 - Train Loss: 0.1460 - Val Acc: 0.8116
2026-04-05 06:13:45,077 - INFO - Epoch 57/100 - Train Loss: 0.1482 - Val Acc: 0.8116
2026-04-05 06:13:45,354 - INFO - Epoch 58/100 - Train Loss: 0.1481 - Val Acc: 0.8116
2026-04-05 06:13:45,634 - INFO - Epoch 59/100 - Train Loss: 0.1458 - Val Acc: 0.8116
2026-04-05 06:13:45,923 - INFO - Epoch 60/100 - Train Loss: 0.1465 - Val Acc: 0.8116
2026-04-05 06:13:46,219 - INFO - Epoch 61/100 - Train Loss: 0.1442 - Val Acc: 0.8116
2026-04-05 06:13:46,505 - INFO - Epoch 62/100 - Train Loss: 0.1449 - Val Acc: 0.7971
2026-04-05 06:13:46,793 - INFO - Epoch 63/100 - Train Loss: 0.1452 - Val Acc: 0.8116
2026-04-05 06:13:47,074 - INFO - Epoch 64/100 - Train Loss: 0.1409 - Val Acc: 0.8116
2026-04-05 06:13:47,348 - INFO - Epoch 65/100 - Train Loss: 0.1453 - Val Acc: 0.8116
2026-04-05 06:13:47,635 - INFO - Epoch 66/100 - Train Loss: 0.1428 - Val Acc: 0.8116
2026-04-05 06:13:47,911 - INFO - Epoch 67/100 - Train Loss: 0.1403 - Val Acc: 0.8116
2026-04-05 06:13:48,186 - INFO - Epoch 68/100 - Train Loss: 0.1389 - Val Acc: 0.8116
2026-04-05 06:13:48,472 - INFO - Epoch 69/100 - Train Loss: 0.1383 - Val Acc: 0.8116
2026-04-05 06:13:48,753 - INFO - Epoch 70/100 - Train Loss: 0.1376 - Val Acc: 0.8116
2026-04-05 06:13:49,040 - INFO - Epoch 71/100 - Train Loss: 0.1373 - Val Acc: 0.8261
2026-04-05 06:13:49,309 - INFO - Epoch 72/100 - Train Loss: 0.1370 - Val Acc: 0.8261
2026-04-05 06:13:49,604 - INFO - Epoch 73/100 - Train Loss: 0.1342 - Val Acc: 0.8261
2026-04-05 06:13:49,889 - INFO - Epoch 74/100 - Train Loss: 0.1369 - Val Acc: 0.8116
2026-04-05 06:13:50,170 - INFO - Epoch 75/100 - Train Loss: 0.1356 - Val Acc: 0.8116
2026-04-05 06:13:50,451 - INFO - Epoch 76/100 - Train Loss: 0.1371 - Val Acc: 0.8116
2026-04-05 06:13:50,745 - INFO - Epoch 77/100 - Train Loss: 0.1312 - Val Acc: 0.8261
2026-04-05 06:13:51,029 - INFO - Epoch 78/100 - Train Loss: 0.1338 - Val Acc: 0.8261
2026-04-05 06:13:51,311 - INFO - Epoch 79/100 - Train Loss: 0.1352 - Val Acc: 0.8261
2026-04-05 06:13:51,587 - INFO - Epoch 80/100 - Train Loss: 0.1351 - Val Acc: 0.8261
2026-04-05 06:13:51,879 - INFO - Epoch 81/100 - Train Loss: 0.1308 - Val Acc: 0.8261
2026-04-05 06:13:52,158 - INFO - Epoch 82/100 - Train Loss: 0.1293 - Val Acc: 0.8261
2026-04-05 06:13:52,444 - INFO - Epoch 83/100 - Train Loss: 0.1332 - Val Acc: 0.8261
2026-04-05 06:13:52,721 - INFO - Epoch 84/100 - Train Loss: 0.1345 - Val Acc: 0.8116
2026-04-05 06:13:52,999 - INFO - Epoch 85/100 - Train Loss: 0.1297 - Val Acc: 0.8261
2026-04-05 06:13:53,277 - INFO - Epoch 86/100 - Train Loss: 0.1311 - Val Acc: 0.8116
2026-04-05 06:13:53,550 - INFO - Epoch 87/100 - Train Loss: 0.1304 - Val Acc: 0.8116
2026-04-05 06:13:53,826 - INFO - Epoch 88/100 - Train Loss: 0.1311 - Val Acc: 0.8261
2026-04-05 06:13:54,103 - INFO - Epoch 89/100 - Train Loss: 0.1264 - Val Acc: 0.8116
2026-04-05 06:13:54,413 - INFO - Epoch 90/100 - Train Loss: 0.1300 - Val Acc: 0.8116
2026-04-05 06:13:54,707 - INFO - Epoch 91/100 - Train Loss: 0.1304 - Val Acc: 0.8116
2026-04-05 06:13:54,992 - INFO - Epoch 92/100 - Train Loss: 0.1268 - Val Acc: 0.8261
2026-04-05 06:13:55,281 - INFO - Epoch 93/100 - Train Loss: 0.1291 - Val Acc: 0.8261
2026-04-05 06:13:55,575 - INFO - Epoch 94/100 - Train Loss: 0.1255 - Val Acc: 0.8261
2026-04-05 06:13:55,857 - INFO - Epoch 95/100 - Train Loss: 0.1258 - Val Acc: 0.8261
2026-04-05 06:13:56,137 - INFO - Epoch 96/100 - Train Loss: 0.1247 - Val Acc: 0.8261
2026-04-05 06:13:56,427 - INFO - Epoch 97/100 - Train Loss: 0.1241 - Val Acc: 0.7971
2026-04-05 06:13:56,712 - INFO - Epoch 98/100 - Train Loss: 0.1261 - Val Acc: 0.7971
2026-04-05 06:13:56,997 - INFO - Epoch 99/100 - Train Loss: 0.1238 - Val Acc: 0.8116
2026-04-05 06:13:57,285 - INFO - Epoch 100/100 - Train Loss: 0.1270 - Val Acc: 0.7971
2026-04-05 06:13:57,668 - INFO - Fold 9 logically complete. Tensor memory bounds cleared cleanly.
2026-04-05 06:13:57,672 - INFO - Original class distribution: [345 276]
2026-04-05 06:13:57,673 - INFO - Training device bound securely to: cuda
2026-04-05 06:13:57,702 - INFO - After SMOTE-ENN deployment: [345 296]

Fold 10:   0%|          | 0/100 [00:00<?, ?it/s]

2026-04-05 06:13:58,005 - INFO - Epoch 1/100 - Train Loss: 0.6497 - Val Acc: 0.8986
2026-04-05 06:13:58,279 - INFO - Epoch 2/100 - Train Loss: 0.5572 - Val Acc: 0.8986
2026-04-05 06:13:58,555 - INFO - Epoch 3/100 - Train Loss: 0.4732 - Val Acc: 0.8986
2026-04-05 06:13:58,840 - INFO - Epoch 4/100 - Train Loss: 0.4041 - Val Acc: 0.8986
2026-04-05 06:13:59,116 - INFO - Epoch 5/100 - Train Loss: 0.3480 - Val Acc: 0.8986
2026-04-05 06:13:59,398 - INFO - Epoch 6/100 - Train Loss: 0.3088 - Val Acc: 0.8986
2026-04-05 06:13:59,668 - INFO - Epoch 7/100 - Train Loss: 0.2781 - Val Acc: 0.8986
2026-04-05 06:13:59,940 - INFO - Epoch 8/100 - Train Loss: 0.2598 - Val Acc: 0.9130
2026-04-05 06:14:00,216 - INFO - Epoch 9/100 - Train Loss: 0.2468 - Val Acc: 0.9130
2026-04-05 06:14:00,494 - INFO - Epoch 10/100 - Train Loss: 0.2406 - Val Acc: 0.9130
2026-04-05 06:14:00,778 - INFO - Epoch 11/100 - Train Loss: 0.2378 - Val Acc: 0.9130
2026-04-05 06:14:01,067 - INFO - Epoch 12/100 - Train Loss: 0.2313 - Val Acc: 0.9130
2026-04-05 06:14:01,358 - INFO - Epoch 13/100 - Train Loss: 0.2269 - Val Acc: 0.9130
2026-04-05 06:14:01,629 - INFO - Epoch 14/100 - Train Loss: 0.2186 - Val Acc: 0.9130
2026-04-05 06:14:01,921 - INFO - Epoch 15/100 - Train Loss: 0.2165 - Val Acc: 0.9130
2026-04-05 06:14:02,205 - INFO - Epoch 16/100 - Train Loss: 0.2110 - Val Acc: 0.9275
2026-04-05 06:14:02,499 - INFO - Epoch 17/100 - Train Loss: 0.2103 - Val Acc: 0.9275
2026-04-05 06:14:02,779 - INFO - Epoch 18/100 - Train Loss: 0.2037 - Val Acc: 0.9275
2026-04-05 06:14:03,067 - INFO - Epoch 19/100 - Train Loss: 0.2002 - Val Acc: 0.9275
2026-04-05 06:14:03,346 - INFO - Epoch 20/100 - Train Loss: 0.2003 - Val Acc: 0.9275
2026-04-05 06:14:03,621 - INFO - Epoch 21/100 - Train Loss: 0.1990 - Val Acc: 0.9275
2026-04-05 06:14:03,909 - INFO - Epoch 22/100 - Train Loss: 0.1953 - Val Acc: 0.9275
2026-04-05 06:14:04,195 - INFO - Epoch 23/100 - Train Loss: 0.1948 - Val Acc: 0.9275
2026-04-05 06:14:04,486 - INFO - Epoch 24/100 - Train Loss: 0.1968 - Val Acc: 0.9275
2026-04-05 06:14:04,790 - INFO - Epoch 25/100 - Train Loss: 0.1950 - Val Acc: 0.9420
2026-04-05 06:14:05,079 - INFO - Epoch 26/100 - Train Loss: 0.1913 - Val Acc: 0.9420
2026-04-05 06:14:05,350 - INFO - Epoch 27/100 - Train Loss: 0.1903 - Val Acc: 0.9275
2026-04-05 06:14:05,622 - INFO - Epoch 28/100 - Train Loss: 0.1892 - Val Acc: 0.9275
2026-04-05 06:14:05,888 - INFO - Epoch 29/100 - Train Loss: 0.1912 - Val Acc: 0.9275
2026-04-05 06:14:06,172 - INFO - Epoch 30/100 - Train Loss: 0.1913 - Val Acc: 0.9275
2026-04-05 06:14:06,471 - INFO - Epoch 31/100 - Train Loss: 0.1903 - Val Acc: 0.9275
2026-04-05 06:14:06,755 - INFO - Epoch 32/100 - Train Loss: 0.1879 - Val Acc: 0.9275
2026-04-05 06:14:07,035 - INFO - Epoch 33/100 - Train Loss: 0.1887 - Val Acc: 0.9420
2026-04-05 06:14:07,306 - INFO - Epoch 34/100 - Train Loss: 0.1882 - Val Acc: 0.9420
2026-04-05 06:14:07,582 - INFO - Epoch 35/100 - Train Loss: 0.1850 - Val Acc: 0.9420
2026-04-05 06:14:07,850 - INFO - Epoch 36/100 - Train Loss: 0.1863 - Val Acc: 0.9420
2026-04-05 06:14:08,139 - INFO - Epoch 37/100 - Train Loss: 0.1866 - Val Acc: 0.9420
2026-04-05 06:14:08,408 - INFO - Epoch 38/100 - Train Loss: 0.1827 - Val Acc: 0.9420
2026-04-05 06:14:08,687 - INFO - Epoch 39/100 - Train Loss: 0.1805 - Val Acc: 0.9420
2026-04-05 06:14:08,958 - INFO - Epoch 40/100 - Train Loss: 0.1807 - Val Acc: 0.9420
2026-04-05 06:14:09,237 - INFO - Epoch 41/100 - Train Loss: 0.1818 - Val Acc: 0.9420
2026-04-05 06:14:09,518 - INFO - Epoch 42/100 - Train Loss: 0.1804 - Val Acc: 0.9420
2026-04-05 06:14:09,796 - INFO - Epoch 43/100 - Train Loss: 0.1820 - Val Acc: 0.9420
2026-04-05 06:14:10,069 - INFO - Epoch 44/100 - Train Loss: 0.1809 - Val Acc: 0.9420
2026-04-05 06:14:10,352 - INFO - Epoch 45/100 - Train Loss: 0.1798 - Val Acc: 0.9420
2026-04-05 06:14:10,637 - INFO - Epoch 46/100 - Train Loss: 0.1794 - Val Acc: 0.9420
2026-04-05 06:14:10,916 - INFO - Epoch 47/100 - Train Loss: 0.1761 - Val Acc: 0.9420
2026-04-05 06:14:11,190 - INFO - Epoch 48/100 - Train Loss: 0.1758 - Val Acc: 0.9420
2026-04-05 06:14:11,474 - INFO - Epoch 49/100 - Train Loss: 0.1809 - Val Acc: 0.9275
2026-04-05 06:14:11,750 - INFO - Epoch 50/100 - Train Loss: 0.1796 - Val Acc: 0.9420
2026-04-05 06:14:12,027 - INFO - Epoch 51/100 - Train Loss: 0.1790 - Val Acc: 0.9420
2026-04-05 06:14:12,303 - INFO - Epoch 52/100 - Train Loss: 0.1753 - Val Acc: 0.9275
2026-04-05 06:14:12,588 - INFO - Epoch 53/100 - Train Loss: 0.1743 - Val Acc: 0.9275
2026-04-05 06:14:12,858 - INFO - Epoch 54/100 - Train Loss: 0.1711 - Val Acc: 0.9275
2026-04-05 06:14:13,137 - INFO - Epoch 55/100 - Train Loss: 0.1712 - Val Acc: 0.9420
2026-04-05 06:14:13,413 - INFO - Epoch 56/100 - Train Loss: 0.1726 - Val Acc: 0.9565
2026-04-05 06:14:13,680 - INFO - Epoch 57/100 - Train Loss: 0.1813 - Val Acc: 0.9420
2026-04-05 06:14:13,959 - INFO - Epoch 58/100 - Train Loss: 0.1851 - Val Acc: 0.9420
2026-04-05 06:14:14,234 - INFO - Epoch 59/100 - Train Loss: 0.1808 - Val Acc: 0.9420
2026-04-05 06:14:14,519 - INFO - Epoch 60/100 - Train Loss: 0.1812 - Val Acc: 0.9420
2026-04-05 06:14:14,839 - INFO - Epoch 61/100 - Train Loss: 0.1776 - Val Acc: 0.9420
2026-04-05 06:14:15,117 - INFO - Epoch 62/100 - Train Loss: 0.1735 - Val Acc: 0.9420
2026-04-05 06:14:15,397 - INFO - Epoch 63/100 - Train Loss: 0.1707 - Val Acc: 0.9420
2026-04-05 06:14:15,673 - INFO - Epoch 64/100 - Train Loss: 0.1730 - Val Acc: 0.9420
2026-04-05 06:14:15,954 - INFO - Epoch 65/100 - Train Loss: 0.1696 - Val Acc: 0.9710
2026-04-05 06:14:16,250 - INFO - Epoch 66/100 - Train Loss: 0.1679 - Val Acc: 0.9710
2026-04-05 06:14:16,537 - INFO - Epoch 67/100 - Train Loss: 0.1661 - Val Acc: 0.9710
2026-04-05 06:14:16,832 - INFO - Epoch 68/100 - Train Loss: 0.1690 - Val Acc: 0.9710
2026-04-05 06:14:17,117 - INFO - Epoch 69/100 - Train Loss: 0.1664 - Val Acc: 0.9710
2026-04-05 06:14:17,393 - INFO - Epoch 70/100 - Train Loss: 0.1660 - Val Acc: 0.9565
2026-04-05 06:14:17,668 - INFO - Epoch 71/100 - Train Loss: 0.1636 - Val Acc: 0.9565
2026-04-05 06:14:17,943 - INFO - Epoch 72/100 - Train Loss: 0.1639 - Val Acc: 0.9565
2026-04-05 06:14:18,219 - INFO - Epoch 73/100 - Train Loss: 0.1631 - Val Acc: 0.9275
2026-04-05 06:14:18,494 - INFO - Epoch 74/100 - Train Loss: 0.1653 - Val Acc: 0.9275
2026-04-05 06:14:18,777 - INFO - Epoch 75/100 - Train Loss: 0.1637 - Val Acc: 0.9275
2026-04-05 06:14:19,054 - INFO - Epoch 76/100 - Train Loss: 0.1605 - Val Acc: 0.9420
2026-04-05 06:14:19,335 - INFO - Epoch 77/100 - Train Loss: 0.1634 - Val Acc: 0.9275
2026-04-05 06:14:19,599 - INFO - Epoch 78/100 - Train Loss: 0.1601 - Val Acc: 0.9275
2026-04-05 06:14:19,875 - INFO - Epoch 79/100 - Train Loss: 0.1590 - Val Acc: 0.9275
2026-04-05 06:14:20,150 - INFO - Epoch 80/100 - Train Loss: 0.1606 - Val Acc: 0.9420
2026-04-05 06:14:20,422 - INFO - Epoch 81/100 - Train Loss: 0.1606 - Val Acc: 0.9420
2026-04-05 06:14:20,699 - INFO - Epoch 82/100 - Train Loss: 0.1581 - Val Acc: 0.9275
2026-04-05 06:14:20,991 - INFO - Epoch 83/100 - Train Loss: 0.1568 - Val Acc: 0.9275
2026-04-05 06:14:21,270 - INFO - Epoch 84/100 - Train Loss: 0.1563 - Val Acc: 0.9275
2026-04-05 06:14:21,562 - INFO - Epoch 85/100 - Train Loss: 0.1586 - Val Acc: 0.9275
2026-04-05 06:14:21,847 - INFO - Epoch 86/100 - Train Loss: 0.1575 - Val Acc: 0.9420
2026-04-05 06:14:22,130 - INFO - Epoch 87/100 - Train Loss: 0.1586 - Val Acc: 0.9565
2026-04-05 06:14:22,414 - INFO - Epoch 88/100 - Train Loss: 0.1587 - Val Acc: 0.9565
2026-04-05 06:14:22,703 - INFO - Epoch 89/100 - Train Loss: 0.1544 - Val Acc: 0.9275
2026-04-05 06:14:23,021 - INFO - Epoch 90/100 - Train Loss: 0.1561 - Val Acc: 0.9275
2026-04-05 06:14:23,323 - INFO - Epoch 91/100 - Train Loss: 0.1567 - Val Acc: 0.9275
2026-04-05 06:14:23,618 - INFO - Epoch 92/100 - Train Loss: 0.1545 - Val Acc: 0.9275
2026-04-05 06:14:23,900 - INFO - Epoch 93/100 - Train Loss: 0.1537 - Val Acc: 0.9275
2026-04-05 06:14:24,172 - INFO - Epoch 94/100 - Train Loss: 0.1516 - Val Acc: 0.9420
2026-04-05 06:14:24,465 - INFO - Epoch 95/100 - Train Loss: 0.1508 - Val Acc: 0.9565
2026-04-05 06:14:24,760 - INFO - Epoch 96/100 - Train Loss: 0.1545 - Val Acc: 0.9565
2026-04-05 06:14:25,037 - INFO - Epoch 97/100 - Train Loss: 0.1524 - Val Acc: 0.9565
2026-04-05 06:14:25,309 - INFO - Epoch 98/100 - Train Loss: 0.1530 - Val Acc: 0.9565
2026-04-05 06:14:25,582 - INFO - Epoch 99/100 - Train Loss: 0.1521 - Val Acc: 0.9565
2026-04-05 06:14:25,857 - INFO - Epoch 100/100 - Train Loss: 0.1491 - Val Acc: 0.9565
2026-04-05 06:14:26,223 - INFO - Fold 10 logically complete. Tensor memory bounds cleared cleanly.
2026-04-05 06:14:26,240 - INFO - ✓ Completed GRU_smoteenn -> Acc: 0.8812

AUSTRALIAN DATASET - FINAL RESULTS SUMMARY

,Experiment,Mean_Accuracy,Std_Accuracy,Mean_Sensitivity,Std_Sensitivity,Mean_Specificity,Std_Specificity
0,MLP_baseline,0.892754,0.041602,0.873871,0.093747,0.908839,0.057389
1,MLP_smoteenn,0.881159,0.050952,0.818817,0.113323,0.932186,0.028979
2,LSTM_baseline,0.894203,0.038372,0.867419,0.093875,0.916734,0.035737
3,LSTM_smoteenn,0.881159,0.052174,0.818925,0.122233,0.932389,0.032720
4,GRU_baseline,0.891304,0.038481,0.854624,0.102096,0.921997,0.034006
5,GRU_smoteenn,0.881159,0.057899,0.815591,0.121961,0.934885,0.030972

## ***Reproduced Results vs. Paper Comparison***
***Purpose:*** Generate comprehensive comparison tables structurally showing our reproduced explicit metric sets mapped natively identical against the original paper's definitively reported data tables.

*Paper Citation: Idowu Aruleba and Yanxia Sun, "Enhanced credit risk prediction using deep learning and SMOTE-ENN resampling", Machine Learning with Applications, vol. 21, 2025.*

In [23]:
logger.info("="*80)
logger.info("GENERATING PAPER VS REPRODUCED COMPARISON TABLES")
logger.info("="*80)

german_paper_results = {
    'MLP_before': {'accuracy': 0.704, 'sensitivity': 0.773, 'specificity': 0.310},
    'MLP_after': {'accuracy': 0.824, 'sensitivity': 0.830, 'specificity': 0.810},
    'LSTM_before': {'accuracy': 0.730, 'sensitivity': 0.770, 'specificity': 0.394},
    'LSTM_after': {'accuracy': 0.819, 'sensitivity': 0.859, 'specificity': 0.729},
    'GRU_before': {'accuracy': 0.749, 'sensitivity': 0.895, 'specificity': 0.431},
    'GRU_after': {'accuracy': 0.899, 'sensitivity': 0.931, 'specificity': 0.852}
}

german_comparison_rows = []
for model in ['MLP', 'LSTM', 'GRU']:
    for condition in ['baseline', 'smoteenn']:
        key = f"{model}_{condition}"
        paper_key = f"{model}_{'before' if condition == 'baseline' else 'after'}"
        
        our_acc, our_sens, our_spec = german_results[key]['mean_accuracy'], german_results[key]['mean_sensitivity'], german_results[key]['mean_specificity']
        paper_acc, paper_sens, paper_spec = german_paper_results[paper_key]['accuracy'], german_paper_results[paper_key]['sensitivity'], german_paper_results[paper_key]['specificity']
        
        for met_name, our_val, p_val in zip(['Accuracy', 'Sensitivity', 'Specificity'], [our_acc, our_sens, our_spec], [paper_acc, paper_sens, paper_spec]):
            diff = our_val - p_val
            german_comparison_rows.append({
                'Model': model, 'Condition': condition.upper(), 'Metric': met_name,
                'Paper': f"{p_val:.3f}", 'Reproduced': f"{our_val:.3f}",
                'Difference': f"{diff:+.3f}", 'Pct_Diff': f"{(diff/p_val*100):+.1f}%"
            })

german_comparison_df = pd.DataFrame(german_comparison_rows)
german_comparison_df.to_csv('results/tables/german_paper_vs_reproduced.csv', index=False)
print("\nGERMAN DATASET: PAPER VS REPRODUCED RESULTS")
display(german_comparison_df)

australian_paper_results = {
    'MLP_before': {'accuracy': 0.810, 'sensitivity': 0.850, 'specificity': 0.781},
    'MLP_after': {'accuracy': 0.850, 'sensitivity': 0.879, 'specificity': 0.830},
    'LSTM_before': {'accuracy': 0.861, 'sensitivity': 0.848, 'specificity': 0.885},
    'LSTM_after': {'accuracy': 0.917, 'sensitivity': 0.897, 'specificity': 0.913},
    'GRU_before': {'accuracy': 0.837, 'sensitivity': 0.829, 'specificity': 0.849},
    'GRU_after': {'accuracy': 0.926, 'sensitivity': 0.911, 'specificity': 0.930}
}

australian_comparison_rows = []
for model in ['MLP', 'LSTM', 'GRU']:
    for condition in ['baseline', 'smoteenn']:
        key = f"{model}_{condition}"
        paper_key = f"{model}_{'before' if condition == 'baseline' else 'after'}"
        
        our_acc, our_sens, our_spec = australian_results[key]['mean_accuracy'], australian_results[key]['mean_sensitivity'], australian_results[key]['mean_specificity']
        paper_acc, paper_sens, paper_spec = australian_paper_results[paper_key]['accuracy'], australian_paper_results[paper_key]['sensitivity'], australian_paper_results[paper_key]['specificity']
        
        for met_name, our_val, p_val in zip(['Accuracy', 'Sensitivity', 'Specificity'], [our_acc, our_sens, our_spec], [paper_acc, paper_sens, paper_spec]):
            diff = our_val - p_val
            australian_comparison_rows.append({
                'Model': model, 'Condition': condition.upper(), 'Metric': met_name,
                'Paper': f"{p_val:.3f}", 'Reproduced': f"{our_val:.3f}",
                'Difference': f"{diff:+.3f}", 'Pct_Diff': f"{(diff/p_val*100):+.1f}%"
            })

australian_comparison_df = pd.DataFrame(australian_comparison_rows)
australian_comparison_df.to_csv('results/tables/australian_paper_vs_reproduced.csv', index=False)
print("\nAUSTRALIAN DATASET: PAPER VS REPRODUCED RESULTS")
display(australian_comparison_df)

print("\nREPRODUCTION FIDELITY ANALYSIS")
ger_diffs = german_comparison_df['Difference'].apply(lambda x: abs(float(x)))
aus_diffs = australian_comparison_df['Difference'].apply(lambda x: abs(float(x)))
print(f"German Abs Mean Diff: {ger_diffs.mean():.4f} | Max Diff: {ger_diffs.max():.4f}")
print(f"Australian Abs Mean Diff: {aus_diffs.mean():.4f} | Max Diff: {aus_diffs.max():.4f}")

2026-04-05 06:14:26,261 - INFO - ================================================================================
2026-04-05 06:14:26,262 - INFO - GENERATING PAPER VS REPRODUCED COMPARISON TABLES
2026-04-05 06:14:26,263 - INFO - ================================================================================

GERMAN DATASET: PAPER VS REPRODUCED RESULTS

   Model Condition       Metric  Paper Reproduced Difference Pct_Diff
0    MLP  BASELINE     Accuracy  0.704      0.884     +0.180   +25.6%
1    MLP  BASELINE  Sensitivity  0.773      0.904     +0.131   +16.9%
2    MLP  BASELINE  Specificity  0.310      0.861     +0.551  +177.8%
3    MLP  SMOTEENN     Accuracy  0.824      0.875     +0.051    +6.2%
4    MLP  SMOTEENN  Sensitivity  0.830      0.841     +0.011    +1.3%
5    MLP  SMOTEENN  Specificity  0.810      0.919     +0.109   +13.5%
6   LSTM  BASELINE     Accuracy  0.730      0.891     +0.161   +22.1%
7   LSTM  BASELINE  Sensitivity  0.770      0.919     +0.149   +19.4%
8   LSTM  BASELINE  Specificity  0.394      0.858     +0.464  +117.7%
9   LSTM  SMOTEENN     Accuracy  0.819      0.880     +0.061    +7.4%
10  LSTM  SMOTEENN  Sensitivity  0.859      0.846     -0.013    -1.5%
11  LSTM  SMOTEENN  Specificity  0.729      0.922     +0.193   +26.5%
12   GRU  BASELINE     Accuracy  0.749      0.894     +0.145   +19.4%
13   GRU  BASELINE  Sensitivity  0.895      0.919     +0.024    +2.7%
14   GRU  BASELINE  Specificity  0.431      0.864     +0.433  +100.5%
15   GRU  SMOTEENN     Accuracy  0.899      0.877     -0.022    -2.5%
16   GRU  SMOTEENN  Sensitivity  0.931      0.846     -0.085    -9.1%
17   GRU  SMOTEENN  Specificity  0.852      0.916     +0.064    +7.5%

AUSTRALIAN DATASET: PAPER VS REPRODUCED RESULTS

   Model Condition       Metric  Paper Reproduced Difference Pct_Diff
0    MLP  BASELINE     Accuracy  0.810      0.893     +0.083   +10.2%
1    MLP  BASELINE  Sensitivity  0.850      0.874     +0.024    +2.8%
2    MLP  BASELINE  Specificity  0.781      0.909     +0.128   +16.4%
3    MLP  SMOTEENN     Accuracy  0.850      0.881     +0.031    +3.7%
4    MLP  SMOTEENN  Sensitivity  0.879      0.819     -0.060    -6.8%
5    MLP  SMOTEENN  Specificity  0.830      0.932     +0.102   +12.3%
6   LSTM  BASELINE     Accuracy  0.861      0.894     +0.033    +3.9%
7   LSTM  BASELINE  Sensitivity  0.848      0.867     +0.019    +2.3%
8   LSTM  BASELINE  Specificity  0.885      0.917     +0.032    +3.6%
9   LSTM  SMOTEENN     Accuracy  0.917      0.881     -0.036    -3.9%
10  LSTM  SMOTEENN  Sensitivity  0.897      0.819     -0.078    -8.7%
11  LSTM  SMOTEENN  Specificity  0.913      0.932     +0.019    +2.1%
12   GRU  BASELINE     Accuracy  0.837      0.891     +0.054    +6.5%
13   GRU  BASELINE  Sensitivity  0.829      0.855     +0.026    +3.1%
14   GRU  BASELINE  Specificity  0.849      0.922     +0.073    +8.6%
15   GRU  SMOTEENN     Accuracy  0.926      0.881     -0.045    -4.8%
16   GRU  SMOTEENN  Sensitivity  0.911      0.816     -0.095   -10.5%
17   GRU  SMOTEENN  Specificity  0.930      0.935     +0.005    +0.5%

REPRODUCTION FIDELITY ANALYSIS
German Abs Mean Diff: 0.1582 | Max Diff: 0.5510
Australian Abs Mean Diff: 0.0524 | Max Diff: 0.1280

## ***Training Dynamics Visualization***
***Purpose:*** Generate comprehensive training and validation curves physically modeling model convergence boundaries iteratively isolating absolute metrics vectors natively across individual states mapping 12 configurations.

In [24]:
def PlotTrainingCurves(results_dict, dataset_name, model_name, condition):
    fig, axes = plt.subplots(2, 2, figsize=(15, 10))
    fig.suptitle(f'{dataset_name.capitalize()} Dataset - {model_name} - {condition.upper()}\nTraining Dynamics (10-Fold CV)', fontsize=16, fontweight='bold')
    
    all_train_losses = [h['train_losses'] for h in results_dict['fold_histories']]
    all_val_losses = [h['val_losses'] for h in results_dict['fold_histories']]
    all_val_accuracies = [h['val_accuracies'] for h in results_dict['fold_histories']]
    all_val_sensitivities = [h['val_sensitivities'] for h in results_dict['fold_histories']]
    all_val_specificities = [h['val_specificities'] for h in results_dict['fold_histories']]
    
    epochs = range(1, len(all_train_losses[0]) + 1)
    
    ax = axes[0, 0]
    for losses in all_train_losses: ax.plot(epochs, losses, alpha=0.3, color='blue', linewidth=0.8)
    ax.plot(epochs, np.mean(all_train_losses, axis=0), color='darkblue', linewidth=2, label='Mean Train Loss')
    ax.set_title('Training Loss')
    ax.legend()
    
    ax = axes[0, 1]
    for losses in all_val_losses: ax.plot(epochs, losses, alpha=0.3, color='red', linewidth=0.8)
    ax.plot(epochs, np.mean(all_val_losses, axis=0), color='darkred', linewidth=2, label='Mean Val Loss')
    ax.set_title('Validation Loss')
    ax.legend()
    
    ax = axes[1, 0]
    for accs in all_val_accuracies: ax.plot(epochs, accs, alpha=0.3, color='green', linewidth=0.8)
    ax.plot(epochs, np.mean(all_val_accuracies, axis=0), color='darkgreen', linewidth=2, label='Mean Val Accuracy')
    ax.set_title('Validation Accuracy')
    ax.set_ylim([0, 1])
    ax.legend()
    
    ax = axes[1, 1]
    ax.plot(epochs, np.mean(all_val_sensitivities, axis=0), color='purple', linewidth=2, label='Mean Sensitivity')
    ax.plot(epochs, np.mean(all_val_specificities, axis=0), color='orange', linewidth=2, label='Mean Specificity')
    ax.set_title('Validation Sensitivity & Specificity')
    ax.set_ylim([0, 1])
    ax.legend()
    
    plt.tight_layout()
    base_save = f'results/plots/{dataset_name}_{model_name}_{condition}_training_curves'
    plt.savefig(f'{base_save}.png', dpi=300, bbox_inches='tight')
    plt.close()

logger.info("Generating plot clusters physically rendering limits across parameters...")
for m_name in ['MLP', 'LSTM', 'GRU']:
    for c_flag in ['baseline', 'smoteenn']:
        PlotTrainingCurves(german_results[f"{m_name}_{c_flag}"], 'german', m_name, c_flag)
        PlotTrainingCurves(australian_results[f"{m_name}_{c_flag}"], 'australian', m_name, c_flag)
logger.info("Plot artifacts rendered explicitly down to vector outputs successfully.")

2026-04-05 06:14:26,297 - INFO - Generating plot clusters physically rendering limits across parameters...
2026-04-05 06:14:43,959 - INFO - ✓ Plot artifacts rendered explicitly down to vector outputs successfully.

## ***Robust SHAP Global Implementations***
***Robust Configuration Protocols:*** Restricting the overall unrolled dimensions securely across mathematically stratified samples natively enforcing bounds guaranteeing $N \ge 20$ elements prior to dispatch.

In [25]:
def GenerateShapPlots(domain_target, best_model_pkg):
    logger.info(f"Initializing SHAP analysis for {domain_target} dataset...")
    neural_inst, _, _ = GetModelAndOptimizer(best_model_pkg['model_name'], best_model_pkg['input_dim'])
    
    state_mapping = best_model_pkg['state']
    unrolled_states = {}
    for local_k, local_v in state_mapping.items():
        stripped_key = local_k[7:] if local_k.startswith('module.') else local_k
        unrolled_states[stripped_key] = local_v
    
    if isinstance(neural_inst, nn.DataParallel):
        neural_inst.module.load_state_dict(unrolled_states)
    else:
        neural_inst.load_state_dict(unrolled_states)
    
    neural_inst.eval()
    neural_inst.to(device)
    
    x_test_subset = best_model_pkg['x_val']
    total_samples = x_test_subset.shape[0]
    
    if total_samples < 20:
        logger.warning(f"Insufficient samples ({total_samples}) for SHAP. Skipping.")
        return
        
    bg_size = min(100, total_samples // 2)
    test_size = min(50, total_samples - bg_size)
    
    np.random.seed(42)
    all_indices = np.arange(total_samples)
    np.random.shuffle(all_indices)
    
    bg_tensor = torch.tensor(x_test_subset[all_indices[:bg_size]], dtype=torch.float32).to(device)
    test_tensor = torch.tensor(x_test_subset[all_indices[bg_size:bg_size + test_size]], dtype=torch.float32).to(device)
    
    assert bg_tensor.numel() > 0, f"Background tensor is empty! Shape: {bg_tensor.shape}"
    assert test_tensor.numel() > 0, f"Test tensor is empty! Shape: {test_tensor.shape}"
    
    try:
        def model_predict(x):
            with torch.no_grad():
                if best_model_pkg['model_name'] in ['LSTM', 'GRU']:
                    output = neural_inst(x.unsqueeze(1))
                else:
                    output = neural_inst(x)
                return torch.sigmoid(output).cpu().numpy()
                
        explainer = shap.DeepExplainer(neural_inst, bg_tensor)
        shap_values = explainer.shap_values(test_tensor)
        shap_values_to_plot = shap_values[0] if isinstance(shap_values, list) else shap_values
        
        plt.figure(figsize=(12, 8))
        shap.summary_plot(shap_values_to_plot, test_tensor.cpu().numpy(), show=False, max_display=15)
        plt.title(f"SHAP Feature Importance - {domain_target.capitalize()} Dataset\nModel: {best_model_pkg['model_name']}-SMOTE", fontsize=14, fontweight='bold')
        plt.tight_layout()
        
        save_path = f'results/shap/{domain_target}_{best_model_pkg["model_name"]}_shap_summary'
        plt.savefig(f'{save_path}.png', dpi=300, bbox_inches='tight')
        plt.close()
        
        feature_names = [f"Feature_{i}" for i in range(shap_values_to_plot.shape[1])]
        pd.DataFrame(shap_values_to_plot, columns=feature_names).to_csv(f'{save_path}_values.csv', index=False)
        logger.info(f"✓ SHAP matrices cleanly exported successfully out over `{save_path}.png`")
        
    except Exception as e:
        logger.error(f"SHAP calculation mechanically blocked: {str(e)}. Bypassing visual arrays.")

GenerateShapPlots('german', best_german_shap_pkg)
GenerateShapPlots('australian', best_australian_shap_pkg)

2026-04-05 06:14:43,973 - INFO - Initializing SHAP analysis for german dataset...
2026-04-05 06:14:44,307 - ERROR - SHAP calculation mechanically blocked: cudnn RNN backward can only be called in training mode. Bypassing visual arrays.
2026-04-05 06:14:44,309 - INFO - Initializing SHAP analysis for australian dataset...
2026-04-05 06:14:44,325 - ERROR - SHAP calculation mechanically blocked: cudnn RNN backward can only be called in training mode. Bypassing visual arrays.

## ***Reproducibility Disconnection & Experimental Findings Audit***

***Quantified Discrepancy Analysis***
| Metric | Dataset | Model | Possible Causes of Deviance Arrays |
|--------|---------|-------|-----------------|
| Accuracy | German | GRU-SE | Random seeds severely effect boundaries across $N=1000$ matrices natively. |
| Sensitivity | Australian | LSTM | Categorical mappings resolving pure modes differ from author configurations strictly. |

1. ***Australian Dataset Mismatch:*** The core paper contradicts official documentation on categorical features natively mapping indices [0, 3, 4, 5, 8, 9, 11] correctly.
2. ***Tabular vs Temporal Sequence Bounds:*** GRU parameters explicitly wrap dimension vectors directly targeting $t=1$.
3. ***CNN/GNN Framework Assumptions Removed***: CNNs construct strictly over spatial bounds mathematically impossible across non-mapped flat lines. GNN variants execute against unknown defined node neighbors absent directly within standard methodology deployments. Attempting structural generations forces arbitrary unscientific parameters.

## ***Report Generation: Data Summary***
***Purpose:*** Output summary JSON dictionaries explicitly configuring parameters formally required heavily for your subsequent 10 Page deployment limits!

In [26]:
ger_b = [german_results[f'{m}_baseline']['mean_accuracy'] for m in MODELS_TO_TEST]
ger_s = [german_results[f'{m}_smoteenn']['mean_accuracy'] for m in MODELS_TO_TEST]
aus_b = [australian_results[f'{m}_baseline']['mean_accuracy'] for m in MODELS_TO_TEST]
aus_s = [australian_results[f'{m}_smoteenn']['mean_accuracy'] for m in MODELS_TO_TEST]

report_summary = {
    'german_baseline_mean': np.mean(ger_b),
    'german_smote_mean': np.mean(ger_s),
    'german_improvement': np.mean(ger_s) - np.mean(ger_b),
    'australian_baseline_mean': np.mean(aus_b),
    'australian_smote_mean': np.mean(aus_s),
    'australian_improvement': np.mean(aus_s) - np.mean(aus_b)
}

with open('results/report_summary.json', 'w') as f:
    json.dump(report_summary, f, indent=4)
logger.info("✓ Report boundaries natively dumped into root /results.")

2026-04-05 06:14:44,334 - INFO - ✓ Report boundaries natively dumped into root /results.

## ***Pre-Submission Verification Routine Block***
***Verifies physical files accurately deposited correctly over entire target sequences mapping checks explicitly ensuring complete deliverables execution.***

In [27]:
print("="*80)
print("PRE-SUBMISSION VERIFICATION CHECKLIST")
print("="*80)

checks = {'experiments_complete': True, 'comparison_tables': False, 'training_curves': False, 'shap_plots': False, 'logs_generated': False, 'csvs_exported': False}

checks['comparison_tables'] = all(os.path.exists(p) for p in ['results/tables/german_paper_vs_reproduced.csv', 'results/tables/australian_paper_vs_reproduced.csv'])

plot_dir = Path('results/plots')
if plot_dir.exists():
    checks['training_curves'] = len(list(plot_dir.glob('*training_curves.png'))) >= 12

shap_dir = Path('results/shap')
if shap_dir.exists():
    checks['shap_plots'] = len(list(shap_dir.glob('*shap_summary.png'))) >= 2

log_dir = Path('results/logs')
if log_dir.exists():
    checks['logs_generated'] = len(list(log_dir.glob('*.log'))) > 0

metrics_dir = Path('results/metrics')
if metrics_dir.exists():
    checks['csvs_exported'] = len(list(metrics_dir.glob('*.csv'))) >= 2

checks['experiments_complete'] = (german_results is not None and australian_results is not None and len(german_results) == 6 and len(australian_results) == 6)

for check_name, status in checks.items():
    print(f"{'✓' if status else '❌'} {check_name.replace('_', ' ').title()}: {'PASS' if status else 'FAIL'}")

if all(checks.values()): print("\n✓✓✓ ALL CHECKS PASSED - READY FOR KAGGLE/SUBMISSION ✓✓✓")
else: print("\nSOME CHECKS FAILED - PLEASE REVIEW")

print("\nSUBMISSION PACKAGE COUNTS:")
print(f"  ├── logs/ ({len(list(Path('results/logs').glob('*')))} files)")
print(f"  ├── metrics/ ({len(list(Path('results/metrics').glob('*')))} files)")
print(f"  ├── histories/ ({len(list(Path('results/histories').glob('*')))} files)")
print(f"  ├── tables/ ({len(list(Path('results/tables').glob('*')))} files)")
print(f"  ├── plots/ ({len(list(Path('results/plots').glob('*')))} files)")
print(f"  └── shap/ ({len(list(Path('results/shap').glob('*')))} files)")

================================================================================
PRE-SUBMISSION VERIFICATION CHECKLIST
================================================================================
✓ Experiments Complete: PASS
✓ Comparison Tables: PASS
✓ Training Curves: PASS
❌ Shap Plots: FAIL
✓ Logs Generated: PASS
✓ Csvs Exported: PASS

SOME CHECKS FAILED - PLEASE REVIEW

SUBMISSION PACKAGE COUNTS:
  ├── logs/ (122 files)
  ├── metrics/ (2 files)
  ├── histories/ (12 files)
  ├── tables/ (2 files)
  ├── plots/ (12 files)
  └── shap/ (0 files)

In [28]:
shutil.make_archive('/kaggle/working/output', 'zip', '/kaggle/working')

'/kaggle/working/output.zip'